### PR TITLE
tools/openocd: check return code of flashing command

### PR DESCRIPTION
**Pull request by thomaseichinger**
Up to now, `make flash` will always succeed as the return
value of the flash command is omitted. This can be confusing
when called by statements like `make flash term`.
With this change make will abort if flashing was not successful.

@Kijewski Is `$?` the right value to check?

### CODE REVIEW

**Comment by OlegHahm** [comment]
Doesn't `shutdown` always trigger an exit code?

**Comment by OlegHahm** [comment]
see also #2470.

**Comment by thomaseichinger** [comment]
@OlegHahm Tested this on OS X and (L)ubuntu and behaves as expected with openocd>=0.9.0.
As discussed offline already, I wonder if anybody uses older openocd versions as many of our boards require 0.9.0 or higher.

**Comment by Kijewski** [comment]
ACK, please squash and merge at will.

**Comment by OlegHahm** [comment]
Why not #2472 if we assume users to have OpenOCD>= 0.9.0?

But AFAIK Ubuntu LTS still ships with an older version.

**Comment by Kijewski** [comment]
According to [1] trusty (14.4.) and precise (12.4), which are still supported by Ubuntu, use OpenOCD  0.7.0 and 0.5.0, resp.
Precise is far too outdated, but maybe trusty is still in our scope?

1: https://launchpad.net/ubuntu/+source/openocd

**Comment by OlegHahm** [comment]
If I remember the discussion correctly, we wanted to make sure that the scripts should work on the latest Ubuntu LTS. This would 14.4, but should be replaced in about two months if I'm not mistaken.

**Comment by kYc0o** [comment]
#2897 also address the issue. So do you agree to close this one?

**Comment by kYc0o** [comment]
Closed by #2897

**Pull request closed without merging**
