### PR TITLE
Fix typo in release notes.

### PR DESCRIPTION
**Pull request by iosabi**
### Contribution description

Release notes mentioned QN808x instead of NQ908x.

### CODE REVIEW

**Comment by jia200x** [comment]
Thanks! Makes sense.
Only one thing, could you please rename the commit to match the [RIOT commit convention](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md#commit-conventions)? (e.g `release-notes.txt: fix typo`)

**Review by benpicco — APPROVED** [review]

**Comment by kaspar030** [comment]
@jia200x did this ever got backported?

**Comment by jia200x** [comment]
Nope, I missed that one.
How do we proceed with this? Does it still make sense to backport it?

**Comment by kaspar030** [comment]
IMO, not worth the hassle. Your release, your call. :) I'm fine with just un-labeling.

**Comment by jia200x** [comment]
thinking it twice, it's just a script call and merging it to the 2021.01-branch. For me has almost zero overhead and this kind of fix is not announced as a point release, so it wouldn't interfere the actual release.
I will push it in some minutes :)

**Pull request merged**
