### PR TITLE
make: add remote packages / "package management"

### PR DESCRIPTION
**Pull request by Kijewski**
This PR is meant to replace the current `USE_PKG` system.
Instead with `REMOTE_PKG` a new option added to load decentralized
modules, that could live in some Git project, a local folder or some
similar place.
The PR is inspired by package managers such as pip or npm.

In your project's Makefile you could add a line such as

``` Makefile
REMOTE_PKG += some_module
```

which would clone `https://github.com/RIOT-OS/some_module.git`, checkout
it's `master`. The revision can be overridden, too: `some_module@devel`
or `some_module@1234ab`.
If `https://github.com/RIOT-OS/` is the right place for such modules is
subject for discussions.

The allow further decentralization, you can add another Git remote URL:

``` Makefile
REMOTE_PKG += git+http://repos.example.com/some_module.git
REMOTE_PKG += git+my_account@repos.example.com:some_module.git
```

also with the option to add a revision / branch / tag.

Last but not least you can add local paths:

``` Makefile
REMOTE_PKG += ./../modules/some_module
REMOTE_PKG += /usr/local/shared/riot-modules/some_module
REMOTE_PKG += local+C:/User/Default/Documents/riot-modules/some_module
```

but of course without a revision.

Adding options for Mercurial, Bazaar, SVN, something, would be trivial.

The checked out project needs to contain an executable file
`./riot-pkg`, which prints lines to STDOUT with are included in the
Makefile. The easiest and probably most common `riot-pkg` will contain:

``` sh
#!/bin/sh
echo "DIRS += $(dirname "$(readlink -f "$0")")"
echo "USEMODULE += some_module"
```

More complicated `riot-pkg`s will download remote data, apply patches or
do similar setup tasks.

The advantage of the proposed system over the current `USEPKG` system is
that everybody who's interested could easily share RIOT modules without
us needed to "approve" it. Library authors might find it easier to
contribute to RIOT because sharing the library is done effectively
immediately after they pushed to their module repository.
Furthermore changes to that libraries that are not part of RIOT won't
clutter out changelog. Excessive patch files might not be needed
anymore: just fork the other repo and apply the changes directly.

Disadvantages are that there could be ugly modules that contain the name
RIOT and could damage RIOT's reputation. As everybody is already free to
fork RIOT, I guess this could happen anyway.
More disadvantageous is the lack of a version relationship between
RIOT's "core" and the remote modules. It could be forgotten to check the
modules against the newest changes to RIOT or the module could require
the rolling version of RIOT instead of the last tagged version.
But there the option to specify a version number in the `REMOTE_PKG +=
...` line will come in handy. Could be that you want to use the tagged
RIOT version but a bleeding edge version of the module.

### CODE REVIEW

**Comment by kaspar030** [comment]
Nice!

> More disadvantageous is the lack of a version relationship between
> RIOT's "core" and the remote modules.

A specific pkg version has to be anchored somewhere in the RIOT tree, otherwise it is impossible to rebuild a RIOT commit, if parts of the tree (a pkg) can change externally.

**Comment by authmillenon** [comment]
Without reading much of the blob of text above, but what is the difference to `EXTERNAL_MODULE`?

**Comment by Kijewski** [comment]
Read the blob of text.

**Comment by authmillenon** [comment]
Did, isn't 100% answered.

**Comment by kaspar030** [comment]
> Did, isn't 100% answered.

EXTERNAL_MODULE doesn't checkout anything.

**Comment by authmillenon** [comment]
Yes, but for that we have USEPKG. So why throw these two together?

**Comment by Kijewski** [comment]
@authmillenon, did you read the "The advantage …" paragraph of the PR? :)

The idea of `REMOTE_PKG` is to allow a unified system of external modules. Whether we maintain them or someone else would not matter. My idea was to provide a fast and easy option to contribute new modules for RIOT.

*You don't like our coding style? Does not matter, you are fine. Just host module yourself.
You don't like the LGPL? Does not matter, you are fine. Just host module yourself.*

If there will be nice third party modules, then we can ask them to move them to RIOT-OS' group. Then you can just use `REMOTE_PKG = fancy-library` instead of `REMOTE_PKG += git+https://github.com/example-user/fancy-library.git`.

**Comment by authmillenon** [comment]
Okay… I think what confused me the most was that you called it `REMOTE_PKG`. To me this says basically twice the same. A package is already remote, otherwise it would be a module ;-). External modules are local, but not in the RIOT repository tree.

**Comment by OlegHahm** [comment]
What's the latest here?

**Comment by Kijewski** [comment]
Things were working the last time I checked. The question is if this feature is wanted or not.

**Comment by OlegHahm** [comment]
@kaspar030, @authmillenon, what was your assessment so far?

**Comment by authmillenon** [comment]
I still prefer `USE_PKG`, unless we make `pkg` a (number of) extra repository, [AUR](https://aur.archlinux.org/) style. (Speaking of: wouldn't it be awesome to describe able to just describe packages in a single file and the build system does the rest.... just dreaming :D).

**Comment by miri64** [comment]
What's the latest to my latest statement?

**Comment by kaspar030** [comment]
I think this is a very nice way of dealing with packages.
It is similar to how plugin managers for vim, tmux, ... do it.

IMHO this should be combined with the current package system, e.g., the checked-out folder of a remote package should contain exactly what our current package folders contain.

**Comment by kYc0o** [comment]
Please rebase. As for now it cannot come into this release, so it will be postponed for the next one.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by miri64** [comment]
With new considerations for `pkg` (which will hopefully come to fruition): is this still on the table? @kaspar030 @haukepetersen?

**Comment by miri64** [comment]
Ping?

**Comment by miri64** [comment]
(postponed)

**Comment by miri64** [comment]
A think we moved in a different direction with this and there was no real activity on this PR for over a year. Re-open, if you disagree.

**Pull request closed without merging**
