### PR TITLE
cpu/samd21: fixed GPIO interrupt line mapping

### LINKED ISSUE #5312: samd21/PA27 GPIO not linked to extint 15
According to the datasheet PA27 has for interrupt 15 but samd21/gpio.c:
```
static const int8_t exti_config[2][32] = {
    {-1,  1, -1, -1,  4,  5,  6,  7, -1,  9, 10, 11, 12, 13, 14, 15,
     -1,  1,  2,  3, -1, -1,  6,  7, 12, 13, -1, -1,  8, -1, -1, -1},
    { 0, -1,  2,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
      0,  1, -1, -1, -1, -1,  6,  7, -1, -1, -1, 15,  8, -1, 10, 11},
};
```

This should be:
````
static const int8_t exti_config[2][32] = {
    {-1,  1, -1, -1,  4,  5,  6,  7, -1,  9, 10, 11, 12, 13, 14, 15,
     -1,  1,  2,  3, -1, -1,  6,  7, 12, 13, -1, 15,  8, -1, -1, -1},
    { 0, -1,  2,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
      0,  1, -1, -1, -1, -1,  6,  7, -1, -1, -1, 15,  8, -1, 10, 11},
};
```

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #5312

see datasheet, pages 12-13, sections 5.1 and 5.2

### CODE REVIEW

**Comment by OlegHahm** [comment]
Seems like a duplicate of https://github.com/RIOT-OS/RIOT/pull/5315 or am I mistaken?

**Comment by OlegHahm** [comment]
(At least the purpose is the same, the diff looks different and I haven't checked with the manual for the correct one.)

**Comment by haukepetersen** [comment]
yes, it is, I overlooked #5315, just looked at the issue... I'd like to leave this open, until those fixes are also put into #5315, then we can close this pr...

**Comment by haukepetersen** [comment]
closed in favor of #5315

**Pull request closed without merging**
