### PR TITLE
libschc: initial import as package

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This is part 1 of my takeover of https://github.com/RIOT-OS/RIOT/pull/15040. The PR only contains the import of the `pkg`, not the GNRC module, which will be provided in part 2 as a separate PR.

I mostly updated to both the current version of libSCHC and RIOT, added tests, and adapted the overall style to be more RIOT-like and following our coding conventions.

Testing already revealed some usage problems (or maybe even bugs) with libSCHC. I will have a call with @bartmoons next week to discuss these.

##### TODOs
- [x] ~~Adapt pre-configured rule in `pkg/libschc/include/rules` set more for general RIOT+LoRaWAN use cases~~
- [x] ~~Increase test coverage of tests~~
- [x] Clean-up rule set for test application

### Testing procedure
Run the provided tests with
```
make -C tests/pkg_libschc/ flash test
```
on a platform of your choice.

### Issues/PRs references
Partial alternative to https://github.com/RIOT-OS/RIOT/pull/15040

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Kicking this out of the CI queue until master is fixed (or blacklisted)

**Comment by miri64** [comment]
Rebased to current master and adopted for current libSCHC master (which saw some fixes in the wake of adopting [pylibschc](https://anr-bmbf-pivot.github.io/pylibschc/)

**Comment by miri64** [comment]
This PR is ready for review in my opinion and required for me to seriously proceed on #18700.

**Comment by miri64** [comment]
The libSCHC version may need some more bumps, but I would rather prefer to do that in master, than keeping track of a moving target here.

**Review by jia200x — APPROVED** [review]
ACK.
I tested this branch through #18700 and everything works as expected. Since this is still a (kind of) experimental feature, I think we should get it ASAP and continue improving from there.

Nice work btw!

**Comment by miri64** [comment]
Squashed and removed the temporary commit that restricted Murdock to the test.

**Comment by miri64** [comment]
bors cancel
bors merge

**Comment by miri64** [comment]
bors try-

**Comment by miri64** [comment]
Or for globs sake, bors try- already!

**Pull request merged**
