### PR TITLE
mulle: Initialize NVRAM storage at boot, update boot counter

### PR DESCRIPTION
**Pull request by gebart**
Add initialization of the on-board NVRAM chip, and write a 32 bit boot counter to the NVRAM on each boot.

Also includes a cleanup commit for removing some leftovers from the unification of Cortex-M platform code.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@gebart I think it could take some days until I'll review this PR. Are there any other volunteers?

**Comment by benoit-canet** [comment]
@gebart : Are the schematics of this device availlable ?

**Comment by PeterKietzmann** [comment]
@benoit-canet please comment inside the PR, not in the commit (compare [Developement Procedures](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures) point 5.). And btw: Thanks for reviewing. AFAIK @gebart is on holiday until the next week. I assume you already found the [mulle wiki](https://github.com/eistec/mulle/wiki)?

**Comment by gebart** [comment]
@benoit-canet Thank you for reviewing.

The schematics of the board are not publicly available, but https://github.com/eistec/mulle/wiki/Mulle-board-overview contains a short description of the on-board devices.

**Comment by gebart** [comment]
- check return value of `mulle_nvram_init`
 - rebased

**Comment by benoit-canet** [comment]
#define MULLE_NVRAM_SPI_DEV SPI_2 /**< FRAM SPI bus */

Why not defining it in boards/mulle/include/board.h like for the others SPI devices ?

Also from the wiki:
FM25L04B 4 Kb Serial F-RAM

This smaller memory is more resilient to multiple writes and is used for storing counters and other data that is updated more frequently, in order to save on the flash memory erase cycles.

Connection:

    SPI bus 0, (CPOL=1, CPHA=1) or (CPOL=0, CPHA=0)
    Chip select active low, SPI0_PCS3 (PTD6)

Everything seems to be on the SPI bus 0 from the wiki but the mentioned header says something else.

**Comment by PeterKietzmann** [comment]
@gebart will you adapt @benoit-canet 's proposed changes and rebase?

**Comment by gebart** [comment]
Will update this later, I will be kind of busy the next two weeks or so

**Comment by PeterKietzmann** [comment]
OKay. Just saw that @benoit-canet already ACKed this one (when small change and cleanup is done)

**Comment by PeterKietzmann** [comment]
@gebart could you please squash (at least the latest commit) so we can run Travis.

**Comment by gebart** [comment]
rebased, added a comment about SPI_2 being mapped to hardware SPI0 and immediately squashed. The cleanup of the old files was merged as a separate PR.

**Comment by gebart** [comment]
added `extern "C"` to mulle-nvram.h and immediately squashed.

**Comment by PeterKietzmann** [comment]
I dare to hit the button now. And go

**Pull request merged**
