### PR TITLE
llvm.inc.mk: completely replace detection of GCC includes

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

This completely removes the hardcoded/os specific path setting for includes.
It directly queries gcc include directories.

It takes what was already done by `makefiles/libc/llvm.inc.mk`.

~I also removed the 'GCC_MULTI_DIR' variable as the pointed directory content was already contained in the base directory.
I checked this on arm with `arch-linux`, `ubunt16.04`, the `gcc-arm` ppa, and the arm website toolchain.~
I replaced the `GCC_MULTI_DIR` handling by givining `CFLAGS_CPU` when
searching for include directories.
`CFLAGS` cannot be used as it will crash when `-target $(CPU_ARCH)` is
added.
It currently requires using deferred variables as `CFLAGS_CPU` can be
overwritten later in the build process.

I completely replaced the original code because I found many issues and could not really find a fix:

* TARGET_TRIPLE is undefined for a long time but was still used
* the base code for `CXX` was always putting things in the variable so the backup lines https://github.com/RIOT-OS/RIOT/blob/55b026b3498f3287fb6c6a02df203be9fa9f3419/makefiles/toolchain/llvm.inc.mk#L77-L78
 could never be used
* The backup code before is not adding all sub directories and is not working for c++
* Hardcoded path do not take into account the current gcc version used as one could try using an old version
* For `arm` boards `newlib` is also used so will also query `gcc` for its path.

### Testing procedure

Test compiling the following examples for `BOARD=iotlab-m3` and `TOOLCHAIN=llvm`
with different environments:

`examples/riot_and_cpp/  tests/cpp11_condition_variable  tests/cpp11_mutex  tests/cpp11_thread`

```
make -C examples/riot_and_cpp BOARD=iotlab-m3 TOOLCHAIN=llvm clean all
```

It should compile without issues.

It would be great if you could also give the output of the `GCC_CXX_INCLUDE_DIRS` variable with the different environments:

```
make --no-print-directory -C examples/riot_and_cpp/  TOOLCHAIN=llvm info-debug-variable-GCC_CXX_INCLUDE_DIRS BOARD=iotlab-m3
```
* arch linux
    * [x] iotlab-m3
* ubuntu 16.04
    * [x] iotlab-m3
    * [x] samr21-xpro
* docker arm-gcc ppa
    * [x] iotlab-m3
    * [x] samr21-xpro
* docker new image
    * [x] iotlab-m3
    * [x] samr21-xpro

I could compile and run the tests when there was one correctly on the given list.

The patch also fixes that even if I was using /opt/gcc-arm-none-eabi-6-2017-q2-update the include directories were still search into /etc/alternatives/gcc-arm-none-eabi-include/c++/4.9.3.

Now the CXXINCLUDES also contains the C includes path which was not the case before. They will just be present two times in the command line as we use $(CXXINCLUDES) $(INCLUDES) when compiling.

* [x] I will test tomorrow but still wants to run `murdock` and maybe get feedback.
* [x] Test compiling `tests/cpp11*` on several different systems and testing the output with `TOOLCHAIN=llvm`
* [x] verify what I said about `GCC_MULTI_DIR`. I will explain how to do it or add a static check for testing.
* [ ] Propagate to use the `GCC_C_INCLUDES` variable for `makefiles/libc/newlib.mk`
    * -> Should come in a follow up PR

### Issues/PRs references

Fixes https://github.com/RIOT-OS/RIOT/issues/10166

### CODE REVIEW

**Comment by miri64** [comment]
One (?) of the workers can't find their Sam. Restarting Murdock.

**Comment by miri64** [comment]
#scnr

**Comment by cladmi** [comment]
@gebart Thanks for the feedback.

We were only using it to put it into `CXXINCLUDES` so is not provided to the linker.
But indeed we are currently linking with `gcc`.

I had a version were I replace directories from `GCC_CXX_INCLUDE_DIRS` with `d/$(GCC_MULTI_DIR)` if it exists but did not commit it as did not find a good reason to do it yet, so prefer to not add it and ask.

Also it looks like I can get the correct `gcc_include_dirs` with the multilib directory when providing `CFLAGS`. I will update accordingly.
I there a variable I could use instead of the whole `CFLAGS` ?

**Comment by cladmi** [comment]
I used deferred variables for the moment so it does not help. I could replace them with immediate ones.
It looks like I can use `CFLAGS_CPU`. It is defined in all the `makefiles/arch/*` files.

I can also put an assert that it is defined to detect issues if a new cpu tries to use llvm.

**Comment by cladmi** [comment]
Even with an immediate variable, `CFLAGS_FPU` can currently be modified later in build parsing https://github.com/RIOT-OS/RIOT/blob/f376b4669119ec88dae244dfde1b07dc7c416979/pkg/nordic_softdevice_ble/Makefile.include#L27

`nordic_softdevice_ble` is currently blacklisted for `llvm` but if enabled the value would change without being evaluated correctly.

**Comment by gebart** [comment]
@cladmi I think this is beginning to get out of hand. This may be a time to re-evaluate build system tools (laze, cmake, etc.)

**Comment by cladmi** [comment]
The problem will still be there. If a package is allowed to overwrite `FPU` the same behavior will be required. And if it is with a language without deferred then the definition order will be even more important than now.

If it should not be allowed and requires another mechanism to do it, we should also be doing it here.

**Comment by jia200x** [comment]
> @cladmi I think this is beginning to get out of hand. This may be a time to re-evaluate build system tools (laze, cmake, etc.)

+1

**Comment by miri64** [comment]
I've turned off the failing worker for now.

**Comment by gebart** [comment]
> The problem will still be there. If a package is allowed to overwrite `FPU` the same behavior will be required. And if it is with a language without deferred then the definition order will be even more important than now.
> 
> If it should not be allowed and requires another mechanism to do it, we should also be doing it here.

What I mean is that when running a Makefile generator tool it will be necessary to configure the CPU CFLAGS once per build. This should also implicitly improve the speed of some of the informational makefile targets, such as `make info-buildsize-diff` which is slow as hell right now for no particular reason other than that the build system will do all these pre-build checks on the module dependencies and configure the compiler before running the `size` tool on the binary.
I only suggested that we compare our options, if the benefits are less than the cost of refactoring, then there is no reason to use an extra tool.

**Comment by gebart** [comment]
@jia200x 
Looks like an incompatibility of the vendor headers. In C++ apparently, unnamed bitfields are not allowed to have qualifiers (volatile, const). I guess the image has an older Clang version without the check implemented.

**Comment by jia200x** [comment]
> @jia200x
Looks like an incompatibility of the vendor headers. In C++ apparently, unnamed bitfields are not allowed to have qualifiers (volatile, const). I guess the image has an older Clang version without the check implemented.

Yes, it seems so :/

**Comment by jia200x** [comment]
the proposed solution seems ok to me. I verified the paths given by ` arm-none-eabi-gcc -mcpu=cortex-m0plus -mlittle-endian -mthumb -mfloat-abi=soft -v -x c -E /dev/null 2>&1` and they are correct.

I'm +1 with @miri64. I think it's OK to merge this one and tackle the (possible) CFLAGS_FPU evaluation issue later. `nordic_softdevice_ble` is blacklisted anyway, so shouldn't affect us

**Comment by jia200x** [comment]
@cladmi could you please squash?

**Comment by cladmi** [comment]
I have the same errors for `samr21-xpro` on `arch linux`. But the issue is also present on `master` so unrelated to this PR.

**Comment by cladmi** [comment]
@jia200x there is no `CFLAGS_FPU` evaluation issue now with `nordic_softdevice_ble` as I am using a normal deferred variable. So it will use the updated value when set.

However there was one before.

**Comment by miri64** [comment]
Can we *please* merge this PR first, if only to fix the symptom and focus on the detail work later? This is stalling the whole integration process at the moment.

**Comment by jia200x** [comment]
> Can we please merge this PR first, if only to fix the symptom and focus on the detail work later? This is stalling the whole integration process at the moment.

Yes, please let's continue the work in follow-ups.

**Comment by cladmi** [comment]
Tests:

* [ ] arch linux
    * [ ] iotlab-m3
* [ ] ubuntu 16.04
    * [ ] iotlab-m3
    * [ ] samr21-xpro
* [ ] docker arm-gcc ppa
    * [ ] iotlab-m3
    * [ ] samr21-xpro
* [ ] docker new image
    * [ ] iotlab-m3
    * [ ] samr21-xpro

**Comment by cladmi** [comment]
I could compile and run the tests when there was one correctly on the given list.

The patch also fixes that even if I was using `/opt/gcc-arm-none-eabi-6-2017-q2-update` the include directories were still search into `/etc/alternatives/gcc-arm-none-eabi-include/c++/4.9.3`.

Now the `CXXINCLUDES` also contains the C includes path which was not the case before. They will just be present two times in the command line as we use `$(CXXINCLUDES) $(INCLUDES)` when compiling.

**Comment by cladmi** [comment]
I rebased and updated the main description with the last updates.

**Comment by kYc0o** [comment]
Tested on OSX and it solves some problems, taken into account that it never worked good on OSX.

I have this error on current master, which this PR solves.

```console
snake:RIOT facosta$ BOARD=samr21-xpro make -C tests/cpp11_mutex/ TOOLCHAIN=llvm clean all flash test
make: Entering directory '/Users/facosta/git/RIOT-OS/RIOT/tests/cpp11_mutex'
Building application "tests_cpp11_mutex" for "samr21-xpro" with MCU "samd21".

/Users/facosta/git/RIOT-OS/RIOT/tests/cpp11_mutex/main.cpp:20:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
```

**Comment by jia200x** [comment]
ok, Murdock green. Let's GO then

**Comment by jia200x** [comment]
thanks for the fix @cladmi!

**Pull request merged**
