### PR TITLE
doc: update to jquery 3.5.1

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR replaces our outdated jquery with current jquery 3.5.1 and jquery-migrate 3.3.0.

The reason for doing this is that github greets everyone on https://github.com/RIOT-OS/RIOT with a security vulnerability warning.

### Testing procedure

I have no clue about jquery, so please double check and test.
Take a look at the output, make sure everything works and looks as before.

Search doesn't work, but it is broken for me on master, too.

### CODE REVIEW

**Comment by miri64** [comment]
For me, the drop-downs in the top navbar don't work with this version. Can you try, if updating [smartmenus](https://www.smartmenus.org/blog/smartmenus/create-advanced-bootstrap-3-navbars-zero-config/) in `footer.html` does the trick?

**Comment by kaspar030** [comment]
(using PR to test CI)

**Comment by kaspar030** [comment]
> For me, the drop-downs in the top navbar don't work with this version. Can you try, if updating [smartmenus](https://www.smartmenus.org/blog/smartmenus/create-advanced-bootstrap-3-navbars-zero-config/) in `footer.html` does the trick?

I updated smartmenus to the latest version, unfortunately it doesn't do the trick. I pushed the commit anyways.

**Comment by miri64** [comment]
Mhh... The DOM abstraction seems to be working. When using the inspect function of the browser, the elements change as they do in master. The only thing missing is the visible menu.

**Comment by miri64** [comment]
Let's close this PR for now. This is just a formality regarding a bug in the rendering framework of our documentation (of a feature we probably don't use). I dismiss the security alert and we should look into modernizing the presentation of our documentation (e.g. by picking up https://github.com/RIOT-OS/RIOT/pull/11459)

**Comment by aabadie** [comment]
> we should look into modernizing the presentation of our documentation (e.g. by picking up #11459)

+1

**Pull request closed without merging**
