### PR TITLE
drivers: modbus_rtu: add initial support

### LINKED ISSUE #13869: Feature Request: ModBus RTU
#### Description
ModBus is usefull protocol for comunicate beetwen sensors and MCU.

I am confused that there is no implementation for RIOT. Perhaps there are some difficulties in implementation this?

I`m ready to realize this. But I need consultation how to start.

### PR DESCRIPTION
**Pull request by basilfx**
### Contribution description
This PR is a reboot of #13913 that got stale. I cloned it, rebased it onto master, adapted it to latest standards (hopefully) and extended it.

Contrary to the original PR, I removed a lot of `#ifdefs` that limited which Modbus functions would be supported. It was hard to manage IMHO.

I also extended the test application to test using a single or multiple devices.

### Testing procedure
A test application is provided in `tests/drivers/modbus_rtu`.

There are multiple ways to test this. The easiest is to connect RX/TX of one UART to TX/RX of another. That way, Modbus runs over 'RS-232'. Alternatively, connect two or more boards via a RS-485 network. Let one run as master and the other as slaves.

See [here](https://github.com/basilfx/RIOT/tree/feature/modbus_rtu/tests/drivers/modbus_rtu#modbus-rtu-driver-test) for more information.

### Issues/PRs references
Fixes #13869.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Maybe we can pick this up after the release?

**Comment by basilfx** [comment]
I found a use case for this driver, so I started using it. I found out that it doesn't really matches with real-world applications.

For example, if you would request Modbus register 1000, then that response is written to a buffer at offset 2000 (Modbus registers are 16 bits). That's odd, and requires you to allocate a lot of memory.

Now, this isn't that big of a deal, you might think. But it becomes much more odd from a slave point of view. If a slave receives a request to read register 1000, it also requires a buffer of sufficient size, to read from offset 2000.

Instead, I am refactoring the implementation, now I have a better understanding. What I am currently implementing:

- Request/response: remove data offset stuff
- Remove bit handling for reading/writing inputs or coils. Instead, the application should handle this.
- Add callback to slave implementation, so that user application can decide if and how to handle a request.
- Add support for returning Modbus exceptions.
  - This also allows the user to return exceptions when requesting data from unsupported registers

**Comment by krzysztof-cabaj** [comment]
Hi! 

If you plan/do refactoring - maybe you could split code concerning serial transmission and code which serve Modbus messages. This could allow easy addition of ModbusTCP.  See figure 1 in this [article](https://ijcnc.com/2020/04/14/ijcnc-01-8/) - I'm preety sure that Modbus messages (FCode and data) are identical both for ModbusRTU and ModbusTCP. 

I could help with ModbusTCP part

**Comment by basilfx** [comment]
@krzysztof-cabaj Thanks for the tip. I decided to move some generic code to separate files (for example in `modbus.c/h` instead of `modbus_rtu.c/h`), which I hope makes it easier to integrate TCP/IP some day. I'm quite far with it already. Hope to finalize it coming week.

**Comment by basilfx** [comment]
Let's continue in https://github.com/RIOT-OS/RIOT/pull/20386.

**Pull request closed without merging**
