### PR TITLE
drivers/nrf24l01p: unify return values

### PR DESCRIPTION
**Pull request by PeterKietzmann**
- The title is speaking I guess
- Not tested yet 
- I think the whole driver needs some love and hopefully adoptions to netdev at one time.

### CODE REVIEW

**Comment by A-Paul** [comment]
> - The title is speaking I guess

Not completely (at least for me). *Unified* with what?

**Comment by PeterKietzmann** [comment]
*Unified* with itself. Before, some functions returned `1` on success and some returned `0`. Now they are all returning a `0` on success (expect those returning a length or similar)

**Comment by PeterKietzmann** [comment]
rebased

**Comment by BytesGalore** [comment]
I like the change towards unified return values :+1:
(Though most of the functions are called without checking the return value.)
They are only used in the `tests` for this driver and check the negative value which didn't chage with this API change:
``` C
tests/driver_nrf24l01p_lowlevel/main.c:224:    if (nrf24l01p_on(&nrf24l01p_0) < 0) {
tests/driver_nrf24l01p_lowlevel/main.c:234:    if (nrf24l01p_preload(&nrf24l01p_0, tx_buf, NRF24L01P_MAX_DATA_LENGTH) < 0) {
tests/driver_nrf24l01p_lowlevel/main.c:229:    if (nrf24l01p_set_txmode(&nrf24l01p_0) < 0) {
tests/driver_nrf24l01p_lowlevel/main.c:198:    if (nrf24l01p_set_rxmode(&nrf24l01p_0) < 0) {
tests/driver_nrf24l01p_lowlevel/main.c:251:    if (nrf24l01p_set_rxmode(&nrf24l01p_0) < 0) {
```
ACK from my side.

**Comment by OlegHahm** [comment]
Something with travis seems to be odd. It seems to skip the `sudo pip install pexpect` line.

**Comment by authmillenon** [comment]
Because the most current travis.yml isn't picked up on travis boot-up. Please rebase.

**Comment by OlegHahm** [comment]
I still don't understand. Why was there a version of the Travis configuration that didn't provide pexpect even if the scripts would have required it?

**Comment by authmillenon** [comment]
This is how travis works:
 * read .travis.yml and start VM accordingly (including pre-build installation instructions)
 * our .travis.yml then (after the install process) merges in master

The .travis.yml in this PR is older then the changes done by merging https://github.com/RIOT-OS/RIOT/pull/3309. This is why the .travis.yml in the current master isn't picked up, but the .travis.yml of the older version of master this PR is based on => travis picks up the old version on boot-up.

**Comment by OlegHahm** [comment]
Can we change this that Travis would either re-reads the yml file after booting the VM or uses the yml from the PR branch?

**Comment by OlegHahm** [comment]
Btw. thanks for the explanation.

**Comment by authmillenon** [comment]
> Can we change this that Travis would either re-reads the yml file after booting the VM or uses the yml from the PR branch?

I'm afraid no. At least not to my knowledge.

**Comment by OlegHahm** [comment]
How about parameterizing the `build_and_test` script?

**Comment by OlegHahm** [comment]
Sorry, this is quite off-topic for the PR. Started #4920 to continue discussion on Travis.

@PeterKietzmann, just rebase and we should be ready to merge.

**Comment by PeterKietzmann** [comment]
Did. But hopefully the driver gets a complete polish soon

**Comment by PeterKietzmann** [comment]
BTW: Travis passed

**Comment by OlegHahm** [comment]
So, why don't you merge?

**Comment by PeterKietzmann** [comment]
Because it's my own PR and
>should be ready to merge
Anyway, will do now...

**Comment by OlegHahm** [comment]
:)

**Pull request merged**
