### PR TITLE
boards/esp32s3-wt32-sc01-plus: fix Kconfig

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes a remaining Kconfig mismatch. It should fix the last compilation problem of the nightly.

### Testing procedure

```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/drivers/ili9341/ -b esp32s3-wt32-sc01-plus
```
should fail w/o this PR but should succeed with this PR.

### CODE REVIEW

**Comment by aabadie** [comment]
The testing procedure fails with this PR:

```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/drivers/ili9341/ -b esp32s3-wt32-sc01-plus
tests/drivers/ili9341/         esp32s3-wt32-sc01-plus         FAIL: Kconfig hash mismatch
```

I tried on commit 952bb264647c7978b330c9642eda1f778fafdfc3

**Review by benpicco — DISMISSED** [review]

**Comment by gschorcht** [comment]
> The testing procedure fails with this PR:
> 
> ```
> python3 dist/tools/compile_test/compile_like_murdock.py -a tests/drivers/ili9341/ -b esp32s3-wt32-sc01-plus
> tests/drivers/ili9341/         esp32s3-wt32-sc01-plus         FAIL: Kconfig hash mismatch
> ```

What? :thinking:

**Comment by gschorcht** [comment]
> python3 dist/tools/compile_test/compile_like_murdock.py -a tests/drivers/ili9341/ -b esp32s3-wt32-sc01-plus

I can't reproduce it. The output for me is:
```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/drivers/ili9341/ -b esp32s3-wt32-sc01-plus
tests/drivers/ili9341/         esp32s3-wt32-sc01-plus         PASS
This took 0:01:10.243525...
You could have 2.16350057e-05 bitcoins mined
```

**Comment by aabadie** [comment]
Ok, my bad: I don't have the esp32 toolchain on my system. After adding `-vv` to the command line, I got this in the output: `Compiler xtensa-esp32s3-elf-gcc is required but not found in PATH.  Aborting.`

I'm trying again with `BUILD_IN_DOCKER=1` added. Not sure this might work or not.

**Comment by aabadie** [comment]
So, I can't make it work using `BUILD_IN_DOCKER=1`. Let's just trust @gschorcht given output.

**Review by aabadie — APPROVED** [review]
ACK

**Comment by aabadie** [comment]
bors merge

**Comment by gschorcht** [comment]
> Build failed (retrying...):
> 
> * [Murdock](https://ci.riot-os.org/details/ba8dc586773848169e824fef3040ba9e)

Unrelated error.

**Comment by gschorcht** [comment]
bors merge

**Pull request merged**
