### PR TITLE
gnrc_netif_conf: fix auto-6ctx switch

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
When configuring a boolean via Kconfig and setting it to `n`, the result is that the symbol will not be defined as a preprocessor macro. As a result, setting `CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX` to `n` has no effect, as

```
#ifndef CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX
#define CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX   1
#endif
```

(as was pointed out in https://github.com/RIOT-OS/RIOT/pull/17678#discussion_r810259709). Without changing the name to a negative, the only other valid option is to check if `gnrc_netif` was configured via Kconfig in addition to the normal `#ifndef`. This PR applies that change.

### Testing procedure
Once a global address is configured with
```
BOARD=native RIOT_CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX=n RIOT_CONFIG_KCONFIG_USEMODULE_GNRC_NETIF=y make -C examples/gnrc_border_router flash -j term
```
the table returned by `6ctx` should remain empty.

### Issues/PRs references
Follow-up on #17678

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by leandrolanzieri** [comment]
I think the test proceeding is missing a `SHOULD_RUN_KCONFIG=1` or a previous Kconfig run to actually run Kconfig and apply the command line options.
```sh
BOARD=native RIOT_CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX=n RIOT_CONFIG_KCONFIG_USEMODULE_GNRC_NETIF=y SHOULD_RUN_KCONFIG=1 make -C examples/gnrc_border_router -j
```

I tested by adding a check in `gnrc_netif.c`:
```C
#if IS_ACTIVE(CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX)
#error "Compression context"
#else
#error "No compression context"
#endif
```

With this PR the option is not overwritten by the header file when configuring with Kconfig.

**Comment by miri64** [comment]
> I think the test proceeding is missing a `SHOULD_RUN_KCONFIG=1` or a previous Kconfig run to actually run Kconfig and apply the command line options.

IIRC with the `RIOT_CONFIG` environment variables this is implied.

**Comment by leandrolanzieri** [comment]
> > I think the test proceeding is missing a `SHOULD_RUN_KCONFIG=1` or a previous Kconfig run to actually run Kconfig and apply the command line options.
> 
> IIRC with the `RIOT_CONFIG` environment variables this is implied.

The example is explicitly disabling it
https://github.com/RIOT-OS/RIOT/blob/9e283b967d20337e50ad5f7ef32de08f1d8e247f/examples/gnrc_border_router/Makefile#L112-L114

**Comment by miri64** [comment]
Backport provided in #18375

**Pull request merged**
