### PR TITLE
pkg: oonf_api: remove compilation error

### PR DESCRIPTION
**Pull request by cgundogan**
building the package `oonf_api` results in the following error at multiple places:
```
error: array subscript has type 'char' [-Werror=char-subscripts]
```

This PR patches `oonf_api` to make the compiler comply.

### CODE REVIEW

**Comment by cgundogan** [comment]
Rationale: the newlib functions for some toolchains might be implemented with arrays. Therefore, it is necessary to cast `char` to `unsigned char` when using functions like `isspace()` and `isblank()`

**Comment by OlegHahm** [comment]
How did you test?

**Comment by authmillenon** [comment]
ACK. (tested compilability with `USEMODULE=oonf_common make -C examples/default/`)

**Comment by cgundogan** [comment]
@OlegHahm I did use #4277 before I included this commit to fix oonf_api there

**Pull request merged**
