### PR TITLE
cpu/stm32: fix name clash between cpu/stm32/Kconfig files and cpu/stm32/kconfig directory

### LINKED ISSUE #15255: Repository 'broken' on macOS due to case-insensitive names
#### Description
When cloning RIOT-OS, Git immediately complains about `cpu/stm32/Kconfig` being deleted. When restoring that file, it removes the directory `cpu/stm32/kconfig`. This has to do with macOS being case-insensitive by default.

I work-around this issue by creating a case-insensitive volume for my RIOT workspace. But I think this issue should be resolved to provide a better user experience.

#### Steps to reproduce the issue
Clone RIOT and notice that `git status` immediately complains about `cpu/stm32/Kconfig`.

#### Expected results
A clean repository.

#### Actual results
`git status` shows that `cpu/stm32/Kconfig` is deleted.

#### Versions
```
Operating System Environment
----------------------------
         Operating System: Mac OS X 10.15.7
                   Kernel: Darwin 19.6.0 x86_64 i386
             System shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
             make's shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

Installed compiler toolchains
-----------------------------
               native gcc: Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: Apple clang version 11.0.0 (clang-1100.0.33.8)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.3.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: missing
                    cmake: cmake version 3.18.4
                 cppcheck: missing
                  doxygen: missing
                      git: git version 2.29.0
                     make: GNU Make 3.81
                  openocd: missing
                   python: Python 2.7.16
                  python2: Python 2.7.16
                  python3: Python 3.8.6
                   flake8: error: /usr/local/opt/python@3.8/bin/python3.8: No module named flake8
               coccinelle: missing
```

### LINKED ISSUE #15256: Kconfig file/folder name collision on case-insensitive filesystem
#### Description

The Kconfig file in cpu/stm32/ is missing in the cloned repository. 
Because there is a folder with the same name the file cannot be created.

I think this is related to #14158 and #14160

#### Steps to reproduce the issue

Clone repository on MacOS with case-insensitive APFS filesystem.

#### Expected results

Both file and folder available.

#### Actual results

cpu/stm32/Kconfig is missing.

#### Versions

MacOS 10.13.6 with case-insensitive APFS filesystem.

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Fixes #15256 and fixes #15255 

The directory `cpu/stm32/kconfig` is renamed to `cpu/stm32/kconfigs` to avoid the name clash on systems with non case-sensitive file systems.

I added the `Needs backport` label to the PR because it's also in 2020.10-branch.

### Testing procedure

- A green Murdock
- the `gen_kconfig.py` script works as expected:

```
$ rm -rf cpu/stm32/kconfigs/f0/Kconfig.models
$ ./cpu/stm32/dist/kconfig/gen_kconfig.py f0 -s ~/Downloads/F0ProductsList.xlsx
```

=> file is back and unchanged

### Issues/PRs references

Fixes #15256 and fixes #15255

### CODE REVIEW

**Comment by basilfx** [comment]
I don't have access to the `F0ProductsList.xlsx` file, but checking out the repository works.

About the name: in line with the `kconfigs/` folder in the root, I would rename `cpu/stm32/configs` to `cpu/stm32/kconfigs` as well.

**Comment by aabadie** [comment]
> in line with the kconfigs/ folder in the root, I would rename cpu/stm32/configs/ to cpu/stm32/kconfigs/ as well.

I agree and (force)-pushed the update. `gen_kconfig.py` is still working.

**Comment by aabadie** [comment]
@fjmolinas mind to ACK this PR ?

**Comment by fjmolinas** [comment]
The fix goes in the same direction as  #14160, I'll test ASAP.

**Review by fjmolinas — APPROVED** [review]
Tested on OSX:

- master

```
ls -la cpu/stm32/
total 128
drwxr-xr-x  21 francisco  staff    672 Oct 21 10:22 .
drwxr-xr-x  47 francisco  staff   1504 Oct 21 10:22 ..
-rw-r--r--   1 francisco  staff    181 Oct 21 10:22 Makefile
-rw-r--r--   1 francisco  staff    692 Oct 21 10:22 Makefile.dep
-rw-r--r--   1 francisco  staff   1441 Oct 21 10:22 Makefile.features
-rw-r--r--   1 francisco  staff   3459 Oct 21 10:22 Makefile.include
drwxr-xr-x   4 francisco  staff    128 Oct 21 10:22 bootloader
-rw-r--r--   1 francisco  staff   7598 Oct 21 10:22 cpu_common.c
-rw-r--r--   1 francisco  staff   5687 Oct 21 10:22 cpu_init.c
drwxr-xr-x   6 francisco  staff    192 Oct 21 10:22 dist
-rw-r--r--   1 francisco  staff   2713 Oct 21 10:22 doc.txt
drwxr-xr-x  12 francisco  staff    384 Oct 21 10:22 include
drwxr-xr-x  14 francisco  staff    448 Oct 21 10:22 kconfig
drwxr-xr-x   3 francisco  staff     96 Oct 21 10:22 ldscripts
drwxr-xr-x  35 francisco  staff   1120 Oct 21 10:22 periph
-rw-r--r--   1 francisco  staff   1253 Oct 21 10:22 stm32_info.mk
-rw-r--r--   1 francisco  staff   4949 Oct 21 10:22 stm32_line.mk
-rw-r--r--   1 francisco  staff  10034 Oct 21 10:22 stm32_mem_lengths.mk
-rw-r--r--   1 francisco  staff   2415 Oct 21 10:22 stm32_riotboot.mk
drwxr-xr-x   9 francisco  staff    288 Oct 21 10:22 stmclk
drwxr-xr-x   4 francisco  staff    128 Oct 21 10:22 vectors

```
- pr

```
ls -la cpu/stm32/
total 136
drwxr-xr-x  22 francisco  staff    704 Oct 21 10:25 .
drwxr-xr-x  47 francisco  staff   1504 Oct 21 10:22 ..
-rw-r--r--   1 francisco  staff   1126 Oct 21 10:25 Kconfig
-rw-r--r--   1 francisco  staff    181 Oct 21 10:22 Makefile
-rw-r--r--   1 francisco  staff    692 Oct 21 10:22 Makefile.dep
-rw-r--r--   1 francisco  staff   1441 Oct 21 10:22 Makefile.features
-rw-r--r--   1 francisco  staff   3459 Oct 21 10:22 Makefile.include
drwxr-xr-x   4 francisco  staff    128 Oct 21 10:22 bootloader
-rw-r--r--   1 francisco  staff   7598 Oct 21 10:22 cpu_common.c
-rw-r--r--   1 francisco  staff   5687 Oct 21 10:22 cpu_init.c
drwxr-xr-x   6 francisco  staff    192 Oct 21 10:22 dist
-rw-r--r--   1 francisco  staff   2713 Oct 21 10:22 doc.txt
drwxr-xr-x  12 francisco  staff    384 Oct 21 10:22 include
drwxr-xr-x  14 francisco  staff    448 Oct 21 10:25 kconfigs
drwxr-xr-x   3 francisco  staff     96 Oct 21 10:22 ldscripts
drwxr-xr-x  35 francisco  staff   1120 Oct 21 10:22 periph
-rw-r--r--   1 francisco  staff   1253 Oct 21 10:22 stm32_info.mk
-rw-r--r--   1 francisco  staff   4949 Oct 21 10:22 stm32_line.mk
-rw-r--r--   1 francisco  staff  10034 Oct 21 10:22 stm32_mem_lengths.mk
-rw-r--r--   1 francisco  staff   2415 Oct 21 10:22 stm32_riotboot.mk
drwxr-xr-x   9 francisco  staff    288 Oct 21 10:22 stmclk
drwxr-xr-x   4 francisco  staff    128 Oct 21 10:22 vectors
```

**Comment by aabadie** [comment]
backport provided in #15261

**Comment by benpicco** [comment]
I wonder if we can enable case folding on Murdock to spot these things early

https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4

**Pull request merged**
