### PR TITLE
doc: fix URLs to the new website

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
With the new website some links in our documentation are not working anymore. This updates them.

### Testing procedure
- Build the docs and check the link
- Open RDM1 and check the reference link

### Issues/PRs references
https://github.com/RIOT-OS/riot-os.org/pull/82

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
ACK. The old link is outdated and those are the only two links remaining to `https://riot-os.org/docs`:

```console
$ git grep 'riot-os.org/docs/'
doc/doxygen/src/mainpage.md:the IoT](https://riot-os.org/docs/riot-ieeeiotjournal-2018.pdf)
doc/memos/rdm0001.md:Poster, p. 79–80, IEEE Press, April 2013.](https://www.riot-os.org/docs/riot-infocom2013-abstract.pdf) \
```

**Comment by miri64** [comment]
Waiting for Circle CI with merge, so the correct link can be confirmed.

**Comment by miri64** [comment]
> Waiting for Circle CI with merge, so the correct link can be confirmed.

Link works now on `index.html` :+1:

**Comment by leandrolanzieri** [comment]
Thanks!

**Pull request merged**
