### PR TITLE
mtd: allow to use non-pagewise functions

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

If the underlying driver implements 'plain' read/write/erase functions, don't convert them to pagewise functions and back.

Just use the old direct functions.

### CODE REVIEW

**Comment by fjmolinas** [comment]
@benpicco how should I test this?

**Comment by benpicco** [comment]
Ideally by running the `mtd_` tests in `tests`

**Comment by fjmolinas** [comment]
> Ideally by running the mtd_ tests in tests

But what platform benefits from thsi change?

**Comment by benpicco** [comment]
> But what platform benefits from thsi change?

All drivers that don't implement `.read_page` / `.write_page`, e.g. `mtd_flashpage`.

Especially for reads converting address -> page -> address is silly when in the end it comes down to a simple `memcpy`.

**Review by vincent-d — APPROVED** [review]
Code-wise, it looks OK and makes sense.

Confirmed unit tests still works.

ACK

**Pull request merged**
