### PR TITLE
boards/msbiot: Configured cc110x as default netdev

### PR DESCRIPTION
**Pull request by maribu**
boards/msbiot/Makefile.include:
 - Use module "cc110x" if netdev_default or gnrc_netdev_default
   is used

boards/msbiot/include/cc110x_params.h:
 - Added configuration for the CC1101 transceiver

### CODE REVIEW

**Comment by maribu** [comment]
Hi,

as the only remaining MSB IoT boards on this planet are all here in my office, I see very little advantage in reviewing patches for it. I suggest to drop support for the MSB IoT board in the official RIOT repository. Instead, I would prefer to maintain the MSB IoT configuration as a separate repository in my own github account, which my students can add as submodule.

Kind regards,
Marian

**Comment by miri64** [comment]
> Instead, I would prefer to maintain the MSB IoT configuration as a separate repository in my own github account, which my students can add as submodule.

Are you and your students using the `cc110x`? Can you confirm that it works? I'm asking [for a friend ;-)](https://github.com/RIOT-OS/RIOT/pull/7414#issuecomment-335611813)

**Comment by maribu** [comment]
Hi,

on the MSB IoT it is not working. I planned to fix it for weeks but never had the time. (Initialisation is working, but I every packet send gets lost.)

Since my students will start working on the real device in two weeks, I am going to dive into it as soon as possible. If there are fixes not specific to the MSB IoT, I will create Pull Requests for those. I have some MSB A2 boards as well sitting on my desk waiting desperately for my attention. I will post an update if the cc110x is working on these devices with gnrc.

Kind regards,
Marian

Am 2. November 2017 19:59:01 MEZ schrieb Martine Lenders <notifications@github.com>:
>> Instead, I would prefer to maintain the MSB IoT configuration as a
>separate repository in my own github account, which my students can add
>as submodule.
>
>Are you and your students using the `cc110x`? Can you confirm that it
>works? I'm asking [for a friend
>;-)](https://github.com/RIOT-OS/RIOT/pull/7414#issuecomment-335611813)

-- 
Via mobile phone

**Comment by maribu** [comment]
Hi,

the MSB-A2 seems to get stuck in a deadlock while booting when a network package is used. I will have a look at it.

Kind regards,
Marian

**Comment by maribu** [comment]
Apparently this is related to https://github.com/RIOT-OS/RIOT/issues/6857

**Comment by maribu** [comment]
With the lastest two commits, which (as a side effect) works arround the issue in https://github.com/RIOT-OS/RIOT/issues/6857, I can confirm that the CC110X driver does *not* work with GNRC.

```
Warning: no PORT set!
/data/riotbuild/RIOT/dist/tools/pyterm/pyterm -tg -p "/dev/ttyUSB0"
2017-11-18 17:49:42,999 - INFO # Connect to serial port /dev/ttyUSB0
Welcome to pyterm!
Type '/exit' to exit.
2017-11-18 17:49:44,005 - INFO # random: NO SEED AVAILABLE!
2017-11-18 17:49:44,006 - INFO # netdev_cc110x_setup()
2017-11-18 17:49:44,008 - INFO # drivers/cc110x/cc110x.c:cc110x_setup:49
2017-11-18 17:49:44,009 - INFO # drivers/cc110x/cc110x.c:_power_up_reset:212
2017-11-18 17:49:44,009 - INFO # drivers/cc110x/cc110x.c:_reset:203
2017-11-18 17:49:44,010 - INFO # cc110x_set_base_freq_raw(): setting base frequency to 867930228Hz
2017-11-18 17:49:44,010 - INFO # drivers/cc110x/cc110x.c:cc110x_set_channel:187
2017-11-18 17:49:44,011 - INFO # drivers/cc110x/cc110x.c:cc110x_set_address:98 setting address 34
2017-11-18 17:49:44,011 - INFO # cc110x: initialized with address=34 and channel=0
2017-11-18 17:49:44,011 - INFO # _init:189
2017-11-18 17:49:44,012 - INFO # drivers/cc110x/cc110x.c:cc110x_rd_set_mode:239
2017-11-18 17:49:44,012 - INFO # drivers/cc110x/cc110x.c:cc110x_setup_rx_mode:131
2017-11-18 17:49:44,013 - INFO # drivers/cc110x/cc110x.c:cc110x_switch_to_rx:140
2017-11-18 17:49:44,013 - INFO # gnrc_netdev_cc110x: sending packet from 34 to 0 with payload length 23
2017-11-18 17:49:44,013 - INFO # _send:41
2017-11-18 17:49:44,014 - INFO # cc110x: snd pkt to 0 payload_length=20
2017-11-18 17:49:44,014 - INFO # write_reg IOCFG2, 0x02
2017-11-18 17:49:44,014 - INFO # strobe SIDLE
2017-11-18 17:49:44,014 - INFO # strobe SFTX
2017-11-18 17:49:44,014 - INFO # _tx_continue
2017-11-18 17:49:44,015 - INFO # main(): This is RIOT! (Version: 2018.01-devel-535-g23db2e-724d788f5a5a)
2017-11-18 17:49:44,015 - INFO # gcoap example app
2017-11-18 17:49:44,015 - INFO # All up, running the shell now
> 2017-11-18 17:49:53,091 - INFO #  gnrc_netdev_cc110x: sending packet from 34 to 0 with payload length 23
2017-11-18 17:49:53,091 - INFO # _send:41
2017-11-18 17:49:53,093 - INFO # cc110x: snd pkt to 0 payload_length=20
2017-11-18 17:49:53,094 - INFO # cc110x: invalid state for sending: tx busy
2017-11-18 17:50:03,090 - INFO # gnrc_netdev_cc110x: sending packet from 34 to 0 with payload length 23
2017-11-18 17:50:03,091 - INFO # _send:41
2017-11-18 17:50:03,092 - INFO # cc110x: snd pkt to 0 payload_length=20
2017-11-18 17:50:03,093 - INFO # cc110x: invalid state for sending: tx busy
2017-11-18 17:50:13,090 - INFO # gnrc_netdev_cc110x: sending packet from 34 to 0 with payload length 23
2017-11-18 17:50:13,091 - INFO # _send:41
2017-11-18 17:50:13,092 - INFO # cc110x: snd pkt to 0 payload_length=20
2017-11-18 17:50:13,093 - INFO # cc110x: invalid state for sending: tx busy
```

Apparently the CC110X driver never leaves the state tx busy. From what I understand, `_tx_continue` should be called once the packet was out. This would detect the empy FIFO and switches to RX mode. It seems `_tx_continue` is only called when `cc110x_send` is called.

Kind regards,
Marian

**Comment by maribu** [comment]
I should split my changes into separate pull requests. I will do so once I got any progress in solving this issue.

**Comment by hahchenchen** [comment]
I have the same issue with yours. the `dev->radio_state` always stay in `RADIO_TX_BUSY`, what i understand is once the packet is send over, the pin gdo2 will generate a interrupt, but i dont know why there is no interrupt occurd.
Do you have any progress?

**Comment by maribu** [comment]
Dear Hahchenchen,
I have to focus on a proposal for now and I will also have a month of parental leave. So I will not work on it any time soon. However, we still have some MSBA2 and MSB-IoT boards. So it would be nice to fix the driver and start using them again.

What board with a CC1100/C1101 do you have?

It is very likely, that the problem is the SPI communication. The driver was written when the SPI Bus was enabled at boot up and remained online. At that time, `spi_acquire()` and `spi_release()` where just to lock a mutex. This locking was done at a fine granular level, so that functions like `cc110x_send()` ended up locking and releasing the mutex many times. But the SPI API changes, so that `spi_acquire()` is configuring the SPI bus for the given mode and frequency and turns it on, while `spi_release()` turns it back off. So within a `cc110x_send()` the SPI BUS is turned on and off many times over. This is not only very disadvantages from a performance point of view, but also can introduce timing issues. I believe that this is the reason the CC1100/CC1101 is no longer working with recent RIOT versions.

A quick fix would be to comment out the code that enables/disables the SPI BUS and check, if the cc110x drivers works again. If so, changing the driver to do a `spi_acquire()` at the begin of every high level function and a `spi_release()` at its end would hopefully work with the current SPI API. If not, one could use an `spi_acquire()` at initializing the cc110x driver. That way the SPI bus can no longer be shared with different devices...

Kind regards,
Marian

**Comment by hahchenchen** [comment]
Dear Marian
I tried it, but seems not working, and i use /test/periph_spi for test, still not working, can't read the data of register.
So odd....

**Comment by hahchenchen** [comment]
I use the oscilloscope to test the sclk ,so and si signal, the maximum voltage of  so and si is only 1.65v, so is there any influence for chip to judge?

**Comment by hahchenchen** [comment]
this is the so and si singal after i send a read register command. 0xf0, the yellow line is so, the blue one is si, so the so signal should be low, not high at the begin of so.
webwxgetmsgimg

**Pull request closed without merging**
