### PR TITLE
tests: add pep8 check in static tests and fix related issues in the tests directory

### PR DESCRIPTION
**Pull request by aabadie**
Since we are planning to use python scripts for automating the applications testing, I think it would be great to stay compliant with Python standards and especially [PEP8](https://www.python.org/dev/peps/pep-0008/)

This PR adds an new check script for PEP8, integrated in the `make static-test` command and fixes the ones that were found by the command.

We also need to install pep8 into Murdock containers and add another package (`python-pep8` in #8020 if it's merged)

### CODE REVIEW

**Comment by miri64** [comment]
Mhhh I'm wondering if PEP8 compliance is really desirable. Sure it helps to find a few issues in python scripts and and cleans up most of the code, but some of the rules I find quite nit-picky (like the two lines after import e.g.) and even go against coding conventions of well established python projects.

**Comment by aabadie** [comment]
> even go against coding conventions of well established python projects

Which ones ?

In this PR, the default parameters are applied but they can be adapted (the line too long can be extended, and I would prefer that in some networking tests).

The 2 blank lines are required before a function or class definition, this is very common.

Maybe `flake8` could be preferred other `pep8`. I just run it and it found an issue skipped by pep8...

**Comment by aabadie** [comment]
@miri64, I just gave a try to [flake8](http://flake8.pycqa.org/en/latest/manpage.html), that I think is more complete than pep8.
I changed the max-line-length to 119 characters which is more convenient that the default 80.

I understand your concern about not being too strict with Python code, since RIOT is a C code project but I think it's good to have consistency across the different script and enabling flake8 checks will help for that.

**Comment by miri64** [comment]
> Which ones ?

E.g. [pexpect itself](https://github.com/pexpect/pexpect/blob/master/pexpect/spawnbase.py#L7-L10) (no two lines after import, no uppercase globals, and properly more).

**Comment by miri64** [comment]
(but I was more thinking about django, but I admit that django is famously known for not being very pythonic ;-))

**Comment by aabadie** [comment]
I looked at Django's Github and [they also use flake8 in their testing env](https://github.com/django/django/blob/master/tox.ini#L32). But they doesn't seem to have an external CI.

**Comment by aabadie** [comment]
[cbor2](https://github.com/agronholm/cbor2/blob/master/tox.ini) is also doing this kind of checks ;)

**Comment by cladmi** [comment]
More than pep8 that only checks style, I would like more to add `pylint` which does static analysis and pushes more coding conventions, requires documenting and things.
We could take some time offline to look into the impact and see if its valuable.

Also before pushing and enforcing the tools, I would require to document the new conventions and add tools with warning at first.
Adding python requirements also requires updating murdock, docker, vagrant vm.

Then, in other PRs, do the tests/code migration to simplify reviewing, like what is done for C warnings to add -Wall -Wextra.

**Comment by aabadie** [comment]
> add pylint which does static analysis and pushes more coding conventions, requires documenting and things

I also thought of that but I fear this is a bit overkill and we will probably end up in a lot Python tricks in the code/configuration files.

> We could take some time offline to look into the impact and see if its valuable.

I have some availability this afternoon. Email me so we can sync.

> I would require to document the new conventions and add tools with warning at first.

+1 for the documentation. For the warning, it's possible, `flake8/check.sh` could return a 0 exit code.

> Adding python requirements also requires updating murdock, docker, vagrant vm.

With static-test run in travis (as proposed in #8020), this could be done in the same PR.

> Then do the tests/code migration in other PRs to simplify reviewing

+1

**Comment by miri64** [comment]
> I looked at Django's Github and they also use flake8 in their testing env. But they don't seem to have an external CI.

The code definitely doesn't look like that :P.

> cbor2 is also doing this kind of checks ;)

Ok. Fine :-).

**Comment by aabadie** [comment]
Created #8141 to track style check errors and related PRs. Closing this one because those PRs will supersede this one.

**Pull request closed without merging**
