### PR TITLE
doc: fix undefined typedef docu

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

Rework documentation of enum with typedef, i.e. remove grouping
as it is not required.

### Testing procedure

run `make doc` on master and this PR, on master you'll see following error:

```
RIOT/core/include/sched.h:102: warning: Member thread_status_t (enumeration) of group core_sched is not documented.
```

which is fixed here.

### CODE REVIEW

**Comment by smlng** [comment]
@aabadie I use doxygen version 1.8.15, btw. its not an error as such that doxygen fails, but it shows a warning (see above). And yes there are lots more ...

Regarding the clarity, I'd say it depends :smile: ... as always. With this PR the documentation is (IMHO) more consistent with the doc of typdefs, functions etc. bc up front you get an overview on structs, functions, variables and enums defined, and further down the detailed description/documentation of each function, ..., and enum.

**Comment by smlng** [comment]
btw doxygen has `@enum` and `@typedef`, for the latter I added a separate commit here. It doesn't seem to change the docu, though.

**Comment by aabadie** [comment]
In the current state, this PR still changes the rendered documentation.
I'm wondering if the warning would be fixed with this rather simple change:
```diff
diff --git a/core/include/sched.h b/core/include/sched.h
index 2511e0bb5ec..6cc0bcf1a8f 100644
--- a/core/include/sched.h
+++ b/core/include/sched.h
@@ -98,6 +98,7 @@ typedef struct _thread thread_t;
 /**
  * @name Thread states supported by RIOT
  * @{
+ * @brief   Thread states enum
  */
 typedef enum {
     STATUS_STOPPED,                 /**< has terminated                           */
```

or, maybe better, this one:
```diff
git diff
diff --git a/core/include/sched.h b/core/include/sched.h
index 2511e0bb5ec..222a7eee148 100644
--- a/core/include/sched.h
+++ b/core/include/sched.h
@@ -98,6 +98,7 @@ typedef struct _thread thread_t;
 /**
  * @name Thread states supported by RIOT
  * @{
+ * @enum    Thread states enum
  */
 typedef enum {
     STATUS_STOPPED,                 /**< has terminated                           */
```

**Comment by tcschmidt** [comment]
This needs additional careful eyes - @kaspar030 ?

**Pull request closed without merging**
