### PR TITLE
Device Driver for TMP006 Sensor

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR add support for TI TMP006 Infrared Thermopile Sensor.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
`vtimer` works now. Needs squashing and waiting for #2059 to be merged. Then I'll give my final ACK.

**Comment by OlegHahm** [comment]
@PeterKietzmann, I think we could merge it independent from #2059.

**Comment by PeterKietzmann** [comment]
Okay, if you are happy with the formalities I'm too. Was just wondering if it's strange to merge an application for a board that is not in master. This also applies to #2119, #2121 and #2123.

**Comment by PeterKietzmann** [comment]
Let's go

**Pull request merged**
