### PR TITLE
boards/nrf52: cleanup shared Makefile.deps

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
The `nrf52832` and the `nrf52840`-based platforms have different default radio modes (`nimble_netif` and `nrf802154`, respectively). But the according `Makefile.dep`s were a little messy, so this PR should improve on this...

### Testing procedure
For `gnrc_networking`, verify that all `nrf52840` boards are now being build with the 802.15.4 support (`nrf802154`) and all `nrf52832` baords with IP-over-BLE support (`nimble_netif`). Also, all boards should flawlessly build with `nrfmin`.

### Issues/PRs references
none

### CODE REVIEW

**Comment by haukepetersen** [comment]
Just in case someone is wondering: for some reason, some of the effected boards were per default using the `nrfmin` driver. Although this is/was helpful for including this driver in the build tests, it is quite strange to have some boards using this driver, and some others with the same CPU using another radio mode... I opened an issue for including the `nrfmin` driver again in the build tests (#12115), so we don't forget about this.

**Comment by aabadie** [comment]
Could this be considered as a duplicate of #11792 ? (I haven't look into the details).

**Comment by haukepetersen** [comment]
Just noticed: this PR also fixes all `nrf52840` boards, as currently we are not able to build `nimble_netif` for these due to a collision with the `nrf802154` module...

**Comment by haukepetersen** [comment]
yes, it actually is kind of (did not see it...). Although #11792 has still some dependency loop and it is not up-to-date with the ble stuff we merged yesterday.

I don't care how we proceed, do you want to adapt #11792 and I simply close this PR? Or the other way around?

**Comment by haukepetersen** [comment]
closing in favor of #11792

**Pull request closed without merging**
