### PR TITLE
dist/tools/tested-support: fix samr30 archi mapping

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is fixing the mapping between `samr30-xpro` and IoT-LAB `samr30:at86rf212b` archi. The archi attribute was changed yesterday on IoT-LAB to reflect the radio used by this board (there was a mistake before...).

### Testing procedure

1. Book a samr30 on IoT-LAB:
```
$ iotlab-experiment submit -n pr_samr30 -d 20 -l 1,archi=samr30:at86rf212b+site=saclay
$ iotlab-experiment wait
```
2. Build, flash, term it with any application using the RIOT build system:
```
$ make BOARD=samr30-xpro IOTLAB_NODE=auto-ssh -C examples/default/ flash term
```

### Issues/PRs references

None

### CODE REVIEW

**Comment by cladmi** [comment]
Tinycrypt failed, restart.

**Comment by aabadie** [comment]
> Please update the commit title and description.

Done @cladmi !

**Comment by cladmi** [comment]
Just waiting for murdock to merge it.

**Comment by aabadie** [comment]
Murdock is green, so let's go ;)

**Pull request merged**
