### PR TITLE
ng_ipv6: only try to parse ext header if enabled

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
I prefer to put it around the whole case as I did with UDP etc.

**Comment by authmillenon** [comment]
I don't only prefer it, it's the right way to do. Otherwise `pkt` gets released more than once.

**Comment by OlegHahm** [comment]
Where is the second release?

**Comment by OlegHahm** [comment]
Just discovered that ICMPv6 has the same problem.

**Comment by authmillenon** [comment]
L109. Or one of the subscribers to one of the extension headers

**Comment by authmillenon** [comment]
Ah wait, the return prevents that.

**Comment by OlegHahm** [comment]
yes

**Comment by authmillenon** [comment]
But it also prevents, that anyone can register to extension headers now...

**Comment by OlegHahm** [comment]
If they are disabled?

**Comment by authmillenon** [comment]
Define disabled. If you mean "not compiled in" then only the default way to handle extension headers is disabled. Is UDP disabled just because there is no UDP module?

**Comment by OlegHahm** [comment]
Yes.

**Comment by authmillenon** [comment]
It hinders the flexibility of the stack and at the same time introduces unnecessary extra code is all I'm saying.

**Comment by authmillenon** [comment]
Because than you have to do it in theory for every unsupported next header. Why are the extension headers the only ones that should get an early way our in your opinion?

**Comment by OlegHahm** [comment]
I didn't introduce this early way out.

**Comment by authmillenon** [comment]
With this PR you do... I need to look into my notes, why I introduced the release in the *error case*.

**Comment by OlegHahm** [comment]
If there's no handler, because the module is not active, then it's an error case for me, too.

**Comment by authmillenon** [comment]
But there might be a handler registered to (`NG_NETTYPE_IPV6`, `NG_PROTNUM_IPV6_EXT_HOPOPT`) in netreg e.g. The error case here is btw that there is [no space in pktbuf](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_ipv6/ext/ng_ipv6_ext.c#L60) which makes a hard abort pretty reasonable.

**Comment by authmillenon** [comment]
> But there might be a handler registered to (`NG_NETTYPE_IPV6`, `NG_PROTNUM_IPV6_EXT_HOPOPT`) in netreg e.g.

This case is handled l100ff btw

**Comment by authmillenon** [comment]
All I'm asking is to change this fix to

```diff
diff --git a/sys/net/network_layer/ng_ipv6/ng_ipv6.c b/sys/net/network_layer/ng_ipv6/ng_ipv6.c
index 0479abd..31a62d4 100644
--- a/sys/net/network_layer/ng_ipv6/ng_ipv6.c
+++ b/sys/net/network_layer/ng_ipv6/ng_ipv6.c
@@ -78,6 +78,7 @@ void ng_ipv6_demux(kernel_pid_t iface, ng_pktsnip_t *pkt, uint8_t nh)
         case NG_PROTNUM_ICMPV6:
             ng_icmpv6_demux(iface, pkt);
             break;
+#ifdef MODULE_NG_IPV6_EXT
         case NG_PROTNUM_IPV6_EXT_HOPOPT:
         case NG_PROTNUM_IPV6_EXT_DST:
         case NG_PROTNUM_IPV6_EXT_RH:
@@ -90,6 +91,7 @@ void ng_ipv6_demux(kernel_pid_t iface, ng_pktsnip_t *pkt, uint8_t nh)
                 ng_pktbuf_release(pkt);
                 return;
             }
+#endif /* MODULE_NG_IPV6_EXT */
         case NG_PROTNUM_IPV6:
             _decapsulate(pkt);
             break;
```

**Comment by OlegHahm** [comment]
Ok, will do.

**Comment by OlegHahm** [comment]
done

**Comment by authmillenon** [comment]
ACK.

**Comment by authmillenon** [comment]
Please squash

**Comment by OlegHahm** [comment]
squashed

**Comment by authmillenon** [comment]
and go

**Pull request merged**
