### PR TITLE
minor text improvements to MAINTAINING.md

### PR DESCRIPTION
**Pull request by jasdeepgill**
### Contribution description
Line 3 and 4:

Moved "technical and non-technical" in front of guidelines. As the guild lines are what is technical or non-technical. The original is confusing as "including technical
and non-technical." doesn't mean anything and the reader does not know what is it is referring to. 

The rest of the changes are simple grammar and readability improvements.

### CODE REVIEW

**Comment by jasdeepgill** [comment]
Change file per review

**Comment by miri64** [comment]
Ping @aabadie?

**Comment by fjmolinas** [comment]
This should be easy to address with a simple rebase...

**Review by OlegHahm — APPROVED** [review]

**Comment by OlegHahm** [comment]
@aabadie, ping!

**Review by aabadie — APPROVED** [review]

**Pull request merged**
