### PR TITLE
.gitignore: Ignore archives

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Once merged, common archives types will be ignored to prevent them accidentally being commited. The two archives that where purposely added to the tests are explicitly white-listed.

### Testing procedure

1. Try adding [42.zip](http://www.fefe.de/antivirus/42.zip). It should not work without force
2. Try adding changes to `tests/pkg_fatfs/riot_fatfs_disk.tar.gz` or `tests/pkg_fatfs_vfs/riot_fatfs_disk.tar.gz`, it should work

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/12406, https://github.com/RIOT-OS/RIOT/pull/12720

### CODE REVIEW

**Comment by kaspar030** [comment]
Why?

There are legitimate archives. This PR even adds exceptions. I don't want to live through the confusion when someone wants to add another archive.

I propose being more careful next time and move on.

**Comment by maribu** [comment]
And how about only ignoring them in examples?

**Comment by kaspar030** [comment]
> And how about only ignoring them in examples?

while we're at it, let's ignore .docx. And maybe xml, but not for doc/. And maybe ignore all .mp3 and .mp4. If someone needs them for a multimedia demo, they can add another exception to .gitignore.

More seriously, are you using git in the shell? Don't do `git add` on wildcards / folders without double-checks. .gitignore won't help otherwise.

And reviewers, maybe take a look at the diff.

**Comment by maribu** [comment]
> Don't do `git add` on wildcards / folders without double-checks.

:+1:

**Pull request closed without merging**
