### PR TITLE
gh-actions: bucket test-on-iotlab artifacts to one ZIP

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Don't know if this it was intended to separate the results in separate ZIP files, but I find it annoying that I have to download each report separately (then I can also just click through the web output... :-P). This PR moves everything in one big ZIP, like I do for the release-tests.

### Testing procedure
I can start an action on my repo if it helps.

### Issues/PRs references
None

### CODE REVIEW

**Comment by aabadie** [comment]
> Don't know if this it was intended to separate the results in separate ZIP files

Yes it was on purpose: one job per board, one artifact per board. I think it's a matter of taste.

**Comment by aabadie** [comment]
Also note that with this PR, a zip will be uploaded each time a board job completes and containing the results of previous boards (if there are any). In fact, I'm not sure that this is actually working.

**Comment by miri64** [comment]
> Also note that with this PR, a zip will be uploaded each time a board job completes and containing the results of previous boards (if there are any). In fact, I'm not sure that this is actually working.

Are you sure? With the release tests I also upload multiple times

https://github.com/RIOT-OS/RIOT/blob/7e411ec1b08c98cbbc556ac5313871b754b51125/.github/workflows/release-test.yml#L120-L124
https://github.com/RIOT-OS/RIOT/blob/7e411ec1b08c98cbbc556ac5313871b754b51125/.github/workflows/release-test.yml#L204-L208

But as you can see [in the resulting runs](https://github.com/RIOT-OS/RIOT/actions?query=workflow%3Arelease-tests) all artifacts are there.

> I think it's a matter of taste.

As I tried to express in OP: It is also a matter of convenience. I mostly use the artifact logs to easier search around in them (which is a bit trickier and sometimes next to impossible in the web logs). Downloading the logs for each board for that is a major inconvenience, but just downloading one big ZIP is less so.

**Comment by miri64** [comment]
I started [a test run](https://github.com/miri64/RIOT/actions/runs/205929489). That should clear up if they are put in one file or not.

**Comment by miri64** [comment]
> I started [a test run](https://github.com/miri64/RIOT/actions/runs/205929489). That should clear up if they are put in one file or not.

As I expected, everything is in one big file.

**Comment by miri64** [comment]
(If you call 2.3 MB big ;-))

**Comment by aabadie** [comment]
Indeed, it works. But it's not clear to how it works.
From [the upload artifact documentation](https://github.com/actions/upload-artifact#uploading-to-the-same-artifact), I see that `Warning: Be careful when uploading to the same artifact via multiple jobs as artifacts may become corrupted`. This is exactly what you are trying to do here.

For each board, there's one job and in each job, there's one upload of the artifact at the end.

And the upload-artifact documentation is even discouraging the use of the same artifact names for jobs in a matrix:
```
In the above example, four jobs will upload four different files to the same artifact but there will only be one file available when my-artifact is downloaded. Each job overwrites what was previously uploaded. To ensure that jobs don't overwrite existing artifacts, use a different name per job.
```

**Comment by miri64** [comment]
The examples given are a bit different than the case at hand, since the script generates distinct files (and thus distinct artifacts) for each board. The only file we could be worried about is `toolchain`, as it is indeed the only file appearing in each job. However, if done right, its content _should_ be the same, but if we want to be save, we could rename it just before upload to `toolchain_<board>`.

**Comment by aabadie** [comment]
As I understand the warning, the problem is not with files generated by our jobs but the archive itself. Several jobs will write at the same time in the same archive and the upload-artifact action has a concurrency issue there which would result in a corrupted zip file.

**Comment by miri64** [comment]
> As I understand the warning, the problem is not with files generated by our jobs but the archive itself. Several jobs ~will~could write at the same time in the same archive and because the upload-artifact action has a concurrency issue there, this would result in a corrupted zip file.

So how do we proceed? If we close this PR because of that, what does this mean for `release-tests` where I copy to the same ZIP?

**Comment by miri64** [comment]
I am not interested in this topic anymore

**Pull request closed without merging**
