### PR TITLE
cpu/efm32/gpio: use gpio_irq feature

### PR DESCRIPTION
**Pull request by haukepetersen**
See #9992

### CODE REVIEW

**Comment by bergzand** [comment]
Number #10000! :tada:

**Comment by kaspar030** [comment]
> Number #10000! tada

Happy 10k everyone!!

**Comment by haukepetersen** [comment]
thanks for forcing me to open separate PRs for every CPU - that helped with the numbers :-)

**Comment by haukepetersen** [comment]
@basilfx would you mind to give this a quick review/test?! Thanks

**Comment by basilfx** [comment]
I have limited time due to my new house, so maybe @kYc0o can do this one?

**Comment by haukepetersen** [comment]
of course, I'll find someone else. Have fun braking the house :-)

**Comment by haukepetersen** [comment]
Murdock pointed out one more issue (unused `_pin_mask()`) function in case `periph_gpio_irq` was not used. Fixed and squashed.

**Comment by kaspar030** [comment]
Happy 10k again ;)

**Pull request merged**
