### PR TITLE
pkg: (git): move pkgdir to $BINDIRBASE/pkg/$BOARD/$PKG_NAME, do proper clean

### LINKED ISSUE #5172: make clean is deleting package code
It used to be `distclean` that did that, while `clean` just removed binaries and other files not in any commit.

### PR DESCRIPTION
**Pull request by kaspar030**
Fixes #5172 for git packages.

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK and go, when murdock is happy.

**Comment by authmillenon** [comment]
Uh, it shows itself as murdock now :-)

**Comment by kaspar030** [comment]
> Uh, it shows itself as murdock now :-)

He finally solved his identity crisis! :)

**Comment by kaspar030** [comment]
forgot to fix the include paths...

**Comment by kaspar030** [comment]
Problem now is that "make clean" cleans all the board files, leaving a board's checked-out package source in place. "make distclean" cleans the whole bin/folder. No way to clean all recreateble files for one board...

**Comment by OlegHahm** [comment]
Why not `$BINDIRBASE/$BOARD/pkg/$PKG_NAME` as for modules?

**Comment by kaspar030** [comment]
> Why not $BINDIRBASE/$BOARD/pkg/$PKG_NAME as for modules?

Because "make clean" in an application's directory removes $BINDIRBASE/$BOARD, making any attempt to keep the pkgs' sources futile.

**Comment by OlegHahm** [comment]
Ah, makes sense.

**Comment by kaspar030** [comment]
@authmillenon I've adapted tlsf to the new directory scheme. Could you take a quick look and re-ack?

**Comment by authmillenon** [comment]
Re-ACK and go.

**Pull request merged**
