### PR TITLE
drivers/at24cxxx: Add M24C01 device and enhance documentation

### PR DESCRIPTION
**Pull request by crasbe**
### Contribution description

This PR adds the ST M24C01 I2C EEPROM to the predefined constants in the at24cxxx driver. Since it is the first non-Atmel/Microchip device, the documentation has been enhanced to make clear the driver is not exclusively for devices from Atmel/Microchip.

Furthermore, documentation has been added to make using the driver easier (via pseudomodules) and a small example how to initialize the EEPROM device with the given data structures.

### Testing procedure

The code has been tested with the Nordic nRF52840-DK and an ST M24C01WP EEPROM as shown in Issue #20202 with the example code and Makefile given in this issue.

The expected impact on other parts of RIOT is low, since only features have been added which concentrate on the at24cxxx driver which do not affect other parts.
A global driver pseudomodule with the filter "m24c%" has been added similar to the existing "at24c%" pseudomodule to give access to all ST devices that will potentially be added in the future. Currently this filter does not cause any namespace conflicts.

### Issues/PRs references

This PR fixes Issue #20202. Please do not merge until the question about the documentation grouping has been answered!

### CODE REVIEW

**Comment by crasbe** [comment]
I screwed this up. Sorry.

**Comment by crasbe** [comment]
Okay. So I learned about the importance of using different branch names when working with PRs today. I'm sorry that I unneccesarily pinged four people with this. The reviewers which are now added are not the code owners I think.

I fixed it now and the changed files and commits reflect the PR I want to make.

Again, I am very sorry for causing any trouble.

**Review by benpicco — APPROVED** [review]
Don't worry, GitHub seems to have sorted it out already.

The additions looks simple enough, thank you for taking care of also enhancing the doc!

**Comment by crasbe** [comment]
I just noticed that the at24cxxx module actually has a test file which can be run: https://github.com/RIOT-OS/RIOT/tree/master/tests/drivers/at24cxxx

I'll run the test and post the results first thing tomorrow.

**Comment by crasbe** [comment]
All tests compiled and ran successfully :)

I'll open a separate issue about the documentation grouping separate from this PR, so from my side it is go for merge.

```
chris@ThinkPias:~/flashdev-riot/RIOT/tests/drivers/at24cxxx$ AT24CXXX_DEV=m24c01 BOARD=nrf52dk make -j10 hexfile
"make" -C /home/chris/flashdev-riot/RIOT/pkg/cmsis/ 
"make" -C /home/chris/flashdev-riot/RIOT/boards/common/init
"make" -C /home/chris/flashdev-riot/RIOT/boards/nrf52dk
"make" -C /home/chris/flashdev-riot/RIOT/core
"make" -C /home/chris/flashdev-riot/RIOT/core/lib
"make" -C /home/chris/flashdev-riot/RIOT/cpu/nrf52
"make" -C /home/chris/flashdev-riot/RIOT/drivers
"make" -C /home/chris/flashdev-riot/RIOT/sys
"make" -C /home/chris/flashdev-riot/RIOT/boards/common/nrf52xxxdk
"make" -C /home/chris/flashdev-riot/RIOT/drivers/at24cxxx
"make" -C /home/chris/flashdev-riot/RIOT/drivers/periph_common
"make" -C /home/chris/flashdev-riot/RIOT/sys/auto_init
"make" -C /home/chris/flashdev-riot/RIOT/sys/div
"make" -C /home/chris/flashdev-riot/RIOT/cpu/cortexm_common
"make" -C /home/chris/flashdev-riot/RIOT/cpu/nrf52/periph
"make" -C /home/chris/flashdev-riot/RIOT/cpu/nrf52/vectors
"make" -C /home/chris/flashdev-riot/RIOT/sys/frac
"make" -C /home/chris/flashdev-riot/RIOT/sys/libc
"make" -C /home/chris/flashdev-riot/RIOT/sys/malloc_thread_safe
"make" -C /home/chris/flashdev-riot/RIOT/sys/newlib_syscalls_default
"make" -C /home/chris/flashdev-riot/RIOT/sys/preprocessor
"make" -C /home/chris/flashdev-riot/RIOT/sys/stdio
"make" -C /home/chris/flashdev-riot/RIOT/cpu/cortexm_common/periph
"make" -C /home/chris/flashdev-riot/RIOT/cpu/nrf5x_common
"make" -C /home/chris/flashdev-riot/RIOT/cpu/nrf5x_common/periph
"make" -C /home/chris/flashdev-riot/RIOT/sys/stdio_uart
"make" -C /home/chris/flashdev-riot/RIOT/sys/ztimer     

chris@ThinkPias:~/flashdev-riot/RIOT/tests/drivers/at24cxxx$ nrfjprog --recover && nrfjprog --chiperase --verify --program bin/nrf52dk/tests_at24cxxx.hex && nrfjprog --pinresetenable &
& nrfjprog --pinreset
Recovering device. This operation might take 30s.
Erasing user code and UICR flash areas.
Writing image to disable ap protect.
[ #################### ]   0.047s | Erase file - Done erasing                                                          
[ #################### ]   0.284s | Program file - Done programming                                                    
[ #################### ]   0.104s | Verify file - Done verifying                                                       
Enabling pin reset.
Applying pin reset.

chris@ThinkPias:~/flashdev-riot/RIOT/tests/drivers/at24cxxx$ make term
/home/chris/flashdev-riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"  
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2024-04-17 10:33:41,653 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2024-04-17 10:33:45,950 # main(): This is RIOT! (Version: 2024.04-devel-656-g251b52)
2024-04-17 10:33:45,954 # Starting tests for module at24cxxx
2024-04-17 10:33:45,955 # EEPROM size: 128 byte
2024-04-17 10:33:45,956 # Page size  : 16 byte
2024-04-17 10:33:45,959 # [SUCCESS] at24cxxx_init
2024-04-17 10:33:45,962 # [SUCCESS] at24cxxx_write_byte
2024-04-17 10:33:45,965 # [SUCCESS] at24cxxx_read_byte
2024-04-17 10:33:45,967 # [SUCCESS] write_byte/read_byte
2024-04-17 10:33:45,973 # [SUCCESS] at24cxxx_write
2024-04-17 10:33:45,977 # [SUCCESS] at24cxxx_read
2024-04-17 10:33:45,978 # [SUCCESS] write/read
2024-04-17 10:33:45,985 # [SUCCESS] at24cxxx_set
2024-04-17 10:33:45,989 # [SUCCESS] set/read
2024-04-17 10:33:45,992 # Finished tests for module at24cxxx
/exit
2024-04-17 10:33:50,579 # Exiting Pyterm
```

**Comment by maribu** [comment]
Thx for the PR!

If I'm correct this is your first PR you got upstream in this repo, correct?

If so: Congratulations 🎉 and welcome to the community!

**Comment by crasbe** [comment]
@maribu Actually it is my third PR that got merged (#20439 and #20440 were the first two). But thank you nevertheless :)

We have a project that uses RIOT, so it's certainly not going to be the last one (in fact there is still a big one in progress right now and I have enough ideas for further PRs).

**Pull request merged**
