### PR TITLE
Use `__restrict` instead of `restrict`

### PR DESCRIPTION
**Pull request by cgundogan**
Use `__restrict` instead of `restrict`, because c++ does not include the keyword `restrict`.

Also see #2401

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Apparently you missed nothing in master, but I guess we should add a test for `\<restrict\>` in code to prevent future creeps.

**Comment by LudwigOrtmann** [comment]
.. and probably we should start writing down these kind of things.. they keep resurfacing.

**Comment by LudwigOrtmann** [comment]
.. and so I did: https://github.com/RIOT-OS/RIOT/wiki/Coding-conventions#c-compatability

**Comment by Kijewski** [comment]
Please don't change the .c files, only the .h files.

**Comment by LudwigOrtmann** [comment]
@Kijewski thanks for pointing that out.

**Comment by cgundogan** [comment]
@Kijewski I kicked out the changes to *.c files. Let's wait for travis now.

**Comment by LudwigOrtmann** [comment]
Everyone is happy, go.

**Pull request merged**
