### PR TITLE
cpu/efm32: fix DAC configuration

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

The EFM32 MCU allows the reference voltage to be configured per DAC device, not per DAC channel. Also, the DAC reference voltage was defined in the configuration but not used anywhere.

At the moment we have only defined one board (`stwstk6220a`) that uses the DAC, so changing the configuration interface shouldn't be critical.

### Testing procedure

`tests/periph/dac` should still work for the `stwstk6220a`
```
BOARD=slwstk6220a make -j8 -C tests/periph/dac flash
```
I don't have a `stwstk6220a` board (EFM32 Series 0) so that I can't test it. I could only test it for the `sltb009a` board (EFM32 Series 1) with the change for VDAC in PR #19887.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
Looks like `.ref` wasn't even used before

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel

**Comment by benpicco** [comment]
looks like `stk3700` also needs an update

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Hm, in C++ the order of struct members in static initializers matters :worried: 
```
../../boards/stk3700/include/periph_conf.h:90:1: error: designator order for field 'dac_conf_t::ref' does not match declaration order in 'const dac_conf_t'
   90 | };
      | ^

I changed the order for all boards and squashed it directly.

**Comment by gschorcht** [comment]
It is really annoying that CI compilations fail 90% of the time because of the `tests/net/gcoap_server`.

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks.

**Pull request merged**
