### PR TITLE
gh-actions: release-tests: properly configure GH token for sudo

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Another follow-up on https://github.com/RIOT-OS/RIOT/pull/15637. `pytest` reads the token from the `HOME` directory, which with `sudo` is `root`, so there is none (since it is in the login user's `HOME`), so it can't comment in the tracking issue for `sudo` the tasks.

### Testing procedure
I started a run in https://github.com/miri64/RIOT/actions/runs/766574330. Murdock should comment from there.

### Issues/PRs references
Follow-up on https://github.com/RIOT-OS/RIOT/pull/15637

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by miri64** [comment]
For reference: it works: https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823118843

**Comment by miri64** [comment]
To make sure the IoT-LAB creds tests are also still commented, I unset 4.3 in OP

**Comment by miri64** [comment]
> To make sure the IoT-LAB creds tests are also still commented, I unset 4.3 in [RIOT-OS/Release-Specs#213](https://github.com/RIOT-OS/Release-Specs/issues/213) OP

Does work: https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823125519

**Comment by kaspar030** [comment]
Then let's go!

**Comment by miri64** [comment]
Backport provided in #16356

**Pull request merged**
