### PR TITLE
dist: make: iotlab: specify exp id in iotlab-term

### PR DESCRIPTION
**Pull request by cgundogan**
Specify the correct experiment id when starting the `serial_aggregator`.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Huh? I thought we already had this. Untested ACK.

**Comment by cgundogan** [comment]
@OlegHahm what's your opinion on the second commit? Merging both calls to `serial_aggregator` may be the way to go ..

**Comment by cgundogan** [comment]
It doesn't seem to hurt `make` when `$(NODES_PARAM_BASE)` is empty.

**Comment by OlegHahm** [comment]
Have you tested?

**Comment by cgundogan** [comment]
Yes, with and without `IOTLAB_PHY_NODES`

**Comment by cgundogan** [comment]
rebased and tested again w/ and w/o `IOTLAB_PHY_NODES`. Works perfectly.

**Comment by PeterKietzmann** [comment]
I wanted to test this PR but obviously the tested currently has the (know) starting problems. Are you aware of a site that still works or a workaround to run experiments?

**Comment by cgundogan** [comment]
I tested this an hour ago on the grenoble site, but I also noticed that the scheduler of the testbed was somehow misbehaving. Let's wait another hour and if nothing changes we should report that to the iotlab mailing list.

**Comment by PeterKietzmann** [comment]
Testbed works again. PR as well :-). ACK and go

**Pull request merged**
