### PR TITLE
CPU: adapt SAM3 to sam_common

### PR DESCRIPTION
**Pull request by smlng**
based on (and includes) #7621

### CODE REVIEW

**Comment by smlng** [comment]
@jonajames would be great if you can test this, thanks!

**Comment by haukepetersen** [comment]
(copied from #7632)

I am not so sure I like it too much. My main issue with this PR is to include a huge list of vendor header files for CPUs that are not used in RIOT (I missed to object when the headers for the sam0 MCUs were included)... The default way was and is to only include the vendor headers for the MCUs that are actually used...

**Comment by smlng** [comment]
@haukepetersen so your comment is actually meant for #7621 😉 Where I already stated, that I'm working on a port for SAM4S MCUs, because I have a board that has one on it. That's why I only included the sam3 and sam4 specific headers from the CMSIS SAM headers <- there are way more, but as RIOT has support for SAM3 (already) and I want to port SAM4, I only included those.

**Comment by haukepetersen** [comment]
yes, you are right. A very confusing morning indeed :-)

> That's why I only included the sam3 and sam4 specific headers from the CMSIS SAM headers <- there are way more

True. Now looking at the actual line counts, the specific headers (e.g. `sam3x8c.h`, `sam3x8e.h`, `sam3x8h.h`, etc) only take a minor part of the overall amount of lines, so maybe my fear of overloading the source tree with unused header information is overrated... In the end it seems valid to include the complete path from the ASF than to manually filter through it. I think you just changed my mind and I can happily live with the proposed changes.

**Comment by smlng** [comment]
rebased

**Comment by smlng** [comment]
@haukepetersen as you have been: thanks for testing 😄 I forgot to mention that I also tested successfully with Arduino-due.

**Comment by haukepetersen** [comment]
Then it seems we made sure it is really working... Better double than nothing :-)

**Pull request merged**
