### PR TITLE
gnrc_ipv6: use gnrc_pktbuf_merge() to loopback packet

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
With `gnrc_pktbuf_merge()` introduced in #10447 we can remove some code duplication when it comes to looping back a packet.

### Testing procedure
Pinging an address of the node (or the loopback address `::1`) should still work as before.

### Issues/PRs references
Follow-up on #10447.

### CODE REVIEW

**Comment by miri64** [comment]
Real easy merge here.

**Comment by jia200x** [comment]
tested on native. Ping still works :)

**Comment by jia200x** [comment]
please squash :)

**Comment by miri64** [comment]
Squashed.

**Comment by jia200x** [comment]
yes!

**Pull request merged**
