### PR TITLE
boards: add Silabs EFM32 Giant Gecko GG11 Starter Kit

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

The PR adds the support for the EFM32GG11B family and the Silabs EFM32 Giant Gecko GG11 Starter Kit board.

The Silabs EFM32 Giant Gecko GG11 has the following on-board features:

- EFM32GG11B MCU with 2 MB flash and 512 kB RAM
- J-Link USB debugger
- 176x176 RGB LCD (not supported)
- 2 user buttons, 2 user RGB LEDs and a touch slider
- Si7021 Relative Humidity and Temperature Sensor
- Si7210 Hall-Effect Sensor (not supported)
- USB OTG interface (Device mode supported)
- 32 MByte Quad-SPI Flash (not supported yet)
- SD card slot (not supported yet, follow-up PR based on PR #19760)
- RJ-45 Ethernet (not supported)
- Dual microphones (not supported)

### Testing procedure

Basic tests should work.

### Issues/PRs references

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
looks good to me

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
I had to add the definition of the `CORETEMP_ADC` macro to fix the compilation error in Murdock https://github.com/RIOT-OS/RIOT/blob/f4b1e1e5a7d01ee2061b808448d87b53918160fa/boards/slstk3701a/include/board.h#L119-L126
Because it was a straight forward fix I squashed it directly.

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Grrr, the `Kconfig` file created with `EFM2RIOT` for the EFM32GG11B family was missing the module definition `MODULE_CPU_EFM32GG11B` for the family. I added it and squashed directly https://github.com/RIOT-OS/RIOT/blob/77769905cdefd93a8c20a2b14199b13af66a42cd/cpu/efm32/families/efm32gg11b/Kconfig#L15-L21

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Hm, I have no idea why the unitest for the `native` board fails with LLVM in CI. It works for me locally.
<details>

```
make: Verzeichnis „tests/unittests“ wird betreten
Due to limitations in the gcoap API it is currently not possible to use a dual stack setup
r
Due to limitations in the gcoap API it is currently not possible to use a dual stack setup
tests/unittests/bin/native/tests_unittests.elf /dev/ttyACM0 
RIOT native interrupts/signals initialized.
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2023.10-devel-294-gf26d0-drivers/lcd_work)
Help: Press s to start test, r to print it is ready
READY
s
START
.......................==1312750==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
...............................................................................................................................................................................................................==1312750==WARNING: ASan is ignoring requested __asan_handle_no_return: stack type: default top: 0xffdf6000; bottom 0x0824e000; size: 0xf7ba8000 (-138772480)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
OK (1158 tests)

make: Verzeichnis „tests/unittests“ wird verlassen
```

</details>

**Comment by benpicco** [comment]
I think that’s just one of those sporadic failures

bors merge

**Comment by gschorcht** [comment]
> I think that’s just one of those sporadic failures

Strange, it failed again, the third time :thinking:

**Comment by benpicco** [comment]
bors merge

**Comment by miri64** [comment]
May I shunt in #19927 and #19933? #19933 still needs to pass the Murdock CI, but this would give us ample time to shunt.

**Comment by benpicco** [comment]
Sure go ahead

**Comment by miri64** [comment]
bors cancel

**Comment by miri64** [comment]
bors merge

**Comment by miri64** [comment]
bors cancel

**Comment by miri64** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks

**Pull request merged**
