### PR TITLE
boards/hamilton: Add minimal doc

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

The doc of the board is still suboptimal, but at least an image to identify what board this is and a link to further information is a starting point.

### Testing procedure

The static tests will do.

### Issues/PRs references

None.

### CODE REVIEW

**Comment by aabadie** [comment]
Static tests are failing because of undocumented things :)

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
looks like a rebase is needed here

**Comment by kaspar030** [comment]
bors retry

**Pull request merged**
