### PR TITLE
makefiles/vars.inc.mk: update USE_PROGRAMMER_WRAPPER_SCRIPT comment

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Documentation change was missed in #16371. This PR is fixing that.

### Testing procedure

Just read and verify that the comment is in sync with the new behavior.

https://github.com/RIOT-OS/RIOT/blob/0493292ef37534732e9504333d8fd08c0e895b17/makefiles/tools/programmer.inc.mk#L8-L9

### Issues/PRs references

#16371

### CODE REVIEW

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by fjmolinas** [comment]
Do you mind sneaking in the comment in https://github.com/RIOT-OS/RIOT/pull/16371/files/a0b83f8195c4cc0a87f5bbf605e3d88ad3defe09#r621214060?

**Comment by aabadie** [comment]
> Do you mind sneaking in the comment

Added

**Comment by fjmolinas** [comment]
> > Do you mind sneaking in the comment
> 
> Added

Thanks!

**Comment by fjmolinas** [comment]
Feel free to hit the button if you see it green before me!

**Pull request merged**
