### PR TITLE
spelling: s/initialisation/initialization/

### PR DESCRIPTION
**Pull request by aabadie**
Follow-up of #7565. Just thought of that.

### CODE REVIEW

**Comment by smlng** [comment]
> we should give some guidelines, if we prefer US or UK spelling

IMHO both is proper English and should we really (really?) bother with (or need to care about) that? I mean, do we want to end up correcting developers/users who prefer British over American English or vice-versa over and over?

Btw. as RIOT originates from Europe maybe we should embrace British English 😉

**Comment by miri64** [comment]
> IMHO both is proper English and should we really (really?) bother with (or need to care about) that? I mean, do we want to end up correcting developers/users who prefer British over American English or vice-versa over and over?

Agreed.

> Btw. as RIOT originates from Europe maybe we should embrace British English :wink:

I'm don't have any particular preference.

**Comment by aabadie** [comment]
Initialize is recommended by [Oxford English Dictionnary](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#-ise.2C_-ize_.28-isation.2C_-ization.29). It seems there's no consensus within the UK.

**Comment by kYc0o** [comment]
I think the problem is not that now you change it, since in upcoming PRs anyways people will spell it as they want (me for instance I'll continue to write "initialisation").

I'm not against having merged this but it won't change anything in the future, and both spellings are correct.

**Comment by OlegHahm** [comment]
> Btw. as RIOT originates from Europe maybe we should embrace British English

Well, not so sure this is a valid argument any more. ;-)

**Comment by smlng** [comment]
@OlegHahm referring to #brexit, I guess? Then, I wouldn't deem recent political decisions higher than long lasting historic (and obvious geographic) ties/bonds 😉 Plus, (IMHO) they have better 🍻 than the US.

**Pull request merged**
