### PR TITLE
cpu/cc13x2: rename cpu to cc26x2_cc13x2.

### PR DESCRIPTION
**Pull request by jeandudey**
### Contribution description

The CC26x2 and CC13x2 share the same register definitions, and both are
treated equally in the TI's technical reference manual. [1]

- To avoid confusions in the future I renamed it to `cc26x2_cc13x2`.
- Documentation was updated.
- The `cc1312-launchpad` board that uses the `cc13x2` MCU was updated.
- The `cc1352-launchpad` board that uses the `cc13x2` MCU was updated.

[1]: https://www.ti.com/lit/ug/swcu185d/swcu185d.pdf

### Testing procedure

On any example you can build and flash it with:

```bash
BOARD=cc1352-launchpad make flash
```

### CODE REVIEW

**Comment by benpicco** [comment]
How does this compare to `cpu/cc26xx_cc13xx`?

**Comment by jeandudey** [comment]
`cpu/cc26xx_cc13xx` is the common code for all the processors of the family, it means, it shares code with those MCUs:

- `cc26x0`: These MCUs are 2.4 GHz only.
- `cc13x0`: These ones are Sub-GHz and 2.4 GHz, however, the CC1310 is Sub-GHz only and the CC1350 is both Sub-GHz and 2.4 GHz (the two can be used at the same time).
- `cc13x2` and `cc26x2`: differentiates like the `cc26x0/cc13x0`, but they share the same register definitions, addresses, and a radio implemented for one of those devices should work for the `cc13x2` and `cc26x2`

**Comment by benpicco** [comment]
Uh, looks something changed in the meantime - I should have triggered Murdock again before merging this - now [CI builds are failing](https://ci.riot-os.org/) for this platform 😕

**Comment by jeandudey** [comment]
@benpicco the Makefile.dep was added and didn't get moved

**Comment by jeandudey** [comment]
@benpicco should've fixed on #13281

**Comment by benpicco** [comment]
You've been faster 😉 
I did find another leftover in `cc26xx_cc13xx_uart.h`.

**Pull request merged**
