### PR TITLE
buildsystem: add EXTERNAL_PKG_DIRS functionality

### LINKED ISSUE #15309: Packages outside RIOT tree
#### Description
It's not possible to make packages outside of RIOT's tree, the way it can be done for modules with `EXTERNAL_MODULE_DIRS`. I get:

    make[1]: *** /home/jdavid/sandboxes/UiO/wsn_riot/RIOT/pkg/arduino_sparkfun_bme280: No such file or directory.  Stop.

I added the package to our own tree `wsn_riot/pkg` but it looks for the package in RIOT's tree. Tried adding `EXTERNAL_MODULE_DIRS`, didn't find a way in the documentation.

We have to package many Arduino libraries for sensors and it would be easier to do if it was possible to package them out of RIOT's tree, as it's possible to do with sys modules and drivers. This would help others that need the same.

### Useful links

None. This concerns the RIOT build system.

### PR DESCRIPTION
**Pull request by NikLeberg**
### Contribution description
The current buildsystem only allows packages residing inside the RIOT tree. For modules this is handled differently, those can be added from external directories with the `EXTERNAL_MUDULE_DIRS` variable. With this pull request I add the same mechanism of a `EXTERNAL_PKG_DIRS` variable for packages outside of the RIOT tree. This mechanism can be used to separate RIOT and user supplied packages without cluttering the RIOT tree. Ultimately packages should be added to the RIOT upstream with a pull request. But with this mechanism one can develop more easily.

This is a draft. ~~My goal is to get early feedback.~~
@fjmolinas Provided some feedback (thanks!), which resulted in splitting of a part of these changes into pr #17551 that was sucessfully merged into master.

ToDo:
- [x] Documentation
- [x] Test
- [x] Kconfig

### Testing procedure
I've ran `make static-test` with success.
For precise test case similar to [tests/external_module_dirs](https://github.com/RIOT-OS/RIOT/blob/3c402d88a84feba03696429cf5a0358d2dd7e290/tests/external_module_dirs/README.md) ~~I'll need a bit of guidance.~~ I've managed to create a test based on `riotgen test --interactive` and the mentioned similar testcase.
~~Interested what the CI has to say about this...~~
In my own project [riot-tdd](https://github.com/NikLeberg/riot-tdd) I'm using this functionality with no problems.

### Issues/PRs references
resolves #15309
depends on pr #17551

### CODE REVIEW

**Comment by maribu** [comment]
From a quick look this looks very nice and consistent to how external modules are handled. Let's see if the CI likes this.

**Comment by benpicco** [comment]
looks like CI does not like this

**Review by fjmolinas — COMMENTED** [review]
Currently, EXTERNAL_MODULES are handled separately then internal MODULES. This PR takes a similar approach but is as well doing other things:

- replacing current package dependency inclusion
- forcing internal packages to directories matching module name

Those two need more testing and IMO would be better be handled in individual PR's. I think it would be best to first add this functionality without touching how internal packages are handled.

Other than that it would be good to be sure that this works with docker as well.

**Comment by NikLeberg** [comment]
I see. Thanks @benpicco and @fjmolinas for your comments.

I'll take a closer look and try to do it more "the EXTERNAL_MODULES - way". The two other things you mentioned @fjmolinas are not intended (replacing dependency inclusion and forcing directory name). Seems like I was lucky to not run into those problems with native and board esp8266.

Is there a way to run the checks / builds the CI / Murdock does locally?

**Comment by NikLeberg** [comment]
I'm not entirely happy with how I implemented it currently. I want to separate the make targets but also dont want to change too much like the first attempt.
But either way, I wanted to see how the CI likes this approach. (Seems like it does?)

I know that it currently builds the external packages multiple times (second time calls make, but it is already up to date).

@fjmolinas do you have any comments about this approach?

**Comment by fjmolinas** [comment]
Hi @NikLeberg I'm sorry for taking so long for getting back to you, some paper work and vacation got in the way. I took a second closer look at this. Regarding:

> replacing current package dependency inclusion
> forcing internal packages to directories matching module name

I now realize that I was wrong, this was already implicitly the case since rules where already doing something like `@for i in $(USEPKG) ; do "$(MAKE)" -C $(RIOTPKG)/$$i distclean ; done`.

But I still think it's better to split the change of using `PKG_PATHS` and adding the external package directory (which is a very nice feature).

What do you think of opening a PR that only does the `PKG_PATHS` change, I'll be more reactive this time around and we can quickly run tests for that. And once that one is merged we add the external pkg directory part.

**Comment by fjmolinas** [comment]
This one now needs a rebase!

**Comment by fjmolinas** [comment]
@leandrolanzieri how should we handle Kconfig for this one? Something like we did for EXTERNAL_MODULES?

**Comment by NikLeberg** [comment]
@fjmolinas I rebased and applied the relevant commits. Kconfig will fail in CI as it is not yet implemented, so to not waste Murdock time, could you remove the *CI: ready for build* label?
I'll work on this next week. Until then, is there a general overview of how Kconfig works?

**Comment by leandrolanzieri** [comment]
> @leandrolanzieri how should we handle Kconfig for this one? Something like we did for EXTERNAL_MODULES?

I think that approach worked pretty well, I don't see why not take it also for this.

**Comment by NikLeberg** [comment]
@fjmolinas I found a bit of time anyway and played around with Kconfig. It seems that you also were the one that implemented it for the external modules with pr #16053 perfect! :grinning:

The way the external modules are handled in Kconfig confuses me a bit. It uses the make variabe `EXTERNAL_MODULE_PATHS` that is only ever set in *dependency_resolution.inc.mk*. But that dependency resolution isn't run when Kconfig is enabled, so from where is this variable set?

Anyway with the lastest commit `cd tests/external_pkg_dirs && make TEST_KCONFIG=1` works without issues.
What are your thoughts about this?

**Comment by fjmolinas** [comment]
> The way the external modules are handled in Kconfig confuses me a bit. It uses the make variable EXTERNAL_MODULE_PATHS that is only ever set in dependency_resolution.inc.Mk. But that dependency resolution isn't run when Kconfig is enabled, so from where is this variable set?

I think you caught that the test case was insufficient then..., when I made the PR https://github.com/RIOT-OS/RIOT/pull/16053, https://github.com/RIOT-OS/RIOT/pull/16104 was not yet in, so that test case was not addressed... Thanks for the catch

> Anyway with the lastest commit cd tests/external_pkg_dirs && make TEST_KCONFIG=1 works without issues.
What are your thoughts about this?

Looks good I think, could you add a test case in `tests/kconfig` as well?

**Comment by fjmolinas** [comment]
> I think you caught that the test case was insufficient then..., when I made the PR #16053, #16104 was not yet in, so that test case was not addressed... Thanks for the catch

Although I think the original PR was only about configurations... not sure about dependencies

**Comment by fjmolinas** [comment]
Thanks for the catch @NikLeberg I opened https://github.com/RIOT-OS/RIOT/pull/17596 to fix, could you do something similar here in `tests/kconfig` for external packages? Thanks! Otherwise this one looks good!

**Comment by NikLeberg** [comment]
I extended `tests/kconfig`. As soon as pr #17596 is in master, I'll rebase and run the test. Without the mentioned pr, the test won't work (module includes will not be found).

**Comment by NikLeberg** [comment]
Rebased. Kconfig now works on my machine. @fjmolinas Feel free to re-add the CI labels, I think code wise its done.
I also added a bit of documentation. Does it look right?

**Comment by fjmolinas** [comment]
Look good! Lets see what the ci thinks!

**Comment by fjmolinas** [comment]
CI had some unrelated issues, re-scheduling and lets see

**Review by fjmolinas — APPROVED** [review]
All green here! Go! Thanks @NikLeberg!

**Pull request merged**
