### PR TITLE
can: use memarray for pkt and router allocation

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

Use memarray instead of gnrc_pktbuf for can dll pkt and can filters allocations.
This has the advantage of not pulling gnrc_pktbuf dependancy if isotp is not used and slightly reduce the size of some objects (do not need a snip pointer anymore).

### CODE REVIEW

**Comment by tcschmidt** [comment]
@miri64 comments?

**Comment by miri64** [comment]
Neither know anything about CAN or this implementation. So no.

**Comment by vincent-d** [comment]
I'd like at least a basic review, could someone provide one?

This PR simplify a bit the allocation process inside the CAN stack and reduce the dependency to gnrc if isotp is not used.

**Comment by kYc0o** [comment]
Maybe @OYTIS might help?

**Comment by smlng** [comment]
please rebase

**Comment by smlng** [comment]
also check and fix CI errors

**Comment by vincent-d** [comment]
rebased

**Comment by smlng** [comment]
please fix CI errors, i.e. cppcheck complains about 3 issues.

**Comment by vincent-d** [comment]
@smlng I fixed the issues and amended directly (it was minor remarks with function-style macro and cppcheck wrongly thinking a variable could be used uninitialized).

**Pull request merged**
