### PR TITLE
drivers: Replaced NETOPT_MAX_PACKET_SIZE by NETOPT_MAX_PDU_SIZE

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Replaced use of deprecated `NETOPT_MAX_PACKET_SIZE` by `NETOPT_MAX_PDU_SIZE` in `cc110x` and `nimble`.

### Testing procedure

Murdock and code review should do here.

### Issues/PRs references

`NETOPT_MAX_PACKET_SIZE` was deprecated in https://github.com/RIOT-OS/RIOT/pull/10905

### CODE REVIEW

**Comment by benpicco** [comment]
Since `NETOPT_MAX_PACKET_SIZE` is unused now, wouldn't it also make sense to remove it from `sys/include/net/netopt.h` ?

**Comment by maribu** [comment]
> Since `NETOPT_MAX_PACKET_SIZE` is unused now, wouldn't it also make sense to remove it from `sys/include/net/netopt.h` ?

@miri64: I think deprecating is done for three releases, right?

**Comment by maribu** [comment]
I feel confident that no re-run of Murdock is needed to confirm nothing is broken, as this is likely the most trivial PR ever merged.

**Comment by miri64** [comment]
Jepp, was thingking the same yesterday when commenting here https://github.com/RIOT-OS/RIOT/pull/12603#discussion_r340325045.

**Pull request merged**
