### PR TITLE
ng_netapi: centralize packet dispatchment for RCV and SND

### PR DESCRIPTION
**Pull request by authmillenon**
Basically every layer does the 

```C
    sendto = ng_netreg_lookup(type, demux_ctx);

    ng_pktbuf_hold(pkt, numof - 1);

    while (sendto) {
        ng_netapi_*(sendto->pid, cmd, pkt);
        ng_netreg_getnext(sendto);
    }
```

bit. So I thought: why not centralize this. This PR does this ;-)

### CODE REVIEW

**Comment by authmillenon** [comment]
IPv6 is excluded since dispatching is a little different there (always 1-to-1 with interfaces, `(pkt->type, NG_NETREG_DEMUX_CTX_ALL)` + `(NG_NETTYPE_IPV6, hdr->nh)` for send).

**Comment by authmillenon** [comment]
Rebased and added minor fix

**Comment by cgundogan** [comment]
Tested and works now. ACK and merge when travis agrees.

**Comment by PeterKietzmann** [comment]
You need to squash the "fixup!" commit

**Comment by authmillenon** [comment]
Squashed.

**Comment by PeterKietzmann** [comment]
@cgundogan ACKed. And go

**Pull request merged**
