### PR TITLE
dist/testbed-support: Add openmote board [backport 2023.10]

### PR DESCRIPTION
**Pull request by miri64**
# Backport of #19979

### Contribution description

As part of fixing the automated release specs test we will need support for another `cc2538` based board.  I was able to get the tests passing with adaption here and to the release specs.

### CODE REVIEW

**Review by aabadie — APPROVED** [review]
ACK

bors merge

**Comment by aabadie** [comment]
#19978 has to be backported first it seems

**Comment by miri64** [comment]
You might want to use https://github.com/RIOT-OS/RIOT/pull/19985 for that ;-)

**Comment by MrKevinWeiss** [comment]
bors merge

**Pull request merged**
