### PR TITLE
boards/stm32f030f4-demo: use picolibc to save ROM

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

STM32F030R4 only has 16k Flash, so use picolibc as done on other 16k flash boards to save some ROM.

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK. This should be low impact, as it only effects a single board. Hence, I see no issue with merging this during soft feature freeze.

I cannot test as I don't have the board. However, the `picolibc` support has been tested quite well, so no need to test this here again.

**Comment by benpicco** [comment]
I don't quite understand why the static test are failing.

**Comment by benpicco** [comment]
let's try a rebase

**Comment by aabadie** [comment]
All green, now!

**Pull request merged**
