### PR TITLE
dist/testbed-support: generate random nodes

### PR DESCRIPTION
**Pull request by cgundogan**
This script generates random nodes from the list of available nodes on the testbed.
The output is the resource id string format as described in `experiment-cli submit --help`

Examples:
```python
import imp
helper = imp.load_source("IOTLABHelper", "RIOT/dist/testbed-support/IOTLABHelper.py").IOTLABHelper()
# generates 20 random nodes from the grenoble site and m3 node type
helper.getRandomTestbedNodes(20)
# 15 random nodes from the paris site and m3 node type
helper.getRandomTestbedNodes(15, 'paris')
# 25 random nodes from the grenoble site and a8 node type
helper.getRandomTestbedNodes(25, 'grenoble', 'a8')
```

### CODE REVIEW

**Comment by phiros** [comment]
ACK -> merge after Travis is happy

**Comment by OlegHahm** [comment]
What's the purpose? Currently using `IOTLAB_NODES` one gets more or less random nodes, but ones that are usually within radio range. Getting completely random nodes scattered over the testbed doesn't make too much sense to me.

**Comment by cgundogan** [comment]
>Getting completely random nodes scattered over the testbed doesn't make too much sense to me.

Well for multi-hop scenarios it makes sense to have nodes scattered over the testbed. Actually, I was also unsure if this kind of script should be included into the riot base or not. However, retrieving a desired amount of random and evenly distributed nodes may be quite useful for automated testing, like the ones I plan to do for RPL, or in general multi-hop communication.
 In the future, this script can be extended by additional useful functions, like parsing the outputs of `ifconfig` or other shell commands, that must be used for information retrieval on the testbed.

>What's the purpose?

So the purpose is: extracting common functions that can be used by several automated test scripts.

**Comment by OlegHahm** [comment]
> Well for multi-hop scenarios it makes sense to have nodes scattered over the testbed. 

Of course, but if they are picked completely randomly, the chance of partitioning the testbed is high.

> However, retrieving a desired amount of random and evenly distributed nodes may be quite useful for automated testing,

Definitely. I have to confess that I haven't looked into the code itself: How do you make sure that they're evenly distributed?

**Comment by cgundogan** [comment]
>Definitely. I have to confess that I haven't looked into the code itself: How do you make sure that they're evenly distributed?

Well, as close to evenly distributed as I can get.. At first, all available node ids are retrieved (so everything that is not busy or *suspected*(?)). From this (sorted) list I simply pick `x` nodes in a random fashion.

**Comment by OlegHahm** [comment]
Hm, still leaves a high chance of partitioned network.

**Comment by cgundogan** [comment]
I don't think that its a *high chance*, because the ranges of the transceivers are fairly wide. But yes, given the fact that running experiments can occupy consecutive nodes may result in partitioned networks. But I don't think that this is a big problem if you are willing to run automated tests more than 1 time. And: the test can still yield a correct positive or negative outcome on one or more of these partitions. RPL, e.g. will still run, but may have shorter routes.

**Comment by authmillenon** [comment]
You probably should use the [https://en.m.wikipedia.org/wiki/Small-world_network](small world model) to generate your network. Erdös networks as you generate (according to your description) tend to be highly fragmented. 

PS: never would have guessed the statistical network analysis course would be so helpful ^^

**Comment by OlegHahm** [comment]
The problem is that we have little to no knowledge about edges that will exist in the graph.

**Comment by cgundogan** [comment]
@authmillenon this article was refreshing, thanks for the information (: However, because of the broadcast nature it will get pretty difficult to build such topologies as I do not know which node is included in the transceiver's range beforehand.

**Comment by authmillenon** [comment]
That's indeed a problem. I thought the radio range or reachability of the nodes could be gathered somehow. I guess it would be a nice feature of IoT-Lab to have a small-world network with minimal connectivity as a experiment type... Should I write a feature request for that?

**Comment by authmillenon** [comment]
But to return to the problem at hand: wouldn't it be possible to infere at least some degree of confidence of connectivity by the physical distance of the nodes? (this information exists AFAIK).

**Comment by authmillenon** [comment]
Meaning something like: 
* d <= 1m => 100% connectivity
* 1m < d <= 3m => 50% connectivity
* 3m < d => 0% connectivity 
Then you can maximize your small-world graph based on this estimated connectivity.

**Comment by cgundogan** [comment]
I still argue that the simple method of just picking random nodes out of the space of all available nodes is sufficient, because those nodes are already numbered consecutively (nodes with adjacent numbering are also adjacent in their physical location, apart from very few corner cases)

**Comment by authmillenon** [comment]
Just to make it easier on the users it would be good - even for your method - und to at least check the connectivity in that way, since there *are* those corner cases.

**Comment by cgundogan** [comment]
I don't think that this PR is necessary anymore. I added more features to the helper script in the release spec tests.  @OlegHahm I will close this PR if you do not object

**Comment by OlegHahm** [comment]
I don't.

**Pull request closed without merging**
