### PR TITLE
examples: rename ng_networking to gnrc_networking

### PR DESCRIPTION
**Pull request by authmillenon**
Related to #3638.

### CODE REVIEW

**Comment by OlegHahm** [comment]
>  Kijewski added the PR-award-nominee label a minute ago

:wink:

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
Fixed whitespace errors in README and squashed.

**Comment by authmillenon** [comment]
Travis is happy, so GO. :-)

**Pull request merged**
