### PR TITLE
drivers/periph_timer: add periph_timer_freq feature

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

The optional feature allows to query the frequency a timer is actually running at. This is especially useful when the MCU is running of an integrated in-silicon RC oscillator, which may run at an actual frequency that differs a lot from the nominal frequency.

### Testing procedure

Some PRs to add this feature will be added soonish. The test app has been extended to print the actual frequency.

### Issues/PRs references

None

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Would you mind adding a single implementation so I can test it.  Other than that it makes sense!

**Comment by maribu** [comment]
> Would you mind adding a single implementation so I can test it. Other than that it makes sense!

Did so now for the fe310. Sadly, that is a pretty boring timer :-/

**Comment by maribu** [comment]
I'll also squash the fixup that adds a missing `")"` in message printed in the test.

**Comment by maribu** [comment]
Let's put this on a hold. With https://github.com/RIOT-OS/RIOT/pull/16349 finally on its way in, I'm not sure this is a good idea anymore.

With https://github.com/RIOT-OS/RIOT/pull/16349 one can just query prior to `timer_init()` what frequencies are supported. If one picks one of the actually supported frequencies, one can expect that the timer is actually running at the requested frequency.

I do agree that this API can be easier to use. But as this would need to be implemented for each and every peripheral, I'm not sure if the effort to maintain it is worth the convenience.

**Comment by maribu** [comment]
After a (short) discussion in the matrix room, I close this in favor of https://github.com/RIOT-OS/RIOT/pull/16349

**Pull request closed without merging**
