### PR TITLE
posix: remove strcasecmp functions and macros

### PR DESCRIPTION
**Pull request by authmillenon**
Those functions and macros are already provided by glibc and newlib, but not by `libc-msp430` and `libc-avr`. However, the only library that uses them is `libcoap` which is too fat for `msp430` and `avr` boards. And since they prove this proved to be a little bit difficult in #3612, this PR removes them

### CODE REVIEW

**Comment by cgundogan** [comment]
ACK

**Comment by OlegHahm** [comment]
> However, the only library that uses them is libcoap which is too fat for msp430 and avr boards.

Are we sure about this?

**Comment by authmillenon** [comment]
The test app that uses libcoap (and nothing much else) is blacklisting them.

**Comment by authmillenon** [comment]
I would prefer to discuss how to handle those boards + POSIX for the next release. I've tried to sneak in some optimizations to the `posix` module during my rework of `pnet` to `posix_sockets` but if we want to finally solidify our POSIX support, we need to discuss what we want to support and how we deal with such conflicts (apart from different libcs supporting different stuff from the POSIX specification there is also the issue of missing definitions from the POSIX specification from in existing `libc` files), among other things.

**Comment by authmillenon** [comment]
> there is also the issue of missing definitions from the POSIX specification from in existing libc files

Most prominent example that comes to my mind is `close()` in newlib's `unistd.h`, which does not exist IIRC

**Comment by cgundogan** [comment]
ACK holds. Nothing seems to be broken so far. These string functions can be added for specific targets in a later phase

**Pull request merged**
