### PR TITLE
CORD: enable THREAD_CREATE_STACKTEST for threads

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This enables the `THREAD_CREATE_STACKTEST` flag for the standalone CORD threads.

### Testing procedure

Testing if the example applications for both `cord_ep` and `cord_epsim` still work with and without `DEVELHELP` enabled should be enough

### Issues/PRs references

similar to #10181

### CODE REVIEW

**Comment by miri64** [comment]
If you want: please unify the commit messages ;-)

**Comment by bergzand** [comment]
> If you want: please unify the commit messages ;-)

But now one of them is longer than 50 chars (still shorter than 72 though).

**Comment by miri64** [comment]
> But now one of them is longer than 50 chars (still shorter than 72 though).

You could have gone the other way :woman_shrugging:

**Comment by bergzand** [comment]
> You could have gone the other way :woman_shrugging:

I know...

**Comment by bergzand** [comment]
Thanks!

**Pull request merged**
