### PR TITLE
cc2538 radio transceiver driver

### PR DESCRIPTION
**Pull request by AnonMall**
WIP
CC2538 Transceiver Driver for the gnrc  stack.
Sending works, but receiving only works in the driver and frames still don't get into the stack.

Also I have expanded the vector table, as the flag for using the more compact vector table does not work, but I still don't really know why.

### CODE REVIEW

**Comment by authmillenon** [comment]
Could you please change the PR's title to a more describing message?

Also, are you aware of [netdev2](https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/net/netdev2.h) and [netdev2_ieee802154](https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/net/netdev2/ieee802154.h)? It would make your driver independent from GNRC and you won't have to include parsing of headers into your driver. Just have a look at the newly remodeled [at86rf2xx driver](https://github.com/RIOT-OS/RIOT/blob/master/drivers/at86rf2xx/at86rf2xx_netdev.c) for reference.

**Comment by AnonMall** [comment]
Ah yeah, sorry about the title. I actually made the driver for an earlier release, but I will work on the port to the netdev2 right away

**Comment by hexluthor** [comment]
See https://github.com/RIOT-OS/RIOT/pull/2198 . This driver worked at the time but RIOT's networking API kept changing and I couldn't keep up.

**Comment by aeneby** [comment]
I'm actually working on an RF driver for this MCU too - so far both sending and receiving work right through the gnrc/netdev2 stack, and it also implements the new netdev2_ieee802154 stuff mentioned by @authmillenon above. I wanted to wait until it was more or less ready to merge before making a PR, but perhaps I should do it now to avoid duplication of effort...

**Comment by AnonMall** [comment]
@hexluthor Yeah same for me. Been working on a driver for some time now, but had to change it sereval times. 
@aeneby Yeah would maybe be the best if you start a PR. Could you then maybe reference @hexluthor and my PR, so that we have a slight oversight.

**Comment by aeneby** [comment]
A more complete driver implementation here: #5291

**Comment by kYc0o** [comment]
Can we close this in favour of #5291 ?

**Comment by AnonMall** [comment]
yeah sure

**Pull request closed without merging**
