### PR TITLE
ng_nettest: some fixes

### PR DESCRIPTION
**Pull request by authmillenon**
Some bugs where overlooked on merging #3098.

### CODE REVIEW

**Comment by authmillenon** [comment]
@PeterKietzmann or @phiros, ping?

**Comment by PeterKietzmann** [comment]
@phiros you reviewed #3098. Can you also look at this PR please?

**Comment by phiros** [comment]
Changes look good to me.
ACK after squash

**Comment by authmillenon** [comment]
Squashed.

**Pull request merged**
