### PR TITLE
make: introduce *_default pseudo-modules

### LINKED ISSUE #2971: Module `ng_icmpv6` and `ng_icmpv6_echo`
What is the purpose of defining these two modules in `Makefile.dep`? They both include `ng_ipv6`, which again includes `ng_icmpv6`. Smells like a circular dependency.. couldn't we just drop them and use `ng_ipv6` instead?

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes #2971

Follow-up to #2910 since I think NDP belongs in here, too.

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by OlegHahm** [comment]
It's no longer dependent on anything, right?

**Comment by OlegHahm** [comment]
Merge at will.

**Pull request merged**
