### PR TITLE
saml1x: enable pm_layered by default

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description

This PR enables pm_layered module by default for SAML10 and SAML11 MCUs.

### Testing procedure

Use the usual testing procedure for power management.

### Issues/PRs references
should fix a bug for #11346

### CODE REVIEW

**Comment by aabadie** [comment]
I tested this PR yesterday using `tests/periph_pm` and found that the switch the deep sleep wasn't very stable. Do you have a precise procedure so I can try to reproduce your use case ?

On my side, using the `tests/periph_pm` shell, I tried `unblock_rtc 1 5` but it had no effect and a second call to this command was raising a failed assertion.
Using `unblock_rtc 1 5`, I was able to switch to low-power only after calling the function twice.

Do you have any idea what could be wrong or if it's expected ?

**Comment by dylad** [comment]
I'll investigate further and try to reproduce.

**Comment by dylad** [comment]
I put the CPU in idle mode by default now, you can use` rtc_unblock 0 5` to reach standby mode for 5 seconds and it'll switch back to idle right after.

**Comment by aabadie** [comment]
Please fix the trailing whitespaces to make the CI happy, you can squash directly.

**Comment by dylad** [comment]
Done.

**Comment by aabadie** [comment]
Let's go then!

**Pull request merged**
