### PR TITLE
drivers/dfplayer: New driver for the DFPlayer Mini MP3 player

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR adds a driver for the UART controlled MP3 player module sold as "DFplayer Mini" for about 2€ and less. The shell command `dfplayer` is provided as well (when both modules `shell_commands` and `dfplayer` are used). The new test application in `tests/driver_dfplayer` provides exactly this.

### Testing procedure

1. Get an SD card sized 32GB or less. (Those come with a DOS partition table with exactly one partition spanning the whole storage and formatted as FAT32. This is what the device needs, in case you manually changed the partition table or the file system.)
2. Store some MP3 files on it using any (or all) of the following naming schemes:
    1. Files with three digit filenames (leading zeors) in two digit folder names (`"01/001.mp3"` to `"99/255.mp3"`)
    2. Files with four digit filenames stored in the folder MP3 (`"MP3/0001.mp3"` to `"MP3/9999.mp3"`)
    3. Files with four digit filenames stored in the folder ADVERT (`"ADVERT/0001.mp3"` to `"ADVERT/9999.mp3"`)
3. Plug the SD card into the DFPlayer Mini, connect it via UART (3.3V logic level) to your board
4. Connect the DFPlayer Mini to a speaker using either
    1. The SPK+ and SPK- pins to directly drive a passive speaker (mono) without the need of an amplifier. (An internal 3W amplifier is used.)
    2. The ADC_L, ADC_R and GND pins to directly drive a headphone, to directly connect to the AUX input via an audio Jack of your home entertainment system, or two to (stereo) speakers using a 2-channel amplifier
5. Compile, flash, and run `tests/driver_dfplayer` and use the `dfplayer` shell command to play music.

### Issues/PRs references

None

### CODE REVIEW

**Comment by maribu** [comment]
Dear reviews: I will not have time to work on this for the next two weeks. Please be patient.

**Comment by kaspar030** [comment]
I've ordered a couple, will test when they arrive!

**Comment by haukepetersen** [comment]
Nice! I am using this device since some in my kids record player. Although its running on Arduino at the moment, the kids still love it :-)

When I got my devices, I of course started also to write a RIOT driver on my own: https://github.com/haukepetersen/RIOT/tree/add_driver_dfplayermini. But as always, I did not get to PRing it, mainly as I was missing the time to add all the missing doc. 

On first sight, it seems like both drivers offer a very similar interface. The main difference I could find is code size, the driver in this PR takes ~1300 byte ROM, while mine takes ~700 (both @ nrf52dk). The question is, if this is due to some additional features or maybe there is room for improvement.

But anyhow, I would be totally fine with merging this PR as is, and I might PR mine as a leight-weight alternative at some point.

**Comment by maribu** [comment]
> The main difference I could find is code size, the driver in this PR takes ~1300 byte ROM, while mine takes ~700 (both @ nrf52dk). The question is, if this is due to some additional features or maybe there is room for improvement.

The difference between the two drivers seem to be mainly that the driver in this PR does error handling, has some workarounds for hardware bugs, and has a more verbose and easier to use callback interface. I currently have two different DFPlayer versions. One works relatively fine with sending commands as fire and forget, so you 700 Bytes version would work there. But for the other skipping error handling is just not going to work.

**Comment by maribu** [comment]
I'm currently doing some redesign and refactoring. I close the PR until this is done and force push the new version here. (The code using the driver is currently calling the API in a loop until the command succeeds or a retry limit is reached. This is pretty annoying to code and better handled internally in the driver. It will increase the driver size a bit, but therefore reduce the code size of the application for every API call - so I expect this to be actually beneficial in total.) Maybe I have some time tonight or tomorrow at the holiday to do this.

**Comment by maribu** [comment]
OK, reopening is prevented by GitHub. The new version is https://github.com/RIOT-OS/RIOT/pull/12363. This are the changes:

- The driver does now internally retry commands for up to `DFPLAYER_RETRIES` times (can be overwritten via `CFLAGS += -DDFPLAYER_RETRIES=<val>`)
- Non-idempotent commands (e.g. increase and decrease volume) are no longer provided
    - When they succeed but the ACK gets missing, retrying will result in the command being executed more than once
    - There are idempotent commands that can be used instead for every non-idempotent command (e.g. the set volume command instead of the increase and decrease volume command)
- The driver will no confirm that commands triggering the playback of a file do actually succeed
    - The DFPlayer only ACKs that reception of the command, not if playback succeeded
    - Previously the driver only verified that playback actually started when the busy pin is connected. Now the driver checks the status via UART in absence of the busy pin.

**Pull request closed without merging**
