### PR TITLE
[NEW] Rename 'openmote' board in-tree to 'openmote-cc2538', to avoid ambigu…

### PR DESCRIPTION
**Pull request by aeneby**
…ity with future versions of the OpenMote platform.

### CODE REVIEW

**Comment by aeneby** [comment]
Supersedes #4473.

**Comment by haukepetersen** [comment]
ACK

**Comment by authmillenon** [comment]
Please provide a commit name that actually fits the length of the submit message. "Rename 'openmote' board to 'openmote-cc2538'" should suffice. The rest can go into the further descriptions of the commit. Your commit message should look like this in your commit editor:

```
Short summery (ideally <= 50 chars, max 72 chars)

More detailed explanatory text, if necessary.  Wrap it to
about 72 characters or so.  In some contexts, the first
line is treated as the subject of an email and the rest of
the text as the body.  The blank line separating the
summary from the body is critical (unless you omit the body
entirely); tools like rebase can get confused if you run
the two together.

Further paragraphs come after blank lines.

  - Bullet points are okay, too

  - Typically a hyphen or asterisk is used for the bullet,
    preceded by a single space, with blank lines in
    between, but conventions vary here
```

See the [git manual](https://git-scm.com/book/ch5-2.html#Commit-Guidelines) for more details.

**Comment by aeneby** [comment]
@authmillenon OK, fixed.

**Comment by authmillenon** [comment]
Re-ACK.

**Pull request merged**
