### PR TITLE
CODEOWNERS: remove Robert Hartung

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Following the maintainer ping, Robert Hartung answered that he has no longer time for maintaining RIOT and requested to be taken off the CODEOWNERS list.

This PR implements this request. 

> I was quite busy with my PhD thesis (and still am), therefore, feel free
> to take me off the active maintainers list.
> Note: I am still listed as a code owner at some places, can you remove
> @roberthartung from there for now as well?

### CODE REVIEW

**Review by roberthartung — APPROVED** [review]
Thanks. ACK.

**Comment by kaspar030** [comment]
Many thanks for everything @roberthartung!!

**Comment by miri64** [comment]
In the meantime I removed @roberthartung from both the maintainer teams here and on the forum. If that was not supposed to happen, I can reverse that.

**Comment by roberthartung** [comment]
@kaspar030 You're welcome, developing the PM module with you was great. Thanks!
@miri64 That's totally fine, thanks, Miri!

Thanks to everyone again I had a great time and I will still have an eye on you!

**Pull request merged**
