### PR TITLE
sys: partly refactor make dependency resolution

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

After the discussion in #19485, I had another look at the dependency resolution in sys (I had time to spend). This (draft) PR is applying a similar approach proposed in https://github.com/RIOT-OS/RIOT/pull/19485#issuecomment-1517395822 to other modules (except those in shell, net, usb, ztimer* and xtimer).

It seems the order of resolution might make a difference in the result. This is why I'm opening this PR as a draft PR, to see what the CI has to say.

~While doing that, I noticed were not ported to Kconfig yet. This PR also adds some commits for that and could be split out in another PR if requested.~ merged in #19622 

### Testing procedure

- Green CI
- Same modules included (there's a tool for that but I don't remember which one)

### CODE REVIEW

**Comment by aabadie** [comment]
IMHO this looks good now and Murdock didn't raise major problems so far => not a draft anymore.

**Comment by benpicco** [comment]
That's a nice cleanup, but already requires a rebase - we should get this in rather soon before more of it changes.

**Comment by aabadie** [comment]
rebase, let's see what Murdock has to say

**Review by benpicco — APPROVED** [review]

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
