### PR TITLE
sys: add pseudomodule scanf_float

### PR DESCRIPTION
**Pull request by gdoffe**
To read float number from stdin, add "-u scanf_float"
option to the linker.
This option is setup using a pseudomodule as it is already done for
printf_float.
Just add to your Makefile:
USEMODULE += scanf_float

Tested on STM32 and native arch.

### CODE REVIEW

**Comment by jcarrano** [comment]
@gdoffe I PR'd unit tests against your banch: https://github.com/gdoffe/RIOT/pull/1

**Comment by kaspar030** [comment]
> ### [@jcarrano](/jcarrano) [jcarrano](/jcarrano) added the [Type: bug](/RIOT-OS/RIOT/labels/Type%3A%20bug) label [2 hours ago](#event-2336379304)

Why is that a bug? The nanospecs disable features for a reason.

**Comment by jcarrano** [comment]
@kaspar030 The bug is that there is a loss of functionality (a part of the libc is missing) and there is no way of bringing it back (until this PR, of course)

**Comment by jcarrano** [comment]
What if `scanf_float` was made the default? It is part of the C standard library and it would be the _least surprising thing_ to do to have it normally available - with the possibility to remove it if the ROM image becomes too big.

**Comment by kaspar030** [comment]
> What if `scanf_float` was made the default? It is part of the C standard library and it would be the _least surprising thing_ to do to have it normally available - with the possibility to remove it if the ROM image becomes too big.

I don't think that argument scales to *all the other* C library functions that are not enabled by default. Some documentation about what is disabled might be very helpful, though.

**Comment by jcarrano** [comment]
The argument cannot be extrapolated to those functions that require additional I/O functionality: datetime functions will only work if there is a RTC, file functions if there is a FS. In those cases, however, the standard specifies how to fail.

It has to be documented, yes, but users should refer to the documentation to learn how to do more advanced tricks (like disabling features to save flash) and not to learn how to make basic functionality work. That would seem more aligned with RIOT's goal of being easy to use by default.

**Comment by kaspar030** [comment]
This PR's ```tests/minimal``` without ```USEMODULE += scanf_float```:

```
   text    data     bss     dec     hex filename
   2980      16    2540    5536    15a0 /home/kaspar/src/riot.tmp/tests/minimal/bin/samr21-xpro/tests_minimal.elf
```

With ``ÙSEMODULE += scanf_float``` added to the makefile:
```
   text    data     bss     dec     hex filename
  21152     488    2548   24188    5e7c /home/kaspar/src/riot.tmp/tests/minimal/bin/samr21-xpro/tests_minimal.elf
```

That's just too expensive to enable by default. For float in general, the number one rule on embedded systems is "don't use at all".

**Comment by gdoffe** [comment]
> That's just too expensive to enable by default. For float in general, the number one rule on embedded systems is "don't use at all".

I agree it should not be activated by default. printf_float is not activated by default. But it needs to be documented somewhere (what is the best place for this ?).

We use it on a big STM32 (STM32F446) which have the capacity to use use it. However that cost of nearly 18kB seems unacceptable.

It is more a feature to activate if needed.

**Comment by jcarrano** [comment]
> That's just too expensive to enable by default.

Expensive? If it still fits into the flash, what's the problem then? If it is desirable to reduce the image size (say, because of flashing time at a production facility of for delivering via OTA) than that's an optimization issue- the user can figure out how to fine-tune his app.

I don't want to deviate the conversation too much from the main purpose of this PR (to make it possible to enable scanf_float). I may make a separate PR dealing with it being or not default.

**Comment by gdoffe** [comment]
> I don't want to deviate the conversation too much from the main purpose of this PR (to make it possible to enable scanf_float). I may make a separate PR dealing with it being or not default.

+1

**Comment by gdoffe** [comment]
Hi,

What is the next step for this PR ?

Thanks,
Gilles

**Comment by aabadie** [comment]
> What is the next step for this PR ?

Merge https://github.com/gdoffe/RIOT/pull/1 ? (use "rebase and merge" option). After that I have the impression that it will be good to go.

**Comment by gdoffe** [comment]
Thx @aabadie, done.

**Comment by aabadie** [comment]
Now you need to rebase to drop the merge commit.

I let @jcarrano give a last round of review.

**Comment by jcarrano** [comment]
@aabadie i'll approve it, but since the test was written by me it would be nice if somebody would give a second approval.

**Comment by zpw199062** [comment]
when i added USEMODULE += scanf_float in Makefile，and i entered the docker to build，it shows that

error: /home/zpw199062/backup/riot/RIOT-2019.04/tests/periph_gpio/bin/stm32f4discovery/scanf_float.a: No such file or directory
/home/zpw199062/backup/riot/RIOT-2019.04/tests/periph_gpio/../../Makefile.include:461: recipe for target '/home/zpw199062/backup/riot/RIOT-2019.04/tests/periph_gpio/bin/stm32f4discovery/tests_periph_gpio.elf' failed

how to solve it？
And my problem is also i cannot printf Float

**Comment by kaspar030** [comment]
@zpw199062 I think "scanf_float" was merged after release 2019.04, which your folder name suggests you're using. You could try cherry-picking this commit:  https://github.com/RIOT-OS/RIOT/pull/11511/commits/7fc32070431ac08677eaa30c2ab8aa52f48db221

**Comment by zpw199062** [comment]
> @zpw199062 I think "scanf_float" was merged after release 2019.04, which your folder name suggests you're using. You could try cherry-picking this commit: [7fc3207](https://github.com/RIOT-OS/RIOT/commit/7fc32070431ac08677eaa30c2ab8aa52f48db221)

Thank you so much for the quikly reply, when i changed file pseudomodules.inc.mk, after i added the part you showed me,
then i opened it again, it shows that:
E325: ATTENTION
Found a swap file by the name "~/backup/riot/RIOT-2019.04/makefiles/.pseudomodul
es.inc.mk.swp"
          owned by: zpw199062   dated: Tue Jun 18 02:03:20 2019
         file name: ~zpw199062/backup/riot/RIOT-2019.04/makefiles/pseudomodules.
inc.mk
          modified: YES
         user name: zpw199062   host name: ubuntu
        process ID: 7527
While opening file "/home/zpw199062/backup/riot/RIOT-2019.04/makefiles/pseudomod
ules.inc.mk"
             dated: Mon Apr 29 04:28:52 2019

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /home/zpw199062/backup/riot/R
IOT-2019.04/makefiles/pseudomodules.inc.mk"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/home/zpw199062/backup/riot/R
IOT-2019.04/makefiles/.pseudomodules.inc.mk.swp"
    to avoid this message.
-- More --
How to make sure that i already chaneg the file,pleas help me!

**Comment by kaspar030** [comment]
The message just tells you what's wrong: probably you had the file still opened in another vim session.

**Comment by kaspar030** [comment]
BTW, this is getting off-topic for this PR. @zpw199062 Could we maybe move to mailing list (devel@riot-os.org)?

**Comment by zpw199062** [comment]
> Hi，gdoffe
> 
> Thank you first for the efforts solving this problem . And I tried to use the Riot-master version that you merged this "float problem" into, and i use it now. I do find that you changed the Make.include part and the pseudomodules.inc.mk which is added the float part. And i then tried the suggestion that adding USEMODULE += scanf_float in Makefile. It is built and flashed successfully, but when i run it. I still cannot see any float number. You can see the picture below.
> image
> 
> And i want to show you my code for this part.
> image
> image
> 
> you can see that i defined the variable speed float type and try to print it ,but it still cannot work. Could you pls help me find the reason why?
> 
> Thanks so much!
> Best regard!
> By Peiwen

I don't get it，how to add the printf_float, what head file explain the function, could you pls tell me?

**Pull request merged**
