### PR TITLE
boards: add samr30-xpro board and samr30 cpu

### PR DESCRIPTION
**Pull request by biboc**
This PR adds samr30-xpro board and samr30 cpu

### CODE REVIEW

**Comment by dylad** [comment]
@biboc I'll do a proper review right after the I2C embargo is over. It should be fast since this MCU is based on SAML21.
First thing I can say, you should adapt doxygen + comments. You left a lot of reference to SAML21, it should be replaced by SAMR30

**Comment by biboc** [comment]
Ok for the reference, I'll edit my PR

**Comment by dylad** [comment]
@biboc the I2C embargo is now over so I guess you can update your periph_conf.h to the new interface.
I'll be on holiday and offline most of the time in August, but I hope to see this PR merged in September :)

**Comment by aabadie** [comment]
@biboc @dylad, FYI I received a couple of these boards today and started to test this PR a bit. I found some issues that I fixed and pushed in the PR.
I also rebased on the latest master and updated the I2C configuration. I also updated all doxygen comments, fixed LED macros and saul support for the board GPIOs.
Note that I split the initial commit in 2: one for the CPU addition and one for the board addition.

What has been tested with success:
- timer/xtimer/saul
- I2C with one sensor plugged on PA16/PA17
- radio configuration using gnrc_networking, but not communication between 2 nodes
- flashing works either with edbg or openocd

I don't really like all this the copy-pasted code but maybe some factorization can be done in follow-up PRs.

As is, I would say that this PR is in a mergeable state (after squashing and green CIs) but maybe @dylad you want to have a look first.

**Comment by dylad** [comment]
> I don't really like all this the copy-pasted code but maybe some factorization can be done in follow-up PRs.

Can you elaborate a bit more on this point ? I think the only copy-paste code come from timer/rtc/rtt driver.

I'll take a look asap but I don't have this board to test.

**Comment by aabadie** [comment]
> Can you elaborate a bit more on this point ? I think the only copy-paste code come from timer/rtc/rtt driver.

Yes, some periph implementation could have been shared. But the rest is ok.

**Comment by dylad** [comment]
> Yes, some periph implementation could have been shared

Since SAMR30 is a SAML21 yes, we can merged all cpu/samr30/periph to cpu/saml21/periph right now.

**Comment by cladmi** [comment]
@aabadie The problem is that `saml21` is already a `CPU` so a CPU should not really depend on another. Can't you declare the board with a `saml21` cpu and do the specific handling based on `CPU_MODEL` in `saml21` ?

**Comment by aabadie** [comment]
> Can't you declare the board with a saml21 cpu and do the specific handling based on CPU_MODEL in saml21 ?

This sounds like a good idea. I'll try it and let you know how it goes.

**Comment by dylad** [comment]
How does samr21 acts ? I mean a samr21 is a samd21. you copy the same behaviour for samr30 and saml21.

**Comment by aabadie** [comment]
@dylad, I dropped the cpu/samr30 directory and slightly adapted the saml21 pm.c. It builds fine now and still works (tested applications examples/default, tests/periph_rtc and tests/periph_rtt).

I can try to re-add authorship of initial commits to @biboc if we want (because my git rebases/edit/amends dropped him).

**Comment by aabadie** [comment]
Just fixed errors reported by Murdock. Let me know when I can squash :)

**Comment by aabadie** [comment]
@dylad, CI is all green. Ok to merge ?

**Comment by dylad** [comment]
Here we go.

**Comment by biboc** [comment]
Have you tried your change on a board?

**Comment by keestux** [comment]
@biboc @dylad
Sorry to complain about the PR that is already merged.
Why was an older ASF version used, 3.34.2 instead of 3.35.1?
Why was it needed to modify the vendor files? The new method (since c5cbc428b, 2017-09-20) is to verbatim copy from ASF.

**Comment by keestux** [comment]
@biboc @dylad
Well, the thing is, the method to copy vendor files was changed, back in 2017. Before c5cbc42 it was as it is described in the README of samr30. It's something I described for samd21 and the samr30 README is basically a copy of that.
Since c5cbc42 we simply copy the files verbatim (i.e. unchanged) from ASF into RIOT. In all cases we describe what ASF version was used, or whatever source was used.

Furthermore I am unhappy of the fact that the samr30 files are from ASF 3.34.2. I believe that was totally unnecessary.

You may think: who cares, but I see great value in documenting. When we want to pull in updates from newer ASF we need to know what changed. Each ASF can have potential bug fixes, which is also the case for 3.34.2 => 3.35.1
```
-typedef volatile       uint32_t WoReg8;  /**< Write only  8-bit register (volatile unsigned int) */
+typedef volatile       uint8_t  WoReg8;  /**< Write only  8-bit register (volatile unsigned int) */
```

**Comment by dylad** [comment]
@keestux Do you want to update the SAMR30 vendor files to 3.35.1 ?

I don't know why 3.34.2 what pick up but we can still improve this :)

**Comment by keestux** [comment]
@dylad Yes, I already have it prepared, but I want to do it on top of #10914

**Comment by dylad** [comment]
Ok I'll have a look at it this weekend for sure.

**Comment by biboc** [comment]
@keestux, you're right, I did pay attention to ASF version and how files verbatim are copied. Feel free to update at best

**Comment by keestux** [comment]
@biboc I guess you wanted to say: "... I did **not** pay attention ...".
In any case, can you have a look at #10941, and confirm that it is working for you?

**Pull request merged**
