### PR TITLE
cpu/sam3s: initial support for the Atmel SAM3S4B

### PR DESCRIPTION
**Pull request by sgso**
This adds support for the SAM3S4B but the includes contain the necessary
headers for all MCUs of the SAM3S family (except the SAM3S8/SD8).

- include/ contains a pristine copy of sam/utils/cmsis/sam3s/include/ from
the latest ASF standalone archive as of commit date (version 3.24.1).
- periph/spi.c: copy from sam3x8e with `spi_init_slave()` removed because it differs but I can't test it (device is a USB stick).
- periph/gpio.c: depends on #3095. It's my own implementation because sam3x8e version is broken anyway.
- periph/timer.c: unchanged copy from sam3x8e. I do not understand this timer stuff (yet). It does something but I'd really like to have more information how timers shall behave. I'm clueless.
- periph/uart.c: shortened copy from sam3x8e.
- startup.c: I #ifdef'd it to be compatible with all SAM3S cpus. Of course not tested.

We should probably have some kind of sam3-common.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Very interesting platform. But by looking at the code, it seems to me that it is 99% identical to the sam3x8e code. I would like to see those two CPUs merged from the beginning... To give you a solid base, I just created #3194.

Does this sound feasible to you or did I overlook any significant differences between the two sam3... CPUs?

**Comment by sgso** [comment]
I'm going to pick this up once the new gpio interface is merged or the rename. I can't handle two branches at the same time.

**Comment by haukepetersen** [comment]
makes sense. Hope to the get the new GPIO IF merged soon!

**Comment by PeterKietzmann** [comment]
@sgso the new GPIO IF was merged with #3095 :-)

**Comment by aethaniel** [comment]
atsam3s and atsam3x share same architecture and have also lot of common peripherals with most of all atsam4 and atsamg5x (but not with samd series). 
Couldn't they have a common folder (ie atsam34 or similar) to host their peripheral drivers?
Device specific actions could be done in dedicated (sub)folders like atsam3x, atsam3s, atsamg55, etc...

**Comment by haukepetersen** [comment]
For this kind of CPU diversity we have three competing solutions at the moment: the `stm32`, the `kinetis`, and now the `samX` families: The `stm32` CPUs work with (sub-optimal) code duplication at the moment. The `kinetis` based CPUs have a share comon folder for their peripheral implementations. I think on the long term, it would be cool, if we find a way that works for all and is used throughout the RIOT CPU folder. I will try to spend some time next week to compare the existing (and proposed) solutions a little more in depth and highlight their benefits/shortcomings. Then I would suggest we put this to a vote for all RIOT people interested in CPU abstraction.

**Comment by OlegHahm** [comment]
What's the latest here?

**Comment by OlegHahm** [comment]
Can you please state why you closed this?

**Comment by sgso** [comment]
@OlegHahm Because this added the sam3s as a separate CPU but now we have the shared cpu/sam3 directory. Any necessary changes to that will be part of #3181 once I update it.

**Comment by OlegHahm** [comment]
Thanks for the explanation.

**Pull request closed without merging**
