### PR TITLE
ipv6_addr: rename ng_ipv6_hdr_is_ipv6_hdr() to something less silly

### PR DESCRIPTION
**Pull request by authmillenon**
Suggested in https://github.com/RIOT-OS/RIOT/pull/2454#discussion_r28870632. Ready for delivery.

### CODE REVIEW

**Comment by OlegHahm** [comment]
How about `ng_ipv6_hdr_check()` or `_verify()`?

**Comment by authmillenon** [comment]
I think `_is` shorter and more to the point of what this function does. `_check` and `_verify` sound like way more powerful functions than a lookup of the version field.

**Comment by OlegHahm** [comment]
I think the new name sounds weird (actually, I think the best way would be to add something to the coding conventions that allows for `is_<MODULE>()` function names). However, that's better than the old name and aligned with 6lowpan IIRC.

**Comment by authmillenon** [comment]
So what is your verdict?

**Comment by OlegHahm** [comment]
That was a "well, okay then"-ACK.

**Pull request merged**
