### PR TITLE
gnrc_pktdump: fix dependencies

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This fixes several quality defects in `gnrc_pktdump`:

- the switch-cases for the NETTYPE are now guarded by the dedicate `gnrc_nettype_*` modules.
- only use `print` functions when the corresponding module is compiled in (not the `gnrc` module that pulls in that dependency), otherwise fall-back to `od_hex_dump()`
- optimize how and when the `od_hex_dump()` function is called.
- re-order switch-cases according to the `gnrc_nettype_t` enum.
- 

### Testing procedure
Ideally, all applications using `gnrc_pktdump` should be tested.

- `examples/ccn-lite-relay`
- `examples/default`
- `examples/gnrc_lorawan`
- `examples/gnrc_networking`
- `examples/gnrc_networking_mac`
- `tests/driver_cc110x`
- `tests/driver_netdev_common`
- `tests/gnrc_dhcpv6_client_6lbr`
- `tests/gnrc_gomach`
- `tests/gnrc_ipv6_ext`
- `tests/gnrc_ipv6_ext_frag`
- `tests/gnrc_lwmac`
- `tests/gnrc_netif`
- `tests/gnrc_netif_ieee802154`
- `tests/gnrc_rpl_srh`
- `tests/gnrc_sixlowpan`
- `tests/gnrc_sock_async_event`
- `tests/slip`

However, there are many duplicates of NETTYPE registrations:

```
$ git grep gnrc_netreg_register -- $(git grep --name-only "\<gnrc_pktdump\>" -- examples/*/Makefile tests/*/Makefile | xargs dirname) 
examples/ccn-lite-relay/main.c:    gnrc_netreg_register(GNRC_NETTYPE_CCN_CHUNK, &dump);
examples/default/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
examples/gnrc_lorawan/main.c:    gnrc_netreg_register(GNRC_NETTYPE_LORAWAN, &dump);
examples/gnrc_networking/udp.c:    gnrc_netreg_register(GNRC_NETTYPE_UDP, &server);
examples/gnrc_networking_mac/udp.c:    gnrc_netreg_register(GNRC_NETTYPE_UDP, &server);
tests/driver_cc110x/main.c:            if (gnrc_netreg_register(GNRC_NETTYPE_SIXLOWPAN, &dump)) {
tests/driver_netdev_common/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
tests/gnrc_gomach/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
tests/gnrc_ipv6_ext/main.c:        gnrc_netreg_register(GNRC_NETTYPE_IPV6, &ip_entry);
tests/gnrc_ipv6_ext_frag/udp.c:    gnrc_netreg_register(GNRC_NETTYPE_UDP, &server);
tests/gnrc_lwmac/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
tests/gnrc_netif/common.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dumper_undef);
tests/gnrc_netif/common.c:    gnrc_netreg_register(GNRC_NETTYPE_IPV6, &dumper_ipv6);
tests/gnrc_netif_ieee802154/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
tests/gnrc_rpl_srh/main.c:        gnrc_netreg_register(GNRC_NETTYPE_IPV6, &ip_entry);
tests/gnrc_sixlowpan/main.c:    gnrc_netreg_register(GNRC_NETTYPE_SIXLOWPAN, &dump_6lowpan);
tests/gnrc_sixlowpan/main.c:    gnrc_netreg_register(GNRC_NETTYPE_IPV6, &dump_ipv6);
tests/gnrc_sixlowpan/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UDP, &dump_udp);
tests/gnrc_sixlowpan/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UDP, &dump_udp_61616);
tests/gnrc_sock_async_event/main.c:    gnrc_netreg_register(GNRC_NETTYPE_IPV6, &_pktdump);
tests/slip/main.c:    gnrc_netreg_register(GNRC_NETTYPE_UNDEF, &dump);
```

So a subset should be enough.

### Issues/PRs references
Depends on PR ~~#13994~~ (merged).

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master, as #13994 was merged while I was writing the OP.

**Comment by miri64** [comment]
All errors are unrelated now:

- [`run_test/tests/pkg_littlefs2/esp32-wroom-32:gnu`](https://ci.riot-os.org/RIOT-OS/RIOT/14028/8ff77f64449bb5b1be261bbcc6a370c5c9f6f6a4/output/compile/tests/libc_newlib/esp32-heltec-lora32-v2:gnu.txt)
- [`compile/tests/libc_newlib/esp32-heltec-lora32-v2:gnu`](https://ci.riot-os.org/RIOT-OS/RIOT/14028/8ff77f64449bb5b1be261bbcc6a370c5c9f6f6a4/output/compile/tests/libc_newlib/esp32-heltec-lora32-v2:gnu.txt)

**Comment by leandrolanzieri** [comment]
Tested on the following applications:

<details><summary><b>examples/ccn-lite-relay (GNRC_NETTYPE_CCN_CHUNK)</b></summary>

```
> ccnl_int /riot/peter/schmerzl
2020-05-07 15:20:44,361 #  ccnl_int /riot/peter/schmerzl
> 2020-05-07 15:20:44,373 #  PKTDUMP: data received:
2020-05-07 15:20:44,379 # ~~ SNIP  0 - size:  24 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
2020-05-07 15:20:44,382 # Content is: Hello World! Hello RIOT!
2020-05-07 15:20:44,386 # ~~ PKT    -  1 snips, total size:  24 byte
```
</details>

<details><summary><b>examples/default (GNRC_NETTYPE_UNDEF)</b></summary>

```
> 2020-05-07 15:23:24,583 #  PKTDUMP: data received:
2020-05-07 15:23:24,585 # ~~ SNIP  0 - size:   5 byte, type: NETTYPE_UNDEF (0)
2020-05-07 15:23:24,586 # 00000000  52  49  4F  54  21
2020-05-07 15:23:24,600 # ~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
2020-05-07 15:23:24,602 # if_pid: 4  rssi: -46  lqi: 255
2020-05-07 15:23:24,602 # flags: 0x0
2020-05-07 15:23:24,603 # src_l2addr: 7B:B6
2020-05-07 15:23:24,605 # dst_l2addr: 32:A9:FA:65:10:6B:11:14
2020-05-07 15:23:24,606 # ~~ PKT    -  2 snips, total size:  23 byte
```
</details>

<details><summary><b>examples/gnrc_lorawan (GNRC_NETTYPE_LORAWAN)</b></summary>

```
> send 4 RIOT 1
2020-05-07 16:37:52,261 #  send 4 RIOT 1
2020-05-07 16:37:55,967 # PKTDUMP: data received:
2020-05-07 16:37:55,976 # ~~ SNIP  0 - size:   7 byte, type: NETTYPE_LORAWAN (1)
2020-05-07 16:37:55,978 # 00000000  48  69  20  6E  6F  64  65
2020-05-07 16:37:55,992 # ~~ SNIP  1 - size:   1 byte, type: NETTYPE_UNDEF (0)
2020-05-07 16:37:55,993 # 00000000  02
2020-05-07 16:37:55,995 # ~~ SNIP  2 - size:   8 byte, type: NETTYPE_UNDEF (0)
2020-05-07 16:37:55,995 # 00000000  60  3B  BA  1F  01  A0  02  00
2020-05-07 16:37:55,996 # ~~ PKT    -  3 snips, total size:  16 byte
2020-05-07 16:37:55,996 # Successfully sent packet
```
</details>

<details><summary><b> examples/gnrc_networking (GNRC_NETTYPE_UDP)</b></summary>

```
> 2020-05-07 15:28:33,564 #  PKTDUMP: data received:
2020-05-07 15:28:33,564 # ~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
2020-05-07 15:28:33,565 # 00000000  52  49  4F  54
2020-05-07 15:28:33,565 # ~~ SNIP  1 - size:   8 byte, type: NETTYPE_UDP (4)
2020-05-07 15:28:33,566 #    src-port:  1234  dst-port:  1234
2020-05-07 15:28:33,566 #    length: 12  cksum: 0x247b
2020-05-07 15:28:33,567 # ~~ SNIP  2 - size:  40 byte, type: NETTYPE_IPV6 (2)
2020-05-07 15:28:33,568 # traffic class: 0x00 (ECN: 0x0, DSCP: 0x00)
2020-05-07 15:28:33,568 # flow label: 0x00000
2020-05-07 15:28:33,569 # length: 12  next header: 17  hop limit: 64
2020-05-07 15:28:33,570 # source address: fe80::e839:76d6:2201:6578
2020-05-07 15:28:33,570 # destination address: fe80::30a9:fa65:106b:1114
2020-05-07 15:28:33,571 # ~~ SNIP  3 - size:  24 byte, type: NETTYPE_NETIF (-1)
2020-05-07 15:28:33,580 # if_pid: 7  rssi: -52  lqi: 255
2020-05-07 15:28:33,580 # flags: 0x0
2020-05-07 15:28:33,581 # src_l2addr: EA:39:76:D6:22:01:65:78
2020-05-07 15:28:33,582 # dst_l2addr: 32:A9:FA:65:10:6B:11:14
2020-05-07 15:28:33,583 # ~~ PKT    -  4 snips, total size:  76 byte
```
</details>

<details><summary><b>tests/gnrc_sixlowpan (GNRC_NETTYPE_SIXLOWPAN)</b></summary>

```
main(): This is RIOT! (Version: 2020.07-devel-444-g8ff77-gnrc_pktdump/fix/opt-deps)
RIOT network stack example application
PKTDUMP: data received:
~~ SNIP  0 - size:  74 byte, type: NETTYPE_SIXLOWPAN (1)
Fragmentation Header (first)
datagram size: 148
tag: 0x0001
IPHC dispatch
TF: traffic class and flow label elided
NH: LOWPAN_NHC
HLIM: 255
Stateless source address compression: elided (use L2 address)
Stateless destinaton address compression: 128 bits inline
00000000  FD  01  00  00  00  00  00  00  00  00  00  00  00  00  00  01
00000010  F3  00  23  2F  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000030  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000040  00  00  00  00
~~ SNIP  1 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 02:00:00:FF:FE:00:00:02
dst_l2addr: 02:00:00:FF:FE:00:00:01
~~ PKT    -  2 snips, total size:  98 byte
PKTDUMP: data received:
~~ SNIP  0 - size:  57 byte, type: NETTYPE_SIXLOWPAN (1)
Fragmentation Header (subsequent)
datagram size: 148
tag: 0x0001
offset: 12
00000000  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000010  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000030  00  00  00  00
~~ SNIP  1 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 02:00:00:FF:FE:00:00:02
dst_l2addr: 02:00:00:FF:FE:00:00:01
~~ PKT    -  2 snips, total size:  81 byte
PKTDUMP: data received:
~~ SNIP  0 - size: 148 byte, type: NETTYPE_IPV6 (2)
traffic class: 0x00 (ECN: 0x0, DSCP: 0x00)
flow label: 0x00000
length: 108  next header: 17  hop limit: 255
source address: fe80::ff:fe00:2
destination address: fd01::1
00000000  F0  B0  F0  B0  00  6C  23  2F  00  00  00  00  00  00  00  00
00000010  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000030  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000040  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000050  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000060  00  00  00  00  00  00  00  00  00  00  00  00
~~ SNIP  1 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 02:00:00:FF:FE:00:00:02
dst_l2addr: 02:00:00:FF:FE:00:00:01
~~ PKT    -  2 snips, total size: 172 byte
PKTDUMP: data received:
~~ SNIP  0 - size: 108 byte, type: NETTYPE_UDP (4)
   src-port: 61616  dst-port: 61616
   length: 108  cksum: 0x232f
00000000  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000010  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000030  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000040  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000050  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000060  00  00  00  00
~~ SNIP  1 - size:  40 byte, type: NETTYPE_IPV6 (2)
traffic class: 0x00 (ECN: 0x0, DSCP: 0x00)
flow label: 0x00000
length: 108  next header: 17  hop limit: 255
source address: fe80::ff:fe00:2
destination address: fd01::1
~~ SNIP  2 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 02:00:00:FF:FE:00:00:02
dst_l2addr: 02:00:00:FF:FE:00:00:01
~~ PKT    -  3 snips, total size: 172 byte
PKTDUMP: data received:
~~ SNIP  0 - size: 100 byte, type: NETTYPE_UNDEF (0)
00000000  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000010  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000030  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000040  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000050  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000060  00  00  00  00
~~ SNIP  1 - size:   8 byte, type: NETTYPE_UDP (4)
   src-port: 61616  dst-port: 61616
   length: 108  cksum: 0x232f
~~ SNIP  2 - size:  40 byte, type: NETTYPE_IPV6 (2)
traffic class: 0x00 (ECN: 0x0, DSCP: 0x00)
flow label: 0x00000
length: 108  next header: 17  hop limit: 255
source address: fe80::ff:fe00:2
destination address: fd01::1
```
</details>

@miri64 am I missing some nettype to test?

**Comment by miri64** [comment]
Does not seem like it :-)

**Comment by leandrolanzieri** [comment]
Here it's also the result of the modified test:
<details><summary><b>tests/gnrc_netif</b></summary>

```
Help: Press s to start test, r to print it is ready
READY
s
START
.......................................................................
OK (71 tests)
Sending data from Ethernet device:
00000000  3E  E6  B5  0F  19  23  3E  E6  B5  22  FD  0A  FF  FF  41  42
00000010  43  44  45  46  47  00
Sending data from Ethernet device:
00000000  FF  FF  FF  FF  FF  FF  3E  E6  B5  22  FD  0A  FF  FF  41  42
00000010  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  DC  00  00  00  0B  FD  22  19  0F  B5  E6  3E  0A  FD  22
00000010  19  0F  B5  E6  3E  31  32  33  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  D8  01  00  00  0B  FD  0A  FD  22  19  0F  B5  E6  3E  31
00000010  32  33  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  9C  02  00  00  0B  FD  22  19  0F  B5  E6  3E  0A  FD  31
00000010  32  33  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  9C  03  00  00  0B  FD  22  19  0F  B5  E6  3E  0A  FD  31
00000010  32  33  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  98  04  00  00  0B  FD  0A  FD  31  32  33  41  42  43  44
00000010  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  D8  05  00  00  FF  FF  0A  FD  22  19  0F  B5  E6  3E  31
00000010  32  33  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  98  06  00  00  FF  FF  0A  FD  31  32  33  41  42  43  44
00000010  45  46  47  00
Sending data from Ethernet device:
00000000  3E  E6  B5  0F  19  23  3E  E6  B5  22  FD  0A  86  DD  60  00
00000010  00  00  00  08  3B  40  FE  80  00  00  00  00  00  00  3C  E6
00000020  B5  FF  FE  22  FD  0A  FE  80  00  00  00  00  00  00  3C  E6
00000030  B5  FF  FE  0F  19  23  41  42  43  44  45  46  47  00
Sending data from Ethernet device:
00000000  33  33  00  00  00  01  3E  E6  B5  22  FD  0A  86  DD  60  00
00000010  00  00  00  08  3B  40  FE  80  00  00  00  00  00  00  3C  E6
00000020  B5  FF  FE  22  FD  0A  FF  02  00  00  00  00  00  00  00  00
00000030  00  00  00  00  00  01  41  42  43  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  DC  07  00  00  0B  FD  22  19  0F  B5  E6  3E  0A  FD  22
00000010  19  0F  B5  E6  3E  60  00  00  00  00  08  3B  40  FE  80  00
00000020  00  00  00  00  00  3C  E6  B5  0F  19  22  FD  0A  FE  80  00
00000030  00  00  00  00  00  3C  E6  B5  FF  FE  0F  19  23  41  42  43
00000040  44  45  46  47  00
Sending data from IEEE 802.15.4 device:
00000000  41  D8  08  00  00  FF  FF  0A  FD  22  19  0F  B5  E6  3E  60
00000010  00  00  00  00  08  3B  40  FE  80  00  00  00  00  00  00  3C
00000020  E6  B5  0F  19  22  FD  0A  FF  02  00  00  00  00  00  00  00
00000030  00  00  00  00  00  00  01  41  42  43  44  45  46  47  00
pktdump dumping Ethernet packet with empty payload
PKTDUMP: data received:
~~ SNIP  0 - size:   0 byte, type: NETTYPE_UNDEF (0)
~~ SNIP  1 - size:  20 byte, type: NETTYPE_NETIF (-1)
if_pid: 6  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 3E:E6:B5:22:FD:0B
dst_l2addr: 3E:E6:B5:22:FD:0A
~~ PKT    -  2 snips, total size:  20 byte
pktdump dumping IEEE 802.15.4 packet with empty payload
PKTDUMP: data received:
~~ SNIP  0 - size:   0 byte, type: NETTYPE_UNDEF (0)
~~ SNIP  1 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: -16472  lqi: 93
flags: 0x0
src_l2addr: 3E:E6:B5:0F:19:22:FD:0B
dst_l2addr: 3E:E6:B5:0F:19:22:FD:0A
~~ PKT    -  2 snips, total size:  24 byte
pktdump dumping Ethernet packet with payload 12 34 45 56
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  12  34  45  56
~~ SNIP  1 - size:  20 byte, type: NETTYPE_NETIF (-1)
if_pid: 6  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 3E:E6:B5:22:FD:0B
dst_l2addr: 3E:E6:B5:22:FD:0A
~~ PKT    -  2 snips, total size:  24 byte
pktdump dumping IEEE 802.15.4 packet with payload 12 34 45 56
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  12  34  45  56
~~ SNIP  1 - size:  24 byte, type: NETTYPE_NETIF (-1)
if_pid: 7  rssi: -16472  lqi: 93
flags: 0x0
src_l2addr: 3E:E6:B5:0F:19:22:FD:0B
dst_l2addr: 3E:E6:B5:0F:19:22:FD:0A
~~ PKT    -  2 snips, total size:  28 byte
pktdump dumping IPv6 over Ethernet packet with payload 01
PKTDUMP: data received:
~~ SNIP  0 - size:  41 byte, type: NETTYPE_IPV6 (2)
traffic class: 0x00 (ECN: 0x0, DSCP: 0x00)
flow label: 0x00000
length: 1  next header: 59  hop limit: 64
source address: fe80::3fe6:b5ff:fe22:fd0a
destination address: fe80::3fe6:b5ff:fe22:fd0b
00000000  01
~~ SNIP  1 - size:  20 byte, type: NETTYPE_NETIF (-1)
if_pid: 6  rssi: 0  lqi: 0
flags: 0x0
src_l2addr: 3E:E6:B5:22:FD:0B
dst_l2addr: 3E:E6:B5:22:FD:0A
~~ PKT    -  2 snips, total size:  61 byte

make: Leaving directory '/home/leandro/Work/RIOT/tests/gnrc_netif'
```
</details>

**Pull request merged**
