### PR TITLE
make: add snippets support

### PR DESCRIPTION
**Pull request by kaspar030**
First try at #4290.

Whenever a module dir contains "NNname.c.snip" (with NN a decimal), the makefile concatenates that file with all other "NNname.c.snip" of other modules into $(BINDIR)/snippets/name.c and compiles all combined files into a "snippets" module.

For all but the application module, the snippets get enclosed by ```#ifdef MODULE_X ... #endif```

That way, static array definitions, functions, ... can be spread over multiple files in all module directories.

Imagine shell commands, auto_init, saul parameters, device driver parameters, coap endpoints, .. can be defined by just adding a snippet where it belongs.

You've hooked up another radio (same as onboard) to your board? Just drop a file "01at86rf2xx_params.c.snip" into your application folder, containing only the array entry for the added device.

Your module auto_inits? Just drop a 01auto_init.c.snip into it's folder, no more rebase conflicts in sys/auto_init/auto_init.c.

What do you guys think?

### CODE REVIEW

**Comment by kaspar030** [comment]
I've changed xtimer's auto init to use snippets in order to show how this is supposed to be used.

**Comment by gebart** [comment]
Couldn't you just use `#include "01snip.c"`... and so on?

**Comment by kaspar030** [comment]
@gebart Yes, much simpler.

**Comment by DipSwitch** [comment]
Nice one! :)

**Comment by kaspar030** [comment]
Fun thing to try:

```
# cd examples/hello-world
# echo 'puts("wooohooo!!");' > 10auto_init.c.snip
# make clean all term
```

**Comment by Kijewski** [comment]
I like the idea. :+1: Maybe add an underscore after the index, too, for better readability?

**Comment by gebart** [comment]
I have some thoughts regarding file names:

`.c.snip` will confuse many IDEs which set syntax highlighting based on `*.c`, is it possible to fix without getting them sucked into the normal build rules?

Since the `name` part of `NNname.c.snip` is what groups them together, would it make sense to change the pattern to `nameNN.c.snip` to also get the files grouped together when listing files alphabetically, in case there are multiple snips in the same directory?

**Comment by kaspar030** [comment]
> .c.snip will confuse many IDEs which set syntax highlighting based on *.c, is it possible to fix without getting them sucked into the normal build rules?

I thought about that, it might be possible to use make filters filters if they're called something like *.snip.c. Then we'd have to create filter rules for all filetypes, currently this would probably also work with headers.

I'll look into it...

**Comment by kaspar030** [comment]
> Since the name part of NNname.c.snip is what groups them together, would it make sense to change the pattern to nameNN.c.snip to also get the files grouped together when listing files alphabetically, in case there are multiple snips in the same directory?

good idea!

**Comment by kaspar030** [comment]
Ok, the snippets are now called ```<filename>.snipNN.ext```.

@Kijewski I tried with a '_' between snip and number, but somehow I liked it better like this. What do you think?

**Comment by kaspar030** [comment]
I'll close this in favor of a linker-script based solution.

**Pull request closed without merging**
