### PR TITLE
boards/pba-d-01-kw2x: add comments to override CPU_MODEL

### PR DESCRIPTION
**Pull request by kYc0o**
~~Trivial change to remove unnecessary comments on pba-d-01-kw2x Makefile.~~

Changed to comments added and make the `CPU_MODEL` variable overridable.

### CODE REVIEW

**Comment by smlng** [comment]
what the CPU model used for anyway? I guess for openocd somehow? Just for completeness is the current setting right or does it work by chance. Because the [wiki](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-Phytec-phyWAVE-KW22) states that the MCU is actually `kw22d512` and **not** `kw21d256` as set here. 

Regarding removal of the comments, it might still be good as an informative hint to name all possible MCUs?

**Comment by cgundogan** [comment]
>Because the wiki states that the MCU is actually kw22d512 and not kw21d256 as set here.

yep, a quick `git grep` also reveals, that `kw22d512` is used in `boards/pba-d-01-kw2x/dist/openocd.cfg:    set _CHIPNAME kw22d512`.

Off-topic: @smlng no irc today?

**Comment by gebart** [comment]
The CPU model is also used to select the right linker script and (on some CPUs) which vendor header to include from cpu_conf.h

**Comment by kYc0o** [comment]
Well the board I have at hand is a kw21d256. There is other models which have the kw22d512? If so, we need to find a way to officially support it since as @gebart says this is also used to select the correct linker script. Although it's a bit strange to sell different models of the same board with the same name.

**Comment by kYc0o** [comment]
Just notice the "x" on the board's name. In this case, I think this board name should be used as the common path for common code (I guess for now all the code is common) and create folders for the actual boards with the correct names.

**Comment by smlng** [comment]
Mine (purchased mid 2016) says `MKW22D512VHA5...` something something

**Comment by smlng** [comment]
btw. works with current configuration without any tweaks or problems.

**Comment by gebart** [comment]
Since they are very similar, a binary built for the kw21dn256 will likely work just fine on a kw22dn512, but not the other way around because of the increased memory size on the kw22dn512.

**Comment by smlng** [comment]
yeah sure, questions is: do we need to care about the mem sizes right now? And if so, how can we do that without much noise?

**Comment by kYc0o** [comment]
I think this is a "rare" case on which the same board with the same peripherals has three different versions of MCU. I'd propose to create a folder for each board including only the needed Makefile and referencing to the current folder for the common code.

**Comment by smlng** [comment]
NO!! Please do not create 4 folders for `pba-d-01-kw2x`, that's exactly what I meant when I said

> without too much noise

Better leave as is then.

**Comment by kYc0o** [comment]
First, I don't know from where this name comes from. Second, do we or don't we support the three cpu's? Third, what's so wrong in having three new folders for actually three different boards? Even though they share all the surrounding hardware, the chips are different, so they need to be compiled (linked) differently.

For the current case: I don't think "uncomment the line to get your cpu supported" is the way to go for an upstream repository. So in my opinion we need a solution for the support of this board(s).

**Comment by kYc0o** [comment]
>First, I don't know from where this name comes from. Second, do we or don't we support the three cpu's? Third, what's so wrong in having three new folders for actually three different boards? Even though they share all the surrounding hardware, the chips are different, so they need to be compiled (linked) differently.

Even more important, for Murdock only one board exists, which leads that code is not being compiled for the other three options.

**Comment by smlng** [comment]
For all I know: the current setting works without any manual adaption for all board variant currently used with RIOT. So I don't see any benefit in acting  prematurely, here. Other then creating commits, that might need revision later on again.

**Comment by kYc0o** [comment]
The current code compiles for the smallest cpu supported, which blocks the higher end chips to be added in some tests and examples for which they have enough memory to be compiled by Murdock.

I think this is a reason enough to have them officially supported and tested by the CI.

**Comment by aabadie** [comment]
> I'd propose to create a folder for each board including only the needed Makefile and referencing to the current folder for the common code.

With the actual board management with Makefile, I think this is the right solution.

For the moment, I think we can close this one and keep it as memo.

**Comment by miri64** [comment]
This PR is approved, Murdock is happy and the discussion seems to weir in a different direction from the proposed patch. So why not merge and make an issue about dividing up the pba-d-01-kw2x configuration?

**Comment by smlng** [comment]
I (strongly) agree with @haukepetersen, which is exactly what I already tried to point out some comments above.

**Comment by kYc0o** [comment]
I'm not opposed to Hauke's proposition, it's just that for me there's a way to have "all boards" supported with the less duplication of code as possible without the need to dig in makefiles to find if my board is supported (or why my big code doesn't fit if the board I have is supposed to have 512K).

I guess we're making an exception with this board but if this is a solution I think there are some other boards on which we could do the same and delete some board folders... anyways, I'll address Hauke's comments asap.

**Comment by haukepetersen** [comment]
thanks!

In general: I think there is no right/wrong when deciding to have a single board folder hosting many variants vs. having a separate board folder for each variant of a board (-> e.g. look at all the nucleo boards...). I guess we should decide on a case-to-case basis what is most fitting?! The good thing, from experience there are not too many boards which have (significant) different variants, so we should be fine?

**Comment by kYc0o** [comment]
Comments addressed.

**Comment by kYc0o** [comment]
and go!

**Pull request merged**
