### PR TITLE
cpu/samd21/periph/i2c: power off did enable instead of disable

### PR DESCRIPTION
**Pull request by keestux**
The i2c_poweroff did not disable.

### CODE REVIEW

**Comment by keestux** [comment]
After sending the PR I found another issue. The wait for SYNCBUSY was done **before** enabling or disabling. It should be done **after**.

**Comment by PeterKietzmann** [comment]
ACK. @keestux would you shorten your second commit message please? E.g. something like this would be usual: *samd21/i2c: wait for SYNCBUSY after power_on/off*. @kYc0o how do we proceed with the release? Do we need a backport of this PR?

**Comment by kYc0o** [comment]
This is solving a bug so it needs to come into the release, so yes we need a backport.

**Comment by kYc0o** [comment]
uhm... strange errors with Murdock and python scripts... it seems there's no stack? @kaspar030

**Comment by keestux** [comment]
@PeterKietzmann Hmm. OK. What is the max length of the commit message? 50, as in "the 50/72 rule"?

**Comment by PeterKietzmann** [comment]
@keestux honestly I'm not aware of such strict rule in our contribution guideline, but 50 sounds good as a rule of thumb. However, I usually comment on the commits length whenever the first line is so long that GitHub shows "`...`". But this time I was mistaken cause your commit isn't too long. There 's just a further line. So again, ACK and go

**Comment by keestux** [comment]
@PeterKietzmann You have to clarify "backport" in combination with "release branch" (which you have as a link to 2016.07-branch. Because the PR is already merged.

**Comment by kYc0o** [comment]
Backporting wasn't needed, since we only merged bug fixes the release branch stayed even with current master.

**Pull request merged**
