### PR TITLE
boards/nucleof7*: SPI and refactoring

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description
- Refactored core clock settings for nucleo-f7* boards
- Added SPI for nucleo-f767zi

### Testing procedure
- Clock settings:
    - Proof read if `cfg_clock_216_8_1.h` contains the same numbers as each board contained previously
- SPI:
    - Hook up you're favorite SPI device (with RIOT support) and connect it to the board. (I tested with the CC1101 transceiver and it worked for me.)

### Issues/PRs references
None

### CODE REVIEW

**Comment by maribu** [comment]
Someone currently reviewing? Otherwise I'd squash right away.

**Comment by maribu** [comment]
> maribu removed the CI: ready for build label 23 seconds ago

Wrong tab :-(

**Comment by maribu** [comment]
@aabadie: Did you already found time to test the SPI?

**Comment by maribu** [comment]
@aabadie: Did you found time to test the SPI? I could alternatively ask a colleague of me to test and report the results here.

**Comment by maribu** [comment]
@aabadie: Thanks for the review. I squashed and now all is ready to merge

**Comment by aabadie** [comment]
> I squashed and now all is ready to merge

Let's go then ! Sorry that it took me some time before I have a look at this.

**Pull request merged**
