### PR TITLE
cpu/stm32:  get the cpuid address from the UID_BASE constant defined in CMSIS

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is an attempt to remove the hardcoded cpuid address defined for each STM32 families (and sometimes for a specific model).
Some CMSIS headers were a bit outdated so had to be updated: all f2xx, f103xx, f334, f72x.

While updating the CMSIS, I also noticed that all CCR registers for timer peripherals have to be patched. I'd like to revert this and adapt the timer peripheral driver accordingly.

### Testing procedure

- A green Murdock
- Verify that `tests/periph_cpuid` is still working and return the same result compared to master
- Maybe also run `compile_and_test_for_board.py` on some of the affected STM32 boards.

### Issues/PRs references

None

### CODE REVIEW

**Comment by bergzand** [comment]
A cleanup that adds 40.000K lines of code? :thinking:

**Comment by aabadie** [comment]
> A cleanup that adds 40.000K lines of code?

There is probably a lot more defines added in the CMSIS files.

**Comment by bergzand** [comment]
@aabadie Could you split the CMSIS headers to their own PRs, maybe even a PR per family for easy reviewing.

**Comment by aabadie** [comment]
rebased on top of #14143

**Comment by bergzand** [comment]
Please rebase

**Comment by aabadie** [comment]
rebased and restarting Murdock (but this time without the "Waiting for another PR" label set...)

**Comment by bergzand** [comment]
I see a difference in the binary for the p-nucleo-wb55 board

**Comment by bergzand** [comment]
> I see a difference in the binary for the p-nucleo-wb55 board

All other stm32 boards produce identical binaries with and without these commits

**Comment by aabadie** [comment]
> I see a difference in the binary for the p-nucleo-wb55 board

interesting, I'll have a look

**Comment by aabadie** [comment]
I tested on the board and indeed the cpuid returned is different. That may explain the difference. The code size is exactly the same btw. Let's verify which one is the right version :)

**Comment by aabadie** [comment]
this PR:
```
CPUID_LEN: 12
CPUID: 0x3f 0x00 0x31 0x00 0x05 0x50 0x36 0x30 0x52 0x38 0x35 0x20
```

master:
```
CPUID_LEN: 12
CPUID: 0xff 0x3f 0x00 0x00 0x26 0xe1 0x80 0x00 0xf0 0xff 0xff 0xff
```

**Comment by aabadie** [comment]
Looking at the CMSIS file, the previous address was set to UID64_BASE. The reference manuel points to the value in UID_BASE (96bits).
I think we should keep UID_BASE, like for other STM32 families. This is what this PR is doing. What do you think ?

**Comment by benpicco** [comment]
I imagine by manually specifying this address, there is a lot of potential for error to slip in.
And since those bytes appear 'random', it would not be caught.

So I fully support this cleanup!

**Pull request merged**
