### PR TITLE
arduino-due: add riotboot support

### PR DESCRIPTION
**Pull request by emmanuelsearch**
### Contribution description

This PR attempts to add riotboot requirements for the arduino due board.

### Testing procedure

Still needs some preparatory work, but ultimately the test below should succeed:

make -C tests/riotboot BOARD=arduino-due flash test

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
Caveat: I don't have the hardware. Can someone test on his/her board?

**Comment by emmanuelsearch** [comment]
@cladmi I'm not sure about the use (or not?) of ROM_OFFSET in the present case (see page 37 of [this doc](https://www.pololu.com/file/0J600/at91sam-datasheet.pdf))

**Comment by emmanuelsearch** [comment]
so apparently no need for ROM_OFFSET ;)

**Comment by emmanuelsearch** [comment]
however there is a need for `periph_flashpage` ...

**Comment by aabadie** [comment]
> however there is a need for periph_flashpage ...

not if you only want to add support for riotboot.

Otherwise, arduino-due is flashed using bossa so the Makefile of this tool needs to be adapted to support the offset parameter.

**Comment by cladmi** [comment]
For handling with `bossac`, the `-e` (`--erase`) should be removed to not erase the whole flash. It is now the becoming the standard for most of our flasher.

For `--offset`, the question is how is it handled internally. Does it take the `8kb` of bootloader into account by default or should it be done with
```
$(if $(ROM_OFFSET),--offset $((8192k+$(ROM_OFFSET))))
```

**Comment by emmanuelsearch** [comment]
@aabadie yes I was looking too much ahead aiming to support #11818 as next step...

**Comment by cladmi** [comment]
One thing I noticed while doing some other cleanups, is that almost all boards using `bossa` currently define `ROM_OFFSET` to `0x2000 == 8192`.

So it may be better to harmonize `arduino-due` too (and `sodaq-explorer`).

<details><summary>git grep -C 2 bossa.inc.mk</summary>

```
git grep -C 2 bossa.inc.mk
boards/common/arduino-due/Makefile.include-# setup flasher (using BOSSA)
boards/common/arduino-due/Makefile.include-export BOSSA_ARDUINO_PREFLASH = yes
boards/common/arduino-due/Makefile.include:include $(RIOTMAKE)/tools/bossa.inc.mk
--
boards/common/arduino-mkr/Makefile.include-  # such bootloader.
boards/common/arduino-mkr/Makefile.include-  ROM_OFFSET ?= 0x2000
boards/common/arduino-mkr/Makefile.include:  include $(RIOTMAKE)/tools/bossa.inc.mk
boards/common/arduino-mkr/Makefile.include-endif
boards/common/arduino-mkr/Makefile.include-
--
boards/feather-m0/Makefile.include-  # such bootloader.
boards/feather-m0/Makefile.include-  ROM_OFFSET ?= 0x2000
boards/feather-m0/Makefile.include:  include $(RIOTMAKE)/tools/bossa.inc.mk
boards/feather-m0/Makefile.include-endif
boards/feather-m0/Makefile.include-
--
boards/sensebox_samd21/Makefile.include-  # such bootloader.
boards/sensebox_samd21/Makefile.include-  ROM_OFFSET ?= 0x2000
boards/sensebox_samd21/Makefile.include:  include $(RIOTMAKE)/tools/bossa.inc.mk
boards/sensebox_samd21/Makefile.include-endif
boards/sensebox_samd21/Makefile.include-
--
boards/sodaq-autonomo/Makefile.include-# preflashed on it. ROM_OFFSET skips the space taken by such bootloader.
boards/sodaq-autonomo/Makefile.include-ROM_OFFSET ?= 0x2000
boards/sodaq-autonomo/Makefile.include:include $(RIOTMAKE)/tools/bossa.inc.mk
boards/sodaq-autonomo/Makefile.include-
boards/sodaq-autonomo/Makefile.include-# setup the boards dependencies
--
boards/sodaq-explorer/Makefile.include-# preflashed on it
boards/sodaq-explorer/Makefile.include-export LINKER_SCRIPT ?= $(RIOTCPU)/sam0_common/ldscripts/$(CPU_MODEL)_arduino_bootloader.ld
boards/sodaq-explorer/Makefile.include:include $(RIOTMAKE)/tools/bossa.inc.mk
boards/sodaq-explorer/Makefile.include-
boards/sodaq-explorer/Makefile.include-# setup the boards dependencies
--
boards/sodaq-one/Makefile.include-# preflashed on it. ROM_OFFSET skips the space taken by such bootloader.
boards/sodaq-one/Makefile.include-ROM_OFFSET ?= 0x2000
boards/sodaq-one/Makefile.include:include $(RIOTMAKE)/tools/bossa.inc.mk
boards/sodaq-one/Makefile.include-
boards/sodaq-one/Makefile.include-# setup the boards dependencies
--
boards/sodaq-sara-aff/Makefile.include-# preflashed on it. ROM_OFFSET skips the space taken by such bootloader.
boards/sodaq-sara-aff/Makefile.include-ROM_OFFSET ?= 0x2000
boards/sodaq-sara-aff/Makefile.include:include $(RIOTMAKE)/tools/bossa.inc.mk
boards/sodaq-sara-aff/Makefile.include-
boards/sodaq-sara-aff/Makefile.include-# setup the boards dependencies
```
</details>

**Comment by aabadie** [comment]
Just in case, I adapted the makefile bossa with an offset parameter. In fact, for bossa, the offset starts at 0 after the Arduino bootloader. And it must be a multiple of flash page (256B on SAM3) so should be ok with riotboot len shift.
If others want to test, I pushed this change to this PR in c453d8f: I can flash a combined bootloader with slot0 and get a running firmware but for some reason flashing directly slot1 doesn't work.

**Comment by cladmi** [comment]
Forget what I said with `ROM_OFFSET` and `bossa` in my previous comment, I was mixing `ROM_OFFSET` and `IMAGE_OFFSET` when writing it ><

**Comment by aabadie** [comment]
Still useful I think

**Pull request closed without merging**
