### PR TITLE
tests/sys/psa_crypto*: Fix failing tests

### PR DESCRIPTION
**Pull request by Einhornhool**
### Contribution description
PSA Crypto tests fail because of multiple issuse:

1. Elliptic curve software implementations need larger stacks than the default stack size, so I increased that to 4096 bytes
2. Secure element tests fail when running them without SE's attached. Since currently there are no SEs connected for testing, this PR removes the `test` folder from the SE tests. This way they will still be built (to test build configurations), but not run anymore.

### Testing procedure
Run `psa_crypto_ecdsa` and `psa_crypto_eddsa` without runtime errors. 

### Issues/PRs references
Alternative fix for #20152 and #20150

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
Would you mind to also revert commits 167a70cd0fe72309236f0014a5ec76b5060c8715 and 754bbe4e6d6392c816243278ab9d8456b42c73ce? Those should no longer be needed.

**Comment by Einhornhool** [comment]
> Would you mind to also revert commits [167a70c](https://github.com/RIOT-OS/RIOT/commit/167a70cd0fe72309236f0014a5ec76b5060c8715) and [754bbe4](https://github.com/RIOT-OS/RIOT/commit/754bbe4e6d6392c816243278ab9d8456b42c73ce)? Those should no longer be needed.

Sure, done!

**Review by mguetschow — APPROVED** [review]
LGTM, thanks for fixing!

**Comment by maribu** [comment]
> ❌ check-commits / check-commits (commit-msg) (pull_request)

This still needs to be addressed. The first line of the commit message cannot exceed 80 chars.

Please squash at will.

**Comment by maribu** [comment]
> cannot exceed 80 chars.

Sorry, my bad. In fact, 72 chars. I assume this is to allow `git log` to indent the message by 8 chars and still be readable on a VT100.

**Comment by Einhornhool** [comment]
> The CI doesn't like your commit messages (too long to display on a VT100 from 1978).

I saw, if everything's fine I'm going to squash them anyways

**Comment by MrKevinWeiss** [comment]
Ugg not this again.  It seems you have to chase the memory increases.  I enabled run hardware tests but maybe we also need to do the hack in the `.murdock` file to test only this app.

**Comment by mguetschow** [comment]
Couldn't you use `cd test/sys/psa_crypto_eddsa && ../../dist/tools/insufficient_memory/create_makefile.ci.sh` to create the respective file? Done that in the past for my PRs, takes some time but worked reliably.

**Comment by MrKevinWeiss** [comment]
Yup, we also want to run the hardware checks though.

**Comment by MrKevinWeiss** [comment]
Thanks @Einhornhool and @maribu for going pushing this forward!

**Comment by maribu** [comment]
Note that on the long term we should still find a better solution. E.g. one of those:

- Let PSA not depend optionally on the secure module (+ implementation of the PSA glue) required
- Pull in a software-only fallback if the optional features are not used

**Pull request merged**
