### PR TITLE
unittests/tests-ipv?_addr: fix some uninitialized variable bugs

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

prevents gcc-11 error:

```
In file included from /home/kaspar/src/riot/sys/include/embUnit/embUnit.h:47,
                 from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:17:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c: In function ‘test_ipv4_addr_to_str__result_NULL’:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:59:22: error: ‘a’ may be used uninitialized [-Werror=maybe-uninitialized]
   59 |     TEST_ASSERT_NULL(ipv4_addr_to_str(NULL, &a, IPV4_ADDR_MAX_STR_LEN));
/home/kaspar/src/riot/sys/include/embUnit/AssertImpl.h:70:47: note: in definition of macro ‘TEST_ASSERT_NULL’
   70 |         __typeof__(pointer_) ____pointer__ = (pointer_); \
      |                                               ^~~~~~~~
In file included from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:20:
/home/kaspar/src/riot/sys/include/net/ipv4/addr.h:72:7: note: by argument 2 of type ‘const ipv4_addr_t *’ to ‘ipv4_addr_to_str’ declared here
   72 | char *ipv4_addr_to_str(char *result, const ipv4_addr_t *addr, uint8_t result_len);
      |       ^~~~~~~~~~~~~~~~
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:57:17: note: ‘a’ declared here
   57 |     ipv4_addr_t a;
      |                 ^
cc1: all warnings being treated as errors
In file included from /home/kaspar/src/riot/sys/include/embUnit/embUnit.h:47,
                 from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:17:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c: In function ‘test_ipv4_addr_to_str__result_NULL’:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:59:22: error: ‘a’ may be used uninitialized [-Werror=maybe-uninitialized]
   59 |     TEST_ASSERT_NULL(ipv4_addr_to_str(NULL, &a, IPV4_ADDR_MAX_STR_LEN));
/home/kaspar/src/riot/sys/include/embUnit/AssertImpl.h:70:47: note: in definition of macro ‘TEST_ASSERT_NULL’
   70 |         __typeof__(pointer_) ____pointer__ = (pointer_); \
      |                                               ^~~~~~~~
In file included from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:20:
/home/kaspar/src/riot/sys/include/net/ipv4/addr.h:72:7: note: by argument 2 of type ‘const ipv4_addr_t *’ to ‘ipv4_addr_to_str’ declared here
   72 | char *ipv4_addr_to_str(char *result, const ipv4_addr_t *addr, uint8_t result_len);
      |       ^~~~~~~~~~~~~~~~
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:57:17: note: ‘a’ declared here
   57 |     ipv4_addr_t a;
      |                 ^
cc1: all warnings being treated as errors
```

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by kaspar030** [comment]
Same problem in ipv6 tests, sorry, I pushed it here.

**Comment by kaspar030** [comment]
... shortened commit subjects

**Review by miri64 — APPROVED** [review]
Re-ACK. Saw this during release test testing today as well on my machine. However, wasn't there a problem with `= {0}` on some machines? At least I seem to remember something like that (should not block this PR however).

**Comment by miri64** [comment]
(can also be seen live [here](https://github.com/RIOT-OS/Release-Specs/issues/227#issuecomment-874236990))

**Comment by miri64** [comment]
Please provide a backport, @kaspar030

**Comment by kaspar030** [comment]
> However, wasn't there a problem with `= {0}` on some machines? At least I seem to remember something like that (should not block this PR however).

I'd be interested in that! The only think I remember is that it might call out to memset, which might not inline. I dropped some `= {0}` in the hot msg code at some point for that reason.

**Comment by miri64** [comment]
Really faded memory, but something something Mac OSX, I believe. Will try to remember to have a look tomorrow.

**Comment by miri64** [comment]
I digged a bit deeper in the git history, but couldn't find anything to clear up my memory :-/.

**Pull request merged**
