### PR TITLE
pkg/nimble: bump version, rmv patches

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Patches were merged upstream so can be removed, this only affects building with `mynewt-core`, tested building with and without on examples/nimble_gatt`

### Testing procedure

- `USEPKG=mynewt-core BOARD=nrf52840-mdk make -C examples/nimble_gatt/ flash term -j`

```
2021-09-09 13:51:55,962 # service 'device info: manufacturer' callback triggered
2021-09-09 13:51:55,967 # This is RIOT! (Version: 2021.10-devel-591-g24a13-HEAD)
2021-09-09 13:51:55,967 # 
2021-09-09 13:51:55,967 # 
2021-09-09 13:51:56,059 # service 'device info: manufacturer' callback triggered
2021-09-09 13:51:56,064 # This is RIOT! (Version: 2021.10-devel-591-g24a13-HEAD)
2021-09-09 13:51:56,064 # 
2021-09-09 13:51:56,064 # 
2021-09-09 13:51:56,157 # service 'device info: manufacturer' callback triggered
2021-09-09 13:51:56,162 # This is RIOT! (Version: 2021.10-devel-591-g24a13-HEAD)
2021-09-09 13:51:56,162 # 
2021-09-09 13:51:56,162 # 
2021-09-09 13:51:58,252 # service 'device info: model' callback triggered
2021-09-09 13:51:58,260 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:51:58,260 # 
2021-09-09 13:51:58,350 # service 'device info: model' callback triggered
2021-09-09 13:51:58,357 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:51:58,357 # 
2021-09-09 13:51:58,447 # service 'device info: model' callback triggered
2021-09-09 13:51:58,455 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:51:58,455 # 
2021-09-09 13:51:58,545 # service 'device info: model' callback triggered
2021-09-09 13:51:58,552 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:51:58,552 # 
2021-09-09 13:52:00,835 # service 'rw demo' callback triggered
2021-09-09 13:52:00,839 # access to characteristic 'rw demo (read-only)'
2021-09-09 13:52:00,841 # new random number: 3
```

- `BOARD=nrf52840-mdk make -C examples/nimble_gatt/ flash term -j7`

```
2021-09-09 13:55:02,382 # service 'device info: manufacturer' callback triggered
2021-09-09 13:55:02,389 # This is RIOT! (Version: 2021.10-devel-591-g24a13-pr_nimble_bump_ver_cleanup)
2021-09-09 13:55:02,389 # 
2021-09-09 13:55:02,389 # 
2021-09-09 13:55:02,480 # service 'device info: manufacturer' callback triggered
2021-09-09 13:55:02,486 # This is RIOT! (Version: 2021.10-devel-591-g24a13-pr_nimble_bump_ver_cleanup)
2021-09-09 13:55:02,486 # 
2021-09-09 13:55:02,487 # 
2021-09-09 13:55:02,577 # service 'device info: manufacturer' callback triggered
2021-09-09 13:55:02,584 # This is RIOT! (Version: 2021.10-devel-591-g24a13-pr_nimble_bump_ver_cleanup)
2021-09-09 13:55:02,584 # 
2021-09-09 13:55:02,584 # 
2021-09-09 13:55:02,675 # service 'device info: manufacturer' callback triggered
2021-09-09 13:55:02,681 # This is RIOT! (Version: 2021.10-devel-591-g24a13-pr_nimble_bump_ver_cleanup)
2021-09-09 13:55:02,681 # 
2021-09-09 13:55:02,682 # 
2021-09-09 13:55:04,088 # service 'device info: model' callback triggered
2021-09-09 13:55:04,095 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:55:04,095 # 
2021-09-09 13:55:04,185 # service 'device info: model' callback triggered
2021-09-09 13:55:04,192 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:55:04,192 # 
2021-09-09 13:55:04,283 # service 'device info: model' callback triggered
2021-09-09 13:55:04,290 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:55:04,290 # 
2021-09-09 13:55:04,380 # service 'device info: model' callback triggered
2021-09-09 13:55:04,387 # You are running RIOT on a(n) nrf52840-mdk board, which features a(n) nrf52 MCU.
2021-09-09 13:55:04,388 # 
2021-09-09 13:55:07,061 # service 'rw demo' callback triggered
2021-09-09 13:55:07,065 # access to characteristic 'rw demo (read-only)'
2021-09-09 13:55:07,067 # new random number: 3
```

### Issues/PRs references

Follow up to https://github.com/RIOT-OS/RIOT/pull/16623 and  #16348

### CODE REVIEW

**Comment by haukepetersen** [comment]
Nice. Will give this a test-run and let you know if everything runs smooth

**Review by haukepetersen — APPROVED** [review]
Run some of the plain NimBLE examples as well as `autoconn` and `gnrc_networking`, all still works as expected -> ACK

**Comment by haukepetersen** [comment]
and always good to see these patches disappear :-)

**Comment by haukepetersen** [comment]
Hmm, Murdock is unable to fetch the latest NimBLE comit. I verified again that the commit hash in this PR is correct, so might this be a Murdock issue?

**Comment by fjmolinas** [comment]
> Hmm, Murdock is unable to fetch the latest NimBLE comit. I verified again that the commit hash in this PR is correct, so might this be a Murdock issue?

re-trigger?

**Comment by haukepetersen** [comment]
worth a try...

**Comment by haukepetersen** [comment]
All green -> go!

**Pull request merged**
