### PR TITLE
net: NETOPT_MAX_{PACKET_SIZE -> PDU_SIZE}

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR renames `NETOPT_MAX_PACKET_SIZE` into `NETOPT_MAX_PDU_SIZE`, which should be clearer. The documentation is updated accordingly.

### Testing procedure

Please verify that the new name and the updated documentation make sense. Apart from that Murdock will verify that this does not break anything.

### Issues/PRs references

PR https://github.com/RIOT-OS/RIOT/pull/10340 implemented `netdev_driver_t::get()` for `NETOPT_MAX_PACKET_SIZE` incorrectly and returned the maximum frame size including the layer 2 header. This rename should make clear that the maximum PDU size should be returned instead of the full frame size.

----
Update 1: Changed `NETOPT_MAX_L2_PDU_SIZE` to `NETOPT_MAX_PDU_SIZE`, as it is not only used to retrieve the layer 2 PDU.

### CODE REVIEW

**Comment by miri64** [comment]
This is an API change just for naming, so I have to think about this for a while. But as a less intrusive alternative: how about just introducing `NETOPT_MAX_L2_PDU_SIZE` for now with the same functionality as `NETOPT_MAX_PACKET_SIZE` (`case` in the drivers can just be added above or below the `case NETOPT_MAX_PACKET_SIZE`), and slowly fade out `NETOPT_MAX_PACKET_SIZE` support over the next two release cycles, as I did with `NETOPT_IPV6_IID`.

**Comment by miri64** [comment]
Would also have the added benefit, that you can open PRs per device so it can be tested per device and doesn't require tests for all devices.

**Comment by maribu** [comment]
Would you really insist on testing this? The `enum` value will still be identical, so the exact same machine code is generated. I don't see how this possibly could break anything.

**Comment by miri64** [comment]
> Would you really insist on testing this? The `enum` value will still be identical, so the exact same machine code is generated. I don't see how this possibly could break anything.

No, but regardless of that the outlined approach would still make the transition easier for me and possible users of the current API.

**Comment by maribu** [comment]
How about adding

```C
#define NETOPT_MAX_PACKET_SIZE NETOPT_MAX_L2_PDU_SIZE
```

instead in order to keep out of master code working, when it is still using `NETOPT_MAX_PACKET_SIZE`?

This would also make sure that duplicated code like

```C
switch (netopt) {
    case NETOPT_MAX_PACKET_SIZE:
    case NETOPT_MAX_L2_PDU_SIZE:
        ....
}
```

is not needed.

Still sooner or later users of `NETOPT_MAX_PACKET_SIZE` would need to adapt their code. So this is not reducing the effort required to adapt, but merely delay it to some future point in time. I personally favor doing renaming in one concentrated effort and then be done with it.

**Comment by miri64** [comment]
> Still sooner or later users of `NETOPT_MAX_PACKET_SIZE` would need to adapt their code. So this is not reducing the effort required to adapt, but merely delay it to some future point in time. I personally favor doing renaming in one concentrated effort and then be done with it.

Unless absolutely impossible, we usually deprecate an API component first before we remove it, so I'd prefer the `#define` solution more. This can get a `@deprecated` note directly in its documentation, so it will appear in the [deprecated list](http://doc.riot-os.org/deprecated.html). Also a referencing note should be added to `NETOPT_MAX_L2_PDU_SIZE` so users are made aware that this was a rename.

**Comment by maribu** [comment]
OK. I will adapt this PR. If I understood you correctly, you would prefer to have the commits like this:

commit 1: Rename, update doc, add compatibility with old name using the `#define`
commit 2: Adapt first driver
commit 3: Adapt second driver
commit n+1: Adapt nth driver

Right? May I force push that directly?

**Comment by miri64** [comment]
> Right? May I force push that directly?

yes and yes :-)

**Comment by maribu** [comment]
Hmm, 

``` C
res = gnrc_netapi_get(iface, NETOPT_MAX_L2_PDU_SIZE, GNRC_NETTYPE_IPV6, &u16, sizeof(u16));
```

to obtain the MTU would be even more confusing than `NETOPT_MAX_PACKET_SIZE`. Maybe better `NETOPT_MAX_PDU_SIZE` to be agnostic to which layer to refer? If so, may I directly force push?

**Comment by miri64** [comment]
Sounds good. And you may force push.

**Comment by maribu** [comment]
In the first force push I forgot to fix the alignment of code (`NETOPT_MAX_PDU_SIZE` is three letters shorter than `NETOPT_MAX_L2_PDU_SIZE`). I fixed that and squashed right away. So the second force push diff will be empty, the first is the one to look at

**Comment by miri64** [comment]
Actually I still found some occurrences of `NETOPT_MAX_PACKET_SIZE`. Is that intentional?

```
$ git grep -c "\<NETOPT_MAX_PACKET_SIZE\>"
release-notes.txt:2
sys/include/net/netopt.h:2
tests/driver_at86rf2xx/cmd.c:1
tests/gnrc_ipv6_nib/main.c:1
tests/gnrc_ipv6_nib/mockup_netif.c:1
tests/gnrc_ipv6_nib_6ln/main.c:1
tests/gnrc_ipv6_nib_6ln/mockup_netif.c:1
tests/gnrc_ndp/main.c:1
tests/gnrc_netif/common.c:3
tests/gnrc_netif/main.c:8
tests/gnrc_sixlowpan/main.c:1
tests/lwip_sock_ip/stack.c:2
tests/lwip_sock_udp/stack.c:2
```

**Comment by maribu** [comment]
I forgot about the tests. The hit in the header in sys/net will be the compatibility code. I'll fix it tonight :-)

**Comment by maribu** [comment]
The tests are also converted now :-) Btw: One mare user of `NETOPT_MAX_PACKET_SIZE` was added in the meantime. May I rebase to tackle that one as well?

**Comment by maribu** [comment]
Did the rebase here: https://github.com/maribu/RIOT/tree/max_pdu_size (and also changed the new user and already squashed there).

This was the new user of `NETOPT_MAX_PACKET_SIZE` is PR https://github.com/RIOT-OS/RIOT/pull/10923 btw:

``` diff
diff --git a/sys/shell/commands/sc_gnrc_netif.c b/sys/shell/commands/sc_gnrc_netif.c
index b72c3caa8..d9777589f 100644
--- a/sys/shell/commands/sc_gnrc_netif.c
+++ b/sys/shell/commands/sc_gnrc_netif.c
@@ -505,7 +505,7 @@ static void _netif_list(kernel_pid_t iface)
                                    line_thresh);
     line_thresh = _netif_list_flag(iface, NETOPT_CHANNEL_HOP, "CHAN_HOP",
                                    line_thresh);
-    res = gnrc_netapi_get(iface, NETOPT_MAX_PACKET_SIZE, 0, &u16, sizeof(u16));
+    res = gnrc_netapi_get(iface, NETOPT_MAX_PDU_SIZE, 0, &u16, sizeof(u16));
     if (res > 0) {
         printf("L2-PDU:%" PRIu16 " ", u16);
         line_thresh++;
```

**Comment by miri64** [comment]
> May I rebase to tackle that one as well?

I'd say, try not to run after changes that were introduced later, otherwise the PR might easily get stalled (this is why we have the deprecation instead of the removal), but since you already did it, please go ahead ;-).

**Comment by miri64** [comment]
There is an (due to an update of `cppcheck` on the CI server unrelated) `cppcheck` warning in https://github.com/RIOT-OS/RIOT/blob/a4549f089fcc780021ae7cadb6ba3212a036256f/tests/gnrc_ipv6_nib_6ln/main.c#L1079 Do you mind piggybacking a fix for this?

**Comment by maribu** [comment]
Sure, will do. (I'm not near any PC right now (not counting my phone), might take until tonight...)

**Comment by maribu** [comment]
@miri64: Can you have a second look at https://github.com/RIOT-OS/RIOT/pull/10905/commits/9216607163f48b805e39874d086e983b0226f0e2. I'm 99.999% sure that `pio` is not changed in the "then-case" of `if (pio)`, so I changed `if (!pio)` to `else`. But it would be nice if you can verify that I did not overlook something.

**Comment by miri64** [comment]
Looks alright to me. I must have been drunk or something when I did that piece of code ^^"

**Comment by maribu** [comment]
> I must have been drunk or something when I did that piece of code ^^

I've also been there. Many times... :-D

**Comment by maribu** [comment]
@miri64: Ping?

**Comment by miri64** [comment]
(for reference: more detailed review above. This ACK was primarily on the `cppcheck` fix).

**Pull request merged**
