### PR TITLE
boards: cleaned up LED handling for NRF5x based boards

### PR DESCRIPTION
**Pull request by haukepetersen**
alternative to #4826

### CODE REVIEW

**Comment by gebart** [comment]
Untested ACK, I don't have the boards so I can't test

**Comment by haukepetersen** [comment]
but can you verify, that this fixes #4644? Thanks!

**Comment by gebart** [comment]
Confirmed, tested building nrf6310/board.c with clang, works fine with this PR but fails on master.

**Comment by haukepetersen** [comment]
had two masks wrong for the airfy and yunjia boards... should be fixed now.

**Comment by haukepetersen** [comment]
@gebart does your ACK hold?

**Comment by gebart** [comment]
ACK holds, did you test on actual boards? I don't have any nrf5x board

**Comment by haukepetersen** [comment]
tested on the nrf52dk and on the nrf51dongle. As the code is identical for the others, i wil merge -> and go

**Pull request merged**
