### PR TITLE
 gnrc_sixlowpan: clean-up configuration and expose via config group

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description

Bringing GNRC's 6LoWPAN module towards #10566 (also I need the last part for my current experiments ;-)). This PR

- removes the `net/gnrc/sixlowpan/nd/border_router.h` header, since the only define in it is nowhere used,
- moves all remaining configurable macros from `net/gnrc/sixlowpan*` to `net/gnrc/sixlowpan/config.h`, and
- exposes `RBUF_SIZE` and `RBUF_TIMEOUT` for compile time configuration via the new macros `GNRC_SIXLOWPAN_FRAG_RBUF_SIZE` and `GNRC_SIXLOWPAN_FRAG_RBUF_TIMEOUT_MS` respectively.

### Testing procedure
Read and compile (the latter should still work, I don't know about the first ;-)).

### Issues/PRs references
Addresses #10566

### CODE REVIEW

**Comment by jia200x** [comment]
thanks for tackling this!

Murdock complains because of undocumented defines

**Comment by miri64** [comment]
Piggy-backed documentation on those two functions, Murdock and Travis were complaining about.

**Comment by miri64** [comment]
Got permission to squash offline

**Comment by miri64** [comment]
Fixed Murdock complained

**Comment by miri64** [comment]
And squashed again.

**Comment by miri64** [comment]
Thanks for the review!

**Pull request merged**
