### PR TITLE
pkg: Remove oonf_api

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
The package has been flagged as deprecated ans scheduled for removal by 2020.04 release in #12190 due to lack of users and maintenance. This PR removes it.

### Testing procedure
- A green Murdock should be enough.

### Issues/PRs references
Deprecated in #12190
Depends on #13396

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
@benpicco I wasn't sure about the email in `LOSTANDFOUND.md`, please check :)

**Comment by smlng** [comment]
still order should be #13396 being first merged

**Comment by miri64** [comment]
Please rebase #13396 was merged.

**Comment by leandrolanzieri** [comment]
> Please rebase #13396 was merged.

@miri64 rebased!

**Comment by benpicco** [comment]
There we go.

**Pull request merged**
