### PR TITLE
sys/bit: provide CPU_HAS_SRAM_BITBAND

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- Add `CPU_HAS_SRAM_BITBAND` flag to allow checking whether all of SRAM has proper bit-banding support
- Use this in the Cortex M implementation of `atomic_utils`

### Testing procedure

```
make BOARD=frdm-k64f -C tests/sys_atomic_utils_unittests flash test
```

### Issues/PRs references

Reported by @fjmolinas, fixes https://github.com/RIOT-OS/RIOT/issues/15810

### CODE REVIEW

**Comment by fjmolinas** [comment]
This fixes the issue:

`make BOARD=frdm-k64f -C tests/sys_atomic_utils_unittests flash test`

```
main(): This is RIOT! (Version: 2021.04-devel-86-g716441-pr-15809)
.......
OK (7 tests)

```

**Review by fjmolinas — APPROVED** [review]
ACK, fixes the issue.

**Comment by fjmolinas** [comment]
GO!

**Comment by maribu** [comment]
Thanks for reporting the error and reviewing!

**Comment by maribu** [comment]
Backport provided in #15812

**Pull request merged**
