### PR TITLE
test: added unittests for the SAUL registry

### LINKED ISSUE #4817: saul: Missing tests
SAUL is currently not found anywhere in the tests directory. The only test we have today are the manual shell commands in examples/default

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #4817

### CODE REVIEW

**Comment by cgundogan** [comment]
looks good! ACK

**Comment by haukepetersen** [comment]
Murdock is green -> and go

**Comment by authmillenon** [comment]
was a backport provided for this?

**Comment by haukepetersen** [comment]
not that I know of

**Pull request merged**
