### PR TITLE
release-test: fetch host key for lille site

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Tasks 4.5 and 4.6 use the firefly nodes at the lille site, so we need to verify the host key for that side as well (not sure why it worked so far without).

### Testing procedure
`release-test` for task 4.5 and 4.6 should succeed now.

### CODE REVIEW

**Comment by miri64** [comment]
> `release-test` for task 4.5 and 4.6 should succeed now.

See https://github.com/miri64/RIOT/actions/runs/957033137. The keys are now loaded but the tests still fail for an unrelated reason (the `samr21-2` at the lille side seems to be just spamming the welcome line... confirmed by manually flashing and accessing that node).

**Comment by MrKevinWeiss** [comment]
Any reason this can't be merged?

**Comment by miri64** [comment]
> Any reason this can't be merged?

A missing ACK as far as I can see ;-).

**Review by MrKevinWeiss — APPROVED** [review]
ACK

**Comment by MrKevinWeiss** [comment]
I trust @miri64 confirmed manually it makes sense to me.

**Comment by miri64** [comment]
> I trust @miri64 confirmed manually it makes sense to me.

No need for blind trust, it is easily confirmed [here](https://github.com/miri64/RIOT/runs/2875068676?check_suite_focus=true#step:6:10) ;-).

**Comment by MrKevinWeiss** [comment]
> No need for blind trust

Even better!

**Comment by MrKevinWeiss** [comment]
Darn, I guess I hit a race condition with the skipping compile tests... Oh well, we have come this far.

**Pull request merged**
