### PR TITLE
[RFC] GitHub Actions: Split static tests via matrix strategy

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Before I spend more time on this little experiment, I want to know your opinion: Now that the static tests are a required GitHub action, what do you think about splitting them into individual build matrix items? While it has the disadvantage that  clutters the checks field quite a bit, it has some advantages:

- Seeing at once in both the check field and check tab, which test failed.
- More granularity which checks are required and which are not.
- Potential for slight speed up, since slower tests don't have to wait on each other.

### Testing procedure
You can see how it could look like in https://github.com/miri64/RIOT/pull/33.

### Issues/PRs references
None

### CODE REVIEW

**Comment by benpicco** [comment]
I like it, it takes some experience to parse the CI output and figure out which parts are relevant.
Having it all integrated into the GitHub UI makes is easier to immediately spot what the problem is.

**Comment by aabadie** [comment]
I think I don't like this PR: the good point with the action as it now in master is that it shows how to run all static tests within a single command, `make static-test`. So people can find here a way to reproduce locally the exact same output.
This action is also testing that the "logic" behind `make static-test` is working.

**Comment by miri64** [comment]
An alternative could be to make the `static_test.sh` script aware of Github check annotations somehow. I guess this also would have the advantage not to clutter the check tab that much.

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/15640 for an alternative approach using annotations.

**Comment by MrKevinWeiss** [comment]
TBH I think #15640 is a bit easier.  I think 7 is a magic number of things to show in the checks area, also having to scroll seems a bit much.

You bring up a good point about required/not required static checks but I somehow think that should be doable with annotation case as well (warning and error) or just splitting the to `required_static_checks` `non_required_static_checks`.

**Pull request closed without merging**
