### PR TITLE
tests: periph_gpio: fix usage of shell_commands

### PR DESCRIPTION
**Pull request by kaspar030**
tests/periph_gpio doesn't show it's custom shell handlers anymore. Fix in this PR.
Reported in #3735. Introduced by #3690.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
We had this issue somewhere before. ACK.

**Comment by kaspar030** [comment]
@PeterKietzmann yeah, sloppy review of #3690. Sorry for adding commits after your ACK, but those are the other cases. Could you take another look?

**Comment by PeterKietzmann** [comment]
BTW I assume there will be other places where this appears

**Comment by PeterKietzmann** [comment]
Whoops

**Comment by kaspar030** [comment]
I wonder why those bugs didn't generate a "defined but not used" warning.

**Comment by PeterKietzmann** [comment]
ACK holds. I restarted Travis. Didn't check other occurrences

**Comment by PeterKietzmann** [comment]
And go

**Comment by OlegHahm** [comment]
Sorry, for the trouble. ;-(

**Pull request merged**
