### PR TITLE
 drivers/ds1307: adapt to new i2c API

### PR DESCRIPTION
**Pull request by MichelRottleuthner**
### Contribution description
This adapts the ds1307 driver to the new i2c api. I don't have hardware to test.

### Issues/PRs references
#6577

### CODE REVIEW

**Comment by MichelRottleuthner** [comment]
Building tests/driver_ds1307 seems to fail because of a missing fix to embunit (#9242) which is not included in new_i2c_if branch. Is it safe to just cherry-pick the related commit to this PR?

**Comment by miri64** [comment]
Don't have it in the office and have to see if I have it at home. Otherwise, I won't be able to test either :(.

**Comment by dylad** [comment]
> Is it safe to just cherry-pick the related commit to this PR?


I guess you can do it, or open a separated PR into new_i2c_if, merge it and then rebased this branch on the new_i2c_if.

**Comment by miri64** [comment]
> I guess you can do it, or open a separated PR into new_i2c_if, merge it and then rebased this branch on the new_i2c_if.

We should rather just cherry-pick the fix for testing locally. Otherwise, the unittests get pulled into the embargo.

**Comment by MichelRottleuthner** [comment]
hmm this indeed sounds bad I somehow thought this will be resolved by git because the commit would be exactly the same on both branches - but tbh I haven't actually tried if that would work...

**Comment by miri64** [comment]
> hmm this indeed sounds bad I somehow thought this will be resolved by git because the commit would be exactly the same on both branches - but tbh I haven't actually tried if that would work...

That *should* be the case, but one (highly unlikely, but still possible) follow-up change in master to embunit might make it not work anymore. We had a similar problem when refactoring `gnrc_netif`.

**Comment by miri64** [comment]
Can't find the little thingy anymore btw :( so I'm not able to test.

**Comment by MichelRottleuthner** [comment]
rebased to get rid of the unrelated cppcheck error

**Comment by MrKevinWeiss** [comment]
So I think the adaptation to the new interface is correct according to the code review.  @dylad would you like to merge and we put in on the "test once we have hardware" list?

**Comment by dylad** [comment]
@MrKevinWeiss let's move forward !

**Pull request merged**
