### PR TITLE
boards/microbit*: deduplicate led matrix module

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

The module that manages the LED matrix on the microbit boards is duplicated between the 2. This PR moves the logic in a common module in `boards/common/microbit`.

### Testing procedure

- Green CI
- The LED matrix is still functional (tested on microbit and microbit-v2, trust me :) )

### Issues/PRs references

Follow-up of #15955

### CODE REVIEW

**Review by fjmolinas — CHANGES_REQUESTED** [review]
```
diff --git a/boards/common/microbit/microbit.c b/boards/common/microbit/microbit.c
index cfcfe9f184..7472682be0 100644
--- a/boards/common/microbit/microbit.c
+++ b/boards/common/microbit/microbit.c
@@ -43,7 +43,7 @@
  */
 #define REFRESH             (6000)      /* 6ms * 3 rows -> ~55Hz */
 
-#if defined(MODULE_BOARD_MICROBIT)
+#if defined(BOARD_MICROBIT)
 /**
  * @brief   The electrical number of rows and columns
  */
@@ -88,7 +88,7 @@ static const uint8_t pixmap[5][5] = {
     {  7,  6,  5,  4,  3 },
     { 20, 15, 18, 14, 19 }
 };
-#elif defined(MODULE_BOARD_MICROBIT_V2)
+#elif defined(BOARD_MICROBIT_V2)
 /**
  * @brief   The electrical number of rows and columns
  */
diff --git a/boards/microbit-v2/Makefile b/boards/microbit-v2/Makefile
index f8fcbb53a0..cc9ea70507 100644
--- a/boards/microbit-v2/Makefile
+++ b/boards/microbit-v2/Makefile
@@ -1,3 +1,5 @@
 MODULE = board
 
+DIRS = $(RIOTBOARD)/common/microbit
+
 include $(RIOTBASE)/Makefile.base
diff --git a/boards/microbit/Makefile b/boards/microbit/Makefile
index f8fcbb53a0..cc9ea70507 100644
--- a/boards/microbit/Makefile
+++ b/boards/microbit/Makefile
@@ -1,3 +1,5 @@
 MODULE = board
 
+DIRS = $(RIOTBOARD)/common/microbit
+
 include $(RIOTBASE)/Makefile.base
```

I had to make the following changes but it does not work on `microbit-v2`, maybe there is still something missing?

**Comment by aabadie** [comment]
@fjmolinas I fixed the issue on microbit-v2: the timer device is not the same (should be 1 instead of 2). The last commit is fixing this (and does some other cleanups to avoid hard-code values). Trust me it works this time!

**Comment by fjmolinas** [comment]
Please squash!

**Review by fjmolinas — APPROVED** [review]
ACK.

**Pull request merged**
