### PR TITLE
samr21/rtc safety isr

### PR DESCRIPTION
**Pull request by bapclenet**
This PR adds safety check to avoid the board to crash on interrupt.

### CODE REVIEW

**Comment by bapclenet** [comment]
@daniel-k , if you think of any more changes, let me know. Otherwise, wait for Travis and merge

**Comment by daniel-k** [comment]
Seems okay. I checked with the debugger: `INTFLAG = 0x00` after calling `rtc_init()` so that's fine.

**Comment by bapclenet** [comment]
Great! Wait for Travis and go

**Comment by bapclenet** [comment]
@authmillenon, Travis is not happy with : 

	Building application: driver_nvram_spi (18/75) .....
		failed: nucleo-f334, stm32f3discovery, stm32f4discovery
		failed .. retrying: mulle
		success: msbiot

This not related to this PR and even not for the right cortex (``m4`` here)
What's the problem?

**Comment by OlegHahm** [comment]
Travis is the problem. In a case like this, you (as a maintainer) can restart the failing buildtests on the Travis page.

**Comment by gebart** [comment]
When you restart a build, it is better to only restart the actual job that failed (cm4 group here) instead of the entire batch. To do this, first click on the job that failed and then select restart job at the top right. This saves time as we don't have to wait for Travis for a second time for jobs that have already succeeded (and risking random failures on those).

**Comment by bapclenet** [comment]
I will know next time though, thanks :-)

**Pull request merged**
