### PR TITLE
ndp: another leftover from renaming...

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK and go if travis goes :bell:

**Comment by authmillenon** [comment]
Seems like the content of #3872 needs to be fixed here too.

**Comment by OlegHahm** [comment]
Yes, that's actually how I came across #3872. ;)

**Comment by OlegHahm** [comment]
So, basically we're waiting for #3874 now.

**Comment by authmillenon** [comment]
#3874 is merged. Please rebase.

**Comment by OlegHahm** [comment]
reBASEd

**Comment by authmillenon** [comment]
And go.

**Pull request merged**
