### PR TITLE
Fix cordep eventcbs

### LINKED ISSUE #12884: examples/cord_ep: Dead lock when (re-)registering in callback function
#### Description
I was using the `cord_ep` example and wanted to automatically (re-)register to an resource directory when the `cord_ep_standalone_cb_t` is executed with the `CORD_EP_DEREGISTERED` event passed to it.

When I call the `register` function in `sys/net/application_layer/cord/ep/cord_ep.c` though, I produce a dead lock, because the function tries to lock a mutex, which is still locked by the function calling the callback function.

Short: `cord_ep_standalone` thread => [cord_ep_update](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep_standalone.c#L75) => 
[cord_ep_standalone_signal](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep.c#L322), => [application callback](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep_standalone.c#L103) => [cord_ep_register](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep.c#L243).

**Possible Solutions**:
1.  Unlock the mutex before calling [cord_ep_standalone_signal](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep.c#L322) (You should do this in all `cord_ep` functions where `cord_ep_standalone_signal` is called)
2.  Use a [recursive mutex](https://github.com/RIOT-OS/RIOT/blob/master/core/rmutex.c), so that the same thread can lock a mutex multiple times and therefore registering in the callback is possible
3.  Remove the call to `cord_ep_standalone_signal` within [cord_ep](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep.c#L322), because [cord_ep_standalone#_reg_runner](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep_standalone.c#L75) is actually calling the callback (Currently the callback is triggered **twice** when an update fails, which is not wanted behavior anyway).

**Solution 3** is probably the best, because it fixes triggering the callback twice and the dead lock issue as well (Do not forget to remove the timer (`xtimer_remove(&_timer);`) when the update failed, so that the thread will not try to update as long as the device is not (re-)registered). 

For all the other functions in [cord_ep.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/cord/ep/cord_ep.c) that call `cord_eap_standalone_signal`, unlocking the mutex before calling it would be probably the best.

#### Steps to reproduce the issue
1.  In `/examples/cord_ep` set a callback function (`cord_ep_standalone_reg_cb(cord_ep_standalone_cb_t cb)`) and register to a [resource directory](https://aiocoap.readthedocs.io/en/latest/module/aiocoap.cli.rd.html) via `cord_ep_register(const sock_udp_ep_t *remote, const char *regif)` in `main`
2.  In the callback function call `cord_ep_register`
3. Execute the example => you should end up in a dead lock

#### Expected results
You can call any function of `cord_ep` in the `cord_ep_standalone_cb_t` without producing a dead lock.

#### Actual results
Calling a any function of `cord_ep` in the `cord_ep_standalone_cb_t` causes a dead lock.

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
fixes #12884

### Testing procedure
a) connect to a RD, watch for the `"RD endpoint event: successfully updated client registration"` messages, kill the RD, wait for the `"RD endpoint event: dropped client registration"` message -> it should only appear once
b) @MatthiasBraeuer could you verify that reconnecting from the event callback does not lead to deadlocks anymore? Thanks

### Issues/PRs references
fixes #12884

### CODE REVIEW

**Comment by MatthiasBraeuer** [comment]
Sure I can verify that. I will do that at the beginning of January!

**Comment by haukepetersen** [comment]
Yepp, you have a point! I don't know why I haven't seen this earlier, but right now a proper solution seems obvious to me: we simply add a proper event callback to the base `cord_ep` module allowing for more detailed feedback on the modules state. The `ep_standalone` can then simply use that callback and forward the events to the high-level user.

Will look into this as soon as I find a minute or two...

**Comment by haukepetersen** [comment]
Done: I decided to open a new PR for the proposed changes: #13128

**Comment by miri64** [comment]
> Done: I decided to open a new PR for the proposed changes: #13128

So can this one be closed?

**Comment by haukepetersen** [comment]
I would like to get some feedback on #13128 first. In case that new PR is bullshit, we still have this one :-)

**Comment by Teufelchen1** [comment]
What's the status here and with #13128?

Given the new approach by @bergzand in #20040 I would opt to close both PRs as @haukepetersen does not seem to be active anymore?

**Comment by Teufelchen1** [comment]
Miri and koen agreed to close those.

**Pull request closed without merging**
