### PR TITLE
README.md: remove section Related Projects

### PR DESCRIPTION
**Pull request by waehlisch**
Whether PR #21052 should have been merged is debatable. The discussion of other PRs that try to improve PR #21052 may take some time. Instead of including content in the README.md, one very important entry point for interested RIOT users, that might conflict with rough consensus, I suggest to remove until we converged on what should be placed in the README (and how).

### CODE REVIEW

**Comment by aabadie** [comment]
I allowed myself to fix the mentioned PR number. Why not use git revert instead of manually editing the file?

**Review by maribu — CHANGES_REQUESTED** [review]
NACK

**Comment by maribu** [comment]
To elaborate a bit on my NACK:

This PR does three things:

1. Remove the section header "Related Projects"
2. Remove all references to projects that are not part of the larger RIOT community
3. Remove the reference to Ariel OS

A rough consensus on having a reference to Ariel OS has been established. Any PR that drops it without establishing a new rough consensus to replace the existing one is in direct violation of our self imposed rules.

If you update the PR to keep the reference to Ariel OS, I'll dismiss my NACK.

**Comment by OlegHahm** [comment]
+1  for removing the other projects (at least unless we have defined which makes a project "worthy" to be listed here).
-1 for removing the reference to Ariel OS.

**Comment by waehlisch** [comment]
maybe someone can explain what the purpose of the README in the RIOT repository is and why Ariel should be mentioned there.

**Comment by maribu** [comment]
@waehlisch it appears that you have personal issues with Ariel OS and/or the people behind it.

The RIOT community (maybe with the exception of you and @tcschmidt personally) has worked together with the people behind Ariel OS for years constructively. That work was productive and fun. Given the feedback and messages exchanged in the last week, it appears that the RIOT community and the Ariel OS community (which, to a large degree overlap) would like to continue to work constructively together.

A single sentence reference to in our README way down (I have to scroll a whole screen on my setup) isn't exactly a big deal. It a small gesture and a sign of respect. Something that I personally feel - and judging from the messages and interactions I have witnessed in the past matches what the RIOT community also feels - is well aligned with our core values of a friendly and welcoming community that strives to innovate by collaboration.

Maybe it is time to let it go and instead work together constructively?

**Comment by waehlisch** [comment]
> @waehlisch it appears that you have personal issues with Ariel OS and/or the people behind it.

i do want things correctly stated. this is why i raised the questions above. if the purpose of the README remains unclear, you cannot come up with a proper solution.

> A single sentence reference to in our README way down (I have to scroll a whole screen on my setup) isn't exactly a big deal. 

it is if the sentence is incorrect or misplaced.

> Maybe it is time to let it go and instead work together constructively?

working constructively means discussions and clarifications.

**Comment by waehlisch** [comment]
@Teufelchen1 thanks!

> @waehlisch would it ease your pain if the `Related Projects` section would be:
> 
> 1. at the end of the README? That's where I would put it (and where I would search for it in other projects).

if we want to include a longer list, yes.

if the content is about giving an example that RIOT welcomes collaboration and inspires others, i would suggest to add a Subsection "Collaboration" in the Section Community, and add a sentence similar to "RIOT closely collaborates with and inspires other open source projects, e.g., [Ariel OS](https://ariel-os.org/), an IoT OS written in Rust. We are more than happy to collaborate with those who share our [vision](https://doc.riot-os.org/vision.html)."

> For me, the section should help users answering the question: "Is RIOT for me?" (or does it suit my use case) - a few other projects to compare against will help with that.

i'm still wondering whether this really belongs to a README file. intuitively, i would expect such discussions on web page that is part of the riot-os.org.

**Comment by kfessel** [comment]
@waehlisch: I like your the suggestion in your recent comment -community and shared vison-, would you like to change your PR?

**Comment by waehlisch** [comment]
> @waehlisch: I like your the suggestion in your recent comment -community and shared vison-, would you like to change your PR?

if there are no objections, yes.

**Pull request closed without merging**
