### PR TITLE
tools/benchmark_udp: fix build

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The location of `list.h` did change

### Issues/PRs references

follow-up to #17652

### CODE REVIEW

**Review by bergzand — APPROVED** [review]
Ack

**Comment by bergzand** [comment]
Does it make sense to add this to the tools-buildtest action?

**Comment by benpicco** [comment]
It's part of `host-tools`, I'm surprised its not build by CI

**Comment by aabadie** [comment]
How about we add the tool to the tools-buildtest action ? This way the error fixed by this PR could be catched automatically by the CI ?

**Comment by aabadie** [comment]
> It's part of `host-tools`, I'm surprised its not build by CI

The tools-buildtest CI action has nothing to do with `host-tools`, each tool must be added in a separate step.

**Comment by benpicco** [comment]
> the tools-buildtest action

where is that?

**Pull request merged**
