### PR TITLE
Adding new board 

### PR DESCRIPTION
**Pull request by seydamir**
I have made my board named amir. I want to merge it in the master branch.

### CODE REVIEW

**Comment by x3ro** [comment]
Do I understand correctly that you made this board yourself? Is the hardware design open source, too?

**Comment by seydamir** [comment]
yes I made this board. It is an arduino shield that can be used for
6lowpan communication.

**Comment by seydamir** [comment]
The hardware is not yet open source.

**Comment by PeterKietzmann** [comment]
@seydamir as long as this hardware is not available at all I guess it makes no sense to integrate it into our master branch. @all please object if you see it differently.

**Comment by LudwigKnuepfer** [comment]
@seydamir is it available at all, open source or not?

**Comment by seydamir** [comment]
I have created the repository for my new shield. 
https://github.com/seydamir/Arduino-6LoWPAN-Shield
I have uploaded the CAD files and it is open source with license GPL V3.

**Comment by LudwigKnuepfer** [comment]
Actually I was mostly interested if it is possible to buy this board somewhere. Is it?

**Comment by seydamir** [comment]
Actually I have not made it ready to market. I will soon

**Comment by PeterKietzmann** [comment]
@ seydamir thanks for the update. I propose to wait with merging this PR until your board is available for the public.

**Comment by seydamir** [comment]
Ok thank you, I will wait.

**Comment by PeterKietzmann** [comment]
@seydamir any progress bringing your board to market?

**Comment by seydamir** [comment]
Actually I am not aware of how to present it in international market. I
would be pleased if anyone wants to cooperate and bring it with the other
toys I made into market. Our group website is http://www.iotup.ir.

Regards,
Amir

**Comment by PeterKietzmann** [comment]
Do you actually use RIOT in your projects? Would be so nice to know if/where you deployed the system! Regarding cooperation I personally can't help, sorry.. Maybe someone else around?

**Comment by seydamir** [comment]
It is ok.Yes I have used Riot. You can see my port committed.

**Comment by PeterKietzmann** [comment]
@seydamir we are in you PR so I have seen your port :-). I was wondering weather you deployed RIOT in one of you projects with IoTUP

**Comment by seydamir** [comment]
Aha, We have developed a Generic IoT Node, which has different
communication capabilities like 6LoWPAN, LoRaWA etc.

**Comment by PeterKietzmann** [comment]
And now the question is if your node is used in a project or product, running RIOT and the different communication capabilities.

**Comment by smlng** [comment]
If the board is not for sale (nor available in the near future), it makes no sense to have the board definition in the RIOT master. Which doesn't prevent you from having it in your RIOT fork @seydamir, and keep that updated - if the board will be commonly available later on, we can reconsider merging it.

For now I suggest to close this, tagged as _memo_

**Comment by PeterKietzmann** [comment]
@seydamir, thank you very much for your contribution. For now I'd like to keep it as @smlng proposed: close your PR with memo label set and consider re-opening once your board is commonly available. Otherwise it is unmaintainable for us.

**Pull request closed without merging**
