### PR TITLE
nanocbor: Initial support for the nanocbor package

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Nanocbor is a small CBOR encoder and parser aiming to provide almost full CBOR spec support with minimal flash footprint

### Testing procedure

execute the test application.

To be completely honest, I was too lazy to write a decoder example and assumed the upstream package is tested well enough to guarantee a functioning package :laughing: 

### Issues/PRs references

None

### CODE REVIEW

**Comment by kaspar030** [comment]
please squash!

**Comment by bergzand** [comment]
Squashed!

**Comment by bergzand** [comment]
Just to be sure, @kaspar030 you reviewed and tested the package makefiles and code right?

**Comment by kaspar030** [comment]
Static tests:

```
pkg/nanocbor/doc.txt:20: new blank line at EOF.
	ERROR: This change introduces new whitespace errors
```

feel free to squash directly.

**Comment by bergzand** [comment]
> Static tests:

Oh, oops

> feel free to squash directly.

Fixed and amended

**Comment by kaspar030** [comment]
> Just to be sure, @kaspar030 you reviewed and tested the package makefiles and code right?

yes!

**Comment by bergzand** [comment]
I've blacklisted the 8 and 16 bit MCU boards in the test application and added a small note to the package doc mentioning the problem and the upstream issue.

**Comment by kaspar030** [comment]
integration very nice.  Ran test application on native and nrf52dk. &go.

**Comment by bergzand** [comment]
Thanks for reviewing and testing!

**Comment by bergzand** [comment]
> I've blacklisted the 8 and 16 bit MCU boards in the test application and added a small note to the package doc mentioning the problem and the upstream issue.

See #11810

**Pull request merged**
