### PR TITLE
doc: Add deprecation warnings for new repos

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Add deprecation warnings for cleanup of hardware testing tools to README.md files and in the lib_if that is to be removed.

### CODE REVIEW

**Comment by miri64** [comment]
What is this PR about? From looking into the code this doesn't seem to change the documentation, but some python code.

**Comment by MrKevinWeiss** [comment]
@miri64 nice catch, sorry a bit rushed here.

**Comment by miri64** [comment]
The commit message still doesn't reflect the content of the change though. Please add a reference to `if_lib` to it, otherwise I will eternally wonder what this commit is about when I scroll through the history ;-)

**Comment by MrKevinWeiss** [comment]
Noted, improve message quality in the near future.

**Comment by miri64** [comment]
Please improve the message quality now, so we can merge this ;)

**Pull request merged**
