### PR TITLE
Added support for Wismote board.

### PR DESCRIPTION
**Pull request by sumanpanchal**
Dear Maintainers,
I have added support for Wismote board [1]. Initially I have tested with "./example/hello-world" program and its working fine. Before I move further, I would like know your feedback on existing update.

[1] http://wismote.org/doku.php

### CODE REVIEW

**Comment by kaspar030** [comment]
@sumanpanchal Welcome to the RIOT community!

And thanks a lot for your work on wismote support.
I don't have the device, so I can't test.

Looking at the code, you based the code on existing msp430 nodes. Unfortunately the msp430 platforms don't support our periphal driver interface (yet). We have implementing that support on our TODO lists, but unfortunately not the time at the moment.

For this port it means that I'd rather not merge one more platform using the old interfaces.

Do you think you could convert your code to the new interfaces?
In particular, it would mean using 'periph/timer.h' instead of hwtimer and "periph/uart.h" instead of uart0.

**Comment by sumanpanchal** [comment]
@kaspar030 Thanks for the feedback. I will try to convert existing code to the new interfaces as per your suggestion.

**Comment by OlegHahm** [comment]
Actually that would be awesome!

**Comment by zhuoshuguo** [comment]
@sumanpanchal Ping. A kind reminder for rebase.

**Comment by OlegHahm** [comment]
Apparently abandoned.

**Pull request closed without merging**
