### PR TITLE
README: Add merge-chance badge

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This adds a new badge to the README, which shows the chance of a PR of a non-member being merged and the number of days that takes. The information is taken from [this website](https://merge-chance.info/target?repo=RIOT-OS/RIOT) which was discovered by @benpicco. I personally find the numbers surprising, given that one of our problems we often discussed in the past was the perceived eternity it tags to merge PRs by new contributors. But maybe the good numbers come from our guilt. To quote @maribu from an offline discussion about this badge:

> Maybe the believe that we are slow on foreign PRs is motivating our fast response time. It would be interesting to see if the lack of guilt results in slower response time once we have this badge in the readme

### Testing procedure
Have a look at the rendered README. There should be the new badge now.

### Issues/PRs references
None

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK

**Review by benpicco — APPROVED** [review]
I hope this encourages outsider contribution more than it let's us get comfortable with slacking on reviews :wink:

**Comment by miri64** [comment]
The way the contributors are counted is a bit off, but this seems to be more of a Github and config issue then the fault of the badge. The way the data is fetched [here](https://github.com/PiotrZakrzewski/oss-responsiveness/blob/main/mergechance/gh_gql.py#L40-L59) e.g. @benpicco is counted as a contributor, not as a member. But let's merge this for now and find out how we can make @benpicco a member (he is in both the [member team](https://github.com/orgs/RIOT-OS/teams/member) as well as listed as a member of the [RIOT-OS people](https://github.com/orgs/RIOT-OS/people).

**Comment by PiotrZakrzewski** [comment]
I am happy that you found merge-chance useful! Let me know if you have any feedback / feature requests.

**Comment by miri64** [comment]
> I am happy that you found merge-chance useful! Let me know if you have any feedback / feature requests.

Hi @PiotrZakrzewski, happy you are happy :-). As stated above, from my sample taken by hand with GraphQL, one of our maintainers (probably more) is for some inexplicable reason listed as a `CONTRIBUTOR`, not a member. It would be great if you could, if possible, shed some light on why that is the case.

**Comment by PiotrZakrzewski** [comment]
> > I am happy that you found merge-chance useful! Let me know if you have any feedback / feature requests.
> 
> Hi @PiotrZakrzewski, happy you are happy :-). As stated above, from my sample taken by hand with GraphQL, one of our maintainers (probably more) is for some inexplicable reason listed as a `CONTRIBUTOR`, not a member. It would be great if you could, if possible, shed some light on why that is the case.

`authorAffiliation` which I use for determining if someone is an "insider" is saved at the time of making a PR, GitHub even has some special affiliations such as "first time contributor", which would be broken if they were recomputed later on. If the author is (at the time of making the PR) a member of GitHub org owning the repo they will get `MEMBER` affiliation for this PR. If they were invited to contribute to the repository (by giving them some rights, GitHub is not specific on that ...) but are not member of the GitHub org then they will be classified as `COLLABORATOR`, a `CONTRIBUTOR` in theory should be anyone else who shows up in the contributor tab (i.e. has merged contributions already). So if I understand everything correctly and the system works as it is described in the docs those maintainers were not (yet?) members of RIOT-OS GitHub organisation, do you this is possible?

If you add all maintainers to RIOT-OS organization then all new PRs should be created with authorAffiliation `MEMBER` and merge-chance.info will ignore them.
It will take some time for stats to converge as I take up to 300 prs in consideration.

**Comment by PiotrZakrzewski** [comment]
Alternatively we could think of some other way of excluding maintainers. Let me know if you have any suggestions!

**Comment by miri64** [comment]
> Alternatively we could think of some other way of excluding maintainers. Let me know if you have any suggestions!

Is there maybe a way to take the team affiliation when opening a PR of the author into account?

**Comment by miri64** [comment]
(AFAIK, member of any team should already also become a member of the organization though)

**Comment by PiotrZakrzewski** [comment]
> > Alternatively we could think of some other way of excluding maintainers. Let me know if you have any suggestions!
> 
> Is there maybe a way to take the team affiliation when opening a PR of the author into account?

I am exploring that. Also: how about labels? Some other projects suggested using labels to mark PRs that should not be counted, e.g. `BOT` and `SPAM`. That be easily checked. Do you routinely add any labels to PRs made by the maintainer team?

**Comment by PiotrZakrzewski** [comment]
@miri64 I cannot rely on organisation teams for two reasons:
- many teams are not public
- it is a costly query (in terms of number of queries and also the rate limiting score)
But I came up with an alternative way to filter out hidden insiders, could you have a look and give feedback ? https://github.com/PiotrZakrzewski/merge-chance/issues/3

**Comment by PiotrZakrzewski** [comment]
@miri64 Have a look at the acceptance version of merge-chance which excludes fake-outsiders (non-member authors who merge a lot) https://acceptance.merge-chance.info/target?repo=riot-os/riot

**Comment by miri64** [comment]
Awesome! Is there a way to configure X as mentioned by @wardweistra in https://github.com/PiotrZakrzewski/merge-chance/issues/3#issuecomment-761549777? Also I am always happy about more explanation what the new badge entails exactly :-).

**Comment by PiotrZakrzewski** [comment]
> Awesome! Is there a way to configure X as mentioned by @wardweistra in [PiotrZakrzewski/merge-chance#3 (comment)](https://github.com/PiotrZakrzewski/merge-chance/issues/3#issuecomment-761549777)? Also I am always happy about more explanation what the new badge entails exactly :-).

Configuring the threshold of PRs to be merged recently to be considered a de-factor insider would make it difficult to compare between repos. Which brings me to the next point - the idea for merge-chance.info badge is to help outsiders pick a project that is more likely to accept their contribution (after filtering out low quality PRs, spam and bots).

I created it after I made a few PRs to smaller projects which went without a response for a long time. Now I see that majority of big actively managed projects process PRs much faster than smaller individual-run projects. But there still are differences in how difficult it is to contribute and what is the time to close.

Besides inferring de-factor insiders I also added some rudimentary spam filtering and also **download data** link to be able to easily verify with project owners if the spam filtering and insider detection worked as intended.

When you have time please have a look at data on https://acceptance.merge-chance.info/target?repo=riot-os/riot and let me know if you would like to use the new version :)

**Pull request merged**
