### PR TITLE
od: signedness and constantness of input parameter

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
The const I understand, but why the signed?

**Comment by authmillenon** [comment]
ACK.

**Comment by authmillenon** [comment]
(Question answered IRL: there are platforms (that @OlegHahm owns), where `char` is unsigned)

**Comment by gebart** [comment]
arm-none-eabi-gcc has a default of char as unsigned (unless -fsigend-char
is specified on the command line)

**Comment by authmillenon** [comment]
It was native on his phone ;-)

**Comment by OlegHahm** [comment]
Rebased to get Travis working agian.

**Comment by OlegHahm** [comment]
Travis is fine. Go.

**Pull request merged**
