### PR TITLE
tm.h: fix typo

### PR DESCRIPTION
**Pull request by yogo1212**

### CODE REVIEW

**Comment by OlegHahm** [comment]
I don't think that's a typo.

**Comment by kaspar030** [comment]
@olegg Couldd youu elaboratee?

**Comment by gebart** [comment]
iff means "If and only if"

**Comment by Kijewski** [comment]
@gebart is correct. I wrote `iff` in here so I did not have to specify a value for the error case.

0 is good, not 0 is bad. I think this pattern is easier to understand and use than "returns 0 if good, -1 if bad", e.g. do I have to test the result for both values? Could the stars be aligned in a way that the function returns 42?

**Comment by yogo1212** [comment]
ok. nice to know ;-)
thank you for your time

**Comment by gebart** [comment]
It might be a good idea to change the iff to if and only if in the
documentation text.

**Comment by Kijewski** [comment]
19 files have matches for `iff` (I did not check if this contains matches in unrelated words). Feel free to `%s/iff/if and only if/g`. :)

**Comment by yogo1212** [comment]
@Kijewski most of the `iff`s come from you :-D
if it's not a bug but a feature i won't do anything :-p

if, however, you decide you want to change that you have yourselves a volunteer right here.

**Comment by OlegHahm** [comment]
> if, however, you decide you want to change that you have yourselves a volunteer right here.

Didn't you mean: "iff, however, you decide you want to change that you have yourselves a volunteer right here."?

**Comment by yogo1212** [comment]
@OlegHahm arrr!
i guess that depends on what i'm volunteering for.
should you decide not to change this or should you not decide anything ... i will not implement the change while i would still be voluntarily contributing to riot.
but: is it still voluntary if that is only because of the commitment i made earlier?
i'm not sure whether it's qualifies as instrumental motivation in that case.
but then again, how can anything be consummatory?
trikk, trikk, trikk

**Pull request closed without merging**
