### PR TITLE
net: Remove NHDP module

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
NHDP module has been flagged as deprecated and scheduled for removal by 2020.04 release in #11987, due to lack of maintenance. This removes the module and adds it to `LOSTANDFOUND.md`.

### Testing procedure
- A green Murdock should be enough

### Issues/PRs references
Deprecated in #11987

### CODE REVIEW

**Comment by smlng** [comment]
checked with `git grep -i nhdp` and found no remaining stuff other than the lost and found

**Comment by leandrolanzieri** [comment]
For some strange reason `ENABLE_DEBUG` was defined in this module and some files in core reference it. @smlng can I add the fixing commit here?

**Comment by leandrolanzieri** [comment]
And some vera++ errors now :sweat:

**Comment by leandrolanzieri** [comment]
@smlng finally all green, do you mind taking a last look?

**Pull request merged**
