### PR TITLE
drivers: fix doxygen for hd44780

### PR DESCRIPTION
**Pull request by smlng**
minor corrections, i.e, fix group name and closing brackets of groups.

### CODE REVIEW

**Comment by smlng** [comment]
Still, I wonder why the missing closing brackets were not discovered by static doc check?

**Comment by miri64** [comment]
I kind of have a deja vu... https://github.com/RIOT-OS/RIOT/pull/6826 ;-)

**Comment by smlng** [comment]
yeah sorry, my bad ... damn typos.

**Comment by smlng** [comment]
mhm, but one closing bracket was missing in the internal header too, and the group name had a typo <- but that's hard to check for, I guess

**Comment by miri64** [comment]
> mhm, but one closing bracket was missing in the internal header too

I have two theories:

- Doxygen doesn't report it, because it is the last closing bracket and that's fine for the parser, SGML-style
- It was removed after the file was created and was just not changed, since we made the doc check fail always.

**Pull request merged**
