### PR TITLE
cpu/stm32f4: fixed minor typo in the hwrng driver

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by miri64** [comment]
If you are faster, I reassign ;-P

**Comment by aabadie** [comment]
> If you are faster, I reassign ;-P

Sorry, I didn't notice you were the assignee ;)

**Comment by aabadie** [comment]
Looks like Jenkins has problems.

**Comment by haukepetersen** [comment]
Let's wait for Murdock and see how that turns out...

**Pull request merged**
