### PR TITLE
tools/bossa: update to latest release and adapt support

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR updates the BOSSA flashing tool to its latest release 1.9.1 which contains several enhancements:
- build on OSX is fixed so there's no need to provide a patch (removed in this PR)
- the tool now supports more SAM CPUs (SAM4S, SAMD51, et)
- no more warning during build

It also seems that the ROM_OFFSET now has to be passed explicitly when calling bossa.

### Testing procedure

This PR should be tested on boards that works with an Arduino bootloader at the beginning of the flash memory: `arduino-mkr*`, `sodaq-*`, `feather-m0` and arduino-due.

**How to test this PR:**

- remove version of bossa that could already be in `dist/tools/bossa`:
```
rm -rf ./dist/tools/bossa/{bin,bossac}
```
- put the board in bootloader mode by double tapping the reset button
- flash the board: it should succeed with this PR
```
make BOARD=arduino-mkr1000 -C tests/leds flash
```
- check that the firmware is working (red LED is blinking)

**Be careful with this PR**: it seems that omitting the ROM_OFFSET parameter can break the preflashed bootloader, since bossa is called with the `-e` (erase) option. This results in the bootloader partially erasing itself and ends up in a broken bootloader. I already bricked 2 boards because of this...
For testing, I recommend to use an Arduino MKR1000 because in case of a problem, the bootloader can be replaced in flash using JLink.
To reflash a broken bootloader on this board:
1. Download the [bootloader firmware](https://github.com/arduino/ArduinoCore-samd/blob/master/bootloaders/mkr1000/samd21_sam_ba_arduino_mkr1000.bin)
2. Plug a JLink programmer and flash the bootloader:
```
FLASHFILE=<path to>/samd21_sam_ba_arduino_mkr1000.bin make BOARD=arduino-mkr1000 -C tests/leds flash PROGRAMMER=jlink
```

### Issues/PRs references

None

### CODE REVIEW

**Comment by dylad** [comment]
How much ROM_OFFSET vary across SAM0 families ? Maybe we could configure it within RIOT with the right default value so unfamiliar users don't brick their board. What do you think ?

**Comment by aabadie** [comment]
> How much ROM_OFFSET vary across SAM0 families ?

ROM_OFFSET corresponds to the offset required by the bootloader preflashed at the beginning of the flash. For samd21, it's 0x2000, but for samd51, it is 0x4000 and for nrf52 (not officially supported by the project upstream), it's even more. This is probably why this was changed in the latest version, before (when only samd21 were supported) it was implicitly set to 0x2000 I think.
I think this offset should be set at board level (like it is now), since it doesn't directly depends on the MCU, it's rather a board configuration (if there's a bootloader or not).

**Comment by dylad** [comment]
> I think this offset should be set at board level (like it is now), since it doesn't directly depends on the MCU, it's rather a board configuration (if there's a bootloader or not).

If all boards currently using BOSSA have ROM_OFFSET defined, we're all good.
I'll give it a try on a board unless @fjmolinas do it before me.

**Comment by aabadie** [comment]
Tested on arduino-due and the new version doesn't work on this board. I'm trying to find what could be cause.

**Comment by aabadie** [comment]
Regarding the ROM_OFFSET thing, have a look at https://github.com/shumatech/BOSSA/issues/79.  This is a known compatibility issue.

**Comment by dylad** [comment]
> Regarding the ROM_OFFSET thing, have a look at shumatech/BOSSA#79. This is a known compatibility issue between 1.8 and 1.9.

Looks like this issue is quite old, no wonder why I bricked my SAMD21 countless time ;)
But as long as boards define their ROM_OFFSET, we should prevent from doing bad thing.

**Comment by aabadie** [comment]
It's less old than the version that is used by RIOT. But the problem is that more recent versions of bossac doesn't work with arduino-due (don't ask me what's opinion on bossac ;) ).

**Comment by aabadie** [comment]
> But the problem is that more recent versions of bossac doesn't work with arduino-due

To me the answer to this problem is somewhere in https://github.com/shumatech/BOSSA/commit/ee5a651aacaf2c3fbcd539789574618a425d1a06, because it is working before but I couldn't find a commit that is working after.

**Comment by dylad** [comment]
> To me the answer to this problem is somewhere in shumatech/BOSSA@ee5a651, because it is working before but I couldn't find a commit that is working after.

IIRC, there is a verbose option with bossac.
Could you paste the complete output of a working flash and a broken one please ?

**Comment by aabadie** [comment]
After some thoughts and some discussion IRL with @kaspar030 and @bergzand, switching from 1.8 to 1.9 can be dangerous for Arduino/Sodaq/etc boards users because of the new ROM_OFFSET requirements.
Imagine someone tries a version of RIOT which provides bossac 1.9 with valid command line options (e.g. setting ROM_OFFSET), then switch back to an older version of RIOT: the bossac binary is still in version 1.9 but the use of ROM_OFFSET is dropped from the command line options. In this case, a user might break the bootloader on his board that could become unflashable after.

The other problem is that bossac 1.9.1 doesn't work with arduino-due.

So the proposition is to move the current version of bossac in dist/tools/bossa-1.8 directory and use this version with arduino-due. Version 1.9 will be fetched in dist/tools/bossa-1.9. This separate potential bootloader issues when changing RIOT versions and arduino-due can still be flashed.

Would this approach be ok for you @dylad ? Also CC'ing @kaspar030 and @bergzand.

I have a branch that does that so I can open a PR so we can discuss there.

**Pull request closed without merging**
