### PR TITLE
cpu/stm32/periph_pwm: support of complementary timer outputs

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides the support of complementary timer outputs as PWM channels for advanced timers (TIM1/TIM8).

To use a complementary output of an advanced timer as PWM channel, the output is defined with an offset of 4, i.e. normal outputs are in the range of 0 to 3 (CH1...CH4) and complementary outputs are in the range of 4 to 6 (CH1N...CH3N). If the defined output is less than 4, the normal output is enabled, otherwise the complementary output is enabled.

This change is required to support PWM on boards that have connected the complementary outputs of advanced timers to the PWM connector pins, for example the STM32L496-DISCO board.

### Testing procedure

- Green CI
- Use any STM32 board which supports the `periph_pwm` feature. `tests/periph_pwm` should still work.
- Change the configuration for this board so that either timer TIM1 or TIM8 and a complementary channel is used for any exposed GPIO. `tests/periph_pwm` should also work with such a configuration.

### CODE REVIEW

**Comment by benpicco** [comment]
@MrKevinWeiss do you have some STM32 boards in your HiL setup?

**Comment by maribu** [comment]
Would you mind to add a bit of documentation (a short 1-3 sentence note would be totally sufficient, IMO). I'm not entirely sure were to add. Maybe the easiest way to find that note would be to add a some "platform specific extensions" to the general PWM doc and add an "STM32" subsection there?

The code looks non-scary. I assume that @gschorcht tested this during development anyway? If so and the doc is added, I'm happy to ACK. Please squash at will.

**Comment by gschorcht** [comment]
@maribu Some doc added for `pwm_chan_t`.

**Comment by maribu** [comment]
I think you might forgot to push :sweat_smile:

**Comment by gschorcht** [comment]
> I think you might forgot to push sweat_smile

Indeed, see https://github.com/RIOT-OS/RIOT/pull/19572/commits/8b882bfbb1db6981d91441419ba907145a894dc9.

**Comment by maribu** [comment]
bors merge

**Comment by maribu** [comment]
please squash :)

**Comment by gschorcht** [comment]
Done

**Comment by maribu** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks

**Pull request merged**
