### PR TITLE
boards/phynode-kw41z: add initial support

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds initial support for the [Phytec PhyNODE KW41Z (PhyNODE Athena)](https://www.phytec.eu/product-eu/internet-of-things/iot-enablement-kit-4/).

The initial support includes SAUL support for all LEDs and the SW button. I also tested the embedded Light sensor and everything seem to work.

I'm currently running all tests and report when I'm done.

### Testing procedure
This board can be tested using the [compile-and-test-for-board](https://github.com/RIOT-OS/Release-Specs/blob/master/02-tests/compile_and_test_for_board.py) script.

Basic testing can be done with the `default` example (saul, etc):
```
BOARD=phynode-kw41z make -C examples/default all flash term
```

Also test the documentation with:
```
make doc
```
Open `doc/doxygen/html/index.html` and check the entry at `Modules>Boards>PhyNODE KW41z`

### Issues/PRs references
None so far

### CODE REVIEW

**Comment by jia200x** [comment]
I also tested both xtimer sources (PIT and LPTMR). Both work

**Comment by gebart** [comment]
nice to see more kw41z boards!
Could you try the network driver in #7107 with this board as well?

I don't have the board so I can't test, but I can do a review later this week, quite busy right now though.

**Comment by jia200x** [comment]
> Could you try the network driver in #7107 with this board as well?

Sure :)

> I don't have the board so I can't test, but I can do a review later this week, quite busy right now though.

Yeah, sure! Thanks!

**Comment by jia200x** [comment]
Fixed a typo and renamed SAUL GPIO entries to make them more user friendly

**Comment by MrKevinWeiss** [comment]
Tested (periphs):
* i2c
* spi
* uart (with standard term)
* adc (internal temp)
* leds

All confirmed to work.

**Comment by jia200x** [comment]
added internal ADC lines (coretemp, etc) to SAUL

**Comment by aabadie** [comment]
From the link that you give, the board is called phyWave. So why call it phynode (which uses a different radio and mcu) ? It would make more sense to call it just `phywave` or `phywave-kw41z` if you prefer.

**Comment by jia200x** [comment]
PhyWAVE is just the RF module + KW41Z. You can check the [website](https://www.phytec.de/produkt/internet-of-things/phywave-kw41z/) here.

The board seems to be called "PhyNODE Athena", but it explicitly says "PhyNODE KW41Z" in the physical board.

**Comment by MrKevinWeiss** [comment]
Saul seems to discover all periphs, the readings that I am getting (around 26049) don't correspond with the basic periph readings (409) for the interal temp ADC 0.  I will investigate tomorrow.

**Pull request merged**
