### PR TITLE
adding wakaama pkg

### PR DESCRIPTION
**Pull request by Darredevil**
This is just the first step for the LWM2M protocol integration. 
At the moment it can't be used in its current state.

### CODE REVIEW

**Comment by haukepetersen** [comment]
oh, forgot: could you please squash into a single commit? Thx

**Comment by kaspar030** [comment]
nice!

please renumber the patch files. Are you not exporting using git-format-patch from your git branch head?

**Comment by Darredevil** [comment]
kaspar030 : Yes, I did use git-format-patch but they aren't all consecutive so I just took each one as I created it. Will fix it shortly.

haukepetersen : Yep, will squash it

**Comment by haukepetersen** [comment]
Looks good and does work -> ACK and go.

**Comment by OlegHahm** [comment]
Congrats!

**Pull request merged**
