### PR TITLE
gh/workflows/release-tests: update LoRaWAN parameters to ttnv3

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This changes the parameters to use the same as in the test reported in  https://github.com/RIOT-OS/Release-Specs/pull/218#issuecomment-946490902. Once secrets are also updated same results should be expected.

### Testing procedure

Start a release test run or merge? Not sure @miri64 might know.

### Issues/PRs references

https://github.com/RIOT-OS/Release-Specs/pull/218

### CODE REVIEW

**Comment by miri64** [comment]
As I changed the secrets, we might need to backport https://github.com/RIOT-OS/RIOT/pull/17003.

**Comment by miri64** [comment]
(for both the old run and the new (if not just restarted))

**Comment by fjmolinas** [comment]
So this time only the first test failed, but I suspect another node, I booked it and will re-run

```
11-lorawan/test_spec11.py::test_task01[nodes0] FAILED                    [ 16%]
11-lorawan/test_spec11.py::test_task02[nodes0] PASSED                    [ 33%]
11-lorawan/test_spec11.py::test_task03[nodes0] PASSED                    [ 50%]
11-lorawan/test_spec11.py::test_task04[nodes0] PASSED                    [ 66%]
11-lorawan/test_spec11.py::test_task05[nodes0-otaa] PASSED               [ 83%]
11-lorawan/test_spec11.py::test_task06[nodes0-abp] FAILED                [100%]

=================================== FAILURES ===================================
```

**Comment by fjmolinas** [comment]
> > Still failing. Could it be a problem with the environment?
> 
> Maybe, I'll try something out...

I think the enviroment defined keys are not there because locally it works with the same keys, and that application is the only one where those variables are defined through the Makefile

**Comment by miri64** [comment]
Then let's first merge #17010 and then this one.

**Pull request merged**
