### PR TITLE
cortexm_common: Update to CMSIS 4.5

### PR DESCRIPTION
**Pull request by gebart**
I figured we should have the latest CMSIS headers for the upcoming release.
Updated CMSIS headers to version 4.5 from the ARM download center.

### CODE REVIEW

**Comment by DipSwitch** [comment]
Nice! Seems fine by me :)

**Comment by kaspar030** [comment]
+1!

The files say version "4.3"?

**Comment by gebart** [comment]
@kaspar030 ARM has a problem deciding on a single version naming scheme for the releases. The old version was listed as 4.3, but contained "v4.10" in the headers, this is listed as 4.5 but contains "v4.30" in the headers. Additionally, the file downloaded is named CMSIS-SP-00300-r4p5-00rel0.zip.

**Comment by OlegHahm** [comment]
Murdock is unhappy because of https://github.com/RIOT-OS/RIOT/issues/4987

**Comment by kaspar030** [comment]
More this:
```
BUILD OUTPUT of group static-tests:
Current branch HEAD is up to date.
Current branch HEAD is up to date.
cpu/cortexm_common/include/cmsis_gcc.h:89: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:114: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:128: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:143: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:157: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:182: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:208: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:80: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:134: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:164: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:194: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:224: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:278: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_armcc_V6.h:332: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:89: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:114: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:128: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:143: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:157: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:182: error (uninitvar): Uninitialized variable: result
cpu/cortexm_common/include/cmsis_gcc.h:208: error (uninitvar): Uninitialized variable: result
```

**Comment by gebart** [comment]
@kaspar030 those errors are a mistake by cppcheck older versions which don't understand arm output variables. I'll add the cppcheck suppression comments.

**Comment by kaspar030** [comment]
@gebart This might be a good occasion to switch murdock to the new ubuntu-based docker image.

**Comment by gebart** [comment]
@kaspar030 should I still add the cppcheck suppression comments?

**Comment by kaspar030** [comment]
@gebart Let's wait for the build! I just switched the docker image.

**Comment by kaspar030** [comment]
That did the trick. ACK from my side, I guess we can merge?

**Comment by authmillenon** [comment]
Is anything speaking against it?

**Comment by kaspar030** [comment]
No. ggo!

**Pull request merged**
