### PR TITLE
boards/atmega256rfr2-xpro: initial support

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is adding an initial support for the [ATmega256RFR2 Xplained pro board](https://www.microchip.com/DevelopmentTools/ProductDetails/ATMEGA256RFR2-XPRO).

Interesting things with this board:
- it allows to test the atmega256rfr2 cpu that has no board support for the moment
- it provides an integrated edbg programmer, compatible with avrdude: the board can be easily flashed and even reset (debug not tested yet).
- it provides a radio (untested yet)

I ran the compile_and_test_for_board.py script and it reports several problems. I'll have a look at that later.

The PR is marked as a draft until the board is fully tested/configured.

### Testing procedure

- A green Murdock
- Allowed automatic tests are passing

### Issues/PRs references

~Based on #12608 to avoid having to update BLACKLIST_BOARD variables that will be removed anyway once merged.~

### CODE REVIEW

**Comment by aabadie** [comment]
I went a little further here:
- debugging the board with gdb is now configured. This is possible thanks to the edbg interface and is supported by avarice
- the radio seems to work out-of-the-box
- the failing automatice tests are only tests using the shell. This is due to a long delay between the reset moment and the moment when the shell is ready. I think this will be fixed by #12458 

This PR is no longer a draft.

**Comment by aabadie** [comment]
Thanks for reviewing @benpicco. If you don't mind, before merging, I'd like to provide more test results with this board.

**Comment by aabadie** [comment]
I tested a bit the radio with `examples/gnrc_networking` and it is working well: I was able to ping a RPI with 802.15.4 enabled :)

**Comment by aabadie** [comment]
Failing automatic tests:
```
Failures during test:
- [tests/bench_runtime_coreapis](tests/bench_runtime_coreapis/test.failed)
- [tests/bitarithm_timings](tests/bitarithm_timings/test.failed)
- [tests/event_wait_timeout](tests/event_wait_timeout/test.failed)
- [tests/evtimer_msg](tests/evtimer_msg/test.failed)
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed)
- [tests/gnrc_ipv6_ext_frag](tests/gnrc_ipv6_ext_frag/test.failed)
- [tests/gnrc_ipv6_fwd_w_sub](tests/gnrc_ipv6_fwd_w_sub/test.failed)
- [tests/gnrc_ndp](tests/gnrc_ndp/test.failed)
- [tests/gnrc_netif](tests/gnrc_netif/test.failed)
- [tests/gnrc_rpl_srh](tests/gnrc_rpl_srh/test.failed)
- [tests/gnrc_sock_dns](tests/gnrc_sock_dns/test.failed)
- [tests/gnrc_tcp](tests/gnrc_tcp/test.failed)
- [tests/isr_yield_higher](tests/isr_yield_higher/test.failed)
- [tests/libfixmath](tests/libfixmath/test.failed)
- [tests/malloc](tests/malloc/test.failed)
- [tests/periph_eeprom](tests/periph_eeprom/test.failed)
- [tests/periph_gpio](tests/periph_gpio/test.failed)
- [tests/pipe](tests/pipe/test.failed)
- [tests/pkg_c25519](tests/pkg_c25519/test.failed)
- [tests/pkg_jsmn](tests/pkg_jsmn/test.failed)
- [tests/pkg_lora-serialization](tests/pkg_lora-serialization/test.failed)
- [tests/pkg_micro-ecc](tests/pkg_micro-ecc/test.failed)
- [tests/ps_schedstatistics](tests/ps_schedstatistics/test.failed)
- [tests/pthread_barrier](tests/pthread_barrier/test.failed)
- [tests/stdin](tests/stdin/test.failed)
- [tests/trickle](tests/trickle/test.failed)
- [tests/xtimer_usleep_short](tests/xtimer_usleep_short/test.failed)
```

I'm looking into them.

**Comment by aabadie** [comment]
Too bad, you merged this on a little bit too early: the failing tests revealed a misconfiguration of the clock on that board. Indeed, it provides an external 16MHz oscillator that can be enabled by properly enabling the low fuse byte. I was just testing with this and it's fixing a lot of timeout issues in the tests.

Will provide this in a follow-up PR.

**Comment by aabadie** [comment]
BTW what is @riot-ci exactly ? how is behind this ?

**Comment by maribu** [comment]
Oh! I had this page open on my phone and never intended to merge it. I guess it unlocked in my pocket. Sorry!

**Comment by maribu** [comment]
Btw: The debugger included in this board cannot by chance be connected to other external ATmega boards?

**Comment by miri64** [comment]
> BTW what is @riot-ci exactly ? who is behind this ?

It's the account Murdock uses to access GitHub, so our CI team (@kaspar030, @smlng, ...)

**Comment by miri64** [comment]
I think I have access as well, somehow.

**Comment by miri64** [comment]
Why are you asking?

**Comment by aabadie** [comment]
> Why are you asking?

This message appeared in the PR yesterday:
`riot-ci pushed a commit to riot-ci/RIOT that referenced this pull request 13 hours ago `

Not sure what this is about.

**Comment by miri64** [comment]
Given these two PRs https://github.com/RIOT-OS/RobotFW-tests/pull/20, https://github.com/RIOT-OS/RobotFW-tests/pull/21, I guess @smlng was logged in as the wrong user again ;-).

**Comment by miri64** [comment]
I'm wondering however if and why @riot-ci needs push rights to master.

**Comment by smlng** [comment]
wasn't me, at least I wasn't using the riot-ci user lately (and also shouldn't anyway, other than by mistake). However, that commit or push was not done by me.

**Comment by aabadie** [comment]
> The debugger included in this board cannot by chance be connected to other external ATmega boards?

Something can be soldered on the back of the board but that doesn't seem very easy. Of course there's nothing in their user guide about that.

**Comment by maribu** [comment]
OK, I see. Thanks for the info!

**Pull request merged**
