### PR TITLE
Shell uart0 newlib distinction

### PR DESCRIPTION
**Pull request by OlegHahm**
Workaround for #3550 as long as uart0 is not phased out.

### CODE REVIEW

**Comment by haukepetersen** [comment]
shouldn't #3402 fix this situation for all platforms?

**Comment by OlegHahm** [comment]
Only if all platforms support getchar() which is currently not the case.

**Comment by OlegHahm** [comment]
Agreed, #3402 would be the nicer way, but seems on some platforms. (Builds, but won't react to input any more.)

**Comment by haukepetersen** [comment]
As we are fixing (or waiting for Travis to accept our fixes) these errors, we go with #3402, right? So should we close this PR?

**Comment by OlegHahm** [comment]
Agreed.

**Pull request closed without merging**
