### PR TITLE
gnrc_ipv6: fix SEGFAULT when multicasting with multiple interfaces [backport 2019.10]

### LINKED ISSUE #11980: Sending a packet to the Multicast Address with multiple interfaces causes Segmentation fault
#### Description
On RIOT, if there is more than once network interface, `ping6 ff02::1` will cause a segmentation fault.

#### Steps to reproduce the issue
In `examples/gnrc_networking`:

```
$ ../../dist/tools/tapsetup/tapsetup
$ sed -i '1i#define NETDEV_TAP_MAX 2' ../../cpu/native/include/netdev_tap_params.h
$ make GNRC_NETIF_NUMOF=2
$ bin/native/gnrc_networking.elf tap0 tap1
> ping6 ff02::1

Program received signal SIGSEGV, Segmentation fault.
0x5656dc02 in _fill_ipv6_hdr (netif=0x5659dcd8 <_netifs+312>, ipv6=0x5659de68 <_pktbuf+40>)
    at /home/benpicco/dev/RIOT/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c:308
308	    hdr->len = byteorder_htons(gnrc_pkt_len(ipv6->next));
(gdb) p hdr
$1 = (ipv6_hdr_t *) 0x40
```

#### Expected results
The packet should be send over both interfaces.
Also, `ipv6->data` should point to a valid address.

#### Actual results
RIOT crashes. This happens both on native and on actual hardware.

#### Versions
RIOT master (ca2b00875a9e91458ba361e293cc4e97d281ecf8)

### PR DESCRIPTION
**Pull request by miri64**
# Backport of #12512

### Contribution description
When writing to the IPv6 header the implementation currently doesn't take the packet with the (potentially) duplicated header, but the packet with the original one, which leads to the packet sent and then released in `gnrc_netif_ethernet.c` first and then accessed again in further iterations of the "writing to the IPv6 header" loop, which causes access to an invalid pointer, causing a crash.

### Testing procedure
When repeating the "Steps to reproduce" in #11980, the node should not crash and you get a lot of (duplicate) replies. When using two interfaces with one being a 6LoWPAN interface, the node should not crash, pinging might however not work due to the bug fixed in #10499.

### Issues/PRs references
Fixes #11980

### CODE REVIEW

**Comment by miri64** [comment]
https://github.com/RIOT-OS/RIOT/pull/12524 is already ACK'd and just waiting for Murdock. So I wait for that to be merged before I rebase.

**Comment by kb2ma** [comment]
OK, thanks for that comment. I'll review the commit, but wait for the rebase.

**Comment by miri64** [comment]
Rebased to current release branch

**Comment by kb2ma** [comment]
ACK. Commits identical and link-local multicast ping works on native.

**Pull request merged**
