### PR TITLE
cpu/stm32: added ADC for g0

### PR DESCRIPTION
**Pull request by david-vankampen**
### Contribution description

Adding ADC functionality for STM32 G0 series MCUs.

### Testing procedure

Verify calls to `adc_init` and `adc_sample` are compilable and linkable.

### CODE REVIEW

**Comment by benpicco** [comment]
Since this is almost identical with `adc_f0.c` why not do

```patch
--- a/cpu/stm32/periph/Makefile
+++ b/cpu/stm32/periph/Makefile
@@ -15,6 +15,8 @@ endif
 ifneq (,$(filter periph_adc,$(USEMODULE)))
   ifneq (,$(filter $(CPU_FAM),f4 f7))
     SRC += adc_f4_f7.c
+  else ifneq (,$(filter $(CPU_FAM),f0 f0))
+    SRC += adc_f0_g0.c
   else
     SRC += adc_$(CPU_FAM).c
   endif
diff --git a/cpu/stm32/periph/adc_f0.c b/cpu/stm32/periph/adc_f0.c
index 16e5f8d7bd..b33ae1a2de 100644
--- a/cpu/stm32/periph/adc_f0.c
+++ b/cpu/stm32/periph/adc_f0.c
@@ -33,12 +33,22 @@ static mutex_t lock = MUTEX_INIT;
 static inline void prep(void)
 {
     mutex_lock(&lock);
+#ifdef RCC_APB2ENR_ADCEN
     periph_clk_en(APB2, RCC_APB2ENR_ADCEN);
+#endif
+#ifdef RCC_APBENR2_ADCEN
+    periph_clk_en(APB2, RCC_APBENR2_ADCEN);
+#endif
 }
 
 static inline void done(void)
 {
+#ifdef RCC_APB2ENR_ADCEN
     periph_clk_dis(APB2, RCC_APB2ENR_ADCEN);
+#endif
+#ifdef RCC_APBENR2_ADCEN
+    periph_clk_dis(APB2, RCC_APBENR2_ADCEN);
+#endif
     mutex_unlock(&lock);
 }
```

instead?

**Comment by david-vankampen** [comment]
I created the new file b/c somewhere in the build system, it seemed hard-coded to just pull in `adc_{CPU_MODEL}.c` - the build failed b/c it could not find adc_g0.c.  So just making the changes in adc_f0.c seemed incorrect, because it wasn't looking for that file.  In addition, the filename would be misleading, b/c that would mean a g0 build was using an f0 file.  Thoughts?

**Comment by benpicco** [comment]
You can rename the file `adc_f0_g0.c` just like `adc_f4_f7.c`.
The adapt `stm32/periph/Makefile` accordingly.

**Comment by david-vankampen** [comment]
@benpicco done. Thank you for the suggestions!

**Comment by aabadie** [comment]
It would be better if one of G0 nucleo board configuration was adapted with some ADC pins. Because otherwise this code won't be compiled by the CI for G0 and it cannot be manually tested with just code in RIOT.

**Comment by david-vankampen** [comment]
@aabadie ok. Added A0-A5 for the nucleo-g070rb.

**Comment by aabadie** [comment]
Thanks. Note that you also have to update the Kconfig part in the board code: https://github.com/RIOT-OS/RIOT/blob/004b93edca4506f899dd438e99c0bb4fd2e8aace/boards/nucleo-g070rb/Kconfig#L17

Can you post the output of `tests/periph_adc` with a potentiometer connected to each of the pin ? (It just to verify that it works without having to dig into the board datasheet)

**Comment by benpicco** [comment]
also please squash 64755316144f0fc0740eed017e15cb670339f452 and 65188fb8615b161914cb4c6df32c3645253b3dc6 so there is only a single commit implementing ADC for STM32G0 and another one adding the ADC config for the nucleo board.

**Comment by david-vankampen** [comment]
@aabadie  I have a Nucleo-g071rb at hand, so I used that to test, which necessitated updating that board as well.  It revealed the need to reference `APB12` for the clock enablement as well, so, good test. :)  I also only have 1 potentiometer at hand, so I manually moved it from pin to pin, for ADCs 0-5.  They all worked, output similar, looked like this (filtered to the pin under test):
        

> 2021-09-24 09:33:51,063 # ADC_LINE(4): 3350
>         2021-09-24 09:33:51,163 # ADC_LINE(4): 4040
>         2021-09-24 09:33:51,264 # ADC_LINE(4): 4079
>         2021-09-24 09:33:51,364 # ADC_LINE(4): 3878
>         2021-09-24 09:33:51,464 # ADC_LINE(4): 666
>         2021-09-24 09:33:51,564 # ADC_LINE(4): 544
>         2021-09-24 09:33:51,664 # ADC_LINE(4): 530
>         2021-09-24 09:33:51,764 # ADC_LINE(4): 522
>         2021-09-24 09:33:51,864 # ADC_LINE(4): 521
>         2021-09-24 09:33:51,964 # ADC_LINE(4): 540
>         2021-09-24 09:33:52,064 # ADC_LINE(4): 544
>         2021-09-24 09:33:52,164 # ADC_LINE(4): 526
>         2021-09-24 09:33:52,264 # ADC_LINE(4): 533
>         2021-09-24 09:33:52,364 # ADC_LINE(4): 517
>         2021-09-24 09:33:52,465 # ADC_LINE(4): 529
>         2021-09-24 09:33:52,565 # ADC_LINE(4): 530
>         2021-09-24 09:33:52,665 # ADC_LINE(4): 529
>         2021-09-24 09:33:52,765 # ADC_LINE(4): 529
>         2021-09-24 09:33:52,865 # ADC_LINE(4): 537
>         2021-09-24 09:33:52,965 # ADC_LINE(4): 536
>         2021-09-24 09:33:53,065 # ADC_LINE(4): 526
>         2021-09-24 09:33:53,165 # ADC_LINE(4): 532
>         2021-09-24 09:33:53,265 # ADC_LINE(4): 535

@benpicco after rebasing, I am not seeing commit https://github.com/RIOT-OS/RIOT/commit/65188fb8615b161914cb4c6df32c3645253b3dc6 anymore.  Is the history as desired now?

**Comment by benpicco** [comment]
>  Is the history as desired now?

You still have 3 commits to implement the ADC feature on STM32G0.
Do the following:

    git rebase -i HEAD~5

 - move the line with `cpu/stm32: fixed APB12 reference` after `cpu/stm32: moved g0 adc definition into shared file with f0`
 - replace the `pick` on those two commits with `fixup` (`f` is enough)
 - save & exit 

Now you should be left with

```
cpu/stm32: added ADC for g0
boards/nucleo-g070rb: added ADC support to demo ADCs on the G0
boards/nucleo-g070rb + nucleo-g071rb: added ADC config
```

**Comment by david-vankampen** [comment]
@benpicco thank you so much for the instructions.  The first squash is done, will take a cut at the board one you mentioned now.

**Comment by david-vankampen** [comment]
@benpicco it seems to have merged them all to 1 now :( . Is that acceptable?

**Comment by benpicco** [comment]
just do a `git reset HEAD^` and create two new commits

**Comment by david-vankampen** [comment]
OK. I think I got it now. 1 commit for cpu, and then 1 commit per board.  Thank you again for the help.

**Review by aabadie — APPROVED** [review]
Thanks for providing the test output. I'm ok with the changes.

ACK

**Pull request merged**
