### PR TITLE
tests: use conversion macros and proper suffixes

### LINKED ISSUE #7301: tests: Delay being "u" instead of "ul" breaks delays on 8-bit/AVR platforms
Running tests on 8-bit platforms such as the AVR sometimes fails, because a delay of 100\*1000u results in 100000u which does not fit into 16bit unsigned values on 8-bit/AVR systems. This can be solved by either introduction SLEEP_100US variables for each architecture or simply by changing the delay to 100*1000ul.

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

This PR changes the value suffix from `U` to `UL` for time conversion macros.
Further it adapts timer values in tests to either use these macros or have proper suffixes to get correct values across all platforms. Specifically on 8 and 16 bit platforms such as Atmega based Arduinos.

### Testing procedure

Run various tests that use timer values, these should still work on any platform as before but should now also work correctly on lower bit platforms.

### Issues/PRs references

Fixes #7301

### CODE REVIEW

**Comment by roberthartung** [comment]
Looks good to me without having it tested!

**Comment by smlng** [comment]
I ran tests on arduino-uno which worked as expected.

**Comment by roberthartung** [comment]
@smlng Should we get this merged?

**Comment by miri64** [comment]
Needs rebase for that, though. This looks also like something @kaspar030 might be interested in.

**Pull request closed without merging**
