### PR TITLE
ipv6: move non-GNRC types and functions in their own module

### PR DESCRIPTION
**Pull request by authmillenon**
Since this was not possible to be done with a tool, this PR needs a little more careful review.

Depends on #3593.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current #3593

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by authmillenon** [comment]
And now for real :)

**Comment by authmillenon** [comment]
Rebased to current master. Can we merge these renaming PRs soonish? Rebasing them isn't really a lot of fun :-/

**Comment by OlegHahm** [comment]
ACK and go!

**Pull request merged**
