### PR TITLE
tools/can_fast_ci_run: several cleanups

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

After looking #17405, I thought the script could be slightly improved:
- rename the file variable in filename as it can be confusing. In the script file means a filename and in Python file can be used for a file object.
- there's double underscore used in one private method, only one is enough
- my proposal in https://github.com/RIOT-OS/RIOT/pull/17405#pullrequestreview-834925535 is also applied. So not only .h/.c are checked.

### Testing procedure

Not sure how to test this.

### Issues/PRs references

Follow-up of #17405

### CODE REVIEW

**Comment by kaspar030** [comment]
really...
- one commit doing both a simple rename and another rename. please split
- another commit adding a feature (cpp, hpp) and refactoring (changing the exception handling). please split.

preferably to seperate PRs. the renames can be in one. the refactoring in two, as the cpp/hpp stuff needs individual testing.

**Comment by aabadie** [comment]
Thanks for the review ! Very useful. Unfortunately, I don't want to spend more time on this. Please open a PR for the extra extensions change.Thanks again @kaspar030 !!

**Comment by kaspar030** [comment]
> Thanks for the review ! Very useful. Unfortunately, I don't want to spend more time on this. Please open a PR for the extra extensions change.Thanks again @kaspar030 !!

No need to get snarky. I'm serious, variable/method renames can be verified "visually", no need for (much) testing. That would be on auto-merge already. There's a reason PRs should do one thing.
Same goes for the exception rework.
Whether hpp/cpp actually works when using gcc, I don't know and I also don't want to spend time on this. So all changes would be blocked on someone testing that.

(These tests need to be done on CI, so preferably when the queue is short/empty...)

**Comment by aabadie** [comment]
> Whether hpp/cpp actually works when using gcc, I don't know and I also don't want to spend time on this. So all changes would be blocked on someone testing that.

That's unfortunate, you seem the most knowledgeable on that and since RIOT support C++ that could be an improvement.

**Comment by maribu** [comment]
I can test the C++ part, but I will be afk until at least next week. (Maybe I'll be able to get to it tonight when the kids are in bed, though)

**Comment by aabadie** [comment]
Hmm,I won't have time to update this PR. If someone thinks it's a useful cleanup and has some bandwidth, feel free to take over!

**Pull request closed without merging**
