### PR TITLE
CI: .murdock: fix bors fast build

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Currently, CI would not skip compilation for builds where `can_fast_ci_build.py`
can figure out that it should. That's because `cfcb.py` depends on `CI_BASE_COMMIT`
being set, which for a branch build like for bors' staging or trying, isn't.

This PR populates `CI_BASE_COMMIT` from the previous (second) merge commit, which
*should* always point to the base branch HEAD.

### Testing procedure

[here](https://ci.riot-os.org/details/701e23634700496e9c3b568422d4b1a2/output) is the result of a bors try of this PR, but with a "remove me"  commit disabling full builds on ".murdock" changes.

### CODE REVIEW

**Comment by kaspar030** [comment]
bors try

**Comment by kaspar030** [comment]
bors try

**Comment by kaspar030** [comment]
- added some comments

**Review by maribu — APPROVED** [review]

**Comment by kaspar030** [comment]
bors merge

**Pull request merged**
