### PR TITLE
pkg/libcoap: adapt Makefile to fix compile error

### PR DESCRIPTION
**Pull request by smlng**
fixes compile error in pkg/libcoap revealed in #8029

### CODE REVIEW

**Comment by smlng** [comment]
Murdock [output](https://ci.riot-os.org/RIOT-OS/RIOT/8029/8bc85b78695fc4cc068224d1d81965d9a32ccb62/output.html) for reference

**Comment by cladmi** [comment]
In libcoap, the `debug.c` file already has patches, so I would prefer fixing it to include `string.h` rather than disabling the warning.

**Comment by smlng** [comment]
@cladmi I fixed the patch as you suggested

**Comment by cladmi** [comment]
Instead of disabling `strlen`, you can enable it in the package makefile with:
```
-+CFLAGS += -DWITH_POSIX
++CFLAGS += -DWITH_POSIX -D_GNU_SOURCE=1
```

**Comment by smlng** [comment]
@cladmi wasn't aware of that, thanks for the pointer I'll give it a try!

**Pull request merged**
