### PR TITLE
gnrc: make all gnrc modules sub-modules of gnrc

### PR DESCRIPTION
**Pull request by authmillenon**
One PR to rule them all,
One PR to find them,
One PR to bring them all,
And in GNRC bind them.

Depends on ~~#3595~~, ~~#3599~~, ~~#3602~~, and ~~#3642~~ ~~#3653~~.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current master and adapted to it.

**Comment by OlegHahm** [comment]
And another rebase is due.

**Comment by authmillenon** [comment]
T.T

**Comment by authmillenon** [comment]
Finally rebased. Took me a while.

**Comment by OlegHahm** [comment]
Honestly: I won't review more than 4000 lines of renaming. We have to trust testing here.

**Comment by authmillenon** [comment]
Please test at least a RPL multi-hop configuration! I'm honestly not sure if I broke something there (1-hop is fine).

**Comment by authmillenon** [comment]
(at least before the last rebase :/)

**Comment by OlegHahm** [comment]
For all the renaming PRs I tested with multi-hop on IoT-LAB.

**Comment by authmillenon** [comment]
Just to be 100% sure that you know what you are signing here: this PR reverts in huge parts the directory-layer-cake you introduced.

**Comment by authmillenon** [comment]
(only for the GNRC parts).

**Comment by OlegHahm** [comment]
And why?

**Comment by authmillenon** [comment]
Because all gnrc modules are moved to the `sys/net/gnrc/` path.

**Comment by OlegHahm** [comment]
Yes, but why?

**Comment by authmillenon** [comment]
Because that is what this PR is supposed to do: moving all GNRC modules to the GNRC module.

**Comment by OlegHahm** [comment]
Why not `sys/net/gnrc/<LAYER>`? IMO that makes it much easier to find stuff if you're not familiar with the implementation. (That's the reason why I introduced it in the first place.)

**Comment by authmillenon** [comment]
(I can however make the directory structure apparent in the gnrc module too, that is a comparably easy fix).

**Comment by OlegHahm** [comment]
I would prefer this.

**Comment by authmillenon** [comment]
Can we have a compromise and leave the "crosslayer" sub-modules in `sys/net/gnrc/`?

**Comment by OlegHahm** [comment]
Yes, most modules weren't really crosslayer anyway.

**Comment by authmillenon** [comment]
```bash
git mv nomac/ slip/ netdev_eth/ link_layer/
git mv icmpv6/ ipv6/ ndp/ sixlowpan/ network_layer/
git mv udp/ transport_layer/
git mv rpl/ routing/
```

Did I miss something? (AODV and NHDP are not ported for GNRC yet and thus not in GNRC).

**Comment by authmillenon** [comment]
Ah

```
git mv zep application_layer/
```

**Comment by authmillenon** [comment]
Done.

**Comment by OlegHahm** [comment]
Actually, I think `sys/net/gnrc/util` or similar would be a btter fit, but that can be done later if we decide, too. So far this seems not to break anything. ACK if Travis is green.

**Comment by authmillenon** [comment]
Great, now let's hope that this does not conflict until it got merged. Thanks for the review!

**Comment by authmillenon** [comment]
Fixed the documentation issue and squashed immediately.

**Comment by authmillenon** [comment]
\o/

**Pull request merged**
