### PR TITLE
boards/sensebox_samd21: fix RTT configuration

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The board did not have an updated RTT configuration yet.
Also remove the obsolete RTC configuration.

### Issues/PRs references

split off #14416

### CODE REVIEW

**Comment by fjmolinas** [comment]
`periph_rtt` doesn't seem to be provided for this board though.

**Comment by benpicco** [comment]
Fixed - if `periph_rtc` is provided, `periph_rtt` is provided too.

**Comment by fjmolinas** [comment]
@leandrolanzieri can you test just in case?

**Comment by leandrolanzieri** [comment]
> @leandrolanzieri can you test just in case?

Yes, I will test shortly

**Comment by leandrolanzieri** [comment]
Both tests are still working correctly:

<details><summary><b>tests/periph_rtt</b></summary>

```
READY
s
START
main(): This is RIOT! (Version: 2020.07-devel-1731-ge4cb2b-boards/sensebox_samd21/rtc_config)

RIOT RTT low-level driver test
This test will display 'Hello' every 5 seconds

Initializing the RTT driver
RTT now: 2
Setting initial alarm to now + 5 s (163842)
Done setting up the RTT, wait for many Hellos
Hello
Hello
Hello
Hello
Hello
```
</details>

<details><summary><b>tests/periph_rtc</b></summary>

```
READY
s
START
main(): This is RIOT! (Version: 2020.07-devel-1731-ge4cb2b-boards/sensebox_samd21/rtc_config)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59

Alarm!
Alarm!
Alarm!
Alarm!
```
</details>

**Pull request merged**
