### PR TITLE
modernizing stm32f0 driver

### PR DESCRIPTION
**Pull request by MohmadAyman**
if someone can delete this PR because things got really messed up there https://github.com/RIOT-OS/RIOT/pull/3753

### CODE REVIEW

**Comment by haukepetersen** [comment]
nice effort. I am not sure I understand your comment correctly -> do you want to close this PR or your previous one (#3753)?

**Comment by MohmadAyman** [comment]
the previous one

**Comment by MohmadAyman** [comment]
just a quick question, is there a way to test my code without pushing ?

**Comment by MohmadAyman** [comment]
can anyone please reopen this PR
sorry for the trouble, i've had a very bad time trying to solve merge conflicts so i had to recreate the  branch from scratch

**Comment by Kijewski** [comment]
Sorry, you have deleted the branch. You need to recreate it before the PR can be opened again. I think you can reopen it yourself, but just leave us a message if not and someone will open it again.

I use `git rebase -i origin/master` to
* rebase (i.e. to update to a newer upstream revision),
* squash commits (i.e. merge a bunch of commits onto one),
* reorder commits if it is more logical,
* drop test commits that I don't need anymore,
* and cherry-pick commits.

One command that solves most of your needs. Git is still sometimes a hassle, but at least you won't have some wrong commits in your branch.

**Comment by MohmadAyman** [comment]
I recreated the master branch, but i still can't reopen the PR.
Thanks @Kijewski  for your helpful comment, i'll try to be more cautious with git next time, 
just to make sure thing wont break again, is there sth wrong with this sequence ?
*git checkout master*
*git fetch origin*
*git merge master*
*git checkout -b new_feature*
*git push -u origin new_feature*
*git rebase -i origin/master*
*git checkout master
git pull origin master
git merge --no-ff new_feature
git push*

**Pull request closed without merging**
