### PR TITLE
ng_sixlowpan_frag: preempt fragmentation

### LINKED ISSUE #3517: gnrc: message queue of MAC runs full for more than 6LoWPAN 8 fragments
When one tries to send packets >900 byte via 6LoWPAN the message queue of `ng_nomac` runs full and isn't emptied anymore, apparently. An asynchronous fragmenting of send packets would help (and also would allow for non-blocking sending of 6LoWPAN frames). Currently 6LoWPAN sends fragments until the whole packet is send.

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes #3517 the simplest way (without resizing the queue of the MAC).

### CODE REVIEW

**Comment by OlegHahm** [comment]
This seems to include #3518 or am I mistaken?

**Comment by OlegHahm** [comment]
Nice! Works like charme:
```
1000 packets transmitted, 995 received, 1% packet loss, time 211.06447901 s
```

**Comment by OlegHahm** [comment]
ACK

**Comment by PeterKietzmann** [comment]
As this PR is labeled with "bug" and  @OlegHahm ACKed, I'll merge this now.

**Comment by authmillenon** [comment]
@OlegHahm yes since they were of different topic, but it was merged anyway now :-)

**Comment by OlegHahm** [comment]
I was just confused because the Label wasn't set.

**Comment by authmillenon** [comment]
True. Must have forgot about that… but in that case it wasn't really that critical.

**Pull request merged**
