### PR TITLE
sys/shell_commands: Makefile: converted tabs to spaces

### PR DESCRIPTION
**Pull request by haukepetersen**
stumbled upon another one, see #2626 for explanation.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
The commit message is a bit confusing.. did you change tabs to spaces? why? which makefile are you referring to?

**Comment by haukepetersen** [comment]
quote by @authmillenon:
> This is on purpose (at least for my part). Tabs and spaces are interpreted differently by make: tabs are interpreted as “the following line contains a command for a target” (which these lines don't carry) [Source], while spaces don't have any syntactic connotations. Though the manual states that it is in these cases arbitrary, using tabs for this kind of indentations already lead to problems in the past which is why I try to not use them for simple eye-candy indentatitions between ifneq() macros e.g. anymore.

So if we agree to use two spaces for indention of if clauses in Makefiles, this should be done everywhere consistently...

**Comment by authmillenon** [comment]
I think @LudwigOrtmann was more criticising the Commit's summary, not its content.

**Comment by haukepetersen** [comment]
I see. I thought it was quite clear... Changed the commit message and the PR title anyway :-)

@LudwigOrtmann better?

**Comment by LudwigOrtmann** [comment]
Thanks, it's much better now.

**Comment by authmillenon** [comment]
ACK.

**Comment by haukepetersen** [comment]
and go.

**Pull request merged**
