### PR TITLE
boards/nucleo-l1: fix non closed doxygen block

### PR DESCRIPTION
**Pull request by aabadie**
Small doxygen fix in nucleo-l1 periph_conf.

### CODE REVIEW

**Comment by miri64** [comment]
Seconded (and tested)

**Comment by miri64** [comment]
(unrelated: timer and uart are not parsed correctly either. Probably due to the usage of `@brief` instead of `@name`)

**Comment by aabadie** [comment]
> (unrelated: timer and uart are not parsed correctly either. Probably due to the usage of @brief instead of @name)

Good catch and this problem is present in a lot of other places ;)

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/issues/6466

**Pull request merged**
