### PR TITLE
Small fatfs usability fixes

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

This is a collection of the small things that make life easier for someone who wants to give fatfs a try:

* Name the tarball of tests/pkg_fatfs .tar.bz2 (tools like [atool](https://www.nongnu.org/atool/) do look at extensions)
* Make the extraction routine work even when bin/ has not yet been created (with Makefile style fixes as bycatch)
* **Tell user what to do when enabling fatfs to get a usable example (because the disk can't format itself)**

### Testing procedure

* In `tests/pkg_fatfs`, run (there is not automation for this, is there?):

    ```
    $ make image all term
    > mount 0
    mounting file system image...
    [OK]
    Volume name: 
    0,124 GiB of 0,124 GiB available
    > ls
    //TEST.TXT
    ```

* In `examples/filesystem`, follow the new set of instructions and observe that indeed the file system becomes usable with a TEST.TXT present from startup.

### CODE REVIEW

**Comment by benpicco** [comment]
We can also wire up format, the only issue is how to provide memory for the workbuffer #14430

**Comment by chrysn** [comment]
Yeah, but that has dragged on long, and it's not like getting a ready-made file system with content rather than a blank one (or seeing that disk geometries matter here) is not helping the user.

(Does that PR need a review to get unstuck, or discussion, or changes?)

**Comment by benpicco** [comment]
I think it needs consensus on where to get the 512 bytes memory needed while formatting:

 - dynamic allocation with `malloc()` and `free()`
 - static allocation
 - put it on the stack and hope for the best

**Review by benpicco — APPROVED** [review]
regardless, those doc improvements are still useful.

**Pull request merged**
