### PR TITLE
doc/emulator: update qemu doc with unix sockets

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

The documentation update of qemu emulator, in particular the part about the local TCP port, was missed in #17679. This PR fixes that.

### Testing procedure

Just a documentation update

### Issues/PRs references

Missed in #17679

### CODE REVIEW

**Comment by kfessel** [comment]
sorry i missed that documentation but there is another change:

EMULATOR_SERIAL_PORT  is no longer at a fixed position /tmp/riot_$(APPLICATION)_$(BOARD)_uart. but at /tmp/riot_$(APPLICATION)_$(BOARD)_<random>/uart

**Comment by kfessel** [comment]
and right now looking at it i think the name of my tmp-dir variable is not well choosen RUNTIME_TMP_DIR should be something like EMULATION_TMP_DIR

**Comment by aabadie** [comment]
`EMULATOR_SERIAL_PORT` is a common variable for qemu and renode but not computed the same after #17751. I pushed a commit to update that and adapt the documentation.

I can rename `RUNTIME_TMP_DIR` to `EMULATOR_TMP_DIR` if you prefer.

**Comment by aabadie** [comment]
> I can rename RUNTIME_TMP_DIR to EMULATOR_TMP_DIR if you prefer.

Done!

**Comment by kfessel** [comment]
> I can rename `RUNTIME_TMP_DIR` to `EMULATOR_TMP_DIR` if you prefer.

Yes please (runtime makes me think of language runtime)

other than that these the doc changes are good

**Review by kfessel — APPROVED** [review]
thanks you for the documentation and the Name-Change

**Pull request merged**
