### PR TITLE
cpu: Add clock source selection based on CLOCK_HSE or CLOCK_HSI for STM32F0 family

### PR DESCRIPTION
**Pull request by DipSwitch**
One more with #3703 in mind.

Propose to configure the STM32F0 PLL clock source with the CLOCK_HSE or CLOCK_HSI define in the includes\periph_conf.h from the BSP

### CODE REVIEW

**Comment by DipSwitch** [comment]
Can't test HSI and HSE implementation

**Comment by OlegHahm** [comment]
What's the latest here?

**Comment by DipSwitch** [comment]
rebased and squashed.

**Comment by PeterKietzmann** [comment]
Code looks fine to me. Doesn't break the stm32f0discovery (which has no HSI available). Will check other related PRs first

**Comment by PeterKietzmann** [comment]
Dammit! Don't know what I had in mind writing the last comment but the stm32f0discovery (of course) has a HSI (definitions seem to be somewhere [here](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32f0/include/stm32f051x8.h#L1884))

**Comment by DipSwitch** [comment]
Yup this was the last one, fixed the implementation. Sorry about that...

For HSI test you would need to set the HSI to 8MHz but the maximum clock speed then can't exceed 24MHz since you always need to divide by 2.

**Comment by DipSwitch** [comment]
Didn't had the hardware yet, but got meself some discovery and nucleo's so I don't have to write a BSP for each MCU my own =)

**Comment by PeterKietzmann** [comment]
Works on stm32f0discovery now

**Comment by PeterKietzmann** [comment]
Mudruck agrees. ACK and go

**Pull request merged**
