### PR TITLE
cpu, cc2538: fix pm, don't go into  cortexm_sleep(0) [2017.10 backport]

### PR DESCRIPTION
**Pull request by smlng**
back port of #7752

### CODE REVIEW

**Comment by smlng** [comment]
@miri64 thx for fixing the title 😉

**Comment by miri64** [comment]
> ACK. Not sure why the commit is not the same...

Because the base-branch is different => different parent => different content of commit => different hash of content. Come-on @kYc0o, learn 2 git ;-) [[1]](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects#_git_commit_objects).

**Comment by kYc0o** [comment]
> Because the base-branch is different => different parent => different content of commit => different hash of content. Come-on @kYc0o, learn 2 git ;-) [1].

Hahaha thanks for the git-tree explanation!

**Comment by smlng** [comment]
IIRC we have/had this 

> the commit is not the same.

discussion for back ports once every release in the past 😄

**Comment by miri64** [comment]
> Hahaha thanks for the git-tree explanation!

Trees (git's representation of directories) have nothing to do with it. If their content is the same they should have the same hash (which in our case they are not, since the content of the trees already diverged here also):

```
$ git cat-file -p 1e1330f
tree b035a3ac8af4404268c5725f72236586ff3a33e2
parent 79b34a722a55dd59a09029054e540fb79f09d589
author smlng <s@mlng.net> 1508320754 +0200
committer smlng <s@mlng.net> 1508335250 +0200

cpu, cc2538: fix pm, don't go into  cortexm_sleep(0)

    fixes #7746
$ git cat-file -p fc5c432
tree e08072839336bbc7f6c729902941327d0c0cf55a
parent 1fec7e690c9ab32819695931ec9512f90ba3ae4c
author smlng <s@mlng.net> 1508320754 +0200
committer smlng <s@mlng.net> 1508335298 +0200

cpu, cc2538: fix pm, don't go into  cortexm_sleep(0)

    fixes #7746
$ diff <(git cat-file -p e080728) <(git cat-file -p b035a3a)
15c15
< 040000 tree 9c056722a511f41efc826b726862e12f108eca39	boards
---
> 040000 tree a086a0fb8744496e0fb5be874e8220c299d355df	boards
17c17
< 040000 tree 2716e7f3e7f8f844f649dab8364a583e8f37be0c	cpu
---
> 040000 tree 87e6cc2f93fcf40adbf70d374ae1893e9891c83d	cpu
20,21c20,21
< 040000 tree 61a8f4bb6e06faa7e96e5a2f8ab81af4a154e47c	doc
< 040000 tree a2a07df386a9648a5453be1d633c96a2eff08f80	drivers
---
> 040000 tree af27f5ccd3ed7133518dfece580c9c6d82e26f97	doc
> 040000 tree e8fad0a8790192e42e37ddf786bb74990776f1d5	drivers
26,27c26,27
< 040000 tree 7a3c69aee83600aa9dd99ce6a99fbcebc6db48f1	sys
< 040000 tree cfdbb713871fd7d4c9e72c93fec65d2033b655d1	tests
---
> 040000 tree b98e8bdb7d426a8792e86a7049de57c0995f549d	sys
> 040000 tree a18b1e7d8e5b2df8cfa06fb049b6a24c4dd18252	tests
```

**Pull request merged**
