### PR TITLE
can: merge candev with netdev [WIP]

### LINKED ISSUE #7294: RFC: merge candev API into netdev API
Looking at the newly merged candev API I still don't see, why this has to be its own API apart from netdev:

* The receive mechanism is nearly the same (except that there is no receive function, I'm guessing the frame is passed via the event callback).
* The only difference in the two `send()` is that `can` gives the explicit frame, instead of a vector array with the data
* `init()`, `isr()`, `set()` and `get()` are the same (the latter to just get a new option set)
* `abort()`, `set_filter()` and `remove_filter()` can be implemented using `set()` and corresponding `NETOPT`s

I understand that CAN's communication paradigm is different from how other packet-switched radios work, so there might never be an IP over CAN ([but people tried](https://tools.ietf.org/html/draft-cafi-can-ip-00)), but at least for a programmer it might be nice to not get used to a same but different API.

### PR DESCRIPTION
**Pull request by vincent-d**
This is an attempt to fix #7294.

This still need some work to clean up and try with other drivers (I gave a try with stm32, though).

My only concern is about tx confirmation, which are not routed to the upper layer anymore. I didn't find a way which suits the netdev API.

### CODE REVIEW

**Comment by miri64** [comment]
Are you still working on this? Might need a rebase.

**Comment by vincent-d** [comment]
I postponed that one, not sure I'll have time to work on it soon.

**Comment by miri64** [comment]
Alright! Thanks for the information.

**Comment by miri64** [comment]
A side-comment: maybe #8198 is beneficial for you here as well.

**Comment by vincent-d** [comment]
Not going to work on this anytime soon.

I wish I could spend more time on this, but unfortunately this is not on top of my priority list...

So closing.

**Pull request closed without merging**
