### PR TITLE
make: run static_tests.sh directly with `static-tests` target 

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This cleans up the `make static-tests` target to call `dist/tools/ci/static_tests.sh` directly instead of first calling `dist/tools/static-tests.sh` which calls `./dist/tools/ci/build_and_test.sh` which then calls `dist/tools/ci/static_tests.sh`.

The only point in doing it that way, is I believe, that ther is an (incomplete) dependency check in `dist/tools/static-tests.sh`. That dependency check I improved and completed and moved it to `dist/tools/ci/static_tests.sh` and adapted it for the look and feel of that script.

### Testing procedure
Run

```sh
make static-tests
```

(also done by the `static-tests` GitHub action). If you have any uninstalled dependency for those tests, the script will report that.

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
Mhhh... `uncrustify` seems to be not installed in the RIOT docker :D

**Comment by jia200x** [comment]
hmmm I noticed the License check runs twice. Is it expected?

**Comment by miri64** [comment]
> hmmm I noticed the License check runs twice. Is it expected?

Yes, they use two different difffilters. One for modified and renamed files, one for added and copied files. The first generates only a warning (the author of the change might not have introduced that license), the second generates an error, making the static tests fail.

**Comment by jia200x** [comment]
then, everything runs as expected :). Tried both in my laptop and Docker

**Review by jia200x — APPROVED** [review]
ACK. Please remove the bogus commit and let's wait for the CI

**Comment by miri64** [comment]
> Please remove the bogus commit and let's wait for the CI

Done.

**Comment by miri64** [comment]
Fixed an unrelated spelling error.... no idea why that file is even checked...

**Pull request merged**
