### PR TITLE
cpu/nrf5x_common/periph_timer: fix spurious IRQs

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title says

### Testing procedure

The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/18963

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK

**Comment by maribu** [comment]
The single CI failure was on `native`:

```
-- running on worker comsys thread 1, build number 2488.
make: Entering directory '/tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/examples/suit_update'
# Reset package to checkout state.
rm -rf /tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/build/pkg/c25519
rm -rf /tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/build/pkg-build/libcose
rm -rf /tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/build/pkg-build/littlefs2
rm -rf /tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/build/pkg-build/nanocbor
make: Leaving directory '/tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/examples/suit_update'
make: Entering directory '/tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/examples/suit_update'
make: *** No rule to make target '/tmp/dwq.0.5191207894204415/945d734232500d3d47e2ddb89f802ef5/examples/suit_update/bin/native/suit_update/fw.1669339261.bin', needed by 'link'.  Stop.
[...]
```

This is obviously unrelated. I'm skipping build tests now and call the last run a pass.

**Comment by maribu** [comment]
Thx :)

**Comment by maribu** [comment]
Backport provided in #18974

**Pull request merged**
