### PR TITLE
emb6: API updates in hal_getrand()

### PR DESCRIPTION
**Pull request by miri64**
This this build branch doesn't seem to be build, this slipped through
back, when the PNRG functions were renamed.

### CODE REVIEW

**Comment by miri64** [comment]
> Shouldn't it be `#ifdef FEATURE_PERIPH_HWRNG`

I thought this is `MODULE_PERIPH_HWRNG` now... @kaspar030 @haukepetersen can you clarify?

**Comment by PeterKietzmann** [comment]
Whoops, your are right (though `FEATURE_PERIPH_HWRNG` is still generated). But you agree that it's not `RANDOM_NUMOF`, do you?

**Comment by miri64** [comment]
Yepp.

**Comment by miri64** [comment]
Fixed

**Pull request merged**
