### PR TITLE
boards: core: cpu: drivers: sys: added missing header guards

### PR DESCRIPTION
**Pull request by BytesGalore**
This PR adds missing guards to headers across RIOT

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@BytesGalore could you rebase? I think you can also squash the commits

**Comment by BytesGalore** [comment]
@PeterKietzmann rebased.

**Comment by gebart** [comment]
Like I wrote in another PR (https://github.com/RIOT-OS/RIOT/pull/2355#discussion_r23561946)

>Leading underscores are not really recommended in include guard macro names.
>
>http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf
>
>>    7.1.3 Reserved identifiers
>>    All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use.

Can you change the include guards to remove the leading double underscores?

**Comment by BytesGalore** [comment]
@gebart done and removed a double-guard caused due to merge

**Comment by PeterKietzmann** [comment]
Well I'm also fine without leading double underscores and would ACK this when squashed

**Comment by BytesGalore** [comment]
@PeterKietzmann squashed

**Comment by PeterKietzmann** [comment]
I wanted to wait for Travis but he came to nothing. So I'll just merge this as it does not change anything crucial

**Comment by PeterKietzmann** [comment]
&go

**Pull request merged**
