### PR TITLE
gnrc_netdev: cleanup

### PR DESCRIPTION
**Pull request by OlegHahm**
This PR removes an unused header and non-existing modules from the Makefiles. As a bonus it adds a missing dependency to Makefile.dep.

### CODE REVIEW

**Comment by authmillenon** [comment]
This was still in? oO

ACK! and go as soon as the CIs are willing to pick up this PR and say its alright ^^.

**Comment by authmillenon** [comment]
Ah now Travis picked it up. Lets do RIOT CI its thing too :-)

**Comment by authmillenon** [comment]
@kaspar030 Is that a bug that RIOT CI won't pick up this PR?

**Comment by OlegHahm** [comment]
We need another cortex_m group for Travis. :-( But this is unrelated to this PR.

**Comment by authmillenon** [comment]
The result is good enough for me. Go!

**Pull request merged**
