### PR TITLE
Largely revert "Merge pull request #16776 from chrysn-pull-requests/shell-make-fixes-2"

### PR DESCRIPTION
**Pull request by chrysn**
This reverts commit d4ed42ad8f9049b99824122b8cdf530bff287edd, reversing
changes made to 2bf1202fb9812c6bc8a7aa63720b17c828d944ad.

Additions to the checks are left in place, but disabled while the
current state would not pass them.

---

Sorry, I messed up there -- this should get things going again. (More text when the PR is sent and tests are running in parallel).

### CODE REVIEW

**Comment by miri64** [comment]
> Sorry, I messed up there -- this should get things going again. (More text when the PR is sent and tests are running in parallel).

Sad the summit isn't in person. I'm sure everyone would have liked a fresh beer ;-P

**Comment by chrysn** [comment]
Ok, nope: this still fails one of the introduced checks (I thought I had caught them all in the first PR). Thus lets' go with yours and cancel this run.

(And yes, I definitely do owe a round).

**Comment by chrysn** [comment]
(For posteriority, build_system_sanity_check/check.sh erred out with:

```
 Command output:
  
  	Invalid build system patterns found by ./dist/tools/buildsystem_sanity_check/check.sh:
  	Redirecting stderr and stdout to /dev/null is `>/dev/null 2>&1`; the other way round puts the old stderr to the new stdout.:
  		dist/testbed-support/makefile.iotlab.single.inc.mk:60:ifneq (0,$(shell command -v iotlab-experiment -h 2>&1 > /dev/null ; echo $$?))
  	Redirecting stderr and stdout to /dev/null is `>/dev/null 2>&1`; the other way round puts the old stderr to the new stdout.:
  		dist/testbed-support/makefile.iotlab.single.inc.mk:69:    ifneq (0,$(shell command -v iotlab-ssh -h 2>&1 > /dev/null ; echo $$?))
  
  Error: Redirecting stderr and stdout to /dev/null is `>/dev/null 2>&1`; the other way round puts the old stderr to the new stdout.
  Error: Redirecting stderr and stdout to /dev/null is `>/dev/null 2>&1`; the other way round puts the old stderr to the new stdout.
```

so I cancelled this one's murdock run in favor of #16803, which also has a nicer commit message)

Closing this.

**Comment by miri64** [comment]
> […] in favor of #16803, which also has a nicer commit message)

The wonders a Revert button in Github can do ^^

**Pull request closed without merging**
