### PR TITLE
drivers/xbee: declared private functions as static

### PR DESCRIPTION
**Pull request by haukepetersen**
seems like I forgot some `static` declarations...

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK - go if Travis is green.

**Comment by haukepetersen** [comment]
rebased.

**Comment by haukepetersen** [comment]
hm, something wrong with Travis again?

**Comment by PeterKietzmann** [comment]
definitively yes!

**Comment by authmillenon** [comment]
And go.

**Pull request merged**
