### PR TITLE
drivers/sx127x: add gpio pull config define for DIO pins

### PR DESCRIPTION
**Pull request by MichelRottleuthner**
### Contribution description
When testing #11022 I discovered that from time to time some spurious interrupts are triggered.
This adds a define to the sx127x driver that sets the gpios of the DIO pins to pull down by default because 
many lora modules actually come without pull resistors equipped (e.g. [I-NUCLEO-SX1272D](https://www.st.com/en/evaluation-tools/i-nucleo-sx1272d.html), [SX1276MB1xAS](https://os.mbed.com/components/SX1276MB1xAS/), [DRF1272F](https://www.tindie.com/products/DORJI_COM/868mhz-lora-sx1272-module-drf1272f/))

### Testing procedure
[edit] set `ENABLE_DEBUG (1)` in `pkg/semtech-loramac/contrib/semtech_loramac.c` then
flash tests/pkg_semtech-loramac on some nucleo board with one of the above modules connected and either leave it running for some hours or provoke an interrupt by touching the DIO3 Pin (aka PB4 or PWM//D5 on nucleo64 boards).
~Because of another bug in the driver this actually triggers a hardfault/reset.~ [edit] fixed by #11134

### Issues/PRs references
none

### CODE REVIEW

**Comment by jia200x** [comment]
nice and clean. Thanks!

**Comment by aabadie** [comment]
Maybe @fjmolinas could have a look since he also has the related hardware.

> Because of another bug in the driver this actually triggers a hardfault/reset.

Can you describe this bug ?

**Comment by jia200x** [comment]
> Because of another bug in the driver this actually triggers a hardfault/reset.

The CadDone pointer in the RadioEvents_t descriptor is never filled in the current pkg version.
Thus, a NETDEV_EVENT_CAD_DONE will call a null pointer.

I will fix it asap unless someone opens it first :)

**Comment by MichelRottleuthner** [comment]
I didn't describe the other bug in more detail because I thought @jia200x would be faster with opening the respective PR ;)

**Comment by jia200x** [comment]
> The CadDone pointer in the RadioEvents_t descriptor is never filled in the current pkg version.
Thus, a NETDEV_EVENT_CAD_DONE will call a null pointer.

See https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/mac/LoRaMac.c#L2521

**Comment by jia200x** [comment]
> I didn't describe the other bug in more detail because I thought @jia200x would be faster with opening the respective PR ;)

I'm in the middle of a huge rebase. When finished, I go with that one :)

**Comment by dylad** [comment]
Changes look unharmful to me.
One can still override the `SX127X_DIO_PULL_MODE` locally. Most MCUs (all ?) have selectable internal pull-down resistor so I guess it's fine.

**Pull request merged**
