### PR TITLE
tests: add more hardware in the loop tests

### PR DESCRIPTION
**Pull request by kYc0o**
### Contribution description
This PR adds more automated tests on the CI. I tested them on OS X and some failed,
but it's maybe related to my configuration. If it shows that there's a problem there, I'll
remove them from the list.

### Issues/PRs references
#8801

### CODE REVIEW

**Comment by kYc0o** [comment]
> @miri64 can you take a look to the socket_zep test?

Talked with her offline, it "needs" networking which is not provided by the docker image.

For the gnrc_netif I have no idea, since the tests works locally both in native and samr21-xpro.

pkg_cayenne-lpp has different outputs in OS X native, Linux native and samr21-xpro. @aabadie do you have an idea why these are different? If there's no reason is hard to have it as a test, since it's not reproducible in different architectures.

**Comment by miri64** [comment]
> Talked with her offline, it "needs" networking which is not provided by the docker image.

To go a little bit more in detail here: The test script use sockets to send data to the native application. Apparently (according to @bergzand), the docker image doesn't have any interfaces, which might be the reason, why binding the socket (and thus the tests) fail.

**Comment by bergzand** [comment]
> Apparently (according to @bergzand), the docker image doesn't have any interfaces

This was just a guess :)

**Comment by aabadie** [comment]
@kYc0o, see #9019 regarding the issue with cayenne-lpp.

**Comment by cladmi** [comment]
For me `gnrc_netif` fails on `samr21-xpro` on IoT-LAB: https://gist.github.com/cladmi/83301f7af482fbe0fec6b01511e7d301

**Comment by cladmi** [comment]
@miri64 I found one problem with the `gnrc_netif`, when executed on my samr21 from computer, I get this output mixed in the middle, where `Sending data` is done before the end of `pktdump`:

```
2018-05-14 15:19:46,238 - INFO # pktdump dumping IEEE 802.15.4 packet with empty payload
2018-05-14 15:19:46,241 - INFO # PKTDUMP: data received:
2018-05-14 15:19:46,245 - INFO # ~~ SNIP  0 - size:   0 byte, type: NETTYPE_UNDEF (0)
2018-05-14 15:19:46,251 - INFO # 00000000~~ SNIP  1 - size:  26 byte, type: NETTYPE_NETIF (-1)
2018-05-14 15:19:46,253 - INFO # if_pid: 7  rssi: 11  lqi: 0
2018-05-14 15:19:46,254 - INFO # flags: 0x0
2018-05-14 15:19:46,258 - INFO # src_l2addr: 3e:e6:b5:0f:19:22:fd:0b
2018-05-14 15:19:46,263 - INFO # dst_l2addr: 3e:e6:b5Sending data from IEEE 802.15.4 device:
2018-05-14 15:19:46,270 - INFO # 00000000  41  D8  09  00  00  FF  FF  0A  FD  22  19  0F  B5  E6  3E  7B
2018-05-14 15:19:46,275 - INFO # 00000010  4B  3A  02  85  00  7B  B8  00  00  00  00
```

We can see that `dst_l2addr` is not correctly printed as the following function is executed.

If I add some delay in `_test_trigger_recv` the test works

``` diff
diff --git a/tests/gnrc_netif/common.c b/tests/gnrc_netif/common.c
index 5a29d29..3ec6efe 100644
--- a/tests/gnrc_netif/common.c
+++ b/tests/gnrc_netif/common.c
@@ -23,6 +23,7 @@
 #include "net/ipv6.h"
 #include "net/netdev_test.h"
 #include "od.h"
+#include "xtimer.h"
 
 static netdev_test_t _devs[GNRC_NETIF_NUMOF];
 
@@ -82,6 +83,7 @@ void _test_trigger_recv(gnrc_netif_t *netif, const uint8_t *data,
     }
     assert(dev->event_callback);
     dev->event_callback(dev, NETDEV_EVENT_ISR);
+    xtimer_usleep(500000);
 }
 
 static int _netdev_recv(netdev_t *dev, char *buf, int len, void *info)
```

I imagine that a proper "wait callback has been processed" or something may be required. Or if not possible, just add some delay with a comment there.

**Comment by cladmi** [comment]
@kYc0o Can you rebase ? I think you can also either split this PR and keep this one for tracking the broken tests (I think it's only gnrc_netif now ?) or keep the working tests and move the other ones to a dedicated issues/prs.

**Comment by kYc0o** [comment]
Discussed offline with @cladmi we'll solve gnrc_netif problems separately, for now all tests pass so we can move forward.

**Comment by miri64** [comment]
@cladmi I think the delay is fine. Thanks for analyzing!

**Comment by miri64** [comment]
If we want to generalize that test framework however, the synchronization solution might be better.

**Comment by cladmi** [comment]
`gnrc_netif` is now enabled \0/ Thanks @miri64 for debugging the issue.

**Pull request merged**
