### PR TITLE
native: create tap interfaces ad-hoc

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
PR currently only works in Linux, I will add support for other systems once the concept is ACK'd.

Usage: ignore `tapsetup.sh`, just use `make term` and get as many tap interfaces as you need.

TODO:
- [x] don't create unless term target is given
- [ ] integrate support for OSX/FreeBSD
- [ ] update documentation

### CODE REVIEW

**Comment by authmillenon** [comment]
Ping?

**Comment by LudwigOrtmann** [comment]
Shall we make it Linux-only?

**Comment by authmillenon** [comment]
If this speeds up things, yes :-)

**Comment by authmillenon** [comment]
(but maybe keep `ng_tapnet` also in mind [needs to activate IPv6])

**Comment by OlegHahm** [comment]
@LudwigOrtmann, are you still planning to finish this?

**Comment by LudwigOrtmann** [comment]
if time

**Comment by authmillenon** [comment]
I can adapt this PR, but as with #3182: I only can test this for Linux (and with some additional research, maybe FreeBSD) so I would need some support for that.

**Comment by authmillenon** [comment]
Ping?

**Comment by LudwigKnuepfer** [comment]
pong

**Comment by LudwigKnuepfer** [comment]
Please adopt.

**Comment by authmillenon** [comment]
Will do, when I find some time to look into this.

**Comment by OlegHahm** [comment]
@authmillenon, adopt or move to the next release?

**Comment by authmillenon** [comment]
Next release.

**Comment by LudwigKnuepfer** [comment]
@OlegHahm @authmillenon I'm closing this as I am not going to work on it any time soon. Please reopen in one of your names if there's still interest.

**Pull request closed without merging**
