### PR TITLE
make.dep: fix sock_udp deps for stnp

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
IMHO, the dependecies for `sntp` and `gcoap` are a little off currently: both directly depend on `gnrc_sock_udp`, but both are not tied to `GNRC` (anymore). So the correct dependency should be to `sock_udp`, right?

This PR changes this dependency slightly by doing two things:
- if GNRC is used, include `gnrc_sock_udp` in the case `sock_udp` is selected (-> sub dependency in the `gnrc` block in `Makefile.dep`)
- make `sntp` and `gcoap` simply depend on `sock_udp` instead of `gnrc_sock_udp`

Context is once more, that I played around with using `gcoap` on top of a non-GNRC network stack... So does this work for everyone or can you think of a better solution?

### Testing procedure
Build `sntp` and `gcoap` examples. The output of `make info-modules` should be unchanged.

### Issues/PRs references
none

### CODE REVIEW

**Comment by miri64** [comment]
Well at the moment `gcoap` is hardly dependent on `gnrc_sock_udp` (see #8130)

>     * if GNRC is used, include `gnrc_sock_udp` in the case `sock_udp` is selected (-> sub dependency in the `gnrc` block in `Makefile.dep`)

Why single out GNRC?

**Comment by haukepetersen** [comment]
> Well at the moment gcoap is hardly dependent on gnrc_sock_udp

Yep, I noticed that by now :-). On first sight it looked like it compiled fine in my environment, but there were some copmile issues that were augmented by local stupidity...

Still, I think for `sntp` this PR should hold?!

**Comment by miri64** [comment]
> Still, I think for `sntp` this PR should hold?!

Yapp

**Comment by kb2ma** [comment]
And with @miri64's [infrastructure work](https://github.com/RIOT-OS/RIOT/issues/8130#issuecomment-562863029), hopefully gcoap can also be liberated soon. ;-)

**Comment by kb2ma** [comment]
If only there were more RIOT hours in a day...

**Comment by haukepetersen** [comment]
Simply removed the commit effecting `gcoap`. So the changes should be valid now, right?

**Comment by haukepetersen** [comment]
some builds for the `esp32` failed, could someone with some knowledge about this platform take a look?

**Comment by miri64** [comment]
> some builds for the `esp32` failed, could someone with some knowledge about this platform take a look?

See #12964.

**Comment by benpicco** [comment]
I guess this can be merged now?

**Comment by miri64** [comment]
Yepp

**Pull request merged**
