### PR TITLE
boards: add ESP32-S3-Box support

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides the support for the [ESP32-S3-Box](https://github.com/espressif/esp-box).

### Testing procedure

The board has been tested with all basic tests for supported hardware including `tests/drivers/ili9341`:

IMG_20230707_113423

- [x] tests/drivers/ili9341
- [x] tests/periph/gpio
- [x] tests/periph/i2c
- [x] tests/periph/spi
- [x] tests/periph/uart
- [x] tests/sys/usbus_cdc_ecm

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
Please squash

**Comment by benpicco** [comment]
KConfig is still unhappy :confused:

**Comment by benpicco** [comment]
Please squash

**Comment by gschorcht** [comment]
Thanks

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
> Build failed:
> 
> * [Murdock](https://ci.riot-os.org/details/24b91ba24a5a4d9ba86c0846da0bea7c)

Build error seems to be unrelated.

bors merge

**Pull request merged**
