### PR TITLE
net_help: remove net_help module

### PR DESCRIPTION
**Pull request by authmillenon**
Its functionality is now divided up into several helper modules that are already used through-out RIOT.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by OlegHahm** [comment]
Makefile.dep needs a cleanup, too.

**Comment by authmillenon** [comment]
Done.

**Comment by OlegHahm** [comment]
please squash

**Comment by authmillenon** [comment]
Done

**Comment by OlegHahm** [comment]
ACK

**Pull request merged**
