### PR TITLE
travis: remove unnecessary nproc output

### PR DESCRIPTION
**Pull request by authmillenon**
I don't see any use for this information cramped up in the output.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
I think this once served to set `NPROC_MAX=`, not sure why it's not used anymore or if it ever was.

**Comment by authmillenon** [comment]
No, this is set whenever `buildtest` or `info-concurrency` is a goal in `make` (https://github.com/RIOT-OS/RIOT/blob/master/Makefile.buildtests#L21).
It currently just outputs a lonely `8` (or confusing `3` on my system) to the console (whatever `NPROC` is https://github.com/RIOT-OS/RIOT/blob/master/Makefile.buildtests#L245).
When I was debugging #2506 this was very confusing because I did not know where this came from

**Comment by LudwigOrtmann** [comment]
I meant that it might have been used to set `NPROC_MAX` here: https://github.com/authmillenon/RIOT/blob/travis/remove-outputting-nproc/.travis.yml#L6

**Comment by authmillenon** [comment]
That wouldn't make much sense, at least in bash syntax. It could be that travis is doing some magic there, taking whatever integer it encounters first for `NPROC_MAX`, or something like this, but I highly doubt it.

**Comment by LudwigOrtmann** [comment]
I am not suggesting it is useful in its current form. Just saying it might be a fragment of something that was (intended to be) useful once. I was kind-of suggesting a trip into the lines history.

**Comment by authmillenon** [comment]
Than do so ^^ I'm more interested in removing legacy code :P

**Comment by LudwigOrtmann** [comment]
I have no time to do so now.

**Comment by Kijewski** [comment]
The output was only a test. I should have removed the line before committing the change that introduced the NPROC_MAX variable.

**Comment by LudwigOrtmann** [comment]
@Kijewski Thank you =)

**Comment by authmillenon** [comment]
@Kijewski thanks for the clarification :-)

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by PeterKietzmann** [comment]
So is this ready to merge?

**Comment by authmillenon** [comment]
If you give it an ACK.

**Comment by LudwigOrtmann** [comment]
ack

**Pull request merged**
