### PR TITLE
periph/timer: Fix return codes of timer API

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

This PR changes the documentation of the periph/timer API to reflect most implementations, i.e., changing the return codes for `timer_set`, `timer_set_absolute`, and `timer_clear` to always use `0` on success instead of `1`. Rational is as follows: 
- most (if not all) C API commonly use `0` for success
- its confusing that `timer_init` returns `0` on success and `-1` on error, but other functions (see above) return `1` for success while still returning `-1` on error. So no bool logic could be used either. 
- most of our implementation already do this (bc. the original contributed assumed said default, or/and just didn't read the documentation)
- the impact of this change is minimal (or even none) for code in RIOT main tree, as return codes are hardly (or never) used - at least for the functions changed here.

### Testing procedure

run `tests/periph_timer` or any other timer test on your favourite board and verify it still works.

I will add a link to our HIL test results in the comments below, after this PR is open.

### Issues/PRs references

#4371

### CODE REVIEW

**Comment by kaspar030** [comment]
I'm not sure I agree on this.

1. for functions returning true/falls (e.h., timer_has_expired()), it should be clear that 1 is success and 0 is non-successs, so we can write ```if (timer_has_expired())...```

2. for all the others, IMO returning "0" for success and "<0" on error feels most fitting. If no specific (POSIXy -EFOOBAR) can be found, default choice would be "-1". Posix usually sets "-1" on error + more specific error in "errno".

Quick grepping shows >350 cases on "-1 on error" or "<0 on error".
The only two case where I could find "1 on error" is in the openthread package.

**Comment by smlng** [comment]
@kaspar030 as I wrote the timer API is inconsistent as it uses `0` for success for `timer_init` but `1` for all other functions. But also it *always* uses `-1` for error, hence true/false (bool logic) doesn't work either -> would always be true for `timer_set` in the current state (master). 

So to me the fix is either as proposed in this PR, or change return code for `timer_set` to `0` on error. But then it is confusing compared to `timer_init`. 

Also the (not so) funny fact is that in master most implementation already follow the logic for return codes as proposed in this PR. I guess bc the implementer didn't read the API doc and copied from `timer_init` or was used to have `0` on success from other C projects and hence assumed RIOT follows that.

**Comment by kaspar030** [comment]
@smlng I'm sorry, I misunderstood your intention at first and argued the wrong direction. I totally agree with returning 0 on success, -1 (or anything negative) on error, as unified in this PR.

**Comment by smlng** [comment]
test results from our HIL can be found here, I ran an early version of a periph/timer test against this PR: https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/pr_timer_basic/9/pipeline

As you can see, apart from the remote-revb (which ran into a timeout) all other boards (and hence MCUs) successfully ran to the tests, which basically tests expected return values for timer_init, timer_set, timer_read and timer_clear.

If you go back (upper left corner) to run 8 of that branch which was against master, you'll see that most boards fail these tests.

**Comment by smlng** [comment]
ping all, this inconsistency is a bit annoying and we should get rid of it.

**Comment by miri64** [comment]
ping @RIOT-OS/maintainers ;-)

**Comment by smlng** [comment]
I won't mind to get a 2nd ACK on this before merge 😉

**Comment by smlng** [comment]
thx all!

**Pull request merged**
