### PR TITLE
pkg/micro-ecc: Update FEATURE_PERIPH_HWRNG -> MODULE_PERIPH_HWRNG 

### PR DESCRIPTION
**Pull request by gebart**
The test application was successfully run on Mulle.

### CODE REVIEW

**Comment by gebart** [comment]
will reword

**Comment by gebart** [comment]
done

**Comment by PeterKietzmann** [comment]
Build still fails for mips boards. Might be related to [this comment](https://github.com/RIOT-OS/RIOT/pull/8248#discussion_r156667649). Let's see what @neiljay says. I don't even know if there platforms provide a hwrng.

**Comment by cladmi** [comment]
Do you know when the `FEATURE_PERIPH_` have been deprecated or if there is an issue on this ?
It would be nice to have the reference in the commit message.

I think this was also the last lines using `ifdef FEATURE_`, so I think this can also be removed:

https://github.com/RIOT-OS/RIOT/blob/d69291c3a1eb3f8a3a4762bf17ab9b213fa98372/makefiles/modules.inc.mk#L1

I will look into the MIPS PR.

**Comment by cladmi** [comment]
Waiting for PR: https://github.com/RIOT-OS/RIOT/pull/8248

**Comment by smlng** [comment]
murdock isn't happy, some undef reference, can you fix for the release 2018.01? Otherwise we need to postpone.

**Comment by neiljay** [comment]
>Waiting for PR: #8248

I'm waiting for @cladmi to ACK this one, then I'll create another which fixes this issue.

**Comment by cladmi** [comment]
> I'm waiting for @cladmi to ACK this one, then I'll create another which fixes this issue.
Done, need second ACK now.

**Comment by neiljay** [comment]
@sming #8242 is not the fix (it did have the fix in for a while, but we decided to separate it into another PR), another PR is coming with the fix, hopefully today.

**Comment by neiljay** [comment]
@smlng  I have pushed what should be the fix as #8360

**Comment by cladmi** [comment]
The mentioned fix makes murdock build correctly.

**Comment by smlng** [comment]
@cladmi thanks for testing and reporting, then lets see that #8360 gets merged 😄

**Comment by cladmi** [comment]
#8292 can now be merged as FEATURE_PERIPH_ are unused anymore.

**Pull request merged**
