### PR TITLE
dtls: Temporary fix example for #6022

### PR DESCRIPTION
**Pull request by miri64**
Seems like DTLS is also affected by #6022 (signal @rfuentess)

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Well, I have no problems building examples/dtls-echo for nrf52dk with**out** this PR. Did you expect that?

**Comment by miri64** [comment]
It is weird, sometimes it works, sometimes not see [Murdocks build of #5598](https://ci.riot-labs.de/RIOT-OS/RIOT/5598/88a3eeb574ee59569303af9f8b508cf934a9a1c2/output.html#cortex_m4_3) and [#5419](https://ci.riot-labs.de/RIOT-OS/RIOT/5419/6067dfb65282416b67612356697ba2d72530735c/output.html#cortex_m4_3) e.g.

**Comment by PeterKietzmann** [comment]
Hmm, I don't know what to do here. Compiled tests/dtls-echo with `make nrf52dk` as well as `make buildtest`. Everything has passed. My compiler is: gcc version 5.2.1

@kaspar030???

**Comment by miri64** [comment]
Same goes for the `nanocoap` stuff ;-)

**Comment by rfuentess** [comment]
@miri64  then DTLS and nanocoap are giving similar issues (Random compilation success for murdok) to those in https://github.com/RIOT-OS/RIOT/pull/6009 ?

**Comment by miri64** [comment]
No, I did just saw this with DTLS so far. The nanocoap issue (#6022) was  a different one that's already fixed (see #6032).

**Pull request merged**
