### PR TITLE
 gnrc_netif_hdr: add setter for netif (minimal approach)

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This splits out the core API to `gnrc_netif_hdr` out of https://github.com/RIOT-OS/RIOT/pull/10661 to simplify the review and testing. I additionally added the adaptations to `gnrc_netif_ethernet` itself, so the test application can use this function and adapted the test script so that it checks `if_pid` in the dumped packets is not set to 0 (which would be a bug). In providing this tests I also found a bug in the original commit from #10661 which I also fixed.

### Testing procedure
```
BOARD="<your fav>" make -C tests/gnrc_netif flash test
```

should still work

### Issues/PRs references
Split out of #10661

### CODE REVIEW

**Comment by miri64** [comment]
Oops forgot to push the fixed version ^^. Force pushed it.

**Comment by miri64** [comment]
And squashed :-)

**Comment by miri64** [comment]
Cherry-picked 73163c5c0eaef00269cff3bf63d38d16aa339570 from #10661 which belongs to this change.

**Comment by miri64** [comment]
And fixed the doc.

**Comment by MrKevinWeiss** [comment]
I guess I can do some testing!

**Comment by miri64** [comment]
I think the 4 extra bytes are the check for `netif != NULL`.

**Comment by MrKevinWeiss** [comment]
@maribu did anything change your mind since the last fixup.  If not then I would be OK with a squash...

**Comment by MrKevinWeiss** [comment]
8 bytes but ya.  I think it is fine.  Weird that it is so much on native...

**Comment by miri64** [comment]
> 8 bytes but ya. I think it is fine. Weird that it is so much on native...

Native does not have size optimization per default. And with native the size is not important anyway.

**Comment by maribu** [comment]
> @maribu did anything change your mind since the last fixup.  If not then I would be OK with a squash.

No, please squash!

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
Thank you for the review. Finally this makes some progress :-).

**Pull request merged**
