### PR TITLE
cpu/esp32: add clear bus during init to the I2C software implementation

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR adds a clear bus mechanism to the I2C software implementation, which is executed during initialization.

On the ESP32 it it often not possible with the I2C software implementation to communicate with an AIP31068 based LCD module.  Therefore, the I2C hardware implementation is enabled when the AIP31068 driver is used. The timing of the two implementations seems to be almost identical. The only difference is that the hardware implementation clears the bus before each access by sending 10 clock pulses on the SCL line while the SDA is held LOW. Using the same mechanism during the I2C initialization for the software implementation solves the communication problem with the AIP31068.

Because the I2C hardware implementation is more buggy than stable and the AIP31068 driver is the only module that used the I2C hardware implementation, this special dependency is removed with this fix.

### Testing procedure
```
make BOARD=esp32-wroom-32 -C tests/driver_aip31068/ flash term
```
should work stable.

### Issues/PRs references

The problem popped up when migrating makefile dependencies to Kconfig in PR #17232.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Maybe you should add that for both esp32 and esp8266 (unless the lack of OD would prevent the condition).

[The toggling makes sense](https://www.i2c-bus.org/i2c-primer/analysing-obscure-problems/blocked-bus/) though it states only 8 clock cycles would be needed not 10.

**Comment by gschorcht** [comment]
> Maybe you should add that for both esp32 and esp8266 (unless the lack of OD would prevent the condition).

For ESP8266 would be a bit more difficult since the `GPIO_OD_PU` are just emulated for timing reasons by switching them between modes `GPIO_OD` when a 0 is written and the bus line is driven LOW and `GPIO_IN_PU` when a 1 is written and the bus line is released and pulled up to high. That is, for ESP8266 it would require this toggling for each clock pulse.

I can add it, if it makes sense.

> [The toggling makes sense](https://www.i2c-bus.org/i2c-primer/analysing-obscure-problems/blocked-bus/) though it states only 8 clock cycles would be needed not 10.

The 10 clock cycles come from the hardware implementation as used by the Espressif ESP-IDF.

**Comment by HendrikVE** [comment]
I can confirm that the demo command from `tests/driver_aip31068`, which tests all features, works like a charm now with the changes.

**Comment by MrKevinWeiss** [comment]
> I can add it, if it makes sense.

We can save that for a different PR if needed.  I like to keep things short and simple.

**Review by MrKevinWeiss — APPROVED** [review]
ACK

**Pull request merged**
