### PR TITLE
sntp: extend API for common real time types 

### PR DESCRIPTION
**Pull request by miri64**
Provides `sntp`'s API with means to get the current time in some common types. Namely

* ~~`struct tm` and~~ (can be calculated from UNIX timestamps using libc's `gmtime`).
* UNIX timestamps (in microseconds)

Also fixes some errors that were not catched, since the module is not build by CI currently. A provided test application in this PR solves this problem.

### CODE REVIEW

**Comment by miri64** [comment]
Ping?

**Comment by miri64** [comment]
`gmtime()` isn't implemented in avr-libc, so I blacklisted them for now.

**Comment by haukepetersen** [comment]
ACK, please squash

**Comment by miri64** [comment]
Can you please approve it too?

**Comment by miri64** [comment]
Squashed

**Comment by haukepetersen** [comment]
squash again :-)

**Comment by miri64** [comment]
Squashed

**Pull request merged**
