### PR TITLE
rpl: edit debug message for instance == NULL

### PR DESCRIPTION
**Pull request by cgundogan**
Alternative to #2667

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
It's not an alternative to but an improvement of if I'm not mistaken.

**Comment by gebart** [comment]
This doesn't work, but my #2667 doesn't really say anything informative either... `inst` is always `NULL` if we end up there...

**Comment by cgundogan** [comment]
Ha! you are right. Should we remove this DEBUG message instead?

**Comment by cgundogan** [comment]
@gebart I updated the debug message. What is your opinion on this?

**Comment by gebart** [comment]
ACK

**Pull request merged**
