### PR TITLE
board/rf231usb: initial support for rf231usb

### PR DESCRIPTION
**Pull request by sgso**
This adds support for the Atmel reference design RF231USB-RD. It was
tested against the dresden elektronik "Funk-Stick deRFusb" and should
work with all their 23E0x variants.

The design combines a ATSAM3S4B cpu with a AT86RF231 2.4Ghz radio
transceiver on a USB stick. It is optionally equipped with 2GB flash
memory.

All devices can be flashed with SAM-BA through USB or with openocd
through JTAG (if pin header present).

The radio transceiver is working. For timer issues see dependency #3180.

For now I work through JTAG and the serial console (UART0) on the JTAG pin header.
I had a working USB CDC serial console earlier but it comes with a lot of Atmel ASF code
and I do not know if I should include it or offer it as a package? What do you think? That is 
one of the reasons why include/conf_clock.h exists. It defines the clock sources with the names
that the USB code in ASF requires.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
Great work, please rebase and adopt to #3591, #3614 and #3645. (in short remove/replace all `NG_` prefixes)

**Comment by OlegHahm** [comment]
Any progress?

**Comment by sgso** [comment]
@OlegHahm I would like to pick it up after I'm done with the XMC and make the USB work then. I don't care if I have to reopen but this already has labels and participants ;)

**Comment by OlegHahm** [comment]
Ok, then let's postpone it after the release.

**Comment by zhuoshuguo** [comment]
@sgso Ping. A kind reminder for rebase.

**Comment by sgso** [comment]
@zhuoshuguo Do you have a use for it? This is "blocked" by #3833. Not technically, but I'm not going to work on this before that one is merged.

**Comment by zhuoshuguo** [comment]
@sgso Actually, this ping is just a notice for the preparation of the the Hack'n'ACK next Tuesday. :-)  I don't have a use of it.

**Pull request closed without merging**
