### PR TITLE
examples/openthread: document libtool dependency

### PR DESCRIPTION
**Pull request by Lotterleben**
### Contribution description
I didn't have `libtool` installed and got the following error while trying to compile `examples/openthread`:

```
cd /Users/lonk/code/riot/examples/openthread/bin/pkg/samr21-xpro/openthread && PREFIX="/" ./bootstrap
/Users/lonk/code/riot/examples/openthread/bin/pkg/samr21-xpro/openthread/third_party/nlbuild-autotools/repo/scripts/bootstrap: line 280: --automake: command not found
cd /Users/lonk/code/riot/examples/openthread/bin/pkg/samr21-xpro/openthread && CPP="arm-none-eabi-gcc -E" CC="arm-none-eabi-gcc" CXX="arm-none-eabi-g++"\
		OBJC="" OBJCXX="" AR="arm-none-eabi-ar" RANLIB="arm-none-eabi-ranlib" NM="arm-none-eabi-nm" \
		STRIP="" \
		CPPFLAGS="-fdata-sections -ffunction-sections -Os -Wno-implicit-fallthrough -Wno-unused-parameter -mcpu=cortex-m0plus -mlittle-endian -mthumb -mfloat-abi=soft -march=armv6s-m -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"platform_config.h\"'" \
		CFLAGS="-fdata-sections -ffunction-sections -Os -Wno-implicit-fallthrough -Wno-unused-parameter -mcpu=cortex-m0plus -mlittle-endian -mthumb -mfloat-abi=soft -march=armv6s-m " \
		CXXFLAGS="-fdata-sections -ffunction-sections -Os -Wno-implicit-fallthrough -Wno-unused-parameter -mcpu=cortex-m0plus -mlittle-endian -mthumb -mfloat-abi=soft -march=armv6s-m -fno-exceptions -fno-rtti " \
		LDFLAGS="-fdata-sections -ffunction-sections -Os -Wno-implicit-fallthrough -Wno-unused-parameter -mcpu=cortex-m0plus -mlittle-endian -mthumb -mfloat-abi=soft -march=armv6s-m -nostartfiles -specs=nano.specs \
		-specs=nosys.specs -Wl,--gc-sections -Wl,-Map=map.map " \
		./configure --disable-docs --host=arm-none-eabi --target=arm-none-eabi \
		--prefix=/ --enable-default-logging --enable-cli-app=ftd --enable-application-coap
/bin/sh: ./configure: No such file or directory
make[1]: *** [all] Error 127
make: *** [pkg-build-openthread] Error 2
```

this PR adds a note for future users.

### Testing procedure
uninstall libtools, try compiling examples/openthread, see if the error mentioned above pops up?

### Issues/PRs references
--

### CODE REVIEW

**Comment by miri64** [comment]
Shouldn't this rather be documented in the packet and not the example?

**Comment by miri64** [comment]
(this might be required for a bunch of packages BTW, libtool is quite often used for bootstrapping)

**Comment by Lotterleben** [comment]
> Shouldn't this rather be documented in the packet and not the example?

Makes sense on an organizational level, I'm just  not sure if it'll be found there?

**Comment by Lotterleben** [comment]
> (this might be required for a bunch of packages BTW, libtool is quite often used for bootstrapping)

Yup, I assumed so– I couldn't find a page listing all necessary dependencies (there used to be one a long time ago, does it still exist?).  Would  be happy to  move this to said page if it still exists, or update additional packages if desired

**Comment by miri64** [comment]
> Yup, I assumed so– I couldn't find a page listing all necessary dependencies (there used to be one a long time ago, does it still exist?). Would be happy to move this to said page if it still exists, or update additional packages if desired

I don't know which page you are referring to, but `openthread`'s doc page is [here](https://doc.riot-os.org/group__pkg__openthread.html). The source for it is [here](https://github.com/RIOT-OS/RIOT/blob/master/pkg/openthread/doc.txt).



> > Shouldn't this rather be documented in the packet and not the example?
> 
> Makes sense on an organizational level, I'm just not sure if it'll be found there?

The alternative would be to document everything everywhere, which just does not scale. We could link the package documentation in the README though (there are already a lot of references to OpenThread's own doc in there).

**Comment by Lotterleben** [comment]
> > Yup, I assumed so– I couldn't find a page listing all necessary dependencies (there used to be one a long time ago, does it still exist?). Would be happy to move this to said page if it still exists, or update additional packages if desired
> 
> I don't know which page you are referring to, but `openthread`'s doc page is [here](https://doc.riot-os.org/group__pkg__openthread.html). The source for it is [here](https://github.com/RIOT-OS/RIOT/blob/master/pkg/openthread/doc.txt).

Nope, I meant a RIOT-specific page, but that was... >5 years ago, so.

> 
> > > Shouldn't this rather be documented in the packet and not the example?
> > 
> > 
> > Makes sense on an organizational level, I'm just not sure if it'll be found there?
> 
> The alternative would be to document everything everywhere, which just does not scale. We could link the package documentation in the README though (there are already a lot of references to OpenThread's own doc in there).

How about we list the dependency in the openthread doc page and then link sau doc page in the READMEs of examples/openthread and pkg/openthread?

**Comment by miri64** [comment]
> Nope, I meant a RIOT-specific page, but that was... >5 years ago, so.

Not sure there was such a page, but there is a documentation on the required toolchains in the Wiki still (namespaced by `Family:`)

> How about we list the dependency in the openthread doc page and then link said doc page in the READMEs of examples/openthread and pkg/openthread?

:+1:

**Pull request closed without merging**
