### PR TITLE
makefiles: socat set tty mode 8N1 

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

For some reason `z1` does not work with socat, all tests forcing socat ar bound to fail on `z1`.

### Testing procedure

A run of tests in master: https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/lastSuccessfulBuild/artifact/ all fail without event starting the terminal, a run of tests with this commi https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/327/artifact/z1/tests/, `congure` still is failing a couple of tests as well as `pkdf2` but not for the same reasons.

### Issues/PRs references

First time this issue was reported https://github.com/RIOT-OS/RIOT/pull/14658

### CODE REVIEW

**Comment by kfessel** [comment]
> For some reason `z1` does not work with socat, all tests forcing socat ar bound to fail on `z1`.

the "for some reason" probably is the programmer of that z1 (all msp430?);
It sets the uart to use even parity, socat lets this thing untouched (since that is no configured)

https://github.com/RIOT-OS/RIOT/blob/844279fa6b3c5b01e3bd0ac281ae21aa97fff035/dist/tools/goodfet/goodfet.bsl#L308

so a better solution would be to reset the tty (either in the programmer tool or using `stty -F /dev/tty-z1 -parenb raw`)

**Comment by fjmolinas** [comment]
> It sets the uart to use even parity, socat lets this thing untouched (since that is no configured)

True that seems to be it,  thansk for not letting me get away with the lazy solution:

```
socat - open:/dev/riot/tty-z1,b115200,echo=0,raw,parenb=0

>
> bufsize
bufsize
128
> test case "check_line_exceeded" blacklisted, SKIP
garbage1234
garbage1234
>
>
shell exited
>
>
start_test
>
> start_test
[TEST_START]
>


>
> echo a string
echo a string
"echo""a""string"
> echo   multiple   spaces   between   argv
echo   multiple   spaces   between   argv
"echo""multiple""spaces""between""argv"
> echo   tabs            processed              like                    spaces
echo     tabs            processed              like                    spaces
"echo""tabs""processed""like""spaces"
> unknown_command
unknown_command
shell: command not found: unknown_command
>      echo leading spaces
     echo leading spaces
"echo""leading""spaces"
>                                       echo leading tabs
                                        echo leading tabs
"echo""leading""tabs"
> echo trailing spaces
echo trailing spaces
"echo""trailing""spaces"
> echo trailing tabs
echo trailing tabs
"echo""trailing""tabs"
> hello-world
hello-world
shell: command not found: hello-world
echo
echo
"echo"
> echo \'
echo \'
"echo""'"
> echo \"
echo \"
"echo""""
> echo escaped\ space
echo escaped\ space
"echo""escaped space"
> echo escape within '\s\i\n\g\l\e\q\u\o\t\e'
echo escape within '\s\i\n\g\l\e\q\u\o\t\e'
"echo""escape""within""singlequote"
> echo escape within "\d\o\u\b\l\e\q\u\o\t\e"
echo escape within "\d\o\u\b\l\e\q\u\o\t\e"
"echo""escape""within""doublequote"
> echo "t\e st" "\"" '\'' a\ b
echo "t\e st" "\"" '\'' a\ b
"echo""te st"""""'""a b"
> echo "hello"world
echo "hello"world
"echo""helloworld"
> echo hel"lowo"rld
echo hel"lowo"rld
"echo""helloworld"
> echo hello"world"
echo hello"world"
"echo""helloworld"
> echo quoted space " "
echo quoted space " "
"echo""quoted""space"" "
> echo abc"def'ghijk"lmn
echo abc"def'ghijk"lmn
"echo""abcdef'ghijklmn"
> echo abc'def"ghijk'lmn
echo abc'def"ghijk'lmn
"echo""abcdef"ghijklmn"
> echo "'" '"'
echo "'" '"'
"echo""'""""
> echo a\
echo a\
shell: incorrect quoting
> echo "
echo "
shell: incorrect quoting
> echo '
echo '
shell: incorrect quoting
> echo abcdef"ghijklmn
echo abcdef"ghijklmn
shell: incorrect quoting
> echo abcdef'ghijklmn
echo abcdef'ghijklmn
shell: incorrect quoting
> ps
ps
        pid | state    Q | pri
          1 | pending  Q |  15
          2 | running  Q |   7
> help
help
Command              Description
---------------------------------------
bufsize              Get the shell's buffer size
start_test           starts a test
end_test             ends a test
echo                 prints the input command
empty                print nothing on command
reboot               Reboot the node
version              Prints current RIOT_VERSION
pm                   interact with layered PM subsystem
ps                   Prints information about running threads.
app_metadata         Returns application metadata
xfa_test1            xfa test command 1
xfa_test2            xfa test command 2
> xfa_test1
xfa_test1
[XFA TEST 1 OK]
> xfa_test2
xfa_test2
[XFA TEST 2 OK]
> reboot
�main(): This is RIOT! (Version: 2022.04-devel-915-g9df84-pr_z1_socat)
test_shell.
> end_test
end_test
[TEST_END]
>

>
>

```

**Comment by kfessel** [comment]
> thansk for not letting me get away with the lazy solution

:+1: 

you are welcome

still think (even though this configuration can be added to socat) the flashing reset the state of the stty to something a user expects (they might want to use another terminal application)

**Review by kfessel — APPROVED** [review]
change is good,
there was a successful murdock run,
positive test results are provided

**Comment by kfessel** [comment]
pr-check does not like 'Update' please squash

**Comment by kfessel** [comment]
if you like you can also add that goodfet patch:
[0001-tools-goodfet-set-serial-port-parity-to-none-prior-c.txt](https://github.com/RIOT-OS/RIOT/files/8353115/0001-tools-goodfet-set-serial-port-parity-to-none-prior-c.txt)

**Comment by fjmolinas** [comment]
I re-ran the test because the patch was wrong, and I had failed to test that, but its all green now and socat was tested by murdock

**Comment by fjmolinas** [comment]
> I re-ran the test because the patch was wrong, and I had failed to test that, but its all green now and socat was tested by murdock

(needs a re-ACK @kfessel :))

**Review by kfessel — APPROVED** [review]
re

**Comment by fjmolinas** [comment]
Note Murdock also verified this was working:

https://ci.riot-os.org/RIOT-OS/RIOT/17853/88942be06ceadf72a8e098e021559baf3653881e/output/run_test/tests/shell/esp32-wroom-32:gnu.txt

**Comment by fjmolinas** [comment]
Thanks @kfessel!

**Pull request merged**
