### PR TITLE
drivers: migrate mpu9x50 and si70xx to ztimer

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

As the title says.

### Testing procedure

- Green CI
- `tests/driver_mpu9x50` and `tests/driver_si70xx` are still working. I might be able to test them tomorrow.

### Test outputs

<details><summary>mpu9x50</summary>

```
Building application "tests_driver_mpu9x50" for "esp8266-esp-12x" with MCU "esp8266".

"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/pkg/esp8266_sdk
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/boards/esp8266-esp-12x
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/boards/common/esp8266
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/core
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/freertos
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/periph
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/sdk
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/esp8266/source
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/nvs_flash/src
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/spi_flash
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/util/src
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/wpa_supplicant
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/wpa_supplicant/src/crypto
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/freertos
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/periph
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/vendor
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/vendor/xtensa
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/mpu9x50
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/mtd
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/periph_common
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/auto_init
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/frac
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/log
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/luid
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/newlib_syscalls_default
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/ps
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/random
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/stdio_uart
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/ztimer
esptool.py v2.4.0
Parsing CSV input...
   text	   data	    bss	    dec	    hex	filename
 284420	   5324	  28752	 318496	  4dc20	/home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_mpu9x50/bin/esp8266-esp-12x/tests_driver_mpu9x50.elf
/home/gs/src/RIOT-Xtensa-ESP.working/dist/tools/esptool/esptool.py --chip esp8266 --port /dev/ttyUSB0 --baud 460800 --before default_reset write_flash -z --flash_mode dout   --flash_freq 26m    0x0000 /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/bin/bootloader.bin 0x8000 /home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_mpu9x50/bin/esp8266-esp-12x/partitions.bin 0x10000 /home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_mpu9x50/bin/esp8266-esp-12x/tests_driver_mpu9x50.elf.bin
esptool.py v2.4.0
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: 18:fe:34:f3:b6:b1
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0341
Compressed 9344 bytes to 6292...
Wrote 9344 bytes (6292 compressed) at 0x00000000 in 0.1 seconds (effective 522.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 85...
Wrote 3072 bytes (85 compressed) at 0x00008000 in 0.0 seconds (effective 4833.5 kbit/s)...
Hash of data verified.
Compressed 289824 bytes to 198433...
Wrote 289824 bytes (198433 compressed) at 0x00010000 in 4.5 seconds (effective 520.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
/home/gs/src/RIOT-Xtensa-ESP.working/dist/tools/pyterm/pyterm -p "/dev/ttyUSB0" -b "115200" --set-rts 0 --set-dtr 0 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2021-12-09 09:07:07,870 # Connect to serial port /dev/ttyUSB0
Welcome to pyterm!
Type '/exit' to exit.
2021-12-09 09:07:10,874 # main(): This is RIOT! (Version: 2022.01-devel-1067-g6fea0-pr/17358)
2021-12-09 09:07:10,875 # MPU-9X50 test application
2021-12-09 09:07:10,877 # 
2021-12-09 09:07:10,880 # +------------Initializing------------+
2021-12-09 09:07:11,032 # Initialization successful
2021-12-09 09:07:11,033 # 
2021-12-09 09:07:11,038 # +------------Configuration------------+
2021-12-09 09:07:11,038 # Sample rate: 200 Hz
2021-12-09 09:07:11,041 # Compass sample rate: 100 Hz
2021-12-09 09:07:11,044 # Gyro full-scale range: 2000 DPS
2021-12-09 09:07:11,046 # Accel full-scale range: 2 G
2021-12-09 09:07:11,049 # Compass X axis factory adjustment: 180
2021-12-09 09:07:11,052 # Compass Y axis factory adjustment: 180
2021-12-09 09:07:11,057 # Compass Z axis factory adjustment: 170
2021-12-09 09:07:11,057 # 
2021-12-09 09:07:11,060 # +--------Starting Measurements--------+
2021-12-09 09:07:11,063 # Accel data [milli g] - X: -20   Y: -180   Z: 985
2021-12-09 09:07:11,069 # Gyro data [dps] - X: 0   Y: 0   Z: 0
2021-12-09 09:07:11,071 # Compass data [micro T] - X: 0   Y: 0   Z: 0
2021-12-09 09:07:11,074 # Temperature [milli deg] : 43832
2021-12-09 09:07:11,074 # 
2021-12-09 09:07:11,078 # +-------------------------------------+
2021-12-09 09:07:12,071 # Accel data [milli g] - X: 216   Y: 335   Z: 1128
2021-12-09 09:07:12,074 # Gyro data [dps] - X: -12   Y: -7   Z: 72
2021-12-09 09:07:12,079 # Compass data [micro T] - X: 0   Y: 7   Z: 18
2021-12-09 09:07:12,082 # Temperature [milli deg] : 43920
2021-12-09 09:07:12,082 # 
2021-12-09 09:07:12,085 # +-------------------------------------+
2021-12-09 09:07:13,079 # Accel data [milli g] - X: 18   Y: 18   Z: 1028
2021-12-09 09:07:13,081 # Gyro data [dps] - X: -3   Y: 1   Z: 0
2021-12-09 09:07:13,087 # Compass data [micro T] - X: 0   Y: 9   Z: 20
2021-12-09 09:07:13,089 # Temperature [milli deg] : 43961
2021-12-09 09:07:13,090 # 
2021-12-09 09:07:13,092 # +-------------------------------------+
2021-12-09 09:07:13,858 # Exiting Pyterm
```

</details>

<details><summary>si70xx</summary>

```
Building application "tests_driver_si70xx" for "esp8266-esp-12x" with MCU "esp8266".

"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/pkg/esp8266_sdk
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/boards/esp8266-esp-12x
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/boards/common/esp8266
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/core
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/freertos
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/periph
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/sdk
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/esp8266/source
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/nvs_flash/src
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/spi_flash
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/util/src
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/wpa_supplicant
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/vendor/esp-idf/wpa_supplicant/src/crypto
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/freertos
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/periph
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/vendor
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp_common/vendor/xtensa
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/mtd
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/periph_common
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/drivers/si70xx
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/auto_init
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/frac
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/log
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/luid
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/newlib_syscalls_default
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/ps
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/random
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/stdio_uart
"make" -C /home/gs/src/RIOT-Xtensa-ESP.working/sys/ztimer
esptool.py v2.4.0
Parsing CSV input...
   text	   data	    bss	    dec	    hex	filename
 281588	   5324	  28752	 315664	  4d110	/home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_si70xx/bin/esp8266-esp-12x/tests_driver_si70xx.elf
/home/gs/src/RIOT-Xtensa-ESP.working/dist/tools/esptool/esptool.py --chip esp8266 --port /dev/ttyUSB0 --baud 460800 --before default_reset write_flash -z --flash_mode dout   --flash_freq 26m    0x0000 /home/gs/src/RIOT-Xtensa-ESP.working/cpu/esp8266/bin/bootloader.bin 0x8000 /home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_si70xx/bin/esp8266-esp-12x/partitions.bin 0x10000 /home/gs/src/RIOT-Xtensa-ESP.working/tests/driver_si70xx/bin/esp8266-esp-12x/tests_driver_si70xx.elf.bin
esptool.py v2.4.0
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: 18:fe:34:f3:b6:b1
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0341
Compressed 9344 bytes to 6292...
Wrote 9344 bytes (6292 compressed) at 0x00000000 in 0.1 seconds (effective 521.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 85...
Wrote 3072 bytes (85 compressed) at 0x00008000 in 0.0 seconds (effective 4764.7 kbit/s)...
Hash of data verified.
Compressed 286992 bytes to 196873...
Wrote 286992 bytes (196873 compressed) at 0x00010000 in 4.5 seconds (effective 515.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
/home/gs/src/RIOT-Xtensa-ESP.working/dist/tools/pyterm/pyterm -p "/dev/ttyUSB0" -b "115200" --set-rts 0 --set-dtr 0 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2021-12-09 09:03:09,400 # Connect to serial port /dev/ttyUSB0
Welcome to pyterm!
Type '/exit' to exit.
2021-12-09 09:03:21,290 # main(): This is RIOT! (Version: 2022.01-devel-1067-g6fea0-pr/17358)
2021-12-09 09:03:21,293 # SI70XX temperature and humidity sensor test application
2021-12-09 09:03:21,297 # Initializing sensor... 
2021-12-09 09:03:21,313 # [OK]
2021-12-09 09:03:21,316 # Found SI7021 sensor, revision 32
2021-12-09 09:03:21,330 # relative humidity: 45.37
2021-12-09 09:03:21,333 # temperature: 25.37 C
2021-12-09 09:03:22,331 # relative humidity: 44.52
2021-12-09 09:03:22,334 # temperature: 25.39 C
2021-12-09 09:03:23,347 # relative humidity: 45.39
2021-12-09 09:03:23,350 # temperature: 25.39 C
2021-12-09 09:03:24,348 # relative humidity: 44.53
2021-12-09 09:03:24,351 # temperature: 25.39 C
2021-12-09 09:03:25,364 # relative humidity: 45.38
2021-12-09 09:03:25,367 # temperature: 25.38 C
2021-12-09 09:03:26,365 # relative humidity: 44.53
2021-12-09 09:03:26,368 # temperature: 25.38 C
2021-12-09 09:03:26,439 # Exiting Pyterm
```

</details>

### Issues/PRs references

~Based on #17315~ not needed, the changes are orthogonal

### CODE REVIEW

**Comment by gschorcht** [comment]
`mpu9x50` driver still works, tested with MPU9250.

**Comment by gschorcht** [comment]
BTW, the tile was wrong, you were changing `mpu9x50` :wink:

**Comment by gschorcht** [comment]
`si79xx` driver still works, tested with SI7021.

**Comment by gschorcht** [comment]
Once PR #17315 is merged and this PR is rebased, I can give an ACK.

**Comment by aabadie** [comment]
> Once PR #17315 is merged and this PR is rebased, I can give an ACK.

I dropped the dependency to #17315, both PRs are orthogonal, no need to have one depends on the other.

**Comment by aabadie** [comment]
Thanks for testing and providing the test output, you were faster than me :)

**Review by fjmolinas — APPROVED** [review]
@gschorcht provided the testing output, changes LGTM ACK.

**Pull request merged**
