### PR TITLE
tests: add test app to flood L2 packets

### PR DESCRIPTION
**Pull request by authmillenon**
This was asked for by @kaspar030 in https://github.com/RIOT-OS/RIOT/issues/3341#issuecomment-120384998.

### CODE REVIEW

**Comment by haukepetersen** [comment]
what for do you include the `udp.c`? It's not linked to a shell command, so I guess you can remove it?

**Comment by authmillenon** [comment]
I thought I removed that -.- It's just copy pasta.

**Comment by authmillenon** [comment]
Removed

**Comment by haukepetersen** [comment]
hmm, pasta :-)

**Comment by authmillenon** [comment]
Postponed

**Pull request closed without merging**
