### PR TITLE
sys/od: increase the size of str_pos variable

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description

This PR fixes a weird bug I've encountered when playing with `tests/periph/flashpage` on nRF53.

I wrote a string in the beginning of the last flash page  and read back its content:
```
2023-07-06 11:31:02,011 # main(): This is RIOT! (Version: 2023.07-devel-760-gf0dc0-cpu/nrf53/add_flashpage_support)
2023-07-06 11:31:02,013 # ROM flash read write test
2023-07-06 11:31:02,014 # 
2023-07-06 11:31:02,018 # Please refer to the README.md for further information
2023-07-06 11:31:02,018 # 
2023-07-06 11:31:02,021 # Flash start addr:             0x00000000
2023-07-06 11:31:02,023 # Page size:                    4096
2023-07-06 11:31:02,028 # Number of pages:              256
2023-07-06 11:31:02,028 # Number of first free page:    7 
2023-07-06 11:31:02,030 # Number of last free page:     255 
read 255
2023-07-06 11:31:06,432 # read 255
2023-07-06 11:31:06,436 # Read flash page 255 into local page buffer
2023-07-06 11:31:06,438 # Local page buffer:
2023-07-06 11:31:06,446 # 00000000  48  65  6C  6C  6F  20  57  6F  72  6C  64  21  20  54  68  69  Hello World! Thi
2023-07-06 11:31:06,454 # 00000010  73  20  69  73  20  61  20  74  65  73  74  21  FF  FF  FF  FF  s is a test!....
2023-07-06 11:31:06,462 # 00000020  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,469 # 00000030  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,477 # 00000040  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,485 # 00000050  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,493 # 00000060  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,501 # 00000070  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,509 # 00000080  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,517 # 00000090  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,525 # 000000A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,533 # 000000B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,541 # 000000C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,549 # 000000D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,557 # 000000E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,564 # 000000F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,572 # 00000100  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  Hello World! Thi
2023-07-06 11:31:06,581 # 00000110  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  s is a test!....
2023-07-06 11:31:06,588 # 00000120  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,596 # 00000130  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,604 # 00000140  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,612 # 00000150  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,620 # 00000160  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,628 # 00000170  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,636 # 00000180  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,644 # 00000190  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,651 # 000001A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,659 # 000001B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,667 # 000001C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,675 # 000001D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,684 # 000001E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,691 # 000001F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,699 # 00000200  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  Hello World! Thi
2023-07-06 11:31:06,707 # 00000210  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  s is a test!....
2023-07-06 11:31:06,715 # 00000220  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,723 # 00000230  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,731 # 00000240  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,739 # 00000250  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,746 # 00000260  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,755 # 00000270  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,763 # 00000280  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,771 # 00000290  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,778 # 000002A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,786 # 000002B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,794 # 000002C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,802 # 000002D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,811 # 000002E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,819 # 000002F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,826 # 00000300  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  Hello World! Thi
2023-07-06 11:31:06,833 # 00000310  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  s is a test!....
2023-07-06 11:31:06,841 # 00000320  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,849 # 00000330  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,857 # 00000340  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,865 # 00000350  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,873 # 00000360  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,881 # 00000370  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,889 # 00000380  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,897 # 00000390  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,905 # 000003A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,914 # 000003B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,920 # 000003C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,928 # 000003D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,936 # 000003E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:31:06,944 # 000003F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
```

The ASCII representation of the flash content is wrong there. "Hello World! This is a test!" should only appears at the very beginning. Note that the hex representation is not affected.

With this PR, this now looks like this:

```
2023-07-06 11:32:31,109 # main(): This is RIOT! (Version: 2023.07-devel-760-gf0dc0-cpu/nrf53/add_flashpage_support)
2023-07-06 11:32:31,111 # ROM flash read write test
2023-07-06 11:32:31,112 # 
2023-07-06 11:32:31,117 # Please refer to the README.md for further information
2023-07-06 11:32:31,117 # 
2023-07-06 11:32:31,119 # Flash start addr:             0x00000000
2023-07-06 11:32:31,120 # Page size:                    4096
2023-07-06 11:32:31,123 # Number of pages:              256
2023-07-06 11:32:31,125 # Number of first free page:    7 
2023-07-06 11:32:31,128 # Number of last free page:     255 
> read 255
2023-07-06 11:32:39,332 # read 255
2023-07-06 11:32:39,335 # Read flash page 255 into local page buffer
2023-07-06 11:32:39,338 # Local page buffer:
2023-07-06 11:32:39,345 # 00000000  48  65  6C  6C  6F  20  57  6F  72  6C  64  21  20  54  68  69  Hello World! Thi
2023-07-06 11:32:39,353 # 00000010  73  20  69  73  20  61  20  74  65  73  74  21  FF  FF  FF  FF  s is a test!....
2023-07-06 11:32:39,361 # 00000020  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,369 # 00000030  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,376 # 00000040  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,385 # 00000050  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,393 # 00000060  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,401 # 00000070  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,408 # 00000080  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,416 # 00000090  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,424 # 000000A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,433 # 000000B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,440 # 000000C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,448 # 000000D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,455 # 000000E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,463 # 000000F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,471 # 00000100  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,479 # 00000110  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,487 # 00000120  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,495 # 00000130  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,504 # 00000140  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,511 # 00000150  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,520 # 00000160  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,528 # 00000170  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,535 # 00000180  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,543 # 00000190  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,550 # 000001A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,559 # 000001B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,567 # 000001C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,574 # 000001D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,583 # 000001E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,590 # 000001F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,599 # 00000200  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,607 # 00000210  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,615 # 00000220  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,623 # 00000230  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,629 # 00000240  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,638 # 00000250  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,646 # 00000260  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,654 # 00000270  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,662 # 00000280  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,670 # 00000290  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,678 # 000002A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,685 # 000002B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,694 # 000002C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,702 # 000002D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,709 # 000002E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,717 # 000002F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,725 # 00000300  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,733 # 00000310  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,741 # 00000320  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,749 # 00000330  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,757 # 00000340  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,765 # 00000350  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,772 # 00000360  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,781 # 00000370  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,789 # 00000380  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,796 # 00000390  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,804 # 000003A0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,811 # 000003B0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,820 # 000003C0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,827 # 000003D0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,835 # 000003E0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
2023-07-06 11:32:39,843 # 000003F0  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  FF  ................
```

Note that I shrank the content of both output because the total flashpage size is 4096 and it is not relevant since its repeating.

I went with `uint16_t`  for the `str_pos` variable because I think it is good enough to fix the issue.

### Testing procedure

Try to display the content of a buffer larger than 256 bytes with `od_hex_dump` and `OD_STRING` module enabled.
In current master, the ASCII representation loops throught the first 256 bytes of the buffer.
With this PR, the ASCII representation is in match with its content.

### Issues/PRs references
None.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by kaspar030** [comment]
> I went with `uint16_t` for the `str_pos` variable because I think it is good enough to fix the issue.

Wouldn't `size_t` be the natural choice?

**Comment by dylad** [comment]
> Wouldn't size_t be the natural choice?

I have nothing against. I'll change.

**Comment by kaspar030** [comment]
bors merge

**Comment by kaspar030** [comment]
bors merge

**Comment by dylad** [comment]
Thanks !

**Pull request merged**
