### PR TITLE
gcoap: Finish the gcoap_get_resource_list_tl -> gcoap_get_resource_list renaming

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

In #16688, an argument was added to the `gcoap_get_resource_list` function by creating a new function `gcoap_get_resource_list_tl` with a deprecation and roll-over plan.

This plan has not been acted on so far.

This PR shortens the original plan by just adding the argument to `gcoap_get_resource_list` and removing `gcoap_get_resource_list_tl` in a single go. The rationale for this deviation is that while it's a public API, its only two practical consumers are the (built-in) well-known/core implementation, and the (built-in) CoRE Resource Directory (cord) endpoint. Moreover, a further change to this API (switching over to `coap_block_slicer_t`) is expected to happen within this release cycle, which would take something like 4 total releases to get through otherwise, which is unrealistic for an API that there are no known external users of.

A second commit clean up ToDo items (in the changed function's documentation) that referred to a IETF draft that has long been abandoned by the CoRE WG.

### Testing procedure

Plain inspection and CI passing should suffice.

### AOB

There is a second analogous pair left over from #16688, `gcoap_req_send` / `gcoap_req_send_tl`. As that *is* expected to be used widely, I prefer not to mix these two concerns, and get the present one through without unnecessary hold-up.

### CODE REVIEW

**Comment by chrysn** [comment]
My apologies, this is based on the wrong branch, and thus not as trivial as it should have been. Expect a rebased version force-pushed momentarily.

**Review by benpicco — APPROVED** [review]
bors merge

**Comment by benpicco** [comment]
smpboot_control

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
