### PR TITLE
sys/shell/gnrc_netif: don't always build lora options with ifconfig

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is a follow-up of #19466 and should address https://github.com/RIOT-OS/RIOT/pull/19466#issuecomment-1508700618

### Testing procedure

Untested yet.

The testing procedure in #19466 should be the same.

### Issues/PRs references

#19466

### CODE REVIEW

**Comment by aabadie** [comment]
@jia200x can you have a look at this one ?

**Review by jia200x — APPROVED** [review]
ACK. Tested on b-l072z-lrwan1. I could select `shell_cmd_gnrc_netif` without selecting LoRa specific commands.

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
