### PR TITLE
gnrc_tcp: refactor tests

### PR DESCRIPTION
**Pull request by brummer-simon**
### Contribution description
This PR refactors the test suite of GNRC_TCP. In consolidates all test scripts in a into a single script
and adds helper classes wrapping common functions used in GNRC_TCP tests.
This PR simplifies the process of adding additional tests greatly.
All existing tests were moved into the new test script.

### Testing procedure
To test this PR follow the instructions under tests/gnrc_tcp/Readme.md

### Issues/PRs references
Depends on PR #16459

### CODE REVIEW

**Comment by benpicco** [comment]
feel free to rebase

**Comment by brummer-simon** [comment]
> 
> 
> feel free to rebase
> 
> Does this only move code around?

Mostly. It adds a few python helper classes simplifying the process of writing tests. All existing tests are merged into a single file and these tests are rewritten based on the helper classes. So the tests are moved partly rewritten with the new helper classes.

**Comment by miri64** [comment]
> It adds a few python helper classes simplifying the process of writing tests.

How would you feel about porting the tests to [`riotctrl`](https://github.com/RIOT-OS/riotctrl/) instead? That is the "new" way for implementing tests. Some of the commands implemented by `shell_commands` are provided in [`riotctrl_shell`](https://github.com/RIOT-OS/RIOT/tree/master/dist/pythonlibs/riotctrl_shell), application-specific `ShellInteraction`s usually are implemented within the applications python test part (basically where you have the helpers now).

**Comment by brummer-simon** [comment]
> 
> 
> > It adds a few python helper classes simplifying the process of writing tests.
> 
> How would you feel about porting the tests to [`riotctrl`](https://github.com/RIOT-OS/riotctrl/) instead? That is the "new" way for implementing tests. Some of the commands implemented by `shell_commands` are provided in [`riotctrl_shell`](https://github.com/RIOT-OS/RIOT/tree/master/dist/pythonlibs/riotctrl_shell), application-specific `ShellInteraction`s usually are implemented within the applications python test part (basically where you have the helpers now).

Makes sence from my point of view. Although this PR and the two PR building onto of this PR introduce new tests based on the old scheme. I would prefer the we review and merge the open followup PRs and port the tests in a single PR after the successfull sock integration. @miri64 What do you think about this approach?

**Comment by miri64** [comment]
> @miri64 What do you think about this approach?

Mh... to be honest, I am not sure if it would be less work for you to rework the tests once instead of twice ;-)

**Comment by miri64** [comment]
It's your code, so if you think rewriting twice in this case is less work, now that the first rework is basically done, I don't mind.

**Comment by brummer-simon** [comment]
> 
> 
> It's your code, so if you think rewriting twice in this case is less work, now that the first rework is basically done, I don't mind.

Lets do it this way then :)

**Comment by benpicco** [comment]
Tests are still passing on 

#### native

```
- "test_connection_lifecycle_as_client": SUCCESS
- "test_connection_lifecycle_as_server": SUCCESS
- "test_send_data_from_riot_to_host": SUCCESS
- "test_send_data_from_host_to_riot": SUCCESS
- "test_gnrc_tcp_garbage_packets_short_payload": SUCCESS
- "test_gnrc_tcp_garbage_packets_short_header": SUCCESS
- "test_gnrc_tcp_garbage_packets_ack_instead_of_sym": SUCCESS
- "test_gnrc_tcp_garbage_packets_option_parsing": SUCCESS
- "test_gnrc_tcp_recv_behavior_on_closed_connection": SUCCESS
- "test_gnrc_tcp_ep_from_str": SUCCESS
- "test_gnrc_tcp_ep_from_str_returns_EINVAL": SUCCESS
- "test_gnrc_tcp_accept_returns_EAGAIN": SUCCESS
- "test_gnrc_tcp_accept_returns_ETIMEDOUT": SUCCESS
- "test_gnrc_tcp_accept_returns_ENOMEM": SUCCESS
    Running listen/accept iteration 0
    Running listen/accept iteration 1
    Running listen/accept iteration 2
    Running listen/accept iteration 3
    Running listen/accept iteration 4
    Running listen/accept iteration 5
    Running listen/accept iteration 6
    Running listen/accept iteration 7
    Running listen/accept iteration 8
    Running listen/accept iteration 9
- "test_connection_listen_accept_cycle": SUCCESS
01-run.py: success
```

and

#### same54-xpro

```
- "test_connection_lifecycle_as_client": SUCCESS
- "test_connection_lifecycle_as_server": SUCCESS
- "test_send_data_from_riot_to_host": SUCCESS
- "test_send_data_from_host_to_riot": SUCCESS
- "test_gnrc_tcp_garbage_packets_short_payload": SUCCESS
- "test_gnrc_tcp_garbage_packets_short_header": SUCCESS
- "test_gnrc_tcp_garbage_packets_ack_instead_of_sym": SUCCESS
- "test_gnrc_tcp_garbage_packets_option_parsing": SUCCESS
- "test_gnrc_tcp_recv_behavior_on_closed_connection": SUCCESS
- "test_gnrc_tcp_ep_from_str": SUCCESS
- "test_gnrc_tcp_ep_from_str_returns_EINVAL": SUCCESS
- "test_gnrc_tcp_accept_returns_EAGAIN": SUCCESS
- "test_gnrc_tcp_accept_returns_ETIMEDOUT": SUCCESS
- "test_gnrc_tcp_accept_returns_ENOMEM": SUCCESS
    Running listen/accept iteration 0
    Running listen/accept iteration 1
    Running listen/accept iteration 2
    Running listen/accept iteration 3
    Running listen/accept iteration 4
    Running listen/accept iteration 5
    Running listen/accept iteration 6
    Running listen/accept iteration 7
    Running listen/accept iteration 8
    Running listen/accept iteration 9
- "test_connection_listen_accept_cycle": SUCCESS
01-run.py: success
```

**Pull request merged**
