### PR TITLE
ci/test-on-iotlab: fix unsupported set-env command

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is an attempt to fix the "test-on-iotlab" GH action that is currently broken. See the [output of this job](https://github.com/RIOT-OS/RIOT/actions/runs/476450467)

```
Unable to process command '::set-env name=IOTLAB_EXP_ID::242632' successfully. 

The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ 
```

The proposed fix follows [this document](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) to replace the deprecated use of `set-env` command.

### Testing procedure

Check if the action runs as expected by performing a manual trigger.

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
For some reason, the manual trigger doesn't take into account this PR (I tried with the commit hash of that PR, and other things but none worked). @miri64, do you have any idea what I'm missing ?

**Comment by miri64** [comment]
`pull/15745/merge` works (`pull/15745/head` would probably also work). The problem with using

1. the commit hash is that fetching a hash does not work in git, it only works for ref-likes.
2. the branch name is that that branch name is valid for your fork, not RIOT-OS/RIOT.
 
`pull/15745/merge` is a valid upstream ref however.

**Comment by miri64** [comment]
Oops hit comment to early. I was writing this up while the test was still running in the hopes that it will work... I am currently trying if the named refs are working.

**Comment by aabadie** [comment]
Seems that you couldn't get better result ;)

**Comment by miri64** [comment]
Yeah... I think you need to do a run in your fork for that to work, with the branch of this PR being the default branch, I am afraid.

**Comment by aabadie** [comment]
I'm testing the branch of that PR on my own fork and it works: https://github.com/aabadie/RIOT/runs/1689850441

**Review by miri64 — APPROVED** [review]
ACK! The linked run is not finished yet, but the fact that it is still running tells be, that the experiment ID was found.

**Pull request merged**
