### PR TITLE
doc: add net to sys group

### PR DESCRIPTION
**Pull request by authmillenon**
This updates the `sys/net/doc.txt` for `net` to be a sub-group of `sys`.

### CODE REVIEW

**Comment by OlegHahm** [comment]
`net` is intentional on the top layer.

**Comment by authmillenon** [comment]
Updated.

**Comment by OlegHahm** [comment]
Actually, I have no opinion on what is better.

**Comment by Kijewski** [comment]
Well, "networking" is more descriptive than "net", hence ACK.

**Comment by authmillenon** [comment]
Squashed

**Pull request merged**
