### PR TITLE
Tweetnacl third attempt

### PR DESCRIPTION
**Pull request by kYc0o**
This is a second attempt to add tweetnacl as a package.

Main, and only, modification is to download the sources at compile time, instead of adding them by default.

### CODE REVIEW

**Comment by BytesGalore** [comment]
I thought we don't want to download the files from "elsewhere" (cf. discussion #5687)?

**Comment by OlegHahm** [comment]
Oops, sorry, we had a offline discussion about this yesterday and I forgot that @BytesGalore already provided this solution half a year ago. Sorry, Martin!

**Comment by emmanuelsearch** [comment]
@OlegHahm so are you also reverting to advocating download of the code?

**Comment by BytesGalore** [comment]
np :)
But, what changed your mind(s)?

**Comment by OlegHahm** [comment]
While I see the performance issues that @kaspar030 mentions, I still think this is the cleanest version.

The version in #4317 would have required some ugly tweaks to the CI or - even worse - require to ignore CI results.

**Comment by kYc0o** [comment]
Oops! Sorry, I already looked at such PR but I don't know why I didn't suggest it again... I agree with the two options, maybe reopen #5687 or make a clone of that sources in a git repo.

The problem now is the CI so that's why we changed our mind... (or at least mine :P )

**Comment by OlegHahm** [comment]
> or make a clone of that sources in a git repo

I think we should go for this solution to take some load from the CI.

**Comment by kYc0o** [comment]
There was a mistake on the test using `USEMODULE += tweetnacl` instead of `USEPKG=tweetnacl`.

Anyways I'm working on a git repo solution...

**Comment by kYc0o** [comment]
Well seems like creating a package is not trivial... I'll try this solution for now while I prepare the pkg...

**Comment by kYc0o** [comment]
>>or make a clone of that sources in a git repo

>I think we should go for this solution to take some load from the CI.

Addressed as another option in #6293

**Comment by OlegHahm** [comment]
Can we close this?

**Comment by kYc0o** [comment]
Uhm... I'm not sure what @kaspar030 would like to do, if continue the way this PR proposes or go for the 4th attempt with "quiet some things different"

**Comment by kYc0o** [comment]
superseded by #6293

**Pull request closed without merging**
