### PR TITLE
gnrc_dhcpv6_client_simple_pd: select upstream based on type/index

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This makes it more straightforward to select an upstream interface if there are multiple possible options.

### Testing procedure

Tested `examples/gnrc_border_router` with

    CFLAGS += -DCONFIG_GNRC_DHCPV6_CLIENT_6LBR_UPSTREAM_TYPE=NETDEV_ESP_WIFI

to set select the WiFi interface as the upstream.
The downstream was `tinyusb_netdev` in my case, so not a 6lo interface that could get auto-selected.

### CODE REVIEW

**Comment by miri64** [comment]
Tried this (intentionally, since your test description does not even mention ESP) on `native`. Unsurprisingly, there is no prefix assigned, but also, there is no warning or error, when trying to select an interface that does not exist.

**Comment by miri64** [comment]
On `esp32-wroom-32`: while explicitly selecting DHCPv6 with `PREFIX_CONF=dhcpv6`, `uhcp` is still compiled in and I get `uhcp_client(): no reply received` log outputs oO. Did not test on `master` , but something is definitely broken here.

**Comment by benpicco** [comment]
I was using it with this

```patch
diff --git a/examples/gnrc_border_router/Makefile b/examples/gnrc_border_router/Makefile
index d9e3929e32..e9347afb8b 100644
--- a/examples/gnrc_border_router/Makefile
+++ b/examples/gnrc_border_router/Makefile
@@ -16,15 +16,15 @@ ifeq (,$(filter ethos slip cdc-ecm wifi ethernet,$(UPLINK)))
 endif
 
 # Set the SSID and password of your WiFi network here
-WIFI_SSID ?= "Your_WiFi_name"
-WIFI_PASS ?= "Your_secure_password"
+WIFI_SSID ?= "changeme"
+WIFI_PASS ?= "changeme"
 
 # Include packages that pull up and auto-init the link layer.
 # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
 USEMODULE += netdev_default
 USEMODULE += auto_init_gnrc_netif
 # Specify the mandatory networking modules for 6LoWPAN border router
-USEMODULE += gnrc_sixlowpan_border_router_default
+USEMODULE += gnrc_ipv6_router_default
 # Additional networking modules that can be dropped if not needed
 USEMODULE += gnrc_icmpv6_echo
 # Add also the shell, some shell commands
@@ -39,8 +39,8 @@ USEMODULE += ps
 # Optionally include DNS support. This includes resolution of names at an
 # upstream DNS server and the handling of RDNSS options in Router Advertisements
 # to auto-configure that upstream DNS server.
-#USEMODULE += sock_dns              # include DNS client
-#USEMODULE += gnrc_ipv6_nib_dns     # include RDNSS option handling
+USEMODULE += sock_dns              # include DNS client
+USEMODULE += gnrc_ipv6_nib_dns     # include RDNSS option handling
 
 # When using a regular network uplink we should use DHCPv6
 ifneq (,$(filter cdc-ecm wifi ethernet,$(UPLINK))$(REUSE_TAP))
@@ -56,7 +56,7 @@ endif
 
 ifeq (dhcpv6,$(PREFIX_CONF))
   # include DHCPv6 client for 6LoWPAN border router
-  USEMODULE += gnrc_dhcpv6_client_6lbr
+  USEMODULE += gnrc_dhcpv6_client_simple_pd
 else ifeq (uhcp,$(PREFIX_CONF))
   # include UHCP client
   USEMODULE += gnrc_uhcpc
diff --git a/examples/gnrc_border_router/Makefile.board.dep b/examples/gnrc_border_router/Makefile.board.dep
index 12f755ceb4..211b05a7aa 100644
--- a/examples/gnrc_border_router/Makefile.board.dep
+++ b/examples/gnrc_border_router/Makefile.board.dep
@@ -7,7 +7,9 @@ ifeq (,$(filter native,$(BOARD)))
   else ifeq (wifi,$(UPLINK))
     ifneq (,$(filter esp32 esp8266,$(CPU)))
       USEMODULE += esp_wifi
-      USEMODULE += esp_now
+      USEMODULE += tinyusb_netdev
+      CFLAGS += -DCONFIG_GNRC_DHCPV6_CLIENT_6LBR_UPSTREAM_TYPE=NETDEV_ESP_WIFI
+      CFLAGS += -DCONFIG_GNRC_IPV6_NIB_NUMOF=32
     else
       $(error Only esp32 and esp8266 are currently supported)
     endif
```

to create a USB <-> WiFi router with `make BOARD=esp32s2-wemos-mini UPLINK=wifi`

`esp32-wroom-32` doesn't have a native USB interface, so you might try with SLIP or ethos.

**Comment by miri64** [comment]
Still worrisome, that apparently there is a bug, when selecting DHCPv6, UHCP is still included.

**Comment by benpicco** [comment]
That's odd because there is only a [single place](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_border_router/Makefile#L60) where the UHCP module is selected.

Still, this is unrelated to this PR.

**Comment by miri64** [comment]
> Tried this (intentionally, since your test description does not even mention ESP) on `native`. Unsurprisingly, there is no prefix assigned, but also, there is no warning or error, when trying to select an interface that does not exist.

Still this issue remains.

**Comment by fabian18** [comment]
> also, there is no warning or error, when trying to select an interface that does not exist

Maybe check return value of `_find_upstream_netif()` in `_configure_dhcpv6_client()` as it is done in `_dhcpv6_cl_simple_pd_thread()`.

**Comment by benpicco** [comment]
True, that one didn't check if the return value was valid at all.

**Comment by miri64** [comment]
:+1: At the moment, I do not have the node around to test, but I am fine with the current version at the moment.

**Review by fabian18 — APPROVED** [review]
Choosing `ESP_WIFI` as uplink works with `CFLAGS += -DCONFIG_GNRC_DHCPV6_CLIENT_6LBR_UPSTREAM_TYPE=NETDEV_ESP_WIFI`.
Else it is choosing `slipdev` or `ethos` when enabled.

```
2023-02-20 16:35:13,272 # Iface  10  HWaddr: A4:CF:12:44:D2:D0  Channel: 1  Link: up 
2023-02-20 16:35:13,281 #           L2-PDU:1500  MTU:1500  HL:64  RTR  
2023-02-20 16:35:13,283 #           Source address length: 6
2023-02-20 16:35:13,285 #           Link type: wireless
2023-02-20 16:35:13,286 #           inet6 addr: fe80::a6cf:12ff:fe44:d2d0  scope: link  VAL
2023-02-20 16:35:13,288 #           inet6 addr: 2a0c:d242:4482:3a00:a6cf:12ff:fe44:d2d0  scope: global  VAL
2023-02-20 16:35:13,303 #           inet6 group: ff02::2
2023-02-20 16:35:13,304 #           inet6 group: ff02::1
2023-02-20 16:35:13,305 #           inet6 group: ff02::1:ff44:d2d0
```

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
