### PR TITLE
Merging mutex_lock and mutex_wait

### PR DESCRIPTION
**Pull request by IldarValiev**
mutex_lock function was meaningless. It checked the mutex and if it was locked then this function checked it again in mutex_wait. In this PR I merged two functions in one and changed the sequence of DEBUG messages.

mutex_wait was not used anywhere in the code, as far as I know.

mutex_unlock_and_sleep test OK.

### CODE REVIEW

**Comment by kaspar030** [comment]
The double check is needed. The first check uses just the atomic variable. If the calling thread set that from "0" to "1", it knows that the mutex was locked before, so it initiates the waiting.

Within the waiting, the calling thread disables IRQ and then checks again if the mutex has been unlocked *since the last check*.

With your change, if an ISR unlocks the mutex after line 49, but before disabling IRQs in line 56, the thread would never get woken up, even if the mutex is actually free.

**Comment by kaspar030** [comment]
It is possible to drop the double check by disabling IRQs right at the beginning, but that's a serious penalty for the non-locked case.

**Comment by Kijewski** [comment]
Depends. Without `ARCH_HAS_ATOMIC_COMPARE_AND_SWAP` disabling IRQs immediately would be faster.

**Comment by kaspar030** [comment]
True, and I'm just realizing that only x86 and Cortex-M* have ```ARCH_HAS_ATOMIC_COMPARE_AND_SWAP```.

But still, as is, the PR introduces a race.

@IldarValiev Are you ok to close it?

**Comment by IldarValiev** [comment]
@kaspar030, now mutex_wait is called only by mutex_lock - unnecessary code splitting. If you don't want to merge two functions in one (with addition of second check), then yes, you can close this PR.

**Comment by kaspar030** [comment]
@IldarValiev Well, the function is static and only called once. I split them for readability. Guess that's a style question...

**Comment by IldarValiev** [comment]
@kaspar030, understood. Feel free to close it.

**Comment by PeterKietzmann** [comment]
I'm gonna close this one for Kaspar. Guess you gave enough explanation to do so

**Pull request closed without merging**
