### PR TITLE
CPU：Fix header include guards

### PR DESCRIPTION
**Pull request by zhuoshuguo**
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#)

### CODE REVIEW

**Comment by gebart** [comment]
Nice!

Please reword the message to include a module prefix, "cpu: Fix header include guards".

Also, I would like to see the trailing double underscores replaced by single underscore,
e.g. `HW_TIMER_H__` -> `HW_TIMER_H_`

**Comment by zhuoshuguo** [comment]
updated.

**Comment by gebart** [comment]
ACK

**Comment by BytesGalore** [comment]
something is broken:
```
Building application "bindist" for "ek-lm4f120xl" with MCU "lm4f120".

/data/riotbuild/cpu/cortexm_common/thread_arch.c: In function 'thread_arch_isr_stack_usage':
/data/riotbuild/cpu/cortexm_common/thread_arch.c:262:24: error: 'STACK_CANARY_WORD' undeclared (first use in this function)
     while (*(ptr++) == STACK_CANARY_WORD) {}
                        ^
```
Murdoc seems to avoid producing the html, but there's still the plain build output here [1].

[1] https://ci.riot-labs.de/RIOT-OS/RIOT/5540/c721125aff2c2003cc22843203bfa5a25e6268cc/output.txt

**Comment by zhuoshuguo** [comment]
@BytesGalore Does some changes modified by this PR lead to such a broken?

**Comment by kaspar030** [comment]
> Does some changes modified by this PR lead to such a broken?

Does the application build for you locally?

**Comment by zhuoshuguo** [comment]
@kaspar030 Actually, I don't know how to build the application locally. what does it refer to? Or what should I do. :-)

**Comment by BytesGalore** [comment]
> Does some changes modified by this PR lead to such a broken?

@zhuoshuguo can't tell, the missing define is located here [1] and should be available.
The only change that could be somehow related is in the [cortex-m4-def.h](https://github.com/RIOT-OS/RIOT/pull/5540/files#diff-35302f461dcbc8018a8696fe4220f6a5).


[1] https://github.com/RIOT-OS/RIOT/blob/master/cpu/cortexm_common/include/cpu.h

**Comment by zhuoshuguo** [comment]
@BytesGalore I think so and have tried to resume cortex-m4-def.h the way it was (cancelled the modification), but still, the check failed.

**Comment by BytesGalore** [comment]
@zhuoshuguo I overlooked it at the first sight, but the MCU includes all stellaris headers [1]. So probably we should have a look there.

[1] https://github.com/RIOT-OS/RIOT/blob/master/cpu/lm4f120/include/cpu_conf.h#L38

**Comment by BytesGalore** [comment]
@zhuoshuguo so the `__CPU_H__` guard [1] caused the fault?

[1] https://github.com/zhuoshuguo/RIOT/blob/a3fa6414691a4ee46f8e67e08fda0a0bb7ffb000/cpu/stellaris_common/include/stellaris_periph/cpu.h#L40

**Comment by zhuoshuguo** [comment]
@BytesGalore Oops, seems like it is!~ I cancelled the revision on [1], and now, the check pass. :-)

[1][https://github.com/zhuoshuguo/RIOT/blob/a3fa6414691a4ee46f8e67e08fda0a0bb7ffb000/cpu/stellaris_common/include/stellaris_periph/cpu.h#L40](https://github.com/zhuoshuguo/RIOT/blob/a3fa6414691a4ee46f8e67e08fda0a0bb7ffb000/cpu/stellaris_common/include/stellaris_periph/cpu.h#L40)

**Comment by zhuoshuguo** [comment]
Now, I applied the revision on [ cortex-m4-def.h](https://github.com/RIOT-OS/RIOT/pull/5540/files#diff-35302f461dcbc8018a8696fe4220f6a5), and check whether it will pass or not.

**Comment by zhuoshuguo** [comment]
@gebart ping. What about now.

**Comment by gebart** [comment]
If you want to fix the cpu.h guard you could use another name, e.g. `STELLARIS_CPU_H_`, which won't collide with the cortexm_common cpu.h guard.
Other than that, the PR looks fine, Murdock passes.

**Comment by zhuoshuguo** [comment]
Thanks for the help. Updated and the checks passed.

**Comment by gebart** [comment]
ACK & go!

**Pull request merged**
