### PR TITLE
dist/tools: Use bash instead of sh where needed

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

A number of scripts use features from bash such as `local` which are not
in the POSIX spec. This breaks on systems where sh is not symlinked to
bash.

This patch changes the interpreter indicated by the hashbang to bash for
those scripts

### Testing procedure

Check that the scripts indeed use bash features :)

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
Thanks a lot for this @bergzand !

**Comment by silkeh** [comment]
This should use `/usr/bin/env bash` as `bash` is not guaranteed to exist in `/bin`!

**Comment by bergzand** [comment]
> This should use `/usr/bin/env bash` as `bash` is not guaranteed to exist in `/bin`!

Done!

**Comment by silkeh** [comment]
Another improvement would probably be to add `set -euo pipefail` to all scripts. From `help set`:

```
-e  Exit immediately if a command exits with a non-zero status.
-u  Treat unset variables as an error when substituting.
-o option-name
    Set the variable corresponding to option-name:
        pipefail     the return value of a pipeline is the status of
                     the last command to exit with a non-zero status,
                     or zero if no command exited with a non-zero status
```

**Comment by bergzand** [comment]
> Another improvement would probably be to add `set -euo pipefail` to all scripts. From `help set`:

There are many improvements we could make to the bash script some day. That day however, is not now. :stuck_out_tongue_winking_eye:

**Comment by aabadie** [comment]
`dist/tools/cmake/generate-xcompile-toolchain.sh` is still using `sh`:
https://github.com/RIOT-OS/RIOT/blob/b1146c0f420fe61e3719422356b12fbbb7e2cb5b/dist/tools/cmake/generate-xcompile-toolchain.sh#L1

**Review by aabadie — APPROVED** [review]
ACK

**Pull request merged**
