### PR TITLE
boards/nucleo-f303: fix broken stdio uart dev

### PR DESCRIPTION
**Pull request by aabadie**
This fixes the nucleo-f303 debug uart which was broken.
This partially fix issue #5707.

### CODE REVIEW

**Comment by aabadie** [comment]
thanks @kYc0o for the help :)

**Comment by PeterKietzmann** [comment]
Seems reasonable to me
```
/* UART 1 pin configuration */
#define UART_1_PORT_CLKEN() (RCC->AHBENR |= RCC_AHBENR_GPIOAEN)
#define UART_1_PORT         GPIOA
#define UART_1_TX_PIN       2
#define UART_1_RX_PIN       3
#define UART_1_AF               7
```

**Comment by kYc0o** [comment]
@PeterKietzmann I didn't get you comment... those lines exist in the current code. (There was a wrong commit immediately squashed...)

**Comment by cgundogan** [comment]
is this PR related to #5993 ? Why is `UART_STDIO_DEV` necessary for the f303 board, while it was superfluous for the f103 board?

**Comment by cgundogan** [comment]
I understand, that you need to define it to switch from the default UART_0 to UART_1, but the question is rather why is this necessary for the f303?

**Comment by aabadie** [comment]
> I understand, that you need to define it to switch from the default UART_0 to UART_1, but the question is rather why is this necessary for the f303?

the change is not the only solution, we could also change the UARTs definition order in `periph_conf.h` in a way that the first one is the debug/USB UART. I used the UART_STDIO_DEV macro to keep the `periph_conf.h` untouched and to keep the USART order (UART_0 => USART_1, UART_1 => USART_2, etc)

I have no strong opinion on what is the best.

**Comment by kYc0o** [comment]
I'd also like to talk about it, since I see several "inconsistencies" on the `periph_conf` file on almost all nucleo boards.

IMHO, I think is better to keep some "coherence" in the assign of `UART_X` to the actual UART ports. I can be surprised by using `UART_2` in my application but it actually points to `UART1` on the board, when I'm expecting it to point to `UART3` for instance.

I see that such "misplacing" it's maybe only done to avoid `UART_STDIO_DEV` pointing to a different UART than the default (0), but maybe I'm wrong and there are strong reasons to keep this like that.

@haukepetersen Can you maybe explain this?

**Comment by haukepetersen** [comment]
Yes, I can try.

> IMHO, I think is better to keep some "coherence" in the assign of UART_X to the actual UART ports. I can be surprised by using UART_2 in my application but it actually points to UART1 on the board, when I'm expecting it to point to UART3 for instance.

no. The 'logical' UART devices that we use in RIOT (i.e. `UART_DEV(x)`) are by design decoupled from the actual uart devices provided by the hardware (i.e. `UARTx`) on purpose so we are free to map pins as we need them. Say you want UART RX on pin A.9, then on most boards you are fixed to use a specific uart device, say UART5. So say also this is the only UART you use on your board, you want to map UART5 to `UART_DEV(0)` in this case. The nice thing is, that RIOT application developers don't even need to know anything about which actual hardware UART they are using as long as the perpih configuration is done. So there is intentional no "coherence" between RIOT devices and hardware devices.

**Comment by haukepetersen** [comment]
@aabadie: to fix the broken UART, you might just want to switch the UART definitions in the `periph_conf.h`, so that `UART_DEV(0)` is mapped to UART2 with the needed pins.

**Comment by aabadie** [comment]
@haukepetersen, I pushed an update with the changes you requested.

**Comment by haukepetersen** [comment]
and go

**Comment by kYc0o** [comment]
> no. The 'logical' UART devices that we use in RIOT (i.e. `UART_DEV(x)`) are by design decoupled from the actual uart devices provided by the hardware (i.e. `UARTx`) on purpose so we are free to map pins as we need them. Say you want UART RX on pin A.9, then on most boards you are fixed to use a specific uart device, say UART5. So say also this is the only UART you use on your board, you want to map UART5 to `UART_DEV(0)` in this case. The nice thing is, that RIOT application developers don't even need to know anything about which actual hardware UART they are using as long as the perpih configuration is done. So there is intentional no "coherence" between RIOT devices and hardware devices.

Thanks for the explanation!

However, I can understand this perspective if you assume that people using RIOT didn't use the device before, but IMHO several developers who are used to platforms that now are supported by RIOT need to learn about this particularity.

Another thing is that in the particular case of this PR the UART is configured only for the convenience of having it as the default STDIO, and since periph configuration is somehow static I cannot see the advantage of mapping UARTx to UART_x without modifying the platform pinout, which I think shouldn't be modified. I can see the advantage if the pin mapping would be allowed for modification at compile time, so this way the platform code doesn't need to be modified.

I have the impression that I'm maybe confused and I'm misunderstanding how this works, so I'll try to keep it in mind for future PRs and issues.

**Pull request merged**
