### PR TITLE
tests: remove remaining use of "TEST_ON_CI_WHITELIST += all"

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Apparently there are 2 remaining use of `TEST_ON_CI_WHITELIST += all` in the test applications although this is not needed since `all` is the default on Murdock (e.g. all boards are whitelisted), see [here](https://github.com/RIOT-OS/RIOT/blob/master/makefiles/murdock.inc.mk#L40).

This PR does 2 things:
- fixing the 2 application Makefiles where the pattern is still used: `tests/test_tools` and `tests/sys_crypto`
- exclude this pattern in the buildsystem sanity check script

Also cc'ing @cladmi to have his opinion on that.

### Testing procedure

- Enable `CI: run tests` and verify the 2 tests are run on all available boards
- Add the pattern in one test application Makefile and verify that the buildsystem sanity check reports an error (e.g. by running `./dist/tools/buildsystem_sanity_check/check.sh`)

### Issues/PRs references

Not sure which one this is related to.

### CODE REVIEW

**Comment by miri64** [comment]
Disabled cache, so the results are actually shown.

**Comment by aabadie** [comment]
> Disabled cache, so the results are actually shown.

Thanks, I was looking for the tests but couldn't find them on Murdock and didn't know how to do that :)

**Comment by aabadie** [comment]
Thanks @miri64 :)

**Comment by cladmi** [comment]
They were indeed tests that I forgot to update when it was changed. Good to prevent re-appearing again :)

**Pull request merged**
