### PR TITLE
ng_inet_csum: fix double-wrap around of carry

### PR DESCRIPTION
**Pull request by authmillenon**
Second fix for the off-by-one error of the checksum.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current master and fixed a typo

**Comment by haukepetersen** [comment]
Works nicely (tested together with #3292). ACK once squashed and Travis is green.

**Comment by PeterKietzmann** [comment]
Nice! The plain IPv6 example runs really stable now:
```
1000000 packets transmitted, 1000000 received, 0% packet loss, time 120.06940713 s
rtt min/avg/max = 0.063/0.120/2000.959 ms
```

**Comment by haukepetersen** [comment]
@PeterKietzmann: We had the same idea, I had my 1 Million pings running just 10min ago :-)

**Comment by PeterKietzmann** [comment]
Please squash your latest commit

**Comment by authmillenon** [comment]
Squashed

**Pull request merged**
