### PR TITLE
pkg/semtech-loramac: update to upstream v4.4.1 + cleanup

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR updates the target version of the Semtech [loramac-node](https://github.com/Lora-net/LoRaMac-node) to the latest release (4.4.1).

For simplicity, the  branch is based on #8639.

While working on it, I realized that some code in the driver was useless (rx timeout timer) so I removed it.

I tested the port against TheThingsNetwork but for the moment it doesn't as reliably as expected.

### Issues/PRs references

Based on ~#8639~

### CODE REVIEW

**Comment by ecarthi** [comment]
I am hoping to use this pull request for a project, and would like to help out. What unreliable behavior have you observed? And do you have a sense of where the problem might be coming from?

From my end, I see OTAA joins failing before a reply can be received (sometimes, but not always), and data transmissions aren't being sent - plus the test code hangs indefinitely with no confirmation or failure message when trying to send data.

Thanks.

**Comment by aabadie** [comment]
Thanks for proposing some help here @ecarthi.

> What unreliable behavior have you observed? And do you have a sense of where the problem might be coming from?

I didn't rework this PR recently, just rebased it now, but the problems I initially observed are the same as the ones you describe regarding reply not received: the RX windows are closed too early so messages sent from the backend are missed. The problems were happening mostly with DR0/DR1.

Regarding the code that is hanging, this was fixed in master, so now that the branch is rebased, this shouldn't happen anymore (not yet tested though).

Otherwise, the good point with this loramac version is the possibility to select the datarate during the join procedure. With the old version, this is not possible.

**Comment by dylad** [comment]
@aabadie do you think you can rebase this PR ? I have some new hardware I'd like to test, I would like to try your PR and I need the I2C rework  ;)

**Comment by aabadie** [comment]
> do you think you can rebase this PR ?

I already rebased it after I2C rework was merged.

**Comment by dylad** [comment]
I ran some tests with this PR and my new board 
What I can say right now : 
otaa join works excepts with DR0 and DR1
I can exchange data between my node and my gateway

**Comment by olegart** [comment]
Hi

We did it separately — https://github.com/unwireddevices/RIOT/tree/loralan-public-2018.07/pkg/semtech-loramac, also backported RU864 band from 1.0.3a

Application logic is here — https://github.com/unwireddevices/RIOT/blob/loralan-public-2018.07/examples/loralan-wan/main-node.c (not a pure example, but a part of a bigger project, and some logic is not here yet, e.g. uplink queue)

Works quite good with Thingpark and Gotthard's LoRaWAN server, including DR0 OTAA joins.

**Comment by dylad** [comment]
I'm trying to figure out what's wrong with this madness but I didn't make any progress.
Looks like the node doesn't see the join request's response from the gateway. I've hacked all the timings and yet I never received the RX done interrupt. It seems to me all parameters are all set correctly by the LoRaMAC stack...
I also tried to compated with @olegart's branch but still no clue.

**Comment by dylad** [comment]
@olegart I am not a ST user so I won't be able to test your branch directly. I'm using TTN with a multitech GW for now. I don't think (yet ?) this is related to the server. I'll try to put more time on it later.

**Comment by dylad** [comment]
I have some news about DR0 and DR1. TTN seems to use the RX2 window to send the join request's response. But a timeout occurs even before the device setup the RX2 window leading to failure.

**Comment by dylad** [comment]
@aabadie I was able to locate the DR0/DR1 join request issue. I'll provide a fix once cleanup done so we can finally move forward. Should I push your branch directly or you prefer handle it ?

**Comment by aabadie** [comment]
Thanks for your help @dylad ! That's really a good news.

> Should I push your branch directly or you prefer handle it ?

You can push to my branch, no problem.

**Comment by dylad** [comment]
To explain more in details what was going on there : 
For DR0/DR1 join requests, TTN send the response on the RX2 Window at the dedicated frequency (869525000 Hz). The issue was the behaviour of the `TimerGetElapsedTime` function implements in semtech_loramac_timer.c
```
    uint64_t CurrentTime = xtimer_now_usec64();
    return (TimerTime_t)(CurrentTime - savedTime) / US_PER_MS;
```
This function was substracting us with ms leading in incorrect results.

This wrong result was then used [here](https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/mac/LoRaMac.c#L1219)
Because of that, the condition was true and LoRaMac was aborting the RX2 setup  when the timeout of RX1 was received. Since the RX2 was not setup, we didn't received the TTN response because the device was not even listening.

Note : I also fixed TimerGetCurrentTime which was also incorrectly set

@aabadie I'll let you check if it solves issues on your side.
Since I commit to this PR, I'll let @jia200x or someone else ACK :)

**Comment by aabadie** [comment]
Interesting fix @dylad, so it was just a conversion issue ? I'll try to test today on IoT-LAB if time permits.

**Comment by aabadie** [comment]
I tested this PR on IoT-LAB and could join/send/receive packets using DR{0,1,2,3,4,5}. Thanks a lot @dylad !
Auto-ACK :)

**Comment by dylad** [comment]
> I tested this PR on IoT-LAB and could join/send/receive packets using DR{0,1,2,3,4,5}. 

Great ! One approves and we can finally merge this one !

**Comment by aabadie** [comment]
> One approves and we can finally merge this one !

To me it's perfectly fine if there's only yours :)

**Comment by dylad** [comment]
Me too but I'm afraid some maintainers don't have the same opinion.

**Comment by aabadie** [comment]
> I'm afraid some maintainers don't have the same opinion.

We can ask @jia200x's opinion but we may have to wait a bit again.

**Comment by jia200x** [comment]
Code-wise looks ok to me and AFAIS this replaces #9618. I will test it now

**Comment by jia200x** [comment]
It freezes :(
``` 
2018-09-24 13:57:37,938 - INFO #  help
2018-09-24 13:57:37,941 - INFO # Command              Description
2018-09-24 13:57:37,945 - INFO # ---------------------------------------
2018-09-24 13:57:37,949 - INFO # loramac              control the loramac stack
2018-09-24 13:57:37,953 - INFO # reboot               Reboot the node
2018-09-24 13:57:37,956 - INFO # random_init          initializes the PRNG
2018-09-24 13:57:37,962 - INFO # random_get           returns 32 bit of pseudo randomness
> loramac set deveui 70B3D57EDA06FF17
2018-09-24 13:57:49,368 - INFO #  loramac set deveui 70B3D57EDA06FF17
> loramac set appeui 70B3D57ED000912E
2018-09-24 13:59:21,864 - INFO #  loramac set appeui 70B3D57ED000912E
> loramac set appkey 16C47933D61F1722437CF9992DAB373F
2018-09-24 13:59:34,946 - INFO #  loramac set appkey 16C47933D61F1722437CF9992DAB373F
> loramac join otaa
2018-09-24 13:59:38,093 - INFO #  loramac join otaa
2018-09-24 13:59:47,460 - INFO # Join procedure succeeded!
> loramac tx asd
2018-09-24 13:59:50,852 - INFO #  loramac tx asd
2018-09-24 13:59:54,328 - INFO # TX complete, no data received
> loramac tx asd
2018-09-24 14:00:00,532 - INFO #  loramac tx asd
help

```
(Keys are posted on purpose, they are from a test app)

**Comment by dylad** [comment]
maybe a duty cycle issue ? You were using DR0 ?

**Comment by jia200x** [comment]
> maybe a duty cycle issue ? You were using DR0 ?

It seems it's DR0 by default, but the node is still  frozen after 25 minutes. So, I don't think it's an issue with the duty cycle.

**Comment by aabadie** [comment]
It's been a moment since I worked on that, but I think a check on the MAC state should be added somewhere: maybe in the send function, to prevent a TX while in a duty cycle or maybe there's a response of the MAC with a certain error code that is not taken into account by the thread.
I'll have a look at this.

**Comment by aabadie** [comment]
@jia200x, I have a fix. I need to polish it a bit and will push it tomorrow.

**Comment by aabadie** [comment]
@jia200x, @dylad I just pushed a couple of commits that improve things significantly in the interaction of RIOT adaption code and the MAC: no more freeze and better return statuses. It works very well now.
I hope this PR will be merged soon.

**Comment by jia200x** [comment]
just tested and works as expected!

**Comment by jia200x** [comment]
there's a bug but it's also present in upstream:

```
2018-09-25 13:46:36,207 - INFO #  loramac set dr 6
> loramac get dr
2018-09-25 13:46:39,839 - INFO #  loramac get dr
2018-09-25 13:46:39,840 - INFO # DATARATE: 0
> loramac set dr 5
2018-09-25 13:46:43,576 - INFO #  loramac set dr 5
> loramac get dr
2018-09-25 13:46:46,168 - INFO #  loramac get dr
2018-09-25 13:46:46,169 - INFO # DATARATE: 5
```

I'm OK to merge this one and add the fix in another PR

**Comment by jia200x** [comment]
(we should fix the DR issue, which is not related to this PR)

**Comment by dylad** [comment]
re-trigger Murdock for LLVM. We can push the green button right after !

**Comment by aabadie** [comment]
The CI passed, there's an ACK => all green, so let's go.
And special thanks to @dylad for finding the timers bug, that helped a lot.

**Pull request merged**
