### PR TITLE
boards/samd20-xpro: add definition for UART on EXT2

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

We can't use PB13/PB12 which would be the 'standard' UART pins on the -xpro EXT connectors since only SERCOM4 can map to those - and that's already used on EXT1.

So use the adjacent PA08/PA09 with SERCOM0.

### Testing procedure

Run `tests/periph_uart` with the UART pins connected

```
2022-06-09 13:10:58,792 - INFO # Manual UART driver test application
2022-06-09 13:10:58,795 - INFO # ===================================
2022-06-09 13:10:58,800 - INFO # This application is intended for testing additional UART
2022-06-09 13:10:58,806 - INFO # interfaces, that might be defined for a board. The 'primary' UART
2022-06-09 13:10:58,811 - INFO # interface is tested implicitly, as it is running the shell...
2022-06-09 13:10:58,811 - INFO # 
2022-06-09 13:10:58,817 - INFO # When receiving data on one of the additional UART interfaces, this
2022-06-09 13:10:58,823 - INFO # data will be outputted via STDIO. So the easiest way to test an 
2022-06-09 13:10:58,829 - INFO # UART interface, is to simply connect the RX with the TX pin. Then 
2022-06-09 13:10:58,835 - INFO # you can send data on that interface and you should see the data 
2022-06-09 13:10:58,837 - INFO # being printed to STDOUT
2022-06-09 13:10:58,837 - INFO # 
2022-06-09 13:10:58,841 - INFO # NOTE: all strings need to be '\n' terminated!
2022-06-09 13:10:58,841 - INFO # 
2022-06-09 13:10:59,098 - INFO # UARD_DEV(0): test uart_poweron() and uart_poweroff()  ->  [OK]
2022-06-09 13:10:59,099 - INFO # 
2022-06-09 13:10:59,100 - INFO # UART INFO:
2022-06-09 13:10:59,103 - INFO # Available devices:               3
2022-06-09 13:10:59,107 - INFO # UART used for STDIO (the shell): UART_DEV(0)

2022-06-09 13:11:18,024 - INFO # > test 2
2022-06-09 13:11:18,024 - INFO # 
2022-06-09 13:11:18,024 - INFO # [START]
2022-06-09 13:11:18,104 - INFO # [SUCCESS]
```

### CODE REVIEW

**Comment by maribu** [comment]
> We can't use PB13/PB12 which would be the 'standard' UART pins on the -xpro EXT connectors since only SERCOM4 can map to those - and that's already used on EXT1.

Would it be possible to "free" SERCOM4 somehow. If I understand correctly, the -xpro EXT connectors are to be used for "Arduino Shields"-like extension boards. I think there is tremendous value in supporting them out of the box.

**Comment by benpicco** [comment]
Unfortunately not, on the designated EXT1 pins we can only map SERCOM4

image

The same is true for PB12/13 on EXT2

image

**Comment by maribu** [comment]
Sounds like a hardware design failure :( (The Nucleo-F767ZI as a similar issue in which an SPI pin is connected to the Ethernet PHY. One can route the SPI to other pins, but that very pin used by the Ethernet PHY is placed on a connector where X-Nucleo expansions boards expect SPI. So running a LoRa Gateway using the X-Nucleo LoRa shield and connecting via Ethernet is impossible... I was considering to design an X-Nucleo adapter PCB that mates just wires the SPI pin differently to solve that issue.)

**Review by maribu — APPROVED** [review]

**Comment by benpicco** [comment]
Thank you for the review!

**Pull request merged**
