### PR TITLE
rust: Update dependencies, use riot-wrappers from git

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

As riot-wrappers has advanced a bit since it was last released, Rust modules are switched to using it from git again. (This is a regular ping-pong between testing the latest release in RIOT master, and using released support crates when they're current).

This primarily updates riot-wrappers, which has accumulated several compatible changes. Several other crates receive updates as well.

### Testing procedure

* Green CI

### Issues/PRs references

Changes on the riot-wrappers side:

* https://github.com/RIOT-OS/rust-riot-wrappers/pull/17
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/22
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/29
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/30

[edit: added:]

This also serves to help preparing a 0.8.1 release of riot-wrappers, which performs some deprecations so that a breaking 0.9 change can be done more effortlessly later on.

### CODE REVIEW

**Comment by chrysn** [comment]
An instasquashed commit fixes that, once again, the coap-handler-implementations' fuzziness when it comes to supporting minicbor. (It supports "any" minicbor version, but unless the user picks the same one consistently in all transitive dependencies, things do fall apart).

After the round of updates, that second change was created using `cargo update --package='minicbor@0.15.0' --precise '0.13.0'` in the rust-gcoap example.

**Comment by chrysn** [comment]
Given I've merged a few more PRs on riot-wrappers today, this was also updated to

* https://github.com/RIOT-OS/rust-riot-wrappers/pull/32
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/31
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/19

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
