### PR TITLE
murdock: allow skipping of PR builds

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR adds support for not running a build by having "[ci skip]" in the HEAD commit message.

The check is hooked into both the job collection (to skip it), and into "static-tests" (to report an error and fail the build).

~~WIP~~

### Testing procedure

There's a test commit that fails the build. Here's the output:

```
-- running on worker riotbuild-6 thread 2, build number 124353.
--> "Skipping build: [ci skip] found in HEAD commit subject."
```

### CODE REVIEW

**Comment by miri64** [comment]
Can you put bb180d0 (or cherry-pick a copy) so the effect is visible with your fixups? Or are you still testing yourself?

**Comment by kaspar030** [comment]
still testing. locally it works perfectly, somehow not in the murdock checkout...

**Comment by fjmolinas** [comment]
Is there a difference between this and `CI: skip compile test`?

**Comment by miri64** [comment]
The label can only be set by contributors with triaging rights and only PR-wise. This change allows for having this commit-wise and done by the contributor who provides the change.

**Comment by fjmolinas** [comment]
> The label can only be set by contributors with triaging rights and only PR-wise. This change allows for having this commit-wise and done by the contributor who provides the change.

Ah thanks, I should stop reading diagonally through a Pr description.

**Comment by miri64** [comment]
@kaspar030 any plans to work on this further?

**Comment by kaspar030** [comment]
> Since the stale bot brought this back to my attention: doesn't it make more sense if this were upstream in `kaspar030/murdock`?

probably, not even queueing the build would be best. @aabadie's rewrite supports this already.
Anyhow, this change is simple enough and might save some CI cycles.

I think this is ready for review!

**Comment by kaspar030** [comment]
closing this one, doesn't seem to scratch enough itch

**Pull request closed without merging**
