### PR TITLE
RIOT/Makefile.include: added indicating of possibe conflicting features on compile

### PR DESCRIPTION
**Pull request by BytesGalore**
Using `SPI0` and `DAC0` on the `stm32f4discovery` at the same time, may result in unexpected behaviour as the `DAC0` is internally wired with the `SPI0` port of the board.

With this PR the user is informed during compile time whenever multiple, probably conflicting, features set in the variable `EXPECT_CONFLICT` in the `Makefile.features` of the individual board, are also required by a project.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann, @phiros may I assign one of you to this PR? As we don't NEED this PR we shouldn't merge it if someone is not satisfied with it. I don't have a strong opinion on this, so I would like give it up to someone who has a stronger positition.

**Comment by LudwigOrtmann** [comment]
@PeterKietzmann I am a bit swamped right now and also not strongly opinionated, so I'll pass ;)

**Comment by PeterKietzmann** [comment]
Has anyone an opinion on this PR? I can just say that I like a feature like that... Looking at #2063 we again had a situation where a conflict seems unavoidable when there is a wish for a special ADC usage.

**Comment by phiros** [comment]
@PeterKietzmann and @BytesGalore  I will be able to provide detailed feedback next week (Currently, I am swamped with work).

**Comment by BytesGalore** [comment]
@PeterKietzmann @phiros I removed the test from the `Makefile` since I have troubles to execute the python script properly when called from the `test:` target.
And of course rebased to current master.

**Comment by PeterKietzmann** [comment]
@phiros may I assign you? I like this feature but as there had been some discussions in the past I would like to pass this PR so someone with more experience in all that makefile stuff and with a stronger opinion on that.

**Comment by PeterKietzmann** [comment]
Travis says there are several trailing whitespaces...

**Comment by BytesGalore** [comment]
@PeterKietzmann I removed the trailing whitespaces.
Beside the need of squahing travis seems to be happy now :)

**Comment by OlegHahm** [comment]
@phiros, @PeterKietzmann , @BytesGalore, what's the current state?

**Comment by BytesGalore** [comment]
@OlegHahm it still works as intended, and I still like it to be merged :) .
The [`test.py`](https://github.com/BytesGalore/RIOT/blob/add_conflict_warning/tests/warn_conflict/test.py) works also, but I can't figure out how I could use it in a test target, 
e.g. using `make BOARD=stm32f4discovery test`.
Calling the script from a make target confuses things with environment variables/exports.

**Comment by BytesGalore** [comment]
@PeterKietzmann should I squash?

**Comment by PeterKietzmann** [comment]
I hoped that someone with more knowledge in the make system (e.g. @phiros) would give feedback. But as nobody NACKed this PR for a long time and this is optional more or less an optinal feature I would finally ACK this now. Yes, please squash!

**Comment by bapclenet** [comment]
@PeterKietzmann, did you try? If yes and it works, let's go

**Comment by BytesGalore** [comment]
squashed.

**Comment by PeterKietzmann** [comment]
Okay, I'll do it now. ACK and go

**Pull request merged**
