### PR TITLE
cpu/lpc11u34: fixed ADC resolution selection

### LINKED ISSUE #5489: cpu/lpc11u34: ADC broken
It looks like the lpc11u34 ADC implementation is broken with regards to the resolution.

https://github.com/RIOT-OS/RIOT/commit/575659cd1cfce7d018e90b4b9d24daee6d6f4a44 broke it.

Given the definition of `adc_res_t` in `periph_cpu.h`: The check at
https://github.com/RIOT-OS/RIOT/commit/575659cd1cfce7d018e90b4b9d24daee6d6f4a44#diff-50f14e4c5c396b6989e259ec75fac8c0R83
will always be true and the function will return -1.

I don't have the board to test and no time to fix it, just adding this as a reminder.

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #5489 (or at least I hope so, don't have a board to test...)

### CODE REVIEW

**Comment by gebart** [comment]
Murdock2 is fine, @haukepetersen did you test this on actual hardware?

**Comment by haukepetersen** [comment]
nope, I don't have this HW, and if I remember correctly nobody in Berlin/HH/Paris does...

**Comment by haukepetersen** [comment]
actually, by looking at the driver once more, I found it broken in many more ways (and it seems to have been broken from the beginning as I see it...). Hopefully all should be good now.

As nobody seems to have a board with this CPU, is anyone willing to give an untested ACK (maybe after sharply comparing the changes done to the [reference manual](http://www.nxp.com/docs/en/user-guide/UM10462.pdf), page 385 ff?!

**Comment by gebart** [comment]
@haukepetersen perhaps it is time to drop the support for this CPU, since nobody seem to have the board and there is little or no interest in the PRs related to it?

**Comment by haukepetersen** [comment]
I send a private mail to Paul to check if he is still able to maintain the platform, so let's wait for his reply before dropping anything...

**Comment by haukepetersen** [comment]
Got an answer a while ago: he will not be able to maintain the board in the near future and we is ok with removing the board for now. I propose the following: we merge this PR untested and remove the board in a next step, but by documenting it so it can be pulled back into master if a new maintainer is available.

@gebart you ok with this? If yes -> press merge :-)

**Pull request merged**
