### PR TITLE
boards/sipeed-longan-nano: revert default to variant with TFT

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR reverts commit 69fb00bdfa13c5e83409fd6b5bd5068cf00fc08b to fix CI compilation.

### Testing procedure

Green CI with full build.

### CODE REVIEW

**Comment by gschorcht** [comment]
> would fix the mismatch, as without `KConfig` the TFT display driver is pulled in by `disp_dev` no matter what, but the board config part of the TFT driver needs to be enabled by hand. The above diff would make sure that the board config is pulled in when the driver is used.

Ok let's try this change.

**Comment by gschorcht** [comment]
@maribu It's still an open issue. Should I squash so that we can try the next round?

**Comment by maribu** [comment]
It will not fix the issue, though:

- With KConfif the correct driver *and* params are pulled in by `disp_dev`
- Without KConfig, the correct driver is pulled in *without* the params

The diff in the params will result in mismatching firmwares. See https://github.com/RIOT-OS/RIOT/pull/19814#issuecomment-1628965917 for a patch

**Comment by gschorcht** [comment]
> The diff in the params will result in mismatching firmwares. See [#19814 (comment)](https://github.com/RIOT-OS/RIOT/pull/19814#issuecomment-1628965917) for a patch

Sorry I missed the diff for `Makefile.include`. I pushed now this change also.

**Review by maribu — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
