### PR TITLE
Block cipher operation modes: ECB, CBC, CTR and CCM

### PR DESCRIPTION
**Pull request by cholin**
Hey.

This is the followup to #1200. Refactored, rebased and without the crypto shell example. It adds support for ECB, CBC, CTR and CCM (RFC 3610) block cipher operation modes. This is the version we are currently using in our DTLS working branch. To omit a pull request of death for DTLS we would be happy if we could manage to merge this before.

Regards
Nico

### CODE REVIEW

**Comment by authmillenon** [comment]
Any progress/activity here?

**Comment by x3ro** [comment]
I would close this now, as it has been replaced by #2759. Any objections @OlegHahm @Kijewski @authmillenon ?

**Comment by Kijewski** [comment]
Yeah, just poke @cholin in the other PR so he knows his PR is not forgotten.

**Comment by PeterKietzmann** [comment]
Just do so!

**Comment by x3ro** [comment]
Changes migrated to #2759

**Comment by cholin** [comment]
:thumbsup:

**Comment by OlegHahm** [comment]
For the record: no objections from my side, either.

**Pull request closed without merging**
