### PR TITLE
doc: Add nightly build status of master to README

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This adds a small badge to the README that shows the current build status of the nightly builds.

### Issues/PRs references
There is still an issue with the alignment within the graphic, that should be fixed with https://github.com/RIOT-OS/murdock-scripts/pull/15 (and once @kaspar030/@smlng worked in that change into the running instance of Murdock)

### CODE REVIEW

**Comment by kaspar030** [comment]
So how do we fix that? the all green button is veery tempting. :)

**Comment by miri64** [comment]
> So how do we fix that?

Merge https://github.com/RIOT-OS/murdock-scripts/pull/15, integrate into Murdock, done.

**Comment by kaspar030** [comment]
beautiful: https://ci.riot-os.org/RIOT-OS/RIOT/8918/07a2b319ec13f2c86d61821e39e1628f2940e80a/badge.svg

I'll merge now. Until the next nightly, the badge will look off, though.

**Comment by miri64** [comment]
I guess the world won't mind one day of an off-looking badge ;-)

**Pull request merged**
