### PR TITLE
cpu/esp32: fix malloc thread safety

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the thread safety of heap allocation functions for ESP32.

Heap allocation functions in `newlibc-nano` for ESP32 (`malloc`/`free`/`...`) seem not to be thread save. `tests/malloc_thread_safety` fails either with
```
Testing: malloc()/free()
EXCEPTION!! exccause=28 (LoadProhibitedCause) @800d2b28 excvaddr=fffffffc
```
or with
```
Testing: malloc()/free()
Not all blocks were correctly freed!
mallinfo().uordblks before test: 4308, after test: 3224625688
Testing: realloc()/free()
Not all blocks were correctly freed!
mallinfo().uordblks before test: 4308, after test: 3224625688
TEST FAILED
```

Therefore, if heap allocation functions from `newlibc-nano` are used (module `esp-idf-heap` is not enabled) module `malloc_thread_safe` has to be used to make heap allocation thread safe. Heap allocation functions in ESP-IDF (module `esp-idf-heap`) that are used with SPI RAM or `esp-wifi` are already thread safe.

### Testing procedure

Use
```
BOARD=esp32-wroom-32` make -j8 -C tests/malloc_thread_safety flash test
```
With this PR the test has to work, without this PR the test crashes or fails.

### Issues/PRs references

Found while testing PR #18202.

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by gschorcht** [comment]
Strange, there are sporadic compilation errors in CI due to different hashes, in this PR, other PRs and for different applications, which I can't reproduce locally [log](https://ci.riot-os.org/RIOT-OS/RIOT/18209/041fe58209c51597ec8f6fc45e11c2a6db4b9d93/output/compile/tests/mtd_mapper/esp32-heltec-lora32-v2:gnu.txt)

**Comment by gschorcht** [comment]
> @kaspar030 traced it down to differences in the debug information of the elf files - the hash of stripped binaries matches again. I was able to reproduce the issue with `BUILD_IN_DOCKER=1`.

Do you mean this time or when we already had this problem two weeks ago? I remember that @kaspar030 said at the time that the debugging information differ, but in fact it was an actual difference in the bootloader binary.

**Comment by maribu** [comment]
The full Murdock run was recent enough and the only failure was a hash mismatch due to different `.debug` sections. No need to wast days of CPU times due to that, so I skip compile tests this time.

**Comment by gschorcht** [comment]
> The full Murdock run was recent enough and the only failure was a hash mismatch due to different `.debug` sections. No need to wast days of CPU times due to that, so I skip compile tests this time.

Yes, but we should still find out the reason. However, I myself have no idea how.

**Comment by gschorcht** [comment]
@maribu Thanks for reviewing and merging

**Pull request merged**
