### PR TITLE
pyterm: exit properly on SIGINT

### PR DESCRIPTION
**Pull request by authmillenon**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Leads to some problems (uncaught exception) if used in combination with json/twisted (`-s <host> -P <port>`).

**Comment by RIOT-notifier** [comment]
Twisted behaves very weirdly... Will investigate.

**Comment by OlegHahm** [comment]
Twisted is a beast...

**Comment by authmillenon** [comment]
I give up on this. Even if I kill twisted properly (at least I assume so, since I call the same thing as in the `/exit` method) it keeps running....

**Pull request closed without merging**
