### PR TITLE
cpu/{sam0_common, stm32}: select netdev_legacy_api in KConfig

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This fixes the discrepancy between the `USEMODULE` based dependency resolution and the KConfig based dependency resolution.

### Testing procedure

CI should build again

### Issues/PRs references

follow-up to #18426

### CODE REVIEW

**Review by MrKevinWeiss — APPROVED** [review]
ACK, tested with 
```
for test in tests/driver_sam0_eth tests/driver_stm32_eth/; do for board in same54-xpro nucleo-f767zi nucleo-f429zi nucleo-f207zg; do echo $board && /bin/bash -c "source .murdock; JOBS=4 compile ${test} ${board}:gnu"; done; done;
```
and it seems to fix the problem.

**Comment by MrKevinWeiss** [comment]
Now that #18423 we can let automerge to the work and don't need to abuse the skip compile test label :wink:

**Comment by MrKevinWeiss** [comment]
Also, thank you for such a fast fix!

**Comment by benpicco** [comment]
For some reason CI now fails when compiling `tests/driver_sx1280` because of unused parameters…
I added a commit to fix that as well.

**Comment by maribu** [comment]
`tests/driver_sx1280` also failed due to `netdev_legacy_api` not being selected in KConfig. I added a commit that should fix this.

**Comment by MrKevinWeiss** [comment]
Thanks @maribu

**Comment by MrKevinWeiss** [comment]
That is one down.  Thanks again reacting so fast!

**Pull request merged**
