### PR TITLE
boards/nucleo64*: rename boards to use their ST marketing name

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR renames all nucleo-64 boards to make them use the marketing name used in ST documentation, see http://www.st.com/en/evaluation-tools/stm32-mcu-nucleo.html

For the record, I used a semi-automatic renaming strategy with the following commands:
```
git mv boards/nucleo-l476 boards/nucleo-l476rg
git grep -l 'nucleo-l476' | xargs sed -i 's/nucleo-l476/nucleo-l476rg/g'
git grep -l 'Nucleo-L476' | xargs sed -i 's/Nucleo-L476/Nucleo-L476RG/g'
git add boards/nucleo-l476rg
git commit -m 'boards/nucleo-l476rg: rename to standard st name'
git add examples
git commit -m 'examples: use new nucleo-l476rg name'
git add tests
git commit -m 'tests: use new nucleo-l476rg name'
```

And I have a simple bash script that generates the commands.

### Issues/PRs references

Partially address #8096

### CODE REVIEW

**Comment by kaspar030** [comment]
I think one commit per board is enough...

**Comment by aabadie** [comment]
> I think one commit per board is enough...

done

**Comment by aabadie** [comment]
@vincent-d, rebased to fix conflicts.

**Comment by vincent-d** [comment]
And go!

**Pull request merged**
