### PR TITLE
gnrc_ipv6: copy user flags from old netif headers

### PR DESCRIPTION
**Pull request by miri64**
Upper layers might want to utilize the flags (e.g. to tell 6LoWPAN to elide UDP checksums, as @ReneHerthel is currently working on). This change allows for this by copying non-addressing related flags to the address resolution generated netif header from the user generated netif header.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Thanks :-)!

**Comment by ReneHerthel** [comment]
Nice!

**Comment by PeterKietzmann** [comment]
The change looks ok to me. For easier understanding one could spend a line somewhere [here](https://github.com/RIOT-OS/RIOT/pull/5551/files#diff-74976d45a42eaa063e3561b5fd36f615R412) which explains why the flags are copied. Just reading the current line `great: someone already added a netif_hdr_t we assume it's wrong  to keep it simple` might be misleading. I propose we wait until @ReneHerthel used and ACKed this PR.

**Comment by miri64** [comment]
I hit a little snag, in that multicast assumes the presence of a netif header to be equal to setting an interface in it (which this new use-case would not require). But by just removing this assertion I hit a hard fault, so I need to look into this one a little deeper :-/

**Comment by miri64** [comment]
Fixed it. As a bonus I added the existing flags to the `gnrc_netif_hdr_print()` function. Maybe you want to add your new flag, too @ReneHerthel.

**Comment by ReneHerthel** [comment]
@miri64 Yes, I would add below your if-cases a "GNRC_NETIF_HDR_FLAGS_ELIDED_CHECKSUM"-flag.

**Comment by ReneHerthel** [comment]
@miri64 @PeterKietzmann I tested it and I was able to print the right values (after the flags have been copied) of the netif header I used. So.. here's my ACK.

**Comment by miri64** [comment]
Can't merge because of feature freeze though :/

**Comment by miri64** [comment]
Or what do you say @kYc0o?

**Comment by miri64** [comment]
Squashed.

**Comment by kYc0o** [comment]
Since it's not a bug we should wait for feature-unfreeze.

**Comment by miri64** [comment]
Can't we just branch and backport the remaining PRs to get out of feature-freeze?

**Comment by kYc0o** [comment]
We can try that, but let's see if #2071 gets merged before. How many tests this will affect?

**Comment by miri64** [comment]
This PR in particular? Just the tests involving `gnrc_ipv6` I would say.

**Comment by kYc0o** [comment]
OK so let's merge it and backport it ;)

**Comment by miri64** [comment]
Why? It's not really a bugfix.

**Comment by kYc0o** [comment]
I thought it was since you asked for including it in the release...

**Comment by miri64** [comment]
True, don't know what I was thinking ^^

**Comment by kYc0o** [comment]
It's ok, what's important is that it's merged ;)

**Pull request merged**
