### PR TITLE
Revert "travis: Actually use the build-skip feature"

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
Reverts RIOT-OS/RIOT#2866

It looks like the PR broke Travis.. see if it works here.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Failed exemplary build https://travis-ci.org/RIOT-OS/RIOT/jobs/59891975 of https://travis-ci.org/RIOT-OS/RIOT/builds/59891974
```
$ git clone --depth=50 git://github.com/RIOT-OS/RIOT.git RIOT-OS/RIOT
Cloning into 'RIOT-OS/RIOT'...
remote: Counting objects: 13842, done.
remote: Compressing objects: 100% (6716/6716), done.
remote: Total 13842 (delta 8583), reused 11299 (delta 6819), pack-reused 0
Receiving objects: 100% (13842/13842), 6.14 MiB | 0 bytes/s, done.
Resolving deltas: 100% (8583/8583), done.
Checking connectivity... done.
$ cd RIOT-OS/RIOT
3.27s
$ git fetch origin +refs/pull/2866/merge:
fatal: Couldn't find remote ref refs/pull/2866/merge
The command "eval git fetch origin +refs/pull/2866/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/2866/merge
The command "eval git fetch origin +refs/pull/2866/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/2866/merge
The command "eval git fetch origin +refs/pull/2866/merge:" failed 3 times.
The command "git fetch origin +refs/pull/2866/merge:" failed and exited with 128 during .
Your build has been stopped.
```

**Comment by LudwigOrtmann** [comment]
selfACK & go

**Comment by authmillenon** [comment]
This fail was unrelated.... Look at all the builds AFTER the branch was merged. They were working and twice as fast...

**Comment by authmillenon** [comment]
Please re-revert!

**Comment by LudwigOrtmann** [comment]
Please do it your self and have Travis not failing before merging it.

**Comment by authmillenon** [comment]
Change was not reverted somehow, so it isn't necessary.

**Pull request merged**
