### PR TITLE
sys/shell/commands/gnrc_icmpv6_echo: Fix alignment

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Fix unaligned memory access in `ping6` shell command

### Testing procedure

Run `examples/gnrc_networking` and `ping6` should stll work

### Issues/PRs references

Split out of https://github.com/RIOT-OS/RIOT/pull/14955

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
ACK. No significant timing changes compared to master

master:

```
--- fe80::d827:1dff:fea8:6424 PING statistics ---
1000 packets transmitted, 1000 packets received, 0% packet loss
round-trip min/avg/max = 0.316/0.781/2.449 ms
```

This PR:

```
--- fe80::d827:1dff:fea8:6424 PING statistics ---
1000 packets transmitted, 1000 packets received, 0% packet loss
round-trip min/avg/max = 0.292/0.766/1.465 ms
```

**Comment by miri64** [comment]
(both tested on `native`)

**Comment by maribu** [comment]
One worker had an connectivity issue while fetching sources for a package. Let's see if they persist.

**Comment by maribu** [comment]
Locally the checkout works. Let's try one last time

**Comment by maribu** [comment]
Thanks :-)

**Pull request merged**
