### PR TITLE
ng_at86rf2xx: don't ifdef type definitions

### PR DESCRIPTION
**Pull request by authmillenon**
According to @haukepetersen's https://github.com/RIOT-OS/RIOT/pull/3528#issuecomment-126487189 I opened a PR for that.

### CODE REVIEW

**Comment by bapclenet** [comment]
Doesn't it save some space on the flash to use ifdef? If not, this PR is fine for me.

**Comment by cgundogan** [comment]
Unused type definitions will be stripped away from the resulting binary as
far as I know
Am 31.07.2015 10:42 schrieb "bapclenet" <notifications@github.com>:

**Comment by authmillenon** [comment]
@bapclenet as @cgundogan said: type definitions don't show up in the binary, they are just a hint for the compiler for the position and width of values. So if you don't use them in code (which is still the case here for non-212b radios), they won't show up in the ROM.

**Comment by bapclenet** [comment]
Ok, great
ACK for me then as soon as Travis is ok

**Pull request merged**
