### PR TITLE
boards: initial support for Nucleo f030 board

### PR DESCRIPTION
**Pull request by aabadie**
Yet another PR for adding very basic support to the nucleo f030 board. I only tested a few examples and had failing xtimer tests.
I need some help from someone more knowledgeable with ARM timers.

### CODE REVIEW

**Comment by haukepetersen** [comment]
A quick look in the [datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/a4/5d/0b/0e/87/c4/4d/71/DM00088500.pdf/files/DM00088500.pdf/jcr:content/translations/en.DM00088500.pdf) revealed, that the stm32f030r8 has only 16-bit timers. You need to adjust 
(a) the periph_conf.h -> `TIMER_0_MAX_VALUE  0x0000ffff`
and 
(b) add some custom xtimer configuration: define `XTIMER_WIDTH 16` in the `board.h`

**Comment by aabadie** [comment]
Thanks for spotting this @haukepetersen. I just pushed an update.

**Comment by aabadie** [comment]
Board tested with the recent changes : the xtimer tests are fixed.

**Comment by haukepetersen** [comment]
Untested ACK, once Murdock is happy.

**Comment by aabadie** [comment]
> once Murdock is happy

Seems that Murdock is quite hard to convince :)

**Comment by aabadie** [comment]
@haukepetersen, I could fix remaining Murdock issues.

**Comment by aabadie** [comment]
ping @haukepetersen

**Comment by haukepetersen** [comment]
and go.

**Pull request merged**
