### PR TITLE
Convert remaining Python2 users to Python3

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This replaces the last invocations on Python2 with Python3.

### Testing procedure

Make sure the affected scripts still run.

### CODE REVIEW

**Comment by bergzand** [comment]
There are some python2/python3 workarounds in the files here, does it make sense to remove those too in this PR.

https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/compile_test/compile_test.py#L22
and 
https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/esptool/gen_esp32part.py#L23

can be removed.

https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/compile_test/compile_test.py#L32-L37

Can be simplified to the python3-only.

I suspect the following can also be simplified:
https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/pyterm/setup.py#L3-L6

**Comment by fjmolinas** [comment]
ping @benpicco!

**Comment by benpicco** [comment]
> I suspect the following can also be simplified:
> https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/pyterm/setup.py#L3-L6

Hm, both of these work both on Python2 and Python3.

**Comment by miri64** [comment]
> > I suspect the following can also be simplified:
> > https://github.com/RIOT-OS/RIOT/blob/3b706706d653439f7104548d0a4ab79baeb3bcec/dist/tools/pyterm/setup.py#L3-L6
> 
> Hm, both of these work both on Python2 and Python3.

Yeah, I think this is rather a "having setuptools or distutils installed" thing than a python 2 vs. 3 thing ;-).

**Comment by bergzand** [comment]
> Yeah, I think this is rather a "having setuptools or distutils installed" thing than a python 2 vs. 3 thing ;-).

Ah, okay, sorry for the confusion

**Pull request merged**
