### PR TITLE
cpu/atmega_common: use __temp_reg__

### PR DESCRIPTION
**Pull request by Josar**
Using __temp_reg__ in assebler code to ensure proper working in future.

### CODE REVIEW

**Comment by basilfx** [comment]
Hi @Josar, thanks for your contribution. Can you adopt your commit message according to [this](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures)?

Something like `cpu/atmega_common: use stackpointer with temp_reg`?

**Comment by kaspar030** [comment]
Doesn't compile.

**Comment by Josar** [comment]
I tried locally they all compile. Did you try to compile them locally?
So Question why don't they compile with Murdock?

My Setup:
gcc version 4.9.2 (AVR_8_bit_GNU_Toolchain_3.5.4_1709)
avr-libc 2.0.0

Murdock:
avr-gcc: avr-gcc (GCC) 4.9.2
avr-libc: "1.8.0svn" ("20111229")

Has anyone an idea why it does not compile?

**Comment by Josar** [comment]
"It's a good idea to use tmp_reg and zero_reg instead of r0 or r1, just in case a new compiler version changes the register usage definitions."

https://www.nongnu.org/avr-libc/user-manual/inline_asm.html#asm_code

**Comment by kaspar030** [comment]
> It's a good idea to use tmp_reg and zero_reg instead of r0 or r1, just in case a new compiler version changes the register usage definitions."

thanks!

So what was the issue, why did it not compile before?

**Comment by Josar** [comment]
Is this PR good to go?

**Comment by Josar** [comment]
@kaspar030 @basilfx some more things to do?

**Comment by basilfx** [comment]
I don't have experience with ATmega, so I leave this one up to @kaspar030.

**Pull request merged**
