### PR TITLE
socket_zep: only report size of single datagram

### LINKED ISSUE #19117: socket_zep: fragmentation broken if destination is multicast / ACK_REQ not set
#### Description

When sending datagrams larger than the L2 MTU, 6LoWPAN fragmentation should transparently take care of splitting the datagram into multiple frames and re-assembling them.

While this works well for unicast, multicast datagrams are not correctly re-assembled.

Multicast ping receives no response

#### Steps to reproduce the issue

Start two 6lo nodes.
On `native` this can be done by starting `examples/gnrc_networking` and `examples/gnrc_border_router`. While no border router is needed for this, the build system will take care of connecting everything if the border router example is used.

    make -C examples/gnrc_border_router all term
    make -C examples/gnrc_networking USE_ZEP=1 all term

alternatively you can just spawn two `native` instances of `gnrc_networking` and run the ZEP dispatcher manually:

    sudo dist/tools/zep_dispatch/bin/zep_dispatch -w wpan0 ::1 17754
    make -C examples/gnrc_networking USE_ZEP=1 all term
    make -C examples/gnrc_networking USE_ZEP=1 all term

The `-w wpan0` allows to sniff packets with Wireshark using the virtal `wpan0` interface created by

    sudo modprobe mac802154_hwsim

#### Expected results

 Fragmentation works with both unicast and multicast.

##### Unicast fragmentation works

```
> ping -s 128 fe80::ac46:21cb:1370:fa9a%7
136 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=0 ttl=64 rssi=0 dBm time=0.561 ms
136 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=1 ttl=64 rssi=0 dBm time=1.538 ms
136 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=2 ttl=64 rssi=0 dBm time=1.487 ms

--- fe80::ac46:21cb:1370:fa9a%7 PING statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.561/1.195/1.538 ms
```

#### Multicast ping works

```
> ping ff02::1%7
12 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=0 ttl=64 rssi=0 dBm time=0.730 ms
12 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=1 ttl=64 rssi=0 dBm time=0.768 ms
12 bytes from fe80::ac46:21cb:1370:fa9a%7: icmp_seq=2 ttl=64 rssi=0 dBm time=0.802 ms

--- ff02::1%7 PING statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.730/0.766/0.802 ms
```

#### Multicast fragmentation does not work

```
> ping -s 128 ff02::1%7
ping -s 128 ff02::1%7

--- ff02::1%7 PING statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The use of `ioctl(zepdev->sock_fd, FIONREAD, &size)` would report the number of total bytes available on the socket. This could mean the cumulative sum of bytes of all datagrams, not just a single one.

Instead, use `recv(zepdev->sock_fd, &hdr, sizeof(hdr), MSG_TRUNC | MSG_PEEK)` to only read the ZEP header (without consuming the datagram) to get the real size of the ZEP message.

This prevents accidental concatenation of two ZEP packets into on, which with 6lo fragmentation, would cause the 2nd fragment to be lost as it is read together with the first fragment, but as part of the payload. 

### Testing procedure

Fragmented multicast datagrams should work now.

```
> ping -s 128 ff02::1
136 bytes from fe80::7c5e:5802:4449:e1b3%7: icmp_seq=0 ttl=64 rssi=0 dBm time=1.515 ms
136 bytes from fe80::7c5e:5802:4449:e1b3%7: icmp_seq=1 ttl=64 rssi=0 dBm time=1.644 ms
136 bytes from fe80::7c5e:5802:4449:e1b3%7: icmp_seq=2 ttl=64 rssi=0 dBm time=1.613 ms

--- ff02::1 PING statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 1.515/1.590/1.644 ms
```

### Issues/PRs references

fixes #19117

### CODE REVIEW

**Comment by maribu** [comment]
bors merge

**Comment by fabian18** [comment]
A: 
```
> ping -s 128 ff02::1
ping -s 128 ff02::1
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::read: reading up to 116 bytes into 0x809e4f8
socket_zep::read: got 150/150 bytes
socket_zep::send_ack: seq_no: 170
socket_zep::_socket_isr: bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::read: reading up to 116 bytes into 0x809e510
socket_zep::read: got 150/150 bytes
socket_zep::send_ack: seq_no: 170
socket_zep::_socket_isr: bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::len 118 bytes on 8
socket_zep::read: reading up to 116 bytes into 0x809e510
socket_zep::read: got 150/150 bytes
socket_zep::send_ack: seq_no: 170
socket_zep::_socket_isr: bytes on 8
socket_zep::len 76 bytes on 8
socket_zep::len 76 bytes on 8
socket_zep::read: reading up to 74 bytes into 0x809e510
socket_zep::read: got 108/108 bytes
socket_zep::send_ack: seq_no: 172
136 bytes from fe80::a47b:d9:d217:fbf9%7: icmp_seq=2 ttl=64 rssi=0 dBm time=8.281 ms
socket_zep::_socket_isr: bytes on 8
socket_zep::len 76 bytes on 8
socket_zep::len 76 bytes on 8
socket_zep::read: reading up to 74 bytes into 0x809e4f8
socket_zep::read: got 108/108 bytes
socket_zep::send_ack: seq_no: 172

--- ff02::1 PING statistics ---
3 packets transmitted, 1 packets received, 66% packet loss
round-trip min/avg/max = 8.281/8.281/8.281 ms
> ping -s 128 ff02::1
ping -s 128 ff02::1
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)
socket_zep::write(113 bytes)
socket_zep::request_transmit(145 bytes)
socket_zep::write(70 bytes)
socket_zep::request_transmit(102 bytes)

--- ff02::1 PING statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
> socket_zep::write(45 bytes)
socket_zep::request_transmit(77 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::read: reading up to 43 bytes into 0x809e4f8
socket_zep::read: got 77/77 bytes
```

B:
```
socket_zep::len 113 bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 111 bytes into 0x809e4f8
socket_zep::read: got -1/145 bytes
socket_zep::_socket_isr: bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::read: reading up to 111 bytes into 0x809e4f8
socket_zep::_socket_isr: bytes on 8
socket_zep::read: got 145/145 bytes
socket_zep::_socket_isr: bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::read: reading up to 111 bytes into 0x809e510
socket_zep::read: got 145/145 bytes
socket_zep::_socket_isr: bytes on 8
socket_zep::len 70 bytes on 8
socket_zep::len 70 bytes on 8
socket_zep::read: reading up to 68 bytes into 0x809e528
socket_zep::read: got 102/102 bytes
socket_zep::write(118 bytes)
socket_zep::request_transmit(150 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 0 bytes into (nil)
socket_zep::read: got 37/34 bytes
socket_zep::request_transmit(150 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 0 bytes into (nil)
socket_zep::read: got 37/34 bytes
socket_zep::request_transmit(150 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 3 bytes into 0x809e159
socket_zep::read: got 37/37 bytes
socket_zep::dst_not_me: got ACK
socket_zep::write(76 bytes)
socket_zep::request_transmit(108 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 0 bytes into (nil)
socket_zep::read: got 37/34 bytes
socket_zep::request_transmit(108 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::read: reading up to 3 bytes into 0x809e159
socket_zep::read: got 37/37 bytes
socket_zep::dst_not_me: got ACK
socket_zep::_socket_isr: bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::len: error reading FIONREAD: Resource temporarily unavailablesocket_zep::_socket_isr: bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::read: reading up to 111 bytes into 0x809e4f8
socket_zep::read: got 145/145 bytes
socket_zep::_socket_isr: bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::len 113 bytes on 8
socket_zep::read: reading up to 111 bytes into 0x809e510
socket_zep::read: got 145/145 bytes
socket_zep::_socket_isr: bytes on 8
socket_zep::_socket_isr: bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::read: reading up to 43 bytes into 0x809e4f8
socket_zep::read: got 77/77 bytes
socket_zep::write(45 bytes)
socket_zep::request_transmit(77 bytes)
socket_zep::_socket_isr: bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::len 45 bytes on 8
socket_zep::read: reading up to 43 bytes into 0x809e4f8
socket_zep::read: got 77/77 bytes
socket_zep::write(45 bytes)
socket_zep::request_transmit(77 bytes)
```
Hmm, not really working for me. Might be an Arch issue.
Tested with two `native` `gnrc_metworking` as shown in the issue.

**Comment by benpicco** [comment]
Uh turns out we end up here: https://github.com/RIOT-OS/RIOT/blob/master/cpu/native/socket_zep/socket_zep.c#L244

I guess discarding the frame if the radio is not in RX mode is not ideal, although I wonder why it's not in RX mode in the first place.

**Comment by benpicco** [comment]
913d72cb99e7b3ad5d187caeafa5fb7c905ab5c1 fixes it, but it may be against the radio HAL interface.

The question is why is the radio not in RX mode?

**Comment by fabian18** [comment]
it works now
```
> ping -s 128 ff02::2
ping -s 128 ff02::2
136 bytes from fe80::b8b0:7191:5734:365e%7: icmp_seq=0 ttl=64 rssi=0 dBm time=4.841 ms
136 bytes from fe80::b8b0:7191:5734:365e%7: icmp_seq=1 ttl=64 rssi=0 dBm time=0.816 ms
136 bytes from fe80::b8b0:7191:5734:365e%7: icmp_seq=2 ttl=64 rssi=0 dBm time=0.885 ms
```

**Comment by kaspar030** [comment]
What's the state here? I'm waiting on this for the next RC. @jia200x could you take a look?

**Comment by jia200x** [comment]
Does this still guarantee that each received frame triggers its corresponding RX Done event? If so, everything should be fine.

**Comment by kaspar030** [comment]
> Does this still guarantee that each received frame triggers its corresponding RX Done event? If so, everything should be fine.

Looks like the RX Done indication might be called more often, not less, so this should be good?

**Review by maribu — APPROVED** [review]

**Comment by miri64** [comment]
bors merge

**Comment by jia200x** [comment]
> 

It should be fine. As per Radio HAL documentation, the user of the HAL must call `ieee802154_radio_set_idle` before calling `ieee802154_radio_read`.

**Comment by benpicco** [comment]
Hm maybe `socket_zep` is sending too fast?

I had hoped `socket_zep` would serve as a good automatic test for the SubMAC, so I don't like that it needs some hacks now to not drop frames - the "RX off" state was simulated to be more like a real radio, removing it feels a bit like cheating.

**Comment by kaspar030** [comment]
bors cancel
bors merge

**Pull request merged**
