### PR TITLE
cpu/stm32f4: Fix SPI baud rate control settings

### PR DESCRIPTION
**Pull request by fnack**
The baudrate control for the SPIs are currently not set correctly during initialization. The SPIs on the stm32f4xx series run either on the APB1 or the APB2 bus which are clocked differently (APB1=42MHz, APB2=84MHz). Therefore during spi initialization we need to distinguish between the two possible clock rates to compute our prescaler.

Additionally, the previously configured prescalers were wrong as well and didn't lead to the desired speed on either bus. Please refer to baud rate control bits in the control register at page 905 of the [reference manual](www.st.com/web/en/resource/technical/document/reference_manual/DM00031020.pdf) where f_pclk is the clock speed of the used bus.

### CODE REVIEW

**Comment by fnack** [comment]
Would be great if someone (@PeterKietzmann, @haukepetersen) could test this with a logic analyzer for one SPI on APB1 and one on APB2.

**Comment by PeterKietzmann** [comment]
Whoops, that must have been my fault. I'll test this!

**Comment by PeterKietzmann** [comment]
I tested the speed values for both ports. Now they're correct. Nice you found this. ACK

**Comment by haukepetersen** [comment]
ACK also from my side -> and go.

**Comment by PeterKietzmann** [comment]
OK let's merge this

**Pull request merged**
