### PR TITLE
llvm 11 compile fixes

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR bundles some llvm changes necessary to build with llvm 11.

### CODE REVIEW

**Comment by maribu** [comment]
Maybe just add `-Wno-implicit-int-float-conversion` to the `utensor` package to fix [this issue](https://ci.riot-os.org/RIOT-OS/RIOT/15595/d422a9a10fbf67d9164571584833e4c83668217b/output/compile/tests/pkg_utensor/nucleo-f401re:llvm.txt)?

**Comment by maribu** [comment]
And maybe `-Wno-c99-designator` to all of C++ to fix [this](https://ci.riot-os.org/RIOT-OS/RIOT/15595/d422a9a10fbf67d9164571584833e4c83668217b/output/compile/tests/sys_arduino/nucleo-f401re:llvm.txt)? I don't see a reason to not use C designators also in C++. They make the code more readable.

**Comment by benpicco** [comment]
Murdock is not happy yet.

**Comment by maribu** [comment]
Maybe we should split out the thread size configuration into a separate header, so that `cpu_conf.h` doesn't need to be included via `thread.h`?

IMO, C++ code should never see any low level headers and we just provide C++ compatibility for the public API. That way, C++ becomes quite a bit less pain in the ass to maintain.

**Comment by kaspar030** [comment]
> Maybe we should split out the thread size configuration into a separate header, so that `cpu_conf.h` doesn't need to be included via `thread.h`?

Yes! I have a commit somewhere doing that. I'm on holidays this week, will dig out when back.

**Comment by maribu** [comment]
> > Maybe we should split out the thread size configuration into a separate header, so that `cpu_conf.h` doesn't need to be included via `thread.h`?
> 
> Yes! I have a commit somewhere doing that. I'm on holidays this week, will dig out when back.

I now remembered why I suggested this: The issue is that `cpu_conf.h` is including the vendor files, which are not compatible with `clang++`. But C++ code needs to include `thread.h`. So splitting this out would fix the first compilation error posted by murdock. Maybe you could PR that commit or add it here?

**Comment by benpicco** [comment]
> I now remembered why I suggested this: The issue is that `cpu_conf.h` is including the vendor files

This has bitten me on multiple occasions already.
A solution would be to split this so that vendor files are only included by cpu specific code, not by common/application code - but this turned out to be a larger yak to shave than I anticipated.

**Comment by kaspar030** [comment]
> Maybe you could PR that commit or add it here?

I found that commit: https://github.com/RIOT-OS/RIOT/pull/16024

That PR is only moving the code so far. As @benpicco stated, dropping the cpu_conf.h includes is a bit more work.

**Comment by kaspar030** [comment]
> dropping the cpu_conf.h includes is a bit more work.

... like, the inlined thread_yield_higher() in thread_arch.h also depends on cpu_conf.h ...

**Comment by fjmolinas** [comment]
Is there a fix for:

```
/data/riotbuild/riotbase/cpu/sam0_common/include/vendor/samr21/include/component/ac.h:226:18: error: anonymous bit-field cannot have qualifiers
    __I uint8_t  :2;               /*!< bit:  2.. 3  Reserved                           */
                 ^
```

**Comment by maribu** [comment]
> Is there a fix for:
> 
> ```
> /data/riotbuild/riotbase/cpu/sam0_common/include/vendor/samr21/include/component/ac.h:226:18: error: anonymous bit-field cannot have qualifiers
>     __I uint8_t  :2;               /*!< bit:  2.. 3  Reserved                           */
>                  ^
> ```

Yes, not including the system headers from C++ :-)

Sadly, this is not so trivial. It would be best if we could avoid including vendor files from "public" header files (directly or indirectly) altogether, so that only the C source in `/cpu/` would ever see the vendor files. This would also avoid a lot of name collisions between preprocessor macros with application level C code, which can be a pain in the ass. But as said, this is a bit of work.

**Comment by kaspar030** [comment]
I'm not going to work on this anymore.

**Comment by maribu** [comment]
Oh, it has been fixed anyway in the meantime

**Comment by mguetschow** [comment]
But it seems murdock is still not building some boards with llvm: https://github.com/RIOT-OS/RIOT/blob/master/.murdock#L40

**Comment by maribu** [comment]
> But it seems murdock is still not building some boards with llvm: https://github.com/RIOT-OS/RIOT/blob/master/.murdock#L40

It has been re-enabled in 52cf2b46c3ee607e43e824d0f9f8ef1a10a9c914 - I forgot to update the comment above, though. That only a subset of the boards are build with LLVM is intentional to avoid increasing CI time by factor 2. I dropped the obsolete comment and added a bit of doc in https://github.com/RIOT-OS/RIOT/pull/20482

**Pull request closed without merging**
