### PR TITLE
tools:pyterm fix deprecation warnings

### PR DESCRIPTION
**Pull request by SemjonKerner**
This PR fixes deprecation warnings for warn and SafeConfigParser as mentioned in issue #9827

### CODE REVIEW

**Comment by SemjonKerner** [comment]
@aabadie already squashed, cause i'll be away until next week.

**Comment by miri64** [comment]
Also please prefix the commit message appropriately `pyterm:`.

**Comment by aabadie** [comment]
Murdock is stuck. @kaspar030 any idea on what's happening ?

**Comment by aabadie** [comment]
CI is green, let's merge.

**Pull request merged**
