### PR TITLE
sys/shell: add RIOT_VERSION_EXTRA output

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The `version` command currently only prints the RIOT version, but the application might also have it's own version if it is maintained in a separate repo.

When there is a shared test installation it can also be useful to know who last flashed the board, does it still contain the state you left it with or did someone else flash something new in the meantime?

This PR allows to define an extra string by setting a new `RIOT_VERSION_EXTRA` variable that will be output as part of the version command.

### Testing procedure

Add to your `Makefile` e.g.

```
RIOT_VERSION_EXTRA += v1.33.7
RIOT_VERSION_EXTRA += flashed by $(shell whoami)
```

Now `version` will output

```
2024-02-05 14:17:48,245 # > version
2024-02-05 14:17:48,246 # 2024.04-devel-127-g8bf613
2024-02-05 14:17:48,246 # v1.33.7 flashed by benpicco
```

### CODE REVIEW

**Review by kfessel — COMMENTED** [review]
good idea;

but won't the command line (CFLAGS) defined macro interfere with Kconfig  ( which we still might use for configuration?

or is that intentional?

**Comment by kfessel** [comment]
Why do you add a CONFIG_ prefix (instead of just using RIOT_VERSION_EXTRA)

**Comment by benpicco** [comment]
I thought that's the new convention for overwritable config variables.
But I can also drop the prefix if you prefer that.

**Comment by kaspar030** [comment]
> I thought that's the new convention for overwritable config variables.

I thought the same. Maybe we need to write that down somewhere.

**Comment by maribu** [comment]
The benefit of consistently using the `CONFIG_` prefix is that

a) it is clear that it is user overwritable
b) it can be exposed to KConfig later on

**Review by kfessel — APPROVED** [review]

**Comment by kfessel** [comment]
You might also want to add this to: 
```
#ifndef CONFIG_BOOT_MSG_STRING
#define CONFIG_BOOT_MSG_STRING "main(): This is RIOT! (Version: " \
    RIOT_VERSION ")"
#endif
```
in `core/init.c`

**Comment by benpicco** [comment]
There is already `CONFIG_BOOT_MSG_STRING` for that, let's not clutter it too much.

**Pull request merged**
