### PR TITLE
release-tests: fix artifact naming and steps cleanup for matrix build

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Found this while helping @jia200x to trouble should a failed run of the release tests: When I moved the release tests to the matrix-based strategy, I forgot to rename the artifacts, so the generated XML and HTML files now both are named after `native`. This fixes that.

### Testing procedure
I guess one has to run the release tests :-/. But it _should_ also work when you abort them, as artifact uploading is always executed and the new names should at least be seen. 

### Issues/PRs references
Follow-up on #15637.

### CODE REVIEW

**Comment by miri64** [comment]
Ping @jia200x or @aabadie?

**Comment by miri64** [comment]
By an offline suggestion by @jia200x I restricted the tests to only run to short tasks, so I can run the workflow in my fork for testing. Will provide a link for that, once that is done.

**Comment by miri64** [comment]
Ok, the output is broken https://github.com/miri64/RIOT/actions/runs/496246257. the `MARK` part of the name is missing. Will investigate what is happening.

**Comment by miri64** [comment]
Found it! I also saw, that `tapsetup` is run also for the IoT-LAB tests. While it shouldn't do any harm to do so, I added a commit to skip that step when running the IoT-LAB tests. Hope it is alright to piggy-back this in this follow-up PR for the matrix configuration. Action with a working run can be found here: https://github.com/miri64/RIOT/actions/runs/496291550

**Comment by jia200x** [comment]
it works now :)

**Review by jia200x — APPROVED** [review]
ACK

**Comment by jia200x** [comment]
could you remove the bogus commit and squash? :)

**Comment by miri64** [comment]
Squashed and removed bogus commits.

**Comment by miri64** [comment]
Also, for some reason 629d3cd39d26386f00f97afa993a4edb262bcfce hid in here (it wasn't shown since it is already part of master). I removed that as well, in case you are wondering why the `uncrustify` script was touched in my force push.

**Comment by miri64** [comment]
Backport provided in #15816

**Pull request merged**
