### PR TITLE
cpu/cc2538: reworked GPIO driver

### PR DESCRIPTION
**Pull request by haukepetersen**
The last GPIO driver target to remodeling.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Your optimization looks great! Unfortunately there are some open issues. I've tested on a remote-reva and I couldn't get the pins on port D running as output. You can easily check that when using LEDs which are all connected to port D. In addition I tried the button pin as external interrupt source as well as usual input pin, without success.

**Comment by haukepetersen** [comment]
Thanks for testing. I forgot to mention above: I did this completely blind, as I don't have any cc2538 hardware at hand. 

@PeterKietzmann would you mind to look into this and tell me what I have to fix?

**Comment by alignan** [comment]
@PeterKietzmann I'll test tomorrow

**Comment by PeterKietzmann** [comment]
Great thanks a lot!

**Comment by alignan** [comment]
Had a quick glance, the addresses seems off, `init_out 3 4` (PD4) uses a wrong address value `0x400DB004` instead of `0x400DC004` at the `GPIO_PIN` macro.  To check I just replaced `pin` for the proper address value at `gpio_init`, `gpio_set` and `gpio_clear` with the `remote-revb` and the red LED was toggling OK.  I will take a look tomorrow as today I ran out of time :smile:

**Comment by haukepetersen** [comment]
Thanks for testing! I will also look into the address computation once more, might be that I just misscounted some bits...

**Comment by haukepetersen** [comment]
ok, found the problem - I did some naive error when computing the right register address which lead to wrong port base addresses...

@alignan would you mind to give this a quick test again? Thanks!

**Comment by alignan** [comment]
@haukepetersen sure!

**Comment by alignan** [comment]
It is working now, thanks for the quick fix!

**Comment by miri64** [comment]
Murdock is building for ~3h now... I think @kaspar030's to Murdock optimization efforts broke something :-/

**Comment by kYc0o** [comment]
All green -> go!

**Pull request merged**
