### PR TITLE
cpu: cortexm_common: fix compile warning

### PR DESCRIPTION
**Pull request by kaspar030**
Release branch version of #5727.

### CODE REVIEW

**Comment by mali** [comment]
+1

**Comment by BytesGalore** [comment]
@haukepetersen any reason to not merge the initializations?

**Comment by cgundogan** [comment]
ACK

**Comment by cgundogan** [comment]
I was unaware of the discussions in #5727 but I cannot revoke my `review`. NACK for now until #5727 is resolved.

**Comment by miri64** [comment]
#5727 was merged, so can your NACK be revoked @cgundogan (and the PR have another ACK since the commit was updated)?

**Comment by miri64** [comment]
Oops this is a backport for #5727! Than this should be merged ASAP.

**Comment by cgundogan** [comment]
ACK

**Comment by cgundogan** [comment]
Murdock is happy => go

**Comment by kaspar030** [comment]
I guess this was not so important after all. ;)

**Pull request merged**
