### PR TITLE
gnrc_uhcp: use actually advertised prefix length

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This makes the UHCP client to use the actually advertised prefix length instead of assuming statically `/64`.

### Testing procedure
Set environment variable `IPV6_PREFIX` to something else than a 64-bit prefix e.g.

```sh
IPV6_PREFIX=2001:db8::/62 make -C examples/gnrc_border_router/ flash term
```

On master the configured prefix will be a 64-bit prefix no matter what. With this change, it will be configured as expected:

```
uhcp_client(): sending REQ...
got packet from fe80::e0bc:7dff:fecb:f54f port 57685
uhcp: push from fe80::e0bc:7dff:fecb:f54f:57685 prefix=2001:db8::/62
gnrc_uhcpc: uhcp_handle_prefix(): got same prefix again
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8::840c:77ec:2333:6278/62
nib prefix
nib prefix
2001:db8::/62 dev #6
```

### Issues/PRs references
None (used to debug https://github.com/RIOT-OS/RIOT/pull/13485#issuecomment-603480280)

### CODE REVIEW

**Comment by kaspar030** [comment]
Looks ok and straight forward. Only thing I see is that as is, only the prefix is compared to determine whether it is the same as already configured, but it should also compare old and new prefix length.

**Comment by miri64** [comment]
> Looks ok and straight forward. Only thing I see is that as is, only the prefix is compared to determine whether it is the same as already configured, but it should also compare old and new prefix length.

Why did I know that this won't be a simple look-and-merge PR :-P

**Comment by miri64** [comment]
> […] only the prefix is compared to determine whether it is the same as already configured, but it should also compare old and new prefix length.

Fixed. Also fixed *how* the prefix is compared (only check the prefix, not the whole address).

**Comment by kaspar030** [comment]
Code looks good. Please squash!

**Comment by miri64** [comment]
Squashed.

**Pull request merged**
