### PR TITLE
periph/i2c: handle i2c register write/read helper function correctly in big endian

### LINKED ISSUE #11544: i2c_read_regs / i2c_write_regs and endianess
#### Description
I'm working on a 8kb EEPROM connected via I2C to a SAML21. I'm having strange wrap around issues on memory writing. After some debug my feeling is that the `i2c_write_regs` and `i2c_read_regs` functions do not take into account the endianess of the CPU and do work only with big endian code.

Example trying to write to register 0x10 the value 1:
`   
i2c_write_reg(I2C_DEV(0), 0x50, 0x10, 1, I2C_REG16);
`
Putting some debug prints I see that the write request will generate an address on the bus:
```
0x10
0x0
```
While I would expect the MSB to come first (by specs, but please correct me if I'm wrong as I'm not very used to I2C):
```
0x0
0x10
```
Looking at `i2c_write_regs` the register is received as an `uint16_t` which is then passed down to `i2c_write_bytes` that gets it as `const void *` that is then written physicall in a loop as `const uint8_t *`.
Therefore in little endian machines the LSB will come first, while for big endian machines MSB will come first (as it should).

I think the two regs function should take the endianess into account and always pass the registers data with MSB first to the underneath functions. I believe this should be the place to do it, so the calls to the CPU specific functions underneath already always receive the data as it should be written.

I would gladly do a PR once I get confirmation that I'm not seeing something wrong. Worst case I would suppose this should be documented if it is correct as it is.

Swapping beforehand the register data in my application seems to solve all the troubles.

#### Steps to reproduce the issue
Write some i2c registers using `i2c_write_regs` and see if the data gets written where it should.

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by fedepell**
### Contribution description
In RIOT I2C we have helper functions to read/write I2C devices (mostly EEPROMS) that need a 16-bit addressing. The standard does not dictate the endianess of this addressing but all the examples found are big-endian. The current code doesn't correctly force a translation to big-endian, therefore it will not work on little-endian architectures.
This PR fixes this by making sure the 16-bit address is always converted into big-endian.

### Testing procedure
The test in `tests/periph_i2c` can be used, specifiying to `i2c_read_reg` the flag value of 2 (equivalent to `I2C_REG16` value)

### Issues/PRs references
Fixed #11544 . Discussion on implementation on that Issue.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Is it possible to get a link or reference to a device (anything) that would need little endian 16 bit registers (I could only find EEPROMs that use big endian)

**Comment by MrKevinWeiss** [comment]
Though it looks like we do need big endian...

**Comment by fedepell** [comment]
Indeed all the devices I used (EEPROMS) do use big endian. The point was mostly that the current implementation was not actually safe (as it wasn't converting to either one, just assuming it was running on big-endian, which was not my case) I had troubles and while assuring that the existing one is really big-endian I also added the little-endian should it be needed.

**Comment by MrKevinWeiss** [comment]
I am currently searching for some little endian devices and reading the issue.  It would be a bit better if it was only big.  The less complexity the better.  I do agree that we need at least big endian though.

**Comment by MrKevinWeiss** [comment]
Device | 8 bit reg | 16 big | 16 little |
-|-|-|-
M24C64||x|
24AA512||x|
ADS1015|x||

_feel free to add if you evaluate, I just need one little endian_

The ADS1015 and the [device dependant](https://www.raspberrypi.org/forums/viewtopic.php?t=122923) statement was not what we mean by register, register to us is the address pointer in this case (which for this device is actually only two bits) the size of the control register (register address 0x01) is 16 bits but that just means that one would have to write two bytes 
`i2c_write_regs 0x68 0x01 0x00 0x12 0x34`
`i2c_write_regs <dev_addr> <reg> <flag> [data0 data1]`

When we are talking about read and write registers we need to be clear what that means
First it is only a helper function that sits on top of the i2c spec
Second, in many but not all cases it can be achieved through basic calls (some issues in the stm devices since flags need to be set before completion and everything is blocking...)
Third, what we mean by read register is
`start_bit-address-write_bit-ack-reg-ack-[optional second byte for reg]-ack-[stop_bit]-start_bit-address-read_bit-ack-slave_data-ack-[slave_data_n]-stop_bit`
and for write it should be
`start_bit-address-write_bit-ack-reg-ack-[optional second byte for reg]-ack-master_data-ack-[master_data_n]-nack-stop_bit`
probably a better way to say this info.

Also sorry I didn't chime in when the issue was raised.  Either someone fine a single device that would need read_reg or just do big endian (which should be simple and less code size).

**Comment by fedepell** [comment]
@MrKevinWeiss thanks for investigating this! Indeed I was checking more eeproms and all have a big-endian addressing (when needed, so for ones that need 16bit). 
Therefore I agree, until (if ever) we have a case for little-endian we can pull this away not to add useless bytes and more code to maintain.

I will now fix the PR to just adress the fact to have it big endian (this I think is a must as it breaks otherwise on my LE) and correct the PR title as well. Hope it will be fine!

**Comment by fedepell** [comment]
Force pushed now and corrected the issue details, hope it is better!

Thanks!
F.

**Comment by MrKevinWeiss** [comment]
Actually according to the commit message it is for all archs but the cpu/efm32/periph/i2c.c uses its own implementation, maybe just fix that one as well.

The nrf also uses its own but they are not supported so I think that is OK.

**Comment by fedepell** [comment]
@MrKevinWeiss many thanks for ACK and testing!

I committed now the change also for the efm32. I also tested the change on a stk3700 that uses it and looks fine! Previously I tested the change on a SAML21.

**Pull request merged**
