### PR TITLE
cpu/sam3: cleaned up UART driver

### PR DESCRIPTION
**Pull request by haukepetersen**
~~based on #4114~~

Cleaned up/optimized the UART driver for the `sam3x` and adjusted the `arduino-due` and the `udoo` boards

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased

**Comment by A-Paul** [comment]
Is a HW runtime check advised?

**Comment by PeterKietzmann** [comment]
@A-Paul yes please. The [periph_uart](https://github.com/RIOT-OS/RIOT/tree/master/tests/periph_uart) test might help you

**Comment by A-Paul** [comment]
Tests on *arduino-due*  with UART{1,2,3}  and {9600,115200} baud showed no issues.

**Comment by A-Paul** [comment]
@haukepetersen  ACK.

**Pull request merged**
