### PR TITLE
sys/net/gnrc: add gnrc_tx_sync for gnrc_sixlowpan_frag_sfr

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Implement TX synchronization for `gnrc_sixlowpan_frag_sfr` and also extend the corresponding test.

### Testing procedure

`tests/gnrc_tx_sync` should pass

### Issues/PRs references

None

### CODE REVIEW

**Comment by miri64** [comment]
Question for understanding: Why does the first fragment send function doesn't require adaptation?

**Comment by maribu** [comment]
For all fragments except for the last the idea is to strip off the TX sync snip prior to the fragmentation and reattach it afterwards. If the packet gets dropped outside of the fragmentation code for whatever reason, the TX snip will also be freed which unblocks the thread waiting for the transmission attempt to conclude.

For the very last fragment, the tx snip will be attached to the fragment to send and no longer re-attached to the packet. Once the last fragment to send is freed by the network device (that is, after TX of that is completed), which triggers the unblocking of the thread syncing with TX.

Since fragmentation is only done if the packet doesn't fit into a single frame, we know that the first fragment cannot also be the last. And only the last fragment needs the special treatment.

**Comment by maribu** [comment]
To be honest: I'm not entirely sure if this approach is indeed the most elegant or efficient way to do this. I didn't dive deeply into the code and only have a rough idea how the fragmentation works. From that, the approach taken here seemed to me to be the most straight forward way to implement this feature.

I think it would totally be possible to restructure the code to keep the tx sync snip in the packet and only strip it of for the very last fragment and attach it there. But I'm not certain enough that this might not play well with the code copying the data from the packet to the fragments, if there is now a tx sync snip at the end of it. (The TX sync snip reports a data length of zero in the hope that this prevents its contents to be ever send out - which might actually be good enough here.)

**Comment by miri64** [comment]
> Since fragmentation is only done if the packet doesn't fit into a single frame, we know that the first fragment cannot also be the last. And only the last fragment needs the special treatment.

I know I go into very theoretical territory with this (and talking about things that are not even implemented), but do we actually know that? For classic fragmentation granted, but one could argue, that a user also wants the benefits of fragment recovery for a single frame. I can imagine use cases where end-to-end (or end-to-gateway) ACKs for all 6LoWPAN data might be desirable.

**Comment by miri64** [comment]
Thanks for addressing my theoretical worries :sweat_smile:

**Comment by maribu** [comment]
This is still very much needed, I will try to give this more priority

**Review by miri64 — APPROVED** [review]
Code looks good to me, normal operation is not affected by this change and I trust your testing. ACK

**Comment by miri64** [comment]
Please squash.

**Comment by maribu** [comment]
Thanks (:

**Pull request merged**
