### PR TITLE
core/panic: don't use LOG_ functions in panic handler

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The LOG_ functions can be overwritten to log e.g. to network or file system.
Calling them in the panic handler will just lead to another panic, obfuscating the original source of the panic.

### CODE REVIEW

**Comment by chrysn** [comment]
For clarification: How is LOG_ more reliable than stdout? Just like logging can be redirected, stdio can be, eg. by going through BLE or to the VFS, and that'd just run into the same issue.

**Comment by Teufelchen1** [comment]
@benpicco ^

**Comment by kaspar030** [comment]
For reference, this creates a hard dependency on libc stdio formatting code. `LOG_` was used here in the first place to remove that dependency (so `tests/minimal` gets smaller).

**Comment by benpicco** [comment]
I'm not so concerned about minimal binary size with `DEVELHELP=1`

I agree that stdio can have the same problem, but we could introduce a flag field to `stdio_provider_t` so that we could skip high-level stdio implementations in case of panic.

That could also solve the issue brought up in https://github.com/RIOT-OS/RIOT/pull/20364#issuecomment-1961328409

**Comment by benpicco** [comment]
That's just by chance - any module using stdio would void that again - lets rather solve the problem properly by turning all calls to `printf()` into a no-op when `stdio_null` is used.
#20872

**Pull request merged**
