### PR TITLE
makefiles/dependencies_debug.inc.mk: add CPU_ARCH

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This PR adds `CPU_ARCH` to dependency debug variables. This variables is used for dependency resolution and was missing from the script. Pointed out offline by @cladmi.

### Testing procedure

`BOARD=nucleo-l152re make -C examples/hello-world/ dependency-debug `
`cat examples/hello-world/dependencies_info_nucleo-l152re `
```
BOARD = nucleo-l152re
CPU = stm32l1
CPU_MODEL = stm32l152re
CPU_FAM = stm32l1
CPU_ARCH = cortex-m3
FEATURES_PROVIDED = periph_adc periph_dac periph_dma periph_i2c periph_pwm periph_rtc periph_spi periph_spi_gpio_mode periph_timer periph_uart riotboot arduino cortexm_mpu periph_eeprom periph_flashpage periph_flashpage_raw periph_cpuid periph_gpio periph_gpio_irq puf_sram periph_uart_modecfg periph_wdt arch_32bit arch_arm arch_cortexm periph_pm cpp cpu_check_address ssp
_FEATURES_PROVIDED_SORTED = arch_32bit arch_arm arch_cortexm arduino cortexm_mpu cpp cpu_check_address periph_adc periph_cpuid periph_dac periph_dma periph_eeprom periph_flashpage periph_flashpage_raw periph_gpio periph_gpio_irq periph_i2c periph_pm periph_pwm periph_rtc periph_spi periph_spi_gpio_mode periph_timer periph_uart periph_uart_modecfg periph_wdt puf_sram riotboot ssp
FEATURES_REQUIRED = periph_uart arch_32bit arch_arm arch_cortexm periph_uart arch_32bit arch_arm arch_cortexm
_FEATURES_REQUIRED_SORTED = arch_32bit arch_arm arch_cortexm periph_uart
FEATURES_OPTIONAL = periph_gpio periph_pm periph_gpio periph_pm
FEATURES_USED = arch_32bit arch_arm arch_cortexm periph_gpio periph_pm periph_uart
FEATURES_MISSING =
FEATURES_CONFLICT =
FEATURES_CONFLICTING =
USEMODULE = auto_init board boards_common_nucleo core core_init core_msg core_panic cortexm_common cortexm_common_periph cpu newlib newlib_nano newlib_syscalls_default periph periph_common periph_gpio periph_init periph_init_common periph_init_gpio periph_init_init periph_init_pm periph_init_uart periph_pm periph_uart pm_layered stdio_uart stm32_common stm32_common_periph sys
DEFAULT_MODULE = auto_init board core core_init core_msg core_panic cpu periph_init periph_init_common periph_init_gpio periph_init_init periph_init_pm periph_init_uart sys
DISABLE_MODULE = stdio_rtt stdio_cdc_acm

```

### CODE REVIEW

**Comment by cladmi** [comment]
You should also run the dependency-debug commands on several boards, I think some do not have a `CPU_ARCH`, and this line would also need to be modified:

https://github.com/RIOT-OS/RIOT/blob/d9b9426a8683234f296bb6cf4bac1a7163dee2dd/makefiles/info-global.inc.mk#L30-L35

**Comment by fjmolinas** [comment]
Weird murdock failure fot this:

```
	'make doc' exited with non-zero code (2)
	make: Entering directory '/tmp/dwq.0.4920613271404861/ea07dcc336b52cac3e136181e0c20e00'
	"make" -BC doc/doxygen
	make[1]: Entering directory '/tmp/dwq.0.4920613271404861/ea07dcc336b52cac3e136181e0c20e00/doc/doxygen'
	( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
	sh: 1: latex: not found
	error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
	sh: 1: dvips: not found
	error: Problems running dvips. Check your installation!
	Killed
	Makefile:18: recipe for target 'html' failed
	make[1]: *** [html] Error 137
	make[1]: Leaving directory '/tmp/dwq.0.4920613271404861/ea07dcc336b52cac3e136181e0c20e00/doc/doxygen'
	Makefile:10: recipe for target 'doc' failed
	make: *** [doc] Error 2
	make: Leaving directory '/tmp/dwq.0.4920613271404861/ea07dcc336b52cac3e136181e0c20e00'
```

**Comment by aabadie** [comment]
I think it's unrelated. I suspect there's a setup issue on one of the workers.

**Comment by fjmolinas** [comment]
> You should also run the dependency-debug commands on several boards, I think some do not have a CPU_ARCH, and this line would also need to be modified:

I had tested on native, and It just lead to an empty result/
```
BOARD = native
CPU = native
CPU_MODEL =
CPU_FAM =
CPU_ARCH =
FEATURES_PROVIDED = periph_rtc periph_timer periph_uart periph_gpio periph_pwm periph_qdec ethernet motor_driver arch_32bit arch_native cpp periph_cpuid periph_hwrng periph_pm periph_pwm ssp periph_spi
_FEATURES_PROVIDED_SORTED = arch_32bit arch_native cpp ethernet motor_driver periph_cpuid periph_gpio periph_hwrng periph_pm periph_pwm periph_qdec periph_rtc periph_spi periph_timer periph_uart ssp
FEATURES_REQUIRED = arch_32bit arch_native arch_32bit arch_native
_FEATURES_REQUIRED_SORTED = arch_32bit arch_native
FEATURES_OPTIONAL = periph_gpio periph_pm periph_gpio periph_pm
FEATURES_USED = arch_32bit arch_native periph_gpio periph_pm
FEATURES_MISSING =
FEATURES_CONFLICT =
FEATURES_CONFLICTING =
USEMODULE = auto_init board core core_init core_msg core_panic cpu native-drivers periph periph_common periph_gpio periph_init periph_init_common periph_init_gpio periph_init_init periph_init_pm periph_init_uart periph_pm periph_uart stdio_native sys
DEFAULT_MODULE = auto_init board core core_init core_msg core_panic cpu periph_init periph_init_common periph_init_gpio periph_init_init periph_init_pm periph_init_uart sys
DISABLE_MODULE =
```

**Comment by cladmi** [comment]
> > You should also run the dependency-debug commands on several boards, I think some do not have a CPU_ARCH, and this line would also need to be modified:
> 
> I had tested on native, and It just lead to an empty result/

It was with the global command, I did not remember the name.
Without the last commit:

```
BOARDS="iotlab-m3 native" DEPENDENCY_DEBUG=1 make info-boards-supported >/dev/null; grep CPU dependencies_info-boards-supported_native
CPU = native
CPU_MODEL =
CPU_FAM = stm32f1
CPU_ARCH = cortex-m3
```

It would be shown by the full execution diff too, but takes longer to run.

**Comment by fjmolinas** [comment]
With the last commit:

```
BOARDS="iotlab-m3 native" DEPENDENCY_DEBUG=1 make -C examples/hello-world info-boards-supported >/dev/null; grep CPU examples/hello-world/dependencies_info-boards-supported_native
CPU = native
CPU_MODEL =
CPU_FAM =
CPU_ARCH =
```

thanks for the catch!

**Comment by fjmolinas** [comment]
all green now @aabadie, do you want to take a second look at the last commit?

**Comment by fjmolinas** [comment]
Rebased to fix merge conflict.

**Comment by aabadie** [comment]
Code still looks good so my ACK holds. CI is green, let's go!

**Pull request merged**
