### PR TITLE
sc_netif: check for NULL pointers on send

### PR DESCRIPTION
**Pull request by authmillenon**
Revisited this bit of code when discussing a separate issue with @OlegHahm. Might be of interest to look at for @haukepetersen since it is his original code.

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
Rebased to allow the unittests to run properly.

**Comment by OlegHahm** [comment]
Rebased on what? What caused this weird behavior?

**Comment by authmillenon** [comment]
That pexpect wasn't installed ;-)

**Comment by OlegHahm** [comment]
But why?

**Pull request merged**
