### PR TITLE
cpu: generalized nrf51822 to nrf51 and updated headers

### PR DESCRIPTION
**Pull request by haukepetersen**
The nrf51822 is only one CPU model in the NRF51 family. The are more CPUs (e.g. NRF51422) that use the same register layer so they are more or less code compatible. To prevent code duplication, it makes sense to centralize the code for all these CPUs into one generic CPU folder, aka `nrf51`.

Further I updated the device headers to their May 2015 versions.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@haukepetersen by just looking over your changes they seem reasonable to me. I will test soon with yunjia and maybe with the new nrf51 dongle.

**Comment by haukepetersen** [comment]
rebased

**Comment by thomaseichinger** [comment]
ACK when Travis passed.

**Comment by haukepetersen** [comment]
fixed whitespace errors in headers, to Travis :-)

**Comment by PeterKietzmann** [comment]
Travis passed, Strider not. I take the risk to merge anyway

**Pull request merged**
