### PR TITLE
gh/workflows/release-tests: add LoRaWAN secrets env variables

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This commit injects some LoRaWAN secrets into `tox` in order to avoid
exposing LoRaWAN keys when running RIOT-OS/Release-Specs#201

The secrets are already loaded.

### Testing procedure
I will try to run RIOT-OS/Release-Specs#201 pointing to this commit

### Issues/PRs references
RIOT-OS/Release-Specs#201

### CODE REVIEW

**Comment by miri64** [comment]
> I will try to run [RIOT-OS/Release-Specs#201](https://github.com/RIOT-OS/Release-Specs/pull/201) pointing to this commit

will only work from your fork, when the branch of this PR is your default branch ;-)

**Review by miri64 — COMMENTED** [review]
I can confirm: the newly configured secrets correspond to the once I configured in the RIOT-OS orga settings.

image

**Review by miri64 — CHANGES_REQUESTED** [review]
Please also include the [remaining TTN parameters](https://github.com/RIOT-OS/Release-Specs/pull/201#discussion_r557565696) here.

**Comment by jia200x** [comment]
>  Please also include the remaining TTN parameters here.

Those parameters are not set when running the release-tests workflow. I only exposed them to the `tox` call (see https://github.com/RIOT-OS/Release-Specs/pull/201/commits/3410becb6b4cbf98c5cce27f5afbad76d7452439)

**Comment by miri64** [comment]
> Those parameters are not set when running the release-tests workflow. I only exposed them to the `tox` call (see [RIOT-OS/Release-Specs@3410bec](https://github.com/RIOT-OS/Release-Specs/commit/3410becb6b4cbf98c5cce27f5afbad76d7452439))

Not sure I like it that way, but fine, not really a reason to block.

**Comment by miri64** [comment]
Hoops ^^ that close was accidental 😅

**Review by miri64 — APPROVED** [review]
ACK!

**Comment by jia200x** [comment]
thanks for the (late night) review!!

**Comment by jia200x** [comment]
> Not sure I like it that way, but fine, not really a reason to block.

Hmmm but you mean, hardcoding the variables here as env variables?

**Comment by miri64** [comment]
> > Not sure I like it that way, but fine, not really a reason to block.
> 
> Hmmm but you mean, hardcoding the variables here as env variables?

Yes.

**Comment by jia200x** [comment]
> Yes

I can do that in a follow up right after the Hard Feature Freeze. Then we simply remove these vars from RIOT-OS/Release-Specs#201

**Comment by jia200x** [comment]
well, it's there: https://github.com/RIOT-OS/RIOT/pull/15775

**Pull request merged**
