### PR TITLE
examples: added fib to ng_networking

### PR DESCRIPTION
**Pull request by OlegHahm**
No reason to not include the fib here.

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK

**Comment by haukepetersen** [comment]
Travis likes it as well, and we got some off-line ok's from @cgundogan and @kaspar030 -> go.

**Comment by authmillenon** [comment]
Why? Though I do not find the exact reference in https://github.com/RIOT-OS/RIOT/pull/2895 I remember that we discussed that `ng_networking` should be a pure 1-hop example and that there should be a seperate example that incorporates routing.

**Comment by authmillenon** [comment]
(I think it was @Lotterleben who argued for that)

**Comment by cgundogan** [comment]
I don't see the point in having two examples, one for 1-hop and one for multi-hop, because they would only differ in the Makefile. I would also want to add either rpl or aodvv2 to `ng_networking` when they are ready. This way any user/new-comer can just go ahead and flash a really simple example application to get dynamic routing capabilities and observe the power and simplicity of RIOT.

**Comment by OlegHahm** [comment]
I think the argument was, that it may be to confusing for users, but since only the Makefile changes a little bit (as @cgundogan mentioned) and even this is marked as optional, I think we can expect our users to deal with this.

**Comment by OlegHahm** [comment]
And the other option would be to maintain two example applications with very similar code (-> code duplication) that needs to be maintained.

**Comment by authmillenon** [comment]
So something like this is planned for the makefile?

```Makefile
ifneq (1,$(ROUTER))
USEMODULE += ng_ipv6_router_default
ifeq (ng_rpp,$(USEMODULE)) # ng_rpp pseudo-module pulled in by any routing protocol
  USEMODULE += ng_rpl
endif
endif
```

**Pull request merged**
