### PR TITLE
doc: drivers/pn532: add missing ingroup

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
I wasn't sure where to put it in a lower level than drivers as it didn't really fit in any of the groups.

### CODE REVIEW

**Comment by OlegHahm** [comment]
@LudwigKnuepfer, I agree with your assessment.

@cgundogan, any idea why Murdock fails, while Jenkins succeeds?

**Comment by cgundogan** [comment]
>@cgundogan, any idea why Murdock fails, while Jenkins succeeds?

I am updating the arm toolchain of all Jenkins slaves. Seems like gcc-5.4~ wasn't catching this error.

**Comment by OlegHahm** [comment]
But the failure seems unrelated anyway - strange.

**Comment by cgundogan** [comment]
#6356 is merged, so it should build now (if Murdock rebases this PR to current master)

**Pull request merged**
