### PR TITLE
Board ek tm4c129xl initial start files.

### PR DESCRIPTION
**Pull request by poppe34**
Here is the start of the ek-tm4c1294xl board.  Hopefully someone has one of these to validate.  It is a very cheap board that could make for a good boarder router when a radio board is added.

### CODE REVIEW

**Comment by OlegHahm** [comment]
@haukepetersen, what's your take on this?

**Comment by haukepetersen** [comment]
there seem to be some issues:
- is this CPU not the same (or very similar) to the lm4f120? I think it should actually use the same CPU code
- it might make sense to merge/move stellaris common and tiva common

@poppe34: do I get this right? I tend to loose track of all the rebranding that TI did for the MCUs...

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by miri64** [comment]
Postponed due to Feature Freeze

**Comment by kYc0o** [comment]
Do this PR still valid?

**Comment by cgundogan** [comment]
```
poppe34 wants to merge 7 commits into RIOT-OS:master from unknown repository 
```

Is this PR still valid, if there's no remote branch?

**Comment by OlegHahm** [comment]
Closing because of inactivity.

**Pull request closed without merging**
