### PR TITLE
drivers: net: fix isr_arg for encx24j600 and ethos

### PR DESCRIPTION
**Pull request by kaspar030**
See #4859.

### CODE REVIEW

**Comment by authmillenon** [comment]
`enc28j60` needs fixing, too.

**Comment by authmillenon** [comment]
Just thinking about it: why do we need this parameter at all? The `isr_arg` is stored in `dev` regardless (which is always given). If we rename `isr_arg` to `event_ctx` or something like that we also make it more clear, that this isn't an argument anymore.

**Comment by kaspar030** [comment]
Yeah, I came to the same conclusion (in #4859).

What do you think, does it make sense to keep the extra argument to event_callback at all?

**Comment by authmillenon** [comment]
IMHO, no. But since this is an API change we should really sleep about this ;-)

**Comment by authmillenon** [comment]
Let's merge this one first (please adapt `enc28j60` for that) and discuss this later.

**Comment by authmillenon** [comment]
(because an API change WILL cause some discussion before getting merged, while this is a no brainer)

**Comment by kaspar030** [comment]
- rebased
- unified isr_arg usage (pass it on EVENT_ISR, pass NULL otherwise)

**Comment by authmillenon** [comment]
ACK and go.

**Comment by OlegHahm** [comment]
Do we already have a follow-up issue/PR?

**Comment by kaspar030** [comment]
> Do we already have a follow-up issue/PR?

Yep, #4871.

**Pull request merged**
