### PR TITLE
nanocoap: clean up coap_iterate_option(), make it public

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Currently we don't have a public way to iterate all options of the same type - `coap_iterate_option()` was intended to be public (it's not `static`) but was never declared in any header file.

This allows for the opportunity to clean up the API to make it more palatable for public consumption.  

### Testing procedure

The function is only used by `coap_opt_get_string()` for which we have unit tests that are still passing.

### CODE REVIEW

**Review by maribu — APPROVED** [review]
Looks good to me. One suggestion for wording in the doc.

I think `_parse_option()` is unable to parse zero-length CoAP options at the end of the CoAP message (e.g. CoAP number delta < 13, CoAP option length is zero, no payload and no payload marker) :/ But that is completely unrelated to this PR.

**Comment by maribu** [comment]
> I think `_parse_option()` is unable to parse zero-length CoAP options at the end of the CoAP message (e.g. CoAP number delta < 13, CoAP option length is zero, no payload and no payload marker) :/ But that is completely unrelated to this PR.

No, its fine. I didn't look closely enough.

**Comment by maribu** [comment]
bors cancel
bors merge

**Comment by maribu** [comment]
bors cancel

Some Makefile.ci bumps are required :-/

**Comment by benpicco** [comment]
Which is odd since I don't see *any* size increase locally

**Comment by maribu** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
