### PR TITLE
pktdump: add 6LoWPAN dump

### PR DESCRIPTION
**Pull request by authmillenon**
~~Depends on #2614~~ (merged)

~~Depends on #2833~~ (merged)

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current #2614

**Comment by authmillenon** [comment]
Rebased to #2833.

**Comment by haukepetersen** [comment]
needs rebase.

**Comment by authmillenon** [comment]
Done

**Comment by authmillenon** [comment]
Anybody care to review?

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by haukepetersen** [comment]
ACK, merge at will once Travis is happy.

**Pull request merged**
