### PR TITLE
sys/vfs: model Kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
Split from #17232. This models the VFS module, include native's, in Kconfig. I added the configuration file for `tests/vfs_plus_stdio`.

### Testing procedure
- Check the modelling
- Green CI

### Issues/PRs references
#17232

### CODE REVIEW

**Comment by fjmolinas** [comment]
Have you taken a look at modeling all the `fs` pkgs? It would be good to see how they all fit in together. No a reason to block though.

**Comment by leandrolanzieri** [comment]
> Have you taken a look at modeling all the `fs` pkgs? It would be good to see how they all fit in together. No a reason to block though.

Not yet. I think fatfs provides an interface to vfs but it's an extra module, which would depend on this I'd say. Same goes for constfs and devfs.

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by leandrolanzieri** [comment]
Thanks for reviewing and merging!

**Pull request merged**
