### PR TITLE
release-notes.txt: add 2023.04 release notes [backport 2023.04]

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
# Backport of #19503

### Contribution description
This are the release notes for the 2023.04 Release. Please give it a look and make sure that your work in the last 3 months is present here.

### Testing procedure
- Read the document

### CODE REVIEW

**Comment by jia200x** [comment]
bors merge

**Comment by jia200x** [comment]
@benpicco do you know why bors rejects the merge command?

**Comment by miri64** [comment]
Try force pushing after a `git commit --amend`. I think it is still stuck with the old label settings.

**Comment by miri64** [comment]
You did not push ;-)

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
bors cancel

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
You can do it bors!

**Comment by MrKevinWeiss** [comment]
bors what's going on?

**Comment by MrKevinWeiss** [comment]
I knew you could do it bors, good job!

**Pull request merged**
