### PR TITLE
drivers/io1_xplained: apply unified params definition scheme

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Missed that one last week. I just discovered it while doing some cleanup in my branches.

### Issues/PRs references

Initially done in #7937 and related to #7519

### CODE REVIEW

**Comment by aabadie** [comment]
Maybe @miri64 is 'interested' ;)

**Comment by miri64** [comment]
Nvm about the crashing... I just used the wrong extension port. However, I can't access the shell, when it is attached, now :-/

**Comment by aabadie** [comment]
There's a RX/TX jumper that needs to be unplugged

**Comment by miri64** [comment]
Ah!

**Comment by miri64** [comment]
Still crashing on master though :(

**Comment by aabadie** [comment]
Can you test on IoT-LAB (Saclay site), the Samr21 there have the extension

**Comment by miri64** [comment]
I can't flash the firmware when setting up the experiment on the site and when I flash with the cli tools the node is not responding :-/

**Comment by aabadie** [comment]
> I can't flash the firmware when setting up the experiment on the site and when I flash with the cli tools the node is not responding

hmm, I'll have a look but only tomorrow.

**Comment by miri64** [comment]
I'll open an issue in the meantime ;-).

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/issues/8761

**Pull request merged**
