### PR TITLE
dist/tools/doccheck: add exclude file for warnings and use it 

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This is purely quick-and-lazy fix to finally unblock RIOT-OS/riotdocker#104 (see https://github.com/RIOT-OS/riotdocker/pull/104#issuecomment-905844998), but may also be useful to add future exclude patterns.

The exclude file was generated using (on Arch Linux, 1.9.1)

```sh
make doc 2> dist/tools/doccheck/exclude_patterns_base
grep "^${PWD}" dist/tools/doccheck/exclude_patterns_base | \
    sed -E -e "s#^${PWD}/(.*:)([0-9]+): #\1DIGITS_MAGIC: #" \
           -e 's/[]\\.$*{}|+?()[^-]/\\&/g' \
           -e 's/:DIGITS_MAGIC:/:[0-9]+:/' | \
        sort -u > dist/tools/doccheck/exclude_patterns
rm dist/tools/doccheck/exclude_patterns_base
```

Also, some fixes to the Doxyfile proposed by the newer Doxygen version are piggy-backed.

### Testing procedure
`doccheck` in

```sh
make static-test
```

should pass with newer doxygen versions than the one in the CI. If you are impatient like me, you can comment out the other checks ;-)

<details>

```diff
diff --git a/dist/tools/ci/static_tests.sh b/dist/tools/ci/static_tests.sh
index a04c5a9d40..d836aa7c1a 100755
--- a/dist/tools/ci/static_tests.sh
+++ b/dist/tools/ci/static_tests.sh
@@ -111,25 +111,25 @@ fi
 
 export BASE_BRANCH="${CI_BASE_BRANCH}"
 
-run ./dist/tools/whitespacecheck/check.sh "${BASE_BRANCH}"
-DIFFFILTER="MR" ERROR_EXIT_CODE=0 run ./dist/tools/licenses/check.sh
-DIFFFILTER="AC" run ./dist/tools/licenses/check.sh
+# run ./dist/tools/whitespacecheck/check.sh "${BASE_BRANCH}"
+# DIFFFILTER="MR" ERROR_EXIT_CODE=0 run ./dist/tools/licenses/check.sh
+# DIFFFILTER="AC" run ./dist/tools/licenses/check.sh
 run ./dist/tools/doccheck/check.sh
-run ./dist/tools/externc/check.sh
-run ./dist/tools/cppcheck/check.sh
-run ./dist/tools/vera++/check.sh
-run ./dist/tools/coccinelle/check.sh
-run ./dist/tools/flake8/check.sh
-run ./dist/tools/headerguards/check.sh
-run ./dist/tools/buildsystem_sanity_check/check.sh
-run ./dist/tools/feature_resolution/check.sh
-run ./dist/tools/boards_supported/check.sh
-run ./dist/tools/codespell/check.sh
-if [ -z "${GITHUB_RUN_ID}" ]; then
-    run ./dist/tools/uncrustify/uncrustify.sh --check
-else
-    run ./dist/tools/uncrustify/uncrustify.sh
-fi
-ERROR_EXIT_CODE=0 run ./dist/tools/shellcheck/check.sh
+# run ./dist/tools/externc/check.sh
+# run ./dist/tools/cppcheck/check.sh
+# run ./dist/tools/vera++/check.sh
+# run ./dist/tools/coccinelle/check.sh
+# run ./dist/tools/flake8/check.sh
+# run ./dist/tools/headerguards/check.sh
+# run ./dist/tools/buildsystem_sanity_check/check.sh
+# run ./dist/tools/feature_resolution/check.sh
+# run ./dist/tools/boards_supported/check.sh
+# run ./dist/tools/codespell/check.sh
+# if [ -z "${GITHUB_RUN_ID}" ]; then
+#     run ./dist/tools/uncrustify/uncrustify.sh --check
+# else
+#     run ./dist/tools/uncrustify/uncrustify.sh
+# fi
+# ERROR_EXIT_CODE=0 run ./dist/tools/shellcheck/check.sh
 
 exit $RESULT
```

</details>

Static tests should pass in CI.

### Issues/PRs references
Should unblock https://github.com/RIOT-OS/riotdocker/pull/104

### CODE REVIEW

**Comment by kfessel** [comment]
Running "./dist/tools/doccheck/check.sh" x
Command output:

        ERROR: Doxygen generates the following warnings:
        deprecated:70: warning: unexpected token TK_COMMAND_BS as the argument of _internalref
        todo:38: warning: unexpected token TK_COMMAND_BS as the argument of _internalref

make: *** [makefiles/tests.inc.mk:3: static-test] Error 2

**Comment by miri64** [comment]
Which doxygen version?

**Comment by miri64** [comment]
Also, not really sure where this is coming from... `git grep TK_COMMAND_BS` yields nothing. Are you sure you are on a clean branch?

**Comment by kfessel** [comment]
$git st 
HEAD detached at FETCH_HEAD
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dist/tools/ci/static_tests.sh

no changes added to commit (use "git add" and/or "git commit -a")

$ doxygen -v
1.8.18

**Comment by kfessel** [comment]
```
<RIOT>$ grep -r TK_COMMAND_BS .
``` 
is empty

**Comment by miri64** [comment]
Seems to be a false positive that is fixed in later version, since, as shown in OP, I can't reproduce this with doxygen 1.9.1.

**Comment by miri64** [comment]
Also, the output looks weird. It seems to think there are some files named `deprecated` and `todo` (maybe this rings a bell?) and the errors are in lines 70 and 38 respectively. Here is how actual error output could look like:

```
Running "./dist/tools/doccheck/check.sh" x
Command output:

	ERROR: Doxygen generates the following warnings:
	warning: Tag 'TCL_SUBST' at line 237 of file '-' has become obsolete.
	         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
	warning: Tag 'COLS_IN_ALPHA_INDEX' at line 1035 of file '-' has become obsolete.
	         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
	warning: Tag 'PERL_PATH' at line 2112 of file '-' has become obsolete.
	         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
	warning: Tag 'MSCGEN_PATH' at line 2134 of file '-' has become obsolete.
	         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
	warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
	drivers/xbee/include/xbee_params.h:33: warning: Member XBEE_PARAM_UART (macro definition) of file xbee_params.h is not documented.
	drivers/xbee/include/xbee_params.h:36: warning: Member XBEE_PARAM_BR (macro definition) of file xbee_params.h is not documented.
	drivers/xbee/include/xbee_params.h:39: warning: Member XBEE_PARAM_PIN_SLEEP (macro definition) of file xbee_params.h is not documented.
	drivers/xbee/include/xbee_params.h:42: warning: Member XBEE_PARAM_PIN_RESET (macro definition) of file xbee_params.h is not documented.
	drivers/xbee/include/xbee_params.h:46: warning: Member XBEE_PARAMS (macro definition) of file xbee_params.h is not documented.
```

**Comment by miri64** [comment]
(generated by reverting some of the changes in this PR)

**Comment by kfessel** [comment]
focal (20.04) is at  1.8.17

**Comment by miri64** [comment]
> focal (20.04) is at 1.8.17

Mhh let me check on my `focal` system :-)

**Comment by miri64** [comment]
Mhh... getting a completely different set of errors:

```
Running "./dist/tools/doccheck/check.sh" x
Command output:

	ERROR: Doxygen generates the following warnings:
	cpu/stm32/include/candev_stm32.h:80: warning: Member CAN_STM32_NB_FILTER (macro definition) of file candev_stm32.h is not documented.
	sys/include/crypto/ciphers.h:107: warning: Member cipher_id_t (variable) of file ciphers.h is not documented.
	sys/include/xtimer.h:630: warning: Member XTIMER_SHIFT (macro definition) of group sys_xtimer is not documented.
	sys/include/xtimer.h:630: warning: Member XTIMER_SHIFT (macro definition) of group sys_xtimer is not documented.
```

Will add those to the exclude file as well.

**Comment by miri64** [comment]
With the latest fixup `doccheck` passes on `focal`.

**Comment by kfessel** [comment]
maybe we can have some generic patterns like value macros are ok to be undocumented this would reduce the number of excludes by a lot

**Comment by kfessel** [comment]
warning: Member [:alnum:]+ (macro definition) of group [:alnum:]+ is not documented.

**Comment by miri64** [comment]
> maybe we can have some generic patterns like value macros are ok to be undocumented this would reduce the number of excludes by a lot

> warning: Member [:alnum:]+ (macro definition) of group [:alnum:]+ is not documented.

But we actually want to have this warning normally. It is not 100% clear why some group members, that used to be perfectly fine to be undocumented now are required to be with newer doxygen versions. The idea is that these warnings can be fixed successively in the future.

Also, as mentioned in OP: This is supposed to be the quick-and-lazy solution. If a more involved solution is desired, I can drop this, but then merging https://github.com/RIOT-OS/riotdocker/pull/104 will be stalled further.

**Comment by miri64** [comment]
> […] (if not false-positive).

And those who are false-positive (or don't really need documentation because it is clear from the group name can be silenced using `#if !defined(DOXYGEN)`

**Comment by kfessel** [comment]
```
/**
 * @name USB HID protocol types
 * @{
 */
#define USB_HID_PROTOCOL_NONE       0x0
#define USB_HID_PROTOCOL_KEYBOARD   0x1
#define USB_HID_PROTOCOL_MOUSE      0x2
/** @} */
```
this is somthing doxyggen currently complains about
i am not sure how much it can be improved with an documentation comment above each line

**Comment by miri64** [comment]
> i am not sure how much it can be improved with an documentation comment above each line

Does not need to be above the line. E.g.

```
/**
 * @name USB HID protocol types
 * @{
 */
#define USB_HID_PROTOCOL_NONE       0x0  /** < None */
#define USB_HID_PROTOCOL_KEYBOARD   0x1  /**< Keyboard */
#define USB_HID_PROTOCOL_MOUSE      0x2  /**< Mouse */
/** @} */
```

would also works. But that is exactly the non-sensical doc we don't want, and why we used grouping here in the first place. However, outright masking Group member documentation does not cut it. With that any missing module-part documentation will also pass the test. Take the following patch for example. With your patch that missing documentation would fall through.

```diff
diff --git a/sys/include/net/gnrc/ipv6.h b/sys/include/net/gnrc/ipv6.h
index 7b7ac466ac..5a3f330711 100644
--- a/sys/include/net/gnrc/ipv6.h
+++ b/sys/include/net/gnrc/ipv6.h
@@ -121,28 +121,14 @@ extern "C" {
  * @ingroup     net_gnrc_conf
  * @{
  */
-/**
- * @brief   Default stack size to use for the IPv6 thread
- */
 #ifndef GNRC_IPV6_STACK_SIZE
 #define GNRC_IPV6_STACK_SIZE        (THREAD_STACKSIZE_DEFAULT)
 #endif
 
-/**
- * @brief   Default priority for the IPv6 thread
- */
 #ifndef GNRC_IPV6_PRIO
 #define GNRC_IPV6_PRIO              (THREAD_PRIORITY_MAIN - 3)
 #endif
 
-/**
- * @brief   Default message queue size to use for the IPv6 thread (as exponent
- *          of 2^n).
- *
- *          As the queue size ALWAYS needs to be power of two, this option
- *          represents the exponent of 2^n, which will be used as the size of
- *          the queue.
- */
 #ifndef CONFIG_GNRC_IPV6_MSG_QUEUE_SIZE_EXP
 #define CONFIG_GNRC_IPV6_MSG_QUEUE_SIZE_EXP    (3U)
 #endif
@@ -205,14 +191,6 @@ extern kernel_pid_t gnrc_ipv6_pid;
 extern fib_table_t gnrc_ipv6_fib_table;
 #endif
 
-/**
- * @brief   Initialization of the IPv6 thread.
- *
- * @return  The PID to the IPv6 thread, on success.
- * @return  a negative errno on error.
- * @return  -EOVERFLOW, if there are too many threads running already
- * @return  -EEXIST, if IPv6 was already initialized.
- */
 kernel_pid_t gnrc_ipv6_init(void);
 
 /**
```

```
Running "./dist/tools/doccheck/check.sh" x
Command output:

	ERROR: Doxygen generates the following warnings:
	sys/include/net/gnrc/ipv6.h:125: warning: Member GNRC_IPV6_STACK_SIZE (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:129: warning: Member GNRC_IPV6_PRIO (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:133: warning: Member CONFIG_GNRC_IPV6_MSG_QUEUE_SIZE_EXP (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:194: warning: Member gnrc_ipv6_init(void) (function) of group net_gnrc_ipv6 is not documented.
	sys/include/net/gnrc/ipv6.h:125: warning: Member GNRC_IPV6_STACK_SIZE (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:129: warning: Member GNRC_IPV6_PRIO (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:133: warning: Member CONFIG_GNRC_IPV6_MSG_QUEUE_SIZE_EXP (macro definition) of group net_gnrc_ipv6_conf is not documented.
	sys/include/net/gnrc/ipv6.h:194: warning: Member gnrc_ipv6_init(void) (function) of group net_gnrc_ipv6 is not documented.
	sys/include/net/gnrc/ipv6.h:166: warning: unable to resolve reference to 'gnrc_ipv6_init()' for \ref command
```

**Comment by miri64** [comment]
And yes… I could try to identify the groups where this is desired and make patterns for those... but then we go way beyond the quick-and-lazy originally intended for this PR...

**Comment by miri64** [comment]
> Running "./dist/tools/doccheck/check.sh" x
> Command output:
> 
>         ERROR: Doxygen generates the following warnings:
>         deprecated:70: warning: unexpected token TK_COMMAND_BS as the argument of _internalref
>         todo:38: warning: unexpected token TK_COMMAND_BS as the argument of _internalref
> 
> make: *** [makefiles/tests.inc.mk:3: static-test] Error 2

This seems to be known bug in Doxygen 1.8.18: https://github.com/doxygen/doxygen/issues/7699

**Comment by kfessel** [comment]
there is a bug in doxygen that does not generate html from this 
```
drivers/include/periph/uart.h
126: * @deprecated  Use the errno constants directly instead.

drivers/include/periph/spi.h
133: * @deprecated  Use negative errno codes instead. The enum is still provided
```
and this 
```
sys/include/net/gnrc/netif/internal.h
203: * @todo Rule 4 from RFC 6724 is currently not implemented. Has to updated as
206: * @todo Rule 6 from RFC 6724 is currently not implemented. Has to updated as
209: * @todo Rule 7 from RFC 6724 is currently not implemented. Has to updated as
```

causing the warning on current doxygen 1.8.18 

this may be adressed  in another PR

i rechecked with  ubuntu focal (likely to be the next ci base) and there is no warning for this -> ACK

**Review by kfessel — COMMENTED** [review]
looks good works as expected 
please squash

**Review by kfessel — APPROVED** [review]
Lets clear the way for new CI.

**Pull request merged**
