### PR TITLE
Kconfig: make app.config and app.config.test mutually exclusive

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
When an application contains an `app.config` for configuration using Kconfig without dependency resolution and an `app.config.test` for configuration using Kconfig with dependency resolution, the `app.config` file is still loaded, setting legacy symbols, and this is causing errors with Kconfig (see e.g. https://github.com/RIOT-OS/RIOT/pull/15951#issuecomment-785760426). This makes `app.config` and `app.config.test` mutually exclusive and their selection as application base configuration based on the setting of `TEST_KCONFIG=1`.

### Testing procedure
I cherry-picked this PR on top of #15951 and try to build the test there with and without `TEST_KCONFIG=1` (currently causing an easy to solve merge conflict

```console
$ git remote add miri64 git@github.com:miri64/RIOT.git
$ git fetch miri64
$ git checkout miri64/congure/feat/initial
$ git cherry-pick miri64/kconfig/fix/app.config-mutual-exclusive
$ TEST_KCONFIG=1 make -C tests/congure_test -j
$ TEST_KCONFIG=1 make -C tests/congure_test -j clean   # otherwise one get's errors
$ make -C tests/congure_test -j
<!--
Details steps to test your contribution:
- which test/example to compile for which board and is there a 'test' command
- how to know that it was not working/available in master
- the expected success test output
-->


### Issues/PRs references

<!--
Examples: Fixes #1234. See also #5678. Depends on PR #9876.

Please use keywords (e.g., fixes, resolve) with the links to the issues you
resolved, this way they will be automatically closed when your pull request
is merged. See https://help.github.com/articles/closing-issues-using-keywords/.
-->

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
As long as people know that they need to double the efforts until the migration is complete that is OK with me but I will let @leandrolanzieri have the final word.

**Review by MrKevinWeiss — APPROVED** [review]
I guess nobody opposes the idea and the implementation seems sound so ACK!

**Comment by MrKevinWeiss** [comment]
Lets holdoff on the merge for a second.  Do other app.config parameter get used with app.config.test?

**Comment by MrKevinWeiss** [comment]
It looks like app.config only exists in some `tests/gnrc_*` `tests/kconfig`

None of which contain a `app.config.test` so I  guess we are OK...

**Comment by miri64** [comment]
Thanks for the review!

**Pull request merged**
