### PR TITLE
msp430: remove deprecated assert.h for MSP430

### PR DESCRIPTION
**Pull request by miri64**
Since we have a central `assert.h` in `core` now we don't need this file anymore (it also introduced bloat on a very constrained platform).

### CODE REVIEW

**Comment by OlegHahm** [comment]
Hm, in general I agree. However, sometimes it is handy to have the complete (non-minimized) assert output. The easiest way to achieve this is actually deleting `core/include/assert.h` temporarily (at least that's my preferred way). With this PR that probably wouldn't work on MSP430 any more.

**Comment by miri64** [comment]
Problem is, that with out this `core/include/assert.h` isn't included into doxygen, since the two `assert.h` colide.

**Comment by OlegHahm** [comment]
Maybe an ifdef helps?

**Comment by miri64** [comment]
How? It's complaining about the `@file` command?

**Comment by OlegHahm** [comment]
Why is it complaining about the `@file` command? What is the error message?

**Comment by miri64** [comment]
```
$ make doc 2>&1 | grep "assert\.h"
/home/mlenders/Repositories/RIOT-OS/RIOT/core/include/assert.h:13: warning: the name `/home/mlenders/Repositories/RIOT-OS/RIOT/core/include/assert.h' supplied as the second argument in the \file statement matches the following input files:
   /home/mlenders/Repositories/RIOT-OS/RIOT/core/include/assert.h
/home/mlenders/Repositories/RIOT-OS/RIOT/cpu/msp430-common/include/assert.h:13: warning: the name `/home/mlenders/Repositories/RIOT-OS/RIOT/cpu/msp430-common/include/assert.h' supplied as the second argument in the \file statement matches the following input files:
   /home/mlenders/Repositories/RIOT-OS/RIOT/cpu/msp430-common/include/assert.h
```

**Comment by OlegHahm** [comment]
This warning doesn't make much sense to me, because there is no argument supplied to `@file` in none of these files. We probably also get this warning for all header files with a name that exists more than once (e.g. all the periph headers).

**Comment by miri64** [comment]
Maybe, but [`assert.h` does not get any doc](http://doc.riot-os.org/core_2include_2assert_8h_source.html) and deleting this file fixes this.

**Comment by gebart** [comment]
How about this: move the declaration of the verbose assert macro to core
and wrap it in `#if DEBUG_ASSERT_VERBOSE` or similar. Then it will be
possible to enable it via the environment (CFLAGS=-DDEBUG_ASSERT_VERBOSE),
and it also solves #5875

**Comment by miri64** [comment]
@gebart sounds like a good idea, though I prefer a pseudo-module.

**Comment by miri64** [comment]
Or not (flip-flopping here ^^)

**Comment by miri64** [comment]
(i meant the preference of a pseudo-module, will cook something up!)

**Pull request closed without merging**
