### PR TITLE
cpu/samd21: added flashpage driver implementation

### PR DESCRIPTION
**Pull request by haukepetersen**
~~rebased on #5365~~

for some reason I did not get it to work on the `samr21-xpro`, so marked it as WIP...

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased, but erase still seems to be broken. Will need further investigation on my side.

**Comment by haukepetersen** [comment]
won't get this debugged for the release -> postponed

**Comment by photonthunder** [comment]
The erase is grabbing the 32 bit address instead of the 16 bit address, /2 fixes it:

```
NVMCTRL->ADDR.reg = (uint32_t)(page_addr)/2;
```

For what it is worth, this is the same thing the ASF way (it is what I used to find the problem):
```
#define FLASH_ADDR            (0x00000000UL) /**< FLASH base address */	
#define NVM_MEMORY        ((volatile uint16_t *)FLASH_ADDR)
const uint32_t rowAddress = (uint32_t)page_addr;
NVMCTRL->ADDR.reg  = (uintptr_t)&NVM_MEMORY[rowAddress / 4];
```

This works on a samd21 board, but I don't have a samr21.

**Comment by haukepetersen** [comment]
Wow, thanks @photonthunder! That seemed to be doing the job. And again one very good example for extremely bad documentation in the ref manual...

While I was at it, I made the following improvements:
- fixed the driver as proposed by @photonthunder 
- moved the flashpage driver in the `sam0_common` tree
- ported the driver also for the `saml21`
- enabled the `periph_flashpage` feature also for the `saml21-xpro` and the `samd21-xpro`

@photonthunder, @kaspar030, @kYc0o: Could you please verify, that the driver works on these platforms? Thanks!

Tested on:
- [x] samr21-xpro
- [ ] samd21-xpro
- [ ] saml21-xpro

**Comment by photonthunder** [comment]
Tested on the samd21-xpro.  Working good...

**Comment by haukepetersen** [comment]
@kYc0o, @kaspar030: any news?

**Comment by kYc0o** [comment]
Unfortunately I don't have the boards for testing, though I think with the samd21 and samr21 boards working is enough to merge this.

**Comment by haukepetersen** [comment]
I agree, but still need your ACK :-)

**Comment by kYc0o** [comment]
And well, we can go!

**Comment by biboc** [comment]
Good job guys! It is a good step to implement bootloader on samr/l/d21!

**Pull request merged**
