### PR TITLE
cpu/stm32f3: set cpu specific hwtimer spin barrier

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Has someone the hardware to test this again?

**Comment by haukepetersen** [comment]
I do and will look at it again.

**Comment by haukepetersen** [comment]
hmm, `test/hwtimer_wait` succeeds when I run it on my board. @thomaseichinger can we verify it on your computer once more?

**Comment by thomaseichinger** [comment]
ACK when Travis is happy.

**Comment by thomaseichinger** [comment]
@haukepetersen Travis needs a rebase.

**Comment by haukepetersen** [comment]
rebased, waiting for Travis.

**Comment by OlegHahm** [comment]
Travis is fine.

**Pull request merged**
