### PR TITLE
drivers: Added support pn532 driver for NFC communication

### PR DESCRIPTION
**Pull request by berbecche**
This library is for pn532's chips via SPI communication.
Library is developed for your udoo board, you should be able to interactively use any Adafruit PN532 Shield right connected to ICSP header and CS on pin 23. It should work with any SAM3X8E mcu. 
It should also work with other boards connected to this device but I haven't tried it out yet due to the lack of time.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Does anyone plan to continue to work on this?

**Comment by thomaseichinger** [comment]
Will take a look at it.

**Comment by thomaseichinger** [comment]
@berbecche I'm sorry I missed this one. Could you elaborate why this should only be usable with the sam3x CPU's? Maybe we can get it working with all of RIOT's supported MCUs.

**Comment by berbecche** [comment]
Hi. I'm pretty sure it works with sam3x CPU's because I tested it. I'm not
able to assure this driver works with all RIOT MCUs and I haven't.
Unfortunately, right now, I haven't time to spend to make it works for all
RIOT MCUs.

Il 24/ago/2015 21:31, "Thomas Eichinger" <notifications@github.com> ha
scritto:
>
> @berbecche I'm sorry I missed this one. Could you elaborate why this
should only be usable with the sam3x CPU's? Maybe we can get it working
with all of RIOT's supported MCUs.

**Comment by thomaseichinger** [comment]
Ok, I will take a look to see what has to be done.

**Comment by thomaseichinger** [comment]
@berbecche I discussed this with other maintainers offline. I will take a look what has to be done to get your code usable by more RIOT supported boards and will open PR against your repo. This is of high value for us so we would then merge it, after some testing, and open an issue to fix styling and debugging messages as a newbie task.
Are you ok if we proceed like this?

**Comment by berbecche** [comment]
Of course. Whatever to make more usable for RIOT.
Regards.

2015-09-01 17:51 GMT+02:00 Thomas Eichinger <notifications@github.com>:

> @berbecche <https://github.com/berbecche> I discussed this with other
> maintainers offline. I will take a look what has to be done to get your
> code usable by more RIOT supported boards and will open PR against your
> repo. This is of high value for us so we would then merge it, after some
> testing, and open an issue to fix styling and debugging messages as a
> newbie task.
> Are you ok if we proceed like this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RIOT-OS/RIOT/pull/2692#issuecomment-136767286>.
>



-- 
Dott. Simone Pecora
Cell. 340 108 6698
Linkedin: Simone Pecora

**Comment by thomaseichinger** [comment]
@berbecche Please consider https://github.com/berbecche/RIOT/pull/1

**Comment by OlegHahm** [comment]
@thomaseichinger, would you be willing to adopt this apparently abandoned PR?

**Comment by berbecche** [comment]
I'm so sorry about it, but I'm too busy this period.

2016-03-11 10:43 GMT+01:00 Oleg Hahm <notifications@github.com>:

> @thomaseichinger <https://github.com/thomaseichinger>, would you be
> willing to adopt this apparently abandoned PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RIOT-OS/RIOT/pull/2692#issuecomment-195294875>.
>



-- 
Dott. Simone Pecora
Cell. 340 108 6698
Linkedin: Simone Pecora

**Comment by thomaseichinger** [comment]
@OlegHahm I can, I actually have a [branch](https://github.com/thomaseichinger/RIOT/tree/pn532) with some fixes already laying around. Will pick it up as I find time.

**Comment by OlegHahm** [comment]
Thanks, @thomaseichinger. Won't make it for the release though.

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by PeterKietzmann** [comment]
#5573 and #2692 implement a driver for the same device. One is based on SPI, the other on I2C. Who is willing to merge both into one implementation :-)?

**Comment by OlegHahm** [comment]
@thomaseichinger, could you bring your fixes upstream please?

@lebrush, would you be willing to see if you can merge the SPI support into your PR?

**Comment by lebrush** [comment]
@OlegHahm i'll try to find some time to work on SPI for #5573. Works start to pile and I can't give a concrete date.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by PeterKietzmann** [comment]
Closing this one in favour of  #5573

**Pull request closed without merging**
