### PR TITLE
[RFC] gnrc_tcp_recv(): fix connection closed by remote host not handled

### PR DESCRIPTION
**Pull request by benemorius**
### Contribution description
I'm not certain this is right, but it fixed the problem I was having and it seems like it's right. Without this PR, I don't see how application code calling `gnrc_tcp_recv()` is notified of the remote host closing the connection. Documentation doesn't say what it should return when the remote end has closed. Currently it just continues blocking until timeout (or else it returns -EAGAIN), so we aren't able to tell that the remote host has closed the connection. This seems wrong.

The way `recv()` works on linux is that it returns 0 if the remote end has closed. The application usually responds to this by closing the local end if it has no more data to send. It seems to me that `gnrc_tcp_recv()` should return 0 so that the application can then call `gnrc_tcp_close()`.

Otherwise what happens is that the connection gets stuck half open because the application never learns that it should close it. That is, `tcb->state` gets stuck in `FSM_STATE_CLOSE_WAIT` and new connections from a client are rejected until the riot node is reset.

### Testing procedure
We don't have anything in tests or examples that uses `gnrc_tcp_recv()` in a way that can test what happens when the remote host closes the connection. What I'm testing with is a [telnet server](/benemorius/RIOT/tree/telnet-shell/examples/telnet_shell) that I implemented against gnrc_tcp. I can connect with a telnet client and then disconnect, but without this PR subsequent connection attempts are refused. With this PR, the connection is closed properly and subsequent connections are successful.

Maybe the telnet server will compile for many platforms but unfortunately I don't have it alone in a clean branch right now and that branch has some hacks in core and sys, so really it's a very non-ideal way to be testing this.

Normally I'd want to stop and write a stripped down test for this, but I don't have a lot of time and this seems like something we should try to address in time for the 2019.01 release unless I'm just mistaken about how it's supposed to work. Anyway I wanted to see what anyone else thought about it since I don't know when I'll have time to continue with it.

### CODE REVIEW

**Comment by benemorius** [comment]
@brummer-simon yes I'm sure that this part is expected behavior although it isn't from being stuck in TIME-WAIT. The TIME-WAIT state is never actually reached as that can't happen until after `gnrc_tcp_close()` is called.

The unexpected part is being unable to close the connection due to `gnrc_tcp_recv()` not giving indication that it has entered CLOSE-WAIT.

**Comment by brummer-simon** [comment]
I'll take a look into the entire issue next weekend (I want to take a look how CLOSE-WAIT is handled in the internal FSM). After that, I can give you more detailed feedback on the issue. 

But it certainly looks like you stumbled open a bug.

**Comment by brummer-simon** [comment]
Hi benemorius,

After looking at the current implementation I think you found something there.

As you said the problem is that the caller is blocked in the recv()-call until the next data carrying packet arrives. If this packet doesn't arrive you get the error that your requested timeout. So far so good. 
In cases where you read anything from the recv buffer and the last packet contained the FIN-Flag, it makes
no sense to wait for new Payload because the connection is terminated already.

I would suggest the following semantics for your fix:
The RFC says that even if the TCB is in the CLOSE-WAIT state, a recv-call must allow to read from the recv-buffer. At first I would check if the TCB is in the CLOSE-WAIT state. If so, try to read Data from the receive buffer. If it is empty (return code is 0) return an appropriate return code otherwise return the number of read bytes.
On the return code: Currently either the number of read bytes or an error code is returned, so using zero to indicate that the connection was closed is fine, although please update the documentation in the header file
because it is a small change in the semantics.

**Comment by miri64** [comment]
See #12367

**Pull request closed without merging**
