### PR TITLE
gnrc_netdev_eth: handle error on iovec initialization.

### PR DESCRIPTION
**Pull request by authmillenon**
In case the packet buffer is full `gnrc_netdev2_eth` might crash currenlty.

(See also https://github.com/RIOT-OS/RIOT/pull/4646#discussion_r52534904)

### CODE REVIEW

**Comment by kaspar030** [comment]
ACK.

**Comment by authmillenon** [comment]
`cortex_m0_2` is failing on RIOT CI with a message that doesn't really makes sense to me:

```
gnrc_networking:samr21-xpro:
Building application "gnrc_networking" for "samr21-xpro" with MCU "samd21".

arm-none-eabi-size: '/data/riotbuild/examples/gnrc_networking/bin/samr21-xpro/gnrc_networking.elf': No such file
/data/riotbuild/Makefile.include:218: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by gebart** [comment]
RIOT CI disk full?

**Comment by gebart** [comment]
How come RIOT CI is generating so many retries during the buildtest?

**Comment by OlegHahm** [comment]
Let's outsource this discussion to #4974

**Comment by authmillenon** [comment]
I'll take the Travis result for now.

**Pull request merged**
