### PR TITLE
cpu/lpc2387: clean up lpc2387.ld, fixes tests/cpp_ctors

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

When running all tests on `mcb2388` I discovered a failure in `tests/cpp_ctors`.
This led to an overdue cleanup of the lpc2387 linker script and init code.
There was some dead code in `startup.s` that could just be removed.

With the linker script I checked for what it did different than `cortexm_base.ld` and decided to just copy it's behavior, at least for the ROM code.
I also dropped some sections that were never used anywhere in RIOT anymore.

Now constructors should be placed just where they are for Cortex M and the test is working.

### Testing procedure

Run `tests/cpp_ctors` on e.g. `msba2`, but also verify that normal operation is unchanged.

##### master
```
2019-11-27 23:02:43,858 # main(): This is RIOT! (Version: 2020.01-devel-584-g8740e-mcb2388)
2019-11-27 23:02:43,858 # ..
2019-11-27 23:02:43,859 # cpp_tests.tests_cpp_global_ctors (tests/cpp_ctors/main.c 26) exp 12345 was 0
2019-11-27 23:02:43,859 # .
2019-11-27 23:02:43,860 # run 3 failures 1
```

##### this branch
```
2019-11-27 23:04:55,153 # main(): This is RIOT! (Version: 2020.01-devel-1124-g924db2-mcb2388-ldscript)
2019-11-27 23:04:55,154 # Help: Press s to start test, r to print it is ready
s
2019-11-27 23:05:00,078 # START
2019-11-27 23:05:00,079 # ...
2019-11-27 23:05:00,079 # OK (3 tests)
```

### Issues/PRs references
discovered in #12669

### CODE REVIEW

**Comment by maribu** [comment]
I confirm that this fixes the test for the MSB-A2. Can you add an commit to un-blacklist the msba2 and the avsextrem?

**Comment by maribu** [comment]
I used `elf_diff` to compare a binaries of a C only (no C++ used) build before and after this PR. Some symbols where placed differently in `.text`, which resulted in immediates in jump and branch instructions to be updated correspondingly; but they all targeted the same symbol and the same offset.

Somehow `.text` got 4 bytes bigger, but no symbol changed in size. I assume some alignment requirements were increased or so.

Anyway: No regression, a very nice cleanup and a fix of the C++ constructors. I really love this PR :-)

**Comment by benpicco** [comment]
#12748 introduced another reference to the `flash` section that got renamed to `rom` in this PR.
I rebased and resolved the sneaky merge conflict, tests should be building now again.

**Comment by maribu** [comment]
Please squash!

**Pull request merged**
