### PR TITLE
pyterm: log to `stdout` per default

### LINKED ISSUE #6139: pyterm: prints to stderr per default
`pyterm` prints to `stderr` per default (and I'm not sure changing this to stdout is configurable). This makes things very difficult if we ever want to use software like [`pexpect` for testing](http://stackoverflow.com/questions/27179383/extracting-stderr-from-pexpect) (the proposed solution on StackOverflow does not allow for input via `child.sendline()` anymore).

### PR DESCRIPTION
**Pull request by OlegHahm**
Fixes #6139.

Does anybody see a need to make this configurable?

### CODE REVIEW

**Comment by Kijewski** [comment]
Can we take a step back and discuss whether `2>&1` wouldn't be the right solution when some tests needs to see the stderr stream?

**Comment by miri64** [comment]
> Can we take a step back and discuss whether 2>&1 wouldn't be the right solution when some tests needs to see the stderr stream?

Sorry, did not see the comment when ACKing.

1) This does not work with e.g. `pexpect` (or anything any other test framework that doesn't use sh-isms)
2) What benefit do you see in having the terminal print a platforms `stdout` to `stderr`?

**Comment by Kijewski** [comment]
What exactly does not PR do? Before and after applying the change: on which stream goes the data from the remote board, on which stream goes the status information etc. of pyterm?

**Comment by OlegHahm** [comment]
> What exactly does this PR do?

Default output is directed to `stdout` instead of `stderr`.

>  Before and after applying the change: on which stream goes the data from the remote board, on which stream goes the status information etc. of pyterm?

There is no separation. Is this a desired feature? We could easily introduce another logging instance for that. But this would be definitely out of scope for this PR.

**Comment by miri64** [comment]
*trying to decipher your comment* Well it makes more sense to put the status information of the terminal out of `stderr`. How about:

```diff
diff --git a/dist/tools/pyterm/pyterm b/dist/tools/pyterm/pyterm
index e72fae7..bce3dac 100755
--- a/dist/tools/pyterm/pyterm
+++ b/dist/tools/pyterm/pyterm
@@ -95,7 +95,7 @@ class SerCmd(cmd.Cmd):
         """
 
         # initialize class members
-        cmd.Cmd.__init__(self)
+        cmd.Cmd.__init__(self, stdout=sys.stderr)
         self.port = port
         self.baudrate = baudrate
         self.toggle = toggle
```

**Comment by OlegHahm** [comment]
> Well it makes more sense to put the status information of the terminal out of stderr.

Why?

**Comment by miri64** [comment]
> Why?

To distinguish status messages and output as it is at the moment (just switched).

**Comment by OlegHahm** [comment]
That wouldn't cut it. Pyterm would require some cleanup. Some status/error messages are printed using `print`, while some are printed using `sys.stderr.write`, and some others use the logging module.

**Comment by Kijewski** [comment]
The `stderr.write(...)` usage looks odd to me in this file (didn't really look at it before). I would replace all with `print(..., file=stderr)`.

**Comment by OlegHahm** [comment]
My proposal:
1. Merge this PR as is (or close it without merging).
2. Refactor Pyterm to use two loggers. One for output of the node, one for status and error information.

**Comment by miri64** [comment]
> The stderr.write(...) usage looks odd to me in this file (didn't really look at it before). I would replace all with print(..., file=stderr).

(and for the print occurrences use `file` parameter also).

**Comment by miri64** [comment]
> 2. Refactor Pyterm to use two loggers. One for output of the node, one for status and error information.

Why is pyterm using `log` for output anyway? What was the rational behind that? The timestamp can also be provided other means.

**Comment by OlegHahm** [comment]
In order to have the output and the log file consistent.

**Comment by Kijewski** [comment]
`print()` always flushes (whilst `write()` does not), so I don't think that two loggers would be needed.

**Comment by OlegHahm** [comment]
Hm, after thinking about it again - I think the original rational was to have status and node output intermingled on purpose. It may help to understand the experiment flow if you have information about user input or pyterm timers etc in the same log file.

However, this discussion is not about this PR any more. Can we first decide what we want to do to address #6139 and keep the discussion about logging and output of pyterm in a separate issue or thread?

**Comment by miri64** [comment]
> However, this discussion is not about this PR any more. 

Well it kind of is, but I agree that most of this discussion is about how to handle output in pyterm which is inconsistent in pyterm at the moment anyway. @Kijewski do you agree to merge?

**Comment by OlegHahm** [comment]
>  but I agree that most of this discussion is about how to handle output in pyterm which is inconsistent in pyterm at the moment anyway. 

I just checked again. And I think it is pretty consistent - apart from the twisted code.

**Comment by Kijewski** [comment]
> @Kijewski do you agree to merge?

Well, I don't disagree. ;)

**Comment by miri64** [comment]
>> but I agree that most of this discussion is about how to handle output in pyterm which is inconsistent in >> pyterm at the moment anyway.
>
> I just checked again. And I think it is pretty consistent - apart from the twisted code.

But you yourself pointed out that there are at least 3 ways present of printing out data...

**Comment by OlegHahm** [comment]
> But you yourself pointed out that there are at least 3 ways present of printing out data...

Yes, but after looking it again, they make sense.

**Pull request merged**
