### PR TITLE
Rename 'openmote' board in-tree to 'openmote-cc2538'

### LINKED ISSUE #4459: Consider renaming "openmote" board in-tree to something less generic
According to the developers[1], OpenMote will be coming out with new versions of their hardware during 2016. This means there will be several different versions of OpenMote hardware, so "openmote" is probably too generic to use in-tree. I would suggest "openmote-cc2538" for the current (and so far only) model. Perhaps it might even be worth including the board revision letter.

[1] http://permalink.gmane.org/gmane.os.contiki.devel/24657

### PR DESCRIPTION
**Pull request by aeneby**
This is to avoid ambiguity with future versions of the OpenMote platform. Simple search-and-replace.

Resolves #4459.

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by aeneby** [comment]
@OlegHahm OK to merge?

**Comment by OlegHahm** [comment]
Not in the current state. Can you please remove all the commits that don't belong here?

**Comment by aeneby** [comment]
Sorry - some funky conflicts happening in that branch and I CBF untangling it for such a small commit :) New PR at #4667.

**Comment by kaspar030** [comment]
Before opening a new PR, you can always create a (fixed) branch locally, hard reset the PR'ed branch to the fixbranch top commit, and force push the PR. That way all the PR settings stay the same...

**Comment by aeneby** [comment]
@kaspar030 OK thanks, will keep this in mind for next time.

**Pull request closed without merging**
