### PR TITLE
cbor: fix documentation

### PR DESCRIPTION
**Pull request by miri64**

### CODE REVIEW

**Comment by smlng** [comment]
oops?!? With the grouping fixed, Murdock says, there is more to do in this file 😞

**Comment by smlng** [comment]
by a quick glance I think the `cbor_stream_t` struct members are not correctly documented, at least the format is off.

**Comment by miri64** [comment]
On that note I really would like to advertise #6966 a little ;-).

**Comment by smlng** [comment]
fair point! I'll look into these tomorrow, if possible ...

**Comment by miri64** [comment]
Fixed documentation (and changed title... Will fix commit message on squash)

**Comment by smlng** [comment]
looks good, please squash.

**Comment by miri64** [comment]
Squashed.

**Pull request merged**
