### PR TITLE
boards/microbit: optimized microbit_matrix_init()

### PR DESCRIPTION
**Pull request by haukepetersen**
Amateur... 

(saves 76 byte ROM)

### CODE REVIEW

**Comment by kaspar030** [comment]
I was wondering when I saw the original PR... ;)

**Comment by aabadie** [comment]
Changes looks good. Will try it asap.

**Comment by haukepetersen** [comment]
Murdock seems to fail unrelated. Has somebody experience with the `nucleo-f207` failing the `arduino-hello-world` example?

**Comment by haukepetersen** [comment]
and go

**Pull request merged**
