### PR TITLE
cpu/atmega1284p: basic implementation

### PR DESCRIPTION
**Pull request by roberthartung**
Adds a cpu/atmega1284p cpu implementation for the upcoming INGA board.

### CODE REVIEW

**Comment by kYc0o** [comment]
Well, I guess we need to know which this INGA board is, and how can we get it, otherwise I cannot know if this implementation works as expected.

**Comment by roberthartung** [comment]
@kYc0o True, I just thought the same when creating the PR for the INGA board. Should I just close this PR and create a new one with atmega1284p AND the INGA board?

Additionally, it would help if you could merge #7601 first

**Comment by roberthartung** [comment]
@kYc0o Thanks for the merge and quick review! Should I close this one and create a new PR with both the INGA board and the atmega1284p cpu?

**Comment by kYc0o** [comment]
Yes please.

**Comment by roberthartung** [comment]
Closed for a combined PR.

**Pull request closed without merging**
