### PR TITLE
ip: added a define to enable a FIB compatibility mode replacing `get_next_hop()`

### PR DESCRIPTION
**Pull request by BytesGalore**
This introduces a compatibility "option" to enable FIB in the ip part of the  good ol' network stack .

Rationale: 
To enable using the FIB in the old stack requires to change the `get_next_hop()` calls in `ip.c`.
Contrary to the prior registered functions of the routing protocols, the `fib_get_next_hop()` function must be called.
Just switching to the FIB functions would break (routing protocol) implementations using the old approach. 
So this PR introduces a compatibility "option" that enables to switch between the FIB and the former direct routing protocol next-hop request handling.

### CODE REVIEW

**Comment by Lotterleben** [comment]
looks good to me... @cgundogan, what do you think?

**Comment by cgundogan** [comment]
this looks sane and I will ACK right after you explain to me why we need it (:
IMHO, nobody wants to put further man power into the old network stack and I have no idea what happens after we've switched fully to the new network stack. Will the code go away?

**Comment by Lotterleben** [comment]
When we've switched it should most certainly go away because the old stack should get deleted, right? The idea ist just to have this until our routing protocols are switched to the new stack completely... (AODVv2 isn't, and rpl is still in progress, right?). otherwise we have them in this weird state where we can't “reach” them anymore from the old stack (when they're already switched to the fib) but can't test them with the new stack either.

**Comment by cgundogan** [comment]
Well, you have my cautious ACK, because I did not really test the PR. Just compiling the code via brain.. and I couldn't find any errors.

**Comment by Lotterleben** [comment]
Same here...

**Comment by Lotterleben** [comment]
Lets see what Travis says...

**Comment by Lotterleben** [comment]
Travis seems to be very unhappy :( @BytesGalore, could you take a look?

**Comment by BytesGalore** [comment]
sure :)

**Comment by BytesGalore** [comment]
travis smiles again :)

**Comment by Lotterleben** [comment]
Wohooo \o/ ACK and go, then.

**Pull request merged**
