### PR TITLE
gh-actions: annotate failures in GitHub action

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While wondering if there is a way to improve skimming through the release test results, I found [this](https://pypi.org/project/pytest-github-actions-annotate-failures/). It's quite new, but it just requires you to install it and then hooks into pytest, so quite straight forward.

### Testing procedure
We can start an action, if required. Otherwise, there is not much code included, so we basically have to trust the included package's testing.

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
Ping? No-one interested in nicer test outputs?

**Comment by aabadie** [comment]
IIUC, it will annotate changed files in PRs if there's an issue. What is the point with release tests (they are run periodically) ?
Can we run this on a fork to see what it would look like ?

**Comment by miri64** [comment]
> Can we run this on a fork to see what it would look like ?

As I already noted:



> We can start an action, if required. Otherwise, there is not much code included, so we basically have to trust the included package's testing.

Just was waiting for someone to ask ;-).

**Comment by miri64** [comment]
I did a rebase to make sure the tests are run against current master.

**Comment by miri64** [comment]
See https://github.com/miri64/RIOT/actions/runs/420260935

**Comment by miri64** [comment]
Ah right, there should be a wrong assert triggered for that to work ;-) See https://github.com/miri64/RIOT/actions/runs/422894506

**Comment by miri64** [comment]
Ah, it is not clearly documented within the plugin itself, but the [plugin also needs to be loaded by pytest](https://docs.pytest.org/en/stable/writing_plugins.html#plugin-discovery-order-at-tool-startup)

**Comment by miri64** [comment]
Here is a shortened run https://github.com/miri64/RIOT/actions/runs/423014296

**Comment by miri64** [comment]
Ok, one needs to admit defeat, when it is clear... This plugin either does not work or does not work with the pytest configuration in our tests... Even though I now got a "successfully" failed [run](https://github.com/miri64/RIOT/actions/runs/423102441/) the file is not annotated, nor is there any output indicating the annotation :-(

**Comment by miri64** [comment]
If anyone wants to look into this later (in case the plugin gets better or our integration changes), I bring the PR into a state without all the test commits again, so they can work from there.

**Pull request closed without merging**
