### PR TITLE
RIOT board cc3200 launchpad

### PR DESCRIPTION
**Pull request by attdona**
First version of the new RIOT board cc3200-launchxl

### CODE REVIEW

**Comment by attdona** [comment]
It seems that inside some files of TI sdk there are not an open source compliant license.

**Comment by authmillenon** [comment]
At first glance it looks like a slightly modified version of a [X11 license](http://directory.fsf.org/wiki/License:X11) to me (please make sure it is!). If it is it's definitely [compatible to LGPL v2.1](http://www.gnu.org/licenses/license-list.en.html#X11License) (that's what is important for us for integration into the repository) and you just have to provide a [pattern file](https://github.com/RIOT-OS/RIOT/tree/master/dist/tools/licenses/patterns) for the license. If it is not a X11 license you might need to contact the original authors and ask for permission for the integration of those files into RIOT.

**Comment by thomaseichinger** [comment]
@attdona Great to see this port. Which files don't have a compatible license?
As a remark, this PR in it's current state is hardly reviewable because of the sheer mass of imported code. Could you please take a look at the ek-lm4f120xl board and the lm4f120 CPU, maybe this will be applicable on your board/CPU too.

**Comment by attdona** [comment]
Take a look for example at drivers/cc3200sdk/netapps/mqtt/sl/sl_mqtt_client.c

I think the right thing to do is to remove all impacted files from cc3200sdk. At first sight we loose the mqtt protocol implementation, but I need to check better.

After that we could ask TI the permission to use the impacted files and reintroduces the netapps library.

**Comment by authmillenon** [comment]
Okay, those are definitely not free licenses (I was only looking at [cpu/cc3200/startup.c](https://github.com/attdona/RIOT/blob/master/cpu/cc3200/startup.c) and the likes).

**Comment by authmillenon** [comment]
> I think the right thing to do is to remove all impacted files from cc3200sdk. At first sight we loose the mqtt protocol implementation, but I need to check better.
>
> After that we could ask TI the permission to use the impacted files and reintroduces the netapps library.

I think an even more portable way to do it is just to provide an implementation for the [`conn`](https://github.com/RIOT-OS/RIOT/tree/master/sys/include/net/conn) interface for the cc3200's networking interface, so we can implement mqtt, http and the like on top of it, so that other RIOT-supported boards may also benefit from those implementations.

**Comment by attdona** [comment]
Ok, now the build says "Pull request needs squashing", so I think time to rest for me ...

If I understand correctly (this is my first RIOT PR) now the patch has to be reviewed by RIOT core mantainers.

Correct me if I'm wrong
greetings
Attilio

**Comment by OlegHahm** [comment]
As long as Github is saying "Sorry, we could not display the entire diff because it was too big." it's gonna be difficult to review this PR. The CI system saying "Pull request needs squashing" is because the label "NEED SQUASHING" was set here on Github, indicating that the PR cannot be merged before some commits haven't been squashed for a more consistent commit history.

Have you already removed the files from `cc3200sdk`? And maybe you could also split up the PR into a CPU, a board, and a drivers related PR?

**Comment by attdona** [comment]
Hi Oleg,

The files from cc3200sdk was removed.

Regards splitting the PR into 3 PR I will do it as soon as I understand how to.

The simple way that I see is the following:

1. create 3 local branches, remove all the files but the module (cpu, board and cc3200sdk) relative to one splitted PR
1.  create the 3 new splitted PR and forget this one
1. delete the temporary branches when the PRs are accepted

let me know if this could work
Attilio

**Comment by OlegHahm** [comment]
I guess this would work. Otherwise you could also create a branch that contains only the cpu changes, another one that contains the cpu and board changes and finally one this one here, which contains everything and we set the label "Waiting for another PR" for the latter two PRs, so the cpu-and-boards-PR would depend on the cpu-only-PR and so on. Do you see what I mean?

PR1: cpu changes
PR2: PR1 + board changes
PR3: PR2 + driver changes

**Comment by attdona** [comment]
Ok, clear to me.

I'm going to create PR1

**Comment by nqd** [comment]
Hello, it's interesting to see a wifi platform in RIOT. How is the status of the porting @attdona. I am willing to provide any help if possible.

**Comment by attdona** [comment]
Hi Nguyen,

In the last weeks I was lost into the cc1310 reference manual trying to
evaluate a future port to RIOT and I made little progress on cc3200
development (the most relevant perhaps is the SPI driver implementation)

For what I remember I was waiting some feedback from Oleg about rebooting
the chip using the reboot_arch api.

Great to hear that you can help, what about to checkout my fork [1] and
testing the port with some examples?

A tcpclient and a tcpserver  could be good new demo examples.

[1] https://github.com/attdona/RIOT


ciao
Attilio

**Comment by nqd** [comment]
Thanks. Will look into your porting; this's a good starting point.

**Comment by attdona** [comment]
I have done some more work on this PR.
For easing the review I've removed TI sdk that have to be merged eventually just after.

This work obsoletes PR #4059 

This cc3200 port is based on TI driverlib and simplelink TI sdk libraries.

There is an ongoing effort #4059 by @nqd to completly rewrite these HALs

**Comment by kYc0o** [comment]
Feature freeze -> postponed. So if this obsoletes #4059 please close it and address the remarks on this one.

**Comment by attdona** [comment]
Rebased. See #5733

**Comment by attdona** [comment]
Rebased. See #5733

**Pull request closed without merging**
