### PR TITLE
VERSION: add 2019.07 version file

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Add version file for release branch

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
daammit

**Comment by miri64** [comment]
Still way more commits in this PR than there should be ;-).

**Comment by miri64** [comment]
Waaait

**Comment by MrKevinWeiss** [comment]
I already did pr3...  rushing a bit much.  I just want it over.

**Comment by miri64** [comment]
You can change the base branch *after* a PR was opened ;-)

**Comment by miri64** [comment]
Ok, not if you already opened one against the release branch ;-)

**Pull request closed without merging**
