### PR TITLE
driver: add mpu_common

### PR DESCRIPTION
**Pull request by smlng**
- generic driver for MPU motion sensors
- works with MPU6050 (6-axis) and MPU9150 (9-axis)
- MPU9150 requires #define MPU_WITH_COMPASS

### CODE REVIEW

**Comment by OlegHahm** [comment]
Ah, at first I thought you were talking about an memory protection unit.

**Comment by smlng** [comment]
@OlegHahm: I agree `mpu_common` might be a bit confusing. However, IMHO we should reconsider naming conventions for drivers anyway, i.e., how to name drivers that support multiple devices/sensors with only minor code diffs? See PR #5433, too. For CPUs we already have some `CPU/ARCH_common` subdir and on top CPU type specific subdirs. IMHO it would be better to group drivers for similar devices into a single subdir (with a reasonable name). 

Anyway, this PR is WIP as it does not replace the driver for mpu9150 but adds a common driver for mpu-based devices, namely mpu6050 and mpu9150 - but it likely works for the mpu9250 as well.

**Comment by miri64** [comment]
What is up with the commits in this PR?

**Comment by smlng** [comment]
@miri64 I can rebase/update this one for the upcoming release. 

However, the problem was/is with the naming: there are 3 devices `MPU6050`, `MPU9150`, and `MPU9250`. They all basically work with this driver - the `9x50` version are identical and `6050` has no compass. Sticking to the naming scheme within RIOT drivers the driver has to be named `MPUxy50` which is kind of ugly.

Or, similar to the `cpu` section, we could introduce `mpu_common` and subdirs for each device?

**Comment by miri64** [comment]
> However, the problem was/is with the naming: there are 3 devices MPU6050, MPU9150, and MPU9250. They all basically work with this driver - the 9x50 version are identical and 6050 has no compass. Sticking to the naming scheme within RIOT drivers the driver has to be named MPUxy50 which is kind of ugly.
> 
> Or, similar to the cpu section, we could introduce mpu_common and subdirs for each device?

Non of this explains the messed up history ;-)

> @miri64 I can rebase/update this one for the upcoming release.

Since there seems to be some discussion in this PR, I can't promise that it will make it for this release, but I guess given the commit history a rebase wouldn't hurt ;-)

**Comment by smlng** [comment]
oh, those other commits - mhm 🤔 I may have to cleanup a bit more ...

**Comment by OlegHahm** [comment]
What's the current state?

**Comment by PeterKietzmann** [comment]
We still did not decide a rule of thumb in which way we want to organize similar device drivers, even though was a [short discussion devel](https://lists.riot-os.org/pipermail/devel/2016-July/004208.html) already

**Comment by smlng** [comment]
the driver would work for mpu_6050, mpu_9150, mpu_9250. With our current _rule_ it would've to be named `mpu_xy5z` that's what @PeterKietzmann is refering to. 

My idea was to introduce some similar concept as for cpu here, have a large mpu_common driver an only very small device specific parts.

**Comment by smlng** [comment]
I won't have to time to make this ready for release, remove milestone for now.

**Comment by tcschmidt** [comment]
Is there activity expected or can we close this?

**Comment by smlng** [comment]
one of my early works in RIOT, will rework in a new PR - closing this one as memo

**Comment by hoekstraarie** [comment]
How can I actually use this driver? Or can I just use the mpu9x50 driver with my mpu6050 module.

**Pull request closed without merging**
