### PR TITLE
dist/tools/cc2538-bsl: fixing pep8 and python 2 & 3 compatibility in cc2538 bsl script

### PR DESCRIPTION
**Pull request by aabadie**
This is a try to make cc2538 python 2 & 3 compliant and also pep 8 compliant (my python IDE was full of red dots...).

### CODE REVIEW

**Comment by miri64** [comment]
My two cents: I share @cgundogan's concerns about upstream compatibility https://github.com/RIOT-OS/RIOT/pull/5784#issuecomment-251604876

**Comment by kYc0o** [comment]
Waiting for upstream repo change (if accepted) to merge this one.

**Comment by kYc0o** [comment]
Upstream merging is taking a bit... We can merge it for the release anyways?

**Comment by miri64** [comment]
Was https://github.com/RIOT-OS/RIOT/pull/5909#issuecomment-251605796 addressed?

**Comment by aabadie** [comment]
@miri64, yes but the [upstream PR](https://github.com/JelmerT/cc2538-bsl/pull/58) takes some time to be merged.
See [comment](https://github.com/RIOT-OS/RIOT/pull/5784#issuecomment-251608591) for more info.

**Comment by aabadie** [comment]
Ok, so GO !

**Comment by miri64** [comment]
(though only to undo my implicit NACK, I did not look too deep into this PR, nor tested it)

**Pull request merged**
