### PR TITLE
cc26xx_cc13xx: fix UART1 initialization

### PR DESCRIPTION
**Pull request by jeandudey**
### Contribution description

Fixes UART1 initialization (didn't work before).

### Testing procedure

- Add UART1 to `periph_conf.h` for your CC13x2/CC26x2 board.
- Tell `stdio` to use `UART_DEV(1)`

<details>
<summary>Example configuration</summary>

```patch
From 083d64aea63ff374654e5410f04322dcd7ff7af3 Mon Sep 17 00:00:00 2001
From: Jean Pierre Dudey <jeandudey@hotmail.com>
Date: Wed, 8 Apr 2020 12:18:17 -0500
Subject: [PATCH] cc1312-launchpad: use UART1

Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>
---
 boards/cc1312-launchpad/include/periph_conf.h | 10 ++++++++++
 examples/hello-world/Makefile                 |  2 ++
 2 files changed, 12 insertions(+)

diff --git a/boards/cc1312-launchpad/include/periph_conf.h b/boards/cc1312-launchpad/include/periph_conf.h
index 0bd76b1da..5e9621ecd 100644
--- a/boards/cc1312-launchpad/include/periph_conf.h
+++ b/boards/cc1312-launchpad/include/periph_conf.h
@@ -90,6 +90,16 @@ static const uart_conf_t uart_config[] = {
      .cts_pin = 19,
 #endif
      .intn = UART0_IRQN
+ },
+ {
+     .regs = UART1,
+     .tx_pin = 3,
+     .rx_pin = 2,
+#ifdef MODULE_PERIPH_UART_HW_FC
+     .rts_pin = 18,
+     .cts_pin = 19,
+#endif
+     .intn = UART1_IRQN
  }
 };
 #define UART_NUMOF          ARRAY_SIZE(uart_config)
diff --git a/examples/hello-world/Makefile b/examples/hello-world/Makefile
index 258d8e9ba..8450428be 100644
--- a/examples/hello-world/Makefile
+++ b/examples/hello-world/Makefile
@@ -15,4 +15,6 @@ DEVELHELP ?= 1
 # Change this to 0 show compiler invocation lines by default:
 QUIET ?= 1
 
+CFLAGS += "-DSTDIO_UART_DEV=UART_DEV(1)" 
+
 include $(RIOTBASE)/Makefile.include
-- 
2.17.1

```
</details>

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Looks pretty good, if I can get some boards I will test it!

**Comment by benpicco** [comment]
@jeandudey Would it make sense to add that `cc1312-launchpad: use UART1` patch (without changing STDIO) too here?
Unless UART1 is used by an application, this has no effect, but it's always nice to have such things pre-configured for quick tests.

**Comment by jeandudey** [comment]
>Would it make sense to add that cc1312-launchpad: use UART1 patch (without changing STDIO) too here?

Yes makes sense, I'm using that UART on another project, I'll add it.

**Comment by jeandudey** [comment]
Updated :wink:

**Comment by MrKevinWeiss** [comment]
I only have the cc2650-launchpad... @benpicco did you test with a board? If not does anyone else have something on hand, usually @aabadie or @fjmolinas have a stockpile.

**Comment by fjmolinas** [comment]
> usually @aabadie or @fjmolinas have a stockpile.

Usually yes, but these are not usual times, I don't have any of those boards at hand ATM.

**Comment by fjmolinas** [comment]
> I only have the cc2650-launchpad... @benpicco did you test with a board? If not does anyone else have something on hand, usually @aabadie or @fjmolinas have a stockpile.

I think we can trust @jeandudey test ouput if he can provide some.

**Comment by MrKevinWeiss** [comment]
Agreed

**Comment by jeandudey** [comment]
<details>
<summary>UART1 output (using stdio with UART_DEV(1))</summary>

```
Building application "hello-world" for "cc1312-launchpad" with MCU "cc26x2_cc13x2".

"make" -C /home/jeandudey/Dev/RIOT/boards/cc1312-launchpad
"make" -C /home/jeandudey/Dev/RIOT/core
"make" -C /home/jeandudey/Dev/RIOT/cpu/cc26x2_cc13x2
"make" -C /home/jeandudey/Dev/RIOT/cpu/cc26x2_cc13x2/periph
"make" -C /home/jeandudey/Dev/RIOT/cpu/cc26xx_cc13xx
"make" -C /home/jeandudey/Dev/RIOT/cpu/cc26xx_cc13xx/periph
"make" -C /home/jeandudey/Dev/RIOT/cpu/cortexm_common
"make" -C /home/jeandudey/Dev/RIOT/cpu/cortexm_common/periph
"make" -C /home/jeandudey/Dev/RIOT/drivers
"make" -C /home/jeandudey/Dev/RIOT/drivers/periph_common
"make" -C /home/jeandudey/Dev/RIOT/sys
"make" -C /home/jeandudey/Dev/RIOT/sys/auto_init
"make" -C /home/jeandudey/Dev/RIOT/sys/newlib_syscalls_default
"make" -C /home/jeandudey/Dev/RIOT/sys/stdio_uart
   text	  data	   bss	   dec	   hex	filename
   8052	   108	  2560	 10720	  29e0	/home/jeandudey/Dev/RIOT/examples/hello-world/bin/cc1312-launchpad/hello-world.elf
/home/jeandudey/.local/opt/ti/uniflash_5.2.0/dslite.sh --config /home/jeandudey/Dev/RIOT/boards/cc1312-launchpad/dist/cc1312r1f3_XDS110.ccxml /home/jeandudey/Dev/RIOT/examples/hello-world/bin/cc1312-launchpad/hello-world.elf
Executing the following command:
> /home/jeandudey/.local/opt/ti/uniflash_5.2.0/deskdb/content/TICloudAgent/linux/ccs_base/DebugServer/bin/DSLite flash --config /home/jeandudey/Dev/RIOT/boards/cc1312-launchpad/dist/cc1312r1f3_XDS110.ccxml /home/jeandudey/Dev/RIOT/examples/hello-world/bin/cc1312-launchpad/hello-world.elf

For more details and examples, please refer to the UniFlash Quick Start guide.

Cortex_M4_0: GEL Output: Memory Map Initialization Complete.
Cortex_M4_0: GEL Output: Board Reset Complete.
/home/jeandudey/Dev/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2020-04-15 10:04:39,984 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.blob:
2020-04-15 10:04:48,167 # main(): This is RIOT! (Version: 2020.04-devel-1937-g9d2700-2020_04_06-uart1)
2020-04-15 10:04:48,168 # Hello World!
2020-04-15 10:04:48,172 # You are running RIOT on a(n) cc1312-launchpad board.
2020-04-15 10:04:48,176 # This board features a(n) cc26x2_cc13x2 MCU.
```
</details>

<details>
<summary>Photo of connected pins as defined in the periph_conf.h file to the debugger</summary>

</details>

**Pull request merged**
