### PR TITLE
test/unittest: cleanup most vera++ complains

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

cleans up most vera++ complains in unitest

what is left:

```
./tests-gnrc_ipv6_nib/tests-gnrc_ipv6_nib-internal.c:2109: warning: source file is too long
```
I tend towards agreeing  and so does github

```
        new_TestFixture(test_ipv6_addr_is_unique_local_unicast_unique_local_unicast_locally_assigned),
./tests-ipv6_addr/tests-ipv6_addr.c:1133: warning: line is longer than 100 characters
        new_TestFixture(test_ipv6_addr_is_unique_local_unicast_unique_local_unicast_not_locally_assigned),
./tests-ipv6_addr/tests-ipv6_addr.c:1134: warning: line is longer than 100 characters
```

```
./tests-ztimer64/tests-ztimer64-core.c:1: warning: no copyright notice found
./tests-ztimer64/tests-ztimer64.c:1: warning: no copyright notice found
./tests-ztimer64/tests-ztimer64.h:1: warning: no copyright notice found
```
there is a license notice but no c holder 

### Testing procedure

read and let murdock check

### Issues/PRs references

in  #18744 i saw some static-test complains for unchanged code the comlainee was vera++ -> i ran that on all unittest and cleaned that up

### CODE REVIEW

**Comment by miri64** [comment]
> ./tests-gnrc_ipv6_nib/tests-gnrc_ipv6_nib-internal.c:2109: warning: source file is too long

Could probably devided up somehow, if more concise test suites are identified.

**Comment by miri64** [comment]
> new_TestFixture(test_ipv6_addr_is_unique_local_unicast_unique_local_unicast_locally_assigned),
> ./tests-ipv6_addr/tests-ipv6_addr.c:1133: warning: line is longer than 100 characters
>         new_TestFixture(test_ipv6_addr_is_unique_local_unicast_unique_local_unicast_not_locally_assigned),
> ./tests-ipv6_addr/tests-ipv6_addr.c:1134: warning: line is longer than 100 characters

Maybe some shorter names by using some abbreviations? `_unique_local_unicast_` could be `_ulu_`. The abbreviation could be explained in a comment within the test case's definition.

**Comment by miri64** [comment]
> ```
> ./tests-ztimer64/tests-ztimer64-core.c:1: warning: no copyright notice found
> ./tests-ztimer64/tests-ztimer64.c:1: warning: no copyright notice found
> ./tests-ztimer64/tests-ztimer64.h:1: warning: no copyright notice found
> ```
> 
> 
>     
>   
> 
> there is a license notice but no c holder

@kaspar030 seems to be the main author in that directory, there is a co-authorship by @fjmolinas too, though. So probably, INRIA, but in the end, they have to say.

PS: Took me a moment to understand what you mean by C-holder...

**Comment by kfessel** [comment]
@miri64 would you approve to merge this as it is?

**Review by miri64 — APPROVED** [review]
> @miri64 would you approve to merge this as it is?

Yepp yepp, sorry thought your original comments were asking for advice how to handle.

**Pull request merged**
