### PR TITLE
Update tiny-asn1 package

### PR DESCRIPTION
**Pull request by mtausig**
### Contribution description

Update the tiny-asn1 package to the newest version.

Only minor changes (const pointers are used where possible)

### Testing procedure

No changes to the unit tests have been made.

### Issues/PRs references

https://gitlab.com/mtausig/tiny-asn1/-/merge_requests/3

### CODE REVIEW

**Comment by benpicco** [comment]
Thank you!
Just one thing: Please prefix the commit message with `pkg/tiny-asn1: ` to keep the git history tidy

**Comment by mtausig** [comment]
> Thank you! Just one thing: Please prefix the commit message with `pkg/tiny-asn1: ` to keep the git history tidy

Done.

**Comment by benpicco** [comment]
Looks like the test will need an update as well

```patch
--- a/tests/pkg_tiny-asn1/main.c
+++ b/tests/pkg_tiny-asn1/main.c
@@ -14,7 +14,7 @@
 
 #include "tiny-asn1.h"
 
-void print_hex(uint8_t *data, unsigned int len)
+void print_hex(const uint8_t *data, unsigned int len)
 {
     unsigned int count = 0;
     unsigned int blockCount = 0;
```

**Comment by benpicco** [comment]
Ah there is another one

```patch
--- a/sys/net/credman/credman.c
+++ b/sys/net/credman/credman.c
@@ -359,8 +359,8 @@ static int _parse_ecc_point(const asn1_tree *key, const void **x, const void **y
     }
 
     size_t coords_len = (key->length - 2) / 2;
-    uint8_t *_x = &key->data[2]; /* skip format specifier and unused bits */
-    uint8_t *_y = &_x[coords_len];
+    const uint8_t *_x = &key->data[2]; /* skip format specifier and unused bits */
+    const uint8_t *_y = &_x[coords_len];
 
     *x = _x;
     *y = _y;
```

**Review by benpicco — APPROVED** [review]
Thank you for the update!

**Pull request merged**
