### PR TITLE
drivers/at86rf2xx: add support for configuring PHY modes

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This implements getting & setting O-QPSK options with #12171
This allows for setting the rate mode (values 0-4, for 250, 500, 1000 & 2000 kbit/s operation) as well as chip rate (1000 kchip/s and 400 kchip/s for O-QPSK and 600 kchip/s and 300 kchip/s for BPSK).

The proprietary rate mode 2 on at86rf233 is compatible with the legacy high data rate mode on at86rf215.

### Testing procedure
Or on `samr30-xpro` you should now be able to to the following:
```
ifconfig 7 set rate_mode 2
ifconfig 7 set chip_rate 400
```

You should get
```
 Iface  7  HWaddr: 34:82  Channel: 0  Page: 2  NID: 0x23 PHY: O-QPSK 
            chip rate: 400 rate mode: 2 (legacy) 
           Long HWaddr: 79:7A:34:2F:9D:73:B4:82
```

On `samr21-xpro`, setting the chip_rate  should fail.

### Issues/PRs references
depends on #12171

### CODE REVIEW

**Comment by miri64** [comment]
@jia200x is this a duplicate of https://github.com/RIOT-OS/RIOT/pull/12069?

**Comment by benpicco** [comment]
@miri64 no this is to expose some modulation options that the chip provides to `ifconfig`.

**Comment by PeterKietzmann** [comment]
@jia200x I think this is a candidate for you

**Comment by jia200x** [comment]
I'm back!

> @jia200x is this a duplicate of #12069?

Not, not at all. #12069 just changes the representation of PHY states. This PR adds the means for configuring new PHY modes.

**Pull request closed without merging**
