### PR TITLE
tests: remove NETOPT_IPV6_IID dependency from lwip_sock tests

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This removes some code duplication and the provision of `NETOPT_IPV6_IID` through the mock device from the `lwip_sock` tests.

### Testing procedure
Run

- `make -C tests/lwip_sock_ip all test`
- `make -C tests/lwip_sock_udp all test`

`native` and `LWIP_IPV6` suffice.

### Issues/PRs references
None

### CODE REVIEW

**Comment by jia200x** [comment]
all tests successful with both `lwip_sock_udp` and `lwip_sock_ip`. Code looks OK.

**Comment by jia200x** [comment]
(with native and LWIP_IPV6 as proposed)

**Comment by aabadie** [comment]
This is all green. @jia200x, did you forget to merge ?

**Comment by aabadie** [comment]
re-running Murdock, just in case.

**Comment by miri64** [comment]
Yeah, this was just forgotten. Doesn't need to be backported though. Driver removal is slated for 2019.07.

**Pull request merged**
