### PR TITLE
netopt: add NETOPT_CSMA_MINBE, NETOPT_CSMA_MAXBE 

### PR DESCRIPTION
**Pull request by gebart**
These options can be used to get/set the backoff exponent parameters MinBE and MaxBE used by the CSMA/CA algorithm (see IEEE Std 802.15.4-2015, http://standards.ieee.org/about/get/802/802.15.html).
Also improved the documentation for the other CSMA options while I was touching that file.

Used by the kw41z radio in #7107

### CODE REVIEW

**Comment by gebart** [comment]
btw, is it OK to add stuff in the middle of the enumeration like this or should new items go at the bottom?
It does break binary compatibility, but I don't think anyone is doing binary releases of object code in RIOT at the moment.

**Comment by miri64** [comment]
It should be okay... at least for now.

**Comment by miri64** [comment]
`netopt2str()` needs to be updated

**Comment by gebart** [comment]
@miri64 updated netopt2str, amended

**Pull request merged**
