### PR TITLE
pkg: remove microcoap

### PR DESCRIPTION
**Pull request by kaspar030**
See #6038 for discussion.

### CODE REVIEW

**Comment by smlng** [comment]
Do we really want to kickout the microcoap package right now? I agree to remove the example and purge the docs. 

I personally have some RIOT applications that still depend on microcoap as a RIOT package - though, I will port them to use gcoap as soon as I have time for it.

**Comment by OlegHahm** [comment]
NAK

:+1: for removing the example, but I see no reason to remove the package. And I agree with @smlng that it would definitely break existing applications.

**Comment by aabadie** [comment]
Instead of immediately remove the microcoap pkg from RIOT, one can propose a smooth alternative : raise a kind of Deprecation Warning explaining that this is package will be removed in the next release (2017.01 ?) of RIOT and that CoAP based application developers should use nanocoap instead.

**Comment by kaspar030** [comment]
+1 for keeping the package, I've updated the PR accordingly.

**Comment by smlng** [comment]
I would keep this PR open/unmerged for a little longer, just to give others the chance to comment. 

Nevertheless, from my side: ACK.

**Comment by kaspar030** [comment]
> I would keep this PR open/unmerged for a little longer, just to give others the chance to comment.

:+1:, there's no rush at all.

**Comment by OlegHahm** [comment]
One problem that I see for now: if we remove the example, but not the package our CI won't complain if the package is broken.

**Comment by smlng** [comment]
So we need to add a small test, to check this; but not a full example?

**Comment by kaspar030** [comment]
> So we need to add a small test, to check this; but not a full example?

How about we just move the example to tests/ ?

**Comment by aabadie** [comment]
before moving/removing this example, I would wait for the nanocoap example to be fully documented ;) A README.md file is still missing there.

**Comment by kaspar030** [comment]
> A README.md file is still missing there.

Now that you've gained some experience with nanocoap, you could
volunteer to write one!

**Comment by haukepetersen** [comment]
how do we proceed with this PR? Do we still want to remove the microcoap example as we have the `gcoap` example for now?

**Comment by smlng** [comment]
I'm very much in favor of removing the example from the RIOT repository. For one to encourage usage of gcoap (which has already more functionality than microcoap), but -secondly- to cleanup the code we ship a little bit. 

However, I also think  we shouldn't throw away good code examples - so maybe we could rather _move_ the example to another repository!? We already have the _applications_ repo, but we might also create a distinct _examples_ repo for such things like deprecated or not that simple anymore examples. So we keep the code directly available - not only somewhere in the GIT history of RIOT.

Btw. as already pointed out: we should have a small test app, maybe just compiling the package, like we have for libcoap, for instance.

**Comment by kaspar030** [comment]
Closed in favour of #7599.

**Pull request closed without merging**
