### PR TITLE
gnrc_sixlowpan_frag: move public rbuf functions to their own module

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While implementing [selective fragment recovery](https://tools.ietf.org/html/draft-ietf-6lo-fragment-recovery-05) I ran into the problem of the reassembly buffer being bound to tight to classic reassembly, which makes it basically impossible to use without it. As a first preparation step to factor it out, I moved all its public functions to a new sub-module `gnrc_sixlowpan_frag_rb`. This should simplify the review greatly, as only move stuff around for now (which you can confirm if you activate [diff.colorMoved](https://git-scm.com/docs/git-config#Documentation/git-config.txt-diffcolorMoved) in your git-config.

### Testing procedure
Verify that apart from some header changes and module definition stuff I only move stuff around (I'm assuming the RIOT-OS/RIOT remote is called `upstream` on your system)

```sh
git fetch upstream
git diff --color-moved $(git merge-base upstream/master HEAD)
```

`tests/gnrc_sixlowpan_frag` should still work:

```sh
BOARD="<pick one>" make -C tests/gnrc_sixlowpan_frag flash test
```

All applications involving 6LoWPAN should still build (see Murdock)

### Issues/PRs references
None so far

### CODE REVIEW

**Comment by benpicco** [comment]
Just squash that last fixup already.
This just moves code around and Murdock will ensure everything still builds.

btw.: does our build system mandate a submodule for each subfolder?

**Comment by miri64** [comment]
> btw.: does our build system mandate a submodule for each subfolder?

No there is also the `SUBMODULE` feature, and a subdirectory does not necessarily have to be a submodule (see e.g. `sys` and `sys/net`) ;-)

**Comment by miri64** [comment]
Squashed a while ago, but forgot to push.

**Comment by miri64** [comment]
Darn, forgot to add a header in the tests. Will do, once I have a keyboard under my fingers.

**Comment by benpicco** [comment]
Just squash directly - Murdock will do most of the work here.

**Pull request merged**
