### PR TITLE
cpu/cc2538: misc UART driver fixes

### PR DESCRIPTION
**Pull request by hexluthor**
Hardware flow control (RTS/CTS) can now be used successfully on UART1. Tested on `cc2538dk`.

### CODE REVIEW

**Comment by kaspar030** [comment]
(don't have the device...)

**Comment by authmillenon** [comment]
Me neither, that's why I was assigning someone else…

**Comment by thomaseichinger** [comment]
@hexluthor I am very sorry for the delay. Code looks good, couldn't test UART1 though but it other UARTs behave sane. I still ACK this when travis passed, could you rebase to get Travis working again?

**Comment by hexluthor** [comment]
Done, thanks.

**Comment by thomaseichinger** [comment]
ACK & Go

**Pull request merged**
