### PR TITLE
doc/doxygen/riot.doxyfile: Do not generate man/LaTeX by default

### PR DESCRIPTION
**Pull request by gebart**
Does anyone actually install the manpages instead of using the html API docs?

### CODE REVIEW

**Comment by haukepetersen** [comment]
I am not.

**Comment by gebart** [comment]
Updated:
 - Added `GENERATE_LATEX = NO`
 - Added `DOT_MULTI_TARGETS = YES`

Anyone use the PDF manuals?

**Comment by OlegHahm** [comment]
For the record: I'm only using HTML (and of course the source itself).

**Comment by authmillenon** [comment]
> I am not.

Me neither.

> Anyone use the PDF manuals?

Nope

> For the record: I'm only using HTML (and of course the source itself).

Me too :D

**Comment by haukepetersen** [comment]
Thinking out loud: is there a way to include doxyfiles from other doxyfiles? Then we could just build html by default, but add targets for pdf/latex, e.g. `make doc-latex` or something...

**Comment by gebart** [comment]
I looked for such an option but I didn't find anything. I guess we could
cat together pieces of configs to stdout or a temp file but I didn't bother
adding it in the makefile.

**Comment by haukepetersen** [comment]
sounds overcomplicated to me... If there is no easy solution for now, I would say we go with this PR as-is. Maybe we could just create a quick issue as `feature-request` or `possible improvement` for others to pick up?

**Pull request merged**
