### PR TITLE
core: remove needless thread creation checks in kernel_init

### PR DESCRIPTION
**Pull request by kaspar030**
Can anyone remember ever seeing those messages?

### CODE REVIEW

**Comment by kaspar030** [comment]
Saves >100b text on 32bit platforms...

```
text	data	bss	dec	BOARD/BINDIRBASE

-116	0	0	-116	airfy-beacon
8276	112	2688	11076	oldbin
8160	112	2688	10960	newbin

-116	0	0	-116	arduino-due
8556	116	2764	11436	oldbin
8440	116	2764	11320	newbin

-28	-82	0	-110	arduino-mega2560
8090	220	770	9080	oldbin
8062	138	770	8970	newbin

-128	0	0	-128	avsextrem
39248	2232	96069	137549	oldbin
39120	2232	96069	137421	newbin

-116	0	0	-116	cc2538dk
8068	112	2688	10868	oldbin
7952	112	2688	10752	newbin

ERR	ERR	ERR	ERR	chronos
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

-116	0	0	-116	ek-lm4f120xl
8068	112	2728	10908	oldbin
7952	112	2728	10792	newbin

-116	0	0	-116	f4vi1
9588	116	2700	12404	oldbin
9472	116	2700	12288	newbin

-116	0	0	-116	fox
9888	112	2704	12704	oldbin
9772	112	2704	12588	newbin

-116	0	0	-116	frdm-k64f
8012	1140	4820	13972	oldbin
7896	1140	4820	13856	newbin

-116	0	0	-116	iot-lab_M3
9916	112	2704	12732	oldbin
9800	112	2704	12616	newbin

-116	0	0	-116	mbed_lpc1768
7888	112	2712	10712	oldbin
7772	112	2712	10596	newbin

ERR	ERR	ERR	ERR	msb-430
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

ERR	ERR	ERR	ERR	msb-430h
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

-136	0	0	-136	msba2
38912	2232	96069	137213	oldbin
38776	2232	96069	137077	newbin

-116	0	0	-116	msbiot
9868	116	2724	12708	oldbin
9752	116	2724	12592	newbin

-116	0	0	-116	mulle
10064	1164	4564	15792	oldbin
9948	1164	4564	15676	newbin

-120	0	0	-120	native
24548	396	51872	76816	oldbin
24428	396	51872	76696	newbin

-116	0	0	-116	nrf51dongle
8300	112	2688	11100	oldbin
8184	112	2688	10984	newbin

-116	0	0	-116	nucleo-f091
11460	112	2712	14284	oldbin
11344	112	2712	14168	newbin

-116	0	0	-116	nucleo-f303
9544	112	2720	12376	oldbin
9428	112	2720	12260	newbin

-116	0	0	-116	nucleo-f334
9288	112	2696	12096	oldbin
9172	112	2696	11980	newbin

-116	0	0	-116	nucleo-l1
9496	112	2704	12312	oldbin
9380	112	2704	12196	newbin

-116	0	0	-116	openmote
8020	112	2688	10820	oldbin
7904	112	2688	10704	newbin

-116	0	0	-116	pba-d-01-kw2x
8080	1140	4204	13424	oldbin
7964	1140	4204	13308	newbin

-116	0	0	-116	pca10000
8300	112	2688	11100	oldbin
8184	112	2688	10984	newbin

-116	0	0	-116	pca10005
8280	112	2688	11080	oldbin
8164	112	2688	10964	newbin

-128	0	0	-128	pttu
39456	2232	96069	137757	oldbin
39328	2232	96069	137629	newbin

-122	0	0	-122	qemu-i386
127773	5468	76436	209677	oldbin
127651	5468	76436	209555	newbin

-144	0	0	-144	redbee-econotag
40296	2264	8972	51532	oldbin
40152	2264	8972	51388	newbin

-116	0	0	-116	saml21-xpro
8280	112	2792	11184	oldbin
8164	112	2792	11068	newbin

-116	0	0	-116	samr21-xpro
8444	112	2680	11236	oldbin
8328	112	2680	11120	newbin

-116	0	0	-116	spark-core
9944	112	2704	12760	oldbin
9828	112	2704	12644	newbin

-116	0	0	-116	stm32f0discovery
11464	112	2712	14288	oldbin
11348	112	2712	14172	newbin

-116	0	0	-116	stm32f3discovery
9548	112	2720	12380	oldbin
9432	112	2720	12264	newbin

-116	0	0	-116	stm32f4discovery
9752	116	2716	12584	oldbin
9636	116	2716	12468	newbin

ERR	ERR	ERR	ERR	telosb
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

-116	0	0	-116	udoo
8556	116	2764	11436	oldbin
8440	116	2764	11320	newbin

ERR	ERR	ERR	ERR	wsn430-v1_3b
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

ERR	ERR	ERR	ERR	wsn430-v1_4
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin

-116	0	0	-116	yunjia-nrf51822
8264	112	2688	11064	oldbin
8148	112	2688	10948	newbin

ERR	ERR	ERR	ERR	z1
ERR	ERR	ERR	ERR	oldbin
ERR	ERR	ERR	ERR	newbin
```

**Comment by Kijewski** [comment]
The check was in there since the very first commit of our current repo. :)
Ack. the test is nonsensical.

**Comment by authmillenon** [comment]
And go.

**Comment by OlegHahm** [comment]
Nice catch!

**Pull request merged**
