### PR TITLE
riotctrl_shell.gnrc: remove superfluous quotation marks

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
`flake8` and `pytest` were warning about this but the first was suppressed and the latter ignored because the problem was not really obvious for tired eyes :sleepy:. 

### Testing procedure
```sh
cd dist/pythonlibs/riotctrl_shell
tox
```

passes

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
It just causes a warning in the framework, so I don't believe this requires a backport.

**Comment by jia200x** [comment]
it passes:
```

======================================================================================= 107 passed in 0.38s ========================================================================================
flake8 installed: flake8==3.8.3,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0
flake8 run-test-pre: PYTHONHASHSEED='1884842537'
flake8 run-test: commands[0] | flake8 .
_____________________________________________________________________________________________ summary ______________________________________________________________________________________________
  test: commands succeeded
  flake8: commands succeeded
  congratulations :)
```

**Comment by jia200x** [comment]
I would click the merge button with a lot of joy, but unfortunately the GH interface doesn't seem to work :(

**Comment by miri64** [comment]
> I would click the merge button with a lot of joy, but unfortunately the GH interface doesn't seem to work :(

let's see if a retrigger of one of the checks helps.

**Comment by miri64** [comment]
Backport provided in #14526

**Pull request merged**
