### PR TITLE
[take-over] boards/omote: add support for OMote board

### PR DESCRIPTION
**Pull request by jia200x**
# Take over PR from #14552
(see https://github.com/RIOT-OS/RIOT/pull/14552#issuecomment-669974743)

### Contribution description

Features

    • ARM cortex-M3 
    • Transceiver with PCB Antenna
    • on board sensors BMP180,ADXL345 and LDR
    • Programming over BSL
    • User LEDs and Power LEDs
    • User, BSL and reset Buttons 
    • on-board 3.3V and 5V Power output
    • Peripherals- UART, GPIO, I2C and SPI, ADC
    • RF 2.4GHz built-in in CC2538

sales@oppila.in – Oppila Microsystems pvt ltd Banglore

### CODE REVIEW

**Comment by benpicco** [comment]
Travis found an issue - just squash directly.

**Comment by jia200x** [comment]
it seems Doxygen didn't like the `bash` tag for triple quotes :/

**Comment by miri64** [comment]
> it seems Doxygen didn't like the `bash` tag for triple quotes :/

No, for doxygen markdown only `~~~~~~~ {.sh}` is acceptable.

**Comment by jia200x** [comment]
I just left it with simple triple quotes

**Comment by benpicco** [comment]
Looks kike the board's `Kconfig` and `lua_repl`'s `Makefile.ci` needs an update.

**Comment by jia200x** [comment]
done

**Comment by benpicco** [comment]
Travis is unhappy

**Comment by Oppila-Microsystems** [comment]
hello 

i would like to update the platform name, so could you please help me modify it

**Pull request merged**
