### PR TITLE
tools/packer: update vagrant image to Ubuntu 18.04 + refactoring

### LINKED ISSUE #12674: vagrant: Update to Ubuntu 18.04
Our Vagrantfile currently points to the Ubuntu 16.04 release, while our Docker points to 18.04 and our buildsystem also assumes more up-to-date toolchains. Should we update that image to Ubuntu 18.04?

### LINKED ISSUE #13015: Quickest start does not build with vagrant
#### Description
Build of [https://doc.riot-os.org/index.html#the-quickest-start](url)
fails with message
```
Building application "default" for "native" with MCU "native".

gcc: error: unrecognized command line option '-Wformat-overflow'
gcc: error: unrecognized command line option '-Wformat-truncation'
```
#### Steps to reproduce the issue
```
vagrant up
vagrant ssh
git clone https://github.com/RIOT-OS/RIOT RIOT.cloned
cd RIOT.cloned
git checkout 2019.10-branch
cd examples/default/
make all
```

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is a rework of the packer scripts used to generate the Vagrant image.

There are several things changed:
- The vagrant image is built on an Ubuntu 18.04 base
- All toolchains are installed in the image (ARM, AVR, ESP32, ESP8266, MIPS, MSP430 and RISCV)
- A fairly recent version of openocd is installed
- A more complete list of usb filters is preconfigured in the VM : the boards are automatically bypassed to the VM when plugged on the host computer
- Udev rules are configured during the VM build
- The main vagrantfile is also updated: the default user name is `user` (and not `vagrant`)

The only thing that remains is to publish the new box to vagrantcloud and I don't have access to this (my account is `riot-course`).

### Testing procedure

- install [packer](https://packer.io/) and [vagrant](https://www.vagrantup.com/)
- cd in dist/tools/packer and run:
```
$ cd ${RIOTBASE}/dist/tools/packer
$ packer build riot.json
```
- wait a bit
- import the vagrant box
```
$ vagrant box add RIOT/ubuntu1804 RIOT-VM_virtualbox.box
```
- start the VM and ssh to it:
```
$ cd ${RIOTBASE}
$ vagrant up
$ vagrant ssh
```
- Plug a board, compile, flash, term, etc

### Issues/PRs references

This should fix #13015 and fix #12674

### CODE REVIEW

**Comment by smlng** [comment]
Tested on MacOS, or tried to and got an error:

```
VBoxManage: error: Unknown option: --clipboard
```

seems to be related to this: https://github.com/hashicorp/vagrant/issues/11288

my versions:
- vbox: 6.1.2r135662
- packer: 1.5.1

**Comment by aabadie** [comment]
> Tested on MacOS, or tried to and got an error:

Thanks for testing. There are 2 options to fix them:
1. I remove the `--clipboard` option used to build the VM (see [here](https://github.com/RIOT-OS/RIOT/pull/13316/files#diff-37a59ac3dadc6d27ae874a3f39fa1729R52))
2. You downgrade to virtualbox 6.0, since from the link you provide, it seems that this option has been changed in 6.1...

I would go for option 1, because I think it useless with a headless VM. What do you think ?

**Comment by smlng** [comment]
I think downgrade is not very future proof, so yes remove the option. Or is it possible to have a condition based on the vbox version, i.e. use old variant for vbox <= 6.0 and fix/change option to new variant for vbox 6.1 and above? I'm not sure if packer can do this.

**Comment by aabadie** [comment]
> Or is it possible to have a condition based on the vbox version

After looking at [the documentation](https://packer.io/docs/builders/virtualbox-iso.html#vboxmanage-commands), it doesn't seem to be possible. The only variable available is `Name` which the VM name. Maybe I missed something though.

So I pushed a fixup commit that removes the use of this option.

**Comment by smlng** [comment]
looking good now, tested build and then run the image, plus some builds. 

During the packer build of the vbox image, I saw this error a couple of time when python stuff is installed via pip:

```
virtualbox-iso: The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

don't know if we want or can do something about it?!

Again: looks good otherwise, and seems to work. Would still be nice if someone else could verify this on Linux (and Windows?). @cgundogan

**Comment by aabadie** [comment]
> don't know if we want or can do something about it?

Yes these messages are weird but in the end the Python packages are usable.

**Comment by KerbenII** [comment]
Hi @aabadie ,
You can use one of the workaround (for example this: https://github.com/hashicorp/vagrant/issues/4649#issuecomment-349933328 ) in order to determine VirtualBox version, and based on it determine if we should execute:

`    virtualbox.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
`
or
`    virtualbox.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
`

**Comment by aabadie** [comment]
> During the packer build of the vbox image, I saw this error a couple of time when python stuff is installed via pip:

I have a workaround for this problem: install Python packages in user home directory and the message is gone.

> You can use one of the workaround

IUUC, the proposed workaround can only go in the Vagrantfile. I'm not against that but is it worth for the clipboard option (knowing that the VM is configured and used headless) ?

**Comment by KerbenII** [comment]
> IUUC, the proposed workaround can only go in the Vagrantfile. I'm not against that but is it worth for the clipboard option (knowing that the VM is configured and used headless) ?

IYAM, that option should just be removed from image's Vagrantfile and enduser should add it once needed.
 Right now I am e.g. overriding v.gui = false (default value), because image creator changed this in his Vagrantfile.

**Comment by aabadie** [comment]
> that option should just be removed from image's Vagrantfile and enduser should add it once needed.

I agree, I removed it.

**Comment by aabadie** [comment]
I rebuilt the VM locally with the latest version of this PR: 
- no more pip cache messages
- basic behavior still working
- tooling is quite complete, output of `make print-versions`:
```
Operating System Environment
----------------------------
         Operating System: "Ubuntu" "18.04.4 LTS (Bionic Beaver)"
                   Kernel: Linux 4.15.0-55-generic x86_64 x86_64
             System shell: /bin/dash (probably dash)
             make's shell: /bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
                  avr-gcc: avr-gcc (GCC) 5.4.0
         mips-mti-elf-gcc: mips-mti-elf-gcc (Codescape GNU Tools 2018.09-03 for MIPS MTI Bare Metal) 6.3.0
               msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
     riscv-none-embed-gcc: riscv-none-embed-gcc (GNU MCU Eclipse RISC-V Embedded GCC, 64-bit) 8.2.0
     xtensa-esp32-elf-gcc: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
   xtensa-esp8266-elf-gcc: xtensa-esp8266-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
                    clang: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.1.0"
      mips-mti-elf-newlib: "2.5.0"
  riscv-none-embed-newlib: "3.0.0"
  xtensa-esp32-elf-newlib: "2.2.0"
xtensa-esp8266-elf-newlib: "2.2.0"
                 avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                   ccache: ccache version 3.4.1
                    cmake: cmake version 3.10.2
                 cppcheck: Cppcheck 1.82
                  doxygen: 1.8.13
                      git: git version 2.17.1
                     make: GNU Make 4.1
                  openocd: Open On-Chip Debugger 0.10.0+dev-01047-g09ac9ab1 (2020-02-13-15:37)
                   python: Python 2.7.17
                  python2: Python 2.7.17
                  python3: Python 3.6.9
                   flake8: 3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.9 on Linux
               coccinelle: spatch version 1.0.4 with Python support and with PCRE support
```

**Comment by smlng** [comment]
looking good, please squash

**Comment by aabadie** [comment]
Squashed!

**Comment by aabadie** [comment]
Before merging, we have to make sure that the new vagrant box is available on [vagrantcloud](https://app.vagrantup.com/RIOT). I don't have access to the RIOT account and I don't know who can do that.

**Comment by smlng** [comment]
@cgundogan did the original one, so maybe he can push the new box and ACK+Merge this one afterwards?!?

**Comment by cgundogan** [comment]
I cannot build the image due to the below issue.

> rm -rf packer_cache && packer build riot.json

```sh
dist/tools/packer % packer build riot.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso
==> virtualbox-iso: /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso => RIOT/dist/tools/packer/packer_cache/619ead18d4ff0ca0d3233f2f405bb9bb5924502e.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying iso/ubuntu-18.04.3-server-amd64.iso
==> virtualbox-iso: Trying iso/ubuntu-18.04.3-server-amd64.iso?checksum=sha256%3A7d8e0055d663bffa27c1718685085626cb59346e7626ba3d3f476322271f573e
==> virtualbox-iso: Download failed source path error: stat RIOT/dist/tools/packer/iso/ubuntu-18.04.3-server-amd64.iso: no such file or directory
==> virtualbox-iso: Trying http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04.3-server-amd64.iso
==> virtualbox-iso: Trying http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04.3-server-amd64.iso?checksum=sha256%3A7d8e0055d663bffa27c1718685085626cb59346e7626ba3d3f476322271f573e
==> virtualbox-iso: Download failed bad response code: 404
==> virtualbox-iso: error downloading ISO: [source path error: stat RIOT/dist/tools/packer/iso/ubuntu-18.04.3-server-amd64.iso: no such file or directory bad response code: 404]
Build 'virtualbox-iso' errored: error downloading ISO: [source path error: stat RIOT/dist/tools/packer/iso/ubuntu-18.04.3-server-amd64.iso: no such file or directory bad response code: 404]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: error downloading ISO: [source path error: stat RIOT/dist/tools/packer/iso/ubuntu-18.04.3-server-amd64.iso: no such file or directory bad response code: 404]

==> Builds finished but no artifacts were created.
```

**Comment by aabadie** [comment]
> I cannot build the image due to the below issue.

Thanks for testing. A new image (18.04.4) is available for download but the previous one (18.04.3) is not anymore.
I updated the version and checksum. The build seems to work (still in progress). Can you try again ?

**Comment by cgundogan** [comment]
@aabadie thanks for this quick fix. I was able to build the image successfully and then uploaded it to vagrantcloud. Could you try with `vagrant up` on this PR?

**Comment by aabadie** [comment]
>  successfully and then uploaded it to vagrantcloud. 

The download should work from vagrantcloud (but is very slow from the place I am at the moment ;))

```
$ vagrant up
Bringing machine 'RIOT-VM' up with 'virtualbox' provider...
==> RIOT-VM: Box 'RIOT/ubuntu1804' could not be found. Attempting to find and install...
    RIOT-VM: Box Provider: virtualbox
    RIOT-VM: Box Version: >= 0
==> RIOT-VM: Loading metadata for box 'RIOT/ubuntu1804'
    RIOT-VM: URL: https://vagrantcloud.com/RIOT/ubuntu1804
==> RIOT-VM: Adding box 'RIOT/ubuntu1804' (v0.0.1) for provider: virtualbox
    RIOT-VM: Downloading: https://vagrantcloud.com/RIOT/boxes/ubuntu1804/versions/0.0.1/providers/virtualbox.box
    RIOT-VM: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
```

I'll squash this PR.

**Pull request merged**
