### PR TITLE
README.md: comment out ASCII art

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This serves as an alternative proposal to https://github.com/RIOT-OS/RIOT/pull/15143.

### Testing procedure
Read the new README (in rendered and unrendered version)

### Issues/PRs references
Alternative to #15143

### CODE REVIEW

**Comment by miri64** [comment]
Why I proposed this alternative: I don't think people _only_ will see first RIOT via the Github landing page. The simplest examples that, in the future, we provide the latest tar ball on our website, as many open source projects do or forks on non-Github pages. The more speculative (but based on past experiences not unfounded) example is, that we might not always be on Github or use Git. There is always the possibility that there will be a newer, shinier VCS in the future, that everybody will run to.

**Comment by benpicco** [comment]
I'd ACK if you also replace it with the RIOT logo as an image so the repo landing page is not so deserted for web viewers. 

> I don't think people only will see RIOT first via the Github landing page.

I would dispute that. I personally rather view the GitHub page of a project to get my first Impression than the website.
Also the riot-os.org website is not exactly well maintained (comparing against TinyOS and Contiki? No mention of Zephyr or Mbed?) and History stops in 2013.

**Comment by miri64** [comment]
> I'd ACK if you also replace it with the RIOT logo as an image so the repo landing page is not so deserted for web viewers.

This I rather would put in a separate PR, TBH, as a follow-up to either this PR or #15143, whichever will get merged (first), as I think the SVG discussion is one of its own. There I agree with https://github.com/RIOT-OS/RIOT/pull/15143#issuecomment-715242112 that it does not hurt to not have the logo for a few days or so.

**Comment by miri64** [comment]
> Also the riot-os.org website is not exactly well maintained (comparing against TinyOS and Contiki? No mention of Zephyr or Mbed?) and History stops in 2013.

A completely different can of worms again ;-). Hopefully, this will change in the future.

**Comment by miri64** [comment]
> > I don't think people only will see RIOT first via the Github landing page.
> 
> I would dispute that. I personally rather view the GitHub page of a project to get my first Impression than the website.

But you are a coder, and you probably also look for the quality of code to get a first impression, I presume.

**Comment by benpicco** [comment]
> But you are a coder, and you probably also look for the quality of code to get a first impression, I presume.

Well RIOT is not much use to non-coders :wink: It provides a framework, no finished application.

**Comment by miri64** [comment]
> > But you are a coder, and you probably also look for the quality of code to get a first impression, I presume.
> 
> Well RIOT is not much use to non-coders wink It provides a framework, no finished application.

Nevertheless a manager might want to look at some material first before they let their coders have a go ;-).

**Comment by LordTy** [comment]
> I don't think people _only_ will see RIOT first via the Github landing page.

To be fair, the Github page is my primary starting point for any documentation with relation to RIOT.
for Questions like "is a cpu/board supported", "How was this example implemented".
I do off course use links to documentation/other documents provided in the readme, but I always start at the Github page.
This may be due to the fact that Riot-os.org is just less usefull.

**Comment by miri64** [comment]
This discussion got somewhat stalled. Now that the riot-os.org issue is fixed, how about we talk about this again ;-).

**Comment by miri64** [comment]
Seems like we would [not be the only ones who hide but celebrate ASCII art](https://gizmodo.com/some-of-the-best-easter-eggs-hidden-in-sites-across-the-1847035175)

**Comment by miri64** [comment]
#16856 is nearly merged so closing this one.

**Pull request closed without merging**
