### PR TITLE
ipv6: make all netif flags obey 8 bit width

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
Otherway around please: make flags 16-bit number. #3049 introduces more flags. and 8-bit just won't cut it.

**Comment by authmillenon** [comment]
Sorry… looked at the wrong struct. They are already 16-bit, so this PR is invalid.

**Comment by OlegHahm** [comment]
Ah, yes, sorry, I think I confused this already while reviewing the PR that introduced them.

**Comment by OlegHahm** [comment]
Why I looked at them in the first place: I was wondering if we could these flags to store information, about being multicast, link-local, site-local and so on to save some code space and run time. What's your opinion on this?

**Comment by authmillenon** [comment]
Again: these flags are for the interface, not the addresses registered to the interface ;-). But in general for address flags: I'm in for it. It was even in my original draft for `ng_ipv6_netif` (as it was - not that fine-granular, but still - in `net_if` too). `NG_IPV6_NETIF_FLAGS_NON_UNICAST` is basically what's left of this, since anycast is the only address type where you *have* to flag it on the interface. But if it reduces code-size we can try it this way :-).

**Comment by OlegHahm** [comment]
Yes, I was talking about netif_addr flags. Will PR something then.

**Comment by OlegHahm** [comment]
Hm, apparently my assumption that one can save code space this way was wrong, because it would only work for addresses assigned to an interface.

**Comment by Kijewski** [comment]
((Am I the only one who thinks that discussions in "closed" PRs are odd?))

**Pull request closed without merging**
