### PR TITLE
 nrf5x_common: gpio: fix port 1 functionality 

### PR DESCRIPTION
**Pull request by silkeh**
### Contribution description

This PR fixes the functionality of the port 1 GPIO pins on the NRF5 platforms (mainly the nRF52840).
There used to be an unused function for this, which was removed in #9699.
This PR reverts that change, and makes use of the function to ensure functionality of port 1.

### Testing procedure

With this PR the `gpio`-functions work with pins on port 1.

### Issues/PRs references

Reverts #9699

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@SemjonKerner can you have a look at this and test it?

**Comment by aabadie** [comment]
I tested this PR with #9833 and it indeed fixes the problem I reported there with the on-board button (which uses port 1).

**Comment by aabadie** [comment]
I enabled Murdock because I think this PR is OK. But it would be great to also have @haukepetersen's opinion before merging it.

**Comment by haukepetersen** [comment]
Nice catch!

Could somebody please also quickly run the GPIO benchmark (`bench` shell command in the `tests/periph_gpio` test application) with this PR and maybe a `nrf52dk`, so we can see if this PR does actually not influence the runtime performance for 1-port nrf CPUs?! If it does change something, we probably want to use a slightly different structure for this PR (e.g. something macro based...).

**Comment by bergzand** [comment]
Tested the `tests/periph_gpio` on an nrf52dk:
current master (917548f37ce268cf03a044c3e1bf2af8cd15e5c9):
```
> bench 0 1
2018-10-17 15:40:53,436 - INFO #  bench 0 1
2018-10-17 15:40:53,437 - INFO # 
2018-10-17 15:40:53,440 - INFO # GPIO driver run-time performance benchmark
2018-10-17 15:40:53,441 - INFO # 
2018-10-17 15:40:53,560 - INFO #                  nop loop:    109376us  ---   0.109us per call  ---    9142773 calls per sec
2018-10-17 15:40:53,865 - INFO #                  gpio_set:    296876us  ---   0.296us per call  ---    3368409 calls per sec
2018-10-17 15:40:54,122 - INFO #                gpio_clear:    250001us  ---   0.250us per call  ---    3999984 calls per sec
2018-10-17 15:40:54,425 - INFO #               gpio_toggle:    296877us  ---   0.296us per call  ---    3368398 calls per sec
2018-10-17 15:40:54,856 - INFO #                 gpio_read:    421876us  ---   0.421us per call  ---    2370364 calls per sec
2018-10-17 15:40:55,131 - INFO #                gpio_write:    265626us  ---   0.265us per call  ---    3764691 calls per sec
2018-10-17 15:40:55,133 - INFO # 
2018-10-17 15:40:55,136 - INFO #  --- DONE ---
```

With this PR merged on top:
```
> bench 0 1
2018-10-17 15:42:06,996 - INFO #  bench 0 1
2018-10-17 15:42:06,997 - INFO # 
2018-10-17 15:42:07,001 - INFO # GPIO driver run-time performance benchmark
2018-10-17 15:42:07,001 - INFO # 
2018-10-17 15:42:07,118 - INFO #                  nop loop:    109376us  ---   0.109us per call  ---    9142773 calls per sec
2018-10-17 15:42:07,422 - INFO #                  gpio_set:    296876us  ---   0.296us per call  ---    3368409 calls per sec
2018-10-17 15:42:07,681 - INFO #                gpio_clear:    250001us  ---   0.250us per call  ---    3999984 calls per sec
2018-10-17 15:42:07,988 - INFO #               gpio_toggle:    296876us  ---   0.296us per call  ---    3368409 calls per sec
2018-10-17 15:42:08,415 - INFO #                 gpio_read:    421876us  ---   0.421us per call  ---    2370364 calls per sec
2018-10-17 15:42:08,689 - INFO #                gpio_write:    265626us  ---   0.265us per call  ---    3764691 calls per sec
2018-10-17 15:42:08,690 - INFO # 
2018-10-17 15:42:08,692 - INFO #  --- DONE ---
```

Also confirmed with cosy that the gpio.o object files both result in 328B flash

**Comment by haukepetersen** [comment]
awesome, thanks for verifying this, I guess this PR is ready to go then, right?!

@aabadie I hope you are ok that I set the `3-testing` label in your name...

**Comment by haukepetersen** [comment]
all green -> go

@silkeh thanks for the fix, I guess that one was on me :-)

**Comment by aabadie** [comment]
Thanks @haukepetersen :)

**Pull request merged**
