### PR TITLE
static-tests: provide optional JSON output

### PR DESCRIPTION
**Pull request by miri64**
Some first steps towards output beautification on Murdock2.

It is thinkable to provide a similar feature for the sub-scripts, but for now let's focus on the main script

### CODE REVIEW

**Comment by kaspar030** [comment]
Instead of hacking json-output into ```build_and_test.sh```, why don't we just split up the calls to the different check scripts into seperate murdock jobs? They'd be json'ized for free...

**Comment by miri64** [comment]
But then we have to do double the work if we want to add new static tests.

**Comment by aabadie** [comment]
@miri64 @kaspar030, is this one still useful with the new CI ?

**Comment by miri64** [comment]
I actually wrote it for the new CI, to someday have a nicer view then just the terminal dump on the results.

**Comment by miri64** [comment]
Closing for now.

**Pull request closed without merging**
