### PR TITLE
gnrc_ipv6_nib: disable router advertisements on interface startup

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Router Advertisements are enabled automatically for routing nodes as soon as they obtain a prefix (e.g. via DHCPv6, UHCP, …).

Enabling router advertisements without a prefix to advertise is wrong and causes no router solicitations to be send on an upstream interface.

Also from https://www.rfc-editor.org/rfc/rfc4861#section-6.2.1

	Note that AdvSendAdvertisements MUST be FALSE by
	default so that a node will not accidentally start
	acting as a router unless it is explicitly
	configured by system management to send Router
	Advertisements.

### Testing procedure

`examples/gnrc_networking` does now instantly obtain an address on a network with an upstream router.

`examples/gnrc_border_router` had this disabled already because an automatic prefix configuration method was used. 

`tests/net/gnrc_rpl` shows that RPL operation is not affected.

### CODE REVIEW

**Comment by miri64** [comment]
How is the RTR_ADV flag set now? When the interface has `isRouter` set and when it has a prefix assigned?

**Comment by benpicco** [comment]
> How is the RTR_ADV flag set now?

`gnrc_ipv6_nib_change_rtr_adv_iface()` is called by `dhcpv6_client_ia_pd`, `gnrc_uhcp`, `gnrc_ipv6_auto_subnets` and `gnrc_ipv6_static_addr` when a prefix is added to a downstream/advertising interface.

If a prefix is added manually with `ifconfig`, the `RTR_ADV` flag now also has to be set manually.

**Comment by miri64** [comment]
> `gnrc_ipv6_nib_change_rtr_adv_iface()` is called by `dhcpv6_client_ia_pd`, `gnrc_uhcp`, `gnrc_ipv6_auto_subnets` and `gnrc_ipv6_static_addr` when a prefix is added to a downstream/advertising interface. (That's why those modules would set `CONFIG_GNRC_IPV6_NIB_ADV_ROUTER` to 0 already)

So not when a prefix is configured by a router advertisement? How will downstream nodes (e.g. in a RPL) have this flag set now?

**Comment by miri64** [comment]
RPL might be a bad example, since it has its own prefix delegation mechanism, but the question stands: will a downstream router set this flag, once it obtains a prefix from upstream?

**Comment by benpicco** [comment]
What good does it do if a downstream router sets this flag if it has no way to route the packets? (Ok, upstream routes will always work, but how will e.g. the border router know it has to route a packet to the downstream router via the next hop router?)

**Comment by miri64** [comment]
> What good does it do if a downstream router sets this flag if it has no way to route the packets? (Ok, upstream routes will always work, but how will e.g. the border router know it has to route a packet to the downstream router via the next hop router?)

That's what a routing protocol is for. But if it is not enabled for a router, the current state seems to be broken. This should be fixed, before this PR introduces that regression.

**Comment by benpicco** [comment]
> That's what a routing protocol is for.

But then IMHO it should still only be enabled if that routing protocol (which one? we only have RPL) is active.

Having routers send router advertisements for prefixes that they can't route just leads to chaos.

**Comment by miri64** [comment]
> Having routers send router advertisements for prefixes that they can't route just leads to chaos.

_with_ prefixes, not _for_ ;-).

The question is: Shouldn't let the routing protocol leave such a central functionality. This may well lead to technical debt with contributors wondering why routers don't advertise themselves as routers.

Also: We still don't have RPL routers that advertise themselves as routers, if I understand your previous statement correctly.

**Comment by benpicco** [comment]
Ok so RPL still needs `RTR_ADV` enabled - maybe that's all the heuristic we need.
It doesn't make sense to send router advertisements if we can't route things, so only enabling it on an interface where RPL is configured sounds like it would make sense.

**Review by miri64 — APPROVED** [review]
ACK, but only if you handle the tickets that will inevitably come from routing protocol implementors/users ;-P

**Comment by benpicco** [comment]
If there is some external user implementing an out-of-tree routing protocol, they can just call `gnrc_ipv6_nib_change_rtr_adv_iface()` - but I'll mark it as an API change so it shows up in the release notes.

**Comment by miri64** [comment]
> they can just call `gnrc_ipv6_nib_change_rtr_adv_iface()`

Might be a bit clunky if it is a UDP-based routing protocol on top of `sock` (dusting of ye good olde AODV2), but let's address this, if it comes to it.

**Comment by miri64** [comment]
bors merge

**Comment by miri64** [comment]
bors merge

**Comment by benpicco** [comment]
Looks like my confusion is not completely unwarranted:

> Thus, multihop prefix distribution (the ABRO) and the 6LoWPAN Context Option (6CO) for distributing header compression contexts go hand in hand.  If substitution is intended for one of them, then both of them MUST be substituted.

 - [RFC6775](https://www.rfc-editor.org/rfc/rfc6775.html#section-1.4)

So when we distribute the prefix via RPL message, we wouldn't need to do multihop prefix distribution. And while compression contexts sure would be helpful on the RPL side (DIO contains a list of full 128 bit IPv6 addresses), the only reference I found is an [expired draft](https://datatracker.ietf.org/doc/draft-turner-roll-dio-ctx/) - or did I miss something there?

**Pull request merged**
