### PR TITLE
cpu: let spi_init_slave() stubs return error codes

### PR DESCRIPTION
**Pull request by sgso**
When you think your samr21 is a slave but is actually doing nothing...

### CODE REVIEW

**Comment by bapclenet** [comment]
ACK this PR, will wait the release before merging it except if @OlegHahm wants to merge it now as it is a bug fixing.

**Comment by haukepetersen** [comment]
how about a more radical approach: #3956?

**Comment by PeterKietzmann** [comment]
I think I prefer this PR, but it's no strong opinion.

**Comment by bapclenet** [comment]
@haukepetersen, let's merge this PR and you will continue the discussion on #3956

**Comment by bapclenet** [comment]
@OlegHahm, how to restart strider-cd/compile-test?

**Comment by PeterKietzmann** [comment]
@bapclenet at first you need to set the "Ready for CI build" label. Then you can click on "Details" right next to the line "continuous-integration/travis-ci/pr".  There (you need to be logged in with your github account because of your maintainer rights) you'll find a restart button somewhere in the upper right. It looks like a circular arrow

**Comment by PeterKietzmann** [comment]
Oh sorry. You asked for strider. AFAIK there is currently not way to restart it. Also I still don't trust strider 100% ATM. That's wait I'm still "just" going for Travis. Will start him now

**Comment by bapclenet** [comment]
@PeterKietzmann, ok thanks. I forgot to set Ready fo CI build last time I restart Travis anyway.

**Pull request merged**
