### PR TITLE
boards/nrf52*dk: Enable Pinreset after Flashing

### LINKED ISSUE #20775: cpu/nrf52: Add Make Option to Enable Pinreset
#### Description

In PR #10072, the `nrf52_resetpin_cfg` tool was introduced, allowing to program the persistent UICR register on the nRF52 boards.
Something must have changed since 2018, but when an nRF52 is programmed via the J-Link (not via bootloader), the UCIR register is _always_ reset and therefore the pinreset does not work anymore.

Usually the programming sequence is somewhat like this:
- Unlock (or recover) the device (this erases all of the Flash and the UICR, which holds the Pinreset configuration)
- Perform a chiperase
- Write the bin/hex
- Verify
- (optionally) write the UCIR
- on the first reset or power down, power up, the nRF has the readback protection enabled which you can only disable by "unlocking" or "recovering" the device, deleting Flash and UICR

`nrfjprog` shows the issue nicely. I try to read the UICR register after powering up an nRF52840DK board. It fails because the readback protection is activated. Then I recover the device, which deletes the Flash and UICR area. After that I can read out the UICR, but it is blank.
To see how it should look like, I activate the pinreset (without powering the device down in between!) and read it out again.

```
chris@ThinkPias:~$ nrfjprog --readuicr asdf.hex
[error] [ Client] - Encountered error -90: Command read_device_info executed for 2 milliseconds with result -90
[error] [ Worker] - Access protection is enabled, can't read device version.
[error] [ Client] - Encountered error -90: Command read_memory_descriptors executed for 2 milliseconds with result -90
[error] [ Worker] - Can't read memory descriptors, ap-protection is enabled.
ERROR: The operation attempted is unavailable due to readback protection in
ERROR: your device. Please use --recover to unlock the device.
NOTE: For additional output, try running again with logging enabled (--log).
NOTE: Any generated log error messages will be displayed.
chris@ThinkPias:~$ nrfjprog --recover
Recovering device. This operation might take 30s.
Erasing user code and UICR flash areas.
Writing image to disable ap protect.
chris@ThinkPias:~$ nrfjprog --readuicr asdf.hex
Storing data in 'asdf.hex'.


chris@ThinkPias:~$ nrfjprog --pinresetenable
Enabling pin reset.
chris@ThinkPias:~$ nrfjprog --readuicr asdf2.hex
Storing data in 'asdf2.hex'.
```

On the left side, the UICR is shown before enabling the pinreset and on the right side it is shown after the pinreset.
UICR before and after pinresetenable

Programming with J-Link is pretty much the same, but `nrfjprog` is a lot more verbose about what it does and why it does (or does not) do something.

So essentially what I want to say is that it would be nice to be able to activate the Pinreset when flashing a RIOT image with `make flash`.
@benpicco proposed a software based solution in #19833, but the nRF52s do have the Pinreset registers in UICR, so why not use them? (However I am still in favor of merging that PR, it is nice to have a software option as well.)

Now... the thing is that with `nrfjprog` it is very easy to activate the Pinreset, just call `nrfjprog --pinresetenable` after programming (and before the first reset). With J-Link it is not so easy because it does not have a dedicated option to do it.
In general I see two main possibilities:
1) Create a `JLINK_POST_FLASH` define for dist/tools/jlink.sh, that writes the right values into the UICR. So far nobody seems to use `JLINK_POST_FLASH` for anything.
2) Activate the pinreset with `nrfjprog`. This would require an additional dependency, which is probably not favorable.

<hr/>
Option 1 seems to work. The base address for the UICR register is 0x10001000 for the nRF52840 and the offset for of the PSELRESET registers is 0x200 and 0x204. Essentially I just copied the memory content from what `nrfjprog` puts into the registers.
Setting the registers with the J-Link programmer works when I add `JLINK_POST_FLASH` to the command like this:

```
JLINK_POST_FLASH='Write4 0x10001200 00000012 00000012' BOARD=nrf52840dk make flash term
```

We can check the burn file that is created by makefiles/tools/jlink.inc.mk has the right post-flash operation:

```
chris@ThinkPias:~/flashdev-riot/RIOT/examples/default$ cat bin/nrf52840dk/burn.seg 
loadfile /home/chris/SmartSensors/spacepatch-riot/RIOT/examples/default/bin/nrf52840dk/default.elf
Write4 0x10001200 00000012 00000012
r
g
exit
```

HOWEVER when I add `JLINK_POST_FLASH = Write4 0x10001200 00000012 00000012` to the boards/nrf52840dk/Makefile.include and just call `BOARD=nrf52840dk make flash term`, it does not work. What's odd though is that it _does_ work when I call `JLINK_POST_FLASH='' BOARD=nrf52840dk make flash term`.

Then I tried it with `JLINK_PRE_FLASH` because that is actually used by some boards, but it has the same behavior.

What's odd as well is that the 'stk3200' board, which uses `JLINK_PRE_FLASH` in it's boards/stk3200/Makefile.include shows the same behavior. Without adding `JLINK_PRE_FLASH=''` or similar to the command line, the `r` from the Makefile is not added to the burn.seg file.

Maybe someone has some guidance on that or generally some feedback about the approach.

### Useful links

Documentation about the UICR:
https://docs.nordicsemi.com/bundle/ps_nrf52832/page/uicr.html#register.PSELRESET-0

Documentation about the Pinreset (not very much unfortunately):
https://docs.nordicsemi.com/bundle/ps_nrf52832/page/power.html#d935e411

### PR DESCRIPTION
**Pull request by crasbe**
### Contribution description

As outlined in #20775, there was a silicon change in the nRF52 chips at some revision making the UICR register non-persistent. This means that the applied configuration is deleted when the flash is erased and programmed.
The reset pin is configured in this UICR register as well, so after flashing RIOT to (any) nRF52 chip without a bootloader, the reset pin won't work anymore.

This PR adds a JLINK_POST_FLASH command which configures the UICR->PSELRESET registers while the nRF52 chip is still unlocked from Flashing.

The JLINK_POST_FLASH variable is added to the builsystem sanity check as well, so it is evaluated alongside JLINK_PRE_FLASH. I'm not sure if that was required, but now it is consistent.

Request for comments: The documentation should be updated accordingly and the old tool in `dist/tools/nrf52_resetpin_cfg` is obsolete and could be deleted. This PR works with all silicon revisions of the nRF52 and the tool does not.
Should I do that in this PR or do a separate PR?

### Testing procedure

You can use any application you want and flash it to either a nRF52DK board (with the nRF52832DK) or an nRF52840DK from Nordic and press the Reset button.
The board should reset.

```
BOARD=nrf52dk make -C examples/default flash term
```

### Issues/PRs references

This fixes #20775.

### CODE REVIEW

**Comment by crasbe** [comment]
> Request for comments: The documentation should be updated accordingly and the old tool in `dist/tools/nrf52_resetpin_cfg` is obsolete and could be deleted. This PR works with all silicon revisions of the nRF52 and the tool does not.
> Should I do that in this PR or do a separate PR?

I am currently working on another PR that updates the nRF documentation (and checks off some points from the list in #20775).
Therefore it's probably best to remove the old tool in this PR (because it fits this one best), but only merge this PR after the documentation update. Then there is no step in between where the documentation is pointing to something that does not exist anymore.

**Comment by mguetschow** [comment]
Nice, thank you! Just tested this locally with an `nRF52840dk` of a newer revision, where the reset button doesn't work on `master`, and does with this PR.

> the old tool in `dist/tools/nrf52_resetpin_cfg` is obsolete and could be deleted. This PR works with all silicon revisions of the nRF52 and the tool does not.

For feature parity, we would need to support `BOARD=dwm1001` with this approach, too: https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/nrf52_resetpin_cfg/Makefile#L17

Also, this approach only works with `PROGRAMMER=jlink`, right? What about OpenOCD?

**Comment by crasbe** [comment]
> > the old tool in `dist/tools/nrf52_resetpin_cfg` is obsolete and could be deleted. This PR works with all silicon revisions of the nRF52 and the tool does not.
> 
> For feature parity, we would need to support `BOARD=dwm1001` with this approach, too: https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/nrf52_resetpin_cfg/Makefile#L17

That is interesting, I did not have the dwm1001 on my radar. The documentation of the dwm1001 does not mention the reset tool.
One board that I actually forgot was the waveshare-nrf52840-eval-kit (which is not part of the tool :D ).

> Also, this approach only works with `PROGRAMMER=jlink`, right? What about OpenOCD?

Yes, currently this only works with JLink. 

I tried to look into how to implement the UICR programming in OpenOCD, but currently OpenOCD does not work with the embedded JLink on the nRF52840. Maybe you can try it to see if it works for you?

Apparently, the new(er?) versions of the J-Link use a different product ID, which is not recognized by "libjaylink" which OpenOCD uses.

```
PROGARMMER=openocd BOARD=nrf52840dk make -C examples/hello-world flash
....

```

libjaylink v0.2.0 recognizes the following Product IDs (https://github.com/syntacore/libjaylink/blob/master/libjaylink/discovery_usb.c#L46-L65), and Segger J-Link firmware from "2024 Oct 9 11:01" uses 1060:
```

```

<hr/>

This is a good opportunity to remove the remarks about the OpenOCD version in `boards/common/nrf52/Makefile.include`.
Since version 0.11 (the current one is 0.12), the nRF52 devices are supported.
```
# setup OpenOCD for flashing. Version 0.10 of OpenOCD doesn't contain support
# for nrf52dk and nrf52840dk boards. To use OpenOCD with these a version
# build from source (master > 2018, August the 13rd) is required.
```

**Comment by crasbe** [comment]
Okay.. this is becoming a pretty deep rabbit hole, I'll open a separate issue about it.

**Comment by mguetschow** [comment]
> Okay.. this is becoming a pretty deep rabbit hole, I'll open a separate issue about it.

A proposal to move this forward for now without too much side-tracking:
1. Do not remove the `nrf52_resetpin_cfg` tool for now, as it still has the advantage that older revisions can be flashed and configured using openOCD. Update the tool's README mentioning that it only works for older revisions (the exact revision number was linked in #20775)
2. Update this to include all nRF52 boards with reset pin that are supported by RIOT and flashed with J-Link.
3. leave the rest to #20968

**Comment by crasbe** [comment]
Alright, that sounds like a good plan.

To point 3: Would you recommend doing a second PR with the OpenOCD fixes? That would probably make sense, right?

**Comment by mguetschow** [comment]
> To point 3: Would you recommend doing a second PR with the OpenOCD fixes? That would probably make sense, right?

I think so too, since it is pretty disjoint. Maybe the OpenOCD fixes could go first and then this PR could build on top of it and include the OpenOCD resetbutton configuration trick.

**Comment by crasbe** [comment]
I went through the RIOT Board list and this board appears to have a hardware reset button as well: https://doc.riot-os.org/group__boards__reel.html

I'll add the JLink and OpenOCD commands to that as well, after that I think this is ready to be merged.
Then I can open the Documentation PR, so we don't run into a hen-egg-problem.

**Comment by mguetschow** [comment]
Sounds good! Would you mind also addressing number 1 from [above](https://github.com/RIOT-OS/RIOT/pull/20965#issuecomment-2464694608)?

**Comment by crasbe** [comment]
> Sounds good! Would you mind also addressing number 1 from [above](https://github.com/RIOT-OS/RIOT/pull/20965#issuecomment-2464694608)?

Sure, I didn't notice the second part of that 😅

**Review by mguetschow — APPROVED** [review]
LGTM then, thanks a lot!

**Comment by maribu** [comment]
> added this pull request to the merge queue 6 hours ago

360 min is the timeout for the merge queue, I'll drop this from the queue and add it again to not waste a 3 hrs Murdock CI pass.

**Comment by crasbe** [comment]
Thanks everyone ❤️

**Pull request merged**
