### PR TITLE
core/lib: split kernel defines by its concerns

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

this splits kernel defines by its concerns to ease the use of its parts

### Testing procedure

read

### CODE REVIEW

**Comment by kaspar030** [comment]
how about we put them in one file per macro, named e.g., `macros/NO_RETURN.h`?

**Comment by kaspar030** [comment]
> thought about that - but then i saw we can keep the NORETURN from conflicting with similar macros defined in pkgs if we just split by general concern.

yes, but, if they're all in one file, I know which file to include. If they are split into files with the same name, I know which to include. 

But, if they're put into files according to "general concern", I have to grep a lot to find the right concern.
If I see `#include "compiler_hints.h"`, I don't know why that was included.
And, the "general concern" might be debatable - is `IS_CT_CONSTANT(x)` a "compiler hint"?

I think I'd like to trade the searching with longer include lists.

Any other opinions?

**Comment by kfessel** [comment]
I think I found a good split but also like get comments

`IS_CT_CONSTANT(expr)` may not be a hint to the compiler but from it :)

**Comment by kfessel** [comment]
`ARRAY_SIZE()` might not be well placed in `container.h`

**Review by benpicco — APPROVED** [review]
Looks good to me and `kernel_defines.h` include still gets the application all defines.

**Pull request merged**
