### PR TITLE
pkg: microcoap: bump version (ef27289, Feb 5 2016)

### PR DESCRIPTION
**Pull request by patgrosse**
The latest version of microcoap contains more CoAP content types (ct=...). The other changes are mainly comments and a small bugfix in the `coap_dumpHeader` function. The IPv6 changes to do apply to RIOT-OS since all changed files are deleted.

Addition: All changes can be found here: https://github.com/1248/microcoap/compare/9cb1dcda2182a8dca8483b230cda8b591a924c82...ef272895925f0d4c563725fe0102966f544a0fdc

### CODE REVIEW

**Comment by patgrosse** [comment]
I have no idea why the second build failed. The only "error" or "failure" I can find in the jenkins logs is from the initial git checkout:
```
error: The last gc run reported the following. Please correct the root cause
and remove gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.
```

**Comment by kaspar030** [comment]
please adjust the commit message (prefix with "pkg: microcoap:")

**Comment by aabadie** [comment]
This one looks good. @kaspar030, what do you think ?

**Comment by kaspar030** [comment]
Yes! @patgrosse sorry for the delay!

**Pull request merged**
