### PR TITLE
rpl_p2p: rm non-existing fib flag (backport)

### PR DESCRIPTION
**Pull request by cgundogan**
backprot of #5478

### CODE REVIEW

**Comment by BytesGalore** [comment]
ACK (obviously)

**Comment by BytesGalore** [comment]
something seems to go wrong with the `static-tests` just before `BUILD OUTPUT of group x86:`

**Comment by cgundogan** [comment]
that's "normal" for branches other than master (ping @kasp)

**Comment by cgundogan** [comment]
murdock does not agree - but that's OK for now for non-master merges. GO

**Pull request merged**
