### PR TITLE
dist: packer: update and add libudev-dev

### PR DESCRIPTION
**Pull request by cgundogan**
This PR updates the packer config to build ubuntu 16.04.**2** and to include `libudev-dev` for `edbg`.
I built the image using this PR and uploaded it to [1]. `vagrant up` should download the new box containing `libudev-dev`. A `vagrant destroy` may be necessary to delete the old box from the local cache.

[1] https://atlas.hashicorp.com/RIOT/boxes/ubuntu1604

### CODE REVIEW

**Comment by smlng** [comment]
sadly you have overwritten the previous box (v0.0.1) instead of creating a new version ...

**Comment by cgundogan** [comment]
>sadly you have overwritten the previous box (v0.0.1) instead of creating a new version ...

is this a hidden ACK?

**Comment by miri64** [comment]
I'm just testing the packer script. Please hold your horses ;-).

Retro-active question BTW: what was your reason to use packer (which as far as I can see is in non of the most popular linux distributions' package management systems) versus more conventional solutions like [puppet](https://puppet.com) or [CFEngine](https://cfengine.com/)?

**Comment by smlng** [comment]
> > sadly you have overwritten the previous box (v0.0.1) instead of creating a new version ...

> is this a hidden ACK?

not yet, testing too 😉

**Comment by smlng** [comment]
I think it's unrelated: but on macOS with VBox `vagrant up` exists with a timeout error. This is caused by the fact, that in the network config of the VM the _network cable_ was not connected (that is a check box). Hence, Ubuntu waits like 5 min for the network to become ready on startup, which subsequently results in a timeout for vagrant.

**Comment by kYc0o** [comment]
> I think it's unrelated: but on macOS with VBox vagrant up exists with a timeout error. This is caused by the fact, that in the network config of the VM the network cable was not connected (that is a check box). Hence, Ubuntu waits like 5 min for the network to become ready on startup, which subsequently results in a timeout for vagrant.

I can confirm this behaviour, which is also present in the current Vagrant image. Is it possible to "connect" the network cable in the configuration file?

**Comment by miri64** [comment]
On Linux it works as expected.

**Comment by cgundogan** [comment]
>Retro-active question BTW: what was your reason to use packer 

the reasoning was that it's from the same people as vagrant itself

**Comment by cgundogan** [comment]
BTW, before creating the box you can set `headless` in the `riot.js` file to `false` to see what happens .. or just connect via `rdesktop` if it already runs in headless mode (:

**Comment by smlng** [comment]
a more general point would be, if this has to reside in the RIOT repo or should be moved similiar to riot-docker?

**Comment by cgundogan** [comment]
I have no strong opinion about that @smlng 
But I rather want to see this box automatically built and published when some of the packer related files change. This might be implemented in a simpler way if this code resides in it's own repo.

**Comment by smlng** [comment]
regarding macOS: cannot reproduce described behavior after first usage of Vagrant and Vbox update 😞 Still ACK 'cause unrelated, but I also think we should move this into a separate repo.

And: I don't think we need to bother Murdock?

**Comment by miri64** [comment]
> And: I don't think we need to bother Murdock?

Just to be on the safe side we should and it's not like it takes long ;-)

**Comment by miri64** [comment]
If we put it in its own repo we could have a Travis instance do the testing for this.

**Comment by miri64** [comment]
(including auto-publishing)

**Comment by miri64** [comment]
Still merge... I thought we discussed this already. Travis was just a proposal about how to easily implement this.

**Comment by cgundogan** [comment]
yup still merge :+1:

**Pull request merged**
