### PR TITLE
boards/nucleo144: fix uninitialized on-board leds

### PR DESCRIPTION
**Pull request by aabadie**
A small fix with on-board leds for nucleo-144: those boards have 3 of them.

### CODE REVIEW

**Comment by kYc0o** [comment]
Have you verified if these changes doesn't add any LED vs periph problem? (any LED pin used by another peripheral).

**Comment by aabadie** [comment]
I thought I did. I double checked, just to be sure, and it appears the RX pin of third UART of nucleo144-f303 conflicts with LED1. What should I do ? skip init of this LED or change third UART configuration ?

**Comment by aabadie** [comment]
actually, after looking at #6879, the nucleo144 configuration should be updated to better reflect the Arduino pinout. I can come with a follow-up PR. What do you think ?

**Comment by kYc0o** [comment]
So you propose to break the third UART with this PR and then fix it with an upcoming PR?

**Comment by aabadie** [comment]
well, yes. since there's no auto init of uart like what is done for spi, I think this is fine.

**Comment by aabadie** [comment]
ping @kYc0o, I just opened #6926 in order to fix the pin clash.

**Comment by aabadie** [comment]
ping @kYc0o

**Pull request merged**
