### PR TITLE
CppCheck: Removing memleak warning

### PR DESCRIPTION
**Pull request by kushalsingh007**
- Changing the name of variable 'new' solved the problem.
- Part of fix for #480

### CODE REVIEW

**Comment by kushalsingh007** [comment]
I did not dig deep enough into the problem , because just changing the name of the variable solved the problem. However I can have another look at the problem (this time to dig deeper ) if you suggest.

**Comment by authmillenon** [comment]
Since I analyzed the s*** out of this with valgrind, and the name change seems to fix it, I'm pretty confident that this is some of this weird `cppcheck` bugs (probably comes from the fact, that `new` is a keyword in C++).

ACK.

**Comment by kushalsingh007** [comment]
Kindly restart the build.

**Comment by haukepetersen** [comment]
restarted...

**Comment by kushalsingh007** [comment]
```All is well```

**Comment by kushalsingh007** [comment]
I guess this one can be merged now and I think the issue #480 can also be closed ?

**Pull request merged**
