### PR TITLE
boards/lsn50: add support for Dragino LSN50 LoRa Sensor Node

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds support for the [Dragino LSN50 LoRa Sensor Node](https://wiki.dragino.com/index.php?title=Lora_Sensor_Node-LSN50). This board comes with a nice waterproof box and a 4Ah battery which make it super interesting for outdoor LoRa deployments.

What has been tested so far:
- SPI (with SX1276)
- UART
- RTC
- RTT
- Timer

LoRaWAN still need to be tested but should work (since the radio seems to work). Also low-power capabilities also need to be tested.

### Testing procedure

Run `./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . lsn50`

It should work the same as for `b-l072z-lrwan1` (same CPU). Note that on v1.0 of the board, there's no NRST pin available, so this script won't work. In this case (my case in fact), one would have to test everything manually.

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
Tested LoRaWAN and it works. I had to set SX127X_PARAM_PASELECT param to PA_BOOST to make it work.

**Comment by aabadie** [comment]
@fjmolinas, doc updated and improved

**Comment by fjmolinas** [comment]
@aabadie Please squash.!

**Comment by aabadie** [comment]
Thanks @fjmolinas. I squashed this one but it would be better to comment with the formal `ACK` before merging :)

**Comment by fjmolinas** [comment]
ACK!

**Pull request merged**
