### PR TITLE
doc: Rust overview

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

This adds overview documentation to using Rust on RIOT, similar to the one existing for C++; much of it is adapted from the riot-examples docs at https://gitlab.com/etonomy/riot-examples (which can then be trimmed down, referring to upstream support).

As a singular non-doc change this contains the addition of RUST_TARGET to `make info-build`, which paves a path (taken in the new documentation) toward proactively installing the right tools, rather than running `make` and waiting for the error message to tell one what is missing.

### Testing procedure

* View the docs
* Run `make info-build` on an arbitrary example, with BOARD set to microbit-v2 (has a RUST_TARGET) and 6lowpan-clicker (has no RUST_TARGET, shows empty)

### Issues/PRs references

Follow-up for: #16274 (where this should have been done already)

### CODE REVIEW

**Comment by chrysn** [comment]
Any clues as to what I'd have to do to make this build viewable docs? Tried setting CI readiness briefly, but that wasn't it.

If a second agrees, I think this can have build skipping set (yes there is a change to make files, but I don't think that that code path is even taken there).

**Comment by kaspar030** [comment]
> If a second agrees, I think this can have build skipping set (yes there is a change to make files, but I don't think that that code path is even taken there).

+1 that the Makefile change is fine, let's skip compilation.

**Comment by kaspar030** [comment]
> Any clues as to what I'd have to do to make this build viewable docs?

@miri64 do you have insight on when circleci triggers?

**Review by kaspar030 — APPROVED** [review]
ACK.

Docs render fine. Didn't verify all steps, but they match my memories.

**Comment by miri64** [comment]
> > Any clues as to what I'd have to do to make this build viewable docs?
> 
> @miri64 do you have insight on when circleci triggers?

I am the wrong person to ask. CircleCI was introduced and is mostly maintained by @aabadie.

**Pull request merged**
