### PR TITLE
ng_netif: don't add duplicates

### PR DESCRIPTION
**Pull request by Lotterleben**
prevent ng_netif_add() from adding duplicates as described in https://github.com/RIOT-OS/RIOT/issues/2965

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK

**Comment by authmillenon** [comment]
And go.

**Comment by authmillenon** [comment]
Args and only now I was wondering why you did not update the unittests for the corner-case :(

**Comment by Lotterleben** [comment]
I can just open a follow-up PR for that :)

**Comment by authmillenon** [comment]
Yes, also please consider https://github.com/RIOT-OS/RIOT/pull/3059 ;)

**Comment by Lotterleben** [comment]
reviewing it right now ;)

**Pull request merged**
