### PR TITLE
ipv6_ext: add fragmentation extension definitions

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides an initial import of IPv6 fragmentation header definitions and helper functions.

### Testing procedure
```C
export BOARD="<your favorite>"
make -C tests/unittests tests-ipv6_hdr flash-only test
```

### Issues/PRs references
Addresses https://github.com/RIOT-OS/RIOT/issues/5371 in part.

### CODE REVIEW

**Comment by cladmi** [comment]
After adding `flash` to the test command, `BOARD=${board} make --no-print-directory -C tests/unittests/ tests-ipv6_hdr flash test` the `arduino-zero iotlab-m3 samr21-xpro b-l475e-iot01a microbit` works on `IoT-LAB` and on `frdm-k64f frdm-kw41z msba2 mulle nrf52dk nucleo-f103rb pba-d-01-kw2x sltb001a stm32f3discovery` on my local hardware.

On the `arduino-mega2560` it failed with 
```
ipv6_hdr_tests.test_ipv6_hdr_set_fl (tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c 233) exp 173 was 173
```
but as @miri64 said, it was not introduced by these changes and it is indeed broken on master.

**Comment by miri64** [comment]
Fixed a warning by coccinelle.

**Comment by miri64** [comment]
While implementing fragmentation, I realized that `ipv6_ext_frag_set_offset_more()` needed to be split up into two functions.

**Comment by miri64** [comment]
Fixed a rebase error and a murdock issue.

**Pull request merged**
