### PR TITLE
code-style/linelencheck: add line length check script

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds a script for checking line length limits. The difference with solutions like #9778 is the fact it has a threshold for warnings and errors, and can also check other kind of documents (documentation, Makefiles, etc).

I added the script under `dist/tools/linelencheck`, and adopted the `doccheck` script to check documentation style.

The following env variables are defined:
- `WARNING_LIMIT`: The script raises `warning` for each line with length greater than this limit (default=80)
- `ERROR_LIMIT`: The script raises `error` for each line with length greater than this limit (default=100). The script throws `exit 1` here.
- `LINEREGEX`: Only check lines that match the given line regex (default="`.*`"). E.g Doxygen tables.

### Testing procedure

Call `dist/tools/linelencheck/check.sh` and check the output. Try changing the env variables values.

### Issues/PRs references
[#9881 (discussion)](https://github.com/RIOT-OS/RIOT/pull/9881#discussion_r215183908)

### CODE REVIEW

**Comment by aabadie** [comment]
@jia200x, how does this work with long urls ?

Otherwise, if we are sure that this check script is robust enough (e.g. it doesn't false positive with long url or other weird things) then there's no need for the warning level I think.

**Comment by jia200x** [comment]
> @jia200x, how does this work with long urls ?

I forgot to add this case, thanks. Well, the script is only a checker, so the `doccheck.sh` call needs to pass the proper `LINEREGEX` to detect long URLs.

> Otherwise, if we are sure that this check script is robust enough (e.g. it doesn't false positive with long url or other weird things) then there's no need for the warning level I think.

I implemented the warnings because of [#9778 (discussion)](https://github.com/RIOT-OS/RIOT/pull/9778#issuecomment-413169048) and the `Line length: aim for no more than 80 characters per line, the absolute maximum should be 100 characters per line.` from "General" section in our "Coding Conventions".

**Comment by jia200x** [comment]
> Code blocks (between triple back quotes) could also be an issue (just thought of this case)

Yes. I might need to extend the tool for handling these cases.

> Ok, I missed this. But I think this discussion applies more to code where we can be a it more tolerant because of the syntax or readability. Here the line length check script is only looking at documentation files (doc.txt, READMEs, etc), so it's a bit different because they are supposed to contain mainly textual information.

I plan to reuse the same `linelencheck` script for C code, so I implemented a generic line checker. I can modify the script to avoid using warnings if `WARNING_LIMIT` and `ERROR_LIMIT` are set to the same value.

What do you think?

**Comment by miri64** [comment]
I think this should still be merged. @aabadie can you have another look, please?

**Pull request closed without merging**
