### PR TITLE
cpu/cc2538: fix spi_transfer_bytes()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

In the `in_buf == NULL` case, `spi_transfer_bytes()` would only write `DR` for every out byte, but then loop reading `DR` only while SPI is busy.

This is not correct, we have to read as many data bytes as we write, otherwise data bytes remain in the FiFo and will corrupt subsequent reads.

While at it, I also took the chance to clean up `spi_transfer_bytes()` by factoring out DR access into a helper function.

### Testing procedure

Run @guyyst's tests application from https://github.com/RIOT-OS/RIOT/pull/12128#issuecomment-552216507 on the `openmote-b`.

Before this patch, the driver would sometimes read both interrupt status registers as 0 (or some other weird value) and in turn not service the interrupt.

With this the test is running smoothly.

### Issues/PRs references

The issue was discovered while testing the `at86rf215` driver on the `openmote-b`.

### CODE REVIEW

**Comment by fjmolinas** [comment]
Had to go back though some of my SPI basics, but change makes sense (was confused by the fact that the Rx_FIFO and TX_FiFO need to behave like a shift register for SPI). I'll test ASAP.

**Comment by fjmolinas** [comment]
I'm trying to replicate the failure using the mentioned example, its been going for 1hour and no failure yet...

**Comment by fjmolinas** [comment]
> I'm trying to replicate the failure using the mentioned example, its been going for 1hour and no failure yet...

Argh, I'm unable to reproduce the issue now... Since the change still makes sense, I'll do a no-regression test.

**Comment by fjmolinas** [comment]
> Argh, I'm unable to reproduce the issue now... Since the change still makes sense, I'll do a no-regression test.

Otherwise maybe @guyyst can verify it fixes the issue for him?

**Comment by guyyst** [comment]
I'll have access to our OpenMotes towards the end of the week. I'll try out the fix and report back then.

**Comment by guyyst** [comment]
Weird, I'll have to echo @fjmolinas findings. I tried the example on 2.4-GHz and Sub-GHz with and without this patch and observed the same behaviour. Neither of them froze even after 5+ minutes.

My only guess is that some other commit to #12128 since the last time I tried this in November already fixed the issue.

**Pull request merged**
