### PR TITLE
cpu/esp: compile optional modules in CI

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

A number of optional ESP modules (#12960) can be used by an application to select additional features of the ESP implementation. Since these optional ESP modules are not enabled by default, they are not covered by the compilation test in CI. This led to compilation issues in the past from time to time, for example #17305.

This PR adds some dependencies for two boards (an ESP8266 and an ESP32 board) that enable all these optional ESP modules when compiled in the CI. Some of these optional ESP models are used by these boards by default, others are only used in certain test applications depending on the use of other modules.

This PR is a try to solve the problem without the necessity to create copies of existing test applications for these optional modules like in PR #12971 or to define a new virtual board that uses them.

### Testing procedure

Compilation should succeed in CI.

### CODE REVIEW

**Comment by gschorcht** [comment]
@benpicco @kaspar030 This approach seems to work without the need to create copies of existing test applications for optional ESP modules as in PR #12971 or to define a new virtual board that uses them. The compilation of these optional modules does not depend on additional defines, i.e. it is sufficient to compile them for one board.

**Review by benpicco — APPROVED** [review]
I like it, there are still enough other esp boards to test the defaults on CI

**Comment by gschorcht** [comment]
@benpicco Can we merge?

**Comment by benpicco** [comment]
Sure!

**Comment by gschorcht** [comment]
Thanks for reviewing and merging.

**Pull request merged**
