### PR TITLE
makesystem: speedup pkg cloning if no git-cache is available

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

This clones repositories used by pkgs without downloading all the history. Due to git clone not being able to load a specific commit: this initializes the packages directory (PKG_SOURCE_DIR) adds the remote configures it and fetches the least amount of data to checkout the PKG_VERSION (commit-id or branch or tag)

for example: this reduces the download of wolfssl from 159.42 MiB to 9.70 MiB + 6.65 MiB ~=16.35MiB

this method or the previous git cache method is selected by the availability of the PATH named by $(GIT_CACHE_DIR) (default: $HOME/.gitcache)

### Testing procedure

make a test/example that uses a pkg that uses a git repo

### Issues/PRs references

non to my knowledge

### CODE REVIEW

**Comment by maribu** [comment]
Maybe it makes more sense to clone with `--depth=1` instead, as we are not really interested in the history of external source for the build process.

E.g. I would expect developers contributing to e.g. NanoCBOR to have the corresponding Repo cloned elsewhere with full history anyway.

Maybe @bergzand and @benpicco have an opinion, as they contribute to other stuff packed in RIOT as well.

**Comment by kfessel** [comment]
i think you can't clone non braches -> --depth=1 will give you a branch that you do not want since RIOT pkgs want arbitrary commits 
even though we do not need the history it isn't the biggest part of a repo

**Comment by kfessel** [comment]
If I take the wolfssl example the complete history is 9 MiB while the blobs are 150 MiB (wee need 7 of them) -> this this saves us ~89% but have all history at hand.

**Comment by fjmolinas** [comment]
Does gitcache need the blobs? If not can't we do the same thing in all cases and not include blobs?

**Comment by kfessel** [comment]
> Does gitcache need the blobs? If not can't we do the same thing in all cases and not include blobs?

I think the profit wouldn't be worth it with git cache (if you are not short on diskspace on the build system (looking at murdock we are talking about the compile result cache which will be much bigger than what we would safe with this)) -the download size is also less of an issue with a git cache  (--- I do not use git cache -> i can not speak much for its usage patters)
- If you still think it would be also be a nice addition to the git cache using systems i can add that or do a second PR

**Comment by kfessel** [comment]
@maribu : you might want to have a look at this i changed it to clone without history (depth=1)

**Comment by maribu** [comment]
Code looks good to me. Please squash :)

**Comment by kfessel** [comment]
rebased an squashed

tried to avoid getting all tags - sadly some git segfaults in that case (so get all tags without blobs)

**Comment by kfessel** [comment]
The Murdock failure left is not related to this PR see #17894. I think we can skip compile.

**Comment by maribu** [comment]
I did this for testing:

```
$ rm build -rf
$ make RIOT_CI_BUILD=1 BOARD=stm32f429i-disc1 -j -C tests/pkg_lvgl_touch/
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch'
Building application "tests_pkg_lvgl_touch" for "stm32f429i-disc1" with MCU "stm32".

[INFO] cloning stm32cmsis
[INFO] cloning lvgl
Cloning into '/home/maribu/Repos/software/RIOT/build/stm32/cmsis/f4'...
Cloning into '/home/maribu/Repos/software/RIOT/build/pkg/lvgl'...
remote: Enumerating objects: 62872, done.
remote: Counting objects: 100% (2101/2101), done.
remote: Compressing objects: 100% (1218/1218), done.
remote: Enumerating objects: 425, done.
remote: Counting objects: 100% (425/425), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 425 (delta 361), reused 400 (delta 336), pack-reused 0
Receiving objects: 100% (425/425), 890.66 KiB | 846.00 KiB/s, done.
Resolving deltas: 100% (361/361), done.
HEAD is now at 6fe2c1f Release v2.6.7 12.53 MiB | 6.15 MiB/s
[INFO] updating stm32cmsis /home/maribu/Repos/software/RIOT/build/stm32/cmsis/f4/.pkg-state.git-downloaded
echo 6fe2c1f498feda34ee422720ff8b3bd1b4656145   > /home/maribu/Repos/software/RIOT/build/stm32/cmsis/f4/.pkg-state.git-downloaded
[INFO] patch stm32cmsis
remote: Total 62872 (delta 1120), reused 1535 (delta 876), pack-reused 60771
Receiving objects: 100% (62872/62872), 88.11 MiB | 6.63 MiB/s, done.
Resolving deltas: 100% (48623/48623), done.
HEAD is now at 0b5a1d4b release v8.2
[INFO] updating lvgl /home/maribu/Repos/software/RIOT/build/pkg/lvgl/.pkg-state.git-downloaded
echo 0b5a1d4b23975b920ff841ea9cd038802f51711b   > /home/maribu/Repos/software/RIOT/build/pkg/lvgl/.pkg-state.git-downloaded
[INFO] patch lvgl
   text	   data	    bss	    dec	    hex	filename
 101228	    188	  15788	 117204	  1c9d4	/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch/bin/stm32f429i-disc1/tests_pkg_lvgl_touch.elf
make: Leaving directory '/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch'
$ du --max-depth 0 -h  build/
216M	build/
```

```
$ git checkout <PR>
$ rm build -rf
$ make RIOT_CI_BUILD=1 BOARD=stm32f429i-disc1 -j -C tests/pkg_lvgl_touch/
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch'
Building application "tests_pkg_lvgl_touch" for "stm32f429i-disc1" with MCU "stm32".

[INFO] cloning without cache stm32cmsis
[INFO] cloning without cache lvgl
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 43 (delta 2), reused 43 (delta 2), pack-reused 0
Receiving objects: 100% (43/43), 13.69 KiB | 560.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
From https://github.com/STMicroelectronics/cmsis_device_f4
 * branch            6fe2c1f498feda34ee422720ff8b3bd1b4656145 -> FETCH_HEAD
 * [new tag]         v2.6.3     -> v2.6.3
 * [new tag]         v2.6.4     -> v2.6.4
 * [new tag]         v2.6.6     -> v2.6.6
 * [new tag]         v2.6.7     -> v2.6.7
 * [new tag]         v2.6.8     -> v2.6.8
remote: Enumerating objects: 1079, done.
remote: Counting objects: 100% (1079/1079), done.
remote: Compressing objects: 100% (966/966), done.
remote: Total 1079 (delta 364), reused 544 (delta 91), pack-reused 0
Receiving objects: 100% (1079/1079), 248.78 KiB | 5.92 MiB/s, done.
Resolving deltas: 100% (364/364), done.
From https://github.com/littlevgl/lvgl
 * branch            0b5a1d4b23975b920ff841ea9cd038802f51711b -> FETCH_HEAD
 * [new tag]         2.1             -> 2.1
 * [new tag]         before-v7-style -> before-v7-style
 * [new tag]         v2.1            -> v2.1
 * [new tag]         v2.2.0          -> v2.2.0
 * [new tag]         v4.0.0          -> v4.0.0
 * [new tag]         v4.1.0          -> v4.1.0
 * [new tag]         v4.1.1          -> v4.1.1
 * [new tag]         v4.2.0          -> v4.2.0
 * [new tag]         v5.0.0          -> v5.0.0
 * [new tag]         v5.0.1          -> v5.0.1
 * [new tag]         v5.0.2          -> v5.0.2
 * [new tag]         v5.1            -> v5.1
 * [new tag]         v5.1.1          -> v5.1.1
 * [new tag]         v5.2            -> v5.2
 * [new tag]         v5.2-rc         -> v5.2-rc
 * [new tag]         v5.3            -> v5.3
 * [new tag]         v6.0            -> v6.0
 * [new tag]         v6.0.1          -> v6.0.1
 * [new tag]         v6.0.2          -> v6.0.2
 * [new tag]         v6.1            -> v6.1
 * [new tag]         v6.1.1          -> v6.1.1
 * [new tag]         v6.1.2          -> v6.1.2
 * [new tag]         v7.0-rc         -> v7.0-rc
 * [new tag]         v7.0.0          -> v7.0.0
 * [new tag]         v7.0.1          -> v7.0.1
 * [new tag]         v7.0.2          -> v7.0.2
 * [new tag]         v7.1.0          -> v7.1.0
 * [new tag]         v7.10.0         -> v7.10.0
 * [new tag]         v7.10.1         -> v7.10.1
 * [new tag]         v7.11.0         -> v7.11.0
 * [new tag]         v7.2.0          -> v7.2.0
 * [new tag]         v7.3.0          -> v7.3.0
 * [new tag]         v7.3.1          -> v7.3.1
 * [new tag]         v7.4.0          -> v7.4.0
 * [new tag]         v7.5.0          -> v7.5.0
 * [new tag]         v7.6.0          -> v7.6.0
 * [new tag]         v7.6.1          -> v7.6.1
 * [new tag]         v7.7.0          -> v7.7.0
 * [new tag]         v7.7.1          -> v7.7.1
 * [new tag]         v7.7.2          -> v7.7.2
 * [new tag]         v7.8.0          -> v7.8.0
 * [new tag]         v7.8.1          -> v7.8.1
 * [new tag]         v7.9.0          -> v7.9.0
 * [new tag]         v7.9.1          -> v7.9.1
 * [new tag]         v8.0.0          -> v8.0.0
 * [new tag]         v8.0.1          -> v8.0.1
 * [new tag]         v8.0.2          -> v8.0.2
 * [new tag]         v8.0.3-dev      -> v8.0.3-dev
 * [new tag]         v8.1.0          -> v8.1.0
 * [new tag]         v8.2.0          -> v8.2.0
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 122 (delta 99), reused 88 (delta 74), pack-reused 0
Receiving objects: 100% (122/122), 361.88 KiB | 926.00 KiB/s, done.
Resolving deltas: 100% (99/99), done.
Updating files: 100% (150/150), done.
HEAD is now at 6fe2c1f Release v2.6.7
[INFO] updating stm32cmsis /home/maribu/Repos/software/RIOT/build/stm32/cmsis/f4/.pkg-state.git-downloaded
echo 6fe2c1f498feda34ee422720ff8b3bd1b4656145   > /home/maribu/Repos/software/RIOT/build/stm32/cmsis/f4/.pkg-state.git-downloaded
[INFO] patch stm32cmsis
remote: Enumerating objects: 1076, done.
remote: Counting objects: 100% (1076/1076), done.
remote: Compressing objects: 100% (984/984), done.
remote: Total 1076 (delta 136), reused 404 (delta 87), pack-reused 0
Receiving objects: 100% (1076/1076), 24.05 MiB | 5.88 MiB/s, done.
Resolving deltas: 100% (136/136), done.
Updating files: 100% (1082/1082), done.
HEAD is now at 0b5a1d4 release v8.2
[INFO] updating lvgl /home/maribu/Repos/software/RIOT/build/pkg/lvgl/.pkg-state.git-downloaded
echo 0b5a1d4b23975b920ff841ea9cd038802f51711b   > /home/maribu/Repos/software/RIOT/build/pkg/lvgl/.pkg-state.git-downloaded
[INFO] patch lvgl
   text	   data	    bss	    dec	    hex	filename
 101228	    188	  15788	 117204	  1c9d4	/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch/bin/stm32f429i-disc1/tests_pkg_lvgl_touch.elf
make: Leaving directory '/home/maribu/Repos/software/RIOT/tests/pkg_lvgl_touch'
$ du --max-depth 0 -h  build/
150M	build/
```

As seen, a chunk of storage is saved and the cloning subjectively felt faster with this PR. Hence, this works as advertised. And Murdock will do the regression testing :)

**Comment by benpicco** [comment]
The failure of [tests/congure_reno/microbit:gnu](https://ci.riot-os.org/RIOT-OS/RIOT/16316/cc3fc8ebb7316a2c0c0c34eabbe680bbc54a5efa/output/compile/tests/congure_reno/microbit:gnu.txt) should be unrelated.

**Review by maribu — APPROVED** [review]
ACK. As above shown I could confirm that storage requirements are reduced as advertised. Builds with git cache still work (as tested by Murdock with good test coverage) and without (as tested by hand with limited test coverage).

**Pull request merged**
