### PR TITLE
tests/driver_sht2x: avoid negative number after decimal dot

### PR DESCRIPTION
**Pull request by keestux**
This is a similar fix as in #12162  and #12140.

### CODE REVIEW

**Comment by keestux** [comment]
Notice that sht3x has a similar problem too. But that one has a bug as well, I think.

**Comment by keestux** [comment]
In the sht3x test there is this:
```
        int16_t temp;
        int16_t hum;

        if ((res = sht3x_read(&dev, &temp, &hum)) == SHT3X_OK) {
            printf("Temperature [°C]: %d.%d\n"
                   "Relative Humidity [%%]: %d.%d\n"
                   "+-------------------------------------+\n",
                   temp / 100, temp % 100,
                   hum / 100, hum % 100);
        }
```
Not only does it need an abs() for the numbers after decimal dot, it has `%d` for a 2 digit number. This means that a temperature of `10.05` degrees will be printed as `10.5`. Same for the humidity. I don't have the device so I can't really test.

**Comment by benpicco** [comment]
> I don't have the device so I can't really test.

I mean the format string is device independent, no?
If we assume the documentation is right, `temp` will be

> `Temperature in hundredths of a degree Celsius`

so we can set `int16_t temp = -1005;` and test the behavior of `printf()` locally.

**Comment by aabadie** [comment]
There's indeed a problem, the formatter for temperature should `%d.%02d` (also tested this locally).

**Comment by aabadie** [comment]
> There's indeed a problem, the formatter for temperature should be %d.%02d (also tested this locally).

well, in fact it's not needed since the number after decimal dot is divided by 10. But this division could be removed if you use `%d.%02d`. This should be better.
I checked and bmx280 driver application has the same behaviour.

**Pull request merged**
