### PR TITLE
cpu/cc2538/timer: fix 32 bit timer reload value

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

I found this bug while testing #10493 since I would see the application getting stuck for 32bit timers. This commit fixes it.

The interval load value was only set to 0xffff regardless of the counter
mode used which mad the 32bit timer apparently stop after 0xffff (it
would never reach values >0xffff).

When a GPTM is configured to one of the 32-bit modes, TAILR appears as a
32-bit register (the upper 16-bits correspond to the contents of the
GPTM Timer B Interval Load (TBILR) register). In a 16-bit mode, the
upper 16 bits of this register read as 0s and have no effect on the
state of TBILR.

Therefore the LOAD_VALUE can be set to 0xffffffff instead of 0xffff
since the higher bits will be ignored in 16bit mode.

### Testing procedure

Can be tested with #10493 `BOARD=openmote-b make -C tests/periph_timer_diff/ flash test`

with this PR:

```
*** Testing TIMER_2 ***
 _init(2, 32000000, cb, args)
 _set(2, 0, 20000)
  fired 10 , offset 20000 [us]

;num, begin, until, timer_diff, simple_diff
 1, 226, 20822, 20596, 20596
 2, 20822, 41117, 20295, 20295
 3, 41117, 61412, 20295, 20295
 4, 61412, 81707, 20295, 20295
 5, 81707, 102002, 20295, 20295
 6, 102002, 122297, 20295, 20295
 7, 122297, 142592, 20295, 20295
 8, 142592, 162887, 20295, 20295
 9, 162887, 183182, 20295, 20295
 10, 183182, 203477, 20295, 20295

  Note: timer_max is equal to UINT_MAX.

*** Testing TIMER_3 ***
 _init(3, 32000000, cb, args)
 _set(3, 0, 20000)
  fired 10 , offset 20000 [us]

;num, begin, until, timer_diff, simple_diff
 1, 226, 20822, 20596, 20596
 2, 20822, 41117, 20295, 20295
 3, 41117, 61412, 20295, 20295
 4, 61412, 81707, 20295, 20295
 5, 81707, 102002, 20295, 20295
 6, 102002, 122297, 20295, 20295
 7, 122297, 142592, 20295, 20295
 8, 142592, 162887, 20295, 20295
 9, 162887, 183182, 20295, 20295
 10, 183182, 203477, 20295, 20295

  Note: timer_max is equal to UINT_MAX.

[SUCCESS]
```

without this PR:

```
  Note: timer_max is less than UINT_MAX.

*** Testing TIMER_2 ***
 _init(2, 32000000, cb, args)
 _set(2, 0, 20000)
Timeout in expect script at "child.expect_exact('*** Testing TIMER_{} ***'.format(timer))" (tests/periph_timer_diff/tests/01-run.py:19)
```

### CODE REVIEW

**Comment by benpicco** [comment]
Looks like the 16 bit timer is also down-counting: The driver does `LOAD_VALUE - dev(tim)->TAV` for `timer_read()` which would now return wrong results.

This is also done in `timer_set_absolute()`.

**Comment by fjmolinas** [comment]
> Looks like the 16 bit timer is also down-counting: The driver does `LOAD_VALUE - dev(tim)->TAV` for `timer_read()` which would now return wrong results.
> 
> This is also done in `timer_set_absolute()`.

Oh yeah worse fix than the issue, on my side, hope now its better.

**Comment by benpicco** [comment]
Please squash!

**Comment by fjmolinas** [comment]
Thanks for the review!

**Pull request merged**
