### PR TITLE
Kconfig: update status message about Kconfig

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

We concluded the Kconfig migration phase. Update the message in `menuconfig` accordingly. 

### Testing procedure

Run `make menuconfig` for any application.

### CODE REVIEW

**Comment by waehlisch** [comment]
we should be more specific. we don't want to remove Kconfig completely.

**Comment by benpicco** [comment]
> we don't want to remove Kconfig completely.

Is this the case? Who will maintain it?

**Comment by MrKevinWeiss** [comment]
> Is this the case?

Only the kconfig dependencies have been removed. The configuration are still there and much cleaner and easy to debug then nested header #ifdefs.

> Who will maintain it?

Kconfig for configurations is much more manageable (and possible).  I can get on that when I am not busy with all the release stuff.  I'm sure I can pull others in as well.

> There is no pain in keeping that around, but at some point it will just be unnecessary clutter.

I agree that the dependency stuff should be cleaned up

**Comment by MrKevinWeiss** [comment]
> My only concern is that keeping Kconfig in sync with the rest of the codebase will be very hard without tests. E.g. how can we detect if some config define gets renamed or added/removed in the C code, but not in Kconfig?

I don't want to have the same issues as with the dep modelling. How I see it happening is:
- a big push to model all configs (a quick check shows ~1000)
- add an optional test to confirm everything fits
- either make the test no longer optional or do the full switch (and simplify the .h file)
- optimize for speed and do some menuconfig cleanup and org

From what I can see on the matrix chat/forum, we should be discussing it more in the VMA and maybe we can also see how it would integrate to _the next build system_.

**Pull request closed without merging**
