### PR TITLE
x86 toolchain upgrade

### PR DESCRIPTION
**Pull request by gebart**
This PR converts the inline patches in build_x86.sh into separate patch files and upgrades the newlib version to 2.2.0.20150623

@Kijewski do you know how to create a new binary tarball for newlib based on the included 2.2.0.20150623 version? I am not sure how the current one at http://download.riot-os.org/i586-newlib_2.1.0_tlsf-1254.tar.bz2 was created.

Who has access to upload new versions of the binary package to download.riot-os.org?

Blocks #3319

### CODE REVIEW

**Comment by OlegHahm** [comment]
> Who has access to upload new versions of the binary package to download.riot-os.org?

I can do so.

**Comment by gebart** [comment]
I managed to build a binary newlib with some upgraded versions of the tools. The result can be found at https://dl.dropboxusercontent.com/u/16785247/i586-newlib_2.2.0.20150623_tlsf-3337.tar.bz2
I assumed the _tlsf patches in the 2.1.0 version meant the malloc patches in build_x86.sh, so I kept the suffix.
@Kijewski do you want to review the tarball before @OlegHahm puts it on the RIOT server?

**Comment by OlegHahm** [comment]
I set the timeout to five days.

**Comment by Kijewski** [comment]
There's a name clash between RIOT's ucontext.h and Newlib's sys/signal.h:
``` diff
diff --git a/cpu/x86/include/ucontext.h b/cpu/x86/include/ucontext.h
index ef1c42a..8574140 100644
--- a/cpu/x86/include/ucontext.h
+++ b/cpu/x86/include/ucontext.h
@@ -87,7 +87,7 @@ typedef struct stack {
     void *ss_sp; /* field in ucontext_t: 0*4 */
     //int ss_flags;
     size_t ss_size; /* field in ucontext_t: 1*4 */
-} __attribute__((packed)) stack_t;
+} __attribute__((packed)) riot_stack_t;
 
 /**
  * @brief   Extra data to perform an `iret`.
@@ -107,7 +107,7 @@ struct x86_interrupted_interrupt {
  * This datatype stores the machine state of a suspended coroutine.
  */
 typedef struct ucontext {
-    stack_t uc_stack;         /* field in ucontext_t: 0*4 - 1*4 */
+    riot_stack_t uc_stack;    /* field in ucontext_t: 0*4 - 1*4 */
     mcontext_t uc_context;    /* field in ucontext_t: 2*4 -> 11*4 */
     struct ucontext *uc_link; /* field in ucontext_t: 12*4 */
     //sigset_t uc_sigmask;
```

**Comment by gebart** [comment]
Addressed in #3319. I will copy that fix to this PR.

There's a name clash between RIOT's ucontext.h and Newlib's sys/signal.h:

diff --git a/cpu/x86/include/ucontext.h b/cpu/x86/include/ucontext.h
index ef1c42a..8574140 100644--- a/cpu/x86/include/ucontext.h+++
b/cpu/x86/include/ucontext.h@@ -87,7 +87,7 @@ typedef struct stack {
     void *ss_sp; /* field in ucontext_t: 0*4 */
     //int ss_flags;
     size_t ss_size; /* field in ucontext_t: 1*4 */-}
__attribute__((packed)) stack_t;+} __attribute__((packed))
riot_stack_t;

 /**
  * @brief   Extra data to perform an `iret`.@@ -107,7 +107,7 @@
struct x86_interrupted_interrupt {
  * This datatype stores the machine state of a suspended coroutine.
  */
 typedef struct ucontext {-    stack_t uc_stack;         /* field in
ucontext_t: 0*4 - 1*4 */+    riot_stack_t uc_stack;    /* field in
ucontext_t: 0*4 - 1*4 */
     mcontext_t uc_context;    /* field in ucontext_t: 2*4 -> 11*4 */
     struct ucontext *uc_link; /* field in ucontext_t: 12*4 */
     //sigset_t uc_sigmask;

—
Reply to this email directly or view it on GitHub
<https://github.com/RIOT-OS/RIOT/pull/3337#issuecomment-120057449>.

**Comment by Kijewski** [comment]
I'm happy with the new blob once this fix is backported. Without we'd have some trouble until #3319 is merged.

**Comment by gebart** [comment]
backported fix for stack_t, rebased, squashed.
Need to upload the blob to the download server and then I'll update the URL in Makefile.include before we merge this.

**Comment by OlegHahm** [comment]
Somehow my account for the server currently doesn't work. Contacted @phiros for help and will upload ASAP.

**Comment by gebart** [comment]
@OlegHahm ping!

**Comment by OlegHahm** [comment]
Oops, sorry and thanks for the ping. Will do it now.

**Comment by OlegHahm** [comment]
Uploaded.

**Comment by gebart** [comment]
Updated URL, rebased.

OK to squash?

**Comment by OlegHahm** [comment]
Ok from my side.

**Comment by gebart** [comment]
@OlegHahm is that an ACK?
@Kijewski seemed to be OK with this PR before.

**Comment by OlegHahm** [comment]
ACK

**Comment by gebart** [comment]
waiting for Travis.

**Pull request merged**
