### PR TITLE
dist: chose binary format for IoT-LAB Makefile

### PR DESCRIPTION
**Pull request by OlegHahm**
IoT-LAB expects different file formats for different architectures.

### CODE REVIEW

**Comment by cgundogan** [comment]
Just to be sure, `hex` is currently only used for the `WSN430` architecture, right? The change looks sane. It is very hard to test though, since we have no support for such an architexture (?). ACK

**Comment by OlegHahm** [comment]
> Just to be sure, hex is currently only used for the WSN430 architecture, right?

On IoT-LAB, yes.

> he change looks sane. It is very hard to test though, since we have no support for such an architexture (?)

Of course, we have: https://github.com/RIOT-OS/RIOT/tree/master/boards/wsn430-v1_3b and https://github.com/RIOT-OS/RIOT/tree/master/boards/wsn430-v1_4 or what do you mean?

Does your ACK hold for the tiny fixup? Can I squash?

**Comment by cgundogan** [comment]
Yes sure, please squash

**Comment by OlegHahm** [comment]
squashed

**Pull request merged**
