### PR TITLE
tests/thread_exti: add small README

### PR DESCRIPTION
**Pull request by PeterKietzmann**
self-explaining

### CODE REVIEW

**Comment by gebart** [comment]
Looks good, except a whitespace error (missing newline at end of file)

**Comment by PeterKietzmann** [comment]
Whoops. Added newline at the end of the README. Already squashed

**Comment by gebart** [comment]
Found another typo: line 72 in main.c, "4rd"->"4th"

also, is the order of the expected lines correct?

**Comment by gebart** [comment]
Regarding the order of the expected output, it is correct as far as I can see.

**Comment by PeterKietzmann** [comment]
Addressed and immediately squashed. Yes it is correct :-)

**Comment by gebart** [comment]
ACK

**Comment by PeterKietzmann** [comment]
and go

**Pull request merged**
