### PR TITLE
unittests: document make debug

### PR DESCRIPTION
**Pull request by Lotterleben**
For the sake of completeness, point out that you can debug your tests using gdb :) (thanks to @x3ro for telling me that this is possible :D)

### CODE REVIEW

**Comment by miri64** [comment]
That target is not unique to the unittests. So I'm not sure if it makes sense to add this here.

**Comment by miri64** [comment]
But more doc is better then less in that case, I guess :-)

**Comment by Lotterleben** [comment]
No it isn't unique, but somebody might not have caught it elsewhere yet (*cough* me *cough*) and I thought it'd be useful to be documented here in case that's where they needed it for the 1st time.

**Comment by miri64** [comment]
It's a readme change. No need to wait for Murdock here.

**Pull request merged**
