### PR TITLE
saml21: add lpm implementation

### PR DESCRIPTION
**Pull request by kaspar030**
~~(depends on #3018)~~

Adds lpm modes to the SAM L21 port.

Idle power consumption goes down from 1.5mA to ~0.7mA. Sleep power consumption is <2uA.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Sorry for the delay in here. I overlooked this one several times and currently don't find much time for that, even if I'm still really interested in spending more thoughts in low power modes. @kaspar030 is the lpm implementation similar to that in #2309 ? That we we could maybe kill two birds with one stone. 
Other than that: I don't have the hardware to test that.
@bapclenet are you aware of this PR?

**Comment by bapclenet** [comment]
@PeterKietzmann, I'm aware of this PR, I work on something else for the moment and I wanted to come back on #2309 as soon as I have time to do it. You're right this PR will certainly help if it works correctly. And I don't have a SAML21 as well

**Comment by kaspar030** [comment]
I think we should get this in the release. It is the world leader in low-power 32bit MCUs...

**Comment by OlegHahm** [comment]
@kaspar030, are you sure? I thought that was rather energy micro?

**Comment by OlegHahm** [comment]
needs a rebase to make Travis working

**Comment by kaspar030** [comment]
- rebased

**Comment by OlegHahm** [comment]
ACK and go!

**Comment by bapclenet** [comment]
@kaspar030, Could you share some results concerning energy consumption by comparing the different modes implemented? 
And also the way you do your tests? I had a quick look at the SAML21 power mode and there are lot more option than those provided by RIOT to save energy. 
As soon as I can, I will try to make the equivalent edit as you did on the SAMR21 and try to see if I obtain equivalent results.

**Pull request merged**
