### PR TITLE
make/boards: add pyocd as optional programmer for stm32

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR allows for using pyocd to flash some stm32 based boards.

Recent versions of pyocd (I tested with 0.24.1) offer the possibility to download a Keil pack that provide support for multiple STM32 (nucleo, etc) targets/boards.

Before using pyocd to flash the boards, the corresponding "packs" must be installed with the following command:
```
pyocd pack --install stm32*
```

I'd like to document this somewhere but don't know where :)

### Testing procedure

Verify that one of the [Nucleo boards supported](https://github.com/mbedmicro/pyOCD/blob/v0.24.1/pyocd/board/board_ids.py#L99) by pyocd can be flashed.

```
PROGRAMMER=pyocd make BOARD=nucleo-f103 -C examples/hello-world flash
PROGRAMMER=pyocd make BOARD=nucleo-f103 -C examples/hello-world reset
PROGRAMMER=pyocd make BOARD=nucleo-f103 -C examples/hello-world debug
```

### Issues/PRs references

Started to look into this when reviewing #11895

### CODE REVIEW

**Comment by fjmolinas** [comment]
> Before using pyocd to flash the boards, the corresponding "packs" must be installed with the following command:

This should be in our installation doc, or toolchain doc. We dont have one in code right now. Maybe you can add it to the wiki for now, and when we come around to moving it to code it will be taken into account

**Comment by fjmolinas** [comment]
Is a reboot or something else needed? It didn;t succeed:

```
### Flashing Target ###
0000790:WARNING:board:Generic 'cortex_m' target type is selected; is this intentional? You will be able to debug but not program flash. To set the target type use the '--target' argument or 'target_override' option. Use 'pyocd list --targets' to see available targets types.
0000876:WARNING:file_programmer:Failed to add data chunk: no memory region defined for address 0x08000000
0000877:INFO:loader:Erased 0 bytes (0 sectors), programmed 0 bytes (0 pages), skipped 0 bytes (0 pages) at 0.00 kB/s
Done flashing
make: Leaving directory '/builds/boards/RIOT/examples/hello-world'
```

**Comment by bergzand** [comment]
> This should be in our installation doc, or toolchain doc. We dont have one in code right now. Maybe you can add it to the wiki for now, and when we come around to moving it to code it will be taken into account

@aabadie Do you want me to  open an issue for this? Then we can continue here

**Comment by kaspar030** [comment]
@aabadie I'm seeing the same issue as @fjmolinas. Is FLASH_TARGET_TYPE set somewhere? I'm trying to flash a `nucleo-f103rb`.

**Pull request closed without merging**
