### PR TITLE
makefile/utils: Add a function for checking that a string is not empty.

### PR DESCRIPTION
**Pull request by jcarrano**
### Contribution description

A call to `$(call ensure_value,x,y)` will fail with message y if x is empty, and otherwise return x. This can be useto write more compact makefiles, while still producing friendly error messages.

### Testing procedure

I should provide an automated test for this, in the meantime:

```
$ cd makefiles/util
$ make -f test-checks.mk test-ensure_value
test-ensure_value
$ make -f test-checks.mk test-ensure_value-negative
test-checks.mk:7: *** "This should fail".  Stop.
```

### Issues/PRs references

Split from #10342.

### CODE REVIEW

**Comment by cladmi** [comment]
I added a test and updated the behavior of your test to verify the returned value of `ensure_value`.
The test prints nothing in case of success.

It can be tested by replacing, in the Makefile, the tested target by the other: `{,_negative}`.
Verifying that the check tests `ensure_value` returned value can be done by replacing it in `checks.mk`.


On the naming, I would prefer having the directory named `utils` instead of using the singular form.
I still kept my script with your convention.

**Comment by jcarrano** [comment]
I renamed it to `utils` and squashed.

**Comment by cladmi** [comment]
Nice catch on the typo in the error message.

Codacy wants one line less in the README… you can inline fix it directly.
The commit titles mention `makefile/util` and `makefiles/util`, please update them to `makefiles/utils` at the same time.

I re-ran the tests and verified that they also detected the errors by tweaking the test

**Comment by jcarrano** [comment]
Done. Stupid codacy.

**Pull request merged**
