### PR TITLE
sys/fib: deprecate the module

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description
This appears to be a leftover from a pre-GNRC network stack. There a no known users outside of tests.

### CODE REVIEW

**Comment by miri64** [comment]
> This appears to be a leftover from a pre-GNRC network stack.

Nope, that is an alternative to the FT of the NIB. IMHO, while not in active use, it is still tested and has its merits (it is not bound to IPv6 and it is able to do source routing).

> There a no known users outside of tests.

That's the problem with "known". One can not be sure if it is not used out of tree. IMHO, as long as the maintainance burden is low (which to me it is) there is no good reason to throw out a feature without replacement.

**Comment by miri64** [comment]
> (and was in fact used with GNRC before the NIB existed).

For reference: https://github.com/RIOT-OS/RIOT/pull/8010

**Comment by benpicco** [comment]
My main concern is that it confuses users who might think this is the `fib` used by GNRC or even a generic fib shared across network stacks when in fact it's only useful to users who would want to write their own network stack.

**Comment by OlegHahm** [comment]
> My main concern is that it confuses users who might think this is the `fib` used by GNRC or even a generic fib shared across network stacks when in fact it's only useful to users who would want to write their own network stack.

Couldn't this be addressed by updating the docs accordingly?

**Comment by benpicco** [comment]
> Couldn't this be addressed by updating the docs accordingly?

#19301

**Comment by miri64** [comment]
bors is about to merge #19301, so this can be closed.

**Pull request closed without merging**
