### PR TITLE
.gitignore: add .mypy_cache/

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Since I'm using mypy to lint python files, it's cache directory shows up in "git status".
This PR adds that folder to .gitignore.

### CODE REVIEW

**Comment by miri64** [comment]
Couldn't you just add it to `.git/info/exclude` in your local repo instead?

**Comment by kaspar030** [comment]
> Couldn't you just add it to `.git/info/exclude` in your local repo instead?

Hm didn't think about that. But look at the gitignore, there are other local cache folders included. And noone will ever want a ".mypy_cache/" folder, no?

**Comment by miri64** [comment]
> Hm didn't think about that. But look at the gitignore, there are other local cache folders included. And noone will ever want a ".mypy_cache/" folder, no?

Well most of them seem to be around tools or configurations provided in the repo. There are some IDE ignores appearently though, admitedly. But that those I personally also disagree with. Can I add my `.syntastic_c_config` or `.local.vimrc` then as well?

**Comment by kaspar030** [comment]
> Can I add my `.syntastic_c_config` or `.local.vimrc` then as well?

why not? saves others the hassle to do so.

**Comment by miri64** [comment]
> why not? saves others the hassle to do so.

Naah, too much hassle for something I already have configured locally :P

**Comment by miri64** [comment]
(I won't block your's though, but I don't condone it either)

**Pull request merged**
