### PR TITLE
boards/cpu: remove support for x86

### LINKED ISSUE #7978: What is the state of the x86 port?
Every once in a while I stumble over the `x86` port and wonder, what the state and our future ambitions with this are. At least on my local machin, the `x86-multiboot-common` does not even build ("cpu_conf.h not found), and from a code/structure perspective this port is not really the best state. Also it seems that there is not really any activity around this port for the last 2 years (hope I did not overlook anything).

So just asking: does it makes sense to (at least for now) remove the port?

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #7978

Dry run trying to remove the `x86` port from RIOT.

Note: a separate PR adding the removed modules to the `LOSTANDFOUND.md` will be created once/if we have a consensus on this PR.

### CODE REVIEW

**Comment by kaspar030** [comment]
There's a typo in one commit message (revmoe). Also, for consistency, I propose using imperatives for all of them. (should we add sth like this to the coding conventions?)

**Comment by miri64** [comment]
> Also, for consistency, I propose using imperatives for all of them. (should we add sth like this to the coding conventions?)

Isn't that how you are supposed to compose commit messages anyway? (I don't think something like that belongs into the coding conventions, but rather the contribution guidelines ;-))

**Comment by haukepetersen** [comment]
fixed commit messages.

> Please also remove toolchain/.

I am not sure which ones are effected here: `RIOT/toolchain` was already removed. `RIOT/dist/tools/toolchains/*` holds also build scripts for `gnuarm` toolchains, I guess these should stay?!

**Comment by haukepetersen** [comment]
documentation of the removal is added in #8050

**Comment by kaspar030** [comment]
> RIOT/toolchain was already removed.

Sorry, that was a leftover in my branch.

**Pull request merged**
