### PR TITLE
sys/xtimer: compare two offsets rather than absolute times [backport 2020.01]

### PR DESCRIPTION
**Pull request by MichelRottleuthner**
# Backport of #13212

### Contribution description

This PR fixes a bug in #9530 reported by #13209, making sure to compare two offsets rather than two absolute times when ordering timers. 

### Issues/PRs references

#9530 
#13209

### CODE REVIEW

**Comment by aabadie** [comment]
#13234 is not the right origin PR, it should be #13212. @MichelRottleuthner why not simply use the `backport_pr.py` script ? That would avoid copy-paste mistakes like this.

**Comment by MichelRottleuthner** [comment]
> (...) why not simply use the backport_pr.py script (...)

I didn't even know that exists :fearful:  thanks for the hint!

**Comment by aabadie** [comment]
> I didn't even know that exists

No problem. For the next times, try it, and you will love it!

**Comment by fjmolinas** [comment]
> No problem. For the next times, try it, and you will love it!

Game changer! Hahahaha

**Pull request merged**
