### PR TITLE
doc: added samd21 vendor header to doxygen excludes

### PR DESCRIPTION
**Pull request by haukepetersen**
gets rid of a number of doxygen warnings...

### CODE REVIEW

**Comment by OlegHahm** [comment]
I like this, but I think @kaspar030 has a stronger opinion on this topic.

**Comment by haukepetersen** [comment]
@kaspar030: what do you say? Again: I would vote to exclude this, as this is a vendor supplied header and would be consistent with the other CPUs.

**Comment by haukepetersen** [comment]
@OlegHahm: since this a vendor header, to you ack to merge this?

**Comment by kaspar030** [comment]
ACK.

**Pull request merged**
