### PR TITLE
cpu/lpc11u34 : Added SPI for NXP LPC11U34 (SPI_0 and SPI_1)

### PR DESCRIPTION
**Pull request by ks156**
This pull request adds the support for SPI to the LPC11U34 chip.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
Code looks good, let's wait for the CI.

**Comment by ks156** [comment]
Some test failed due to insufficient memory. I've blacklisted the board in the Makefile.

**Comment by ks156** [comment]
@thomaseichinger : tests pass for cortex m0. Cortex M4 failed due to timeout and msp430 didn't start at all. Travis seems tired :sleeping:

**Comment by thomaseichinger** [comment]
ok, kicked Travis to wake up.

**Comment by thomaseichinger** [comment]
@ks156 Please squash.

**Comment by thomaseichinger** [comment]
ACK & Go

**Comment by ks156** [comment]
@thomaseichinger Thank you :relaxed:

**Pull request merged**
