### PR TITLE
sys: random: rename genrand_* to random_*

### PR DESCRIPTION
**Pull request by kaspar030**
Now that the periph driver has a different name...

Files modified by ```find . -name '*.[hc]' -exec grep -l 'genrand_' \{\} \; | xargs -n 1 sed -i 's/genrand_/random_/g'```

### CODE REVIEW

**Comment by kaspar030** [comment]
I'll randomly reassign.

**Comment by authmillenon** [comment]
ACK. Travis ignored this somehow.

**Comment by authmillenon** [comment]
(try to rebase)

**Comment by authmillenon** [comment]
Ah reopening did the trick! Go when Travis is happy the :)

**Comment by OlegHahm** [comment]
Ah, shit, will have to update this in CCN-Lite.

**Comment by OlegHahm** [comment]
Probably the easiest thing for to get this merged ASAP, is provide a small patch file for CCN-Lite.

**Comment by kaspar030** [comment]
@OlegHahm Hm, the patch is a two-liner: https://gist.github.com/a170dbe510e37df4f7a4
But the ccn-lite pkg Makefile doesn't apply patches. What would be the correct branch in your ccn-lite repo?
Should we somehow coordinate a merge?

**Comment by kaspar030** [comment]
- rebased and included tinymt32 fixes

**Comment by OlegHahm** [comment]
Take a look at master from https://github.com/OlegHahm/ccn-lite.

**Comment by kaspar030** [comment]
So I change the github URL to your fork?

**Comment by kaspar030** [comment]
@OlegHahm not that easy:
```
In file included from ccn-lite-riot.c:41:0:
ccnl-core.c: In function ‘ccnl_interface_cleanup’:
ccnl-core.c:220:24: error: ‘struct ccnl_if_s’ has no member named ‘sock’
     ccnl_close_socket(i->sock);
                        ^
/home/kaspar/src/riot/pkg/ccn-lite/ccn-lite-riot.h:64:47: note: in definition of macro ‘ccnl_close_socket’
 #define ccnl_close_socket(s)            close(s)
                                               ^
ccn-lite-riot.c: In function ‘ccnl_open_netif’:
ccn-lite-riot.c:134:6: error: ‘struct ccnl_if_s’ has no member named ‘sock’
     i->sock = -1;
      ^
ccn-lite-riot.c:143:6: error: ‘struct ccnl_if_s’ has no member named ‘sock’
     i->sock = -1;
      ^
Makefile:144: recipe for target 'lib-ccn-lite.a' failed
make[2]: *** [lib-ccn-lite.a] Error 1
Makefile:15: recipe for target 'all' failed
make[1]: *** [all] Error 2
/
```

**Comment by OlegHahm** [comment]
Yeah, just realize. No problem, will cherry-pick some commits from my ccn-lite working branch. Wait a second.

**Comment by OlegHahm** [comment]
> So I change the github URL to your fork? 

Otherwise you would have to wait until a PR on the ccn-lite side would get merged, which may take longer than we want to wait with this change here. I propose to apply the following diff and revert back to ccn-lite upstreas as soon as my latest changes are merged there.

```diff
diff --git a/pkg/ccn-lite/Makefile b/pkg/ccn-lite/Makefile
index 9961bba..6c81e3f 100644
--- a/pkg/ccn-lite/Makefile
+++ b/pkg/ccn-lite/Makefile
@@ -1,6 +1,6 @@
 PKG_NAME=ccn-lite
-PKG_URL=https://github.com/cn-uofbasel/ccn-lite/
-PKG_VERSION=57be9b1985dc501b26f861b24448b54db37f73f1
+PKG_URL=https://github.com/OlegHahm/ccn-lite/
+PKG_VERSION=39b1406c11de9de364220909488eebabe7e81613
 PKG_DIR=$(CURDIR)/$(PKG_NAME)
 
 ifneq ($(RIOTBOARD),)
```

**Comment by kaspar030** [comment]
That compiles locally. Thanks!

**Comment by authmillenon** [comment]
re-ACK and go.

**Pull request merged**
