### PR TITLE
cpu/msp430: added periph SPI driver

### PR DESCRIPTION
**Pull request by haukepetersen**
~~based on #3724, #3742, and #3760~~

~~CAUTION: This PR is basically not tested, as it depends on other, not yet fixed PRs. I open it anyway, so we can do a feature freeze towards the release today... As soon as the interrupt issue in #3742 and in #3760 is resolved, this PR should also run fine. Will look into this now.~~

### CODE REVIEW

**Comment by OlegHahm** [comment]
I guess you can rebase now.

**Comment by OlegHahm** [comment]
And @thomaseichinger could finally test his cc2420 driver.

**Comment by haukepetersen** [comment]
rebased.

**Comment by thomaseichinger** [comment]
See https://github.com/haukepetersen/RIOT/pull/17 for z1 support.

**Comment by thomaseichinger** [comment]
Please consider https://github.com/haukepetersen/RIOT/pull/18 to get Travis' green light.

**Comment by haukepetersen** [comment]
done.

**Comment by thomaseichinger** [comment]
Issues fixed, please squash. @haukepetersen

**Comment by thomaseichinger** [comment]
ACK when squashed. Merge at will.

**Comment by haukepetersen** [comment]
squashed.

**Comment by authmillenon** [comment]
```
WARNING: The following modified files generate doxygen warnings:
cpu/msp430fxyz/include/msp430_regs.h
```

**Comment by haukepetersen** [comment]
fixed doxygen issue, rebased and squashed.

**Comment by haukepetersen** [comment]
waiting on #3866, as this should make Travis happy.

**Comment by thomaseichinger** [comment]
Please rebase.

**Comment by haukepetersen** [comment]
rebased

**Comment by thomaseichinger** [comment]
ACK when Travis is done.

**Comment by haukepetersen** [comment]
Travis is happy -> go.

**Pull request merged**
