### PR TITLE
net/gcoap: renamed source folder s/coap/gcoap/

### PR DESCRIPTION
**Pull request by haukepetersen**
wanted to do this for a while: IMHO it makes sense to name the source folder of `gcoap` also `gcoap`, as this will prevent potential naming clashes in the future if ever someone else gets into the idea of writing their own coap library...

### CODE REVIEW

**Comment by kb2ma** [comment]
s/gocap/gcoap :-)

**Comment by haukepetersen** [comment]
fixed title...

**Comment by haukepetersen** [comment]
rebased

**Comment by haukepetersen** [comment]
all green -> go

**Pull request merged**
