### PR TITLE
pkg/tlsf,cpu/esp_common: fix possible overflow in calloc implementations

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

The documentation of `void *calloc(size_t nmemb, size_t size)` says it should detect overflows in `nmemb * size`, but the two implementation failed to comply. This fixes the issues.

[Some people might consider this a security fix](https://msrc-blog.microsoft.com/2021/04/29/badalloc-memory-allocation-vulnerabilities-could-affect-wide-range-of-iot-and-ot-devices-in-industrial-medical-and-enterprise-networks/). (But honestly, there are few legitimate use cases of dynamic memory management on MCUs in general. And using unchecked user input (including data received via network) to compute allocation sizes is something that will still allow resource exhaustion attacks even after the fix. So an application previously vulnerable is still vulnerable, only with one attack vector fewer.)

The preexisting test in `tests/malloc` was updated to also check for correct behavior of `calloc()`.

### Testing procedure

On a 32 bit system the following should result in a blowing assertion on `master`, but no longer with this PR:

```C
    assert(NULL == calloc((1UL << 30), 2));
```

Update: `tests/malloc` will check for correct behavior of `calloc`. It needs however to be modified to actually make use of tlsf.

### Issues/PRs references

Found on twitter: https://twitter.com/mumblegrepper/status/1388058046908219394

(But I cannot find the original bug report the tweet is referring to.)

### CODE REVIEW

**Comment by maribu** [comment]
The test in `tests/malloc` passes for newlib 4.1.0 (as packaged in Alpine).

**Comment by kaspar030** [comment]
so the newlib test breaks with current riotdocker. can we maybe drop the test change for now, backport, then merge the test fix?

**Comment by maribu** [comment]
> so the newlib test breaks with current riotdocker. can we maybe drop the test change for now, backport, then merge the test fix?

Done, split out the test into a separate PR.

Being honest, I'm not sure where the two fixed calloc implementations are used; maybe they only have internal usage and the issue is impossible to trigger. But the fix is trivial, unlikely to break anything, and has only minimal impact on ROM size. IMO just getting the fix in is easier than making sure internal usage does not rely on correct calloc semantics.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by kaspar030** [comment]
@maribu do you want me to open the backport?

**Pull request merged**
