### PR TITLE
correcting linker LTO flags on OSX

### PR DESCRIPTION
**Pull request by smlng**
longer discussion here #5787, corrects some changes introduces in #5742 for OSX

### CODE REVIEW

**Comment by gebart** [comment]
ffunction-sections and fdata-sections are already set and -flto is set when the environment variable LTO=1

**Comment by smlng** [comment]
@gebart you're right with `-flto`, I'll correct that. But did you read [this](http://blog.senthilthecoder.com/post/lto-linker-commandline/), it states that `-ffunction-sections` should be added to linker flags, too - not only CFLAGS. Or are CFLAGS applied to the linker as well?

**Comment by gebart** [comment]
CFLAGS should be added to link flags. I think it was added some time ago, but I'm replying from the phone so I can't look up the source now.

**Comment by smlng** [comment]
From what I found, CFLAGS are (somehow) added to LINKFLAGS for many boards, but not in native. But, as already said I'm not expert on compiler or linker options, plus not familiar with the internal details of RIOTs build system - maybe you can check on this later on, when you have a bigger screen and keyboard available?

**Comment by smlng** [comment]
Ping! This isn't that hard, is it? Could we resolve it (very) soon, its an annoying bug when testing on macOS.

**Comment by gebart** [comment]
I'm sorry, I will not be able to assist here for a few days. To anyone interested in this issue, feel free to dig through the makefiles, I suggest starting with `git grep LINKFLAGS`

**Comment by smlng** [comment]
That's what I did and - as said above - I found that for some boards CFLAGS are added to LINKFLAGS, but not for native, which this patch corrects.

**Comment by thomaseichinger** [comment]
This change definitely fixes building on Darwin systems.
CC: @gebart @kYc0o

**Comment by basilfx** [comment]
I can also confirm this works.

**Comment by smlng** [comment]
mhm, everybody seems happy - even Murdock, though this doesn't count in this case as it is OS X specific. Anyhow, I'll squash the 2 commits and then ACK + GO.

**Comment by smlng** [comment]
I'm reluctant to merge my own PR, I just tested it on OS X and Linux again: works for both. We can wait for Murdock to complete  and then GO?

**Comment by smlng** [comment]
Does anybody understand why Murdock fails building `examples/arduino_hello-world`, I don't see how this should be related to the failure?!

**Comment by gebart** [comment]
I believe the arduino error is unrelated to this PR and seem to be a race condition caused by using the application source directory as the destination for the _sketches.cpp file.

**Comment by gebart** [comment]
The failing build is not related to this PR. The change looks OK and is confirmed working by maintainers  above. ACK & go

**Pull request merged**
