### PR TITLE
native: file descriptors

### PR DESCRIPTION
**Pull request by OlegHahm**
Took over this branch from @LudwigOrtmann. Currently testing and potentially updating this. Stay tuned. For now I'll mark it as WIP.

### CODE REVIEW

**Comment by benoit-canet** [comment]
@OlegHahm : There is some overlap with  #3449

**Comment by OlegHahm** [comment]
@benoit-cane: thx for the hint I will look out for this.

**Comment by OlegHahm** [comment]
abandoned

**Comment by LudwigKnuepfer** [comment]
abandoned why? (i.e. is there a conceptual problem or do you just lack time?)

**Comment by OlegHahm** [comment]
Lack of time and motivation

**Pull request closed without merging**
