### PR TITLE
ng_icmpv6_echo: fix time output on shell command

### PR DESCRIPTION
**Pull request by authmillenon**
That was not milliseconds

### CODE REVIEW

**Comment by OlegHahm** [comment]
timex_normalize?

**Comment by authmillenon** [comment]
This converts microseconds to seconds?

**Comment by OlegHahm** [comment]
I don't understand the question. How do you convert microseconds in seconds? Doxygen says that `timex_normalize()` "corrects timex structure so that microseconds < 1000000".

**Comment by authmillenon** [comment]
Did you read my edit?

**Comment by authmillenon** [comment]
I don't understand how `timex_normalize()` would help me here. As you said: it corrects the microsecond part so that it is < 1e6. This PR calculates milliseconds from a second + microsecond pair. What happens here is basically moving the comma by three places to the right.

**Comment by OlegHahm** [comment]
Ah, now I understand. Wouldn't it be much cheaper to change to outputting secondes instead of milliseconds? (Btw. the second case is already `s` instead of `ms`.)

**Comment by authmillenon** [comment]
But I want it to feel like a real `ping6` on linux :(. Also with 6 places behind the comma I think it's much harder to read, than milliseconds.

with the second case your right

**Comment by OlegHahm** [comment]
Just be aware that modulo can become very expensive on some architectures, but for a shell command that probably doesn't matter too much.

**Comment by authmillenon** [comment]
Yes.

**Comment by authmillenon** [comment]
Fixed the one wrong conversion in the second case.

**Comment by cgundogan** [comment]
Tested this. Output looks great. Please fixup so that travis can have a look at it, too.

**Comment by authmillenon** [comment]
Squashed

**Comment by cgundogan** [comment]
kicked..

**Comment by OlegHahm** [comment]
I guess the failing build with MSP430 and ng_networking is a real issue.

**Comment by authmillenon** [comment]
Then let's try this again ;-)

**Pull request merged**
