### PR TITLE
board: port to iotlab M3 of A8

### PR DESCRIPTION
**Pull request by aabadie**
Here is a port to the iotlab-a8-m3. I tried to factorize the code with iotlab-m3 as the only changes are:
* some sensor to remove (isl29020 and lps331ap)
* use a different SPI interface (2 instead of 1) and some GPIO changed

I put all the common code in a  `boards/iotlab-common` directory and the specific code in `boards/iotlab-m3` and `boards/iotlab-a8-m3`.

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
@kYc0o can you review and test this on the hardware?

**Comment by kYc0o** [comment]
Yes sure! I'll review it asap.

**Comment by aabadie** [comment]
branch rebased and conflicts fixed.

**Comment by aabadie** [comment]
Any comment on this one ?

**Comment by kYc0o** [comment]
Sorry for the delay, I'll look into this ASAP.

**Comment by aabadie** [comment]
Rebased and fixed conflicts with master.

**Comment by aabadie** [comment]
For the record, I updated the initial branch:
* openocd config files were not found by the flash target : the `dist` directory is duplicated in both directories
* my previous rebase broke the iotlab-m3 code. It should be fixed now.

**Comment by kYc0o** [comment]
Tested in the new IoT-Lab Saclay site, working like a charm. Thanks @aabadie ! Can you add a small wiki and reference the [tutorial](https://www.iot-lab.info/tutorials/riot-public-ipv66lowpan-network-with-a8-m3-nodes/) to test this new functionality?

I tested this PR with the upstream master with this PR merged, so if you want you can reference the upstream repo when merged.

ACK and let's Murdock have a last word!

**Comment by kYc0o** [comment]
and go!

**Comment by kYc0o** [comment]
Ah! I just forgot a small (but important) thing... can you add your name to the sources you've modified? @OlegHahm what's the procedure on this case? Should he add it on a new PR?

**Comment by OlegHahm** [comment]
Would be probably the best, yes.

**Pull request merged**
