### PR TITLE
ng_at86rf2xx: substract maximum MAC header length for MTU getter

### PR DESCRIPTION
**Pull request by authmillenon**

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by PeterKietzmann** [comment]
In general ACK! But wasn't there the idea once, to keep that size somehow "dynamic" according to the the setup?

**Comment by OlegHahm** [comment]
@peterkietzmann, definitely yes, but for now this is better than nothing. (Or something wrong.)

**Comment by PeterKietzmann** [comment]
Ok there you're right. Then I'll adapt and keep open #3086.

**Pull request merged**
