### PR TITLE
makefiles/docker.inc.mk: use release docker image

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Tag the release docker image. Not sure if we want to merge this right now or start doing it only with future releases...

### Testing procedure

- green murdock
- run release tests maybe?

### CODE REVIEW

**Comment by fjmolinas** [comment]
Ups wrong release.

**Comment by miri64** [comment]
This is closed now, but IMHO we should stick to `latest` in the current master and only use the release docker in the release branch.

**Comment by miri64** [comment]
(`latest` will remain as the latest release of the docker image, right?)

**Comment by fjmolinas** [comment]
> (`latest` will remain as the latest release of the docker image, right?)

yes.

**Pull request closed without merging**
