### PR TITLE
cpu/stm32f0: add flashpage driver from stm32f1 + fix stm32f1 driver

### PR DESCRIPTION
**Pull request by vincent-d**
Hi,

This adds the flashpage driver to stm32f0. It's a copy/paste of the stm32f1. We could maybe move that to stm32_common, but the f2 and f4 (at least, it didn't check f3 and l1) flash are quite different and the driver can not be shared with the whole stm32 family.

It also fixes HSI disabling at the end of the write process.

Tested on nucleo-f091 and nucleo-f042 with tests/periph_flashpage.

### CODE REVIEW

**Comment by kYc0o** [comment]
Please squash.

**Comment by PeterKietzmann** [comment]
@kYc0o PR seems ready if your approval still holds

**Comment by kYc0o** [comment]
Yes it does. However why Jenkins is still working? I noticed that it got stuck for several PRs.

**Comment by miri64** [comment]
@kYc0o Both CIs are happy now. You want to merge? :D

**Comment by kYc0o** [comment]
With pleasure ;-)

**Comment by haukepetersen** [comment]
By the way: let's try not to introduce code duplication: the `flashpage` driver for the `stm32f0` is identical to the one for the `stm32f1` -> clear case for common code... So for the future: let's only merge cpu model specific things when they are acutally specific...

fix: #6574

**Pull request merged**
