### PR TITLE
xtimer: add func to diff with now

### PR DESCRIPTION
**Pull request by cgundogan**
Adds inline functions to return (timer - now).
Just an idea. @kaspar030 what do you think?

### CODE REVIEW

**Comment by cgundogan** [comment]
Actually, I just realized that `xtimer_now_diff` can be removed and `xtimer_now_diff64` renamed to `xtimer_now_diff` and adjusting the return to `return timer->target - xtimer_now();`

**Comment by kaspar030** [comment]
Ah, I see your point now.

**Comment by kaspar030** [comment]
IMHO the solution here is to always set long_target...

**Comment by cgundogan** [comment]
How do you propose to set long_target? If the offset is small enough, target_long will still be 0?

**Comment by kaspar030** [comment]
Sorry, I wasn't clear. xtimer itself should always set the correct long target when setting a timer. I'll take a look.

**Comment by kaspar030** [comment]
We found a different solution.

**Pull request closed without merging**
