### PR TITLE
tests/phydat_dump: use raw strings in expect regexp

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR cleans up the Python automated test script of the `tests/phydat_dump` application: regexp string should be marked as raw string to avoid the following flake8 errors:

```
tests/sys/phydat_dump/tests/01-run.py:19:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:19:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:20:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:20:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:21:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:21:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:22:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:22:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:23:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:23:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:24:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:24:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:25:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:25:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:26:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:26:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:27:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:27:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:28:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:28:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:29:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:29:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:30:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:30:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:31:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:31:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:32:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:32:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:33:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:33:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:34:43: W605 invalid escape sequence '\^'
tests/sys/phydat_dump/tests/01-run.py:35:43: W605 invalid escape sequence '\^'
tests/sys/phydat_dump/tests/01-run.py:36:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:36:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:37:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:37:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:38:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:38:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:39:26: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:39:29: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:40:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:40:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:41:21: W605 invalid escape sequence '\['
tests/sys/phydat_dump/tests/01-run.py:41:24: W605 invalid escape sequence '\]'
tests/sys/phydat_dump/tests/01-run.py:60:45: W605 invalid escape sequence '\^'
tests/sys/phydat_dump/tests/01-run.py:61:45: W605 invalid escape sequence '\^'
```

### Testing procedure

- A green CI
- `tests/phydat_dump` test is still working:

<details>

```
$ make -C tests/phydat_dump all test --no-print-directory 
Building application "tests_phydat_dump" for "native" with MCU "native".

"make" -C /work/riot/RIOT/boards/native
"make" -C /work/riot/RIOT/boards/native/drivers
"make" -C /work/riot/RIOT/core
"make" -C /work/riot/RIOT/cpu/native
"make" -C /work/riot/RIOT/cpu/native/periph
"make" -C /work/riot/RIOT/cpu/native/stdio_native
"make" -C /work/riot/RIOT/drivers
"make" -C /work/riot/RIOT/drivers/periph_common
"make" -C /work/riot/RIOT/sys
"make" -C /work/riot/RIOT/sys/auto_init
"make" -C /work/riot/RIOT/sys/fmt
"make" -C /work/riot/RIOT/sys/phydat
"make" -C /work/riot/RIOT/sys/test_utils/interactive_sync
/usr/bin/ld: /work/riot/RIOT/tests/phydat_dump/bin/native/cpu/tramp.o: warning: relocation against `_native_saved_eip' in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
   text	   data	    bss	    dec	    hex	filename
  31057	    978	  47812	  79847	  137e7	/work/riot/RIOT/tests/phydat_dump/bin/native/tests_phydat_dump.elf
r
/work/riot/RIOT/tests/phydat_dump/bin/native/tests_phydat_dump.elf  
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2021.01-devel-573-g7010e3-pr/tests/phydat_dump_script_enh)
Visual phydat test application
Data:	          12.34 °C
Data:	          12.34 °F
Data:	          123.4 K
Data:	          123.4 lx
Data:	[0]        1234 m
	[1]       13456 m
	[2]      -14567 m
Data:	[0]      1234e1 m
	[1]     13456e1 m
	[2]    -14567e1 m
Data:	[0]        1234 km
	[1]       13456 km
	[2]      -14567 km
Data:	[0]       12.34 m
	[1]      134.56 m
	[2]     -145.67 m
Data:	[0]        1234 mm
	[1]       13456 mm
	[2]      -14567 mm
Data:	       -0.12345 m^2
Data:	      -12345e-6 m^3
Data:	[0]        0.12 g
	[1]        0.34 g
	[2]       56.78 g
Data:	[0]         123 mdps
	[1]         345 mdps
	[2]         678 mdps
Data:	         1234.5 G
Data:	          12345 kA
Data:	          12345 MV
Data:	        12345e7 W
Data:	         1234.5 Gs
Data:	         12.345 dBm
Data:	          12345 C
Data:	          12345 uF
Data:	       12345e-7 F
Data:	         123.45 pH
Data:	          12345 Bar
Data:	          12345 hPa
Data:	         123.45 cd
Data:	          12345 mcts
Data:	         12.345 %
Data:	         1.2345 permille
Data:	          12345 uppm
Data:	          12345 nppb
Data:	         1234.5 g/m^3
Data:	         1234.5 #/m^3
Data:	12:34:56
Data:	2020-02-27

```

</details>

### Issues/PRs references

Raised when running the static test locally in #15358

### CODE REVIEW

**Review by fjmolinas — COMMENTED** [review]
Test still passing:

```
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2021.01-devel-573-g7010e3-pr-15374)
Visual phydat test application
Data:	          12.34 °C
Data:	          12.34 °F
Data:	          123.4 K
Data:	          123.4 lx
Data:	[0]        1234 m
	[1]       13456 m
	[2]      -14567 m
Data:	[0]      1234e1 m
	[1]     13456e1 m
	[2]    -14567e1 m
Data:	[0]        1234 km
	[1]       13456 km
	[2]      -14567 km
Data:	[0]       12.34 m
	[1]      134.56 m
	[2]     -145.67 m
Data:	[0]        1234 mm
	[1]       13456 mm
	[2]      -14567 mm
Data:	       -0.12345 m^2
Data:	      -12345e-6 m^3
Data:	[0]        0.12 g
	[1]        0.34 g
	[2]       56.78 g
Data:	[0]         123 mdps
	[1]         345 mdps
	[2]         678 mdps
Data:	         1234.5 G
Data:	          12345 kA
Data:	          12345 MV
Data:	        12345e7 W
Data:	         1234.5 Gs
Data:	         12.345 dBm
Data:	          12345 C
Data:	          12345 uF
Data:	       12345e-7 F
Data:	         123.45 pH
Data:	          12345 Bar
Data:	          12345 hPa
Data:	         123.45 cd
Data:	          12345 mcts
Data:	         12.345 %
Data:	         1.2345 permille
Data:	          12345 uppm
Data:	          12345 nppb
Data:	         1234.5 g/m^3
Data:	         1234.5 #/m^3
Data:	12:34:56
Data:	2020-02-27

```

**Comment by fjmolinas** [comment]
No flake8 errors raised in this file.

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by aabadie** [comment]
[Failure on Murdock](https://ci.riot-os.org/RIOT-OS/RIOT/15374/7010e331e2f689489a289ada076362f38e36b5af/output/compile/examples/suit_update/nucleo-l552ze-q:gnu.txt) is unrelated. I'm retriggering Murdock without compile tests.

**Pull request merged**
