### PR TITLE
boards/arduino-mega2560: added Ardunio pin mapping

### PR DESCRIPTION
**Pull request by haukepetersen**
added a pin mapping file that maps MCU GPIO pins to Ardunio specific pin numbers

generated from https://www.arduino.cc/en/Hacking/PinMapping2560

### CODE REVIEW

**Comment by kaspar030** [comment]
PR title is wrong.

**Comment by kaspar030** [comment]
Fixed it.

**Comment by kaspar030** [comment]
(but I can't fix the commit message)

**Comment by haukepetersen** [comment]
fixed commit message

**Comment by OlegHahm** [comment]
Looks good. ACK

**Comment by haukepetersen** [comment]
Travis is happy -> go

**Pull request merged**
