### PR TITLE
Cortex-M(3|4): `atomic_arch_set_return()` without `disableIRQ()`

### PR DESCRIPTION
**Pull request by gebart**
This PR is an experimental branch for performing atomic operations without the need to disable interrupts.

Todo: 
 - [x] compare sizes before and after the change.
 - [ ] Test thoroughly on all cortex platforms

### CODE REVIEW

**Comment by gebart** [comment]
Regarding the Travis failures: It seems that some of the CPU headers do not include the core_cmX.h headers, even though they are using cortex-mX_common.

**Comment by thomaseichinger** [comment]
Checking the instruction set, seems cortex-m0 platforms don't know `ldrex` and `strex` instructions.

**Comment by gebart** [comment]
@thomaseichinger Ah, I did not see this line in core_cmInstr.h:
```c
#if       (__CORTEX_M >= 0x03)
...
#define __LDREXB(ptr)                     ((uint8_t ) __ldrex(ptr))
```
I'll revert the M0 change

**Comment by gebart** [comment]
```
  <-------------- Before -------------->  <-------------- After -------------->                                 <- Diff ->
   text    data     bss     dec    hex     text    data     bss     dec    hex  filename                         
  39276    2552    5184   47012    b7a4   39300    2552    5184   47036    b7bc bin/spark-core/default.elf        24
  53968    2568    9148   65684   10094   54000    2568    9148   65716   100b4 bin/fox/default.elf               32
  37272    2552    5336   45160    b068   37296    2552    5336   45184    b080 bin/cc2538dk/default.elf          24
  38820    2552    5184   46556    b5dc   38844    2552    5184   46580    b5f4 bin/nucleo-l1/default.elf         24
  37180    2552    5336   45068    b00c   37204    2552    5336   45092    b024 bin/openmote/default.elf          24
  35836    2552    9784   48172    bc2c   35868    2552    9784   48204    bc4c bin/f4vi1/default.elf             32
  35868    2552    5120   43540    aa14   35900    2552    5120   43572    aa34 bin/stm32f3discovery/default.elf  32
  36060    2552    9792   48404    bd14   36092    2552    9792   48436    bd34 bin/stm32f4discovery/default.elf  32
  39036    2560    7152   48748    be6c   39068    2560    7152   48780    be8c bin/mbed_lpc1768/default.elf      32
  38268    2560    9848   50676    c5f4   38292    2560    9848   50700    c60c bin/arduino-due/default.elf       24
  43664    2608   17176   63448    f7d8   43624    2608   17176   63408    f7b0 bin/msbiot/default.elf           -40
  54896    2568    9188   66652   1045c   54920    2568    9188   66676   10474 bin/iot-lab_M3/default.elf        24
  38244    2560    9848   50652    c5dc   38268    2560    9848   50676    c5f4 bin/udoo/default.elf              24
```

The size of the default example went up by 24-32 bytes on average, but msbiot reduced in size, strange...

**Comment by gebart** [comment]
Closing this for lack of time and in favour of #2321 and a follow-up PR which will replace `atomic_set_return` by `atomic_set`, `atomic_clear`, `atomic_inc`, `atomic_dec`.

**Pull request closed without merging**
