### PR TITLE
boards/stm32l496g-disco: enable ST7789 display and touch panel

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR enables the ST7789 display and the touch panel for the `stm32l496g-disco`.

The PR requires PR #19937.

### Testing procedure

```
BOARD=stm32l496g-disco make -j8 -C tests/drivers/st77xx
```
should work.

### Issues/PRs references

Depends on PR #19937

### CODE REVIEW

**Comment by gschorcht** [comment]
@benpicco The PR had to be rebased after merging PR #19937.

**Review by benpicco — APPROVED** [review]
Just squash the Kconfig fix directly

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Interesting, merging is blocked :thinking: and the CI compilation just took about 3 minutes.

**Comment by gschorcht** [comment]
Ok, merging was obviously delayed.

**Pull request merged**
