### PR TITLE
boards/weact-f411ce: enable automatic reset to bootloader

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This enables to reset the `weact-f411ce` in bootloader mode using the same USB CDC ACM sequence already employed by samd/bossa boards.
For this, the usb reset sequence is moved to a common file.

### Testing procedure

Flash any application on the `weact-f411ce`.

A subsequent `make flash` will automatically reset the board in bootloader mode and flash the new application.
You don't have to press any buttons anymore.

### Issues/PRs references

depends on #14119

### CODE REVIEW

**Comment by maribu** [comment]
This does work, however, I don't like that the `preflash` can fail.

E.g. let's assume I just got a new board without RIOT flashed on it. In that case I have to manually enter the bootloader by pressing NRST while holding BOOT0. After that the DFU bootloader is running and ready to accept the firmware, but there is no `/dev/ttyACM0` anymore. Thus, a `make flash` will fail in the `preflash` target:

```
stty -F /dev/ttyACM0 raw ispeed 1200 ospeed 1200 cs8 -cstopb ignpar eol 255 eof 255
stty: /dev/ttyACM0: No such file or directory
make: *** [/home/maribu/Repos/software/RIOT/examples/default/../../Makefile.include:714: preflash] Error 1
```

Maybe something like this would be a generic solution:

```diff
diff --git a/Makefile.include b/Makefile.include
index 11135a0cd8..9776403304 100644
--- a/Makefile.include
+++ b/Makefile.include
@@ -710,8 +710,13 @@ flash: all $(FLASHDEPS)
 flash-only: $(FLASHDEPS)
     $(flash-recipe)
 
+ALLOW_PREFLASHER_TO_FAIL ?= 1
+PREFLASHER_PREFIX:=
+ifeq (1,$(ALLOW_PREFLASHER_TO_FAIL))
+  PREFLASHER_PREFIX:=-
+endif
 preflash: $(BUILD_BEFORE_FLASH)
-    $(PREFLASHER) $(PREFFLAGS)
+    $(PREFLASHER_PREFIX)$(PREFLASHER) $(PREFFLAGS)
 
 TERMFLASHDEPS ?= $(filter flash flash-only,$(MAKECMDGOALS))
 # Add TERMFLASHDEPS to TERMDEPS so it also applies to `test`
```

And every board where the preflasher must not fail can set `ALLOW_PREFLASHER_TO_FAIL := 0`.

**Comment by benpicco** [comment]
Good idea!
Or how about just

```Makefile
PREFLASHER ?= -stty
```

**Comment by maribu** [comment]
> Or how about just
> 
> ```makefile
> PREFLASHER ?= -stty
> ```

This was also my first idea. But then I thought allowing it to fail and which command to use might be better treated independently, as this allows to inherit the preflasher command. But I wouldn't mind this approach as well.

**Comment by benpicco** [comment]
Ok, but I think we don't need

```
ALLOW_PREFLASHER_TO_FAIL ?= 1
PREFLASHER_PREFIX:=
ifeq (1,$(ALLOW_PREFLASHER_TO_FAIL))
  PREFLASHER_PREFIX:=-
endif
```

When `PREFLASHER_PREFIX` is not set, it will just be empty and do no harm.

**Comment by maribu** [comment]
Please squash and rebase against master. (Without the rebase I get `There are unsatisfied feature requirements: bootloader_stm32`. It would ease biseting if you would do the rebase.)

**Comment by maribu** [comment]
Btw: Thanks for properly splitting out the `usb_board_reset.mk`

**Pull request merged**
