### PR TITLE
boards/due|udoo: cleaned up LED handling

### PR DESCRIPTION
**Pull request by haukepetersen**
simplyfied initialization, added some missing parens and so on.

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
Tested on Arduino Due. Was able to toggle LED.

**Comment by emmanuelsearch** [comment]
ACK

**Comment by PeterKietzmann** [comment]
needs rebase

**Comment by haukepetersen** [comment]
rebased

**Comment by PeterKietzmann** [comment]
Green lights and go

**Pull request merged**
