### PR TITLE
lwip: initialize link-local address correctly

### PR DESCRIPTION
**Pull request by miri64**
lwIP does some weird byte-swapping in netif_create_ip6_linklocal_address()
with non-ethernet-addresses, so I rather initialize it like in GNRC, so it is
compatible to both GNRC and emb6.

### CODE REVIEW

**Comment by miri64** [comment]
Marked for 2016.10, since we can't fix the IEEE 802.15.4 header parsing issue for this release anyway, so Interop between the other stacks isn't possible anyway.

**Comment by kYc0o** [comment]
Ok let's try for the next release.

**Comment by miri64** [comment]
We shouldn't just try, but do ;-) but the interop is lwIP's business ;-)

**Comment by PeterKietzmann** [comment]
I can confirm that with this PR, local address and EUI-64 in lwip correlate like in RIOT. However, I am still not able to transmit UDP packets between two nodes, one with tests/lwip and one with examples/gnrc_networking. 

> so Interop between the other stacks isn't possible anyway

@miri64 do you say it is known that both stacks are currently not interoperable?

**Comment by miri64** [comment]
Yes, but that's on lwIP's side. They don't parse the IEEE 802.15.4 header correctly (they don't check the source PAN elision flag, but [skip](http://git.savannah.gnu.org/cgit/lwip.git/tree/src/netif/lowpan6.c?id=92f385aaed7dcccde632502711281234ccda958c#n1005) it anyway).

**Comment by miri64** [comment]
Yapp: https://github.com/RIOT-OS/RIOT/pull/5741

**Pull request merged**
