### PR TITLE
sys: xtimer: add xtimer_set_timeout_flag()

### PR DESCRIPTION
**Pull request by kaspar030**
This PR adds an xtimer convenience function to set the timeout flag after a certain period.

This intentionally does not allow to set any flag (only THREAD_FLAG_TIMEOUT), or set a flag on any thread (not the calling one), for simplicity and performance reasons.

The thread_flags test is updated with a simple test of the new function.

### CODE REVIEW

**Comment by kaspar030** [comment]
> I think that the unittests dependencies need updating. However, is it OK for a core feature test to 
> depend on a sys module?

Which unittests do you mean? Thread flags don't have unittests (yet). The deps of ```tests/thread_flags``` are updated with the xtimer dependency.

**Comment by gebart** [comment]
Re unit tests: I must have misread when I looked at the diff before.
Tested working on samr21-xpro.

There is another thread flags test `thread_flags_xtimer` which seem somewhat redundant now. Could it be removed? @haukepetersen @kaspar030 
https://github.com/RIOT-OS/RIOT/blob/master/tests/thread_flags_xtimer/main.c

**Comment by kaspar030** [comment]
> There is another thread flags test thread_flags_xtimer which seem somewhat redundant now. Could it be removed? @haukepetersen

Hm, that test was showing a bug in thread_flags, IIRC the thread flag was only triggered the first time. @haukepetersen what do you think, remove the test?

**Comment by gebart** [comment]
Can we modify this test to catch that kind of error as well?

**Comment by kaspar030** [comment]
> Can we modify this test to catch that kind of error as well?

I think the best way would be to do proper unit tests. How about we merge this and go from there?

There are some follow-ups anyway:

- xtimer_set_timeout_flag64()
- make xtimer_sleep* use them
- make xtimer_msg_timeout use the thread flag

...

**Comment by gebart** [comment]
I'm fine with some follow ups

**Pull request merged**
