### PR TITLE
Fix the shell of example/gnrc_networking/

### PR DESCRIPTION
**Pull request by DipSwitch**

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
If @OlegHahm ACKs it he can has it :-)

**Comment by authmillenon** [comment]
@DipSwitch can you please prefix the commit message with the scope `examples: ` and describe the topic of the commit (e. g. "Add local shell handlers for gnrc_networking"?

**Comment by DipSwitch** [comment]
ACK

**Comment by authmillenon** [comment]
You can't acknowledge your own PR ^^

**Comment by authmillenon** [comment]
ACK. Merge when Travis is happy.

**Pull request merged**
