### PR TITLE
dist/tools/tunslip: fix cppcheck warnings

### PR DESCRIPTION
**Pull request by makomi**
Inspired by #480, I used `cppcheck` to cleanup some things. This commit is part of a series of commits (s.a. #5764).

### CODE REVIEW

**Comment by miri64** [comment]
Can confirm that it still compiles. @gebart you had a test setup for this?

**Comment by gebart** [comment]
I'm traveling at the moment, I can test maybe this weekend or next week.

**Comment by miri64** [comment]
@gebart were you able to test?

**Comment by OlegHahm** [comment]
@gebart, any news?

**Comment by gebart** [comment]
Sorry for the absence, I'll test this tomorrow or Sunday.

**Comment by miri64** [comment]
@gebart did you ;-)

**Comment by miri64** [comment]
Summon @gebart ;-).

**Comment by kYc0o** [comment]
Maybe related to #5677 ?

**Comment by miri64** [comment]
There might be some overlap, but this is primarily a static code analyzer fix, while #5677 is code beautification ;-).

**Pull request merged**
