### PR TITLE
cpu/stm32f4: added lost port clock eanble

### PR DESCRIPTION
**Pull request by haukepetersen**
Seems like I broke the GPIO driver implementation when optimizing it - the ports clock activation got lost... Should be fixed again with this PR.

### CODE REVIEW

**Comment by fnack** [comment]
Code's looking good. Input pins worked like a charm and my CC3000 now works with this one again as well. But I have no equipment here to test the signal for output pins, so it might be good if @PeterKietzmann could test for the F4Discovery Board?

**Comment by PeterKietzmann** [comment]
Yep I 'll test this

**Comment by PeterKietzmann** [comment]
ACK. Also checked pins as outputs.

**Comment by PeterKietzmann** [comment]
And go

**Pull request merged**
