### PR TITLE
drivers/lsm6dsl: add power up/down functions

### PR DESCRIPTION
**Pull request by vincent-d**
This PR adds ability to power down the LSM6DSL accelerometer and gyroscope independently.

The test app is updated accordingly.

### CODE REVIEW

**Comment by smlng** [comment]
I approve the added functionality, but I (very much) dislike the changes to the test application. Currently the test is rather simple and easy, requiring no user interaction (and thus knowledge) to run.

**Comment by vincent-d** [comment]
@smlng would you prefer I add the power down/up as a step in the infinite loop, let's say every 4 or 5 loops?

I'd really prefer that code is called from somewhere so completely remove it from a test app is not an option IMO.

**Comment by smlng** [comment]
I agree with you that these function should be tested somehow, but I do not like to use the shell for that matter and thereby turning this currently self running test into a user-interactive test.

That said I would suggested something like:

- init the device
- try to power down gyro and acc, exit on error
- try to power up both again, exit on error
- run measuring loop as before

**Comment by vincent-d** [comment]
Reworked test app as @smlng requested

**Comment by smlng** [comment]
please squash

**Comment by smlng** [comment]
looks good now, tested ACK, btw.

**Comment by vincent-d** [comment]
Squashed

**Pull request merged**
