### PR TITLE
check-pr.yml: Fail when `State: waiting for CI update` is set

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
See https://github.com/RIOT-OS/RIOT/pull/18956#issuecomment-1342781762

### Testing procedure
I've set the label in question, so the test should fail in the beginning.

### Issues/PRs references
See https://github.com/RIOT-OS/RIOT/pull/18956

### CODE REVIEW

**Comment by miri64** [comment]
> I've set the label in question, so the test should fail in the beginning.

https://github.com/RIOT-OS/RIOT/actions/runs/3650150320/jobs/6165766644 it did.

**Review by kaspar030 — APPROVED** [review]
ACK.

bors merge

**Comment by kaspar030** [comment]
bors merge

**Comment by kaspar030** [comment]
We might be hitting this: https://github.com/bors-ng/bors-ng/issues/1492 :(

**Comment by kaspar030** [comment]
bors merge

**Comment by miri64** [comment]
Should I rebase, as recommended in the referenced issue?

**Comment by kaspar030** [comment]
> Should I rebase, as recommended in the referenced issue?

yeah! I don't have a better idea.

**Comment by miri64** [comment]
bors merge

**Pull request merged**
