### PR TITLE
drivers/ng_at86rf2xx: correct array bounds on tx_pow_to_dbm

### PR DESCRIPTION
**Pull request by gebart**
There are only 37 entries in the array in the C file as well as in the
table in the data sheet.

Fixes the following cppcheck error:

    drivers/ng_at86rf2xx/ng_at86rf2xx_getset.c:49: error (arrayIndexOutOfBounds): Array 'dbm_to_tx_pow_868[37]' accessed at index 37, which is out of bounds.

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by PeterKietzmann** [comment]
@OlegHahm why didn't you merge? Travis is happy. At least now...

**Comment by haukepetersen** [comment]
ACK and go :-)

**Comment by OlegHahm** [comment]
> @OlegHahm why didn't you merge? Travis is happy. At least now...

The PR was only open for 3 hours and it was quite early on a Monday, so I wanted to give others the chance to look at it.

**Comment by PeterKietzmann** [comment]
Whoops didn't look at the time :-), just saw the ACK

**Pull request merged**
