### PR TITLE
cpu/esp32: always include libc_gettimeofday

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Tries to fix the issue described in https://github.com/RIOT-OS/Release-Specs/issues/247#issuecomment-1111511070, I'm not sure why this does not fail more loudly, is there a `weak` implementation being used instead? Does the same thing need to be done for `esp8266`?

### Testing procedure

I sadly don't have the hardware to test maybe @benpicco  could? I would want to do as in https://github.com/RIOT-OS/Release-Specs/blob/faafe7bcbaf13751b9b07cf5490a7bead13faa27/08-interop/README.md#task-13---icmpv6-echo-between-esp-and-named-internet-host-through-linux-with-6lowpan/

### Issues/PRs references

#https://github.com/RIOT-OS/Release-Specs/issues/247

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
This fixes the issue on esp32.
It doesn't appear to be required for esp8266 - that works without it.

**Comment by fjmolinas** [comment]
> This fixes the issue on esp32. It doesn't appear to be required for esp8266 - that works without it.

Thanks for testing and figuring out the issue!

**Comment by gschorcht** [comment]
`_gettimeofday_r` is a ROM function provided here `https://github.com/RIOT-OS/RIOT/blob/77382affa3d476beae5b1ed96031bf3b8745cf85/cpu/esp32/ld/esp32.rom.ld#L151

**Comment by benpicco** [comment]
hm maybe that address is no longer correct?

**Comment by benpicco** [comment]
hm maybe that address is no longer correct?

**Pull request merged**
