### PR TITLE
Psoc5lp

### PR DESCRIPTION
**Pull request by cakmakmurat2000**
This branch is created to port RIOT to cy8ckit-050 development kit which designed for Cypress PSoC 5LP IC.  
Following directories are added;
 - board/cy8ckit-050
 - cpu/psoc5lp
 - dist/PSoCCreator

RIOT is ported to an empty PSoC Creator project.  To use this port, please open following file with PSoC Creator IDE (please download from http://www.cypress.com/psoccreator/);
 -> dist/PSoCCreator/RIOT.cywrk

This is a PSoC Project and developer only use RIOT port with this project. Default RIOT build environment cannot be used with this port; PSoC port does not include makefile's. 

PSoC IC's does not have some HW blocks (e.g. Timer, UART ) as default. Some simple HW blocks are created for RIOT. RIOT Project under dist/PSoCCreator already contains those HW designs. 

PSoC Creator IDE creates some file for device initialization. It is also creates files for created HW designs. (Auto-generated file will be created after build in PSoC Creator). board and cpu files use those files directly. This port did not try to re-implement all.

Please, open RIOT project with PSoC Creator, build and download to device. RIOT is going to work on PSoC 5LP. 

Note: Other development kit environments(LCD, Buttons, LEDs etc.) will be supported in the next revisions.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Hm, anyone with any idea how to test this?

**Comment by cakmakmurat2000** [comment]
I am sorry, Is there any link (e.g. wiki page) which introduces testing the RIOT?  
Are unit tests active or do we have nightly build tests? 
Is there any code coverage expectation for testing?

**Comment by cakmakmurat2000** [comment]
So, What do you think about testing?

I can also write test codes in PSoC Creator project.

**Comment by OlegHahm** [comment]
Maybe you can first fix the issues Travis is complaining about:
1. line ending with white spaces.
2. blacklist some applications

**Comment by cakmakmurat2000** [comment]
Is there any way to see details of fails (e.g. line numbers)?

I didnot create make files for PSoC 5LP Port because PSoC Creator dont use makefiles. 
May some of issues be related with missing makefiles.

**Comment by OlegHahm** [comment]
For the white space issue, just call `git diff --check $(git merge-base master HEAD)` from your branch.

**Comment by OlegHahm** [comment]
Is it even possible to build for this platform with make?

**Comment by cakmakmurat2000** [comment]
Hi Oleg, 

I have also added auto-generated files and makes files for default RIOT build. But PSoC Creator project are still under dist/PSOCCreator/cy8ckit-050 folder. ,
,
I have copied auto-generated files from this project. There are many files under cpu/psoc5lp/boot (~1.4MB)  and they will also need manual maintanence.

**Comment by cakmakmurat2000** [comment]
Additionally, 
Using default RIOT build system also requires a conversion(by a tool) to a special HEX from ELF file because PSoC devices needs a special formatted HEX. PSoC tools (ELF converter, programmer etc. ) are implemented for Windows so developer will have to use Windows OS too. 
I will try to automatize this conversation under RIOT build for Windows OS. (PSoC Creator makes this conversation automatically after build)

**Comment by cakmakmurat2000** [comment]
Travis CI build has some error for my PR. 
https://travis-ci.org/RIOT-OS/RIOT/jobs/54232430

But I can build failed examples and tests in my local (both windows and linux) by re-cloning psoc5lp branch with BOARD=cy8ckit-050 parameter.

What is the problem? What am I missing?

**Comment by cakmakmurat2000** [comment]
Any response for Travis build fail?

**Comment by OlegHahm** [comment]
Travis is still complaining about white spaces. Let me check where exactly.

**Comment by OlegHahm** [comment]
```
git diff --check $(git merge-base origin/master HEAD) | grep trailing | awk '{ FS=":"; print $1 }' | sort | uniq
cpu/psoc5lp/boot/CharacterLCD.h
cpu/psoc5lp/boot/CharacterLCD_LCDPort_aliases.h
cpu/psoc5lp/boot/CharacterLCD_LCDPort.h
cpu/psoc5lp/boot/CLK_TIMER.c
cpu/psoc5lp/boot/CLK_TIMER.c:12:
cpu/psoc5lp/boot/CLK_TIMER.h
cpu/psoc5lp/boot/CLK_UART.c
cpu/psoc5lp/boot/CLK_UART.h
cpu/psoc5lp/boot/cydevicegnu.inc
cpu/psoc5lp/boot/cydevicegnu_trm.inc
cpu/psoc5lp/boot/cydevice.h
cpu/psoc5lp/boot/cydevice_trm.h
cpu/psoc5lp/boot/cyfitter_cfg.c
cpu/psoc5lp/boot/cyfitter_cfg.h
cpu/psoc5lp/boot/CyFlash.c
cpu/psoc5lp/boot/CyLib.c
cpu/psoc5lp/boot/cyPm.c
cpu/psoc5lp/boot/CySpc.c
cpu/psoc5lp/boot/LED3_aliases.h
cpu/psoc5lp/boot/LED3.h
cpu/psoc5lp/boot/LED4_aliases.h
cpu/psoc5lp/boot/LED4.h
cpu/psoc5lp/boot/project.h
cpu/psoc5lp/boot/TIMER0.c
cpu/psoc5lp/boot/TIMER0_CONTROL.c
cpu/psoc5lp/boot/TIMER0_CONTROL.h
cpu/psoc5lp/boot/TIMER0.h
cpu/psoc5lp/boot/TIMER0_IRQn.c
cpu/psoc5lp/boot/TIMER0_IRQn.h
cpu/psoc5lp/boot/UART0_BOOT.c
cpu/psoc5lp/boot/UART0.c
cpu/psoc5lp/boot/UART0_RX_IRQn.c
cpu/psoc5lp/boot/UART0_RX_IRQn.h
cpu/psoc5lp/boot/UART0_TX_IRQn.c
cpu/psoc5lp/boot/UART0_TX_IRQn.h
cpu/psoc5lp/cpu.c
cpu/psoc5lp/periph/timer.c
cpu/psoc5lp/periph/uart.c
cpu/psoc5lp/psoc5lp_linkerscript.ld
dist/PSoCCreator/cy8ckit-050/RIOT-CY8CKIT-050.cydsn/dist_readme.txt
dist/PSoCCreator/cy8ckit-050/RIOT-CY8CKIT-050.cydsn/doc_readme.txt
dist/PSoCCreator/cy8ckit-050/RIOT-CY8CKIT-050.cydsn/main.c
dist/PSoCCreator/cy8ckit-050/RIOT-CY8CKIT-050.cydsn/Notes
dist/PSoCCreator/cy8ckit-050/RIOT-CY8CKIT-050.cydsn/pkg_readme.txt
```

**Comment by OlegHahm** [comment]
You could use `sed -i 's/\s\+$//'` to fix these errors.

**Comment by OlegHahm** [comment]
White spaces seem to be fixed, but now we have a license issue.

**Comment by cakmakmurat2000** [comment]
Yes, I am still waiting response from Cypress Lawyers about Licensing. I will fix when I am answered.

**Comment by cakmakmurat2000** [comment]
Why am I getting build error in example folders in Travis Build : https://travis-ci.org/RIOT-OS/RIOT/builds/57270738

I can build all in my local. 

It is not related with license issue, is not it?

**Comment by OlegHahm** [comment]
No, that's not license related, but I have no clue what's wrong. I'll test locally.

**Comment by OlegHahm** [comment]
Confirmed - builds like charm locally. @authmillenon, @Kijewski, IIRC there was a way to get more verbose output from Travis' buildtest, right?

**Comment by authmillenon** [comment]
I have no idea… but have you rebased the branch to master before building? That is where travis mostly get weird unexpected errors from. Because it does that ;-)

**Comment by OlegHahm** [comment]
```
git co cakmakmurat2000/psoc5lp 
...
git rebase origin/master
...
make buildtest                                                                                              [14:32:37][0]
Building for airfy-beacon .. success
Building for arduino-due .. success
Building for arduino-mega2560 .. success
Building for avsextrem .. success
Building for cc2538dk .. success
Building for chronos .. success
Building for cy8ckit-050 .. success
...
```
Weird.

**Comment by LudwigOrtmann** [comment]
Just build an application for this board directly to get more output.
http://bit.ly/1ynpA6N => https://github.com/RIOT-OS/RIOT/issues/1377#issuecomment-51484021

**Comment by cakmakmurat2000** [comment]
Hi all, 

I am not able to get response/support from Cypress Semi about license issues more than one month and also I transfered to different company one month ago from Cypress so I  cannot access to internal resources now. 

Therefore, Can we withdraw this pull request? 

Regards. 
Murat.

**Comment by LudwigOrtmann** [comment]
Sure, if you don't want to work on it anymore you can just close it (button below).

**Comment by OlegHahm** [comment]
Apparently, @cakmakmurat2000 decided to abandon this effort.

**Comment by andrew-from-pretoria** [comment]
Has anybody else taken up this port?

**Comment by zaya-mc** [comment]
Hello @andrew-from-pretoria , I dont have time to complete this effort for now but if you have questions about processor or my port effort, I will be happy to answer.

**Comment by andrew-from-pretoria** [comment]
Dear Murat

Thank you for the response.

We are porting RIOT to SmartFusion2 SoC and your experience may be helpful.

We have made some progress in the port and hope to share our successes with the RIOT community once our port is mature.

Kind regards
Andrew

-- 
=================================================================================================
CSIR Meraka Institute 
www.meraka.org.za | www.csir.co.za 
tel +27 (0)12 841 4626   fax +27 (0)12 841 4720. 
Mail: Building 43a, PO Box 395, 0001, South Africa
=================================================================================================



>>> On 16/08/2017 at 22:13, in message
<RIOT-OS/RIOT/pull/2501/c322885447@github.com>, Murat Cakmak
<notifications@github.com> wrote:
- Hello @andrew-from-pretoria , I dont have time to complete this effort for 
- now but if you have questions about processor or my port effort, I will be 
- happy to answer.
- 
- -- 
- You are receiving this because you were mentioned.
- Reply to this email directly or view it on GitHub:
- https://github.com/RIOT-OS/RIOT/pull/2501#issuecomment-322885447


--

This message is subject to the CSIR's copyright terms and conditions, e-mail legal notice, and implemented Open Document Format (ODF) standard. 
The full disclaimer details can be found at http://www.csir.co.za/disclaimer.html. 

Please consider the environment before printing this email.

**Pull request closed without merging**
