### PR TITLE
iotlab: add capability to create and connect to debug server

### PR DESCRIPTION
**Pull request by authmillenon**
~~It's a little bit hacky, since I did not manage to find out how to get a easily parsable list of the nodes of an experiment~~ (nvm found one), but here's my proposal for the usage of `--debug-start` in Makefile.iotlab.

### CODE REVIEW

**Comment by cladmi** [comment]
I see two simplifications:

* you don't need to only get the `m3-XX` part of the node for the url the whole hostname also works. This can simplify the sed command to get IOTLAB_DEBUG_NODE.  `sed 's/.*: "\(.*\)".*/\1/'`

     ```
    harter@grenoble:~$ host m3-1.grenoble.iot-lab.info
    m3-1.grenoble.iot-lab.info has address 172.16.10.1
    harter@grenoble:~$ host m3-1
    m3-1.grenoble.iot-lab.info has address 172.16.10.1
    ```

* For the port forwarding, you can use `ssh -N` option to not execute a remote command and wait for `ctrl+c`

Also your experiment id is hardwritten in the command to get debug node.

**Comment by authmillenon** [comment]
Addressed

**Comment by cladmi** [comment]
Looks good like this, not tested though.

Also a variable for "$(IOTLAB_USER)@$(IOTLAB_SITE).iot-lab.info" can be added, but it's not related to the 'debug' feature, only refactoring.

I look into adding a feature to select values from the cli-tools output, like an xpath for json selection.

**Comment by authmillenon** [comment]
There are a number of tools already available ([jq](https://stedolan.github.io/jq/) looks nice e.g. [[Source](http://unix.stackexchange.com/a/121734)]). I just wanted to keep dependencies low.

**Comment by authmillenon** [comment]
> Also a variable for "$(IOTLAB_USER)@$(IOTLAB_SITE).iot-lab.info" can be added, but it's not related to the 'debug' feature, only refactoring.

[RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.2) refers to this as the "authority" of a URI, so my newest commit refers to it by this name by introducing the macro `IOTLAB_AUTHORITY`

**Comment by authmillenon** [comment]
Reordered commits and squashed.

**Comment by cladmi** [comment]
ACK, perfect.

**Comment by OlegHahm** [comment]
How is this supposed to work? If I fire this from my local computer, something like `m3-123.grenoble.iot-lab.info` cannot be resolved, but executing this on directly on `grenoble.iot-lab.info` doesn't work either (for various reasons).

**Comment by cladmi** [comment]
I think you should access it with "localhost:3333" on your computer using the ssh port forwarding.

And it does not work on grenoble.iot-lab.info because "grenoble" is not in the internal DNS (don't know why), and that you would also need to add the frontend ssh key as public key.

**Comment by authmillenon** [comment]
@OlegHahm you just use `BOARD=iotlab-m3 make iotlab-debug-server` which starts the debug server on the iotlab site and opens a SSH tunnel to `localhost:<IOTLAB_DEBUG_PORT>` (typically `localhost:3333`). Then you can connect to the debug as you would locally using `BOARD=iotlab-m3 make debug`. As @cladmi pointed out: there seems to be no DNS entry for "grenoble" in the internal SSH, so your `IOTLAB_DEBUG_NODE` macro needs to be set just to `m3-123`

**Comment by OlegHahm** [comment]
If I access this locally, I get
```
Remote debugging using :3333
Remote connection closed
```
in the terminal where I call `make debug` and 
```
Debug on node m3-25.lille.iot-lab.info
channel 2: open failed: connect failed: Connection refused
```
in the terminal with `make iotlab-debug-server`.

On the IoT-LAB hosts, no arm-none-eabi-gdb seems to be installed.

**Comment by cgundogan** [comment]
I can confirm everything @OlegHahm stated above.

**Comment by authmillenon** [comment]
Will try out ASAP. When this was merged it definitely was working.

**Comment by cgundogan** [comment]
I can also confirm that it used to work. @cladmi I think port `3333` is not open after running `node-cli --debug-start`. Did the port change maybe?

**Comment by cladmi** [comment]
Ok I introduced a regression in the last version.

When running `--debug-start` the result of the command should be '1' for all nodes.
I'm I right? This means the debug start failed and so should not work.

The bug is here: https://github.com/iot-lab/iot-lab-gateway/blob/master/gateway_code/utils/openocd.py#L82 It should be `**self._openocd_args`.

Part that was not tested, of course.

I'm finally writing the tests and will correct this.

**Comment by cladmi** [comment]
Fixed in iot-lab-gateway 2.0.2: https://github.com/iot-lab/iot-lab-gateway/tree/2.0.2
Will see to release it as soon as possible.

**Comment by cladmi** [comment]
Released on Grenoble, sorry for the inconvenience.

**Comment by OlegHahm** [comment]
Thanks for the fix and information. Confirmed to be working again.

**Pull request merged**
