### PR TITLE
cpu/stm32l1: allow running in low-power run (MSI)

### PR DESCRIPTION
**Pull request by lebrush**
This implements the low power run mode in the stm32l1 MCU.

**EDIT**: and also allows to run without using PLL.

### CODE REVIEW

**Comment by lebrush** [comment]
@haukepetersen @miri64 ping!

**Comment by lebrush** [comment]
Rebased and ping @haukepetersen @DipSwitch

**Comment by haukepetersen** [comment]
Sorry, lost sight of this PR... 

Just tested the `default` example on the `nucleo-l1`: the board is stuck after the `This is RIOT!...` message and never reaches the shell for some reason. Don't have time right know to look into this, but as the UART is doing some output already, seems that this could be something unrelated to the clock init code?!

**Comment by gebart** [comment]
someone else will have to take this, I don't have any stm32l1 hardware.

**Comment by tcschmidt** [comment]
@haukepetersen is this still useful from the perspective of the new PM concepts?

**Comment by tcschmidt** [comment]
@MichelRottleuthner @roberthartung finish or close?

**Comment by roberthartung** [comment]
Some parts seem to be useful! However, someone was talking about implementing a generic clock module for the stm32 family, in order to change clocks for the sleep modes, which was the reason we didn't implement the new PM layered for stm32 whatsoever.

**Comment by lebrush** [comment]
No time to work on it right now. Feel free to close and add a memo.

**Pull request closed without merging**
