### PR TITLE
cpu/cc2538: fix debug statements

### PR DESCRIPTION
**Pull request by jasonatran**
This PR fixes the input arguments to two debug statements.

### CODE REVIEW

**Comment by kYc0o** [comment]
Can you change the commit message to the standard conventions?

**Comment by jasonatran** [comment]
@kYc0o: Sorry about that! I'm still new to this community -- I hope this is correct. Please let me know if I am missing anything else.

**Comment by kYc0o** [comment]
Don't worry I know how it is ;) all we passed through that. The.previous commit name was avoiding the CI to complete the tests :)

**Comment by PeterKietzmann** [comment]
ACK and go

**Pull request merged**
