### PR TITLE
[WIP] doc: Use Sphinx for documentation.

### PR DESCRIPTION
**Pull request by jcarrano**
## Documentation in RIOT

Right now, RIOT is (partly) documented using Doxygen. While it is a great tool, it has its limitations. The main problem with Doxygen is that it is a tool designed for API reference. Documentation is much more than API reference. Ideally we would want to have a "RIOT handbook" that walks the user through the different parts of the system, and guides the developer who wants to improve RIOT, alongside the API reference.

Doxygen does an excellent job at capturing and extracting the low-level details, but has no support for higher-level concepts (like modules, packages or custom constructs). It does not have the flexibility to support them either. In general, it is very oriented towards documenting files and C++ (or C, or Java) constructs. For C the problem is worse because several concepts which are used in practice (like objects and interfaces) do not have a formal representation in thus language and are thus hard to document.

Regarding the flexibility of doxygen: it is not easy to customize the output. The HTML output does not (easily) support full text search. The only way to organize the docs is with groups, whose meaning is not very well defined, and one ends up with the same entity appearing in multiple pages.

Last, if a modules has really good documentation, it will probably be too much to have it as a comment in a header file.

## [Sphinx](http://www.sphinx-doc.org/)

Check out the preview here: https://riot-os.readthedocs.io/ . It's still missing everything.

### Benefits

* Full text search
* Customizable and themeable output
* Support for automatic documentation using Doxygen and ~[Breathe](http://breathe.readthedocs.io/)~ [antidox](https://github.com/riot-appstore/antidox).
* Support for custom ["domains"](http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html). We could define a RIOT domain whose roles are, for example "package", "module", "board", etc. 
* If necessary, we can make our own extensions.
* We can publish on [Read the Docs](https://readthedocs.org/).
* We can structure the docs like we want.
* Supports markdown, so we don't need to rewrite what we have. There are [reasons](http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/) for writing new docs in reStructuredText, though.

### Downsides

* Requires a more manual involvement for writing and organizing the docs.
* The build process is slower an more complex.
* The integration between Doxygen and Sphinx is not perfect (though it can be improved)
* It is more noticeable if we are missing something (maybe this is good). Doxygen, in contrast, is specially good at extracting loads of content.

### Example

The Zephyr project is using Sphinx+Breathe+Doxygen. Check it out [here](http://docs.zephyrproject.org/index.html).

### Procedure

1. Doxygen generates XML output.
2. ~`breathe-apidoc` reads the XML and generates reStructuredText documents with indices (e.g. `doxygenclass` directives)~ [I need to figure out this step]
3. Sphinx (with the ~breathe~ antidox extension) reads hand written MD and RST documents, plus the ones generated in step 2. When a `doxygen*` directive is found, the XML database is read and the appropriate document nodes are generated.  

## TODO

- [x] Publish a preview of the Sphinx docs.
- [ ] Sketch an outline for the Docs
- [ ] Make the process automatic: There is still not a single makefile controlling everything.
- [ ] Remove conflicting definitions: Doxygen does not like the same entity defined more than once. This happens a lot in board support code. Solution: we can create "fake" interfaces, and "fake" implementations, so we get some sort of namespacing.
- [ ] ~Customize breathe-apidoc: The indices it generates are not very detailed.~ antidox provides full XSLT support.
- [ ] Extract huge comment blocks into their own documents (for example, sock)
- [ ] Create a RIOT hierarchy.
- [ ] Migrate some documents from the wiki.
- [ ] Reduce build times: it takes ages now. See [this issue](https://github.com/michaeljones/breathe/issues/315). I'm working on a replacement extension.

### Further enhancements

- [ ] Configure [extlinks](http://www.sphinx-doc.org/en/master/ext/extlinks.html) to easily refer to PRs and issues.
- [ ] Add RIOT specific domain. This would provide a "standard" way of documenting packages, boards, etc.
- [ ] Make a prettier changelog (there are other project to steal scripts from)

## Related PRs

Complementary to: #8516

### CODE REVIEW

**Comment by miri64** [comment]
While I welcome the work you've put into this, we should be careful with such a huge change. IMHO, this is not something we should decide with one ACK ;-)

PS: also if it comes to it, we need @OlegHahm I think, to change the deployment script for doc.riot-os.org / api.riot-os.org ;-).

**Comment by jcarrano** [comment]
@miri64 I know, I thought I had marked it as a WIP, but the label seems to have disappeared. There are several issues where it is by no means obvious how to proceed and that's why I need feedback from the community.

**Comment by jcarrano** [comment]
I added a link to the Zephyr docs.

**Comment by jcarrano** [comment]
Check out https://riot-os.readthedocs.io/
I had to apply a few hacky hacks so that the compilation does not time out.
Additionally, I forgot to turn off the "classic" theme.

**Comment by miri64** [comment]
Some superficial comments on that: 

* Can we remove the leading "Group" in the group list?
* Can we keep the hierarchy of the groups?

**Comment by miri64** [comment]
+ can we call groups modules instead, to keep with the old style?

**Comment by miri64** [comment]
(sorry for the dripping comments, just notice it as I go)

* Somehow all the CPUs and boards are missing

**Comment by jcarrano** [comment]
@miri64 

> Can we remove the leading "Group" in the group list?
> can we call groups modules instead, to keep with the old style?

It says groups because right now it is just listing Doxygen groups (everything defined with `@defgroup`). This is lazt should be fixed. Some files are in more than one group, which can be ok conceptually, but it should not show up like that in the docs.

> Somehow all the CPUs and boards are missing

I removed them on purpose. There are some issues in breathe (actually in minidom) that cause it to take up a lot of RAM and the build failed on rtd. Also, listing lots of duplicate functions for each CPU did not make much sense for the manual (it is OK for the API reference)
We will have to decide how to document the boards in a sensible way, maybe import from the wiki.

**Comment by miri64** [comment]
Please put a big banner or something on the readthedocs page that that documentation is currently in Beta (or Alpha even) and refer to the official doc (doc.riot-os.org)

**Comment by jcarrano** [comment]
As an internal note, so I don't forget in the future:
I'm writing the Lua docs right now, and I realize the **pain** of writing narrative documentation with Doxygen is even greater than I initially supposed. Markdown's **lack of proper directives** makes it worse (for those who want to stick to markdown!!)

**Comment by jia200x** [comment]
hi @jcarrano,

As far as I see, these PR still depends on #8516 because the board documentation is there. Am I right?

**Comment by jcarrano** [comment]
@jia200x I wouln't sat it *depends* on it. I would be nice to have and quite dumb to migrate the document twice, but #8516 does not block this PR because boards can be added to the docs at any time.

It's a pity that they will be formatted with doxygen's flavor of markdown, which needs some touch ups to be acceped by Sphinx (it accepts markdown, but not doxygen `@ref` directive which tend to be used a lot in documents).

**Comment by jcarrano** [comment]
Due to some issues in Breathe (https://github.com/michaeljones/breathe/issues/315) the build in Read the Docs times out (and runs out of memory).

For that reason I'm developing a custom extension for Sphinx: https://github.com/riot-appstore/antidox/ as, according to the bug report in Breathe, their issue is hard to solve.

The custom extension will also be more customizable which I envision will be critical in getting this merged (we have to please everyone!).

**Comment by jcarrano** [comment]
@aabadie I looked at the thread and at the code and got the opposite impression.

Another issue is customization. If you look at my extension, there is almost **no display logic written in python**. It is all handled by XSLT. There is an included stylesheet, but the user can also provide his own (and xsl:import the included one to inherit all templates). This means we will not ever have to tolerate things not showing up like we want.

> If memory consumption is problematic with RTD ....

Even if I could, I don't think it is OK to have such a long build time for docs. My own PC sounded like it's going to catch fire each time I did `sphinx-build`. Also, we will want to run doctests on doxygen too for each PR.

**Comment by OlegHahm** [comment]
Thanks for the thoughts and input, @jcarrano! Great work!

As long as the API documentation can still be written in doxygen style, I don't see a blocking issue. But if we need to adapt the format of the comments, I'm a bit hesistant, since doxygen syntax is so established and widely understood.

Concerning your points:
> Requires a more manual involvement for writing and organizing the docs.
> The build process is slower an more complex.

Can you elaborate a little bit? What does it mean? More manual involvement because we can do more with the Sphinx documentation compared to doxygen or even more involvement for the parts that we currently _can_ do with doxygen?
Can you give some rough numbers concerning the overhead for building the documentation? And what does "more complex" mean here?

**Comment by aabadie** [comment]
Even if I'm in favor of having the documentation managed by sphinx, I think we should stick to commonly/widely used sphinx extensions (breathe) to integrate the existing doxygen comments.
I don't think writing your own extension (antidox ?) is the way to go. In the future, you'll have to maintain it and this adds another technical depth just because you want to build on ReadTheDocs.

> We can publish on Read the Docs.

Why is this a requirement ? I see it more as a contraint since RTD has very limited resources for building documentation (1 or 2GB per project). The only benefit (and not the least) of RTD is the possibility to keep versions of the documentation (one tag, one version + master as latest version).
I know other projects that build their docs on their CI (Circle CI, Travis, etc) and have tweaks to manage their versions.

**Comment by jcarrano** [comment]
@OlegHahm To elaborate a bit more:

**Comment by jcarrano** [comment]
@OlegHahm, to elaborate a bit more:

### Fomatting

It is not necessary to change the format of the documentation comments at all. One thing I should fix, though is that doxy comments can be formatted in Markdown, while Sphinx uses rST by defaults (but supports md via a plugin). It is just a matter of informing the builder that a block of text must be interpreted as md.

### Requires a more manual involvement for writing and organizing the docs.

When I say more manual involvement I mean compared to Doxygen, where one just drops in some comments and forgets.
Doxygen is bottom up: documents say in which index they are included. In Sphinx indices are generated manually, so it's more like writing a book.
In practical terms, it means that to generate the documentation for a module you should create a document and then include the API docs in that document. Here is where the plugin that links with doxygen is used to avoid repetition. An alternative would be to automatically generate Sphinx pages from doxygen group definitions, which is not hard to do. The best way to get a grasp of the process is to look at a project that uses Sphinx.

### The build process is slower an more complex.

Normally
- Doxygen: run `doxygen` and you are done.
- Sphinx: run `sphinx-build` and you are done. `sphinx-build` also does incremental recompilation of documents.

Combining both:
- Sphinx triggers a doxygen build before it's own build. If we decide we want pages to be generated dynamically from doxy groups, that is also a separate step (for example, see autoindex).

 ### Resources (@aabadie )

Even it we use our own build server, the requirements when using Breathe are high. I don't have numbers now, but with all cores on my i7 machine, it took an uncomfortable amount of time (and the fans were blowing like crazy).

### The extension

Performance is not the only reason for going with my own extension. Configurability is a big one too. With the antidox extension any user is able to configure all the rendering rules using XSL templates, so the code is quite small, and IMO quite readable too.

Going back to performance, it is nice to be able to rebuild the docs in a couple of seconds to see the changes.

I had a brief exchange with a guy who is working on improving SQLite3 support in Doxygen (https://github.com/riot-appstore/antidox/issues/13) so that part of the code can be simplified in the future.

Sphinx and Doxygen are pretty mature projects, so I would not expect big or frequent API changes.

**Comment by jcarrano** [comment]
I'm closing this in favour of #11459 . The newer approach is cleaner and faster.

**Pull request closed without merging**
