### PR TITLE
CODING_CONVENTIONS.md: default to C11

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The standard is 9 years old now, it is well supported in all major compilers.
In fact, features of the 'new' standard are already used in RIOT (std_atomic).

Let's make it the default and adapt the Makefiles accordingly.

### Testing procedure

Murdock will ensure everything compiles with the new flags.

### CODE REVIEW

**Comment by kaspar030** [comment]
was msp430 the last platform that didn't support it?

**Comment by benpicco** [comment]
MIPS still is on [gnu99](https://github.com/RIOT-OS/RIOT/blob/master/makefiles/arch/mips.inc.mk#L32) but that should be fixed with https://github.com/RIOT-OS/riotdocker/pull/107

**Comment by maribu** [comment]
When I last checked, the docker image used the default ubuntu package for the AVR platform. Sadly, this package is unmaintained, broken, and missing C11 support. However, no changes to the RIOT code base are needed when updating the AVR toolchain; I have been using locally an up to date GCC without issue for quite some time.

**Comment by kaspar030** [comment]
> However, no changes to the RIOT code base are needed when updating the AVR toolchain; I have been using locally an up to date GCC without issue for quite some time.

same here, I'm usually building with the avr-gcc toolchain that comes with arch linux, which currently is at 10.2.0, with no issues.
I guess we should add avr-gcc to https://github.com/RIOT-OS/toolchains.

**Comment by maribu** [comment]
I think Ubuntu's AVR toolchain has preliminary C11 support. Maybe it works well enough to pass Murdock?

**Comment by maribu** [comment]
I can't believe it: All green!

**Review by maribu — APPROVED** [review]
ACK

**Review by miri64 — APPROVED** [review]
Well, I think if Murdock likes this, there is no reason to stall this any longer! ACK

**Comment by miri64** [comment]
Needs a rebase though, since there seem to be something missing for the `check-commits` check.

**Comment by miri64** [comment]
```
/home/runner/work/_temp/34f22052-d53d-46be-a1cb-e40e7cca36df.sh: line 1: ./dist/tools/pr_check/check.sh: No such file or directory
```

**Comment by maribu** [comment]
All green. Anyone whos against this should speak up now ;-)

**Pull request merged**
