### PR TITLE
drivers/mma7660: initial support (adopted from #5970)

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

This adopts the initial support for the MMA7660 accelerometer. It fixes an issue with the initialisation causing all reads to return 0 and also adapts the new I2C API. Hence, this works now.

Tested with `tests/driver_mma7660` and `tests/saul`. Sample output see below:

driver tests:
```
2018-06-12 14:03:45,821 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:45,926 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,031 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,136 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,241 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,347 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,452 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,557 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,662 - INFO # Acceleration [in mg]: X: 94 Y: -940 Z: 423
2018-06-12 14:03:46,767 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:46,872 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:46,977 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,083 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,188 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,293 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,398 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,503 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
2018-06-12 14:03:47,608 - INFO # Acceleration [in mg]: X: 47 Y: -940 Z: 517
```

with SAUL:
```
2018-06-12 14:05:29,642 - INFO # ##########################
2018-06-12 14:05:30,596 - INFO # 
2018-06-12 14:05:30,603 - INFO # Dev: LED(orange)       Type: ACT_SWITCH
2018-06-12 14:05:30,607 - INFO # Data:            1
2018-06-12 14:05:30,721 - INFO # 
2018-06-12 14:05:30,727 - INFO # Dev: Button(SW0)       Type: SENSE_BTN
2018-06-12 14:05:30,731 - INFO # Data:            0
2018-06-12 14:05:30,732 - INFO # 
2018-06-12 14:05:30,738 - INFO # Dev: mma7660   Type: SENSE_ACCEL
2018-06-12 14:05:30,742 - INFO # Data:  [0]     47 mg
2018-06-12 14:05:30,746 - INFO #        [1]   -893 mg
2018-06-12 14:05:30,749 - INFO #        [2]    470 mg
2018-06-12 14:05:30,750 - INFO # 
2018-06-12 14:05:30,755 - INFO # ##########################
2018-06-12 14:05:31,596 - INFO # 
2018-06-12 14:05:31,603 - INFO # Dev: LED(orange)       Type: ACT_SWITCH
2018-06-12 14:05:31,607 - INFO # Data:            1
2018-06-12 14:05:31,608 - INFO # 
2018-06-12 14:05:31,614 - INFO # Dev: Button(SW0)       Type: SENSE_BTN
2018-06-12 14:05:31,618 - INFO # Data:            0
2018-06-12 14:05:31,619 - INFO # 
2018-06-12 14:05:31,625 - INFO # Dev: mma7660   Type: SENSE_ACCEL
2018-06-12 14:05:31,629 - INFO # Data:  [0]     94 mg
2018-06-12 14:05:31,632 - INFO #        [1]   -940 mg
2018-06-12 14:05:31,635 - INFO #        [2]    470 mg
2018-06-12 14:05:31,637 - INFO # 
2018-06-12 14:05:31,642 - INFO # ##########################
2018-06-12 14:05:32,596 - INFO # 
2018-06-12 14:05:32,603 - INFO # Dev: LED(orange)       Type: ACT_SWITCH
2018-06-12 14:05:32,607 - INFO # Data:            1
2018-06-12 14:05:32,608 - INFO # 
2018-06-12 14:05:32,614 - INFO # Dev: Button(SW0)       Type: SENSE_BTN
2018-06-12 14:05:32,618 - INFO # Data:            0
2018-06-12 14:05:32,619 - INFO # 
2018-06-12 14:05:32,625 - INFO # Dev: mma7660   Type: SENSE_ACCEL
2018-06-12 14:05:32,629 - INFO # Data:  [0]     94 mg
2018-06-12 14:05:32,632 - INFO #        [1]   -940 mg
2018-06-12 14:05:32,636 - INFO #        [2]    423 mg
```

### Issues/PRs references

- original PR #5970
- tracking new I2C API #6577

### CODE REVIEW

**Comment by smlng** [comment]
hey besides these unrelated Murdock errors this one is tested and ready for merging, if you like?!

**Comment by dylad** [comment]
We cannot rely on Murdock as long as all implementations are not done. I trust your results, I'll review it asap.
Can you tell us on which platform did you test it ? also, could you try on a second platform if it is feasible for you, just to be sure ?
Or if you know someone else for a second test using this sensor ?

**Comment by smlng** [comment]
I tested on SAMR21-XPRO as I know from @MrKevinWeiss that he tested (and fixed) the periph implementation.

**Comment by MrKevinWeiss** [comment]
I tested but it was all @dylad who fixed it (I did a few silly fixes while on my testing branch but as of now I use pretty much the implementation on the new_i2c_if branch, only one problem that is probably a bug with the bpt)

**Comment by smlng** [comment]
@aabadie, so you mean I should wait until the I2C rework is finished and than make this a PR against master?

**Comment by aabadie** [comment]
> so you mean I should wait until the I2C rework is finished and than make this a PR against master?

Yes, because I think we should avoid new high level features in the I2C refactoring (new sensor, SAUL, new test applications). The most difficult part is the CPU drivers adaption. Adapting existing device drivers is quite straight forward.

Maybe this could be an extra motivation for getting this done faster ;)

**Comment by smlng** [comment]
will rebase after I2C rework to be merged into master then

**Comment by smlng** [comment]
rebased onto master

**Comment by smlng** [comment]
ping all, this is now ready for reviewing and testing.

**Comment by MrKevinWeiss** [comment]
The driver test works on both the nucleo-l152re and the samr21-xpro but I was not able to test it with saul (it just doesn't show up).  Is there any way you can tell me if you did anything more than running the tests/saul and adding USEMODULE += mma7660 into the makefile?

**Comment by MrKevinWeiss** [comment]
Figured it out TESTED ACK!

**Pull request merged**
