### PR TITLE
unittests: fix (some more) invisible unicode chars in Makefiles

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

remove invisible unicode chars from Makefiles which breaks (at least ) on macOS.

### Issues/PRs references

#9396

### CODE REVIEW

**Comment by miri64** [comment]
We should have some test for checking this. People [can do funky stuff with that](https://media.ccc.de/v/34c3-9249-hardening_open_source_development), so this is a potential attack vector.

**Comment by bergzand** [comment]
Based on master, I've found the following files with an UTF-8 BOM. @smlng Would you mind fixing the other files here too? Otherwise I can open a followup PR

```
tests/unittests/tests-cn_cbor/Makefile.include
tests/unittests/tests-cn_cbor/tests-cn_cbor.c
tests/unittests/tests-libcose/Makefile
tests/unittests/tests-libcose/Makefile.include
tests/unittests/tests-libcose/tests-libcose.c
tests/unittests/tests-uuid/Makefile
tests/unittests/tests-uuid/Makefile.include
tests/unittests/tests-uuid/tests-uuid.c
```

> We should have some test for checking this. People can do funky stuff with that, so this is a potential attack vector.

I've fixed these using `dos2unix`, maybe we could integrate this into the CI.

**Comment by smlng** [comment]
yeah will fix the rest, too. I used: `pcregrep --color='auto' -n "[\x80-\xFF]" <file>` (or together with `find`) to find those chars.

**Comment by bergzand** [comment]
I used `find . -type f  -exec dos2unix -v '{}' \;`, also catches the line endings in a few vendor files and patch files.

**Comment by smlng** [comment]
@bergzand, downside of you approach: needs another tool, which is currently not present on murdock slaves, pcgrep is already required by RIOT so maybe we can make this work somehow

**Comment by smlng** [comment]
and implement or add a check to the ci (static-tests)

**Comment by bergzand** [comment]
Thanks for fixing @smlng!

**Pull request merged**
