### PR TITLE
cpu: make msp430fxyz use uart stdio

### PR DESCRIPTION
**Pull request by kaspar030**
msp430fxyz used an ugly-hacked uart_stdio replacement as it was not fast enough to handle bytewise isr-to-thread transfer using ringbuffer at 115kbaud.

Using the improved thread-safe ringbuffer (which avoids interrupt disabling), the msp easily handles higher speeds.

~~Depends on #3923.~~

### CODE REVIEW

**Comment by kaspar030** [comment]
Without this, everything but shell that using uart is probably broken, and shell loses input echo until "\r" is received.

**Comment by kaspar030** [comment]
- rebased.

IMHO this fixes a lot of bugs and is a rather trivial change. Should we get it in the release?

**Comment by thomaseichinger** [comment]
Successfully tested on z1 and msb-430h. I'm fine with taking this into this release.

**Comment by OlegHahm** [comment]
:+1:

**Comment by kaspar030** [comment]
Are those ACKs? Then merge at will.

**Comment by thomaseichinger** [comment]
ACK & Go

**Pull request merged**
