### PR TITLE
implement gpio_toggle properly for stm32f0 cpu

### PR DESCRIPTION
**Pull request by MohmadAyman**
my first ever commit, hope this works and can be of some help,
i'm waiting for some feedback to make sure that i'm on the right track, and so i can continue working on the rest of the boards.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Hi and welcome to RIOT!

I think your implementation is quite off and is using an old and deprecated paradigm. Have a look at the how the `set` and `clear` functions are implemented for a short-term solution. On the long term, it would be even better to re-write the complete GPIO driver as done already e.g. for the `stm32f4`...

**Comment by MohmadAyman** [comment]
Ok i'll look at stm32f4 and try to work this out, thanks for the feedback ☺

**Comment by MohmadAyman** [comment]
@LudwigOrtmann after looking at Issue https://github.com/RIOT-OS/RIOT/pull/2696 ,isn't that what i should be doing, or am i wrong here ?-i dont really know specially after what haukepetersen said-

**Comment by PeterKietzmann** [comment]
Hi @MohmadAyman. What Hauke meant was, that we recently changed our peripheral-driver architecture. The driver you are working on, and the change in #2696 are based on the old architecture but should be ported soon. That would mean, your change will be deprecated in the near future. If you dare to do so,  you could be the one who renews the driver :-) ? Take a look at  #3535. This is how your PR could look like then. There, Hauke adapted the implementation for stm32f1 CPUs.

**Comment by MohmadAyman** [comment]
Renewing the driver sound ok to me, so I do have to take a look at what Hauke did to the stm32f1 driver and try doing the same thing for the stm32f0, right?

**Comment by PeterKietzmann** [comment]
Yes.

**Comment by PeterKietzmann** [comment]
Close in favor of  #3816

**Pull request closed without merging**
