### PR TITLE
congure_reno: initial import of TCP Reno congestion control

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides an implementation for CongURE of the congestion control mechanism of classic TCP congestion control (TCP Reno) as specified in [RFC 5681](https://tools.ietf.org/html/rfc5681).

### Testing procedure
Tests are provided for which [`riotctrl`](https://github.com/RIOT-OS/riotctrl/) (at least v0.2.2) is required for them to run. If installed,

```
make -j -C tests/congure_reno flash test
```

should succeed.

### Issues/PRs references
Requires ~~#15951~~ (merged), ~~#16111, and #16119~~ (merged). When merged, I will adapt the test framework to use the turo framework introduced in #15950, which was the original idea to begin with (which is why it is already printing JSON strings).

PR dependency graph

### CODE REVIEW

**Comment by miri64** [comment]
Same as with #15952: Rebased to current master, needs some adaptions to the changes done in #15951, so I am marking this WIP temporarily.

**Comment by miri64** [comment]
Adopted tests, however on real boards, there seems to be a problem with the shell: even though I increased the input buffer for `stdio_uart` to 512, the shell only reads up to 64 characters and then garbage after that :-/. Anyone has any idea why? In `tests/emcute` this does not seem to be a problem.

**Comment by kaspar030** [comment]
This is probably caused by the uart usb converter that is provided by the on-board debugger.

**Comment by miri64** [comment]
> This is probably caused by the uart usb converter that is provided by the on-board debugger.

But why does it work with `tests/emcute` then?

**Comment by miri64** [comment]
> This is probably caused by the uart usb converter that is provided by the on-board debugger.

Ok, there might be something to it though. On IoT-LAB M3 it succeeds.

**Comment by miri64** [comment]
Latest round of commits finishes adopting to the changes from #15951. If the error I am facing really stems from the hardware I might need to rethink my test frame work.

**Comment by miri64** [comment]
(mostly for the `report_msgs_timeout` method, but still)

**Comment by miri64** [comment]
Same treatment as in #15952: Rebased to current master and dependencies and added #16119 as new dependency.

**Comment by miri64** [comment]
Rebased to current master. This PR does not have any dependencies anymore now. As such, ready for review.

**Comment by miri64** [comment]
Rebased and squashed to current master

**Comment by benpicco** [comment]
The new tests fail [on samr21-xpro](https://ci.riot-os.org/RIOT-OS/RIOT/15953/b9d84f178f5ad0bd682af2570508ea0f17f272db/output/run_test/tests/congure_reno/samr21-xpro:gnu.txt)

**Comment by miri64** [comment]
Might be the good old line-off-by-one error I encountered in the past with RIOTCtrl :-/ We might need to fix that in the backend.

**Comment by benpicco** [comment]
The code looks fine though, so what do we do about the test?

**Comment by miri64** [comment]
> The code looks fine though, so what do we do about the test?

Fix the framework, once I have some time to look into it :-) (or maybe @fjmolinas can have a look as well). Maybe its also just a matter of usage. I remember that for `congure_test` I needed to do some adaptations after the fact as well, maybe these are required here as well and I just did not integrate them here yet (and in #15952)

**Comment by miri64** [comment]
Fixed the same issue here.

**Review by benpicco — APPROVED** [review]
So the only remaining failure are due to missing `Makefile.ci` (maybe #16109 could come in handy here :wink: But then again the list is small enough to be created manually)

Please squash!

**Comment by OlegHahm** [comment]
@miri64 ping :)

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
And rebased (in the hopes that something in the current master will fix the murdock issues :P)

**Comment by miri64** [comment]
@OlegHahm If Murdock fails, don't bother to push for it to get into the release. Sadly, I don't have time for bug hunting today :(.

**Comment by miri64** [comment]
Mh... all related test failures only seem to be connected to RAM overflows. Allow me to fix that!

**Comment by miri64** [comment]
@benpicco can this still be merged?

**Comment by benpicco** [comment]
Sure!

**Pull request merged**
