### PR TITLE
examples/micropython: fix checked PID

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
With https://github.com/RIOT-OS/RIOT/pull/14224 the idle thread became optional, so the main thread can have either 1 or 2 as PID, depending if the idle thread is included or not. As this might also change in the future, it is probably the best to just expect any number.

### Testing procedure
```
make -C examples/micropython flash test
```
Should now succeed again on e.g. Cortex-M platforms.

### Issues/PRs references
Follow-up on #14224

### CODE REVIEW

**Comment by miri64** [comment]
Murdock failures as most of the times when using `CI: run tests` are unrelated:

```
    failed:
    tests/cpp_ctors/nrf52dk:gnu
    tests/cond_order/nrf52dk:gnu
    tests/driver_apds99xx_full/nrf52dk:gnu
    tests/driver_apds99xx_full/nrf52dk:llvm
    tests/event_threads/nrf52dk:llvm
    tests/event_wait_timeout/nrf52dk:gnu
    tests/float/nrf52dk:llvm
    tests/periph_flashpage/nrf52dk:llvm
    tests/mutex_order/nrf52dk:gnu
    tests/mtd_mapper/nrf52dk:gnu
    tests/pipe/nrf52dk:llvm
    tests/mtd_flashpage/nrf52dk:gnu
    tests/pkg_jsmn/nrf52dk:llvm
    tests/pkg_cayenne-lpp/nrf52dk:gnu
    tests/riotboot/nrf52dk:gnu
    tests/driver_nrfmin/nrf52dk:llvm
    tests/pkg_c25519/nrf52dk:llvm
    tests/pkg_micro-ecc-with-hwrng/nrf52dk:llvm
    tests/pkg_libhydrogen/nrf52dk:llvm
    tests/pkg_cn-cbor/nrf52dk:llvm
    tests/shell/nrf52dk:llvm
    tests/pkg_hacl/nrf52dk:llvm
    tests/periph_gpio/nrf52dk:llvm
    tests/pthread_barrier/nrf52dk:llvm
    tests/posix_time/nrf52dk:gnu
    tests/pkg_nanocbor/nrf52dk:gnu
    tests/devfs/nrf52dk:gnu
    tests/pkg_micro-ecc/nrf52dk:llvm
    tests/pkg_monocypher/nrf52dk:llvm
    tests/pkg_libb2/nrf52dk:gnu
    tests/pthread_cleanup/nrf52dk:gnu
    tests/pkg_nanopb/nrf52dk:gnu
    tests/pkg_spiffs/nrf52dk:llvm
    tests/pkg_cmsis-nn/nrf52dk:gnu
    tests/thread_msg_block_race/nrf52dk:gnu
    tests/thread_msg_seq/nrf52dk:gnu
    tests/thread_msg_block_wo_queue/nrf52dk:gnu
    tests/thread_msg/nrf52dk:llvm
    tests/pkg_littlefs/nrf52dk:gnu
    tests/pkg_littlefs/nrf52dk:llvm
    tests/rmutex/nrf52dk:llvm
    tests/pthread/nrf52dk:gnu
    tests/ztimer_msg/nrf52dk:llvm
    tests/pkg_qdsa/nrf52dk:gnu
    tests/thread_basic/nrf52dk:llvm
    tests/trickle/nrf52dk:gnu
    tests/trace/nrf52dk:gnu
    tests/pthread_flood/nrf52dk:llvm
    tests/xtimer_remove/nrf52dk:llvm
    tests/ztimer_underflow/nrf52dk:gnu
    tests/bench_sizeof_coretypes/nrf52dk:gnu
    tests/pthread_cooperation/nrf52dk:gnu
    tests/xtimer_mutex_lock_timeout/nrf52dk:gnu
    tests/xtimer_hang/nrf52dk:gnu
    tests/thread_race/nrf52dk:llvm
    tests/kconfig/nrf52dk:gnu
    tests/unittests/nrf52dk:gnu
    tests/unittests/nrf52dk:llvm
    tests/cpp11_mutex/nrf52dk:gnu
    tests/cpp11_mutex/nrf52dk:llvm
```

**Comment by aabadie** [comment]
It seems that the PR branch was pushed on the RIOT main fork. I deleted it.

**Comment by miri64** [comment]
Yeah sorry 'bout that. I pushed this from the repo the release manager created since I accidentally was working there :sweat_smile:

**Comment by miri64** [comment]
Backport provided in #14530

**Pull request merged**
