### PR TITLE
gnrc_sixlowpan_frag: prepare reassembly base types for VRB

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
For the [VRB] I also need to track which the intervals of the fragments already received (mostly for finding out when I am able to get rid of a VRB entry, see [this conversation][VRB entry removal]) and the arrival time for garbage collection. This resulted in some refactoring in the data structures of the reassembly buffer.

[VRB]: https://tools.ietf.org/html/draft-ietf-lwig-6lowpan-virtual-reassembly-00
[VRB entry removal]: https://mailarchive.ietf.org/arch/msg/6lo/bTm2REo4PpVcMFH04mF_SlPvS_M

### Testing procedure
Sending and receiving fragmented packets with `gnrc_networking` should still work. `tests/gnrc_sixlowpan_frag` should still compile and pass.

### Issues/PRs references
No dependencies, but provides basis for others:

Route to 6Lo minimal fragment forwarding

### CODE REVIEW

**Comment by miri64** [comment]
Okay, I also exposed the arrival time now. In consequence the members of `rbuf_t` and `gnrc_sixlowpan_rbuf_t` became equivalent, so I also removed the internal type `rbuf_t`.

**Comment by miri64** [comment]
I think I'm done with this now.

**Comment by miri64** [comment]
#11068 is to experimental so it doesn't make any sense to try to get this into the release => post-poned.

**Comment by miri64** [comment]
Rebased to current master

**Comment by miri64** [comment]
Rebased to current master

**Comment by miri64** [comment]
Rebased and squashed to current master.

**Comment by cgundogan** [comment]
Please squash.

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
And rebased accidentally ^^"

**Pull request merged**
