### PR TITLE
Pull request to solve issue #1759; sys/include/fd.h

### PR DESCRIPTION
**Pull request by BigDaddyD**
This commit is to fix the ambiguity in sys/include/fd.h where the the internal RIOT filedescriptor shared the name of the POSIX filedescriptor, leading to some possible confusion. The POSIX filedescriptor is already references as 'fd', so it can be confusing the have the internal RIOT filedescriptor also be referenced by the same name inside the 'fd_t' struct. To avoid this the variable was changed to 'internal_fd' and more comments were added to clarify the distinction.The multiple commits were just to fix the typo in the inital commit message.

### CODE REVIEW

**Comment by BigDaddyD** [comment]
Since the test failed, do I edit this pul request once I solve the problem or do I create a brand new pull request?

**Comment by OlegHahm** [comment]
No need to create a new PR - just fix this one. Usually, by adding a fixing commit and squash it after a reviewer acknowledges it.

**Comment by OlegHahm** [comment]
@BigDaddyD, any news?

**Comment by BigDaddyD** [comment]
I do believe the problem was solved by another pull request

**Comment by BigDaddyD** [comment]
Also I have a question for you. Do you know of any sort of manual on
doxygen documentation? I have been looking for newbie issues to get done
so I can stay involved and get a feel for the the organization of RIOT,
but I have never seen or really used a doxygen type system before, so I
am very unsure on how to proceed in order to fix any issues

>>> Oleg Hahm <notifications@github.com> 04/13/15 10:46 AM >>>
@BigDaddyD, any news?

**Comment by PeterKietzmann** [comment]
@BigDaddyD it seems you had several merge conflicts which haven't been solved. I'm wondering about the ...
```
<<<<<<< HEAD

=======
```
... parts in your code. Do you __think__ or do you __know__ the issues have already been solved? (I didn't look at it)
According to the doxygen question: I guess you found general doxygen documentations with google, right? Did you check our [Coding Conventions](https://github.com/RIOT-OS/RIOT/wiki/Coding-conventions)? Is this what you are looking for?

**Comment by BigDaddyD** [comment]
I was speaking about the problem that this PR was trying to solve. That is, the renaming of the internal file descriptor within fd_t. Last time i checked this PR the travis build had simply stalled so I wasn't sure what to do. From what I was told there was no way to tell if my build was bad or if travis was just not working. I see now that I have real errors to fix, however i see in the current master that the internal fd in fd.h has been renamed. Should i bother fixing this PR?

**Comment by OlegHahm** [comment]
@BigDaddyD, I think http://www.stack.nl/~dimitri/doxygen/manual/index.html is indeed a good starting point for beginners. Or did I misread your question?
And yes, you are right: #1759 has been solved in https://github.com/RIOT-OS/RIOT/pull/2566, so you can just close this PR.

**Comment by BigDaddyD** [comment]
Thanks!

**Pull request closed without merging**
