### PR TITLE
make: remove obsolete check for jenkins

### PR DESCRIPTION
**Pull request by cgundogan**
there is no jenkins anymore, so why keep this check?

### CODE REVIEW

**Comment by cgundogan** [comment]
much easier to review with https://github.com/RIOT-OS/RIOT/pull/5380/files?w=

**Comment by OlegHahm** [comment]
Can you split the typo fix into a separate commit? Otherwise ACK.

**Comment by cgundogan** [comment]
@OlegHahm addressed your comment

**Comment by authmillenon** [comment]
ACK and go.

**Pull request merged**
