### PR TITLE
cpu/esp32: add periph_flashpage support

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides the `periph_flashpage` support for ESP32x SoCs.

For byte-aligned read access to constant data in the flash, the MMU of all ESP32x SoCs allows to map a certain number of 64 kByte pages of the flash into the data address space of the CPU. This address space is called DROM. Normally the whole DROM address space is assigned to the section `.rodata`. The default flash layout used by all ESP32x SoCs is:
| Address in Flash | Content |
|:-----------------------|:-----------|
| `0x0000` or `0x1000` | bootloader |
| `0x8000` | parition table |
| `0x9000` | `nvs` parition with WiFi data |
| `0xf000`  | `phy_init` partition with RF data |
| `0x10000` | `factory` partition with the app image |

The factory partition consists of a number of 64 kByte pages for the sections `.text`, `.rodata`, `.bss` and others. The `.text` and `rodata` sections are page-aligned and are simply mapped into the instruction address space (IROM) and the data address space (DROM), respectively. All other sections are loaded into RAM.

If the `periph_flashpage` module is used, the `periph_flashpage` driver
- decreases the size of the `.rodata` section in DROM address space by `CONFIG_ESP_FLASHPAGE_CAPACITY`,
- adds a section `.flashpage.writable` of size `CONFIG_ESP_FLASHPAGE_CAPACITY` at the end of DROM address space that is mapped into data address space of the CPU,
- reserves a region of size `CONFIG_ESP_FLASHPAGE_CAPACITY` starting from `0x10000` in front of the image partition `factory` and
- moves the image partition `factory` by  `CONFIG_ESP_FLASHPAGE_CAPACITY` to address `0x10000 + CONFIG_ESP_FLASHPAGE_CAPACITY`. 

The new flash layout is then:
| Address in Flash | Content |
|:-----------------------|:-----------|
| `0x0000` or `0x1000` | bootloader |
| `0x8000` | parition table |
| `0x9000` | `nvs` parition with WiFi data |
| `0xf000`  | `phy_init` partition with RF data |
| `0x10000` | flashpage region |
| `0x10000 + CONFIG_ESP_FLASHPAGE_CAPACITY` | `factory` partition with the app image |

This guarantees that the flash pages are not overwritten if a new app image with changed size is flashed. `CONFIG_ESP_FLASHPAGE_CAPACITY` has to be a multiple of 64 kBytes.

~The PR includes PR #19077 and PR #19078 for the moment to be compilable.~

### Testing procedure

The following tests should pass.
```
USEMODULE='esp_log_startup ps shell_cmds_default' BOARD=esp32-wroom-32 make -j8 -C tests/periph_flashpage flash term
```
```
USEMODULE='esp_log_startup ps shell_cmds_default' BOARD=esp32-wroom-32 make -j8 -C tests/mtd_flashpage flash term
```

### Issues/PRs references

Depends on PR #19077
Depends on PR #19078

### CODE REVIEW

**Comment by gschorcht** [comment]
**Please note:** There is an open problem with the ESP32-S2 implementation. The flashpage access requires any kind of additional mapping between the DCache and the MMU pages for ESP32-S2. Unfortunatly, til now this works only with ICache but not with DCache, no idea why yet. The problem of ICache is that it only allows word access.

**Comment by gschorcht** [comment]
`periph_flashpage` implementation has been finished  now and is working also on ESP32-S2.

**Comment by benpicco** [comment]
bors try

**Review by benpicco — APPROVED** [review]
Also works on ESP32-C3 and ESP32-S3

btw, what's needed for `riotboot` support? 

bors merge

**Comment by gschorcht** [comment]
> btw, what's needed for `riotboot` support?

I was already thinking about that. There will be no chance to replace the ESP-IDF bootloader by a bare metal implementation since the bootloader preconfigures a lot of the SoC. My approach would be to implement `riotboot` as an RIOT application which includes the CPU startup procedure and that is loaded by the ESP-IDF bootloader. But instead of starting RIOT kernel it loads the RIOT application without the CPU startup procedure which then starts the kernel. I have no idea whether this could be realized.

**Comment by benpicco** [comment]
> My approach would be to implement riotboot as an RIOT application which includes the CPU startup procedure and that is loaded by the ESP-IDF bootloader.

That's already how riotboot works anyway.

> But instead of starting RIOT kernel it loads the RIOT application without the CPU startup procedure which then starts the kernel.

That would make changes to the CPU startup routines impossible.

Is it a problem to call the CPU init twice?
Those ESP32s usually have plenty of flash.

**Comment by gschorcht** [comment]
> That's already how riotboot works anyway.
>
I see, I didn't check it yet.

> Is it a problem to call the CPU init twice?

I'm afraid that doing the complete SoC initialization a second time won't really work. We will have to give it a try. I have actually had it on my to-do list for quite some time.

**Comment by benpicco** [comment]
Well for the most simple `riotboot_slot` (needed for SUIT updates) you might not even need to init the CPU.

It just checks the riotboot header of the two slots to decide where to jump, so you don't need to initialize any peripherals, the boot config should be sufficient for that.

**Comment by gschorcht** [comment]
@benpicco Thankd for reviewing and merging.

**Comment by gschorcht** [comment]
> Well for the most simple [`riotboot_slot`](https://github.com/RIOT-OS/RIOT/blob/master/bootloaders/riotboot/main.c) (needed for SUIT updates) you might not even need to init the CPU.

I will take a look into `riotboot` and check it when I have time.

**Pull request merged**
