### PR TITLE
dist/tests/if_lib: Update to riot_pal

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

This removes all non-application based driver/devices and replaces with riot_pal.
riot_pal (riot protocol abstraction layer) can be installed with pip install riot_pal.
The purpose is ti simplify and modularize the interfaces and tests.
All tests using the if_lib interface are updated too.

### Testing procedure

1. flash philip [firmware](https://github.com/MrKevinWeiss/PHiLIP/blob/master/QUALIFICATION/FW/PHiLIP-NUCLEO-F103RB-REV10009.bin) on a nucleo-f103rb and plug in to the cpu (assuming port is ACM0)
2. plug in a second board (assume it is ACM1)
3. `BOARD=<BOARD_NAME> make flash -C tests/periph_i2c/`
4. Connect all wires with test (in this case i2c wires)
5. `PYTHONPATH=$PYTHONPATH:<RIOTBASE>/dist/tests python3 tests/periph_i2c/tests/test.py --bpt_port=/dev/ttyACM0 --dut_port=/dev/ttyACM1`

### CODE REVIEW

**Comment by smlng** [comment]
question: is there documentation/hint on how to install `riot-pal`?

**Comment by MrKevinWeiss** [comment]
You should get a descriptive import error exception if it fails now.

**Comment by smlng** [comment]
Ci is not happy, specifically flake8 is complaining ... please fix

**Comment by smlng** [comment]
This is rather non-intrusive, so ACK and GO!

**Pull request merged**
