### PR TITLE
{examples,tests}/rust: Rust updates

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description and PR references

These updates enable tests on beta (stable for the 2022.04 release) on
all platforms, and open the way for [17804].

[17804]: https://github.com/RIOT-OS/RIOT/pull/17804

### Testing procedure

* green CI

### CODE REVIEW

**Comment by chrysn** [comment]
CI only fails because tests were requested, and there they fail at build time (which passed on the more recently updated other hosts).

Removing the test runs and trying again; I don't think tests are critical here as the changes if anything would rather cause build than actual test failure, and on the ARM platform which the tests would run I've conducted some locally.

**Review by benpicco — APPROVED** [review]
Looks like a simple update and CI is happy

**Comment by benpicco** [comment]
Wait did I get it right that this will break the 'run tests' build? That would of course be silly - or was that a known sporadic failure?

**Comment by chrysn** [comment]
That was before the builders for the tests were updated, which AIU they are now. I've triggered another run with tests enabled just to be sure.

**Pull request merged**
