### PR TITLE
cpu/fe310: Uncrustify code

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Simple uncrustify of the `cpu/fe310` code.

### Testing procedure

CI should be enough here

### Issues/PRs references

None

### CODE REVIEW

**Review by aabadie — APPROVED** [review]
Tested with success a few applications locally on hifive1b. Code changes are generated automatically by uncrustify.

ACK

**Comment by bergzand** [comment]
Thanks!

**Comment by miri64** [comment]
Can you also whitelist the fixed files in the `dist/tools/uncrustify/whitelist.txt`, please?

**Comment by bergzand** [comment]
> Can you also whitelist the fixed files in the `dist/tools/uncrustify/whitelist.txt`, please?

Wasn't aware that that is a thing, see #15778!

**Pull request merged**
