### PR TITLE
Gpio Interrupt fix for the CC2538

### PR DESCRIPTION
**Pull request by AnonMall**
Fixed the issue where the gpio interrupt is not properly acknowledged.

### CODE REVIEW

**Comment by smlng** [comment]
please squash (and rebase if necessary?), otherwise ACK!

**Comment by aabadie** [comment]
Does this PR provides a fix for #6650 ? Then it should be merged asap.

**Comment by smlng** [comment]
partly - the issue is more complex, #6773 provides the other part, but is more a workaround than a fix. The problem is that the gpio periph of cc2538 was partly adapted to periph_gpio driver of RIOT, but i2c, spi, and uart are still using the gpio driver from TI. Hence, rather than applying #6773 workaround, I'd work on rewritting the named 3 periph drivers ...

Nevertheless, this PR fixes an issue when using interrupts on gpios

**Comment by smlng** [comment]
But still: DO NOT MERGE THIS, just to have in the release. We had lots of trouble lately with prematurely merged periph drivers - this need very careful testing!

**Comment by aabadie** [comment]
> DO NOT MERGE!

no problem, it won't be in the release if it's not ACK'ed, merged and backported. Keep calm ;)

**Comment by AnonMall** [comment]
sorry i am a little new to squashing... just fixing some things. Please bear with me.

**Comment by smlng** [comment]
take your time, consider the following:

1. setup RIOT-OS/RIOT as an upstream to your repo, see [here](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
2. update your master to upstream master:
```
git fetch upstream
git checkout master
git pull --rebase upstream master
```
3. now update your branch and push (force, is needed as you rewrite history of your branch):
```
git checkout  gpioIntFix
git rebase master
git push -f
```

**Comment by miri64** [comment]
In fact you can just `git fetch upstream` and rebase to `upstream/rebase` (`git rebase upstream/rebase` or `git rebase -i upstream/master` for interactive mode).

**Comment by AnonMall** [comment]
fnished rebase and should be squashed... as it is only one file, further rebasing shouldn't be nescessary i guess.

**Comment by smlng** [comment]
perfect! I'll test.

**Comment by smlng** [comment]
tested this PR on board `remote-revb` and it fixes the following issue present on master:

- GPIO init as interrupt works as expected
- but when interrupt fires, it does not return correcty
- for `tests/periph_gpio` this means no shell prompt after interrupt

With this PR interrupt handling returns and shell prompt is available again.

Nice job @AnonMall, thanks! ACK - and GO as soon as Murdock is happy.

**Comment by aabadie** [comment]
I think it should be backported (since the mentioned bugs are quite important)

**Comment by smlng** [comment]
@AnonMall can you provide the backport? Basically make a copy of the branch and rebase onto tag `2017.07-RC1`, then make a new pull request against `2017.07-branch` (instead of master).

**Comment by AnonMall** [comment]
I can do that. But that also means you want me to rebase it against '2017.07-branc' instead of 'master' right?

**Comment by AnonMall** [comment]
Okay done. #7314

**Pull request merged**
