### PR TITLE
sys/net/netif: Keep interfaces in order they were added

### PR DESCRIPTION
**Pull request by yarrick**
### Contribution description

Without it, interfaces are kept in the reverse order.
`netif_iter` will return the latest netif first,
as seen in ifconfig:

```
> ifconfig
Iface  10  HWaddr: 24:0A:C4:E6:0E:9C  Channel: 0  Link: down
[..]

Iface  7  HWaddr: 24:0A:C4:E6:0E:9F  Link: down
[..]
```

Now they are in the increasing order:

```
> ifconfig
Iface  7  HWaddr: 24:0A:C4:E6:0E:9F  Link: down
[..]

Iface  10  HWaddr: 24:0A:C4:E6:0E:9C  Channel: 0  Link: down
[..]
```

lwIP is moving to using the netif code, and with this change two ethernet
interfaces (`ET0` and `ET1`) will be listed in the expected order.

### Testing procedure

Boards with multiple interfaces show them printed in increasing order in `ifconfig`.

### CODE REVIEW

**Comment by miri64** [comment]
Should we maybe use `clist` instead? This way all these operations can be O(1).

**Comment by yarrick** [comment]
Ok, I will look into that. Insertion will be O(1) in either case

**Comment by yarrick** [comment]
I understand that there is no specific order defined, but since both GNRC and lwIP (directly or indirectly) name the interfaces based on the order they are created this could be nice to have.

**Comment by kfessel** [comment]
gnrc uses the iface>-pid for its netif_id, maybe the generic implementation could use the memory position of the 
netif struct? making it independant from its list position.
search ( netif_get_by_id) by itterate an compare

**Pull request closed without merging**
