### PR TITLE
cc110x: Add ccn-lite support in cc110x gnrc.

### PR DESCRIPTION
**Pull request by hahchenchen**
This PR fix the cc110x gnrc to support the ccn-lite.

### CODE REVIEW

**Comment by cgundogan** [comment]
Looks like this branch has conflicts. @hahchenchen coud you rebase onto current master?

**Comment by hahchenchen** [comment]
done

**Comment by PeterKietzmann** [comment]
@hahchenchen you tried with examples/ccn-lite-relay? Can report your changes, to the Makefile in particular?

**Comment by PeterKietzmann** [comment]
@hahchenchen I would review and test your PR but please provide a description of you changes (why it is needed and what it actually does).

**Comment by smlng** [comment]
@hahchenchen please answer questions by @PeterKietzmann and me. @cgundogan any comment from you on this, as said it looks a bit weird to me to have such in a low-level driver, you think that makes sense?

**Comment by tcschmidt** [comment]
@hahchenchen please answer ASAP or we close this PR

**Pull request closed without merging**
