### PR TITLE
 gnrc_(*)2: rename to gnrc_\1

### PR DESCRIPTION
**Pull request by miri64**
Renames `gnrc_netif2` and `gnrc_ndp2` to the respective version without the 2.

I used the following script to do that:

```sh
rename2() {
    MODULE=$1
    # rename directories
    for dir in $(find . -type d -name "*${MODULE}2*" -not -path "./.git/*"); do
        new_dir=$(echo "${dir}" | sed "s/${MODULE}2/${MODULE}/g")
        if [ -d "${new_dir}" ]; then
            git mv "${dir}"/* "${new_dir}"/
        else
            git mv "${dir}" "${new_dir}"
        fi
    done
    # rename files
    for file in $(find . -type f -name "*${MODULE}2*" -not -path "./.git/*"); do
        new_file=$(echo "${file}" | sed "s/${MODULE}2/${MODULE}/g")
        git mv "${file}" "${new_file}"
    done
    # change name in files
    git grep --name-only -i "${MODULE}2" | xargs sed -i "s/\(${MODULE}\)2/\1/gI"
    # first (temporary) commit
    git commit -am "gnrc_${MODULE}2: rename to gnrc_${MODULE}"
    # fix formatting (for the most part)
    uncrustify -c uncrustify-riot.cfg -l C --no-backup \
        $(git diff --name-only --diff-filter="ACMR" HEAD~1 -- *.c *.h)
    # the tedious part of stepping through (mostly false positive or unrelated)
    # uncrustify output
    git add -p
    # append changes to commit
    git commit --amend
    # reset rest
    git checkout -f
}

# create new CCN-lite patch ;-)
rename2 netif
rename2 ndp
```

Depends on #8064.

### CODE REVIEW

**Comment by miri64** [comment]
NDP is missing because again: I want to test the `gnrc_netif` code on Murdock first.

**Comment by miri64** [comment]
(Same reason, why I did not set the "Waiting for other PR" label yet)

**Comment by miri64** [comment]
Ready for review.

**Comment by bergzand** [comment]
How do you want this reviewed? The script looks good from here, and I trust murdock to some extend, but I'm not looking forward to spitting through 16K lines of code. :)

**Comment by bergzand** [comment]
Never mind the number of lines, that rebase made it a lot less -_-

**Pull request merged**
