### PR TITLE
boards/pba-d-01-kw2x: fix driver params usage

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR updates the way on-board drivers params are configured on the pba-d-01-kw2x board.

Since the driver default are the same than on this board, I just removed them. Maybe there should be a comment in the related drivers params header file ?

### Issues/PRs references

Initially done in #7937 and related to #7519. Ideally, it should be merged with #8690, #7822, #8683

### CODE REVIEW

**Comment by miri64** [comment]
@smlng @PeterKietzmann @cgundogan can one of you test? I only have one that doesn't has the TCS3772 sensor on-board.

**Comment by smlng** [comment]
will do ASAP

**Comment by aabadie** [comment]
Normally this PR should work without #8690 since the radio defines are the same in master. Not sure about the other on-board sensor devices.

**Comment by smlng** [comment]
tested, works with all sensors

**Comment by smlng** [comment]
tested with `examples/default` and tried `saul read` on all sensors

**Comment by aabadie** [comment]
all green, go!
And thanks for reviewing and testing @miri64 and @smlng

**Pull request merged**
