### PR TITLE
cpu/kinetis: unified PM implementation

### PR DESCRIPTION
**Pull request by haukepetersen**
~~rebased on #6346~~

Actually, the (rudimentary) PM implementation is good for all Kinetis-based CPUs, so we should define the feature accordingly...

### CODE REVIEW

**Comment by miri64** [comment]
Please choose a more descriptive title for the PR. ;-)

**Comment by haukepetersen** [comment]
sorry...

**Comment by gebart** [comment]
Could you please add a note in the source that this implementation only
goes to WAIT or STOP mode. I didn't look close which mode is being used but
also be aware that the UART module stops (mid transfer) when you go to stop
mode.

**Comment by gebart** [comment]
Wait should not hurt anything. All modules are working in wait mode.

**Comment by haukepetersen** [comment]
added a note on the implementation state and rebased.

**Pull request merged**
