### PR TITLE
ci: migrate to github merge queues

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

These are changes required to switch merging from bors to Merge Queues.

### Testing procedure

Ideally required tests pass and we can enter it into a merge queue.

### Issues/PRs references

Tracking issue: #20051

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I am guessing I need an ack?  maybe we try merging without one

**Comment by kaspar030** [comment]
> I am guessing I need an ack? maybe we try merging without one

now you should need an ACK.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Review by kaspar030 — APPROVED** [review]
ACK.

(will fail due to temprary commit)

**Pull request merged**
