### PR TITLE
cpu/nrf51822: added SPI driver

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
This one has already been ACKed, right?

**Comment by haukepetersen** [comment]
rebased. @d00616, can you ack this?

**Comment by d00616** [comment]
Yes i can ack this but new locking feature is missing:

diff --git a/cpu/nrf51822/periph/spi.c b/cpu/nrf51822/periph/spi.c
index 69eb7ad..d6d6650 100644
--- a/cpu/nrf51822/periph/spi.c
+++ b/cpu/nrf51822/periph/spi.c
@@ -20,12 +20,28 @@
  */
 
 #include "cpu.h"
+#include "mutex.h"
 #include "periph/spi.h"
 #include "periph_conf.h"
 
 /* guard this file in case no SPI device is defined */
 #if SPI_NUMOF
 
+/**
+ * @brief Array holding one pre-initialized mutex for each SPI device
+ */
+static mutex_t locks[] =  {
+#if SPI_0_EN
+    [SPI_0] = MUTEX_INIT,
+#endif
+#if SPI_1_EN
+    [SPI_1] = MUTEX_INIT,
+#endif
+#if SPI_2_EN
+    [SPI_2] = MUTEX_INIT
+#endif
+};
+
 /* static port mapping */
 static NRF_SPI_Type *const spi[] = {
 #if SPI_0_EN
@@ -126,6 +142,24 @@ int spi_init_slave(spi_t dev, spi_conf_t conf, char (*cb)(char data))
     return -1;
 }
 
+int spi_acquire(spi_t dev)
+{
+    if (dev >= SPI_NUMOF) {
+        return -1;
+    }
+    mutex_lock(&locks[dev]);
+    return 0;
+}
+
+int spi_release(spi_t dev)
+{
+    if (dev >= SPI_NUMOF) {
+        return -1;
+    }
+    mutex_unlock(&locks[dev]);
+    return 0;
+}
+
 int spi_transfer_byte(spi_t dev, char out, char *in)
 {
     return spi_transfer_bytes(dev, &out, in, 1);

**Comment by haukepetersen** [comment]
oh, will add.

**Comment by haukepetersen** [comment]
rebased and implemented locking functions as well as pin config function

**Comment by haukepetersen** [comment]
rebased ans squashed.

**Comment by d00616** [comment]
ACK

**Pull request merged**
