### PR TITLE
tests: remove some pointless test applications

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
@Kijewski ping

**Comment by LudwigOrtmann** [comment]
@Kijewski ping

**Comment by LudwigOrtmann** [comment]
@Kijewski ping

**Comment by OlegHahm** [comment]
```
PING kijweski (1.2.3.4) 56(84) bytes of data.

--- kijewski ping statistics ---
5 packets transmitted, 0 received, 0 errors, 100% packet loss, time 67d
```

**Comment by LudwigOrtmann** [comment]
:laughing:

**Comment by LudwigOrtmann** [comment]
@Kijewski ping

**Comment by Kijewski** [comment]
@LudwigOrtmann, wanna take over this PR?

**Comment by LudwigOrtmann** [comment]
I would like to know if you have more insight on my old question:

> Why do you think tests/irq is not testing anything?

**Comment by LudwigOrtmann** [comment]
@Kijewski a simple "dunno" will do. In that case I'll adopt this PR and remove said change.

**Comment by Kijewski** [comment]
dunno

**Comment by LudwigOrtmann** [comment]
;)

**Comment by LudwigOrtmann** [comment]
Closed in favor of #2824

**Pull request closed without merging**
