### PR TITLE
[2017.10 backport] pm_layered: make sure no conflict for pm_set_lowest exists

### PR DESCRIPTION
**Pull request by roberthartung**
Backport of #7863

@miri64

### CODE REVIEW

**Comment by roberthartung** [comment]
I think I branched off master and not 2017.10 :/

**Comment by miri64** [comment]
Mh and did not set the correct base branch :-/.

**Comment by miri64** [comment]
Try to rebase again

**Comment by roberthartung** [comment]
Base branch is 2017.10-devel?

**Comment by miri64** [comment]
No 2017.10-branch.

**Comment by roberthartung** [comment]
@miri64 looks better now?

**Comment by miri64** [comment]
:+1:

**Comment by haukepetersen** [comment]
Dam'n, other backports got in the way again. @roberthartung sorry to ask, but would you be so kind to rebase (again)?! Thanks!

**Comment by miri64** [comment]
(you have to re-ACK as well as soon as @roberthartung rebases ;-))

**Comment by haukepetersen** [comment]
will do

**Comment by roberthartung** [comment]
@haukepetersen @miri64 rebased.

**Comment by haukepetersen** [comment]
all green -> go!

**Pull request merged**
