### PR TITLE
at86rf2xx: implement Basic Mode

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description

This adds support for Basic Mode operation (no auto-ack, no
auto-retrans with CSMA).
A new configuration flag is added for setting the default
operation mode. However, the device can switch between modes
on runtime (see `AT86RF2XX_OPT_EXT_MODE` option).

By default, the device is set to Extended Operation.

### Testing procedure
Test with a couple of nodes. Set one to extended mode and the other one to basic:
E.g
```
CFLAGS=-DCONFIG_AT86RF2XX_DEFAULT_MODE=AT86RF2XX_MODE_BASIC BOARD=iotlab-m3 make all flash term
```
and
```
BOARD=iotlab-m3 make all flash term
```
Send packets from BASIC->EXTENDED. You should see an ACK packet (8 bytes with netif_hdr) in the BASIC node:
```
1566572302.955737;m3-11;> txtsnd 4 15:11:6B:10:65:FC:BD:52 holi
1566572302.957690;m3-11;> PKTDUMP: data received:
1566572302.957966;m3-10;> PKTDUMP: data received:
1566572302.958641;m3-11;~~ SNIP  0 - size:   0 byte, type: NETTYPE_UNDEF (0)
1566572302.960005;m3-10;~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
1566572302.960198;m3-10;00000000  68  6F  6C  69
1566572302.960334;m3-10;~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
1566572302.961037;m3-10;if_pid: 4  rssi: -46  lqi: 255
1566572302.961192;m3-10;flags: 0x0
1566572302.961774;m3-11;00000000~~ SNIP  1 - size:   8 byte, type: NETTYPE_NETIF (-1)
1566572302.961953;m3-11;if_pid: 4  rssi: -46  lqi: 255
1566572302.962089;m3-11;flags: 0x0
1566572302.962249;m3-10;src_l2addr: AD:56
1566572302.962370;m3-10;dst_l2addr: 15:11:6B:10:65:FC:BD:52
1566572302.963227;m3-11;src_l2addr: (nil)
1566572302.963729;m3-11;dst_l2addr: (nil)
1566572302.964136;m3-11;~~ PKT    -  2 snips, total size:   8 byte
1566572302.964533;m3-10;~~ PKT    -  2 snips, total size:  22 byte

```

Send from EXTENDED->BASIC. You should see the retransmission packets on BASIC:
```m3-10;txtsnd 4 15:11:6B:10:65:FC:AD:56 holi
1566572246.940421;m3-10;> txtsnd 4 15:11:6B:10:65:FC:AD:56 holi
1566572246.944401;m3-11;> PKTDUMP: data received:
1566572246.944594;m3-11;~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
1566572246.944733;m3-11;00000000  68  6F  6C  69
1566572246.945702;m3-11;~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
1566572246.946942;m3-11;if_pid: 4  rssi: -45  lqi: 255
1566572246.947133;m3-11;flags: 0x0
1566572246.948295;m3-11;src_l2addr: BD:52
1566572246.948472;m3-11;dst_l2addr: 15:11:6B:10:65:FC:AD:56
1566572246.949881;m3-11;~~ PKT    -  2 snips, total size:  22 byte
1566572246.950059;m3-11;PKTDUMP: data received:
1566572246.950551;m3-11;~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
1566572246.951460;m3-11;00000000  68  6F  6C  69
1566572246.952444;m3-11;~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
1566572246.953410;m3-11;if_pid: 4  rssi: -45  lqi: 255
1566572246.953588;m3-11;flags: 0x0
1566572246.953713;m3-11;src_l2addr: BD:52
1566572246.954456;m3-11;dst_l2addr: 15:11:6B:10:65:FC:AD:56
1566572246.955447;m3-11;~~ PKT    -  2 snips, total size:  22 byte
1566572246.956426;m3-11;PKTDUMP: data received:
1566572246.957399;m3-11;~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
1566572246.957578;m3-11;00000000  68  6F  6C  69
1566572246.958500;m3-11;~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
1566572246.959442;m3-11;if_pid: 4  rssi: -45  lqi: 255
1566572246.959607;m3-11;flags: 0x0
1566572246.960428;m3-11;src_l2addr: BD:52
1566572246.961398;m3-11;dst_l2addr: 15:11:6B:10:65:FC:AD:56
1566572246.962408;m3-11;~~ PKT    -  2 snips, total size:  22 byte
1566572246.962574;m3-11;PKTDUMP: data received:
1566572246.963450;m3-11;~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
1566572246.964425;m3-11;00000000  68  6F  6C  69
1566572246.965401;m3-11;~~ SNIP  1 - size:  18 byte, type: NETTYPE_NETIF (-1)
1566572246.966344;m3-11;if_pid: 4  rssi: -45  lqi: 255
1566572246.966780;m3-11;flags: 0x0
1566572246.967168;m3-11;src_l2addr: BD:52
1566572246.967685;m3-11;dst_l2addr: 15:11:6B:10:65:FC:AD:56
1566572246.968635;m3-11;~~ PKT    -  2 snips, total size:  22 byte


```

### Issues/PRs references
Depends on #12069 
Partially addresses https://github.com/RIOT-OS/RIOT/issues/8213

### CODE REVIEW

**Comment by jia200x** [comment]
@roberthartung might be interested on this one

**Comment by jia200x** [comment]
I forgot to fix the TX_DONE event here. In Basic Mode, it's not necessary to read the TRX_STATUS register

**Comment by roberthartung** [comment]
@jia200x Certainly interested, but currently (This and next week) out of capacity.

**Comment by fjmolinas** [comment]
@jia200x is this still wip? Can you give it a rebase?

**Comment by jia200x** [comment]
@fjmolinas I will close this one for now. We would eventually get the basic mode for free with the SubMAC + radio HAL.

I will re-open if needed

**Pull request closed without merging**
