### PR TITLE
static_tests: move diff annotations by offset.

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
I am always a bit irritated when the diffs are _above_ the lines they are commenting on. This should fix that.

### Testing procedure
I provided changes to trigger annotations. See Files tab.

### Issues/PRs references
Depends on #15795

### CODE REVIEW

**Comment by miri64** [comment]
Rebased and squashed since #15795 got merged.

**Comment by MrKevinWeiss** [comment]
I would think the extra maintenance cost isn''t worth it but if you really want it maybe just a comment of what the lines are doing for those of us who aren't super `sed`y

Maybe even refactor in lieu of a comment to a common function?

**Comment by miri64** [comment]
> I would think the extra maintenance cost isn''t worth it

Which extra maintainance? Once it is deployed I don't expect much maintainance.

**Comment by miri64** [comment]
> if you really want it maybe just a comment of what the lines are doing for those of us who aren't super `sed`y

Done

**Comment by miri64** [comment]
> Maybe even refactor in lieu of a comment to a common function?

Not sure what you mean here.

**Review by MrKevinWeiss — APPROVED** [review]
Thanks, please squash.

**Comment by MrKevinWeiss** [comment]
> > Maybe even refactor in lieu of a comment to a common function?
> 
> Not sure what you mean here.

Maybe some helper function in the github annotate script since it is doing the same thing, but it is fine how it is.

**Comment by miri64** [comment]
> > > Maybe even refactor in lieu of a comment to a common function?
> > 
> > 
> > Not sure what you mean here.
> 
> Maybe some helper function in the github annotate script since it is doing the same thing, but it is fine how it is.

I don't remember exactly anymore what was the problem, but it doesn't work. Either, we decided against it, since there was a small enough difference between the diff formats those checks output, that we deemed it not worth the effort or there was a problem with how bash/dash handlesline breaks when thrown into a function..

**Comment by miri64** [comment]
Squashed

**Pull request merged**
