### PR TITLE
 unittests: Const input strings

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Add const qualifier to strings that are used as test inputs.

### Testing procedure

Run tests/unittests

### Issues/PRs references

Nothing yet.

### CODE REVIEW

**Comment by gebart** [comment]
These changes are necessary for a successful build if `-Wwrite-strings` is added to CFLAGS.

**Comment by PeterKietzmann** [comment]
`Timeout in expect script at "child.expect_exact('[SUCCESS]', timeout=TIMEOUT)" (tests/bench_runtime_coreapis/tests/01-run.py:18)`

**Comment by aabadie** [comment]
@PeterKietzmann, the failure reported by Murdock initially seemed unrelated to me so I have retriggered Murdock and now it passes.

**Comment by gebart** [comment]
This saves 208 bytes of RAM on frdm-kw41z for a full unittests application build because of the relocated strings from .data to .rodata.

**Comment by miri64** [comment]
Does anyone want to take over this simple clean-up? @bergzand @aabadie?

**Comment by miri64** [comment]
Rebased to current master in https://github.com/RIOT-OS/RIOT/pull/14359

**Pull request closed without merging**
