### PR TITLE
saul: initial import of saul_bat_voltage module

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This exposes the battery measuring capabilities for feather-like boards (see, e.g., https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/power-management-2#measuring-battery-3122383) into SAUL so that the output value is the voltage and provides support for ~~4~~ 7 boards:

- feather-nrf52840-sense ( :white_check_mark: tested )
- feather-nrf52840 ( :white_check_mark: tested )
- particle-xenon ( :white_check_mark: tested )
- particle-argon ( :red_square: not tested, don't own the board )
- ~~feather-m0, as well as its derivates, `feather-m0-lora` and `feather-m0-wifi`, ( :yellow_square: tested, but not working as expected[^1] )~~, see https://github.com/RIOT-OS/RIOT/pull/21018#issuecomment-2491210025

[^1]: not sure if the board I used for testing is broken. It used to work 5 years ago, [here is the app](https://github.com/miri64/RIOT_playground/tree/master/wand) where I took the config from. Sadly, I did not find the LARP prop I integrated the board I used for that into.

### Testing procedure

Flash `example/saul` to one (or ideally all) of the supported boards and use the CLI to read from the `BAT` registry entry. Here is a handy check list so reviewers might distribute the job among themselves. The bold ones are particularly important as I was unable to test them properly myself.

- [x] feather-nrf52840-sense
- [x] feather-nrf52840
- [x] particle-xenon
- [ ] **particle-argon**
- [x] ~~**feather-m0**, **feather-m0-lora**, or **feather-m0-wifi**~~

### Issues/PRs references

Used for testing the power consumption of #20996.

### CODE REVIEW

**Review by maribu — APPROVED** [review]
code looks good to me. I think @chrysn has plenty of particle boards, maybe also the one that still needs testing?

**Comment by miri64** [comment]
> 1. not sure if the board I used for testing is broken. It used to work 5 years ago, [here is the app](https://github.com/miri64/RIOT_playground/tree/master/wand) where I took the config from. Sadly, I did not find the LARP prop I integrated the board I used for that into. [↩](#user-content-fnref-1-9c44d1763d0ecb3f243e65547adbce47)

I just remembered, that I also have a `feather-m0-lora` here. Same problem as with the bare `feather-m0`, so its definitely not the board: ADC line 7 samples constantly to -1, which results in -6mV being returned.

**Comment by miri64** [comment]
I am removing the `feather-m0`-part for now from this PR, so this can go ahead with the working configurations.

**Comment by miri64** [comment]
Moved to https://github.com/RIOT-OS/RIOT/pull/21022

**Comment by chrysn** [comment]
I only have particle-xenon, but it works fine there. It reads a voltage of 4.458V, no matter whether the battery is connected or not (probably b/c I can't use serial w/o also powering the device). All my boards are xenon, but my understanding is that the differences between the particle boards are quite minimal.

**Comment by miri64** [comment]
> It reads a voltage of 4.458V, no matter whether the battery is connected or not (probably b/c I can't use serial w/o also powering the device).

Here's some proof, that the value actually changes over time ;-)

grafik

**Comment by mguetschow** [comment]
Successfully tested on `feather-nrf52840`: With a 600mAh battery connected and one LED turned on, the reported voltage dropped from around 4100mV to 3600mV over night.

**Comment by mguetschow** [comment]
> Successfully tested on `feather-nrf52840`: With a 600mAh battery connected and one LED turned on, the reported voltage dropped from around 4100mV to 3600mV over night.

The `feather-nrf52840-sense` also reports 3600mV with the same battery attached.

**Comment by miri64** [comment]
Anyone has an [Argon](https://store.particle.io/products/argon-kit) laying around? Otherwise, can we just assume that it works, as they use the common interface?

**Comment by maribu** [comment]
Compromise: Let's merge this as is, but document that we did not test on Argon specifically, but are optimistic that it will just work due to the similarity? A one-line comment would be totally sufficient.

**Review by maribu — APPROVED** [review]

**Comment by miri64** [comment]
> Let's merge this as is, but document that we did not test on Argon specifically, but are optimistic that it will just work due to the similarity? A one-line comment would be totally sufficient.

Where should this doc go then? To the header file of `saul_bat_voltage` or to the particle-argon doc?

**Comment by miri64** [comment]
> Where should this doc go then? To the header file of `saul_bat_voltage` or to the particle-argon doc?

Done.

**Pull request merged**
