### PR TITLE
boards/{calliope-mini,microbit*}: factorize common microbit module, use ztimer

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR does 2 things:
- it reuses the common microbit module used to control the LED matrix with the calliope-mini (a microbit clone) 
- it migrates the common microbit module to ztimer

### Testing procedure

- Green CI
- `tests/board_calliope-mini` and `tests/board_microbit` are still working (untested yet, I don't own a calliope-mini for testing)

### Issues/PRs references

None

### CODE REVIEW

**Comment by fjmolinas** [comment]
@haukepetersen you contributed the calliope-mini, do you think you could test this one?

**Comment by fjmolinas** [comment]
@aabadie there are some static checks complaints!

**Comment by aabadie** [comment]
Tested `tests/board_microbit` with success on microbit and microbit-v2.

**Review by fjmolinas — APPROVED** [review]
ACK, there is a missing test on `calliope` but I look at the code and it's exactly the same, so I think it's OK to go ahead. @aabadie tested on the other BOARDs

**Pull request merged**
