### PR TITLE
tests: remove some pointless test applications

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
Adopted #2144

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
ACK for the last two commits. Can't say something about the first one

**Comment by LudwigOrtmann** [comment]
@OlegHahm you implicitly ACK'd this in #2144, does it hold?

**Comment by OlegHahm** [comment]
I guess it does.

**Comment by PeterKietzmann** [comment]
And Travis doesn't complain. Should we merge this?

**Comment by LudwigOrtmann** [comment]
Why not?

**Comment by phiros** [comment]
ACK from my side for this PR in its current form.
The msg queue fairness test should be replaced by multiple unit tests which use mockups instead
of running threads.

**Comment by PeterKietzmann** [comment]
I was just wondering why nobody just pressed the merge-button. I'll do this now

**Comment by LudwigOrtmann** [comment]
@PeterKietzmann I guess you were the first in front of the green light.

**Pull request merged**
