### PR TITLE
tests: Add missing test targets

### PR DESCRIPTION
**Pull request by Lotterleben**
Add test targets to Makefiles of three tests that have a `tests/` folder with a test (python) script in it, but no matching target. I've put them in separate commits for now but I'll be happy to squash them if that's more concise...

### CODE REVIEW

**Comment by miri64** [comment]
Mhhhhh.... Maybe add something centrally :-/ Let me think about it.

**Comment by Lotterleben** [comment]
What do you mean by centrally?

**Comment by miri64** [comment]
For example in `tests/Makefile.tests_common` (only if there are files in `tests/<testname>/tests` of course, but this you can scan)

**Comment by Lotterleben** [comment]
Mhm, but I though for example for the lwIP tests it works differently than in this case, can that be generalized somehow?

**Comment by miri64** [comment]
Yes, but let's do this in a follow-up PR.

**Comment by Lotterleben** [comment]
Okay, to be honest I don't quite get what Jenkins' problem seems to be here... He gets stuck with the example applications, where this PR changes nothing?

**Comment by miri64** [comment]
Those are the same errors Jenkins is struggling randomly with for a while now, and Murdock is still the deciding voice, so go.

**Comment by Lotterleben** [comment]
All right, thanks! :)

**Pull request merged**
