### PR TITLE
gnrc_netdev: remove remaining files and references

### PR DESCRIPTION
**Pull request by miri64**
Somehow, these files were forgotten in my big cleanup in #7925. This fixes that.

### CODE REVIEW

**Comment by bergzand** [comment]
Looks like Murdock discovered some includes that were missing from some tests but pulled in by the gnrc_netdev headers.

**Comment by miri64** [comment]
Fixed

**Comment by bergzand** [comment]
@miri64 From the remaining errors, it looks like the openthread package first needs a bit of reworked glue to get rid of gnrc_netdev.

**Comment by miri64** [comment]
> @miri64 From the remaining errors, it looks like the openthread package first needs a bit of reworked glue to get rid of gnrc_netdev.

WTF???!!? What has openthread to do with GNRC???!

**Comment by bergzand** [comment]
Whoa, don't shoot the messenger.

[Here](https://github.com/RIOT-OS/RIOT/blob/master/pkg/openthread/include/ot.h#L33) is the guilty line, but from what I see is that that should be a "net/netdev.h", but I didn't test it.

**Comment by miri64** [comment]
> Whoa, don't shoot the messenger.

Never said I would ;-). More like stomping of and blindly shouting at the people responsible (me included because I didn't catch it in #7082 either).

**Comment by bergzand** [comment]
Is it possible to also remove the gnrc_netdev modules from `Makefile.dep`?

**Comment by bergzand** [comment]
Pre-rebase ACK btw.

**Comment by miri64** [comment]
> Is it possible to also remove the gnrc_netdev modules from Makefile.dep?

Done and rebased.

**Comment by bergzand** [comment]
A quick grep shows quite a few remaining references to either gnrc_netdev as comment (netdev radio drivers) or gnrc_netdev_default` as a module. Do you want to have those removed here too?

Most notable references found to gnrc_netdev so far:

Most notably so far
- `sys/Makefile:64`
- `drivers/Makefile.dep:57`

**Comment by miri64** [comment]
`gnrc_netdev_default` is supposed to stay (it pulls in GNRC and the default netdev for a board. Will remove the other references.

**Comment by miri64** [comment]
Done.

**Comment by bergzand** [comment]
Ack, squash please.

**Comment by miri64** [comment]
Squashed.

**Pull request merged**
