### PR TITLE
Adding a RELIC package plus example application that demonstrates its use

### PR DESCRIPTION
**Pull request by tfar**
Test-Information:

This has been tested on OS X for the native target and on Ubuntu for both the
native target and STM32F4Discovery.

### CODE REVIEW

**Comment by tfar** [comment]
@OlegHahm any progress or other news on this? IIRC you wanted to take a look at this?

**Comment by OlegHahm** [comment]
I'm looking. The problem seems one the one hand that unittests so far do not expect packages - currently trying to fix that - and on the other hand that the test strings are somehow not properly escaped - which they should be.

**Comment by OlegHahm** [comment]
Why is the distinction between native and non-native in the relic Makefile necessary?

**Comment by tfar** [comment]
See line 22 and 28 in pkg/relic/Makefile. For non-native targets we tell CMake, by passing a generated configuration file, to not do any system test regarding the supported features and just use the values in the configuration file. Without this CMake will try to build and run cross-compiled tests which is doomed to fail.

**Comment by OlegHahm** [comment]
https://github.com/tfar/RIOT/pull/1 fixes the unittest problems.

**Comment by OlegHahm** [comment]
> See line 22 and 28 in pkg/relic/Makefile. For non-native targets we tell CMake, by passing a generated configuration file, to not do any system test regarding the supported features and just use the values in the configuration file. Without this CMake will try to build and run cross-compiled tests which is doomed to fail.

Ok, but can't we just use the the same feature set for native, too? I'm asking because I would like to prepare patch files to get rid of the compiler warnings and with a sub-folder for each platform that seems to be impossible.

**Comment by OlegHahm** [comment]
@tfar, if you review/merge tfar#1 and rebase we're close to getting this merged.

**Comment by OlegHahm** [comment]
@tfar, ping!

**Comment by tfar** [comment]
@OlegHahm thx for the poke. Will take a look at it today or tomorrow and do a rebase.

**Comment by tfar** [comment]
@OlegHahm seems it still doesn't work. I do not have the time to setup the complete test environment to run the tests and Travis needs > 48h to test changes to this pull request. Feel free to fix. Happy to answer questions related to Relic.

**Comment by tfar** [comment]
@OlegHahm seems it still doesn't work. I do not have the time to setup the complete test environment to run the tests and Travis needs > 48h to test changes to this pull request. Feel free to fix. Happy to answer questions related to Relic.

**Comment by OlegHahm** [comment]
I have prepared a fix for the whitespace issue (https://github.com/OlegHahm/RIOT/tree/relic_fixes), but do not have the time to take a closer look into the rest. @x3ro, do you have some capacities to help? (You are also physically closer to @tfar. :wink:)

**Comment by x3ro** [comment]
@OlegHahm Not until the end of next week, I'm afraid :confused: After that I could reserve a timeslot :D

**Comment by OlegHahm** [comment]
This PR is open for 4 months now - I think one week doesn't make much difference. :)

**Comment by x3ro** [comment]
I tried to run the unit tests, but for some reason patch 0002 doesn't apply for me. Says it's corrupt in the current HEAD of the PR. @OlegHahm Do the patches actually apply for you in the current state, either yours or the on in the PR?

**Comment by OlegHahm** [comment]
Try without https://github.com/tfar/RIOT/commit/8fa7753598d81454a798841ecab540dbffa15157

**Comment by x3ro** [comment]
Tried that, but it does not apply either :frowning:

**Comment by OlegHahm** [comment]
Updated the patch and pinned the RELIC revision in https://github.com/OlegHahm/RIOT/tree/relic_fixes

**Comment by x3ro** [comment]
Thanks!

**Comment by OlegHahm** [comment]
For the record: I created the patch with
`find . -name "*.[hc]" | xargs sed -i 's/util_print(\(.*\)")/util_print(\1", NULL)/`

**Comment by OlegHahm** [comment]
@x3ro, any news from this end?

**Comment by x3ro** [comment]
Not really :( Currently caught up w/ work until at least mid next week, will try to squeeze it in then!

**Comment by OlegHahm** [comment]
Ok, no worries, was just checking. I think this PR is too close to be mergeable to drop it, but mostly not dependent on anything else, so you can just continue to work on it when you have time and then we see if we can have it for the release or not.

**Comment by OlegHahm** [comment]
Merged in #4360.

**Pull request closed without merging**
