### PR TITLE
doc: order modules alphabetically

### PR DESCRIPTION
**Pull request by OlegHahm**
Addresses #2838

### CODE REVIEW

**Comment by authmillenon** [comment]
Doctest has past, so ACK and go (am not able to restart failed jobs)

**Comment by OlegHahm** [comment]
>  (am not able to restart failed jobs)

Out of curiosity: Why not?

**Comment by authmillenon** [comment]
That you have to ask Travis. It said it restarted the Job after I hit the button but did not...

**Comment by phiros** [comment]
Travis is an asynchronous system. Sometimes it can take a while until changes propagate through all components of travis.
A while ago I also encountered this problem. More than one hour after pressing the restart button travis decided that it would restart the job.

**Pull request merged**
