### PR TITLE
New pkg_bitlash (WIP)

### PR DESCRIPTION
**Pull request by d00616**
Bitlash http://bitlash.net/ is an compact interpreter. My goal is porting this to RIOT as an Shell replacement by mapping all shell_commands to bitlash.

Actually i don't know how to fix this build error:
# cd tests/pkg_bitlash
# LANG=C make
Building application "testbitlash" for "native" with MCU "native".

"make" -C /tmp/RIOT/pkg/bitlash
make -C /tmp/RIOT/pkg/bitlash/bitlash
make /tmp/RIOT/tests/pkg_bitlash/bin/native/bitlash.a
make[2]: Nothing to be done for `/tmp/RIOT/tests/pkg_bitlash/bin/native/bitlash.a'.
"make" -C /tmp/RIOT/boards/native
..
"make" -C /tmp/RIOT/sys/vtimer
/tmp/RIOT/tests/pkg_bitlash/bin/native/testbitlash.a(main.o): In function `main':
main.c:(.text.main+0x11): undefined reference to `initBitlash'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

### CODE REVIEW

**Comment by Kijewski** [comment]
Hi, d00616, thanks for your interest in porting this project for RIOT!

Please see https://github.com/d00616/RIOT/pull/2:

- You need to add `extern "C"` to the .h file to prevent name mangling. I am not sure though why bitlash.cpp is a .cpp.
- `RIOT_BUILD` is only defined in the Makefile of the package itself, not in code using it. I replaced it with `BUILD_BOARD`.

Now `tests/pkg_bitlash` builds, but I don't know how to use it.

**Comment by d00616** [comment]
> Now |tests/pkg_bitlash| builds, but I don't know how to use it.
>
Thank you for this fix. At the moment the code needs a lot of work to
get this running in the way i want. If you want to test bitlash, run
make from pkg/bitlash/bitlash/src directory. This builds an Linux binary.

In past i have used bitlash for scripting micro controllers. It possible
store functions in eeprom which are running on startup. Bitlash Tasks
can created.

**Comment by OlegHahm** [comment]
@d00616, do you plan to continue to work on this?

**Comment by d00616** [comment]
You can close this PR. I have no time to work on this at the moment.

Am 26.02.2016 um 17:43 schrieb Oleg Hahm:

**Comment by OlegHahm** [comment]
Ok, too bad, but thanks for the quick response.

**Pull request closed without merging**
