### PR TITLE
cpu: cortexm: make newlib a default module

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Currently, newlib is always selected using ```USEMODULE``` for all Cortex-M.
This PR turns it into ```DEFAULT_MODULE```. The advantage is that now it can be disabled on-demand using ```DISABLE_MODULE```.

### Testing procedure

CI compiling successfully should be fine.

### Issues/PRs references

With #10744, this allows deployments without newlib altogether in some cases.

### CODE REVIEW

**Comment by jcarrano** [comment]
To be more precise, this does _really_ disable newlib, only the bindings to the system calls (which are not "system calls" in RIOT really.)

I'm trying to achieve the same, but in a more granular way, in #9258. Many applications will not be able to remove their dependencies on all syscalls, but they can still benefit from not including certain parts.

**Comment by kaspar030** [comment]
> To be more precise, this does _really_ disable newlib

Yup. Useful for chopping off unused fat, or possibly using a slimmer libc, or ...

**Comment by cladmi** [comment]
Can you give a testing procedure for the NEW possible usage?

**Comment by cladmi** [comment]
If it should be used to select a different `libc` I would not do it with `DEFAULT_MODULE`. 
`libc` should be in `DEFAULT_MODULE`, and `newlib_nano` would be the default implementation.

So I am interested at seeing the usage.

Also right now, when not setting `newlib` I think it would make the default C library being used as`newlib.inc.mk` would not be included. Which feels different from the meaning of disabling `newlib`.

**Comment by kaspar030** [comment]
> Can you give a testing procedure for the NEW possible usage?

Add ```DISABLE_MODULE += newlib newlib_nano``` to ```tests/minimal/Makefile```.
Then try compilation with master and with this branch for e.g., samr21-xpro.

On master, you'll get the usual "EXPECT ERRORS" warning. There even seems to be some effect on code size, but that must be accidental.

Size:

```
   text    data     bss     dec     hex filename
   3044      36    2604    5684    1634 /home/kaspar/src/riot/tests/minimal/bin/samr21-xpro/tests_minimal.elf
```

This is the output of ```BOARD=samr21-xpro make info-modules```:

```
board
core
core_msg
cortexm_common
cortexm_common_periph
cpu
isrpipe
newlib
newlib_nano
newlib_syscalls_default
periph
periph_common
periph_gpio
periph_pm
periph_uart
pm_layered
sam0_common_periph
stdio_uart
sys
tsrb
```

Note newlib\*, stdio_uart and periph_uart.

With this PR (and the same modified Makefile):

Size:

```
   text    data     bss     dec     hex filename
   2140      16    2524    4680    1248 /home/kaspar/src/riot/tests/minimal/bin/samr21-xpro/tests_minimal.elf
```

info-modules:

```
[kaspar@ng minimal (cortexm_make_newlib_default_module)]$ BOARD=samr21-xpro make info-modules
board
core
core_msg
cortexm_common
cortexm_common_periph
cpu
periph
periph_common
periph_gpio
periph_pm
pm_layered
sam0_common_periph
sys
[kaspar@ng minimal (cortexm_make_newlib_default_module)]$
```

Note the absence of newlib\*, stdio_uart and periph_uart.

**Comment by jcarrano** [comment]
>> To be more precise, this does really disable newlib

Oh, OK, good to know. I think we need a test to show that a _functioning_ application can be built without newlib, and that newlib itself is not being included (i.e. that the change is effective). For the second point, maybe verify that newlib init stuff is not the symbols in the elf file.

**Comment by kaspar030** [comment]
> I think we need a test to show that a _functioning_ application can be built without newlib, and that newlib itself is not being included (i.e. that the change is effective). For the second point, maybe verify that newlib init stuff is not the symbols in the elf file.

I've added a commit disabling newlib for the bootloader.

This is before (on samr21-xpro):

```
   text    data     bss     dec     hex filename
   2544      24     672    3240     ca8 /home/kaspar/src/riot/bootloaders/riotboot/bin/samr21-xpro/riotboot.elf
```

This is after:

```
   text    data     bss     dec     hex filename
   1124       0     512    1636     664 /home/kaspar/src/riot/bootloaders/riotboot/bin/samr21-xpro/riotboot.elf                              
```

@basilfx can you give this a try on efm32?

**Comment by fjmolinas** [comment]
> @basilfx can you give this a try on efm32?

I have 1 `efm32`, what would you want me to test? just build `riotboot`? @kaspar030

**Comment by fjmolinas** [comment]
ping @kaspar030 are you still interested in this one?

**Comment by miri64** [comment]
> ping @kaspar030 are you still interested in this one?

Obviously not...

**Pull request closed without merging**
