### PR TITLE
WIP: Lua tests

### PR DESCRIPTION
**Pull request by danpetry**
### Contribution description

This adds tests for the Lua pkg.
This PR will include a cut down version of the Lua test suite, written in Lua, and a basic assert test to test the "hello world" output in examples/lua, as a framework for tests for further additions such as API bindings.

### Issues/PRs references
Depends on https://github.com/RIOT-OS/RIOT/pull/9153, because without it, a lot of the tests are likely to fail.
Depends on #9282 to properly integrate Lua source code.

### CODE REVIEW

**Comment by jcarrano** [comment]
I think it's better if we don't include the test suite in RIOT itself, but rather we download them as a package.

**Comment by jia200x** [comment]
@jcarrano @danpetry please inform me when this PR is not WIP anymore

**Comment by haukepetersen** [comment]
> I think it's better if we don't include the test suite in RIOT itself, but rather we download them as a package.

big +1 one. Please don't simply copy the lua test code into the RIOT repo (as we speak about 15k lines of code here). You might want to add the tests either as a package on their own, or simply include them (maybe optional) to the lua pkg.

**Comment by jcarrano** [comment]
Closed as it's easier to start from scratch. Will open new PR.

**Pull request closed without merging**
