### PR TITLE
ng_at86rf2xx: implement RAWMODE for sending.

### PR DESCRIPTION
**Pull request by thomaseichinger**
Allows the driver being used by with network stacks compiling their own packets.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Acutally, if we would move the driver to use the `netdev2` interface, this PR is not needed anymore (as netdev2 is implicitly providing rawmode).

@thomaseichinger: Are you ok to close this PR as `netdev2` support is planned anyway?

**Comment by cgundogan** [comment]
@haukepetersen @thomaseichinger can this PR then be closed after #4646 gets merged?

**Comment by OlegHahm** [comment]
Is this still relevant?

**Comment by thomaseichinger** [comment]
Not with the transition to netdev2.

**Pull request closed without merging**
