### PR TITLE
Openthread nrf52840

### PR DESCRIPTION
**Pull request by dcellucci**
### Contribution description

I added nrf52840 radio support to the OpenThread example. This involved adding a custom config file that doesn't redefine the PACKAGE value, linking to it in the example's makefile, and instantiating the correct netdev radio struct in the package.

### Testing procedure

I ran the example on two separate boards and verified that they could use the radio to ping eachother.

NB: I found that the UART parser for the CLI (on the RIOT side) does not work properly if you send both a carriage return and a new line. Fixing it will be another pull request.

### Issues/PRs references

#10045

### CODE REVIEW

**Comment by jia200x** [comment]
hi @dcellucci 

welcome to the RIOT community and thanks for adding support for this board!

Could you specify which specific configurations you needed for the nrf52840? Are those board specific or cpu specific? Maybe we can provide them in the pkg or board configuration.

**Comment by dcellucci** [comment]
hi @jia200x ! 

Thanks- RIOT is a pretty cool OS looking forward to working with it. 
I just needed to mod the Platform-config.h file that comes with the `thread-reference-20180926` version of OpenThread. This commit redefines the PACKAGE preprocessor symbol that then causes problems for the Nordic boards because it's then later used as vendor specific attribute in a struct (located at `cpu/nrf52/include/vendor/nrf52.h`). Simply commenting out this line was sufficient to fix the compilation error, but I needed to copy it over a fresh config file to implement this change. I put this config file in the nrf52 directory, but I'm open to suggestions if there's somewhere else it would fit better.

All changes are at the chip level, so any board using an nrf52840 chip should be able to use OpenThread with this commit. 

What isn't implemented is the NETDEV_EVENT_TX_COMPLETE_DATA_PENDING event.  As far as I can tell the current Nordic radio code doesn't ever read the packet to check if the frame pending bit is set or not. However, I have not seen any unexpected behavior due to the absence of this code. Is there something I should look out for that would stem from not implementing this event?

Thanks!
DC

P.S.
I also have a version of the openthread RIOT package that builds using a more recent commit of OpenThread - [af46ffa53b7d8cf17259dbb15f2b42b0d6573841](https://github.com/openthread/openthread/commit/af46ffa53b7d8cf17259dbb15f2b42b0d6573841) (I just picked the most recent commit at the time). There have been a few small changes to the platform API that might be worth updating. They also seem to be 6 months overdue for a new reference release.

**Comment by jia200x** [comment]
hi @dcellucci 

> Thanks- RIOT is a pretty cool OS looking forward to working with it.
I just needed to mod the Platform-config.h file that comes with the thread-reference-20180926 version of OpenThread. This version of OpenThread redefines the PACKAGE preprocessor symbol that then causes problems for the Nordic boards because it's then later used as vendor specific attribute in a struct (located at cpu/nrf52/include/vendor/nrf52.h). Simply commenting out this line was sufficient to fix the compilation error, but I needed to copy it over a fresh config file to implement this change. I put this config file in the nrf52 directory, but I'm open to suggestions if there's somewhere else it would fit better.

I fixed the original problem in #11817. Some contrib files were including the openthread configuration header, which is only required to build OpenThread and not to build the RIOT contrib files. With that it shouldn't be necessary to add a config file and it's still possible to use other configurations if needed. Can you check if that PR solves the issue for you?

> What isn't implemented is the NETDEV_EVENT_TX_COMPLETE_DATA_PENDING event. As far as I can tell the current Nordic radio code doesn't ever read the packet to check if the frame pending bit is set or not. However, I have not seen any unexpected behavior due to the absence of this code. Is there something I should look out for that would stem from not implementing this event?

This NETDEV_EVENT_TX_COMPLETE_DATA_PENDING only works in radios that support automatic ACK handling (e.g at86rf2xx).

For the current OpenThread implementation, the DATA_PENDING and standard TX_DONE are handled the same way, as seen in: https://github.com/RIOT-OS/RIOT/blob/210265cbce3092f0b4b8c93b06fa3d37d2f38d8a/pkg/openthread/contrib/platform_radio.c#L189

You will be able to use Openthread normally, but Sleepy End Devices will not be fully supported (but they aren't in the other radios anyway). There are plans to improve this,so in case you have any ideas/contributions they are welcome!

**Comment by jia200x** [comment]
hi again.

#11817 was merged. Could you try the latest master version of RIOT to see if the OT example compiles without the nrf configuration file?

**Comment by dcellucci** [comment]
Yes that works! I have working ping between two nrf52840 boards using the latest master. There are still a few small changes to the Makefile/Riot package to get nrf52840 working but I can push a new commit that has those and not the config file. 

Best, 
DC

**Comment by jia200x** [comment]
hi @dcellucci 

All right! So, is this issue solved for you? (so I can close it)

**Pull request closed without merging**
