### PR TITLE
stdio: remove superfluous mutex_lock in init

### PR DESCRIPTION
**Pull request by OlegHahm**
Stumbled across this while trying to debug mutexes - which are used inside this module...

### CODE REVIEW

**Comment by haukepetersen** [comment]
NACK. IMHO this adds runtime overhead to a very often used functionality - just so debugging for some core module works...

**Comment by kaspar030** [comment]
agreed...

**Comment by OlegHahm** [comment]
So, we need a printk?

**Comment by OlegHahm** [comment]
btw. I assume that accessing the UART slow things down much more than checking a single value.

**Comment by haukepetersen** [comment]
> So, we need a printk?

I say no. All you can not debug using printf is mutexes and the peripheral UART driver. So introduce printk just for debugging mutexes? No...

**Comment by kaspar030** [comment]
@OlegHahm move the mutex_lock below uart_init?

**Comment by OlegHahm** [comment]
@kaspar030, seems legit. Was probably too late yesterday to see the simple solution.

**Comment by haukepetersen** [comment]
looks better :-)

**Comment by kaspar030** [comment]
@oleghahm would you mind adding a short explanation to the commit?

**Comment by OlegHahm** [comment]
@kaspar030, additional to "Otherwise one cannot enable debugging for mutexes."?

**Comment by kaspar030** [comment]
needs rebase

**Comment by OlegHahm** [comment]
rebased and squashed

**Comment by kaspar030** [comment]
Wait a minute. With the new ringbuffer, the mutex_lock() call is not needed anymore. We can drop it completely. Would you mind changing the PR accordingly?

**Comment by OlegHahm** [comment]
So, just dropping the mutex_lock() in init?

**Comment by kaspar030** [comment]
I don't have a board at hand, but if you could do a quick test and this doesn't break in a completly unforseen way, ACK.

**Comment by OlegHahm** [comment]
rebased

**Comment by kaspar030** [comment]
Would you mind changing the commit & PR descriptions? They don't reflect what's going on anymore. Other than that, ACK.

**Comment by OlegHahm** [comment]
Can't deny that. Updated.

**Comment by kaspar030** [comment]
Nice. Go!

**Pull request merged**
