### PR TITLE
sys/net/rpl: fix possible NULL dereference

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title says

### Testing procedure

No regression in RPL. (Beware: Fully untested!)

### Issues/PRs references

fixes https://github.com/RIOT-OS/RIOT/issues/15006 (or rather the last issue of the three instances reported there)

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK. I tracked `gnrc_rpl_validation_DAO_ACK()` until the first access of dst without any prior NULL check.

**Comment by benpicco** [comment]
bors merge

**Comment by chrysn** [comment]
I see no user that uses this with a NULL argument, nor is it documented as optional -- is silently returning a good thing to do here? (I'd softly lean towards "passing NULL to pointer arguments that don't say they can be NULL is generally not good").

**Comment by maribu** [comment]
I think github cut of crucial context here. Just one line above the snipped shown here we have:

```C
#ifdef MODULE_NETSTATS_RPL
    gnrc_rpl_netstats_rx_DAO_ACK(&gnrc_rpl_netstats, len, (dst && !ipv6_addr_is_multicast(dst)));
#endif
```

As there is already a null pointer check for `dst` here, I think `dst` being `NULL` indeed is indeed intended to be allowed here.

**Comment by maribu** [comment]
Thx :)

**Pull request merged**
