### PR TITLE
.circleci: rename job from build to doc-build

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR rename the job name configured in circleci from "build" to "doc". It will make it more explicit what the circleci check is about.

### Testing procedure

Just check in this PR, the name of the circleci job.

This PR (just wait a bit):

In master:

image

### Issues/PRs references

None

### CODE REVIEW

**Comment by miri64** [comment]
Circle CI does not show up here :-/

**Comment by aabadie** [comment]
Hmm, still appear as "build"...

**Comment by miri64** [comment]
I think the attributes name does not do what you think it does:

```
* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```

**Comment by miri64** [comment]
:clap:

**Comment by miri64** [comment]
It is already uploading. Please squash.

**Comment by miri64** [comment]
On second thought: maybe it makes more sense to rename it to "doc-build"? This is more clearer imho.

**Comment by aabadie** [comment]
renamed doc to doc-build, rebased and squashed :)

**Comment by miri64** [comment]
Go!

**Pull request merged**
