### PR TITLE
boards: initial support of ST Nucleo f446

### PR DESCRIPTION
**Pull request by aabadie**
This is a first attempt for supporting the ST Nucleo f446 board. There's room for improvement (mainly code factorization with other similar boards).

I only tested the port with the hello-world example for the moment and it worked.

### CODE REVIEW

**Comment by aabadie** [comment]
For the record, I added the saul support for the user LED and button. I put it in nucleo-common so it should be available for all supported nucleo.

**Comment by aabadie** [comment]
That would be good if someone could test this one. And also the other related PRs (#5709, #4949, #5798)

**Comment by aabadie** [comment]
Thanks for testing @wilhelmmatilainen. It's strange that your approved review doesn't have any effect on the status of this PR.
Let's wait for @PeterKietzmann review and then it can be merged.

**Comment by PeterKietzmann** [comment]
@aabadie code-wise the PR looks fine to me. @wilhelmmatilainen what did you test? @all who else has this board available?

**Comment by PeterKietzmann** [comment]
@aabadie please add the vendor header to the doxygen exclude patterns [here](https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/riot.doxyfile#L842)

**Comment by aabadie** [comment]
> please add the vendor header to the doxygen exclude patterns

Good catch ! Just pushed the change.

**Comment by wilhelmmatilainen** [comment]
Upload, blinking led, serial. I think it would be fine to resolve problems
as they occur. For the beginning it would be nice to have this as a base.

2016-09-28 16:20 GMT+03:00 Alexandre Abadie <notifications@github.com>:

**Comment by aabadie** [comment]
@PeterKietzmann, I added a [wiki page for this board](https://github.com/RIOT-OS/RIOT/wiki/RIOT-Platforms).

**Pull request merged**
