### PR TITLE
cpu/kinetis_common: Use gpio_init_port for PWM pin handling

### PR DESCRIPTION
**Pull request by gebart**
Updated PWM driver to use gpio_init_port instead of its own pin initialization routine. The periph_conf.h settings are easier to understand now IMO.

### CODE REVIEW

**Comment by gebart** [comment]
ping @haukepetersen

**Comment by haukepetersen** [comment]
looks good, but I don't have time to test right now... So untested ACK from my side

**Comment by gebart** [comment]
Would you be fine with merging this if I say that I ran a couple of tests on Mulle?

**Comment by haukepetersen** [comment]
yes!

**Comment by gebart** [comment]
The servo example works with an RC servo connected to PWM_0 on Mulle.

**Comment by gebart** [comment]
i did not scope the waveform but I assume that since this PR only touches the pin initialization then if it works with a servo, it's OK.

**Comment by haukepetersen** [comment]
Travis failed unrelated and Murdock is happy -> go

**Pull request merged**
