### PR TITLE
kinetis: Refactor RTT driver

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

- Keep counter value between resets
- Let kinetis_mcg_init manage the RTC oscillator, to avoid disrupting the core clock in certain configurations
- Remove some unnecessary macros for hardware abstraction; all Kinetis CPUs which have an RTC only have a single RTC instance, and the ISRs and hardware registers are named the same way in all Kinetis CPU headers.

### Issues/PRs references

Depends on #8928

### CODE REVIEW

**Comment by gebart** [comment]
Rebased after #8928 was merged

**Comment by aabadie** [comment]
Well, this PR was also touching periph_conf files that will probably be changed with I2C rework... Why not waiting ?

**Comment by kYc0o** [comment]
I think what we need is a certitude that the embargo is also in place for **any** change on all the periph_conf files. Therefore, if that's the case, we urge to have the I2C branch in really super fast, otherwise we block more than a half of the current PRs.

**Comment by aabadie** [comment]
You just have to look in the periph_conf if there's already some I2C configured, which was the case here. I think @gebart will probably take the I2C rework opportunity for updating old style (using defines) to new style (using array of struct) I2C configuration.
Unfortunately, the I2C configuration is just above the RTT config so there's a high chance that it will raise a conflict.

> we urge to have the I2C branch in really super fast, otherwise we block more than a half of the current PRs

+1. So what are we waiting for ?

**Pull request merged**
