### PR TITLE
pkg/semtech-loramac: enable setting channels mask

### PR DESCRIPTION
**Pull request by geonnave**
### Contribution description
This change contains an addition to pkg/semtech-loramac/contrib and a patch to be applied on the original semtech-loramac code. Specifically, it:
- enable users to set the channels mask
- includes a patch that enables arbitrary channels masks to be set on region AU915. The change was extracted from the original *Lora-net/LoRaMac-node* repository, see [this commit](https://github.com/Lora-net/LoRaMac-node/commit/e60bd869). It reflects restrictions that were relaxed in a newer LoRa spec (v1.0.3rA).

### Testing procedure

I could not find automated unit tests for `semtech_loramac_getset.c`.

Manual testing could be performed as follows:
- on `examples/lorawan/main.c`, just after `semtech_loramac_set_dr`, add the following:
```.c
/* Set a mask for using only the first 8 channels */
uint16_t channel_mask[6] = {0x00FF, 0, 0, 0, 0, 0};
semtech_loramac_set_channels_mask(&loramac, channel_mask);
```
- inspect that `SendFrameOnChannel` only uses channels in the 0-7 range. For example, modify it temporarily as follows:
```diff
+#include <stdio.h>
LoRaMacStatus_t SendFrameOnChannel( uint8_t channel )
{
+    printf("SendFrameOnChannel: %d\n", channel);
```

### Issues/PRs references

N/A.

### CODE REVIEW

**Comment by aabadie** [comment]
The change only applies to AU915, do you think it could apply to other regions (e.g EU868, I haven't checked) ? If so, what would be useful (especially for testing) is to extend the `loramac` shell command with getter/setter for channel masks.

**Comment by geonnave** [comment]
Hi, I checked the other regions and a similar patch is not necessary for them:
- all others but US915* have no restrictions on minimum channel numbers
- US915* requires at least 2 channels, but that is still the case on latest version of LoRaMac-node as well

Nevertheless, I can try adding a `loramac set ch_mask 00FF00000000000000000000` shell command.

**Comment by geonnave** [comment]
By the way, any tips on converting `"00FF"` to `uint16_6` in a RIOT-idiomatic way?

**Comment by aabadie** [comment]
> any tips on converting "00FF" to uint16_t in a RIOT-idiomatic way? fmt_* functions seem to provide only helpers for uint8_t

I'm wondering if that's possible to give a pointer (casted to uint8_t *) of the uint16_t array to the `fmt_hex_bytes` function. Maybe that would work.

**Comment by geonnave** [comment]
> > any tips on converting "00FF" to uint16_t in a RIOT-idiomatic way? fmt_* functions seem to provide only helpers for uint8_t
> 
> I'm wondering if that's possible to give a pointer (casted to uint8_t *) of the uint16_t array to the `fmt_hex_bytes` function. Maybe that would work.

It didn't (sets only the first 8 bits). The following works, though. Is it fine?

```c
else if (strcmp("ch_mask", argv[2]) == 0) {
    if (argc < 4) {
        puts("Usage: loramac set ch_mask <value>");
        puts("Example setting only channels 0-3: loramac set ch_mask 000F00000000000000000000");
        return 1;
    }
    uint16_t mask[LORAMAC_CHANNELS_MASK_LEN] = { 0 };
    uint8_t tmp[LORAMAC_CHANNELS_MASK_LEN*2];
    fmt_hex_bytes(tmp, argv[3]);
    for (size_t i = 0, j = 0; i < LORAMAC_CHANNELS_MASK_LEN; i++, j+=2) {
        /* copy over to span a 16-bit -wide unsigned integer */
        mask[i] |= tmp[j] << 8;
        mask[i] |= tmp[j+1];
    }
    semtech_loramac_set_channels_mask(&loramac, mask);
}
```

**Comment by aabadie** [comment]
> The following works, though. Is it fine?

I'm fine with the approach.

**Comment by geonnave** [comment]
Ok, change has been uploaded.

**Comment by geonnave** [comment]
Just added a getter for the channel mask as well.

**Comment by geonnave** [comment]
@aabadie ping -- anything else needed here?

**Comment by aabadie** [comment]
Thanks for pinging, I almost forgot this one. I'll try to do another round of review and test it next week (don't hesitate to ping me again if I forgot)

**Comment by geonnave** [comment]
@aabadie ping :)

**Comment by geonnave** [comment]
> I'm trying this PR on iotlab - deployment in EU868 region -, so there's only one channel mask. By default, the channel mask getter return `0007`. Does it correspond to LC1, LC2, LC3 ?

Correct: default channel mask 0x7 (0b111)  =>  the three default channels [LC1, LC2, LC3](https://github.com/Lora-net/LoRaMac-node/blob/32554735fc4e8c764b150497115e71bd67341050/src/mac/region/RegionEU868.h#L270).

**Comment by aabadie** [comment]
> So you could try setting the mask to 0003 (0b11), which should cause only the first 2 channels to be used.

Thanks, so I understood it well. What I'm wondering is how to extend the list of possible channels, since it's possible to have 16 in EU868 (I don't know for other regions). I didn't find how to do that after looking at loramac-node code.

**Comment by geonnave** [comment]
I'm on mobile right now, but my hypothesis is that the LCX are just the
defaults, i.e., setting the mask to 0x15 it should enable a fourth channel,
provided that the region supports a fourth channel.

**Review by aabadie — APPROVED** [review]
Added more EU868 channels using the new setter, and more channels are randomly used when sending packets.

Code changes look good and my questions were answered. Thanks!

ACK

**Pull request merged**
