### PR TITLE
cpu/kinetis_common: Add periph/dac implementation

### PR DESCRIPTION
**Pull request by gebart**
~~(depends on #4431)~~

A minimal DAC implementation for Kinetis.

### CODE REVIEW

**Comment by DipSwitch** [comment]
Needs rebase.

**Comment by gebart** [comment]
rebased

**Comment by DipSwitch** [comment]
Would it be possible to refactor the code so it looks like the ADC implementation and uses a `dac_conf_t` ?

**Comment by haukepetersen** [comment]
I am with @DipSwitch here: I am strictly against moving peripheral drivers that use the old `ifdef endif ifdef endif` paradigm.

**Comment by DipSwitch** [comment]
ACK

Looks good, please squash :)

**Comment by gebart** [comment]
squashed

**Comment by DipSwitch** [comment]
Some build errors

**Comment by gebart** [comment]
Moved `dac_config` array to dac.c

**Comment by gebart** [comment]
OK to squash?
(Murdock passed except the needs squashing part)

**Comment by DipSwitch** [comment]
Fine by me, looks good :)

**Comment by gebart** [comment]
rebased, squashed

**Comment by cgundogan** [comment]
was ACKed and both CIs are happy => GO

**Pull request merged**
