### PR TITLE
Fletcher16: extend with multi-part functions

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This commit extends the fletcher16 function with a set of init, update
and finish functions to allow for multi-part checksums. This is useful
when the data that has to be checksummed is not available in a single
continuous buffer.

### Testing procedure

There is a unittest for verification of the algorithm

### Issues/PRs references

None

### CODE REVIEW

**Comment by bergzand** [comment]
Of course!

**Comment by bergzand** [comment]
Added a test.

**Comment by PeterKietzmann** [comment]
I don't know why travis indicates that the build is in progress. The detailed view shows success. ACK and go

**Comment by bergzand** [comment]
@PeterKietzmann Thanks!

**Pull request merged**
