### PR TITLE
uhcp: improve documentation

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This is the result of [some discussion on the devel mailing list](https://lists.riot-os.org/pipermail/devel/2020-November/006622.html). As proposed by @OlegHahm I added parts of the discussion as a paragraph to the main documentation of UHCP. I also added a half-sentence on which functions are supposed to be implemented by the network stack.

### Testing procedure
Reading and a happy Murdock and Circle CI.

### Issues/PRs references
None

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
LGTM.

**Comment by miri64** [comment]
In Circle CI, however, it does not [look so good](https://4898-7370241-gh.circle-artifacts.com/0/doc/group__net__uhcp.html) ;-).

**Comment by miri64** [comment]
Fixed and squashed.

**Comment by kaspar030** [comment]
&go.

**Comment by OlegHahm** [comment]
Too late for the review, but thanks a lot! 👍

**Pull request merged**
