### PR TITLE
makefile.iotlab.single.inc.mk: add new supported nodes [backport 2018.10]

### PR DESCRIPTION
**Pull request by cladmi**
# Backport of #10282

### Contribution description

This PR adds 2 new types of supported IoT-LAB nodes to `makefile.iotlab.single.inc.mk`: nrf52840dk and microbit.
The new nodes are available on the Saclay site.

### Backport reason

This is not a bugfix but it will allow using these two extra boards to run release tests.
I would have used the commit anyway to do it, so better putting them in the release branch.

### Testing procedure

1. Start an experiment with one of the node:
```
iotlab-experiment submit -n microbit -d 60 -l saclay,microbit,1
```
2. use `auto-ssh` to remotely flash an interact with the node:
```
make BOARD=microbit IOTLAB_NODE=auto-ssh -C examples/default flash term
```
3. Perform steps 1 and 2 with `nrf52840dk`

### Issues/PRs references

Follows #10240

### CODE REVIEW

**Comment by miri64** [comment]
Please provide a reasoning why this backport is needed, as the original PR wasn't a bug fix.

**Comment by miri64** [comment]
Ah sorry, did not see the reasoning in #10282.

**Comment by miri64** [comment]
(I deleted the backport label you introduced, though)

**Comment by cladmi** [comment]
@miri64 Thanks for removing the new label, it was introduced by the backport script but I updated it now.

I will update the reasoning here, thanks for asking.

**Comment by jia200x** [comment]
Thanks @cladmi!

**Pull request merged**
