### PR TITLE
dist: make: iotlab: use target specific var assignment

### PR DESCRIPTION
**Pull request by cgundogan**
Using a target specific variable assignment looks better, IMO.

### CODE REVIEW

**Comment by kYc0o** [comment]
Looks better to me too, can you rebase?

**Comment by kYc0o** [comment]
Well... didn't make it, let's try next release.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by PeterKietzmann** [comment]
@kYc0o I assigned you because you already "half-ACKed" this PR some time ago. Please take over. If not testable until feature freeze, I'll postpone it..

**Comment by OlegHahm** [comment]
Doesn't work for me.

**Comment by kYc0o** [comment]
Maybe something changed on IoT-Lab's side? @aabadie ?

**Comment by aabadie** [comment]
> Maybe something changed on IoT-Lab's side? @aabadie ?

not to my knowledge.

**Comment by OlegHahm** [comment]
No, the Make-magic simply doesn't work here. Does it work for you, @kYc0o?

**Comment by aabadie** [comment]
Tested this PR rebased on latest master and it worked with the following workflow:
* Add `include $(RIOTBASE)/dist/testbed-support/Makefile.iotlab` in `examples/gnrc_networking`
* Use the following command:
```
    make BOARD=iotlab-m3 -C examples/gnrc_networking all iotlab-exp iotlab-flash iotlab-term
```

@cgundogan can you rebase ?

**Comment by cgundogan** [comment]
@aabadie rebased

**Comment by cgundogan** [comment]
btw .. I invoke it as follows:
```
BOARD=iotlab-m3 IOTLAB_PHY_NODES="350+358" IOTLAB_DURATION=5 make clean all iotlab-exp iotlab-term
```

works perfectly.

**Pull request merged**
