### PR TITLE
murdock: disable nrf52dk

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

They're currently too flakey to give useful results.
Thus I suggest disabling until we debug why they're giving so many false negatives. (boards might be physically broken, ...)

### CODE REVIEW

**Comment by miri64** [comment]
Does it make sense to replace them with some `nrf52840-dongle`s? They are cheap and also nRF52 and once they are flashed with RIOT firmware they are able to be flashed without any extra hardware.

**Comment by kaspar030** [comment]
> Does it make sense to replace them with some `nrf52840-dongle`s? They are cheap and also nRF52 and once they are flashed with RIOT firmware they are able to be flashed without any extra hardware or user interaction.

Maybe. IMO boards that have "real" jtag access are preferable, the dongles work by triggering a bootloader, right? Maybe they can be hooked up to jtag.

I actually don't know what's going on with the nrf. (cannot debug atm as they're in the office). It could be that the flash is becoming too used. I also think there might be a power issue.

I opened this PR to reduce the number of false negatives, so we don't have to restart so many builds...

**Comment by maribu** [comment]
I think our current procedure is:

1. Let CI run with tests
2. Tests fail (always, no matter what)
3. Blame broken nrf52dk
4. Ignore test results

If we just ignore the nrf52dk results anyway, we can just disable them in the first place. So I agree with @kaspar030 to disable them until they work reliable.

> Maybe they can be hooked up to jtag.

They have an SWD interface (the two holes left and right next to the USB connector are SWDIO and SWDCLK). Attaching a debugger requires some soldering and is not as easy to work with as a board with an integrated debugger.

I think there is no way to reset the devices to the bootloader if the firmware running is broken. So one buggy PR being tested would result in human interaction required to flash them again. (I think on notebooks the USB ports can be powered on and off individually to reduce power consumption. My notebook does so when I connect a dump ATtiny85 to USB for power only. The kernel prints an "failed to enumerate" message in `dmesg` and will turn the power supply off and on again - I can see the power LED of that ATtiny85 breakout board go dark and on again. If this would be supported by the hardware the dongles are plugged in and could be made available to the userspace, we would indeed have a way to reliably enter the bootloader, no matter what the internal state is. This might be an alternative to a full debugger.)

**Comment by kaspar030** [comment]
> I think on notebooks the USB ports can be powered on and off individually to reduce power consumption.

on the raspi workers, the USB ports can be power cycled. This is done before running each test job. If that's sufficient...

**Comment by benpicco** [comment]
Well with a bad firmware they would still end up unflashable after the power cycle.
Entering the bootloader on the `nrf52840dongle` works by pulling the reset line low, so it's not like with a magic bootloader variable that we could always set 'just in case' on CI (then we would still have to rely on a watchdog to trigger the reset if the firmware hangs) 

`panic()` will enter the bootloader, that should work most of the time - unless `panic()` crashes too.

**Comment by maribu** [comment]
> Entering the bootloader on the `nrf52840dongle` works by pulling the reset line low

Is this a hardware limitation, or an implementation choice of the bootloader? There are some open source bootloader options for the nF52840. If this is not due to a hardware limitation, those likely could be adopted to boot to bootloader in a cold boot, and directly to the firmware after flashing has completed.

**Comment by benpicco** [comment]
> Is this a hardware limitation, or an implementation choice of the bootloader? 

That's just the way the bootloader is configured, no hardware limitation

> those likely could be adopted to boot to bootloader in a cold boot, and directly to the firmware after flashing has completed.

Sounds like a good idea!

**Comment by kaspar030** [comment]
> If this is not due to a hardware limitation, those likely could be adopted to boot to bootloader in a cold boot, and directly to the firmware after flashing has completed.

it would not allow testing reset behavior, like the shell test does. not sure that's important...

**Comment by maribu** [comment]
> it would not allow testing reset behavior, like the shell test does.

If the bootloader logic is as simple as always go to the bootloader on a cold boot and always to firmware on a warm boot, it would. Or am I missing something?

**Comment by miri64** [comment]
:+1: Just to be clear, I agree with this PR, I just wanted to throw in viable alternatives. :-)

**Comment by maribu** [comment]
> +1 Just to be clear, I agree with this PR, I just wanted to throw in viable alternatives. :-)

I think the alternatives are still on the table ;-) It would be nice to again have an nRF52 in the CI :-)

**Pull request merged**
