### PR TITLE
dist/testbed-support: use '.elf' binary for dwm1001 board

### PR DESCRIPTION
**Pull request by blueted2**
### Contribution description

When uploading firmware for the `dwm1001` to the test-bed, this Makefile attempts to use the `.hex` binary, however it appears that one isn't generated for this board, thus it generates an error.

Command:
```
make iotlab-exp
```
Error:
```
iotlab-experiment: error: [Errno 2] No such file or directory: '<firmware>.hex'
```

This commit makes it so that the `.elf` binary is used for both `m3:*` and `dwm1001:*` boards. I don't know if this issue exists for any other boards.

---
My top-level Makefile configuration:
```
IOTLAB_SITE ?= lille
IOTLAB_TYPE ?= dwm1001:dw1000
```
---
### Testing procedure

This commit now allows the firmware to be uploaded for the `dwm1001` board using `make iotlab-exp`.

### CODE REVIEW

**Comment by maribu** [comment]
@aabadie: Could you take a look at this one?

**Comment by aabadie** [comment]
I never tried that part of the build system with IoT-LAB. Looking at the changes I see 2 things:
- this Makefile.iotlab could be used not only with m3 and dwm1001 but also with nrf52xxxdk and other boards. Only zigduino should use .hex and firefly should use .bin
- Instead of using an elf file, I think it's more optimal to use .bin files because the firmware is much smaller, so it saves some bandwidth when uploading the file to IoT-LAB

**Comment by blueted2** [comment]
Good points. It seems fit iot lab complains if you try to start an experiment directly with a .bin (without uploading the firmware first, it shows a pop-up with `Wrong format for this type of nodes. (expected elf)`), but once it's uploaded it's fine.

**Comment by blueted2** [comment]
Okay, so it sees that fit iot doesn't like starting experiments directly with the .bin file, giving the following error on the dashboard:
[screenshot](https://user-images.githubusercontent.com/30503300/190355424-8b257373-143e-4c2f-ad83-8b0a502367c1.png)

It does however seem that first launching the experiment with no firmware, then flashing the firmware seems to do the trick.

**Pull request closed without merging**
