### PR TITLE
esp_now: fix doxygen groups

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Minor doc clean-up after #10663.

### Testing procedure
Follow-up to #10663.

### CODE REVIEW

**Comment by TimoRoth** [comment]
esp_now_params.h also needs its group changed.

**Comment by miri64** [comment]
Fixed

**Comment by miri64** [comment]
Force-pushed embarrassing 35C3-induced typo xD

**Comment by gschorcht** [comment]
@miri64 Thank you. I just forgot that moving the module also affects the documentation :sunglasses:

I'm wondering whether we should have additional `@ingoup` commands for `cpu_esp32` and later `cpu_esp8266` to have it also grouped with the documentation of the MCUs.

**Comment by miri64** [comment]
> I'm wondering whether we should have additional `@ingoup` commands for `cpu_esp32` and later `cpu_esp8266` to have it also grouped with the documentation of the MCUs.

The other MCUs don't do it either so I'd say no.

**Comment by gschorcht** [comment]
Please squash.

**Comment by miri64** [comment]
Squashed

**Pull request merged**
