### PR TITLE
ng_networking: configure as router per default

### PR DESCRIPTION
**Pull request by OlegHahm**
IMO we want every node to be a router per default and only disable routing functionality in special cases.

### CODE REVIEW

**Comment by authmillenon** [comment]
Can we do this via a Makefile macro?

```Makefile
ROUTER ?= 1

ifeq (1,$(ROUTER))
  USEMODULE += ng_ipv6_router_default
else
  USEMODULE += ng_ipv6_default
endif
```

**Comment by authmillenon** [comment]
Also I guess the inclusion of the fib can then also be removed again, since `ng_ipv6_router_default` pulls it in, too.

**Comment by OlegHahm** [comment]
> Can we do this via a Makefile macro?

Hm, should we put this into Makefile.include then?

**Comment by authmillenon** [comment]
Nah, that's application specific IMHO.

**Comment by authmillenon** [comment]
My argument: `ng_ipv6_[router_]default` are in their function as pseudo-modules already flags for the build system. Adding an additional flag to determine which to build would add just a nonsensical addition.

**Comment by authmillenon** [comment]
However since this application is supposed to represent both routing and non-routing behavior (in a production application you very likely won't do that), the user should decide upon which to build. Since changing the Makefile is IMHO always an ugly solution this flag gives the user this possibility.

**Comment by cgundogan** [comment]
BTW, if we decide to include `ng_rpl` in this example, then this PR will be rendered useless, as rpl also pulls in `ng_ipv6_router_default`. But I have to rebase first.

**Comment by authmillenon** [comment]
How about something like this:

```Makefile
RP ?= rpl

ifeq (rpl,$(RP))
  USEMODULE += ng_rpl
else
ifeq (,$(RP))
  USEMODULE += ng_ipv6_default
endif
```

**Comment by OlegHahm** [comment]
I think putting the macro in the example's Makefile may be confusing for starters. So, I would vote to keep it simple and configure it always as a router.

**Comment by cgundogan** [comment]
IMHO this is too over-engineered for a simple example. It will not hurt if we compile with `ng_ipv6_router_default` as default.for

**Comment by authmillenon** [comment]
On the other hand we hide the fact this way, that we are able to be even smaller.

**Comment by OlegHahm** [comment]
I think this is tolerable.

**Comment by authmillenon** [comment]
Fine then. ACK.

**Comment by cgundogan** [comment]
Travis approves

**Pull request merged**
