### PR TITLE
boards/kw41z*: add common configuration and use it with existing kw41z boards

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is factorizing boards configuration of frdm-kw41z, usb-kw41z and phynode-kw41z boards. There are sharing the same clock/uart/spi/i2c configurations so this PR is removing a lot of duplicated code.

### Testing procedure

frdm-kw41z, usb-kw41z, phynode-kw41z should still work.

### Issues/PRs references

Should help with PR adding support of kw41z boards (#10846 for example).

### CODE REVIEW

**Comment by aabadie** [comment]
Briefly tested `examples/default` on frdm-kw41z and usb--kw41z and it still work. I don't have phynode-kw41z.

**Comment by aabadie** [comment]
@gebart, @jia200x, ping

**Comment by aabadie** [comment]
> Unless wired internally to an unboard driver i2c, uart and spi depends on external pins, these are not the same for every board.

I checked again and you are right. I'll update this PR with a new common default SPI configuration, only used by phynode and usb-kw41z. frdm-kw41z will use it's own spi configuration (with 2 spi configured).

**Comment by aabadie** [comment]
@fjmolinas, I reworked this PR following your suggestions. It should be much cleaner now.

**Comment by fjmolinas** [comment]
@aabadie I'm good with the changes. I'll test on frdm-kw41z & usb-kw41z (all tests) before giving ACK.

**Comment by fjmolinas** [comment]
@aabadie I tested it on usb-kw41z and frdm-kw41z. In general most expected to pass tests are succeeding (except periph_timer witch is fixed in masters).
I do have a failing test in ps_schedstatistics (not sure why yet) but this is also failing in master, I wan't to look into it a bit before ACK but I won't block the PR because of that. Also detected #11493 while running tests. Also, can you rebase?

**Comment by aabadie** [comment]
Thanks @fjmolinas, I rebased the branch and fixed some conflicts.

**Comment by aabadie** [comment]
It seems like Murdock is stuck since yesterday. @kaspar030 any idea what's going on ?

**Comment by aabadie** [comment]
@fjmolinas, do you finally ACK this one ?

**Comment by fjmolinas** [comment]
@aabadie Sorry fo the delay, I wanted to perform a final round of testing. There are a bunch of failing tests all related to wrong behaviour with xtimer, but this has been flagged in other ISSUES or PR so ACK.

**Pull request merged**
