### PR TITLE
VERSION: add 2019.07 version file

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Add version file for release branch

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Sorry, I checked before clicking open instead of while this time.

**Comment by miri64** [comment]
Please rebase.

**Comment by MrKevinWeiss** [comment]
Why does it need that commit message in there?

**Comment by miri64** [comment]
> Why does it need that commit message in there?

What commit message? Anyway, please rebase, not merge.

**Comment by MrKevinWeiss** [comment]
Ok maybe that worked!

**Comment by MrKevinWeiss** [comment]
I tried to do it with the web interface and the merge commit message was there...  Then I rebased one of the old PRs that I had closed.

All good now.

**Comment by miri64** [comment]
Ah. Yeah... It's stupid, that you can't rebase via the web interface... :(

**Comment by miri64** [comment]
And merged! Happy release :tada:

**Comment by MrKevinWeiss** [comment]
Many thanks!

**Pull request merged**
