### PR TITLE
tools: ethos: allow `start_network.sh` script to run from anywhere

### PR DESCRIPTION
**Pull request by authmillenon**
allows to run `start_network.sh` like this

```bash
dist/tools/ethos/start_network.sh ...
```

### CODE REVIEW

**Comment by authmillenon** [comment]
Since he is the author, @kaspar030 might also want to have a look at this.

**Comment by kaspar030** [comment]
Fine for now. ACK.

**Comment by authmillenon** [comment]
Backport provided in #5368

**Comment by kYc0o** [comment]
Murdock green -> GO!

**Pull request merged**
