### PR TITLE
cpu/esp32: use module newlib_nano

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the compilation and execution problem of `tests/libc_newlib` for ESP32. The new toolchain version uses the `newlibc-nano`. Module `newlib_nano` has to be used therefore.

### Testing procedure

Compilation and execution of `tests/libc_newlib` should work with any ESP32 board, for example
```
make BOARD=esp32-wroom-32 -C tests/libc_newlib flash test
```

### Issues/PRs references

Depends on #13814

### CODE REVIEW

**Comment by gschorcht** [comment]
@kaspar030 The merge of this PR has to be synchronized with the update of the workers with the new toolchain version

**Comment by benpicco** [comment]
@gschorcht Why do you think only some workers were updated?
It's been consistently failing - maybe the esp32 RTT PR was already queued for build before the update.

**Comment by benpicco** [comment]
> @gschorcht Why do you think only some workers were updated?

nvm, I see…

> ```
> /tests/libc_newlib/main.c:41:2:[m[K [01;31m[Kerror: [m[K#error newlib-nano is enabled but the header is not visible by the build system
>  #error newlib-nano is enabled but the header is not visible by the build system
> ```

**Comment by gschorcht** [comment]
> @gschorcht Why do you think only some workers were updated?
> It's been consistently failing - maybe the esp32 RTT PR was already queued for build before the update.

No, it failed in an earlier run and did not fail in the last run. Furthermore, according to `https://ci.riot-os.org/` a different number of boards failed for different runs. According to the logs, all tests failed on `mobi9.inet.haw-hamburg.de`.

**Comment by cgundogan** [comment]
@gschorcht I enabled a coupld of more workers in mobi9. This usually pulls in the latest riotdocker image. Do you think the problem is with the latest image?

**Comment by gschorcht** [comment]
> This usually pulls in the latest riotdocker image. Do you think the problem is with the latest image?

Ah, I see. The docker image seems to have already the new version of the toolchain with the `newlibc-nano`. This is usually no problem, except for `tests/libc_newlib`. The new version of the toolchain requires this PR for a successful compilation of this test.

What are the options? If we don't merge, compilation of `tests/libc_newlib` will fail on `mobi9`. If we merge this PR, the test will fail on all other nodes.

We could blacklist ESP32 boards for this test until all Murdock nodes are updated.

**Comment by cgundogan** [comment]
@gschorcht then let's get this in as soon as possible. I updated all the mobis to use the latest riotdocker image. I also triggered an update to haw-icc. It takes a bit time until all pods in that cluster react to the command, though. I guess @kaspar030 is then updating the image on breeze and @aabadie on riotbuild?

**Comment by benpicco** [comment]
Looks like Murdock is happy now.

**Comment by cgundogan** [comment]
>Looks like Murdock is happy now.

I think that's luck. I am not sure whether breeze and riotbuild have yet been updated. haw-icc still take a lot of time to update all the docker images.

**Comment by benpicco** [comment]
The change in this PR is still valid and required to work with the updated Murdock workers, so we should merge it.

@gschorcht want to remove the blacklist & revert commit from this PR?

**Comment by gschorcht** [comment]
@cgundogan @kaspar030 @aabadie The compilation of this PR still fails on some workers. That is, they are still not updated with the last docker image which contains the new ESP32 toolchain version with the newlibc-nano.

I was hoping we'd have merged the PR before the hard feature freeze. @leandrolanzieri I think this  PR should also be backported to the release branch, as the current master does not match the ESP32 toolchain version released with the riotdocker image.

**Comment by gschorcht** [comment]
I'm just wondering if it wouldn't be better to fall back from `newlib-nano` to `newlib` for the formatted io. I had to realize that printing `long long int` isn't working with `newlib-nano-formatted-io` by intention. So the question arises whether it is really worth to use `newlib-nano-formatted-io` on a platform that has enough space in the flash memory.

The use of `newlib-nano-malloc` is unaffected. `newlib-nano-malloc` must be used in any case to get `malloc` working for multiple heaps.

**Comment by kaspar030** [comment]
> So the question arises whether it is really worth to use `newlib-nano-formatted-io` on a platform that has enough space in the flash memory.

Good question. I guess if there's megabytes of flash, it would be less surprising to have actually working long long prints in stdio.

I'm a bit worried about portability issues. One of the biggest selling points of RIOT is that applications written for one MCU can be ported easily to another, usually be just re-compiling. That promise is broken if the application is using `%llu`, as it then doesn't work on any board with nano stdio (which means, every cortexm and soon msp430. also AVR doesn't do `%llu`). Worse, it'll break horribly at runtime. Thus I'd rather make users figure out the alternatives early.

**Comment by gschorcht** [comment]
> I'm a bit worried about portability issues. One of the biggest selling points of RIOT is that applications written for one MCU can be ported easily to another, usually be just re-compiling. That promise is broken if the application is using `%llu`, as it then doesn't work on any board with nano stdio (which means, every cortexm and soon msp430. also AVR doesn't do `%llu`). Worse, it'll break horribly at runtime. Thus I'd rather make users figure out the alternatives early.

Ah ok, I see, it makes sense.

I have encountered this problem with `DEBUG` outputs in platform implementations where `uint64_t` and `%llu` are used for 48-bit and 64-bit hardware timers. Would it make more sense to change this `DEBUG` outputs and use the `newlib-nano-formatted-io` from your point of view?

**Comment by kaspar030** [comment]
> Would it make more sense to change this `DEBUG` outputs and use the `newlib-nano-formatted-io` from your point of view?

How many are there? :)

**Comment by kaspar030** [comment]
> How many are there? :)

But the DEBUG outputs are per-file. Is it easy to turn on full stdio (when debugging esp32)?

**Comment by gschorcht** [comment]
> > Would it make more sense to change these `DEBUG` outputs and use the `newlib-nano-formatted-io` from your point of view?
> 
> How many are there? :)

There is only one file `periph/rtc` with five such `DEBUG` outputs.

**Comment by gschorcht** [comment]
> > How many are there? :)
> 
> But the DEBUG outputs are per-file. Is it easy to turn on full stdio (when debugging esp32)?

How could it be controlled to use `newlib` instead of `newlib-nano-formatted-io`?

**Comment by kaspar030** [comment]
> How could it be controlled to use `newlib` instead of `newlib-nano-formatted-io`?

If the toolchain supports both (like ARM), nano is selected by the "newlib-nano" module. Without that, the full newlib is used. "newlib-nano" should be a default module, then it can be disabled case-by-case.

**Comment by gschorcht** [comment]
> > How could it be controlled to use `newlib` instead of `newlib-nano-formatted-io`?
> 
> If the toolchain supports both (like ARM), nano is selected by the "newlib-nano" module. Without that, the full newlib is used. "newlib-nano" should be a default module, then it can be disabled case-by-case.

It should be possible to use the ARM approach. The newlib could be compiled once with `--enable-nano-formatted-io` and once without `--disable-nano-formatted-io`. I will try but it will take some time.

**Comment by kaspar030** [comment]
> It should be possible to use the ARM approach. The newlib could be compiled once with `--enable-nano-formatted-io` and once without `--disable-nano-formatted-io`. I will try but it will take some time.

Hm, maybe this is overkill. I'm happy with this PR for now. Should we just fix the `%llu` in rtc as a followup?

**Comment by gschorcht** [comment]
@benpicco Thanks for merging the PR. Obviously, you had simply luck with Murdock :wink: It seems that there are workers that are still not updated. The compilation of your [PR #13965 failed in `tests/libc_newlib`](https://ci.riot-os.org/RIOT-OS/RIOT/13965/411fd91ec24e8cefef188a00d556946702656677/output.html). `breeze` is complaining that `newlib-nano` is enabled but the header is not visible by the build system :worried:

**Comment by benpicco** [comment]
Gnarly, I would have thought after a month the update would have trickled down to all the workers :confused:

**Comment by cgundogan** [comment]
>breeze is complaining that newlib-nano is enabled but the header is not visible by the build system

ping @kaspar030

**Comment by kaspar030** [comment]
breeze should be updated now.

**Comment by benpicco** [comment]
I still get the occasional

```
-- running on worker breeze thread 12, build number 301935.
make: Entering directory '/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/tests/libc_newlib'
ESP32_SDK_DIR should be defined as /path/to/esp-idf directory
ESP32_SDK_DIR is set by default to /opt/esp/esp-idf
Building application "tests_libc_newlib" for "esp32-mh-et-live-minikit" with MCU "esp32".

[01m[K/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/tests/libc_newlib/main.c:41:2:[m[K [01;31m[Kerror: [m[K#error newlib-nano is enabled but the header is not visible by the build system
 #error newlib-nano is enabled but the header is not visible by the build system
[01;32m[K  ^[m[K
/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/Makefile.base:108: recipe for target '/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/build/application_tests_libc_newlib/main.o' failed
make[1]: *** [/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/build/application_tests_libc_newlib/main.o] Error 1
/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/tests/libc_newlib/../../Makefile.include:568: recipe for target '/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/build/application_tests_libc_newlib.a' failed
make: *** [/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/build/application_tests_libc_newlib.a] Error 2
make: Leaving directory '/tmp/dwq.0.11409646860483635/da8ef86477e10da72afc1594dede9071/tests/libc_newlib'
-- build directory size: 2.2M
```

**Pull request merged**
