### PR TITLE
gnrc_netif_raw: add NETIF header on receive

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
... to give upper layer a hint on the interface the packet came from.

### Testing procedure
`examples/gnrc_minimal` should not run into an assertion:

<details>

```diff
diff --git a/examples/gnrc_minimal/Makefile b/examples/gnrc_minimal/Makefile
index cb657e60b4..f7e72d658e 100644
--- a/examples/gnrc_minimal/Makefile
+++ b/examples/gnrc_minimal/Makefile
@@ -14,7 +14,8 @@ DEVELHELP ?= 0
 
 # Include packages that pull up and auto-init the link layer.
 # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
-USEMODULE += gnrc_netdev_default
+USEMODULE += slipdev_stdio
+CFLAGS += -DGNRC_IPV6_STATIC_LLADDR='"fe80::2"'
 USEMODULE += auto_init_gnrc_netif
 # Enable single interface optimization.
 # Remove this if more than one interface is present
```

```sh
BOARD=samr21-xpro make -C examples/gnrc_minimal/ -j flash term
```

Let run for a minute or two

</details>

(also see https://github.com/RIOT-OS/RIOT/issues/15171)

`examples/gnrc_border_router` should work as before

<details>

(requires two nodes)

###### Terminal 1

```sh
BOARD=samr21-xpro SERIAL="<serial 1>" make -C examples/gnrc_networking/ -j flash
```

###### Terminal 2

```
$ BOARD=samr21-xpro UPLINK=slip SERIAL="<serial 2>" make -C examples/gnrc_border_router/ -j flash term
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_border_router'
make -C ethos
make[2]: Nothing to be done for 'all'.
make -C uhcpd
cc -g -O3 -Wall -DUHCP_SERVER -I/home/mlenders/Repositories/RIOT-OS/RIOT/sys/include -I. /home/mlenders/Repositories/RIOT-OS/RIOT/sys/net/application_layer/uhcp/uhcp.c uhcpd.c -o bin/uhcpd
make -C sliptty
make[2]: Nothing to be done for 'all'.
sudo sh /home/mlenders/Repositories/RIOT-OS/RIOT/dist/tools/sliptty/start_network.sh  2001:db8::/64 /dev/ttyACM0 115200 
Device "sl0" does not exist.
net.ipv6.conf.all.forwarding = 1
Activated forwarding for all interfaces.
Deactivate with
    sudo sysctl -w net.ipv6.conf.all.forwarding=0
when not desired without this script
net.ipv6.conf.sl0.accept_ra = 2
Starting dispatch. TUN: 3, Stream: 4, In: 0, Out: 1
uhcp_client(): no reply received
uhcp_client(): sending REQ...
got packet from fe80::a7a2:cd2f:3eb8:ba18 port 59048
uhcp: push from fe80::a7a2:cd2f:3eb8:ba18:59048 prefix=2001:db8::/64
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8::204:2519:1801:ab27/64
gnrc_uhcpc: uhcp_handle_prefix(): configured new prefix 2001:db8::204:2519:1801:ab27/64
ifconfig
ifconfig
Iface  6 
          MTU:65535  HL:64  RTR  
          
          Link type: wired
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff00:2
          
Iface  5  HWaddr: 2B:27  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 00:04:25:19:18:01:AB:27 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102  MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::204:2519:1801:ab27  scope: link  VAL
          inet6 addr: 2001:db8::204:2519:1801:ab27  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff01:ab27
          
> uhcp_client(): sending REQ...
got packet from fe80::a7a2:cd2f:3eb8:ba18 port 34349
uhcp: push from fe80::a7a2:cd2f:3eb8:ba18:34349 prefix=2001:db8::/64
nib neigh
2001:db8::204:2519:1801:ae82 dev #5 lladdr 00:04:25:19:18:01:AE:82  REACHABLE REGISTERED
```

###### Terminal 1

```
$ ping 2001:db8::204:2519:1801:ae82
PING 2001:db8::204:2519:1801:ae82(2001:db8::204:2519:1801:ae82) 56 data bytes
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=1 ttl=63 time=33.6 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=2 ttl=63 time=34.1 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=3 ttl=63 time=34.5 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=4 ttl=63 time=34.8 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=5 ttl=63 time=32.7 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=6 ttl=63 time=37.2 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=7 ttl=63 time=33.3 ms
64 bytes from 2001:db8::204:2519:1801:ae82: icmp_seq=8 ttl=63 time=35.0 ms
^C
--- 2001:db8::204:2519:1801:ae82 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7011ms
rtt min/avg/max/mdev = 32.705/34.416/37.224/1.288 ms
```

</details>

### Issues/PRs references
Fixes https://github.com/RIOT-OS/RIOT/issues/15171

### CODE REVIEW

**Comment by nmeum** [comment]
Thanks you for the quick fix, I can test it later today! :)

**Comment by nmeum** [comment]
> I can test it later today! :)

Can confirm that this fixes PR the crash described in #15171.

**Review by benpicco — APPROVED** [review]
Looks good, I also tested routing to the host *behind* the border router and that works fine as well.

**Comment by miri64** [comment]
> Looks good, I also tested routing to the host _behind_ the border router and that works fine as well.

I described that and tested that myself in my testing description as well ;-)

**Pull request merged**
