### PR TITLE
doc: Make bootloaders visible in modules

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

Currently, documentation about the bootloaders is only accessible through the source tree and not through the API documentation.

This adds the `bootloaders/` directory to the list of starting points for doxygen, and moves the riotboot documentation into a place where doxygen can pick it up. Some metadata is added to make it fit nicely.

### Testing procedure

* Open the documentation search for "bootloader".
* Since this change, a section shows up (also in the modules list) that currently contains only riotboot

### Issues/PRs references

* The current form of #16011 adds board defines that influence how the bootloader is used; until this is merged, they are not visibly documented.
* Further work seems indicated to document the DFU based bootloader (currently blank), and to make the riotboot docs more newcomer friendly in general. (They describe how it works, but not why it's done (to enable further modules like SUIT to do the actual uploads, or DFU uploads), or how to use it when one does not already have a progammer attached anyway)

### CODE REVIEW

**Review by jeandudey — COMMENTED** [review]
On doxygen 1.8.3 gives the following warning (don't know if this is present on a recent release):

```
"make" -BC doc/doxygen
make[1]: Entering directory '/home/jeandudey/Dev/RIOT/doc/doxygen'
( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
/home/jeandudey/Dev/RIOT/bootloaders/riotboot/doc.txt:110: warning: unable to resolve reference to `https:' for \ref command
*make[1]: Leaving directory '/home/jeandudey/Dev/RIOT/doc/doxygen'
```

It may be a bug on the Doxygen parser, I've got to silence it by using an `a` tag instead :-)

```diff
diff --git a/bootloaders/riotboot/doc.txt b/bootloaders/riotboot/doc.txt
index c3845fef9f..caa3d29e33 100644
--- a/bootloaders/riotboot/doc.txt
+++ b/bootloaders/riotboot/doc.txt
@@ -107,7 +107,7 @@ flash` if the `riotboot` feature is used.
 
 ## Testing riotboot
 
-See [tests/riotboot/README.md](https://github.com/RIOT-OS/RIOT/blob/master/tests/riotboot/README.md).
+See <a href="https://github.com/RIOT-OS/RIOT/blob/master/tests/riotboot/README.md">tests/riotboot/README.md</a>
 
 # Quick riotboot porting guide
 
```

**Comment by chrysn** [comment]
I feel reaffirmed in my distinct dislike for all the tools that use markdown with its sloppy specification(s), especially when they try to use links in a way that they are not only URI references but possibly something different.

The misbehavior does not occur with the Doxygen 1.9 I'm using (which also does a better job at not making headings into an auto-brief).

I'm adding a commit with the necessary changes to work around it, and keeping it separate so that when https://github.com/RIOT-OS/riotdocker/pull/104 is done, it can be reverted.

**Review by jeandudey — APPROVED** [review]
Tested building the documentation, bootloaders show up :-)

<details>
<summary>Docs preview</summary>

Screenshot from 2021-02-17 10-04-54
</details>

**Comment by chrysn** [comment]
During squashing and test runs I found that riotboot/main.c had a conflicting `defgroup`; removed that as while we can have documentation in .c files, it's not the most intuitive place to find high-level groups in.

**Pull request merged**
