### PR TITLE
doc/boards: move jiminy from wiki to RIOT repo

### PR DESCRIPTION
**Pull request by PeterKietzmann**
### Contribution description

This PR moves the documentation of the Jiminy Board from the wiki to this repository

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Addressed. Also removed the pinout link and embedded the picture. Squashed immediately.

**Comment by jia200x** [comment]
thanks! Let's wait for Murdock ;)

**Comment by PeterKietzmann** [comment]
green

**Comment by jia200x** [comment]
alles klar. GO

**Pull request merged**
