### PR TITLE
Update CMSIS HAL to version 4.0

### PR DESCRIPTION
**Pull request by gebart**
I saw that the latest CMSIS release (v4.2) contains an updated CMSIS HAL (versioned 4.0 in the header files).

The largest change is the addition of the Cortex-M7, which we don't support yet, but there seem to be some small bug fixes in the header files as well.

I want to start experimenting with using the CMSIS DSP components for doing signal processing on the node and I believe it is better to update to the latest version of the HAL before I begin working on using the CMSIS DSP.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
Great, to track testing the new versions I'll introduce a checkable list. I'll test the boards I have access to trying to cover all CPUs effected but it would be great if others could contribute their results too.

- [ ] cc2538 (OpenMote)
- [ ] lpc1768 (mbed_lpc1768)
- [ ] nrf51822 (pca10000)
- [ ] sam3x8e (arduino-due)
- [ ] samd21 (samr21-xpro)
- [ ] stm32f0 (stm32f0discovery)
- [ ] stm32f1 (iot-lab_M3)
- [ ] stm32f3 (stm32f3discovery)
- [ ] stm32f4 (stm32f4discovery)
- [ ] stm32l1 (nucleo-l1)

Feel free to add if I missed something.

**Comment by haukepetersen** [comment]
tested the discovery boards and the nordic SoC, everything seems fine!

**Comment by gebart** [comment]
Does anyone have a cc2538 board to test this on? @hexluthor maybe?

**Comment by thomaseichinger** [comment]
Sorry missed this one, can test on OpenMote tomorrow.

**Comment by hexluthor** [comment]
`cc2538dk` seems fine.

**Comment by thomaseichinger** [comment]
All boards seem to be fine. @gebart Want to squash the `extern "C"` commits?

**Comment by gebart** [comment]
@thomaseichinger 
Do you mean squash the extern "C" commits into one per CPU?
I figured we should keep the import commit clean without modifications to the original file from CMSIS and then add a separate commit for our own changes, just to more easily distinguish that it is not part of upstream CMSIS.

**Comment by thomaseichinger** [comment]
Fine with me. ACK & Go

**Pull request merged**
