### PR TITLE
MAINTAINING.md: Add entry on exceptions

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Clarify that common sense should always be applied and that sometimes exceptions from our guidelines are preferable over blindly applying rules.

### Testing procedure

Check the changes in regard to its content, grammar and spelling.

### Issues/PRs references

In https://github.com/RIOT-OS/RIOT/pull/12781 the fear was expressed that a section of the coding convention might be applied blindly. This tries to raise awareness of that issue in general.

### CODE REVIEW

**Comment by miri64** [comment]
This somewhat repeats partly what is already stated in the introduction:

> -   Any of the items in this list might be skipped, if clearly and logically
>     articulated reasons are presented.

**Comment by maribu** [comment]
How about "can be presented" instead of "are presented"? Otherwise it sounds like those reasons have to be documented. In cases it is not obvious why an exception was made, documenting it might make sense. But e.g. for exceptions to the coding convention I'd personally wouldn't like to "fill out forms to formally grant an exception" (purposely wildly exaggerating here).

**Comment by maribu** [comment]
@miri64: I deduplicated the section you quoted from the introduction and reused its wording.

The diff in content are now:

- The exceptions are broader to apply on all guidelines and explicitly also on the coding convention
- The need to document the reasons for the exception is weakened to `can be presented`

**Comment by waehlisch** [comment]
i'm not in favor of the proposed changes. (1) a separate section unnecessarily blows up the document. the statement is already prominently located (first bullet point). in particular, it is located up-front of Section 4. - Review the code against the coding conventions, which means it also applies to Section 4. (2) There is no reason to weaken the statement. usually, it is important to document exceptions. the description in the Coding Conventions is sufficiently flexible. ("shall" instead of "must")

**Pull request closed without merging**
