### PR TITLE
boards: Initial support for Ellduino

### PR DESCRIPTION
**Pull request by latsku**
Hello

This is a first version of support for ELL-i's Ellduino development board.

Short description of the board can be found here:
https://github.com/Ell-i/Hackathon/wiki/Ellduino-development-board

The board does not have an external oscillator and therefore had to move stm32f0 HSE clock initialization to f0 discovery board initialization.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@latsku Do you plan to put any work into this?

**Comment by OlegHahm** [comment]
@latsku, ping!

**Comment by latsku** [comment]
@OlegHahm Pong

I rebased this on top of master and fixed emerging issues. Also found couple mistakes on serial configuration, but couldn't get the serial working. 
* The board has a known **hardware bug** on serial lines, which requires some black magic with `DTR`/`CTS` to boot properly. (`DTR` or `CTS` should be inverted, can't remember which one.)
* Flashing the board requires custom `stm32flash`.
* This is one time prototype board from ELL-i, which isn't going to get re-run in my best knowledge. 

With these in mind, it doesn't really make sense to push further with this pull request.

**Comment by OlegHahm** [comment]
Ok, thanks for the response!

**Pull request closed without merging**
