### PR TITLE
gnrc netif: add a check for interface existence

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
No comment available

**Comment by authmillenon** [comment]
(Please describe why we need this)

**Comment by OlegHahm** [comment]
My concrete use case: an application wants to configure an interface selected by a user. The application needs to check if the interface exists.

**Comment by authmillenon** [comment]
Mh… alright, let's merge this. Can you provide a unittest please?

**Comment by OlegHahm** [comment]
Do you think this is sufficient?

**Comment by authmillenon** [comment]
Yapp, ACK. Please squash.

**Comment by OlegHahm** [comment]
Just wondering: what is BCP? Having unittests and functions in one commit or separated? I would have a light preference for keeping them separated.

**Comment by cgundogan** [comment]
>Just wondering: what is BCP? Having unittests and functions in one commit or separated? I would have a light preference for keeping them separated.

+1

**Comment by OlegHahm** [comment]
Hence, I just changed the commit message of the second commit. If someone strongly disagrees with keeping them separated, please speak up - otherwise we can merge after Travis turns green.

**Comment by cgundogan** [comment]
travis agrees - GO

**Pull request merged**
