### PR TITLE
Monocypher: Initial import of package

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Add support for the [Monocypher] crypto library as external package. Compared to TweetNaCl, the flash usage is twice the size (around 10K), but signature generation and verification is 5 - 8 times as fast as TweetNaCl on the different ARM cortex versions.

### Issues/PRs references

None

[Monocypher]: https://monocypher.org

### CODE REVIEW

**Comment by tcschmidt** [comment]
How does compare to the Relic library already available in RIOT?

**Comment by bergzand** [comment]
> How does compare to the Relic library already available in RIOT?

@tcschmidt Do you have an example on how to use ed25519 based signatures with RELIC? I'd be happy to compare it, but I'd have to know how to actually use RELIC first. For me the interesting metrics to compare on are flash size, stack space usage and speed on the Cortex-M{0+,3,4F}

Monocypher doesn't compile for 8 bit and 16 bit architectures unfortunately.

**Comment by tcschmidt** [comment]
Maybe a look at #4360 helps - or contact @tfar .

**Comment by bergzand** [comment]
@tcschmidt #4360 also was the first thing I thought of for an example, but it only implements ecdh. Comparing goals between RELIC and Monocypher, it seems that RELIC is a library for the low level cryptographic operations where Monocypher presents the user with the high level cryptographic primitives.

Assuming you still want a direct performance comparison between RELIC and Monocypher for public key signature operations, would you mind asking @tfar if he has an example somewhere that is using RELIC for ed25519 based signatures?

**Comment by jcarrano** [comment]
@bergzand Could you add a simple doc.txt so that it shows up in the API docs. Otherwise no one will even know we support this lib?

> Monocypher doesn't compile for 8 bit and 16 bit architectures unfortunately

Put that in the doc.txt

**Comment by bergzand** [comment]
@jcarrano Added a doc.txt based on the tweetnacl one. Also fixed the whitespace issues reported by travis.

**Comment by jcarrano** [comment]
@bergzand Squash and we are ready to go. BTW, its so annoying that the CI fails when you don't squash!

**Comment by bergzand** [comment]
@jcarrano Squashed!

**Comment by bergzand** [comment]
Thanks for the quick review @jcarrano!

**Pull request merged**
