### PR TITLE
CI: bors.toml: set cut_body_after

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR configures bors to not include the whole PR description in its merge messages.

See https://github.com/RIOT-OS/RIOT/pull/18910#issuecomment-1342759338.

### CODE REVIEW

**Comment by kaspar030** [comment]
From #18910 @aabadie :

> What would be a good position? (we could add a marker to the github PR template).
> It's a bit annoying that the comments don't get filtered out. Maybe drop the initial comment, and add a marker to the template, maybe just before the testing instructions?

I would even use `### Contribution description` because it can also be quite long. The PR number is already referenced in the commit message and GitHub/Murdock turns it into a link to the PR anyway.

**Comment by kaspar030** [comment]
> I would even use `### Contribution description` because it can also be quite long. The PR number is already referenced in the commit message and GitHub/Murdock turns it into a link to the PR anyway.

I set it to the first `<!---`, so basically the whole PR description is cut.

**Review by aabadie — APPROVED** [review]
ACK

**Pull request merged**
