### PR TITLE
Driver for Freescale MMA8652 Accelerometer

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR add support for Freescale MMA8652 3-Axis 12-bit Digital Accelerometer.
This driver only implements basic functionality.

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
Tested with af03da054435475f2e395e55fd77ba5a3af29ce9, OK.

**Comment by OlegHahm** [comment]
Ready to go.

**Comment by PeterKietzmann** [comment]
Okay, go

**Comment by PeterKietzmann** [comment]
Ups, don't go yet. After merging the other drivers there are conflicts...

**Comment by PeterKietzmann** [comment]
PS: Without looking deeper in it I assume you just need to rebase and solve conflicts in drivers/Makefile.include

**Comment by jfischer-phytec-iot** [comment]
rebased, but the merging of TMP006 was not working properly.

**Comment by OlegHahm** [comment]
> but the merging of TMP006 was not working properly

What do you mean?

**Comment by jfischer-phytec-iot** [comment]
Ignore it about TMP006, I'm a little confused today :-) :ghost:

**Comment by PeterKietzmann** [comment]
@jfischer-phytec-iot what is the problem? Today I can't test this with hardware but compiling the test application for the stm32f4discovery board with the current master is successful.

**Comment by PeterKietzmann** [comment]
Sorry ignore the last one please.It's outdated. I had some craftsmen here today working on the communication lines. That's why I couldn't go to the office and had no internet here for a while. So everything should be ready to merge.

**Comment by PeterKietzmann** [comment]
And go

**Pull request merged**
