### PR TITLE
sys/fmt: make fmt_s32_dfp() string based

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This re-writes `fmt_s32_dfp()` to be string based (adding "." or "0" instead of using arithmetics). This makes it independent of TENMAP_SIZE.

Code is roughly the same size, performs roughly the same. The dropped tenmap dependency makes binaries ~32b smaller.

### CODE REVIEW

**Review by MrKevinWeiss — COMMENTED** [review]
I guess some documentation and tests should be updated in this case:

<details>

```diff
diff --git a/sys/fmt/fmt.c b/sys/fmt/fmt.c
index ae47fbf387..e612a245f8 100644
--- a/sys/fmt/fmt.c
+++ b/sys/fmt/fmt.c
@@ -46,6 +46,7 @@ static const uint32_t _tenmap[] = {
     10000000LU,
 };
 
+/** @brief       Max precision of floating point numbers */
 #define TENMAP_SIZE  ARRAY_SIZE(_tenmap)
 
 static inline char _to_lower(char c)
diff --git a/sys/include/fmt.h b/sys/include/fmt.h
index 816791cf92..f51e0e52e8 100644
--- a/sys/include/fmt.h
+++ b/sys/include/fmt.h
@@ -306,16 +306,16 @@ size_t fmt_s16_dfp(char *out, int16_t val, int fp_digits);
  *
  * The resulting string will always be patted with zeros after the decimal point.
  *
- * For example: if @p val is -3548 and @p fp_digits is -2, the resulting string
- * will be "-35.48". The same value for @p val with @p fp_digits of 2 will
- * result in "-354800".
+ * For example: if @p val is -35648 and @p fp_digits is -2, the resulting
+ * string will be "-352.48". The same value for @p val with @p fp_digits of 2
+ * will result in "-3524800".
  *
- * @pre fp_digits > -8 (TENMAP_SIZE)
+ * @attention As there are no bounds checks this must be done by the calling
+ *            function.
  *
  * @param[out] out          Pointer to the output buffer, or NULL
  * @param[in]  val          Fixed point value
- * @param[in]  fp_digits    Number of digits after the decimal point, MUST be
- *                          >= -7
+ * @param[in]  fp_digits    Number of digits after the decimal point
  *
  * @return      Length of the resulting string
  */
@@ -333,7 +333,7 @@ size_t fmt_s32_dfp(char *out, int32_t val, int fp_digits);
  *            It pulls in about 2.4k bytes of code on ARM Cortex-M platforms.
  *
  * @pre -2^32 < f < 2^32
- * @pre precision < 8 (TENMAP_SIZE)
+ * @pre precision < 10 (TENMAP_SIZE)
  *
  * @param[out]  out         string to write to (or NULL)
  * @param[in]   f           float value to convert
@@ -490,7 +490,7 @@ void print_s64_dec(uint64_t val);
  * @note See fmt_float for code size warning!diff --git a/sys/fmt/fmt.c b/sys/fmt/fmt.c
index ae47fbf387..e612a245f8 100644
--- a/sys/fmt/fmt.c
+++ b/sys/fmt/fmt.c
@@ -46,6 +46,7 @@ static const uint32_t _tenmap[] = {
     10000000LU,
 };
 
+/** @brief       Max precision of floating point numbers */
 #define TENMAP_SIZE  ARRAY_SIZE(_tenmap)
 
 static inline char _to_lower(char c)
diff --git a/sys/include/fmt.h b/sys/include/fmt.h
index 816791cf92..f51e0e52e8 100644
--- a/sys/include/fmt.h
+++ b/sys/include/fmt.h
@@ -306,16 +306,16 @@ size_t fmt_s16_dfp(char *out, int16_t val, int fp_digits);
  *
  * The resulting string will always be patted with zeros after the decimal point.
  *
- * For example: if @p val is -3548 and @p fp_digits is -2, the resulting string
- * will be "-35.48". The same value for @p val with @p fp_digits of 2 will
- * result in "-354800".
+ * For example: if @p val is -35648 and @p fp_digits is -2, the resulting
+ * string will be "-352.48". The same value for @p val with @p fp_digits of 2
+ * will result in "-3524800".
  *
- * @pre fp_digits > -8 (TENMAP_SIZE)
+ * @attention As there are no bounds checks this must be done by the calling
+ *            function.
  *
  * @param[out] out          Pointer to the output buffer, or NULL
  * @param[in]  val          Fixed point value
- * @param[in]  fp_digits    Number of digits after the decimal point, MUST be
- *                          >= -7
+ * @param[in]  fp_digits    Number of digits after the decimal point
  *
  * @return      Length of the resulting string
  */
@@ -333,7 +333,7 @@ size_t fmt_s32_dfp(char *out, int32_t val, int fp_digits);
  *            It pulls in about 2.4k bytes of code on ARM Cortex-M platforms.
  *
  * @pre -2^32 < f < 2^32
- * @pre precision < 8 (TENMAP_SIZE)
+ * @pre precision < 10 (TENMAP_SIZE)
  *
  * @param[out]  out         string to write to (or NULL)
  * @param[in]   f           float value to convert
@@ -490,7 +490,7 @@ void print_s64_dec(uint64_t val);
  * @note See fmt_float for code size warning!
  *
  * @pre -2^32 < f < 2^32
- * @pre precision < TENMAP_SIZE (== 8)
+ * @pre precision < TENMAP_SIZE (== 10)
  *
  * @param[in]   f           float value to print
  * @param[in]   precision   number of digits after decimal point
diff --git a/tests/unittests/tests-fmt/tests-fmt.c b/tests/unittests/tests-fmt/tests-fmt.c
index 75a647b8c7..a11a48e254 100644
--- a/tests/unittests/tests-fmt/tests-fmt.c
+++ b/tests/unittests/tests-fmt/tests-fmt.c
@@ -738,6 +738,15 @@ static void test_fmt_s32_dfp(void)
     out[act_len] = '\0';
     TEST_ASSERT_EQUAL_STRING("-0.0000001", (char *)out);
 
+    val = -1;
+    fpp = -24;
+    len = fmt_s32_dfp(NULL, val, fpp);
+    TEST_ASSERT_EQUAL_INT(3 - fpp, len);
+    act_len = fmt_s32_dfp(out, val, fpp);
+    TEST_ASSERT_EQUAL_INT(3 - fpp, act_len);
+    out[act_len] = '\0';
+    TEST_ASSERT_EQUAL_STRING("-0.000000000000000000000001", (char *)out);
+
     /* check that the buffer was not overflowed */
     TEST_ASSERT_EQUAL_STRING("z", &out[28]);
 }

  *
  * @pre -2^32 < f < 2^32
- * @pre precision < TENMAP_SIZE (== 8)
+ * @pre precision < TENMAP_SIZE (== 10)
  *
  * @param[in]   f           float value to print
  * @param[in]   precision   number of digits after decimal point
diff --git a/tests/unittests/tests-fmt/tests-fmt.c b/tests/unittests/tests-fmt/tests-fmt.c
index 75a647b8c7..a11a48e254 100644
--- a/tests/unittests/tests-fmt/tests-fmt.c
+++ b/tests/unittests/tests-fmt/tests-fmt.c
@@ -738,6 +738,15 @@ static void test_fmt_s32_dfp(void)
     out[act_len] = '\0';
     TEST_ASSERT_EQUAL_STRING("-0.0000001", (char *)out);
 
+    val = -1;
+    fpp = -24;
+    len = fmt_s32_dfp(NULL, val, fpp);
+    TEST_ASSERT_EQUAL_INT(3 - fpp, len);
+    act_len = fmt_s32_dfp(out, val, fpp);
+    TEST_ASSERT_EQUAL_INT(3 - fpp, act_len);
+    out[act_len] = '\0';
+    TEST_ASSERT_EQUAL_STRING("-0.000000000000000000000001", (char *)out);
+
     /* check that the buffer was not overflowed */
     TEST_ASSERT_EQUAL_STRING("z", &out[28]);
 }
```
</details>

**Comment by kaspar030** [comment]
> I guess some documentation and tests should be updated in this case:

would you mind uploading the patch as gist? I tried copy&pasing it, seems malformed.

**Comment by MrKevinWeiss** [comment]
[here](https://gist.githubusercontent.com/MrKevinWeiss/bf84a4ca4062d34f80aaeac798596da3/raw/0f537ce3a529d62d664950b17fe9f657bd294a31/%252317106.patch), ya it looked like some copy and paste issues.

**Comment by MrKevinWeiss** [comment]
cough cough @kaspar030

**Comment by kaspar030** [comment]
> cough cough @kaspar030

oh, forgot about this, thanks. I think I had already integrated your changes,  I rebased & squashed & pushed just now.
BTW, I'm about to remove the "attention" thing, as that is needed for *all* the fmt functions. (having it only for one might give the impression that the other functions somehow handle this better).

**Comment by kaspar030** [comment]
I've added some docs regarding `out` to the module level docs.

**Comment by MrKevinWeiss** [comment]
Can you directly squash (save a testing cycle)

**Review by MrKevinWeiss — APPROVED** [review]
ACK!

**Comment by fjmolinas** [comment]
> For some reason, this commit is the reason why xtimer_now64_continuity is failing on arduino-uno. The current output is:

Hmm git bisect seems to have lied to me.

**Comment by MrKevinWeiss** [comment]
flakey tests make life hard...

**Pull request merged**
