### PR TITLE
[treewide] lora: use int16_t for RSSI value

### LINKED ISSUE #17451: sx127x: wrong RSSI values
#### Description
Seems that the RSSI values reported in netdev_lora_rx_info_t structure are incorrect. The sx127x driver is definitely affected, and other LoRa modem drivers (sx126x and STM32WL55) could be broken too (though I can't test them now).

#### Steps to reproduce the issue
Receive a packet on the border of modem sensitivity and read the value in rssi field of packet info.

#### Expected results
The actual RSSI should be something like -120 to -130 dBm, similar to receiver sensitivity in the datasheet.

#### Actual results
The value in the rssi field of netdev_lora_rx_info_t will be a large positive (120-130).

#### Versions
All RIOT versions and all sane build environments.

The reason is that rssi field of netdev_lora_rx_info_t (as defined in drivers/include/net/netdev/lora.h) is a uint8_t, but it must contain the values in the range from, possibly, -140 to something like -10 to 10, maybe (a very strong signal, possibly the receiver and transmitter are in close proximity). In the actual device, the RSSI is indicated by a single-byte value (unsigned), and the offset is specified in the documentation. The calculations in the driver (lines 150-177) of sx127x_netdev.c use int16_t for RSSI value, and probably the simplest solution could be changing the type of rssi member in netdev_lora_rx_info_t to int16_t (probably int8_t would be unsuitable).

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
The RSSI values reported by LoRa transceiver can be less than -127.
Therefore, `int8_t` is not enough. This commit defines the RSSI of
`netdev_lora_rx_info` as `int16_t` and adapt the drivers accordingly
(sx126x, sx127x).

BTW, the `sx126x` was writing an `int16_t` into an `int8_t`. :man_shrugging:. It's indirectly fixed by this commit.

### Testing procedure
- Check that the RSSI values reported by the LoRa radios (sx126x, sx127x) are right (negative values, starting from around -140). Use `tests/driver_sx127x` and `test/drivers_sx126x` for that.

### Issues/PRs references
Fixes #17451

### CODE REVIEW

**Comment by aabadie** [comment]
The netopt `NETOPT_RSSI` documentation must be updated (it's still mentioned `int8_t`):

https://github.com/RIOT-OS/RIOT/blob/73ccd1e2e721bee38f958f8906ac32e5e1fceb0c/sys/include/net/netopt.h#L766-L775

There's also a use of that option in other places:
```
$ git grep NETOPT_RSSI
drivers/atwinc15x0/atwinc15x0_netdev.c:        case NETOPT_RSSI:
drivers/sx126x/sx126x_netdev.c:    case NETOPT_RSSI:
drivers/sx127x/sx127x_netdev.c:    case NETOPT_RSSI:
pkg/semtech-loramac/contrib/semtech_loramac_radio.c:    loramac_netdev_ptr->driver->get(loramac_netdev_ptr, NETOPT_RSSI, &rssi, sizeof(int8_t));
sys/include/net/netopt.h:    NETOPT_RSSI,
sys/net/crosslayer/netopt/netopt.c:    [NETOPT_RSSI]                  = "NETOPT_RSSI",
sys/shell/commands/sc_gnrc_netif.c:    res = netif_get_opt(iface, NETOPT_RSSI, 0, &i8, sizeof(i8));
```
The use in `sc_gnrc_netif.c` at least needs an update. I don't know if it can be turned into an `int16_t` in atwinc15x0_netdev.c (probably yes)

**Comment by jia200x** [comment]
Done!

**Comment by aabadie** [comment]
`drivers/atwinc15x0/atwinc15x0_netdev.c` still needs to be adapted, maybe in a separate commit, since it's not lora specific (but wifi)

**Comment by jia200x** [comment]
Thanks for pointing that out. I just pushed again

**Comment by jia200x** [comment]
ping @aabadie

**Comment by aabadie** [comment]
`examples/default` fails to build on b-l072z-lrwan1:

```
/work/riot/RIOT/sys/shell/commands/sc_gnrc_netif.c: In function '_netif_list':
/work/riot/RIOT/sys/shell/commands/sc_gnrc_netif.c:610:12: error: unused variable 'i8' [-Werror=unused-variable]
  610 |     int8_t i8;
      |            ^~
cc1: all warnings being treated as errors
```

see https://github.com/RIOT-OS/RIOT/blob/ace880dddf7e70e95fff2269e380def1db0c8541/sys/shell/commands/sc_gnrc_netif.c#L610

**Comment by jia200x** [comment]
The `int8_t` is not used anymore so I just removed it. `examples/default` compiles now.

**Comment by aabadie** [comment]
I'm currently testing this PR on iot-lab between 2 b-l073z-lrwan1 boards (so with sx1276 radio) and the bug is fixed when using the `tests/driver_sx127x` application, on receive of a packet the RSSI printed is more realistic:

- **master**

```
Data reception started
{Payload: "test" (5 bytes), RSSI: 193, SNR: 6, TOA: 37}
```

- **this PR**:

```
> Data reception started
{Payload: "test" (5 bytes), RSSI: -63, SNR: 6, TOA: 37}
```

I also tried `examples/defaut` but there the RSSI value is still invalid:

- **master**:

```
> ifconfig 3 set state rx
ifconfig 3 set state rx
success: set state of interface 3 to RX
> PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  74  65  73  74
~~ SNIP  1 - size:   8 byte, type: NETTYPE_NETIF (-1)
if_pid: 3  rssi: -32768  lqi: 0
flags: 0x0
src_l2addr: (nil)
dst_l2addr: (nil)
~~ PKT    -  2 snips, total size:  12 byte
```

- **this PR**

```
> ifconfig 3 set state rx
ifconfig 3 set state rx
success: set state of interface 3 to RX
> PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  74  65  73  74
~~ SNIP  1 - size:   8 byte, type: NETTYPE_NETIF (-1)
if_pid: 3  rssi: -32768  lqi: 0
flags: 0x0
src_l2addr: (nil)
dst_l2addr: (nil)
~~ PKT    -  2 snips, total size:  12 byte
```

rssi is the lower limit of `int16_t`. I haven't checked with `tests/pkg_semtech-loramac` yet, but will do now.

**Comment by aabadie** [comment]
I made a few basic tests with `tests/pkg_semtech-loramac` and all worked as expected.

**Comment by aabadie** [comment]
After digging a little more, the "problem" with `examples/default` is unrelated, RSSI is not part of the gnrc netfi header with LoRa raw packets.

**Comment by aabadie** [comment]
It's labelled as a bug, so backporting is needed.

**Comment by jia200x** [comment]
done!

**Comment by aabadie** [comment]
Please provide a backport to 2022.01-branch.

**Comment by jia200x** [comment]
backport provided in #17527

**Pull request merged**
