### PR TITLE
cpu/samd21: increase default stack size

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
I propose to merge this as a hot-fix for the release even though the value is probably not optimal.
We can provide a better solution when the discussion #2228 has come up with something more useful later.

### CODE REVIEW

**Comment by bapclenet** [comment]
@OlegHahm, just to let you know that the values you suggested in your first commit doesn't work. we're trying to optimize stacks but we're stuck when running "init n"
When do you think the network will be totally refactored?

**Comment by wiredsource** [comment]
@OlegHahm 
Our experience tells us that it need more default stack... We are running with 1536

**Comment by LudwigOrtmann** [comment]
@wiredsource how much stack size do you have left in `examples/default`?

**Comment by saurabh984** [comment]
@wiredsource @LudwigOrtmann I noticed quite a few changes in recent CMSIS updates from Atmel for SAM R21.

I think RIOT uses CMSIS released with ASF 3.16.x version. Most recent version of ASF is 3.21.0

Should this be updated? Or is it not required?!

Also, any update on the ADC implementation @wiredsource :wink:

**Comment by OlegHahm** [comment]
@saurabh984, how is this related to this PR and which part of CMSIS are you talking about?

**Pull request merged**
