### PR TITLE
dist: iotlab-testbed: add possibility to exclude nodes

### PR DESCRIPTION
**Pull request by cgundogan**
This PR adds a new variable called `IOTLAB_EXCLUDE_NODES`. This variable will be used to exclude
certain nodes from the flash and/or reset target.

Example:
```
IOTLAB_USER=<user> IOTLAB_EXCLUDE_NODES=11+15 BOARD=iotlab-m3 make iotlab-reset
iotlab-term -I ../../dist/testbed-support
```
This will reset all nodes that are used in the current experiment, but not node 11 and node 15.
`iotlab-flash` works the same.

This exclusion is particularly helpful when sniffers are used for certain nodes that should not be reset/flashed with another application.

### CODE REVIEW

**Comment by BytesGalore** [comment]
nice one, I will take a look.
This sounds really helpful for simulating node churn and dynamic topology changes.

**Comment by cgundogan** [comment]
ping @OlegHahm

**Comment by cgundogan** [comment]
@OlegHahm I believe you ACKed this offline yesterday. Could you verify?

**Comment by cgundogan** [comment]
@OlegHahm updated the readme to be a bit more verbose regarding the new variable (amended)

**Comment by OlegHahm** [comment]
ACK.

**Comment by BytesGalore** [comment]
tested it, ACK too

**Pull request merged**
