### PR TITLE
ci: always run on-hardware tests

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Currently, some tests are run by CI on real hardware, if the label "CI: run tests" is set.
This PR reverses the logic, so the tests are run unless "CI: skip tests" is set.

Test caching reduces the build time overhead to less than a minute for most PRs. For more intrusive changes, it is more, but also more likely to find bugs.

### CODE REVIEW

**Comment by miri64** [comment]
In general :clap:, but this reminds me that at one point we wanted a feature in Murdock (similar to travis), where a `[skip]` in the commit message would skip the commit for building.

**Comment by miri64** [comment]
Any more comments on this?

**Comment by fjmolinas** [comment]
> In general :clap:, but this reminds me that at one point we wanted a feature in Murdock (similar to travis), where a `[skip]` in the commit message would skip the commit for building.

+1, the skip feature would also be good, but it another PR (and relates to murdock itself)

**Comment by fjmolinas** [comment]
https://github.com/RIOT-OS/RIOT/pull/12847 got me thinking on this one again I think this should really be the default. Personally I often forget to tick `CI: run-tests`, or don't tick it before `CI:run-build`, I would rather have to think of adding `CI: dont-run-tests` and If I forget a label for that to be the one.

**Comment by kaspar030** [comment]
IMO, at the moment the tests are too flakey and too slow.

**Pull request closed without merging**
