### PR TITLE
boards/{bluepill*,blackpill*}: rename and improve doc

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- renamed:
    - `bluepill` --> `bluepill-stm32f103c8`
    - `bluepill-128kib` --> `bluepill-stm32f103cb`
    - `blackpill` --> `blackpill-stm32f103c8`
    - `blackpill-128kib` --> `blackpill-stm32f103cb`
- doc:
    - added link to corresponding hardware page on the STM32-base
      project
    - added picture

### Testing procedure

- check the documenation
- `make flash` and `make term` should still work for Bluepill and Blackpill boards (with updated values for `BOARD`, though)

### Issues/PRs references

None

### CODE REVIEW

**Comment by benpicco** [comment]
`Makefile.ci` will need an update too

**Comment by benpicco** [comment]
Sorry, needs a rebase (or better re-run of the `sed` command) but I agree with this PR, this is much more consistent.

**Review by benpicco — APPROVED** [review]

**Comment by maribu** [comment]
Looks like the static test checking that a board has no impossible dependencies did pay off :)

**Comment by aabadie** [comment]
The doc check is still failing :)

**Comment by maribu** [comment]
All green now. If this can be merged during soft feature-freeze, this would be the time :)

**Comment by kaspar030** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Comment by maribu** [comment]
A number of new entries to `Makefile.ci` files have been merged to `master`, so I had to rebase in order to update them with `s/bluepill-128kib/bluepill-stm32f103cb/` and so on.

In addition, I apparently forgot to update the KConfig board name. Both should hopefully be fixed now. Murdock will know :)

**Comment by aabadie** [comment]
bors merge

**Comment by maribu** [comment]
bors try

**Comment by maribu** [comment]
bors try

**Comment by maribu** [comment]
Build succeeded, but a debugging log was sneaked in that I still had to delete. It should now be ready to merge.

**Review by benpicco — COMMENTED** [review]
bors merge

**Comment by maribu** [comment]
Hooray! Thx for the patience, this took quite a bit longer than expected :-/

**Pull request merged**
