### PR TITLE
drivers/stmpe811: fix initialization if callback function parameter is NULL

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the `stmpe811` driver initialization if the callback function parameter `cb` is `NULL. This might be the case for example if the application uses the touch device in polling mode.

If the interrupt pin is initialized if the callback function parameter `cb` is `NULL`, the driver crashes the first time an interrupt is triggered. Therefore, the INT pin must be initialized only if also the callback function parameter `cb` is not `NULL`.

To be able to test the polling mode, this PR also includes a change of the `tests/drivers/stmpe811` application which introduces the environment variables `STMPE811_POLLING_MODE` `STMPE811_POLLING_PERIOD` and in the makefile.

### Testing procedure

1. Use a `stm32f429i-disc1` board and test it in polling mode:
   ```
   STMPE811_POLLING_MODE=1 BOARD=stm32f429i-disc1 make -C tests/drivers/stmpe811 flash term
   ```
   It should work as expected.
   ```
   main(): This is RIOT! (Version: 2023.10-devel-119-g26e7a-drivers/stmpe811_fix_cb_null)
   STMPE811 test application
   +------------Initializing------------+
   Initialization successful
   Pressed!
   X: 113, Y:135
   X: 113, Y:135
   X: 113, Y:136
   Released!
   ```

2. Checkout master branch and cerry-pick commit 691a5e6308426ddc685e5a2c297238529211c258. The test application `tests/drivers/stmpe811` will crash once a touch event occur:
   ```
   main(): This is RIOT! (Version: 2023.10-devel-117-g91441)
   STMPE811 test application
   +------------Initializing------------+
   Initialization successful
   Stack pointer corrupted, reset to top of stack
   FSR/FAR:
    CFSR: 0x00020000
    HFSR: 0x40000000
    DFSR: 0x00000008
    AFSR: 0x00000000
   Misc
   EXC_RET: 0xfffffff1
   *** RIOT kernel panic:
   HARD FAULT HANDLER
   ```

### Issues/PRs references

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by gschorcht** [comment]
@maribu Thank you for reviewing so promptly.

While modifying `tests/drivers/touch_dev` in PR #19882, I realized that at least the device interrupts have to be configured in any case, even if the interrupt pin is not initialized because of the parameter `cb`. The reason is that the the touch device API first initializes the device with `NULL` for the callback function parameter `cb` and later it just initializes the interrupt pin. Configuring the device interrupts in any case isn't a problem even if the interrupt pin is not used at all since the interrupt status is cleared on every read operation.

Therefore, I pushed commit 3e35dba5c5a9d1494172f851e792e3aaa13c82b6 with a small additional change. I could squash it with commit 16abf022c939c3d1b86afa422111e467450f15fd if you prefer.

**Comment by maribu** [comment]
> I could squash it with commit https://github.com/RIOT-OS/RIOT/commit/16abf022c939c3d1b86afa422111e467450f15fd if you prefer.

as you prefer. The ACK remains valid in either case

**Comment by gschorcht** [comment]
> > I could squash it with commit [16abf02](https://github.com/RIOT-OS/RIOT/commit/16abf022c939c3d1b86afa422111e467450f15fd) if you prefer.
> 
> as you prefer. The ACK remains valid in either case

I squashed it because it makes the change more clear if is in one commit instead of two commits.

**Comment by maribu** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks for reviewing and mergin.

**Pull request merged**
