### PR TITLE
core: Fix/refactor function naming in core/incude/irq.h

### PR DESCRIPTION
**Pull request by DipSwitch**
Fixes: #5041

I did the refactor by hand because the code is kind if critical and I don't trust oneliners with with :)

### CODE REVIEW

**Comment by DipSwitch** [comment]
But maybe the function `irq_in` should be refactored again to `irq_is_in` since this is more expressive.

I know just took removed the arch from `irq_arch_in`

**Comment by haukepetersen** [comment]
nice one, this was long overdue! And I agree, I also like `irq_is_in` better.

**Comment by DipSwitch** [comment]
Done :)

**Comment by LudwigKnuepfer** [comment]
> I did the refactor by hand because the code is kind if critical and I don't trust oneliners with with :)

WTF! Next time, do the oneliner and verify the diff ;-)

**Comment by DipSwitch** [comment]
At least now I know for sure there aren't any errors and I didn't miss anything =)

**Comment by DipSwitch** [comment]
Famous last words :')

**Comment by OlegHahm** [comment]
Apparently you introduced some whitespaces.

**Comment by DipSwitch** [comment]
This is because it's a patch file with `\r\n` line endings, I guess I can't fix those :p

org

**Comment by DipSwitch** [comment]
And new for completeness:

screenshot from 2016-03-20 10-18-01

**Comment by DipSwitch** [comment]
They where already there:

    diff --git a/pkg/tlsf/patch.txt b/pkg/tlsf/patch.txt
    index f548684..2da61ae 100644
    --- a/pkg/tlsf/patch.txt
    +++ b/pkg/tlsf/patch.txt
    @@ -23 +23 @@ index 0000000..cb16af8
    -+    unsigned old_state = disableIRQ();^M
    ++    unsigned old_state = irq_disable();^M
    @@ -25 +25 @@ index 0000000..cb16af8
    -+    restoreIRQ(old_state);^M
    ++    irq_restore(old_state);^M
    @@ -40 +40 @@ index 0000000..cb16af8
    -+    unsigned old_state = disableIRQ();^M
    ++    unsigned old_state = irq_disable();^M
    @@ -42 +42 @@ index 0000000..cb16af8
    -+    restoreIRQ(old_state);^M
    ++    irq_restore(old_state);^M
    @@ -48 +48 @@ index 0000000..cb16af8
    -+    unsigned old_state = disableIRQ();^M
    ++    unsigned old_state = irq_disable();^M
    @@ -50 +50 @@ index 0000000..cb16af8
    -+    restoreIRQ(old_state);^M
    ++    irq_restore(old_state);^M
    @@ -56 +56 @@ index 0000000..cb16af8
    -+    unsigned old_state = disableIRQ();^M
    ++    unsigned old_state = irq_disable();^M
    @@ -58 +58 @@ index 0000000..cb16af8
    -+    restoreIRQ(old_state);^M
    ++    irq_restore(old_state);^M

**Comment by OlegHahm** [comment]
Hm, damn it. Anyway, can you rebase to master to fix the oonf problem?

**Comment by DipSwitch** [comment]
Done

**Comment by DipSwitch** [comment]
All Murdock complains about are the white space errors which where already there, can I get an ACK?

**Comment by OlegHahm** [comment]
Wow, just realized that `boards/avsextrem/drivers/avsextrem-smb380.c` contains 132 calls of enabling or disabling IRQs... Someone should take a look in a separate PR.

**Comment by OlegHahm** [comment]
ACK

**Comment by DipSwitch** [comment]
Then lets clean up the API

**Comment by DipSwitch** [comment]
@OlegHahm It are actually 33 disables and 33 restores but I created an issue so it won't be forgotten :)

**Pull request merged**
