### PR TITLE
cc3200: Initial support

### PR DESCRIPTION
**Pull request by Ameya22**
1. CC3200
Added board support for CC3200. 
Changed Core, Boards, CPU, Examples, toolchain, CPU/CC3200 to support board.
Added UDP server example for testing

### CODE REVIEW

**Comment by miri64** [comment]
Hello @Ameya22 and welcome to the RIOT community. First of all, thank you for your contribution, but consider the following:

1. It looks like you are importing a lot of external code. Consider providing it as a [`pkg`](http://doc.riot-os.org/group__pkg.html) instead.
2. You are importing an example that uses a socket-like API. Consider porting the [`sock` API](http://doc.riot-os.org/group__net__sock.html) for the cc3200. It has the advantage, that it is
     1. more light-weight than the traditional socket API
     2. makes other examples run with the cc3200 out-of-the-box without any porting effort on behalf of the users
     3. it's POSIX-socket-wrapper is 100% compatible with our filesystem layer => no conflicts if both of them are used.

Also, consider dividing the PR in multiple PRs (e.g., one for the CPU, one for the board, one for the `pkg`, one for the `sock`-port). This usually speeds-up the review process greatly, since reviewers tend to be overwhelmed by >80000 lines of code ;-)

**Comment by miri64** [comment]
Ping @Ameya22?

**Comment by Ameya22** [comment]
Hi miri64, 
I have added separate PR #7472 & #7473 
The thing is CC3200 only supports IPv4. Working on the server example using lwip network stack for the socket API. You can close this PR. I will update you soon.

**Comment by smlng** [comment]
closing, replaced by #7472 and #7473

**Pull request closed without merging**
