### PR TITLE
cpu/atmega2560: gpio - fixes a bug where gpio_* behaves incorrect if …

### LINKED ISSUE #4046: cpu/atmega2560: gpio_* behaves incorrectly for PORTn addresses > 0xFF
Due to truncation of return value in _ddr_addr and _pin_addr in cpu/atmega2560/periph/gpio.c

### PR DESCRIPTION
**Pull request by danielamkaer**
…PORTn address > 0xFF

fixes #4046

### CODE REVIEW

**Comment by kaspar030** [comment]
Looks good to me. Can't test until tomorrow the earliest, though.

**Comment by gebart** [comment]
@danielamkaer nice work polishing up the atmega drivers!

**Comment by PeterKietzmann** [comment]
@ReneHerthel can you please confirm that?

**Comment by ReneHerthel** [comment]
@danielamkaer 

I see you choose uint16_t because it returns values up to 0xFFFF instead of 0xFF.
The basic port addresses from H to L are in the range of uint16_t, it seems to be logical.

Can you please specify which incorrect behavior you mean?

**Comment by danielamkaer** [comment]
I just mean that it doesn't work, and it may control a different port than you expected because of it.

**Comment by PeterKietzmann** [comment]
@ReneHerthel please confirm by testing and explaining your results. You are one of the elected persons with an arduino-mega2560 board :-)

**Comment by ReneHerthel** [comment]
@danielamkaer Did the strange behavior with controlling different ports disappaer for you with this changes?

When I'm doing the following as example...

>init_int PORTE 5 1
2015-10-24 15:58:05,009 - INFO # > init_int PORTE 5 1
2015-10-24 15:58:05,066 - INFO # PORT_0.05 initialized successful as external interrupt
init_out PORTA 0
2015-10-24 15:58:10,719 - INFO # > init_out PORTA 0
2015-10-24 15:58:10,760 - INFO # PORT_0.0 initialized successful as output
inti_out PORTL 0
2015-10-24 15:58:17,629 - INFO # > inti_out PORTL 0
2015-10-24 15:58:17,666 - INFO # shell: command not found: inti_out
read PORTA 0
2015-10-24 15:58:23,417 - INFO # > read PORTA 0
2015-10-24 15:58:23,434 - INFO # PORT_0.00 is LOW
read PORTL 0
2015-10-24 15:58:26,752 - INFO # > read PORTL 0
2015-10-24 15:58:26,772 - INFO # PORT_0.00 is LOW
toggle PORTL 0
2015-10-24 15:58:30,955 - INFO # > toggle PORTL 0
2015-10-24 15:58:30,991 - INFO # INT: external interrupt from pin 5
read PORTA 0
2015-10-24 15:58:34,227 - INFO # > read PORTA 0
2015-10-24 15:58:34,244 - INFO # PORT_0.00 is HIGH

..PA0 is low, but when I toggle PL0, it toggles PA0 too.

Did I miss something?

**Comment by PeterKietzmann** [comment]
@ReneHerthel that is independent from the change of this PR. ACK from my side

**Pull request merged**
