### PR TITLE
pkg/lvgl: bump to v8.3.0

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

As the title says.

The patch added in #17681 is removed since this release contains the same change.
The test applications work on adafruit-clue and native (using lv_drivers). I don't have a board for testing the touch variant but this also works on native.

I noticed a code size increase of 3KB.

### Testing procedure

- Green Murdock
- Some on-board testing is partially done

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
Just tested this PR with success on stm32f429i-disc1.

**Comment by aabadie** [comment]
This one has unrelated build failures even though it's rebased on latest master. Are there any problems with CI workers (last one was on riotbuild) ?

**Comment by aabadie** [comment]
> Are there any problems with CI workers (last one was on riotbuild) ?

Failures are not bound to a worker so it seems to be more general. I'll retrigger without build since the failures are all unrelated.

**Comment by chrysn** [comment]
Looks good to me, but we'll need to find how this breaks builds. Started another CI run for inspection.

**Comment by aabadie** [comment]
This is finally green :)

**Review by benpicco — APPROVED** [review]

**Pull request merged**
