### PR TITLE
boards: fix ztimer adjust values for arduino-mega2560 and z1

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This fixes the values.

### Testing procedure

Simply run `tests/ztimer_overhead`

```
BUILD_IN_DOCKER=1  BOARD=z1 make -C tests/ztimer_overhead/ flash test -j
main(): This is RIOT! (Version: 2022.04-devel-905-g6ce15-pr_ztimer_adjust_correcitons)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 99
    ZTIMER_USEC->adjust_sleep = 100
ZTIMER_USEC auto_adjust params cleared
zitmer_overhead_set...
min=99 max=100 avg_diff=99
zitmer_overhead_sleep...
min=100 max=101 avg_diff=100
ZTIMER_USEC adjust params for z1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    99
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  100
```

```
BUILD_IN_DOCKER=1  BOARD=arduino-mega2560 make -C tests/ztimer_overhead/ flash test -j
main(): This is RIOT! (Version: 2022.04-devel-905-g6ce15-pr_ztimer_adjust_correcitons)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 132
    ZTIMER_USEC->adjust_sleep = 120
ZTIMER_USEC auto_adjust params cleared
zitmer_overhead_set...
min=132 max=136 avg_diff=133
zitmer_overhead_sleep...
min=120 max=124 avg_diff=123
ZTIMER_USEC adjust params for arduino-mega2560:
    CONFIG_ZTIMER_USEC_ADJUST_SET    132
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  120
```

### CODE REVIEW

**Comment by fjmolinas** [comment]
Thanks for the review!

**Comment by fjmolinas** [comment]
> I really don't like that this is required, but at least now the values are more accurate.

What do you mean? You don't like the adjust values?

**Comment by benpicco** [comment]
No I don’t like per-board calibration values that realistically will not be set in most cases.

**Comment by fjmolinas** [comment]
> No I don’t like per-board calibration values that realistically will not be set in most cases.

There is this `auto-adjust` module, but that has some impact on start-up which is why we disabled it by default

**Pull request merged**
