### PR TITLE
dist/tools/ci: toolchain versions: Fix heading formatting

### PR DESCRIPTION
**Pull request by gebart**
Changes the heading formatting for the print toolchain versions script.

https://github.com/RIOT-OS/RIOT/pull/6390#issuecomment-273718671

### CODE REVIEW

**Comment by gebart** [comment]
there's something wrong with the output.. The last line (avr-libc version) is not shown in the script output.

**Comment by cgundogan** [comment]
>there's something wrong with the output.. The last line (avr-libc version) is not shown in the script output.

provided fix in https://github.com/gebart/RIOT/pull/14

**Comment by cgundogan** [comment]
cf. https://github.com/gebart/RIOT/pull/14#issuecomment-273771418

I wasn't aware that echo could throw an error if the output starts wit ha `-`? I tried it in bash/zsh and it works:
```
OUT="- test"; echo "$OUT"
```
has the desired effect.

**Comment by gebart** [comment]
updated with suggestions from @cgundogan

**Comment by cgundogan** [comment]
>I wasn't aware ...

OK after reading up on the topic I agree on using rintf in this case.

**Comment by gebart** [comment]
@cgundogan echo behaves differently depending on what platform you are running on.
http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo

**Pull request merged**
