### PR TITLE
boards: stk3200: add support

### PR DESCRIPTION
**Pull request by basilfx**
### Contribution description

This PR add supports for the Silicon Labs [STK3200](https://github.com/basilfx/EFM2RIOT/blob/master/dist/doc/STK3200.md).

The files are very similar to the SLTB001a already supported

### Issues/PRs references

Made possible by #8139.

### CODE REVIEW

**Comment by haukepetersen** [comment]
One thing I just noticed: when adding all the SiLabs boards, it seems to me that there are some parts of the board configuration that basically pop up in each of the PRs (e.g. LED macros, feature definitions, clock config?, more?). I think it would make sense to factor those parts out into a shared board folder, e.g. something like `boards/common/silabs_devkit` or similar. 

You have probably the better overview on the similarities of all those boards, so do you think this is a sensible thing to do?

**Comment by basilfx** [comment]
Currently, I only think the common features (or, at least very common) are:

* LEDs
* Advanced energy module (or, at least the code to enable the core features)
* Flash scripts

What isn't (or what would cost more preprocessor lines):

* Xtimer: I am working on the 32 bit timers supported in the newer ones (different config)
* Peripherals: pin numbers changes
* Clock configuration: the STK3200 uses different configuration, just like ikea-tradfri

If I would generalize it, it is easier to open one PR for all the boards IMHO. Would that be OK? Or could we first accept the PRs (than we don't get a long list of vendor files in the commits)?

(p.s. the build error is related to a bug in pwm.c of the EFM32 code).

**Comment by basilfx** [comment]
Closing this one for a common approach that I soon will PR.

**Comment by basilfx** [comment]
Second attempt in #8520. 

I tried to generalize as much as possible, but limited it to board controller, AEM and PIC (SLTB001a only).

**Pull request closed without merging**
