### PR TITLE
WIP: Add package for mbed TLS

### PR DESCRIPTION
**Pull request by mtausig**
Builds fine so far, but still needs some testing and some work on the configuration options.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Oops, this one slipped through so far. What's the state?

**Comment by mtausig** [comment]
Nothing new, I'm afraid. I don't have enough time for it, at the moment.

**Comment by kYc0o** [comment]
Some news here?

**Comment by mtausig** [comment]
I'll close this for the time being. I will reopen it, once I will find the time to properly do this.

**Pull request closed without merging**
