### PR TITLE
pkg: add qDSA package

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR adds a package for qDSA, a small, fast and secure digital signature library, including simple unittests.

The original code has been RIOT'ized and stored [here](https://github.com/RIOT-OS/qDSA).

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
Nice! tested successfully on SAMR21.

```
Debugger: ATMEL EDBG CMSIS-DAP ATML2127031800001921 01.1A.00FB (S)
Target: SAM R21G18
Erasing...  done.
Programming............................................................................................................ done.
Verification............................................................................................................ done.
/Users/emmanuel/Documents/work/CODING/RIOT/dist/tools/pyterm/pyterm -p "/dev/tty.usbmodem1411442" -b "115200"
No handlers could be found for logger "root"
2018-03-14 17:51:55,405 - INFO # Connect to serial port /dev/tty.usbmodem1411442
Welcome to pyterm!
Type '/exit' to exit.
2018-03-14 17:52:00,668 - INFO # main(): This is RIOT! (Version: 2018.04-devel-646-gba7b4-airboolfight.imp.fu-berlin.de-qdsa)
2018-03-14 17:52:01,103 - INFO # .
2018-03-14 17:52:01,105 - INFO # OK (1 tests)
```

**Comment by kaspar030** [comment]
Please test again, added some last-minute fixes.

**Comment by emmanuelsearch** [comment]
mmmh now not working anymore, getting a hard fault + reboot

**Comment by emmanuelsearch** [comment]
and on Arduino mega I get:

```
2018-03-14 18:08:28,416 - INFO # main(): This is RIOT! (Version: 2018.04-devel-648-gf36d67-airboolfight.imp.fu-berlin.de-qdsa2)
2018-03-14 18:08:30,951 - INFO # .
2018-03-14 18:08:31,045 - INFO # qDSA_tests.test_qDSA_sign_verify (tests/unittests/tests-qDSA/tests-qDSA.c 59) exp 0 was 1
2018-03-14 18:08:31,046 - INFO # 
2018-03-14 18:08:31,066 - INFO # run 1 failures 1
```

**Comment by kaspar030** [comment]
I factored the random_bytes() change into #8782...

**Comment by emmanuelsearch** [comment]
#8782 was merged please rebase.

**Comment by kaspar030** [comment]
- rebased

**Comment by emmanuelsearch** [comment]
Works on SAMR21, but this is what I get on Arduino Mega:

```
2018-03-16 13:43:51,007 - INFO # main(): This is RIOT! (Version: 2018.04-devel-659-g567df7-airboolfight.imp.fu-berlin.de-qdsa)
2018-03-16 13:43:53,535 - INFO # .
2018-03-16 13:43:53,630 - INFO # qDSA_tests.test_qDSA_sign_verify (tests/unittests/tests-qDSA/tests-qDSA.c 59) exp 0 was 1
2018-03-16 13:43:53,634 - INFO # 
2018-03-16 13:43:53,749 - INFO # run 1 failures �!H�+���):
```

**Comment by emmanuelsearch** [comment]
Works like a charm now!

**Comment by emmanuelsearch** [comment]
Please squash!

**Pull request merged**
