### PR TITLE
periph/flashpage: remove deprecated flashpage_*_free functions

### PR DESCRIPTION
**Pull request by Ollrogge**
### Contribution description
With the 2022.04 release being out this PR removes the `flashpage_*_free` functions deprecated with #17860.

I reverted all the changes I introduced with #16972 except for be254d4125c24805cba06e6e7cbe7dbb3acc0a69 since I this was a kind of fix that is still valid in my opinion.

### Testing procedure

* `tests/periph_flashpage` 

### Issues/PRs references
#17860
#16972

### CODE REVIEW

**Comment by benpicco** [comment]
Those functions came in handy to get the current image with `riotboot_vfs_dump_rom()` in #17379 though

**Comment by Ollrogge** [comment]
> Those functions came in handy to get the current image with `riotboot_vfs_dump_rom()` in #17379 though

Well in this case the functions can stay since they now have a use case I guess. @chrysn do you have any thoughts on this ?

**Comment by chrysn** [comment]
If we need a way to tell which flash pages correspond to the text section, let's use that (introducing first_used / last_used, or just feed the relevant linker symbols through the mapped address to flash page conversion -- a bootloader needs to understand some section stuff anyway). These functions invite usage patterns that conflict between parts of an application, and should go.

**Comment by chrysn** [comment]
> I can change the functions to reflect this but it should be first_used / last_used based on the whole firmware not just the .text section right ?

That's really what whoever does the firmware dump needs to concern itself with (is it dumping firmware? or everything allocated by the linker? also pages used through the deprecated functions? or the full ROM?) -- another reason why I'd rather not have these functions used for that purpose.

**Comment by Ollrogge** [comment]
> > I can change the functions to reflect this but it should be first_used / last_used based on the whole firmware not just the .text section right ?
> 
> That's really what whoever does the firmware dump needs to concern itself with (is it dumping firmware? or everything allocated by the linker? also pages used through the deprecated functions? or the full ROM?) -- another reason why I'd rather not have these functions used for that purpose.

@benpicco what is your opinion?

**Comment by Ollrogge** [comment]
@benpicco @chrysn I don't care if the functions stay or get removed. You guys have to discuss & decide please.

**Comment by Teufelchen1** [comment]
@chrysn @benpicco ping! :angry: :hourglass_flowing_sand: 
The functions have been marked deprecated for years! Either, we move this forward or we de-deprecate them. The current state is not okay for me.

**Comment by Ollrogge** [comment]
@benpicco what is your call ? If you are fine with the functions being removed I will rebase.

**Comment by benpicco** [comment]
`flashpage_first_free()` was useful to dump the current firmware (to enable roll-back) in a single-slot design where the new firmware is stored on e.g. external flash.

But since that has not been merged and there is currently no use for this, I'm fine with dropping those functions.

I can re-introduce the function under a different name if the need for single-slot updates with external storage arises again.

**Comment by Ollrogge** [comment]
> ### Murdock results
> 
> ❌ [FAILED](https://ci.riot-os.org/details/4ce85d475eb046ebb7c36fad79ecad29)
> 
> [10c987e](https://github.com/RIOT-OS/RIOT/commit/10c987eb669d6b5134269e3b8675062927a82d2a) Revert "periph/flashpage: extend API"
> Success 	Failures 	Total 	Runtime
> 3710 	0 	9428 	04m:07s
> #### Artifacts

Idk why this failed ?

**Comment by Teufelchen1** [comment]
I think that's unrelated. We might have bug in the samr21-xpro timer implementation, maybe related to #10019

**Comment by Teufelchen1** [comment]
The problem was probably fixed in #20548.

**Comment by Ollrogge** [comment]
All green now :)

**Pull request merged**
