### PR TITLE
CDCACM: Add interface association descriptor before CDC ACM control interface descriptor

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This adds an interface association descriptor to the USBUS CDC ACM code. This should enable the Windows operating system (at least version 10) to correctly enumerate, detect and use the CDC ACM functionality in RIOT.

#### Background

Currently RIOT describes itself as a composite device to host computers. When this is used, WIndows uses interface association descriptors to detect logical interface collections on the device[1].

### Testing procedure

Flash the `tests/usbus_cdc_acm_stdio` test on a board, Windows should correctly detect the COM device and allow usage of said COM device.

More extensive test (as already done by @chrysn) would be to add the CDC ECM in different configurations and test that Windows does not enable the CDC ECM functionality, but does offer the COM functionality of the device.

(Linux and MacOS should still work just fine)

### Issues/PRs references

~~Depends on #12429~~ 

[1]: https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/support-for-interface-collections

### CODE REVIEW

**Comment by bergzand** [comment]
rebased, no longer waiting for other PR's

**Comment by dylad** [comment]
Here we go

**Comment by bergzand** [comment]
This broke support for me on Linux due to a claimed header length mismatch. Will open a PR to fix this asap. Not sure how this slipped through on bot my test and @dylad's test

**Comment by chrysn** [comment]
Aah, that's that. I was just about to start bisecting when I noticed
that mail.

For better googles:

    config 1 has an invalid descriptor of length 7, skipping remainder of the config                              
    config 1 interface 3 altsetting 1 has 0 endpoint descriptors, different from the interface descriptor's value: 2

**Pull request merged**
