### PR TITLE
nrfusb: Fix data stage handling of control writes

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

When writing the usbdev driver for the nrf52840, I forgot to implement code for the optional data stage of control write transfers. This PR adds the necessary code for handling the data from the data stage.

### Testing procedure

Probably best tested with the STDIO test from #11085. Without this PR the STDIO should fail to set up or take a long time to initialize. With this PR it should work again.

### Issues/PRs references

None

### CODE REVIEW

**Comment by bergzand** [comment]
> I don't think we _have_ to wait until someone tried this PR on every OS (I can also only test on Linux) - if it was broken before, it would probably be broken on other operating systems as well.

I'm not against this, but I think for usbdev peripherals it should be enough to test on one OS. It is very unlikely that only one of the three OS fails/succeeds as that would indicate a USB spec violation at a very low level.

At above USBUS level (CDC ECM, CDC ACM etc.) failures with different OS's become more likely as some require a specific flavor of optional features to correctly detect the function.

**Comment by bergzand** [comment]
On the other hand, Linux is far more lenient with USB spec violations from the device side, so maybe it is a good idea to test this change also on macOS :laughing:

**Comment by miri64** [comment]
@smlng could you try?

**Comment by benpicco** [comment]
I'm trying to run this on Windows (together with #12269) - it's more involved than I would have thought!
Windows does not simply bind a driver based on the class, but expects you to have a driver that matches the USB ID. There doesn't seem to be a generic CDC ACM driver.

After some google search I found [Silabs-CDC_Install.zip](https://www.silabs.com/content/usergenerated/asi/cloud/attachments/siliconlabs/en/community/mcu/32-bit/forum/_jcr_content/content/primary/qna/usb_cdc_and_virtualc-xz9d/i_think_if_you_updat-kSkx/Silabs-CDC_Install.zip). I selected the first VID/PID combination from the `.inf` file and compiled RIOT with that.

The driver binds to the device, I can connect to it with [hterm](http://www.der-hammer.info/terminal/), but send some data to it, I get no response.

I'm not sure if this is due to the sketchy driver or due to RIOT.

usb

On Linux everything works out of the box.

**Comment by benpicco** [comment]
Hm, when I run the Zephyr [cdc_acm](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/subsys/usb/cdc_acm) example on this board things work out of the box even on Windows.

[Termite](https://www.compuphase.com/software_termite.htm) seems to be working more reliably then hterm, but I only get output with Zephyr, not RIOT.

When I use the PID/VID from Zephyr (`2fe3:0001`) in RIOT, Windows will not bind the driver:
RIOT

With Zephyr and the same ID it looks like this:
Zephyr

**Comment by benpicco** [comment]
(Without this patch it's broken in the same manner, so no reason to block this PR because of that)

**Comment by miri64** [comment]
Then I say, let's merge this ;-)

**Comment by bergzand** [comment]
Thanks!

**Pull request merged**
