### PR TITLE
boards/saml21-based: model kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This models Kconfig for saml21-based boards:
- bastwan
- saml21-xpro
- samr30-xpro
- samr34-xpro
- yarm

It also changes the way sx127x drivers are modelled and models USB ACM CDC stdio.

### Testing procedure
- Check the Kconfig changes and modelling
- Green CI

### Issues/PRs references
Part of #16875

### CODE REVIEW

**Comment by dylad** [comment]
Overall looks good to me but Murdock isn't happy.

**Comment by leandrolanzieri** [comment]
> Overall looks good to me but Murdock isn't happy.

The sx127x test app configuration did not reflect the change in the Kconfig symbols, 667ca81 should fix this

**Comment by MrKevinWeiss** [comment]
Murdock is happy, please remove the extra commit!

**Comment by leandrolanzieri** [comment]
Done!

**Review by MrKevinWeiss — APPROVED** [review]
Testing worked it looks good, ACK!

**Comment by leandrolanzieri** [comment]
Thanks for the review!

**Pull request merged**
