### PR TITLE
tests/irq: migrate to testrunner

### PR DESCRIPTION
**Pull request by aabadie**
partially addresses #7871

### CODE REVIEW

**Comment by kYc0o** [comment]
?? Description? It's now a trend to make PRs without any comment?

**Comment by aabadie** [comment]
I thought the title of this PR was explicit enough.

**Comment by kYc0o** [comment]
🙄 ...

**Comment by aabadie** [comment]
Initial comment updated with a reference to the related issue. Hope this is fine now @kYc0o :smile:

**Comment by aabadie** [comment]
Then let's go !

**Pull request merged**
