### PR TITLE
gh-actions: release-tests: add filter input

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This way, the tests that shall be run can be determined using [`pytest -k` expressions][k]. E.g. `spec04 and task04` would only run task 4.4.

[k]: https://docs.pytest.org/en/stable/usage.html#specifying-tests-selecting-tests

### Testing procedure
See https://github.com/miri64/RIOT/actions/runs/807124859 for a run with the filter and https://github.com/miri64/RIOT/actions/runs/807138408 for a run without.

### Issues/PRs references
Unrelated, but had this idea for testing https://github.com/RIOT-OS/RIOT/pull/16430.

### CODE REVIEW

**Comment by miri64** [comment]
Either Github's yaml files or bash are a bit annoying about whitespaces so that's the reason why the parameter definitions look like they look like now... But it works now :-)

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by fjmolinas** [comment]
Please hit the button once green.

**Comment by miri64** [comment]
Thanks for the review!

**Pull request merged**
