### PR TITLE
doxygen: Clean up groups for msp430 and arm7

### PR DESCRIPTION
**Pull request by gebart**
Cleaning up some Doxygen groups in cpu/

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK

**Comment by gebart** [comment]
`__ARM_COMMON_H` was the include guard for two different files which hid some errors before, pushed a new commit which fixes building on pttu, avsextrem and msba2

**Comment by haukepetersen** [comment]
Seems like Travis failed unrelated, kicked it.

**Comment by OlegHahm** [comment]
Apparently didn't help.

**Comment by OlegHahm** [comment]
Fails are unrelated (libcoap repository being unreachable). Go!

**Pull request merged**
