### PR TITLE
gnrc_sixlowpan_iphc: set correct length for IPv6 header

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes issue discussed in [#3669 (comment)](https://github.com/RIOT-OS/RIOT/pull/3669#issuecomment-132921534)ff.

### CODE REVIEW

**Comment by cgundogan** [comment]
This PR makes ping work again for payload sizes that enforce fragmentation, like e.g. a ping with 200 bytes. Tested on the iotlab testbed w/ and w/o iphc.

@PeterKietzmann can you utilize your udp test program again with this patch?

**Comment by PeterKietzmann** [comment]
Yes, in 30-40 minutes

**Comment by cgundogan** [comment]
While testing this PR I found another misbehaviour, which seems to be unrelated to this PR.
Pinging on the testlab w/ and w/o iphc works for pings with payload `<=1999`. However, pings with payload `>=2000` result in a timeout. I have no idea why this magic number.. Can anyone reproduce?

**Comment by authmillenon** [comment]
You are sending quite some huge packets. With more then 20 fragments some are bound to get lost. How great was your sample size?

**Comment by cgundogan** [comment]
I am pinging with 10 samples right now. Does not work with a payload of `2000` (timeouts for every sample).  When I repeat this with a payload of `1999` I get `0%` packet loss

**Comment by OlegHahm** [comment]
@authmillenon, how big is the reassembly buffer?

**Comment by authmillenon** [comment]
> @authmillenon, how big is the reassembly buffer?

It has space to reassemble up to 4 datagrams. The datagrams themselves are stored in the packet buffer.

**Comment by authmillenon** [comment]
Might be, that 2000 makes the packet buffer full ;-)

**Comment by authmillenon** [comment]
@cgundogan have you tried resizing the packet buffer with `CFLAGS=-DGNRC_PKTBUF_SIZE=<n>` where n is a lot bigger than 6k? (needs a clean first of course)

**Comment by cgundogan** [comment]
`CFLAGS=-DGNRC_PKTBUF_SIZE=12288 IOTLAB_USER=X IOTLAB_NODES=6 IOTLAB_EXP_NAME=ping_test IOTLAB_DURATION=30 BOARD=iotlab-m3 make -B clean all iotlab-exp -I ../../dist/testbed-support`

ping still times out for payload sizes `>=2000`

**Comment by authmillenon** [comment]
Open an issue. Will look into it, when I find time for it (I think it is unrelated to this issue).

**Comment by authmillenon** [comment]
This PR is still missing an ACK however ;-) @PeterKietzmann?

**Comment by authmillenon** [comment]
See #3672

**Comment by PeterKietzmann** [comment]
Maybe we can generate one ACK from two half ACKs. I didn't look at the code but the problems I stated in #3669 disappeared with this PR. I think that is half an ACK ;-)

**Comment by cgundogan** [comment]
So, I tested manually on the testbed and @PeterKietzmann's udp test program also approves. Ah and travis is also happy => GO

**Pull request merged**
