### PR TITLE
tests/ps_schedstatistics: fix test on AVR + improve Python test script

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is an attempt to fix the `tests/ps_schedstatistics` on AVR by simply increasing the XTIMER_BACKOFF value.

The PR also contains small cleanup in the Python test script:
- It ensures all lines are displayed before exiting the script
- It escapes the parenthesis that are not use for group regexp

### Testing procedure

The following command should succeed, also on AVR (where it fails on master):
```
make BOARD=<board of your choice> -C tests/ps_schedstatistics flash test
```

### Issues/PRs references

Tick one item in #12651

### CODE REVIEW

**Comment by maribu** [comment]
After thinking about it again, I think that @fjmolinas is right that it is better to should increase the value of `XTIMER_BACKOFF` on AVR. Ideally, depending on the CPU frequency. (This is currently still not running on 8 MHz AVRs.)

**Comment by maribu** [comment]
But on the other hand I see no reason to not just also decrease the load a bit to make the test more robust in case of small values of `XTIMER_BACKOFF`. (The value of `XTIMER_BACKOFF` for ATmegas can still be tweaked definitely.)

**Comment by maribu** [comment]
@fjmolinas: Could you double-check my reasoning above? To me, the value in `xtimer_usleep()` is pretty arbitrary anyway, so increasing it a bit (in addition to fixing `XTIMER_BACKOFF` later on) to make the test more robust makes sense.

**Comment by fjmolinas** [comment]
> @fjmolinas: Could you double-check my reasoning above? To me, the value in xtimer_usleep() is pretty arbitrary anyway, so increasing it a bit (in addition to fixing XTIMER_BACKOFF later on) to make the test more robust makes sense.

I have no issue with increasing the `sleep` time, it will have an impact on how the load is shared among threads, e.g. for `native` runtime for the threads goes down from ~1.4% to ~0.3%. But this is not in itself wrong, so +1.

> After thinking about it again, I think that @fjmolinas is right that it is better to should increase the value of XTIMER_BACKOFF on AVR. Ideally, depending on the CPU frequency. (This is currently still not running on 8 MHz AVRs.)

Here is where is get tricky, I'm not sure how `CPU` frequency and `TIMER` frequency interact here, and since there are other `xtimer` issues. I would need to take a closer look at `xtimer` again as well as all the resent PR's trying to fix `xtimer` issues, so I agree with not dealing with this here.

**Comment by aabadie** [comment]
The issue with Murdock is unrelated, I'm retriggering a simple build.

**Comment by fjmolinas** [comment]
> The issue with Murdock is unrelated, I'm retriggering a simple build.

Next time please post the build result in the PR, specially if triggering a simple build.

**Comment by aabadie** [comment]
Only `examples/suit_update` test was failing on samr21-xpro.

**Pull request merged**
