### PR TITLE
lpc11u34: Remove short name macros for GPIO modes

### PR DESCRIPTION
**Pull request by gebart**
... and replace with a GPIO bitmask generator macro instead.
The short macro names (IN, OUT, PD, PU, OD) in the original implementation were prone to collisions or other problems with user applications and library headers.

Bonus commit: fixes a tiny typo in the Kinetis periph_cpu.h in the documentation for the corresponding macro on that platform.

Untested on real hardware, I don't have any board with an LPC11u34.

### CODE REVIEW

**Comment by gebart** [comment]
ping @haukepetersen

**Comment by gebart** [comment]
This is a small changeset which should be mergable before the next release

**Comment by aabadie** [comment]
I don't have the hardware either. ping @haukepetersen ?

**Comment by gebart** [comment]
Ping @haukepetersen. 
Let's merge this before #7511

**Comment by haukepetersen** [comment]
and go

**Pull request merged**
