### PR TITLE
Pinoccio atmegarfr2

### PR DESCRIPTION
**Pull request by Josar**

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@Josar Welcome to RIOT and thanks for your contribution! Great to see support coming in for that board, the code seems a bit rough around the edges still and please see the above merge conflicts. Because of that I add the WIP label. When you think your code is in a ready to review shape, please ping me.

**Comment by thomaseichinger** [comment]
Also, I think it would make sense to try to combine the `at86rfr2` with the `at86rf2xx` module.

**Comment by aabadie** [comment]
@Josar, if you want to fix merge conflicts, consider using `git fetch origin && git rebase origin master` or `git pull --rebase origin master` (assuming `origin` is the upstream remote).
Otherwise you create merge commits in your branch, and we want to avoid that.

**Comment by aabadie** [comment]
ping @Josar, still working on this ?

**Comment by Josar** [comment]
pong @aabadie  yes

**Comment by aabadie** [comment]
ok great. Then I think you need to do some heavy rebase (and avoid merge commit as much as possible).

**Comment by Josar** [comment]
This can be closed as it will not be continued in favor of the jiminy board support.

**Pull request closed without merging**
