### PR TITLE
VERSION: add 2021.04 version file

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This PR adds the 2021.04 VERSION file.

### CODE REVIEW

**Comment by kaspar030** [comment]
Let's not merge this before https://github.com/RIOT-OS/RIOT/pull/16455!

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by kaspar030** [comment]
> kaspar030 dismissed fjmolinas’s stale review via 97dd467 2 minutes ago

Just for the vanity of having the proper commit order. :/

**Review by miri64 — APPROVED** [review]
ACK :-P

**Pull request merged**
