### PR TITLE
makefiles/tools/uf2conv.inc.mk: partial riotboot support 

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Follow up to #16276, by setting the correct base when converting some of the `riotboot/%` commands are now supported. The other ones require to flash a binary

### Testing procedure

- flash bootloader `BOARD=feather-nrf52840 make -C tests/riotboot riotboot/flash-bootloader`

- flash slot0 `BOARD=feather-nrf52840 make -C tests/riotboot riotboot/flash-slot0`

```
2021-04-13 14:29:17,349 # om slot 0
2021-04-13 14:29:17,350 # Image magic_number: 0x544f4952
2021-04-13 14:29:17,351 # Image Version: 0x60758e66
2021-04-13 14:29:17,352 # Image start address: 0x00002400
2021-04-13 14:29:17,353 # Header chksum: 0x0075b07d
2021-04-13 14:29:17,353 #
> dumpaddrs 0
2021-04-13 14:29:30,796 # slot 0: metadata: 0x2000 image: 0x00002400
2021-04-13 14:29:30,798 # slot 1: metadata: 0x7a800 image: 0x00000000
```

- flash slot1 `BOARD=feather-nrf52840 make -C tests/riotboot riotboot/flash-slot1`
```
2021-04-13 14:29:59,982 # om slot 1
2021-04-13 14:29:59,984 # Image magic_number: 0x544f4952
2021-04-13 14:29:59,984 # Image Version: 0x60758ec0
2021-04-13 14:29:59,985 # Image start address: 0x0007ac00
2021-04-13 14:29:59,986 # Header chksum: 0x11e538df
2021-04-13 14:29:59,986 #
> dumpaddrs
2021-04-13 14:30:05,181 # dumpaddrs
2021-04-13 14:30:05,181 # slot 0: metadata: 0x2000 image: 0x00002400
2021-04-13 14:30:05,182 # slot 1: metadata: 0x7a800 image: 0x0007ac00
```

I have not yet figured out how to concatenate two uf2 files so that `flash` can seamlessly be used.

### Issues/PRs references

depends on #16276

### CODE REVIEW

**Comment by fjmolinas** [comment]
How about I don't set it as the default programmer can we go ahead with this one @miri64 @benpicco?

**Comment by miri64** [comment]
> depends on #16267

Needs rebase? #16276 got merged (and I think the reference in OP is wrong)

**Comment by fjmolinas** [comment]
With the last push `FEATURES_REQUIRED=riotbot make -C <someapp>` also works... but still no combined or extended...

**Comment by fjmolinas** [comment]
Can we get this one in as is? I does not cover all cases, but at least allows for some basic riotboot flash support with uf2

**Comment by fjmolinas** [comment]
Thanks!

**Pull request merged**
