### PR TITLE
pkg/semtech-loramac: small fixes

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR fixes a broken link in the semtech-loramac package documentation and improves slightly one of the code snippet by adding a return statement if the join procedure failed.

### Issues/PRs references

None

### CODE REVIEW

**Comment by jia200x** [comment]
Link works and code looks good

**Comment by miri64** [comment]
I would have preferred two separate commits, but let's go with this.

**Comment by aabadie** [comment]
Let's go here

**Comment by miri64** [comment]
Oops, sorry. Forgot to actually merge :-/

**Pull request merged**
