### PR TITLE
shell_commands: port ifconfig command for gnrc_netif2

### PR DESCRIPTION
**Pull request by miri64**
Does what it says on the bin (+ port auto_init_netdev_tap non-intrusively for testing).

~~Depends on #7370.~~

This PR is part of the network layer remodelling effort:
PR dependencies

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master and current dependencies

**Comment by miri64** [comment]
Rebased to current master and current dependencies

**Comment by miri64** [comment]
Again..

**Comment by miri64** [comment]
And again...

**Comment by miri64** [comment]
Rebased to current master, no longer waiting for other PR

**Comment by miri64** [comment]
> Looks good mostly, but where is `set` mentioned. E.g. I only figured out through the source that I can do `ifconfig 6 set key ...`. I've found that I can get the `set` usage with just running `ifconfig <if> set` without parameters, but `ifconfig 6 help` doesn't seem to mention `set`.

I'm not sure what you mean. If you type `ifconfig help` I get:

```
ifconfig help
ifconfig help
usage: ifconfig [<if_id>]
usage: ifconfig <if_id> set <key> <value>
      Sets an hardware specific specific value
      <key> may be one of the following
       * "addr" - sets (short) address
       * "addr_long" - sets long address
       * "addr_short" - alias for "addr"
       * "cca_threshold" - set ED threshold during CCA in dBm
       * "channel" - sets the frequency channel
       * "chan" - alias for "channel"
       * "csma_retries" - set max. number of channel access attempts
       * "encrypt" - set the encryption on-off
       * "hop_limit" - set hop limit
       * "hl" - alias for "hop_limit"
       * "key" - set the encryption key in hexadecimal format
       * "mtu" - IPv6 maximum transition unit
       * "nid" - sets the network identifier (or the PAN ID)
       * "page" - set the channel page (IEEE 802.15.4)
       * "pan" - alias for "nid"
       * "pan_id" - alias for "nid"
       * "power" - TX power in dBm
       * "retrans" - max. number of retransmissions
       * "src_len" - sets the source address length in byte
       * "state" - set the device state

usage: ifconfig <if_id> [-]{ack_req|autoack|autocca|csma|encrypt|mac_no_sleep|fwd|iphc|preload|promisc|raw|rtr_adv
usage: ifconfig <if_id> add [anycast|multicast|unicast] <ipv6_addr>[/prefix_len]
usage: ifconfig <if_id> del <ipv6_addr>
```

There is a really long nice section about `set`

**Comment by x3ro** [comment]
Oh seems like this is different when you type `ifconfig 6 help`

**Comment by miri64** [comment]
Will provide something

**Comment by miri64** [comment]
Ok. I added a specific if-branch for help now (before it was just the default that caused the output, so it was just a coincident `ifconfig help` outputed actual help ;-))

**Comment by x3ro** [comment]
🎉  squash please

**Comment by miri64** [comment]
Done

**Comment by miri64** [comment]
The `@ingroup auto_init_gnrc_netif` change was already pointed out in a previous PR. I reverted that after your ACK. I hope that is ok.

**Pull request merged**
