### PR TITLE
pktbuf: release correct snip in error case

### PR DESCRIPTION
**Pull request by OlegHahm**
In the loopback case, the wrong snip was released in an error case.

### CODE REVIEW

**Comment by cgundogan** [comment]
ACK

**Comment by authmillenon** [comment]
Is there a release correspondent too?

**Comment by authmillenon** [comment]
@cgundogan Y U NO restart travis? ;-)

**Comment by OlegHahm** [comment]
Not yet. Wanted to wait for a final ACK.

**Comment by OlegHahm** [comment]
see #4024

**Pull request merged**
