### PR TITLE
saml21: add I2C support

### PR DESCRIPTION
**Pull request by dylad**
Add I2C support to SAML21 & SAML21-Xplained board
Most of the change are located in the i2c init function, saml21 and samd21 don't have the same clock management.
I added specific init function for saml21 under the sam21_common directory. Maybe it was not the best way to do it. Any thoughts ?

### CODE REVIEW

**Comment by kaspar030** [comment]
I don't have the board anymore... @haukepetersen ?

**Comment by haukepetersen** [comment]
sorry for the delay. Looks to me, like #6205 is the more generic approach and as it's build upon this work, does anyone opposed to going with #6205? @dylad: would that be ok for you?

**Comment by dylad** [comment]
Hi @haukepetersen,
I'm not oppose to anything as long as RIOT supports I2C on saml21 board.
and also I would gladly help to improve saml21 support on RIOT.
Should I close this PR ?

**Comment by haukepetersen** [comment]
perfect: I just opened #6223 to improve the sam0 structure and clarity a bit -> would you maybe mind to have a look at those changes?!

**Comment by haukepetersen** [comment]
closed in favor of #6205 (and #6223)

**Pull request closed without merging**
