### PR TITLE
sys/net/gnrc/netif: Make aac_mode a flag field

### PR DESCRIPTION
**Pull request by JKRhb**
### Contribution description

This PR is another spin-off from #16228. Its changes let the the `aac_mode` field of `gnrc_netif_ipv6_t` be treated as flag field.
The members of the `net_gnrc_netif_aac` enum are updated accordingly. This way, it is possible for a net interface to use (for instance) both SLAAC and DHCPv6 for auto-adress configuration.

### Testing procedure

As this is curently more or less a refactoring, you can use the existing `gnrc` and unit tests should which should still be passing.

### CODE REVIEW

**Comment by JKRhb** [comment]
Hmm, [one test](https://ci.riot-os.org/RIOT-OS/RIOT/16596/672a86d58ef693be8d25a31924fc60d8a2b727f1/output/compile/tests/gnrc_sixlowpan_frag_minfwd/stm32mp157c-dk2:gnu.txt) has failed because of unsufficient ROM (4 bytes). Should the board be added to the `BOARD_INSUFFICIENT_MEMORY` list?

**Comment by benpicco** [comment]
I'd say just add it to the list - if it's this tight it's not worth the trouble.
By how much does the ROM consumption increase compared to master? I can't imagine it to be more than a handful of bytes.

**Comment by JKRhb** [comment]
> I'd say just add it to the list - if it's this tight it's not worth the trouble.

Will do :)

> By how much does the ROM consumption increase compared to master? I can't imagine it to be more than a handful of bytes.

If I am not mistaken, it should be 8 bytes ([before](https://ci.riot-os.org/RIOT-OS/RIOT/master/0fd22d4c618e1d65c6632f972f1022096066374e/output/compile/tests/gnrc_sixlowpan_frag_minfwd/esp32-wroom-32:gnu.txt), [after](https://ci.riot-os.org/RIOT-OS/RIOT/16596/672a86d58ef693be8d25a31924fc60d8a2b727f1/output/compile/tests/gnrc_sixlowpan_frag_minfwd/esp32-wroom-32:gnu.txt)). So pretty close :/

**Review by benpicco — APPROVED** [review]
Looks good to me - @miri64 any objections?

**Comment by miri64** [comment]
Nope, was my proposal after all :-), let's gooooo.

**Pull request merged**
