### PR TITLE
test: missing test for periph/timer #3552

### LINKED ISSUE #3552: tests: Missing test for periph/timer
The other parts of the periph interface have tests, but not periph/timer. `tests/hwtimer` could be used as a base for such a test application.

### PR DESCRIPTION
**Pull request by Gmedhin**
Test application of timer /tested on native platform

### CODE REVIEW

**Comment by haukepetersen** [comment]
I am not quite sure I understand this test - and also I have a little doubt it works as expected. When you are testing all periph timers, which timer is used for usleep then? Do we even have usleep on non-native platforms?

**Comment by Gmedhin** [comment]
I am a new to RIOT. So I am not sure if I can answer your questions correctly. But I will try to explain some of my ideas (please correct me if i am wrong). 
Let me explain first why I used usleep
     I used usleep in order to provide enough time (delay) for (previously set) timer interrupt (timer_set) to fire before I issue a new one. Otherwise, only one interrupt (timer_set) is fired and the others are missed or overwritten (not sure though). 

Initially I tried to use vtimer_usleep instead of usleep. However,  it was not working. Maybe because the native platform has only one timer device ( I guess it has only one channel also) and it is already under test and there is no timer left to be used by vtimer_usleep.  When I use usleep; however, it works. But I do not know for sure  which timer it uses or if usleep actually uses busy waiting (which is then it does not need a timer). 

However, if usleep in fact uses a timer, can we use a busy waiting delay (software delay) instead? then we do not need to use a timer for the busy waiting and, therefore, it is possible to use all timer peripherals in the test?

**Comment by haukepetersen** [comment]
I see. Maybe a quick intro to the timer arch: on embedded hardware we use low-level timers (the actual hardware peripheral timers that this test is for). On top of that we have an abstraction with more functionality and which is easier to use: the new xtimer (and as to next week or so the deprecated vtimer). These actually use the low-level timers. The stdlib timer functions (i.e. usleep) then again are based on top of xtimer/vtimer. So using usleep for testing the low-level timers gives us a hen and egg problem here...

I would actually propose the following testing scheme: 
- for each defined periph timer:
  - set each channel to a different value
  - let the timer callback send message to the main thread
  - in the main thread run something like 
```
while (1) {
    counter++; 
    msg_try_receive(...); 
    if (msg_has_arrived) {
        has_counter_counted_up_to_some_value?
    }
}
````
You can further use the system clock (`CLOCK_CORECLOCK`) to take an informed guess about how many steps the `counter` variable should be counted up until a timer channel's callback message comes in.

The most important part is, that there are no timer dependencies while testing the timers... Maybe someone else has also some (better) ideas how to test the low-level timers, @kaspar030?

P.S.: And I forgot: Welcome to RIOT!

**Comment by Gmedhin** [comment]
Thank you for the explanation and the proposal. Your proposal seems a better way (especially) for testing the timer_set method. But I would like to ask a simple question (just to make sure). Would that be ok (enough) to check the return values for testing some of the methods? Example, timer_set returns 1 (on success) and -1 (on error).

**Comment by haukepetersen** [comment]
Sure, for some functions that would suffice - although only the actual test if a certain time has passed until the timer fires is the key point here :-)

**Comment by haukepetersen** [comment]
@Gmedhin: I was implementing a timer driver earlier today and needed a test, so I went ahead and wrote one more or less as described above: #3780

Feel free to comment on it or to improve it!

**Comment by Gmedhin** [comment]
That is very good. Thank you @haukepetersen, I appreciate you also for reviewing my work and your  helpful feedback. Then this thread can be closed, I think. I will try to pick an other task.

**Comment by kaspar030** [comment]
Closing in favour of #3780. @Gmedhin, thanks for the effort!

**Pull request closed without merging**
