### PR TITLE
boards/nucleo-l1: use upstream openocd configuration

### PR DESCRIPTION
**Pull request by thomaseichinger**
Configuration for the ST Nucleo L152RE board was merged into
OpenOCD upstream. This commit changes scripts for flashing,
debugging and reseting to use this and removes RIOT's configuration
file.

### CODE REVIEW

**Comment by haukepetersen** [comment]
nice one! Can you take the board then I will test @Hack'n'ACK

**Comment by gebart** [comment]
Maybe update the wiki page with information on which OpenOCD version is minimum required as well during the hack'n'ack? https://github.com/RIOT-OS/RIOT/wiki/Board:-ST-nucleo-l1

**Comment by thomaseichinger** [comment]
@gebart I updated the wiki.

**Comment by haukepetersen** [comment]
Works with the OpenOCD version checked out today. Also very nice changes -> ACK and go.

**Pull request merged**
