### PR TITLE
gnrc_ipv6_ext_frag: fix release on rbuf creation for n-th fragment

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While testing #12375, @kb2ma noticed that in some rare cases, one of the nodes crashes. He informed me offline and I was able to reproduce that. After some more runs, I was able to pinpoint it to the following corner case:
1. a subsequent fragment is received before the first and
2. the reassembly buffer is currently filled up when another fragment of a different datagram arrives and thus needs to be cached out to make room for the new reassembly.

Due to that I added a test case to the unittests of IPv6 reassembly (feee568).

In the end it turned out that when a subsequent fragment is received packet parts that are stored in the reassembly buffer are freed from the packet buffer on reassembly buffer creation. This in turn leads that freed (but still referenced by the reassembly buffer) region to be reused for another packet coming in, e.g. another fragment, that then caches the other reassembly buffer entry out, since the reassembly buffer is full, leading to parts of its data to be released by the reassembly buffer, causing a crash, as the data is now not valid anymore.

### Testing procedure
With a board of your choice (preferably `native`, as this test due to an `ethos` bug [#12264] skips some tests for non-native boards):
```
make -C tests/gnrc_ipv6_ext_frag flash
sudo make -C tests/gnrc_ipv6_ext test
```

if feee568 is reverted, the test fails.

### Issues/PRs references
Follow-up on #12375.

### CODE REVIEW

**Comment by miri64** [comment]
Yes sorry, as with most networking tests you have to run `dist/tools/tapsetup/tapsetup` before. I most often forget about that, because I have it setup anyway.

**Comment by miri64** [comment]
@kb2ma what do I need to do to fullfil your change request?

**Comment by kb2ma** [comment]
Apologies, It turns out the issue with the test is my firewall. The TEST_PORT is set to 20908. When I set this to an allowed incoming port, the test succeeds. Is there a customary way to work around this issue for testing? Allow incoming on any port across the tap interface?

I will dismiss the blocking review and try running the release specs test that generated the issue.

**Comment by miri64** [comment]
> and try running the release specs test that generated the issue.

Did it work?

**Comment by miri64** [comment]
Mh, if I rebase to current master to include #12375 and initialize my tap interfaces first, 3.6 passes with 0% packet loss:

```
> ping6 -s 2048 -i 100 -c 1000 fe80::4c1:8ff:fed9:c0b1
ping6 -s 2048 -i 100 -c 1000 fe80::4c1:8ff:fed9:c0b1
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=0 ttl=64 time=1.503 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=1 ttl=64 time=1.597 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=2 ttl=64 time=1.512 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=3 ttl=64 time=1.703 ms
[…]
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=995 ttl=64 time=1.470 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=996 ttl=64 time=1.662 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=997 ttl=64 time=1.665 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=998 ttl=64 time=1.247 ms
2056 bytes from fe80::4c1:8ff:fed9:c0b1: icmp_seq=999 ttl=64 time=1.628 ms

--- fe80::4c1:8ff:fed9:c0b1 PING statistics ---
1000 packets transmitted, 1000 packets received, 0% packet loss
round-trip min/avg/max = 0.442/1.273/7.141 ms
```

Did you maybe not include #12375 when testing this PR? Should I rebase so it is included?

**Comment by kb2ma** [comment]
Well, that was embarrassing. :-/ Yes, when I rebased on master, the tasks from the test-specs for native (03) and for physical board (04) both passed. I ran the 04 task five times.

**Comment by miri64** [comment]
@benpicco @bergzand @cgundogan can you have a look at the rest? This has to be part of the release, otherwise some release specifications might not be fulfilled.

**Comment by miri64** [comment]
> @benpicco @bergzand @cgundogan can you have a look at the rest? This has to be part of the release, otherwise some release specifications might not be fulfilled.

Or maybe @jia200x or @leandrolanzieri?

**Comment by miri64** [comment]
Backport provided in #12434

**Pull request merged**
