### PR TITLE
tests/unittests: rename set_up/tear_down function

### PR DESCRIPTION
**Pull request by pokgak**
### Contribution description

Rename `setup()` and `tear_down()` in template code to mirror the name used in `tests_<module>_<header>_tests`.

### Testing procedure

This is just a small change in the README. It should not affect other code.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Is `tests_<module>_<header>_set_up` a name that is already in use somewhere? Otherwise, what's the benefit of this change? If you wanted more precise naming, why didn't you adjust `test_<function1>_<what1>` too?

**Comment by miri64** [comment]
NACK on prefixing it with `tests_`. Oftentimes test frameworks (see most python framework) use prefixes like this to distinguish tests from non-tests. Both setup and tear-down are by definition not part of the test. While this is not the case with embUnit (there everything has to be classified by hand), I'd like to keep a clear distinction between tests an non-tests to be portable in case we ever decide to change.

**Comment by miri64** [comment]
Also not sure what the benefit of the `<module>_<header>_` prefix could be. The tests are static, they are in a module specific (or even header specific) test suite, so it should be clear which module/header they belong to.

**Comment by pokgak** [comment]
This is not really about precise naming. During my first time writing unit  test, I copy pasted the template and changed all the `<module>` and `<header>` accordingly. That includes `set_up` and `tear_down` in EMB_UNIT_TESTCALLER call:

```
static void set_up(void)
{
    /* omit if not needed */
}

static void tear_down(void)
{
    /* omit if not needed */
}

...

Test *tests_<module>_<header>_tests(void)
{
    .....

    EMB_UNIT_TESTCALLER(<module>_<header>_tests,
                        tests_<module>_<header>_set_up,                <----------- Both of these lines
                        tests_<module>_<header>_tear_down, fixtures);  <-----------
    /* set up and tear down function can be NULL if omitted */

    return (Test *)&<module>_<header>;
}
```

The test failed to build because there is no `tests_<module>_<header>_set_up` and ` tests_<module>_<header>_tear_down`. There is only `set_up` and `tear_down`. After spending a few minutes on it I managed to figure it out and make the changes accordingly.

Because of that I thought maybe it will be easier for newcomers to write their first test in the future with these changes :)

Based on the comments, would it be better if the `set_up` and `tear_down` in EMB_UNIT_TESTCALLER are changed instead?

So the changes would be:
```
Test *tests_<module>_<header>_tests(void)
{
   ...

    EMB_UNIT_TESTCALLER(<module>_<header>_tests,
                        set_up, tear_down, fixtures);
    /* set up and tear down function can be NULL if omitted */

    return (Test *)&<module>_<header>;
}
```

**Comment by miri64** [comment]
> Based on the comments, would it be better if the set_up and tear_down in EMB_UNIT_TESTCALLER are changed instead?
>
> So the changes would be:
> 
> ```
> Test *tests_<module>_<header>_tests(void)
> {
>    ...
> 
>     EMB_UNIT_TESTCALLER(<module>_<header>_tests,
>                         set_up, tear_down, fixtures);
>     /* set up and tear down function can be NULL if omitted */
> 
>     return (Test *)&<module>_<header>;
> }
> ```

Yeah, that would be the better way around. I usually just copy-paste existing tests and completely forgot about the template :sweat_smile:

**Comment by PeterKietzmann** [comment]
BTW: good finding @pokgak! I think it's very useful for newcomers.

**Comment by pokgak** [comment]
Pushed the fix.

**Pull request merged**
