### PR TITLE
gnrc_lorawan: fix gnrc_pktbuf_release_error (introduced by #16080) [backport 2021.07]

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Backport of #16617

### CODE REVIEW

**Review by jia200x — APPROVED** [review]
ACK

**Comment by jia200x** [comment]
please rebase :)

**Comment by MrKevinWeiss** [comment]
I actually made a PR with your branch which it seems I cannot push to, please use #16626

**Comment by miri64** [comment]
@MrKevinWeiss and his ghosts... ehh remotes.

**Pull request closed without merging**
