### PR TITLE
boards/msp430-based: Model features in Kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This PR models the features of all msp430-based boards in Kconfig. Also, common variables (`CPU_FAM`, `CPU_CORE`, `CPU_ARCH`) are defined in `Makefile.features`.

### Testing procedure
- Check the symbol organization
- Green CI, `tests/kconfig_features` should test everything

### Issues/PRs references
Part of #14148

### CODE REVIEW

**Comment by kaspar030** [comment]
this might cause a lot of conflicts with the msp430 toolchain upgrade, is it urgent or could it possibly wait another release?

**Comment by kaspar030** [comment]
> this might cause a lot of conflicts with the msp430 toolchain upgrade, is it urgent or could it possibly wait another release?

well, as it just adds files, it might not be too bad, so please ignore.

**Comment by MrKevinWeiss** [comment]
> well, as it just adds files, it might not be too bad, so please ignore.

It does change some files but it is only a k-config files, so makefile should remain the same.

Thanks for checking.

**Comment by leandrolanzieri** [comment]
Thanks for the review!

**Pull request merged**
