### PR TITLE
WIP: marz: Initial commit (SWP)

### PR DESCRIPTION
**Pull request by sgso**
This adds a tool which can be used to reach RIOT nativenet instances
without a proper border router (for e.g. application layer testing).

It was useful for me, so I share it here (I do not think, that this necessarily belongs into the code tree, but you know why...)

TODOS:
- [ ] defragmentate 6LoWPAN
- [ ] add TCP
- [ ] cleanup the messy code
- [ ] rewrite the whole 6LoWPAN scapy module (it sucks)
- [ ] abolish python.

### CODE REVIEW

**Comment by OlegHahm** [comment]
@sgso, do you think this is already useful enough to get merged or are you planning to continue to work on this?

**Comment by sgso** [comment]
@OlegHahm: Neither nor. It works for udp and does just enough for me to test a point-to-point connection. But it's a ugly hack using a hacked version of a dead-end piece of software (scapy-dev). I'll not doing any more work on it.

**Comment by LudwigOrtmann** [comment]
OK, then I suggest we either leave this open until the new netapi and some changes in native allow for direct network connections, or close it as memo now.

**Comment by sgso** [comment]
I'll put it into a separate repository, post a reference here and close this PR afterwards. This should make it easier to find in case someone has a use for it later.

**Comment by LudwigOrtmann** [comment]
Thanks =)

**Comment by sgso** [comment]
Moved to https://github.com/sgso/marz for future reference.

**Pull request closed without merging**
