### PR TITLE
cpu/sam3: udpate gpio driver

### PR DESCRIPTION
**Pull request by TobiasFredersdorf**
Updated the gpio peripheral driver implementation for sam3x CPUs.

### CODE REVIEW

**Comment by TobiasFredersdorf** [comment]
Update of the gpio-driver

**Comment by kaspar030** [comment]
-2200 +270. Nice!

**Comment by TobiasFredersdorf** [comment]
@haukepetersen  @PeterKietzmann Sorry but I didn't see any chance to save the other pullrequest

**Comment by PeterKietzmann** [comment]
Thanks @TobiasFredersdorf ! Don't worry about the other PR. I will close it. WOuld you say that all features of this driver do work as expected now? One other thing: Please rephrase your commit message slightly to something like "cpu/sam3: udpate gpio driver". You can compare [this posting](http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git) or just google to find out how to realize that

**Comment by haukepetersen** [comment]
thanks!

Minor remark: the cpu is called `sam3` instead of `sam3x8e` by now... :-) Otherwise looking good and works fine. 

ACK once Travis is also happy.

**Comment by haukepetersen** [comment]
oh, and as @PeterKietzmann said, once the commit message is changed.

**Comment by PeterKietzmann** [comment]
Comments were addressed, PR was tested and ACKed and Travis agrees.

**Comment by PeterKietzmann** [comment]
Congrats for your first PR Tobias!

**Comment by haukepetersen** [comment]
nice!

**Pull request merged**
