### PR TITLE
rpl: fix netapi commands handling

### PR DESCRIPTION
**Pull request by cgundogan**

### CODE REVIEW

**Comment by cgundogan** [comment]
ping @authmillenon

**Comment by OlegHahm** [comment]
Maybe you can provide some information about the rationale for this fix.

**Comment by cgundogan** [comment]
Sure:
`GNRC_NETAPI_MSG_TYPE_SND` and `GNRC_NETAPI_MSG_TYPE_RCV` do not accept a reply.
Only `GNRC_NETAPI_MSG_TYPE_GET` and `GNRC_NETAPI_MSG_TYPE_SET` do that.
Currently, upon receiving a `GNRC_NETAPI_MSG_TYPE_SND`, this would slide down the switch cases until the point where a reply is send to the other thread. This is wrong, because the other thread is not expecting a message.

Although, RPL is not utilizing `GNRC_NETAPI_MSG_TYPE_SND` for now (and the bug never executed), the code is still wrong

**Comment by OlegHahm** [comment]
Currently I fail to understand why RPL implements netapi calls at all, but the change itself seems to be legit anyway. ACK.

**Comment by cgundogan** [comment]
@OlegHahm ICMP RPL control traffic is sent from the ipv6 thread via netapi to all registrees. RPL registeres for that kind of ICMP traffic and hence must implement at least `GNRC_NETAPI_MSG_TYPE_RCV`

**Comment by OlegHahm** [comment]
Thanks for explanation/reminder.

**Pull request merged**
