### PR TITLE
boards/sodaq-explorer: add configuration for rn2483 module

### PR DESCRIPTION
**Pull request by aabadie**
Follow-up of ~~#7725~~ with #7505.

### CODE REVIEW

**Comment by keestux** [comment]
@aabadie Do you happen to know if I can somehow use the USB (ttyACM0) of the Explorer board as the serial for printf and getline (stdin, stdout)? (Instead of uart0)

**Comment by aabadie** [comment]
> Do you happen to know if I can somehow use the USB (ttyACM0) of the Explorer board as the serial for printf and getline (stdin, stdout)?

Not for the moment with RIOT. This requires the support of the USB stack to emulate UART other USB. With this, one can have the same behaviour as with Arduino. There are discussions about this in #7510 (because Adafruit Feather M0 has the same 'problem') and in this old PR #3890 which is about adding an USB stack.

**Comment by aabadie** [comment]
Once #7505 is in this one can be merged right away. I just tested it and it works.

**Comment by aabadie** [comment]
We just made some testing with @kYc0o, so can this still be part of 2018.01 @smlng ?

**Comment by smlng** [comment]
> some testing with @kYc0o, 

can we have @kYc0o approval then?

**Comment by kYc0o** [comment]
>>Do you happen to know if I can somehow use the USB (ttyACM0) of the Explorer board as the serial for printf and getline (stdin, stdout)?

>Not for the moment with RIOT. This requires the support of the USB stack to emulate UART other USB. With this, one can have the same behaviour as with Arduino. There are discussions about this in #7510 (because Adafruit Feather M0 has the same 'problem') and in this old PR #3890 which is about adding an USB stack.

AFAIK what I understand from that is that there is already an USB-Serial converter (if you can see a /dev/ttyACMx). Thus it's a matter of knowing where is it mapped. Should be straightforward and would be much more practical.

**Comment by smlng** [comment]
great!

**Pull request merged**
