### PR TITLE
pkg/lvgl: add extra widget dependency

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Just a missing dependency, not sure it's woth the full build.

### Testing procedure

Add the module, see missing files.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Review by aabadie — CHANGES_REQUESTED** [review]
@benpicco, any reason why you approved this PR without comment ?

I checked in LVGL code and there's indeed [an implicit dependency between tabview and btnmatrix widgets](https://github.com/lvgl/lvgl/blob/0b5a1d4b23975b920ff841ea9cd038802f51711b/src/extra/widgets/tabview/lv_tabview.c#L108) but it's not specified explicitly in their code, neither in the tabview.c nor in their Kconfig.
That should be fixed upstream.

Since we are doing the same automatic dependency resolution with the `lv_win` extra widget, there's no reason to also do it for tabview.

I'm blocking because you forgot to update Kconfig.

**Comment by benpicco** [comment]
It appeared to be a simple enough change - but yea, if the pkg provides Kconfig that needs to be updated as well

**Comment by fjmolinas** [comment]
I have some more down the pipe, I'll bundle them together before fixing Kconfig

**Comment by fjmolinas** [comment]
@aabadie I added Kconfig

**Review by aabadie — APPROVED** [review]
ACK

**Comment by fjmolinas** [comment]
Thanks @aabadie and @benpicco!

**Pull request merged**
