### PR TITLE
[Tracking] makefiles/docker: add docker/% targets

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This PR adds `docker/%` targets to be able to `flash` and `tests` in docker. It is still WIP but wanted to PR early so it can be tested (firstly in @cladmi and my one "paper-ci"). There is also the first section of common code that can be merged early (after release).

**TODO**:

- [x] add `PROG_DEV`, `/dev` used for programming
- [ ] add `SERIAL_ID` for serial device (could be different from programmer)
- [ ] add docker image with flash tools
- [ ] documentation on how to map devices

### Testing procedure

Try flashing, testing on a target. The easy way of testing is just passing `DOCKER_TARGET_FLAGS=--privileged`.

To be done properly for most boards a `PROG_PORT` must be passed to docker to map the `device` used for flashing. I don't yet understand in detail which one, but in the case of  `samr21-xpro` it is `/dev/hidraw*` but for `mulle` is `/dev/bus/usb/001/065`

I was able to find the device by doing:

```
udevadm monitor -ukp | grep DEVNAME

DEVNAME=/dev/bus/usb/001/065
DEVNAME=/dev/usb/hiddev4
DEVNAME=/dev/hidraw6
DEVNAME=/dev/ttyACM0
DEVNAME=/dev/bus/usb/001/065
DEVNAME=/dev/bus/usb/001/065
```

For `native` and `samr21-xpro` (or other boards using `edbg`) this can be done without the need of aditional flash-tools since `riot/riotbuild` is capable of building `edbg` and has `pyserial`.

If wanting to test on other toolchains I have a very WIP and dirty `Dockerfile` to build https://github.com/fjmolinas/riotdocker/blob/riot/Dockerfile.build.flash an Image with all flashing toolchains (or most of them).

```
docker build -t riot/riotflash -f Dockerfile.build.flash .
```

```
PROG_PORT=/dev/bus/usb/001/062 DOCKER_TARGET_IMAGE=riot/riotbuildflash BOARD=mulle make -C examples/default/ docker/flash-only docker/term
```

### Issues/PRs references

Alternative to #11220.

### CODE REVIEW

**Comment by fjmolinas** [comment]
@aabadie might want to take a look :)

**Comment by cladmi** [comment]
@smlng this could be the alternative to https://github.com/RIOT-OS/RIOT/issues/10121 that we finally implemented
It does not handle creating the `tap` interface yet but could be thought too.

**Comment by miri64** [comment]
@fjmolinas. Do you think this can be finished for the release?

**Comment by fjmolinas** [comment]
Rebased and squashed  since no one seems to have taken a look yet.

**Comment by mguetschow** [comment]
Is this still relevant and if so, is anyone willing to take this up again? @Teufelchen1 @maribu @MrKevinWeiss

**Comment by maribu** [comment]
Sorry. I think this is a non-trivial to get working with every programmer on every host system. Personally, this is too much work for too little reward for me to take this one up.

Especially since most programmer tools are now build from source and well integrated: The host system now only needs a full USB stack, a working C toolchain and some `libusb-dev` + `libusb-compat-dev` (or whatever the distro calls the package with the USB headers) to just work. Other than the USB headers, I think most systems will be able to flash out of the box.

I think instead documenting how to install the headers on popular distros would go a long way and be a trivial task :)

**Comment by mguetschow** [comment]
Okay thanks for your explanation, in that case I will close this PR now.

**Pull request closed without merging**
