### PR TITLE
cpu/sam0_common: implement EXTWAKE for SAM L21

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

On SAM L21 only 8 EXTWAKE pins can wake the CPU from Backup sleep.
Handle this analogous to the RTC tamper pins on SAM D5x/E5x where configuring them as an interrupt will also cause them to wake the device from Deep Sleep.

### Testing procedure

Flash the `tests/periph_gpio` on e.g. `saml21-xpro`. The user button is connected to PA02 which can be used as an EXTWAKE source.

```
# initialize PA02 as interrupt with falling flank
init_int 0 2 0 
# press the button a few times to ensure the configuration is correct
…
# enter lowest sleep mode
pm set 0
```

If you press the button again, the CPU should wake up from sleep.

~~*still untested as I currently don't have access to the hardware*~~

### CODE REVIEW

**Comment by dylad** [comment]
@benpicco Is this WIP only because this PR isn't tested yet ? Or is there another reason ?

**Comment by benpicco** [comment]
Yes this is still untested.

**Comment by dylad** [comment]
FWICT, it works as expected.
I am just wondering if this should be enabled by default without any way for end-users to disable it easily.
What do you think ?

**Comment by benpicco** [comment]
Thank you for testing!
> I am just wondering if this should be enabled by default without any way for end-users to disable it easily.

Hm my reasoning was that interrupts wake the CPU from lower sleep modes, so this would be the least surprising thing to do.
Then again on `samd5x` the behavior needs to be enabled with the `periph_gpio_tamper_wake` module, but that's because doing so is much more expensive there.
So I'm not sure - should I introduce a new pseudo-module/feature for wake from Deep Sleep by GPIO?

**Comment by dylad** [comment]
> So I'm not sure - should I introduce a new pseudo-module/feature for wake from Deep Sleep by GPIO?

I am unsure too, I wasn't able to think about a specific use case for this but who knows ?
Maybe we can leave it as it for now and implement a pseudomodule later if we have this need.

**Review by dylad — APPROVED** [review]
ACK.
Work as expected on SAML21.

**Comment by benpicco** [comment]
Thank you for the review!

**Pull request merged**
