### PR TITLE
core/mutex: Cleanup

### PR DESCRIPTION
**Pull request by maribu**
#### `core/mutex`: Cleanup

- Use `static inline` function for `mutex_try_lock()`
    - The implementation is trivial enough with the `inline`-able IRQ API to just always be `inline`-ed
- Rename `_mutex_lock()` to `mutex_lock()` and drop the blocking parameter
    - This was possible to the stand-alone `mutex_try_lock()` implementation
    - This yields a measurable performance bump
- Add `mutex_cancel()` to allow a canceling a pending call to `mutex_lock()`
    - This will allow to simplify the implementing `xtimer_mutex_lock_timeout()` and will make implementing `ztimer_mutex_lock_timeout()` a piece of cake

#### `sys/xtimer`: Simplify xtimer_mutex_lock_timeout()
    
- Use mutex_cancel() for a trivial implementation

#### `sys/ztimer`

An implementation of `ztimer_mutex_lock_timeout()` will now be trivial. But that should be its own PR.

##### Nucleo-F767ZI

Master:

```
make RIOT_VERSION=test BOARD=nucleo-f767zi -C tests/bench_mutex_pingpong flash test

   text	   data	    bss	    dec	    hex	filename
  13776	    132	   3952	  17860	   45c4	/home/maribu/Repos/software/RIOT/tests/bench_mutex_pingpong/bin/nucleo-f767zi/tests_bench_mutex_pingpong.elf

{ "result" : 188317, "ticks" : 1147 }
```

PR:

```
make RIOT_VERSION=test BOARD=nucleo-f767zi -C tests/bench_mutex_pingpong flash test

   text	   data	    bss	    dec	    hex	filename
  13728	    132	   3952	  17812	   4594	/home/maribu/Repos/software/RIOT/tests/bench_mutex_pingpong/bin/nucleo-f767zi/tests_bench_mutex_pingpong.elf

{ "result" : 200185, "ticks" : 1079 }
```

##### Arduino Mega2560

Master:

```
make RIOT_VERSION=test BOARD=arduino-mega2560 -C tests/bench_mutex_pingpong flash test

   text	   data	    bss	    dec	    hex	filename
   9358	    276	   1690	  11324	   2c3c	/home/maribu/Repos/software/RIOT/tests/bench_mutex_pingpong/bin/arduino-mega2560/tests_bench_mutex_pingpong.elf

{ "result" : 14549, "ticks" : 1099 }
```

PR:

```
make RIOT_VERSION=test BOARD=arduino-mega2560 -C tests/bench_mutex_pingpong flash test

   text	   data	    bss	    dec	    hex	filename
   9276	    276	   1690	  11242	   2bea	/home/maribu/Repos/software/RIOT/tests/bench_mutex_pingpong/bin/arduino-mega2560/tests_bench_mutex_pingpong.elf

{ "result" : 14683, "ticks" : 1089 }
```

#### Correctness

All of these automated tests should still pass

- `tests/xtimer_mutex_lock_timeout`
- `tests/xtimer_rmutex_lock_timeout`
- `tests/mutex_order`
- `tests/mutex_unlock_and_sleep`

### Issues/PRs references

None

### CODE REVIEW

**Comment by kaspar030** [comment]
I think I'd prefer this PR to be split. I contains multiple quite substantial changes.

**Comment by maribu** [comment]
> I think I'd prefer this PR to be split. I contains multiple quite substantial changes.

You can't split it without breaking stuff. E.g. the current `xtimer_mutex_lock_timeout()` is quite nasty and directly accesses `core/mutex` and `core/sched` internals. I cannot change those internals without also updating `xtimer`.

**Comment by kaspar030** [comment]
I don't know. The inlined `mutex_try_lock()` for example, can't that be split out? It would also making performance / code size assessment easier.

**Comment by maribu** [comment]
> I don't know. The inlined `mutex_try_lock()` for example, can't that be split out?

When still keeping `_mutex_lock()` taking a blocking parameter and keeping `mutex_lock(mutex_t *m)` as a wrapper for `_mutex_lock(m, 1)`, then yes.

But it would be strange to have two implementations of `mutex_try_lock()` in the code base, wouldn't it? Also, there is no benchmark for `mutex_try_lock()` in place. The speedup for `mutex_lock()` is caused by splitting out the `mutex_try_lock()` case.

**Comment by maribu** [comment]
After this PR `xtimer` and `core/mutex` will no longer be entangled. Future PRs targeting `core/mutex` could be done in smaller step.

**Comment by maribu** [comment]
If you insist on splitting this, https://github.com/RIOT-OS/RIOT/pull/15071 needs to be merged first. But as I said, this is really ugly.

**Comment by MrKevinWeiss** [comment]
[Running tests on the HiL CI](https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/master/32/pipeline)

**Comment by maribu** [comment]
> [Running tests on the HiL CI](https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/master/32/pipeline)

`frdm-k22f` consistently failed to flash, all other tests were passed.

**Comment by MrKevinWeiss** [comment]
Yup flashing is a bit of a pain...

**Comment by fjmolinas** [comment]
I ran the test on two `frdm-*` boards to replace the `frdm-k22f` https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/194/artifact/. All good.

**Comment by benpicco** [comment]
Why only split out a part of 63d673a42eab8ebcb620fabd88c41b491eefec53?

**Comment by maribu** [comment]
> Why only split out a part of [63d673a](https://github.com/RIOT-OS/RIOT/commit/63d673a42eab8ebcb620fabd88c41b491eefec53)?

I don't quite understand the question.

**Comment by benpicco** [comment]
You've split out parts of commit 63d673a as PR #15071. But that part does not do much on it's own.
Why not make a separate PR for 63d673a since that's already a good change.

The rest will build on top of it.

**Comment by maribu** [comment]
> You've split out parts of commit 63d673a as PR #15071.

Not true. That PR contains no code of this PR. It copy-pastes the current `mutex_lock()` implementation to `xtimer` as its own "personal" implementation. That will allow changing the `mutex_lock()` implementation without touching `xtimer` - provided that the data format remains compatible with the `xtimer` copy of `mutex_lock()`.

> Why not make a separate PR for 63d673a since that's already a good change.

I can do so. But first PR #15071 needs to be merged. Otherwise this will break compilation of `xtimer`.

**Comment by benpicco** [comment]
needs a rebase

**Comment by fjmolinas** [comment]
This one needs a rebase now.

**Comment by maribu** [comment]
Now everything this PR contributed is provided by split out PRs - most of them even already merged.

**Pull request closed without merging**
