### PR TITLE
[GNRC_PPP] CLI for SIM900

### PR DESCRIPTION
**Pull request by jia200x**
Hi.
This PR is an example of the CLI of GNRC PPP. With this example is possible to test SIM900 internet access through GNRC PPP.
Check the readme for details.

### CODE REVIEW

**Comment by miri64** [comment]
Does anymody has this device so I might reassign?

**Comment by kaspar030** [comment]
I have a random SIM900 devel board with serial connection. Can try to get it running...

**Comment by miri64** [comment]
Then I assign you for now.

**Comment by OlegHahm** [comment]
@kaspar030, any time for testing?

**Comment by miri64** [comment]
Sadly nothing happening substential here for >2 years. AFAIK @jia200x is not working on this anymore, so ok to close?

**Comment by jia200x** [comment]
yeah, and I think this PR doesn't make sense anymore, because there's support for generic AT devices and stuff. We can close it

**Pull request closed without merging**
