### PR TITLE
atmega: added panic function

### PR DESCRIPTION
**Pull request by OlegHahm**
should fix https://github.com/RIOT-OS/RIOT/pull/3886#issuecomment-141789316

### CODE REVIEW

**Comment by authmillenon** [comment]
Works with #3886 and #3904 and even just for `gnrc_networking`. ACK.

**Comment by authmillenon** [comment]
I'll remove the blacklisting in #3886, if this one gets merged first, alternatively you remove the blacklisting if #3886 gets merged first. Deal?

**Comment by OlegHahm** [comment]
Deal!

**Comment by authmillenon** [comment]
Tickling Travis.

**Comment by authmillenon** [comment]
Oh and #3886 was merged, so this needs a rebase + adaptation

**Comment by OlegHahm** [comment]
rebased and updated

**Pull request merged**
