### PR TITLE
drivers/cc2420: move flush sequence to inline function 

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
See https://github.com/RIOT-OS/RIOT/pull/10416#issuecomment-451980544

### Testing procedure
Check it compiles properly. Try to receive packets and check they are received correctly (if FIFO is not flushed, new packets won't be received)

### Issues/PRs references
#10416

### CODE REVIEW

**Comment by smlng** [comment]
I guess its safe to squash already

**Comment by maribu** [comment]
> I guess its safe to squash already

+1

**Comment by jia200x** [comment]
done!

**Comment by maribu** [comment]
If Travis and Murdock don't find any issues, I would just merge this PR untested. I really cannot see how this could break anything - I would bet that the compiler would generate the exact same machine code before and after this PR.

**Comment by maribu** [comment]
@smlng, @PeterKietzmann: Are you fine with untested merge of this PR?

**Comment by maribu** [comment]
OK. I did just compile it with and without the PR and disassembled cc2420.o. The result is the same - so indeed the same machine code is generated. I think this should be as good as testing. (I cannot test because I'm missing the hardware.)

**Comment by maribu** [comment]
Huh! A moment ago all three checks were green - now Codacy is running again... Strange. (But I guess that test will pass again, as no code was change since it was green and I hit merge.)

**Comment by maribu** [comment]
For the record Codacy [says the PR is up to standards](https://app.codacy.com/app/danpetry/RIOT/pullRequest?prid=2834530) now. Next time I'll hit Ctrl+F5 instead of F5 before clicking on merge. Maybe the browser chache served me ill this time.

**Pull request merged**
