### PR TITLE
openocd: use exit instead of shutdown

### PR DESCRIPTION
**Pull request by OlegHahm**
Using the shutdown command directly will trigger an exit code.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Fixes #2470 alternatively to #2471.

**Comment by gebart** [comment]
does this actually execute the `reset run` command on the line after `program`?

**Comment by OlegHahm** [comment]
Not sure, the openocd documentation is a bit blurry here - but with https://github.com/OlegHahm/RIOT/commit/aedaa10f9f1198a214710b2611f33b47c7627da6 it should do so. From [openocd documentation](http://openocd.sourceforge.net/doc/html/Flash-Programming.html)
```
5. reset run is called if reset parameter is given.
6. OpenOCD is shutdown if exit parameter is given. 
```

**Comment by gebart** [comment]
in OpenOCD 0.8.0 the `program` command is different:

>  -- Command: program filename [verify] [reset] [offset]
     This is a helper script that simplifies using OpenOCD as a
     standalone programmer. The only required parameter is `filename',
     the others are optional.  *Note Flash Programming::.

**Comment by gebart** [comment]
The behaviour according to the 0.8.0 manual is to shut down OpenOCD after the `program` command has been executed, which is why we were seeing this difference between 0.9.0 and 0.8.0

Since the program command is a convenience macro for the real flash commands and it has different semantics for different versions it may be better to use the real commands instead?

```
    -c 'flash write_image erase $(ELFFILE) 0x00000000 elf' \
    -c 'verify_image $(ELFFILE)' \
    -c 'reset run' \
    -c 'shutdown'
```
or if you prefer ihex:
```
    -c 'flash write_image erase $(HEXFILE) 0x00000000 ihex' \
    -c 'verify_image $(HEXFILE)' \
    -c 'reset run' \
    -c 'shutdown'
```

**Comment by OlegHahm** [comment]
`shutdown` is a bad option since it results in an error return value.

**Comment by OlegHahm** [comment]
If I see it correctly, we have three choices:
1. Force users to use latest openocd version from Git or provide our own fork.
2. Add a check to the openocd script to set the commands according to the used revision.
3. Use the proposed solution from @gebart with the `shutdown` command and ignore the return value (similar to #2471) for now and use the "proper" version as soon as openocd 0.90 is widespread.

Personally, I think I prefer 3.

**Comment by PeterKietzmann** [comment]
In my opinion 1. is quite ok. How do we go on here?

**Comment by gebart** [comment]
@PeterKietzmann I would like to wait with 1. until at least a supported version is in the upstream repos of Ubuntu (possibly even LTS) before forcing people to upgrade when there is no functional reason to upgrade to the prerelease version.

So I vote no. 3

**Comment by PeterKietzmann** [comment]
Well, I do agree with waiting for a supported version. Also I believe that your solution is fine :-) . Just wanted to trigger the conversation/progress of this PR

**Comment by haukepetersen** [comment]
+1 for 3

**Comment by OlegHahm** [comment]
Will be rebased as soon as OpenOCD 0.9.0 is part of most common distributions.

**Comment by cgundogan** [comment]
>Will be rebased as soon as OpenOCD 0.9.0 is part of most common distributions.

@OlegHahm openocd-0.9.0 seems to be part of ubuntu since the 2015-09 version. Is ubuntu common enough?

**Comment by OlegHahm** [comment]
I think the agreement was to wait for the version in Ubuntu LTS, i.e. waiting for Ubuntu 04.2016

**Comment by authmillenon** [comment]
> I think the agreement was to wait for the version in Ubuntu LTS, i.e. waiting for Ubuntu 04.2016

That's what I just wanted to say. Also keep in mind that 14.04 will be supported until April 2019.
Also: The most current Debian stable (Jessie) also only has support for 0.8.0 (EOL not provided yet).

**Comment by authmillenon** [comment]
(though I use a hand-build version of openocd I run 14.04 on one of my main working machines)

**Comment by cgundogan** [comment]
>That's what I just wanted to say. Also keep in mind that 14.04 will be supported until April 2019.
Also: The most current Debian stable (Jessie) also only has support for 0.8.0 (EOL not provided yet).

Having system support doesn't mean that people can still install a newer version by hand ..

**Comment by kYc0o** [comment]
What's the status on this? the new Ubuntu release is already there with the new OpenOCD version AFAIK, so can this be merged for the release?

**Comment by OlegHahm** [comment]
Can anybody try?

**Comment by kYc0o** [comment]
Please rebase and I can give it a try ;)

**Comment by OlegHahm** [comment]
good point

**Comment by OlegHahm** [comment]
Unfortunately, openocd.com seems to be down.

**Comment by kYc0o** [comment]
But rebase should be up it isn't? :P

**Comment by OlegHahm** [comment]
Actually it is.

**Comment by kYc0o** [comment]
All is up now, rebase? :D

**Comment by OlegHahm** [comment]
If I see this correctly, the openocd maintainers have changed to not let shutdown return an error value any more unless you give it a parameter. Hence, we can go with #2897.

**Comment by kYc0o** [comment]
Great, thanks!

**Pull request closed without merging**
