### PR TITLE
cpu/stm32f1: Disable HSI when using the HSE as system clock

### PR DESCRIPTION
**Pull request by DipSwitch**
This one was missed in the clock source selection update of the STM32F1.

(If it's not included in in .04 it's alright ;) )

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Can you have a look at the periph_conf.h for iotlab-m3? I assume `CLOCK_PLL_DIV` needs adaption? I wasn't able to use HSI here.

**Comment by PeterKietzmann** [comment]
Probably it's not `CLOCK_PLL_DIV ` to change but again clock speeds. Simply changing `CLOCK_HSE` into `CLOCK_HSI` int the periph_conf does not work. I didn't look into the ref manual to find out about valid clock rates...

**Comment by thomaseichinger** [comment]
The code looks sane I don't have a device for testing though. 
@PeterKietzmann I'm troubling to understand the motivation of changing `CLOCK_HSE` to `CLOCK_HSI`. HSI runs on 8MHz so values definitely would have to be adapted.

**Comment by DipSwitch** [comment]
For the iotlab-m3 you would need to set the CLOCK_CORECLOCK to 64MHz. And change the HSI clock value to 8MHz and set the PLL multiplier to 16.

I Also needed to add `#define XTIMER_SHIFT_ON_COMPARE 1` due to the CPU not running fast enough to get the two timer values in a single timer tick.

**Comment by PeterKietzmann** [comment]
Sorry I didn't make it the last days. As this is a feature I guess we need to postpone until the current release is over. @thomaseichinger not sure I understand your doubts correctly. Yes you need to tough some values when changing to HSI but with this PR you just need to touch the periph_conf. I dont like the need of `#define XTIMER_SHIFT_ON_COMPARE 1`. Will check once I'm on it again.

**Comment by DipSwitch** [comment]
Maybe the `XTIMER_SHIFT_ON_COMPARE ` was needed due to single stepping, not sure though.

**Comment by kYc0o** [comment]
This won't make it for this release, so postponing for the next one.

**Comment by PeterKietzmann** [comment]
Tested with an iotlab-m3 board and `HSE` in default configuration and `HSI` with:
```
/**
 * @name Clock system configuration
 * @{
 **/
#define CLOCK_HSI           (8000000U)             /* frequency of external oscillator */
#define CLOCK_CORECLOCK     (64000000U)             /* targeted core clock frequency */
/* configuration of PLL prescaler and multiply values */
/* CORECLOCK := CLOCK_SOURCE / PLL_DIV * PLL_MUL */
#define CLOCK_PLL_DIV       (1)
#define CLOCK_PLL_MUL       (16)
```
Worked. ACK and go

**Pull request merged**
