### PR TITLE
gnrc_tcp: fix data race on fsm status

### PR DESCRIPTION
**Pull request by brummer-simon**
### Contribution description
This PR fixes a race condition within gnrc_tcp. The multiple threads within gnrc_tcp read the connections
state of the TCB processing FSM to base decisions on. This state variable is only changed within the FSM function
that is protected by a mutex. The current readout of the state is not protected.

This PR adds a function to get the current state of the FSM. Calling the function locks/unlocks the FSM and returns
the current state. This adds a dedicated synchronization point to resolve the issue.

### Testing procedure
This fix should not change the behavior of gnrc_tcp. To test the changes, run the gnrc_tcp test suite.

### Issues/PRs references
None. I came across this, implementing something else.

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
Looks good to me and tested on `native` and `samr21-xpro`.

**Comment by brummer-simon** [comment]
Thanks @miri64.

I saw that the static-tests produced some small warnings. I could fix them within this PR.
Should I do this or create a seperate PR for that?

**Comment by miri64** [comment]
> I saw that the static-tests produced some small warnings. I could fix them within this PR.

If you want, feel free to do so, but please put them in a separate commit.

**Comment by brummer-simon** [comment]
Done

**Pull request merged**
