### PR TITLE
drivers/ws281x: esp32 neopixel driver to set the rmt symbol high/low lengths at init instead of every write

### PR DESCRIPTION
**Pull request by IsikcanYilmaz**
### Contribution description

Minor change to the `WS281x` driver, specifically the `esp32` side.

The `ws281x` driver for the `esp32` uses a hardware module called the `RMT`, which generates the data signal that the `ws281x`s expect. The `RMT` module is supplied with the information about how to generate this signal; for a `1` symbol, how long should the signal be held high, how long should it be low, so on. These `1` and `0` symbol high/low times are recalculated at every `RMT` write. 

This PR does the calculation once at init. Marginal speed up (~10us on my 80 neopixel strip).

If there was a reason for doing it at every write, it was not obvious to me. Please let me know if so.

### CODE REVIEW

**Comment by IsikcanYilmaz** [comment]
What would yield a better speedup would be having `ws281x_set_buffer` to write to its buffer in the form of a `rmt_item32_t` instead of `color_rgb_t`, at least for the esp32 that uses the RMT. 

Currently the `color_rgb_t`s get converted to `rmt_item32_t`s at every write operation. As far as I understand, if we could avoid this conversion at every write, we could have the RMT driver do writes without blocking. Do the ESP gurus here see anything wrong with this potential solution?

**Comment by maribu** [comment]
The code change looks good to me. Do you happen to already have tested that this doesn't cause any regressions? (Not that I would expect any from the changes, but better safe than sorry.)

Otherwise I can give the code a spin.

**Comment by IsikcanYilmaz** [comment]
> Do you happen to already have tested that this doesn't cause any regressions?

I'v been running it yes. So far so good. 

> Otherwise I can give the code a spin.

That would give me more confidence.

**Comment by IsikcanYilmaz** [comment]
as far as i understand, this change would affect someone's application only if they change clock frequency in run time. 

with this change in, should someone do such thing, they would have to deinit and reinit the neopixel driver.

**Review by maribu — APPROVED** [review]

**Pull request merged**
