### PR TITLE
cpu/cc2538: avoid using bitfields with the LCRH register

### PR DESCRIPTION
**Pull request by hexluthor**
Otherwise the UART ignores the new baudrate divisor. Tested on cc2538dk with various SYS_DIV (system clock rate) settings.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Looks reasonable. Has anyone the hardware to test? I don't...

**Comment by OlegHahm** [comment]
Me neither. Should we just merge?

**Comment by PeterKietzmann** [comment]
I'd say yes but I don't dare to do so :-)

**Comment by OlegHahm** [comment]
@haukepetersen, can you test?

**Comment by haukepetersen** [comment]
yes, will ASAP (sorry for the delay)

**Comment by OlegHahm** [comment]
@hexluthor, can you rebase? @kYc0o, you have the hardware to test, right?

**Comment by kYc0o** [comment]
Yes I can test :)

**Comment by hexluthor** [comment]
Rebased.

**Comment by OlegHahm** [comment]
Cool!

**Comment by kYc0o** [comment]
I just tested with sucess, just waiting for travis.

**Comment by authmillenon** [comment]
@kYc0o I give you the honor to merge this ;)

**Comment by kYc0o** [comment]
hohoho I was very optimistic with the T-guy xD

**Comment by OlegHahm** [comment]
@kYc0o, wanna give it another try with merging? ;-)

**Comment by kYc0o** [comment]
wow! It has just finished? I was looking at it every 5min! yes! ACK and merge!

**Comment by OlegHahm** [comment]
Yeah!

**Pull request merged**
