### PR TITLE
fib: cs precision

### PR DESCRIPTION
**Pull request by cgundogan**
This is just an exercise to see how reducing the precision of the fib's lifetimes impacts the size. I did no verification besides of compiling `gnrc_networking` and running the unittests. This PR should not be merged and may still be subject to discussion.

This PR basically assumes seconds in absolute time. So I reduced all `uint64_t` to `uint32_t`. I am not sure whether going lower than 32-bit is a good idea, though.

see #4518

Following a size comparison for `gnrc_networking`

```
text    data    bss     dec     BOARD/BINDIRBASE

-60     0       -160    -220    arduino-due
58168   284     17480   75932   master-bin
58108   284     17320   75712   fib-bin

-426    0       -80     -506    arduino-mega2560
81686   11578   11284   104548  master-bin
81260   11578   11204   104042  fib-bin

-152    0       0       -152    avsextrem
86280   220     98077   184577  master-bin
86128   220     98077   184425  fib-bin

-56     0       -160    -216    cc2538dk
58340   220     17432   75992   master-bin
58284   220     17272   75776   fib-bin

-64     0       -160    -224    ek-lm4f120xl
58600   220     17408   76228   master-bin
58536   220     17248   76004   fib-bin

-64     0       -160    -224    f4vi1
60288   224     17544   78056   master-bin
60224   224     17384   77832   fib-bin

-32     0       -160    -192    fox
73436   220     20600   94256   master-bin
73404   220     20440   94064   fib-bin

-64     0       -168    -232    frdm-k64f
58704   1248    17944   77896   master-bin
58640   1248    17776   77664   fib-bin

-32     0       -160    -192    iotlab-m3
73448   220     20600   94268   master-bin
73416   220     20440   94076   fib-bin

-60     0       -160    -220    limifrog-v1
59440   220     17528   77188   master-bin
59380   220     17368   76968   fib-bin

-60     0       -160    -220    mbed_lpc1768
57944   220     17400   75564   master-bin
57884   220     17240   75344   fib-bin

-152    0       0       -152    msba2
108228  220     98077   206525  master-bin
108076  220     98077   206373  fib-bin

-64     0       -160    -224    msbiot
60624   224     17592   78440   master-bin
60560   224     17432   78216   fib-bin

-48     0       -160    -208    mulle
76264   1284    21056   98604   master-bin
76216   1284    20896   98396   fib-bin

-236    0       -96     -332    native
197838  620     103128  301586  master-bin
197602  620     103032  301254  fib-bin

-64     0       -168    -232    nrf52dk
57952   220     17400   75572   master-bin
57888   220     17232   75340   fib-bin

-44     0       -160    -204    nucleo-f091
59768   220     17528   77516   master-bin
59724   220     17368   77312   fib-bin

-64     0       -160    -224    nucleo-f303
58648   220     17536   76404   master-bin
58584   220     17376   76180   fib-bin

-64     0       -160    -224    nucleo-f401
60256   224     17544   78024   master-bin
60192   224     17384   77800   fib-bin

-60     0       -160    -220    nucleo-l1
59320   220     17520   77060   master-bin
59260   220     17360   76840   fib-bin

-56     0       -160    -216    openmote-cc2538
58964   220     17688   76872   master-bin
58908   220     17528   76656   fib-bin

-64     0       -168    -232    pba-d-01-kw2x
75464   1248    21128   97840   master-bin
75400   1248    20960   97608   fib-bin

-152    0       0       -152    pttu
86488   220     98077   184785  master-bin
86336   220     98077   184633  fib-bin

-56     0       -160    -216    remote
58976   220     17632   76828   master-bin
58920   220     17472   76612   fib-bin

-44     0       -160    -204    saml21-xpro
59772   220     17520   77512   master-bin
59728   220     17360   77308   fib-bin

-40     0       -160    -200    samr21-xpro
76224   220     20608   97052   master-bin
76184   220     20448   96852   fib-bin

-32     0       -168    -200    slwstk6220a
58068   220     17528   75816   master-bin
58036   220     17360   75616   fib-bin

-64     0       -160    -224    stm32f3discovery
58728   220     17536   76484   master-bin
58664   220     17376   76260   fib-bin

-64     0       -160    -224    stm32f4discovery
60536   224     17568   78328   master-bin
60472   224     17408   78104   fib-bin

-60     0       -160    -220    udoo
58168   284     17480   75932   master-bin
58108   284     17320   75712   fib-bin
```

### CODE REVIEW

**Comment by BytesGalore** [comment]
If we stick to `s` and 32bits we would have max timescales of ~138 years, that's probably too enthusiastic for a FIB entry. Going down to 16bits, our max timescale falls down to ~18 days using `s`.

I don't oppose to go for 32bit precision, but I'm still not convinced that `s` is sufficient.
I think of scenarios with high speed node movement, where nodes churn and need to update/out-date routes in a very high frequency.
If we would go for `s`, we will deny finer granularity by design.

If we would go for `ms` precision and 32bits, our max timescale is ~49 days. For me this feels like a more applicable timescale in length and precision for a FIB entry.

**Comment by cgundogan** [comment]
>Going down to 16bits, our max timescale falls down to ~18 days using s.

By my calculations it's even 18 hours, not days. So definitely not feasable for us.

**Comment by BytesGalore** [comment]
> By my calculations it's even 18 hours, not days. So definitely not feasable for us.

yup typo. Iguess 32bit is definitely the lower bound here.

**Comment by kaspar030** [comment]
Did you consider more than seconds and miliseconds? centiseconds might be a good fit, with 32bit fitting 13years. ms seems overkill for network routes, but seconds seem slow.

AFAIK babel uses centiseconds, so if fib is fixed to second granularity, they can't be used together without losing babel's convergence time properties.

Maybe this should be a compile time choice?

**Comment by BytesGalore** [comment]
> Did you consider more than seconds and miliseconds?

Not yet.
Just to use centiseconds internally for FIB entries seems sufficient, when taking the measurements from @PeterKietzmann on our stack into account, cf. https://github.com/RIOT-OS/RIOT/issues/4518#issuecomment-200780334. 
However, I have a feeling that we should avoid using magnitudes of tens because we would always need to covert the value to a common base when comparing/calculating with it.

13 years for the lifetime of a temporary FIB entry (without being updated) seems very optimistic to me, but would be really cool when a RIOT node lifecycle and continuous runtime would exceed such period.

**Comment by cgundogan** [comment]
Okay, I changed it to centiseconds precision and also switched the order of "Interface" and "Expires" in the fib output (this makes the alignment much simpler, because the length of the lifetime is harder to guess)

`gnrc_networking` diff:
```
text    data    bss     dec     BOARD/BINDIRBASE

-128    0       -160    -288    arduino-due
58316   284     17480   76080   master-bin
58188   284     17320   75792   fib-bin

-596    -2      -80     -678    arduino-mega2560
82246   11578   11284   105108  master-bin
81650   11576   11204   104430  fib-bin

-188    0       0       -188    avsextrem
86516   220     98077   184813  master-bin
86328   220     98077   184625  fib-bin

-132    0       -160    -292    cc2538dk
58488   220     17432   76140   master-bin
58356   220     17272   75848   fib-bin

-116    0       -160    -276    ek-lm4f120xl
58744   220     17408   76372   master-bin
58628   220     17248   76096   fib-bin

-116    0       -160    -276    f4vi1
60432   224     17544   78200   master-bin
60316   224     17384   77924   fib-bin

-104    0       -160    -264    fox
74528   220     20624   95372   master-bin
74424   220     20464   95108   fib-bin

-132    0       -168    -300    frdm-k64f
58848   1248    17944   78040   master-bin
58716   1248    17776   77740   fib-bin

-104    0       -160    -264    iotlab-m3
74540   220     20624   95384   master-bin
74436   220     20464   95120   fib-bin

-128    0       -160    -288    limifrog-v1
59588   220     17528   77336   master-bin
59460   220     17368   77048   fib-bin

-128    0       -160    -288    mbed_lpc1768
58092   220     17400   75712   master-bin
57964   220     17240   75424   fib-bin

-184    0       0       -184    msba2
108464  220     98077   206761  master-bin
108280  220     98077   206577  fib-bin

-132    0       -160    -292    msbiot
60768   224     17592   78584   master-bin
60636   224     17432   78292   fib-bin

-128    0       -160    -288    mulle
77404   1284    21080   99768   master-bin
77276   1284    20920   99480   fib-bin

-800    0       -96     -896    native
199054  620     103128  302802  master-bin
198254  620     103032  301906  fib-bin

-132    0       -168    -300    nrf52dk
58112   220     17400   75732   master-bin
57980   220     17232   75432   fib-bin

-88     0       -160    -248    nucleo-f091
59924   220     17528   77672   master-bin
59836   220     17368   77424   fib-bin

-116    0       -160    -276    nucleo-f303
58792   220     17536   76548   master-bin
58676   220     17376   76272   fib-bin

-132    0       -160    -292    nucleo-f401
60400   224     17544   78168   master-bin
60268   224     17384   77876   fib-bin

-128    0       -160    -288    nucleo-l1
59468   220     17520   77208   master-bin
59340   220     17360   76920   fib-bin

-132    0       -160    -292    openmote-cc2538
59108   220     17688   77016   master-bin
58976   220     17528   76724   fib-bin

-128    0       -168    -296    pba-d-01-kw2x
75608   1248    21128   97984   master-bin
75480   1248    20960   97688   fib-bin

-188    0       0       -188    pttu
86724   220     98077   185021  master-bin
86536   220     98077   184833  fib-bin

-132    0       -160    -292    remote
59120   220     17632   76972   master-bin
58988   220     17472   76680   fib-bin

-88     0       -160    -248    saml21-xpro
59928   220     17520   77668   master-bin
59840   220     17360   77420   fib-bin

-84     0       -160    -244    samr21-xpro
77256   220     20624   98100   master-bin
77172   220     20464   97856   fib-bin

-100    0       -168    -268    slwstk6220a
58212   220     17528   75960   master-bin
58112   220     17360   75692   fib-bin

-132    0       -160    -292    stm32f3discovery
58888   220     17536   76644   master-bin
58756   220     17376   76352   fib-bin

-116    0       -160    -276    stm32f4discovery
60680   224     17568   78472   master-bin
60564   224     17408   78196   fib-bin

-128    0       -160    -288    udoo
58316   284     17480   76080   master-bin
58188   284     17320   75792   fib-bin
```

**Comment by cgundogan** [comment]
hm, the fib stores absolute time which can be dangerous if the system is running for a very long time. While it was "not such a big deal" with 64-bit precision, it might be a problem if we start to use 32-bit values for fib entries. Storing centiseconds, the values could wrap over if the system is running for a little bit more than a year. Maybe we should use sequence numbers à la https://github.com/RIOT-OS/RIOT/blob/master/sys/include/seq.h (RFC 1982) ?

**Comment by OlegHahm** [comment]
Sounds sensible to me.

**Comment by BytesGalore** [comment]
> hm, the fib stores absolute time ...

exactly, this way the FIB doesn't need an own timer to determine if a lifetime of a FIB entry is expired.
If we would store relative time we also would need to track the time for each individual FIB entry.

**Comment by kYc0o** [comment]
Needs rebase. This is WIP so I'll move it for the next release.

**Comment by cgundogan** [comment]
>Storing centiseconds, the values could wrap over if the system is running for a little bit more than a year. Maybe we should use sequence numbers à la https://github.com/RIOT-OS/RIOT/blob/master/sys/include/seq.h (RFC 1982) ?

did not look further into this and it's unlikely that I will do this until the upcoming release. So let's postpone.

**Comment by OlegHahm** [comment]
Postpone until when?

**Comment by BytesGalore** [comment]
@OlegHahm I guess eventually the FIB will be a merged Portion of the NIB (#5866). 
So probably its not necessary to take effort for lowering the precision in the FIB for now?

I still prefer to go for `ms` over using centi-second precision.

**Comment by kYc0o** [comment]
This PR needs a rebase and the discussion is not ended, so maybe it needs to be postponed. @cgundogan do you care?

**Comment by smlng** [comment]
> eventually the FIB will be a merged Portion of the NIB

so @miri64, @cgundogan and @BytesGalore what up with this one? Can we close?

**Comment by miri64** [comment]
Routes in NIB have *second* precision, so I'd say this is not needed anymore.

**Pull request closed without merging**
