### PR TITLE
STM32_common/dma: Optimize the latency in the hot path

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR optimizes the stm32 DMA controller to reduce the number of operations in the hot path of a DMA stream configuration.

1. Move power-on and enable function to the DMA init. The DMA is never powered off, so the most this will do is prematurely enable the DMA before it is strictly required.
2. FCR configuration changes only during memory-to-memory transfers. clearing the DMDIS flag during the acquire should be sufficient for now
3. Same as above, clearing the flags during the acquire and not every transfer is sufficient as these are also cleared in the ISR.
4. This removes a number of asserts that should have been triggered during proper functional call usage anyway. This is why the dma asserts remain in the acquire function. No need to assert this again during the transfer, start and wait call.
5. This commit splits the `dma_configure` into a setup function, called once in a series of DMA transfers, and a prepare, called every DMA transfer. The setup configures the stream channel, direction, the peripheral address and transfer width. This is usually only required once in a set of transfers (for example a spi_transfer_regs, which consists of a transfer for the device register and a transfer for the data.). The `dma_prepare` is called before every transfer to change the memory address and the length of the transfer.
6. Cache the DMA stream register base address in RAM. Calculating the register base address during init and not every call reduced the overhead from a single transfer from 7.4μs to 6.4μs. This comes at the cost of 4 bytes per logical DMA stream configured.

Let me know if it is preferred to split this commit in multiple PRs

### Testing procedure

This should be tested on the different stm32 (f0, f1, f2, f4, l4 and f7) classes to ensure that I didn't accidentally broke the DMA peripheral.

Testing is probably easiest with SPI, using #14087 and #14093.

Boards that have DMA configured (and thus might break) are:

- b-l072z-lrwan1 (SPI and UART)
- b-l475e-iot01a (SPI and UART)
- iotlab-(a8-)m3 (UART)
- nucleo-f207zg (SPI, UART and ethernet)
- nucleo-f767zi (SPI, UART and ethernet)
- nucleo-l152re (SPI and UART)
- nucleo-l476rg (SPI and UART)

### Issues/PRs references

Depends on #14087 for some measurements on this.

### CODE REVIEW

**Comment by benpicco** [comment]
please rebase

**Comment by bergzand** [comment]
rebased

**Comment by bergzand** [comment]
Rebased!

**Comment by aabadie** [comment]
I tested this PR on `iotlab-m3` (UART) and `stm32f429i-disc1` (ILI9341 screen via SPI) and both worked.

I have a few comments on several points:
1. What happens if the device goes to sleep mode (STOP). Shouldn't the DMA be powered on again after a wake up ? It seems dangerous to me to only call `dma_poweron` in `dma_init`.
5. configure is split in setup/prepare but in the change, both functions are called one after the other. Do you have a use case where prepare is called somewhere else ? Or maybe you forgot to push dma_prepare additions in DMA related peripheral (UART, SPI) ?

**Comment by bergzand** [comment]
> What happens if the device goes to sleep mode (STOP). Shouldn't the DMA be powered on again after a wake up ? It seems dangerous to me to only call `dma_poweron` in `dma_init`.

My assumption was that the DMA is not automatically powered off by the MCU. Preferably I would want to have the DMA be powered during the acquire and be turned off again during the release *if* no other streams are active. This adds additional complexity and I didn't want to include it in this PR.



> configure is split in setup/prepare but in the change, both functions are called one after the other. Do you have a use case where prepare is called somewhere else ? Or maybe you forgot to push dma_prepare additions in DMA related peripheral (UART, SPI) ?

Yes, In the SPI DMA PR adds them. The setup is used [here](https://github.com/RIOT-OS/RIOT/pull/14097/files#diff-993728c780a3d5357c0032c8c1adfd11R179-R184) in the SPI acquire function. The prepare function is later used [here](https://github.com/RIOT-OS/RIOT/pull/14097/files#diff-993728c780a3d5357c0032c8c1adfd11R228-R241). For example during a `spi_transfer_regs()`, the prepare is called twice where previously the whole configure function was called twice.

**Comment by aabadie** [comment]
> This adds additional complexity and I didn't want to include it in this PR.

OK

> For example during a spi_transfer_regs(), the prepare is called twice where previously the whole configure function was called twice.

Ok, makes sense.

**Comment by aabadie** [comment]
Please fix the issue raised by ccpcheck:
```
cpu/stm32/periph/dma.c:381: style (clarifyCondition): Boolean result is used in bitwise operation. Clarify expression with parentheses.
```
You can squash directly.

**Comment by bergzand** [comment]
> Please fix the issue raised by ccpcheck:

Amended!

**Comment by bergzand** [comment]
Thanks!

**Pull request merged**
