### PR TITLE
tests: add minimal test application

### PR DESCRIPTION
**Pull request by kaspar030**
Curious how small RIOT could get, I "wrote" this test. It tries to minimize the set of selected options and debugging output in order to get the smallest possible binary.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Do you think we should merge this? I mean, it's a nice show case but as you know, it does nothing.

**Comment by emmanuelsearch** [comment]
If it gives an indicator we want to keep an eye on, then let's merge it.

**Comment by kaspar030** [comment]
@PeterKietzmann Yeah, I want to merge it. We will have a nice indicator over time on how (not) bloated our default settings are.

**Comment by PeterKietzmann** [comment]
ACK and go

**Comment by OlegHahm** [comment]
Would be cool to generate numbers automatically for the web page.

**Comment by gebart** [comment]
@OlegHahm :+1: I would like to expand on that thought and generate build sizes for each platform for each of the examples (hello-world, ng_networking, rpl_udp, default) for each master commit in order to see how it evolves over time. Takes a lot of resources (and therefore time) to compile everything though.

**Comment by OlegHahm** [comment]
Since the CI is doing this more or less anyways, wouldn't it make sense to generate these numbers on the CI system(s) and upload them somewhere? @phiros, what do you say?

**Comment by kaspar030** [comment]
same time ago I've set up python CodeSpeed to track these changes. Didn't take care of the installation, but you could take a look. Seems perfect for the job.

**Comment by gebart** [comment]
We should continue this discussion in the proper place: #3383

**Pull request merged**
