### PR TITLE
boards/seeedstudio-gd32: add mtd_sdcard_default

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR adds the default configuration for `mtd_sdcard` module.

### Testing procedure

Green CI

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
```patch
diff --git a/tests/nanocoap_cli/Makefile b/tests/nanocoap_cli/Makefile
index cd7d3c6bfb..dad3097ef2 100644
--- a/tests/nanocoap_cli/Makefile
+++ b/tests/nanocoap_cli/Makefile
@@ -26,6 +26,7 @@ LOW_MEMORY_BOARDS := \
   nucleo-f302r8 \
   saml10-xpro \
   saml11-xpro \
+  seeedstudio-gd32 \
   sipeed-longan-nano \
   spark-core \
   stm32f7508-dk \
```

**Comment by gschorcht** [comment]
> ```diff
> diff --git a/tests/nanocoap_cli/Makefile b/tests/nanocoap_cli/Makefile
> index cd7d3c6bfb..dad3097ef2 100644
> --- a/tests/nanocoap_cli/Makefile
> +++ b/tests/nanocoap_cli/Makefile
> @@ -26,6 +26,7 @@ LOW_MEMORY_BOARDS := \
>    nucleo-f302r8 \
>    saml10-xpro \
>    saml11-xpro \
> +  seeedstudio-gd32 \
>    sipeed-longan-nano \
>    spark-core \
>    stm32f7508-dk \
> ```

I didn't add it by intention since it will be already added by PR #19256.

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks.

**Pull request merged**
