### PR TITLE
Import of Nucleo 411

### PR DESCRIPTION
**Pull request by OlegHahm**
Since #2366 got closed and merged but removed from master again yesterday due to a mishap, I re-open this PR here.

I have now two of these boards available. However, flashing doesn't seem to work -  the board remains unflashable afterwards until I upload a valid firmware again.

### CODE REVIEW

**Comment by authmillenon** [comment]
Lots of trailing whitespaces says Travis

**Comment by LudwigOrtmann** [comment]
How do you upload a firmware when flashing is impossible?

**Comment by OlegHahm** [comment]
It's possible to mount the chip as a USB mass storage device.

**Comment by OlegHahm** [comment]
Addressed @authmillenon's comments.

**Comment by haukepetersen** [comment]
This PR needs some love:
- I don't think it comes without features
- the linkerscript structure changed
- possible more?

**Comment by OlegHahm** [comment]
Will not  work on this foreseeable future. If anyone wants to work on this, I'm happy to give you my boards.

**Pull request closed without merging**
