### PR TITLE
New "readline" module for a better shell

### PR DESCRIPTION
**Pull request by noshky**
This is a more sophisticated shell implementation, that has colors, cursor-navigation, bash/zsh-like shortcuts and even a history (no tab-completion yet).

The implementation can be integrated as a module via ``USEMODULE += readline``. The dependency to the ``shell``-module is provided.

The shell module can now be configured with ``USE_SHELL_COLORS=1`` to have fancy colors.
The readline module can be configured with ``SHELL_HISTORY_SIZE=<n>`` to have a history-buffer that is n-times the buffer size. ``SHELL_HISTORY_SIZE=0`` compiles without the usage of the history, as well as not mentioning that flag at all.

TODOs:
The SHELL_BUFFER_SIZE has a big FIXME written next to it in ``readline.h``. It should be of the same size as the buffer size used for the ``shell`` module, but i haven't figured a way out yet to combine them.

### CODE REVIEW

**Comment by authmillenon** [comment]
To be clear: this is a native only feature right?

**Comment by authmillenon** [comment]
Because as a far as I know: pyterm provides most of this already.

**Comment by Kijewski** [comment]
Does RIOT really need to provide terminal features?

**Comment by noshky** [comment]
@authmillenon No this feature is independent of the port, just as the ``shell`` module. Only for the native port, ``ncurses`` is needed to use ``stdio`` in raw mode.

@Kijewski This is not needed at all, but I found it nice to have. Pyterm is just one of many terminal programs, I'm sure different people have different favours and different use cases may also require different terminals. For that matter, terminal features may be of interest.

**Comment by LudwigOrtmann** [comment]
please add module prefixes to the commits.

**Comment by x3ro** [comment]
Haven't had time to look into the "why" yet, but the PR currently bumps the RAM usage on the SAMR21 by 512 bytes when **not** including the readline module and by 648 bytes when including it.

**Comment by LudwigOrtmann** [comment]
Needs rebase

**Comment by noshky** [comment]
@LudwigOrtmann I will add prefixes, what is the syntax for it? "``sys/readline:``"?
@LudwigOrtmann Rebase - what am I supposed to do?
@x3ro I'd like to figure out why that is, can you give me a hint on how I can observe the RAM usages?

**Comment by x3ro** [comment]
@noshky if you build for the SAMR with

    BOARD=samr21-xpro make clean all

It will display the size of the different sections in the binary at the end. The section you're interested in for RAM usage is `bss`.

**Comment by LudwigOrtmann** [comment]
@noshky seems you figured this out on your own =)

**Comment by authmillenon** [comment]
Found another use-case for this module: iotlab-term doesn't use pyterm either and is would also benefit, I guess. @OlegHahm what do you think?

**Comment by OlegHahm** [comment]
You can easily use pyterm with IoT-LAB and the serial-aggregator also uses readline.

**Comment by authmillenon** [comment]
How? I'm having problems accessing the history.

**Comment by OlegHahm** [comment]
That's probably an ssh issue. Try with https://github.com/RIOT-OS/RIOT/pull/2952

**Comment by OlegHahm** [comment]
I think it would be a nice feature for toying around, but not really enhance RIOT handling, but just increase memory usage. Since original contributor seems to have abandoned this anyway, I think we can close this.

**Pull request closed without merging**
