### PR TITLE
makefiles/kconfig: add board & CPU config variables

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This introduces `KCONFIG_BOARD_CONFIG` and `KCONFIG_CPU_CONFIG` variable for boards and CPUs (including common directories) to add default configuration files to be merged. The current approach, as it uses `Makefile.features`, would include boards first, not allowing them to override CPU configurations.

Documentation on this is added as well.

### Testing procedure
- You can check that for a board like `stm32f769i-disco`, which has configuration files from different sources (board, stm32, cortexm_common), now the order is the correct: 1st the arch, 2nd the cpu, 3rd the board. This can be seen by printing `MERGE_SOURCES` from `makefiles/kconfig.mk` and building with `TEST_KCONFIG=1`.
- Read the docs
- Green CI

### Issues/PRs references
Found in #17349

### CODE REVIEW

**Review by fjmolinas — APPROVED** [review]
ACK, murdock should check the dependencies.

**Comment by MrKevinWeiss** [comment]
Looks like there are still some issues, I will try to push a solution as @leandrolanzieri is a bit unavailable.

**Comment by MrKevinWeiss** [comment]
I changes the priority of `KCONFIG_ADD_CONFIG` back to the original.  The `KCONFIG_APP_CONFIG` and `KCONFIG_USER_CONFIG` should be able to overwrite the values set by `KCONFIG_ADD_CONFIG`.

**Comment by MrKevinWeiss** [comment]
Things seem to be doing OK now.  May I squash (or @leandrolanzieri ).

**Comment by fjmolinas** [comment]
Please squash, ACK stands

**Comment by MrKevinWeiss** [comment]
Done! now we wait :)

**Pull request merged**
