### PR TITLE
kw2xrf: use static inline

### LINKED ISSUE #7090: kw2xrf: linking problems with arm-none-eabi-gcc 7.1.0 and *-ld 2.28
With the latest arm-none-eabi-gcc (7.1.0) and -ld (2.28) on my Arch machine, I get the following linking problems when building `gnrc_networking` for the `pba-d-01-kw2x` board:
```
% BOARD=pba-d-01-kw2x make
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf.o): In function `kw2xrf_reset_phy':                                                                                                                                                                                     
RIOT/drivers/kw2xrf/kw2xrf.c:126: undefined reference to `kw2xrf_clear_dreg_bit'
RIOT/drivers/kw2xrf/kw2xrf.c:128: undefined reference to `kw2xrf_enable_irq_b'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_netdev.o): In function `_isr':
RIOT/drivers/kw2xrf/kw2xrf_netdev.c:694: undefined reference to `kw2xrf_mask_irq_b'
RIOT/drivers/kw2xrf/kw2xrf_netdev.c:754: undefined reference to `kw2xrf_enable_irq_b'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_getset.o): In function `kw2xrf_abort_sequence':
RIOT/drivers/kw2xrf/kw2xrf_getset.c:152: undefined reference to `kw2xrf_mask_irq_b'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:173: undefined reference to `kw2xrf_enable_irq_b'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_getset.o): In function `kw2xrf_set_idle_sequence':
RIOT/drivers/kw2xrf/kw2xrf_getset.c:182: undefined reference to `kw2xrf_mask_irq_b'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:218: undefined reference to `kw2xrf_enable_irq_b'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_getset.o): In function `kw2xrf_set_option':
RIOT/drivers/kw2xrf/kw2xrf_getset.c:386: undefined reference to `kw2xrf_clear_dreg_bit'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:435: undefined reference to `kw2xrf_clear_dreg_bit'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:439: undefined reference to `kw2xrf_set_dreg_bit'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:454: undefined reference to `kw2xrf_clear_dreg_bit'
RIOT/drivers/kw2xrf/kw2xrf_getset.c:469: undefined reference to `kw2xrf_set_dreg_bit'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_intern.o): In function `kw2xrf_timer_load':
RIOT/drivers/kw2xrf/kw2xrf_intern.c:116: undefined reference to `kw2xrf_set_dreg_bit'
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_intern.o): In function `kw2xrf_seq_timeout_on':                                                                                                                                                                         
RIOT/drivers/kw2xrf/kw2xrf_intern.c:197: undefined reference to `kw2xrf_mask_irq_b'                                                                                                                                                                                                     
RIOT/drivers/kw2xrf/kw2xrf_intern.c:206: undefined reference to `kw2xrf_set_dreg_bit'                                                                                                                                                                                                   
RIOT/drivers/kw2xrf/kw2xrf_intern.c:207: undefined reference to `kw2xrf_enable_irq_b'                                                                                                                                                                                                   
RIOT/examples/gnrc_networking/bin/pba-d-01-kw2x/kw2xrf.a(kw2xrf_intern.o): In function `kw2xrf_seq_timeout_off':                                                                                                                                                                        
RIOT/drivers/kw2xrf/kw2xrf_intern.c:212: undefined reference to `kw2xrf_clear_dreg_bit'                                                                                                                                                                                                 
collect2: error: ld returned 1 exit status                                                                                                                                                                                                                                                        
make: *** [RIOT/examples/gnrc_networking/../../Makefile.include:298: all] Error 1
```

### PR DESCRIPTION
**Pull request by cgundogan**
fixes #7090

### CODE REVIEW

**Comment by gebart** [comment]
I don't see why the linking failures happened in the first place.

**Comment by miri64** [comment]
@gebart because multiple c-files include `drivers/kw2xrf/include/kw2xrf_intern.h`, the compiler decides to not make the function inline (because sizewise it would be more ideal) => function gets global name with first c-file => second c-file tries to do the same => boom.

Maybe it even makes more sense to not make these functions inline. This should however be evaluated with a size check.

**Comment by gebart** [comment]
I see. I would have expected it to become multiple definition rather than undefined reference.

**Comment by gebart** [comment]
It's possible this affects my #7107 as well.

**Comment by cgundogan** [comment]
murdock agrees - GO

**Pull request merged**
