### PR TITLE
sys/fmt: disarm footgun

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Mixing `print*()` from `fmt.h` with `puts()` `*printf()` from `stdio.h` results in corrupted output even with only one thread printing. That's an obvious footgun. This fixes the issue.

### Testing procedure

The first commit extends `tests/fmt_print` to detect output corruptions when mixing with `stdio.h` (this should fail on `master`). The second fixes the issue (so it should pass again after the second commit).

### Issues/PRs references

Alternative to dropping the use of `fmt` in https://github.com/RIOT-OS/RIOT/pull/18161

### CODE REVIEW

**Comment by miri64** [comment]
@kaspar030 can you have a look at this?

**Review by kaspar030 — APPROVED** [review]
ACK.

This does now adds a dependency of fmt to newlib's stdio code (+200b for a `print_str("foo\n")` for an otherwise `-DLOG_LEVEL=LOG_NONE` build). But, no more broken output.

**Comment by maribu** [comment]
I added special handling for `native` and some comments to explain why that is needed and squashed this right in.

It seems that consistent behavior among the different implementations is a bit more involved that I have hoped for, so lets run tests to be sure.

I disabled the auto merge in case someone wants to take a look at the changes.

**Comment by maribu** [comment]
looks like the ESP32s from the pi fleet are unplugged / broken. But other than that this seems to be ready now

**Comment by maribu** [comment]
All green now

**Comment by maribu** [comment]
Thx!

**Pull request merged**
