### PR TITLE
nanocoap: fix byte order of request message ID, and add test application

### PR DESCRIPTION
**Pull request by kb2ma**
nanocoap was inconsistent in its public interface to the message ID for a request. For details, see the [issue](https://github.com/kaspar030/sock/issues/13) and the [PR](https://github.com/kaspar030/sock/issues/14) for the fix. This PR updates RIOT's package to include the fix. I also added a gcoap unit test to verify.

This PR uses the nanocoap from my fork, and I hope/expect @kaspar030 will accept the fix into his repository. Until that happens, RIOT can use the commits from the kb2ma nanocoap (sock) repository.

### CODE REVIEW

**Comment by smlng** [comment]
nanocoap is now part of RIOT, @kb2ma please adapt this accordingly. The changes you requested on nanocoap (use `htons`) are not in RIOT yet, hence open a separate PR for that.

**Comment by kb2ma** [comment]
Adapted to nanocoap in RIOT. Created nanocoap unit test suite. Also, it turns out the byteorder function renaming was merged in #6897, so I think we're good there.

**Comment by smlng** [comment]
@kaspar030 any comments on this from your side?

**Comment by smlng** [comment]
ping @kaspar030, this should go into to the release, too.

**Pull request merged**
