### PR TITLE
CI: no quickbuild on "bors try"

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Make "bors try" behave like "bors merge", don't do a quick build.

### Testing procedure

- [x] regular PR build (should be a quickbuild): [build](https://ci.riot-os.org/details/a3d6db6f70624d5aa08d138ca63a702b)
- [x] "bors try" (should be a full build) [build](https://ci.riot-os.org/details/6a994d3894e44fc2a34bcddd676e4e62/builds/examples:default)
- [x] finally, "bors merge"

### Issues/PRs references

fixes https://github.com/RIOT-OS/murdock-scripts/issues/45

### CODE REVIEW

**Comment by kaspar030** [comment]
So this would still fast-fail on "bors try"...
IMO, as there is the option to do "CI: full build" and "CI: no fast fail" for regular PR builds, I'd prefer to actually have "bors try" be "bors merge but don't merge". 
There's no (easy) way to control "bors try" (it doesn't know about PR labels).

**Comment by kaspar030** [comment]
bors try

**Comment by kaspar030** [comment]
> Build failed:
> 
>     * [Murdock](https://ci.riot-os.org/details/6a994d3894e44fc2a34bcddd676e4e62)

this did build [examples/default](https://ci.riot-os.org/details/6a994d3894e44fc2a34bcddd676e4e62/builds/examples:default) for >200 boards, so it was not a quick build.

**Review by maribu — APPROVED** [review]

**Comment by kaspar030** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
