### PR TITLE
boards/saml21-xpro & boards/samr21-xpro: added dummy ADC and DAC config

### PR DESCRIPTION
**Pull request by kartben**
Signed-off-by: Benjamin Cabé <benjamin@eclipse.org>

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@kartben could you give a hint why you need that "fix"? Some people, e.g. 
@msolters, already started on implementing a driver for these CPUs (compare #4162) but we got stuck in some design issues at that time (IIRC)

**Comment by PeterKietzmann** [comment]
I would merge this one if it helps but you need to rebase after #5449 was merged

**Comment by kartben** [comment]
@PeterKietzmann OK i will try to have another look, thanks!

**Comment by PeterKietzmann** [comment]
@kartben any insights? Would you rebase your branch?

**Comment by PeterKietzmann** [comment]
Hi @kartben! I would like to merge or close this PR. In the first case you need to rebase. Would you do that please? Once you are at it, could your shorten you commit message? Something like the following should be fine:
`boards/samX21-xpro: added dummy ADC and DAC config`

**Comment by PeterKietzmann** [comment]
I will close this PR cause there was no progress for a long time and it's marked as "minor".  @kartben we can re-open it whenever you are able to rebase and rephrase the commit message.

**Pull request closed without merging**
