### PR TITLE
pyterm/testbeds: added support for iotlab

### PR DESCRIPTION
**Pull request by OlegHahm**
Logging and efficient terminal control not yet implemened.

### CODE REVIEW

**Comment by phiros** [comment]
Please rebase and test. We should extend this class in order to make use of pytermcontroller.

The latter we could accomplish by connecting pyterms to the tcp ports of each involved node in the testbed. Since pyterms connect to the pytermcontroller (and not the other way around) we could make use of ssh port forwarding in order to allow the pyterms to connect to the pytermcontroller even if the pytermcontroller runs on a developer machine (often behind NAT/firewall).

**Comment by authmillenon** [comment]
Needs rebase.

**Comment by miri64** [comment]
Still needs rebase.

**Comment by miri64** [comment]
.

**Comment by kYc0o** [comment]
Well... the rebase never came, so it will be postponed.

**Comment by OlegHahm** [comment]
Sorry, I think I will abandon this.

**Comment by OlegHahm** [comment]
Labeled as memo in case anyone would like to pick this up someday.

**Comment by kYc0o** [comment]
Ohhh schade... maybe @aabadie or @cladmi ?

**Pull request closed without merging**
