### PR TITLE
board/axavior: Initial import for AxAvior

### PR DESCRIPTION
**Pull request by DipSwitch**
I would like to import the module / board our company created.

It is currently available on CrowdSupply: https://www.crowdsupply.com/axtrel/axavior

**Specifications:**
MCU: STM32F101RD (Clock: 36MHz - Flash: 384K - RAM: 48K)
Transceiver: AT86RF212B (868 to 920 MHz)
MicroBus on dev board: http://www.mikroe.com/mikrobus/

Reliable range in and around buildings
Range: > 500 m / 1500 ft (line-of-sight)
Bitrate up to 250 kbits/s
Power supply: 3.3 V
Active power: 60 mW
Inactive power: < 0.3 mW

**Depending on PR:**
 - [x] #4154 - cpu: Add clock source selection based on CLOCK_HSE or CLOCK_HSI for STM32F1 family
 - [ ] #4225 - cpu/stm32f1/periph/dac: DAC implementation for STM32F1
 - [ ] #4227 - cpu/stm32f1/periph/pwm: PWM implementation for STM32F1

### CODE REVIEW

**Comment by haukepetersen** [comment]
@DipSwitch: would you mind waiting also for #4952?

**Comment by DipSwitch** [comment]
No problem! :)

**Comment by haukepetersen** [comment]
awesome!

**Comment by DipSwitch** [comment]
Rebased and updated, almost there.

I could also wait for #4862 and update this board aswell :)

**Comment by haukepetersen** [comment]
that would be great, maybe we can get #4862 in today?

**Comment by DipSwitch** [comment]
At the moment there is no interest for this board, so we won't produce it.

**Pull request closed without merging**
