### PR TITLE
doc/emulators: add emulators documentation in Doxygen

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds an emulator page in the doxygen documentation. The renode documentation that is currently in [dist/tools/renode/README.md](https://github.com/riot-os/riot/tree/master/dist/tools/renode/README.md) is moved as-is to this page.
General notes on how to use the emulators are added as well as basic qemu documentation.

### Testing procedure

Read the doc (remember there will be a preview in the CI checks)

### Issues/PRs references

based on #15512

### CODE REVIEW

**Comment by fjmolinas** [comment]
Looks like there are some unrelated changes.

**Comment by aabadie** [comment]
> Looks like there are some unrelated changes.

The PR is based on #15512, that's why

**Review by fjmolinas — APPROVED** [review]
ACK, documentation is good. Lets wait for the dependency to get merged.

**Comment by aabadie** [comment]
rebased, to solve conflicts

**Pull request merged**
