### PR TITLE
netdev_ieee802154: add radio capabilities

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
Several radios include hardware acceleration for common MAC tasks (automatic ACK handling, automatic retransmissions, CSMA, automatic FCS, etc).
Since these are MAC tasks, the MAC layer needs a mechanism for discovering which tasks are already handled by the radio.

Here comes the concept of radio capabilities.

E.g:
```c
/* ieee802154_mac */

void _send(...) {
    netdev->driver->send(...);
    if(!(netdev->caps & NETDEV_IEEE802154_CAPS_FRAME_RETRIES)) {
        /* The radio does not handle the frame retransmission procedure. Use software logic */
        retrans_procedure();
    }
}
```
I took the caps that I think make more sense for RIOT. I added a typedef for caps so we don't have to change the API if the flags grow (e.g uint16_t to uint32_t).

This tends to be a common pattern (check [Linux IEEE802154 MAC](https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/include/net/mac802154.h#L95) and [OpenThread caps](https://github.com/openthread/openthread/blob/ae04d5928030b809c72dd710f0c2a00d847aaa3f/include/openthread/platform/radio.h#L119))
I didn't handle these caps as NETOPT because it's assumed a radio can enable or disable a feature if it exists but not otherwise. E.g it's indeed possible to disable the automatic ACK procedure while in extended mode of the driver (at82rf2xx), but the radio is still capable of handling ACKs. 

This is required in order to implement components of the IEEE802.15.4 MAC and add basic mode support for radios.

### Testing procedure
- Check the capabilities for each radio match the datasheet/implementation
- `make doc`
- Check if the defined capabilities make sense

### Issues/PRs references
I will be updating this list on the run

#11150

### CODE REVIEW

**Comment by miri64** [comment]
Mhhhh, since these are things that do not change at runtime: is there maybe a way how to figure this out at compile-time (ideally with keeping multi-device support and keeping code-duplication low ;-))?

**Comment by miri64** [comment]
> Mhhhh, since these are things that do not change at runtime: is there maybe a way how to figure this out at compile-time (ideally with keeping multi-device support and keeping code-duplication low ;-))?

Just tossing some ideas, but how about a link-layer specific "MAC driver" struct (names are just examples take from the flags, please don't consider them to be serious)?

```C
typedef struct {
    int tx_checksum(netdev_ieee802154_t *dev, ...);
    int csma(netdev_ieee802154_t *dev, ...);
    /* ... */
} netdev_ieee802154_mac_ops_t;
```

A driver then can set the once it supports in hardware to NOP, and otherwise use some common MAC implementation.

**Comment by miri64** [comment]
(question is: is this more memory saving than your proposal?)

**Comment by jia200x** [comment]
> A driver then can set the once it supports in hardware to NOP, and otherwise use some common MAC implementation.

Hmmm the only issue is the fact these functions (tx checksum, csma) are usually implemented in common code on top of the driver. So, 3 transceiver without hardware FCS calculation will need to either implement this `tx_checksum(...)` function or point it to a common ieee802154_mac_tx_checksum()`. Hence, I tend to think a flag is more lightweight.

Opinions?

**Comment by PeterKietzmann** [comment]
The flag based indication for feature availability seems more intuitive to. The other way around would lead to many "NOP" calls on our devices that often implement many features in hardware, or am I mistaken? However, I don't think that this PR is very urgent to merge unless we don't have the MAC implementation that uses it, so we could IMO wait until then.

**Comment by jia200x** [comment]
Since #12070 is out, this PR starts to block :). I'm adding ACK support on top of the radios, and I need to know if a radio supports automatic ACK or not.
Someone minds to give it a try? :) It should be very easy to review

**Comment by bergzand** [comment]
At the moment I think the flag based approach is fine. However, I think it would be good to have a few (`static inline`) wrapper functions to check for these flags. If, in the future, we have to change to a more complex function-based approach only the wrapper functions needs to be adapted.

**Comment by bergzand** [comment]
> ```c
> netdev->caps & NETDEV_IEEE802154_CAPS_FRAME_RETRIES
> ```

This would be something like:
```C
netdev_has_caps(netdev, NETDEV_IEEE802154_CAPS_FRAME_RETRIES)
```

which would be implemented along the lines of:
```C
static inline bool netdev_has_caps(netdev_t *netdev, netdev_flags_t flag)
{
    return netdev->caps & flag;
}
```

**Comment by jia200x** [comment]
@bergzand I like the idea.

**Comment by jia200x** [comment]
Added `netdev_ieee802154_has_cap` function, as requested by @bergzand

**Comment by jia200x** [comment]
This one is not needed for now, so I will close it.

**Pull request closed without merging**
