### PR TITLE
gh_action: exclude tests/periph_timer_periodic from test-on-iotlab

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

The python test script seems to have timing issues when launched from the github actions environment. Most of the boards are failing reliably([example on nrf52dk](https://github.com/RIOT-OS/RIOT/runs/1948186596?check_suite_focus=true)) every week.

I tried locally, or on IoT-LAB, with compile_and_test_for_board used on my computer and I'm not able to reproduce at all.

My guess is that the github actions are running in a virtualized environment and time measured by Python is very imprecise in this context.

### Testing procedure

The test application is skipped when launched via the test-on-iotlab action.

### Issues/PRs references

None

### CODE REVIEW

**Comment by fjmolinas** [comment]
@aabadie you mentioned to me offline something about github action workers being windows machines and that could be the issue, id its the case do you have some reference we could point to in the PR? You also mentioned that increasing the margin worked, can you also mention this.

**Comment by aabadie** [comment]
> you mentioned to me offline something about github action workers being windows machines and that could be the issue

That was a guess. I think those are Linux systems running in virtual machines, see [this repository](https://github.com/actions/virtual-environments). I'm not sure if/why this has an impact on python timing measurements.

> You also mentioned that increasing the margin worked, can you also mention this.

I tried that in [this commit](https://github.com/aabadie/RIOT/commit/84c8aceaa02a804b53eff2da218221667c88ee9f) but wasn't able to reproduce such timing differences when testing on iot-lab from my local machine (the python script executing locally). The only difference was the environment (gh actions != local PC).
Only a 15% error tolerance was working reliably and I think that's too much to be honest and this error doesn't come from the hardware.

**Comment by fjmolinas** [comment]
@benpicco I think you wrote the test, any extra input here? Otherwise, I'm fine with removing but maybe add a reference in the release tests that these tests are not run on iotlab.

**Comment by benpicco** [comment]
Does it help to widen the error margin in `01-run.py`?
I'm not as much concerned about accuracy as the test working at all here.

**Comment by fjmolinas** [comment]
> Does it help to widen the error margin in `01-run.py`?
> I'm not as much concerned about accuracy as the test working at all here.

@aabadie increased the error margin to 15% which seems like a lot.

**Comment by benpicco** [comment]
I mean yea, the periodic timer should be a lot more accurate than any software timer, that's the whole point - but there are many more ways to break the timer so it would not tick at all / crash than to make it tick at a wrong frequency. (And any reconfiguration would typically cause a greater deviation)

So I'd rather keep a test that can detect 90% of all failures than dropping the test entirely.

**Comment by fjmolinas** [comment]
@aabadie so how about we use https://github.com/aabadie/RIOT/commit/84c8aceaa02a804b53eff2da218221667c88ee9f but set t a lower value, that can be overridden by the environment, and in the github action we lower the requirement for the iot-lab test?

**Comment by miri64** [comment]
Would it help to print the current timestamp in ticks (or even micro seconds when conversion is known) within the test application and have the differences of those be checked by the python script instead of fiddling around with timings in both frontend and backend?

**Comment by miri64** [comment]
https://github.com/RIOT-OS/RIOT/blob/dc8b96f7a6b8b02f3e6710c2515f01c976d0047f/tests/periph_timer_periodic/tests/01-run.py#L15-L18

This basically amounts to: stop time between when `pexpect` (which uses SSH, which uses socat over TCP, which uses serial on the `test-on-iotlab` tests) finds `TEST START` and `TEST SUCCEEDED` in the output. There are so many things beyond the actual output that can happen between those things, that I wouldn't count the measure to be accurate by any means.

**Comment by aabadie** [comment]
> This basically amounts to: stop time between when pexpect (which uses SSH, which uses socat over TCP, which uses serial on the test-on-iotlab tests) finds TEST START and TEST SUCCEEDED in the output. There are so many things beyond the actual output that can happen between those things, that I wouldn't count the measure to be accurate by any means.

True, but keep in mind that the first assert was failing: the one checking that the total time is **at least** 250ms and all these things should only add extra time, so one would expect the upper bound (400ms) would break and it was not the case.

**Comment by miri64** [comment]
> True, but keep in mind that the first assert was failing: the one checking that the total time is **at least** 250ms and all these things should only add extra time, so one would expect the upper bound (400ms) would break and it was not the case.

No, not necessarily. If `TEST START` comes in late for what ever reason (key exchange, flow or congestion control in TCP, ...) but `TEST SUCCEEDED` comes in more real-time-like (by luck or maybe even deterministicly due to some underlying state), the difference of time can be shorter than expected.

**Comment by aabadie** [comment]
> So I'd rather keep a test that can detect 90% of all failures than dropping the test entirely.

I'll add the commit with the error tolerance, 0 by default and bump it to 20% when launched inside the test-on-iotlab github actions. I agree that this is better than completely skip it.

**Comment by aabadie** [comment]
I changed that PR as suggested by @benpicco and @fjmolinas

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by miri64** [comment]
Now that the test is changed, I would prefer the test to be run in the CI. Also @aabadie can you start a test run of the workflow in your fork, to see if it now passes (if that was the goal here and there are not more issues).

**Comment by fjmolinas** [comment]
> Now that the test is changed, I would prefer the test to be run in the CI. Also @aabadie can you start a test run of the workflow in your fork, to see if it now passes (if that was the goal here and there are not more issues).

yes you are right I was a bit premature, and will run tests on my side as well

**Comment by fjmolinas** [comment]
All the BOARD's I have are passing https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/240/artifact/

**Comment by miri64** [comment]
I would still prefer a run in the Github actions as well. Sadly, since there is a change to the workflow file itself this can only be done by @aabadie in his fork.

**Comment by aabadie** [comment]
[First attempt](https://github.com/aabadie/RIOT/runs/1961423217?check_suite_focus=true) is still failing (and you have some numbers), so increased the error precision to 0.30.

**Comment by aabadie** [comment]
[Works better](https://github.com/aabadie/RIOT/runs/1961479084?check_suite_focus=true) with 0.30. Ok to squash ?

**Comment by miri64** [comment]
Yes please!

**Pull request merged**
