### PR TITLE
unittests: Move at test to driver tests

### PR DESCRIPTION
**Pull request by Teufelchen1**
### Contribution description

Hi 🦜

This moves the unit test for the at driver into the folder for driver tests. The test accesses/depends on hardware which is not valid for a unit test.

Further, the original test disabled `UART_DEV(0)` which I changed to `UART_DEV(1)`. This is needed as some boards use device zero for stdio and you can not have a good testing experience without stdio. 
**Please** provide feedback on this workaround, I am unsure on the quality of it. 

### Testing procedure

Running `make -C tests/drivers/at_unit/ all flash` should provide this output upon success:
```
# main(): This is RIOT! 
# AT unit-like test
# 
# .......
# OK (7 tests)
```

### Issues/PRs references

Introduced in commit 63e057c by PR #20423

### CODE REVIEW

**Comment by kfessel** [comment]
you are right even thought the test itself does not make use of the uart the driver/at that it tests depend on it 

@derMihai might have some thoughts

**Review by chrysn — APPROVED** [review]
It's weird that there is a device involved that just gets turned off, but aparently that's how at_dev_init works (can't pass it the none-device), but that's beyond the scope of fixing it.

I don't know the precise workings of the AT module or this test, but as the test passes (doing things) for you, I think it's good.

**Comment by Teufelchen1** [comment]
C is such a magic. A test that compiles and runs fine on my machine, suddenly misses a header on the CI.
@chrysn, I won't be able to fix that today (or even this weekend) could you fix up my branch? 👉 👈 Hardfreeze is on monday...

**Comment by chrysn** [comment]
Fixup passed. Let's try if I can force push too (not sure it really worked); at any rate, I'll let you do the merge pushing so you confirm my one-line addition.

**Comment by miri64** [comment]
Ah, please update the Makefile.ci with the `arduino-duemilanove`. It is too large for that board.

**Comment by chrysn** [comment]
This'll need Makefile.ci, building it already.

**Comment by miri64** [comment]
(maybe even more, but the full build stopped there)

**Comment by derMihai** [comment]
This PR does break a few things, see https://github.com/RIOT-OS/RIOT/pull/20551.

**Pull request merged**
