### PR TITLE
[backport] Gpio Interrupt fix for the CC2538

### PR DESCRIPTION
**Pull request by AnonMall**
CC2538 gpio interrupt fix, where the interrupt has not been properly acknowledged

### CODE REVIEW

**Comment by aabadie** [comment]
Is it the backport from #7303 ? Then I think there's something wrong: the commit is not the same (correct me if I'm wrong).
The right process is to open PR of the same branch PR'ed in #7303 to 2017.07-branch. Then same commit hash ensure the changes are the same.

Second problem: prefix the PR title with [backport] and give the same title.

Please re-open another one.

**Comment by aabadie** [comment]
Sorry, looking at #7283, the commit were different there as well. So I'm wondering what is the correct procedure here. Cherry-pick ? Direct PR of initial branch ?

**Comment by smlng** [comment]
@aabadie I think this backport is fine, it matches #7303 though the commit hash is different. Me personally made that mistake when backporting in the past, too. 

@AnonMall: either create a new branch based on release-branch and cherry-pick your fix-commit or rebase the original fix-branch onto the release-branch, would do I guess. 

Anyhow, I ACK this!

**Comment by aabadie** [comment]
Ok, thanks @smlng, then we can merge after Murdock is green.

**Comment by miri64** [comment]
> The right process is to open PR of the same branch PR'ed in #7303 to 2017.07-branch. Then same commit hash ensure the changes are the same.

Just to shed some git knowledge: that's impossible. 2017.07-branch and master have now diverged, so rebaseing the commit in #7303 will always result in a different commit hash, since it will have a different parent. Remember: the hash is generated from an objects content, and [a commit object consists of the tree's hash it s pointing to, the hash of the parent(s) and commit and author date](https://git-scm.com/book/fr/v2/Les-tripes-de-Git-Les-objets-de-Git#_git_commit_objects).

> Sorry, looking at #7283, the commit were different there as well. So I'm wondering what is the correct procedure here. Cherry-pick ? Direct PR of initial branch ?

The way it is done here. If you don't trust your eyes make a diff to the respective merge base and get a hash of that (`git diff $(git merge-base <base-branch> <PR-branch>) | sha1sum`)

**Comment by smlng** [comment]
@miri64 thanks for clearing things up - it was my (intuitive) understanding (but wasn't 100% sure) as well that is impossible to have the same commit hash with two different parent-branches.

**Comment by miri64** [comment]
(cherry-picking internally is the same as rebasing btw, just done manually)

**Comment by aabadie** [comment]
That was my intuition as well, but I was ensure if I missed something in the RIOT procedure.

**Pull request merged**
