### PR TITLE
make: Makefile.include: Remove -Wno-implicit-fallthrough

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

These flags should hopefully not be necessary now.

### Issues/PRs references

Introduced in #8603, #8617

### CODE REVIEW

**Comment by cladmi** [comment]
It is strange, the errors are places with "falls through" statements.
Also I have the same `arm-none-eabi-gcc` version as said in `static-test` and I do not get errors on my computer.

Could some workers have a different version than the one running `static-test` ? @smlng 

If not, it maybe requires a more safe proof falls through comment.

**Comment by cladmi** [comment]
I really do not get why it is not building… I do not get any error on my computer.

**Comment by kaspar030** [comment]
This is for mobi3 (failed asymcute_mqttsn on acd52832):

```
[kaspar@ng riot (master)]$ dwqc -q mobi3.inet.haw-hamburg.de './dist/tools/ci/print_toolchain_versions.sh'                           
Installed compiler toolchains
-----------------------------
             native gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609                                                          
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
                avr-gcc: avr-gcc (GCC) 4.9.2
       mips-mti-elf-gcc: mips-mti-elf-gcc (Codescape GNU Tools 2016.05-03 for MIPS MTI Bare Metal) 4.9.2                             
             msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)                                             
   riscv-none-embed-gcc: riscv-none-embed-gcc (GNU MCU Eclipse RISC-V Embedded GCC, 64-bits) 7.2.0                                   
                  clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)                                                       

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "2.5.0"
    mips-mti-elf-newlib: "2.1.0"
riscv-none-embed-newlib: "2.5.0"
               avr-libc: "1.8.0svn" ("20111229")

Installed development tools
---------------------------
                  cmake: cmake version 3.10.0
               cppcheck: Cppcheck 1.72
                doxygen: 1.8.11
                 flake8: missing
                    git: git version 2.7.4
             coccinelle: spatch version 1.0.4 with Python support and with PCRE support                                              
[kaspar@ng riot (master)]$ 
```

**Comment by kaspar030** [comment]
> This is for mobi3 (failed asymcute_mqttsn on acd52832):

well, accidentaly that is also the one printing the static test output for the last build.

**Comment by kaspar030** [comment]
If you scroll all the way down in the build output, you'll see that the failures are spread across all workers.

**Comment by gebart** [comment]
So why does it fail? Is it a gcc 5 thing?

**Comment by gebart** [comment]
After reading #9398 it seems like this error must be the same ccache problem that the clang builds have. The preprocessor is run separately from the compilation stage and therefore the `/* falls through */` comments are not visible to the compiler and therefore we get an error. Modifying the ccache configuration to run the preprocessor twice should fix the errors seen in this PR.

**Comment by gebart** [comment]
Setting CCACHE_CPP2=yes fixed the problem with the compiler incorrectly reporting Wimplicit-fallthrough errors for intentional fall through.
Ping @cladmi @kaspar030 @miri64

**Comment by kaspar030** [comment]
> Setting CCACHE_CPP2=yes fixed the problem with the compiler incorrectly reporting Wimplicit-fallthrough errors for intentional fall through.

Nice to have found the cause, too bad we need that setting also for gcc, as this has non-negligable impact on compilation speed when using CCACHE.

**Comment by cladmi** [comment]
It had a 2:37 minutes impact to do the `CCACHE_CPP2=yes` by comparing #9772 with this one. Current runtime: 13m:11s 

But, in practice it should be less I think.

Now this PR is build with the cache from the other PRs that do not set CCACHE_CPP2. So basically there should be more cache miss than what would be at the end when all PRs use this one and the cache is warm everywhere.

**Comment by miri64** [comment]
> Nice to have found the cause, too bad we need that setting also for gcc, as this has non-negligable impact on compilation speed when using CCACHE.

Well, sometimes correctness should take precedence over speed :clown_face:

**Comment by kaspar030** [comment]
This should be good to go, right?

**Pull request merged**
