### PR TITLE
drivers/mtd_spi_nor: fix init when only ztimer_msec is used

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

If only `ztimer_msec` (and not `ztimer_usec`) is used, the `mtd_spi_nor_power()` function will not execute the `wait_chip_wake_up` delay.

This causes `mtd_init()` to fail (and in a very annoying way: adding debug prints can cause enough of a delay that the init then works again).

### Testing procedure

`tests/drivers/mtd_raw`  should work with only `ztimer_msec`  instead of `ztimer_usec`.

### Issues/PRs references

wouldn't have happened if we had #19719

### CODE REVIEW

**Comment by viktorbatista** [comment]
Should we not add an #else so in case neither xtimer nor ztimer m/usec are used it outputs an error (or at least a warning of some sorts)?

**Comment by fabian18** [comment]
If the driver needs either ztimer [ms/us] or xtimer, why is there no such logic in the Makefile.dep?

**Comment by benpicco** [comment]
The idea is to have a polling fallback for e.g. use in `riotboot`.
But then the number of retries needs to be increased in that case.

**Review by fabian18 — APPROVED** [review]
ACK

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
