### PR TITLE
boards/nucleo144-f446: add initial support

### PR DESCRIPTION
**Pull request by aabadie**
I also have this one on my desk :)

It has small differences with the nucleo-f446 (64 pins).

### CODE REVIEW

**Comment by kYc0o** [comment]
@astralien3000 If you have time could you test this board? Code looks OK. While testing can you also run the unittests? (in tests/unittests, `make flash term`)

**Comment by aabadie** [comment]
@kYc0o, I fixed a build issue since #6714 is now merged and also removed the commit related to saul (since #6705 will do that)

**Comment by kYc0o** [comment]
OK, let's see what Murdock says.

**Comment by astralien3000** [comment]
I tested `default`, and I can't get the user button's state with saul.

**Comment by aabadie** [comment]
This is because it's not exported via Saul. Only LED0 is for the moment. #6705 will do that.

**Comment by astralien3000** [comment]
@kYc0o, are the unittests supposed to print something ?

**Comment by astralien3000** [comment]
I tested default, periph_uart, periph_timer and xtimer_usleep, everything is ok

**Comment by aabadie** [comment]
@astralien3000, the button issue can be related to this  [comment](https://github.com/RIOT-OS/RIOT/pull/6705#pullrequestreview-25465158) because it is actually exposed via saul. #6705 will fix this BTW.
I also noticed a wrong alphabetical order of the features exposed by the board. Will fix.

**Comment by kYc0o** [comment]
@astralien3000 yes it should print that all test passed, if not, something is wrong and we need to see what.

**Comment by aabadie** [comment]
@astralien3000 I rebased on latest master with #6705 inside. The button should work with saul and 3 leds are also exposed. Can you try again ?

**Comment by astralien3000** [comment]
@aabadie, done, everything is ok with saul in default example
@kYc0o, so, unittests is not working

**Comment by astralien3000** [comment]
I retested unittests with the newest commits, and everything is good

**Comment by aabadie** [comment]
@kYc0o, I think you can now press the green button, right ?

**Comment by kYc0o** [comment]
If everything is good, let's go.

**Pull request merged**
