### PR TITLE
tests: unify pktbuf expect for emptiness check

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
How a NULL pointer is represented by `printf()` differs from platform to platform. Sometimes it's `(nil)`, sometimes `0x0` (with varying length of 0s attached), and sometimes just `0`. This unifies the expect for that in the testing scripts.

### Testing procedure
Run the tests changed on a handful of platforms. They should still pass (some require `sudo` and or TAP interfaces!).

### Issues/PRs references
Addresses https://github.com/RIOT-OS/RIOT/pull/11108#issuecomment-545408811

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
```c
static inline void _print_unused(_unused_t *ptr)
{
    printf("~ unused: %p (next: %p, size: %4u) ~\n", (void *)ptr,
           (void *)ptr->next, ptr->size);
}
```

Is the cause for the difference a compiler specific thing?

**Comment by miri64** [comment]
> ```c
> ```c
> static inline void _print_unused(_unused_t *ptr)
> {
>     printf("~ unused: %p (next: %p, size: %4u) ~\n", (void *)ptr,
>            (void *)ptr->next, ptr->size);
> }
> ```
> 
> 
> Is the cause for the difference a compiler specific thing?
> ```

I think more the different `libc`s are to blame here.

**Comment by MrKevinWeiss** [comment]
OK, I guess since the old esp implementation is just 0 and the new one is 0x0.

**Comment by cgundogan** [comment]
>>
    static inline void _print_unused(_unused_t *ptr)
    {
        printf("~ unused: %p (next: %p, size: %4u) ~\n", (void *)ptr,
               (void *)ptr->next, ptr->size);
    }

    Is the cause for the difference a compiler specific thing?

>I think more the different libcs (and newlib-variants) are to blame here.

It would be far better to unify the output in https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c#L280. Check for NULL explicitly and print a well-defined NULL indication .. otherwise we will see this problem again and again with libc/newlib updates ..

**Comment by miri64** [comment]
> It would be far better to fix the output in https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c#L280. Check for NULL explicitly and print a well-defined NULL indication .. otherwise we will see this problem again and again with libc/newlib updates ..

This is not just a `pktbuf` problem... This is a problem of pointer representation with `printf` in general.

**Comment by cgundogan** [comment]
For this particular case you only touch expect statements that match against the `pktbuf` output. I am just saying that it is more robust and less error-prone to solve this particular issue at the source, not at the very end of the tests chain.

**Comment by miri64** [comment]
You mean something like

```
diff --git a/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c b/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
index ba2101e1d..86831fb2e 100644
--- a/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
+++ b/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
@@ -275,10 +275,23 @@ static inline void _print_chunk(void *chunk, size_t size, int num)
     od_hex_dump(chunk, size, OD_WIDTH_DEFAULT);
 }
 
+static inline void _print_ptr(_unused_t *ptr)
+{
+    if (ptr == NULL) {
+        printf("(nil)");
+    }
+    else {
+        printf("%p", (void *)ptr);
+    }
+}
+
 static inline void _print_unused(_unused_t *ptr)
 {
-    printf("~ unused: %p (next: %p, size: %4u) ~\n", (void *)ptr,
-           (void *)ptr->next, ptr->size);
+    printf("~ unused: ");
+    _print_ptr(ptr);
+    printf(" (next: ");
+    _print_ptr(ptr->next);
+    printf(", size: %4u) ~\n", ptr->size);
 }
 #endif
```

Not sure how thread-safe this is or how it affects existing tests.

**Comment by cgundogan** [comment]
>You mean something like

Yeah, the patch reflects exactly what I meant

>

>Not sure how thread-safe this is or how it affects existing tests.

Well, printf is not thread-safe anyway (: and for the existing tests: I assume you touched them all anyways with this current PR? Changing them to match against "(nil)" makes also reading the tests much clearer, and we wouldn't need to drag this regex to future test scripts.

**Comment by miri64** [comment]
> Well, printf is not thread-safe anyway (: and for the existing tests: I assume you touched them all anyways with this current PR? Changing them to match against "(nil)" makes also reading the tests much clearer, and we wouldn't need to drag this regex to future test scripts.

Not the ones in the release specs ;-P

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/12555 for the alternate approach.

**Comment by MrKevinWeiss** [comment]
I am in favor of this one but as long as there is a fix I am happy.  @cgundogan any strong opinions?

**Comment by miri64** [comment]
BTW, the regex as I use it here is already used like that in master in `tests/gnrc_ipv6_fwd_w_sub/tests/01-run.py` ;-)

**Comment by miri64** [comment]
Yah!

**Pull request closed without merging**
