### PR TITLE
sys/fmt: add print_bytes_hex()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Pretty straightforward function to print a byte buffer

### CODE REVIEW

**Review by jue89 — APPROVED** [review]
I wonder why this hasn't been around before ... :D

Did a quick test - works like expected.

**Comment by benpicco** [comment]
eh is that realy needed for such a trivial function?

**Comment by aabadie** [comment]
> eh is that realy needed for such a trivial function?

who knows what can happen ? It's also trivial to add the corresponding test and to be safe

**Comment by benpicco** [comment]
> It's also trivial to add the corresponding test and to be safe

eh we only have `unittests/tests-fmt` which can't test the `pint_()` functions so we'd need a whole new dedicated test application for this.

**Comment by kaspar030** [comment]
> eh we only have `unittests/tests-fmt` which can't test the `print_*()` functions so we'd need a whole new dedicated test application for this.

there's `tests/fmt_print` which could be extended. but I agree that the function is rather trivial.

**Comment by benpicco** [comment]
Ah I didn't see that one.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Pull request merged**
