### PR TITLE
samd21/clock: add OSCULP32K/DFLL option

### PR DESCRIPTION
**Pull request by Hyungsin**
This PRR adds OSCULP32K/DFLL clock option for samd21.
This also allows xtimer to use 32kHz OSCULP32K/RTT timer to provide low power sleep mode.  

@thomaseichinger may be a good reviewer.

### CODE REVIEW

**Comment by photonthunder** [comment]
PR #7315 attempts to address the need for having different sources running different peripherals.  It would make your additions even easier because then you could just add an option to use the OSCULP32k instead of XOSC32k (rather then duplicate so much code).  It also sets up OSCULP32k as gen3.

**Comment by Hyungsin** [comment]
@photonthunder, Cool.
Then I need to rework after #7315 is merged.

**Comment by Hyungsin** [comment]
Any review here?

**Comment by Hyungsin** [comment]
Is it possible to merge this PR before #7315?

**Pull request closed without merging**
