### PR TITLE
tests/congure-turo: reset before opening terminal

### LINKED ISSUE #16415: riotctrl: shell interaction seems timing sensitive
#### Description

`tests/turo` and `tests/congure_test`fail on samr21-xpro since the programmer wrapper has been disabled.
A simple delay fixes the issue: https://gist.github.com/kaspar030/a3022c79e4ed07ec82b91a988db5b4cb

#### Steps to reproduce the issue

`BOARD=samr21-xpro make -Ctests/turo flash test`

#### Expected results

tests succeed

#### Actual results

tests fail

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Some BOARD terminal is slow to start so if the BOARD is reset after
opening the terminal this can lead to off-by-one error when parsing
the output.

So instead do as testrunner and reset before opening the terminal.
Note that no interactive_sync is needed since a similar mechanism
happens in ShellInteraction.

### Testing procedure

- Murdock should now be green

- Ran the tests on a list of [BOARD's](https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/271/artifact/), (atmega based boards failures are unrelated to this PR, and `ek-lm4f120xl` failed to flash, and `z1` fails to boot the firmware on master as well)

### Realted issues

fixes  #16415

### CODE REVIEW

**Comment by miri64** [comment]
Can you please split this PR into two commits? One for each test? Also it is spelled `congure` ;-). Otherwise I am fine with this change and it seems to fix the issue in the latest nightlies.

**Comment by fjmolinas** [comment]
split

**Review by miri64 — APPROVED** [review]
ACK

**Comment by miri64** [comment]
Thanks for fixing this @fjmolinas!

**Pull request merged**
