### PR TITLE
gnrc_netdev2: harmonize naming scheme to rest of GNRC

### PR DESCRIPTION
**Pull request by authmillenon**
Always am confused, when I search something related to `gnrc_netdev2.h`. Now no more. Used

```sh
git mv sys/include/net/gnrc/gnrc_netdev2.h sys/include/net/gnrc/netdev2.h
mkdir -p sys/include/net/gnrc/netdev2
git mv sys/include/net/gnrc/gnrc_netdev2_eth.h sys/include/net/gnrc/netdev2/eth.h
git grep --name-only "gnrc_netdev2\.h" | xargs sed -i 's:gnrc_netdev2\.h:netdev2.h:g'
git grep --name-only "gnrc_netdev2_eth\.h" | xargs sed -i 's:gnrc_netdev2_eth\.h:netdev2/eth.h:g'
```

to achieve this.

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK when Travis agrees.

Just a side question: shouldn't `netdev2` be gnrc agnostic?

**Comment by OlegHahm** [comment]
Isn't this the gnrc adaption layer for netdev2?

**Comment by authmillenon** [comment]
Yes.

**Comment by authmillenon** [comment]
Fixed travis' issue with native. Will fix unrelated doc issues in `netdev2.h` in separate PR.

**Comment by authmillenon** [comment]
See #4352

**Pull request merged**
