### PR TITLE
drivers/boards: unused SPI CS pins should use SPI_CS_UNDEF

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by lebrush** [comment]
looks pretty obvious change, I didn't try to compile whatsoever, let's leave that to Murdock :-) 

However, I think you forgot some though, because I see 44 changes in this PR but running 
`git show -m 513b20ffd328934c58af169e2bce0c0a01eddee2 | grep GPIO_UNDEF | wc -l` I get 58 (3 of them are irrelevant though, not sure about the rest... or if they got fixed somewhere else). You've to find 11 still :-P

One file I so checking the changes on the other PR is `boards/arduino-due/include/sdcard_spi_params.h`.

**Comment by kYc0o** [comment]
I think Jenkins spotted the 11 boards remaining...

**Comment by lebrush** [comment]
@haukepetersen please rebase and apply https://github.com/lebrush/RIOT/commit/d1229d686d76cd3f3202daf9d6b5b5493ff4cfef

**Comment by haukepetersen** [comment]
rebased

**Comment by lebrush** [comment]
Needs squash as wel :-)

**Comment by aabadie** [comment]
ping @haukepetersen, look like this one is very close to being merged.

**Comment by haukepetersen** [comment]
Yes, it does look so, but there is a systematic problem of include dependencies that blocks the progress... I am working on fixing the include hierarchy for CPUs first, so that this PR will work...

**Comment by smlng** [comment]
postponed, but also rebase please.

**Comment by haukepetersen** [comment]
will not rebase until the underlying problem is solved :-)

**Comment by kaspar030** [comment]
> will not rebase until the underlying problem is solved :-)

is there an issue for that?

**Comment by tcschmidt** [comment]
@haukepetersen want to discuss the problem with @cladmi ?

**Comment by smlng** [comment]
ping again!

**Comment by benpicco** [comment]
What's the advantage of this?

**Pull request closed without merging**
