### PR TITLE
at86rf2xx_netdev: debug output is wrong

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK and go when Murdock is happy.

**Comment by authmillenon** [comment]
Do we want to provide a backport for this?

**Comment by OlegHahm** [comment]
I don't think it's necessary, but no strong opinion.

**Comment by kaspar030** [comment]
maybe fix the commit message?

**Comment by OlegHahm** [comment]
done

**Comment by OlegHahm** [comment]
(do we need a spellchecker for Murdock? ;-))

**Pull request merged**
