### PR TITLE
cpu: samd21: fix synchronization loop in clk_init

### PR DESCRIPTION
**Pull request by kaspar030**
fixes
<pre>
"make" -C /home/kaspar/src/riot.9/cpu/samd21
/home/kaspar/src/riot.9/cpu/samd21/cpu.c: In function 'clk_init':
/home/kaspar/src/riot.9/cpu/samd21/cpu.c:68:67: warning: comparison of constant '3u' with boolean expression is always false [-Wbool-compare]
            (SYSCTRL_DPLLSTATUS_CLKRDY | SYSCTRL_DPLLSTATUS_LOCK)) ==
                                                                   ^
/home/kaspar/src/riot.9/cpu/samd21/cpu.c:68:67: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
</pre>

### CODE REVIEW

**Comment by kaspar030** [comment]
@haukepetersen Is the condition still correct?

**Comment by haukepetersen** [comment]
Yap, again one of these code parts where you wonder what you did.. ACK once Travis is green.

**Comment by haukepetersen** [comment]
kicked Travis.

**Comment by bapclenet** [comment]
Kicked Travis again, should be ok soon

**Comment by bapclenet** [comment]
Travis ok, merged

**Pull request merged**
