### PR TITLE
lpc2387: Add missing exception tables to linker script

### PR DESCRIPTION
**Pull request by gebart**
Copied from kinetis_common

Found during build test of #3115

### CODE REVIEW

**Comment by gebart** [comment]
rebased after #3120 was merged.

**Comment by gebart** [comment]
Could someone with an msba2 board, or other lpc2387, test this to make sure it still runs?

**Comment by gebart** [comment]
Who has an msba2, pttu or avsextrem board available for testing?

**Comment by OlegHahm** [comment]
Sorry, won't be able to test for the next 2,5 weeks. There are some MSB-A2 boards at FU Berlin (@haukeptersen, @kaspar030) and at HAW (@BytesGalore, @Lotterleben).

**Comment by gebart** [comment]
It would be nice if we could get this merged in time for release 2015.06. This issue blocks C++ support on those boards.

**Comment by gebart** [comment]
ping @BytesGalore

**Comment by BytesGalore** [comment]
wow sorry, missed this one.
Will test now

**Comment by BytesGalore** [comment]
ok so far, 
- the basic examples without c++ work on the msba2
- the simple `example\riot_and_cpp` also works

building `tests/cpp11_*` generates the same errors with and without this PR:
```
/RIOT/tests/cpp11_mutex/bin/msba2/cpp11_mutex.a(main.o): In function `std::__atomic_base<unsigned int>::operator--()':
/gcc-arm-none-eabi-4_9-2015q1/arm-none-eabi/include/c++/4.9.3/bits/atomic_base.h:416: undefined reference to `__atomic_fetch_sub_4'
/gcc-arm-none-eabi-4_9-2015q1/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/lib/libstdc++.a(system_error.o): In function `_GLOBAL__sub_I__ZNSt14error_categoryD2Ev':
system_error.cc:(.text.startup._GLOBAL__sub_I__ZNSt14error_categoryD2Ev+0x30): undefined reference to `__dso_handle'
/gcc-arm-none-eabi-4_9-2015q1/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: /home/user01/Schreibtisch/RIOT/tests/cpp11_thread/bin/msba2/cpp11_thread.elf: hidden symbol `__dso_handle' isn't defined
/gcc-arm-none-eabi-4_9-2015q1/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/RIOT/tests/cpp11_thread/../../Makefile.include:186: recipe for target 'all' failed
make: *** [all] Error 1
```
but they seem unrelated (or only related to my compiler version)
will test additionally with code sourcery.

**Comment by BytesGalore** [comment]
ok, its the same for the code sourcery compiler gcc version 4.8.3 20140320 (prerelease) (Sourcery CodeBench Lite 2014.05-28) [1]
(The one before was compiled the launchpad version)

[1] https://github.com/RIOT-OS/RIOT/wiki/Family:-ARM#codebench-for-linux

**Comment by gebart** [comment]
The C++11 examples are not expected to run with this change alone, but this PR is a prerequisite for #3107 
@BytesGalore Do I have your ACK for this change?

**Comment by BytesGalore** [comment]
@gebart In that case yes, ACK :)

**Pull request merged**
