### PR TITLE
cpu/samX: remove guards from periph drivers

### LINKED ISSUE #7981: periph: remove file guards from peripheral drivers
follow up on #7241

Since #7241 was merged, there is no need anymore for ugly file guards around peripheral driver implementations, as they are now finally only touched by the compiler if they are actually (a) included in the build (using USEMODULE) and (b) provided by a board/cpu (as in FEATURES_PROVIDED). So now it is time to clean up a little bit, and this issue should help so we don't forget anything.

Removed file guards from peripheral drivers in:
- [x] arm7_common
- [x] atmega1281
- [x] atmega2560
- [x] atmega328p
- [x] atmega_common (#8959)
- [x] cc2538 (#8955)
- [x] cc26x0
- [x] cc430
- [x] cortexm_common
- [x] efm32
- [x] ezr32wg
- [x] k22f
- [x] k60
- [x] k64f
- [x] kinetis_common (-> @gebart, #7882)
- [x] kw2xd
- [x] lm4f120 (#8958)
- [x] lpc1768 (#8956) (-> @aabadie, #8956)
- [x] lpc2387 (#8957)
- [x] mips32r2_common
- [x] mips_pic32_common
- [x] mips_pic32mx
- [x] mips_pic32mz
- [x] msp430_common
- [x] msp430fxyz
- [x] native
- [x] nrf51 (-> @haukepetersen, #7982)
- [x] nrf52 (-> @haukepetersen, #7982)
- [x] nrf5x_common (-> @haukepetersen, #7982)
- [x] sam0_common ( -> @haukepetersen, #7984)
- [x] sam3 ( -> @haukepetersen, #7984)
- [x] sam_common
- [x] samd21 ( -> @haukepetersen, #7984)
- [x] saml21 ( -> @haukepetersen, #7984)
- [x] stellaris_common
 - [x] stm32_common (-> @haukepetersen, #7983)
 - [x] stm32f0 (-> @haukepetersen, #7983)
 - [x] stm32f1 (-> @haukepetersen, #7983)
 - [x] stm32f2 (-> @haukepetersen, #7983)
 - [x] stm32f3 (-> @haukepetersen, #7983)
 - [x] stm32f4 (-> @haukepetersen, #7983)
 - [x] stm32f7 (-> @haukepetersen, #7983)
 - [x] stm32l0 (-> @haukepetersen, #7983)
 - [x] stm32l1 (-> @haukepetersen, #7983)
 - [x] stm32l4 (-> @haukepetersen, #7983)
- [x] x86

### PR DESCRIPTION
**Pull request by haukepetersen**
addresses #7981
same as #7982

### CODE REVIEW

**Comment by aabadie** [comment]
> fixed #7981 (partly)

The problem when writing this is that #7981 will be closed when this PR will be merged...

**Comment by dylad** [comment]
Changes look good. I'll give it a try later today.
Murdock complains about sam0 i2c but this should be fix with #7588

**Comment by haukepetersen** [comment]
@aabadie 'addresses' won't lead to automatic closing, right?

@dylad: thanks for reviewing. Will fix the cppcheck issues for now (temporarily) and #7588 can than take care of it for good...

**Comment by aabadie** [comment]
>  'addresses' won't lead to automatic closing, right?

`addresses` seems to be fine. I'm wondering if Github will take the change into account since you initially used `fixes`

**Comment by haukepetersen** [comment]
we'll see.

**Comment by dylad** [comment]
I tested this PR, I introduces some errors within driver & try to compile them. Errors are only show if I add the required `USEMODULE += periph_xxx`. It works like a charm.
There is no need to test it on real hardware right ?

**Comment by haukepetersen** [comment]
> There is no need to test it on real hardware right ?

I would say no. If I did anything wrong with this PR, it would IMHO only lead to failed builds (by building more stuff than necessary). So if everything still builds correctly, all should be in order.

**Comment by haukepetersen** [comment]
thanks a lot!

All green -> go

**Pull request merged**
