### PR TITLE
cpu/cortexm_common: Add support for Cortex-M interrupt sub-priorities

### PR DESCRIPTION
**Pull request by pekkanikander**
### Contribution description

This commit enables Cortex-M CPU interrupt sub-priorities and allows the PendSV interrupt to have a priority different from the default one.  Together these two new preprocessor defines can be used to have PendSV always run as the last interrupt, before returning from the interrupt stack back to the user space.

Running PendSV as the last interrupt before returning to the user space is recommended by ARM, as it increases efficiency.  Furthermore, that change enhances stability a lot with the new nRF52 SoftDevice support, currently being worked in PR #9473.

This commit merely enables sub-priorities and a separate PendSV priority to be used without changing the default RIOT behaviour.

### Testing procedure

As such, this should not change anything.  All the previous tests should run as before, and no new ones are introduced.

### Issues/PRs references

See also #9473 and https://github.com/RIOT-OS/RIOT/issues/10122

### CODE REVIEW

**Comment by gebart** [comment]
@pekkanikander Thanks for working on this!

I did not look into the code yet, but does this work the same way on all Cortex-M CPUs, even M0/M0+? Does it depend on any optional features in the NVIC or are all vendors the same here?

Background info: There are some features in other parts of the CPU which are mandatory on the CM3 and up, but optional on the CM0.

**Comment by pekkanikander** [comment]
@gebart Unfortunately I am not a definite expert here, but AFAIK and as far as I was able to check quickly, the patch is ok for all Cortex-M CPUs.  

Apparently Cortex-M0 doesn't have this feature, while Cortex-M3 and M4 do.  However, Cortex-M0 CMSIS does not implement `NVIC_SetPriorityGrouping`, so setting this on Cortex-M0 should lead to a compile-time error (though I haven't tested that.)

http://infocenter.arm.com/help/topic/com.arm.doc.dui0553a/Cihehdge.html
http://infocenter.arm.com/help/topic/com.arm.doc.dui0552a/Cihehdge.html
http://infocenter.arm.com/help/topic/com.arm.doc.dui0497a/Cihehdge.html

https://embeddedgurus.com/state-space/2014/02/cutting-through-the-confusion-with-arm-cortex-m-interrupt-priorities/

**Comment by gebart** [comment]
This looks ready. I will test and review tonight or tomorrow

**Comment by gebart** [comment]
Looks good I added one comment on the wording. Accidentally commented on the commit instead of on the PR, but it is visible above this post

**Comment by pekkanikander** [comment]
Changed the wording as suggested and squashed.

**Comment by pekkanikander** [comment]
What should be done with this?  No interest from RIOT side and so close?  Or someone should rebase?  (I don't have any recent RIOT tree on my laptop, since I haven't been working with RIOT for a while.)

**Comment by benpicco** [comment]
@pekkanikander this has already been approved, but there is a merge conflict that needs to be resolved before it can be merged.

**Comment by benpicco** [comment]
No change in default behavior, so no reason why we shouldn't have that option.

**Comment by pekkanikander** [comment]
@benpicco Thanks for taking care of this!  (I don't have RIOT build environment, so I couldn't have been able to rebase or test.)

**Pull request merged**
