### PR TITLE
cpu/efm32/periph: add DAC support for EFM32 Series 1 (VDAC)

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides a small change for `periph_dac` to support the VDACs of EFM32 Series 1 MCUs. It was tested with `sltb009a` board for which this PR includes the DAC configuration.

### Testing procedure

`tests/periph/dac` should work for the `sltb009a` board. I've tested it already.
```
BOARD=sltb009a make -j8 -C tests/periph/dac flash
```

### Issues/PRs references

Depends on PR #19886

### CODE REVIEW

**Review by aabadie — APPROVED** [review]

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
It seems other boards have to be adapted of something is missing. https://ci.riot-os.org/results/d24f504a91b54fb987d1606d97b9d409/output/builds/tests/drivers/bh1750/xg23-pk6068a:gnu.txt

**Comment by gschorcht** [comment]
Hm :thinking: the board for which the compilation failed is a EFM32 Series 2 board for which the VDAC driver is not yet implemented.

The problem seems to be that `em_vdac.h` is included only for EFM32 Series 1 in `periph_cpu.h` but the `VDAC_COUNT` variable that is used to decide whether to define the `dac_conf_t` struct using the `VDAC_RefType` is also defined for EFM32 Series 2 MCUs. For EFM32 Series 2 MCUs, however, `em_idac.h` is included in `periph_cpu.h` instead but I couldn't find any place where IDAC is used.

Maybe, EFM32 Series 2 VDACs also work with this PR. I don't have a EFM32 Series 2 board. Maybe @jue89 can help.

**Comment by gschorcht** [comment]
@aabadie I fixed the compilation error by including `em_vdac.h` also for EFM32 Series 2 MCUs which have VDACs if `VDAC_COUNT´ is defined. This shouldn't make any problem since the ´periph_dac` feature isn't enabled for the only board we have with a EFM32 Series 2 MCU. We can try to use the VDAC for this board later.

**Comment by aabadie** [comment]
please squash!

**Comment by gschorcht** [comment]
> please squash!

Done

**Comment by aabadie** [comment]
bors merge

**Comment by gschorcht** [comment]
@aabadie Thanks for reviewing and merging :smile:

**Pull request merged**
