### PR TITLE
scan-build: Add make goal for running Clang static code analyzer (ccc-analyzer)

### PR DESCRIPTION
**Pull request by gebart**
usage:
`make scan-build` will generate a report under `$PWD/scan-build/.....` and open it in the user's web browser of choice.

supported running inside a Docker container as well.

Some Docker fixes are included:
 - Pass TOOLCHAIN variable to container
 - Share `/etc/localtime` with container (the current time is used as a base for the output directory name, it gets confusing for the user when the time zone is wrong inside the container)
 - Sorted all environment variable names in Makefile.docker, for easier navigation
 - Detect if running inside Docker (avoid calling xdg-open inside the container)

### CODE REVIEW

**Comment by gebart** [comment]
@thomaseichinger could you test if this works on OSX?

**Comment by OlegHahm** [comment]
How do I execute this outside container? Just calling `make scan-build` gives me:
```
Performing Clang static code analysis using toolchain "".
env: scan-build: No such file or directory
/home/oleg/git/RIOT/Makefile.scan-build:61: recipe for target 'scan-build-analyze' failed
make: *** [scan-build-analyze] Error 127
```

**Comment by gebart** [comment]
you need to install clang
on Ubuntu:
`sudo apt-get install clang` (or `clang-3.5` or any other major version)

**Comment by OlegHahm** [comment]
clang is installed:
```
clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by gebart** [comment]
strange...

```
root@3af3cffb4fa1:/data/riotbuild# dpkg -L clang
/.
/usr
/usr/share
/usr/share/man
/usr/share/man/man1
/usr/share/doc
/usr/share/doc/clang
/usr/share/doc/clang/NEWS.Debian.gz
/usr/share/doc/clang/copyright
/usr/share/doc/clang/changelog.Debian.gz
/usr/bin
/usr/bin/clang++
/usr/bin/clang-apply-replacements
/usr/bin/clang-tidy
/usr/bin/asan_symbolize
/usr/bin/scan-view
/usr/bin/pp-trace
/usr/bin/clang-check
/usr/bin/clang-query
/usr/bin/scan-build
/usr/bin/clang
/usr/bin/clang-tblgen
/usr/bin/c-index-test
root@3af3cffb4fa1:/data/riotbuild# 
```
I found this, but it was related to clang 2.7 on Ubuntu..
https://bugs.launchpad.net/ubuntu/+source/clang/+bug/549680

**Comment by gebart** [comment]
@OlegHahm what distro are you running?

**Comment by OlegHahm** [comment]
Arch Linux

**Comment by OlegHahm** [comment]
Found it, packet is called `clang-analyzer`.

**Comment by cgundogan** [comment]
seems to work for me on Arch Linux. However, I have no xdg-open so showing the report does not work and results in an error

**Comment by OlegHahm** [comment]
And I get
```
scan-build: Removing directory '/tmp/scan-build-2015-07-21-135737-32147-1' because it contains no reports.
scan-build: No bugs found.
Showing most recent report in your web browser...
find: `/home/oleg/git/RIOT/examples/hello-world/scan-build/': No such file or directory
xdg-open 
   xdg-open -- opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
/home/oleg/git/RIOT/Makefile.scan-build:61: recipe for target 'scan-build-analyze' failed
make: *** [scan-build-analyze] Error 1
```
now.

**Comment by gebart** [comment]
@OlegHahm the problem is that if ccc-analyzer doesn't find anything (or if you run it with a complete build already done, without `make clean`) it will just delete the report directory after it finished..

**Comment by gebart** [comment]
Should I force a `make clean` before scan-build?

**Comment by cgundogan** [comment]
If no errors are found, the folder will not be created and this results in the same error. Checking if the folder exists before issueing xdg-open will fix this

**Comment by gebart** [comment]
@cgundogan making a fix for that now.

If the project is already built, then nothing will be analyzed and there will be no report either. Should we add a dependency to clean before analyzing?

**Comment by gebart** [comment]
updated

**Comment by cgundogan** [comment]
The error is fixed. I have a question though: While building with scan-build, I can see multiple warnings on stdout, but not report is generated. Is this normal?

**Comment by cgundogan** [comment]
And regarding the `make clean` question: I vote for a `make clean` before `scan-build`. Otherwise, the reporting will only contain bugs in modified files

**Comment by gebart** [comment]
@cgundogan what does scan-build say at the end of the run?

**Comment by cgundogan** [comment]
```
 text    data     bss     dec     hex filename
 136406     548  114944  251898   3d7fa /home/cnk/riotos/RIOT/examples/ng_networking/bin/native/ng_networking.elf
make: Leaving directory '/home/cnk/riotos/RIOT/examples/ng_networking'
scan-build: 9 bugs found.
scan-build: Run 'scan-view /tmp/scan-build-2015-07-21-142834-11957-1' to examine bug reports.
Showing most recent report in your web browser...
No report found
```

scan-builds seem to be in /tmp/ instead of `PWD`

**Comment by gebart** [comment]
I messed something up in the refactoring, working on it now.

**Comment by thomaseichinger** [comment]
I have the same problem as described in @OlegHahm's https://github.com/RIOT-OS/RIOT/pull/3468#issuecomment-123277928

```bash
% clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

**Comment by cgundogan** [comment]
@thomaseichinger try https://github.com/RIOT-OS/RIOT/pull/3468#issuecomment-123281650

**Comment by gebart** [comment]
added an mkdir. Try it again, please.

**Comment by thomaseichinger** [comment]
@gebart works for me too.

**Comment by gebart** [comment]
added clean as a prerequisite for scan-build, squashed

**Comment by cgundogan** [comment]
seems to work for me.

FYI: The first line when executing is:
`Performing Clang static code analysis using toolchain "".`
Is something missing there?

**Comment by gebart** [comment]
so far, `TOOLCHAIN` switching is only supported on Cortex M. We should add it to native and other platforms as well in order for easy switching between gcc and clang.

**Comment by OlegHahm** [comment]
ACK

**Comment by OlegHahm** [comment]
And since again only libfixmath is failing on Travis: Go!

**Pull request merged**
