### PR TITLE
ng_pkt: adapt ng_pktsnip_t for easy iovec conversion

### PR DESCRIPTION
**Pull request by authmillenon**

### CODE REVIEW

**Comment by haukepetersen** [comment]
We had slight mistake in our considerations yesterday: just parsing a `pkt_t` to `struct iovec` is not sufficient. #3213 is creating an array of these structs (the ptr/length tuples are copied into a continuous memory section). This PR does not help with that... So I would vote for closing it.

**Comment by authmillenon** [comment]
I knew that, but this helps still by simplifying the assignment a lot...

**Comment by authmillenon** [comment]
Ah … yes of course, because it is an array this is not possible… Why don't you use an array of `struct iovec *` pointers in `ng_netdev2`?

**Comment by kaspar030** [comment]
Well, the idea was to go standard, that's why I thought of iovecs. Also, using an array to pointers to two values seems ... odd.

**Comment by authmillenon** [comment]
Mh… yeah, than it's probably best to close this one :/.

**Pull request closed without merging**
