### PR TITLE
frdm-kl43z: NXP Kinetis FRDM-KL43Z development board

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Add initial CPU support for NXP Kinetis KL43Z and an initial configuration for the FRDM-KL43Z development board.

This PR lays the foundation for the KL series support and will enable easily adding support for other Kinetis L based boards.

#### What works?

 - Clock configuration (MCG_Lite), 2 MHz, 8 MHz, 48 MHz, external clock
 - UART/LPUART
 - GPIO
 - I2C
 - Timers (RTC/RTT, PIT, LPTMR)
 - MMA8451 accelerometer
 - MAG3110 magnetometer

#### What is missing?

 - SPI (different hardware module than used in the other supported Kinetis CPUs)
 - PWM
 - Segment LCD driver

### Issues/PRs references

#7154

### CODE REVIEW

**Comment by gebart** [comment]
To be able to flash this board, the on board debugger must be updated to a J-Link or CMSIS-DAP firmware. The factory programmed firmware is a P&E debugger which we don't have a configuration for.
Follow the instructions at https://www.nxp.com/support/developer-resources/run-time-software/kinetis-developer-resources/ides-for-kinetis-mcus/opensda-serial-and-debug-adapter:OPENSDA for updating the debugger firmware.

**Comment by gebart** [comment]
Rebased and updated configuration to match upstream changes. Added configuration for onboard inertial sensors (MAG3110 and MMA8451Q).

Tested:
- UART
- sensors
- LEDs
- button (SW3, via SAUL)
- timers
- xtimer

Not tested:
- ADC

**Comment by benpicco** [comment]
Welp, I think we should still be able to get this in - if you're still interested, let's start with a rebase

**Comment by benpicco** [comment]
No regressions on the `openlabs-kw41z-mini`.

**Review by benpicco — APPROVED** [review]

**Comment by aabadie** [comment]
This was merged before I could finish my comment below!

> No regressions on the openlabs-kw41z-mini.

Ok, but do we know if this particular board and its provided features work ? Do you have the board to test @benpicco. It would be nice to have some test results before merging.

**Comment by aabadie** [comment]
I really wanted to block this PR before we get at least the test results from someone. Now there's no guarantee that things are working on that board. And sorry @benpicco, but I also don't like that you clearly took other this PR from someone else and kind of auto-ACKed himself. I good to have things in fast(er) but we at least need a minimum of testing before merging, especially for boards.

**Pull request merged**
