### PR TITLE
drivers/at86rf2xx: remove redundant radio wakeup

### PR DESCRIPTION
**Pull request by aabadie**
Finalize and polish #7279 to have it in feature freeze.

### CODE REVIEW

**Comment by aabadie** [comment]
I cannot push in @Hyungsin original branch (this is the reason I open a new PR)

**Comment by aabadie** [comment]
ping @miri64, Murdock is green

**Comment by Hyungsin** [comment]
Cool. Thanks! :)

**Comment by miri64** [comment]
No, thank *you* for your contribution :-)

**Pull request merged**
