### PR TITLE
boards/native: fix overriden INCLUDES leading to build failure

### LINKED ISSUE #11603: NATIVEINCLUDES Does not include USEMODULE_INCLUDES from log_printfnoformat
#### Description
If I try to build an application, which uses a module (log_printfnoformat) that requires an include path in USEMODULE_INCLUDES, but my build fails with:

```
➜  RIOT/tests/log ‹master*› » QUIET=0 LANG=C make all 
Building application "log" for "native" with MCU "native".

'/home/robin/git/RIOT/dist/tools/genconfigheader/genconfigheader.sh' -DDEVELHELP -Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -DDEBUG_ASSERT_VERBOSE -DRIOT_APPLICATION=\"log\" -DBOARD_NATIVE=\"native\" -DRIOT_BOARD=BOARD_NATIVE -DCPU_NATIVE=\"native\" -DRIOT_CPU=CPU_NATIVE -DMCU_NATIVE=\"native\" -DRIOT_MCU=MCU_NATIVE -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -DMODULE_AUTO_INIT -DMODULE_BOARD -DMODULE_CORE -DMODULE_CORE_MSG -DMODULE_CPU -DMODULE_LOG -DMODULE_LOG_PRINTFNOFORMAT -DMODULE_NATIVE_DRIVERS -DMODULE_PERIPH -DMODULE_PERIPH_COMMON -DMODULE_PERIPH_GPIO -DMODULE_PERIPH_PM -DMODULE_PERIPH_UART -DMODULE_SYS -DRIOT_VERSION=\"2019.07-devel-479-g3f425\" \
	| '/home/robin/git/RIOT/dist/tools/lazysponge/lazysponge.py' --verbose '/home/robin/git/RIOT/tests/log/bin/native/riotbuild/riotbuild.h'
Keeping old /home/robin/git/RIOT/tests/log/bin/native/riotbuild/riotbuild.h (7873b9dce997c1b8e120b6302e22f558)
DIRS=" " "make" -C /home/robin/git/RIOT/tests/log -f /home/robin/git/RIOT/makefiles/application.inc.mk
make[1]: Entering directory '/home/robin/git/RIOT/tests/log'
"make" -C /home/robin/git/RIOT/boards/native
make[2]: Entering directory '/home/robin/git/RIOT/boards/native'
gcc \
	-DRIOT_FILE_RELATIVE=\"boards/native/board.c\" \
	-DRIOT_FILE_NOPATH=\"board.c\" \
	-Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -include '/home/robin/git/RIOT/tests/log/bin/native/riotbuild/riotbuild.h'  -DNATIVE_INCLUDES -I/home/robin/git/RIOT/boards/native/include/ -I/home/robin/git/RIOT/core/include/ -I/home/robin/git/RIOT/drivers/include/ -I/home/robin/git/RIOT/cpu/native/include -I/home/robin/git/RIOT/sys/include -MD -MP -c -o /home/robin/git/RIOT/tests/log/bin/native/board/board.o /home/robin/git/RIOT/boards/native/board.c
In file included from /home/robin/git/RIOT/boards/native/board.c:21:
/home/robin/git/RIOT/core/include/log.h:98:10: fatal error: log_module.h: No such file or directory
 #include "log_module.h"
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/robin/git/RIOT/Makefile.base:83: /home/robin/git/RIOT/tests/log/bin/native/board/board.o] Error 1
make[2]: Leaving directory '/home/robin/git/RIOT/boards/native'
make[1]: *** [/home/robin/git/RIOT/Makefile.base:20: ALL--/home/robin/git/RIOT/boards/native] Error 2
make[1]: Leaving directory '/home/robin/git/RIOT/tests/log'
make: *** [/home/robin/git/RIOT/tests/log/../../Makefile.include:464: /home/robin/git/RIOT/tests/log/bin/native/application_log.a] Error 2

```

I Only tested this with "USEMODULE = log_printfnoformat" so far, but the problem may also appear with other (pseudo-)modules.

Problem Description:

"USEMODULE = printfnoformat" invokes sys/log/Makefile.include

```
ifneq (,$(filter log_printfnoformat,$(USEMODULE)))
  USEMODULE_INCLUDES += $(RIOTBASE)/sys/log/log_printfnoformat
endif
```

As you can see in the code the include directory of log_printfnoformat is correctly added to USEMODULE_INCLUDE. USEMODULE_INCLUDE is later appended to INCLUDES. Later INCLUDES is overwritten in boards/native/Makefile

```
MODULE = board

DIRS = drivers

include $(RIOTBASE)/Makefile.base

INCLUDES = $(NATIVEINCLUDES)
```

I assume this should only add $NATIVEINCLUDES to INCLUDES and thus the last line should look like the following: 

```
INCLUDES += $(NATIVEINCLUDES)
```

Changing this line results in working builds on my system. If anybody could back my assumption or provide a better solution I will happily create a small PR. 

Alternatively one could reduce impact heavily with the following change in sys/log/Makefile.include

```
diff --git a/sys/log/Makefile.include b/sys/log/Makefile.include
index 05720548d..b7320744f 100644
--- a/sys/log/Makefile.include
+++ b/sys/log/Makefile.include
@@ -1,3 +1,6 @@
 ifneq (,$(filter log_printfnoformat,$(USEMODULE)))
   USEMODULE_INCLUDES += $(RIOTBASE)/sys/log/log_printfnoformat
+  ifeq ($(BOARD),native)
+    NATIVEINCLUDES += -I$(RIOTBASE)/sys/log/log_printfnoformat
+  endif
 endif
```
#### Steps to reproduce the issue

1. Create a new Application which includes "log.h" in its main.c
2. Add "USEMODULE += log_printfnoformat" to the applications Makefile
3. Run "BOARD=native make all"

#### Expected results
Build should run without any error

#### Actual results
Build fails with compiler errors due to missing include path

#### Versions

```
Operating System Environment
-----------------------------
       Operating System: "Arch Linux" 
                 Kernel: Linux 5.1.2-arch1-1-ARCH x86_64 unknown

Installed compiler toolchains
-----------------------------
             native gcc: gcc (GCC) 8.3.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (Arch Repository) 9.1.0
                avr-gcc: avr-gcc (GCC) 9.1.0
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
   xtensa-esp32-elf-gcc: missing
   xtensa-lx106-elf-gcc: missing
                  clang: clang version 8.0.0 (tags/RELEASE_800/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.1.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
xtensa-esp32-elf-newlib: missing
xtensa-lx106-elf-newlib: missing
               avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                  cmake: cmake version 3.14.4
               cppcheck: Cppcheck 1.86
                doxygen: 1.8.15
                 flake8: missing
                    git: git version 2.21.0
                   make: GNU Make 4.2.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 3.7.3
                python2: Python 2.7.16
                python3: Python 3.7.3
             coccinelle: spatch version 1.0.7 compiled with OCaml version 4.07.1
```

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR fixes an issue when one loads the `log_printfnoformat` submodule into an application and builds for native. This use case works for all other boards.

I'm not sure this is the best fix and I'm also wondering why using `INCLUDES = $(NATIVEINCLUDES)` in `Makefile.include` is needed.

### Testing procedure

Build an application with `log_printfnoformat` on native:
```sh
USEMODULE=log_printfnoformat make -C examples/hello-world/ clean all
```

With this PR it works, on master, you get the following error:
```
make: Entering directory '/home/aabadie/softs/src/riot/RIOT/examples/hello-world'
Building application "hello-world" for "native" with MCU "native".

"make" -C /home/aabadie/softs/src/riot/RIOT/boards/native
In file included from /home/aabadie/softs/src/riot/RIOT/boards/native/board.c:21:
/home/aabadie/softs/src/riot/RIOT/core/include/log.h:98:10: fatal error: log_module.h: No such file or directory
 #include "log_module.h"
          ^~~~~~~~~~~~~~
compilation terminated.
```

### Issues/PRs references

Required by #11573, fixes #11603

### CODE REVIEW

**Comment by cladmi** [comment]
I checked in `board.c` and the issue is only for `native_motor`, so I think it should be moved outside.

**Comment by cladmi** [comment]
The main question for native, is what should be using the `system` headers instead of the RIOT ones. Restricting this to the lowest layer modules as possible would be good.
Another solution is to make our headers use the reference `posix` ones if available.

**Comment by jcarrano** [comment]
@cladmi So you say that the _real_ solution is to move ´native_motor´ outside?

**Comment by aabadie** [comment]
> I checked in board.c and the issue is only for native_motor, so I think it should be moved outside.

I don't understand the relation with the problem that this PR is trying to solve. Moving native_motor "outside" doesn't solve the build issue you get with `USEMODULE=log_printfnoformat make -C examples/hello-world`.

I checked info-build target to compare the list of directories included (in `INCLUDES`), using `USEMODULE=log_printfnoformat make -C examples/hello-world info-build`:
- this PR:
```
INCLUDES: 
	-I/home/aabadie/softs/src/riot/RIOT/core/include  
	-I/home/aabadie/softs/src/riot/RIOT/drivers/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/include  
	-I/home/aabadie/softs/src/riot/RIOT/boards/native/include  
	-DNATIVE_INCLUDES  
	-I/home/aabadie/softs/src/riot/RIOT/boards/native/include/  
	-I/home/aabadie/softs/src/riot/RIOT/core/include/  
	-I/home/aabadie/softs/src/riot/RIOT/drivers/include/  
	-I/home/aabadie/softs/src/riot/RIOT/cpu/native/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/include  
	-I/home/aabadie/softs/src/riot/RIOT/cpu/native/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/log/log_printfnoformat
```
- master:
```
INCLUDES: 
	-I/home/aabadie/softs/src/riot/RIOT/core/include  
	-I/home/aabadie/softs/src/riot/RIOT/drivers/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/include  
	-I/home/aabadie/softs/src/riot/RIOT/boards/native/include  
	-DNATIVE_INCLUDES  
	-I/home/aabadie/softs/src/riot/RIOT/boards/native/include/  
	-I/home/aabadie/softs/src/riot/RIOT/core/include/  
	-I/home/aabadie/softs/src/riot/RIOT/drivers/include/  
	-I/home/aabadie/softs/src/riot/RIOT/cpu/native/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/include  
	-I/home/aabadie/softs/src/riot/RIOT/cpu/native/include  
	-I/home/aabadie/softs/src/riot/RIOT/sys/log/log_printfnoformat
```

They are exactly the same but the latter doesn't work. So for me the use of `INCLUDES = $(NATIVEINCLUDES)` in the board Makefile is somehow breaking the list of includes.

Now if I use the verbose build, one can see that the `log_printfnoformat` is not in the list of `-I` arguments of gcc, which is in contradiction with what `info-build` returns:
- on master (and it fails right after of course):
```
gcc \
	-DRIOT_FILE_RELATIVE=\"boards/native/board_init.c\" \
	-DRIOT_FILE_NOPATH=\"board_init.c\" \
	-Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -include '/home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/riotbuild/riotbuild.h'  -DNATIVE_INCLUDES -I/home/aabadie/softs/src/riot/RIOT/boards/native/include/ -I/home/aabadie/softs/src/riot/RIOT/core/include/ -I/home/aabadie/softs/src/riot/RIOT/drivers/include/ -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -MD -MP -c -o /home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/board/board_init.o /home/aabadie/softs/src/riot/RIOT/boards/native/board_init.c
gcc \
	-DRIOT_FILE_RELATIVE=\"boards/native/board.c\" \
	-DRIOT_FILE_NOPATH=\"board.c\" \
	-Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -include '/home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/riotbuild/riotbuild.h'  -DNATIVE_INCLUDES -I/home/aabadie/softs/src/riot/RIOT/boards/native/include/ -I/home/aabadie/softs/src/riot/RIOT/core/include/ -I/home/aabadie/softs/src/riot/RIOT/drivers/include/ -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -MD -MP -c -o /home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/board/board.o /home/aabadie/softs/src/riot/RIOT/boards/native/board.c
In file included from /home/aabadie/softs/src/riot/RIOT/boards/native/board.c:21:
/home/aabadie/softs/src/riot/RIOT/core/include/log.h:98:10: fatal error: log_module.h: No such file or directory
 #include "log_module.h"
```
- with this PR:
```
gcc \
	-DRIOT_FILE_RELATIVE=\"examples/hello-world/main.c\" \
	-DRIOT_FILE_NOPATH=\"main.c\" \
	-Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -include '/home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/riotbuild/riotbuild.h'  -I/home/aabadie/softs/src/riot/RIOT/core/include -I/home/aabadie/softs/src/riot/RIOT/drivers/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -I/home/aabadie/softs/src/riot/RIOT/boards/native/include -DNATIVE_INCLUDES -I/home/aabadie/softs/src/riot/RIOT/boards/native/include/ -I/home/aabadie/softs/src/riot/RIOT/core/include/ -I/home/aabadie/softs/src/riot/RIOT/drivers/include/ -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/log/log_printfnoformat -MD -MP -c -o /home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/application_hello-world/main.o /home/aabadie/softs/src/riot/RIOT/examples/hello-world/main.c
"make" -C /home/aabadie/softs/src/riot/RIOT/boards/native
make[2]: Entering directory '/home/aabadie/softs/src/riot/RIOT/boards/native'
mkdir -p /home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/board/
gcc \
	-DRIOT_FILE_RELATIVE=\"boards/native/board_init.c\" \
	-DRIOT_FILE_NOPATH=\"board_init.c\" \
	-Werror -Wall -Wextra -pedantic -std=gnu99 -m32 -fstack-protector-all -ffunction-sections -fdata-sections -fno-delete-null-pointer-checks -fdiagnostics-color -Wstrict-prototypes -Wold-style-definition -fno-common -Wall -Wextra -Wformat=2 -Wformat-overflow -Wformat-truncation -Wmissing-include-dirs -include '/home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/riotbuild/riotbuild.h'  -I/home/aabadie/softs/src/riot/RIOT/core/include -I/home/aabadie/softs/src/riot/RIOT/drivers/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -I/home/aabadie/softs/src/riot/RIOT/boards/native/include -DNATIVE_INCLUDES -I/home/aabadie/softs/src/riot/RIOT/boards/native/include/ -I/home/aabadie/softs/src/riot/RIOT/core/include/ -I/home/aabadie/softs/src/riot/RIOT/drivers/include/ -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/log/log_printfnoformat -DNATIVE_INCLUDES -I/home/aabadie/softs/src/riot/RIOT/boards/native/include/ -I/home/aabadie/softs/src/riot/RIOT/core/include/ -I/home/aabadie/softs/src/riot/RIOT/drivers/include/ -I/home/aabadie/softs/src/riot/RIOT/cpu/native/include -I/home/aabadie/softs/src/riot/RIOT/sys/include -MD -MP -c -o /home/aabadie/softs/src/riot/RIOT/examples/hello-world/bin/native/board/board_init.o /home/aabadie/softs/src/riot/RIOT/boards/native/board_init.c
```

**Comment by cladmi** [comment]
NATIVEINCLUDES is not as simple as this. It is there for a good reason.

https://github.com/RIOT-OS/RIOT/pull/8940

And indeed, the modules using NATIVEINCLUDES cannot use any riot modules includes. It is on purpose.

**Comment by cladmi** [comment]
@jcarrano currently it is using APIs that are not available for `boards/native/board.c` as it uses restrictive includes, so the placement is wrong.
As `native/boards` is not using any system `posix` headers it should be possible to use the normal `INCLUDES` there. Doing a rationalization of the `NATIVEINCLUDES` handling in general could be a good thing.

However, in practice, why is there even a `native_motor_driver_qdec_simulation` in `boards/native/board.c`?
If there is a need for a fake test device, why not put it in its own module ?
It is always compiled even if `motor_driver` features is not used.

**Comment by aabadie** [comment]
> And indeed, the modules using NATIVEINCLUDES cannot use any riot modules includes. It is on purpose.

Can you explain this a bit more ?

**Comment by cladmi** [comment]
> > And indeed, the modules using NATIVEINCLUDES cannot use any riot modules includes. It is on purpose.
> 
> Can you explain this a bit more ?

From https://github.com/RIOT-OS/RIOT/pull/8940.

The goal of `NATIVEINCLUDES`, as I understood it, is to handle conflicts between `RIOT` headers and the system headers which may contain different values.
(I know about POSIX for example)
POSIX is only an API and not an ABI, so "names" are the same but not the values for the enums/defines and even differ between linux/mac.

For `native` our `POSIX` headers do not match with the ones from the system.
Using `INCLUDES` directories makes the system use `RIOT` posix values, which are not the one for the host system. So not working when communication with the system.

Every modules that need to communicate with the Linux/mac underlying system, must use the system headers, not the ones we provide if they can be different.


Currently who should use `NATIVEINCLUDES` is not that clear and maybe too general as here `board` for `native` does not interact directly with Host system.

**Comment by aabadie** [comment]
@cladmi, see #11603 where there is an alternative to the change proposed here: extend NATIVEINCLUDES from the log submodule.
I have no idea what would be better. Do you have an even better suggestion ?

**Comment by cladmi** [comment]
@aabadie I think we can change that `NATIVEINCLUDES` is not used at all `boards/native/*` as neither `board` nor `native-drivers` implement direct interaction with the system. If another `periph` using system interaction must be implemented it should be put in its own directory .
So the definition of `NATIVEINCLUDES` could be moved to `cpu/native` too.

**Comment by aabadie** [comment]
@cladmi, I remove `INCLUDES = $(NATIVEINCLUDES)` from `boards/native` and `cpu/native` and it seems to work. I'm not sure if that was what you proposed.

I'll removed the previous commits if it's ok for you, just keeping the commit with the new test application.

**Comment by cladmi** [comment]
I was thinking about `boards/native` and `boards/native/drivers`.

`cpu/native` should keep it, `async_read.c` uses `posix` headers, and we have a custom `fcntl.h`. It may be ok but would not want to try.

When removing it needs to be reviewed that the included header did not change unexpectedly.
This can be checked by comparing the `.d` files output after compilation for all affected files like `bin/native/board/board.d`. So this needs its specific pull request.

**Comment by aabadie** [comment]
@cladmi, I updated this PR following your suggestion: `cpu/native/Makefile` change is reverted and only `boards/native/Makefile`/`boards/native/drivers/Makefile` are modified.

> When removing it needs to be reviewed that the included header did not change unexpectedly.

After building `examples/hello-world`, I also checked the content of `bin/native/board/board.d`, it doesn't seem to have changed: same number of files included (using a combination of `cat` and `grep` with regexp).

> So this needs its specific pull request.

I'm not sure to understand. Do you mean the included files verification ? e.g. a new static test or something ?

**Comment by aabadie** [comment]
ping @cladmi

**Comment by cladmi** [comment]
> > So this needs its specific pull request.
> 
> I'm not sure to understand. Do you mean the included files verification ? e.g. a new static test or something ?

I mean `tests/log_printfnoformat: add test application & script` should not stay in the pr removing `NATIVE_INCLUDES` from `boards/native` and `boards/native/drivers`.

I will test the update now.

**Comment by cladmi** [comment]
Comparing with your reference PR, it indeed did not change the `.d` files for `board` and `native-led` according to diff `RIOT_CI_BUILD=1 make -C examples/hello-world/`

```
diff -u bin_master/native/native-drivers/native-led.d bin_pr/native/native-drivers/native-led.d
diff -u bin_master/native/board/board.d bin_pr/native/board/board.d
```

And to be even more precise, the whole binary directories are the same

```
diff -r -a bin_master/ bin_pr/
```

And both the `log_printfnoformat` and the `USEMODULE=log_printfnoformat make -C examples/hello-world/ clean all` test case work.

Can you please rebase and only keep the commit removing `NATIVEINCLUDES` from `native`, and update the PR description.

As a justification somehow if you want inspiration

```
Both `board` and `native-drivers` do not interact with the host operating system so does not need to use system headers. So using restricted `NATIVEINCLUDES` is not needed.

It also fixes the issue that they use RIOT headers for, for example logging, which were not available in `NATIVEINCLUDES`.
```

**Comment by aabadie** [comment]
> I mean tests/log_printfnoformat: add test application & script should not stay in the pr removing NATIVE_INCLUDES from boards/native and boards/native/drivers.

I'm sorry but I read 3 times [your initial comment](https://github.com/RIOT-OS/RIOT/pull/11572#issuecomment-498232440) about "So this needs its specific pull request" and this cannot the reason. It seems at least that the test application had nothing to with "So this needs its specific pull request".
Can you explain this again better ?

Also I think it's fine to keep the test application in this PR event if it doesn't seem related: it gives a way to verify that `log_printfnoformat` can be build for native (which was the initial goal of this PR).

**Comment by aabadie** [comment]
I cut out the test application from this PR and opened #11968

**Comment by miri64** [comment]
So where do `NATIVEINCLUDES` go now? IIRC `native` needs some different defines, otherwise their is a collision with our POSIX headers, and the host system's POSIX headers.

**Comment by aabadie** [comment]
> So where do NATIVEINCLUDES go now? 

They are not needed in `boards/native`

> IIRC native needs some different defines, otherwise their is a collision with our POSIX headers, and the host system's POSIX headers.

See https://github.com/RIOT-OS/RIOT/pull/11572#issuecomment-498232440

**Comment by miri64** [comment]
> > So where do NATIVEINCLUDES go now?
> 
> They are not needed in `boards/native`
> 
> > IIRC native needs some different defines, otherwise their is a collision with our POSIX headers, and the host system's POSIX headers.
> 
> See [#11572 (comment)](https://github.com/RIOT-OS/RIOT/pull/11572#issuecomment-498232440)

I see. I did not read the whole discussion.

**Comment by miri64** [comment]
Triggered rebuild, since last build was a few days back.

**Comment by aabadie** [comment]
All green, let's merge. Thanks @miri64 !

**Pull request merged**
