### PR TITLE
sys/flash_utils: Minor bug fixes

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- The signature of `flash_memcpy()` in the Doxygen output was incorrect. This is fixed by the first commit
- Using the prepocessor to alias the `<funcname>_P()` functions to `flash_<funcname>()` doesn't work with LLVM
    - unlike GCC, LLVM doesn't like dropping `FLASH_ATTR` (or `__flash`) silently, but wants a cast
    - using C code (`static inline` wrappers) in place of the preprocessor makes the use of clangd much easier with AVR, and will make future support of LLVM for AVR easier
    - for `flash_printf()`, `flash_fprintf()`, and `flash_snprintf()` the `static inline` wrapper would have to be implemented by calling `vprintf_P()`, `vfprintf_P()` and `vsnprintf_P()` with added impedance matching. This impedance matching would add 400 B of `.text`, so instead the linker is used to create aliases
    - finally, a work around for Ubuntu's toolchain is added so that the linker aliases also work there

### Testing procedure

`printf()` on AVR (which is converted to `flash_printf()` on AVR to place string literals in the flash) should still work.

### Issues/PRs references

None

### CODE REVIEW

**Review by nandojve — APPROVED** [review]

**Comment by maribu** [comment]
Oh, crap, this increases `.text` for me :/ (It does still flash and run fine, though.)

Let's see if I can get the increased `.text` size sorted out

**Comment by maribu** [comment]
The size increase is now down from 400 B to 74 B for `examples/default`.

**Comment by maribu** [comment]
OK, the remaining 74 B diff go away when using the incorrect function signature (as the avr-libc does) for my toolchain; it is already on-par with the docker toolchain.

I think this is a bug in GCC that the optimizer and not worth to add a work around for. And given that the docker toolchain is not impacted anyway, I'd say it is worth to have proper clangd support and eventually LLVM support.

**Comment by maribu** [comment]
Thx :-)

**Pull request merged**
