### PR TITLE
sys/{x,z}timer: assert() successful initialization of periph_timer

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title says.

### Testing procedure

1. With assertions enabled, an application using `xtimer` (`ztimer`) should still start
2. With assertions enabled and an invalid clock config, an assertion should trigger for an application using `xtimer` (`ztimer`)

### Issues/PRs references

None

### CODE REVIEW

**Comment by maribu** [comment]
Note: `rtt_init()` and `rtc_init()` return `void`. So only the `periph_timer` for `ztimer` was updated.

**Comment by bergzand** [comment]
I've added the 'run test' to check if the assert triggers on the CI boards.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by maribu** [comment]
> I've added the 'run test' to check if the assert triggers on the CI boards.

Good idea. (Still, boards previously passing `tests/periph_timer` and `tests/xtimer_*` should not be affected by this change.)

**Comment by bergzand** [comment]
>  should not be affected by this change

Famous last words :)

**Comment by maribu** [comment]
> > should not be affected by this change
> 
> Famous last words :)

OK, you convinced me. But let's run the CI tonight. Running tests blocks Murdock for an hour or so...

**Comment by maribu** [comment]
@kaspar030: You wanted to check the output of the ESP test failures. Now would be a chance. It seems the error is not due to a single flanky ESP, as the failures don't occur all on the same pi.

**Comment by kaspar030** [comment]
> @kaspar030: You wanted to check the output of the ESP test failures. Now would be a chance. It seems the error is not due to a single flanky ESP, as the failures don't occur all on the same pi.

thanks for the heads up. Yup, multiple Pi. If I read the output right, they seem to get stuck at boot time, and then the WDT reboots the node?

**Comment by kaspar030** [comment]
Following unrelated tests failed:

```
    tests/mtd_mapper/esp32-wroom-32:gnu
    tests/lwip_sock_tcp/esp32-wroom-32:gnu
    tests/pkg_libhydrogen/samr21-xpro:llvm
    tests/pkg_littlefs2/esp32-wroom-32:gnu
    tests/pkg_littlefs/esp32-wroom-32:gnu
    tests/pkg_spiffs/esp32-wroom-32:gnu
```

rebuilding...

**Comment by maribu** [comment]
Thanks :-)

**Pull request merged**
