### PR TITLE
sys/can: model in kconfig

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

To get the same modules loaded with and without TEST_KCONFIG, I had to fix a few dependencies with the gnrc_pktbuf shell command and STM32 `periph_can`.

Since `conn_can` has a dependency to `gnrc_pkt`, some modules are defined in the can Kconfig file. They should be removed once GNRC is fully migrated to Kconfig (some files already exists but seem to use an absolete strategy).

### Testing procedure

- Green CI

### Issues/PRs references

Tick one item in #16875

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
> Since conn_can has a dependency to gnrc_pkt,

Is that actually what we want? It would seem this is only due to
```c
int conn_can_isotp_recv(conn_can_isotp_t *conn, void *buf, size_t size, uint32_t timeout)
{
    assert(conn != NULL);
    assert(buf != NULL);

    int ret = 0;
    gnrc_pktsnip_t *snip;

    if (!conn->bound) {
        return -ENOTCONN;
    }
```
    
  `gnrc_pktsnip_t`, maybe we can better isolate it?  I feel like these low level things should be as isolated as possible and will help with the overall dependency modeling.

**Comment by MrKevinWeiss** [comment]
unless this `gnrc_pkt` is a completely self contained utility...

**Comment by aabadie** [comment]
> unless this `gnrc_pkt` is a completely self contained utility

It is used in many places. In the CAN code, the static implementation of `gnrc_pktbuf` is used and in other places the malloc implementation of `gnrc_pktbuf` is used. This PR only covers the static implementation and the dependency resolution is done in the CAN Kconfig file (with a TODO comment to tell to move it to gnrc once it's adapted to Kconfig)

**Comment by aabadie** [comment]
no longer needed

**Pull request closed without merging**
