### PR TITLE
board/nucleo-f334: removed obsolete GPIO defines

### PR DESCRIPTION
**Pull request by haukepetersen**
same as #3212

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Untested ACK.

**Comment by haukepetersen** [comment]
waiting for Travis.

**Comment by PeterKietzmann** [comment]
All builds passed but still we see an error here. Any ideas why?

**Comment by haukepetersen** [comment]
No (besides Travis giving us a hard time - I restarted one of the jobs at least 5! times...).

As Travis is happy (just not showing here) -> go.

**Pull request merged**
