### PR TITLE
 boards: move CPU/CPU_MODEL definition to Makefile.features

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

This moves CPU and CPU_MODEL to Makefile.features for a selection of board that currently cause no difference at all in the dependency parsing.

This was accepted in "Tracking: move CPU/CPU_MODEL to Makefile.features" #11477 and more precisely by this PR "Makefile.features: prerequisites for moving CPU/CPU_MODEL to boards/Makefile.features" #11478

cpu/$(CPU)/Makefile.features and cpu/$(CPU)/Makefile.dep are
automatically included

Part of moving CPU/CPU_MODEL definition to Makefile.features to have it
available before Makefile.include.

### Review procedure

This PR modifications are only

* moving `CPU`, `CPU_MODEL` to a different file
* removing the `include $(RIOTCPU)/cpu_name/...`
* Removing the `export CPU` and `export CPU_MODEL` as they are globally exported in https://github.com/RIOT-OS/RIOT/blob/3e753834e793928d2ee0946c25d6bd1232ad69c6/makefiles/vars.inc.mk#L11-L12
* It removed the comment saying "we set the cpu" as it is quite obvious. If it is not it should be part of a board porting guide.

The testing procedure dumps all variables used for dependency parsing and compare that the new value is consistent.

The dependency to #12004 is only for testing and could be merged without it.

#### Review of the new state

In the PR run

```
./dist/tools/buildsystem_sanity_check/save_all_dependencies_resolution_variables.sh  build/deps/cpu_model
...
# This takes more than 2 hours on my machine
```

Then run the aggregation script:
<details><summary><code>generate_aggregated.sh</code></summary>

```bash
#! /bin/bash

set -ue

readonly DIRECTORY=$1

set -v
rm -f ${DIRECTORY}/tests/nordic_softdevice/info-global/dependencies_info-boards-supported_reel  # Remove as not generated by normal compilation
rm -rf ${DIRECTORY}/tests/cpu_efm32_features # Remove as issues with BOARD being unconditionally set https://github.com/RIOT-OS/RIOT/pull/12009
find "${DIRECTORY}" -type f -name 'dependencies_info_*' | sort | xargs cat > ${DIRECTORY}/deps_info
find "${DIRECTORY}" -type f -name 'dependencies_info-boards-supported_*' | sort | xargs cat > ${DIRECTORY}/deps_info-boards-supported
```
</details>

```
./generate_aggregated.sh build/deps/cpu_model
```

Now the value of `CPU` and `CPU_MODEL` `info-boards-supported` and the normal dependency parsing are the same except for boards that are not migrated by this PR:

<details><summary>Difference in `CPU/CPU_MODEL/BOARD`</summary>

```
diff -W 80 -y --suppress-common-lines build/deps/cpu_model/deps_info-boards-supported build/deps/cpu_model/deps_info | grep -e BOARD -e 'CPU ' -e CPU_MODEL | awk '!x[$0]++'
CPU =                                 | CPU = nrf52
CPU =                                 | CPU = nrf51
CPU =                                 | CPU = stm32f1
CPU_MODEL =                           | CPU_MODEL = stm32f103c8
CPU =                                 | CPU = cc2538
CPU_MODEL =                           | CPU_MODEL = cc2538nf53
CPU =                                 | CPU = lm4f120
CPU_MODEL =                           | CPU_MODEL = LM4F120H5QR
CPU =                                 | CPU = esp32
CPU_MODEL =                           | CPU_MODEL = esp32
CPU =                                 | CPU = esp8266
CPU_MODEL =                           | CPU_MODEL = esp8266
CPU =                                 | CPU = fe310
CPU_MODEL =                           | CPU_MODEL = fe310_g000
CPU_MODEL =                           | CPU_MODEL = fe310_g002
CPU_MODEL =                           | CPU_MODEL = lpc1768
CPU =                                 | CPU = kinetis
CPU_MODEL =                           | CPU_MODEL = mk60dn512vll10
CPU_MODEL =                           | CPU_MODEL = nrf51x22xxaa
CPU =                                 | CPU = mips_pic32mx
CPU_MODEL =                           | CPU_MODEL = p32mx470f512h
CPU =                                 | CPU = mips_pic32mz
CPU_MODEL =                           | CPU_MODEL = p32mz2048efg100
CPU =                                 | CPU = efm32
CPU_MODEL =                           | CPU_MODEL = efr32mg12p332f1024gl125
```
</details>

Note that currently there are still differences in both parsing with

```
DISABLE_MODULE DEFAULT_MODULE USEMODULE FEATURES_REQUIRED FEATURES_USED FEATURES_OPTIONAL FEATURES_CONFLICT FEATURES_MISSING CPU_FAM
```

#### Comparison with the previous state

On the commit: `"squash! make: add targets to debug dependencies variables "` run the same generation:

```
./dist/tools/buildsystem_sanity_check/save_all_dependencies_resolution_variables.sh  build/deps/ref
# This takes more than 2 hours on my machine
./generate_aggregated.sh build/deps/ref
```

It did not change the variables used when normal dependency parsing:

```
diff build/deps/ref/deps_info build/deps/cpu_model/deps_info
# no difference
```

And in general nothing changed except `CPU` and `CPU_MODEL` values being now declared in `info-boards-supported`:

```
diff -r -W 80 -y  --suppress-common-lines build/deps/ref/ build/deps/cpu_model/ -I 'CPU ' -I 'CPU_MODEL ' --exclude='deps_info*'
```

I need to exclude the aggregated file as diff reports a few lines with `CPU` / `CPU_MODEL` even if I asked to ignore them.</summary>

<details><summary>For reference without excluding the aggregated files</summary>

```diff
$ diff -r -W 80 -y  --suppress-common-lines build/deps/ref/ build/deps/cpu_model/ -I 'CPU ' -I 'CPU_MODEL '
diff -r -W 80 -y --suppress-common-lines -I 'CPU ' -I 'CPU_MODEL ' build/deps/ref/deps_info-boards-supported build/deps/cpu_model/deps_info-boards-supported
BOARD = opencm904                     | BOARD = opencm904
CPU =                                 | CPU = stm32f1
CPU_MODEL =                           | CPU_MODEL = stm32f103cb
BOARD = nz32-sc151                    | BOARD = nz32-sc151
CPU =                                 | CPU = stm32l1
CPU_MODEL =                           | CPU_MODEL = stm32l151rc
BOARD = pba-d-01-kw2x                 | BOARD = pba-d-01-kw2x
CPU =                                 | CPU = kinetis
CPU_MODEL =                           | CPU_MODEL = mkw21d256vha5
BOARD = slwstk6220a                   | BOARD = slwstk6220a
CPU =                                 | CPU = ezr32wg
CPU_MODEL =                           | CPU_MODEL = ezr32wg330f256r60
BOARD = stm32f0discovery              | BOARD = stm32f0discovery
CPU =                                 | CPU = stm32f0
CPU_MODEL =                           | CPU_MODEL = stm32f051r8
BOARD = saml21-xpro                   | BOARD = saml21-xpro
CPU =                                 | CPU = saml21
CPU_MODEL =                           | CPU_MODEL = saml21j18a
BOARD = remote-reva                   | BOARD = remote-reva
CPU =                                 | CPU = cc2538
CPU_MODEL =                           | CPU_MODEL = cc2538sf53
```
</details>

### Issues/PRs references

* Tracking: move CPU/CPU_MODEL to Makefile.features #11477
* Depends on the debug targets from: make: add targets to debug dependencies variables #12004 (could be removed before merging if it can get it sooner through)

### CODE REVIEW

**Comment by cladmi** [comment]
I ran the validation script on a previous version of the branch as I needed to rebase it at the end to `master` and tweak some things.
I will re-run the testing procedure this evening and post the confirmation it is still valid tomorrow (or get back at fixing).

**Comment by jcarrano** [comment]
I'm running the script and getting tons of

```
/bin/sh: + : syntax error: operand expected (error token is "+ ")
```

in standard output.

**Comment by cladmi** [comment]
> I'm running the script and getting tons of
> 
> ```
> /bin/sh: + : syntax error: operand expected (error token is "+ ")
> ```
> 
> in standard output.

This is an issue with the `riotboot` handling in `sys/riotboot/Makefile.include` and that `CFLAGS` are evaluated even when not needed.
For a board that does not have `riotboot`, calling make in the directory gives these errors.

And for comparing the dependency resolution, I call it on all boards (that are not blacklisted).

<details><summary><code>BOARD=native make --no-print-directory -C bootloaders/riotboot/ | head</code></summary>

```
BOARD=native make --no-print-directory -C bootloaders/riotboot/ | head
/bin/sh: 1: arithmetic expression: expecting primary: " + "
There are unsatisfied feature requirements: riotboot


EXPECT ERRORS!


/bin/sh: 1: arithmetic expression: expecting primary: " + "
/bin/sh: 1: arithmetic expression: expecting primary: " + "
/bin/sh: 1: arithmetic expression: expecting primary: " + "
/bin/sh: 1: arithmetic expression: expecting primary: " + "
/bin/sh: 1: arithmetic expression: expecting primary: " + "
"make" -C /home/harter/work/git/RIOT/boards/native
"make" -C /home/harter/work/git/RIOT/boards/native/drivers
"make" -C /home/harter/work/git/RIOT/core
"make" -C /home/harter/work/git/RIOT/cpu/native
"make" -C /home/harter/work/git/RIOT/cpu/native/periph
"make" -C /home/harter/work/git/RIOT/cpu/native/vfs
"make" -C /home/harter/work/git/RIOT/drivers
"make" -C /home/harter/work/git/RIOT/drivers/periph_common
"make" -C /home/harter/work/git/RIOT/sys
"make" -C /home/harter/work/git/RIOT/sys/checksum
```
</details>

**Comment by cladmi** [comment]
I compared again the output with the last versions of this PR and I get the same output as the testing description.

**Comment by jcarrano** [comment]
Squash please.

**Comment by cladmi** [comment]
I will remove the test script as it is part of https://github.com/RIOT-OS/RIOT/pull/12004

**Comment by cladmi** [comment]
Thank you for the review. Now I need to tackle the complex ones.

**Pull request merged**
