### PR TITLE
pktdump: add IPv6 header dump

### PR DESCRIPTION
**Pull request by authmillenon**
Depends on #2697 and ~~#2731~~ (merged).

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current #2697

**Comment by haukepetersen** [comment]
ACK

**Comment by haukepetersen** [comment]
besides the ACK (maybe as future improvement): does it make sense to extract the format specific dumping functions and move them from the pktdump module to their 'natural' modules, e.g. move '_dump_ipv6_hdr` to the ipv6 module and make it public as in `ipv6_hdr_to_string()` or something? This could be useful as one could call the `xx_hdr_to_string()` function anywhere in the code for debugging...

**Comment by authmillenon** [comment]
Makes sense, will do in a future improvement ;-)

**Pull request merged**
