### PR TITLE
sys/turo: Allow default selection of json

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Cleanup  the `OUTPUT_FORMAT` selection when using turo and by default select json and overriding with USEMODULE.
This also adds checks to make sure multiple modules are not selected (maybe this should be a part of features conflict?) as well as check that the specific output format module exists (also could be done better, maybe by looking at the directory so we don't need to maintain a list).

### Testing procedure

Run `tests/turo` with each format by only using `USEMODULE=test_utils_result_output_<OUTPUT_FORMAT>`, and also an invalid format, and also multiple formats.
Then do it all again with kconfig I guess...

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
cough cough cough...

**Comment by leandrolanzieri** [comment]
Changes LGTM. I tried building the test app as described in the test procedure and the make checks are working. I also ran the provided script and everything matches the expected outputs. The Kconfig changes are also fine.

Please squash!

**Comment by MrKevinWeiss** [comment]
squashed!

**Review by leandrolanzieri — APPROVED** [review]
ACK

**Comment by MrKevinWeiss** [comment]
Thanks for the review!

**Pull request merged**
