### PR TITLE
Test all board kconfig models for hello-world

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Just a test...

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Hmmm, 
still working on things (using the CI to show the errors)

It seems
- pyboard - has the same binary size but different hashes
- nucleo-wl55jc - has different a binary size, probably clock
- lora-e5-dev - also different sizes but same modules
- 
nucleo-l011k4 requires using picolibc (although I don't really like how that is done...) so I need a way to force the board to select it instead of the default nanolibc.

**Comment by fjmolinas** [comment]
> nucleo-l011k4 requires using picolibc (although I don't really like how that is done...) so I need a way to force the board to select it instead of the default nanolibc.

What do you mean?

**Comment by fjmolinas** [comment]
Maybe @aabadie can take a look at 804ff503eb0002bbbf72ea0ae345a2bb87a08431? I know he had worked on the initial wl port as well, maybe he has this somewhere in a branch?

**Comment by MrKevinWeiss** [comment]
> > nucleo-l011k4 requires using picolibc (although I don't really like how that is done...) so I need a way to force the board to select it instead of the default nanolibc.
> 
> What do you mean?

[This](https://github.com/RIOT-OS/RIOT/blob/master/boards/nucleo-l011k4/Makefile.dep#L1)

**Comment by MrKevinWeiss** [comment]
OK probably I should be splitting this out into other PRs.

The issues with nucleo-wl55jc, lora-e5-dev and stm32mp157c-dk2 are the kconfig clock model, this must be done first and I will take a look at @aabadie work before progressing.


The nucleo-l011k4 and stm32f030f4-demo should be easy, just needs to force picolib (maybe in a nicer way)

The stm32f723e-disco has some obvious issues, though I haven't looked into it too much.

The stm32f429i-disco is probably just missing the stdio_usb_cdc_acm thing.

As I am out of time for now I will be picking up the work later.  If anyone fixes this stuff before I get to it please ping me :)

**Comment by MrKevinWeiss** [comment]
The following boards are still not passing:
- stm32mp157c-dk2 (clocks)
- stm32f3discovery (? size diff)
- stm32f030f4-demo (? size diff)
- pyboard (? size the same)
- nucleo-l011k4 (picolib)
- lora-e5-dev (clocks)

**Comment by fjmolinas** [comment]
Needs a rebase now!

**Comment by MrKevinWeiss** [comment]
closing as the test did its job!

**Pull request closed without merging**
