### PR TITLE
sys/log_*: modularize log into log_color and log_printfnoformat

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

this transforms sys/log into two simple modules

this also makes log_write nonstatic for log_color
(saving a lot of space in builds) from #18403

### Testing procedure

there are log tests all variants

### Issues/PRs references

this arose from the discussion in #18403
this also solves #18379

### CODE REVIEW

**Comment by kfessel** [comment]
i moved the doccheck changes to  #18431 and added the Kconfig adaption

**Review by miri64 — COMMENTED** [review]
`log_%` should pull in `log` as a dependency in `sys/Makefile.dep`, so it also works as long as we still use "legacy" dependencies.

**Comment by kfessel** [comment]
> `log_%` should pull in `log` as a dependency in `sys/Makefile.dep`, so it also works as long as we still use "legacy" dependencies.

this already is the case in master

https://github.com/RIOT-OS/RIOT/blob/master/sys/Makefile.dep#L399-L402

and unchaged in this PR

https://github.com/kfessel/RIOT/blob/039f1835dd9e002dce03ccd0f7cd8f9fa87feedf/sys/Makefile.dep#L399-L402

**Comment by kfessel** [comment]
@maribu and @benpicco showed some interest i this PRs predecessors

**Review by benpicco — APPROVED** [review]
That's a sensible cleanup.

**Comment by maribu** [comment]
Not having a copy of the log function in every object file is IMO a bugfix.

@leandrolanzieri I'd like to still have this. Please hit merge if you have no objections.

**Pull request merged**
