### PR TITLE
rust: Make dependencies visible

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

The Cargo.lock of rust_riotmodules_standalone should explicitly list all
    versions of software that would ever be pulled in by enabling RIOT
    modules backed by a Rust crate. This did not happen before, because
    while the optional dependencies could all be selected on the command
    line, they were not visible as possible features to `cargo update`, and
    were thus not encoded in the Cargo.lock file.

### Testing procedure

CI is probably good enough, but to understand what it does, look at `cargo tree --all-features` in `sys/rust_riotmodules_standalone` before and after -- and compare those with the output of `make` in `tests/rust_libs`. You will see that before, `cargo tree -all-features` did not show the `lsm303agr` crate as a listed dependency, even though the `make` output clearly illustrates that it *is* being pulled in. After, all crates used will also be shown in `cargo tree`.

These `cargo tree` outputs also align with the content of the Cargo.lock files before and after.

### Issues/PRs references

This should probably have been done right in #16833 -- sorry for the oversight.

This PR is built on #18683 -- so while that's not in, please ignore the first commit.

### CODE REVIEW

**Comment by Teufelchen1** [comment]
Is this still relevant?

**Comment by chrysn** [comment]
It still is, and I completely forgot about it. Thanks for pinging me -- it is now rebased (with only one commit left because master is sufficiently up to date).

Unless anything happens in CI, this should be good to go.

**Comment by chrysn** [comment]
... and force pushed because this would have conflicted with #20489 that is already in the merge queue. (So, ignore the first 3 commits; by the time this gets merged, only the latest commit should be new relative to master.)

**Review by Teufelchen1 — APPROVED** [review]

**Comment by MrKevinWeiss** [comment]
Sorry, https://github.com/RIOT-OS/RIOT/pull/20438 will never get in if every merge conflicts and kicks it out.  I will requeue when ready.

**Comment by chrysn** [comment]
sure, take priority for that. can you reenable once done so i get pinged to resolve?

**Pull request merged**
