### PR TITLE
net/gcaop: misc. minor style fixes and optimizations

### PR DESCRIPTION
**Pull request by haukepetersen**
- fixed typo in header doxygen (`s/request/response/`)
￼- fixed coding style issue (missing parenthesis)
￼- make gcoap_op_state return count directly
￼- fixed/unified alignment in gcoap header

### CODE REVIEW

**Comment by kb2ma** [comment]
@haukepetersen, thanks for the fixes and code style improvements. Regarding gcoap_op_state(), I definitely expect the statistics for gcoap to expand with time. At some point it will make sense to maintain the statistics internally in a struct. And I see your change matches the semantics for netstats by using the return value, as in gnrc_ipv6_netif_get_stats().

**Comment by haukepetersen** [comment]
What do you think about actually using `netstats_t` in gcoap? I am thinking of giving this a try...

**Comment by kb2ma** [comment]
Implementation of `netstats_t` sounds good to me. A few thoughts: It might be worthwhile to separately count Observe notifications, rather than just call them tx. It will be useful for tuning purposes to know when a tx failed due to a full buffer (open_reqs array). This will become more important with confirmable messaging, which I'm working on now.

**Comment by haukepetersen** [comment]
makes sense, I will propose something that we can use as a base for discussion.

**Pull request merged**
