### PR TITLE
shell: sc_icmpv6_echo: only allow unicast ping for now

### PR DESCRIPTION
**Pull request by authmillenon**
Currently the ping shell command is too simple to handle multicast ping, so the simplest solution for now is to not allow it at all.

### CODE REVIEW

**Comment by cgundogan** [comment]
Could you also PR this against the RC branch? Otherwise, I do not understand why you tagged this as `Release 2015.09`

**Comment by authmillenon** [comment]
Will do, just forgot about it yesterday.

**Comment by OlegHahm** [comment]
Hm, to me that still seems to be a workaround for an underlying problem. What about changing the netapi IPC send call to non-blocking? Since all layers have their message queues, the default behavior shouldn't change (messages are delivered), but the system won't get stuck any more in cases like this. (I checked with `ping 100 ff02::1 0 0` and `msg_try_send()` in the corresponding netapi call and the system isn't hanging any more.)

**Comment by OlegHahm** [comment]
With https://github.com/RIOT-OS/RIOT/pull/4005 the problem seems to be solved in a less intrusive way then switching to non-blocking netapi calls.

**Comment by authmillenon** [comment]
@OlegHahm did you check the state of the packet buffer, too?

**Comment by OlegHahm** [comment]
No, but since the application hung after some time without the release and now doesn't hang any more, I assume it to be okay, but I will check.

**Comment by authmillenon** [comment]
So with #4009 and #4013 this is not necessary anymore right? Then close?

**Comment by OlegHahm** [comment]
I think so, yes.

**Pull request closed without merging**
