### PR TITLE
boards/frdm-k64f: fix typo on UART_0_ISR

### PR DESCRIPTION
**Pull request by kYc0o**
A typo on the periph_conf.h definition of UART_0_ISR led to a kernel panic.

Rebased on top of #6983.

### CODE REVIEW

**Comment by miri64** [comment]
@kaspar030 should this be backported?

**Comment by kYc0o** [comment]
I'd say so, it was a bug which made the board unusable (at least for the uart).

**Comment by gebart** [comment]
@miri64 yes, this is quite severe. Any RX byte on the UART will cause the system to panic in the fallback dummy handler.

**Comment by miri64** [comment]
Then please go ahead and create a backport.

**Comment by kYc0o** [comment]
Well, actually is not needed since #6958 which introduced the bug is not in the 2017.04 release, so it will get everything together in the next release.

**Pull request merged**
