### PR TITLE
boards/esp32: enable GPS module on ESP32 TTGO T-Beam V1.0

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR enables the GPS module on ESP32 TTGO T-Beam V1.0 boards.

PR #11418 introduced the board definition for ESP32 TTGO T-Beam boards which include a GPS module that is connected via UART1 interface and provides NMEA messages on that interface. 

However, on boards from version 1.0, the power supply of the GPS module is contolled with an AXP192 that is connected via I2C. The GPS module is powered off by default and has to be switched on explicitly.

For this purpose the, this PR introduces 

1. the possibility to have a board-specific initialization function that is usually simply a wrapper around the common board initialization function `board_init_common`
2. a board-specific initialization function for ESP32 TTGO T-Beam boards, which switches on the power supply of the GPS module for version 1.0 boards.

Since the board initialization function `board_init` has to use the I2C interface to switch on the GPS module, the `board_init` function has to be called after `periph_init`. Therefore, the order of these both functions is also changed by this PR.

### Testing procedure

Use a [version 1.0 board of ESP32 TTGO T-Beam](https://github.com/Xinyuan-LilyGO/TTGO-T-Beam), flash and use `tests/periph_uart` with command `init 1 9600` to observe the output from the GPS module with and without this PR:
```
USEMODULE=esp32_ttgo_t_beam_v1_0 make BOARD=esp32-ttgo-t-beam -C tests/periph_uart flash term
```
With this PR the output should something like
```
Success: UART_DEV(1) RX: [$GPRMC,,V,,,,,,,,,,N*530x0d]\n
Success: UART_DEV(1) RX: [$GPVTG,,,,,,,,,N*300x0d]\n
Success: UART_DEV(1) RX: [$GPGGA,,,,,,0,00,99.99,,,,,,*480x0d]\n
Success: UART_DEV(1) RX: [$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*300x0d]\n
Success: UART_DEV(1) RX: [$GPGSV,1,1,00*790x0d]\n
Success: UART_DEV(1) RX: [$GPGLL,,,,,,V,N*640x0d]\n
```
Without this PR there should be no output.

### Issues/PRs references

### CODE REVIEW

**Comment by gschorcht** [comment]
@yegorich Do you see any chance to get a version 1.0 of TTGO T-Beam to try this PR?

**Comment by yegorich** [comment]
@gschorcht unfortunately no.

**Comment by gschorcht** [comment]
> @gschorcht unfortunately no.

:worried: I know your board is version 0.7, it could have been that you will order more boards in the near future, which could be version 1.0.

**Comment by gschorcht** [comment]
On the other hand, this PR would be a necessary improvement of the board definition. It is very likely that a user who orders such a board will receive version 1.0. Maybe the user will order this board just because of the GPS module and will then encounter exactly this problem.

Maybe a code review would be sufficient. I have tested it intensively.

**Comment by gschorcht** [comment]
> Looks good to me.

Yes, but Murdock isn't happy with some compilations :worried:

**Comment by benpicco** [comment]
Murdock is happy now - please squash.

**Comment by gschorcht** [comment]
@benpicco May I squash?

**Comment by benpicco** [comment]
Go ahead!

**Comment by gschorcht** [comment]
@benpicco Squashed.

**Comment by gschorcht** [comment]
@benpicco Thanks for approving and merging.

**Pull request merged**
