### PR TITLE
cpu/atmega_common: refactor AVR libc code into module

### PR DESCRIPTION
**Pull request by kaspar030**
This PR refactors atmega libc specific code and compatibility headers into a
subfolder.

Test if CI still builds, sizes stay same.

### CODE REVIEW

**Comment by kaspar030** [comment]
- rebased

@kYc0o care to take a look at this?

**Comment by kaspar030** [comment]
[here](https://ci.riot-os.org/RIOT-OS/RIOT/9984/3edd7b45594ec23b423cce8ce99c76d96bf7031b/output/static_tests.txt) is the new static-tests output.

**Comment by smlng** [comment]
can someone else please verify this, too: @MrKevinWeiss @leandrolanzieri? Just to be sure

**Comment by smlng** [comment]
@kaspar030 please squash if Murdock is happy

**Comment by MrKevinWeiss** [comment]
running tests now

**Comment by MrKevinWeiss** [comment]
Both master and this PR fail the same tests using @cladmi compile_and_test_for_board.py script
```
Failures during test:
- [tests/bench_runtime_coreapis](tests/bench_runtime_coreapis/test.failed)
- [tests/bitarithm_timings](tests/bitarithm_timings/test.failed)
- [tests/evtimer_msg](tests/evtimer_msg/test.failed)
- [tests/isr_yield_higher](tests/isr_yield_higher/test.failed)
- [tests/libfixmath](tests/libfixmath/test.failed)
- [tests/periph_eeprom](tests/periph_eeprom/test.failed)
- [tests/periph_gpio](tests/periph_gpio/test.failed)
- [tests/pipe](tests/pipe/test.failed)
- [tests/pkg_fatfs_vfs](tests/pkg_fatfs_vfs/test.failed)
- [tests/pkg_jsmn](tests/pkg_jsmn/test.failed)
- [tests/pkg_libb2](tests/pkg_libb2/test.failed)
- [tests/pkg_lora-serialization](tests/pkg_lora-serialization/test.failed)
- [tests/pkg_micro-ecc](tests/pkg_micro-ecc/test.failed)
- [tests/pkg_tiny-asn1](tests/pkg_tiny-asn1/test.failed)
- [tests/posix_semaphore](tests/posix_semaphore/test.failed)
- [tests/ps_schedstatistics](tests/ps_schedstatistics/test.failed)
- [tests/rng](tests/rng/test.failed)
- [tests/trickle](tests/trickle/test.failed)
```

**Comment by kYc0o** [comment]
Maybe this can come after #9130 ?

**Comment by smlng** [comment]
> Maybe this can come after #9130 ?

I think the order is not important, its more a matter of who needs to rebase (and maybe manual merge stuff) later on 😄

**Comment by kaspar030** [comment]
- squashed

Can this be considered minor impact regarding the freeze?

**Comment by smlng** [comment]
reACK, tested with arduino-mega2560 and several different test applications: all good. Also tested with Arduino-uno, same same. GO!

**Comment by miri64** [comment]
Am I right to understand that this PR reverts parts of https://github.com/RIOT-OS/RIOT/pull/8857 (specifically b597700a677157d04e7681025aa529eb8e9c84f0)?

**Comment by kaspar030** [comment]
> Am I right to understand that this PR reverts parts of #8857 (specifically [b597700](https://github.com/RIOT-OS/RIOT/commit/b597700a677157d04e7681025aa529eb8e9c84f0))?

Yes and no. #8857 updated vendor files and moved them from ```avr-libc-extra/include``` into ```include/vendor``` in order to keep CI from checking them. This PR re-introduces ```avr-libc-extra/``` but also adds a ```vendor/``` subfolder.

Having ```avr-libc-extra``` doesn't make sense as is (if all AVR boards always use the avr libc), but is a first step towards either not using a libc at all or using a different one.

**Pull request merged**
