### PR TITLE
servo ctor fix

### PR DESCRIPTION
**Pull request by dkm**
'dev' is an output. The pwm to initialize must be read from arg 2

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK

**Comment by LudwigKnuepfer** [comment]
Thank you for the fix!

Please change the commit message to match the "module: change" pattern. If in doubt compare git log output.

Example: 
```
drivers/servo: fix initialization

'dev' is an output. The pwm to initialize must be read from arg 2
```

However I think the example above still be improved on.

Then "arg 2" is not a very good - for one it uses an abbreviation (should be avoided in documentation in general), secondly - argument of what?
Same goes for "ctor" - I even had to look this one up.

Sorry for lecturing, I just thought I might get you to write even better commit messages in the future ;)

**Comment by dkm** [comment]
commit message fixed, hopefully meeting your standards :)

**Comment by LudwigKnuepfer** [comment]
ACK

**Comment by PeterKietzmann** [comment]
and go

**Pull request merged**
