### PR TITLE
[WIP] Initial Rust language support with make

### PR DESCRIPTION
**Pull request by nmeum**
This is very loosly based on #5740 the main difference between #5740 and this pull request are that I integrated rust into the existing build system instead of depending on xargo or cargo. This has a bunch of advantages, for one thing it is now possible to build rust applications for the native family. Besides you don't need the `rust-linker-hook` hack.

I am not so sure if it is a good idea to integrate the wrappers in `sys/rust` at this point. I am currently working on better wrappers for riot modules and newlibc.

Anyways, let me know what you think…

---

I tested this with `BOARD=native` and `BOARD=pba-d-01-kw2x` with gcc 6.2.

Files in `dist/rust` have been slightly modified but where basically taken from #5740.

### CODE REVIEW

**Comment by kaspar030** [comment]
Indeed this seems less hacky. Is it still possible to somehow use cargo crates?

**Comment by nmeum** [comment]
> Is it still possible to somehow use cargo crates?

Not really. my idea was to allow users to integrate crates by adding a pkg for them in `pkg/` that works in theory (`pkg/libcore` is a cargo crate). In reality, however, it doesn't seem to be possible to make packages in `pkg/` depend on each other in a decent way. 

This is relevant because if you build rust creates with `#![no_std]` each crate has to be linked against libcore, so each crate that you would want to add as a package to `pkg/` would need to depend on `pkg/libcore`.

Even though including external crates as a package doesn't really work currently compiling crates does of cause work. The directories in `sys/fmt` are normal rust crates.

But even if you would fix the dependency problem most cargo crates that you can find on [crates.io](https://crates.io/) wouldn't work with riot anyhow because most of them need libstd.

**Comment by kaspar030** [comment]
> I managed to integrate crates more closely into the existing pkg/-System I am currently testing and cleaning that up a bit and will update the pull request the following week (or so).

I'm opposed to not using the cargo/xargo infrastructure.

Users developing with rust will now cargo, and their packaging system is actually quite nice.
Rust RIOT packages should be cargo.io crates.

I suggest going with the linker hack now and rather try to get a "linker_args" option upstream, where we can just pass "$archives", which just get linked in using RIOT's build system.

**Comment by nmeum** [comment]
We made some progress with rust support on RIOT. We mirrored our master branch to a GitHub Repository (in case anybody wants to test it), this repository can be viewed [here](https://github.com/beduino-project/RIOT). We just integrated wrappers for sock and are now planning to rebase our changes against the current upstream master branch. If you want to experiment with rust on RIOT you should probably wait until we did that (it's scheduled for this weekend).

Afterwards we will work on wrappers for coap and as soon as we are finished doing that we will make some changes to our buildsystem requested by @kaspar030. After all of that has been done this merge request will be updated.

**Comment by aabadie** [comment]
why ?

**Comment by nmeum** [comment]
This was closed by accident. We will reopen this shortly. In the meantime just use the [beduino github repository](https://github.com/beduino-project/RIOT) if you are interested in playing around with rust.

**Comment by miri64** [comment]
No new development for over a year. Let's close this for now.

**Pull request closed without merging**
