### PR TITLE
cpu/stm32f0: optimizations to UART driver

### PR DESCRIPTION
**Pull request by haukepetersen**
Optimized the UART driver for less memory usage. See numbers for `tests/periph_uart_int`:

before:

```
   text	   data	    bss	    dec	    hex
  19464	    116	   5548	  25128	   6228
```

and after:

```
   text    data     bss     dec     hex
  18544     116    5548   24208    5e90
```

### CODE REVIEW

**Comment by BytesGalore** [comment]
hi I tested this PR on the `f0` using `/tests/shell` with no funny chracter:
```
help
2015-01-06 19:00:29,748 - INFO # > help
2015-01-06 19:00:29,749 - INFO # 
2015-01-06 19:00:29,749 - INFO # Command              Description
2015-01-06 19:00:29,750 - INFO # ---------------------------------------
2015-01-06 19:00:29,751 - INFO # start_test           starts a test
2015-01-06 19:00:29,752 - INFO # end_test             ends a test
2015-01-06 19:00:29,753 - INFO # echo                 prints the input command
2015-01-06 19:00:29,754 - INFO # reboot               Reboot the node
2015-01-06 19:00:29,756 - INFO # ps                   Prints information about running threads.
```
my toolchain:
`gcc version 4.8.4 20140725 (release) [ARM/embedded-4_8-branch revision 213147] (GNU Tools for ARM Embedded Processors)`

**Comment by PeterKietzmann** [comment]
By the way: mine was the following which also did not lead to funny characters 
```
gcc version 4.8.4 20140526 (release) [ARM/embedded-4_8-branch revision 211358] (GNU Tools for 
ARM Embedded Processors)
```

**Comment by thomaseichinger** [comment]
Can't reproduce anymore neither. Seems to be fixed. ACK when rebased.

**Comment by haukepetersen** [comment]
rebased and go.

**Pull request merged**
