### PR TITLE
examples/gnrc_border_router: add optional DHCPv6 support

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This is an alternative to #8803 and a follow-up to #13307 and introduces (optional) DHCPv6 support for the `gnrc_border_router` example. Currently, the documentation only provides configurations for KEA, which while provided by the ISC itself, isn't the most wide-spread used DHCPv6 server. Something more in the direction of `dnsmasq` would be nice but I wasn't able to get IA_PD options out of that yet (see https://github.com/RIOT-OS/RIOT/pull/8796#issuecomment-589093781). I know my OpenWRT router provides it but there the real config is mostly hidden behind [UCI](https://openwrt.org/docs/guide-user/base-system/uci). So if someone has a working config for a more common DHCPv6 server, I'll be happy to add it.

### Testing procedure
Follow the README for the DHCPv6 case. The 6Lo interface of the border router should get a global address.

### Issues/PRs references
Alternative to #8803 
Follow-up on #13307

### CODE REVIEW

**Comment by miri64** [comment]
Ping @benpicco?

**Comment by benpicco** [comment]
I'm fine with the changes, but don't know much about `dnsmasq`.

My only gripe is that Makefile has grown to be even more intimidating for newcomers who want to set up a border router. (This is in the `examples/` folder after all)

Can't we just have subfolders for different types of border routers, so we don't have to keep all possible config permutations in one file?

- `ethos with uhcpd` - no need to wrestle with a DHCP server config if you just want to quickly set up a temporary border router
- `esp_wifi with DHCPv6` - we could use `esp_wifi` <-> `esp_now` or provide an example for a WiFi <-> 6lo border router that is ready to use.
- `native with both options` - for testing

**Comment by miri64** [comment]
> Can't we just have subfolders for different types of border routers, so we don't have to keep all possible config permutations in one file?

Currently sub-folders aren't as easy due to the CI configuration I believe.

> My only gripe is that Makefile has grown to be even more intimidating for newcomers who want to set up a border router. (This is in the `examples/` folder after all)

Mhhh... Does it really look that intimidating now?



> * `ethos with uhcpd` - no need to wrestle with a DHCP server config if you just want to quickly set up a temporary border router
> 
> * `esp_wifi with DHCPv6` - we could use `esp_wifi` <-> `esp_now` or provide an example for a WiFi <-> 6lo border router that is ready to use.
> 
> * `native with both options` - for testing

Problem: there are far more permutations (e.g. Ethernet enabled board with xyz-radio). All of those apps also then need additional testing during the release testing phase.

**Comment by jia200x** [comment]
> Problem: there are far more permutations (e.g. Ethernet enabled board with xyz-radio). All of those apps also then need additional testing during the release testing phase.

Kconfig is our best friend :)

**Comment by benpicco** [comment]
> Currently sub-folders aren't as easy due to the CI configuration I believe.

The maybe not subfolders, but how about a `Makefile.native`, `Makefile.ethos`, `Maklefile.dhcp`, `Makefile.uhcpc` that only contains the relevant options and can be `include`d by the main Makefile

> Mhhh... Does it really look that intimidating now?

Let's say the beauty that you only need two network interfaces and `gnrc_sixlowpan_border_router_default` is hidden behind thick layers of `ethos` config 😉

**Comment by miri64** [comment]
> > Mhhh... Does it really look that intimidating now?
> 
> Let's say the beauty that you only need two network interfaces and `gnrc_sixlowpan_border_router_default` is hidden behind thick layers of `ethos` config wink

That I can co-sign... but that's a problem with `ethos`/host-facing interface config in general (see all the tests that involve communication with the host)

**Comment by benpicco** [comment]
> but that's a problem with `ethos`/host-facing interface config in general

That's why I was suggesting to stow it away in a separate Makefile.
Maybe it can even be reused across tests, but that's for another PR.

**Comment by miri64** [comment]
> > 
> 
> That's why I was suggesting to stow it away in a separate Makefile.
> Maybe it can even be reused across tests, but that's for another PR.

We already do this partly with `Makefile.board.dep` (which has to stay, otherwise the output of `make boards-supported` is broken). But we could stow away the configurations of the modules indeed.

**Comment by miri64** [comment]
Question is: do we want to do it in *this* PR?

**Comment by benpicco** [comment]
> Question is: do we want to do it in _this_ PR?

I thought it would make adding a new option easier.
But if you want to clean in up in a separate PR that's fine too.

This PR doesn't change the default behavior. My only gripe is that if you want an *example* for using DHCPv6 in RIOT, you'd usually want to use it in a 'real' network, not ethos.

**Comment by miri64** [comment]
> > Question is: do we want to do it in _this_ PR?
> 
> I thought it would make adding a new option easier.
> But if you want to clean it up in a separate PR that's fine too.

I rather want to clean up later ;-)

**Pull request merged**
