### PR TITLE
gitignore: Add .clang_complete and YouCompleteMe

### PR DESCRIPTION
**Pull request by gebart**
.clang_complete files can be used to pass the command line arguments needed to compile the sources in order to get the proper code completion using Clang with plugins for popular editors.

Vim: https://vtluug.org/wiki/Clang_Complete
Atom: 
 - Code completion: https://atom.io/packages/autocomplete-clang
 - Code linter: https://github.com/AtomLinter/linter-clang

### CODE REVIEW

**Comment by cgundogan** [comment]
Could you also add `.ycm_extra_conf.py` and `.ycm_extra_conf.pyc`?
I use `YouCompleteMe` [1] instead of `clang_complete`. Several sources say that YCM works better than clang_complete, but I have not much experience with clang_complete to verify this. Just a hint (:

[1] https://github.com/Valloric/YouCompleteMe

**Comment by gebart** [comment]
Sure, I'll add it.

**Comment by gebart** [comment]
updated with ycm

**Comment by cgundogan** [comment]
great, thank you. ACK

**Comment by gebart** [comment]
I doubt Travis will have anything interesting to say about this PR.

**Pull request merged**
