### PR TITLE
dist/tools/coccinelle/force: remove static.cocci

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

The rule is not behaving as it should and flagging all 'static'
variables based only on initialization (if the variable is initialized
before usage), but fails to recognize if 'static' is used to limit
visibility.

### Testing procedure

Murdock

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by fjmolinas** [comment]
I'll try a quick alternative...

**Comment by benpicco** [comment]
Should we move forward with this?
Those false warnings are *really* distracting.

**Comment by benpicco** [comment]
We can always add it back once it's fixed properly, but we need to get rid of those false warnings ASAP

**Pull request merged**
