### PR TITLE
sys/ztimer: rework Kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This changes the entry point for the ztimer modules in Kconfig, trying to fix:

1. the xtimer compatibility modules selection issue (https://github.com/RIOT-OS/RIOT/pull/17137)
2. the dependency loop happening in the native migration of RTC to ztimer (https://github.com/RIOT-OS/RIOT/pull/17125)

### Testing procedure
- CI should pass
- xtimer / ztimer compatibility modules should be activated
- the change applied in #17125 should not generate a loop

### Issues/PRs references
Alternative to https://github.com/RIOT-OS/RIOT/pull/17160

### CODE REVIEW

**Comment by fjmolinas** [comment]
I'm fine with this change, I would maybe like the commit message to be more descriptive mentioning that this is a special case. I'm wondering if when tackling the network stack we will to do this kinds of things as well...

**Comment by leandrolanzieri** [comment]
> I'm wondering if when tackling the network stack we will to do this kinds of things as well...

IMO we should try hard to avoid this. The main reason to switch the entry point of ztimer module selection was the (special) case of native RTC, which we still seem to want to work out of the box. In a more conservative point of view native actually does not provide `HAS_PERIPH_RTC` unless `MODULE_ZTIMER_MSEC` is active (that would be a `depends on`). That would also prevent the dependency loop, but adds more steps to select that periph.

**Comment by kfessel** [comment]
i tested: #17137 with this pr does no longer need the the patch to tests/driver_io1_xplained/app.config.test :heavy_check_mark: -> i like it.
reviewing the KConfig this looks good to me (but I haven't much experience with Kconfig): this seems to create a intemediate config value which is then used to determine whether the MODULE_XTIMER_ON_ZTIMER is need (sound good to me).

**Review by kfessel — COMMENTED** [review]
i tested: #17137 with this PR, it does no longer need the the patch to `tests/driver_io1_xplained/app.config.test` :heavy_check_mark: -> i like it. (it would have saved me a lot of time. 
reviewing the KConfig this looks good to me (but I haven't much experience with Kconfig): this seems to create a intemediate config value which is then used to determine whether the MODULE_XTIMER_ON_ZTIMER is need (sound good to me).
Lets have murdock take a look at this.

**Review by kfessel — APPROVED** [review]
I think this is good to go -maybe you want to ask for a second opinion from someone with more KConfig experience.

My Test: :heavy_check_mark: , Read: :heavy_check_mark: , Murdock: :heavy_check_mark: 

If merging is done with the current commits (messages) please provide a very descriptive Merge message.

**Comment by MrKevinWeiss** [comment]
> maybe you want to ask for a second opinion from someone with more KConfig experience.

I spent some time looking into this in detail and helping come up with a solution and agree that it is sufficient.

**Comment by leandrolanzieri** [comment]
Hmm I was not fast enough to address @fjmolinas comment before this got merged

**Comment by kfessel** [comment]
> Hmm I was not fast enough to address @fjmolinas comment before this got merged

I think the merge message that @MrKevinWeiss wrote is fine and solves the "commit message not being descriptive" issue without doing another Murdock cycle. Only the word "special case" maybe missing.

**Comment by leandrolanzieri** [comment]
> > Hmm I was not fast enough to address @fjmolinas comment before this got merged
> 
> I think the merge message that @MrKevinWeiss wrote is very good and solves the "commit message not being descriptive" issue without doing another Murdock cycle. Only the word "special case" maybe missing.

Ahh cool, missed that. Thanks for the review BTW!

**Comment by MrKevinWeiss** [comment]
This was the first time I wrote something in the merge commit :) (I also just wanted to prevent another CI cycle)

**Pull request merged**
