### PR TITLE
check_pr.sh: remove label check 

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
As discussed in https://github.com/RIOT-OS/RIOT/pull/14850, the newly introduced check there makes the existing label checks redundant. Moreover: the new check can react to changes in the PR, while the old check only works if the "CI: ready for build" label is set (Murdock) or something is pushed to the PR (Murdock and Travis). The Murdock check has the additional disadvantage that it also does all the other checks including building and testing if the according labels are set.

### Testing procedure
`CI: needs squashing` and `State: waiting for other PR` should not be reported by Murdock and Travis anymore.

### Issues/PRs references
Follow-up on https://github.com/RIOT-OS/RIOT/pull/14850.
Requires https://github.com/RIOT-OS/RIOT/pull/14850.

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master (but keeping the label, just to test)

**Comment by aabadie** [comment]
For some reason, the Murdock job failed although all static checks are green. Weird

**Comment by miri64** [comment]
Can't really tell why as well. Maybe Murdock does some label checking internally? Summon @kaspar030

**Comment by kaspar030** [comment]
> Maybe Murdock does some label checking internally?

Yes it does, configured in mutdock.toml on ci.riot-os.org. If we want to disable that, @MrKevinWeiss or @cgundogan need to remove that.

Persoally I find it much nicer to have this checked by Murdock, it makes me cringe to know that somewhere a VM is fired up just to do that check.

**Comment by miri64** [comment]
>  it makes me cringe to know that somewhere a VM is fired up just to do that check.

Isn't that basically the case with Murdock as well, just that it takes ages to get through the queue?

**Comment by miri64** [comment]
Static tests on murdock are now deactivated, so this PR is not that important anymore

**Pull request closed without merging**
