### PR TITLE
VERSION: add 2020.10 version file

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This adds the `VERSION` for the release 2020.10.

### Testing procedure

The correct version (2020.10) should be printed on any application:

```
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2020.10)
Hello World!
You are running RIOT on a(n) native board.
This board features a(n) native MCU.
```

### Issues/PRs references

None

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
Confirmed that `Version: 2020.10` is printed in `examples/hello-world` with this change.

**Comment by miri64** [comment]
Which PR is this waiting for?

**Comment by bergzand** [comment]
> Which PR is this waiting for?

[A backport of the release notes](https://github.com/RIOT-OS/RIOT/pull/15340)

**Comment by miri64** [comment]
Ah, I thought you wanted to merge before :D you will have to rebase the PR then once the backport is in.

**Comment by bergzand** [comment]
I realized after submitting this PR that first merging the release notes is maybe more technically correct. :laughing:

**Review by aabadie — APPROVED** [review]
ACK

**Pull request merged**
