### PR TITLE
Add more support for ek-lm4f120xl / lm4f120 (PWM, ADC, GPIO)

### PR DESCRIPTION
**Pull request by dkm**
This is still work in progress.
I've added support for the gpio interface, adc interface (with limitations) and a basic support for PWM.

This is mostly FYI and for feedback

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Hi @dkm, thanks for that work! I'm on holiday for two weeks, starting on Monday. Hence I won't look into your code before then. Sorry...

**Comment by OlegHahm** [comment]
@PeterKietzmann, you can also re-assign.

**Comment by PeterKietzmann** [comment]
AFAIK @haukepetersen is also away and @thomaseichinger is overloaded with code to be reviewed. So if someone stumbles upon this PR, feel free to self-assign :-) . Otherwise it might take some weeks.

**Comment by dkm** [comment]
Hi !
There's no hurry. It's mainly for avoiding duplication as I see activity on this board. I'll continue to maintain and improve the branch and can wait 2 weeks (or more) before getting any feedback :)
Thanks !

**Comment by thomaseichinger** [comment]
@dkm Great, I quickly scanned over it and it looks good. If you have any particular questions or think it is not WIP anymore could you please ping me?

**Comment by dkm** [comment]
I'll split this one into several smaller ones, so closing this PR.

**Pull request closed without merging**
