### PR TITLE
samd21/i2c: wait for bus idle after stop condition

### PR DESCRIPTION
**Pull request by PeterKietzmann**
Follow discussion in #5460. @smlng please verify before merging.

### CODE REVIEW

**Comment by smlng** [comment]
Didn't work for me 😢 

I'm testing with latest RIOT master on samr21-xpro, compiling with 'CFLAGS_OPT = -O0' works. My compiler version is
```
arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 224288]
```

**Comment by PeterKietzmann** [comment]
Hm. I tested tests/driver_tmp006 again, compiled with :

`gcc version 5.2.1 20151202 (release)` and

`gcc version 4.8.4 20140526 (release)`

both worked well... I will pick up your hardware and control the bus signals

**Comment by PeterKietzmann** [comment]
@smlng can you please try this one? I added a delay to wait for the bus to be in idle state again, after the stop condition was sent. I can *not* explain how this is related to compiler optimization or volatile variables (as discussed in #5460) but IMO it is reasonable to wait in there. @gebart what is your opinion in general?

**Comment by smlng** [comment]
@PeterKietzmann: that did the trick, works nicely! I tested with 2 different samr21-xpro boards using RIOT with `tests/driver_tmp006`.

**Comment by PeterKietzmann** [comment]
@kaspar030, @gebart ping?

**Comment by gebart** [comment]
I don't know the hardware details, but if it works then I think you could go with it.

**Comment by PeterKietzmann** [comment]
Ok then I take @smlng's report and your answer as an ACK :-)

**Pull request merged**
