### PR TITLE
cpu/esp32: workaround for UART problems

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides a workaround for the following problems:

1. The UART peripheral clock seems to be sporadically set to wrong value when the CPU clock is changed. In this case, the UART clock is not set to 115.200 kbps but to 96 kbps, so that the output in the console seems like garbage. This can also cause automatic tests to fail.

    Therefore, the system clock is only changed if CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ defines a different default CPU clock than the one already used at boot time.

2. If `stdio` based outputs are mixed with direct calls of `uart_write`, e.g., in `sys/arduino/serialport.cpp`, the TX FIFO of the UART interface can be smashed. Automatic tests may fail in that case.

   Therefore, the TX FIFO buffer is flushed now before the next write operation with `uart_write`.

### Testing procedure

Defining different CPU clocks should work as before.

Use the default CPU clock of 80 MHz
```
make BOARD=esp32-wroom-32 -C tests/bench_sched_nop/ flash test
```
and a CPU of 160 MHz
```
CFLAGS='-DCONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=160' make BOARD=esp32-wroom-32 -C tests/bench_sched_nop/ flash test
```
The result value in second case should be about the double of the value in the first case.

### Issues/PRs references

This PR is required for stability of automatic tests (issue #12763)

### CODE REVIEW

**Comment by benpicco** [comment]
I'm fine with the first patch, but the second one feels a bit hacky.
Are the stdio functions no using the TX FIFO?

If two processes write to the UART at the same time, garbled output is to be expected.

**Comment by benpicco** [comment]
I'm fine with the first patch, but the second one feels a bit hacky.
Are the stdio functions no using the TX FIFO?

If two processes write to the UART at the same time, garbled output is to be expected.

**Comment by gschorcht** [comment]
> I'm fine with the first patch, but the second one feels a bit hacky.
> Are the stdio functions not using the TX FIFO?

Indeed, it's a hack to workaround a problem that came up with `tests/sys_arduino` which calls `uart_write` directly here https://github.com/RIOT-OS/RIOT/blob/af0c6e9319371478dfc0b98975847fae62a31910/sys/arduino/serialport.cpp#L268-L272 that overwrites the TX FIFO for any reason. The result is an output at startup like the following
```
Board configuration:
	ADC		pins=[ 0 2 4 12 13 14 15 25 26 27 32 33 34 35 36 39 ]
	I2C_DEV(0)	scl=22 sda=21
	SPI_DEV(0)	VSPI sck=18 miso=19 mosi=23 cs=5
	SPI_DEV(1)	HSPI sck=14 miso=12 mosi=13 cs=15
	UART_DEV(0)	txd=1 rxd=3
	UART_DEV(1)	txd=10 rxd=9
	LED		pins=[Hello Arduino!
```
and the test for `tests/sys_ardunio` fails.

**Comment by gschorcht** [comment]
BTW, I tried other workarounds. However they affect other tests.

**Comment by aabadie** [comment]
Can you try with  #12461 ?

**Comment by kaspar030** [comment]
> that overwrites the TX FIFO for any reason.

It probably bypasses newlib's stdout buffer?

**Comment by gschorcht** [comment]
> > that overwrites the TX FIFO for any reason.
> 
> ~It probably bypasses newlib's stdout buffer?~ Sorry, didn't look at the code.

Yes, it bypasses newlib's `stdout` buffer. But the problem seems to a bit more complicated. Message `Hello Arduino!` which is directly written using `uart_write` seems to overwrite the existing contents in TX FIFO buffer written from `stdio`. Sometimes, I only see
```
maHelloArduino
```
where `ma` is from the `main(): This is RIOT! (Version: ...` greeting message which is written using newlib`s `stdio` which in turn uses `uart_write` when it is flushed.

That is, it seems that successive calls of `uart_write` overwrite the contents in TX FIFO that is not yet sent.

**Comment by gschorcht** [comment]
@benpicco You should now satisfied with this PR. I was able remove the UART TX FIFO hack in `uart_write`. After an extensive investigation of the problem, I have figured out the reason for the problem with the UART output in `tests/sys_arduino`.

`tests/sys_arduino` calls `SerialPort::begin` which in turn calls again `uart_init` and thus `_uart_config` which simply dropped the output in the UART TX FIFO. Now, `_uart_config` waits until the UART TX FIFO is empty before it changes anything. This fixes the problem.

**Comment by gschorcht** [comment]
@benpicco Thanks for reviewing and merging.

**Pull request merged**
