### PR TITLE
unittest: fix ztimer(64)_initilization #18352 #18365 [backport 2022.07] 

### PR DESCRIPTION
**Pull request by kfessel**
This is the backport of #18352 #18365 which fix some ztimer ztimer64 xtimer_compat induced initialization issues  

### Contribution description

This is the backport of #18352 #18365 which fix some ztimer ztimer64 xtimer_compat induced initialization issues  

### Testing procedure

build and run unittest

there is a (potential) infinity loop that was fixed by #18352 due to double initialization of ztimer (if no ztimer64 was used  ztimer would be initialized a second time by xtimer_init)

and a non initialization of ztimer64 fixed by #18365 ( if xtimer_init didn't do that (which was made visible by #18352)

### Issues/PRs references

Backports: #18352 #18365

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
ACK. Confirmed that this combines the changes from #18352 and #18365

**Comment by miri64** [comment]
Ah sorry, pushed a button without really looking, assuming it was the "Enable auto-merge", but it was actually the "Update branch" button. Please rebase!

**Comment by kfessel** [comment]
I think i did right

**Comment by miri64** [comment]
> I think i did right

Looks like it :-)

**Comment by miri64** [comment]
Needs another rebase...

**Pull request merged**
