### PR TITLE
doc: add RIOT root doxygen example path

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description
add RIOT root to Doxygen example path
and include some Readme.md with their respective doc.txt  

sadly we can't use `@includedoc` or `@include{doc}` until Doxygen 1.9.2 
see https://github.com/doxygen/doxygen/pull/8395

### Testing procedure

read
and
check circleci: doc-build artifact 

eg
https://15379-7370241-gh.circle-artifacts.com/0/doc/group__pkg__u8g2.html
vs
https://doc.riot-os.org/group__pkg__u8g2.html

### Issues/PRs references

#10815

### CODE REVIEW

**Comment by chrysn** [comment]
I generally appreciate rendering more and more of what we have in documentation to where we advertise that our documentation is.

The linked output currently has the markdown included as preformatted text rather than inlined and parsed.

Why the split of doc.txt and README.md for the uwb? I think this would perfectly well as one file, given suitable markup.

Similarly for the others: Why is this split into two files in the first place?

**Comment by kfessel** [comment]
As you can see with the UBW it previously was part of the doc.txt  (empty README.md should be considered an achievement) (at the same time it was unrenderd) - (and the writer did not care or he like how it was more readable)

.md files are much easier to write and to read that these .txt (personal opinion)

README.MD further have the advantage that they are automaticaly render by github 

with doxygen 1.9.2 @include{doc} should work as it should (sandly with 1.9.1 it does not parse markdown)  

https://doc.riot-os.org/group__pkg__uwb__dw1000.html
https://15379-7370241-gh.circle-artifacts.com/0/doc/group__pkg__uwb__dw1000.html
https://github.com/kfessel/RIOT/tree/p-set-doxygen-example-path/pkg/uwb-dw1000

**Comment by kfessel** [comment]
at least a *.md wild card in doc/doxygen/riot.doxyfile:l794 FILE_PATTERNS
 creates a very messy doc
 maybe including doc.md and rewriting (remove that c-comment decoration would be a good solution)

**Comment by kfessel** [comment]
with doc.md
image

**Comment by OlegHahm** [comment]
Is there an estimated release date for doxygen 1.9.2? Would it make sense to wait a little bit?

**Comment by OlegHahm** [comment]
And wouldn't #17575 be the preferred solution?

**Comment by waehlisch** [comment]
> Is there an estimated release date for doxygen 1.9.2?

?? "The latest version of doxygen is 1.9.3 (release date 31 december 2021, updated 3th of January 2022)." https://www.doxygen.nl/download.html#srcbin

**Comment by kfessel** [comment]
#17575 would be nice but it does not work as expected see https://github.com/RIOT-OS/RIOT/pull/17572#issuecomment-1023110127 , i am not sure if there is a doxygen version where that is fixed

1.9.2  (even 1.9.3) is already released but neither in our circleci nor is it used to build doc.riot-os.org 

- as #17580 shows they have diverged a bit making evalution of changes in the circleci artifact less useful

**Comment by OlegHahm** [comment]
Sorry for the late response: apparently I've disabled too many of the GitHub notifications.

Regarding the doxygen version: I was referring to the release of 1.9.2 as part of Debian. Even unstable still contains doxygen 1.9.1.

Given the problem with #17575 I would agree with merging this PR for now and give #17575 another try once a newer doxygen version is available.

**Review by OlegHahm — APPROVED** [review]

**Pull request merged**
