### PR TITLE
driver/ng_at86rfxxx: fixed formatting in header

### PR DESCRIPTION
**Pull request by haukepetersen**
just found it annoying, that there where typedefs in between defines and function definitions...

### CODE REVIEW

**Comment by authmillenon** [comment]
Why does a type definition needs to be in `#ifdef`s anyway?

**Comment by cgundogan** [comment]
Look sane. Waiting for travis' response. BTW, does it make sense to pull the doxy annotations into the `#ifdef` block? Or is doxygen smart enough to omit empty `@brief` statements?

**Comment by authmillenon** [comment]
I'm still confused about the `#ifdef`'d type...

**Comment by authmillenon** [comment]
(doxygen will ignore every build-path not defined in https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/riot.doxyfile#L1986)

**Comment by cgundogan** [comment]
@authmillenon thanks for the hint, but this makes only sense if the `@brief` section is within the `#ifdef`, am I wrong?

**Comment by authmillenon** [comment]
Yes, otherwise doxygen will add the `@brief` to the documentation of `ng_at86rf2xx_t` (and since that contains a `@brief` too I think (but am not sure) will be overwritten).

**Comment by haukepetersen** [comment]
@authmillenon actually I have no idea why the type was ifdef'd. But I would say that is unrelated to this PR, so feel free to open another one...

**Comment by authmillenon** [comment]
Okay.

**Pull request merged**
