### PR TITLE
cpu: added dev_enums.h include to all periph_cpu.h

### PR DESCRIPTION
**Pull request by haukepetersen**
This PR is just a small preparation for updating further peripheral driver interfaces down the line to simplify PR dependencies...

### CODE REVIEW

**Comment by kaspar030** [comment]
Is that file (```dev_enums.h```) already somewhere in master?

**Comment by haukepetersen** [comment]
yes

**Comment by haukepetersen** [comment]
@kaspar030, do you ack this?

**Comment by PeterKietzmann** [comment]
I do. As far as @kaspar030's question was answered with yes I assume he's fine.

**Comment by PeterKietzmann** [comment]
and go

**Pull request merged**
