### PR TITLE
xtimer: Use {} for empty while loops

### PR DESCRIPTION
**Pull request by gebart**
Trivial change

### CODE REVIEW

**Comment by smlng** [comment]
The coding style doesn't make a statement on this, so which way to go? A look into the RIOT code base shows the following:

* `while \(.*\);` found 189 times
* `while \(.*\) {}` found 295 times

so its 2:3 for your suggested solution.

**Comment by kaspar030** [comment]
> its 2:3 for your suggested solution.

AFAIR LLVM complains about ```while(...);```, that's why we're going with the empty braces.

**Comment by gebart** [comment]
Exactly, clang/llvm with some combination of -W options will give warnings on empty while with semicolon, but not with empty braces. 
The braces are good for readability because it shows that the empty while body was intentional and not just a reflex semicolon added by a stressed programmer.

**Comment by smlng** [comment]
I'm fine with that conclusion and consensus, just wanted to point out that we (in RIOT) do not have (or had) a distinct rule on that matter in our coding convention -> should be added and explained to clarify?

**Comment by smlng** [comment]
ah, we alread have 😕 but I only looked at the `indention and braces` section not from the beginning ...

**Pull request merged**
