### PR TITLE
pkg/lwip: fix adaption to API change of netdev_new_api

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Since https://github.com/RIOT-OS/RIOT/pull/21012 a netdev in the new API can return > 0 directly in netdev_driver_t::send() to indicate the driver is naturally synchronous and has already completed the transmission.

The adaption of lwIP to that API change contained a bug: It handled the case after the thread is already blocked waiting for the signal that is never going to arrive. This is now fixed.

#### In `master`

```
$ make BOARD=native64 -C tests/pkg/lwip -j && tests/pkg/lwip/bin/native64/tests_lwip.elf tap1
[...]
RIOT native interrupts/signals initialized.
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2025.01-devel-318-g4044c8)
RIOT lwip test application
> ifconfig
ifconfig
Iface ET0 HWaddr: 26:de:d0:85:bd:b2 Link: up State: up
        Link type: wired
        inet6 addr: fe80:0:0:0:24de:d0ff:fe85:bdb2 scope: link state: tentative (1 probes send)
```

```
$  make BOARD=native64 -C examples/gnrc_networking flash term -j
[...]
2024-12-16 14:58:22,260 # RIOT native interrupts/signals initialized.
2024-12-16 14:58:22,261 # RIOT native board initialized.
2024-12-16 14:58:22,261 # RIOT native hardware initialization complete.
2024-12-16 14:58:22,261 # 
2024-12-16 14:58:22,261 # main(): This is RIOT! (Version: 2025.01-devel-318-g4044c8)
2024-12-16 14:58:22,261 # RIOT network stack example application
2024-12-16 14:58:22,261 # All up, running the shell now
> ping fe80:0:0:0:24de:d0ff:fe85:bdb2
2024-12-16 14:58:23,914 # ping fe80:0:0:0:24de:d0ff:fe85:bdb2
2024-12-16 14:58:26,915 # 
2024-12-16 14:58:26,916 # --- fe80:0:0:0:24de:d0ff:fe85:bdb2 PING statistics ---
2024-12-16 14:58:26,916 # 3 packets transmitted, 0 packets received, 100% packet loss
```

#### This PR

```
$ make BOARD=native64 -C tests/pkg/lwip -j && tests/pkg/lwip/bin/native64/tests_lwip.elf tap1
[...]
RIOT native interrupts/signals initialized.
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2025.01-devel-319-g5ea74-pkg/lwip/adapt-to-netdev_new_new_api)
RIOT lwip test application
> ifconfig
ifconfig
Iface ET0 HWaddr: 26:de:d0:85:bd:b2 Link: up State: up
        Link type: wired
        inet6 addr: fe80:0:0:0:24de:d0ff:fe85:bdb2 scope: link state: valid preferred
```

```
$ make BOARD=native64 -C examples/gnrc_networking flash term -j
[...]
2024-12-16 14:59:14,001 # RIOT native board initialized.
2024-12-16 14:59:14,001 # RIOT native hardware initialization complete.
2024-12-16 14:59:14,001 # 
2024-12-16 14:59:14,002 # main(): This is RIOT! (Version: 2025.01-devel-319-g5ea74-pkg/lwip/adapt-to-netdev_new_new_api)
2024-12-16 14:59:14,002 # RIOT network stack example application
2024-12-16 14:59:14,002 # All up, running the shell now
> ping fe80:0:0:0:24de:d0ff:fe85:bdb2
2024-12-16 14:59:18,610 # ping fe80:0:0:0:24de:d0ff:fe85:bdb2
2024-12-16 14:59:18,611 # 12 bytes from fe80::24de:d0ff:fe85:bdb2%6: icmp_seq=0 ttl=255 time=0.550 ms
2024-12-16 14:59:19,612 # 12 bytes from fe80::24de:d0ff:fe85:bdb2%6: icmp_seq=1 ttl=255 time=0.605 ms
2024-12-16 14:59:20,612 # 12 bytes from fe80::24de:d0ff:fe85:bdb2%6: icmp_seq=2 ttl=255 time=0.522 ms
2024-12-16 14:59:20,612 # 
2024-12-16 14:59:20,613 # --- fe80:0:0:0:24de:d0ff:fe85:bdb2 PING statistics ---
2024-12-16 14:59:20,613 # 3 packets transmitted, 3 packets received, 0% packet loss
2024-12-16 14:59:20,613 # round-trip min/avg/max = 0.522/0.559/0.605 ms
```

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/21012

### CODE REVIEW

**Comment by maribu** [comment]
I tested again after the last force push, still works as before.

I originally assumed that this was just not adapted to the new API; it was, but just a few lines where it should have come.

**Comment by benpicco** [comment]
You can also drop the `if (res < 0) {` case on line 322, this can never be reached.

**Comment by maribu** [comment]
It could be set to an error other than `-EAGAIN` by `confirm_send()` in https://github.com/RIOT-OS/RIOT/blob/424eae0095675b2fdb7489c676f5b7648ae63de9/pkg/lwip/contrib/netdev/lwip_netdev.c#L312

**Comment by maribu** [comment]
Thx :tada:

**Pull request merged**
