### PR TITLE
boards/nucleo-f302r8: add ADC feature

### PR DESCRIPTION
**Pull request by hugueslarrive**
### Contribution description
Add ADC feature.

### Testing procedure
Untested.

### Issues/PRs references
Depends on PR #14860.

### CODE REVIEW

**Comment by aabadie** [comment]
This doesn't build because ADC12_COMMON is not define. Just add an extra commit with the following diff and it will be good:

```diff
diff --git a/cpu/stm32/periph/adc_f3.c b/cpu/stm32/periph/adc_f3.c
index 18e1b11fbe..332169bd08 100644
--- a/cpu/stm32/periph/adc_f3.c
+++ b/cpu/stm32/periph/adc_f3.c
@@ -28,6 +28,12 @@
 #define SMP_SLOW    (0x2) /*< Sampling time for slow channels
                                 (0x2 = 4.5 ADC clock cycles) */
 
+#ifdef ADC1_COMMON
+#define ADC_INSTANCE    ADC1_COMMON
+#else
+#define ADC_INSTANCE    ADC12_COMMON
+#endif
+
 /**
  * @brief   Allocate locks for all available ADC devices
  */
@@ -77,11 +83,11 @@ int adc_init(adc_t line)
      * prescaler is 1 */
     if (!(RCC->CFGR & RCC_CFGR_HPRE_3)) {
         /* set ADC clock to HCLK/1 */
-        ADC12_COMMON->CCR |= ADC_CCR_CKMODE_0;
+        ADC_INSTANCE->CCR |= ADC_CCR_CKMODE_0;
     }
     else {
         /* set ADC clock to HCLK/2 otherwise */
-        ADC12_COMMON->CCR |= ADC_CCR_CKMODE_1;
+        ADC_INSTANCE->CCR |= ADC_CCR_CKMODE_1;
     }
 
     /* Configure the pin */
```

**Comment by hugueslarrive** [comment]
Thanks @aabadie !

**Comment by aabadie** [comment]
You're welcome! This PR is on my todo list for tomorrow's testing.

**Review by aabadie — APPROVED** [review]
Tested and it works.

ACK!

**Pull request merged**
