### PR TITLE
Driver for Freescale MAG3110 Magnetometer

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR add support for Freescale MAG3110 3-Axis Digital Magnetometer.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
`vtimer` works now. Needs squashing and waiting for #2059 to be merged. Then I'll give my final ACK.

**Comment by OlegHahm** [comment]
I think we are ready to go.

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann I think I didn't get what you meant above. Are you willing to merge after the conflicts are solved?

**Comment by PeterKietzmann** [comment]
PS: Without looking deeper in it I assume you just need to rebase and solve conflicts in drivers/Makefile.include

**Comment by LudwigOrtmann** [comment]
@PeterKietzmann
Judging from the chronological order there was some issue with the commit messages which has been resolved since my comment.

Why should this PR wait for #2059?
As far as I can tell the driver is independent from the board.

**Comment by LudwigOrtmann** [comment]
@jfischer-phytec-iot please rebase / resolve the conflicts.

**Comment by PeterKietzmann** [comment]
I was just thinking it's illogical to merge this even if the (only) board which has this sensor is not merged to master. But generally it's independent, that's why we already merged two other sensor drivers of the phyWave board. After rebase I'll finally ACK :-)

**Comment by jfischer-phytec-iot** [comment]
I will rebase thie PR when #2119 will be merged.

**Comment by PeterKietzmann** [comment]
#2119 is merged

**Comment by PeterKietzmann** [comment]
Jippie. And go

**Pull request merged**
