### PR TITLE
sys: xtimer: fix xtimer_now_timex() for values > 16383 seconds

### LINKED ISSUE #4067: bug: xtimer: calculation used in xtimer_now_timex() works only up to 16384 sec

### PR DESCRIPTION
**Pull request by kaspar030**
Fixes #4067.

### CODE REVIEW

**Comment by gebart** [comment]
ACK

**Comment by PeterKietzmann** [comment]
Travis agrees. Isn't that enough?

**Comment by PeterKietzmann** [comment]
@gebart ping! Will you hit the button?

**Comment by gebart** [comment]
done!

**Pull request merged**
