### PR TITLE
gnrc_ipv6: send ICMPv6 "Packet Too Big Message" if packet is too big

### PR DESCRIPTION
**Pull request by Yonezawa-T2**
“Packet Too Big” message is required for Path MTU Discovery. Without “Packet Too Big” message, sender will repeat sending large packets, so that the packets cannot reach the destination forever.

https://tools.ietf.org/html/rfc4443#section-3.2

### CODE REVIEW

**Comment by authmillenon** [comment]
See #3184 for import of ICMPv6 error messages.

**Comment by authmillenon** [comment]
And #3544 for an API to automatically send them.

**Comment by Yonezawa-T2** [comment]
Mostly deprecated. Closing for now.

**Comment by PeterKietzmann** [comment]
Can be closed? If so, please do :-)

**Pull request closed without merging**
