### PR TITLE
core/msg: Add submodule core_msg_prio

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

With submodule `core_msg_prio` enabled, priority message can be send that bypass the regular message queue. By having each thread allocate one slot for a priority message and allowing new priority messages to overwrite pending priority messages, `msg_send_prio()` never blocks or fails. A thread calling `msg_receive()` (or friends) will receive a priority message just like a regular message.
    
This new feature allows to provide both a best effort service (regular messages) and low latency service (priority messages) using the same thread. This feature will come in handy for `gnrc_netif`, which currently does not prioritize ISR requests over send requests. With this feature, it becomes trivial to prioritize ISR requests over regular messages.

The `msg_receive_prio()` is intended for implementing waiting on network devices in `gnrc_netif` until a transmission is complete (so ignoring regular messages), but still serving ISR requests (implemented as prio message) until TX is completed (implemented as prio message).

### Testing procedure

- `BOARD=<YOUR_FAVOURITE_BOARD> make -C tests/msg_prio -j flash test`
- With the exception of the additional thread state name in `ps`, no changes in compiled binaries should be present without module `core_msg_prio` being used.

### Issues/PRs references

None

### CODE REVIEW

**Comment by miri64** [comment]
Why not use the `event` feature for that? See also https://github.com/RIOT-OS/RIOT/pull/13669.

**Comment by maribu** [comment]
> Why not use the event feature for that? See also #13669.

I wasn't aware of this. But I think this might be simpler than the multiplexed msg and event reception, as #13669 pulls in three IPC mechanism: `thread_flags `, `event`, and `core_msg`. Using this approach instead would result in `gnrc_netif` being much simpler. In fact, just avoid lost interrupts would only require one `msg_send()` for the ISR request to be replaced by a `msg_send_prio()` - the remaining code could be unchanged. It would be interesting ro compare RAM & ROM consumption of both approaches.

Also: Priority messages might have use cases outside of netif, which can be catered by this API.

**Comment by maribu** [comment]
> It would be interesting ro compare RAM & ROM consumption of both approaches.

This is slightly better, but no big difference. On my toolchain (which contains a more recent and more bloaty newlib and results in bigger binaries, but the diff should be the same):

`USEMODULE=gnrc_netif_events BOARD=nucleo-f767zi make -C examples/gnrc_networking`:

```
   text	   data	    bss	    dec	    hex	filename
  77480	    176	  28768	 106424	  19fb8	/home/maribu/Repos/software/RIOT/examples/gnrc_networking/bin/nucleo-f767zi/gnrc_networking.elf
```

And with `USEMODULE=core_msg_prio BOARD=nucleo-f767zi make -C examples/gnrc_networking`:
```
   text	   data	    bss	    dec	    hex	filename
  77160	    176	  28752	 106088	  19e68	/home/maribu/Repos/software/RIOT/examples/gnrc_networking/bin/nucleo-f767zi/gnrc_networking.elf
```

With the following patch applied (to make use of `msg_send_prio`):

```diff
diff --git a/sys/net/gnrc/netif/gnrc_netif.c b/sys/net/gnrc/netif/gnrc_netif.c
index c7115143ff..736d19b422 100644
--- a/sys/net/gnrc/netif/gnrc_netif.c
+++ b/sys/net/gnrc/netif/gnrc_netif.c
@@ -1616,9 +1616,7 @@ static void _event_cb(netdev_t *dev, netdev_event_t event)
             msg_t msg = { .type = NETDEV_MSG_TYPE_EVENT,
                           .content = { .ptr = netif } };
 
-            if (msg_send(&msg, netif->pid) <= 0) {
-                puts("gnrc_netif: possibly lost interrupt.");
-            }
+            msg_send_prio(&msg, netif->pid);
         }
     }
     else {
```

So -320 B ROM, - 16 B RAM.

**Comment by miri64** [comment]
My problem with this is that it is YAM—Yet Another Mechanism—which doesn't help with clarity driver-side. It also poses the problem, that like the classic message queue, the prio queue is a finite array, while `event` uses linked lists, so less risk of messages getting lost, if the event issuer adds the events correctly.

**Comment by maribu** [comment]
I disagree that this is yet another mechanism. It extends the feature set of an existing mechanism. The fact that the existing `msg_receive()` will fetch the priority messages just like it fetches normal messages shows that this is not a new mechanism, but an extension.

Note that the event list does not have the real time attributes this has. E.g. when the event queue is also used for other events as proposed in the PR, the ISR event ends up being queued at the end of the list. The ISR callback should however be called as soon as possible.

And events in the event queue are also subject of loss: If an the event is queued again prior it being processed, information is lost. (In the use case of netif, this is IMO also not an issue. In both cases one pending ISR request is guaranteed to not being lost, which is good enough).

For drivers an ISR being served to late often is equally bad as it not being served at all. So IMO just mixing event queue and msg only solves part of the issue. This API can solve it complete, while requiring a change of `+1 -3` lines on the netif implementation. #13669 required `+138 -7` lines.

**Comment by kaspar030** [comment]
> I disagree that this is yet another mechanism.

I think it is. The use case mentioned (ISR message from driver) can be implemented in a couple of other ways using existing mechanisms. For simple flags, a thread flag can be used. If data is needed, events come to mind. both play well with messages, as a thread_flag_wait() can wait for all three.

This PR is adding a side line to core/msg, which is already hard enough to reason about (synchronous messages are delivered in priority-of-sender order, unless there is a message queue, ...). This PR adds (, unless there is a priority message). Similar to the sending side.

For simple flags, a thread flag can be used. If data is needed, events come to mind. both play well with messages, as a thread_flags_wait() can wait for all three.

Also, this further blurs the distinction between the characteristics:

- msgs are receiver allocated, whereas events are sender allocated. thread flags don't need allocation (or are implicitly receiver allocated.
- Sending a message twice either blocks or takes double space, and causes double events. Events and thread flags would trigger only once, but never block on send.
- msg needs all logic at the receiver end, same as thread flags. events come together with the handling logic.
- msg cannot safely be used from ISRs (message gets lost if not waiting or queue full). thread_flags or events can.

IIUC, msg_prio would be a single implicitly allocated message. receiver needs to hold the handling logic. sending twice would never block but always overwrite the previous message. it could be used from isr.
IMO, this is closest to thread_flags, but allows passing along data. I would rather not make msg more complex just for this (and increase the tcb size).

> For drivers an ISR being served to late often is equally bad as it not being served at all. So IMO just mixing event queue and msg only solves part of the issue. This API can solve it complete, while requiring a change of `+1 -3` lines on the netif implementation. #13669 required `+138 -7` lines.

I think a lot of those 138 lines could be shortened. E.g., msg_send also sets a thread flag, so the loop handling both within ` _process_events_await_msg()` can probably shortened to 5 lines.

I'm not sure this API wouldn't cause other issues. As implemented in #13669, the netif thread can handle multiple devices (at least from the event queue side, as an event includes the netdev pointer). That would not be possible using msg_prio. If that is not needed, a simple thread flag would be much simpler anyhow.

**Comment by maribu** [comment]
> For simple flags, a thread flag can be used. If data is needed, events come to mind. both play well with messages, as a thread_flags_wait() can wait for all three.

I don't think that mixing multiple APIs and mechanisms for IPC in a single event loop is a good idea. In the end, all IPC mechanisms try to solve pretty much the same problem and - in the majority of use cases - any IPC mechanism could be used in place of any other. IMO mixing IPC mechanisms is only reasonable if indeed the unique features of all used IPC mechanisms are needed. Otherwise, one should IMO pick one mechanism over the others and convert everything interacting with that event loop to the chosen IPC mechanism.

The problem to solved in https://github.com/RIOT-OS/RIOT/pull/13669 is not solved by any unique feature of `sys/event`. It is solved because the IPC events via the event queue side-step the events via the message queue and allow to implement priorities. The very moment one would (as suggested in #13669) add other sources of events to the event queue, the prioritization of ISR events over everything else would be gone. And while just throwing in one more IPC mechanism to implement a third level of priority would be consistent with the previous approach, this would sounds even less appealing to me that mixing `core_msg` with `event`.

> That would not be possible using msg_prio. If that is not needed, a simple thread flag would be much simpler anyhow.

I don't think that a `gnrc_netif` will be handling multiple devices without major architectural changes, nor that this is on the agenda of GNRC. Handling multiple devices with a single thread would be well aligned with the design goals a single-threaded event based network stack; but GNRC has different design goals. That said, I do like the idea of allowing a network stack to do just that very much and https://github.com/RIOT-OS/RIOT/pull/14660 would be a small step into that direction (and the new IEEE 802.15.4 Radio HAL a big step).

I will give mixing thread flags with messages a try. But let me at least provide an API for that, so that the event loop looks readable. Also e.g. `xtimer_msg_receive_timeout()` could directly make use of that (and a `ztimer_msg_receive_timeout()` as well).

**Comment by kaspar030** [comment]
> I don't think that mixing multiple APIs and mechanisms for IPC in a single event loop is a good idea.
> ...
> I will give mixing thread flags with messages a try. But let me at least provide an API for that, so that the event loop looks readable.

I think mixing would be totally acceptable. thread_flags would be used to wait for msg, events and thread flags:

```
while (1) {
  flags = thread_flags_wait_any(THREAD_FLAG_MSG_WAITING | THREAD_FLAG_EVENT | OTHER_FLAGS);
  if (flags & THREAD_FLAG_MSG_WAITING) {
      handle_messages(); // call msg_try_receive in a loop until no message is available
  }
  if (flags & THREAD_FLAG_EVENT) {
      handle_events(); // call event_get() in a loop until it returns NULL
  }
  if (flags & OTHER_FLAGS) {
     handle_other_flags(); // do whatever
  }
}
```

The order of handling the flags would define the desired priority.

I agree that mixing might look "dirty", but in the end, the different characteristics make sense in different scenarios, which might need to be dealt with from a single event loop. E.g., if only a single ISR like flag is needed, a single thread flag might be the fastest. No need to use an event, if that is implemented on top of thread flags anyways.

**Pull request closed without merging**
