### PR TITLE
openocd.sh: fix binfile on osx

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

OSx default sed does not have the 'gnu' extensions and fails in 'openocd.sh' when flashing a binfile.

It fixes usage of:
 * multiple commands in one line
 * '\n' in replacement string

### Testing procedure

`iotlab-m3` flash base address should work:

```
make -C examples/hello-world/ BOARD=iotlab-m3 binfile flash 'IMAGE_FILE=$(BINFILE)' 2>/dev/null | grep 'Binfile detected, adding ROM base address: 0x08000000' 
Binfile detected, adding ROM base address: 0x08000000
```

And there is currently a debug commit to see if it works with multiple lines.

`_flash_list` should correctly print two lines for `yunjia-nrf51822` board.

```
make -C examples/hello-world/ BOARD=yunjia-nrf51822 binfile flash 'IMAGE_FILE=$(BINFILE)' 2>&1 >/dev/null  | head -n 4
DEBUG
name nrf51 base 0 size 0 bus_width 1 chip_width 1
name nrf51 base 268439552 size 0 bus_width 1 chip_width 1
DEBUG
```

It would be great to also try if all commits are necessary by removing the last one.

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/10065#issuecomment-429820176

### CODE REVIEW

**Comment by cladmi** [comment]
Fixed the first test command.

**Comment by cladmi** [comment]
@emmanuelsearch did you manage to test #10065 with it ?

**Comment by emmanuelsearch** [comment]
Tested on iotlab-m3 and on samr21-xpro

**Comment by emmanuelsearch** [comment]
@cladmi can you squash?

**Comment by cladmi** [comment]
@emmanuelsearch I removed the debug commit and rebased on master.

**Pull request merged**
