### PR TITLE
pkg/semtech-loramac: improve and cleanup doxygen doc

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is improving the code snippet provided in the Loramac-node package documentation by showing that the send function return code should be checked before calling the receive function.

It also fixes a broken link (well no link in fact) to the upstream package in github + adds a missing newline at the end of the file.

### Testing procedure

Just read the generated documentation.

### Issues/PRs references

None

### CODE REVIEW

**Comment by dylad** [comment]
second commit mentions an added newline at EOF but I don't see it.
Otherwise looks good !

**Comment by fjmolinas** [comment]
@aabadie same comment as @dylad.

**Comment by aabadie** [comment]
@fjmolinas, github shows that [line 117](https://github.com/RIOT-OS/RIOT/pull/11370/files#diff-1276ac94a3f40031453aa79e15a4521dR117) has changed : this is just because there's a return added (to fix the missing newline). In gitk, I can see that before there was `\ No newline at end of file` and now it's fine.

**Comment by fjmolinas** [comment]
@aabadie True, confirmed it!

**Comment by fjmolinas** [comment]
GO!

**Comment by aabadie** [comment]
Thank @fjmolinas !

**Pull request merged**
