### PR TITLE
makefiles/suit: make it possible to accept multiple SUIT keys

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

A board may be flashed with a development firmware. The development firmware should accept SUIT updates signed with *both* the development *and* the production key.

Therefore allow to include multiple public keys to verify the SUIT manifest with.

### Testing procedure

Run `tests/suit_manifest` with multiple keys, e.g.

    SUIT_SECS="/home/benpicco/dev/RIOT/keys/default.pem /home/benpicco/.local/share/RIOT/keys/default.pem" make -C tests/suit_manifest all term

The tests should still success even though the 'wrong' key is tried first.

### CODE REVIEW

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by kaspar030** [comment]
re-shuffling merge train:

bors cancel
bors merge

**Comment by miri64** [comment]
bors retry

**Comment by miri64** [comment]
bors cancel
bors merge

**Pull request merged**
