### PR TITLE
cpu, drivers, boards, tests: remove trailing whitespace

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
Also contains some comment reformatting on the go.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
ACK

**Comment by Lotterleben** [comment]
Cool! ACK. Kicked travis. :shipit:

**Comment by Lotterleben** [comment]
(but could you squash the commits, please?)

**Comment by LudwigOrtmann** [comment]
Sure I can.

**Comment by LudwigOrtmann** [comment]
(I could squash or even more carefully split the last one as well if you insist)

**Comment by OlegHahm** [comment]
Kicked T again.

**Comment by LudwigOrtmann** [comment]
@Lotterleben are you satisfied with the commits? Travis is.

**Comment by Lotterleben** [comment]
Me too. :)

**Pull request merged**
