### PR TITLE
[WIP] Initial commit for Particle Photon support.

### PR DESCRIPTION
**Pull request by LaszloLango**
This is a WIP patch of Particle Photon board support. Simple tests are working, but I had some issues with the xtimer, that case failures in AT86RF233 driver. Could you give me some advice what to do with the board specific changes in the RIOT core?

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@LaszloLango Great to see this contribution!

Regarding the changes to core, I understand there is no way to turn off the watchdog timer? If so, maybe arming a timer to reset the wd timer would be a better approach. (Although I am aware of the irony induced by this approach, defeating RIOT's tickless feature.)

**Comment by LaszloLango** [comment]
@thomaseichinger, you need to modify the bootloader of the Photon and re-flash it with a programmer shield to turn off the watchdog.

**Comment by kYc0o** [comment]
@LaszloLango Are you completely sure that you cannot deactivate it at startup? I just remember @astralien3000 having an issue with the USB and some interrupts set up by the bootloader but easily changed at startup.

**Comment by aabadie** [comment]
@LaszloLango, about the interrupt deactivation, have a look at #6589 and #6388. The changes were applied in board.c.

**Comment by LaszloLango** [comment]
@kYc0o, Yes I'm sure. If watchdog is enabled then it cannot be disabled, because of security reasons. The only way is to modify the original bootloader to never enable it.

@aabadie, thank you. That did the trick. Timers seem to work fine now.

@thomaseichinger, my newest problem is inside the at86rf2xx driver. My code stucks in a loop in _set_state. https://github.com/RIOT-OS/RIOT/pull/5244
Any idea?

**Comment by kYc0o** [comment]
> Yes I'm sure. If watchdog is enabled then it cannot be disabled, because of security reasons. The only way is to modify the original bootloader to never enable it.

After some reading I see the point, and since we cannot modify the bootloader, this will be a problem. Let's see where is the best place to reset it, because the actual code in the core is not the way to do.

**Comment by thomaseichinger** [comment]
@LaszloLango What state are you trying to enter when it gets stuck? Also, does it get stuck everytime `_set_state` is called or only every now and then?

**Comment by thomaseichinger** [comment]
@LaszloLango Out of curiosity, are you connecting the OpenLabs 802.15.4 module to the particle board?

**Comment by kYc0o** [comment]
Looking at another PR I found [this](https://github.com/RIOT-OS/RIOT/blob/master/boards/spark-core/board.c#L42). I think that's the way to do with the watchdog.

**Comment by LaszloLango** [comment]
@thomaseichinger, yes. http://openlabs.co/OSHW/Raspberry-Pi-802.15.4-radio

**Comment by LaszloLango** [comment]
@kYc0o, I could not apply that solution to the Photon board.

@thomaseichinger, It does not fail on every call of `_set_state`. If I revert #5244 the `auto_init` finish successfully, but there is no hardware address. Here is the output from `examples/gnrc_networking`

```
> ifconfig
Iface  7   HWaddr: 00:00  Channel: 0  Page: 0  NID: 0x0
           Long HWaddr: 00:00:00:00:00:00:00:00 
           TX-Power: 4dBm  State: IDLE  max. Retrans.: 0 
           MTU:1280  HL:64  
           Source address length: 2
           Link type: wireless
           inet6 addr: ff02::1/128  scope: local [multicast]
           inet6 addr: fe80::ff:fe00:0/64  scope: local
           inet6 addr: ff02::1:ff00:0/128  scope: local [multicast]
           inet6 addr: fe80::cafe:cafe:cafe:1/64  scope: local
           inet6 addr: ff02::1:fffe:1/128  scope: local [multicast]
           inet6 addr: ff02::1a/128  scope: local [multicast]
           
           Statistics for Layer 2
            RX packets 0  bytes 0
            TX packets 1 (Multicast: 1)  bytes 58
            TX succeeded 0 errors 0
           Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 1 (Multicast: 1)  bytes 50
            TX succeeded 1 errors 0

```

Modifications in the Makefile:

```diff
diff --git a/examples/gnrc_networking/Makefile b/examples/gnrc_networking/Makefile
index 2dff6fd..49ba85e 100644
--- a/examples/gnrc_networking/Makefile
+++ b/examples/gnrc_networking/Makefile
@@ -34,6 +34,8 @@ USEMODULE += ps
 USEMODULE += netstats_l2
 USEMODULE += netstats_ipv6
 USEMODULE += netstats_rpl
+USEMODULE += at86rf233
+
 
 # Comment this out to disable code in RIOT that does safety checking
 # which is not needed in a production environment but helps in the
@@ -43,8 +45,8 @@ CFLAGS += -DDEVELHELP
 # Comment the following 2 lines out to specify static link lokal IPv6 address
 # this might be useful for testing, in cases whre you cannot or do not want to
 # run a shell with ifconfig to get the real link lokal address.
-#IPV6_STATIC_LLADDR ?= '"fe80::cafe:cafe:cafe:1"'
-#CFLAGS += -DGNRC_IPV6_STATIC_LLADDR=$(IPV6_STATIC_LLADDR)
+IPV6_STATIC_LLADDR ?= '"fe80::cafe:cafe:cafe:1"'
+CFLAGS += -DGNRC_IPV6_STATIC_LLADDR=$(IPV6_STATIC_LLADDR)
 
 # Comment this out to join RPL DODAGs even if DIOs do not contain
 # DODAG Configuration Options (see the doc for more info)
```

**Comment by thomaseichinger** [comment]
Although the description is different it might still be related since both issues concern the openlabs module. Thus for reference #6750
Will look into that.

**Comment by thomaseichinger** [comment]
Although the description is different it might still be related since both issues concern the openlabs module. Thus for reference #6750
Will look into that.

**Comment by thomaseichinger** [comment]
@LaszloLango Regarding the hardware addresses, can you confirm you are actually building the `luid` module?

In your build output you should see a line like 
```shell
...
"/usr/bin/make" -C RIOTBASE/sys/luid
...
```

**Comment by thomaseichinger** [comment]
Also, could you try applying the patch to `_set_state`mentioned [here](https://github.com/RIOT-OS/RIOT/issues/6750#issuecomment-287390696)

**Comment by LaszloLango** [comment]
@thomaseichinger sorry for the late answer.
1) Yes, I see `"/usr/bin/make" -C RIOTBASE/sys/luid` in the build log.
2) Applied the mentioned patch. I see only one state in the output.
```
...
00 != 19
00 != 19
00 != 19
...
```

**Comment by kbumsik** [comment]
Hi, I am exited about this PR. Since you decided not to use the programmer shield but dfu, shouldn't we use a different ldscript to keep the original linkerscript of stm32f205rb?

**Comment by kYc0o** [comment]
This PR, quickly reviewed, still needs several changes which I'll point out when the WIP flag is removed. 

It means, it will get reviewed when the PR is in a working state and we can actually test it on real hardware. Then usually we will make some comments on the code style and conventions used in RIOT codebase.

**Comment by aabadie** [comment]
ping @LaszloLango ! Very interesting PR, we will be happy to see it in the next release (mid-july). Do you plan to update it in the remaining time ?

**Comment by LaszloLango** [comment]
@aabadie first of all sorry for the long inactivity on this PR. I'm currently busy with other tasks and I think I cannot finish it until the next release.

**Comment by tcschmidt** [comment]
@LaszloLango is there energy to continue work?

**Comment by LaszloLango** [comment]
@tcschmidt, sorry but I have no time to work on this. I do not know when I will have. Feel free to continue my work if anybody interested in it.

**Pull request closed without merging**
