### PR TITLE
periph timer: init does not require return value

### PR DESCRIPTION
**Pull request by OlegHahm**
The return value is not checked anyway and asserting is good enough here.

### CODE REVIEW

**Comment by haukepetersen** [comment]
disagree. For the timer used as base of xtimer that might be fine (as this is initialized and we might as well panic if this is not successful then), but for timers that are used for other purposes, supposedly with a frequency chosen at runtime, the return value is of much interest!

**Comment by OlegHahm** [comment]
> but for timers that are used for other purposes, supposedly with a frequency chosen at runtime

Do you have a usecase for this?

**Comment by OlegHahm** [comment]
Still waiting for the use case? ;-)

**Comment by smlng** [comment]
I'm also against this, a bit of rational (or use-case, so to speak):

Lately I was working on (x)timer problems with cc2538 and discovered that `tests/periph_timer` fails for related boards. The cc2538 has 4 timers, each of which can be configured in 16Bit mode with 2 channels or 32bit mode with a single channel. However, the problem is that in 32 Bit mode only a frequency of 16MHz is supported while in 16Bit mode you can configure any frequency (prescaling is done automatically within the driver). 

The tests (`tests/periph_timer) currently inits all timers with the same frequency of 1MHz and hence  fails for timers in 32 Bit mode. We could use 16MHz which will work with 16 and 32 bit drivers, but on the hand it might be good to extend the test to try different frequencies (if supported). So IMHO it would be reasonable that the init function returns a proper error value if a certain frequency is not supported. That way, we could run timer tests with a range of frequencies and ignore unsupported once.

**Comment by OlegHahm** [comment]
So, the use case is testing?

**Comment by smlng** [comment]
No, I just want to point out that a higher layer might want to use/init a timer with a specific frequency, for instance to achieve a certain accuracy. With RIOT I'm able to write an IoT application without knowing (or caring about) the platform it will run on when deployed - at least I thought that's one goal/benefit of RIOT? That said, it could be that the desired frequency is not supported on all platforms, but the application may define a certain range or set of applicable frequencies. Having an init function with proper (int) return values, it could cope with that.

The alternative would be lots of platform specific defines/configurations?!

**Comment by OlegHahm** [comment]
Usually an application should use xtimer. Here the board initialization takes care of initializing the periph timer correctly. If an application however needs a higher precision than xtimer or has other needs in terms of timer configuration, a try&error timer initialization is most likely not sufficient. In this case the application probably needs to know the speed of the timer during development.

**Comment by smlng** [comment]
inconclusive discussion, remove milestone.

**Comment by OlegHahm** [comment]
Won't continue to work/discuss this issue.

**Pull request closed without merging**
