### PR TITLE
cpu/cortexm: disable interrupts before sleeping

### LINKED ISSUE #6484: boards/nucleo-l1: hard faults with shell?
Running e.g. tests/shell, examples/default or examples/gnrc_networking on a nucelo-l1 hard-faults. I didn't check other nucleo boards nor did I look into details

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #6484 (though temporarily for now)

A real fix will be provided with #6239

### CODE REVIEW

**Comment by haukepetersen** [comment]
Acutally, I changed the fix: The ARM Cortex-M reference manual advises to disable global interrupt before going to sleep. This prevents interrupts that might be triggered right between the execution of the __DSB and the __WFI instruction and would be subsequently lost.

Further there seems to be some hardware issue on some Cortex MCUs (e.g. on the `stm32l1`), that crash when waking up from __WFI with interrupts enabled...

**Comment by PeterKietzmann** [comment]
Did the backport for you in  #6505

**Comment by immesys** [comment]
@haukepetersen, who did this fix, and @kaspar030 who did the new samd21/periph/pm.c. Is this a change that should be made universally? There are 4 places in the code where cortex chips execute __DSB(); __WFI(); and this is only one of them. The other three are in various periph/pm.c files. Should they be changed too?

**Comment by haukepetersen** [comment]
@immesys: yes, it should be generalized -> see #6812

**Comment by miri64** [comment]
There is a new release pending so at this point the backporting-needed label is only noise ;-)

**Pull request merged**
