### PR TITLE
gh-actions: add direct link to circleci doc preview

### LINKED ISSUE #15151: CI: Link to generated documentation
#### Description

The docs built from the doc-build job are publicly available for as long as they exist, on URLs like <https://3723-7370241-gh.circle-artifacts.com/0/doc/index.html>. Finding that entry point requires going through several indirections and logging in to CircleCI.

It Would Be Nice If™ there could be a link to the built documentation in the build checklist. For changes that affect only the documentation, this would allow a thorough review without getting a local checkout of the branch.

### Useful links

The numpy project [has introduced this](https://github.com/numpy/numpy/commit/1a3aa8416033e052e4353548d18a447755afaab4) based on the [circleci-artifacts-redirector-action](https://github.com/larsoner/circleci-artifacts-redirector-action) action, and it looks like this:

ci

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds a github actions that adds a link to the generated documentation preview available on circleci.
As reported in #15151, this PR is simply doing the same [thing that is done for numpy](https://github.com/numpy/numpy/blob/master/.github/workflows/circleci.yml).

### Testing procedure

- Check the direct link to the doc preview is available in the PR checks (below doc-build).

### Issues/PRs references

fixes #15151

### CODE REVIEW

**Comment by aabadie** [comment]
Hmm, according to the README of the [run-circleci-artifacts-redirector](https://github.com/marketplace/actions/run-circleci-artifacts-redirector) action, it's not possible to get the link before it's actually available in master:

> Note: The standard PR-to-main-repo-from-branch-in-a-fork workflow might not activate the action. For changes to take effect, changes might need to be made to to the default branch in a repo with the action enabled. For example, you could iterate directly in master, or in master of a fork. This seems to be a limitation of the fact that CircleCI uses the status (rather than app) API and that this is always tied to the master/default branch of a given repository.

I can try to setup this up on my own repo and report here.

**Comment by miri64** [comment]
> I can try to setup this up on my own fork and report here.

Please do, I trust you that you read the doc correctly, but I rather would prefer to acutally see something.

**Comment by aabadie** [comment]
I opened https://github.com/aabadie/RIOT/pull/20 on my own repo. The action is already in my master branch. It seems to work but let's wait for the whole workflow to complete.

**Comment by aabadie** [comment]
It works :) The direct link to the doc is reported correctly in the PR status.

**Comment by aabadie** [comment]
ping @miri64 ;)

**Comment by miri64** [comment]
> ping @miri64 ;)

Sorry went straight to bed when I came home yesterday, so I had no chance to look at your results yet.

**Review by miri64 — APPROVED** [review]
Output in aabadie#20 looks good. ACK!

**Comment by aabadie** [comment]
Thanks for reviewing !

**Comment by chrysn** [comment]
Thanks for implementing this!

I've tried to observe it in its live glory, but https://github.com/RIOT-OS/RIOT/pull/15419 doesn't have a link added -- even though it's branching off at the current master that has this PR merged, and doc-build has compelted. Is there anything left open to make this visible?

**Comment by aabadie** [comment]
> doesn't have a link added

I confirm the problem, same on #14967 although it's rebased on latest master. I have no idea what's the issue.
It seems to run though (see https://github.com/RIOT-OS/RIOT/actions?query=workflow%3A.github%2Fworkflows%2Fcircleci.yml)

**Comment by miri64** [comment]
Is it me, or is that action only running on merges? Did not look at all of them, but every action I looked at in https://github.com/RIOT-OS/RIOT/actions?query=workflow%3A.github%2Fworkflows%2Fcircleci.yml, ran on a merge commit.

**Comment by aabadie** [comment]
It is supposed to trigger on status changes. Could it be an issue with the github token ?

https://github.com/RIOT-OS/RIOT/blob/948777936dde897505c8e0cd69bb8f2cbe53606a/.github/workflows/circleci.yml#L10

**Comment by aabadie** [comment]
Also it worked like a charm on my repo :)

**Comment by miri64** [comment]
> It is supposed to trigger on status changes.
> 
> https://github.com/RIOT-OS/RIOT/blob/948777936dde897505c8e0cd69bb8f2cbe53606a/.github/workflows/circleci.yml#L1

Now that I look at it again: Shouldn't this rather be

```yaml
on:
  pull_request:
    types: [status]
```

?

> Could it be an issue with the github token ?
> 
> https://github.com/RIOT-OS/RIOT/blob/948777936dde897505c8e0cd69bb8f2cbe53606a/.github/workflows/circleci.yml#L10

That's [provided natively by GitHub](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow) and works like a charm with the `check-label.yml` action.

> Also it worked like a charm on my repo :)

True, but it does not work here ;-).

**Comment by aabadie** [comment]
> True, but it does not work here ;-)

Since it also work on numpy, I guess the issue in on our project config. They are using the same action code.

**Comment by miri64** [comment]
> Since it also works on numpy, I guess the issue in on our project config. They are using the same action code.
> 
> https://github.com/numpy/numpy/blob/a20eca25e9b492efedafea4b7c5d84692d869f7e/.github/workflows/circleci.yml#L1

As far as I can see that action uses no project config, unless the `larsoner/circleci-artifacts-redirector-action` hides some.

**Comment by miri64** [comment]
In case you don't believe me, here are our currently configured secrets (the only project relevant thing I see in the action):

image

As you can see: the `GITHUB_TOKEN` secret is not overwritten.

**Comment by miri64** [comment]
In the doc for the action, there is also a `check-url` step: https://github.com/larsoner/circleci-artifacts-redirector-action#circleci-artifacts-redirector

**Comment by aabadie** [comment]
> there is also a check-url step

I don't think that makes a difference, it's just check in case the doc is not generated correctly.

Do we have all actions enabled in the project settings ?

**Comment by aabadie** [comment]
Maybe enabling debug in the actions as suggested in the README could give some help:

> If you have trouble, try enabling debugging logging for the action by setting the secret ACTIONS_STEP_DEBUG=true

https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging

**Comment by miri64** [comment]
> Do we have all actions enabled in the project settings ?

Do they have to be enabled one by one? For the other actions this wasn't necessary?

**Comment by aabadie** [comment]
> Do they have to be enabled one by one? For the other actions this wasn't necessary?

They don't necessarily have to but they can. I think by default they are all enabled but one can also define a list of enabled actions. I don't know the config for RIOT, but I suppose they are all enabled by default :)

**Comment by aabadie** [comment]
Is there a special config for the circleci webhook ? (especially in "Which events would you like to trigger this webhook?")

**Comment by miri64** [comment]
> Is there a special config for the circleci webhook ? (especially in "Which events would you like to trigger this webhook?")

Which one would that be? This is the current config of the https://circleci.com/hooks/github webhook

image

**Comment by aabadie** [comment]
Same config as the one on my own fork (testing again with https://github.com/aabadie/RIOT/pull/21 and the action still show up). Do you have a list of deliveries below the config ? I think it should contain requests between the action and circleci. Maybe this will give some info.

**Comment by miri64** [comment]
> Same config as the one on my own fork.

I can't see your config ;-). 

> Do you have a list of deliveries below the config ? I think it should contain requests between the action and circleci. Maybe this will give some info.

I have, but the list is very long... Should we maybe make a short call with a screen sharing session so we can sift through them together?

**Comment by aabadie** [comment]
> I can't see your config ;-)

Trust me :)

> the list is very long

I see. On my fork, I had several ones (each time there's a status update on the PR). The most important ones are I think:

<details><summary>Sent while the doc build is in progress (there could be several of this kind)</summary>

image

</details>

<details><summary>Sent when the doc build has completedsummary>

image


</details>

<details><summary>Sent when the link is available</summary>

image

</details>

Maybe you can try and compare with your own fork ?

**Comment by miri64** [comment]
> > I can't see your config ;-)
> 
> Trust me :)

What I meant: I can't configure this repo to be like yours if I don't know what you configured ;-).

**Comment by miri64** [comment]
> > the list is very long
> 
> I see. On my fork, I had several ones (each time there's a status update on the PR). The most important ones are I think:

Well there is a bit more happening in this repo than in your fork, and as you have seen there are also events reported, that don't seem to have anything to do with building the doc...

**Comment by miri64** [comment]
I looked through a few of them, but did not see any `status` Github events btw.

**Comment by miri64** [comment]
Activating this in the Circle CI project settings helped :-)

image

**Pull request merged**
