### PR TITLE
kinetis: Enable UART hardware FIFO buffers.

### PR DESCRIPTION
**Pull request by gebart**
This enables the RX and TX FIFOs in the Kinetis UART hardware module.
Tested on K60, improves RX alot when using high baud rates, I used to lose bytes because of a full RX buffer without this.

This change may affect the timing/latency of TX since we can now queue sizeof(TXFIFO) bytes before blocking when writing to the UART, instead of only writing one byte non-blocking.

Disabled for CPUs without KINETIS_UART_ADVANCED (KW0x etc)

### CODE REVIEW

**Comment by gebart** [comment]
@jfischer-phytec-iot can you test this PR on the Phytec boards?

**Comment by gebart** [comment]
Updated with the proper commit.

**Comment by jfischer-phytec-iot** [comment]
Otherwise it looks good, I have tested it briefly.

**Comment by gebart** [comment]
The UART_PFIFO_TXFIFOSIZE macro is the other way around; left shift, then mask, instead of mask, then right shift.

**Comment by gebart** [comment]
I agree on the indentation, however it is difficult to find a good solution since the macro names are so long.

**Comment by gebart** [comment]
Travis had a hiccup, build is passing now.

**Pull request merged**
