### PR TITLE
icmpv6: put message definitions in their own files

### PR DESCRIPTION
**Pull request by authmillenon**
Depends on #3594 and its dependencies

* moves all message definitions to `net/icmpv6.h`
* Removes the `ng_` prefix from all the effected types and macros.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by authmillenon** [comment]
Reassigned since @haukepetersen asked me to.

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by OlegHahm** [comment]
```
/home/oleg/git/RIOT/sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c: In function ‘ng_ndp_internal_sl2a_opt_handle’
/home/oleg/git/RIOT/sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c:347:14: error: ‘NG_ICMPV6_NBR_SOL’ undeclared (first use in this function)
         case NG_ICMPV6_NBR_SOL:
              ^
/home/oleg/git/RIOT/sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c:347:14: note: each undeclared identifier is reported only once for each function it appears in
/home/oleg/git/RIOT/sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c: In function ‘ng_ndp_internal_tl2a_opt_handle’
/home/oleg/git/RIOT/sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c:387:14: error: ‘NG_ICMPV6_NBR_ADV’ undeclared (first use in this function)
         case NG_ICMPV6_NBR_ADV:
              ^
```

**Comment by authmillenon** [comment]
Already on it ;-)

**Comment by authmillenon** [comment]
Adapted for changes in master.

**Comment by OlegHahm** [comment]
ACK if Travis is green

**Comment by authmillenon** [comment]
Squashed

**Pull request merged**
