### PR TITLE
cpu/sam3: fixed vectors.c

### PR DESCRIPTION
**Pull request by haukepetersen**
This was an error introduced by merging #3194...

### CODE REVIEW

**Comment by thomaseichinger** [comment]
ACK

**Comment by haukepetersen** [comment]
rebased.

**Comment by haukepetersen** [comment]
Since without this the current master is broken and all Travis builds will fail, I take the courage to merge without waiting for Travis...

**Comment by OlegHahm** [comment]
I still don't get the logic. Isn't it the purpose of this PR to fix building?

**Pull request merged**
