### PR TITLE
pkg/lwip: Start DHCP early for all Ethernet interfaces

### PR DESCRIPTION
**Pull request by yarrick**
### Contribution description

Change the special case hack for native tap interfaces into a general start
of DHCP for all Ethernet interfaces. 

Netifs without link status support will keep sending discover
messages with increasing time between.
    
Netifs that support link status will wait for the link to be up,
and then start sending.
    
Netifs that support link status but send no link status events
will continue to not work (unless link status is up from the
first check when setting it up).

### Testing procedure

Test for native board in `tests/lwip` still passes (in dualstack & v6 only)

Boards without link status support will now have DHCP starting properly (there can be a delay from inserting cable until DHCP sends next discover message).

Boards with link status event support will send DHCP discover right away after link comes up.

### Issues/PRs references

Depends on and includes #16082 

Removes hack from #14150

### CODE REVIEW

**Comment by yarrick** [comment]
Ping @benpicco , this is what I mentioned earlier.

**Comment by benpicco** [comment]
I can confirm this works. I now get an address on `same54-xpro`

```
2021-03-25 13:55:52,018 # Iface ET0 HWaddr: fc:c2:3d:0d:2d:1f Link: up State: up
2021-03-25 13:55:52,020 #         Link type: wired
2021-03-25 13:55:52,026 #         inet addr: 192.168.42.103 mask: 255.255.255.0 gw: 192.168.42.1
2021-03-25 13:55:52,040 #         inet6 addr: fe80:0:0:0:fec2:3dff:fe0d:2d1f scope: link
2021-03-25 13:55:52,047 #         inet6 addr: 2001:16b8:45c3:ac00:fec2:3dff:fe0d:2d1f scope: global
```

**Comment by benpicco** [comment]
@maribu what to give this a try on stm32, as that implements `NETDEV_EVENT_LINK_UP`

**Comment by maribu** [comment]
> @maribu what to give this a try on stm32, as that implements `NETDEV_EVENT_LINK_UP`

I do get an IPv4 address from a DHCP server in `tests/lwip`. This also uncovered a bug in the stm32 Ethernet driver, but that can be merged independently.

**Review by benpicco — APPROVED** [review]

**Comment by fjmolinas** [comment]
All green GO!

**Pull request merged**
