### PR TITLE
examples: gnrc_tftp: add bluepill board to insufficient memory list

### PR DESCRIPTION
**Pull request by miri64**
The NIB makes this application (for now) to big for this board. So put it into the list of boards with insufficient memory for now.

### CODE REVIEW

**Comment by kYc0o** [comment]
Well actually I have another problem... This board has a bootloader which can be overwritten if you flash it using a SWD adaptor (like ST-Link), in which case you can use the whole memory. However, if you decide to use the internal bootloader the size of the ROM is decreased by 8K, which don't fit in the examples found by Murdock on #7799.

This PR got merged before I thought about it, I wanted to ask you to include the examples found by Murdock...

I guess I need to open a new one...

**Comment by miri64** [comment]
> This PR got merged before I thought about it, I wanted to ask you to include the examples found by Murdock...

1) Adding a board to the list of boards with insufficient memory doesn't mean Murdock doesn't build (i.e. compile) it anymore, it just isn't linked, so I'm not sure what you mean by that.
2) The plan is to optimize GNRC after #7925 was merged (my personal goal is to be able to run on `chronos`, but maybe that is to high set ^^) and then this list will shrink again anyway.

> This PR got merged before I thought about it, I wanted to ask you to include the examples found by Murdock...
>
> I guess I need to open a new one...

3) This PR is against `gnrc_netif2_integration/master`, not `master` ;-).

**Comment by bergzand** [comment]
> This PR got merged before I thought about it,

Sorry if I was too trigger-happy with this PR. As @miri64 said, the code is still build, but not linked, so I didn't see too much harm in this

**Comment by miri64** [comment]
@bergzand no worries. @kYc0o and I just discussed this online. Actually his comment was supposed to say, that due to the mentioned bootloader, the available space is actually *smaller* than the linker script suggests (which ignores the bootloader entirely). So adding it to `BOARD_INSUFFICIENT_MEMORY` was definitely the right call (for now).

**Pull request merged**
