### PR TITLE
gnrc_sixlowpan_frag/rbuf: centralize gnrc_pktbuf_release()

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This moves all releases of `pkt` in `_rbuf_add()` to `rbuf_add()`

### Testing procedure
`tests/gnrc_sixlowpan_frag` should still compile and pass. Packet exchange between two `iotlab-m3` or `samr21-xpro` should see no significant change.

### Issues/PRs references
None.

### CODE REVIEW

**Comment by cgundogan** [comment]
Looks good on first sight. Will test later today!

**Comment by cgundogan** [comment]
```
> 2019-01-29 19:07:57,871 - INFO #  sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c:226 => 0xd49
2019-01-29 19:07:57,873 - INFO # *** RIOT kernel panic:
2019-01-29 19:07:57,875 - INFO # FAILED ASSERTION.
```

This is what I get after waiting for 1-2 minutes with the `gnrrc_networking` application and either a samr or iotlab node.

I don't get this on master.

**Comment by miri64** [comment]
Will check!

**Comment by miri64** [comment]
Confirmed. I'm investigating.

**Comment by miri64** [comment]
This line is the problem:

https://github.com/RIOT-OS/RIOT/blob/a249ebd2a14edb0e403d2fed626886b7f7520e08/sys/net/gnrc/network_layer/sixlowpan/frag/rbuf.c#L168

See also http://doc.riot-os.org/group__net__gnrc__sixlowpan.html.

**Comment by miri64** [comment]
Okay ... 000379729e4a809229c11239218230b34e3e1cb9 fixes that, but compared to master it gains 40 bytes on `iotlab-m3`. Even though the code is more beautify this just isn't worth it. So nevermind.

**Pull request closed without merging**
