### PR TITLE
style: uncrustify: remove spaces between pointer stars

### PR DESCRIPTION
**Pull request by authmillenon**
See https://github.com/RIOT-OS/RIOT/pull/4266/files#r44786853

### CODE REVIEW

**Comment by OlegHahm** [comment]
Untested ACK

**Comment by authmillenon** [comment]
I encountered an issue with function pointers when trying to uncrustify `sys/net/` but I don't think it was related to this.

**Comment by authmillenon** [comment]
Yupp, its unrelated:

```
[martine@beutlin RIOT]<3 uncrustify -l C -c uncrustify-riot.cfg --no-backup sys/include/net/gnrc/gnrc_netdev2.h
Parsing: sys/include/net/gnrc/gnrc_netdev2.h as language C
[martine@beutlin RIOT]<3 git diff
diff --git a/sys/include/net/gnrc/gnrc_netdev2.h b/sys/include/net/gnrc/gnrc_netdev2.h
index d04c538..1c87584 100644
--- a/sys/include/net/gnrc/gnrc_netdev2.h
+++ b/sys/include/net/gnrc/gnrc_netdev2.h
@@ -65,7 +65,7 @@ struct gnrc_netdev2 {
      * device and convert it into a pktsnip while adding a netif header
      * and possibly marking out higher-layer headers.
      */
-    gnrc_pktsnip_t * (*recv)(gnrc_netdev2_t *dev);
+    gnrc_pktsnip_t * (*recv)(gnrc_netdev2_t * dev);
 
     /**
      * @brief netdev2 handle this adapter is working with
@@ -91,7 +91,7 @@ struct gnrc_netdev2 {
  * @return KERNEL_PID_UNDEF on error
  */
 kernel_pid_t gnrc_netdev2_init(char *stack, int stacksize, char priority,
-                        const char *name, gnrc_netdev2_t *gnrc_netdev2);
+                               const char *name, gnrc_netdev2_t *gnrc_netdev2);
 
 #ifdef __cplusplus
 }
```

**Comment by authmillenon** [comment]
(That result is true for both master and this PR ;-))

**Comment by authmillenon** [comment]
Travis is happy btw.

**Pull request merged**
