### PR TITLE
gnrc_netif_pktq: add function to check usage

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This adds a new function to the API of `gnrc_netif_pktq` to check how much resources (i.e. number of entries in the pool) are currently in use.

### Testing procedure
I extended the unittests, so they should still pass.
gnrc_netif_pktq: add function to check usage

### Issues/PRs references
None

### CODE REVIEW

**Comment by jia200x** [comment]
It passes:
```
main(): This is RIOT! (Version: 2021.04-devel-1037-g6507d-copr/16193)
Help: Press s to start test, r to print it is ready
READY
s
START
.........
OK (9 tests)
```

**Review by jia200x — APPROVED** [review]
ACK

**Comment by miri64** [comment]
Thanks!

**Comment by miri64** [comment]
The failing test seems unrelated, but will have a look.

**Comment by miri64** [comment]
Mhhhh could not reproduce locally. I will rerun Murdock.

**Comment by miri64** [comment]
Thanks @kaspar030 for investigating and for fixing! Let's go with this one!

**Pull request merged**
