### PR TITLE
makefiles/tools/programmer: do not use wrapper with jlink

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

J-Link can get stuck in a

 > Mass erase done!

loop that is hidden with the programmer wrapper.

### Testing procedure

This typically happens with a loose wire or somehow odd state of J-Link or the CPU.

The wrapper will spin forever until aborted, the it reveales that it would print

```
Connecting to target via SWD
InitTarget() start
InitTarget()
Secured Atmel SAMD device detected.
For debugger connection the device needs to be unsecured.
Note: Unsecuring will trigger a mass erase of the internal flash.
Executing default behavior previously saved in the registry.
Device will be unsecured now.
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
Mass erase done!
```

in the meantime.

### CODE REVIEW

**Comment by fjmolinas** [comment]
This is starting to beat the whole purpose of the wrapper now... If I recall correctly it was added mainly for jlink..., should it still be on by default?

**Comment by aabadie** [comment]
Another solution I was thinking of is to add a timeout in the wrapper script.

**Comment by benpicco** [comment]
> should it still be on by default?

I don't think so. The wrapper looks nice, but it's hiding information from the programmer and by that causes more trouble only for the sake of aesthetics. 

Programming can be finicky and this wrapper is just stealing people's time.

I can provide an alternative PR to disable the wrapper by default.

**Comment by aabadie** [comment]
> should it still be on by default?

Yes definitely, in terms of user experience I see it as a big plus. The only thing that is missing, as I mentioned above, is something to manage a timeout in case the underlying process is stuck.
Otherwise, there's no point in having such a sophisticated wrapper script and it could just be completely removed.

**Comment by aabadie** [comment]
> only for the sake of aesthetics.

The build system is also do that to hide calls to the compiler (QUIET=0). Should we also disable this by default ? I already had to do that to debug issues when building (include directories, etc) because the current build lines hide that information.

**Comment by fjmolinas** [comment]
> > should it still be on by default?
> 
> Yes definitely, in terms of user experience I see it as a big plus. The only thing that is missing, as I mentioned above, is something to manage a timeout in case the underlying process is stuck.
> Otherwise, there's no point in having such a sophisticated wrapper script and it could just be completely removed.

Sure, if the script is improved then it makes sense to keep it, will you consider doing it @aabadie?

**Comment by aabadie** [comment]
> if the script is improved then it makes sense to keep it, will you consider doing it @aabadie?

See #16370

**Comment by benpicco** [comment]
> The build system also does that to hide calls to the compiler (QUIET=0). Should we also disable this by default?

The compilation process is very predictable and can't be interfered by lose wires or MCUs/Programmers in weird states.
If it works one, it will work always.

The same is not true for programming, especially when dealing with sometimes flaky physical connections.

**Comment by fjmolinas** [comment]
Not relevant since #16371

**Pull request closed without merging**
