### PR TITLE
lpc2387: Fix wrong factor in driver poll-timer

### LINKED ISSUE #4530: MSBA2 MCI Driver timer issue
I've run into an odd problem where a long-running operation (block erase) on the MSBA2s SDcard interface fails. If I'm not mistaken, the problem lies [on this line of code](https://github.com/RIOT-OS/RIOT/blob/master/cpu/lpc2387/mci/lpc2387-mci.c#L480), the `xtimer_now()` invocation below. According to the function description, the `tmr` value should have millisecond resolution. Given that `xtimer` provides microsecond resolution, the factor being applied should be `1000` instead of `100`, right? :confused: 

    [...]
    /**
     * @param tmr   Timeout in unit of 1ms
     * @returns 1 when card is tran state, otherwise returns 0
     */
    static int wait_ready(unsigned short tmr)
    {
        unsigned long rc;

        //                                       vvv wrong factor?
        uint32_t stoppoll = xtimer_now() + tmr * 100;
        bool bBreak = false;
    [...]

### PR DESCRIPTION
**Pull request by x3ro**
Fixes #4530

### CODE REVIEW

**Comment by BytesGalore** [comment]
nice, ACK

**Comment by cgundogan** [comment]
OT: @gebart do you have some hooks on your side? I checked the webhooks of this repository quickly, but I couldn't find something suspicious for now..

**Comment by cgundogan** [comment]
@gebart the `in progress` label might come from waffle.io. Do you have any knowledge about that?

**Comment by cgundogan** [comment]
OT: I deactivated the waffle.io webhook that was in RIOT's repo. Let's see if that fixes something.

**Comment by BytesGalore** [comment]
Murdock is happy -> Gogogogo

**Comment by gebart** [comment]
@cgundogan I may have signed in on waffle.io once when it was being discussed in a mail discussion before, but not used it since then. I've revoked the access token for waffle to my account now as well.

**Pull request merged**
