### PR TITLE
pkg/fatfs: fix mkfs on native

### LINKED ISSUE #7795: tests/pkg_fatfs *mkfs* not functional
Testing 2017.10-RC1:
In the shell *mkfs* always returns ``[FAILED] error 1 ``. Even if an image file has been created.
All other functions are O.K.

### PR DESCRIPTION
**Pull request by MichelRottleuthner**
Fixes #7795.
To verify run the following from tests/pkg_fatfs:
```
dd if=/dev/zero of=riot_fatfs_disk.img bs=1M count=128
make && make term
mkfs 0 fat
mount 0
touch testfile
ls
<various combinations of read and write if you like>
```
Keep in mind the exfat option of mkfs wont work if not enabled explicitly at compile time.

What the fix actually does: there was a missing include, that lead to `#if (_USE_MKFS == 1)` never beeing true. Also I added some debug messages that would have helped to find the error.

### CODE REVIEW

**Comment by haukepetersen** [comment]
@A-Paul: are you going to test this PR?

**Comment by A-Paul** [comment]
> @A-Paul: are you going to test this PR?
@haukepetersen, I just arrived on campus. I'll check within the next our.

**Comment by haukepetersen** [comment]
perfect!

**Comment by haukepetersen** [comment]
nice. All green, so go!

**Comment by haukepetersen** [comment]
@MichelRottleuthner @A-Paul : could one of you provide a backport for this PR until tomorrow morning? Thanks a lot!

**Comment by A-Paul** [comment]
@haukepetersen Backport is here: https://github.com/RIOT-OS/RIOT/pull/7821

**Pull request merged**
