### PR TITLE
feather-m0: add usbdev feature

### PR DESCRIPTION
**Pull request by ynezz**
### Testing procedure

Tested this successfully with #11077

### CODE REVIEW

**Comment by dylad** [comment]
I don't have the board but it should be good.
Maybe @aabadie can give it a try quickly with examples/usbus_minimal and check lsusb output.

**Comment by aabadie** [comment]
> Maybe @aabadie can give it a try quickly with examples/usbus_minimal and check lsusb output.

Sure!

**Comment by miri64** [comment]
Mine's the only one I have at home, but sadly tightly integrated into a project ^^.

**Comment by miri64** [comment]
The project is [this one](https://twitter.com/miri_64/status/1098329628924612639) ;-)

**Comment by miri64** [comment]
This PR (+ #11085) would have helped *a lot* with debugging that back then :grin:

**Pull request merged**
