### PR TITLE
boards/remote: new revision B

### PR DESCRIPTION
**Pull request by alignan**
The new RE-Mote revision B is an update on the revision A, comprising improves in manufacturing and simplifications some of the RE-Mote features, like the power management block. The revision B also exposes more pins in the side connectors, increasing the number of ADC channels available (shared with the microSD) via configuration resistors, etc.

A full list of the changes from revision A to B can be browsed [in the Wiki page](https://github.com/Zolertia/Resources/wiki/RE-Mote:-Enhancements-from-Rev.A-to-Rev.B)

This PR sits on top of  https://github.com/RIOT-OS/RIOT/pull/5823

### CODE REVIEW

**Comment by smlng** [comment]
FYI: tried to run this (including #5823). Got the following failure:

```
2016-09-19 14:52:03,442 - INFO # > 0x205449
2016-09-19 14:52:03,443 - INFO # *** RIOT kernel panic:
2016-09-19 14:52:03,444 - INFO # FAILED ASSERTION.
2016-09-19 14:52:03,444 - INFO # 
2016-09-19 14:52:03,447 - INFO # 	pid | name                 | state    Q | pri | stack ( used) | base       | current    
2016-09-19 14:52:03,449 - INFO # 	  - | isr_stack            | -        - |   - |   512 (  180) | 0x20000000 | 0x200001c8
2016-09-19 14:52:03,451 - INFO # 	  1 | idle                 | pending  Q |  15 |   256 (  128) | 0x2000041c | 0x2000049c 
2016-09-19 14:52:03,452 - INFO # 	  2 | main                 | bl mutex _ |   7 |  1536 (  740) | 0x2000051c | 0x2000099c 
2016-09-19 14:52:03,454 - INFO # 	  3 | pktdump              | bl rx    _ |   6 |  1536 (  240) | 0x200031f4 | 0x20003704 
2016-09-19 14:52:03,456 - INFO # 	  4 | 6lo                  | running  Q |   3 |  1024 (  572) | 0x20003dc4 | 0x200040ac 
2016-09-19 14:52:03,457 - INFO # 	  5 | ipv6                 | bl rx    _ |   4 |  1024 (  372) | 0x20001118 | 0x2000141c 
2016-09-19 14:52:03,459 - INFO # 	  6 | udp                  | bl rx    _ |   5 |  1024 (  264) | 0x200045cc | 0x200048c4 
2016-09-19 14:52:03,460 - INFO # 	  7 | cc2538_rf            | bl rx    _ |   3 |  1024 (  340) | 0x20000c88 | 0x20000f94 
2016-09-19 14:52:03,461 - INFO # 	  8 | RPL                  | bl rx    _ |   5 |  1024 (  216) | 0x200039ac | 0x20003cec 
2016-09-19 14:52:03,462 - INFO # 	    | SUM                  |            |     |  8960 ( 3052)
2016-09-19 14:52:03,462 - INFO # 
2016-09-19 14:52:03,462 - INFO # *** halted.
2016-09-19 14:52:03,463 - INFO # 
2016-09-19 14:52:03,463 - INFO # Stack pointer corrupted, reset to top of stack
2016-09-19 14:52:03,464 - INFO # FSR/FAR:
2016-09-19 14:52:03,464 - INFO #  CFSR: 0x00000000
2016-09-19 14:52:03,464 - INFO #  HFSR: 0x80000000
2016-09-19 14:52:03,465 - INFO #  DFSR: 0x00000002
2016-09-19 14:52:03,465 - INFO #  AFSR: 0x00000000
2016-09-19 14:52:03,465 - INFO # Misc
2016-09-19 14:52:03,466 - INFO # EXC_RET: 0xfffffffd
```

It happens shortly after I switched interface channel to one where some other nodes are transmitting, might be related to packet reception. However, that's wild guessing at the moment. 

I will investigate further.

**Comment by smlng** [comment]
I enabled debugging in `sys/net/gnrc/link_layer/netdev2/gnrc_netdev2.c` and `sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_ieee802154.c`. Again, switched channel, here the output:

```
2016-09-19 15:03:57,479 - INFO # ifconfig 7 set channel 16
2016-09-19 15:03:57,481 - INFO # gnrc_netdev2: GNRC_NETAPI_MSG_TYPE_SET received. opt=NETOPT_CHANNEL
2016-09-19 15:03:57,484 - INFO # gnrc_netdev2: response of netdev->set: 2
2016-09-19 15:03:57,486 - INFO # gnrc_netdev2: waiting for incoming messages
2016-09-19 15:03:57,488 - INFO # success: set channel on interface 7 to 16
2016-09-19 15:04:00,693 - INFO # > gnrc_netdev2: GNRC_NETDEV_MSG_TYPE_EVENT received
2016-09-19 15:04:00,695 - INFO # gnrc_netdev2: event triggered -> 2
2016-09-19 15:04:00,696 - INFO # _recv_ieee802154: received packet from  of length 0
2016-09-19 15:04:00,698 - INFO # 000000_recv_ieee802154: reallocating.
2016-09-19 15:04:00,699 - INFO # gnrc_netdev2: waiting for incoming messages
2016-09-19 15:04:00,700 - INFO # gnrc_netdev2: GNRC_NETDEV_MSG_TYPE_EVENT received
2016-09-19 15:04:00,701 - INFO # gnrc_netdev2: event triggered -> 2
2016-09-19 15:04:00,703 - INFO # RFCORE_ASSERT(RFCORE_XREG_RXFIFOCNT > 0) failed at line 81 in rfcore_read_byte()!
2016-09-19 15:04:00,704 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-19 15:04:00,706 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-19 15:04:00,706 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-19 15:04:00,707 - INFO # gnrc_netdev2: waiting for incoming messages
2016-09-19 15:04:00,708 - INFO # gnrc_netdev2: GNRC_NETDEV_MSG_TYPE_EVENT received
2016-09-19 15:04:00,709 - INFO # gnrc_netdev2: event triggered -> 2
2016-09-19 15:04:00,710 - INFO # RFCORE_ASSERT(RFCORE_XREG_RXFIFOCNT > 0) failed at line 81 in rfcore_read_byte()!
2016-09-19 15:04:00,711 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-19 15:04:00,712 - INFO # _recv_ieee802154: received packet from  of length 0
2016-09-19 15:04:00,712 - INFO # 000000_recv_ieee802154: reallocating.
2016-09-19 15:04:00,713 - INFO # gnrc_netdev2: waiting for incoming messages
2016-09-19 15:04:00,714 - INFO # gnrc_netdev2: GNRC_NETDEV_MSG_TYPE_EVENT received
2016-09-19 15:04:00,715 - INFO # gnrc_netdev2: event triggered -> 2
2016-09-19 15:04:00,782 - INFO # RFCORE_ASSERT(RFCORE_XREG_RXFIFOCNT > 0) failed at line 81 in rfcore_read_byte()!
2016-09-19 15:04:00,783 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-19 15:04:00,785 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-19 15:04:00,786 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-19 15:04:00,787 - INFO # gnrc_netdev2: waiting for incoming messages
```

**Comment by alignan** [comment]
Hi!

I think this error is unrelated to the PR, and probably common to all CC2538-based platforms.

I tested with the `gnrc_networking` example and two `RE-Motes`, one pinging the other, and the second one switching channels back and forth, and I haven't been able to reproduce, do you have any tip on how to reproduce?  Cheers!

**Comment by smlng** [comment]
Hi @alignan,

you're probably right, that all cc2538 platforms are affected. As I already said, it was just a quick test of your changes, but the failure points into something network or net driver related. I tested as follows: I flashed a `remote-revb` with gnrc_networking (including your 2 PRs) which worked fine. I also have another test setup consisting of 2 PhyNodes (`pba-d-01-kw2x`) that communicate with a raspberry pi (with openlabs transceiver) based border router.

When I run `remote-revb` on default channel and pan (26 and 0x23) no failure (even after minutes), but as soon as I switch to channel 16 where the phynodes and the RPi are transmitting, the remote goes into hardfault or failed assertion as shown above.

**Comment by smlng** [comment]
I think I can verify your scenario with 2 `remote-revb`, today, and then I'll try to add an RPi (with openlabs transceiver) to this setup. I'll report the outcome ...

**Comment by alignan** [comment]
Thanks!

**Comment by smlng** [comment]
@alignan I can confirm your scenario is working, having just tried with 2 RE-motes revision B on an isolated channel. So as long as the remote are on their own, without any foreign device they can ping each other.

UDP send and receive is working, too. Btw. I again use `gnrc_networking` with PRs as stated above.

I will proceed with my tests, and will now add some foreign devices - namely PhyNodes and RPi with OpenLabs.

**Comment by smlng** [comment]
@alignan I just tried one `remote-revb` with a PhyTec `pba-d-01-kw2x`. It works somewhat, that is I can ping; no kernel panic... 

But this output, with lots of failed assertions:
```
2016-09-20 11:50:48,552 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,553 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,618 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,619 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,621 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,622 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,624 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,626 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,627 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,628 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,630 - INFO # RFCORE_ASSERT(RFCORE_XREG_RXFIFOCNT > 0) failed at line 81 in rfcore_read_byte()!
2016-09-20 11:50:48,631 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,632 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,633 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,634 - INFO # RFCORE_ASSERT(RFCORE_XREG_RXFIFOCNT > 0) failed at line 81 in rfcore_read_byte()!
2016-09-20 11:50:48,634 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,635 - INFO # RFCORE_ASSERT(NOT(flags & RXUNDERF)) failed at line 42 in isr_rfcoreerr()!
2016-09-20 11:50:48,636 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:50:48,636 - INFO # _recv_ieee802154: received packet from  of length 30
2016-09-20 11:50:48,637 - INFO # 000000 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d
2016-09-20 11:50:48,638 - INFO # 000010 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d
2016-09-20 11:50:48,639 - INFO # _recv_ieee802154: reallocating.
2016-09-20 11:50:48,640 - INFO # gnrc_netdev2: waiting for incoming messages
```

I still have debugging enabled in the netdev2 files (see above).

**Comment by smlng** [comment]
Maybe of interest, too, is this failed assertion:

```
2016-09-20 11:53:08,569 - INFO #   RFCORE_SFR_RFERRF = 0x00
2016-09-20 11:53:08,571 - INFO # _recv_ieee802154: received packet from  of length 1
2016-09-20 11:53:08,571 - INFO # 000000 07
2016-09-20 11:53:08,572 - INFO # _recv_ieee802154: reallocating.
2016-09-20 11:53:08,573 - INFO # gnrc_netdev2: waiting for incoming messages
2016-09-20 11:53:11,090 - INFO # gnrc_netdev2: GNRC_NETDEV_MSG_TYPE_EVENT received
2016-09-20 11:53:11,092 - INFO # gnrc_netdev2: event triggered -> 2
2016-09-20 11:53:11,094 - INFO # RFCORE_ASSERT(rssi_val > CC2538_RF_SENSITIVITY) failed at line 340 in _recv()!
```

Getting lots of this, when running in parallel with the PhyTec board

**Comment by smlng** [comment]
Another observation: sending pings with large payload (e.g. 256B) will result in fragmentation, with multiple frames arriving in a short interval which the cc2538 receiver cannot handle/offload fast enough. Hence, dropped frames which results in 100% packet loss for large ping packets.

**Comment by smlng** [comment]
This seems to be the core problem: fast packet handling. Something is too slow in during packet reception which always results in this failed assertion, and sometimes even in a kernel panic.

**Comment by alignan** [comment]
See https://github.com/RIOT-OS/RIOT/issues/5786

Perhaps we should move the conversation there, as it is unrelated to the PR :-)

**Comment by aeneby** [comment]
@sming you are probably right - the cc2538 driver does not handle multiple packets in the RX FIFO, currently. The RX underflow assertions are occurring because two packets are received (in very quick succession, i.e. both placed in the same FIFO) and therefore two interrupts generated, but after the first packet is processed the RX FIFO is flushed. So when RIOT asks for the second packet, the FIFO is empty.

Unfortunately I haven't had time to look into this further, but now that more people are testing in "busier" environments with more RF activity, I think it will become a more urgent problem to fix. Anyway, as @alignan mentioned, let's discuss this further on #5786.

**Comment by smlng** [comment]
@aeneby yes it's definitely getting urgent, is it easily feasible to move the _flush_ out of the isr routine?

**Comment by aeneby** [comment]
@smlng I don't think it's the flush in the isr which is the issue here, but rather in the driver's recv() function. But again, let's discuss this further in #5786 :)

**Comment by PeterKietzmann** [comment]
The code looks fine for me and I did some basic testing. Once we agreed in #5823 we can merge this one.

**Comment by smlng** [comment]
With #5891 by @kaspar030 merged into master recently, this PR needs a file `Makefile.dep` in `boards/remote-rev*` with content:
```
include $(RIOTBOARD)/remote-common/Makefile.dep
```

Otherwise (atleast) the radio driver is missing ....

**Comment by smlng** [comment]
needs rebase and adaption, see my comment above - would still be great to have this in the upcoming release!

**Comment by alignan** [comment]
Why was this closed?  I have a high work load right now, but we are working on the related topics... a heads up would be great next time! (or this was it? :smile:  )

**Comment by PeterKietzmann** [comment]
@alignan we need that board supported in master for an ongoing project and you haven't been responsive for some time. In addition, this PR is/was based on the ADC driver which needed some adoptions but the general port worked. @smlng (cherry-)picked your board commit, adapted it to #5891 and opened a new PR (#5978) so we can speed up the merge process before we land in feature freeze

**Comment by sming** [comment]
Guys, WRONG SMING!

⁣

Sent from TypeApp

​

**Comment by miri64** [comment]
Sorry for not explaining the close :/, but what @PeterKietzmann is saying!

Am 21.10.2016 6:14 nachm. schrieb "Peter Kietzmann" <
notifications@github.com>:

**Comment by PeterKietzmann** [comment]
@alignan the guy I'm always reffering to is s-m-l-n-g (@smlng) :-)

**Pull request closed without merging**
