### PR TITLE
pkg/ccn-lite: drop unmaintained package

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Most of the recent commit history in the [upstream repo] is from RIOT maintainers upstreaming fixes to an otherwise dead project. The [website] of ccn-lite was [last online] at end of 2019 and has [been down] since at least at least February 2020 without anyone noticing.

By all means, this project is dead. If there ever were users, the long have moved on. Let's clean this up.

[upstream repo]: https://github.com/cn-uofbasel/ccn-lite
[website]: http://www.ccn-lite.net/
[last online]: http://web.archive.org/web/20191127125924/http://ccn-lite.net/
[been down]: http://web.archive.org/web/20200228025524/http://www.ccn-lite.net/

### Testing procedure

Green CI

### Issues/PRs references

None

### CODE REVIEW

**Comment by miri64** [comment]
Mh, could still be useful, and many RIOT-affiliated people have maintainer right in the CCN-lite repo. We were using it for ICN-related projects. What do @OlegHahm, @cgundogan and @PeterKietzmann think?

**Comment by OlegHahm** [comment]
I'm totally against dropping *all* ICN packages and since I have much more hands-on experience on this package (compared to ndn-riot) I would strongly vote to keep this package. What is the burden from the RIOT site to maintain this as a package?

**Comment by maribu** [comment]
Maybe we could vendor in the code then and maintain it as a module? Right now the bug fix process involves adding patches to RIOT, upstreaming the, updating RIOT again. This would make sense if there were upstream development. But since RIOT contributors are the only onces still maintaining ccn-lite, we could IMO cut the middle man and maintain it here directly.

**Comment by OlegHahm** [comment]
Fine with me.

**Comment by maribu** [comment]
But I guess that should be a new, distinct PR.

**Pull request closed without merging**
