### PR TITLE
pkg/lvgl: bump to 8.3.4

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

As the title says

### Testing procedure

Tested with success on native and stm32f429i-disc1

### Issues/PRs references

None

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
bors merge

**Comment by aabadie** [comment]
it seems that bors doesn't react to status check updates: if one write the magic bors command when not all checks are green, bors never triggers the full job.

bors merge

**Comment by aabadie** [comment]
ah no, for some reason some required github actions checks were missing (static-tests, tools-test and tools-buildtest)

**Comment by benpicco** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
