### PR TITLE
cpu/nrf5x/nrfmin: ignore empty iolist elements

### LINKED ISSUE #11163: netdev: iolist not checked for empty elements on send
#### Description
It is not possible to send an UDP packet with an empty payload via an `at86rf2xx`-shipping board (considering #11161 is merged), as an assertion in the device driver is hit. I was able to find the same problem in `cc2420` but did not check any more devices.

_**Edit: the discussion came to the conclusion that (3) should be implemented (see Tracking list)**_

I am raising this issue instead of fixing it, since I'm not sure where to fix it exactly, as I see three possible solutions. The assert (see "Actual results" section) itself is correct, so the deepest level to fix this would be to add a check for `len` in `at86rf2xx_sram_write()` (1).

https://github.com/RIOT-OS/RIOT/blob/b50ad9ed4cecf367f05e009f63b8fa5b5cc0b06e/drivers/at86rf2xx/at86rf2xx_internal.c#L71-L81

or ` at86rf2xx_tx_load()` (2) if we just want to solve this for sending specifically by checking there for `len` 

https://github.com/RIOT-OS/RIOT/blob/b50ad9ed4cecf367f05e009f63b8fa5b5cc0b06e/drivers/at86rf2xx/at86rf2xx.c#L158-L164

**However, one typically knows what they are doing when they are sending with the device driver directly, so maybe we rather want to fix the `netdev` interface handling of the device(s) by checking in this loop for `iol->iol_len == 0` (3).**

https://github.com/RIOT-OS/RIOT/blob/b50ad9ed4cecf367f05e009f63b8fa5b5cc0b06e/drivers/at86rf2xx/at86rf2xx_netdev.c#L102-L110

Lastly, we could just fix it in GNRC, which would be the least intrusive fix, as we only need to fix the `gnrc_pktsnip_t` to `iolist_t` conversion instead of checking all device drivers somewhere here (4)

https://github.com/RIOT-OS/RIOT/blob/b50ad9ed4cecf367f05e009f63b8fa5b5cc0b06e/sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c#L265-L290

(which would however remove the advantage of mapping the `gnrc_pktsnip_t` list directly to `iolist_t`).

#### Steps to reproduce the issue
~~Merge #11161 and~~ (was merged) try to send a UDP packet with empty payload using `gnrc_networking` on `samr21-xpro` (with other boards the actual result might differ):

```
udp send ff02::1 1337 ""
```

#### Expected results
The packet is sent and can be received by another radio (or sniffed with a sniffer).

#### Actual results
The node aborts on a failed assertion in this line

https://github.com/RIOT-OS/RIOT/blob/b50ad9ed4cecf367f05e009f63b8fa5b5cc0b06e/cpu/sam0_common/periph/spi.c#L162

#### Versions
Current master (4af354852b555de41cb55b7c820c30a6c29a5a55) with #11161 merged.

#### Tracking
To implement (3) and close this issue the following tasks need to be completed:

- [x] adapt and amend to [doc of `netdev_driver_t::_send`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/include/net/netdev.h#L300) #11195
- [x] fix the device drivers
   - [x] [`cc2538_rf`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/cc2538/radio/cc2538_rf_netdev.c#L274-L284) @kYc0o not affected https://github.com/RIOT-OS/RIOT/issues/11163#issuecomment-478632370
   - [x] [`esp32/esp-eth`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/esp32/esp-eth/esp_eth_netdev.c#L198-L205) @gschorcht #11186
   - [x] [`esp32/esp-wifi`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/esp32/esp-wifi/esp_wifi_netdev.c#L296-L303) @gschorcht #11184
   - [x] [`esp8266/esp-wifi`](https://github.com/RIOT-OS/RIOT/blob/master/cpu/esp8266/esp-wifi/esp_wifi_netdev.c#L421-L426); not affected as it copies the data byte-by-byte (@gschorcht)
   - [x] [`esp-now`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/esp_common/esp-now/esp_now_netdev.c#L649-L661) @gschorcht, also should check if `iol_base` is a NULL pointer [here](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/esp_common/esp-now/esp_now_netdev.c#L635-L640) #11187 
   - [x] `netdev_tap`; not affected since it is wrapping [`writev()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/writev.html)
   - [x] `socket_zep`; not affected since it is wrapping [`writev()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/writev.html)
   - [x] [`nrf802154`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/nrf52/radio/nrf802154/nrf802154.c#L265-L273) @bergzand #11176 
   - [x] [`nrfble`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/nrf5x_common/radio/nrfble/nrfble.c#L277); not affected, see https://github.com/RIOT-OS/RIOT/issues/11163#issuecomment-473216806
   - [x] [`nrfmin`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L330-L337) @haukepetersen -> ~~#11194~~ shown to be working without problems in current master
   - [x] [`at86rf2xx`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/at86rf2xx/at86rf2xx_netdev.c#L102-L110) @miri64 #11196 
   - [x] `cc110x`; not affected according to https://github.com/RIOT-OS/RIOT/issues/11163#issuecomment-472449069
   - [x] [`cc2420`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/cc2420/cc2420.c#L122-L137) @kYc0o https://github.com/RIOT-OS/RIOT/pull/11331
   - [x] [`enc28j60`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/enc28j60/enc28j60.c#L291-L294) @maribu https://github.com/RIOT-OS/RIOT/pull/11214
   - [x] [`encx24j600`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/encx24j600/encx24j600.c#L296-L299) @kaspar030, @maribu https://github.com/RIOT-OS/RIOT/pull/11325
   - [x] `ethos`; not affected as it copies the data byte-by-byte, using `iol_len` for the length check
   - [x] [`kw2xrf`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/kw2xrf/kw2xrf_netdev.c#L145-L153) @PeterKietzmann -> **NOT AFFECTED** https://github.com/RIOT-OS/RIOT/issues/11163#issuecomment-478569711
   - [x] [`mrf24j40`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/mrf24j40/mrf24j40_netdev.c#L73-L88) @bergzand -> #11321 
   - [x] `slipdev`; not affected as it copies the data byte-by-byte, using `iol_len` for the length check
   - [x] [`sx127x`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/sx127x/sx127x_netdev.c#L79-L81) @jia200x -> #11215
   - [x] [`w5100`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/w5100/w5100.c#L213-L217) @maribu; not affected, see https://github.com/RIOT-OS/RIOT/issues/11163#issuecomment-474748136 
   - [x] [`xbee`](https://github.com/RIOT-OS/RIOT/blob/4af354852b555de41cb55b7c820c30a6c29a5a55/drivers/xbee/xbee.c#L666-L668); (checksum calculation not affected) @kYc0o https://github.com/RIOT-OS/RIOT/pull/11332

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
fixes #11163 for the `nrfmin` radio driver

### Testing procedure
e.g. run `examples/gnrc_networking` enabling the `nrfmin` module (`USEMODULE=nrfmin`) on 2 Nordic boards. Sending empty UDP payloads should not lead to crashes.

### Issues/PRs references
#11163

### CODE REVIEW

**Comment by SemjonKerner** [comment]
I can send and receive packets with payload size of zero on master (gnrc_networking+udp).
However, with this PR I can still send packets with 0 payload, but I am not receiving these packets. Reception of packets with some payload still works. I think this is a step backwards.?

**Comment by haukepetersen** [comment]
it should be the other way around, ideed... Will have another look

**Comment by miri64** [comment]
This one is the only one remaining in #11163. I try to test this tomorrow. Or did you figure out what went wrong @SemjonKerner?

**Comment by SemjonKerner** [comment]
Please try it. I was not in office last week and will not come in before thursday, so I could not verify my findings. In the worst case I messed up with github and in the best case the master is already fit for #11163.

**Comment by miri64** [comment]
I can confirm @SemjonKerner's findings, that in master sending 0 bytes is possible, but with this PR it is not (I even checked the debug output in the driver; the packet does not arrive there). As to why this is: This PR is based on a version of master before #11161 was merged, which only allowed GNRC to handle payload length 0 packets in the first place (as pointed out in #11163). Considering that #11163 is not an issue for `nrfmin` in master, I rather close this PR as it adds unnecessary code.

**Pull request closed without merging**
