### PR TITLE
FIB: remove extraneous parentheses

### PR DESCRIPTION
**Pull request by Lotterleben**
Title says it all... Gets rid of an annoying warning. :)

### CODE REVIEW

**Comment by OlegHahm** [comment]
I like parentheses, but that's definitely too much. :smile: ACK

**Comment by BytesGalore** [comment]
should we wait for travis here?

**Comment by x3ro** [comment]
I'd say it's a bit overcautious to wait on Travis for this :shipit: :smile:

**Comment by BytesGalore** [comment]
yeah, and I think travis is in bad mood today

**Comment by BytesGalore** [comment]
obligatory: and go!

**Comment by Lotterleben** [comment]
:runner:

**Pull request merged**
