### PR TITLE
cpu/nrf5x_common: clean up UART implementation

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

The functions `uart_poweron()`, `uart_poweroff()` and  `uart_mode()` can share code between the UART (UART without EasyDMA) and UARTE (UART with EasyDMA) implementations, so let's do that.

### Testing procedure

UART should still work including switching modes - best checked with a logic analyzer attached to verify the output - for:

- [x] nRF5x with `UART` peripheral (UART without EasyDMA), so any nRF51*
- [x] nRF5x with `UARTE` peripheral (UART with EasyDMA) but no support for two stop bits, so e.g. nRF52832
- [x] nRF5x with `UARTE` peripheral (UART with EasyDMA) plus support for two stop bits, so e.g. nRF52840 / nRF53 / nRF9160 / ...

### Issues/PRs references

Follow up to / made possible by https://github.com/RIOT-OS/RIOT/pull/20102

### CODE REVIEW

**Comment by maribu** [comment]
Using `USEMODULE=stdio_rtt make BOARD=nrf52dk flash term` in `tests/periph/uart`:

### 115200 Bd, 8E1

image

### 115200 Bd, 8N1

image

### 9600 Bd, 8N1

image

**Comment by maribu** [comment]
Using `USEMODULE=stdio_rtt make BOARD=nrf51dk flash term` in `tests/periph/uart`:

### 9600 Bd, 8N1

image

### 115200 Bd, 8E1

image

### 115200 Bd, 8N1

image

**Comment by maribu** [comment]
Tested using `make BOARD=nrf52840dk flash term` in `tests/periph/uart`, connected the logic analyzer to the second UART (Arduino pins D0/D1):

### 9600 Bd, 8N1

image


### 115200 BD, 8E1

image


### 115200 Bd, 8E2

image

### 115200 Bd, 8N1

image

### 115200 Bd, 8N2

image

**Review by benpicco — APPROVED** [review]
Simple cleanup

**Comment by maribu** [comment]
Thx :-)

**Pull request merged**
