### PR TITLE
lostandfound: add x86 and qemu-i386

### PR DESCRIPTION
**Pull request by haukepetersen**
Documenting #8042

Waiting for #8042 to be merged so the correct commit hashes can be added.

### CODE REVIEW

**Comment by miri64** [comment]
#8042 was merged. Please update!

**Comment by kaspar030** [comment]
So we sort alphabetically by folder name now? Maybe by date is more useful?

**Comment by haukepetersen** [comment]
> So we sort alphabetically by folder name now? Maybe by date is more useful?

Yes, we do :-) And now don't tell me to open a separate PR for this thing...

IMHO alphabetically is way more usefuld -> in the end it is about finding information about a certain module (cpu, board). The order by date would be completely random. And if one wants to find out the order, you can always look at the commit history of this file...

**Comment by haukepetersen** [comment]
Updated the PR with the correct commit hashes and rebased.

**Pull request merged**
