### PR TITLE
doxygen/Makefile: summarize warnings, log full output to file. 

### PR DESCRIPTION
**Pull request by jcarrano**
### Contribution description

The latest versions of doxygen produce an unwieldy amount of warnings. Instead of ignoring them, this commit causes them to be saved to a log file in the common build directory and prints only a summary with a tally of the number of each type of warning found.

#### New logs directory

As a side effect of this change, I needed a place to place the logs. I defined BUILD_DIR/logs as that place.
Also, The definition of BUILD_DIR is moved to makefiles/buildout.inc.mk so that it can be reused by makefiles that do not include Makefile.include (such as the docs makefile).

### Testing procedure

Run `make doc` with a recent version of doxygen (I'm using 1.8.15) with and without this patch.

Without it, your screen will be flooded with warning messages. With the patch you get:

```
( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen - 2>&1 1>&2 | tee /home/jcarrano/source/masterRIOT/build/logs/doxygen.log | sed -nf warning_patterns.sed | sort | uniq -c
     20 Repeated label
  12824 Undocumented member
```

and the file `logs/doxygen.log` will get created containing the full logs.

```
$ wc -l build/logs/doxygen.log
12844 build/logs/doxygen.log
```

### Issues/PRs references

Trying to alleviate #10815 .

### CODE REVIEW

**Comment by jcarrano** [comment]
@gschorcht 

> One problem, however, was that doxygen did not work when I tried to use the `DOXYGEN` variable to define the path to my doxygen executable:

Oops, I screwed up! I didn't think about that usage. Let me fix it.

**Comment by kaspar030** [comment]
please make sure that parallel builds in the same directory don't collide.

**Comment by jcarrano** [comment]
> please make sure that parallel builds in the same directory don't collide.

You mean that the logs don't collide? The docs are built with `make docs` only, so I don't see why anyone would parallel-build the docs. However, if it is not desired to lose the previous logs, the log file could be versioned like `doxygenNNNN.log`, but I don't think the use cases for that justify the effort.

**Comment by jcarrano** [comment]
I rebased and squashed.

**Pull request closed without merging**
