### PR TITLE
gnrc_netif: make link-layer specific operations proper submodules

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This is a cleaner alternative to #10546 build-system-wise. Instead of making the inclusion of source files dependent on external modules, the link-layer specific implementations of `gnrc_netif` operations are moved to their own (sub-)modules and the combination (`gnrc_netif`, `netdev_x`) made dependent on `gnrc_netif_x`.

### Testing procedure
`make buildtest` (or Murdock ;-)) for `gnrc_networking` should pass.

### Issues/PRs references
Alternative to #10546.

### CODE REVIEW

**Comment by miri64** [comment]
Fixed some Murdock-reported errors and squashed directly.

**Comment by miri64** [comment]
Aaand murdock passes, so the testing procedures are at least working on Murdock :-)

**Comment by kaspar030** [comment]
Hm, I was aiming for SUBMODULES=1. :)

Does it make sense to have a reverse dependency (```if gnrc_netif_% USEMODULE+=gnrc_netif```)?

**Comment by miri64** [comment]
> Hm, I was aiming for SUBMODULES=1. :)

I was thinking about using it, but as the rest of GNRC uses directory-submoduling I thought it would become inconsistent (also I don't like amending to `pseudomodules.mk` these days unless absolutely necessary, but I'm aware that the directory-submoduling way also has its downsides).

> Does it make sense to have a reverse dependency (`if gnrc_netif_% USEMODULE+=gnrc_netif`)?

I'm not sure, but my gut-feeling says no. Here some reasons: The user wants to pick `gnrc` as a module (usually e.g. via `gnrc_<protocol>` which in turn has `gnrc` as a dependency) and it *always* requires among other things `gnrc_netif` to communicate with a network device. Your proposal would basically require (through some indirection in dependencies) the network device to check if `gnrc` is there and then include the `gnrc_netif_x` dependency (which in turn then includes `gnrc_netif`). At this point we are talking about semantics, but I think its cleaner, if GNRC pulls in the dependencies it needs to communicate with a device and not the other way around.

**Comment by kaspar030** [comment]
> I was thinking about using it, but as the rest of GNRC uses directory-submoduling I thought it would become inconsistent

ok

> (also I don't like amending to `pseudomodules.mk` these days unless absolutely necessary, but I'm aware that the directory-submoduling way also has its downsides).

That seems to be the most confusing / inconvenient thing regarding submodules. :( I wonder if that can be worked around somehow.

> I think its cleaner, if GNRC pulls in the dependencies it needs to communicate with a device and not the other way around.

ok

**Comment by miri64** [comment]
Thanks for the review :-)

**Pull request merged**
