### PR TITLE
boards/cpu: removed support for weio and lpc11u34

### PR DESCRIPTION
**Pull request by haukepetersen**
The `weio` and its `lpc11u34` CPU are not maintained anymore and there is no hardware for testing available to the community. After offline communication, @ks156 agreed to removing this board for now.

But just removing these files would be a shame after all the work that was put into it. So additionally to just removing the code I propose that we open a dedicated Wiki page, on which we list the features that were removed, together with the last commit where the feature was still available (-> we could call it the RIOT graveyard). This way, features can easily be put back into master if a new maintainer is found. What do you say?

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased

**Comment by haukepetersen** [comment]
lets wait with merging for a moment, I'd like to figure out where to document the removed feature(s) first. Just had an offline discussion with @kaspar030 and we came to the conclusion that some kind of doc file in the RIOT tree instead a wiki page would be a good idea. Will look into this.

**Comment by gebart** [comment]
maybe just a Makefile inside the cpu and board directories of the removed platforms which give a URL to this PR if you try to use them?

**Comment by haukepetersen** [comment]
I think that would lead to potentially many 'empty' folders. I prefer a central (markdown or similar) file, which documents the removed features, including a reason for removal, and gives the last commit in which the feature was still available.

**Comment by haukepetersen** [comment]
This way, people still find this information with a simple `get grep`

**Comment by haukepetersen** [comment]
Added my idea for documenting removed feature in #7520. The reason for a separate PR is that the commit hashes of the two removal commits in this PR can still change (e.g. by rebasing)...

**Pull request merged**
