### PR TITLE
boards/msbiot: on-board buttons and saul integration

### PR DESCRIPTION
**Pull request by maribu**
This PR adds:
 - support for the on-board buttons
- SAUL integration of on-board buttons and on-board LEDs
- Added the MPU-9150 as default saul device (driver is loaded when module `saul_default` is used)

### CODE REVIEW

**Comment by aabadie** [comment]
To avoid confusion, I updated this PR's title since only it's only related to msbiot board

**Comment by maribu** [comment]
Should I update the commit titles in the same way?

**Comment by maribu** [comment]
I just also added saul integration of the on-board MPU-9150 to this PR, as this commit fits nicely into this PR

**Comment by aabadie** [comment]
> Should I update the commit titles in the same way?

yes, they should start with `boards/msbiot: ...`

**Comment by maribu** [comment]
Done :-)

**Pull request merged**
