### PR TITLE
at: add at command parser with basic test app (based on #7084)

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

This is #7084 with a very basic test app to be able to build the module from CI.

### Issues/PRs references

Based on #7084

### CODE REVIEW

**Comment by kaspar030** [comment]
would you mind just pull requesting the test app there?

**Comment by vincent-d** [comment]
> would you mind just pull requesting the test app there?

Sure. I can also create PR against your branch if you prefer.

**Comment by kaspar030** [comment]
> Sure. I can also create PR against your branch if you prefer.

I can just cherry-pick the commit.

**Comment by vincent-d** [comment]
> I can just cherry-pick the commit

Go ahead ;)

**Comment by kaspar030** [comment]
Did. Thanks!

**Pull request closed without merging**
