### PR TITLE
boards: common: stdio_cdc_acm: let tests wait a bit for serial port

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Some tests may fail spuriously with `stdio_cdc_acm`, since the `tty` might not exist yet. This configures a small delay after resetting for `testutils` and also piggybacks the honoring of that delay for the `riotctrl`-based tests.

### Testing procedure
CI should pass all tests. Maybe we should also run `tests-on-iotlab` for this PR.

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
> Maybe we should also run `tests-on-iotlab` for this PR.

See https://github.com/RIOT-OS/RIOT/actions/runs/3892598987. The one to look for is `nrf52840dk`.

**Review by maribu — APPROVED** [review]
bors merge

**Comment by miri64** [comment]
The ESP issues seem unrelated but they show up :-/.

**Comment by miri64** [comment]
https://ci.riot-os.org/?sha=cc83f446fdf6a4bc8e6ab710447ec090c7f5dd9b

**Comment by miri64** [comment]
Deactivated tests for now. The tests this touches worked and the failing tests fail in [master as well](https://ci.riot-os.org/details/37c12a945b904270a9d401c891a8a9e2/tests).

**Comment by aabadie** [comment]
bors merge

**Comment by miri64** [comment]
bors retry

**Comment by miri64** [comment]
bors merge

**Comment by maribu** [comment]
bors retry

**Pull request merged**
