### PR TITLE
tests/driver_at86rf2xx: blacklist stk3200

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description
This board does no longer fit the test application after the latest toolchain update.

### CODE REVIEW

**Comment by benpicco** [comment]
On second thoughts, this will not be enough.
CI now aborts on first failure, so this will likely not be the only instance where the new toolchain pushes some apps across the limit :(

**Comment by benpicco** [comment]
bors try

**Comment by benpicco** [comment]
bors try

**Comment by benpicco** [comment]
bors retry

**Comment by benpicco** [comment]
bors retry

**Comment by benpicco** [comment]
bors retry

**Comment by benpicco** [comment]
bors you lie

**Comment by benpicco** [comment]
bors abort

**Comment by benpicco** [comment]
bors cancel

**Comment by benpicco** [comment]
bors retry

**Comment by benpicco** [comment]
bors ping

**Comment by benpicco** [comment]
bors try

**Comment by benpicco** [comment]
bors retry

**Comment by maribu** [comment]
bors merge

**Review by aabadie — CHANGES_REQUESTED** [review]
NACK, this PR is no longer needed.

**Pull request closed without merging**
