### PR TITLE
tests: fix python style 'E302 expected 2 blank lines, found 1'

### PR DESCRIPTION
**Pull request by aabadie**
Partially addresses #8141.

Fixes E302 issue `expected 2 blank lines, found 1`.

### CODE REVIEW

**Comment by miri64** [comment]
Needs rebase

**Comment by aabadie** [comment]
rebased

**Comment by miri64** [comment]
Needs rebase though.

**Comment by smlng** [comment]
and rebase again 😉

**Comment by aabadie** [comment]
rebased

**Pull request merged**
