### PR TITLE
cpu/stm32: remove CLOCK_LSE define, use CONFIG_BOARD_HAS_LSE instead

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

CLOCK_LSE was kept for backward compatibility with a direct mapping with `CONFIG_BOARD_HAS_LSE` until all STM32 clock configurations were on the same line. Now that is the case, so this PR removes the `CLOCK_LSE` define and directly use the `CONFIG_BOARD_HAS_LSE` instead.

### Testing procedure

- A green Murdock
- I ran a few test with RTT and RTC (only affected peripherals) and found no issue

### Issues/PRs references

Tick an item in #14975

### CODE REVIEW

**Comment by fjmolinas** [comment]
I still find 2 occurrences of `CLOCK_LSE`:

```
cpu/stm32/dist/clk_conf/clk_conf.c:           "#define CLOCK_LSE           (%uU)\n", is_lse);
cpu/stm32/doc.txt: *  - CLOCK_LSE: 0 if LSI must be used as low speed clock, 1 otherwise
```

**Comment by fjmolinas** [comment]
Did a quick test all seems good, please squash once removing the repeated occurrences of `CLOCK_LSE`

**Comment by aabadie** [comment]
> I still find 2 occurrences of CLOCK_LSE:

Those 2 files are completely outdated. There are items in #14975 to take care of them: adapt doc.txt and maybe remove `clk_conf` (or rewrite it to only report the PLL values for a desired sysclk).

**Comment by fjmolinas** [comment]
> > I still find 2 occurrences of CLOCK_LSE:
> 
> Those 2 files are completely outdated. There are items in #14975 to take care of them: adapt doc.txt and maybe remove `clk_conf` (or rewrite it to only report the PLL values for a desired sysclk).

Ok if its on the todo list then.

**Review by fjmolinas — APPROVED** [review]
ACK!

**Pull request merged**
