### PR TITLE
examples/nimble_scanner: fix typo in README

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR fixes an obvious typo in the `examples/nimble_scanner` application README.

### Testing procedure

Just compare the README with the [puts code](https://github.com/RIOT-OS/RIOT/blob/master/examples/nimble_scanner/main.c#L52) of the application.

### Issues/PRs references

Found while looking at #11372

### CODE REVIEW

**Comment by miri64** [comment]
For reference: Found the typo in the code, but not in the README m): https://github.com/RIOT-OS/RIOT/pull/11281#discussion_r269664355

**Comment by miri64** [comment]
?

**Comment by aabadie** [comment]
Ah, I thought it was already merged, sorry :)

**Comment by aabadie** [comment]
Will reopen

**Comment by aabadie** [comment]
Ah, I could finally reopen the initial one. Sorry for the noise ;)

**Pull request merged**
