### PR TITLE
periph/i2c: added means to make I2C thread-safe

### PR DESCRIPTION
**Pull request by thomaseichinger**
As discussed in #2289 this changes provide means to use the i2c interface safely within multiple threads. Missing implementations will be provided as the concept is accepted. Implementation is analog to #2290.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
ACK

**Comment by PeterKietzmann** [comment]
@thomaseichinger did you link this PR in issue #2314? If so, do you want to change all other i2c implementations in here? I could also adapt some, just want to avoid that our work collides

**Comment by thomaseichinger** [comment]
@PeterKietzmann I did, updated adopting all other existing i2c implementations.

**Comment by PeterKietzmann** [comment]
Ah haven't seen this. Ok I'll go through the commits

**Comment by thomaseichinger** [comment]
@PeterKietzmann As the proposed concept doesn't break the current usage of the interface I decided to adopt i2c's uses separately. Would you mind taking over this task?

**Comment by PeterKietzmann** [comment]
@thomaseichinger. ACK for this PR. I could adapt the uses. Thanks for the list in #2314. I'll register my name to some , just to avoid collisions if someone else hops in. If not, i'll adapt all within the next days

**Comment by PeterKietzmann** [comment]
Everything is fine. ACK

**Pull request merged**
