### PR TITLE
shell: add support for (un-)setting 6LoWPAN support on an interface

### PR DESCRIPTION
**Pull request by authmillenon**
~~Depends on #2614 and #2778 (and all their dependencies).~~ (merged)

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current dependencies

**Comment by authmillenon** [comment]
Rebased to current dependencies

**Comment by authmillenon** [comment]
Rebased to current master and #2614 and squashed

**Comment by authmillenon** [comment]
Rebased to current #2614.

**Comment by authmillenon** [comment]
Found some errors and squashed already.

**Comment by haukepetersen** [comment]
ACK when dependencies are merged and this PR is rebased.

**Comment by authmillenon** [comment]
Dependency are merged => rebased to current master and waiting for travis.

**Comment by haukepetersen** [comment]
ACK

**Pull request merged**
