### PR TITLE
oonf_api: adjust Makefile

### PR DESCRIPTION
**Pull request by cgundogan**
This PR refactors the Makefile of the `oonf_api` `pkg` to look more like the other `pkg`'s Makefiles

### CODE REVIEW

**Comment by OlegHahm** [comment]
The changes look sound. @Lotterleben, @mfrey, can you check if this breaks anything for you?

**Comment by Lotterleben** [comment]
My AODVv2 update is still broken, so unfortunately not... @mfrey , what about you? :)

**Comment by mfrey** [comment]
I'll still have to check. However, I'm quite busy with other things right now :-( If you don't mind I would get back to you next Monday/Tuesday?

**Comment by cgundogan** [comment]
Rebased to current master and kicked travis. At least now we are be able to verify if it still builds since we have a ndhp buildtest

**Comment by cgundogan** [comment]
Again, rebased to current master to see if oonf still builds with these changes to the Makefile. Seems good so far. @mfrey @Lotterleben care to ACK?

**Comment by mfrey** [comment]
@cgundogan works for me! thanks!

**Comment by cgundogan** [comment]
@mfrey thanks for the review. Travis is also happy -> GO

**Pull request merged**
