### PR TITLE
cpu/saml1x: set wait state according to datasheet

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description
According to datasheet, SAML1X should be set in PL2 with 1 WaitState if it runs at 16MHz (which is currently the default speed supported).
See Chap 46.12 from the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAM-L10-L11-Family-Data-Sheet-DS60001513C.pdf)

### Testing procedure
run any tests you want on SAML10-XPRO or SAML11-XPRO

### Issues/PRs references
@emmanuelsearch could you check that your PR works with this one ?

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
#11248

**Comment by emmanuelsearch** [comment]
tried tests/riotboot with this and #11248 on SAML11-xpro. It does not get through the jump from the bootloader into the image (tried LED debugging, could not trace it precisely, but it seems it does not make it to kernel_init)

**Comment by dylad** [comment]
@emmanuelsearch Should be better now. 
I forced-push to squash at the same time.

**Comment by emmanuelsearch** [comment]
with this, riotboot support (with #11248) works like a charm on saml11xpro!

**Comment by dylad** [comment]
@emmanuelsearch Care to ACK ?

**Pull request merged**
