### PR TITLE
make: include RIOT_VERSION in CFLAGS for riotbuild

### LINKED ISSUE #5695: make: RIOT_VERSION not updated if core/kernel_init.c unchanged
So if you switch branches and rebuild, `RIOT_VERSION` will still have the old branch name in it unless `core/kernel_init.c` gets rebuilt.

This should be solvable with a `.FORCE` directive in a Makefile somewhere, but since I'm unsure exactly where that should be I'm opening an issue instead of a PR :)

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
fixes #5695

### CODE REVIEW

**Comment by gebart** [comment]
Possible side effect: `make` after a git commit will also rebuild everything.
I don't think that's too unexpected though.

**Comment by LudwigKnuepfer** [comment]
@gebart is that an ACK?

**Comment by OlegHahm** [comment]
Would't this indeed lead to a huge number of unnecessary rebuilds?

**Comment by LudwigKnuepfer** [comment]
There are a lot of rebuilds if there is a lot of committing / branch changing going on..

**Comment by OlegHahm** [comment]
Apparently, I miss something. What is "riotbuild"?

**Comment by LudwigKnuepfer** [comment]
https://github.com/RIOT-OS/RIOT/pull/5097/files#diff-7766447651641d0ba0a9b6b723841f50

**Comment by gebart** [comment]
@OlegHahm #5097 introduced a script that generates a header file named `riotbuild.h`

**Comment by kaspar030** [comment]
+1

-----Original Message-----

**Comment by gebart** [comment]
ACK for the change from my side. What is your opinion on the increased number of rebuilt files @OlegHahm?
I take @kaspar030's +1 as agreeing with the idea.

**Comment by miri64** [comment]
@OlegHahm?

**Comment by OlegHahm** [comment]
I have the impression that I got something wrong, but I thought that this change would cause a complete rebuild for any new commit, causing the CI to be unbearable slow again. Can anyone enlighten me?

**Comment by LudwigKnuepfer** [comment]
@OlegHahm I didn't check what `RIOT_VERSION` is set to in the CI, but if it contains a different string on each build, rebuilding is the reasonable thing to do.

**Comment by kaspar030** [comment]
> I thought that this change would cause a complete rebuild for any new commit, causing the CI to be unbearable slow again.

CI builds with ```RIOT_VERSION_OVERRIDE=buildtest```, and it doesn't rely on make for deciding what to build anyways, e.g., it uses a fresh checkout for every build.

**Comment by OlegHahm** [comment]
@kaspar030: ah, okay, thanks for the clarification. In this case, I don't see a major problem with this PR.

**Pull request merged**
