### PR TITLE
[WIP] RFC5444/MANET transport layer

### PR DESCRIPTION
**Pull request by jeandudey**
### Contribution description

This implements a new transport-layer module for MANET networks using RFC 54444 packets.

*Be warned most of the code could be wrong, this is still on an experimentation phase and most of the code is subject to change. Any recommendation or improvement is well received*.

**Why don't use OONF?**

OONF is a quite complete library to work with RFC 5444, however, it's quite heavy for micro controllers, uses too much memory which is quite scarce these days and is not actively developed. Making it work with RIOT before was difficult, even running tests on CI for example.

**Does it require explicitly GNRC?**

I had a conversation with myself a lot whether to use the `sock_ip`/`sock_udp` modules to make it more portable, e.g.: without requiring a dependency on GNRC, lwIP or anything, as long as sock has an implementation on whatever system it is ported to, however I had a few questions:

- Sock IP/Sock UDP could be used at the same time? RFC 5444 can receive IP datagrams directly by using the `PROTNUM_MANET` next header or UDP datagrams on it's port, it doesn't _explicitly_ require to listen using both methods, however listening for IP and UDP at the same time can be achieved easily with `gnrc_netreg`, with `sock` I'm still unsure about this.
- Packet handling, using `gnrc_pktbuf` makes it easy to handle packets and generally fits well the structure of RFC 5444 messages.
- Along with the last point, `gnrc_netreg` makes the demultiplexing of RFC 5444 messages easier, threads can just register interest for specific messages and `gnrc_manet` will dispatch them using `gnrc_netreg`.

**And for what?**

My interest personally on RFC 5444 mainly is for implementing AODVv2 on the near future completely using RIOT modules, without depending too much on external code. AODVv2 is still a draft, probably it's standardization is not going to happen soon mainly due to lacking implementations to identify edge cases, errors, to test it's performance.

Previous attempts were made (#1767) to implement it, based on that code I did some experiments by updating the code to the new RIOT APIs, etc, and the principal pain point was OONF where in some cases it would eat all the heap space :smile: .

I know that introducing this code into RIOT introduces a maintenance backlog in some cases, for CI, testing, et all and that probably most people wouldn't use it as routing protocols like RPL are more suited for IoT applications, are easier to work with and significantly more stable for what the future holds. Use cases would be devices that are carried anywhere, autonomous devices that are changing their topology at any time,  VoIP applications maybe? However RPL should still work fine for most these cases if I'm not mistaken.

### Testing procedure

Compilation test:

```
make -C tests/gnrc_manet
```

Small to-do list on testing:

- [ ] Unit tests for packet, message and TLV parsing.
- [ ] Integration test, on packet reception, and message sending.
- [ ] Example protocol (maybe NHDP as it's small enough) test.
- [ ] Compatibility test to verify interop with other libraries, only OONF as far I know.
- [ ] Fuzzing as a good thing to have, to catch any unwanted crash, error, or vulnerability.

### CODE REVIEW

**Comment by jeandudey** [comment]
Wooow, wrong place (and time) for PR :sweat: . I'll keep it open though to see if anyone has any interest on it. :smile:

Will update the PR description, testing, etc.

**Comment by aabadie** [comment]
> I'll keep it open though to see if anyone has any interest on it

Maybe @adjih :)

**Comment by miri64** [comment]
The alternative could be to [resurrect `pkg/oonf_api`](https://github.com/RIOT-OS/RIOT/blob/master/LOSTANDFOUND.md#pkgoonf_api-c829f820ee870bffc60c7df688d2da8373553212)

**Comment by fjmolinas** [comment]
> Wooow, wrong place (and time) for PR sweat . I'll keep it open though to see if anyone has any interest on it. smile

Why wrong place?

**Comment by jeandudey** [comment]
> > Wooow, wrong place (and time) for PR sweat . I'll keep it open though to see if anyone has any interest on it. smile
> 
> Why wrong place?

It was for the fork repo for an on-going diff of the changes, and didn't notice it was RIOT the target repo. Of course, when it had a good shape my intention was to open a PR here

**Comment by luisan00** [comment]
Work in progress, it need some love, are crazy  times but the development is continuing. Any suggestions would be welcome 💪

**Comment by jeandudey** [comment]
Will close the PR, once I get back to this I'll reopen it.

**Pull request closed without merging**
