### PR TITLE
.murdock: disable hash checks of kconfig/make

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
Much CI time is wasted as unrelated hash failure occur.
Finding out why is taking some time.
In order to stop killing dolphins we will disable only the hash checks.
There is a risk of introducing new issues with the kconfig/make
dependency resolution.
However, the package/module checks are still enforced which should catch
95% of the problems.
The nightlies will continue to check as well.

### Testing procedure

Check the murdock output?  It is pretty hard to test CI changes.

### Issues/PRs references

A little less destructive than #18399

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
Looks like you caught a difference in the module list that was not impacting the binary hash

**Comment by MrKevinWeiss** [comment]
I imagine there are a few of these.

**Comment by MrKevinWeiss** [comment]
It seems the failures are caused by `periph_gpio_ll_irq_unmask` included in every make build.  The seems a bit wrong so I adapted the make to only bring it in when the `periph_gpio_ll`.  I would expect that kconfig will still have some issues with some apps but I guess we will see.

Introduced in #16787, ping @maribu if you want to confirm my off-the-cuff logic.

**Comment by leandrolanzieri** [comment]
> It seems the failures are caused by `periph_gpio_ll_irq_unmask` included in every make build. The seems a bit wrong so I adapted the make to only bring it in when the `periph_gpio_ll`. I would expect that kconfig will still have some issues with some apps but I guess we will see.
> 
> Introduced in #16787, ping @maribu if you want to confirm my off-the-cuff logic.

I think this may be more complicated, as the `periph_gpio_ll` and related modules were not modelled in Kconfig when introduced in #16787

**Comment by MrKevinWeiss** [comment]
Darn another day gone... if only #17688 got in.

**Comment by MrKevinWeiss** [comment]
It looks like Murdock is happy, all problems seems to be fixed (maybe not the best way but better than being broken).

Ping @maribu @benpicco @leandrolanzieri @jia200x 

I would like to squash, the sooner this is in the faster we can get through the murdock stuff (and start debugging the hash mismatch problem).

**Comment by MrKevinWeiss** [comment]
Though looking at the CI time, this doesn't really make that big a difference.  It would at least prevent the hash mismatch errors.

**Comment by leandrolanzieri** [comment]
Thanks for tackling this @MrKevinWeiss !! I took a look and changes seem reasonable. Please go ahead and squash!

**Review by leandrolanzieri — APPROVED** [review]

**Comment by MrKevinWeiss** [comment]
Thank you for the review

**Pull request merged**
