### PR TITLE
tests/turo_txt: Basic test for txt turo variant

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Adds a test for the txt output of turo.  As it is only meant to be human readable, we don't need to confirm the contents (ie, regex everything) with automated tests.  Instead we just confirm the return codes and parsing works and no asserts are hit.

### Testing procedure

Murdock green should be all.

### Issues/PRs references

Follow-up of #17036 to prevent regressions

### CODE REVIEW

**Review by miri64 — DISMISSED** [review]

**Comment by MrKevinWeiss** [comment]
@miri64 can we go with this direction for now? This adds a test that should catch any asserts and only check the exit codes of each command.  I don't want to actually parse the text to verify as this should be somewhat unstructured.

**Comment by miri64** [comment]
> @miri64 can we go with this direction for now? This adds a test that should catch any asserts and only check the exit codes of each command. I don't want to actually parse the text to verify as this should be somewhat unstructured.

Maybe align the PR's title to its content now ;-). What about the other flavors of `turo`?

**Comment by MrKevinWeiss** [comment]
True :)

**Comment by MrKevinWeiss** [comment]
Done

**Comment by MrKevinWeiss** [comment]
> What about the other flavors of turo?

The default `tests/turo` check json and the `check` version is tested in the unittests (only enforces structure of the calls).

**Comment by miri64** [comment]
Then let's give those a spin on Murdock :-).

**Comment by MrKevinWeiss** [comment]
Nightlies have been failing due to hardware tests.  I think the python version needs to be updated or something.  I am rerunning without the hardware as this shouldn't really have an effect (also the failing tests were unrelated).

**Comment by miri64** [comment]
> Nightlies have been failing due to hardware tests. I think the python version needs to be updated or something. I am rerunning without the hardware as this shouldn't really have an effect (also the failing tests were unrelated).

Do you have a link of the tests in the CI? Would have liked to see the results.

**Comment by miri64** [comment]
In tonight's nightlies I only saw

```
    failed:
    tests/pkg_edhoc_c/esp32-wroom-32:gnu
    tests/thread_float/esp32-wroom-32:gnu
    tests/thread_float/samr21-xpro:gnu
    tests/pthread_barrier/esp32-wroom-32:gnu
    tests/pthread_barrier/samr21-xpro:gnu
```

so the turo tests should succeed.

**Comment by MrKevinWeiss** [comment]
ping

**Comment by fjmolinas** [comment]
All green here @miri64!

**Review by fjmolinas — APPROVED** [review]
ACK, nice to have a test for this

**Comment by MrKevinWeiss** [comment]
Thanks!

**Pull request merged**
