### PR TITLE
drivers: add support for LPD8808 based LED stripes

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by miri64** [comment]
Not sure if this makes sense or is possible (code certainly looks like it), but as a user I might want to have a way to set the color of individual LEDs, not just in array.

**Comment by haukepetersen** [comment]
My aim was to keep the driver as simple as possible... IMHO the way it is now is the most flexible but still easy to use variant (just look at the example/test code).

**Comment by miri64** [comment]
But does it scale with the `for`-loop?

**Comment by haukepetersen** [comment]
there is no way around the for loop: remember, its a shift register -> you can not simply address and write any LED on it's own. To address a single LED, you have to shift out the data for all LEDs on the strip.

Now having the data array outside of the driver is the most efficient solution: you edit the values you want to change directly on the array and then push the data on the strip. If you would have a function like `write_led(position, value)`, which would be possible when buffering driver internal, you would either need to push the changes to the strip for each single change, or you would need something like an `update()` function on top of it -> so more function calls and more ROM usage for the same thing...

**Comment by miri64** [comment]
See, that was what I meant with 

> Not sure if this makes sense or is possible 

;-) I did assume it is possible to address a single LED.

**Comment by PeterKietzmann** [comment]
Simon! Will you be assignee ;-)?

**Comment by brummer-simon** [comment]
Just out of curiosity and without knowledge of the chip in use: 
Why are you setting the msb of every color before putting it onto the led stripe ? 

 for (int i = 0; i < dev->led_cnt; i++) {
        put_byte(dev, ((vals[i].g >> 1) | 0x80));
        put_byte(dev, ((vals[i].r >> 1) | 0x80));
        put_byte(dev, ((vals[i].b >> 1) | 0x80));
 }

**Comment by haukepetersen** [comment]
@brummer-simon: the chip on the strip only supports 128-bit color values and expects the MSB to be `1`, so I simply take away the LSB of the original color value

**Comment by miri64** [comment]
Let's try to merge this for the release!

**Comment by haukepetersen** [comment]
Definitely! I would suggest we target this PR for the upcoming Hack'n'ack.

**Comment by haukepetersen** [comment]
rebased

**Comment by cgundogan** [comment]
Murdock is happy => GO

**Pull request merged**
