### PR TITLE
shell: fix condition for ping command

### PR DESCRIPTION
**Pull request by OlegHahm**
No idea how this sneaked in.

### CODE REVIEW

**Comment by authmillenon** [comment]
Well, without xtimer the ping command isn't working so why would you want to remove it?

**Comment by OlegHahm** [comment]
Because this doesn't model the dependency for ping, but builds ping if either icmpv6_echo *or* xtimer are used.

**Comment by authmillenon** [comment]
Then we should make that an *and*, not remove it altogether ;-)

**Comment by OlegHahm** [comment]
ICMPv6 already pulls in xtimer in Makefile.dep.

**Comment by cgundogan** [comment]
wouldn't the dependency to `xtimer` go rather in [here](https://github.com/RIOT-OS/RIOT/blob/master/Makefile.dep#L205) instead? This way we can have it like @OlegHahm proposed, because it wouldn't build without xtimer.

**Comment by cgundogan** [comment]
>ICMPv6 already pulls in xtimer in Makefile.dep.

In a really ugly way IMO. It's actually pulled in by `gnrc_ipv6_netif`. So I'd vote to also include it for `gnrc_icmpv6_echo` explicitely.

**Comment by OlegHahm** [comment]
Well, icmpv6_echo itself doesn't require xtimer, only the shell command, but since ipv6 requires xtimer and icmpv6_echo requires ipv6 we have this case covered anyway. (Yes, one might argue that this will break as soon as the dependency of ipv6 to xtimer would be removed, but I would consider this as rather theoretical.)

**Comment by authmillenon** [comment]
> wouldn't the dependency to xtimer go rather in here instead? This way we can have it like @OlegHahm proposed, because it wouldn't build without xtimer.

You don't need timers for ICMPv6 echo request/reply. Just the ping application since it stops the times. There is a difference between echo and ping!

**Comment by authmillenon** [comment]
> ICMPv6 already pulls in xtimer in Makefile.dep.

Why?

**Comment by authmillenon** [comment]
> Well, icmpv6_echo itself doesn't require xtimer, only the shell command, but since ipv6 requires xtimer and icmpv6_echo requires ipv6 we have this case covered anyway. (Yes, one might argue that this will break as soon as the dependency of ipv6 to xtimer would be removed, but I would consider this as rather theoretical.)

Why does IPv6 require xtimer?

**Comment by OlegHahm** [comment]
Because it requires gnrc_ipv6_netif.

**Comment by cgundogan** [comment]
and `xtimer` is also used in `gnrc_ipv6_nc`

**Comment by cgundogan** [comment]
>You don't need timers for ICMPv6 echo request/reply. Just the ping application since it stops the times. There is a difference between echo and ping!

Yep, you're right I overlooked that

**Comment by authmillenon** [comment]
Okay, yes in theory IPv6 should be independent of `gnrc_ipv6_netif` and `gnrc_ipv6_nc`, but let's face it that use-case is rarely the a case you want to have. So ACK for the change (maybe add a comment?)

**Comment by OlegHahm** [comment]
I think the cleanest solution actually would be to model the dependency for shell commands somewhere else (in the current state of our dependency modelling in some Makefile.dep).

**Comment by OlegHahm** [comment]
added a comment

**Comment by authmillenon** [comment]
please squash.

**Comment by OlegHahm** [comment]
squashed

**Pull request merged**
