### PR TITLE
ble/nimble: bump version to 9d4bda2

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
The current NimBLE version used has an issue when receiving large data packets via L2CAP COC. This was fixed upstream (https://github.com/apache/mynewt-nimble/pull/378). So this PR updates NimBLE to include those fixe(es).

### Testing procedure
Once #11235 is merged, use that test application to verify that sending/receiving large data packets at a high rate is working properly.

### Issues/PRs references
fixes https://github.com/apache/mynewt-nimble/issues/373
depends on #11235 (for proper testing)

### CODE REVIEW

**Comment by haukepetersen** [comment]
I'd like to put this PR on hold until https://github.com/apache/mynewt-nimble/pull/392 is also merged into NimBLE. This way we save one version bump PR...

**Comment by haukepetersen** [comment]
apache/mynewt-nimble#392 was merged, so I updated the NimBLE version in this PR once more. The PR is now ready to be tested and merged.

**Comment by haukepetersen** [comment]
Turns out that NimBLE appears to have new issues since https://github.com/apache/mynewt-nimble/pull/414. When running out `tests/nimble_l2cap` application, the send fails using this new event. Still looking into the cause...

**Comment by SemjonKerner** [comment]
I still have failed assertion with packagelength > 2518 on client.
`tests/nimble_l2cap/main.c:205 => 0xce9`, MTU is 250 now.

Also when flooding the client does not print to pyterm after 23 packets - but it recovers after resetting the server. Did not debug this further.

**Comment by haukepetersen** [comment]
Yes, thats exactly the faulty behavior. The problem ist, that somehow the internal send buffers are not processed properly, so that the `BLE_L2CAP_EVENT_COC_TX_UNSTALLED` event is triggered in an eternal loop, letting the node to constantly send the same packet over and over...

**Comment by haukepetersen** [comment]
Alright, found the issue: the application code around the send function was flawed.

Updated this PR: 
- bumped Nimble version once more: 9d4bda2edcf0e7c2a03aa908321293a53361d258
- fixed the `test/nimble_l2cap` test applications to make now proper use of the new `BLE_L2CAP_EVENT_COC_TX_UNSTALLED` event

This PR should be ready for final review now.

**Comment by SemjonKerner** [comment]
Great, `flood` and `inctest` from `/tests/nimble_l2cap` to `/tests/nimble_l2cap_server` go through now.
Anything else I should test?

**Comment by haukepetersen** [comment]
you could just try the `examples/nimble_gatt` example and connect with a phone or similar. But there weren't any significant changes in that code path of nimble...

**Comment by haukepetersen** [comment]
Awesome, thanks a lot!

**Pull request merged**
