### PR TITLE
drivers/ft5x06: fix initialization if callback function parameter is NULL

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the `ft5x06` driver initialization if the callback function parameter `cb` is `NULL. This might be the case for example if the application uses the touch device in polling mode.

If the interrupt pin is initialized if the callback function parameter `cb` is `NULL`, the driver crashes the first time an interrupt is triggered. Therefore, the INT pin must be initialized only if also the callback function parameter `cb` is not `NULL`.

To be able to test the polling mode, this PR also includes a change of the `tests/drivers/ft5x06` application which introduces the environment variables `FT5X06_POLLING_MODE` `FT5X06_POLLING_PERIOD` and in the makefile.

### Testing procedure

1. Use any board with a FTXXXX touch device and test it in polling mode, for example:
   ```
   FT5X06_POLLING_MODE=1 BOARD=stm32f746g-disco make -C tests/drivers/ft5x06 flash term
   ```
   It should work as expected.
   ```
   main(): This is RIOT! (Version: 2023.10-devel-119-g92a44a-drivers/ft5x06_fix_cb_null)
   FT5x06 test application
   +------------Initializing------------+
   Initialization successful
   1 touch detected
   Touch 1 - X: 236, Y:111
   Touch 1 - X: 236, Y:111
   ...
   Touch 1 - X: 236, Y:111
   Released!
   ```

2. Checkout master branch and cerry-pick commit 691a5e6308426ddc685e5a2c297238529211c258. The test application `tests/drivers/ft5x06` will crash once a touch event occur:
   ```
   +------------Initializing------------+
   Initialization successful
   1 touch detected
   Context before hardfault:
   ```

### Issues/PRs references

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
This needs a rebase

**Comment by gschorcht** [comment]
@benpicco I had to add a small change (commit 7acf801). The INT pin must not be initialized if `cb` is NULL. The interrupt trigger mode, however, should be configured independent on whether the INT pin is initialized by the `ft5x06_init` function or later, for example by the `touch_dev` implementation. Even if the INT pin isn't defined, it doesn't matter to configure the interrupt trigger mode.

It worked before without this change because the interrupt trigger mode is the default mode after reset. That is, we could also drop its configuration completely.

**Comment by aabadie** [comment]
Just tested this PR on stm32f723e-disco and I get a hard fault when enabling polling mode:

```
2023-08-28 09:07:15,847 # Initialization successful
2023-08-28 09:07:16,881 # Stack pointer corrupted, reset to top of stack
2023-08-28 09:07:16,881 # FSR/FAR:
2023-08-28 09:07:16,884 #  CFSR: 0x00020000
2023-08-28 09:07:16,885 #  HFSR: 0x40000000
2023-08-28 09:07:16,887 #  DFSR: 0x0000000b
2023-08-28 09:07:16,889 #  AFSR: 0x00000000
2023-08-28 09:07:16,889 # Misc
2023-08-28 09:07:16,891 # EXC_RET: 0xfffffff1
2023-08-28 09:07:16,892 # *** RIOT kernel panic:
2023-08-28 09:07:16,894 # HARD FAULT HANDLER
2023-08-28 09:07:16,894 # 
2023-08-28 09:07:16,895 # *** halted.
2023-08-28 09:07:16,896 # 
2023-08-28 09:07:16,897 # Inside isr -13
2023-08-28 09:07:18,009 # Exiting Pyterm
```

The interrupt mode still works though.

**Comment by aabadie** [comment]
> Just tested this PR on stm32f723e-disco and I get a hard fault when enabling polling mode

If I revert 7acf801, polling mode works.

**Comment by aabadie** [comment]
I think the following diff makes more sense:

```diff
diff --git a/drivers/ft5x06/ft5x06.c b/drivers/ft5x06/ft5x06.c
index d455e8b1b8..e13ee7dc4d 100644
--- a/drivers/ft5x06/ft5x06.c
+++ b/drivers/ft5x06/ft5x06.c
@@ -83,9 +83,10 @@ int ft5x06_init(ft5x06_t *dev, const ft5x06_params_t *params, ft5x06_event_cb_t
     if (gpio_is_valid(dev->params->int_pin) && cb) {
         DEBUG("[ft5x06] init: configuring touchscreen interrupt\n");
         gpio_init_int(dev->params->int_pin, GPIO_IN, GPIO_RISING, cb, arg);
-        i2c_write_reg(FT5X06_BUS, FT5X06_ADDR, FT5X06_G_MODE_REG, FT5X06_G_MODE_INTERRUPT_TRIGGER & 0x01, 0);
     }
 
+    i2c_write_reg(FT5X06_BUS, FT5X06_ADDR, FT5X06_G_MODE_REG, FT5X06_G_MODE_INTERRUPT_TRIGGER & 0x01, 0);
+
     i2c_release(FT5X06_BUS);
 
     return 0;
```

(keep the `&& cb` in the `if`)
Because the interrupt pin might be defined by default in the board configuration, so skipping the interrupt pin initialization if it's not defined and cb is also not defined is better IMHO.

**Comment by gschorcht** [comment]
> (keep the `&& cb` in the `if`) Because the interrupt pin might be defined by default in the board configuration, so skipping the interrupt pin initialization if it's not defined and cb is also not defined is better IMHO.

:see_no_evil: This was exactly what I intended by the last change. I shouldn't have changed the source on my mobile. Of course `gpio_init` must only be called if `cb` is not `NULL`. This was the initial intention of the fix in this PR.

I fixed it and squashed this small fix directly.

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

...

**Comment by gschorcht** [comment]
Thanks for reviewing and merging :smile:

**Pull request merged**
