### PR TITLE
tests/bench_bitarithm: Move and add JSON output

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR moves the `tests/bitarithm_timings` benchmark to `tests/bench_bitarithm` to have the name more consistent with the other benchmark tests.

The second part of the test JSON output for the results:

```
2020-08-07 11:09:33,674 # START
2020-08-07 11:09:33,680 # main(): This is RIOT! (Version: 2020.10-devel-597-g53b8b-HEAD)
2020-08-07 11:09:33,681 # Start.
2020-08-07 11:09:38,685 # + bitarithm_msb: 3848550 iterations per second
2020-08-07 11:09:38,691 # { "bitarithm_msb" : { "iter/second" : 3848550, "ticks" : 56}}
2020-08-07 11:09:43,695 # + bitarithm_lsb: 4867603 iterations per second
2020-08-07 11:09:43,701 # { "bitarithm_lsb" : { "iter/second" : 4867603, "ticks" : 44}}
2020-08-07 11:09:48,705 # + bitarithm_bits_set: 1974857 iterations per second
2020-08-07 11:09:48,711 # { "bitarithm_bits_set" : { "iter/second" : 1974857, "ticks" : 109}}
2020-08-07 11:09:53,716 # + bitarithm_test_and_clear: 1741934 iterations per second
2020-08-07 11:09:53,723 # { "bitarithm_test_and_clear" : { "iter/second" : 1741934, "ticks" : 124}}
2020-08-07 11:09:53,724 # Done.
```

Of course let me know if you think that the regular output (now interleaved with the JSON) should be removed.

### Testing procedure

Run the test application on both native and a board with `CLOCK_CORECLOCK` defined.

### Issues/PRs references

None

### CODE REVIEW

**Comment by fjmolinas** [comment]
If we are going to start using JSON, should we revive https://github.com/RIOT-OS/RIOT/pull/11224/files? @MrKevinWeiss

**Comment by MrKevinWeiss** [comment]
The helper function is implemented with the robot tests in https://github.com/RIOT-OS/RobotFW-tests/pull/28. It would be nice to use helper functions but this can also be done later... There is still a problem with the schema that the test helpers require.

**Comment by benpicco** [comment]
Having the information displayed twice is weird. 
Just remove the non-JSON then, this way it's not any more readable.

**Comment by fjmolinas** [comment]
> Having the information displayed twice is weird.
> Just remove the non-JSON then, this way it's not any more readable.

+1, lets not stall this because of the helpers.

**Comment by fjmolinas** [comment]
BTW can you rebase @bergzand?

**Comment by bergzand** [comment]
rebased!

>  Just remove the non-JSON then, this way it's not any more readable.

Removed!

**Comment by fjmolinas** [comment]
@bergzand care to rebase?

**Pull request closed without merging**
