### PR TITLE
cpu: stm32: use unsigned as loop counter

### PR DESCRIPTION
**Pull request by OlegHahm**
Small fix to an unintended change in #6184.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Again some unrelated Murdock failure caused by external packages?

**Comment by OlegHahm** [comment]
The failure seems to be related to https://github.com/RIOT-OS/RIOT/pull/6260.

**Comment by OlegHahm** [comment]
Okay, apparently we have to merge #6260 first.

**Comment by kaspar030** [comment]
no, but this needs a rebase.

**Comment by OlegHahm** [comment]
Where is the rebase? We need the rebase!

**Pull request merged**
