### PR TITLE
makefiles/arch/riscv.inc.mk: Detect target triple

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This improves the target triple detection logic to include all possible target triples of compilers that might be able to generate our binaries.

### Testing procedure

`make BOARD=hifive1 -C exampes/default` should work if you have a GCC cross compiler able of generating RISC-V binaries for embedded systems, no matter what variant of the target triple you chose.

### Issues/PRs references

Suggested by @nmeum in https://github.com/RIOT-OS/RIOT/pull/15176

### CODE REVIEW

**Comment by maribu** [comment]
@nmeum: I somehow cannot request a review from you with the dedicated "request review" feature. But I would be happy if you could take a look anyway.

**Comment by aabadie** [comment]
This is still working for me both when using my local toolchain (`riscv-none-embed-`) or the toolchain provided by Docker (which are the same...).
The list of possible triples looks ok for me.

**Comment by aabadie** [comment]
I'm trying to use the riscv toolchain provided in the Ubuntu packages (riscv64-unknown-elf). First, the compiler is found with success by the new makefile. Second, the build fail because the includes are not found. I guess something is missing on my local setup (and I don't know how to fix it).

**Review by aabadie — APPROVED** [review]
So the logic of this PR is working fine and that's what is expected. The problems I have are with the newlib which is not found but are not related to this PR.

ACK

**Pull request merged**
