### PR TITLE
cpu: moved msp430-common to msp430_common

### PR DESCRIPTION
**Pull request by haukepetersen**
All other shared CPU folders are name `xxx_common`. This PR does the same for the `msp430_common`...

### CODE REVIEW

**Comment by OlegHahm** [comment]
Murdock would like you to write documentation. ;-)

**Comment by miri64** [comment]
FYI:

```
cpu/msp430_common/include/time.h:13: warning: the name `cpu/msp430_common/include/time.h' supplied as the second argument in the \file statement matches the following input files:
   cpu/msp430_common/include/time.h
cpu/msp430_common/include/msp430_types.h:46: warning: Compound timeval is not documented.
cpu/msp430_common/include/msp430_types.h:40: warning: Compound timespec is not documented.
cpu/msp430_common/include/msp430_types.h:41: warning: Member tv_sec (variable) of class timespec is not documented.
cpu/msp430_common/include/msp430_types.h:42: warning: Member tv_nsec (variable) of class timespec is not documented.
cpu/msp430_common/include/msp430_types.h:48: warning: Member tv_usec (variable) of class timeval is not documented.
```

(the first one sounds rather tautological)

**Comment by haukepetersen** [comment]
How I hate this: just by moving some old existing code you get trouble by non-existent documentation...

remark: why is Jenkins happy and Murdock is not? I thought they are doing the same thing (-> @kaspar030 , @cgundogan)

**Comment by cgundogan** [comment]
@haukepetersen seems like the `dist/tools/build_and_test.sh` script does not return a non-zero return value if there are warnings in doxygen. I will take a look at that. The log for the static tests is here:
https://riot-ci.inet.haw-hamburg.de/job/RIOT/job/PR-6349/4/artifact/success_static-tests.log

**Comment by haukepetersen** [comment]
doxygen should hopefully be fixed now. Although I don't quite get wha statements like:
```
/home/hauke/dev/riot/RIOT/cpu/msp430_common/include/time.h:13: warning: the name `/home/hauke/dev/riot/RIOT/cpu/msp430_common/include/time.h' supplied as the second argument in the \file statement matches the following input files:
   /home/hauke/dev/riot/RIOT/cpu/msp430_common/include/time.h
```
are supposed to tell me?!

**Comment by miri64** [comment]
Suspected to be a doxygen bug: https://github.com/RIOT-OS/RIOT/issues/6367

**Comment by PeterKietzmann** [comment]
All green! @miri64 everything fine with doxygen now?

**Comment by miri64** [comment]
There was no fix, so that would be surprising. But maybe this bug is more of a heisenberg nature ;-).

**Pull request merged**
