### PR TITLE
rust: Use stable Rust

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

Since Rust 1.65, we don't depend on anything nightly any more. This changes the examples and documentation to use stable.

### Testing procedure

* Green CI with tests enabled
* Look at changed documentation ([rendered](https://ci.riot-os.org/results/2923b30a4ba04dbface1ed38fb6aae12/doc-preview/using-rust.html#toolchain))

<del>Note that these will *not* pass yet: This needs a CI update (no PR associated: Any CI image built from now on will do).</del>

### Issues/PRs references

A follow-up will simplify things a bit further, but that will depend on CI to have made stable the default, which is a later step in what is a bit of a lock-step game:

* [x] CI rebuilds riotdocker -- no PR, then stable=1.65
* [ ] Use stable in examples -- this PR, then examples use stable
* [ ] CI removes nightly and makes stable the default -- https://github.com/RIOT-OS/riotdocker/pull/214, then default=stable
* [ ] Use the new default to simplify makefiles -- https://github.com/RIOT-OS/RIOT/pull/18840

### CODE REVIEW

**Comment by chrysn** [comment]
Fixed one more obsolete comment and punctuation error in the docs (insta-squashed). This should now be ready.

(If we were in a hurry with getting rid of nightly, it might even be proposed for backporting into any 2022.10.1, but given that nightly just "sits there" after this commit, I don't think we are in a hurry)

**Comment by maribu** [comment]
We could still backport it to the 2022.10 branch. I'm not qualified to truly understand the consequences, but to me it looks mostly like a convenience update.

I'd say we can make an exception and backport it (especially on the grounds that I do not think that switching from a nightly toolchain to a stable toolchain branch is scary). But IMO we need to have some solid reasoning for why this cannot just wait for the next release. Would it fix any issues?

**Comment by chrysn** [comment]
Convenience and speedier removal of nightlies from CI is all there is to it. It solves no concrete problem of the shipped release.

**Comment by maribu** [comment]
Did you say this speeds up the CI times? We need to backport this!!!!!one one eleven

**Comment by chrysn** [comment]
The speedup is only in procedures: If this is backported, it'll take us one fewer release to achieve full nightly-freeness through the lockstepping between main git and the CI image. I don't expect any change in build times through the process, except if you count image obtaining times, which will be a few percent faster after https://github.com/RIOT-OS/riotdocker/pull/214.

But anyway, it could need an ACK *fish fish* before it is backported (or, rather not)

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
Let's backport this :)

**Pull request merged**
