### PR TITLE
WIP try to make shell tests reliable

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

When running CI tests on nodes, regularly the following tests fail:

    tests/struct_tm_utility/samr21-xpro
    tests/ps_schedstatistics/samr21-xpro
    tests/shell/samr21-xpro

This is an attempt to fix this by waiting that the shell correctly answers to newline characters.

The goal is to re-run the tests several times to check if they are reliable.

### List of executions:

 * Run tests (start time):
    * 5/30/2018, 5:09:21 PM - [Success]
    * 5/30/2018, 5:54:46 PM - [Success]
    * 5/30/2018, 6:18:51 PM - [Success]
    * 5/30/2018, 7:25:42 PM - [Success]
    * ... [todo]
 * Failed tests: 0

### Implementation

I added another module in testrunner for RIOT specific calls.
It was somehow inspired by https://github.com/RIOT-OS/Release-Specs/blob/master/07-multi-hop/IOTLABHelper.py that has riot specific high level expect functions.

### Future work

They are currently implemented as functions, as testrunner returns a pexpect child.
But if refactoring testrunner as a class, this could just be a subclassing and implemented as methods.

### Issues/PRs references

For example https://github.com/RIOT-OS/RIOT/pull/8841#issuecomment-392893606

### CODE REVIEW

**Comment by kYc0o** [comment]
Relaunched at 5/30/2018, 5:54:46 PM

**Comment by cladmi** [comment]
I managed to have errors in the middle of tests using the shell on my local setup even with this. So fixing the beginning may not be enough.

**Comment by smlng** [comment]
doesn't work for me, tested on macOS with remote-revb and `tests/ps_...`. Output of `make flash test` was:

```
g/RIOT/dist/tools/pyterm/pyterm -p "/dev/tty.SLAB_USBtoUART" -b "115200"
No handlers could be found for logger "root"
2018-06-05 09:02:01,625 - INFO # Connect to serial port /dev/tty.SLAB_USBtoUART
Welcome to pyterm!
Type '/exit' to exit.
2018-06-05 09:02:03,092 - INFO # main(): This is RIOT! (Version: 2018.07-devel-462-gea0c0-mobi25.inet.haw-hamburg.de-HEAD)
2018-06-05 09:02:03,098 - INFO # Creating thread #0, next=1
2018-06-05 09:02:03,099 - INFO # Creating thread #1, next=2
2018-06-05 09:02:03,099 - INFO # Creating thread #2, next=3
2018-06-05 09:02:03,099 - INFO # Creating thread #3, next=4
2018-06-05 09:02:03,100 - INFO # Creating thread #4, next=0
> 







































Timeout in expect script at "child.expect(RIOT_PROMPT, *args, **kwargs)" (dist/tools/testrunner/riot.py:24)

make: *** [test] Error 1
```

The empty lines where generated when running the test. Running the same on master (2018-06-05), works with output:

```
/RIOT/dist/tools/pyterm/pyterm -p "/dev/tty.SLAB_USBtoUART" -b "115200"
No handlers could be found for logger "root"
2018-06-05 09:04:26,532 - INFO # Connect to serial port /dev/tty.SLAB_USBtoUART
Welcome to pyterm!
Type '/exit' to exit.
2018-06-05 09:04:28,026 - INFO # main(): This is RIOT! (Version: 2018.07-devel-458-g5e577-mobi25.inet.haw-hamburg.de)
2018-06-05 09:04:28,027 - INFO # Creating thread #0, next=1
2018-06-05 09:04:28,028 - INFO # Creating thread #1, next=2
2018-06-05 09:04:28,028 - INFO # Creating thread #2, next=3
2018-06-05 09:04:28,028 - INFO # Creating thread #3, next=4
2018-06-05 09:04:28,029 - INFO # Creating thread #4, next=0
> 
help

help
2018-06-05 09:04:29,646 - INFO #  help
2018-06-05 09:04:29,654 - INFO # Command              Description
2018-06-05 09:04:29,655 - INFO # ---------------------------------------
2018-06-05 09:04:29,658 - INFO # reboot               Reboot the node
2018-06-05 09:04:29,665 - INFO # ps                   Prints information about running threads.
ps
> ps
2018-06-05 09:04:29,719 - INFO #  ps
2018-06-05 09:04:29,735 - INFO # 	pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     | runtime  | switches
2018-06-05 09:04:29,745 - INFO # 	  - | isr_stack            | -        - |   - |    512 (  128) | 0x20000000 | 0x200001c8
2018-06-05 09:04:29,763 - INFO # 	  1 | idle                 | pending  Q |  15 |    256 (  128) | 0x2000075c | 0x200007dc  | 66.867% |      1036
2018-06-05 09:04:29,781 - INFO # 	  2 | main                 | running  Q |   7 |   1536 (  744) | 0x2000085c | 0x20000c94  |  0.870% |       104
2018-06-05 09:04:29,799 - INFO # 	  3 | thread               | bl rx    _ |   6 |   1024 (  388) | 0x20000f7c | 0x2000129c  |  5.067% |       463

```

**Comment by cladmi** [comment]
Why is the board not answering ?
Is it because a difference when sending an empty line ?

**Comment by cladmi** [comment]
We found out that sending an empty line in pyterm does nothing, so I tried to replace it by 'help'.

**Comment by kYc0o** [comment]
In current master the remote-revb doesn't have a functional reset target which is called by the test target. I find very strange that the test works, @smlng might be coincidence?

However, for samr21-xpro this PR doesn't work for me in OS X, but as far as I know, we don't claim complete support for OS X so it doesn't matter.

**Comment by cladmi** [comment]
It is normal that it failed with my changes as it was my "initialization" check that failed.

**Comment by kaspar030** [comment]
I did some more debugging on the samr21-xpro murdock node, and I'm more convinced that this is a bug in edbg. It seems like, at some point, something is stuck pointing to a buffer 7 bytes in the past.
Thus, if you'd type "abcdefg....", the samr21-xpro will get whatever was before in the buffer, until you send "g", at which point it starts outputting "abcd..." (with each transmitted byte).

rmmod cdc_acm does not help, power-cycling the samr21-xpro does bring it back to a usable state.

Power-cycling USB can be done programmatically on RasPi, so there's at least a workaround for murdock. #9622 adds the necessary infrastructure to ```./.murdock```.

**Comment by kaspar030** [comment]
> Power-cycling USB can be done programmatically on RasPi, so there's at least a workaround for murdock. #9622 adds the necessary infrastructure to `./.murdock`.

The CI samr21-xpro are now power cycled before each test run, which seems to have fixed the issue.

Thanks @cladmi for investigating!

**Pull request closed without merging**
