### PR TITLE
cpu/cc26x0_cc13x0: Drop feature cortexm_mpu

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

At least the CC2650 doesn't have an MPU, I assume this is also true for the rest of the family.

The CC2652 does have an MPU according to the datasheet. So I keep the feature there in place.

### Testing procedure

E.g.

```
make BOARD=cc2650-launchpad -C tests/mpu_noexec_ram flash test
```

fails. (Note: A successful test run would also crash but with a mem manage handler rather than a hardfault due to an invalid instruction on the stack being executed.)

It would be nice to also test the same for a `cc2652-launchpad`, for which the MPU should work.

### Issues/PRs references

None

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by maribu** [comment]
bors merge

**Comment by maribu** [comment]
bors retry

**Comment by maribu** [comment]
bors merge

**Comment by maribu** [comment]
bors merge

**Pull request merged**
