### PR TITLE
pic32: Add SPI Support

### PR DESCRIPTION
**Pull request by neiljay**
This is a re-open of #7383 with a couple of fixes + rebase.

This PR adds SPI support for PIC32 devices and has been tested on wifire and clicker.

Depends on #9433

### CODE REVIEW

**Comment by cladmi** [comment]
@neiljay How can I test this ? I have a pic32-wifire board.

**Comment by neiljay** [comment]
@cladmi, apply #7656 also then plug in an sdcard and runs tests/driver_sdcard_spi (I would build it with debug turned on).

**Comment by cladmi** [comment]
I managed to put an sdcard in the board but not testing it yet. I will try to do it next week.

**Comment by benpicco** [comment]
This would need another rebase

**Pull request closed without merging**
