### PR TITLE
tools: Add spectrum-scanner host side script

### PR DESCRIPTION
**Pull request by gebart**
The host side component for use with the spectrum-scanner application in https://github.com/RIOT-OS/applications/pull/30

Example output:

image

### CODE REVIEW

**Comment by smlng** [comment]
sorry for being blunt: but why put the script here if it specifically depends on an application in another repo? I assume its because of `dist/tools/sniffer/`, which (IMHO) is also misplaced and should be moved.

**Comment by smlng** [comment]
besides: nice work - the tool/application and script for plotting!

**Comment by gebart** [comment]
Yes, I put it here because of dist/tools/sniffer. I will move it to the applications repo and add it to the PR for the scanner application.

**Comment by gebart** [comment]
moved to RIOT-OS/applications#30

**Pull request closed without merging**
