### PR TITLE
sixlowpan: Clean-up, take IPv6 out, and refactor to netapi

### PR DESCRIPTION
**Pull request by authmillenon**
Depends on ~~#1448, #1984~~ (both merged), #1967, and ~~#2027~~ (merged).

Had to restructure this PR a little bit due to the introduction of #1967. I also used the opportunity and introduced `byteorder` to IPv6 (where I already needed parts of it, namely headers and addresses), so every time one tries to send in wrong order, there will be a nice compiler error now :-).

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to #1967

**Comment by authmillenon** [comment]
On hold, until I'm done with the IPv6 implementation (see #2278). Please don't ask me to rebase this PR, until #2003 is under review.

**Comment by OlegHahm** [comment]
Can we close this?

**Comment by authmillenon** [comment]
@OlegHahm see https://github.com/RIOT-OS/RIOT/pull/1680#issuecomment-73412225. I'll decide when I'm done with #2454 if I recycle this one, or open a new one.

**Comment by OlegHahm** [comment]
ok

**Comment by authmillenon** [comment]
New port in #2614 and onwards.

**Pull request closed without merging**
