### PR TITLE
doc: Doxygen beautification

### PR DESCRIPTION
**Pull request by miri64**
I used my Sunday to finally provide a beautified version of our Doxygen documentation. The design is based around [bootstrap](http://getbootstrap.com/), but with costumized color scheme, based on the color scheme of our website (see [config.json](https://github.com/miri64/RIOT/blob/f9a936399b96b8aa2b0fdbe4d092917e03ede6b9/doc/doxygen/src/config.json) provided). This however only provides some basic formatting. Everything else is handcrafted or included because doxygen uses a way old version of jQuery and bootstrap requires a newer one (mainly every js file that has jquery in name ;-)). Thanks to bootstraps mobile first paradigm we also now have mobile support for our doc.

Main page

Code view

Mobile view

(if the colors are to dark: this is the simplest thing to change ;-)).

### CODE REVIEW

**Comment by aabadie** [comment]
This is very nice ! Good job @miri64

**Comment by miri64** [comment]
Discovered some bugs. Please don't merge yet ;-)

**Comment by kaspar030** [comment]
Very nice indeed!

**Comment by miri64** [comment]
Now the bugs I was talking about are fixed. Say the word if your favorite view is broken ;-)

**Comment by aabadie** [comment]
What about a white (or any better bright color) for the main and treeview panel ?
We could also hide/remove the handle between the treeview and main panel.

**Comment by miri64** [comment]
@aabadie this sounds like you want the whole thing inverted (except for header and footer). Did I get this right ^^?

**Comment by aabadie** [comment]
Yes kind of. Just to compare.

**Comment by miri64** [comment]
Aaaww, but the bootstrap conversion was what took most of the time ^^. Also I think it looks boring:

untitled

**Comment by miri64** [comment]
(the slide is a bit tricky to remove, since doxygen either has a slider or no treeview :-/)

**Comment by Lotterleben** [comment]
I'm with @aabadie on this one– the black version looks nifty, but white-on-black text is harder to read and we want our documentation to be as helpful as possible, no? :) The white version looks great t o me though, thank you for doing this!

**Comment by miri64** [comment]
Updated color scheme (and some fixes to the overall design):

screenshot from 2017-04-12 12-43-15

screenshot from 2017-04-12 12-43-26

screenshot from 2017-04-12 12-44-02

screenshot from 2017-04-12 12-45-14

**Comment by gebart** [comment]
I like the newest scheme.
The side bar/table of contents would maybe go better with the rest of the page if that too was in a dark text on a bright background.

**Comment by miri64** [comment]
I actually like this one too. Will prepare a patch.

screenfulllight

**Comment by Lotterleben** [comment]
I think the last one's great! It solves the readability issues of black background and the menu bar doesn't compete with the content. You instantly know where to look. Fantastic Job :)

**Comment by aabadie** [comment]
Let's use the emoji to vote ?

**Comment by miri64** [comment]
> Let's use the emoji to vote ?

Okay, first let me collect the alternatives in separate posts. Votes go like this: everyone has as many votes as there are options, approval can be given by a :+1: emoji, disapproval by a :-1: emoji, or you can just abstain from the vote on the option. The result with the highest positive sum wins. If only negative somes come out I make a re-design ;-P

**Comment by miri64** [comment]
# Option 1: Full Dark

64aa4e16-1d63-11e7-9d42-dc75e3a9e5c2

(Fonts of title will be set to the font of the other headings)

**Comment by miri64** [comment]
# Option 2: Light content, Dark side-bar

6d7c517e-1f7f-11e7-8655-b94ce91a31f1

**Comment by miri64** [comment]
Option 3: Full light

screenfulllight

**Comment by miri64** [comment]
Seems like option three gets an overwhelming majority. Shall I squash? Remember: tomorrow is feature freeze, so it would be nice to have this in for the release ;-).

**Comment by miri64** [comment]
BTW. I did not add the LESS-files I used to generate the `riot.css`. Shall I include it too (or since it is on my machine at home, provide a follow-up for them) or upload them separately somewhere?

**Comment by miri64** [comment]
Squashed

**Comment by gebart** [comment]
@miri64 I think you should add, in a separate PR, the source files for the design if you have used some tools for it.

**Comment by miri64** [comment]
Removed trailing whitespaces in the autogenerated Font-SVGs and squashed immediately.

**Comment by aabadie** [comment]
so Murdock is green now, let's go for new style documentation !

**Comment by gebart** [comment]
why does my local doc build look like this now? The one at https://riot-os.org/api looks fine

screenshot_20170414_104035

**Comment by aabadie** [comment]
Could it be a doxygen version issue ? I have 1.8.11 and don't see any problem locally.

**Comment by gebart** [comment]
@aabadie I have 1.8.13.

I found this in the web browser developer tools console log:

```
Uncaught TypeError: $(...).smartmenus is not a function
    at initMenu (menu.js:25)
    at HTMLDocument.<anonymous> (modules.html:83)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
```

**Comment by gebart** [comment]
Opened #6910 for this problem

**Pull request merged**
