### PR TITLE
make: use LLDB if GDB is not available on native platform

### PR DESCRIPTION
**Pull request by Yonezawa-T2**
If GDB is not available on native platform (i.e. macOS), then use LLDB instead.
Related: #534

Known problem: It spawns two processes but LLDB kills only one when quitting. We have to `kill -9` it manually.

Another problem: `make TOOLCHAIN=llvm all` results in `error: unknown target triple '-Wall', please use -triple or -arch`. We can, though, build RIOT with `make all` without genuine GCC because `/usr/bin/gcc` mimics GCC and delegates to Clang.

### CODE REVIEW

**Comment by miri64** [comment]
> If GDB is not available on native platform (i.e. macOS), then use LLDB instead.
Related: #534

Wasn't the problem in #534 that GDB does not work even IF it is installed?

**Comment by Yonezawa-T2** [comment]
I didn't confirmed that GDB didn't work. Now I confirmed that GDB didn't work.
Changed to use LLDB on Darwin even if GDB is installed.

I got different error message. It is terminated with SIG113. Maybe we could investigate it deeper, but I'm satisfied with LLDB.

**Comment by miri64** [comment]
Can we get this merged today @kYc0o @smlng @emmanuelsearch @thomaseichinger?

**Comment by smlng** [comment]
I can confirm that this runs `lldb` instead of `gdb`  for `make debug` on macOS. But I have to admit that  I'm a not very familiar with the debugging tools. However, this seems to work as far as I can tell - so ACK from my side.

**Pull request merged**
