### PR TITLE
boards/nucleo-l433rc: initial support

### PR DESCRIPTION
**Pull request by aabadie**
~Work in progress~ port for [nucleo-l433](http://www.st.com/en/evaluation-tools/nucleo-l433rc-p.html).

This board is interesting since the UART on Arduino pinout is not the same as the ST Link uart (used as STDIO). Then we can use any XBee (or other Bee like radios) extension board on top of it for communication.

The problem is that the UART used with ST Link is an LPUART so I couldn't make the board fully work (only led blink actually...): no output on terminal...

Any help appreciated.

### CODE REVIEW

**Comment by haukepetersen** [comment]
As an intermediate solution, I guess we have to go with manual multiplexing inside the UART driver as proposed already for the Kinetis...

**Comment by aabadie** [comment]
> we have to go with manual multiplexing inside the UART driver as proposed already for the Kinetis

Sorry, I don't understand this. Looking at the kinetis code, there's no multiplexing in the UART driver. By the way, there is in the timer/lptimer driver.

**Comment by gebart** [comment]
@aabadie I think @haukepetersen was referring to the proposed Kinetis LPUART+UART multiplexing driver in #7362

**Comment by haukepetersen** [comment]
yes

**Comment by aabadie** [comment]
Just to move forward with this one (until we have support for stm32 lpuart), I updated the port to use the RX/TX of the Arduino pinout as stdio. The thing is one has to use a serial to USB converter in order to have the debug output.

I also rebased and fixed a couple of issues. The board works well:
- timer, pwm, uart, spi peripherals work
- also tested saul gpio, threads and xtimer with success

This PR is no more WIP.

**Comment by aabadie** [comment]
rebased and conflicts fixed. Maybe @astralien3000, can just give it a try (the stdout is on the Arduino RX/TX pins).

**Comment by astralien3000** [comment]
I tested, all is ok for me.

**Comment by aabadie** [comment]
> I tested, all is ok for me.

Thanks, so I guess this can go then ?

**Comment by aabadie** [comment]
> no problem

Thanks, so let's go !

**Pull request merged**
