### PR TITLE
ztimer: fix `ztimer_is_set()`

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

  ztimer's machinery depends on figuring out if a timer is currently set
  or not. It does that using _is_set(), which is also exposed as
  ztimer_is_set().
  Now when a timer expired and got taken of the timer queue using
  _now_next(), the `next` pointer wasn't unset. This caused _is_set() to
  wrongly return `true` for that timer.
  Internally in ztimer, this didn't cause breakage, just an unnecessary
  iteration of the timer queue by _delete_timer_from_list().
  But this also broke the public ztimer_is_set().

  This PR fixes the issue by correctly NULLing the timer's `next`
  pointer when the timer triggers.

There's also an added regression test to ztimer's unittests.

### Testing procedure

The regression test now ensures correct behaviour. To see it fail, uncomment the new lines in sys/ztimer/core.c and run ztimer's unittests.

### CODE REVIEW

**Comment by haukepetersen** [comment]
This one gave me a hard night yesterday :-)

One way to trigger the faulty behavior:
- run `gnrc_networking` example using BLE (`nimble_netif`) on any supporting platform
- try to connect to BLE node with a fake address, e.g. `ble connect aa:aa:aa:aa:aa:aa`

Without this PR:
```
2021-04-22 11:25:15,387 # RIOT network stack example application
2021-04-22 11:25:15,389 # All up, running the shell now
ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:25:17,634 # ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:25:17,639 # initiated connection procedure with AA:AA:AA:AA:AA:AA
> ble info
2021-04-22 11:25:19,870 # ble info
2021-04-22 11:25:19,876 # Own Address: E8:0C:C0:C3:FD:AD -> [FE80::E80C:C0FF:FEC3:FDAD]
2021-04-22 11:25:19,877 #  Free slots: 2/3
2021-04-22 11:25:19,878 # Advertising: no
2021-04-22 11:25:19,880 # Connections: 0
2021-04-22 11:25:19,881 # Slots:
2021-04-22 11:25:19,883 # [ 0] state: 0x4000 - connecting
2021-04-22 11:25:19,886 # [ 1] state: 0x8000 - unused
2021-04-22 11:25:19,888 # [ 2] state: 0x8000 - unused
2021-04-22 11:25:19,888 # 
> ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:25:23,180 # ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:25:23,184 # err: unable to trigger connection sequence (-3)
> 
```
-> the connection procedure is stuck and does not time out after 500ms as it is expected to

With this PR:
```
2021-04-22 11:26:34,919 # RIOT network stack example application
2021-04-22 11:26:34,922 # All up, running the shell now
ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:26:36,970 # ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:26:36,975 # initiated connection procedure with AA:AA:AA:AA:AA:AA
> 2021-04-22 11:26:37,476 # event: handle 0 -> CONNECTION ABORT (AA:AA:AA:AA:AA:AA)
ble info
2021-04-22 11:26:42,354 # ble info
2021-04-22 11:26:42,360 # Own Address: E8:0C:C0:C3:FD:AD -> [FE80::E80C:C0FF:FEC3:FDAD]
2021-04-22 11:26:42,361 #  Free slots: 3/3
2021-04-22 11:26:42,363 # Advertising: no
2021-04-22 11:26:42,364 # Connections: 0
2021-04-22 11:26:42,364 # Slots:
2021-04-22 11:26:42,367 # [ 0] state: 0x8000 - unused
2021-04-22 11:26:42,369 # [ 1] state: 0x8000 - unused
2021-04-22 11:26:42,372 # [ 2] state: 0x8000 - unused
2021-04-22 11:26:42,372 # 
> ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:26:43,736 # ble connect aa:aa:aa:aa:aa:aa
2021-04-22 11:26:43,741 # initiated connection procedure with AA:AA:AA:AA:AA:AA
> 2021-04-22 11:26:44,241 # event: handle 0 -> CONNECTION ABORT (AA:AA:AA:AA:AA:AA
```
-> the connection procedure times out as expected.

Also the test newly added unit tests run as expected:
```
Type '/exit' to exit.
s
2021-04-22 11:20:23,940 # START
2021-04-22 11:20:28,845 # ..........
2021-04-22 11:20:28,846 # OK (10 tests)
2021-04-22 11:23:41,600 # Exiting Pyterm
```

**Review by haukepetersen — APPROVED** [review]
Confirmed to fix the broken `ztimer_is_set()` behavior as encountered with NimBLE.

**Comment by miri64** [comment]
> Also the test newly added unit tests run as expected:
> 
> ```
> Type '/exit' to exit.
> s
> 2021-04-22 11:20:23,940 # START
> 2021-04-22 11:20:28,845 # ..........
> 2021-04-22 11:20:28,846 # OK (10 tests)
> 2021-04-22 11:23:41,600 # Exiting Pyterm
> ```

Does it also fail without the fix (i.e. does it indeed check for a regression)?

**Comment by haukepetersen** [comment]
Sorry, yes! Without this PR:
```
2021-04-22 11:38:27,274 # START
2021-04-22 11:38:27,292 # .......
2021-04-22 11:38:27,302 # ztimer_tests.test_ztimer_mock_is_set (tests/unittests/tests-ztimer/tests-ztimer-mock.c 277) !ztimer_is_set(z, &alarm)
2021-04-22 11:38:32,241 # ...
2021-04-22 11:38:32,243 # run 10 failures 1
```

**Comment by haukepetersen** [comment]
Or rather without the fixing commit :-)

**Comment by haukepetersen** [comment]
all green -> go!

**Comment by kaspar030** [comment]
Backport provided in #16368

**Pull request merged**
