### PR TITLE
radio/nrf802154: fix state transition and `off` function

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR fixes the following bugs:
- The `off` function was turning on the radio instead of turning it off.
- The `config_phy` function was disabling the radio without going back to the desired state. With the fix, if the radio was in RX mode, the radio will go first to `DISABLE` and then `RXEN`. This "blocks" the `config_phy` for 60 us, which IMO is still OK for the asynchronous API.
- After finishing sending the ACK frame, the radio tried to go to RX mode. This changed with #15228 .

I also updated the `ieee802154_hal` test accordingly (and piggy-backed setting the CCA threshold, otherwise this radio always gets MEDIUM BUSY)

### Testing procedure
Use the HAL test `tests/ieee802154_hal`:
- Check that the radio is able to receive and send data
- Use the `config_phy` command to set a different channel. Check that it works as expected.
- Use the `netdev_ieee802154_submac` with this radio with any example (e.g `gnrc_networking`). Everything should work.

### Issues/PRs references
#15228

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by SemjonKerner** [comment]
hey @benpicco whats the reason for canceling murdock?

**Comment by jia200x** [comment]
I forgot to rebase, this one depends on #15231

**Comment by benpicco** [comment]
This needs a rebase

**Comment by jia200x** [comment]
done!

**Comment by SemjonKerner** [comment]
For `tests/ieee802154_hal` I can confirm txtsnd on master does not work (device busy), but it works as expected with this PR.
Setting channels on both nodes also acted as I expected. I did not confirm it with a sniffer.

I also sent a udp packet and a ping with the submac enabled and both worked fine; see
`USEMODULE=netdev_ieee802154_submac IOTLAB_NODE=nrf52840dk-1.saclay.iot-lab.info BOARD=nrf52840dk make -C examples/gnrc_networking flash term`

From a test point of view it looks good.

**Comment by jia200x** [comment]
thanks for the review and testing!!

**Pull request merged**
