### PR TITLE
dist: Remove Dockerfile in favour of separate repo

### PR DESCRIPTION
**Pull request by gebart**
Replaces #5770.
See https://github.com/RIOT-OS/riotdocker for an up-to-date Dockerfile.

Pre-built images at https://hub.docker.com/r/riot/riotbuild/

use `docker pull riot/riotbuild` to download using the Docker command line tools.

### CODE REVIEW

**Comment by miri64** [comment]
ACK and go. Don't think we need to wait for Murdock for this ;-)

**Comment by tingxin** [comment]
Please also update the doc https://github.com/RIOT-OS/RIOT/wiki/Use-Docker-to-build-RIOT, it misled.....

**Comment by gebart** [comment]
@tingxin I updated the wiki instructions now. Tell me if something does not work or doesn't make sense.

**Comment by tingxin** [comment]
@gebart Thank you good doc, i follow it and try it again, it works well, good job!

**Pull request merged**
