### PR TITLE
drivers/lis2dh12: add I2C mode

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description
The PR adapts the `lis2dh12` driver to work also in I2C mode, which is the used configuration on the `thingy52`. 

The PR is a rebase of #8419 by @haukepetersen and adapts it to changes in the I2C API during the last two years.

### Testing procedure
On a board with lis2dh12 over I2C, run `tests/driver_lis2dh12` and change `DRIVER ?= lis2dh12_spi` to `DRIVER ?= lis2dh12_i2c` in the Makefile.

@MrKevinWeiss tested the original PR with the thingy52. I don't have the thingy52 but a custom samd51 board with the same chip - here the driver is working as expected.

### Issues/PRs references
#8419 rebased & updated to the API changes in master (see fixup)

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I have a thingy52 but I cannot find my jlink to flash it.   Ping me after Oct. 1st and hopefully I can test it (vacation).

**Comment by haukepetersen** [comment]
@benpicco thanks for taking this over! I just could not find the time to finally get this merged... I will close #8419 in favor of this PR.

**Comment by MrKevinWeiss** [comment]
Tested with `BOARD=thingy52 DRIVER=lis2dh12_i2c make flash term -C tests/driver_lis2dh12/`
and got reasonable numbers:
```
2019-10-02 11:06:45,318 - INFO # X:   -0.050 Y:   -0.003 Z:   -1.007
2019-10-02 11:06:45,425 - INFO # X:   -0.050 Y:   -0.003 Z:   -1.023
2019-10-02 11:06:45,522 - INFO # X:   -0.054 Y:    0.000 Z:   -1.015
```
and it makes sense.

**Comment by MrKevinWeiss** [comment]
Squash please

**Comment by benpicco** [comment]
Thank you for the test and review!
Had to push a small fixup: for C++, the struct members have to have the same order for initialization and declaration.

**Pull request merged**
