### PR TITLE
fe310: Merge and optimize trap_entry with irq_arch

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR moves the `intr.S` assembly for the fe310 MCU to the `irq_arch.c`, using inline assembly.

The trap entry handler itself is restructured similar to #14710, the full thread context save/restore is skipped when the active thread is not swapped, only the caller-saved registers are saved and restored by default. As the trap_entry function is used for every interrupt on the platform, this saves cycles on every interrupt on the fe310.

The amount of context *not* saved when exiting a thread is also reduced, slightly optimizing the case where the active thread is set to `NULL`.

### Testing procedure

The `tests/thread_*` must still work. Usually these kind of changes break the tests pretty hard when they contain a bug.

### benchmarks

Number of cycles per interrupt. Can vary a bit per measurement run, the fe310 uses a 32.768 kHz crystal for these measurements.

(Lower is better)

| | master | 3aa4af3 |
|---|----:|----:|
| bench_sched_nop | 232 | 198 |
| bench_mutex_pingpong | 591 | 576 |
| bench_thread_yield_pingpong | 488 | 484 |

### Issues/PRs references

This can also benefit from #14709. The

### CODE REVIEW

**Comment by aabadie** [comment]
Running some threads, pthreads tests and got some differences in results between this PR and master:

<details><summary>this PR:</summary>

```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . hifive1b --jobs=4 --applications="tests/thread* tests/pthread* tests/cpp11_thread tests/cpp11_mutex"
INFO:hifive1b:Saving toolchain
INFO:hifive1b.tests/cpp11_mutex:Board supported: True
INFO:hifive1b.tests/cpp11_mutex:Board has enough memory: True
INFO:hifive1b.tests/cpp11_mutex:Application has test: True
INFO:hifive1b.tests/cpp11_mutex:Run compilation
INFO:hifive1b.tests/cpp11_mutex:Run test
INFO:hifive1b.tests/cpp11_mutex:Run test.flash
INFO:hifive1b.tests/cpp11_mutex:Success
INFO:hifive1b.tests/cpp11_thread:Board supported: True
INFO:hifive1b.tests/cpp11_thread:Board has enough memory: True
INFO:hifive1b.tests/cpp11_thread:Application has test: True
INFO:hifive1b.tests/cpp11_thread:Run compilation
INFO:hifive1b.tests/cpp11_thread:Run test
INFO:hifive1b.tests/cpp11_thread:Run test.flash
INFO:hifive1b.tests/cpp11_thread:Success
INFO:hifive1b.tests/pthread:Board supported: True
INFO:hifive1b.tests/pthread:Board has enough memory: True
INFO:hifive1b.tests/pthread:Application has test: True
INFO:hifive1b.tests/pthread:Run compilation
INFO:hifive1b.tests/pthread:Run test
INFO:hifive1b.tests/pthread:Run test.flash
INFO:hifive1b.tests/pthread:Success
INFO:hifive1b.tests/pthread_barrier:Board supported: True
INFO:hifive1b.tests/pthread_barrier:Board has enough memory: True
INFO:hifive1b.tests/pthread_barrier:Application has test: True
INFO:hifive1b.tests/pthread_barrier:Run compilation
INFO:hifive1b.tests/pthread_barrier:Run test
INFO:hifive1b.tests/pthread_barrier:Run test.flash
INFO:hifive1b.tests/pthread_barrier:Success
INFO:hifive1b.tests/pthread_cleanup:Board supported: True
INFO:hifive1b.tests/pthread_cleanup:Board has enough memory: True
INFO:hifive1b.tests/pthread_cleanup:Application has test: True
INFO:hifive1b.tests/pthread_cleanup:Run compilation
INFO:hifive1b.tests/pthread_cleanup:Run test
INFO:hifive1b.tests/pthread_cleanup:Run test.flash
INFO:hifive1b.tests/pthread_cleanup:Success
INFO:hifive1b.tests/pthread_condition_variable:Board supported: True
INFO:hifive1b.tests/pthread_condition_variable:Board has enough memory: True
INFO:hifive1b.tests/pthread_condition_variable:Application has test: True
INFO:hifive1b.tests/pthread_condition_variable:Run compilation
INFO:hifive1b.tests/pthread_condition_variable:Run test
INFO:hifive1b.tests/pthread_condition_variable:Run test.flash
WARNING:hifive1b.tests/pthread_condition_variable:make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pthread_condition_variable test
r
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Bench Clock Reset Complete

ATE0-->CMD Length Timed Out Busy
 Send sync error AT+BLEINIT=0-->AT+BLEINIT=0
OK
AT+CWMODE=0--> Send sync error 
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)
START
Timeout in expect script at "child.expect('condition fulfilled.')" (tests/pthread_condition_variable/tests/01-run.py:15)

make: *** [/work/riot/RIOT/tests/pthread_condition_variable/../../Makefile.include:792: test] Error 1

Return value: 2

ERROR:hifive1b.tests/pthread_condition_variable:Error during test, writing to results/hifive1b/tests/pthread_condition_variable/test.failed
ERROR:hifive1b.tests/pthread_condition_variable:Failed during: test
INFO:hifive1b.tests/pthread_cooperation:Board supported: True
INFO:hifive1b.tests/pthread_cooperation:Board has enough memory: False
INFO:hifive1b.tests/pthread_flood:Board supported: True
INFO:hifive1b.tests/pthread_flood:Board has enough memory: True
INFO:hifive1b.tests/pthread_flood:Application has test: True
INFO:hifive1b.tests/pthread_flood:Run compilation
INFO:hifive1b.tests/pthread_flood:Run test
INFO:hifive1b.tests/pthread_flood:Run test.flash
INFO:hifive1b.tests/pthread_flood:Success
INFO:hifive1b.tests/pthread_rwlock:Board supported: True
INFO:hifive1b.tests/pthread_rwlock:Board has enough memory: True
INFO:hifive1b.tests/pthread_rwlock:Application has test: True
INFO:hifive1b.tests/pthread_rwlock:Run compilation
INFO:hifive1b.tests/pthread_rwlock:Run test
INFO:hifive1b.tests/pthread_rwlock:Run test.flash
INFO:hifive1b.tests/pthread_rwlock:Success
INFO:hifive1b.tests/pthread_tls:Board supported: True
INFO:hifive1b.tests/pthread_tls:Board has enough memory: True
INFO:hifive1b.tests/pthread_tls:Application has test: True
INFO:hifive1b.tests/pthread_tls:Run compilation
INFO:hifive1b.tests/pthread_tls:Run test
INFO:hifive1b.tests/pthread_tls:Run test.flash
INFO:hifive1b.tests/pthread_tls:Success
INFO:hifive1b.tests/thread_basic:Board supported: True
INFO:hifive1b.tests/thread_basic:Board has enough memory: True
INFO:hifive1b.tests/thread_basic:Application has test: True
INFO:hifive1b.tests/thread_basic:Run compilation
INFO:hifive1b.tests/thread_basic:Run test
INFO:hifive1b.tests/thread_basic:Run test.flash
INFO:hifive1b.tests/thread_basic:Success
INFO:hifive1b.tests/thread_cooperation:Board supported: True
INFO:hifive1b.tests/thread_cooperation:Board has enough memory: True
INFO:hifive1b.tests/thread_cooperation:Application has test: True
INFO:hifive1b.tests/thread_cooperation:Run compilation
INFO:hifive1b.tests/thread_cooperation:Run test
INFO:hifive1b.tests/thread_cooperation:Run test.flash
INFO:hifive1b.tests/thread_cooperation:Success
INFO:hifive1b.tests/thread_exit:Board supported: True
INFO:hifive1b.tests/thread_exit:Board has enough memory: True
INFO:hifive1b.tests/thread_exit:Application has test: True
INFO:hifive1b.tests/thread_exit:Run compilation
INFO:hifive1b.tests/thread_exit:Run test
INFO:hifive1b.tests/thread_exit:Run test.flash
INFO:hifive1b.tests/thread_exit:Success
INFO:hifive1b.tests/thread_flags:Board supported: True
INFO:hifive1b.tests/thread_flags:Board has enough memory: True
INFO:hifive1b.tests/thread_flags:Application has test: True
INFO:hifive1b.tests/thread_flags:Run compilation
INFO:hifive1b.tests/thread_flags:Run test
INFO:hifive1b.tests/thread_flags:Run test.flash
INFO:hifive1b.tests/thread_flags:Success
INFO:hifive1b.tests/thread_flags_xtimer:Board supported: True
INFO:hifive1b.tests/thread_flags_xtimer:Board has enough memory: True
INFO:hifive1b.tests/thread_flags_xtimer:Application has test: True
INFO:hifive1b.tests/thread_flags_xtimer:Run compilation
INFO:hifive1b.tests/thread_flags_xtimer:Run test
INFO:hifive1b.tests/thread_flags_xtimer:Run test.flash
INFO:hifive1b.tests/thread_flags_xtimer:Success
INFO:hifive1b.tests/thread_float:Board supported: True
INFO:hifive1b.tests/thread_float:Board has enough memory: True
INFO:hifive1b.tests/thread_float:Application has test: False
INFO:hifive1b.tests/thread_float:Run compilation
INFO:hifive1b.tests/thread_float:Success
INFO:hifive1b.tests/thread_flood:Board supported: True
INFO:hifive1b.tests/thread_flood:Board has enough memory: True
INFO:hifive1b.tests/thread_flood:Application has test: True
INFO:hifive1b.tests/thread_flood:Run compilation
INFO:hifive1b.tests/thread_flood:Run test
INFO:hifive1b.tests/thread_flood:Run test.flash
INFO:hifive1b.tests/thread_flood:Success
INFO:hifive1b.tests/thread_msg:Board supported: True
INFO:hifive1b.tests/thread_msg:Board has enough memory: True
INFO:hifive1b.tests/thread_msg:Application has test: True
INFO:hifive1b.tests/thread_msg:Run compilation
INFO:hifive1b.tests/thread_msg:Run test
INFO:hifive1b.tests/thread_msg:Run test.flash
INFO:hifive1b.tests/thread_msg:Success
INFO:hifive1b.tests/thread_msg_block_race:Board supported: True
INFO:hifive1b.tests/thread_msg_block_race:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_race:Application has test: True
INFO:hifive1b.tests/thread_msg_block_race:Run compilation
INFO:hifive1b.tests/thread_msg_block_race:Run test
INFO:hifive1b.tests/thread_msg_block_race:Run test.flash
INFO:hifive1b.tests/thread_msg_block_race:Success
INFO:hifive1b.tests/thread_msg_block_w_queue:Board supported: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Application has test: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Run compilation
INFO:hifive1b.tests/thread_msg_block_w_queue:Run test
INFO:hifive1b.tests/thread_msg_block_w_queue:Run test.flash
INFO:hifive1b.tests/thread_msg_block_w_queue:Success
INFO:hifive1b.tests/thread_msg_block_wo_queue:Board supported: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Application has test: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run compilation
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run test
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run test.flash
INFO:hifive1b.tests/thread_msg_block_wo_queue:Success
INFO:hifive1b.tests/thread_msg_bus:Board supported: True
INFO:hifive1b.tests/thread_msg_bus:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_bus:Application has test: True
INFO:hifive1b.tests/thread_msg_bus:Run compilation
INFO:hifive1b.tests/thread_msg_bus:Run test
INFO:hifive1b.tests/thread_msg_bus:Run test.flash
WARNING:hifive1b.tests/thread_msg_bus:make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/thread_msg_bus test
r
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Bench Clock Reset Complete

ATE0-->ATE0
OK
AT+BLEINIT=0-->OK
AT+CWMODE=0-->OK

Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)
THREAD 1 start
Timeout in expect script at "child.expect_exact('THREAD 2 start')" (tests/thread_msg_bus/tests/01-run.py:9)

make: *** [/work/riot/RIOT/tests/thread_msg_bus/../../Makefile.include:792: test] Error 1

Return value: 2

ERROR:hifive1b.tests/thread_msg_bus:Error during test, writing to results/hifive1b/tests/thread_msg_bus/test.failed
ERROR:hifive1b.tests/thread_msg_bus:Failed during: test
INFO:hifive1b.tests/thread_msg_seq:Board supported: True
INFO:hifive1b.tests/thread_msg_seq:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_seq:Application has test: True
INFO:hifive1b.tests/thread_msg_seq:Run compilation
INFO:hifive1b.tests/thread_msg_seq:Run test
INFO:hifive1b.tests/thread_msg_seq:Run test.flash
INFO:hifive1b.tests/thread_msg_seq:Success
INFO:hifive1b.tests/thread_priority_inversion:Board supported: True
INFO:hifive1b.tests/thread_priority_inversion:Board has enough memory: True
INFO:hifive1b.tests/thread_priority_inversion:Application has test: False
INFO:hifive1b.tests/thread_priority_inversion:Run compilation
INFO:hifive1b.tests/thread_priority_inversion:Success
INFO:hifive1b.tests/thread_race:Board supported: True
INFO:hifive1b.tests/thread_race:Board has enough memory: True
INFO:hifive1b.tests/thread_race:Application has test: True
INFO:hifive1b.tests/thread_race:Run compilation
INFO:hifive1b.tests/thread_race:Run test
INFO:hifive1b.tests/thread_race:Run test.flash
INFO:hifive1b.tests/thread_race:Success
INFO:hifive1b.tests/thread_zombie:Board supported: True
INFO:hifive1b.tests/thread_zombie:Board has enough memory: True
INFO:hifive1b.tests/thread_zombie:Application has test: True
INFO:hifive1b.tests/thread_zombie:Run compilation
INFO:hifive1b.tests/thread_zombie:Run test
INFO:hifive1b.tests/thread_zombie:Run test.flash
INFO:hifive1b.tests/thread_zombie:Success
ERROR:hifive1b:Tests failed: 2
Failures during test:
- [tests/pthread_condition_variable](tests/pthread_condition_variable/test.failed)
- [tests/thread_msg_bus](tests/thread_msg_bus/test.failed)
```

</details>

<details><summary>master:</summary>

```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . hifive1b --jobs=4 --applications="tests/thread* tests/pthread* tests/cpp11_thread tests/cpp11_mutex"
INFO:hifive1b:Saving toolchain
INFO:hifive1b.tests/cpp11_mutex:Board supported: True
INFO:hifive1b.tests/cpp11_mutex:Board has enough memory: True
INFO:hifive1b.tests/cpp11_mutex:Application has test: True
INFO:hifive1b.tests/cpp11_mutex:Run compilation
INFO:hifive1b.tests/cpp11_mutex:Run test
INFO:hifive1b.tests/cpp11_mutex:Run test.flash
WARNING:hifive1b.tests/cpp11_mutex:make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/cpp11_mutex test
r
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line 
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Bench Clock Reset Complete

ATE0-->ATE0
OK
AT+BLEINIT=0-->OK
AT+CWMODE=0-->OK

Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)

************ C++ mutex test ***********
Lock and unlock ... 
tests/cpp11_mutex/main.cpp:65 => failed condition
*** RIOT kernel panic:
CONDITION FAILED.

*** halted.

Timeout in expect script at "child.expect_exact("Done")" (tests/cpp11_mutex/tests/01-run.py:17)

make: *** [/work/riot/RIOT/tests/cpp11_mutex/../../Makefile.include:792: test] Error 1

Return value: 2

ERROR:hifive1b.tests/cpp11_mutex:Error during test, writing to results/hifive1b/tests/cpp11_mutex/test.failed
ERROR:hifive1b.tests/cpp11_mutex:Failed during: test
INFO:hifive1b.tests/cpp11_thread:Board supported: True
INFO:hifive1b.tests/cpp11_thread:Board has enough memory: True
INFO:hifive1b.tests/cpp11_thread:Application has test: True
INFO:hifive1b.tests/cpp11_thread:Run compilation
INFO:hifive1b.tests/cpp11_thread:Run test
INFO:hifive1b.tests/cpp11_thread:Run test.flash
INFO:hifive1b.tests/cpp11_thread:Success
INFO:hifive1b.tests/pthread:Board supported: True
INFO:hifive1b.tests/pthread:Board has enough memory: True
INFO:hifive1b.tests/pthread:Application has test: True
INFO:hifive1b.tests/pthread:Run compilation
INFO:hifive1b.tests/pthread:Run test
INFO:hifive1b.tests/pthread:Run test.flash
INFO:hifive1b.tests/pthread:Success
INFO:hifive1b.tests/pthread_barrier:Board supported: True
INFO:hifive1b.tests/pthread_barrier:Board has enough memory: True
INFO:hifive1b.tests/pthread_barrier:Application has test: True
INFO:hifive1b.tests/pthread_barrier:Run compilation
INFO:hifive1b.tests/pthread_barrier:Run test
INFO:hifive1b.tests/pthread_barrier:Run test.flash
INFO:hifive1b.tests/pthread_barrier:Success
INFO:hifive1b.tests/pthread_cleanup:Board supported: True
INFO:hifive1b.tests/pthread_cleanup:Board has enough memory: True
INFO:hifive1b.tests/pthread_cleanup:Application has test: True
INFO:hifive1b.tests/pthread_cleanup:Run compilation
INFO:hifive1b.tests/pthread_cleanup:Run test
INFO:hifive1b.tests/pthread_cleanup:Run test.flash
INFO:hifive1b.tests/pthread_cleanup:Success
INFO:hifive1b.tests/pthread_condition_variable:Board supported: True
INFO:hifive1b.tests/pthread_condition_variable:Board has enough memory: True
INFO:hifive1b.tests/pthread_condition_variable:Application has test: True
INFO:hifive1b.tests/pthread_condition_variable:Run compilation
INFO:hifive1b.tests/pthread_condition_variable:Run test
INFO:hifive1b.tests/pthread_condition_variable:Run test.flash
INFO:hifive1b.tests/pthread_condition_variable:Success
INFO:hifive1b.tests/pthread_cooperation:Board supported: True
INFO:hifive1b.tests/pthread_cooperation:Board has enough memory: False
INFO:hifive1b.tests/pthread_flood:Board supported: True
INFO:hifive1b.tests/pthread_flood:Board has enough memory: True
INFO:hifive1b.tests/pthread_flood:Application has test: True
INFO:hifive1b.tests/pthread_flood:Run compilation
INFO:hifive1b.tests/pthread_flood:Run test
INFO:hifive1b.tests/pthread_flood:Run test.flash
INFO:hifive1b.tests/pthread_flood:Success
INFO:hifive1b.tests/pthread_rwlock:Board supported: True
INFO:hifive1b.tests/pthread_rwlock:Board has enough memory: True
INFO:hifive1b.tests/pthread_rwlock:Application has test: True
INFO:hifive1b.tests/pthread_rwlock:Run compilation
INFO:hifive1b.tests/pthread_rwlock:Run test
INFO:hifive1b.tests/pthread_rwlock:Run test.flash
INFO:hifive1b.tests/pthread_rwlock:Success
INFO:hifive1b.tests/pthread_tls:Board supported: True
INFO:hifive1b.tests/pthread_tls:Board has enough memory: True
INFO:hifive1b.tests/pthread_tls:Application has test: True
INFO:hifive1b.tests/pthread_tls:Run compilation
INFO:hifive1b.tests/pthread_tls:Run test
INFO:hifive1b.tests/pthread_tls:Run test.flash
INFO:hifive1b.tests/pthread_tls:Success
INFO:hifive1b.tests/thread_basic:Board supported: True
INFO:hifive1b.tests/thread_basic:Board has enough memory: True
INFO:hifive1b.tests/thread_basic:Application has test: True
INFO:hifive1b.tests/thread_basic:Run compilation
INFO:hifive1b.tests/thread_basic:Run test
INFO:hifive1b.tests/thread_basic:Run test.flash
INFO:hifive1b.tests/thread_basic:Success
INFO:hifive1b.tests/thread_cooperation:Board supported: True
INFO:hifive1b.tests/thread_cooperation:Board has enough memory: True
INFO:hifive1b.tests/thread_cooperation:Application has test: True
INFO:hifive1b.tests/thread_cooperation:Run compilation
INFO:hifive1b.tests/thread_cooperation:Run test
INFO:hifive1b.tests/thread_cooperation:Run test.flash
INFO:hifive1b.tests/thread_cooperation:Success
INFO:hifive1b.tests/thread_exit:Board supported: True
INFO:hifive1b.tests/thread_exit:Board has enough memory: True
INFO:hifive1b.tests/thread_exit:Application has test: True
INFO:hifive1b.tests/thread_exit:Run compilation
INFO:hifive1b.tests/thread_exit:Run test
INFO:hifive1b.tests/thread_exit:Run test.flash
INFO:hifive1b.tests/thread_exit:Success
INFO:hifive1b.tests/thread_flags:Board supported: True
INFO:hifive1b.tests/thread_flags:Board has enough memory: True
INFO:hifive1b.tests/thread_flags:Application has test: True
INFO:hifive1b.tests/thread_flags:Run compilation
INFO:hifive1b.tests/thread_flags:Run test
INFO:hifive1b.tests/thread_flags:Run test.flash
INFO:hifive1b.tests/thread_flags:Success
INFO:hifive1b.tests/thread_flags_xtimer:Board supported: True
INFO:hifive1b.tests/thread_flags_xtimer:Board has enough memory: True
INFO:hifive1b.tests/thread_flags_xtimer:Application has test: True
INFO:hifive1b.tests/thread_flags_xtimer:Run compilation
INFO:hifive1b.tests/thread_flags_xtimer:Run test
INFO:hifive1b.tests/thread_flags_xtimer:Run test.flash
INFO:hifive1b.tests/thread_flags_xtimer:Success
INFO:hifive1b.tests/thread_float:Board supported: True
INFO:hifive1b.tests/thread_float:Board has enough memory: True
INFO:hifive1b.tests/thread_float:Application has test: False
INFO:hifive1b.tests/thread_float:Run compilation
INFO:hifive1b.tests/thread_float:Success
INFO:hifive1b.tests/thread_flood:Board supported: True
INFO:hifive1b.tests/thread_flood:Board has enough memory: True
INFO:hifive1b.tests/thread_flood:Application has test: True
INFO:hifive1b.tests/thread_flood:Run compilation
INFO:hifive1b.tests/thread_flood:Run test
INFO:hifive1b.tests/thread_flood:Run test.flash
INFO:hifive1b.tests/thread_flood:Success
INFO:hifive1b.tests/thread_msg:Board supported: True
INFO:hifive1b.tests/thread_msg:Board has enough memory: True
INFO:hifive1b.tests/thread_msg:Application has test: True
INFO:hifive1b.tests/thread_msg:Run compilation
INFO:hifive1b.tests/thread_msg:Run test
INFO:hifive1b.tests/thread_msg:Run test.flash
INFO:hifive1b.tests/thread_msg:Success
INFO:hifive1b.tests/thread_msg_block_race:Board supported: True
INFO:hifive1b.tests/thread_msg_block_race:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_race:Application has test: True
INFO:hifive1b.tests/thread_msg_block_race:Run compilation
INFO:hifive1b.tests/thread_msg_block_race:Run test
INFO:hifive1b.tests/thread_msg_block_race:Run test.flash
INFO:hifive1b.tests/thread_msg_block_race:Success
INFO:hifive1b.tests/thread_msg_block_w_queue:Board supported: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Application has test: True
INFO:hifive1b.tests/thread_msg_block_w_queue:Run compilation
INFO:hifive1b.tests/thread_msg_block_w_queue:Run test
INFO:hifive1b.tests/thread_msg_block_w_queue:Run test.flash
INFO:hifive1b.tests/thread_msg_block_w_queue:Success
INFO:hifive1b.tests/thread_msg_block_wo_queue:Board supported: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Application has test: True
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run compilation
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run test
INFO:hifive1b.tests/thread_msg_block_wo_queue:Run test.flash
INFO:hifive1b.tests/thread_msg_block_wo_queue:Success
INFO:hifive1b.tests/thread_msg_bus:Board supported: True
INFO:hifive1b.tests/thread_msg_bus:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_bus:Application has test: True
INFO:hifive1b.tests/thread_msg_bus:Run compilation
INFO:hifive1b.tests/thread_msg_bus:Run test
INFO:hifive1b.tests/thread_msg_bus:Run test.flash
INFO:hifive1b.tests/thread_msg_bus:Success
INFO:hifive1b.tests/thread_msg_seq:Board supported: True
INFO:hifive1b.tests/thread_msg_seq:Board has enough memory: True
INFO:hifive1b.tests/thread_msg_seq:Application has test: True
INFO:hifive1b.tests/thread_msg_seq:Run compilation
INFO:hifive1b.tests/thread_msg_seq:Run test
INFO:hifive1b.tests/thread_msg_seq:Run test.flash
INFO:hifive1b.tests/thread_msg_seq:Success
INFO:hifive1b.tests/thread_priority_inversion:Board supported: True
INFO:hifive1b.tests/thread_priority_inversion:Board has enough memory: True
INFO:hifive1b.tests/thread_priority_inversion:Application has test: False
INFO:hifive1b.tests/thread_priority_inversion:Run compilation
INFO:hifive1b.tests/thread_priority_inversion:Success
INFO:hifive1b.tests/thread_race:Board supported: True
INFO:hifive1b.tests/thread_race:Board has enough memory: True
INFO:hifive1b.tests/thread_race:Application has test: True
INFO:hifive1b.tests/thread_race:Run compilation
INFO:hifive1b.tests/thread_race:Run test
INFO:hifive1b.tests/thread_race:Run test.flash
INFO:hifive1b.tests/thread_race:Success
INFO:hifive1b.tests/thread_zombie:Board supported: True
INFO:hifive1b.tests/thread_zombie:Board has enough memory: True
INFO:hifive1b.tests/thread_zombie:Application has test: True
INFO:hifive1b.tests/thread_zombie:Run compilation
INFO:hifive1b.tests/thread_zombie:Run test
INFO:hifive1b.tests/thread_zombie:Run test.flash
INFO:hifive1b.tests/thread_zombie:Success
ERROR:hifive1b:Tests failed: 1
Failures during test:
- [tests/cpp11_mutex](tests/cpp11_mutex/test.failed)
```

</details>

For `tests/pthread_condition_variable`, it works well when running it alone. So there's one which is fixed by this PR (`tests/cpp11_mutex`) and a new one which is failing `tests/thread_msg_bus`.

Regarding performances, I got this:

| test  | master | this PR |
| ------ | ---------| ----------|
| bench_mutex_ping_pong | `{ "result" : 540966, "ticks" : 591 }` | `{ "result" : 544194, "ticks" : 588 }` |
| bench_sched_nop | `{ "result" : 1441331, "ticks" : 222 }` | `{ "result" : 1729639, "ticks" : 185 }` |
| bench_thread_yield_pingpong | `{ "result" : 655698, "ticks" : 488 }` | `{ "result" : 688131, "ticks" : 465 }` |

So this confirms your results.

**Comment by bergzand** [comment]
Thanks for testing! 

I can't reproduce the failure with `tests/pthread_condition_variable`, as you mention, it works fine when running alone.
`tests/thread_msg_bus` also works fine here.

**Comment by bergzand** [comment]
Merged #14876 into this PR after offline request from @aabadie 

22a44cb is a small optimization to the RISC-V trap handler. By splitting
the call to sched_run from the trap_handle call, loading the previous
thread ptr can be delayed until after it is determined that a schedule
run is required. This shaves of a few cycles during regular interrupts
that do not trigger the scheduler.

This should have at most a very minimal impact on scheduling performance, but does remove a memory load operation during a regular interrupt that doesn't trigger the scheduler.

**Comment by aabadie** [comment]
Please squash!

**Comment by bergzand** [comment]
Squashed!

**Review by aabadie — APPROVED** [review]
ACK !

**Comment by bergzand** [comment]
Awesome, thanks for reviewing!

**Comment by aabadie** [comment]
While testing #14887 I noticed that `tests/thread_flags` is now broken on master and bisecting points to 4289b09a33deaf914a2edd580784d8b5fbf5f0ef.

**Comment by aabadie** [comment]
Apparently it's because `xtimer_set_timeout_flag64` triggers a little too early (less than 100ms) and the Python script expect 6 digits in the measured elapsed time.

**Pull request merged**
