### PR TITLE
pkg: add minmea NMEA parsing library

### PR DESCRIPTION
**Pull request by kaspar030**
"Minmea is a minimalistic GPS parser library written in pure C intended for
resource-constrained platforms, especially microcontrollers and other embedded
systems."

See https://github.com/cloudyourcar/minmea for more information.

### CODE REVIEW

**Comment by kaspar030** [comment]
I've added a compile fix for <32bit platforms and changed the pkg to point to my fork containing the fix (PR'ed upstream [here](https://github.com/cloudyourcar/minmea/pull/23)).

**Comment by kaspar030** [comment]
- blacklisted msp430 boards
- squashed

@vincent-d does your ACK hold?

**Comment by vincent-d** [comment]
Re-ACK

**Comment by vincent-d** [comment]
And go

**Pull request merged**
