### PR TITLE
trickle: correctly reset t [2017.10 backport]

### PR DESCRIPTION
**Pull request by cgundogan**
backport of #7870

### CODE REVIEW

**Comment by cgundogan** [comment]
@smlng please try to reproduce the error as described in the original PR

**Comment by miri64** [comment]
> @smlng please try to reproduce the error as described in the original PR

What are you talking about?

**Comment by cgundogan** [comment]
@miri64 let's give someone a chance to at least try

**Comment by miri64** [comment]
> @miri64 let's give someone a chance to at least try

If the PR to master was broken it needs to be fixed.

**Comment by cgundogan** [comment]
>If the PR to master was broken it needs to be fixed.

I don't understand. This commit is cherry-picked from master.

**Comment by miri64** [comment]
> I don't understand. This commit is cherry-picked from master.

Your comment made it sound that the original PR wasn't working.

**Pull request merged**
