### PR TITLE
gnrc_netif: remove deprecated CONFIG_GNRC_NETIF_LORAWAN_NETIF_HDR

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Deprecated since forever and was slated for removal after 2021.10. So let's do it now! As a consequence, I deprecated the now unused (at least in our codebase) `GNRC_NETTYPE_LORAWAN` and aliased it with `GNRC_NETTYPE_UNDEF` (and removed the dependency from `gnrc_lorawan`).

### Testing procedure
Everything should still compile as before (in fact, the binary should even look the same, but did not confirm that).

### CODE REVIEW

**Review by Teufelchen1 — APPROVED** [review]
Trusting Miri... a lot. :smirk:

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
And rebased.

**Comment by miri64** [comment]
And another rebase...

**Pull request merged**
