### PR TITLE
boards/slwstk6220a: add support (via efm32)

### PR DESCRIPTION
**Pull request by basilfx**
### Contribution description
This adds the new version of the SLWSTK6220A board that is based on the existing EFM32 implementation. It provides more peripherals. The radio driver is not supported (yet).

### Testing procedure
Unfortunately, I don't own this board. I think @haukepetersen had access to this board. GPIO, UART and Timer are implemented based on the pin mapping of the old implementation (#10685), but other peripherals are now available as well. I've mapped the other peripherals based on the [user manual](https://www.silabs.com/documents/public/user-guides/ug200-brd4502c-user-guide.pdf).

### Issues/PRs references
~~Depends on #10685, since the commits to 'remove' the old version of this board is included as well.~~

### CODE REVIEW

**Comment by benpicco** [comment]
Murdock is not yet happy.

did you use EFM2RIOT for this? I have a EFR32MG1B board, still curious if that will just work with the current RIOT if you update that script :)

**Comment by basilfx** [comment]
> Murdock is not yet happy.

Will fix that soon.

> did you use EFM2RIOT for this? I have a EFR32MG1B board, still curious if that will just work with the current RIOT if you update that script :)

I did. I've been updating it last weekend to make it more maintainable. Will update the repository soon.

**Comment by basilfx** [comment]
Two tests are failing because of a duplicate definition of `AES_COUNT`. This define is defined by the EFM32 vendor files, but also clashes with a similar definition by `pkg/cryptoauthlib`.

I'm not sure how to fix this..

**Comment by benpicco** [comment]
I mean you could just blacklist efm32, but I have another (slightly hacky) solution:

```patch
diff --git a/cpu/efm32/include/cpu_conf.h b/cpu/efm32/include/cpu_conf.h
index e6427b0d82..cdff65125c 100644
--- a/cpu/efm32/include/cpu_conf.h
+++ b/cpu/efm32/include/cpu_conf.h
@@ -24,6 +24,12 @@
 
 #include "em_device.h"
 
+/* avoid namespace conflict */
+#ifdef AES_COUNT
+#define EFM32_AES_COUNT AES_COUNT
+#undef AES_COUNT
+#endif
+
 #ifdef __cplusplus
 extern "C" {
 #endif
diff --git a/cpu/efm32/include/periph_cpu.h b/cpu/efm32/include/periph_cpu.h
index 864a61e5e2..47269c07d2 100644
--- a/cpu/efm32/include/periph_cpu.h
+++ b/cpu/efm32/include/periph_cpu.h
@@ -27,7 +27,6 @@
 
 #include "em_adc.h"
 #include "em_cmu.h"
-#include "em_device.h"
 #include "em_gpio.h"
 #include "em_timer.h"
 #include "em_usart.h"
diff --git a/pkg/cryptoauthlib/include/cryptoauthlib_test.h b/pkg/cryptoauthlib/include/cryptoauthlib_test.h
index 8a66d58091..899a42ec6c 100644
--- a/pkg/cryptoauthlib/include/cryptoauthlib_test.h
+++ b/pkg/cryptoauthlib/include/cryptoauthlib_test.h
@@ -23,9 +23,9 @@
 extern "C" {
 #endif
 
-#include "cryptoauthlib.h"
 #include "atca.h"
 #include "atca_params.h"
+#include "cryptoauthlib.h"
 
 /**
  * @brief   Helper function to use the library's unittests
```

**Comment by basilfx** [comment]
I chose the first option to blacklist EFM32 for the package. After some investigation, it seems that the `cryptoauthlib` package uses a one-header-for-all-includes approach, which is hard to fix without patching. 

I was hoping that I only had to blacklist certain CPU families (`cpu_ezr32wg`), but that doesn't work. So I had blacklist all of them (`arch_efm32`).

**Review by benpicco — APPROVED** [review]
Looking good.
CPU support is based on generated code, so I don't expect any surprises here.

Board is re-added and replaces the previous, unorthodox port.

Thank you for adding yourself to CODEOWNERS!

**Pull request merged**
