### PR TITLE
core: cib: fix overflow handling

### LINKED ISSUE #8117: Message Queue (cib) breaks on write counter overflow
After running for ~4days a thread reproducibly keeps loosing messages sent from an interrupt handler ('msg_send_int') and from itself.
When debugging I noticed, that a message comes through when the target thread was waiting in 'msg_receive' (state 'STATUS_RECEIVE_BLOCKED'). However, when it was to be queued (e.g. because the thread was already active) it gets lost.

Digging deeper I found that the "Circular integer buffer interface" (core/include/cib.h) which is used by the message queue does not handle integer overflows correctly. Write and read counters are incremented but never decremented or reset to 0. So it is just a matter of time until they overflow.
The overflow itself is not a problem if handled correctly, like in 'cib_avail'. However 'cib_get' and 'cib_peek' are using a simple "greater then"-comparison instead of calling 'cib_avail', so the buffer breaks when 'write_count' overflows:

1. Consider the following state for cib_t (buffer is empty, size = 4):
read_count = 0xFFFFFFFF
write_count=0xFFFFFFFF
mask = 0x00000003

2. Call 'cib_put'
-> returns write index: 0x00000003 (now 'write_count' overflows to 0)

3. Call 'cib_get'
-> returns read index: -1 (expected: 0x00000003)
Now the buffer is broken :(

Suggested fix:
Replace 
`if (cib->write_count > cib->read_count) {`
with
`if (cib_avail(cib)) {`
in both 'cib_get' and 'cib_peek'.

### PR DESCRIPTION
**Pull request by kaspar030**
```cib_get()``` and ```cib_peek()``` did not handle overflows correctly.

Fixes #8117.

### CODE REVIEW

**Comment by miri64** [comment]
(untested, but code looks sane and passes unittests, btw ;-))

**Comment by kaspar030** [comment]
> (untested, but code looks sane and passes unittests, btw ;-))

So did #5298. ;-)

The proper way would be to add this case to the unittests. But I don't have the time.

**Comment by bergzand** [comment]
@kaspar030 note #8120 :)

**Comment by miri64** [comment]
Or https://github.com/kaspar030/RIOT/pull/31 ;-)

**Comment by bergzand** [comment]
I must admit that @miri64's PR is a bit more thorough in the testing. :)

Anyway, tested, problem exists and is fixed with this PR, so have an ACK.

**Comment by kaspar030** [comment]
#8120 doesn't use UINT_MAX, thus in order to save us more work, I've merged @miri64's unittest update. @bergzand Thanks for yours anyways!!

I think this needs a re-ACK...

**Comment by kaspar030** [comment]
Ok. @bergzand ACK'ed my PR. I hereby ACK @miri64's unittest changes. Thus everything has been reviewed & ACKed -> go.

**Pull request merged**
