### PR TITLE
doc/doxygen: remove support for lesscpy

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

lessc (node-less) and lesscpy do not produce the same output.
There are some minor whitespace +-1 in color values which
are not important but the output file is not stable

However lesscpy removes comments and so the license of the output file
As it produces an invalid file it support is dropped.

https://lesscpy.readthedocs.io/en/latest/#differences-from-less-js

Apparently when it was added by https://github.com/RIOT-OS/RIOT/pull/7607 the output was not checked.

### Alternative solution

~Decide we do not care about the license header in `riot.css` and only use `lesscpy` instead of `node-less`.~
Not a valid alternative https://github.com/RIOT-OS/RIOT/pull/11037#issuecomment-465552480

### Testing procedure

I used this diff to show the command being executed:

```
diff --git a/doc/doxygen/Makefile b/doc/doxygen/Makefile
index 300739358..293daf17b 100644
--- a/doc/doxygen/Makefile
+++ b/doc/doxygen/Makefile
@@ -22,7 +22,7 @@ man: src/changelog.md

 ifneq (,$(LESSC))
 src/css/riot.css: src/css/riot.less src/css/variables.less
-       @$(LESSC) $< $@
+       $(LESSC) $< $@

 src/css/variables.less: src/config.json
        @grep "^\s*\"@" $< | sed -e 's/^\s*"//g' -e 's/":\s*"/: /g' \
```

With `node-less` installed and touching `riot.less` the file is rebuilt:
See the `/usr/bin/lessc src/css/riot.less src/css/riot.css` line:

```
touch doc/doxygen/src/css/riot.less

make doc
"make" -BC doc/doxygen
make[1]: Entering directory '/home/harter/work/git/RIOT/doc/doxygen'
/usr/bin/lessc src/css/riot.less src/css/riot.css
( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
*make[1]: Leaving directory '/home/harter/work/git/RIOT/doc/doxygen'
```

If `LESSC` is empty it is not:

```
touch doc/doxygen/src/css/riot.less

LESSC= make doc
"make" -BC doc/doxygen
make[1]: Entering directory '/home/harter/work/git/RIOT/doc/doxygen'
( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
*make[1]: Leaving directory '/home/harter/work/git/RIOT/doc/doxygen'
```

And if `node-less` is not installed it is not rebuild

```
command -v lessc

touch doc/doxygen/src/css/riot.less

make doc
"make" -BC doc/doxygen
make[1]: Entering directory '/home/harter/work/git/RIOT/doc/doxygen'
( cat riot.doxyfile ; echo "GENERATE_HTML = yes" ) | doxygen -
*make[1]: Leaving directory '/home/harter/work/git/RIOT/doc/doxygen'
```

### Issues/PRs references

The file was always being modified and said different from the version of the repository when doing `make doc` with only `lesscpy` installed.

I mentioned the issue with the comments being removed in https://github.com/RIOT-OS/RIOT/pull/10249#issuecomment-462417175

### CODE REVIEW

**Comment by cladmi** [comment]
@miri64 as you added the `riot.css` file in the first place, I think you may have an opinion about caring about the license header here or not.

**Comment by miri64** [comment]
`lesscpy` w was introduced by @gebart in d01d91d3, so I'd like to have his opinion on this as well. 

> @miri64 as you added the `riot.css` file in the first place, I think you may have an opinion about caring about the license header here or not.

If lesscpy is the one removing the license header and lesscpy is the one removed here I don't really understand that comment... However, I don't really care about that header in the generated result, as long as it stays in in the upstream repo.

**Comment by cladmi** [comment]
> If lesscpy is the one removing the license header and lesscpy is the one removed here I don't really understand that comment... However, I don't really care about that header in the generated result, as long as it stays in in the upstream repo.

Sorry for not being precise, I was asking about having the alternative solution and use `lesscpy` to generate a file without header by default.

If the tool is generating a file without header, it would mean keeping the file without header in the repository as the generated file is tracked. Otherwise you end up in a state where you cannot generate it anymore.

The generated file is here https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/src/css/riot.css and the source file has `riot.css` in the description: https://github.com/RIOT-OS/RIOT/blob/1335bf60fe7001376b09321d684018e39bcfd174/doc/doxygen/src/css/riot.less#L1-L6

**Comment by miri64** [comment]
Since the generated file is the one exposed on the website, I'd prefer to keep in the copyright header.

**Comment by cladmi** [comment]
> Since the generated file is the one exposed on the website, I'd prefer to keep in the copyright header.

Ok that what I was thinking, but prefered to ask. I strike the alternative then.

**Comment by cladmi** [comment]
`less` is not `lessc` :) 

None of `lessc` and `lesscpy` is currently installed in `riotdocker` image.

I re-updated the image just to be sure:

```
sudo docker run -i --rm riot/riotbuild   lessc --help
/run.sh: line 16: lessc: command not found
sudo docker run -i --rm riot/riotbuild   lesscpy --help
/run.sh: line 16: lesscpy: command not found
```

**Comment by miri64** [comment]
> `less` is not `lessc` :)

Yes... `less` is a terminal pager tool. `lessc` is a LESS compiler, with LESS being a pre-processable style sheet language that can be compiled to CSS ;-).

**Pull request merged**
