### PR TITLE
static-tests: disable cppcheck

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

cppcheck produces too many false positives to be useful.
This is likely due to a configuration error (not all header files are included?) but until this is sorted out, disable the tool as it currently does more harm than good.

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by kaspar030** [comment]
my first automerge :)

**Comment by miri64** [comment]
So, now we only have GCC as binding syntax check left? Because I remember, that LLVM checks were disabled with a similar reasoning ;-). We could have at least kept `cppcheck` as warnings...

**Comment by maribu** [comment]
> So, now we only have GCC as binding syntax check left?

Note that `cppcheck` does not perform syntax checks. In fact, `cppcheck` will happily accept syntactically incorrect C files. It does only performs style checks that rule out a given set of anti-patterns.

The reason to disable `cppcheck` is that in the current version and/or without the proper include paths it just caused more harm than benefit. I agree that we should try to update `cppcheck` and enhance the CI integration to provide the proper include paths. But until that is done, it is a poor tool that provides no benefit.

**Comment by miri64** [comment]
> I agree that we should try to update `cppcheck` and enhance the CI integration to provide the proper include paths. But until that is done, it is a poor tool that provides no benefit.

My fear is just that, just as with the LLVM checks, now this is disabled, nobody really cares to work on fixing the config, meaning it will basically be deactivated for years, until hopefully somebody has the time and remembers "oh right, we used to have those checks, and they need fixing". And at that point the state of the code will probably be far away from what `cppcheck` will recognize an error-free code, meaning even more work, making it even less attractive to work on that.

**Comment by benpicco** [comment]
That's still better than getting used to ignoring warnings because they are almost always false positives.

**Comment by miri64** [comment]
Not sure what is better when it comes to those two choices *looks at vera++*, but IMHO it is always better to try to at least fix the problem before ignoring it ;-).

**Pull request merged**
