### PR TITLE
sixlowpan: move non-GNRC stuff to its own module

### PR DESCRIPTION
**Pull request by authmillenon**
Based on #3613 for easier rebasing.

This again wasn't possible with just a simple tool. This PR moves all dispatch definitions and helper function to set or test dispatches to `net/sixlowpan.h`.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current #3613 and master.

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by OlegHahm** [comment]
ACK as soon as Travis is green.

**Pull request merged**
