### PR TITLE
pkg/semtech-loramac: fix deadlock when sending unconfirmed messages

### LINKED ISSUE #11530: pkg/semtech_loramac: deadlock with UNCONFIRMED messages
#### Description

If you are unlucky, `semtech_loramac` package can produce a deadlock when you send `UNCONFIRMED` messages from a thread that doesn't have a message queue.

The simplest way to show why is to explain how `semtech_loramac` package is connected to **LoRaMAC-node** library. This library has 3 interfaces: **MLME**, **MCPS** and **MIB**. When you send an application uplink you use the **MCPS** interface. This interface is asynchronous and can trigger two events: `Confirm` and `Indication`.

LoRMAC architecture

When you send an uplink you first call `semtech_loramac_send` and then `semtech_loramac_recv` to wait for the transmission to finish. Currently `semtech_loramac` handle the two **LoRaMAC-node** events as following:

* when an `UNCONFIRMED` message is sent, `semtech_loramac_recv` returns on `Confirm` event.

* when a `CONFIRMED` message is sent, `Confirm` event [is ignored][confirm-ignored]. As we expect an Ack from the LoRa server, `semtech_loramac_recv` will return on `Indication` event (when this Ack is received). Waiting for `Indication` event allows also to retrieve data from downlinks.

Function `semtech_loramac_recv` is waiting using the message module on the caller thread. When `Confirm` / `Indication` event is received, loramac event loop sends a `MSG_TYPE_LORAMAC_TX_STATUS` message to the caller thread, so it can returns from `semtech_loramac_recv`. If this thread doesn't have a message queue, sending the message blocks the event loops until the caller thread receives the message.

The problem is that when you transmit an `UNCONFIRMED` message you are also waiting for the 2 RX windows. If the LoRa server is sending a downlink to the device, `Indication` event will be fired but loramac event loop has already sent `MSG_TYPE_LORAMAC_TX_STATUS` on `Confirm` event. It will send another `MSG_TYPE_LORAMAC_TX_STATUS` that will block the event loop forever because the caller thread is out of `semtech_loramac_recv`. Even worse, if now the caller thread calls `semtech_loramac_send`, a deadlock occurs.

With the current architecture of `semtech_loramac` package, it is quite difficult to fix this issue. The simplest way would be to ignore `Indication` event when an `UNCONFIRMED` message was sent, but data from downlink messages would be lost.

#### Steps to reproduce the issue

Send an `UNCONFIRMED` message from a thread that doesn't have an message queue to a LoRa server that have a downlink message to transmit to the end device.  
In fact if you are lucky LoRa server can send a downlink by itself if it has MAC parameters to transmit to end device (for example `NewChannelReq`).

The image below describes what happened when a downlink is received after an `UNCONFIRMED` uplink.

Deadlock

The code that was used to produce this example is the following:

```c
loramac.cnf = LORAMAC_TX_UNCNF;
uint8_t ret = semtech_loramac_send(&loramac, (uint8_t *)message, strlen(message));

ret = semtech_loramac_recv(&loramac);
printf("Received: %d\n", ret);

xtimer_sleep(10);
printf("Send second message\n");
ret = semtech_loramac_send(&loramac, (uint8_t *)message, strlen(message));
```

[confirm-ignored]: https://github.com/RIOT-OS/RIOT/blob/master/pkg/semtech-loramac/contrib/semtech_loramac.c#L165

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is attempt to fix #11530. Even if the problem was well explained in #11530, I had a hard time figuring out what was going on with the messages exchanged between the MAC and the caller thread in the loramac adaption code. I end up to the conclusion that one TX done message should'nt be sent from the mcps_confirm event callback, as it was received by the semtech-loramac_recv function. And in the case of data effectively received, the RX message was blocking the event loop. On the next send, calling the send function in the mac, which is using a msg_send_receive, was causing the deadlock.

The proposed solution in this PR is to use a background timer to send a TX done message to the MAC thread after an amount time enough to ensure received data are processed in `semtech-loramac_recv`. This message, is not sent anymore from the mcps_confirm event. The RX message is then correctly retrieved by the caller thread. And no deadlock on future sends.
For me, it's working quite reliably now with this.

I tried other solutions, like setting a message queue to the caller thread but I found this was a workaround not really fixing the original issue.

Maybe there's a better fix that I didn't think of, suggestions are welcome.

@ParksProjets would you like to have a look ang give some feedback ?

### Testing procedure

Repeat the procedure described in #11530, the deadlock doesn't occur anymore with this PR

### Issues/PRs references

fixes #11530

### CODE REVIEW

**Comment by jia200x** [comment]
Thanks for tackling this.

> I tried other solutions, like setting a message queue to the caller thread but I found this was a workaround not really fixing the original issue.

Why? 
Strictly speaking the TX Done status should be reported by the Confirm primitive and any kind of data reception by Indication (although the pkg seems to call Indication even for ACKs...). I think it would simplify a lot the implementation if we use the messages as signals instead of a synchronization between the caller and MAC.

Also, "Indication right after Confirm" is only valid for class A, so we would need a message queue anyway for class B and class C.

What do you think about:
- Sending a message with the packet to the caller in case of an Indication with data (same principle as GNRC's `_pass_on_pkt`)
- Decide if we send an extra message with TX status. In most cases this is handled internally by the MAC (increment tx_failed counter), but I'm aware most LoRaWAN applications directly interact with the MAC.

This way we could also send other information to the caller (Link Check, etc) and the caller can't block or de-synchronize the MAC layer.
What do you think?

**Comment by ParksProjets** [comment]
One way you could do it is to read `McpsInd` flag from `LoRaMacFlags` variable (which [strangely is not static][loraflags]). This flag indicates that an `Indication` event will be trigger soon.

But in fact, the real problem is to use `Indication` event for confirming an uplink. I found some other potential bugs that can occur by doing so.

For example a single message (even `CONFIRMED`) we sent can produce two data responses if the LoRa server has two downlinks to make. It will send it a first downlink containing the first message data, an Ack and `FramePending` set to `true`. The `semtech_loramac` package will automatically make a second uplink (because of `FramePending`) and the LoRa server will send its second downlink. As `semtech_loramac_recv` now only returns when this second message is received, data from the first downlink will be lost.

Also, I noticed in LoRaMAC-node source code that there is a case where `Indication` [event is not called][ind-skip] (even with `CONFIRMED` message). It happens when the LoRa server send again a `CONFIRMED` downlink because it didn't received an Ack from the device. In that case, the application will be stuck forever on `semtech_loramac_recv`.

One way to solve all of these problems is to use `Confirm` event (and not `Indication` event) to confirm that an uplink has been sent, as expected by LoRaMAC-node.  
For handling downlink data, we can imagine that the application could define a receiving thread or a function called when a downlink message arrives (triggered by `Indication` event from LoRaMAC-node). That's what is done in [GNRC LoRaWAN][gnrc].

[loraflags]: https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c#L408
[ind-skip]: https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c#L991
[gnrc]: https://github.com/jia200x/RIOT/blob/pr/gnrc_lorawan/tests/gnrc_lorawan/main.c#L39

**Comment by aabadie** [comment]
Thanks for your help @jia200x @ParksProjets.

Your suggestion of only use mcps confirm event to confirm the TX is interesting, that would indeed make this more robust. For receiving messages, I prefer the thread approach over the callback function.

See #11541 that provides this change.

**Comment by aabadie** [comment]
closing in favor of #11541

**Pull request closed without merging**
