### PR TITLE
fs: add tmpfs, a RAM file system

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

This PR adds a temporary RAM file system. It uses dynamic memory allocation (malloc/free, but this can be overwritten with defines and could be improved later on) to allocate RAM files.

The file system is based on a chained list of files, each file containing a chained list of buffers.
There is no support for directories.

### Issues/PRs references

None

### CODE REVIEW

**Comment by gebart** [comment]
What is your main use case? I'm guessing it is something running on native where there is no limits on using malloc?

**Comment by vincent-d** [comment]
To be honest, this was more an experiment than something with a real use case so far. I had this idea and wanted to test it ;) It could be a simple way to share data between threads with file-like access, or maybe cache in RAM before writing to a non-volatile memory.

With a second thought, I could improve malloc'ing with a minimal malloc size to limit fragmentation.

**Comment by vincent-d** [comment]
Updated to use memarray instead of malloc/free

**Comment by vincent-d** [comment]
I won't work on this in the near future, so closing.

**Pull request closed without merging**
