### PR TITLE
native: remove ltc4150

### PR DESCRIPTION
**Pull request by kaspar030**
AFAIR this was intended as an emulation for msba2's ltc4150, but it doesn't seem to do much but count cycles.

As it is heavily relying on hwtimer and hwtimer is supposed to be phased out, I propose to remove this.

(currently with out this, master is broken as there's only one hwtimer which is consumed by vtimer and ltc4150 hard-crashes when no timer is available).

### CODE REVIEW

**Comment by kaspar030** [comment]
*bump*, master on native is broken.

**Comment by OlegHahm** [comment]
I wonder who broke it...

**Comment by kaspar030** [comment]
jaja. :)

**Comment by kaspar030** [comment]
@OlegHahm So you think we need this?

**Comment by OlegHahm** [comment]
I would guess one can get similar values with `time` on the host and `SCHEDSTATISTICS` on RIOT. Would be good to hear @LudwigOrtmann's opinion on this.

**Comment by LudwigOrtmann** [comment]
Just remove it for now, we'll come up with a better version later.

**Comment by LudwigOrtmann** [comment]
(I wanted to switch to a different clock anyways...)

**Comment by OlegHahm** [comment]
Then: ACK and go!

**Pull request merged**
