### PR TITLE
jenkins: ccache optimizations

### PR DESCRIPTION
**Pull request by cgundogan**
This PR introduces some optimizations to better utilize the ccache.
1. By building in the same bin dir the ccache is using the same path when determining cached objects.
1. By exluding the debug symbols, ccache seems to have a better hit rate.

On my local ccache, the ccache size reduced vastly and the hit rate skyrocketed ..
Let's see how this behaves on production.

### CODE REVIEW

**Comment by kaspar030** [comment]
Interesting. What's your ccache hitrate so far? On production Murdock, it is about 85%.

**Comment by cgundogan** [comment]
@kaspar030 The PR took about ~11min with this enhancement. I have no current values for the ccache right, but I remember something around the same as yours (~80-90%). Hopefully this will increase with this PR, though. What's your opinion on removing the debug symbols? Do you think this will introduce side effects?

**Comment by smlng** [comment]
@OlegHahm can you have a quick view on this one, we would like to get this one merged today for Jenkins, its make a real speedup possible! The changes should not affect any third parties such as Murdock ...

**Comment by cgundogan** [comment]
well, no big changes in this PR. Anyone feeling lucky? (:

**Pull request merged**
