### PR TITLE
pkg: cooja network simulator integration

### PR DESCRIPTION
**Pull request by phiros**
Alternative to #1921 with the difference that this PR contains only files required by cooja.
For that purpose I created a fork of cooja [[1]](https://github.com/phiros/cooja). There are ~~two~~ three reasons for forking cooja:

* downloading the whole contiki repo in order to work with cooja seems like overkill
* sparse checkouts still contain a lot of versioning information which aren't needed 
(a sparse checkout of cooja results in a repo size of about 70M; my fork results in about 40M)
* maybe we want to customize cooja in the future in order to better fit our needs. Right now cooja is pretty contiki-centric.

The rest of the PR description is nearly identical to #1921 (for now):

This will add the network simulator Cooja [[2]](http://soda.swedish-ict.se/2296/1/SICS-T--2006-05--SE.pdf) to pkg.
Cooja in conjunction with mspsim is able to simulate whole networks consisting of
MSP-430 compatible platforms (various ATmega128* platforms are also supported through avrora[[3]](http://compilers.cs.ucla.edu/avrora/)). 
The simulator does not only support cycle accurate simulation of nodes but also a range of 
different models for wireless networks (ranging from simple unit disk graphs to ray
tracing based interference models).

TODO:
- [X] add cooja to pkg.
- [ ] demonstrate scripting capabilities and nogui mode with a transceiver driver test 
- [ ] integrate cooja into pytermcontroller (and testbed abstraction)
- [ ] ...

### CODE REVIEW

**Comment by authmillenon** [comment]
How's the status on this?

**Comment by OlegHahm** [comment]
.

**Comment by authmillenon** [comment]
.

**Comment by OlegHahm** [comment]
To me it seems that the first part of this PR is ready and would vote for merging this now. Anyone objects?

@thomaseichinger, maybe you can use this for cc2420 testing?

**Comment by thomaseichinger** [comment]
@OlegHahm Looks good to me. Thanks to remind me about the cc2420, I knew there was something I don't think of.

**Comment by OlegHahm** [comment]
Don't think or don't want to think? ;-)

**Comment by thomaseichinger** [comment]
Doesn't make a difference in the end I guess. ;-)

**Comment by authmillenon** [comment]
What is with this PR btw?

**Comment by OlegHahm** [comment]
> To me it seems that the first part of this PR is ready and would vote for merging this now.

**Comment by OlegHahm** [comment]
I think we have two way forward here:
1. Merge this PR as is, expecting that @phiros or someone else pick up the work on this later on.
2. Extract the documentation from this PR and put in the Wiki or somewhere else and close this PR.

Personally, I would vote for 2.

**Comment by emmanuelsearch** [comment]
+1 for option 2.

**Comment by kaspar030** [comment]
I'll re-tag as this is WIP on release day.

**Comment by OlegHahm** [comment]
https://github.com/RIOT-OS/RIOT/wiki/RIOT-and-Cooja

**Comment by emmanuelsearch** [comment]
nice move ;)

**Pull request closed without merging**
