### PR TITLE
iot-lab_M3: rename to iotlab-m3

### PR DESCRIPTION
**Pull request by authmillenon**
Ever since this board got RIOT support it bugged me a little bit, that it uses `-` and `_` in its name and additionally uses an upper-case "M". While I got used to it, the introduction of the testbed support of the same name made it extra annoying, since the Make goals for the testbed are called `testbed-.*`. This PR renames the board in a way, that it is a) the same format as these make goals and b) in line with the naming of the rest of the boards.

### CODE REVIEW

**Comment by authmillenon** [comment]
All I did was

```bash
git mv boards/iot-lab_M3/ boards/iotlab_m3/
git grep --name-only -i iot-lab_M3 | xargs sed -i 's/iot-lab_M3/iotlab_m3/g'
```

BTW.

**Comment by OlegHahm** [comment]
Please rename to `iotlab-m3` then in order to be aligned with Contiki and openlab (FreeRTOS).

**Comment by authmillenon** [comment]
You are right. I thought the boards are all using underscores, but looking at it again I realize they are all using dashes (except the `wsn430` boards, but they might be left to other PRs :-))

**Comment by authmillenon** [comment]
Done.

**Comment by authmillenon** [comment]
```bash
git mv boards/iotlab_m3/ boards/iotlab-m3/
git grep --name-only iotlab_m3| xargs sed -i 's/iotlab_m3/iotlab-m3/g'
```

**Comment by OlegHahm** [comment]
Will take me a while, to get used to it, but ACK

**Comment by authmillenon** [comment]
@thomaseichinger said something similar when he left the office :D

**Comment by authmillenon** [comment]
(me probably too, but better this than grumbling about it all the time ^^)

**Comment by authmillenon** [comment]
Fixing the wiki I realized, that the page might need some love (pictures are missing, no mention of the testbed support, etc.).

**Comment by thomaseichinger** [comment]
Mistyped 8 times for testing. This will be hard. Go

**Pull request merged**
