### PR TITLE
native: remove `make all-debug` target

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Was deprecated in https://github.com/RIOT-OS/RIOT/pull/13432 as `make all` now fulfills the same function. I can add this to the LOSTANDFOUND.md once this is merged.

### Testing procedure
Make sure `all-debug` does not show up in the code base anymore (except for the release notes).

### Issues/PRs references
Follow-up on https://github.com/RIOT-OS/RIOT/pull/13432

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by aabadie** [comment]
duplicate of  #15333

**Comment by miri64** [comment]
Weird, I looked, but did not see that one...

**Comment by aabadie** [comment]
> Weird, I looked, but did not see that one...

I'm sorry about that. I'm surprised that you were not automatically requested to review #15333 (I thought that was the case).

**Comment by miri64** [comment]
> > Weird, I looked, but did not see that one...
> 
> I'm sorry about that. I'm surprised that you were not automatically requested to review #15333 (I thought that was the case).

There is a difference of ten between this one and yours, so maybe I just didn't scroll far enough :sweat_smile: did not expect the PR to go that "far back".

**Pull request closed without merging**
