### PR TITLE
Make: Add generate-Makefile.ci

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This is the same as the create-Makefile.ci. The alias is added to stay in line with other generate-* Make targets. Now the documentation should also be valid again

### Testing procedure

The target should now match the documentation in the doxygen.

### Issues/PRs references

follow-up to #19239

### CODE REVIEW

**Review by maribu — APPROVED** [review]
Maybe we can also drop create-Makefile ci. I don't expect any downstream users (they would need a Murdock instance themselves), so I think we don't need a deprecation.

I hope @benpicco' s muscle memory adapts swiftly to the new name, otherwise he should speak up against the change quickly :)

**Comment by benpicco** [comment]
Yea just remove the `create-Makefile.ci` target, no need to have this twice.

**Comment by bergzand** [comment]
I took the liberty of force pushing a new commit with a rename instead of adding a new target.

**Comment by bergzand** [comment]
I also added a similar commit to #19245, making `BUILD_IN_DOCKER=1` the default

**Comment by maribu** [comment]
bors merge

**Comment by bergzand** [comment]
Thanks for the swift review

**Pull request merged**
