### PR TITLE
dist/tools/coccinelle: fix static.cocci

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Trying to fix the static check...

### Testing procedure

A REMOVEME commit is included... no comment should be there..

### CODE REVIEW

**Comment by fjmolinas** [comment]
Static check passed, lets make sure it fails without...

**Comment by fjmolinas** [comment]
> Static check passed, lets make sure it fails without...

Ahh failed to parse...

**Comment by fjmolinas** [comment]
@JuliaLawall you submitted the original patch, any suggestions on how to fix this I'm a complete noob regarding SmPL and coccinelle...

**Comment by JuliaLawall** [comment]
On Fri, 5 Nov 2021, Francisco wrote:

>
> @JuliaLawall you submitted the original patch, any suggestions on how to fix this I'm a complete noob regarding SmPL and coccinelle...

Could you give some hint about what the issue is?

thanks,
julia

**Comment by kaspar030** [comment]
@JuliaLawall we recently upgraded to coccinelle 1.0.8.

[static.cocci](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/coccinelle/force/static.cocci) previously found wrong uses of `static` at function scope, but since the upgrade, also complains about uses at file scope.

Here's a wrong file scope patch:

<details>

```
 drivers/encx24j600/encx24j600.c#L48

Coccinelle proposes the following patch:

--- drivers/encx24j600/encx24j600.c
+++ drivers/encx24j600/encx24j600.c
@@ -49,20 +49,20 @@
 #define TX_BUFFER_END           (RX_BUFFER_START)
 #define TX_BUFFER_START         (TX_BUFFER_END - TX_BUFFER_LEN)
 
-static void cmd(encx24j600_t *dev, uint8_t cmd);
-static void reg_set(encx24j600_t *dev, uint8_t reg, uint16_t value);
-static uint16_t reg_get(encx24j600_t *dev, uint8_t reg);
-static void reg_clear_bits(encx24j600_t *dev, uint8_t reg, uint16_t mask);
-static inline int _packets_available(encx24j600_t *dev);
+void cmd(encx24j600_t *dev, uint8_t cmd);
+void reg_set(encx24j600_t *dev, uint8_t reg, uint16_t value);
+uint16_t reg_get(encx24j600_t *dev, uint8_t reg);
+void reg_clear_bits(encx24j600_t *dev, uint8_t reg, uint16_t mask);
+inline int _packets_available(encx24j600_t *dev);
 
-static void _get_mac_addr(netdev_t *dev, uint8_t* buf);
+void _get_mac_addr(netdev_t *dev, uint8_t* buf);
 
 /* netdev interface */
-static int _send(netdev_t *netdev, const iolist_t *iolist);
-static int _recv(netdev_t *netdev, void *buf, size_t len, void *info);
-static int _init(netdev_t *dev);
-static void _isr(netdev_t *dev);
-static int _get(netdev_t *dev, netopt_t opt, void *value, size_t max_len);
+int _send(netdev_t *netdev, const iolist_t *iolist);
+int _recv(netdev_t *netdev, void *buf, size_t len, void *info);
+int _init(netdev_t *dev);
+void _isr(netdev_t *dev);
+int _get(netdev_t *dev, netopt_t opt, void *value, size_t max_len);
 
 static const netdev_driver_t netdev_driver_encx24j600 = {
     .send = _send,

```
</details>

**Comment by JuliaLawall** [comment]
On Sat, 6 Nov 2021, Kaspar Schleiser wrote:

>
> @JuliaLawall we recently upgraded to coccinelle 1.0.8.
>
> static.cocci previously found wrong uses of static at function scope, but since the upgrade, also complains about uses at file scope.
>
> Here's a wrong file scope patch:
>
>  drivers/encx24j600/encx24j600.c#L48
>
> Coccinelle proposes the following patch:

Thanks for the report.  I will fix Coccinelle.

julia

**Comment by fjmolinas** [comment]
Seems like the issue needs fixing upstream, so closing this one.

**Pull request closed without merging**
