### PR TITLE
SAML21 CPU: support 4MHz, 8MHz, 12MHz CORE_CORECLOCK choices

### PR DESCRIPTION
**Pull request by ant9000**
Microchip SAML21 CPU allows a few slow clock modes which are useful on low power devices, to save energy.
This PR adds support for the PL0 power level modes to the CPU initialization.

### CODE REVIEW

**Comment by dylad** [comment]
Thanks for this PR @ant9000 !
Overall looks good to me.
Let me run some tests on the board when I have the hardware with me. Probably tomorrow.

**Review by dylad — APPROVED** [review]
ACK.
I ran a few tests on SAML21-xpro with all the new clock speed, looks good so far.

**Comment by dylad** [comment]
Here we go,
Thanlks @ant9000

**Comment by ant9000** [comment]
Great, thanks!

**Pull request merged**
