### PR TITLE
gnrc_netif: don't allocate message queue on the stack

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The message queue of the netif was allocated on the netif stack, so we had to increase the netif stack size if we increase the message queue size.
    
CC110x was the only driver to get this right - add a new `GNRC_NETIF_STACKSIZE_DEFAULT` define so all drivers will get this right by default.

### Testing procedure

This should not change the stack size except for one case: `cc110x` had `CC110X_EXTRA_STACKSIZE` set to `(GNRC_NETIF_MSG_QUEUE_SIZE - 8) * sizeof(msg_t))` but the default message queue size is 16, adding `(16 - 8) * 8` = 64 bytes to the stack.

Leaving this at 8 for all drivers would effectively bump their stack by 8 messages.
Maybe this was a mistake or maybe `cc110x` really needs the extra 64 bytes of stack. 

@maribu might be able to give this a try and say if stack size is still sufficient.

### CODE REVIEW

**Comment by maribu** [comment]
After rebasing this on top of `master` I ran `examples/gnrc_networking` on our MIoT Nucleo-F767ZI boards:

```
	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
	 - | isr_stack            | -        - |   - |    512 (  256) (  256) | 0x20000000 | 0x200001c8
	 1 | main                 | running  Q |   7 |   1536 (  868) (  668) | 0x20000460 | 0x20000824 
	 2 | pktdump              | bl rx    _ |   6 |   1536 (  240) ( 1296) | 0x20004dd4 | 0x200052e4 
	 3 | 6lo                  | bl rx    _ |   3 |   1024 (  464) (  560) | 0x20005a24 | 0x20005c9c 
	 4 | ipv6                 | bl rx    _ |   4 |   1024 (  604) (  420) | 0x20000a64 | 0x20000cd4 
	 5 | udp                  | bl rx    _ |   5 |   1024 (  256) (  768) | 0x200061fc | 0x200064fc 
	 6 | stm32_eth            | bl anyfl _ |   2 |   1024 (  500) (  524) | 0x20002bd4 | 0x20002e94 
	 7 | at86rf215 [sub GHz]  | bl anyfl _ |   2 |   1024 (  576) (  448) | 0x20001288 | 0x200014bc 
	 8 | at86rf215 [2.4 GHz]  | bl anyfl _ |   2 |   1024 (  576) (  448) | 0x20001688 | 0x200018bc 
	 9 | cc110x               | bl anyfl _ |   2 |   1024 (  572) (  452) | 0x200020b4 | 0x200022ec 
	10 | nrf24l01p_ng         | bl anyfl _ |   2 |   1088 (  628) (  460) | 0x20002640 | 0x200028bc 
	11 | sx127x               | bl anyfl _ |   2 |   1024 (  468) (  556) | 0x200031b4 | 0x20003474 
	   | SUM                  |            |     |  12864 ( 6008) ( 6856)
```

The CC1101 driver seems to be roughly on par with the at86rf215 driver regarding stack consumption. So as it worked fine with the AT86RF215, it should work fine with the CC1101.

**Review by maribu — APPROVED** [review]

**Comment by miri64** [comment]
Maybe, if the message queue size leads to problems, it is better to decouple it from the stack size, by making the message queue a `static` global?

**Comment by benpicco** [comment]
You need one for every thread, so it can’t be static

**Comment by miri64** [comment]
> You need one for every thread, so it can’t be static

Ah, right! Sorry forgot about that ^^"

**Comment by miri64** [comment]
Mhhh, but it could be part of the `gnrc_netif` struct :-D.

**Comment by miri64** [comment]
Isn't that, what https://github.com/RIOT-OS/RIOT/pull/18171 is for?

**Comment by maribu** [comment]
I thought https://github.com/RIOT-OS/RIOT/pull/18171 would solve the issue this PR aims to solve?

https://github.com/RIOT-OS/RIOT/pull/18171 is already ACKed, only the CI needs to be pleased yet.

**Comment by benpicco** [comment]
I like this one more as it also introduces a common `GNRC_NETIF_STACKSIZE_DEFAULT`

**Pull request merged**
