### PR TITLE
pkg_littlefs: call mtd_write with size == prog_size  [2018.01 backport]

### PR DESCRIPTION
**Pull request by pwillem**
Backport of #8384

### CODE REVIEW

**Comment by smlng** [comment]
needs rebase

**Comment by smlng** [comment]
otherwise pre-re-ACK, as for master PR

**Comment by pwillem** [comment]
rebased

**Comment by smlng** [comment]
ah damn, needs rebase again (sry)

**Comment by pwillem** [comment]
rebased again

**Pull request merged**
