### PR TITLE
[FIXME][testbranch] crypto: RFC3610 tests not all passing

### PR DESCRIPTION
**Pull request by cladmi**
I wanted to test the following pull request https://github.com/RIOT-OS/RIOT/pull/6706 and could not get same output for one personal test vector I wrote compared to pycrypto (master branch).

I tried using all rfc3610 tests and discovered that nor the pr branch, nor the master version pass all of them.

This branch adds all these tests from the RFC, (vector i is called TEST i + 10) and adds some debug output. Its not meant to be merged as is but more as a test branch.
I also included https://github.com/RIOT-OS/RIOT/pull/6706 commit to test its version.

From what I see, the errors are located in the final part of the result so calculated from the output of ccm_compute_cbc_mac.

To get the tests files I used https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/SelfTest/Cipher/test_AES.py#L1489 inputs. I included the script to generate the tables.
I only checked that their test for "Packet Vector 7" correctly matches the RFC because it is the first broken test on our suite. So I just expect their tests to be valid.

### Related issue

Tracking Issue https://github.com/RIOT-OS/RIOT/issues/8107

### CODE REVIEW

**Comment by cladmi** [comment]
Found that the problem for tests is that some RFC tests use a 'mac_length' of 12 and not 8 which is hard-written now.

**Comment by cladmi** [comment]
Now all RFC tests are passing, but NIST tests don't.
Maybe its still a configuration issue, I don't know.

**Comment by cladmi** [comment]
I will keep looking into it next week.

**Comment by cladmi** [comment]
The other tests from NIST where using a different 'len_encoding' (!= 2), I fixed it so tests set len_encoding from nonce_len.

This made me saw that the fix for testing len_encoding and input_len is broken for len_encoding >= 4 on 32b platform.

Also I think that we are missing one byte when writing plaintext_len, should write until `i > 16 - L -1`.

I have fixes here but will add tests to demonstrate it.

**Comment by cladmi** [comment]
Also just found out that encryption is broken for `input_len >= 256`.

**Comment by cladmi** [comment]
I will move this to a dedicated issue to track all the problems.

**Comment by smlng** [comment]
@cladmi what is the state of and plan for this PR? @PeterKietzmann requested a review from me, but it reads like this is WIP?

**Comment by cladmi** [comment]
This PR is a huge mess with everything.

It intended to add tests for PR https://github.com/RIOT-OS/RIOT/pull/6706 but found that some reference tests where not working (RFC and NIST).
This test is making these tests work and try to add tests for the PR fixes.
But I also found other bugs when trying to test.

I will make a dedicated issue to track the problems and sub-PRs to address them one by one.
But keep this one as "final" result/test branch.

**Comment by smlng** [comment]
to summarise: no review required here, right?

**Comment by cladmi** [comment]
No, I managed to understand myself what was broken even before the PR.

**Comment by tcschmidt** [comment]
@cladmi what is the status here: better close and work out a new PR?

**Comment by cladmi** [comment]
It is already started to be split into smaller PRs and tracked with https://github.com/RIOT-OS/RIOT/issues/8107
This PR is the aggregate of almost all the fix even those that are not already in a PR.

I will rebase it.

**Comment by cladmi** [comment]
After rebasing, I checked if it would make sense to split `tests-crypto` out of `unittests` as adding all RFC tests could add a lot of ROM usage.

And it goes from:

```
   text    data     bss     dec     hex filename
  29312     948    2696   32956    80bc /home/harter/work/git/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf
```
to

```
   text    data     bss     dec     hex filename
  32124    3468    2696   38288    9590 /home/harter/work/git/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf
```
Why `data` ?

I noted that the test data are not `const` and that `cipher_encrypt_ccm` and `cipher_decrypt_ccm` do not have input pointers declared as `const`.

So more dependencies to fix before the other fixes.

**Comment by cladmi** [comment]
Updated to have const inputs for the crypto functions. I did not change other crypto suites.

I will do split PRs for the changes.

```
BOARD=samr21-xpro RIOT_VERSION_OVERRIDE=buildtest make  -C tests/unittests/ clean tests-crypto
```

I get this size output

    # master
       text    data     bss     dec     hex filename
      29292     948    2696   32936    80a8 /home/harter/work/git/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf

    # const inputs
       text    data     bss     dec     hex filename
      29356     748    2696   32800    8020 /home/harter/work/git/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf


    # all RFC and NIST tests
       text    data     bss     dec     hex filename
      34532     748    2696   37976    9458 /home/harter/work/git/RIOT/tests/unittests/bin/samr21-xpro/tests_unittests.elf

**Comment by tcschmidt** [comment]
@jcarrano @smlng is it now good to review?

**Comment by jcarrano** [comment]
I'm a bit lost as to what we want to do with this PR.

> Its not meant to be merged as is but more as a test branch.

Why? Are this tests OK in the sense that the test is not buggy? If yes then we should merge the tests even if they don't pass.

**Comment by tcschmidt** [comment]
> > Its not meant to be merged as is but more as a test branch.
> 
> Why? Are this tests OK in the sense that the test is not buggy? If yes then we should merge the tests even if they don't pass.

Testing crypto is very important, so we should try to get this (+ additional work) into some production state. Maybe @PeterKietzmann has also some perspective to add?

**Comment by cladmi** [comment]
I will update this one again.

**Comment by cladmi** [comment]
I split adding the `RFC3610` and `NIST` tests taken from `pycrypto` tests vectors.

The other fixes will still need to add proper tests that I did not manage to write when I first published.

**Comment by fjmolinas** [comment]
Closing since #8107 is donde.

**Pull request closed without merging**
