### PR TITLE
examples: only whitelist a few essential boards (dirty hack)

### PR DESCRIPTION
**Pull request by miri64**
This is a dirty hack proposed by @kaspar030 offline (with slight adaptations) to allow Murdock to build properly tonight. @kaspar030 revert if the issue is fixed, @miri64 close this one if it isn't merged tonight.

### CODE REVIEW

**Comment by miri64** [comment]
(the problem is that @kaspar030 did some maintenance work and missed some machines and doesn't have access to them right now. This is a **very** temporary fix that should be properly resolved by tomorrow).

**Comment by kaspar030** [comment]
actually, xxd is needed for all boards (including native and samr21) thus will only make a false negative more unlikely...

**Comment by miri64** [comment]
I didn't want to deactivate all the boards that's why I kept our two "reference" platforms. Until now it seems to work.

**Comment by kaspar030** [comment]
The problem is resolved. Should we just press revert in this PR?

**Comment by miri64** [comment]
I guess that is the cleanest approach

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/7987 for reresal.

**Pull request merged**
