### PR TITLE
mtd: add fast path to mtd_write_page()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

If we overwrite a whole sector, don't perform a read-modify-write cycle.

### CODE REVIEW

**Comment by dylad** [comment]
The idea makes a lot of sense and PR looks good !
I can give it a try tonight.

**Review by dylad — APPROVED** [review]
ACK.

**Comment by dylad** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
