### PR TITLE
tests/emcute: add check for message ID with PUBLISH QoS 0

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides a test for the bug uncovered in https://github.com/RIOT-OS/RIOT/pull/15656 and https://github.com/RIOT-OS/RIOT/pull/15661.

### Testing procedure
```
sudo dist/tools/tapsetup/tapsetup
make -C tests/emcute -j clean flash test
```

Without #15661 this test should fail. When #15661 is merged it should succeed.

This test is not run by Murdock due to the TAP requirement.

### Issues/PRs references
Depends on https://github.com/RIOT-OS/RIOT/pull/15661.

### CODE REVIEW

**Review by haukepetersen — APPROVED** [review]
Change looks valid to me, however seem unable to run the test on my system in the first place. Some python related error or missconfiguration as it seems:
<details>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hauke/dev/riot/RIOT/tests/emcute/tests/01-run.py", line 496, in <module>
    sys.exit(run(testfunc, timeout=TIMEOUT, echo=False))
  File "/home/hauke/dev/riot/RIOT/dist/pythonlibs/testrunner/__init__.py", line 27, in run
    child = setup_child(timeout, env=os.environ,
  File "/home/hauke/dev/riot/RIOT/dist/pythonlibs/testrunner/spawn.py", line 88, in setup_child
    sync_child(child, env)
  File "/home/hauke/dev/riot/RIOT/dist/pythonlibs/testrunner/spawn.py", line 121, in sync_child
    utils.test_utils_interactive_sync_shell(child,
  File "/home/hauke/dev/riot/RIOT/dist/pythonlibs/testrunner/utils.py", line 41, in test_utils_interactive_sync_shell
    _test_utils_interactive_sync(child, retries, delay, '\n', '>')
  File "/home/hauke/dev/riot/RIOT/dist/pythonlibs/testrunner/utils.py", line 17, in _test_utils_interactive_sync
    ret = child.expect_exact([ready_exp, pexpect.TIMEOUT], timeout=delay)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 418, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f4dfa8a01f0>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): ''
before (last 100 chars): 's already in use\r\nmake[1]: *** [/home/hauke/dev/riot/RIOT/Makefile.include:733: cleanterm] Error 1\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 2
flag_eof: True
pid: 76732
child_fd: 9
closed: False
timeout: 1
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: '>'
    1: TIMEOUT
make: *** [/home/hauke/dev/riot/RIOT/tests/emcute/../../Makefile.include:789: test] Error 1
</details>

But I trust that you have verified it successfully, so ACK

**Comment by miri64** [comment]
> Change looks valid to me, however seem unable to run the test on my system in the first place. Some python related error or missconfiguration as it seems:

Did you start `tapsetup` beforehand? If yes, I had some issues running it on my Arch machine as well, as scapy seems to have some problems with python 3.9, but on Ubuntu it runs like a charm.

**Comment by miri64** [comment]
Reminder: https://github.com/RIOT-OS/RIOT/pull/15661 needs to be merged before this PR, even if the build might succeed. The test won't work otherwise.

**Comment by haukepetersen** [comment]
#15661 was merged and this PR is all green: lets go!

**Pull request merged**
