### PR TITLE
 gnrc_ipv6: remove obsolete and harmful reception code

### PR DESCRIPTION
**Pull request by miri64**
#### Observation
When subscribing to IPv6 packets on a router for sniffing, the NETIF header is released prematurely, because of a wrong `gnrc_pktbuf_start_write()` call. This test provided reproduces this error case.

#### Explanation
When reworking the reception of IPv6 packets I reset a previously set `ipv6` snip as follows  when the IPv6 extension handler returns a packet:

https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L727-L729

With `gnrc_ipv6_ext` this makes *somewhat* sense, `pkt->next` was previously equal to `ipv6` and after the function call `pkt->next` is the marked extension header, while `pkt->next->next` is the IPv6 header. However, since `ipv6` is already write-protected i.e. `ipv6->users == 1` (see [ll. 665-675](https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L665-L675)), any additional call of `gnrc_pktbuf_start_write()` [won't][start-write-doc] duplicate the
packet. In fact, the only `gnrc_pktbuf_start_write()` in `gnrc_ipv6_ext` is used to send the *result* to the subscribers of that extension header type, leaving the original packet unchanged for the caller (`tests/gnrc_ipv6_ext` tests that case):

https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/net/gnrc/network_layer/ipv6/ext/gnrc_ipv6_ext.c#L215-L229

As such `ipv6` remains the pointer to the IPv6 header whether we set it in the line above or not. So we actually don't need that line.

However, the extension header handling also returns a packet when `gnrc_ipv6_ext` is not compiled in. In that case it is just a dummy define that returns the packet you give provide it which means that this still holds true: `pkt->next == ipv6`.

https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/include/net/gnrc/ipv6/ext.h#L123

So setting `ipv6` in this case is actually harmful, as `ipv6` now points to the NETIF header [following the IPv6 header][pkt-structure] in the packet and this causes the `user` counter of that NETIF header `hdr` to be decremented if `hdr->users > 1` here:

https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L765-L771

But as we already established, `ipv6->users` is already 1, so we don't actually need the write protection here either.

Since the packet stays unchanged after the `ipv6` snip, we also don't need to re-search for `netif_hdr` after the other two lines are removed.

https://github.com/RIOT-OS/RIOT/blob/56085b10a0dd48fab8c7b5582fef161d6b13d1e1/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L773-L777

[start-write-doc]: https://doc.riot-os.org/group__net__gnrc__pktbuf.html#ga640418467294ae3d408c109ab27bd617
[pkt-structure]: https://doc.riot-os.org/group__net__gnrc__pkt.html#ga278e783e56a5ee6f1bd7b81077ed82a7

### Testing procedure
Build and run both `tests/gnrc_ipv6_ext` and `tests/gnrc_ipv6_fwd_w_sub` on a board of you preference. Remember that you need a TAP interface if you use `native` for your tests (as our [README points out](https://github.com/RIOT-OS/RIOT#using-the-native-port-with-networking)).

```
export BOARD="<you decide>"
make -C tests/gnrc_ipv6_ext flash
sudo make -C tests/gnrc_ipv6_ext test
make -C tests/gnrc_ipv6_fwd_w_sub flash test
```

`tests/gnrc_ipv6_ext` should succeed both in this PR and on master. `tests/gnrc_ipv6_fwd_w_sub` will fail on master (considering you cherry-picked the test with 47d633b and all the fixups to it to master).

Extra testing for safety: compile and run `tests/gnrc_ipv6_fwd_w_sub` with `USEMODULE += gnrc_ipv6_ext`.

### Issues/PRs references
None

### CODE REVIEW

**Comment by cladmi** [comment]
The testing procedure is not working. 

```
export BOARD=samr21-xpro
RIOT_CI_BUILD=1 make -C tests/gnrc_ipv6_ext all test
make: Entering directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext'
Building application "tests_gnrc_ipv6_ext" for "samr21-xpro" with MCU "samd21".

   text    data     bss     dec     hex filename
  55232     508   15892   71632   117d0 /home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/bin/samr21-xpro/tests_gnrc_ipv6_ext.elf
This test requires root privileges.
It's constructing and sending Ethernet frames.

/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/../../Makefile.include:589: recipe for target 'test' failed
make: *** [test] Error 1
make: Leaving directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext'
```

With adding `sudo` for `test`

```
sudo RIOT_CI_BUILD=1 make -C tests/gnrc_ipv6_ext test
make: Entering directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext'
Device "tap0" does not exist.

Traceback (most recent call last):
  File "/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/tests/01-run.py", line 646, in <module>
    sys.exit(run(testfunc, timeout=1, echo=False))
  File "/home/harter/work/git/RIOT/dist/pythonlibs/testrunner/__init__.py", line 23, in run
    testfunc(child)
  File "/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/tests/01-run.py", line 596, in testfunc
    lladdr_src = get_host_lladdr(tap)
  File "/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/tests/01-run.py", line 583, in get_host_lladdr
    "lladdr"
  File "/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/tests/01-run.py", line 562, in check_and_search_output
    output = subprocess.check_output(cmd, *args, **kwargs).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ip', 'addr', 'show', 'dev', 'tap0', 'scope', 'link']' returned non-zero exit status 1.
/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext/../../Makefile.include:589: recipe for target 'test' failed
make: *** [test] Error 1
make: Leaving directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_ext'
```

The second line is not running any tests and just compiling, this seems wrong.
If I add `flash test` it works on `samr21-xpro`.

```
RIOT_CI_BUILD=1 make -C tests/gnrc_ipv6_fwd_w_sub flash test
make: Entering directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_fwd_w_sub'
Building application "tests_gnrc_ipv6_fwd_w_sub" for "samr21-xpro" with MCU "samd21".

   text    data     bss     dec     hex filename
  52576     508    9420   62504    f428 /home/harter/work/git/RIOT/tests/gnrc_ipv6_fwd_w_sub/bin/samr21-xpro/tests_gnrc_ipv6_fwd_w_sub.elf
/home/harter/work/git/RIOT/dist/tools/edbg/edbg  -t atmel_cm0p -b -v -p -f /home/harter/work/git/RIOT/tests/gnrc_ipv6_fwd_w_sub/bin/samr21-xpro/tests_gnrc_ipv6_fwd_w_sub.bin
Debugger: ATMEL EDBG CMSIS-DAP ATML2127031800004678 01.1A.00FB (S)
Clock frequency: 16.0 MHz
Target: SAM R21G18 (Rev C)
Programming................................................................................................................................................................................................................... done.
Verification................................................................................................................................................................................................................... done.
run_test
/home/harter/work/git/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2019-06-26 15:09:08,908 - INFO # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2019-06-26 15:09:11,997 - INFO # main(): This is RIOT! (Version: buildtest)
> 2019-06-26 15:09:12,026 - INFO #  run_test
2019-06-26 15:09:12,028 - INFO # Forwarded Ethernet frame:
2019-06-26 15:09:12,035 - INFO # 00000000  57  44  33  22  11  00  CE  AB  FE  AD  F7  26  86  DD  60  00
2019-06-26 15:09:12,041 - INFO # 00000010  00  00  00  10  11  3F  20  01  0D  B8  00  00  EF  01  02  CA
2019-06-26 15:09:12,048 - INFO # 00000020  4B  EF  F4  C2  DE  01  20  01  0D  B8  00  00  AB  CD  55  44
2019-06-26 15:09:12,054 - INFO # 00000030  33  FF  FE  22  11  00  54  B8  59  AF  3A  B4  5C  85  1E  CE
2019-06-26 15:09:12,057 - INFO # 00000040  E2  EB  05  4E  A3  85
2019-06-26 15:09:12,060 - INFO # Forwarded Ethernet frame:
2019-06-26 15:09:12,067 - INFO # 00000000  57  44  33  22  11  00  CE  AB  FE  AD  F7  26  86  DD  60  00
2019-06-26 15:09:12,073 - INFO # 00000010  00  00  00  10  11  3F  20  01  0D  B8  00  00  EF  01  02  CA
2019-06-26 15:09:12,080 - INFO # 00000020  4B  EF  F4  C2  DE  01  20  01  0D  B8  00  00  AB  CD  55  44
2019-06-26 15:09:12,086 - INFO # 00000030  33  FF  FE  22  11  00  54  B8  59  AF  3A  B4  5C  85  1E  CE
2019-06-26 15:09:12,089 - INFO # 00000040  E2  EB  05  4E  A3  85
2019-06-26 15:09:12,091 - INFO # I got a subscription!
2019-06-26 15:09:12,098 - INFO # 00000000  60  00  00  00  00  10  11  40  20  01  0D  B8  00  00  EF  01
2019-06-26 15:09:12,104 - INFO # 00000010  02  CA  4B  EF  F4  C2  DE  01  20  01  0D  B8  00  00  AB  CD
2019-06-26 15:09:12,111 - INFO # 00000020  55  44  33  FF  FE  22  11  00  54  B8  59  AF  3A  B4  5C  85
2019-06-26 15:09:12,114 - INFO # 00000030  1E  CE  E2  EB  05  4E  A3  85
pktbuf
> 2019-06-26 15:09:12,167 - INFO #  pktbuf
2019-06-26 15:09:12,173 - INFO # packet buffer: first byte: 0x200024a0, last byte: 0x200026a0 (size: 512)
2019-06-26 15:09:12,176 - INFO #   position of last byte used: 256
2019-06-26 15:09:12,180 - INFO # ~ unused: 0x200024a0 (next: 0, size:  512) ~

make: Leaving directory '/home/harter/work/git/RIOT/tests/gnrc_ipv6_fwd_w_sub'
```

**Comment by cladmi** [comment]
Oh the first one was missing `flash`, but even with `flash`, the test still fails with the same error.

**Comment by miri64** [comment]
I assume of a RIOT maintainer how to run a `native` networking application. Otherwise, you would be complaining that the `tapsetup` script is failing because the bridge already exist.

**Comment by miri64** [comment]
Squashed.

**Pull request merged**
