### PR TITLE
build_system: let DISABLE_MODULE disable optional features

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

I was a bit surprised when I could not disable optional features with `DISABLE_MODULE`.
riotbot uses a hack to still disable `periph_pm`, but with this we can remove that special case and handle all via `DISABLE_MODULE`.

### Testing procedure

Still no `periph_pm` in `info-modules` of `bootloaders/riotboot`.

### CODE REVIEW

**Comment by maribu** [comment]
I think this already works, but you have to use `FEATURES_BLACKLIST` to disable features.

At least to me it js surprising to use `DISABLE_MODULE` for features.

It is also a pity that it is not named `DISABLE_FEATURE` rather than `FEATURES_BLACKLIST`.

**Comment by benpicco** [comment]
Ah I must have missed that, will try with that.

**Comment by benpicco** [comment]
`FEATURES_BLACKLIST` works, I wonder if we should add an alias to `DISABLE_FEATURE`.

**Comment by maribu** [comment]
> `FEATURES_BLACKLIST` works, I wonder if we should add an alias to `DISABLE_FEATURE`.

Strong +1. I would even favor making `FEATURES_BLACKLIST` an deprecated alias for `DISABLE_FEATURE`.

**Pull request closed without merging**
