### PR TITLE
tests/slip: homogenize CFLAGS in Makefile with slipdev driver

### PR DESCRIPTION
**Pull request by DanielLockau-MLPA**
### Contribution description

Homogenize out-of-sync CFLAGS in Makefile of tests/slip.

### Testing procedure

There is no issue with the test app but the different CFLAGS defines wrt. the actual driver param names might confuse users who take a look into this test to setup their devices.

### CODE REVIEW

**Comment by DanielLockau-MLPA** [comment]
Sorry, I just noticed that the module is overwriting the entire params struct in a header with the original defines so the state is ok. I only see a problem when people are pulling the makefile into another project (which happened at our place) and wonder why it does not work. I would rework the test to use the params in the makefile if you agree or just discard this PR.

**Comment by benpicco** [comment]
I wonder why the test provides it's own `slipdev_params.h` in the first place, except for not providing defaults it does not differ from `drivers/slipdev/include/slipdev_params.h` and might as well be removed.

**Comment by miri64** [comment]
> I wonder why the test provides it's own `slipdev_params.h` in the first place, except for not providing defaults it does not differ from `drivers/slipdev/include/slipdev_params.h` and might as well be removed.

I guess _someone_(TM) forgot to remove that, when the driver-owned `slipdev_params.h` was introduced ;-)

**Comment by DanielLockau-MLPA** [comment]
I removed the slipdev_params.h in the test's directory.

**Review by benpicco — APPROVED** [review]

**Pull request merged**
