### PR TITLE
cpu/stm32f1/periph/usart: Implement USART under DMA 

### PR DESCRIPTION
**Pull request by DipSwitch**
Untested but almost the same implementation as the F4 so should be functioning.
I'll create a BSP for a board I've laying around here to be able to test it myself.

Depends on #5095

Still need to port the other boards.

### CODE REVIEW

**Comment by haukepetersen** [comment]
looks good on first sight! Though I would like to fix the issue the `uart_stdio` implementation first, so it can handle printfs from different threads concurrently. When using UART with DMA (as the stm32f4), we have scrambled output at the moment...

Making newlib thread safe would be once solution, but I think it would be cool to have something more light-weight..

**Comment by DipSwitch** [comment]
@haukepetersen Please look at the last commit, that is essentially the only thing you could if you don't want to implement newlib thread safe. And even this has a race condition from where the string is formated and placed in the output buffer. To the point till it's copied into the temp buffer.

**Comment by DipSwitch** [comment]
@haukepetersen Please look at the last commit, that is essentially the only thing you could if you don't want to implement newlib thread safe. And even this has a race condition from where the string is formated and placed in the output buffer. To the point till it's copied into the temp buffer.

Another thing could be to overwrite printf with a function which first allocates a temp buffer on the stack and then tries to format it into with snprintf and pass that to the libc write function.

**Comment by DipSwitch** [comment]
Maybe @gebart has some thoughts on the subject aswell :)

**Comment by gebart** [comment]
The stack allocated buffer in https://github.com/RIOT-OS/RIOT/pull/5101/commits/09cf6e3b44e8a9677fab5c29dc0cc3500927d258 will in essence make the program require two copies of the string since you will have one in newlib's buffer and then copy it to the uart buffer.. I don't have a good solution right now, but I feel this is too expensive and too fragile.

**Comment by DipSwitch** [comment]
Then we must override printf to allocate a buffer on te stack en fill it
with snprintf :)

**Comment by kYc0o** [comment]
This new feature requires other PR and is WIP, so it will be reviewed for the next release.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by aabadie** [comment]
> No significant progress for nearly two years. Closing as memo for now.

Just a side comment about the 'closing inactive PR process': wouldn't it be better/smoother to send a notification, wait a few days or 1 week, and if there's no reply within with extra period, close the PR ?
Instead of just mentioning that there's no activity and closing immediately. I fear that most of the PRs in the memo list will be lost for good.

**Pull request closed without merging**
