### PR TITLE
periph/rtc: add support for stm32l4

### PR DESCRIPTION
**Pull request by MichelRottleuthner**
As the title says, this adds rtc support for stm32l4. Currently this was only tested on `nucleo-l476`.
Can someone test this on other stm32l4-based boards?

### CODE REVIEW

**Comment by MichelRottleuthner** [comment]
@haukepetersen I assume your ACK still holds?

**Comment by MichelRottleuthner** [comment]
ping @haukepetersen

**Comment by haukepetersen** [comment]
yes. All green -> go.

**Comment by haukepetersen** [comment]
@MichelRottleuthner would you be willing to put some efforts into #7123?

**Comment by MichelRottleuthner** [comment]
@haukepetersen you mean like #7469? But with #7477 it would make sence to integrate the changes there.

**Pull request merged**
