### PR TITLE
doc: Enable REPEAT_BRIEF in Doxygen

### PR DESCRIPTION
**Pull request by gebart**
The detailed documentation of some functions need the brief description included to make sense without having to jump back and forth between the brief list and the detailed descriptions when scrolling through the API docs.

This will make all API documentation HTML pages longer, but I think it helps readability of the manual.

### CODE REVIEW

**Comment by miri64** [comment]
Mhhhh for some docs I started to write them as such that the brief doesn't has to be backtraced (without looking weird in-code). I think if this is activated those (few) cases might look weird.

**Comment by smlng** [comment]
I tend to agree with @gebart -- I'd rather use this option than to repeat text in the docu which is already in the `@brief`. At least we should find consensus and add that to the wiki (or so).

**Comment by miri64** [comment]
I'm not saying we shouldn't do it, only that some parts of the doc might need rework after the merge ;-)

**Comment by kaspar030** [comment]
> only that some parts of the doc might need rework after the merge ;-)

Well said, volunteer! :)

**Comment by miri64** [comment]
> Well said, volunteer! :)

I'll keep an eye out for that, but I meant this to be a collective effort by the community in both code and reviews ;-).

**Comment by aabadie** [comment]
> a collective effort by the community in both code and reviews

I'm in

**Comment by aabadie** [comment]
We have 3 ACK here, I think it's fine to merge this one.

**Pull request merged**
