### PR TITLE
dist/tools: update EDBG version

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description
This PR updates EDBG version of RIOT to the lastest.
I had a lot of troubles when playing with low power modes or DPLL/DFLL on SAM0 based board. Most of the time, the board was stuck in a unrecoverable state for EDBG and I had to erase the flash using Atmel Studio (switch back to windows to unbrick the board...)
The lastest version of EDBG get rid of this problem as I can now erase/reflash the board in all situations. No need to use Atmel Studio anymore to unbrick a board !

### Issues/PRs references
None

### CODE REVIEW

**Comment by cladmi** [comment]
Let's see if murdock can handle it already.

**Comment by dylad** [comment]
@cladmi Looks like Murdock is happy :)

**Comment by cladmi** [comment]
It looks like murdock does not use the compiled `edbg` and uses a local installation:

```
make: Entering directory '/tmp/dwq.0.3981599149433197/4ceadfbccb6700af35ecc065b126a1aa/tests/gnrc_ndp'

/usr/local/bin/edbg --serial ATML2127031800002130 --serial ATML2127031800002130 -t atmel_cm0p -b -e -v -p -f /tmp/dwq.0.3981599149433197/4ceadfbccb6700af35ecc065b126a1aa/tests/gnrc_ndp/bin/samr21-xpro/tests_gnrc_ndp.bin
Debugger: ATMEL EDBG CMSIS-DAP ATML2127031800002130 01.1A.00FB (S)
...
```

For testing the new version I needed to make `edbg` rebuild by removing it from `dist/tools/edbg`.

The correct solution to correctly rebuild `edbg` is to add the Makefile dependency:
(it should even be there for all tools).

``` diff
diff --git a/makefiles/tools/targets.inc.mk b/makefiles/tools/targets.inc.mk
index 352f146..74f1de6 100644
--- a/makefiles/tools/targets.inc.mk
+++ b/makefiles/tools/targets.inc.mk
@@ -12,7 +12,7 @@ $(RIOTTOOLS)/bossa/bossac:
        @make -C $(RIOTTOOLS)/bossa
        @echo "[INFO] bossac binary successfully build!"
 
-$(RIOTTOOLS)/edbg/edbg:
+$(RIOTTOOLS)/edbg/edbg: $(RIOTTOOLS)/edbg/Makefile
        @echo "[INFO] edbg binary not found - building it from source now"
        CC= CFLAGS= make -C $(RIOTTOOLS)/edbg
        @echo "[INFO] edbg binary successfully build!"
```

With this change, when flashing from your PR edbg is correctly rebuild and flashes.
You could add it in a separate commit.

Propagating to other tools should be done in another PR.

**Comment by dylad** [comment]
Thanks @cladmi, I'll update it soon.

**Comment by cladmi** [comment]
@dylad  I would prefer if you could add the explanation of why you need the update in the commit message body.

I was thinking about adding the new version number/changelog too but it looks like there is nothing like this in the edbg repository :D

**Comment by dylad** [comment]
@cladmi I'll edit the first commit msg too then.

**Comment by dylad** [comment]
@cladmi do you like the changes ?

**Comment by cladmi** [comment]
It's good for me on `ubuntu 16.04`. I tested with:

```
git checkout master; rm -f dist/tools/edbg/edbg; make -C examples/hello-world/ BOARD=samr21-xpro flash
```
Then go the PR and try flashing again, `edbg` is correctly rebuild before flashing.

After testing you may need to redo `rm -f dist/tools/edbg/edbg` before switching back to master to remove the "new" version until this is merged.

I would just like to get it tested on other setups too:

* [ ] arch linux @jcarrano 
* [ ] gentoo @bergzand 
* [ ] mac @kYc0o

**Comment by bergzand** [comment]
Confirmed that EDBG is rebuild on my setup after switching from master to this branch.

**Comment by kaspar030** [comment]
you could add a temporary commit that disables EDBG override from local version (I think thats in makefiles/tools/edbg.inc.mk), set the run-tests-on-ci label, then trigger murdock. that should make the samr21-xpro raspis re-build edbg from the updated source and use it to flash the tests.

**Comment by cladmi** [comment]
I pushed a commit that should do it.

**Comment by kaspar030** [comment]
It seems to fail because there's no libudev on the worker. I'll install that manually...

**Comment by kaspar030** [comment]
Did so, an I'm watching the worker, the flashing works from the in-tree compiled version.

**Comment by cladmi** [comment]
@kaspar030 Thanks for testing this

**Comment by cladmi** [comment]
@kYc0o does it work on mac ?

**Comment by cladmi** [comment]
Maybe @smling you can test: https://github.com/RIOT-OS/RIOT/pull/9502#issuecomment-403875030

**Comment by cladmi** [comment]
Please remove my two last commits (I don't want to push force to your branch).

**Comment by dylad** [comment]
@cladmi Sorry for the delay, this is done.

**Comment by cladmi** [comment]
20 minutes after my message is not "delay" :p 

Murdock is failing on the same shell tests as it often does. I removed `CI: run tests` and you can merge when it's done if I forget to.

**Pull request merged**
