### PR TITLE
mma8x5x: interruption management added

### PR DESCRIPTION
**Pull request by AurelienGONCE**
Accelerometer mma8x5x have two interrupt pins configurable.

This PR gives the possibility to use the mma8x5x type device with interruption(s) and configure, one or the two interrupts to the expected source (data ready, freefall/motion, landscape, ...).
- The use of `mma8652_int` module is necessary to call the right init function.
- One or two `mma8652_int_t` structure have to be created to configure the mm8652 device.

This modification could be use with any of MMA devices defined in header file: MMA8652, MMA8653, MMA8451, MMA8452 and MMA8453.

It is `xtimer` and `gpio` module dependent

This PR is based on #5433.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Nice. I think we could make the interface a little simpler though, from an interface perspective, I think 1 single set function and 2 more user functions for landscape and freefall should be quite sufficient:
```c
void mma8x5x_set_int(mma8x5x_t *dev, mma8x5x_intsrc_t src, void(*cb)(void*), void *arg);
// and
int mma8x5x_is_portrait(dev);
int mma8x5x_is_freefall(dev);
```
IMHO there is not need to export anything else.

Further, would you mind to rebase your PR on #6153?! Thx.

**Comment by cgundogan** [comment]
@AurelienGONCE coudl you rebase to current master again?

**Comment by PeterKietzmann** [comment]
Be aware of #6153 which will be merged soon

**Comment by vincent-d** [comment]
@AurelienGONCE is not working with us anymore. I'll rebase this once #6153 is merged.

**Comment by vincent-d** [comment]
It's really a pain to rebase! I won't do it in the next days.

**Comment by aabadie** [comment]
@vincent-d, do think you'll be able to rebase before next release (feature freeze is next friday) ?

**Comment by vincent-d** [comment]
I won't have time to work on this next week. It would maybe be less effort to restart from scratch.

And I think #7166 already implemented half of what's here.

Maybe we can close.

**Comment by aabadie** [comment]
Ok, closing and setting as memo.

**Pull request closed without merging**
