### PR TITLE
ng_nomac: use dispatch function

### PR DESCRIPTION
**Pull request by authmillenon**
Follow-up to #2893.

### CODE REVIEW

**Comment by haukepetersen** [comment]
looks good to me, will test now.

**Comment by authmillenon** [comment]
That's a long test for a small change ;-)

**Comment by haukepetersen** [comment]
sorry, I got distracted... Will take it on tomorrow morning

**Comment by haukepetersen** [comment]
Compiler warning: `RIOT/sys/net/link_layer/ng_nomac/ng_nomac.c:42:28: warning: unused variable ‘sendto’ [-Wunused-variable]`

**Comment by haukepetersen** [comment]
Besides the unused variable everything runs smoothly here -> ACK once that is fixed, squashed and Travis...

**Comment by authmillenon** [comment]
Fixed warning and squashed

**Pull request merged**
