### PR TITLE
doc: README: Add documentation on downloads and release cycle

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This offers an alternative to https://github.com/RIOT-OS/RIOT/pull/16087 for the documentation of our release cycle. The README is amended with a short section how to download RIOT and the doxygen documentation receives a page about our release cycle in detail

### Testing procedure
Read, doxygen should build properly and all the links should work (except the `[release cycle]` link; for that `https://doc.riot-os.org` needs to be updated with this PR first).

### Issues/PRs references
Alternative to https://github.com/RIOT-OS/RIOT/pull/16087.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
For what it matters I like this version better.  The initial README should be giving an idea where to get detailed information and the docs are for the details.

**Review by fjmolinas — APPROVED** [review]
ACK, I prefer this version than this alternative

**Comment by miri64** [comment]
Needs one more ACK due to the README change.

**Comment by miri64** [comment]
May I squash in the meantime?

**Comment by fjmolinas** [comment]
> May I squash in the meantime?

yep

**Comment by miri64** [comment]
> > May I squash in the meantime?
> 
> yep

Mixed messages ^^ (due to the :-1: emoji on the post)

**Comment by miri64** [comment]
Squashed.

**Comment by fjmolinas** [comment]
> > > May I squash in the meantime?
> > 
> > 
> > yep
> 
> Mixed messages ^^ (due to the -1 emoji on the post)

Sorry wrony emoji

**Review by jeandudey — APPROVED** [review]
ACK. Improves the situation for newcomers looking for this information 👍🏻 

Rendered docs:

- [release-cycle.md](https://9551-7370241-gh.circle-artifacts.com/0/doc/release-cycle.html)
- [README.md](https://github.com/RIOT-OS/RIOT/blob/af7152eeca3ac906a1f673576d5c9cc343cbdd00/README.md#getting-riot)

**Pull request merged**
