### PR TITLE
cpu/sam0_common: update samr21 vendor files to version 1.1.72

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This updates the samr21 vendor files to the latest version from http://packs.download.atmel.com/

This release adds EXTINT defines compatible with later versions of the sam0 series of MCUs.

### Testing procedure

No change in functionality is expected.

### Issues/PRs references

needed for #13310

### CODE REVIEW

**Comment by benpicco** [comment]
I hate editing vendor files as much as the next guy, but `_U` and `_L` are already used by `newlib/ctype.h` and all the newer SoCs use `_U_` and `_L_` anyway…

**Comment by dylad** [comment]
@benpicco 
If you modify vendor files, please notify it in the README.md so users shouldn't be surprise.

**Comment by benpicco** [comment]
Ok, updated the Readme.md.

**Comment by dylad** [comment]
ACK again, please squash.

**Pull request merged**
