### PR TITLE
cpu/stm32: clone cmsis header in build/stm32

### LINKED ISSUE #17207: stm32: cmsis: some issues with files downloaded into source tree.
#### Description

The stm32 cmsis headers are getting downloaded *right into the source tree*, and don't get cleaned up.
While individually they're not that large (3-12mb), they sum up to ~190mb. While probably unnoticable locally, that's causing higher peak load on CI's tmpfs. 
`git status` doesn't even show them, and `git clean -xfd` ignores them.

I think we should download (and use them from) `build/...`. That way, they could at least get clean between builds. (checking out from git-cache is almost instant for such small repos).

I've taken a brief look, that shouldn't be too hard. `gen_irqs.py` and `gen_irqs.py` can be changed to allow specifying the input and output files/folders, and after that, it's just a matter changing the makefiles, (I think).

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This should fix the problem reported in #17207 by cloning the STM32 cmsis headers under `build/stm32` instead of inside the `cpu/stm32/include` directory.

### Testing procedure

- Green CI
- No more memory issues on the Murdock workers

### Issues/PRs references

fixes #17207

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by aabadie** [comment]
Hmm, Murdock already spotted issues with the patches. Will check

**Comment by aabadie** [comment]
3ca9800 should have fixed the problems with the patches but I don't know how to deal with the other errors (see [this one](https://ci.riot-os.org/RIOT-OS/RIOT/17212/5c1444888988599113eed3d773e7b63d21f187d9/output/compile/tests/driver_at30tse75x/nucleo-f429zi:gnu.txt) for example).
I thought #15367 was supposed to have fixed such issues.

**Comment by kaspar030** [comment]
would you mind limiting this build with a REMOVEME commit (e.g., adding `BOARDS=nucleo-f401re` to .murdock)?

**Comment by kaspar030** [comment]
(adding a test label, will remove soon)

**Comment by aabadie** [comment]
I need some help here because I have absolutely no idea what is wrong with Murdock. On my machine it works perfectly (well, I'm not using git-cache, ccache but I don't see why that would make a difference).

**Comment by kaspar030** [comment]
> I need some help here because I have absolutely no idea what is wrong with Murdock. On my machine it works perfectly (well, I'm not using git-cache, ccache but I don't see why that would make a difference).

I'll take a look. git-cache/ccache might speed up things to a point where races show up.

**Comment by kaspar030** [comment]
I was able to reproduce this, on tmpfs.

I tried doing the exact steps that murdock does:

```
export BINDIR=/tmp/riot/build
export PKGDIRBASE=${BINDIR}/pkg
export RIOT_CI_BUILD=1
rm -Rf bindir

BOARD=nucleo-f429zi make clean
BOARD=nucleo-f429zi TEST_KCONFIG=1 make all test-input-hash -j
BOARD=nucleo-f429zi make clean all test-input-hash -j
```

This fails similar to murdock:

```
❯ sh test.sh 
=== [ATTENTION] Testing Kconfig dependency modelling ===
=== [ATTENTION] Testing Kconfig dependency modelling ===
[INFO] cloning stm32cmsis
git-cache: cloning from cache. tag=commit4cf505380bf123941fd485b1ae01c0747dca3792-287848
Building application "tests_shell" for "nucleo-f429zi" with MCU "stm32".

[INFO] updating stm32cmsis /tmp/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded
echo 4cf505380bf123941fd485b1ae01c0747dca3792   > /tmp/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded
[INFO] patch stm32cmsis
sha1sum /tmp/riot/tests/shell/tests/01-run.py /tmp/riot/build/tests_shell.elf > /tmp/riot/build/test-input-hash.sha1
   text    data     bss     dec     hex filename
  13140     132    2380   15652    3d24 /tmp/riot/build/tests_shell.elf
Building application "tests_shell" for "nucleo-f429zi" with MCU "stm32".

[INFO] updating stm32cmsis /tmp/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded
fatal: cannot change to '/tmp/riot/build/stm32/cmsis/f4': No such file or directory
[INFO] fetching new stm32cmsis version 4cf505380bf123941fd485b1ae01c0747dca3792fatal: not a git repository: '.git'
make[1]: *** [/tmp/riot/pkg/pkg.mk:123: /tmp/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded] Error 128
make: *** [/tmp/riot/cpu/stm32/Makefile.include:89: /tmp/riot/build/stm32/cmsis/f4/Include/stm32f4xx.h] Error 2
make: *** Waiting for unfinished jobs....
```

on ssd, this completes, but there is a hint:
```
=== [ATTENTION] Testing Kconfig dependency modelling ===
=== [ATTENTION] Testing Kconfig dependency modelling ===
[INFO] cloning stm32cmsis
git-cache: cloning from cache. tag=commit4cf505380bf123941fd485b1ae01c0747dca3792-288861
Building application "tests_shell" for "nucleo-f429zi" with MCU "stm32".

[INFO] updating stm32cmsis /home/kaspar/src/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded
echo 4cf505380bf123941fd485b1ae01c0747dca3792   > /home/kaspar/src/riot/build/stm32/cmsis/f4/.pkg-state.git-downloaded
[INFO] patch stm32cmsis
sha1sum /home/kaspar/src/riot/tests/shell/tests/01-run.py /home/kaspar/src/riot/build/tests_shell.elf > /home/kaspar/src/riot/build/test-input-hash.sha1
   text    data     bss     dec     hex filename
  13140     132    2380   15652    3d24 /home/kaspar/src/riot/build/tests_shell.elf
Building application "tests_shell" for "nucleo-f429zi" with MCU "stm32".

[INFO] cloning stm32cmsis
rm: cannot remove '/home/kaspar/src/riot/build': Directory not empty
make: [/home/kaspar/src/riot/tests/shell/../../Makefile.include:758: clean] Error 1 (ignored)
git-cache: cloning from cache. tag=commit4cf505380bf123941fd485b1ae01c0747dca3792-289412
sha1sum /home/kaspar/src/riot/tests/shell/tests/01-run.py /home/kaspar/src/riot/build/tests_shell.elf > /home/kaspar/src/riot/build/test-input-hash.sha1
   text    data     bss     dec     hex filename
  13140     132    2380   15652    3d24 /home/kaspar/src/riot/build/tests_shell.elf
```

Note the `rm: cannot remove '/home/kaspar/src/riot/build': Directory not empty`, which points to some race condition. That `rm` is called with `rm -rf`, thus should remove subdirs. The error points to some file being created *after* rm thinks it has cleaned the contents of that folder.

CI has the bindir in `build/`, maybe that leads to clashes? Is `build/` hard-coded somewhere?

**Comment by kaspar030** [comment]
This patch fixes the issue here:

https://gist.github.com/kaspar030/5db6b6f0ca7966b49a9e36edbb1792e5

The cmsis pkg download step needs to be executed after clean...

**Comment by aabadie** [comment]
> This patch fixes the issue here:

Thanks, that did the trick :+1:

**Review by kaspar030 — APPROVED** [review]
I did a quick sanity check on nucleo-f401re, examples/hello-world and tests/ztimer_msg worked fine. I'd assume that this would fail builds anyways, long before runtime errors. :)

ACK.

**Comment by kaspar030** [comment]
please squash and drop REMOVEME!

**Pull request merged**
