### PR TITLE
net/ng_netdev: made pointer to driver const

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK when Travis is happy

**Comment by haukepetersen** [comment]
ok, only a matter of days :-)

**Comment by authmillenon** [comment]
Nope, only two hours :D

**Comment by haukepetersen** [comment]
dammit, just wanted to press the button...

**Comment by authmillenon** [comment]
You can re-ack #2563

**Comment by OlegHahm** [comment]
Wouldn't `const ng_netdev_driver_t *driver;` the more common notation?

**Comment by haukepetersen** [comment]
it has a different meaning then...

**Comment by gebart** [comment]
Can you clarify if you mean non const pointer to const object or const pointer to non const object? If you mean const pointer to non const then you can put the const after the asterisk. If it is a non const pointer to const then the const can go before the type.

**Pull request merged**
