### PR TITLE
ng_nomac: fix receive

### PR DESCRIPTION
**Pull request by authmillenon**
In case of a receive event of the driver there was for some reason a SND command issued to the subscribers.

### CODE REVIEW

**Comment by haukepetersen** [comment]
how about we introduce `ng_netapi_receive(..)` instead to `ng_netapi` and use that here?

**Comment by authmillenon** [comment]
Isn't that more overhead? It's technically only 2 loc. (The `msg` could be initialized statically in theory).

**Comment by haukepetersen** [comment]
slightly more overhead (same as for using the `netapi_send` function), but makes the code more readable and would be consistent with the use of `netapi_send`...

We could also change `netapi_send` to something like `netapi_fw()` and add a third parameter `type := [NETAPI_MSG_TYPE_SND|NETAPI_MSG_TYPE_RCV]`

**Comment by authmillenon** [comment]
@haukepetersen done

**Comment by haukepetersen** [comment]
nice, works. ACK when Travis is ok with it.

**Pull request merged**
