### PR TITLE
kinetis: update vendor headers

### PR DESCRIPTION
**Pull request by gebart**
based on #7379 
This updates the vendor headers to the latest ones currently available in the tool chain packages from https://mcuxpresso.nxp.com
Moved all compatibility definitions to a separate header to make updating easier.

### CODE REVIEW

**Comment by kYc0o** [comment]
Is this updated to master? I'd like to test the new headers with the new clocking configurations.

**Comment by gebart** [comment]
this should be on the latest master with the unified kinetis cpu.c and clocking

**Comment by kYc0o** [comment]
Hmmm... Murdock fails because whitespaces in some lines... I thought these files were omitted isn't it?

**Comment by gebart** [comment]
I think they are omitted from style checks but not whitespace. I'll fix them and amend the PR  when I am back at the computer

**Comment by gebart** [comment]
amended the whitespace change (deleted empty lines at the bottom of each header)

**Pull request merged**
