### PR TITLE
pkg: fix build jerryscript on macOS

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

The javascript example does not compile on macOS with clang/llvm toolchain, this PR fixes that.
It also updates the jerryscript to latests master (2017, December). 

Fixed errors:

```
/RIOT/examples/javascript/bin/pkg/native/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-helpers-date.c:642:31: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
  lit_utf8_byte_t date_buffer[date_buffer_length];
                              ^~~~~~~~~~~~~~~~~~
1 error generated.
```
 and

```
/RIOT/examples/javascript/bin/pkg/native/jerryscript/jerry-core/jrt/jrt.h:20:9: error: '_XOPEN_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
#define _XOPEN_SOURCE 500
        ^
/RIOT/examples/javascript/bin/native/riotbuild/riotbuild.h:6:9: note: previous definition is here
#define _XOPEN_SOURCE 600
        ^
1 error generated.
```
### Issues/PRs references

None

### CODE REVIEW

**Comment by smlng** [comment]
@kaspar030 can you have a look at this one? I'd like to get RIOT working on macOS and (as mentioned some time ago) add a CI worker to make regular checks on macOS. I admit that disabling some compiler warning isn't the nicest way, but it's the quickest workaround for now.

**Comment by kYc0o** [comment]
Normal situation in master:

```console
Scanning dependencies of target jerry-core
[  0%] Building C object jerry-core/CMakeFiles/jerry-core.dir/api/jerry-debugger.c.obj
error: unknown warning option '-Wlogical-op'; did you mean '-Wliblto'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=logical-op'; did you mean '-Werror=liblto'? [-Werror,-Wunknown-warning-option]
make[6]: *** [jerry-core/CMakeFiles/jerry-core.dir/api/jerry-debugger.c.obj] Error 1
make[5]: *** [jerry-core/CMakeFiles/jerry-core.dir/all] Error 2
make[4]: *** [jerry-core/CMakeFiles/jerry-core.dir/rule] Error 2
make[3]: *** [jerry-core] Error 2
make[2]: *** [libjerry] Error 2
make[1]: *** [all] Error 2
```

With this PR that problem is fixed, however:

```console
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

make: *** [term] Segmentation fault: 11
```

I got that when trying to run it.

**Comment by smlng** [comment]
@kYc0o in the Makefile the thread stack size was changed for all boards, even native. While it was fine for Linux it didn't suffice for macOS, I fixed that by changed stack size for non-native boards only. Please test again, works for me now.

**Comment by smlng** [comment]
as you've been: thx for testing and reviewing @kYc0o! And also merging 😉

**Pull request merged**
