### PR TITLE
sys/xtimer: untangle from core/mutex

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Place a verbatim copy of `_mutex_lock()` as `static` in `xtimer`, so internal mutex function can be optimized one step at a time without breaking `xtimer`.

### Testing procedure

- `make BOARD=<some_board> -C tests/xtimer_mutex_lock_timeout flash test`
- `make BOARD=<some_board> -C tests/xtimer_rmutex_lock_timeout flash test`

### Issues/PRs references

Needed to split https://github.com/RIOT-OS/RIOT/pull/15052, as requested

### CODE REVIEW

**Comment by benpicco** [comment]
I understand correctly that the initial code duplication is to allow the implementations to diverge as follow-up?

**Comment by maribu** [comment]
> I understand correctly that the initial code duplication is to allow the implementations to diverge as follow-up?

Exactly. IMO `core/mutex` should gain an `void mutex_cancel(mutex_t *mutex, thread_t *waiter)` (as implemented in https://github.com/RIOT-OS/RIOT/pull/15052) that allows to unblock a thread waiting on a mutex. This function makes implementing `xtimer_mutex_lock_timeout()` and `ztimer_mutex_lock_timeout()` trivial and might be useful by itself.

If this PR gets a NACK, I'm equally happy. Then I wouldn't have to split https://github.com/RIOT-OS/RIOT/pull/15052 up.

**Comment by benpicco** [comment]
But why split this PR out?
63d673a42eab8ebcb620fabd88c41b491eefec53 would be a more logical choice. It sets a clean state and then the simplifications / new features are based on that.

You could then split that commit into three and make a PR out of that :wink:

**Comment by maribu** [comment]
> But why split this PR out?
> [63d673a](https://github.com/RIOT-OS/RIOT/commit/63d673a42eab8ebcb620fabd88c41b491eefec53) would be a more logical choice. It sets a clean state and then the simplifications / new features are based on that.
> 
> You could then split that commit into three and make a PR out of that wink

The problem is, that `xtimer_mutex_lock_timeout()` calls into `_mutex_lock()`. But that commit refactors it. Hence, `xtimer` wouldn't compile anymore. Giving `xtimer` a local copy of `_mutex_lock()` like done here would allow my to make a PR of just [63d673a](https://github.com/RIOT-OS/RIOT/commit/63d673a42eab8ebcb620fabd88c41b491eefec53).

**Comment by benpicco** [comment]
So how about including 63d673a here.
That way this PR actually does something useful and the change is split in more digestible chunks.

**Comment by fjmolinas** [comment]
How do we proceed here? I can run the `xtimer` tests if that is needed.

**Comment by fjmolinas** [comment]
> I can run the xtimer tests if that is needed.

Did that https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/195/artifact/ all good.

**Review by benpicco — APPROVED** [review]
I wish you would have just included the next batch of changes here, but if this makes it easier for you we can also merge this as is.

No functional changes as this just duplicates the code from the original place.

**Pull request merged**
