### PR TITLE
gnrc_rpl: make DODAG_CONF optional when joining DODAG

### LINKED ISSUE #4236: rpl: ignoring DIOs without DODAG Configuration option
According to RFC6550 this option is not required, however in the current implementation a node won't join a until this option is included in the DIO.

### PR DESCRIPTION
**Pull request by cgundogan**
Fixes #4236 (see discussion there).

@OlegHahm 
>@cgundogan, let's discuss next Tuesday.

We never discussed it, but I am fine providing that feature as a compile-time option.

### CODE REVIEW

**Comment by cgundogan** [comment]
rebased to master

**Comment by cgundogan** [comment]
@OlegHahm if you think we need more discussion on this topic feel free to move the milestone.

**Comment by OlegHahm** [comment]
Sorry for the pending reaction. I wonder if it wouldn't even make sense to add this option (at least as a comment) to the gnrc_networking example's Makefile. So that everybody who wants to test interoperability between RIOT and unstrung or Contiki's RPL implementation, can set this easily (without digging into documentation).

**Comment by cgundogan** [comment]
@OlegHahm that's a splendid idea! Added a comment to the `Makefile` of the `gnrc_networking` example.

**Comment by OlegHahm** [comment]
ACK

**Comment by cgundogan** [comment]
both CIs agree - GO

**Pull request merged**
