### PR TITLE
make: enable NHC by default

### PR DESCRIPTION
**Pull request by cgundogan**
~~depends on #5281~~

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
#5281 was merged.

**Comment by authmillenon** [comment]
But #5402 wasn't yet.

**Comment by authmillenon** [comment]
#5402 was merged, please provide a backport.

**Comment by authmillenon** [comment]
libfixmath issue is independent and was fixed in #5435. Should we merge regardless?

**Comment by cgundogan** [comment]
@authmillenon ACK ACK ACK?

**Comment by authmillenon** [comment]
ACK and go

**Pull request merged**
