### PR TITLE
sys: remove config module

### PR DESCRIPTION
**Pull request by kaspar030**
IMHO this module is unmaintained and unused... Do we still need it?

### CODE REVIEW

**Comment by OlegHahm** [comment]
:+1: for removing this, but we definitely need a replacement.

**Comment by gebart** [comment]
I suggest a vfs or nvram based replacement. that should go in a separate PR
though.

Den 18 aug. 2016 10:46 AM skrev "Oleg Hahm" <notifications@github.com>:

**Comment by OlegHahm** [comment]
Sounds a bit like overkill to me. Think of MSP430 and its INFOMEM (a small flash section, intended to store persistent device specific information).

**Comment by kYc0o** [comment]
So should we close this #162 issue?

**Comment by miri64** [comment]
> Sounds a bit like overkill to me. Think of MSP430 and its INFOMEM (a small flash section, intended to store persistent device specific information).

Why would it be overkill to implement a very simple read-only vfs backend for this and make it something comparible to `/proc` or `/sys` on Linux? I think this only would provide more consistency to more powerful platforms if they provide something like this as well.

**Comment by OlegHahm** [comment]
A whole filesystem to store some bytes in a persistent way sounds certainly like overkill to me and I don't see any benefit.

**Comment by gebart** [comment]
@OlegHahm I didn't mean a whole file system for a config store. What I meant is that the implementation should be either an NVRAM device, or a file-like persistent memory using the VFS API. Using familiar APIs such as vfs_read/write would just make it easier to use from an application developer point of view.
The "file system" driver does not need to support multiple files, just a single file which is the interface to the backing memory. Similar to what a /dev/sdx device does in Linux.

**Comment by LudwigKnuepfer** [comment]
I guess it is worthwhile to move the discussion about what to do as a replacement to a dedicated issue.

**Comment by gebart** [comment]
I agree, I think since this PR has been open for more than a week, I don't think anyone will mind that we remove this module until a replacement is ready.

**Comment by kaspar030** [comment]
- fixed last build errors, squashed

**Comment by LudwigKnuepfer** [comment]
ACK

**Pull request merged**
