### PR TITLE
sys/bitfield: add atomic variants of write functions

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This adds wrapper functions for all the bitfield functions that write to the bitfield, to allow two (or more) threads to set/clear bits on the bitfield.

This uses `irq_disable()` as the critical section that modifies the bitfield is shorter than a `mutex_lock()`.

### Testing procedure

This just adds a 2nd `_atomic()` variant of each function that wraps the original function within `irq_disable()`/`irq_restore()`.

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by kaspar030** [comment]
bors merge

**Comment by benpicco** [comment]
bors retry

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
