### PR TITLE
gnrc_sixlowpan_nd_border_router: initial import of border router behavior of 6LoWPAN-ND

### PR DESCRIPTION
**Pull request by authmillenon**
This imports [border router behavior](https://tools.ietf.org/html/rfc6775#section-7) for [6LoWPAN-ND](https://tools.ietf.org/html/rfc6775) and adapts GNRC accordingly

Depends on:
* ~~#3049: router-behavior for normal router discovery~~ (merged)
* ~~#3628: address-less link-layer handling for NDP~~ (merged)
* ~~#3744: `gnrc_ipv6_nc` adaption for 6LoWPAN-ND~~ (merged)
* ~~#3745: `gnrc_ipv6_netif` adaptations for router discovery~~ (merged)
* ~~#3746: host-behavior for normal router discovery~~ (merged)
* ~~#3747: adaption of the NA send function to build ARO externally~~ (merged)
* ~~#3748: host-behavior for 6LoWPAN-ND~~ (merged)
* ~~#3749: router-behavior for 6LoWPAN-ND~~ (merged)

### CODE REVIEW

**Comment by authmillenon** [comment]
This is still very WIP. I'll focus on implementing the host behavior first (currently I ensured the forbidden actions are not executed and modified the interface initialization), so we can use it with a Linux or Contiki (border) router. After that router behavior (for the same reason) and finally the border router behavior.

**Comment by authmillenon** [comment]
Added #3143 as dependency.

**Comment by authmillenon** [comment]
Newest force-push of my ongoing work.

Depends now on #3159 too.

**Comment by authmillenon** [comment]
Updated. Now router behavior is implemented too.

**Comment by authmillenon** [comment]
Updated to latest version.

**Comment by authmillenon** [comment]
No longer WIP in that I implemented everything from RFC 6775 I planned to, but I never really came to test it.

**Comment by gebart** [comment]
needs rebase

**Comment by authmillenon** [comment]
Here too: And a lot more ;-)

**Comment by authmillenon** [comment]
WIP again.

**Comment by authmillenon** [comment]
Added #3734 as dependency.

**Comment by authmillenon** [comment]
Host behavior done.

**Comment by authmillenon** [comment]
Not WIP anymore again. If there is need: I can split this up further into smaller (but probably dependent) PRs.

**Comment by authmillenon** [comment]
Features missing: Multihop DAD (the old one did not have this either and that's a nice addition for next release :-)) and multiple BR in a LoWPAN (afaik there isn't even a specification for that, it's out of scope of RFC6775 at least).

**Comment by authmillenon** [comment]
Restructured PR to only import the border router functionality. All other functionality is now provided by the dependent PRs (see description)

**Comment by authmillenon** [comment]
Rebased to current #3749.

**Comment by authmillenon** [comment]
Rebased to current #3749.

**Comment by authmillenon** [comment]
Rebased to current #3749

**Comment by authmillenon** [comment]
Rebased to current #3749

**Comment by OlegHahm** [comment]
needs rebase

**Comment by authmillenon** [comment]
Done

**Comment by OlegHahm** [comment]
needs rebase

**Comment by authmillenon** [comment]
Rebased

**Comment by OlegHahm** [comment]
ACK!

**Comment by authmillenon** [comment]
Thanks for the review. This was a long way coming :D

**Comment by OlegHahm** [comment]
What happened to the good old "the border router will be ready soon"?

**Comment by authmillenon** [comment]
The border router… is done :D

**Pull request merged**
