### PR TITLE
sixlowpan: rename to sixlowpan_legacy

### PR DESCRIPTION
**Pull request by authmillenon**
Since #1680 turns out to become quite a nightmare review-wise, I decided to split and clean it up a little. First point on the agenda is to make it more or less independent from the old 6LoWPAN module. For this I renamed the old module to `sixlowpan_legacy` and I will remove the move commit from #1680. Though I recycled lot of the original code in #1680, it is not what it used to be, so the changes wouldn't be that visible anyways.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to master

**Comment by authmillenon** [comment]
Will rebase next either after review of #1680 or when heavy changes to rpl stop.

**Comment by OlegHahm** [comment]
I think we should not rename this before the new network stack is ready anyways. In the best case we don't need this PR and can just remove the old implementation completely.

**Comment by authmillenon** [comment]
Yes of course: the goal of this PR is more to get the old implementation out of the way to give me breathing room for the new implementation, than a thing I actually want to do ;-)

**Comment by authmillenon** [comment]
Abandoned. New implementation will get a `ng_` prefix (see #2278)

**Pull request closed without merging**
