### PR TITLE
core: fix thread_print_stack macro

### PR DESCRIPTION
**Pull request by travisgriggs**
thread_print_stack() currently has a compilation error because it expands to thread_arch_print_stack, but the arch files all define thread_arch_stack_print (note the order).

An alternate fix would be to leave the define as is, but change the C functions to match. Either way, it's a function that doesn't compile as advertised.

As an aside, I find the name of the function a bit misleading. It actually *seems* to print the current call *frame* size (as opposed to the total stack size or position). At least I think.

### CODE REVIEW

**Comment by kaspar030** [comment]
Seems like noone has ever used this...

**Comment by kaspar030** [comment]
> An alternate fix would be to leave the define as is, but change the C functions to match. Either way, it's a function that doesn't compile as advertised.

The C functions actually have documentation and a prototype in the same header, so I guess this PR is more a typo fix...

**Comment by kaspar030** [comment]
Murdock doesn't like the commit starting with "fix". Maybe prepend "core:" to the commit message?

**Comment by smlng** [comment]
@travisgriggs please change the commit message (use `git commit --amend`) as suggested by @kaspar030 - this will make Murdock happy, too.

**Comment by travisgriggs** [comment]
Sorry for the delay. I *think* I've fixed this now.

**Comment by travisgriggs** [comment]
Sigh, do I need to squash now?

**Comment by kaspar030** [comment]
> Sigh, do I need to squash now?

We need to get rid of the merge commit... Probably the easiest is to rebase the branch on master, then do ```git reset master```. That should leave you with just the changes of this PR, uncommitted. Then you can create a new commit, and force-push.

(creating a backup branch is advisable, just in case...)

**Comment by kaspar030** [comment]
> Probably the easiest is to rebase the branch on master

I'm just realizing that this is a oneline-change, so there might be simpler ways. ;)

**Comment by OlegHahm** [comment]
ping

**Comment by travisgriggs** [comment]
I'll redo this. My git skills are not up to untangling whatever I screwed up. Since it's a one line, seems just easier to redo it. I'll commit to getting it done in the next couple of hours.

**Comment by OlegHahm** [comment]
Thanks!

**Comment by travisgriggs** [comment]
Resubmitted as #7668. I'll close/destroy/withdraw this one after that one goes in.

**Comment by miri64** [comment]
#7668 was merged.

**Pull request closed without merging**
