### PR TITLE
github: move ISSUE_TEMPLATE.md to ISSUE_TEMPLATE/bug_report.md

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
GitHub supports different types of issue templates for a while now.
The following types are supported:

* Bug report
  (living in `.github/ISSUE_TEMPLATE/bug_report.md`),
* Feature request
  (living in `.github/ISSUE_TEMPLATE/feature_request.md`), and
* Custom issue template
  (living in `.github/ISSUE_TEMPLATE/custom.md`)

Our current issue template is mostly a bug report template, so this
moves it to `.github/ISSUE_TEMPLATE/bug_report.md`.

### Issues/PRs references
None

### CODE REVIEW

**Comment by aabadie** [comment]
For reference, can you provide a link to the GH documentation page ? Maybe also add in this PR, a `feature_request.md` ?

**Comment by miri64** [comment]
> For reference, can you provide a link to the GH documentation page ?

https://help.github.com/articles/about-issue-and-pull-request-templates/#issue-templates I guess, but for me it came to my attention due to the [community profile checklist](https://github.com/RIOT-OS/RIOT/community) not being complete anymore. 

>  Maybe also add in this PR, a `feature_request.md` ?

I leave that to someone else

**Comment by miri64** [comment]
> I leave that to someone else

(But above all else I also think this doesn't belong here)

**Comment by miri64** [comment]
> After reading the new documentation, I think this PR makes sense and should be merged. We can discuss later what other issue template we want to have and add them.

That was my intent.

**Comment by miri64** [comment]
Just needed some meta-data. See #9529

**Pull request merged**
