### PR TITLE
cpu/lm4f120: fix ADC pin mapping

### PR DESCRIPTION
**Pull request by dkm**
fix GPIO pin mapping for ADC_0 and use macro to make the mapping less error-prone

### CODE REVIEW

**Comment by haukepetersen** [comment]
big dislike -> I think it does not really make it more error prone while introducing an additional layer of macro. NACK from my side (though this might highly subjective). But one of the style goals for RIOT is, to restrict macro usage to only where it's really needed, and in this place I would say this is not the case.

**Comment by dkm** [comment]
Ok. I can still fix the big struct init, but I think it's harder to match it with the documentation. Should I rework the patch ?

**Comment by haukepetersen** [comment]
Yes, that would be great!

**Comment by dkm** [comment]
Done. I've reverted to the previous verbose struct init, but with the mapping corrected.

**Comment by haukepetersen** [comment]
ACK once Murdock is green

**Comment by dkm** [comment]
Thanks !

**Pull request merged**
