### PR TITLE
tests/lwip: stabalize test script

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While running this test script, I encountered the problem, that the process for the previous test was not finished, not allowing the next test to use its TAP interface. This small timer should fix that.

### Testing procedure
```sh
BOARD=native make -C tests/lwip all test
```

passes.

### Issues/PRs references
None

### CODE REVIEW

**Comment by gschorcht** [comment]
@miri64 How should the test environment loooks like to execute the test. I have set up two `tap` devices
```
sudo ip tuntap add dev tap0 mode tap user $(id -u -n)
sudo ip tuntap add dev tap1 mode tap user $(id -u -n)
sudo ip link set up tap0
sudo ip link set up tap1
```
but it doesn't work.

**Comment by miri64** [comment]
@gschorcht just run `sudo dist/tools/tapsetup/tapsetup` before. Sorry I usually just run this once after startup, so I always forget it to add to the testing procedures 😅

**Comment by miri64** [comment]
(or you just create a bridge between the interfaces yourself)

**Comment by gschorcht** [comment]
> (or you just create a bridge between the interfaces yourself)

Yeah, of course. That's easy for me. The test works.

**Comment by miri64** [comment]
> 

Oops :relaxed:

**Pull request merged**
