### PR TITLE
tapsetup: fix typo in usage text

### PR DESCRIPTION
**Pull request by dimka-rs**
tapsetup: fix typo in usage text

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
I have some kind of deja-vu, but wasn't able to find any reference to this in the currently open PRs (maybe a fix I have done myself but did not manage to PR...) Anyway, totally makes sense! ACK!

**Comment by miri64** [comment]
Ah, can you please format your commit message in accordance with our [contributing guidelines](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md#commit-conventions), please? E.g. `tapsetup: fix typo in usage text`.

**Comment by dimka-rs** [comment]
Is it correct now?

**Comment by miri64** [comment]
> Is it correct now?

Yepp. Let's merge this :-).

**Pull request merged**
