### PR TITLE
build system: error on conflicting features 

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

When the build system is aware of an invalid configuration - such as multiple C libs being used or a single piece of hardware being used in two conflicting roles - this now is treated as an error rather than a warning.

Because of this, the app `tests/build_system/warn_conflict` can no longer be build and is obsolete. It is removed in the second commit.

> [!NOTE]
> The static tests in `dist/tools/feature_resolution/check.sh` already covers testing the build system feature resolution, including feature conflicts.

#### `master`

```
$ FEATURES_REQUIRED='periph_rtt periph_rtc' BOARD=nucleo-f103rb make -C examples/default
make: Entering directory '/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/examples/default'
The following features may conflict: periph_rtc periph_rtt
Rationale: On the STM32F1, the RTC and RTT map to the same hardware peripheral. Only one standard C library can be used. Only one GPIO IRQ implementation can be used. Package tinyUSB is not yet compatible with periph_usbdev.

EXPECT undesired behaviour!
[...]
```

==> builds successfully a defunct app

#### This PR

```
$ FEATURES_REQUIRED='periph_rtt periph_rtc' BOARD=nucleo-f103rb make -C examples/default 
make: Entering directory '/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/examples/default'
The following features conflict: periph_rtc periph_rtt
Rationale: On the STM32F1, the RTC and RTT map to the same hardware peripheral. Only one standard C library can be used. Only one GPIO IRQ implementation can be used. Package tinyUSB is not yet compatible with periph_usbdev.
/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/examples/default/../../Makefile.include:1006: *** You can let the build continue on expected errors by setting CONTINUE_ON_EXPECTED_ERRORS=1 to the command line.  Stop.
make: Leaving directory '/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/examples/default'
```

==> does not build a defunct app

### Issues/PRs references

None

### CODE REVIEW

**Comment by Enoch247** [comment]
Have you done any digging through git logs or old PRs to verify that conflict resolution has always been a warning and not an error. I'd like to make sure that we aren't reverting a feature that was needed for forgotten reasons.

**Comment by maribu** [comment]
It seems to be added ~10 years ago as a warning in f9a79eee41a723943a53da1ff7d26586094d9672 and unchanged ever since.

**Review by Enoch247 — APPROVED** [review]
I tested, and the change works as described. 

If a user really wishes to ignore the conflict, they can still bypass this error by setting `CONTINUE_ON_EXPECTED_ERRORS=1`.

Shall I merge?

**Comment by maribu** [comment]
Thx :)

**Pull request merged**
