### PR TITLE
tests: revert gnrc_netif2 Makefile to resolve merge conflict

### PR DESCRIPTION
**Pull request by miri64**
Not sure this does work, but I'm a little desperate now. If it doesn't work we still can reset it back to the commits parent in `gnrc_netif2_integration/master` as I did with #8074.

### CODE REVIEW

**Comment by miri64** [comment]
I adapted the test to the renaming now so it should compile now ;-)

**Comment by haukepetersen** [comment]
and go.

**Comment by miri64** [comment]
Thanks!

**Comment by haukepetersen** [comment]
youre welcome :-)

**Comment by miri64** [comment]
(Put this into TODO, so I remember to remove this again, once #7925 is merged)

**Pull request merged**
