### PR TITLE
release-notes: add 2018.01

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

update release notes for 2018.01

### CODE REVIEW

**Comment by miri64** [comment]
Mhhh... as far as I can see [the release is already out](https://github.com/RIOT-OS/RIOT/releases/tag/2018.01), but the release notes are [not in it](https://github.com/RIOT-OS/RIOT/blob/2018.01/release-notes.txt).

**Comment by smlng** [comment]
ah damn, my bad wrong order - am I allowed to update the release tag?

**Comment by smlng** [comment]
I basically followed https://github.com/RIOT-OS/RIOT/wiki/%5Bdraft%5D-Managing-a-Release#actual-release

**Comment by miri64** [comment]
You are right, that is in the wrong order :-/... But no high would highly discourage to update the release tag.

**Comment by miri64** [comment]
What you *can* do is add a follow-up release, e.g. 2018.01.1. But maybe wait with that until #8499 was backported ;-).

**Comment by miri64** [comment]
Updated the wiki page, so the next release manager doesn't fall into that trap ;-)

**Comment by miri64** [comment]
> But no high [sic] would highly discourage to update the release tag.

I'm not even sure how GitHub's release system would handle a force push of a tag... The release refers to the SHA of the annotated tag, not it's reference name, so in the end it would most likely still point to the outdated tag.

**Pull request merged**
