### PR TITLE
micro-ecc: require hardware RNG

### LINKED ISSUE #5943: pkg: micro-ecc: missing dependency to periph/random
Trying to build #5914 I realized that the micro-ecc package requires a hardware RNG, which is apparently not modeled correctly.

### PR DESCRIPTION
**Pull request by cgundogan**
fixes #5943

### CODE REVIEW

**Comment by mtausig** [comment]
I'd prefer if you put the `FEATURES_REQUIRED += periph_hwrng` line in the `Makefile.dep` right in the package directory. The central Makefiles shouldn't contain any specifics about the packages.

**Comment by cgundogan** [comment]
@mtausig I addressed your comment

**Comment by miri64** [comment]
Regarding the dtls-echo issue in Murdock: #6032.

**Comment by cgundogan** [comment]
@mtausig how about this?

**Comment by cgundogan** [comment]
squashed

**Comment by miri64** [comment]
Backport needed.

**Comment by miri64** [comment]
Backport provided in https://github.com/RIOT-OS/RIOT/pull/6049.

**Pull request merged**
