### PR TITLE
examples: nanocoap: add comment regarding resource sorting

### PR DESCRIPTION
**Pull request by kaspar030**

### CODE REVIEW

**Comment by miri64** [comment]
ACK and go when Murdock is happy.

**Comment by OlegHahm** [comment]
Is this only relevant for the example?

**Comment by miri64** [comment]
As far as I know this is relevant for all of nanocoap, but nanocoap is imported as a package, so where to put the doc otherwise?

**Comment by miri64** [comment]
@OlegHahm ping? I would like to merge.

**Comment by OlegHahm** [comment]
> As far as I know this is relevant for all of nanocoap, but nanocoap is imported as a package, so where to put the doc otherwise?

In the nanocoap documentation that should be provided in `pkg/nanocoap`.

**Comment by kaspar030** [comment]
> In the nanocoap documentation that should be provided in pkg/nanocoap.

Still I'd say the comment this PR adds is useful, regardless of otherwise missing doc for nanocoap.

**Comment by miri64** [comment]
Then go.

**Comment by miri64** [comment]
(pkg needs more doc independent from nanocoap regardless ;-))

**Pull request merged**
