### PR TITLE
travis: reorder mcu groups

### PR DESCRIPTION
**Pull request by kaspar030**
The cortex-m groups take a lot longer, but they are started last. That often leads to one or two of them stalling the whole build process.

This PR arbitrarily reorders the MCU groups per gut-feeling.

### CODE REVIEW

**Comment by phiros** [comment]
This change would provide quicker feedback to people working on 
something that affects cortex m* boards. Since, a lot of devs are working on cortex m* related stuff
I think it makes sense to reorder this a little bit.

However, I think it would make sense to move the x86 group up so that you end up with an order like this:  

1. static
2. x86 (this is the only group which actually executes the unit tests instead of just building them; also the build time for this is relatively short)
3. cortex M* groups (not sure how they should be ordered in detail; I think we can work this out later)
4. avr8
5. msp430
6. arm7

**Comment by kaspar030** [comment]
My idea was to lower the overall time, having the unittests closer to the top defeats that goal. (But so does having static-tests.)

Usually, building cortex_m4 takes more time than it takes to start the last group + the buildtime of the last group, so I'd like to start that as early as possible. Cortex-M0 should be high up, too. The rest doesn't matter for the overall buildtime, so we can order them by feedback.

IMHO the static tests suck to do locally, as they always rebase, but everyone can build&try x86 unittests very quickly, so I think the static tests are more important as quick feedback than x86 is.

Would you be fine if we move x86 after static-tests, c-m4, c-m0?

**Comment by phiros** [comment]
Hmm, I am not completely sold on the argument that people could execute the unit tests locally. However, I think I could live with the order you proposed in your last comment.
-> You have my ACK as soon as you change the order (and travis is happy).

**Comment by kaspar030** [comment]
> I am not completely sold on the argument that people could execute the unit tests locally.

Well, ```# make -C tests/unittests clean all term``` takes 8 seconds on my shitty laptop.

Anyhow, 
- kind of addressed @phiros' comment, amended

**Comment by kaspar030** [comment]
This already feels faster. :)

**Comment by kaspar030** [comment]
&go.

**Pull request merged**
