### PR TITLE
tests: Build unit test suites individually

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by phiros** [comment]
@Kijewski are you still working on this?

**Comment by Kijewski** [comment]
@phiros worked on it.

**Comment by authmillenon** [comment]
Related to #3363?

**Comment by authmillenon** [comment]
Needs rebase.

**Comment by zhuoshuguo** [comment]
@Kijewski Ping. A kind reminder for rebase.

**Comment by authmillenon** [comment]
Needs rebase.

**Comment by Kijewski** [comment]
Abandoned for lack of time.

**Pull request closed without merging**
