### PR TITLE
sys: net: add netdev device driver using dev_eth low-level ethernet driver API

### PR DESCRIPTION
**Pull request by kaspar030**
Based on #2558. Depends on #2766.

This PR makes any ethernet device that implements #2766 available for the new network stack.

### CODE REVIEW

**Comment by authmillenon** [comment]
There ended somehow parts of #2600 up in here to. Can you please mention this in the description? ;-)

**Comment by kaspar030** [comment]
Sorry, that was transitive from #2558 if I understand correctly.
I'll try to refactor out unrelated commits.

**Comment by authmillenon** [comment]
Well you need it, if you want to implement multicast and broadcast. It's also very important that this stays in as examplary code for ethernet multicast address generation

**Comment by kaspar030** [comment]
I'll try to cut out dependencies in order to make reviewing easier...

**Comment by kaspar030** [comment]
Obsoleted by #2776.

**Comment by authmillenon** [comment]
(Can you close it then please)

**Pull request closed without merging**
