### PR TITLE
core/kernel_defines.h: add ARG_UNUSED macro

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds the ARG_UNUSED macro, available in several C projects (Zephyr, etc).
This:
```
void function(void *arg)
{
    /* arg variable is not used */
    (void) arg;
    ...
}
```
Becomes this:
```
void function(void *arg)
{
    /* arg variable is not used */
    ARG_UNUSED(arg);
    ...
}
```

This makes the code look more clear IMO.

### Testing procedure
Apply this patch with `git apply file.patch`

file.patch:
```
diff --git a/examples/ipc_pingpong/main.c b/examples/ipc_pingpong/main.c
index 655ff39a7..874bcb0af 100644
--- a/examples/ipc_pingpong/main.c
+++ b/examples/ipc_pingpong/main.c
@@ -26,7 +26,7 @@
 
 void *second_thread(void *arg)
 {
-    (void) arg;
+    ARG_UNUSED(arg);
 
     printf("2nd thread started, pid: %" PRIkernel_pid "\n", thread_getpid());
     msg_t m;
```

Compile the `ipc_pingpong` example with `ipc_pingpong`. Check there are no `unused variable` errors.

### Issues/PRs references
None so far

### CODE REVIEW

**Comment by kaspar030** [comment]
> This makes the code look more clear IMO.

I don't agree. ```(void) arg;``` is idiomatic C, it's meaning is clear and in the open.

```ARG_UNUSED()``` a custom macro. It *might* just be only defined to ```#define ARG_UNUSED(x) (void)x```, but I'd have to check when encountering it for the first time.

Using this macro also requires to include "kernel_macros.h" in possibly completely kernel-unrelated code, unnecessarily creating a dependency to a mess of macro code to possibly otherwise sane C.

Macros are bad. Avoid them at all costs.

**Comment by kaspar030** [comment]
Next thing we'll see is someone proposing ```FOREACH(entry, list)```. :wink:

**Comment by jia200x** [comment]
> From my side a clear NACK.

Ok

> Macros are bad. Avoid them at all costs.

Sometimes this feels like a vim vs emacs discussion IMO :). It's not like we don't use macros in RIOT... (LL utils, container_of, etc)

> Next thing we'll see is someone proposing FOREACH(entry, list). wink

I think there were already a couple of attempts

**Comment by jia200x** [comment]
I will just close it. Please re-open if needed

**Comment by gebart** [comment]
@kaspar030 
> Next thing we'll see is someone proposing `FOREACH(entry, list)`. wink

You mean like:
https://github.com/RIOT-OS/RIOT/blob/68dc5b0d6e0422df9c3653c2cb8021fc35974aae/sys/include/utlist.h#L468-L474

I agree though, `(void) x;` is such a common phrase that it should not need to be hidden behind a macro, it should be common knowledge among C developers that this is a way to mark an argument as unused.

**Pull request closed without merging**
