### PR TITLE
wolfSSL Alpha examples

### PR DESCRIPTION
**Pull request by kaleb-himes**
These examples have only been tested successfully on MAC OS X using the following toolchain:

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix

This is strictly an alpha release to allow the RIOT-OS community and wolfSSL community to begin collaborating! There may be portability issues if building with another gcc version. Please report all issues and direct all development related questions to support@wolfssl.com

For all other questions please contact info@wolfssl.com

We look forward to working with RIOT-OS community to provide an IoT friendly ssl/tls and/or cryptographic solution!

wolfSSL can be compiled for cryptography only by adding  ```WOLFCRYPT_ONLY``` to CFLAGS

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
Some comments:
- It is required per our development procedures that discussion and takes place on github (as opposed to email as your PR description says).
- I am kind of surprised that there is neither a package, (compare [documentation](http://api.riot-os.org/group__pkg.html)) nor code or at least a Makefile in the examples.
- Tests should go into [/tests](https://github.com/RIOT-OS/RIOT/tree/master/tests).

**Comment by kaleb-himes** [comment]
Hi LudwigKnuepfer,

1. I can change the names from ```Makefile.testname``` to just Makefile if that is more helpful.

2. Given that we had pre-existing tests that built fine it seemed unnecessary to write entirely new main.c, simpler to just copy them over from the wolfSSL package.

3. I will happily move to the test/ directory if that is preferred!

**Comment by kYc0o** [comment]
As Ludwig suggests, this kind of new features should be located on the pkg/ folder, where you add some Makefiles which will download automatically the new code, add some patches if necessary and compile it (either using RIOT's compiling rules or upstream, you can get examples of this in any pkg_* prefixed test).

The test should be located under tests/ on which the Makefile should use the associated pkg (look for instance to tests prefixed by pkg_* on the tests folder) and eventually a main program performing the tests.

As far as I can see, everything is based on scripts which will do the job, which is not very common in RIOT, but neither is forbidden nor non-recommended. I'd like to have the opinion of @OlegHahm or @kaspar030 on this.

Whenever possible, we prefer Markdown readme, but that's just a detail.

Commits should be also prefixed by the place where they are modifying/adding code, for instance:

tests/wolfSSL: adding wolfSSL package tests

Any commit addressing reviewers comments should not be squashed until the reviewer ACK your PR. Those commits can have any name and description.

I'll test it asap and give feedback, but this PR needs to reorganise the way wolfSSL is added to RIOT before getting merged.

Thanks for your contribution!

**Comment by kaleb-himes** [comment]
Hi @OlegHahm and @kYc0o

Excellent suggestions! I will research your documentation on how to create a package in this manner. I agree that would be far more convenient from a developer standpoint to be able to add ```USEPKG += wolfssl``` to the Makefile.

Thank you so much for all the feedback and helpful commentary thus far!

**Comment by OlegHahm** [comment]
Great!

Let us know if you have problems or questions regarding the documentation and creating a package. We will happily help you and may have a chance to improve the docs.

**Comment by kaleb-himes** [comment]
Thank you, will do!

**Comment by emmanuelsearch** [comment]
@kaleb-himes what's the latest on this?
FYI we have release planned at the end of the month ;)

**Comment by kaleb-himes** [comment]
Hi @emmanuelsearch 

We have been extremely busy since the 1st of the year and it has severely impacted my progress on this. No rush before your release, it may be some time before I am free to look into generating the requested "package". We have RSA 2017 quickly approaching and many paid projects in the queue!

Once we get some breathing room again this will be one of the first things on my to-do list.

Warmest Regards,

Kaleb

**Comment by miri64** [comment]
People are asking for the progress of this PR ;-) https://twitter.com/wolfSSL/status/857376741706186752

**Comment by miri64** [comment]
Ping?

**Comment by kYc0o** [comment]
Hi @kaleb-himes! Do you have some progress on this PR?

**Comment by kaleb-himes** [comment]
Closing this pull request based on feedback. wolfSSL has instead created a "PKG" solution and opened a new PR. See new PR here: https://github.com/RIOT-OS/RIOT/pull/7348

**Pull request closed without merging**
