### PR TITLE
cortexm_common: Add thread info to hard fault handler

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

While the hard fault handler prints the offending program counter, it
does not print information about the context triggering the hard fault.
This commit adds a line printing the thread ID and name that triggered
the hard fault. 

~~If the hard fault is triggered during an ISR, it only~~
~~prints that the hard fault happened during ISR context, not which ISR~~
~~triggered it. This is mostly because I have no clue how to get the preempted ISR number from the cortex-m core.~~

### Testing procedure

Use `tests/fault_handler` to trigger a hard fault and print the new line.

### Issues/PRs references

None

### CODE REVIEW

**Comment by bergzand** [comment]
> This is mostly because I have no clue how to get the preempted ISR number from the cortex-m core.

This can of course be grabbed from the PSR registered pushed on the stack

**Comment by bergzand** [comment]
> This can of course be grabbed from the PSR registered pushed on the stack

Modified to include this information.

**Review by benpicco — APPROVED** [review]
This sure is a helpful addition!

**Comment by fjmolinas** [comment]
Since ROM overflowed for `nucleo-l031k6`:

- master:

```
Building application "hello-world" for "nucleo-l031k6" with MCU "stm32".

   text	   data	    bss	    dec	    hex	filename
   8212	    112	   2556	  10880	   2a80	/data/riotbuild/riotbase/examples/hello-world/bin/nucleo-l031k6/hello-world.elf

```

- pr

```
Building application "hello-world" for "nucleo-l031k6" with MCU "stm32".

   text	   data	    bss	    dec	    hex	filename
   8360	    112	   2556	  11028	   2b14	/data/riotbuild/riotbase/examples/hello-world/bin/nucleo-l031k6/hello-world.elf

```

**Comment by fjmolinas** [comment]
@bergzand lets just remove the extra space and get this one done, I think its a bad habit to skip compile test for changes that touch code, it can lead down a slippery slope.

**Comment by bergzand** [comment]
> lets just remove the extra space

Removed!

**Comment by bergzand** [comment]
@fjmolinas All green (again)

**Comment by fjmolinas** [comment]
Go!

**Comment by bergzand** [comment]
Thanks!

**Pull request merged**
