### PR TITLE
pkg/wolfssl: bump version to 4.7.0

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Update to the latest upstream release

https://www.wolfssl.com/docs/wolfssl-changelog/

### Testing procedure

`tests/pkg_wolfssl` should still pass.

#### same54-xpro

```
2021-03-05 18:20:41,946 # wolfSSL Crypto Test!
2021-03-05 18:20:42,953 # ------------------------------------------------------------------------------
2021-03-05 18:20:42,955 #  wolfSSL version 4.7.0
2021-03-05 18:20:42,962 # ------------------------------------------------------------------------------
2021-03-05 18:20:42,966 # error    test passed!
2021-03-05 18:20:42,968 # MEMORY   test passed!
2021-03-05 18:20:42,970 # base64   test passed!
2021-03-05 18:20:42,972 # asn      test passed!
2021-03-05 18:20:42,979 # RANDOM   test passed!
2021-03-05 18:20:43,023 # SHA-256  test passed!
2021-03-05 18:20:43,169 # SHA-384  test passed!
2021-03-05 18:20:43,314 # SHA-512  test passed!
2021-03-05 18:20:43,317 # Hash     test passed!
2021-03-05 18:20:43,319 # HC-128   test passed!
2021-03-05 18:20:43,321 # Chacha   test passed!
2021-03-05 18:20:43,323 # POLY1305 test passed!
2021-03-05 18:20:43,327 # ChaCha20-Poly1305 AEAD test passed!
2021-03-05 18:20:43,329 # AES      test passed!
2021-03-05 18:20:43,331 # AES192   test passed!
2021-03-05 18:20:43,333 # AES256   test passed!
2021-03-05 18:20:51,619 # ECC      test passed!
2021-03-05 18:20:52,485 # ECC buffer test passed!
2021-03-05 18:20:57,201 # CURVE25519 test passed!
2021-03-05 18:21:29,709 # ED25519  test passed!
2021-03-05 18:21:29,711 # logging  test passed!
2021-03-05 18:21:29,713 # mutex    test passed!
2021-03-05 18:21:29,714 # Test complete
2021-03-05 18:21:29,716 # wolfSSL Benchmark!
2021-03-05 18:21:29,722 # ------------------------------------------------------------------------------
2021-03-05 18:21:29,724 #  wolfSSL version 4.7.0
2021-03-05 18:21:29,731 # ------------------------------------------------------------------------------
2021-03-05 18:21:29,736 # wolfCrypt Benchmark (block bytes 1024, min 1.0 sec each)
2021-03-05 18:21:30,754 # RNG                925 KB took 1.010 seconds,  916.269 KB/s
2021-03-05 18:21:31,762 # AES-128-CBC-enc    825 KB took 1.002 seconds,  823.472 KB/s
2021-03-05 18:21:32,788 # AES-128-CBC-dec    775 KB took 1.021 seconds,  759.267 KB/s
2021-03-05 18:21:33,818 # AES-192-CBC-enc    650 KB took 1.025 seconds,  634.371 KB/s
2021-03-05 18:21:34,834 # AES-192-CBC-dec    600 KB took 1.011 seconds,  593.686 KB/s
2021-03-05 18:21:35,881 # AES-256-CBC-enc    550 KB took 1.041 seconds,  528.260 KB/s
2021-03-05 18:21:36,910 # AES-256-CBC-dec    500 KB took 1.023 seconds,  488.577 KB/s
2021-03-05 18:21:37,919 # CHACHA               3 MB took 1.004 seconds,    3.454 MB/s
2021-03-05 18:21:38,928 # CHA-POLY             2 MB took 1.004 seconds,    2.334 MB/s
2021-03-05 18:21:39,934 # POLY1305            10 MB took 1.000 seconds,    9.838 MB/s
2021-03-05 18:21:40,941 # SHA-256              2 MB took 1.001 seconds,    2.316 MB/s
2021-03-05 18:21:41,978 # SHA-384            725 KB took 1.032 seconds,  702.654 KB/s
2021-03-05 18:21:43,015 # SHA-512            725 KB took 1.032 seconds,  702.679 KB/s
2021-03-05 18:21:44,169 # ECC   [      SECP256R1]   256 key gen         4 ops took 1.145 sec, avg 286.261 ms, 3.493 ops/sec
2021-03-05 18:21:45,895 # ECDHE [      SECP256R1]   256 agree           4 ops took 1.145 sec, avg 286.179 ms, 3.494 ops/sec
2021-03-05 18:21:47,118 # ECDSA [      SECP256R1]   256 sign            4 ops took 1.214 sec, avg 303.458 ms, 3.295 ops/sec
2021-03-05 18:21:48,245 # ECDSA [      SECP256R1]   256 verify          2 ops took 1.118 sec, avg 559.143 ms, 1.788 ops/sec
2021-03-05 18:21:49,542 # CURVE  25519 key gen         3 ops took 1.290 sec, avg 429.968 ms, 2.326 ops/sec
2021-03-05 18:21:52,120 # CURVE  25519 agree           4 ops took 1.711 sec, avg 427.746 ms, 2.338 ops/sec
2021-03-05 18:21:53,436 # ED     25519 key gen         3 ops took 1.308 sec, avg 436.055 ms, 2.293 ops/sec
2021-03-05 18:21:55,658 # ED     25519 sign            4 ops took 1.779 sec, avg 444.628 ms, 2.249 ops/sec
2021-03-05 18:21:57,487 # ED     25519 verify          2 ops took 1.822 sec, avg 910.872 ms, 1.098 ops/sec
2021-03-05 18:21:57,488 # Benchmark complete
```

### Issues/PRs references

upstream PR for the minor fix to `test.c`: https://github.com/wolfSSL/wolfssl/pull/3829

### CODE REVIEW

**Review by pokgak — APPROVED** [review]
LGTM

**Comment by miri64** [comment]
Murdock is not happy though. Also, @benpicco, do you want to address the static check warnings, while you are in those files?

**Review by miri64 — COMMENTED** [review]
> pkg/wolfssl/include/user_settings.h#L1
>
> `no copyright notice found`

I guess since you are not the original author, this can't be addressed by you ;-)

> pkg/wolfssl/include/user_settings.h#L37
>
> `too many consecutive empty lines`

But this one can be :-)

**Comment by benpicco** [comment]
I still have to look into the size increase.
Maybe `WOLFSSL_SP_MATH_ALL` is too broad, the build complained about a missing function so I tried that.

**Comment by elms** [comment]
@benpicco I think there are two ways to solve this. I haven't looked at the details of what functions are used so may be missing something.

1. Only configure SP with algorithms
`WOLFSSL_SP_MATH` is used with certain algorithms, so if they are all disabled, then it's not built. For example `./configure --enable-sp --enable-sp-math --disable-dh --disable-ecc --disable-rsa` disables sp and generates an error since no algorithms will use it.

I think you can move the SP defines lower and wrap them to fix the error.

<details>
<summary>Diff</summary>

```
--- riot_user_settings.h        2021-04-19 13:13:55.654229797 -0700
+++ riot_user_settings_sp.h     2021-04-19 14:21:03.516567600 -0700
@@ -26,14 +26,6 @@
 // #define DEBUG_WOLFSSL
 // #define WOLFSSL_LOG_PRINTF
 
-/* Single precision math */
-#define WOLFSSL_SP_MATH
-#define WOLFSSL_SP_SMALL
-#define SP_WORD_SIZE 32
-#define WOLFSSL_SP
-
-
-
 /* GNRC support enabled if not
  * using sockets
  */
@@ -181,7 +173,6 @@
 #define HAVE_ECC
 #define FP_ECC
 #define WOLFSSL_HAVE_SP_ECC
-#define WOLFSSL_HAVE_SP_ECC
 #define ECC_TIMING_RESISTANT
 #define HAVE_SUPPORTED_CURVES
 #endif
@@ -309,6 +300,14 @@
 #define BUILD_TLS_AES_128_GCM_SHA256
 #endif
 
+#if defined(WOLFSSL_HAVE_SP_DH) ||  defined(WOLFSSL_HAVE_SP_RSA) ||  defined(WOLFSSL_HAVE_SP_ECC)
+/* Single precision math */
+#define WOLFSSL_SP_MATH
+#define WOLFSSL_SP_SMALL
+#define SP_WORD_SIZE 32
+#define WOLFSSL_SP
+#endif
+
 #ifdef __cplusplus
 }
 #endif
```

</details>

2. Fall back

If this doesn't address the issue for some reason that I am overlooking. Then I'd like to understand the use-case and we can expand the inclusion of some functions. I think this [change](https://github.com/wolfSSL/wolfssl/compare/master...elms:sp/riotos_fixes) with removing `WOLFSSL_SP_MATH_ALL` may be worth testing to address the missing `_sp_cmp`.

**Pull request closed without merging**
