### PR TITLE
Updating the README.md for examples/default

### PR DESCRIPTION
**Pull request by kushalsingh007**
- Removing the date command from the README.md since date is part of rtc now.

### CODE REVIEW

**Comment by kushalsingh007** [comment]
I accidently created another PR for the issue. Sorry for that , I have closed the other copy of this  
#2536.

**Comment by kushalsingh007** [comment]
Could someone please tell me why the build keeps failing ? I had a look at the output of the build but I still couldn't figure out why it failed ?

**Comment by gebart** [comment]
Travis is very flaky... see #1377

**Comment by OlegHahm** [comment]
Shouldn't be `date` replaced by `rtc` instead?

**Comment by kushalsingh007** [comment]
@OlegHahm  I do not have the corresponding description for rtc , can you give me the description for it. Even better can you give me output of  the `help` command on an msba2 : I guess output in the current README.md  is pretty old now ~1 year old :)

**Comment by kushalsingh007** [comment]
Done with the changes ... added rtc for the command.

**Comment by kushalsingh007** [comment]
I guess this one can be closed now.

**Comment by authmillenon** [comment]
Okay

**Comment by authmillenon** [comment]
Just kidding ;-)

**Comment by kushalsingh007** [comment]
:P

**Comment by authmillenon** [comment]
Just checked the order of commands: according to [`sys/shell/commands/shell_commands.c`](https://github.com/RIOT-OS/RIOT/blob/master/sys/shell/commands/shell_commands.c#L249) `rtc` comes after the `mersenne_` commands. After a quick check running it on native it seems like this too. Could you move it to this position?

**Comment by kushalsingh007** [comment]
Moved it and squashed it too with the previous one( sorry, couldn't resist  ).
* Regarding the ability to restart a build , clicking the button does not allow me to restart the build.
I guess the owner level access allows you to do it (but not the collaborator level access).

**Comment by kushalsingh007** [comment]
All is well :)

**Comment by authmillenon** [comment]
ACK and go. :-)

**Pull request merged**
