### PR TITLE
board:stm32f0discover LED name fixes 

### PR DESCRIPTION
**Pull request by anandsr21**
Previously Green LED was mapped to Blue LED and Red LED was mapped to Green LED.
This patch fixes it by mapping the Green LED to Green LED and Red LED to Blue LED.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@anandsr21 ACK for the LED fix. Please try to push just YOUR changes from a separate branch like described in our [Development procedures](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures). If you need help with git refer to the [git cheatsheet](https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet).

**Comment by anandsr21** [comment]
Hi Peter,

I am learning GIT/GitHub.

I did committed only one file with those six lines changed.

I should have created a branch, before sending my PR.

Sorry, next time I will be more careful.

regards,
-anand

**Comment by LudwigOrtmann** [comment]
Please use module prefixes for the commit messages and keep the first line to the maximum length that is still displayed completely in github. Use `git log` for a exemplary commit messages.

**Comment by PeterKietzmann** [comment]
@anandsr21 are you planning to address my above comment? You just changed one file so you could easily start from the beginning to learn a developement-cycle for RIOT. Just follow the [Developement Procedures](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures) from the beginning

**Comment by anandsr21** [comment]
Hi Peter,

Oh. I was under the impression that the code was merged.

I will do it now.

regards,
-anand

**Comment by PeterKietzmann** [comment]
Closing this PR in favor of #2966

**Comment by anandsr21** [comment]
Hi Peter,

I have created a new Pull request. It should be fine this time.

regards,
-anand

**Pull request closed without merging**
