### PR TITLE
gnrc_uhcpc: ensure compression context is managed by the ABR

### PR DESCRIPTION
**Pull request by miri64**
### Testing procedure
Flash `gnrc_border_router` and `gnrc_networking` to a node respectively. Run `make term` for the border router using UHCP. When the `gnrc_networking` node receives its prefix it also should receive a 6LoWPAN compression context. Check with

```
2020-03-05 13:04:23,477 #  6ctx
2020-03-05 13:04:23,477 # cid|prefix                                     |C|ltime
2020-03-05 13:04:23,478 # -----------------------------------------------------------
2020-03-05 13:04:23,478 #   0|                             2001:db8::/64 |1|   60min
```

When restarting the `make term` the border router with (do **not** reset or reflash)

```sh
IPV6_PREFIX=2001:db8:1::/64 make -C examples/gnrc_border_router/ term
```

the old context should be removed and replaced with the new one when the prefix is updated:

```
6ctx
6ctx
cid|prefix                                     |C|ltime
-----------------------------------------------------------
  0|                             2001:db8::/64 |1|   60min
> uhcp_client(): sending REQ...
got packet from fe80::20e3:19ff:feee:2a93 port 39409
uhcp: push from fe80::20e3:19ff:feee:2a93:39409 prefix=2001:db8:1::/64
gnrc_uhcpc: uhcp_handle_prefix(): removed old prefix 2001:db8::28ab:dc15:5401:6478/64
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8:1:0:28ab:dc15:5401:6478/64
gnrc_uhcpc: uhcp_handle_prefix(): configured new prefix 2001:db8:1:0:28ab:dc15:5401:6478/64
6ctx
6ctx
cid|prefix                                     |C|ltime
-----------------------------------------------------------
  0|                           2001:db8:1::/64 |1|   60min
```

### Issues/PRs references
Fixes regression mentioned in https://github.com/RIOT-OS/RIOT/pull/8576#issuecomment-594934664

### CODE REVIEW

**Comment by benpicco** [comment]
I just flashed `gnrc_border_router` on a `samr21-xpro` and with this the interfaces are not getting a public IP anymore:

```
sudo sh /home/benpicco/dev/RIOT-staging/dist/tools/ethos/start_network.sh  /dev/ttyACM1 tap0 2001:db8::/64
net.ipv6.conf.tap0.forwarding = 1
net.ipv6.conf.tap0.accept_ra = 0
----> ethos: sending hello.
----> ethos: activating serial pass through.
----> ethos: hello reply received        
> uhcp_client(): sending REQ...
got packet from fe80::5017:90ff:feba:857 port 56010
uhcp: push from fe80::5017:90ff:feba:857:56010 prefix=2001:db8::/64
gnrc_uhcpc: uhcp_handle_prefix(): got same prefix again
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8::80b4:739d:2f34:7a78/64

Iface  7  HWaddr: 00:36:6B:F5:09:3C 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          RTR_ADV  Source address length: 6
          Link type: wired
          inet6 addr: fe80::236:6bff:fef5:93c  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:fff5:93c
          inet6 group: ff02::1:ff00:2
          
Iface  6  HWaddr: 04:45  Channel: 26  Page: 0  NID: 0x23
          Long HWaddr: 82:B4:73:9D:2F:34:7A:78 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::80b4:739d:2f34:7a78  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff34:7a78
          
> 6ctx
cid|prefix                                     |C|ltime
-----------------------------------------------------------
  0|                             2001:db8::/64 |1|   59min

```

**Comment by miri64** [comment]
I am honestly dumb-founded how it worked before with the line I removed in the latest commit, but removed an extra address removal.

**Comment by benpicco** [comment]
Well now the compression context arrives at the nodes and routing works again 😃 
Please squash!

**Comment by miri64** [comment]
Squashed

**Pull request merged**
