### PR TITLE
tools/zep_dispatch: add topology generator

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This adds a small tool to generate topologies for `zep_dispatcher`.
It places a custom amount of nodes at random positions in a virtual space. The radio ranges of the nodes can be randomized too.

The network is then serialized into a format that can be consumed by `zep_dispatcher` as well as a data set of all nodes and their radio ranges that can be plotted using Gnuplot.

To aid debugging the 'radio circles' of the nodes are also colored: The root node gets assigned a random color, each node that has a bi-directional connection to the root inherits that color. If a node can only hear the root node, but not reach it, it will inherit the color value divided in half.

This process is repeated recursively for each node so that in the end all nodes that have an (in)direct connection to the root should have the same color.

### Testing procedure

`make run` in `dist/tools/zep_dispatch` will automatically generate a new topology if there is none yet.
Parameters can be adjusted in `topogen.sh`.

This will also produce a visualization of the network layout (requires Gnuplot)

All nodes that have a bi-directional connection to the root node (A) are colored turquoise. Nodes that can only receive packets from a node connected to the root node are colored green. Nodes that have no connection to the root network at all are black.

You can now start an instance of `examples/gnrc_networking` with `USE_ZEP=1` for each simulated node. The ZEP dispatcher will place it in a free spot in the network.

Once all spots are filled you can run `make graph` to produce a connection graph of all nodes in the simulated network (requires Graphviz) 

If you want a new topology, just delete `network.topo` and run `make run` again.

### Issues/PRs references

useful for #14623

### CODE REVIEW

**Review by fjmolinas — COMMENTED** [review]
I don't really use zep to much, but since you are actively maintaining it if you find it useful let's fo with it. Can you add a task so its built by murdock like other tools?

**Comment by benpicco** [comment]
Actually this should already be build: It's part of the `all` target in `zep_dispatch` which itself is part of the `HOST_TOOLS` list.

You can verify this by calling

    make -C dist/tools

You'll find that this also creates `dist/tools/zep_dispatch/bin/topogen`

**Comment by aabadie** [comment]
> It's part of the all target in zep_dispatch which itself is part of the HOST_TOOLS list.

I think @fjmolinas was asking to add a step in the tools-buildtest GH action: https://github.com/RIOT-OS/RIOT/blob/master/.github/workflows/tools-buildtest.yml. It's not there AFAICS.

**Comment by benpicco** [comment]
Ok, added.

**Review by aabadie — APPROVED** [review]
I trust you that it works. Please squash!

ACK

**Pull request merged**
