### PR TITLE
sys/shell: don't include suit command by default

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The `suit` command is pretty expensive as it calls `suit_worker_trigger()` which starts the SUIT worker thread.
If this function is not called otherwise, this will pull in the (quite substantial) suit worker thread stack.

### Testing procedure

If your application calls `suit_handle_url()` directly (doesn't make use of the worker thread) this saves `3 * THREAD_STACKSIZE_LARGE` Bytes of RAM.

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
bors merge

**Comment by benpicco** [comment]
Ah no hurry, we can fit more into the merge train

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel
bors merge

**Comment by benpicco** [comment]
bors status

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
