### PR TITLE
cpu/nrf5x: unified hwrng driver

### PR DESCRIPTION
**Pull request by haukepetersen**
moved the hwrng implementation for the NRF5x cpus into the common dir.

### CODE REVIEW

**Comment by haukepetersen** [comment]
this was broken somehow through rebasing, fixed and rebased on #4839

**Comment by authmillenon** [comment]
ACK when travis is happy and #4839 was merged.

**Comment by authmillenon** [comment]
Please rebase correctly. The SHA sums of the commits in this PR differ from the SHAs in #4839

**Comment by authmillenon** [comment]
Thanks!

**Comment by PeterKietzmann** [comment]
#4839 was merged, travis is happy, PR was rebased correctly. And go

**Comment by authmillenon** [comment]
I don't see that Travis is happy. Static tests were aborted and the M0 group containing the boards in question too. Let's hope Travis is happy later or we need to revert this ;).

**Comment by OlegHahm** [comment]
I'm not 100% sure, but I think I saw Travis showing green here, too.

**Comment by cgundogan** [comment]
https://travis-ci.org/RIOT-OS/RIOT/builds/112985091
Everything is OK.

For some reason travis started a second run for the same commit. So it shouldn't be a problem.

**Comment by cgundogan** [comment]
Seems like the second run for the same commit was triggered by @authmillenon closing/re-opening this PR

**Comment by authmillenon** [comment]
This is the build for this PR https://travis-ci.org/RIOT-OS/RIOT/builds/112986289.

https://travis-ci.org/RIOT-OS/RIOT/builds/112985091 was for #4839.

**Comment by cgundogan** [comment]
please open my link at look at the middle section. It states:
```
Commit 7c59f24
#4840: cpu/nrf5x: unified hwrng driver
Hauke Petersen authored and committed
```

It states the same for your link, too.

**Comment by authmillenon** [comment]
The commits below https://github.com/RIOT-OS/RIOT/pull/4840#issuecomment-190933158 are from this PR, the ones above are from #4839.

**Comment by authmillenon** [comment]
Okay.... this is indeed weird... Yeah then probably my impatience is at fault. :-)

**Pull request merged**
