### PR TITLE
cpu/lpc2387: cleanup PWM driver

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Works on msba2. However, I don't understand the pin configuration. According to [this](https://raw.githubusercontent.com/wiki/RIOT-OS/RIOT/images/MSBA2_layout.png) board diagram I see output on pins P2.2, P2.3, P2.4. The periph_conf.h says `PINSEL4` pin 2,3,4. @OlegHahm can you explain?

**Comment by haukepetersen** [comment]
I can: the lpc2387 has up to 10 `PINSELx` registers, in which they have two bit for each pin. So P0.0 is configured in PSEL0, while P2.0 would be configured in PSEL4. Accordingly, the settings for P2.2 etc are also made in PSEL4

**Comment by PeterKietzmann** [comment]
Murdock unhappy mostly for avsextreme

**Comment by haukepetersen** [comment]
oh, will look into this

**Comment by haukepetersen** [comment]
alright, `avsextrem` should now also build just fine.

**Comment by PeterKietzmann** [comment]
Still problems with `pttu` platform.

**Comment by OlegHahm** [comment]
Oh, I thought we already dropped support for this board.

**Comment by OlegHahm** [comment]
see #6384

**Comment by miri64** [comment]
#6384 was merged, please rebase.

**Comment by haukepetersen** [comment]
rebased.

**Comment by haukepetersen** [comment]
CIs are happy, @PeterKietzmann would you mind to approve?

**Pull request merged**
