### PR TITLE
doc: fix spelling in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by LukeTheEngineer**
Very simple modifications to sentence structure

### CODE REVIEW

**Review by maribu — APPROVED** [review]
Good catch, thanks!

**Comment by maribu** [comment]
Ah, wait, would you mind to change the commit message to match the pattern

`subsystem: abstract`

E.g. `doc: fix spelling in CONTRIBUTING.md`or `CONTRIBUTING.md: fix spelling` or something like that.

**Comment by LukeTheEngineer** [comment]
> Ah, wait, would you mind to change the commit message to match the pattern
> 
> `subsystem: abstract`
> 
> E.g. `doc: fix spelling in CONTRIBUTING.md`or `CONTRIBUTING.md: fix spelling` or something like that.

Done!

**Comment by maribu** [comment]
Thx for changing the PR title. Could you do the same with the commit message, e.g. by running:

```
git commit --amend
```

then the editor will open, allowing you to change the commit message. Finally, run


```
git push --force-with-lease
```

to also get the PR in sync with the local state.

**Comment by MrKevinWeiss** [comment]
:) I think there was a miscommunication.  The commit message should be `CONTRIBUTING.md: fix spelling` and one can change it by using the
```
git commit --amend
```

command.

**Comment by maribu** [comment]
> I think there was a miscommunication.

Indeed. Sorry for the confusion.

@LukeTheEngineer I did just change the commit message. The first PR is always a bit rough because of all the hoops to jump through. But the learning curve is not too steep and we are always eager to help and answer any questions.

The commit conventions regarding the naming and when and how to do squashing are the two most challenging hoops to jump through for new contributors, so you already now have learned 50% of this ;)

Anyway: Congratz for the first PR (about to be) merged and welcome to the community!

**Pull request merged**
