### PR TITLE
cc2650stk: remove XTIMER_SHIFT_ON_COMPARE definition

### PR DESCRIPTION
**Pull request by yogo1212**
only saw this afterwards :-(

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@A-Paul please compare #5310

**Comment by A-Paul** [comment]
@PeterKietzmann, valuable reference. Thanks. :-)

**Comment by A-Paul** [comment]
ACK and CI is green.

**Comment by PeterKietzmann** [comment]
So why don't you merge?

**Comment by A-Paul** [comment]
@PeterKietzmann, to keep the tension. :D

**Comment by A-Paul** [comment]
:rocket:

**Pull request merged**
