### PR TITLE
dist/tools/headerguards: annotate errors in Github Action

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides Github annotation support for the `headerguard` check.

### Testing procedure
I provided a test commit that will cause some annotations.

### Issues/PRs references
None

### CODE REVIEW

**Comment by aabadie** [comment]
This seems to work as expected. Please squash!

**Comment by miri64** [comment]
Removed the test commit.

**Review by aabadie — APPROVED** [review]
ACK!

**Comment by miri64** [comment]
Found a problem while annotating uncrustify that might also be a problem here, but I can provide that as a follow-up if necessary :-). Thanks for the review!

**Pull request merged**
