### PR TITLE
hash_string module : adding unittests and edge-case checks

### PR DESCRIPTION
**Pull request by kushalsingh007**
- Stopped calculation for hash_string if value exceeds ULLONG_MAX.
- Written unit-tests for hash_string
- Fixes  a part of #1131

### CODE REVIEW

**Comment by kushalsingh007** [comment]
This is my first time writing unit-tests in RIOT so there might be some (or a lot ) errors , do review the changes that I have made,

**Comment by Kijewski** [comment]
This is a very bad fix. Very bad, because a hash should not map every string longer than 7 characters to the same value. To tell it bluntly: The idea is terrible.

**Comment by kushalsingh007** [comment]
@Kijewski : I agree , but then can you suggest an alternative , Isn't it better to have the same value returned to the person calling the hash_string function (ULLONG_MAX) so that he can know that it failed other than having overflow.
Instead of returning ULLONG_MAX, I think we can also add a can_calculate_hash_value() which the programmer can call before calling the function ?

**Comment by Kijewski** [comment]
An overflow is not an error. It's a hash, so multiple inputs will map to the same value per definition. I see no need for any change in here.

**Comment by kushalsingh007** [comment]
Ok , I''ll remove the changes from the hash_string.c file and update the tests taking the overflow into account . ( If I recall correctly the architectural part does not affect the result after overflow , right ? )

**Comment by kushalsingh007** [comment]
Sorry for accidentally adding all the commit :( 
Here is the new PR with the proper changes  #2793

**Pull request closed without merging**
