### PR TITLE
dist/tools/uncrustify: annotate errors in Github Action

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides Github annotation support for the `uncrustify` check.

### Testing procedure
I provided a test commit that will cause some annotations.

### Issues/PRs references
None, but the check-script adaptation is similar to #15746 and #15747 as all generate patches.

### CODE REVIEW

**Comment by jia200x** [comment]
```
 Error: Uncrustify proposes the following patch:

--- a/core/mutex.c
+++ a/core/mutex.c
@@ -111,7 +113,7 @@ int mutex_lock_cancelable(mutex_cancel_t *mc)
DEBUG("PID[%" PRIkernel_pid "] mutex_lock_cancelable() "
"cancelled.n", thread_getpid());
}
-        return (mc->cancelled)?-ECANCELED: 0;
+        return (mc->cancelled) ? -ECANCELED : 0;
}
}

Error: Uncrustify proposes the following patch:

--- a/core/mutex.c
+++ a/core/mutex.c
@@ -185,6 +187,7 @@ void mutex_unlock_and_sleep(mutex_t *mutex)
void mutex_cancel(mutex_cancel_t *mc)
{
unsigned irq_state = irq_disable();
+
mc->cancelled = 1;

mutex_t *mutex = mc->mutex;
Error: Uncrustify proposes the following patch:

--- a/core/mutex.c
+++ a/core/mutex.c
@@ -197,8 +200,8 @@ void mutex_cancel(mutex_cancel_t *mc)
}

if ((mutex->queue.next != MUTEX_LOCKED)
-            && (mutex->queue.next != NULL)
-            && list_remove(&mutex->queue, (list_node_t *)&thread->rq_entry)) {
+        && (mutex->queue.next != NULL)
+        && list_remove(&mutex->queue, (list_node_t *)&thread->rq_entry)) {
/* Thread was queued and removed from list, wake it up */
if (mutex->queue.next == NULL) {
mutex->queue.next = MUTEX_LOCKED;
Error: Uncrustify proposes the following patch:
```

Nice one :)

**Review by jia200x — APPROVED** [review]
ACK. For some reason it doesn't always show the annotations, but this is clearly not related to this PR. I can see them in the job.

Please remove the bogus commit

**Comment by miri64** [comment]
Done.

**Comment by miri64** [comment]
Thanks for the review!

**Pull request merged**
