### PR TITLE
cpu/nrf5x: clean up periph_uart

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- nRF51: Use `uart_conf_t` for consistency with nRF52
- nRF52832: Use UARTE (UART with EasyDMA) over UART (without DMA), as done for all other nRF52 family members
- use `UARTE_PRESENT` to detect whether an UARTE can be used, rather than family names

### Testing procedure

UART should still work on

- [x] nRF51 (tested with `nrf51-dk`)
- [x] nRF52 other than nRF52832 (tested with `nrf52840-dk`)
- [x] nRF52832 (tested with `nrf52-dk`)

### Issues/PRs references

None

### CODE REVIEW

**Comment by dylad** [comment]
I can test it on nRF53 too probably tonight or tomorrow if you want.

**Comment by maribu** [comment]
> I can test it on nRF53 too probably tonight or tomorrow if you want.

That would be awesome! Thx :smile:

**Review by dylad — APPROVED** [review]
nRF53 shell still works and changes looks good to me.

**Comment by dylad** [comment]
Seems like `ruuvitag` slips through

**Comment by maribu** [comment]
Indeed. But at least the `static_assert()` has been tested this way 😅

I'll fix and squash when the kids are asleep :-)

**Comment by maribu** [comment]
Now at least locally all boards build `exmaples/hello-world`. So I hope the `ruuvitag` and the `thingy52` were the only two slipped through *thumbs pressed*

**Comment by maribu** [comment]
And the usual forgot about KConfig issue :sweat_s

**Comment by maribu** [comment]
🎉  thx :-)

**Pull request merged**
