### PR TITLE
cpu/stm32: add periph_adc for STMF7

### LINKED ISSUE #15406: There are unsatisfied feature requirements: periph_adc
#### Description
Cannot compile code that uses ADC on nucleo-stm32 767zi board

#### Steps to reproduce the issue
git clone --recursive https://github.com/playhard21/Nucleo-stm32767Zi_RIoTCode 
cd Nucleo-stm32767Zi_RIoTCode/ADCandDigitalPintest
make all term
I am using Ubuntu 20.10 installed all the requirements for RIoT (ARM toolchain, GCC etc).
I want to use the ADC pin of my board using RIoT os.
I even could not able to find any configuration regarding ADC in https://api.riot-os.org/boards_2nucleo-f767zi_2include_2periph__conf_8h.html.

#### Expected results

The application compiles without errors.

#### Actual results
There are unsatisfied feature requirements: periph_adc

EXPECT ERRORS!

Building application "ADCAndDigitalPin" for "nucleo-f767zi" with MCU "stm32".

"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/boards/nucleo-f767zi
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/boards/common/nucleo
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/core
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/cpu/stm32
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/cpu/cortexm_common
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/cpu/cortexm_common/periph
"make" -C /home/aki/Desktop/TryNucleoCode/RIOT/cpu/stm32/periph
make[3]: *** No rule to make target 'adc_f7.c', needed by '/home/aki/Desktop/TryNucleoCode/ADCandDigitalPintest/bin/nucleo-f767zi/periph/adc_f7.o'.  Stop.
make[2]: *** [/home/aki/Desktop/TryNucleoCode/RIOT/Makefile.base:30: ALL--/home/aki/Desktop/TryNucleoCode/RIOT/cpu/stm32/periph] Error 2
make[1]: *** [/home/aki/Desktop/TryNucleoCode/RIOT/Makefile.base:30: ALL--/home/aki/Desktop/TryNucleoCode/RIOT/cpu/stm32] Error 2
make: *** [/home/aki/Desktop/TryNucleoCode/ADCandDigitalPintest/../RIOT/Makefile.include:603: application_ADCAndDigitalPin.module] Error 2

#### Versions
Operating System Environment
----------------------------
         Operating System: "Ubuntu" "20.10 (Groovy Gorilla)"
                   Kernel: Linux 5.8.0-26-generic x86_64 x86_64
             System shell: /usr/bin/dash (probably dash)
             make's shell: /usr/bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
                  avr-gcc: avr-gcc (GCC) 5.4.0
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
       riscv64-unknown-elf-gcc: missing
       riscv-none-embed-gcc: missing
       xtensa-esp32-elf-gcc: missing
       xtensa-esp8266-elf-gcc: missing
                    clang: missing

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.3.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
    riscv64-unknown-elf-newlib: missing
    riscv-none-embed-newlib: missing
    xtensa-esp32-elf-newlib: missing
    xtensa-esp8266-elf-newlib: missing
                 avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                   ccache: missing
                    cmake: missing
                 cppcheck: missing
                  doxygen: missing
                      git: git version 2.27.0
                     make: GNU Make 4.3
                  openocd: Open On-Chip Debugger 0.10.0+dev-01433-g9e2a0effb-dirty (2020-10-26-20:05)
                   python: missing
                  python2: missing
                  python3: Python 3.8.6
                   flake8: error: /usr/bin/python3: No module named flake8
               coccinelle: missing

### PR DESCRIPTION
**Pull request by playhard21**
### Contribution description

- RIoT ADC drivers for nucleoF767ZI board
- Made flashpage_erase and flashpage_write API available for f7 family

### Testing procedure

- Tested ADC driver working manually by taking data from ADC driver.
- TODO: Need to test flashpage APIs with SUIT update and/or with riotboot.

### Issues/PRs references

Fixes #15406

### CODE REVIEW

**Comment by benpicco** [comment]
Thank you for the patch!

Please split up the commit, one for the flashpage and one for the ADC changes.
Also, I see you changed the ethernet configuration too, that too should be a separate commit. (And actually a separate PR since those are all unrelated).

For flashpage there has already been some work in #15420, would be good to check how that compares.

**Comment by maribu** [comment]
> * one for the changes in Ethernet configuration if those are intentional and not an artifact of rebasing *wink*

I'm 99.9% sure they are an artifact of rebasing. I recognize the changes as one of my PRs.

Regarding the ADC driver: Why not just rename `adc_f4.c` to `adc_f4_f7.c` and change the Makefile like this:

```diff
diff --git a/cpu/stm32/periph/Makefile b/cpu/stm32/periph/Makefile
index 9b171e154c..5184150cdd 100644
--- a/cpu/stm32/periph/Makefile
+++ b/cpu/stm32/periph/Makefile
@@ -11,7 +11,11 @@ endif
 
 # Select the specific implementation for `periph_adc`
 ifneq (,$(filter periph_adc,$(USEMODULE)))
-  SRC += adc_$(CPU_FAM).c
+  ifneq (,$(filter $(CPU_FAM),f4 f7))
+    SRC += adc_f4_f7.c
+  else
+    SRC += adc_$(CPU_FAM).c
+  endif
 endif
 
 # Select the correct implementation for `periph_gpio`
```

**Comment by benpicco** [comment]
Looks much better :)
Please do a `git rebase master`  first and split this into two commits, one for the cpu and one for the board.

**Comment by benpicco** [comment]
You also want to prefix the commit message with the subsystem, e.g. `cpu/stm32: enable ADC driver for f7 family`

**Comment by benpicco** [comment]
Why close/delete this? :cry:

**Comment by benpicco** [comment]
fyi: #15420 has now been merged too.

**Pull request closed without merging**
