### PR TITLE
boards: use common Makefile.include for cc2538 boards

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

@benpicco suggested in https://github.com/RIOT-OS/RIOT/pull/14554#issuecomment-669877070 for me to open my suggestions as a follow up. This PR uses the same `Makefile.include` for all cc2538 based platforms.

### Testing procedure

`flash`, `debug`, `reset`  should still work for all boards and for all programmers, I'll update as I test each board variant (I will have access to the remaining boards on Monday).

- [x] `openmote-b`

- [x] `openmote-cc2538`

<details><summary>cc2538-bsl</summary>

- flash

```
Opening port /dev/ttyUSB0, baud 460800
Reading data from /home/francisco/workspace/RIOT3/examples/default/bin/openmote-cc2538/default.hex
Your firmware looks like an Intel Hex file
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:06:15:A4:44
    Performing mass erase
Erasing 524288 bytes starting at address 0x00200000
    Erase done
Writing 524288 bytes starting at address 0x00200000
Write 16 bytes at 0x0027FFF0F8
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0xb6b23a7a)
```

- reset (this doesn't work in master)

```
Opening port /dev/ttyUSB0, baud 460800
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:06:15:A4:44
```

</details>

<details><summary>jlink</summary>

```
2020-08-07 11:32:06,324 # main(): This is RIOT! (Version: 2020.10-devel-580-g0f103-pr_cc2538_makefile.include)
2020-08-07 11:32:06,324 # Welcome to RIOT!
> 2020-08-07 11:32:36,807 #  main(): This is RIOT! (Version: 2020.10-devel-580-g0f103-pr_cc2538_makefile.include)
2020-08-07 11:32:36,808 # Welcome to RIOT!
>
```

- flash

```
### Flashing Target ###
### Flashing at base address 0x200000 with offset 0 ###
SEGGER J-Link Commander V6.71a (Compiled Apr  3 2020 11:59:31)
DLL version V6.71a, compiled Apr  3 2020 11:59:21

J-Link Commander will now exit on Error

J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link EDU Mini V1 compiled Mar 19 2020 11:12:22
Hardware version: V1.00
S/N: 801014916
License(s): FlashBP, GDB
VTref=2.253V
Target connection not established yet but required for command.
Device "CC2538SF53" selected.


Connecting to target via JTAG
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Failed to power up DAP
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Cannot determine DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[1]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x412FC230. Implementer code: 0x41 (ARM)
Found Cortex-M3 r2p0, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 002BB000 SCS
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 002BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 002BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 002BB923 TPIU-Lite
Cortex-M3 identified.
Halting CPU for downloading file.
Downloading file [/home/francisco/workspace/RIOT3/examples/default/bin/openmote-cc2538/default.bin]...
Comparing flash   [100%] Done.
J-Link: Flash download: Bank 0 @ 0x00200000: Skipped. Contents already match
O.K.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.
```

- reset

```
### Resetting Target ###
SEGGER J-Link Commander V6.71a (Compiled Apr  3 2020 11:59:31)
DLL version V6.71a, compiled Apr  3 2020 11:59:21

J-Link Commander will now exit on Error

J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link EDU Mini V1 compiled Mar 19 2020 11:12:22
Hardware version: V1.00
S/N: 801014916
License(s): FlashBP, GDB
VTref=2.249V
Target connection not established yet but required for command.
Device "CC2538SF53" selected.


Connecting to target via JTAG
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Failed to power up DAP
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Cannot determine DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[1]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x412FC230. Implementer code: 0x41 (ARM)
Found Cortex-M3 r2p0, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 002BB000 SCS
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 002BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 002BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 002BB923 TPIU-Lite
Cortex-M3 identified.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
```

- debug

```
J-Link found 2 JTAG devices, Total IRLen = 10
JTAG ID: 0x4BA00477 (Cortex-M3)
Connected to target
Waiting for GDB connection...Connected to 127.0.0.1
Reading all registers
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA4 (Data = 0xBF308F4F)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA4 (Data = 0xBF308F4F)
Read 2 bytes @ address 0x00200DA8 (Data = 0xF382)
Read 2 bytes @ address 0x00200DA6 (Data = 0xBF30)
Read 2 bytes @ address 0x00200DA4 (Data = 0x8F4F)
Read 2 bytes @ address 0x00200DA8 (Data = 0xF382)
Read 2 bytes @ address 0x00200DA6 (Data = 0xBF30)
Read 2 bytes @ address 0x00200DA4 (Data = 0x8F4F)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA4 (Data = 0xBF308F4F)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA4 (Data = 0xBF308F4F)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
Read 4 bytes @ address 0x00200DA8 (Data = 0x8810F382)
__set_PRIMASK (priMask=1)
    at /home/francisco/workspace/RIOT3/cpu/cortexm_common/include/vendor/cmsis_gcc.h:414
414       __ASM volatile ("MSR primask, %0" : : "r" (priMask) : "memory");
(gdb)
```

</details>

- [x] `cc2538dk`

<details><summary>cc2538-bsl</summary>

- flash

```
BOARD=cc2538dk make -C examples/default/ flash-only term PORT=/dev/ttyUSB3
make: Entering directory '/home/francisco/workspace/RIOT3/examples/default'
/home/francisco/workspace/RIOT3/dist/tools/cc2538-bsl/cc2538-bsl.py -p "/dev/ttyUSB3"  -e -w -v -b 500000	 /home/francisco/workspace/RIOT3/examples/default/bin/cc2538dk/default.bin
Opening port /dev/ttyUSB3, baud 500000
Reading data from /home/francisco/workspace/RIOT3/examples/default/bin/cc2538dk/default.bin
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:04:13:31:68
    Performing mass erase
Erasing 524288 bytes starting at address 0x00200000
    Erase done
Writing 524288 bytes starting at address 0x00200000
Write 16 bytes at 0x0027FFF0F8
    Write done                                
Verifying by comparing CRC32 calculations.
    Verified (match: 0x5f67f12c)
/home/francisco/workspace/RIOT3/dist/tools/pyterm/pyterm -p "/dev/ttyUSB3" -b "115200"  
2020-08-07 18:11:42,210 # Connect to serial port /dev/ttyUSB3
Welcome to pyterm!
Type '/exit' to exit.
help
2020-08-07 18:11:48,982 # help
2020-08-07 18:11:48,983 # Command              Description
2020-08-07 18:11:48,984 # ---------------------------------------
2020-08-07 18:11:48,985 # reboot               Reboot the node
2020-08-07 18:11:48,986 # version              Prints current RIOT_VERSION
2020-08-07 18:11:48,987 # pm                   interact with layered PM subsystem
2020-08-07 18:11:48,989 # ps                   Prints information about running threads.
2020-08-07 18:11:48,990 # random_init          initializes the PRNG
2020-08-07 18:11:48,991 # random_get           returns 32 bit of pseudo randomness
2020-08-07 18:11:48,992 # ifconfig             Configure network interfaces
2020-08-07 18:11:49,003 # txtsnd               Sends a custom string as is over the link layer
2020-08-07 18:11:49,005 # saul                 interact with sensors and actuators using SAUL
```

- reset (this doesn't work in master)

```
Opening port /dev/ttyUSB0, baud 460800
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:06:15:A4:44
```

- reset

```
make: Entering directory '/home/francisco/workspace/RIOT3/examples/default'
/home/francisco/workspace/RIOT3/dist/tools/cc2538-bsl/cc2538-bsl.py -p "/dev/ttyUSB3"  -b 460800 
Opening port /dev/ttyUSB3, baud 460800
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:04:13:31:68
make: Leaving directory '/home/francisco/workspace/RIOT3/examples/default'

```

</details>

<details><summary>jlink</summary>

- flash

```
PROGRAMMER=jlink BOARD=cc2538dk make -C examples/gnrc_networking/ flash -j3
...
Cortex-M3 identified.
Halting CPU for downloading file.
Downloading file [/home/francisco/workspace/RIOT3/examples/gnrc_networking/bin/cc2538dk/gnrc_networking.bin]...
Comparing flash   [100%] Done.
Erasing flash     [100%] Done.
Programming flash [100%] Done.
Verifying flash   [100%] Done.
J-Link: Flash download: Bank 0 @ 0x00200000: 1 range affected (90112 bytes)
J-Link: Flash download: Total time needed: 1.550s (Prepare: 0.021s, Compare: 0.136s, Erase: 0.390s, Program: 0.992s, Verify: 0.003s, Restore: 0.005s)
O.K.

Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.

> 2020-08-07 18:22:02,558 #  main(): This is RIOT! (Version: 2020.10-devel-580-g061b9-pr_cc2538_makefile.include)
2020-08-07 18:22:02,560 # RIOT network stack example application
2020-08-07 18:22:02,562 # All up, running the shell now
>


```

- reset

```
...
AHB-AP ROM base: 0xE00FF000
CPUID register: 0x412FC230. Implementer code: 0x41 (ARM)
Found Cortex-M3 r2p0, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 002BB000 SCS
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 002BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 002BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 002BB923 TPIU-Lite
Cortex-M3 identified.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.
```

- debug

```
Read 4 bytes @ address 0x00201750 (Data = 0x0000BDC9)
Read 4 bytes @ address 0x00201754 (Data = 0x2108B500)
Read 4 bytes @ address 0x00201750 (Data = 0x0000BDC9)
Read 4 bytes @ address 0x00201754 (Data = 0x2108B500)
Read 4 bytes @ address 0x00201754 (Data = 0x2108B500)
Read 4 bytes @ address 0x00201754 (Data = 0x2108B500)
Breakpoint 1, main () at /home/francisco/workspace/RIOT3/examples/gnrc_networking/main.c:40
40          msg_init_queue(_main_msg_queue, MAIN_QUEUE_SIZE);
(gdb)

```

</details>

- [x] `remote*`

<details><summary>cc2538-bsl</summary>

- flash

```
/home/francisco/workspace/RIOT3/dist/tools/cc2538-bsl/cc2538-bsl.py -p "/dev/riot/tty-remote-revb"  -e -w -v -b 460800 /home/francisco/workspace/RIOT3/tests/bloom_bytes/bin/remote-revb/tests_bloom_bytes.bin
Opening port /dev/riot/tty-remote-revb, baud 460800
Reading data from /home/francisco/workspace/RIOT3/tests/bloom_bytes/bin/remote-revb/tests_bloom_bytes.bin
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:14:D5:2D:91
    Performing mass erase
Erasing 524288 bytes starting at address 0x00200000
    Erase done
Writing 524288 bytes starting at address 0x00200000
Write 16 bytes at 0x0027FFF0F8
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0x4b69cf49)
/home/francisco/workspace/RIOT3/dist/tools/pyterm/pyterm -p "/dev/riot/tty-remote-revb" -b "115200"
2020-08-11 09:24:15,096 # Connect to serial port /dev/riot/tty-remote-revb
Welcome to pyterm!
Type '/exit' to exit.
2020-08-11 09:24:16,750 # Help: Press s to start test, r to print it is ready
s
2020-08-11 09:24:33,577 # START
2020-08-11 09:24:33,589 # main(): This is RIOT! (Version: 2020.10-devel-628-gcf723-pr_cc2538_makefile.include)
2020-08-11 09:24:33,591 # Testing Bloom filter.
2020-08-11 09:24:33,591 #
2020-08-11 09:24:33,592 # m: 4096 k: 8
2020-08-11 09:24:33,592 #
2020-08-11 09:24:34,032 # adding 512 elements took 441ms
```

- reset

```
 BOARD=remote-revb make -C tests/bloom_bytes/ reset term
make: Entering directory '/home/francisco/workspace/RIOT3/tests/bloom_bytes'
/home/francisco/workspace/RIOT3/dist/tools/cc2538-bsl/cc2538-bsl.py -p "/dev/riot/tty-remote-revb"  -b 460800
Opening port /dev/riot/tty-remote-revb, baud 460800
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:14:D5:2D:91
/home/francisco/workspace/RIOT3/dist/tools/pyterm/pyterm -p "/dev/riot/tty-remote-revb" -b "115200"
2020-08-11 09:24:56,750 # Connect to serial port /dev/riot/tty-remote-revb
Welcome to pyterm!
Type '/exit' to exit.
2020-08-11 09:24:58,482 # Help: Press s to start test, r to print it is ready
```

</details>

<details><summary>jlink</summary>

- flash

```
 PROGRAMMER=jlink BOARD=remote-revb make -C tests/bloom_bytes/  flash-only DEBUG_ADAPTER_ID=000801014916 term
make: Entering directory '/home/francisco/workspace/RIOT3/tests/bloom_bytes'
/home/francisco/workspace/RIOT3/dist/tools/jlink/jlink.sh flash /home/francisco/workspace/RIOT3/tests/bloom_bytes/bin/remote-revb/tests_bloom_bytes.bin
### Flashing Target ###
### Flashing at base address 0x200000 with offset 0 ###
SEGGER J-Link Commander V6.71a (Compiled Apr  3 2020 11:59:31)
DLL version V6.71a, compiled Apr  3 2020 11:59:21

J-Link Commander will now exit on Error

J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link EDU Mini V1 compiled Mar 19 2020 11:12:22
Hardware version: V1.00
S/N: 801014916
License(s): FlashBP, GDB
VTref=3.291V
Target connection not established yet but required for command.
Device "CC2538SF53" selected.


Connecting to target via JTAG
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Failed to power up DAP
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Cannot determine DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[1]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x412FC230. Implementer code: 0x41 (ARM)
Found Cortex-M3 r2p0, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 002BB000 SCS
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 002BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 002BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 002BB923 TPIU-Lite
Cortex-M3 identified.
Halting CPU for downloading file.
Downloading file [/home/francisco/workspace/RIOT3/tests/bloom_bytes/bin/remote-revb/tests_bloom_bytes.bin]...
Comparing flash   [100%] Done.
J-Link: Flash download: Bank 0 @ 0x00200000: Skipped. Contents already match
O.K.

Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.

/home/francisco/workspace/RIOT3/dist/tools/pyterm/pyterm -p "/dev/riot/tty-remote-revb" -b "115200"
2020-08-11 09:54:48,031 # Connect to serial port /dev/riot/tty-remote-revb
Welcome to pyterm!
Type '/exit' to exit.
2020-08-11 09:54:49,781 # Help: Press s to start test, r to print it is ready
s
2020-08-11 09:54:50,589 # START
2020-08-11 09:54:50,602 # main(): This is RIOT! (Version: 2020.10-devel-628-gcf723-pr_cc2538_makefile.include)
2020-08-11 09:54:50,604 # Testing Bloom filter.
2020-08-11 09:54:50,605 #
2020-08-11 09:54:50,606 # m: 4096 k: 8
2020-08-11 09:54:50,606 #
2020-08-11 09:54:51,044 # adding 512 elements took 441ms
2020-08-11 09:54:54,717 # checking 10000 elements took 3661ms
2020-08-11 09:54:54,717 #
2020-08-11 09:54:54,717 # 267 elements probably in the filter.
2020-08-11 09:54:54,718 # 9733 elements not in the filter.
2020-08-11 09:54:54,718 # 0.026700 false positive rate.
2020-08-11 09:54:54,718 #
2020-08-11 09:54:54,718 # All done!
```

- reset

```
PROGRAMMER=jlink BOARD=remote-revb make -C tests/bloom_bytes/ DEBUG_ADAPTER_ID=000801014916 reset term
make: Entering directory '/home/francisco/workspace/RIOT3/tests/bloom_bytes'
/home/francisco/workspace/RIOT3/dist/tools/jlink/jlink.sh reset
### Resetting Target ###
SEGGER J-Link Commander V6.71a (Compiled Apr  3 2020 11:59:31)
DLL version V6.71a, compiled Apr  3 2020 11:59:21

J-Link Commander will now exit on Error

J-Link Command File read successfully.
Processing script file...

J-Link connection not established yet but required for command.
Connecting to J-Link via USB...O.K.
Firmware: J-Link EDU Mini V1 compiled Mar 19 2020 11:12:22
Hardware version: V1.00
S/N: 801014916
License(s): FlashBP, GDB
VTref=3.289V
Target connection not established yet but required for command.
Device "CC2538SF53" selected.


Connecting to target via JTAG
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Failed to power up DAP
InitTarget: Found ICE-Pick with ID: 0x8B96402F
InitTarget: Found CPU TAP 0x4BA00477
Cannot determine DP version. Assuming DPv0
Scanning AP map to find all available APs
AP[1]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x24770011)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FF000
CPUID register: 0x412FC230. Implementer code: 0x41 (ARM)
Found Cortex-M3 r2p0, Little endian.
FPUnit: 6 code (BP) slots and 2 literal slots
CoreSight components:
ROMTbl[0] @ E00FF000
ROMTbl[0][0]: E000E000, CID: B105E00D, PID: 002BB000 SCS
ROMTbl[0][1]: E0001000, CID: B105E00D, PID: 002BB002 DWT
ROMTbl[0][2]: E0002000, CID: B105E00D, PID: 002BB003 FPB
ROMTbl[0][3]: E0000000, CID: B105E00D, PID: 002BB001 ITM
ROMTbl[0][4]: E0040000, CID: B105900D, PID: 002BB923 TPIU-Lite
Cortex-M3 identified.
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.



Script processing completed.

/home/francisco/workspace/RIOT3/dist/tools/pyterm/pyterm -p "/dev/riot/tty-remote-revb" -b "115200"
2020-08-11 09:55:45,082 # Connect to serial port /dev/riot/tty-remote-revb
Welcome to pyterm!
Type '/exit' to exit.
2020-08-11 09:55:46,862 # Help: Press s to start test, r to print it is ready
s
2020-08-11 09:55:51,287 # START
2020-08-11 09:55:51,301 # main(): This is RIOT! (Version: 2020.10-devel-628-gcf723-pr_cc2538_makefile.include)
2020-08-11 09:55:51,303 # Testing Bloom filter.
2020-08-11 09:55:51,304 #
2020-08-11 09:55:51,304 # m: 4096 k: 8
2020-08-11 09:55:51,305 #
2020-08-11 09:55:51,743 # adding 512 elements took 441ms
```

- debug

```
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/francisco/workspace/RIOT3/tests/bloom_bytes/bin/remote-revb/tests_bloom_bytes.elf
Reset target CPU...
Reset target CPU...
Reading all registers
Reading 64 bytes @ address 0x00200EC0
Reading 64 bytes @ address 0x00200F00
Read 2 bytes @ address 0x00200F06 (Data = 0xF300)
Read 4 bytes @ address 0x00200F06 (Data = 0x80B0F300)
Read 2 bytes @ address 0x00201798 (Data = 0x2308)
Read 2 bytes @ address 0x00201798 (Data = 0x2308)
Read 2 bytes @ address 0x00200F06 (Data = 0xF300)
Setting breakpoint @ address 0x00200F06, Size = 4, BPHandle = 0x0001
Read 2 bytes @ address 0x00201798 (Data = 0x2308)
Setting breakpoint @ address 0x00201798, Size = 2, BPHandle = 0x0002
Starting target CPU...
...Breakpoint reached @ address 0x00200F06
Reading all registers
[Switching to Thread 57005]
Removing breakpoint @ address 0x00200F06, Size = 4
Removing breakpoint @ address 0x00201798, Size = 2

Breakpoint 1, 0x00200f06 in leds_init () at /home/francisco/workspace/RIOT3/boards/remote-revb/board.c:53
53          LED_RAINBOW();
(gdb)
```

</details>
### Issues/PRs references

Alternative or can come after  #14554.

### CODE REVIEW

**Comment by benpicco** [comment]
I can confirm that flashing & resetting also works with an `openmote-b`.

**Comment by benpicco** [comment]
Might need a rebase now that #14720 is merged.

**Comment by fjmolinas** [comment]
Rebased and also added @benpicco changes from  #14554. Only remote testing is missing.

**Comment by fjmolinas** [comment]
Fixed missing new line, and added test for remote.

**Comment by fjmolinas** [comment]
Are you OK with the changes @benpicco?

**Comment by MrKevinWeiss** [comment]
It seems this PR deleted the renode config file `boards/cc2538dk/dist/board.resc`.  I am still trying to get renode up and running.  Once I do I will make a PR to restore it.

**Comment by fjmolinas** [comment]
> It seems this PR deleted the renode config file boards/cc2538dk/dist/board.resc. I am still trying to get renode up and running. Once I do I will make a PR to restore it.

Oh my bad, are you sure you don't want me to restore it ASAP?

**Comment by MrKevinWeiss** [comment]
I just want to make sure it works (and it does). https://github.com/RIOT-OS/RIOT/pull/14839

**Pull request merged**
