### PR TITLE
gnrc_ipv6_nib: don't stop sending router solicitations when receiving last router advertisement from router

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

When the default router was removed as it did send it's 'last RA' or could not be added, `dr` will be NULL.
In this case, don't cease sending router solicitations - we still don't have a default router.

### CODE REVIEW

**Comment by miri64** [comment]
I still need to look into the surrounding code to be sure, but I think this enables invalid behavior:

>     If a host sends MAX_RTR_SOLICITATIONS solicitations, and receives no
>     Router Advertisements after having waited MAX_RTR_SOLICITATION_DELAY
>     seconds after sending the last solicitation, the host concludes that
>     there are no routers on the link for the purpose of [ADDRCONF].
>     However, the host continues to receive and process Router
>     Advertisements messages in the event that routers appear on the link.

**Comment by benpicco** [comment]
I fail to see the connection - but granted, this is an edge case that will likely not cause much trouble.
The scenario is as follows:

 - a node has no default router yet
 - it receives a router solicitation from a router that just did `_snd_ra()` with `final` set to true, meaning it would be removed from the default router list
 - the node still doesn't have a default router, but ceases to send router solicitations

**Comment by miri64** [comment]
> I fail to see the connection - but granted, this is an edge case that will likely not cause much trouble.
> The scenario is as follows:
> 
>     * a node has no default router yet
> 
>     * it receives a router solicitation from a router that just did `_snd_ra()` with `final` set to true, meaning it would be removed from the default router list, but as it's not in the list yet, nothing happens
> 
>     * the node still doesn't have a default router, but ceases to send router solicitations

Shouldn't it than rather reset the router solicitation retransmission counter, if it receives a final RA? Seems like the more legitimate way to go, as it is basically like it lost its default router, but basically just when meeting it.

**Comment by miri64** [comment]
The faulty behavior is that it accepts a final router advertisement as if it where a normal router advertisement, not that it did not find a router after `MAX_RTR_SOLICITATIONS`.

**Comment by miri64** [comment]
Arghs sorry... the way Github shows me the change it looks like the change is in the handling of the router solicitation. But now I see it is in the RA handling.

**Comment by miri64** [comment]
Ok, now I oriented myself: shouldn't the function not just bail out after this line?

https://github.com/RIOT-OS/RIOT/blob/62308d200c4a2d61a5b9a7cdc8ee59785640ea20/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L696

I have to reread RFC4861 to be sure, but from what I can see, everything after is just config and taking config from a "dying" router does not seem to be wise. The only thing I am not sure about is the handling of the SLLAO option, as it could have implications for neighbor unreachability detection (for a "dying" router we might want to have it be detected as unreachable ad one point ;-)).

**Comment by benpicco** [comment]
Well I found it to be quite handy that the options of a non-default router are still parsed…
(And since the options come with their own lifetimes that doesn't even seem too outlandish - basically it allows a router to say "I'm not a router to an upstream network, but I might still have some useful information for you")

**Comment by miri64** [comment]
Yepp, the RFC confirms your stance. From [RFC 4861, section 4.2](https://datatracker.ietf.org/doc/html/rfc4861#section-4.2):

>                     […] The Router Lifetime applies only to
>                     the router's usefulness as a default router; it
>                     does not apply to information contained in other
>                     message fields or options.  Options that need time
>                     limits for their information include their own
>                     lifetime fields.

**Review by miri64 — APPROVED** [review]
ACK. Change makes sense. With regards to the default router list, a final RA (i.e. an RA with a router lifetime of 0) must be handled like no default router had been found. As @benpicco mentioned: this is a rare corner case that should be dealt with, where a router advertises itself as not being a router anymore while another node is searching for a router using RSs. Typically, a final RA is not sent in reply to a RS.

**Pull request merged**
