### PR TITLE
sys/xtimer: Remove dependency to core_msg

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description
When module `core_msg` is not used, `xtimer` now no longer provides the features related to messages. This allows using `xtimer` without `core_msg`.

### Testing procedure
The tests `test/xtimer*` should still work

### Issues/PRs references
Spun out of https://github.com/RIOT-OS/RIOT/pull/11226

### CODE REVIEW

**Comment by maribu** [comment]
Instead of adding multiple pairs of `#ifdef MODULE_CORE_MSG` ... `#endif` to every file this PR relocates the code depending on `core_msg`, so that only a single pair is required. Therefore the relatively high number of lines changed.

**Comment by miri64** [comment]
@kaspar030 IMHO this looks interesting and should also be a lesson learned for `ztimer`.

**Comment by miri64** [comment]
(@maribu, needs rebase)

**Comment by benpicco** [comment]
Murdock is not happy - looks like some missing includes that were pulled in before by accident.

**Comment by maribu** [comment]
@benpicco: Thanks for reminding me of this. Now the missing `#include`s are added.

**Comment by benpicco** [comment]
Feel free to squash.

**Pull request merged**
