### PR TITLE
ng_net: add 6LoWPAN as dependency for IEEE 802.15.4 devices

### PR DESCRIPTION
**Pull request by authmillenon**
Only applies if ng_ipv6 also was included.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Why `ng_sixlowpan_frag`?

**Comment by authmillenon** [comment]
Because otherwise it wouldn't the frame size

**Comment by OlegHahm** [comment]
A very simple IPv6 would fit, right?

**Comment by authmillenon** [comment]
Yes, but the stack wouldn't pass received packets to IPv6.

**Comment by authmillenon** [comment]
But that was not the point of the splitting out of frag. Fragmentation is not optional for IEEE 802.15.4. For BLE it is not needed however.

**Comment by OlegHahm** [comment]
To repeat what I've written in the chat: I think that 6LoWPAN without fragmentation is a reasonable choice for many use cases (think of reading a single sensor over UDP) even if it is not 100% RFC compliant. And fragmentation consumes quite some memory. Therefore, I would like to keep it optional. (However, I agree that including it as a default case makes sense.)

**Comment by authmillenon** [comment]
It is still optional. You can disable it via `DISABLE_MODULE` or by removing these lines by hand.

**Comment by OlegHahm** [comment]
>  by removing these lines by hand

That's not an option.

> You can disable it via DISABLE_MODULE

Will have to test this.

**Comment by authmillenon** [comment]
I did just that… it does not seem to have this behavior anymore and only removes modules from the `DEFAULT_MODULES` list.

**Comment by authmillenon** [comment]
Just for comparison: on iot-lab_M3:

with `ng_sixlowpan_frag`:
```
   text	   data	    bss	    dec	    hex	filename
  46120	    156	  17804	  64080	   fa50	/home/martine/Repositories/RIOT-OS/RIOT/tests/driver_at86rf2xx/bin/iot-lab_M3/driver_at86rf2xx.elf
```

without `ng_sixlowpan_frag`:

```
   text	   data	    bss	    dec	    hex	filename
  44588	    156	  17336	  62080	   f280	/home/martine/Repositories/RIOT-OS/RIOT/tests/driver_at86rf2xx/bin/iot-lab_M3/driver_at86rf2xx.elf
```

difference:
```
   text	   data	    bss	    dec	    hex	filename
   1533	      0	    468	   2000	    7d0	/home/martine/Repositories/RIOT-OS/RIOT/tests/driver_at86rf2xx/bin/iot-lab_M3/driver_at86rf2xx.elf
```

Actual stack and packet buffer usage is of course not in there.

**Comment by OlegHahm** [comment]
Hence, 1,5k ROM + a significant bigger packet buffer for reassembly and IP packets up to a full MTU. I'd like to see this configurable in an easy way.

**Comment by authmillenon** [comment]
The packet buffer could be actually smaller than it currently is without fragmentation ;-)

**Comment by OlegHahm** [comment]
> The packet buffer could be actually smaller than it currently is without fragmentation ;-)

Isn't that exactly what I said?

**Comment by authmillenon** [comment]
I thought you meant, that with fragmentation we need *more* packet buffer space

**Comment by OlegHahm** [comment]
Yes.

**Comment by authmillenon** [comment]
> I did just that… it does not seem to have this behavior anymore and only removes modules from the `DEFAULT_MODULES` list.

https://github.com/RIOT-OS/RIOT/pull/2951

**Comment by OlegHahm** [comment]
What about the proposed solution from https://github.com/RIOT-OS/RIOT/issues/2971#issuecomment-101266042? Having a PSEUDOMOLUE with something like `default_sixlowpan` that includes fragmentation and header compression, but making 802.15.4 transceivers with IPv6 enabled only depend on naked 6lowpan.

**Comment by authmillenon** [comment]
Will do, when I come to it

**Comment by authmillenon** [comment]
Now based upon #3004

**Comment by kaspar030** [comment]
wouldn't it be easier the other way around? 802.15.4 devices provide a 802.15.4 transceiver pseudomodule, and if that's linked in and ipv6, so is sixlowpan?

**Comment by authmillenon** [comment]
Probably… Will do.

**Comment by authmillenon** [comment]
done

**Comment by authmillenon** [comment]
Rebased to current #3004

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
Rebased to current master. Will add #2983 if it gets merged first.

**Comment by authmillenon** [comment]
(merge conflicts were in `Makefile.dep`)

**Comment by authmillenon** [comment]
Why was the execution of the test stopped?

**Comment by authmillenon** [comment]
Rebased to current master and adapted for #2983

**Comment by jremmert-phytec-iot** [comment]
@authmillenon thx :). According to the status page, Travis had some problems yesterday.

> We are working through cleanup. Builds are processing, but we are still seeing some delays in some cases.

**Comment by authmillenon** [comment]
It wasn't delayed but stopped by hand, even though it was already ACK'd (long before #2983). I suspect some trigger-happy fingers in the merging effort for #2881. ;)  Anyways: shit happens, let's merge this as soon as Travis is ready.

**Comment by OlegHahm** [comment]
You have seen the mails on the maintainer mailing list, haven't you? Might be related.

**Pull request merged**
