### PR TITLE
dist: Update Vagrant packer files to include xsltproc and Ubuntu 16.04.3

### PR DESCRIPTION
**Pull request by adrianghc**
Some repositories have Makefiles that require xsltproc to unpack, which means that if you want to use a RIOT package whose source uses such a Makefile, you must have xsltproc installed on your system. However, if you develop for RIOT with the provided Vagrant box, xsltproc is not installed with no easy way to install it. This PR adds xsltproc to the preseed.cfg file so it will be included when building a Vagrant box with the included packer tool. This PR also upgrades the ISO to Ubuntu 16.04.3, although this is not necessary for xsltproc.

I'd also ask you to consider updating the official Vagrant box for RIOT development with these changes so users don't need to build their Vagrant box on their own if they require xsltproc.

### CODE REVIEW

**Comment by cgundogan** [comment]
@adrianghc could you try the provided patch? I uploaded a test box with your change. If you think that's okay, then we can go ahead and merge your PR.

```diff
diff --git a/Vagrantfile b/Vagrantfile
index c15f8d3d6..56bbf8dc7 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -8,7 +8,8 @@ RIOTBASE ||= "./"
 Vagrant.configure(2) do |config|
   # For a complete reference, please see the online documentation at https://docs.vagrantup.com.
 
-  config.vm.box = "RIOT/ubuntu1604"
+  config.vm.box = "RIOT/testing-ubuntu1604"
+  config.vm.box_version = "0.0.2"
 
   config.vm.provider "virtualbox" do |vb|
     vb.name = "RIOT-VM"
```

**Comment by adrianghc** [comment]
There is no version 0.0.2 yet and version 0.0.1 doesn't include xsltproc, am I missing something or does it simply take a while for the new box to become available?

**Comment by cgundogan** [comment]
@adrianghc could you try again? I hadn't pushed the release button ..

**Comment by adrianghc** [comment]
I've just checked again, xsltproc is installed and can be used in version 0.0.2.

**Comment by cgundogan** [comment]
@adrianghc alright, let's merge this! Thanks (:

I will build a new version of the box and upload it within the next hour.

**Pull request merged**
