### PR TITLE
dist/tools/goodfet: Update goodfet flasher to python3

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Since python2 is now obsolete we should update the scripts in RIOT to python3.
After a quick search I couldn't find and easy replacement so I did the following:

Apply `2to3` for scripted python 2 to 3 update.
Fix encoding and decoding of serial write and read.
Fix `chr` and `ord` to `to_bytes` and `bytearray`.
### Testing procedure

Flash boards that use the `goodfet` flasher.

I only tested on the `z1` board.

### CODE REVIEW

**Comment by jia200x** [comment]
great!

Just as a side note, maybe you could consider putting this publicly available in a repo. I'm pretty sure there would be more people interested in this

**Comment by aabadie** [comment]
> you could consider putting this publicly available in a repo

Isn't this an adapted copy of https://github.com/travisgoodspeed/goodfet ? Maybe PR the change upstream and use a package ?

**Comment by MrKevinWeiss** [comment]
It is pretty poorly written and I only updated what was needed to.  Maybe a gist is a bit for fitting?

**Comment by MrKevinWeiss** [comment]
> The GoodFET is a nifty little tool for quickly exposing embedded system buses to userland Python code. It is no longer under active development, but I hope that you find it useful nonetheless.

I think if we just update here it would be fine.

**Comment by jia200x** [comment]
> I think if we just update here it would be fine.

I'm fine with it, since it's not maintained anymore

**Comment by MrKevinWeiss** [comment]
ping

**Comment by MrKevinWeiss** [comment]
ping @jia200x

**Comment by MrKevinWeiss** [comment]
ping

**Comment by MrKevinWeiss** [comment]
https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/master/69/pipeline/78

Shows flashing with this PR

**Review by jia200x — APPROVED** [review]
ACK. I trust the provided test results

**Pull request merged**
