### PR TITLE
cpu/stm32f1: added stm32f103c8 linkerscript

### PR DESCRIPTION
**Pull request by avmelnikoff**
Added stm32f103c8 memory definitions for cortexm common linkerscript

### CODE REVIEW

**Comment by haukepetersen** [comment]
The linkerscript looks fine, but may I ask what this is for? We don't have any board using a stm32f103c8 CPU currently in RIOT, right? So why put the linkerscript in?

In case you are planning to add a board using that CPU, I would suggest to add the Linkerscript in that PR...

**Comment by avmelnikoff** [comment]
I have a couple of development board that are using stm32f103c8 CPU. They are simple dev boards that were manufactured by chinese. I thought that it is not good (not right) to add non-famous dev boards to the RIOT's tree, so I added it to my own repo and use them as external board directory.
But I thought, that it is good/right to add linker script to the RIOT's CPU tree. Sorry, if I'm wrong.

**Comment by haukepetersen** [comment]
Yes, your are right, in this situation it makes completely sense! Just wanted to make sure we don't just add anything without a reason for it :-)

so ACK and go.

**Comment by OlegHahm** [comment]
Feature freeze?

**Pull request merged**
