### PR TITLE
kinetis: Generic ISR vector table for all Kinetis CPUs

### PR DESCRIPTION
**Pull request by gebart**
Replaces #7761.

Use one generic ISR vector table with contents depending on what is available in the selected vendor header. The numbering is handled by the vendor header definition of `enum IRQn`, so it will always match each CPU.

This table was generated using an AWK script and then manually edited where the script generated the wrong preprocessor conditions.

### CODE REVIEW

**Comment by smlng** [comment]
> may replace #7761 completely if squashed.

I agree, they go hand-in-hand and its fine to have this done here completely.

**Comment by gebart** [comment]
I will close #7761 to focus on this instead.

**Comment by gebart** [comment]
@smlng yes, https://github.com/RIOT-OS/RIOT/pull/7878/commits/a55349707185f715f2db84cbe7cc6e1f6a7461ff
>k22f: Remove unused MK22F10.h header  …
gebart committed on Aug 4
According to NXP material, there are no 100 MHz K22F parts in 144 pin
packages, which is the reference manual that this header is supposed to
correspond to.
The header was originally included from Keil uVision Kinetis support
packages. It is possible that this header was only used with
engineering samples of the K22F.

**Comment by smlng** [comment]
ah thanks for the info, haven't read the (self explanatory) long commit message 😞

**Comment by gebart** [comment]
regarding https://github.com/RIOT-OS/RIOT/pull/7761#issuecomment-339905975
@haukepetersen 
> On first sight, I am not too happy with this change. Having the vector names following the coding rules makes the code just so much nicer to look at, and I more pressingly feel that if we start to make an exception to the rules here, people will start to make these exceptions in many other places (be it for good reasons or not), leading to a more incoherent code base... But maybe I am to picky here?!
>
>>  It will be easier to verify the implementation when the vector table in the binary can be compared with the IRQ list in the vendor header.
>
>I see the point, but I imagine that this test is mostly done automatically using some kind of script, right? In that case, I think it is easy to convert a string from upper to lower case. Also when using some kind of regex to do these checks, it is mostly also simple to ignore the case.
>
>But in the end I stated my doubts, but I will not block this PR if it is decided to go with it, I just won't be the one merging this :-)

@smlng @haukepetersen are you fine with this if I keep the ISR names as proposed but make them all lowercase?

**Comment by smlng** [comment]
I agree, lowercase would be consistent with RIOTs coding style and other ISR vectors, for instance the once for the STM families.

**Comment by haukepetersen** [comment]
Yes, that would be great!

**Comment by gebart** [comment]
@haukepetersen @smlng I changed the names to lowercase now.
I'll let Murdock do a compile run to see if I have missed anything.

**Comment by gebart** [comment]
rebased, squashed
@smlng does your ACK still hold?

**Comment by smlng** [comment]
retested with PhyNode `pba-d-01-kw2x`, still works. Again: nice work!

**Comment by smlng** [comment]
ACK & GO!

**Pull request merged**
