### PR TITLE
board/nucleo-f334: blacklist board in failing tests and fix CPU_USAGE

### PR DESCRIPTION
**Pull request by thomaseichinger**

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@haukepetersen might want to verify 0b79dff

**Comment by fnack** [comment]
Of course we can wait for @haukepetersen statement, but the changes look legit to me. As stated [here](http://www.st.com/web/en/catalog/tools/FM116/SC959/SS1532/LN1847/PF260004) the board is equipped with a STM32F334R8 which is a Cortex M4 MCU (see [here](http://www.st.com/web/en/catalog/mmc/FM141/SC1169/SS1576/LN1820/PF259916).

Let's see what Travis and Hauke are saying ;)

**Comment by thomaseichinger** [comment]
@fnack As this currently corrupts build tests I'd put it on fast track when Travis succeeds. Do you ACK?

**Comment by fnack** [comment]
Yes, ACK!

**Comment by thomaseichinger** [comment]
Travis passed, Go

**Pull request merged**
