### PR TITLE
cc110x: remove warning about the transceiver mode

### PR DESCRIPTION
**Pull request by OlegHahm**
* RPL is currently working with both transceiver modes (wake on radio _and_ constant RX)
* tested on MSB-A2 in the DES testbed

### CODE REVIEW

**Comment by OlegHahm** [comment]
Fixes #769.

**Comment by cgundogan** [comment]
Could you briefly explain how I can test this on the two msb-a2 nodes I have lying around here?

**Comment by OlegHahm** [comment]
I think I just realized that I wasn't this at all: MSBA2 is not using cc110x_legacy_csma as defaulttransceiver.

To test this, one would have to use the `cc110x_legacy_csma` driver and test with two setups for https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/cc110x_legacy_csma/cc1100-interface.h#L56 `CC1100_MODE_CONSTANT_RX` and `CC1100_MODE_WOR`.

**Comment by OlegHahm** [comment]
Actually it looks like that neither the one nor the other is working properly with this driver.

**Comment by OlegHahm** [comment]
Hm, it seems that CONSTANT_RX works even better (which I would have expected anyway). So, I would say this patch doesn't make things worse.

**Comment by OlegHahm** [comment]
@cgundogan, @BytesGalore, anyone willing to test?

**Comment by BytesGalore** [comment]
@OlegHahm sure. I've tested with 2 `msba2` nodes using the this example application [1], one acting as root and one as a node. 
I changed the driver to `cc110x_legacy_csma` in the `msba2` [`Makefile.include`](https://github.com/RIOT-OS/RIOT/blob/master/boards/msba2/Makefile.include#L4) [2].
I've set the driver to and changed the mode in [`rpl.h`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/include/rpl.h#L42) [3] since it `undef`s it otherwise. 

Using the `cc110x_legacy_csma` driver does not seem to work for neither ` CC1100_MODE_CONSTANT_RX` nor `CC1100_MODE_WOR`.

Using `cc110x_legacy` works for both ` CC1100_MODE_CONSTANT_RX` and `CC1100_MODE_WOR`. 
I can't say if ` CC1100_MODE_CONSTANT_RX` works better, I didn't experienced a significant difference.

[1] https://github.com/BytesGalore/RIOT/tree/watrli_rpl_udp_example
[2] https://github.com/RIOT-OS/RIOT/blob/master/boards/msba2/Makefile.include#L4
[3] https://github.com/RIOT-OS/RIOT/blob/master/sys/net/include/rpl.h#L42

**Comment by OlegHahm** [comment]
So, you would ACK?

**Comment by BytesGalore** [comment]
oh, sorry of course. 
ACK.

**Comment by cgundogan** [comment]
I'll be able to test this in about 2-3 hours
Am 11.05.2015 15:05 schrieb "BytesGalore" <notifications@github.com>:

**Comment by cgundogan** [comment]
>So, I would say this patch doesn't make things worse.

+1
I got similar results to @BytesGalore's, so ACK and Go when travis is happy

**Comment by BytesGalore** [comment]
kicked travis

**Comment by OlegHahm** [comment]
Rebased to master to fix Travis emdebian problem.

**Pull request merged**
