### PR TITLE
cpu/esp8266: fix bootloaders and log outputs in vendor code

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

New bootloaders that suppress the bootloader startup information if the LOG_LEVEL is not at least 4 or the `esp_log_start` module is not enabled were introduced with PR #12896. These bootloaders were built with the standard SPI flash parameters for the ESP8266 and use the QIO flash mode and a frequency of 40 MHz.

However, some ESP8266 modules and ESP8285 modules only work with the DOUT SPI flash mode and a SPI flash frequency of 26 MHz. These modules do not start with these bootloaders.

This PR provides a fix for these bootloaders and use the DOUT SPI flash mode and a SPI flash frequency of 26 MHz.

### Testing procedure

Make any application and test it after flashing on any ESP8266 board with and without startup information, e.g.,

```
LOG_LEVEL=4 make BOARD=esp8266-esp-12x -C tests/thread_basic/ flash test
```
```
make BOARD=esp8266-esp-12x -C tests/thread_basic/ flash test
```

### Issues/PRs references

Problem was introduced with PR #12896

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
I tested this on a esp8266 board that I had (I still compiled and flashed as the `esp8266-esp-12x`).

I could not reproduce the error, though it may just be the wrong board.

<details><summary>master, log level 4, esp8266-devkitc-02d-f</summary>

```
B��J��� ESP-IDF v3.1-4-g08c234e 2nd stage bootloader
2019-12-12 09:45:36,678 # I (45) boot: compile time 16:17:57
2019-12-12 09:45:36,680 # I (45) boot: SPI Speed      : 26.7MHz
2019-12-12 09:45:36,684 # I (45) boot: SPI Mode       : DOUT
2019-12-12 09:45:36,686 # I (48) boot: SPI Flash Size : 2MB
2019-12-12 09:45:36,689 # I (52) boot: Partition Table:
2019-12-12 09:45:36,695 # I (54) boot: ## Label            Usage          Type ST Offset   Length
2019-12-12 09:45:36,701 # I (61) boot:  0 nvs              WiFi data        01 02 00009000 00006000
2019-12-12 09:45:36,707 # I (67) boot:  1 phy_init         RF data          01 01 0000f000 00001000
2019-12-12 09:45:36,713 # I (74) boot:  2 factory          factory app      00 00 00010000 00044ae0
2019-12-12 09:45:36,718 # I (80) boot: End of partition table
2019-12-12 09:45:36,726 # I (83) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x39620 (235040) map
2019-12-12 09:45:36,841 # I (208) esp_image: segment 1: paddr=0x00049638 vaddr=0x3ffe8000 size=0x01134 (  4404) load
2019-12-12 09:45:36,847 # I (211) esp_image: segment 2: paddr=0x0004a774 vaddr=0x3ffe9138 size=0x011f8 (  4600) load
2019-12-12 09:45:36,854 # I (216) esp_image: segment 3: paddr=0x0004b974 vaddr=0x40100000 size=0x09144 ( 37188) load
2019-12-12 09:45:36,869 # I (240) boot: Loaded app from partition at offset 0x10000
2019-12-12 09:45:36,905 # Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
2019-12-12 09:45:36,910 # Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
2019-12-12 09:45:37,116 # 
2019-12-12 09:45:37,119 # Starting ESP8266 CPU with ID: 00291731
2019-12-12 09:45:37,122 # ESP8266-RTOS-SDK Version v3.1-4-g08c234e
2019-12-12 09:45:37,123 # 
2019-12-12 09:45:37,125 # CPU clock frequency: 80 MHz
2019-12-12 09:45:37,128 # heap: 57840 (used 1444, free 56396) [bytes]
2019-12-12 09:45:37,129 # 
2019-12-12 09:45:37,135 # MTD in SPI flash starts at address 0x00080000 with a size of 1516 kbytes
2019-12-12 09:45:37,135 # 
2019-12-12 09:45:37,138 # Board configuration:
2019-12-12 09:45:37,140 # 	UART_DEV(0)	txd=1 rxd=3
2019-12-12 09:45:37,141 # 	LED		pins=[ 2 ]
2019-12-12 09:45:37,144 # 	BUTTON		pins=[ ]
2019-12-12 09:45:37,144 # 
2019-12-12 09:45:37,147 # main(): This is RIOT! (Version: 2020.01-devel-1371-ga9bf)
```
</details>

<details><summary>pr, log level 4, esp8266-devkitc-02d-f</summary>

```
2019-12-12 09:51:35,659 # B��J��� ESP-IDF v3.1-4-g08c234ec-dirty 2nd stage bootloader
2019-12-12 09:51:35,663 # I (45) boot: compile time 07:32:52
2019-12-12 09:51:35,665 # I (45) boot: SPI Speed      : 26.7MHz
2019-12-12 09:51:35,670 # I (46) boot: SPI Mode       : DOUT
2019-12-12 09:51:35,672 # I (49) boot: SPI Flash Size : 2MB
2019-12-12 09:51:35,675 # I (52) boot: Partition Table:
2019-12-12 09:51:35,681 # I (54) boot: ## Label            Usage          Type ST Offset   Length
2019-12-12 09:51:35,687 # I (60) boot:  0 nvs              WiFi data        01 02 00009000 00006000
2019-12-12 09:51:35,693 # I (67) boot:  1 phy_init         RF data          01 01 0000f000 00001000
2019-12-12 09:51:35,699 # I (73) boot:  2 factory          factory app      00 00 00010000 000450f0
2019-12-12 09:51:35,703 # I (80) boot: End of partition table
2019-12-12 09:51:35,710 # I (83) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x39c10 (236560) map
2019-12-12 09:51:35,827 # I (209) esp_image: segment 1: paddr=0x00049c28 vaddr=0x3ffe8000 size=0x01134 (  4404) load
2019-12-12 09:51:35,833 # I (211) esp_image: segment 2: paddr=0x0004ad64 vaddr=0x3ffe9138 size=0x0121c (  4636) load
2019-12-12 09:51:35,841 # I (216) esp_image: segment 3: paddr=0x0004bf88 vaddr=0x40100000 size=0x09144 ( 37188) load
2019-12-12 09:51:35,855 # I (240) boot: Loaded app from partition at offset 0x10000
2019-12-12 09:51:35,891 # nvs_flash_init_custom partition=nvs start=9 count=���Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
2019-12-12 09:51:35,894 # nvs_open_from_partition backup_mac 0
2019-12-12 09:51:35,897 # nvs_get_str_or_blob backup_mac_data
2019-12-12 09:51:35,898 # nvs_close 1
2019-12-12 09:51:35,904 # Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
2019-12-12 09:51:35,908 # nvs_open_from_partition backup_mac 0
2019-12-12 09:51:35,910 # nvs_get_str_or_blob backup_mac_data
2019-12-12 09:51:35,913 # nvs_close 2
2019-12-12 09:51:35,915 # loading PHY init data from application binary
2019-12-12 09:51:35,919 # nvs_open_from_partition phy 0
2019-12-12 09:51:35,921 # nvs_get_str_or_blob cal_data
2019-12-12 09:51:35,923 # nvs_get_str_or_blob dc_table
2019-12-12 09:51:35,924 # nvs_close 3
2019-12-12 09:51:36,131 # 
2019-12-12 09:51:36,134 # Starting ESP8266 CPU with ID: 00291731
2019-12-12 09:51:36,137 # ESP8266-RTOS-SDK Version v3.1-4-g08c234e
2019-12-12 09:51:36,137 # 
2019-12-12 09:51:36,139 # CPU clock frequency: 80 MHz
2019-12-12 09:51:36,143 # heap: 57808 (used 1444, free 56364) [bytes]
2019-12-12 09:51:36,144 # 
2019-12-12 09:51:36,148 # Enable task watch dog panic, panic time parameter is 11
2019-12-12 09:51:36,153 # task watch dog trigger time parameter is 15
2019-12-12 09:51:36,159 # MTD in SPI flash starts at address 0x00080000 with a size of 1516 kbytes
2019-12-12 09:51:36,160 # 
2019-12-12 09:51:36,163 # Board configuration:
2019-12-12 09:51:36,164 # 	UART_DEV(0)	txd=1 rxd=3
2019-12-12 09:51:36,165 # 	LED		pins=[ 2 ]
2019-12-12 09:51:36,167 # 	BUTTON		pins=[ ]
2019-12-12 09:51:36,167 # 
2019-12-12 09:51:36,171 # main(): This is RIOT! (Version: 2020.01-devel-1330-gbaf4db-tstxxx/12929)
```
</details>

**Comment by gschorcht** [comment]
@MrKevinWeiss Thanks for testing. You would need a module that only uses 2 data lines for the SPI flash. This is the case for all ESP8285 boards. That is, you would need an ESP8285 board, for example Wemos D1 mini Lite or any NodeMCU with ESP8285 to see the difference.

**Comment by MrKevinWeiss** [comment]
Hmmm I don't think I have one :disappointed:

**Comment by gschorcht** [comment]
@MrKevinWeiss Would you mind approving the PR anyway since it is a bugfix? At least the PR won't make it worse :wink:

**Comment by gschorcht** [comment]
@MrKevinWeiss Thanks a lot.

**Pull request merged**
