### PR TITLE
cpu/sam3/periph_rtt: fix rtt_get_alarm()

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- Previously, the return value was off by one. The second commit fixes this
- The first commit sneaks in some enhancement of `tests/periph_rtt` to ease debugging, as this might be useful in the future as well

### Testing procedure

`make BOARD=arduino-due -C tests/periph_rtt` should now pass

### Issues/PRs references

Noticed in https://github.com/RIOT-OS/RIOT/pull/16257

### CODE REVIEW

**Comment by maribu** [comment]
Output with master:

```
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)

RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0xffffffff
RTT_FREQUENCY: 1

Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok

Initializing the RTT driver
This test will now display 'Hello' every 5 seconds

RTT now: 0
Setting initial alarm to now + 5 s (5)
Error: rtt_get_alarm() not working (expected 5 but got 4
Hello
Timeout in expect script at "child.expect_exact('Done setting up the RTT, wait for many Hellos')" (tests/periph_rtt/tests/01-run.py:29)

make: *** [/home/maribu/Repos/software/RIOT/makefiles/tests/tests.inc.mk:22: test] Error 1
```

Output with this PR:

```
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)

RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0xffffffff
RTT_FREQUENCY: 1

Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok

Initializing the RTT driver
This test will now display 'Hello' every 5 seconds

RTT now: 0
Setting initial alarm to now + 5 s (5)
rtt_get_alarm() PASSED
Done setting up the RTT, wait for many Hellos
Hello
Hello
Hello
Hello
Hello

Traceback (most recent call last):
  File "/home/maribu/Repos/software/RIOT/tests/periph_rtt/tests/01-run.py", line 40, in <module>
    sys.exit(run(testfunc))
  File "/home/maribu/Repos/software/RIOT/dist/pythonlibs/testrunner/__init__.py", line 30, in run
    testfunc(child)
  File "/home/maribu/Repos/software/RIOT/tests/periph_rtt/tests/01-run.py", line 36, in testfunc
    assert elapsed < (MAX_HELLOS * period * (1 + PRECISION))
AssertionError
make: *** [/home/maribu/Repos/software/RIOT/makefiles/tests/tests.inc.mk:22: test] Error 1
```

Still a failure, but a less severe ;-)

**Comment by maribu** [comment]
Here the output with pyterm to see by how much the RTT is off:

```
2021-03-30 14:53:26,810 # Help: Press s to start test, r to print it is ready
s
2021-03-30 14:53:28,697 # START
2021-03-30 14:53:28,703 # main(): This is RIOT! (Version: buildtest)
2021-03-30 14:53:28,703 # 
2021-03-30 14:53:28,706 # RIOT RTT low-level driver test
2021-03-30 14:53:28,707 # RTT configuration:
2021-03-30 14:53:28,710 # RTT_MAX_VALUE: 0xffffffff
2021-03-30 14:53:28,711 # RTT_FREQUENCY: 1
2021-03-30 14:53:28,711 # 
2021-03-30 14:53:28,714 # Testing the tick conversion
2021-03-30 14:53:28,718 # Trying to convert 1 to seconds and back
2021-03-30 14:53:28,721 # Trying to convert 256 to seconds and back
2021-03-30 14:53:28,725 # Trying to convert 65536 to seconds and back
2021-03-30 14:53:28,728 # Trying to convert 16777216 to seconds and back
2021-03-30 14:53:28,734 # Trying to convert 2147483648 to seconds and back
2021-03-30 14:53:28,734 # All ok
2021-03-30 14:53:28,735 # 
2021-03-30 14:53:28,736 # Initializing the RTT driver
2021-03-30 14:53:28,739 # This test will now display 'Hello' every 5 seconds
2021-03-30 14:53:28,740 # 
2021-03-30 14:53:28,742 # RTT now: 0
2021-03-30 14:53:28,745 # Setting initial alarm to now + 5 s (5)
2021-03-30 14:53:28,747 # rtt_get_alarm() PASSED
2021-03-30 14:53:28,751 # Done setting up the RTT, wait for many Hellos
2021-03-30 14:53:34,559 # Hello
2021-03-30 14:53:40,383 # Hello
2021-03-30 14:53:46,208 # Hello
2021-03-30 14:53:52,033 # Hello
2021-03-30 14:53:57,858 # Hello
2021-03-30 14:54:03,683 # Hello
2021-03-30 14:54:09,504 # Hello
```

But let's have another PR for that.

**Comment by fjmolinas** [comment]
> Here the output with pyterm to see by how much the RTT is off:
> 
> ```
> 2021-03-30 14:53:26,810 # Help: Press s to start test, r to print it is ready
> s
> 2021-03-30 14:53:28,697 # START
> 2021-03-30 14:53:28,703 # main(): This is RIOT! (Version: buildtest)
> 2021-03-30 14:53:28,703 # 
> 2021-03-30 14:53:28,706 # RIOT RTT low-level driver test
> 2021-03-30 14:53:28,707 # RTT configuration:
> 2021-03-30 14:53:28,710 # RTT_MAX_VALUE: 0xffffffff
> 2021-03-30 14:53:28,711 # RTT_FREQUENCY: 1
> 2021-03-30 14:53:28,711 # 
> 2021-03-30 14:53:28,714 # Testing the tick conversion
> 2021-03-30 14:53:28,718 # Trying to convert 1 to seconds and back
> 2021-03-30 14:53:28,721 # Trying to convert 256 to seconds and back
> 2021-03-30 14:53:28,725 # Trying to convert 65536 to seconds and back
> 2021-03-30 14:53:28,728 # Trying to convert 16777216 to seconds and back
> 2021-03-30 14:53:28,734 # Trying to convert 2147483648 to seconds and back
> 2021-03-30 14:53:28,734 # All ok
> 2021-03-30 14:53:28,735 # 
> 2021-03-30 14:53:28,736 # Initializing the RTT driver
> 2021-03-30 14:53:28,739 # This test will now display 'Hello' every 5 seconds
> 2021-03-30 14:53:28,740 # 
> 2021-03-30 14:53:28,742 # RTT now: 0
> 2021-03-30 14:53:28,745 # Setting initial alarm to now + 5 s (5)
> 2021-03-30 14:53:28,747 # rtt_get_alarm() PASSED
> 2021-03-30 14:53:28,751 # Done setting up the RTT, wait for many Hellos
> 2021-03-30 14:53:34,559 # Hello
> 2021-03-30 14:53:40,383 # Hello
> 2021-03-30 14:53:46,208 # Hello
> 2021-03-30 14:53:52,033 # Hello
> 2021-03-30 14:53:57,858 # Hello
> 2021-03-30 14:54:03,683 # Hello
> 2021-03-30 14:54:09,504 # Hello
> ```
> 
> But let's have another PR for that.

Do you have an idea of the reason for this? The internal oscillator maybe?

**Comment by fjmolinas** [comment]
> But let's have another PR for that.

Agreed.

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by maribu** [comment]
Thanks :-)

**Pull request merged**
