### PR TITLE
release-notes.txt: Add Release 2018.10.1 notes [backport 2019.01]

### PR DESCRIPTION
**Pull request by aabadie**
# Backport of #10924

### Contribution description
This PR adds the (sub) Release 2018.10.1 notes.

It contains the list of merged PRs and commits in `2018.10-branch` between `2018.10-devel` tag and the #10285  

### Testing procedure
Read

### Issues/PRs references
None so far

### CODE REVIEW

**Comment by aabadie** [comment]
This is not a joke. It is required otherwise the 2019.01 release notes cannot be backported smoothly on 2019.01-branch...

**Comment by miri64** [comment]
> This is not a joke. It is required otherwise the 2019.01 release notes cannot be backported smoothly on 2019.01-branch...

You seem surprised. ;-)

**Comment by miri64** [comment]
Can't properly revise right now, since I'm on a train right now and later will be unavailable until around midnight. @emmanuelsearch @jia200x can one of you review maybe?

**Comment by jia200x** [comment]
Commit matches. All OK

**Comment by aabadie** [comment]
Thanks @jia200x !

**Comment by miri64** [comment]
> Can't properly review right now, since I'm on a train and later will be unavailable until around midnight. @emmanuelsearch @jia200x can one of you review maybe?

I didn't even realize that this was about 2018.10.1 so bad was my capability to review.

**Comment by miri64** [comment]
> > This is not a joke. It is required otherwise the 2019.01 release notes cannot be backported smoothly on 2019.01-branch...
> 
> You seem surprised. ;-)

Honestly, now that I know that this was about `2018.10.1-branch` I don't understand either. `2018.10.1-branch` and `2019.01-branch` should be independent from each other. What happened?

**Comment by aabadie** [comment]
> What happened?

The release notes were conflicting !

**Comment by miri64** [comment]
But how? I mean this branch has nothing to do with `2019.01` so how did the backport help?

**Comment by miri64** [comment]
Ahhh... this PR is not against the `2018.10.1-branch` but backports the `2018.10.1` release notes to the `2019.01-branch`. This makes sense, since `2018.10.1` was released after the feature freeze of `2019.01`!

**Pull request merged**
