### PR TITLE
net/gcoap: Fix typo, replacing _uri with _proxy

### PR DESCRIPTION
**Pull request by Teufelchen1**
### Contribution description

Hello 🦇

this fixes a small typo, ensuring the correct buffer is checked.

### Testing procedure

`make -C tests/net/gcoap_dns all test` should be enough, I do not see other use cases of this function.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
You could also just 

```C
return strscpy(proxy, _proxy, proxy_len);
```

which would simplify this function quite a bit.

**Comment by Teufelchen1** [comment]
@benpicco I added a fixup showing your proposed solution. Feedback?

**Review by benpicco — APPROVED** [review]
Looks good to me, I wonder if we should just return `-E2BIG` instead so we don't have to convert the error value, but that would also require a doc update.

Please squash.

**Comment by miri64** [comment]
> I wonder if we should just return `-E2BIG` instead so we don't have to convert the error value, but that would also require a doc update.

Yeah, that would be an API change. So voting to keep it `-ENOBUFS`.

**Pull request merged**
