### PR TITLE
cpu/esp_common: fixes common CPU configurations

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the handling of `cpu_conf.h` in `cpu/esp_common`. Furthermore, it removes the platform specific `heap_stats` function in `cpu/esp_common` if module `esp_idf_heap` is not used.

ESP CPUs share common definitions in `cpu/esp_common`. There is also a `cpu_conf.h` file in `cpu/esp_common` which should contain common CPU configurations. However, this file was not included in the CPU specific `cpu_conf.h` in `cpu/esp32` and `cpu/esp8266` so that the definitions in this file had no affect. Furthermore, to include this file in CPU specific `cpu_conf.h`, it has to be renamed.

### Testing procedure

Compilation should succeed in Murdock.

### Issues/PRs references

Prerequisite for PR #13517

### CODE REVIEW

**Comment by benpicco** [comment]
Hm, I ran `tests/pkg_littlefs2` on both `esp32-wroom-32` and `esp8266-esp-12x` but didn't see the crashes like on CI.

**Comment by gschorcht** [comment]
> Hm, I ran `tests/pkg_littlefs2` on both `esp32-wroom-32` and `esp8266-esp-12x` but didn't see the crashes like on CI.

Yes, this happens sporadically. The test synchronization seems a little unstable. It's the same as with `nrf52dk`. I bet it won't happen next time.

**Comment by benpicco** [comment]
> Yes, this happens sporadically. The test synchronization seems a little unstable.

Yea but this time it prints a

```
EXCEPTION!! exccause=0 (IllegalInstructionCause) @8008783c excvaddr=00000000

.heap: 183848 (used 848, free 183000) [bytes]

register set
pc      : 400d96c5	ps      : 00060130	exccause: 00000000	excvaddr: 00000000
epc1    : 400d96c5	epc2    : 00000000	epc3    : 00000000	epc4    : 00000000
epc5    : 00000000	epc6    : 00000000	epc7    : 00000000	
a0      : 8008783c	a1      : 3ffb2e00	a2      : 3ffb30c4	a3      : 00000000
a4      : 00000000	a5      : 0000002b	a6      : 00000002	a7      : 3ffb2f00
a8      : 80082907	a9      : 3ffb2de0	a10     : 00000000	a11     : ffffffff
a12     : 00060120	a13     : 0000ff00	a14     : 00ff0000	a15     : ff000000
lbeg    : 40089f29	lend    : 40089f39	lcount  : fffffffc

Timeout in expect script at "child.expect(r'OK \(\d+ tests\)')" (tests/pkg_littlefs2/tests/01-run.py:14)
```

**Comment by gschorcht** [comment]
> Yea but this time it prints a
> 
> ```
> EXCEPTION!! exccause=0 (IllegalInstructionCause) @8008783c excvaddr=00000000

Wow, it's a crash. But, I don't see how the changes in this PR should affect the `littlefs` tests. Furthermore, they work locally for me. The last nightly build had also no problems, but these tests were executed on another node. Maybe node `pi-6356c652` has a hardware problem with the flash.

**Comment by gschorcht** [comment]
H, this time the tests failed again but on node `pi-e4c1d860`. This is really weird.

**Comment by gschorcht** [comment]
@benpicco Obviously it was again a problem of a write access of the `littlefs(2)` file system to the flash memory. As explained in comment https://github.com/RIOT-OS/RIOT/pull/12955#issuecomment-589897334, the cache of the flash memory is disabled during write accesses and the program code in the IROM is not available. Therefore, only program code from the IRAM can be executed. That it sometimes works and sometimes not is probably due to different delays during writing.

Although commit https://github.com/RIOT-OS/RIOT/pull/12955/commits/5b4389cf46acff8c9439456068ef0d9fae3ef34e already moved the functions of the `littlefs(2)` filesystems to the IRAM, some of these functions in turn called system functions that were still in the IROM. Moving these functions to the IRAM seems to solve the problem.

The test runs are working now. The remaining failures are unrelated.

**Comment by gschorcht** [comment]
@kaspar030 `tests/nordic_softdevice` fails permanently on `nrf52dk`. Is anything known?

**Comment by benpicco** [comment]
Those tests have been failing quite reliably in the past…

**Pull request merged**
