### PR TITLE
ng_ndp: fix documentation

### PR DESCRIPTION
**Pull request by authmillenon**

### CODE REVIEW

**Comment by Lotterleben** [comment]
ACK

**Comment by Lotterleben** [comment]
(this can be merged without travis, right?)

**Comment by authmillenon** [comment]
I'd say so, but won't do it...

**Comment by Lotterleben** [comment]
:D Since it's not a critical fix, I'll leave the tab open and wait for travis to be happy.

**Comment by x3ro** [comment]
Agreed that this doesn't need a Travis build. @Lotterleben can you cancel it and merge? Should I?

**Comment by Lotterleben** [comment]
I don't dare to, if you want to push the button go ahead :D

**Pull request merged**
