### PR TITLE
boards/samr21-xpro: add a note about EDBG UART limitation

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The stdin line length limitation can be very surprising and there is nothing in RIOT that would explain it.
To prevent users from scratching their head, add a note to the docs. 

### Testing procedure

execute 

    echo 012345678901234567890123456789012345678901234567890123456789

in e.g. `tests/shell`

### CODE REVIEW

**Comment by bergzand** [comment]
I can't confirm it right now, but I would expect that this issue is present on any eDBG based board such as the samr54-xpro. Should we also add the note on the other eDBG boards?

**Comment by benpicco** [comment]
The same54-xpro doesn't have this issue.
The samr21-xpro is also much older, so it's well possible this is fixed in newer versions.

I can check `samd21-xpro` though.

**Comment by maribu** [comment]
Note that the edbg firmware can be updated with the Windoofs-only "Atmel Studio".

I guess this could fix the issue?

**Comment by bergzand** [comment]
> I can check `samd21-xpro` though.

Any luck checking this?

**Review by bergzand — APPROVED** [review]

**Comment by benpicco** [comment]
Indeed `samd20-xpro` and `saml21-xpro` show the same issue.

I'll try `saml10-xpro` and `same54-xpro` shortly.

**Comment by maribu** [comment]
Let's get this in as is. The other EDBG boards can be tested later on and subsequently be documented.

**Pull request merged**
