### PR TITLE
gh-actions: check-labels: move to upstream fix

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Fixes the current issue of the check-label action.

### Testing procedure
See https://github.com/miri64/RIOT/pull/39

### Issues/PRs references
Follow-up on #19101

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by kaspar030** [comment]
bors merge

**Comment by miri64** [comment]
Reactivation of bors check can be found in https://github.com/RIOT-OS/RIOT/pull/19161

**Comment by miri64** [comment]
bors merge ...

**Comment by aabadie** [comment]
bors merge

**Pull request merged**
