### PR TITLE
uncrustify: use unified diff to generate GH annotation

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
`git diff` creates diffs where the file name starts with `a/` or `b/` respectively. These are obviously not in path, so the Github annotations point to nowhere when the path is used without accounting for this.

This fixes the GH annotation parsing to account for that.

### Testing procedure
I will provide a test commit to generate annotations. The annotations should now show up in the 'Files' tab as well.

### Issues/PRs references
Follow-up on #15748.

### CODE REVIEW

**Comment by jia200x** [comment]
I really missed that one during review... Sorry
Let's check what the static-checks report

**Comment by jia200x** [comment]
Current master shows a wrong path:
```
static-tests: a/core/include/log.h#L85 
```

With this PR:
```
static-tests: core/msg.c#L394 
```

It works as expected

**Comment by jia200x** [comment]
and now we see the annotations :)

**Review by jia200x — APPROVED** [review]
ACK

**Comment by jia200x** [comment]
Please remove bogus commit :)

**Comment by miri64** [comment]
> Please remove bogus commit :)

Done.

**Pull request merged**
