### PR TITLE
boards/frdm: update openocd version requirements

### LINKED ISSUE #10857: frdm-kw41z: requires newer flasher than openocd `0.10` from `ubuntu-bionic`.
#### Description

While trying to use the `frdm-kw41z` I noticed an error message when compiling and it cannot be flashed. I am using `openocd 0.10` and also does not work with `USE_OLD_OPENOCD`.

#### Steps to reproduce the issue

Fixed in https://github.com/RIOT-OS/RIOT/pull/10888

> Clean shows an error (Maybe `clean` could be used to detect unwanted messages as it should be completely silent).~
> ```
> BOARD=frdm-kw41z make --no-print-directory -C examples/default/ clean
> /bin/sh: 1: Syntax error: Missing '))'
> ```

When flashing with `openocd v0.10` from ubuntu `bionic` I get

```
### Flashing Target ###
/home/harter/work/git/RIOT/examples/default/bin/frdm-kw41z/default.elf is fine.
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : add flash_bank kinetis klx.flash
adapter speed: 1000 kHz
none separate
cortex_m reset_config sysresetreq
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : No device selected, using first device.
Info : J-Link OpenSDA 2 compiled May  6 2016 11:04:17
Info : Hardware version: 1.00
Info : VTarget = 3.300 V
Info : clock speed 1000 kHz
Info : SWD DPIDR 0x0bc11477
Error: MDM: failed to read ID register
Info : SWD DPIDR 0x0bc11477
Info : klx.cpu: hardware has 2 breakpoints, 2 watchpoints
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* klx.cpu            cortex_m   little klx.cpu            running
Info : MDM: Chip is unsecured. Continuing.
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00000790 msp: 0x1fff8200
auto erase enabled
Error: Unsupported K-series
Error: MCU is unsupported, SDID 0x41591004
Error: auto_probe failed
```

According to the documentation, version `0.10` should be enough. I noticed an option with `USE_OLD_OPENOCD` but it also fails because there is no configuration file for this one:

```
/home/harter/work/git/RIOT/dist/tools/openocd/openocd.sh flash /home/harter/work/git/RIOT/examples/default/bin/frdm-kw41z/default.elf
### Flashing Target ###
Error: Unable to locate OpenOCD configuration file
       (/home/harter/work/git/RIOT/boards/common/frdm/dist/old-openocd-klx.cfg)
/home/harter/work/git/RIOT/examples/default/../../Makefile.include:534: recipe for target 'flash-only' failed
make: *** [flash-only] Error 1
```

#### Expected results

A silent `make clean` and being able to flash.

#### Versions

Ubuntu 18.04 bionic.

```
openocd --version
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
```
```
apt-cache show openocd
Package: openocd
Architecture: amd64
Version: 0.10.0-4
Priority: extra
Section: universe/embedded
Origin: Ubuntu
```

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR drops the `Makefile.include` code and OpenOCD config related to older versions of OpenOCD (<0.10) for the NXP FRDM boards.

It also document the need for a built from source and more recent version of OpenOCD for KW41Z CPU models.

### Testing procedure

The following command should work with an OpenOCD version >= 0.10:
```
$ make BOARD=frdm-k64f -C examples/hello-world flash
```

The following command should work with a built from OpenOCD version that is earlier than https://github.com/ntfreak/openocd/commit/2c8602ed9f084d6680cec7d0ca1d5dc71c865a5f: 
```
$ make BOARD=frdm-kw41z -C examples/hello-world flash
$ make BOARD=usb-kw41z -C examples/hello-world flash
```

### Issues/PRs references

fixes #10857 (according to https://github.com/RIOT-OS/RIOT/issues/10857#issuecomment-458117903, only the doc is missing and this is added by 4c794c1)

### CODE REVIEW

**Comment by aabadie** [comment]
> Might people with old raspbian not have it though? Thinking of our hil setups?

CC'ing @MrKevinWeiss then.

**Comment by MrKevinWeiss** [comment]
Thanks for the heads up.  Let me run it!

**Comment by MrKevinWeiss** [comment]
[Running on HiL](https://ci.riot-os.org/hil/blue/organizations/jenkins/RIOT-HIL/detail/master/31/pipeline)

**Comment by MrKevinWeiss** [comment]
So far it looks like flash on the `frdm-kw41` and `frdm-k22f` are passing...  It also seems like we are using the 0.10.0 openOCD version.

**Comment by fjmolinas** [comment]
> So far it looks like flash on the frdm-kw41 and frdm-k22f are passing... It also seems like we are using the 0.10.0 openOCD version.

What distribution are you using?

**Comment by MrKevinWeiss** [comment]
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

But we use ansible to compile openOCD from sources I think (this is more a @smlng thing):
```
openocd -v
Open On-Chip Debugger 0.10.0+dev-00925-g08195413 (2019-08-29-11:22)
```

**Comment by smlng** [comment]
yes we compile openocd from source, which include the respective commit for kw41z by @gebart

**Comment by aabadie** [comment]
> yes we compile openocd from source, which include the respective commit for kw41z 

Thanks @smlng. So I guess we are good here.

**Comment by fjmolinas** [comment]
> Thanks @smlng. So I guess we are good here.

Yep, ACK!

**Pull request merged**
