### PR TITLE
samd21/i2c: add feedback in case transfer failed

### PR DESCRIPTION
**Pull request by daniel-k**
According to the I2C interface the return value of any read or write function is either 'the bytes transfered' or `-1` in case of undefined device.

With this PR those functions now return `0` in case of general failure, so the user/driver code can react accordingly.

### CODE REVIEW

**Comment by bapclenet** [comment]
I definitely agree with PR, this is great that you had a look at it! I don't see any errors here. 
Just why do we need to return -4 for a kind of error if we don't return it afterwards? 
I mean, you wrote:

    static inline int _write(SercomI2cm *dev, char *data, int length)
    ...
    return -4;

And then 

    if(_write(i2c, (char *)(&reg), 1) < 0) return 0;


-4 will never be handle by the device driver. So I don't know if it is really useful to return different value for different errors. What's your opinion?

**Comment by daniel-k** [comment]
The Riot I2C interface doesn't provide detailed feedback in case of failure, but internally the driver has some additional feedback. It was just that you could use this information maybe somewhere, but then it turned out that it's not the case. I don't have an opinion on this as long as the I2C interface doesn't provide more detailed feedback.

**Comment by bapclenet** [comment]
Ok so we should merge your PR and someone might want to edit the I2C driver and use those feedback values.
Will try it on Monday

**Comment by bapclenet** [comment]
Ok great! Let's wait for Travis and merge

**Comment by bapclenet** [comment]
@OlegHahm, may I merge this PR even if it's not for the release? It's a very small add.

**Comment by cgundogan** [comment]
If I may put my two cents in, I'd say only bug fixes and discussed features should be included in the coming release. Looking at the number of PRs and issues that are still open and tagged for this release.. it is strangely growing

**Comment by OlegHahm** [comment]
I agree with @cgundogan. Even if it's only a small patch, we have to cut the line somewhere. Hopefully, we will have the release by the end of next week.

**Comment by bapclenet** [comment]
Ok, will wait the release then

**Comment by LudwigOrtmann** [comment]
Related: 
https://github.com/RIOT-OS/RIOT/issues/3366

**Comment by PeterKietzmann** [comment]
@bapclenet, feature freeze is over. We should find out why the build test fails for M0 group and merge the PR then.

**Comment by daniel-k** [comment]
> We should find out why the build test fails for M0 group

Doesn't fail anymore. Maybe some travis issue some time ago?

**Comment by PeterKietzmann** [comment]
Ah nice. Well, as @bapclenet already ACKed I'm gonna hit the button now

**Comment by bapclenet** [comment]
Thanks, @PeterKietzmann :-)

**Pull request merged**
