### PR TITLE
doc: add 'Getting started' page

### PR DESCRIPTION
**Pull request by authmillenon**
Re-adds getting started section as its own page.

### CODE REVIEW

**Comment by authmillenon** [comment]
@OlegHahm and @haukepetersen might want to look over this, too.

**Comment by OlegHahm** [comment]
What's the source of this document or is it written from scratch?

**Comment by authmillenon** [comment]
The old introduction page / https://github.com/RIOT-OS/RIOT/wiki/Introduction

**Comment by OlegHahm** [comment]
Seems good. ACK.

**Comment by authmillenon** [comment]
Squashed

**Comment by haukepetersen** [comment]
and go.

**Pull request merged**
