### PR TITLE
boards/arduino-nano: Support for the Arduino Nano

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR adds support for the Arduino Nano. The Arduino Nano board is the cheapest member of the Arduino family and used the same MCU as the Arduino Uno. It differs in the form factor (the Nano is much smaller), it uses an integrated FT232RL TTL adapter instead of an ATmega16u2 to provide access to the serial console via USB, and it uses a different bootloader (which occupies 2 KiB of the 32 KiB flash instead of 0.5 KiB occupied on the Arduino Uno). This commit mostly copy pastes code from the Arduino Uno.  

### Testing procedure

- Check the provided documentation
- Check if `make BOARD=arduino-nano flash` and `make BOARD=arduino-nano term` works for `examples/hello-world` 

As this shares most code with the Arduino UNO, no huge troubles are expected.

### Issues/PRs references

None

### CODE REVIEW

**Comment by maribu** [comment]
TODO: Is the serial device on Linux really `/dev/ttyUSB0` for Arduino Nano? (I own a board that should be mostly compatible to the Arduino Nano and looks similar to it, but it is not actually an Arduino at all.) Maybe someone can help me with that?

**Comment by ZetaR60** [comment]
@maribu I think you need to find someone with an Arduino Nano in order to complete this PR. Your similar board is not enough because we have no guarantee that it will translate over to the Arduino Nano.

**Comment by maribu** [comment]
@ZetaR60: All Arduino clones I saw so far use the same PIN layout, the same MCU, and the same bootloader. Some use a different USB to UART chip, which is a minor inconvenience on Linux machines. E.g. the device file of official Arduino UNO will be located at `/dev/ttyACM0`, while most clones will have it named `/dev/ttyUSB0`. Apart from that and the missing Arduino logo the clones are identical to the real boards.

This PR uses `/dev/ttyUSB0`, as [this almost accepted PR](https://github.com/RIOT-OS/RIOT/pull/7540) used it also. But maybe that PR was never tested on an official board...

**Comment by maribu** [comment]
@SemjonKerner, @sebastiankliem, @smlng: You were active in the old and apparently dead Arduino Nano PR. Did you test that PR on original hardware? If so, could test this PR, also?

**Comment by ZetaR60** [comment]
@maribu The code would probably end up okay, but in my opinion should still be tested at least once on an original. I think it is fine to go ahead and work on the PR, as it shouldn't be too hard to find someone that has one.

**Comment by maribu** [comment]
@ZetaR60: I totally agree that this should be tested on an original Arduino. I just wanted to point out, that apart from the `PORT` value on Linux it is unlikely that something wont work.

**Comment by maribu** [comment]
Another issue: Currently this PR contains no C code or header files. As result, Doxygen documentation for this board is available. May creating a `board.h` that contains the documentation and an `#include` to the Arduino Uno's `board.h` would be better?

Or maybe the whole folder should be dropped and instead some Makefile magic like

```Makefile
ifeq($(BOARD),arduino-zero)
  export PROGRAMMER_SPEED ?= 57600
  BOARD := arduino-uno
endif
```
should be used?

**Comment by kYc0o** [comment]
Please look at #9130, I'd like to avoid more code duplication by adding more atmega based boards. I know the PR seems big but I'll try to split it once they allow me to squash.

**Comment by maribu** [comment]
@kYc0o: I'm not sure if I got you. Are you suggesting to wait until https://github.com/RIOT-OS/RIOT/pull/9130 is merged, than rebase this PR against it?

Actually, I'm not even sure if this PR is really required. Updating [the wiki page](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-Arduino-Nano) to tell users to just use treat the Nano as an Arduino Uno with a different programmer speed might be just as fine. E.g. like this:
``` sh
make BOARD=arduino-uno PROGRAMMER_SPEED=57600 flash
make BOARD=arduino-uno term
```

**Comment by sebastiankliem** [comment]
I did not test the code on original hardware. Unfortunately, I do not have any capacity to work on this further.

**Comment by kYc0o** [comment]
> @kYc0o: I'm not sure if I got you. Are you suggesting to wait until #9130 is merged, than rebase this PR against it?

I'd say yes, wait to unify and clean up the code. Then we continue to add more boards.

For the sake of consistency, I think the board folder is needed, along with the required (minimal) files. After #9130 is merged this should be 2 or 3 files max.

**Comment by maribu** [comment]
Maybe @miri64 might want to take a look, as I shamelessly stole all code in this PR from her ;-)

In the meantime I verified that `/dev/ttyUSB0` is indeed the correct path even for non-clones, as the Nano does not use the ATmega32u2 for USB connectivity but a USB TTL adapter. According to the doc of that adapter `dev/ttyUSBx` is correct on Linux.

**Comment by miri64** [comment]
Again: not my domain (I only reviewed #7306 because I happened to have it in my drawer ;-)).

**Comment by kYc0o** [comment]
You need to blacklist the board on some tests before Murdock is happy.

**Comment by SemjonKerner** [comment]
I believe I have a nano at home. If so I can test this PR by beginning of the next week.

**Comment by SemjonKerner** [comment]
My "nano" is indeed a clone. The PR works out of the box, but sadly I couldn't flash some tests and examples, like `examples/default` and `tests/saul`, for a lack of memory. It came back with  _section '.data' is not within region 'data'_ and some more overflow messages.

I did nothing but install the compiler, and make `examples/hello-world`, `tests/shell`, and two or three `tests/driver_*`.
If you want me to test anything specific, pls summon me again.

**Comment by maribu** [comment]
> but sadly I couldn't flash some tests and examples, like examples/default and tests/saul,

Thats expexted, this doesn't work for the Uno either. Thanks for testing!

**Comment by kYc0o** [comment]
Everything seems ok but (again...) the board needs to be marked as insufficient memory...

**Comment by maribu** [comment]
So, after updating 141 Makefiles and adding the Nano `BOARD_INSUFFICIENT_MEMORY` or to `BOARDS_BLACKLISTED`, everything is green now.

@kYc0o: Mind to merge before anyone touches one of the 141 Makefiles? Otherwise I would need to rebase again and solve the merge conflicts.

**Comment by kYc0o** [comment]
Oops, the latest commit message has "Upadte" twice, but it's rather a detail. Thanks for your contribution @maribu !

**Comment by maribu** [comment]
> Oops, the latest commit message has "Upadte" twice

That kind of error is really typical for me... *faceplam*

**Pull request merged**
