### PR TITLE
examples: Add asynchronous Rust example

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

Async is a popular coding style in Rust. Basic support for it is provided in riot-wrappers, mainly deferring to embassy tools.

### Testing procedure

* Run the example

### Caveats

There are fewer components exposed for async than there are for synchronous code in the riot-wrappers. Nonetheless, this should be user visible, if only to find what users' priorities are in terms of added components.

<del>[edit: This is based on #20829, only the most recent commit "counts"; I should probably rebase once that is merged so that GitHub shows things correctly]</del>
[edit2: This is now blocked by #20831 to avoid merge races]

### CODE REVIEW

**Comment by chrysn** [comment]
It's not pretty that this has to take care of its own to enable the right portable-atomics; looking for better ways, but that shouldn't need to stop things here.

**Comment by chrysn** [comment]
Added Makefile.ci (a short one -- this is just firing a few timers), and rebased onto #20831 to avoid logging a BOARDS_BLACKLIST entry around through parallel development.

**Comment by chrysn** [comment]
On the caveat topic of not many wrappers being available, there is now a structured list at https://github.com/RIOT-OS/rust-riot-wrappers/issues/111

**Review by maribu — APPROVED** [review]
Code looks good to me and I trust your testing :)

**Comment by chrysn** [comment]
I've taken this out of the merge queue for a moment (it's a few-minutes merge) because this PR includes https://github.com/RIOT-OS/RIOT/pull/20831 commits as well.

If you have reviewed both parts and are happy with them, please leave an ACK there too, and we can restart this PR's merge queue run. I don't know what'd would happen if a a PR (20831) gets merged by another PR without itself qualifying for lack of ACKs, it could leave the PR in a weird state.

**Comment by chrysn** [comment]
Thank you and mguetschow, both reviewed now, pressing the button. (With checks green, even if there is a fluke that keeps 20831 from being merged through the queue, and this one goes through, GitHub should recognize both as merged with all checks green).

**Pull request merged**
