### PR TITLE
Use {} notation for empty while loops

### PR DESCRIPTION
**Pull request by gebart**
Clang gives the following error for empty while loops:
```
.../riot/cpu/stm32l1/periph/i2c.c:227:51: error: while loop has empty body [-Werror,-Wempty-body]
                while (!(i2c->SR1 & I2C_SR1_RXNE));
                                                  ^
.../riot/cpu/stm32l1/periph/i2c.c:227:51: note: put the semicolon on a separate line to silence this warning
```

What are your opinions on this syntax?
I agree with @haukepetersen (https://github.com/RIOT-OS/RIOT/pull/4643#discussion_r50437513) that putting a single semicolon on a separate line looks strange. With the empty brace notation everything remains on one line but it is still clear that the while loop is supposed to be empty.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Isn't that a very strange error message? With `{}` the body is still empty...

However, I have no strong feelings about this syntax and if this is required in order to build with clang, I can live with it.

**Comment by gebart** [comment]
I agree that the message from Clang is wrong, the body is still empty.

**But**, the purpose of the warning is to catch unintentional infinite loops like:
```c
int i = 3;
while(i > 0);
{
  printf("Hello world!\n");
  --i;
}
```

**Comment by haukepetersen** [comment]
If this is something clang worries about, I guess we have to comply. I am much more in favor of putting `{}` instead of a semicolon in the next line then, too.

To reduce trouble in the future, I would propose to do two things on top of this PR: add this to the coding style conventions in the wiki as 'MUST', and how about we add a check to Travis, so that this is addressed automatically during the build-test?

**Comment by OlegHahm** [comment]
:+1: for the Wiki, but for Travis, I wouldn't introduce a style checker and compiling everything with gcc _and_ clang...I guess no!

**Comment by haukepetersen** [comment]
but as long as we are not compiling with clang, we will always have new code with `while();` introduced because there is always someone not paying attention...

**Comment by kaspar030** [comment]
Is "-Wno-empty-body" an option?

**Comment by LudwigKnuepfer** [comment]
Can't uncrustify take care of this?

**Comment by cgundogan** [comment]
>Can't uncrustify take care of this?

only if we finally decide whether we want to run uncrustify for each pull request or not

**Comment by kYc0o** [comment]
I'm not sure that use "computational methods" to be sure about the quality of code is the best approach to deal with this. There is a chart about how to contribute to the project, I think that is somehow better if we can trust contributors that they will look into this chart and try to make his/her code follow the style, instead of run automatic tools to change it. That's also the case about the travis checks that run and fail because the contributor didn't take care about the CI behaviour.

Perfect coding is difficult for us and at the same time develop a perfect tool to look into it seems to me so difficult too.

**Comment by OlegHahm** [comment]
> only if we finally decide whether we want to run uncrustify for each pull request or not

IMO that's pretty much decided: no! I don't want to see the CI failing for style related issues. There are sometimes good reasons to bend the coding conventions a little bit.

**Comment by OlegHahm** [comment]
But I just realized: we're discussing a topic that is actually out of scope for this PR (once again).

**Comment by OlegHahm** [comment]
Needs a rebase.

**Comment by gebart** [comment]
rebased

**Comment by gebart** [comment]
I have updated the wiki (https://github.com/RIOT-OS/RIOT/wiki/Coding-conventions) with the statement:

>* Use empty braces for empty while loops waiting for a hardware register instead of semicolon. `while (HW_STATUS != STATUS_OK) {}` is correct, `while (HW_STATUS != STATUS_OK);` is wrong.

Is anyone opposed to the changes in this PR? Can we get an ACK?

**Comment by kaspar030** [comment]
ACK!

**Pull request merged**
