### PR TITLE
boards/arduino*: Added/refactored params for W5100

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description
- ATmega based boards: Added parameter for W5100 to `board_common.h`
- Arduino Due based boards: Use `board.h` to override `W5100_PARAM_CS` and `W5100_PARAM_EVT` instead of providing an adapted copy of `w5100_params.h`

### Testing procedure
Running `USEMODULE=w5100 BOARD=arduino-mega2560 make` in `examples/gnrc_minimal` should successfully build and when flashed should respond to `ping6`. (The example will print the IPv6 address over UART).

The same should still work for `arduino-due`.

### Issues/PRs references
None.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Code-wise makes sense and I set proper labels. Have no hardware to test though.

**Comment by maribu** [comment]
Maybe @kYc0o has an Ethernet Shield and can test this. @kYc0o, do you also have an Arduino Due and mind testing it for both Mega2560 and Due?

**Comment by miri64** [comment]
Still works for Arduino Due. However, I didn't check transmitting packets since I don't have my Laptop with me at the moment.

**Comment by miri64** [comment]
Ok I tried it now by disconnection my normal workstation from the Internet and doing it with that. Still works as good as it does in master ;-).

**Comment by PeterKietzmann** [comment]
@miri64  this PR is only about pin configuration so any kind of device interaction would be a succeeded test here. Was this the case?

**Comment by miri64** [comment]
> I'm not sure if I understood you correctly. Did this PR lead to the W5100 becoming unreliable (similar to the issues in #10412), but it works reliable in master?

Yes at least that was what I observed. But I can recheck tomorrow. Maybe some "cosmic rays" were at fault, because I agree with @PeterKietzmann that this shouldn't affect device interaction.

**Comment by miri64** [comment]
I can confirm that the unreliabilities also occur on master. So sorry for the noise.

**Comment by miri64** [comment]
Doc is ok under our current practices, but might lead to problems with later Doxygen versions (see #10815)

**Pull request merged**
