### PR TITLE
boards/efm32-based: Model features in Kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This models in Kconfig all the features of the efm32-based boards:
- `ikea-tradfri`
- `slstk3401a`
- `slstk3402a`
- `sltb001a`
- `slwstk6000b-slwrb4150a`
- `slwstk6000b-slwrb4162a`
- `stk3600`
- `stk3700`

### Testing procedure
- Check the symbol organization
- Green CI
- `tests/kconfig_features` should pass for all boards

### Issues/PRs references
Part of #14148

### CODE REVIEW

**Comment by basilfx** [comment]
@leandrolanzieri I guess that there is not much to test, except that it passes CI?

**Comment by leandrolanzieri** [comment]
> @leandrolanzieri I guess that there is not much to test, except that it passes CI?

Yes, that and that the symbol organization makes sense. In this case it was pretty straightforward because the CPUs are nicely organized in families (thanks for that :)

**Comment by basilfx** [comment]
Should the modules like `USEMODULE += silabs_aem` also be in there? I do see `USEMODULE += boards_common_silabs` though.

**Comment by leandrolanzieri** [comment]
> Should the modules like `USEMODULE += silabs_aem` also be in there? I do see `USEMODULE += boards_common_silabs` though.

No, this is only to model features. `BOARD_COMMON_SILABS` is a symbol to provide the common features, it is not related with the module `boards_common_silabs`.

**Comment by basilfx** [comment]
That makes sense. Thanks for explaining.

**Comment by leandrolanzieri** [comment]
Thanks for reviewing!

**Pull request merged**
