### PR TITLE
 sys/test_helper: Add test_helper module

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

This PR adds a test_helper module adds a collection of helpers used for shell based tests.  Specifically it adds basic, lightweight json formatting, print_echo and collects module dependencies.  This should make it easier to stick to a standard way of writing and reduce code duplication.

### Testing procedure

`make all -C tests/shell/ test`

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
@smlng should I also add an implementation with it (maybe the spi so it doesn't break the HiL)?

**Comment by MrKevinWeiss** [comment]
I should maybe add a different pseudomodule that brings in the shell everything something like `USEMODULE=test_helper_interactive` or `USEMODULE=test_helper_shell`

**Comment by MrKevinWeiss** [comment]
Implemented in RFtests but I don't want to close until some conclusion is reached.

**Comment by fjmolinas** [comment]
@MrKevinWeiss would be nice to have this in a way where it could optionally be toogled on and off.

**Comment by MrKevinWeiss** [comment]
I will try to get this up to speed when I come back to work next week.

**Comment by MrKevinWeiss** [comment]
closed with #15950

**Pull request closed without merging**
