### PR TITLE
boards/arduino-mega2560: cleanup in periph_conf.h

### PR DESCRIPTION
**Pull request by haukepetersen**
~~rebased on #5020~~

removed some unused defines and cleaned up doxygen.

### CODE REVIEW

**Comment by OlegHahm** [comment]
What about the added SPI?

**Comment by kYc0o** [comment]
@OlegHahm I'll test it ASAP ;)

**Comment by OlegHahm** [comment]
I was more referring to the fact that this is not mentioned in the PR title or description.

**Comment by OlegHahm** [comment]
Ah, now I get it. Overlooked the #5020 in the description, because the label was not set.

**Comment by kYc0o** [comment]
Oh yes, there are two different PRs

**Comment by haukepetersen** [comment]
dependencies are in, ready for review.

**Comment by kYc0o** [comment]
ACK and go

**Pull request merged**
