### PR TITLE
tests: u8g2: fix i2c addresses.

### PR DESCRIPTION
**Pull request by basilfx**
This PR right aligns the I2c addresses. I've contributed these files, and made the mistake.

### CODE REVIEW

**Comment by aabadie** [comment]
Regarding the Si70xx, since you are at it @basilfx, can you have a look at #7296. Just testing it would be fine.

**Comment by aabadie** [comment]
The I2C address for U8G2 test application is valid, this is the one that works for me.

**Comment by basilfx** [comment]
@aabadie I tested #7296 and it worked.

**Comment by basilfx** [comment]
With #7296 merged, the only change is to U8g2.

**Pull request merged**
