### PR TITLE
Fix misc errors that occur with ENABLE_DEBUG

### PR DESCRIPTION
**Pull request by x3ro**
I enabled debug output in all files to poke around
and there were some errors (seemingly) due to code
changes that were not tested with debug enabled. This
commits tries to fix these issues.

### CODE REVIEW

**Comment by x3ro** [comment]
Why does travis complain about squashing? :confused:

**Comment by thomaseichinger** [comment]
Because your commit message starts with "Fix". It is best practice to start commit messages with the module's name affected. In your case `sys: ...`

**Comment by cgundogan** [comment]
@x3ro can you rename your PR like suggested by @thomaseichinger in order to get travis happy? After this I have no further objections, seems good for me

**Comment by x3ro** [comment]
Will do! Sorry for the delay.

**Comment by x3ro** [comment]
Commit message changed. Let's see if that makes Travis happy :hamster:

**Comment by OlegHahm** [comment]
Travis happy, @cgundogan happy, me happy -> :fireworks:  go!

**Pull request merged**
