### PR TITLE
doxygen: add make targets to build man and latex

### LINKED ISSUE #3455: doc/doxygen/riot.doxyfile: Add target for latex (pdf), man
Add separate make targets for man and PDF documentation

#3429 removed man and pdf from the default documentation build.

### PR DESCRIPTION
**Pull request by OlegHahm**
Fixes #3455

### CODE REVIEW

**Comment by gebart** [comment]
Could you do the same construct for the html target so that html is only built for make html (and make doc)

**Comment by OlegHahm** [comment]
like this?

**Comment by gebart** [comment]
@OlegHahm exactly.

**Comment by OlegHahm** [comment]
squashed

**Comment by gebart** [comment]
ACK

(I generated the latex manual and built refman.tex for fun, the resulting PDF is 1750 pages long!)

**Pull request merged**
