### PR TITLE
boards/common/nrf52: resolve netdev dependencies for all family members

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

I noticed a few small issues with the common nRF52 code

 - the smaller nRF52 parts only have a max output power of 4 dBm - fortunately the vendor files provide a define for that, so we don't have to hard-code the value.
 - default netdev was only configured for nRF52832 and nRF52840
 - `nimble_netif` is too large for nRF52810.  Instead, use nrfmin on `e104-bt5010a-tb` so we don't have to blacklist it from most tests

### Testing procedure

`e104-bt5010a-tb` should now come up with a netdev if `gnrc_netdev_default` is selected.
All other boards will be unaffected.

### Issues/PRs references

split off #15388

### CODE REVIEW

**Comment by aabadie** [comment]
> split off #15388

Some commits (2c84115c30f463b0691b5d5306c287486992e8a3 and 49df32cffc24a3feb48b13cdf7364c68167379d9) are still there.

**Comment by benpicco** [comment]
> Some commits ([2c84115](https://github.com/RIOT-OS/RIOT/commit/2c84115c30f463b0691b5d5306c287486992e8a3) and [49df32c](https://github.com/RIOT-OS/RIOT/commit/49df32cffc24a3feb48b13cdf7364c68167379d9)) are still there.

No this is alright. `e104-bt5010a-tb` previously had no default netdev configured. It's nRF52810, so it doesn't have the 802.15.4 radio and would now default to Nimble.
However, using `nimble_netif` overflows most tests so it's not very useful. Instead, I chose `nrfmin`  for this board,

 #15388 adds `e104-bt5011a-tb` which is the same board but with nRF52811, this one comes with the 802.15.4 radio.

**Comment by fjmolinas** [comment]
Can you provide test results for `e104-bt5010a-tb` @benpicco ?

**Comment by Citrullin** [comment]
So that means IPv6 over BLE is not supported on the nRF52810, while 802.15.4 is supported?

**Comment by benpicco** [comment]
`nrfmin` being selected for `examples/gnrc_networking` instead of `netif_nimble` (or nothing)

```
2020-11-13 15:47:29,996 #  ps
2020-11-13 15:47:30,005 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2020-11-13 15:47:30,014 # 	  - | isr_stack            | -        - |   - |    512 (  216) (  296) | 0x20000000 | 0x200001c8
2020-11-13 15:47:30,022 # 	  1 | main                 | running  Q |   7 |   1536 (  656) (  880) | 0x200002f8 | 0x2000075c 
2020-11-13 15:47:30,031 # 	  2 | pktdump              | bl rx    _ |   6 |   1536 (  236) ( 1300) | 0x20002a40 | 0x20002f54 
2020-11-13 15:47:30,040 # 	  3 | 6lo                  | bl rx    _ |   3 |   1024 (  416) (  608) | 0x20003a84 | 0x20003cfc 
2020-11-13 15:47:30,049 # 	  4 | ipv6                 | bl rx    _ |   4 |   1024 (  380) (  644) | 0x200009f4 | 0x20000cf4 
2020-11-13 15:47:30,057 # 	  5 | udp                  | bl rx    _ |   5 |   1024 (  248) (  776) | 0x20003e84 | 0x2000418c 
2020-11-13 15:47:30,066 # 	  6 | nrfmin               | bl rx    _ |   2 |   1024 (  532) (  492) | 0x200043f4 | 0x200046bc 
2020-11-13 15:47:30,072 # 	    | SUM                  |            |     |   7680 ( 2684) ( 4996)

2020-11-13 15:47:31,429 #  ifconfig
2020-11-13 15:47:31,433 # Iface  6  HWaddr: 8A:0A  Channel: 0  NID: 0xaffe 
2020-11-13 15:47:31,437 #            TX-Power: 0dBm  State: IDLE 
2020-11-13 15:47:31,441 #           L2-PDU:200  MTU:1280  HL:64  RTR  
2020-11-13 15:47:31,443 #           6LO  IPHC  
2020-11-13 15:47:31,446 #           Link type: wireless
2020-11-13 15:47:31,451 #           inet6 addr: fe80::ff:fe00:8a0a  scope: link  VAL
2020-11-13 15:47:31,453 #           inet6 group: ff02::2
2020-11-13 15:47:31,456 #           inet6 group: ff02::1
2020-11-13 15:47:31,460 #           inet6 group: ff02::1:ff00:8a0a
2020-11-13 15:47:31,461 #           
2020-11-13 15:47:31,464 #           Statistics for Layer 2
2020-11-13 15:47:31,466 #             RX packets 0  bytes 0
2020-11-13 15:47:31,471 #             TX packets 0 (Multicast: 0)  bytes 52
2020-11-13 15:47:31,474 #             TX succeeded 0 errors 0
2020-11-13 15:47:31,477 #           Statistics for IPv6
2020-11-13 15:47:31,480 #             RX packets 0  bytes 0
2020-11-13 15:47:31,484 #             TX packets 2 (Multicast: 2)  bytes 112
2020-11-13 15:47:31,487 #             TX succeeded 2 errors 0
```

**Comment by benpicco** [comment]
already solved by #15388

**Pull request closed without merging**
