### PR TITLE
tools: move sniffer to applications repo

### PR DESCRIPTION
**Pull request by smlng**
remove sniffer script, added/moved to applications repo see RIOT-OS/applications#31

### CODE REVIEW

**Comment by miri64** [comment]
But why?

**Comment by smlng** [comment]
well the sniffer depends on the sniffer application provided in https://github.com/RIOT-OS/applications/tree/master/sniffer. Similar to the spectrum scanner by @gebart it makes IMHO sense to have RIOT application and tools in one place not distributed over 2 different repository.

**Comment by smlng** [comment]
especially as the script is useless without the application, there is no code here in the RIOT main repo that can run with this script.

**Comment by kaspar030** [comment]
> especially as the script is useless without the application, there is no code here in the RIOT main repo that can run with this script.

Yep, that bothered me, too. +1 for moving this to the applications repository.

**Comment by miri64** [comment]
applications' PR was merged, so go.

**Pull request merged**
