### PR TITLE
cpu/esp32: add ESP32-C3 support in makefiles

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR is a split-off from PR #17844, which adds the support of ESP32-C3 in makefiles.

### Testing procedure

It is not yet possible to cover this PR when compiling in CI without having ESP32-C3 support and a board definition with an ESP32-C3. Vice versa, the ESP32-C3 port that needs this PR cannot be compiled in CI without it.

Therefore a green CI with the label `CI: skip compile test` must be sufficient for the moment. If it doesn't work, the problem will pop up as soon as ESP32-C3 support is provided. And of course, I have tested it together with the ESP32-C3 support in PR #17844.

### Issues/PRs references

Split-off from PR #17844

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
No need to split such tiny patches :wink: 
Does KConfig also need an update?

**Comment by gschorcht** [comment]
> No need to split such tiny patches wink

I have splitted all changes that can be merged independently on the core PR for ESP32-C3 support.  Most of them don't ned full CI compilation yet.

> Does KConfig also need an update?

Yes, but these are more changes https://github.com/RIOT-OS/RIOT/pull/17844/commits/39905cbb231874f1b31497794929a0b1df4182d4  that should be probably part of the core PR for ESP32-C3 to be covered by CI compilation. If you think that it makes sense to split it off to decrease the size of core PR further, I could do it. The remaining core PR size is 40 files changed, 2406 insertions(+), 3 deletions(-).

**Comment by benpicco** [comment]
That's much better, thank you!

**Comment by gschorcht** [comment]
@benpicco Thanks for reviewing and merging.

**Pull request merged**
