### PR TITLE
remove old network stack

### PR DESCRIPTION
**Pull request by kaspar030**
This is my WIP branch for removing the legacy stack. Feel free to PR more removals against this, or just ignore.

### CODE REVIEW

**Comment by kaspar030** [comment]
- removed some more stuff
- rebased

**Comment by OlegHahm** [comment]
NACK - I'm against removing ccn-lite and cc2420 completely without having a commitment of someone to re-import this within the next three months.

**Comment by kaspar030** [comment]
@OlegHahm So you're against what we decided three weeks ago (removal of the old network stack)?

The code is not gone. It is just kicked out of master. The old functionality will still be there for all eternity (good luck, github!), nicely tagged, for everyone interested in using today's RIOT together with cc2420.

**Comment by OlegHahm** [comment]
I'm against removing ccn-lite and drivers that are mostly unrelated to the old or the new network stack without any commitment of re-import them soonish.

> The code is not gone. It is just kicked out of master. 

Which is basically the same thing. No-one will use invisible, unmaintained code.

**Comment by kaspar030** [comment]
> I'm against removing ccn-lite and drivers that are mostly unrelated to the old or the new network stack without any commitment of re-import them soonish.

I'd prefer keeping them in, too, but it is not that easy. Guys, anyone keen on nitpicking all the coding convention breaches and other problems of an evolving RIOT, expressing feelings of "rather not", please let's not make the burden of supporting legacy stuff so big that RIOT will just stagnate feature wise.

The old network code is legacy. We cannot support it.

**Comment by OlegHahm** [comment]
I don't see any burden with this particular code, seems more like FUD statement.

**Comment by kaspar030** [comment]
> I don't see any burden with this particular code, seems more like FUD statement.

cc2420 uses the old transceiver interface...

**Comment by cgundogan** [comment]
IMHO we could use #3417 to assign certain features that will be lost during the transition to certain people. This way, features won't be lost forever and we will have something to use as a lookup in case we need a reminder. However, this still requires that we check on this list regularly in order to not lose the goal out of sight

**Comment by kaspar030** [comment]
Travis is happy for everything but tests/coap on avr8, which is being blacklisted in #3562.
So I'd say, please review!

**Comment by kaspar030** [comment]
- rebased

**Comment by cgundogan** [comment]
+13 −32,369 :+1:

**Comment by haukepetersen** [comment]
sys/Makefile.include: remove net_help entry, ieee802154 entry,

**Comment by kaspar030** [comment]
- rebased

**Comment by kaspar030** [comment]
(@OlegHahm's issues sorted out while having lunch)

**Comment by kaspar030** [comment]
Travis is happy. Could you guys please take another look? @authmillenon? @haukepetersen?

**Comment by PeterKietzmann** [comment]
@kaspar030 yesterday I looked at the list of changed files and at some special files where I felt insecure. Then I built and tested unit tests and the ng_networking example (as well as the default example to check if old network stack stuff is really not included anymore) for native and some boards. So all in all I checked if all-day usage is influenced by the removal and I experienced no problems. Do you have some ideas how to test this PR in a more structured or professional way?

**Comment by PeterKietzmann** [comment]
BTW: I see many green lights above :-)

**Comment by OlegHahm** [comment]
I think this is the first time, that I see Strider and Travis in accordance showing green lights! :+1:

**Comment by kaspar030** [comment]
@PeterKietzmann It is hard to test removed functionality. IMHO if everything compiles and the unittest run through, we're good. But maybe @authmillenon can say more, as she knows both the old and new stacks very well.

**Comment by OlegHahm** [comment]
No network functionalities in default example any more - is this intensional?

**Comment by kaspar030** [comment]
@OlegHahm Yes, this PR was about removal, we've left all refactoring / redesigning for future PRs.

IMHO we should rename ng_networking to default_networking.

**Comment by OlegHahm** [comment]
> IMHO we should rename ng_networking to default_networking.

Shouldn't it be rather `gnrc_default`?

**Comment by kaspar030** [comment]
Well, as gnrc is our default network stack, and newbies might not now "gnrc", why not default_networking? But IMHO that's offtopic for this PR.

**Comment by OlegHahm** [comment]
Yes it is.

On-topic: the PR needs squashing.

**Comment by kaspar030** [comment]
@OlegHahm what do you want to squash? All in one commit? Personally I'd just squash the remove-and-revert-remove commits.

**Comment by OlegHahm** [comment]
Yes, at least all revert commits should be squashed and all commits without a sensible commit message should be either squashed or be given a sensible message.

**Comment by OlegHahm** [comment]
The README.md also needs an update. Remove:
* TCP
* AODVv2, RPL
* WIselib support (unrelated to this PR)

The "EXAMPLE APPLICATIONS" section needs to be rewritten or removed.

**Comment by kaspar030** [comment]
- squashed some commits

**Comment by kaspar030** [comment]
I'd say, merge...

**Comment by OlegHahm** [comment]
oops, accidentally hit the Travis restart button...

**Comment by PeterKietzmann** [comment]
It was green, I saw it :-)

**Comment by PeterKietzmann** [comment]
We could try to formulate this: Is anyone **against** merging this PR? @authmillenon ?

**Comment by haukepetersen** [comment]
go ahead! It might make sense to squash a little bit, but I do not really have an opinion on this...

**Comment by authmillenon** [comment]
If everything is green: go ahead an merge. I'm with @kaspar030: the only way to test it is to compile the remaining apps. If you want and in-depth look at the list of removed files you have to wait a little: the mobile interface complains: "can't show full diff, too many files changed" ^^

**Comment by haukepetersen** [comment]
YEAH!

**Comment by OlegHahm** [comment]
Update the web page accordingly. Let me know if I missed something.

**Comment by kaspar030** [comment]
YES!

**Comment by authmillenon** [comment]
Bittersweet (since it removed s a lot of old code of mine) yay!

**Pull request merged**
