### PR TITLE
drivers/kw2xrf: adapt to netdev2

### PR DESCRIPTION
**Pull request by smlng**
tries to fix remaining issues in #5469

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
@smlng Thanks, would you like to rebase it, or should I take it to #5469?

**Comment by smlng** [comment]
@jfischer-phytec-iot its based on your PR, so we could close yours and merge this one instead, if you're okay with this procedure?! Your commits would stay as they are, so no work and effort lost.

**Comment by smlng** [comment]
@jfischer-phytec-iot , we still have to wait for the SPI rework PR #4780, and this has to be adapted to it before final merge. @PeterKietzmann will help with that

**Comment by jfischer-phytec-iot** [comment]
>@jfischer-phytec-iot its based on your PR, so we could close yours and merge this one instead, if >you're okay with this procedure?! Your commits would stay as they are, so no work and effort lost.

I agree, thank you

**Comment by PeterKietzmann** [comment]
@smlng can you check if this PR fixes #4822 as you stated there? Anyway, it should not block this PR from being merged as long as the issue persists. However, we're still waiting for the SPI rework to be merged before.

**Comment by PeterKietzmann** [comment]
BTW I've tested some stress pinging with small payloads (un-fragmented 6Lo) between a samr21 and a phytec board with success.

**Comment by smlng** [comment]
@PeterKietzmann could to know that basic test succeeded. Regarding #4822: I'll try to do extend tests soon, but I won't make it for the release. Still, as suggested that should not block this PR in general.

**Comment by OlegHahm** [comment]
@smlng, care to update the PR title to something more speaking? ;-)

**Comment by PeterKietzmann** [comment]
#4780 has been merged. Please rebase!

**Comment by smlng** [comment]
@PeterKietzmann its not that simple, but I'll try

**Comment by smlng** [comment]
adapted to new SPI interface and rebased, needs testing

**Comment by smlng** [comment]
tested between boards `samr21-xpro` and `pba-d-01-kw2x` with `ping6 100 <fe80::xyz> 10 100`, resulted in 0-2 % loss. @PeterKietzmann please retest and confirm, thanks! Otherwise ready to merge - after approval I'll squash ...

**Comment by smlng** [comment]
@PeterKietzmann ping, 🍒

**Comment by PeterKietzmann** [comment]
Fragmentation does not work as reported in #4822 I guess. Small packet hardcore pinging on different channels works between samr21-xpro and the phytec board. Let me have a look at the code again

**Comment by PeterKietzmann** [comment]
Please review [#1](https://github.com/smlng/RIOT/pull/1)

**Comment by PeterKietzmann** [comment]
I don't think we need all commits. Please squash. IMO one commit should be fine. Maybe two. For example one commit containing the netdev2 adoption and the other containing SPI rework. I trust you to find a reasonable  decision to squash your commits.

**Comment by smlng** [comment]
squashed as much as I found reasonable, and so that everyone involved gets his share 😄

**Comment by PeterKietzmann** [comment]
Thanks @jfischer-phytec-iot for your initial work and @smlng for shepherding.

**Comment by smlng** [comment]
finally!

**Pull request merged**
