### PR TITLE
gnrc_sixlowpan_frag: msg based fragmentation

### PR DESCRIPTION
**Pull request by PeterKietzmann**
#4381 version for the latest release branch 2015.09

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@authmillenon let's also put it in the "old" release branch!

**Comment by authmillenon** [comment]
Mh… we are in feature freeze for the next release and discussed to no longer support the old release as of now. @OlegHahm what do you think?

**Comment by PeterKietzmann** [comment]
1. Some people call the "fixed" behaviour a bug
2. Are we already in feature freeze right now :-) ?
3. You've tested the change and decided to merge it to the current master (to be part of the new release). So it should not break anything
4. You know that I need the old release branch for some measurements (if things don't change)

**Comment by authmillenon** [comment]
1. Yes, but that is argument is void if we drop support for 2015.09
2. AFAIK yes, since midnight (though I'm not sure since there was no official statement)
3. Yes, but again, if we don't update 2015.09 anymore, since we have a new and shiny 2015.12, this isn't necessary
4. I think we'll go for 2015.12 for the measurements, unless there were some hard API changes that make this impossible.

**Comment by authmillenon** [comment]
In case I am wrong: please add the change from #4437 ;-)

**Comment by PeterKietzmann** [comment]
Did, in case.....

**Comment by OlegHahm** [comment]
> > Are we already in feature freeze right now :-) ?

Not yet, but very soon.

> AFAIK yes, since midnight (though I'm not sure since there was no official statement)

Maybe you should look into your mailbox again. ;)

My first reflex was that this PR is not needed, but thinking about it again it still may help people out there who want to continue with 2015.09 for some time and it just don't hurt.

In general, I think you could save a lot of time by just acking and merging it, instead of discussing about a change that is either useful or superfluous, but definitely not harmful.

**Comment by authmillenon** [comment]
Better save than sorry ;-)

**Pull request merged**
