### PR TITLE
cpu/cc2538: Make ED and LQI values 802.15.4 compliant

### PR DESCRIPTION
**Pull request by aeneby**

### CODE REVIEW

**Comment by aeneby** [comment]
@alignan any thoughts on this?

**Comment by alignan** [comment]
Oops! still catching up after holidays.  Looks good to me :+1:

**Comment by OlegHahm** [comment]
Since @alignan agrees, let Murdock state his opinion.

**Comment by alignan** [comment]
Murdock is happy now :smile:

**Comment by OlegHahm** [comment]
If you and Murdock are both happy, who am I not to click the button? :wink:

**Comment by aeneby** [comment]
Thanks!

**Pull request merged**
