### PR TITLE
libmathfix: move to git repository and adapt

### PR DESCRIPTION
**Pull request by authmillenon**
The repositories on Google Code are now deleted, so libfixmath needs to be moved to its new GitHub source.

This PR moves libfixmath to a git source and adapts it for the git download schema (and get's rid of a lot of hard to understand Makefile magic).

### CODE REVIEW

**Comment by authmillenon** [comment]
Marked as "major" because this bug currently lets every build fail.

**Comment by OlegHahm** [comment]
Hm, that's actually not the purpose of the "major" label.

**Comment by OlegHahm** [comment]
Is the LWIP repository down, too?

**Comment by authmillenon** [comment]
Just wondering: isn't this what git-cache is for?

**Comment by authmillenon** [comment]
Anyway, their `git://` service seems to be down -.- (sadly they don't have a  HTTPS source). The [project page](http://savannah.nongnu.org/projects/lwip/) and the [cgit](http://git.savannah.gnu.org/cgit/lwip.git) is still reachable

**Comment by kaspar030** [comment]
> Just wondering: isn't this what git-cache is for?

git-cache currently doesn't automatically update it's cache, so if the commit changed since I last touched it (weeks ago), the cache will not have it...

**Comment by authmillenon** [comment]
@kaspar030 can you update the cache from my porting repository: https://github.com/authmillenon/lwip

**Comment by OlegHahm** [comment]
The LWIP git repository is back online, but the unittests need some blacklisting.

**Comment by authmillenon** [comment]
Only the weio board. I don't see how the rest Arduino example stuff is related. Does the Arduino sketches support run on top of libfixmath?

**Comment by authmillenon** [comment]
Updated test's makefile.

**Comment by authmillenon** [comment]
We've got the same error in #5447. So this seems to be another unrelated problem -.- Let's merge as soon Murdock is done and this PR got an ACK I would say.

**Comment by OlegHahm** [comment]
Please squash.

**Comment by authmillenon** [comment]
Done.

**Comment by authmillenon** [comment]
Murdock is happy, PR still needs an ACK.

**Comment by OlegHahm** [comment]
ACK and go!

**Comment by authmillenon** [comment]
> Hm, that's actually not the purpose of the "major" label.

What is it then?

**Comment by authmillenon** [comment]
Backport provided in #5449.

**Comment by authmillenon** [comment]
@kaspar030 or @cgundogan please update the git-cache on Murdock's machine.

**Comment by OlegHahm** [comment]
Hm, I see the Wiki isn't that descriptive here: "**major** - some "big" or "complicated" thing, possibly API changing". Anyway the intention of this label was to mark PRs that have a major impact on the OS and should be reviewed with extreme caution and by at least two maintainers.

However, I recently discussed with @A-Paul that we may want to re-think the whole set of labels.

**Comment by kaspar030** [comment]
> please update the git-cache on Murdock's machine.

done.

**Comment by authmillenon** [comment]
Thanks :sparkles:

**Pull request merged**
