### PR TITLE
dist/tools/compile_test: loop other auto_init enable drivers for saul test application

### LINKED ISSUE #6405: Some drivers with saul capabilities are not tested automatically by the saul test
This is the case for:
* si70xx
* bmp180
* jc42
* and soon bme280 (after #6156 is merged)

I open this issue to discuss a solution that could be applied to the CI scripts : [dist/tools/compile_test/compile_test.py](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/compile_test/compile_test.py)) or the [JenkinsFile](https://github.com/RIOT-OS/RIOT/blob/master/Jenkinsfile).

@PeterKietzmann suggested a simple solution in this [comment](https://github.com/RIOT-OS/RIOT/pull/6156#issuecomment-272965500), e.g call building `tests/saul` for each sensor drivers having a saul implementation, to verify it builds. For example:
```bash
drivers="bmp180 jc42 si70xx"
for driver in $drivers; do USEMODULE=$driver make -C tests/saul clean all; done
```

### PR DESCRIPTION
**Pull request by aabadie**
This is an attempt to fix #6405.

I'm absolutely unsure if it fix the original problem. Let's see how Murdock behaves.

### CODE REVIEW

**Comment by aabadie** [comment]
Murdock is green but doesn't seem to have taken into account the changes here. Do it use compile_test.py ? (I might have missed something :confused:)

**Comment by kaspar030** [comment]
Please, for *every* PR , state:

- what was the previous state
- whats the problem
- how the PR solves the problem.

**Comment by kaspar030** [comment]
> Do it use compile_test.py ?

Nope.

**Comment by kaspar030** [comment]
I'm strongly opposed for module specifics in buildtest.

**Comment by aabadie** [comment]
Does this mean I can close this one?

**Comment by kaspar030** [comment]
> Does this mean I can close this one?

Yes please ;)

**Pull request closed without merging**
