### PR TITLE
added Travis CI status image in README.md

### PR DESCRIPTION
**Pull request by MatthiasLohr**

### CODE REVIEW

**Comment by BytesGalore** [comment]
please provide a small description :)

**Comment by PeterKietzmann** [comment]
Nice. ACK

**Comment by PeterKietzmann** [comment]
&go

**Comment by OlegHahm** [comment]
Actually we had this proposal some time ago and I don't like it too much, because a) for me, a README should provide its information mostly when viewed in a pager or editor offline and b) I don't see any benefit.

**Comment by OlegHahm** [comment]
...and c) Travis is failing too often for RIOT-code unrelated reasons.

**Comment by PeterKietzmann** [comment]
@OlegHahm I had the same worry but wanted to give it a tray. As we can see you are completely right with c) . Please merge #2370

**Comment by thomaseichinger** [comment]
@PeterKietzmann  As for now, c) doesn't apply. Travis fails for master currently.

**Pull request merged**
