### PR TITLE
make: verify before flash

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Some flashers (jlink) check if the flash contents already matches the to-be-written binary and if yes, skip re-programming. That saves time and flash cycles.

This PR adds make infrastructure to support that with other flashers, too.
Basically it works by, instead of doing ```$flash $flash_args```, it does ```$flash_verify || $flash $flash_args```.
If no ```FLASH_VERIFY``` is provided, `false` is used thus flashing is done as before.

Another commit implements this for edbg.

### Testing procedure

With an edbg supported board, try ```make all; make flash-only; make flash-only``` and observe that the first flashing actually programs the device, the second skips programming.

Also test non-edbg boards (which don't yet supply "FLASH_VERIFY").

### Issues/PRs references

none

### CODE REVIEW

**Comment by cladmi** [comment]
I like the idea, but I would define it empty by default and add the handling if defined.
Seeing `false || ./openocd.sh firmware` feels out of place.

Also, both variables need to be documented.

**Comment by jcarrano** [comment]
One observation: this works only if the flasher only flashes and nothing more. If the flasher also resets, then the reset has to be added as an additional step that is always performed.

**Comment by cladmi** [comment]
I tested, and with `edbg` it does not break incremental flashing like done in `makefiles/boot/riotboot.mk`. The file currently does not use `flash-recipe` but I updated it do to it.

@jcarrano On `edbg` it resets the board on the check.

Both these case should be documented as requirements.

Another solution is to allow overwriting `flash-recipe` and currently overwrite it for `edbg` only.
I think would just need to replace the current recipe name by `default-flash-recipe` and do `flash-recipe ?= default-flash-recipe`. And then in `edbg.inc.mk` do `flash-recipe = edbg-flash-recipe` that defines the new behavior.

**Comment by maribu** [comment]
I fixed a typo in the PR description. (`false || flash` should is used when no verification command is present, not `true || flash`)

**Comment by jcarrano** [comment]
> @jcarrano On edbg it resets the board on the check.

I don't think that's a problem. I'd even say it's better: after FLASH the board is reset, so having it reset after verify is consistent.

**Comment by aabadie** [comment]
> more documentation would be nice

@maribu, I think @cladmi suggestion was to add some documentation of the new variable in `vars.inc.mk`.

**Comment by kaspar030** [comment]
Closing in favor of #12301. Indeed @cladmi's suggestion is nicer (more localized).

**Pull request closed without merging**
