### PR TITLE
makefiles: use C++14 standard by default for C++ compilations

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

The GCC version of all used toolchains supports at least C++14. Option `-std=c++14` is therefore set by default for C++ compilations.

### Testing procedure

Green CI.

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
Let's get two ACKs for this, as it has a high impact. Maybe @jnohlgard could provide the second ACK?

**Comment by maribu** [comment]
It would be nice to get this into the next release. There are still some issues Murdock has found and a second ACK would be nice.

@jnohlgard: Since you engaged into the discussion on the C++ standard to use in Matrix, maybe  you might want to review this?

**Comment by gschorcht** [comment]
> There are still some issues Murdock has found and a second ACK would be nice.

Ok, small fix. Let's see whether Murdock is happy now.

**Comment by maribu** [comment]
Murdock looks mostly happy now, except for a (hopefully temporary) glitch not related to this PR.

Please squash :)

**Comment by gschorcht** [comment]
@maribu May I squash the last change 9269de8664e9563a6146ac102bccc145242abc43 that should fix the remaining compilation problems before we take another round in Murdock.

**Comment by gschorcht** [comment]
> Murdock looks mostly happy now, except for a (hopefully temporary) glitch not related to this PR.
> 
> Please squash :)

Oops, I haven't seen it before I asked to squash.

**Comment by maribu** [comment]
> Oops, I haven't seen it before I asked to squash.

The Murdock frontend didn't pick them up due to the f-string issue, so one could only see the issues after clicking on the full build log.

**Review by jnohlgard — APPROVED** [review]

**Comment by gschorcht** [comment]
Thanks for reviewing and merging.

**Pull request merged**
