### PR TITLE
sys/shell: add pm command for power management

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR moves the `pm` commands from `tests/periph_pm`' to a shell command module `pm_cmd` to make them available for embedding in other applications, e.g. for debugging by using
```
USEMODULE=pm_cmd BOARD=... make -C tests/shell
```
The test application `tests/periph_pm` now uses the shell command module instead of defining the `pm` commands by itself.

Dependent on module `pm_layered` and feature `periph_rtc` the following commands are available:
```
off		turn off
reboot		reboot
set		set power mode
block		block power mode
unblock		unblock power mode
unblock_rtc	temporary unblock power mode
```
The `set`, `block`, `unblock` commands are available if the platform supports `pm_layerd`. The `unblock_rtc` is only available if the platform support `pm_layered` and feature `periph_rtc`.

### Testing procedure

Compile and flash `tests/periph` for a board with `periph_rtc` feature, for example
```
make BOARD=nucleo-f411re -C tests/periph_pm flash term
```
and excute the following tests:

- [ ] Set mode 1
   ```
   > rtc gettime
   2020-03-22 16:30:18
   > rtc setalarm 2020-03-22 16:30:40
   > pm set 1
   CPU will enter power mode 1.
   ...
   > 
   ```
- [ ] Set mode 1
   ```
   rtc setalarm 2020-03-22 16:31:50
   > 
   > pm set 0
   CPU will enter power mode 0.
   .main(): This is RIOT! (Version: 2020.04-devel-1400-g5aff3-sys/shell/pm_cmd)
   test_shell.
   >
   ```
- [ ] Unblock mode 1 for 5 seconds
   ```
   > pm unblock 1 5
   ```
- [ ] Reboot with `pm` command
   ```
   > pm reboot
   ```
- [ ] Power off `pm` command
   ```
   > pm off
   ```

### CODE REVIEW

**Comment by aabadie** [comment]
Sorry, duplicate of #11731...

**Comment by gschorcht** [comment]
@aabadie Sorry, duplicate of #11731 

Okay, I didn't realize that, no problem. I just needed the `pm` command to test PM in other applications and had to copy and paste it over and over again. So I just moved it to a module and thought it was worth sharing it with others. If there is already a PR, this is even better.

**Comment by benemorius** [comment]
At first glance this looks more mature than #11731 so I'm inclined to abandon it.

@gschorcht could you add a `pm show` command?

**Comment by gschorcht** [comment]
> @gschorcht could you add a `pm show` command?

Sure.

**Comment by aabadie** [comment]
> At first glance this looks more mature than #11731 so I'm inclined to abandon it.

Not sure, this PR introduces pm_cmd which I think is not needed (well, there are design decisions that should be further discussed,  since `pm reboot` might now be duplicated in the shell) .
I would rather go with #11731 which is close from being merged (if you address the remaining comments). We can improve it later or eventually @gschorcht can take it over ?

The pm show command is also a nice addition in #11731.

**Comment by benemorius** [comment]
@aabadie you're right I'm sorry I completely forgot there was a review on that one already. IIRC I addressed the comments and neglected to say anything about it. I'll check on it now.

**Pull request closed without merging**
