### PR TITLE
cpu/cortexm_common: make SVC call always available

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description
This PR proposes to make SVC call always available for user and thus removes the `cortexm_svc` pseudomodule.
SVCall is available on all ARMvx-M architecture. This exception was used before to trigger PendSV for the sheduler. Now PendSV is triggered manually and no longer require to use SVCall.
Since the feature was provided by default for all cortexm, I think it makes sense to remove the pseudomodule and to let it hardcoded in the code.

### Testing procedure
CI should be happy.

### Issues/PRs references
None.

### CODE REVIEW

**Review by Teufelchen1 — APPROVED** [review]
Looks reasonable, didn't test it

**Comment by dylad** [comment]
I didn't `arch_arm` would also include ARM7TMDI.
I've added a fixup commit to blacklist `arch_arm7` from `pkg/wamr`.
I'll squash if Murdock is happy about the fix.

**Comment by Teufelchen1** [comment]
Hey @dylad what do you need to move this forward?

**Comment by dylad** [comment]
I forgot about this one !
If ACK is still valid, I just need to squash this.

**Comment by dylad** [comment]
@kaspar030 Any objections here ?

**Comment by dylad** [comment]
I'm starting to reconsider this. I were wrong thinking that `cortexm_svc` was pulled by default already. This is NOT the case.
Indeed the feature is provided for all Cortex-M but there is no `FEATURES_REQUIRED=cortexm_svc` anywhere. Thus, the default mode is still the legacy one.
Switching to the new behavior will increase ROM by A LOT. Since we do not have a real use case for SVC exception yet. (except for context switching) This PR is not worthwhile.
I'm closing this.

**Comment by Teufelchen1** [comment]
That's what I get for not thinking stuff through 🥲

**Pull request closed without merging**
