### PR TITLE
kinetis: periph/uart cleanup/rewrite

### PR DESCRIPTION
**Pull request by gebart**
@haukepetersen could you test this on your pba-d-01-kw2x and frdm-k64f boards?

This PR updates the periph/uart driver on Kinetis with a new configuration style that matches the other modern periph drivers.

We will be adding another UART driver on Kinetis for the newer Cortex-M0+ LPUART module which is a different hardware and which will need a separate driver, this configuration refactor is a preparation for that work.

~~Depends on #6867~~

### CODE REVIEW

**Comment by gebart** [comment]
Rebased, ready for review

**Comment by kYc0o** [comment]
Tested on pba-d-01-kw2x with success.

**Comment by gebart** [comment]
Oops, something is wrong with the frdm-k64f config

**Comment by gebart** [comment]
Had to change the pcr_rx and pcr_tx to uint32_t to avoid problems with C++ treating enums specially.

**Comment by gebart** [comment]
Thanks for the review and testing effort!  I'll squash and merge when I get back to the computer.

**Comment by gebart** [comment]
Murdock is green -> go!

**Pull request merged**
