### PR TITLE
boards/nucleo-f303k8: DMA feature added

### PR DESCRIPTION
**Pull request by hugueslarrive**
### Contribution description
As tests/periph_spi was not working at all, I first addressed this issue (AF mistake).

Then I have added the DMA configuration.

### Testing procedure
First commit tested with tests/periph_spi.

The second with tests/periph_spi_dma after applying #14764.

### Issues/PRs references
Depends on #14764.

### CODE REVIEW

**Comment by fjmolinas** [comment]
This one needs a rebase now.

**Comment by hugueslarrive** [comment]
@fjmolinas rebased

**Comment by fjmolinas** [comment]
@hugueslarrive can you provide some test output?

**Comment by hugueslarrive** [comment]
tests/periph_dma:
```
2020-08-19 13:52:44,884 # Help: Press s to start test, r to print it is ready
s
2020-08-19 13:52:49,916 # START
2020-08-19 13:52:49,923 # main(): This is RIOT! (Version: 2020.10-devel-846-g820be-boards/nucleo-f303k8)
2020-08-19 13:52:49,924 # DMA is working
```
tests/periph_spi_dma:
```
2020-08-19 13:55:18,599 # main(): This is RIOT! (Version: 2020.10-devel-846-g820be-boards/nucleo-f303k8)
2020-08-19 13:55:18,602 # Manual SPI peripheral driver test
2020-08-19 13:55:18,607 # Refer to the README.md file for more information.
2020-08-19 13:55:18,607 # 
2020-08-19 13:55:18,612 # There are 1 SPI devices configured for your platform.
> init 0 0 4 0 0
2020-08-19 13:55:59,538 #  init 0 0 4 0 0
2020-08-19 13:55:59,543 # SPI_DEV(0) initialized: mode: 0, clk: 4, cs_port: 0, cs_pin: 0
> bench
2020-08-19 13:56:03,820 #  bench
2020-08-19 13:56:03,825 # ### Running some benchmarks, all values in [us] ###
2020-08-19 13:56:03,828 # ### Test				Transfer time	user time
2020-08-19 13:56:03,828 # 
2020-08-19 13:56:03,845 #  1 - write 1000 times 1 byte:			13158	13162
2020-08-19 13:56:03,862 #  2 - write 1000 times 2 byte:			12923	12928
2020-08-19 13:56:03,984 #  3 - write 1000 times 100 byte:		117236	14943
2020-08-19 13:56:04,014 #  4 - write 1000 times 1 byte to register:	26048	26053
2020-08-19 13:56:04,045 #  5 - write 1000 times 2 byte to register:	25862	25865
2020-08-19 13:56:04,180 #  6 - write 1000 times 100 byte to register:	130204	27912
2020-08-19 13:56:04,197 #  7 - read 1000 times 2 byte:			12658	12662
2020-08-19 13:56:04,318 #  8 - read 1000 times 100 byte:		116986	14705
2020-08-19 13:56:04,348 #  9 - read 1000 times 2 byte from register:	25579	25584
2020-08-19 13:56:04,484 # 10 - read 1000 times 100 byte from register:	129939	27696
2020-08-19 13:56:04,500 # 11 - transfer 1000 times 2 byte:		12689	12694
2020-08-19 13:56:04,622 # 12 - transfer 1000 times 100 byte:		117049	14755
2020-08-19 13:56:04,653 # 13 - transfer 1000 times 2 byte to register:	25705	25710
2020-08-19 13:56:04,788 # 14 - transfer 1000 times 100 byte to register:130095	27818
2020-08-19 13:56:04,809 # 15 - acquire/release 1000 times:		16845	16850
2020-08-19 13:56:05,812 # -- - SUM:					912976	299337
2020-08-19 13:56:05,812 # 
2020-08-19 13:56:05,814 # ### All runs complete ###
```

**Review by fjmolinas — COMMENTED** [review]
I'm under the impression tthat all `dma_chan` are unused for `stm32f3`, at least for all that do not have
`defined(DMA_CSELR_C1S) || defined(DMA1_CSELR_DEFAULT)`. It was confusing for me to see this values set and with random values. If I'm not wrong (correct me If I am), Can you set them all to 0 and add a comment that these are unused.

image

**Comment by hugueslarrive** [comment]
That was inspired from that of nucleo-l467rg which have a similar dma peripheral board. It was confusing for me too. I have understand that dma_chan value was the line index in the table... but you are right, we can remove those parameters without any effect on the tests. I also performed the periph_uart test adding `FEATURES_REQUIRED += periph_dma` to it's Makefile and it pass.

**Comment by fjmolinas** [comment]
@hugueslarrive I think the compiler will complain about initialized fields, now that https://github.com/RIOT-OS/RIOT/pull/14794 is in can you use `DMA_CHAN_CONFIG_UNSUPPORTED`?

**Review by fjmolinas — APPROVED** [review]
ACK, thanks for the contribution @hugueslarrive (sorry for all the nitpicks)!

**Pull request merged**
