### PR TITLE
kw2xrf: Fix ack flag handling

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Missing getter for `NETOPT_AUTOACK` and tx_exec used `AUTOACK` flag instead of `ACK_REQ` flag.

### Issues/PRs references

None

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Strange side story: With my sniffer (ATUSB) I'm failing to see most of the (ping) packets from the kw2x **but** I seem to get all ACK packets

**Comment by bergzand** [comment]
Thanks again for testing and reviewing!

**Comment by bergzand** [comment]
> Strange side story: With my sniffer (ATUSB) I'm failing to see most of the (ping) packets from the kw2x but I seem to get all ACK packets

Yeah, @kYc0o and me had the same with the pba-kw2x board I think. There are some weird issues with either the driver or the board.

**Comment by PeterKietzmann** [comment]
I took the phytec board as well. Don't you have a Mulle available board in Berlin? Could you give it a quick shot?

**Comment by bergzand** [comment]
I can ask tomorrow if there is one and test a bit.

**Comment by kYc0o** [comment]
Mulle has an at86rf212b. AFAICT, this is about kw2x.

**Comment by PeterKietzmann** [comment]
You are right.

**Comment by bergzand** [comment]
Backport provided in #9593

**Pull request merged**
