### PR TITLE
Fix kconfig models breaking nightlies

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

It seemed that the `tinyusb` package exposes some issues with the kconfig modelling for some `stm32`s as well as improper modelling in the `tinyusb` package.

This broke the extensive kconfig tests in nightlies.  

### Testing procedure

The remove me commit forces the nightly test, it is limited to only the boards failing, maybe we want to check it with a full nightly run, but as this is a fix I would be ok removing the REMOVEME and do a regular test.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
ping @miri64 @kaspar030   this _should_ fix the broken nightlies...  Ideally we get it in before tonight...  Though with the CI times that may take some time.

**Comment by miri64** [comment]
> The remove me commit forces the nightly test, it is limited to only the boards failing, maybe we want to check it with a full nightly run, but as this is a fix I would be ok removing the REMOVEME and do a regular test.

Me too. But I'd like to see the nightly run first, before I give my ACK.

**Comment by miri64** [comment]
In case the nightlies tonight then pass, I would prefer the Kconfig migration tests to be activated per PR again.

**Comment by miri64** [comment]
> The intermittent hash problem is still not solved AFAIK.

Wasn't that possibly solved with the recent cryptoauthlib fix in #18705?

**Comment by MrKevinWeiss** [comment]
No, that was the consistent, reproducible problem when the package was bumped.

The intermittent hash mismatch spans different boards and different apps and is not reproducible.
First, mostly occurred, on the ESP but also on some AVR, then quite a bit on the cryptoauth apps.

I would first try to get a week of passing nightlies before re-enabling the kconfig hash check.  2 hour build times that need to be rerun 50% of the time is not a nice thing.

**Comment by MrKevinWeiss** [comment]
Passed the quick tests, not rerunning the long murdock tests.  I would be OK if there was an ack + automerge enabled.  I don't have so much time left to monitor today.

**Comment by MrKevinWeiss** [comment]
Strange that this was queued 12 hours ago but other have jumped the queue in front...  ping @kaspar030

**Comment by miri64** [comment]
> Passed the quick tests

The build for `tests/sys_fido2_ctap` [is missing](https://ci.riot-os.org/RIOT-OS/RIOT/18718/db44b4469237dbefea6832a47509fc6f81bb4265/output.html) isn't it?

**Comment by miri64** [comment]
Ah.. you wrote `tests_sys_fido2_ctap` not `tests/sys_fido2_ctap` in db44b4469237dbefea6832a47509fc6f81bb4265 ...

**Comment by miri64** [comment]
@MrKevinWeiss is AFK at the moment, so lets try it again.

**Comment by miri64** [comment]
[Passed](https://ci.riot-os.org/RIOT-OS/RIOT/18718/1800f3eb7ec04fd736ccdf5dc0ee204ee847a232/output.html)

**Review by miri64 — APPROVED** [review]

**Comment by MrKevinWeiss** [comment]
Hmm still seems like some of the stms are broken (though I thought we ran them in the CI).  It is now just a hash missmatch (not modules), which probably means some issue with the clock configuration.

**Comment by miri64** [comment]
> (though I thought we ran them in the CI)

Twice even, for the tinyusb app.

**Comment by MrKevinWeiss** [comment]
Ahh, it seems they are different boards, that is why.  Hmm, could be problematic not running the tests per PR.

**Comment by MrKevinWeiss** [comment]
Hmm, it would seem Kconfig is not aware of the HSE speed which would be somewhat needed for selecting 48MHz as well as no real information modeled in kconfig for the PLLI2S or the PLLSAI.

Any suggestions on a way forward? Maybe @aabadie can suggest something as he did most of the kconfig and make work.

**Pull request merged**
