### PR TITLE
drivers/periph_eeprom: refactor implementation and test application

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR follows discussions in #10026 and #10056 and refactor the architecture specific implementation:
Before, each CPU architecture with an internal had to implement eeprom_read_byte/eeprom_write_byte functions and eeprom_read/eeprom_write were just wrappers on top of the former (basically looping on each byte).
This PR changes this to the opposite: each CPU now provides a specific implementation of eeprom_read and eeprom_write and eeprom_read_byte/eeprom_write_byte are special case of them. The API is kept unchanged.

This will allow architecture specific implementations to provide optimization (like what's proposed in #10026) without having to change the API.

In the meantime, I refactor slightly the test application:
- added 2 new commands for manipulating eeprom_read_byte/eeprom_write_byte functions
- added a new test command that performs different calls to the different API functions and that checks everything is correctly written/read
- added an automatic python script that calls this test function

Thus, this PR should be merged before the 2 other related PRs #10026 and #10056 (since it provides an automatic testing procedure and other fixes).

### Testing procedure

- Grab a board with a CPU providing internal EEPROM: arduino-mega2560, nucleo-l073rz, nucleo-l152re
- Run the following command:
```
$ make BOARD=<your board> -C tests/periph_eeprom flash test
```

It should run without error.

### Issues/PRs references

Following the discussion in #10056 and should be helpful for #10026.

### CODE REVIEW

**Comment by aabadie** [comment]
@MrKevinWeiss, would you like to review and give this one a try ?

**Comment by MrKevinWeiss** [comment]
Why is len returned on eeprom_write and eeprom_read if nothing is actionable?

**Comment by MrKevinWeiss** [comment]
Also not a big deal but why not write the test logic in the test.py not in the c file.  This should allow it to be more extendable and have a smaller binary.

**Comment by MrKevinWeiss** [comment]
I did run it though the tests and it passed, also did some manual playing around and everything looks correct.  This was done on the nucleo-l152re and arduino-mega2560.

**Comment by aabadie** [comment]
> Why is len returned on eeprom_write and eeprom_read if nothing is actionable?

If nothing is actionable, it won't change anything because the program will either crash (due to an assertion failed) or hang (because the EEPROM cannot be read/write). This was the previous behaviour by the way.

**Comment by MrKevinWeiss** [comment]
Ok, part of keeping the API then fair enough.

**Comment by aabadie** [comment]
> why not write the test logic in the test.py not in the c file

That's a matter of taste. I prefer it this way ;)

**Comment by MrKevinWeiss** [comment]
Heh, alright then, maybe it's the Canadian in me but I won't push back.

**Comment by aabadie** [comment]
@MrKevinWeiss, CI is all green there !

**Pull request merged**
