### PR TITLE
pkg/nimble: improve structure of Makefiles

### LINKED ISSUE #11051: NimBLE port should be always building all NimBLE files
Building NimBLE for RIOT is part of Apache NimBLE CI now. Whenever new file is added to tree our CI fails on RIOT port due to hardcoded list of files in controller.mk and nimble.host.mk makefiles.

Could RIOT port simply build all .c file for NimBLE? This is how NimBLE is build with newt anyway so building all files is expected to work even if some of NimBLE features are disabled.

This way RIOT port wouldn't require updating per release and would easily allow us to use it for master branch testing.

Example hackish workaround we need to use now:(
https://github.com/JuulLabs-OSS/mynewt-travis-ci/pull/33/commits/235c309f8f0c42a3b23dfe4bc755898cfeb49901

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
This PR reworks the Makfiles for the `nimble` package a little bit, to make it more robust and improve modularity a bit. I think I still have to do some improvements to the `Makefile.include`, but aside from that the situation should be improved with this PR already...

### Testing procedure
Simply verify that `exampels/nimble_gatt` is still working as expected

### Issues/PRs references
fixes #11051

### CODE REVIEW

**Comment by haukepetersen** [comment]
Now it looks better:
- bumped up the nimble version (as it does not make sense to optimize makefiles against some old version)
- also modularized the `Makefile.include` file

**Comment by kaspar030** [comment]
hard faults on nrf52dk.

**Comment by haukepetersen** [comment]
the version bumb did the crash. For now, reverted to the old version, and everything runs fine (again). Will move the version dump do a separate PR and investigate in that context...

So for now, this PR should work.

**Comment by haukepetersen** [comment]
Seems I was mistaken, the alignment fix introduced by the patch was not yet fixed in the used nimble version. So reverted removing the patch as well...

**Comment by haukepetersen** [comment]
all green -> go

**Pull request merged**
