### PR TITLE
Automatically initialize git-cache when necessary

### PR DESCRIPTION
**Pull request by kennethjiang**
Otherwise it'll take a new developer (like myself) a bit of time to figure this out.

### CODE REVIEW

**Comment by kaspar030** [comment]
The git-cache specific part looks OK, but I don't use vagrant. @cgundogan could you take a look?

**Comment by cgundogan** [comment]
I actually would prefer the `git-cache` script that is in `dist/tools/git`. No need to wget from `kaspar030/git-cache`.

**Comment by kennethjiang** [comment]
Ah I didn't know there is `dist/tools/git/git-cache`. I just made the change to use it.

**Comment by cgundogan** [comment]
@kennethjiang looks much better. But is it really necessary to copy git-cache to /usr/bin? You could also just call the script directly from ./dist/tools/git/git-cache. The RIOT build system is aware of git-cache's location

**Comment by kennethjiang** [comment]
@cgundogan you are right that `git-cache` doesn't have to be in $PATH. Sorry that I missed that earlier.

I found out the problem I had was caused by the fact that `git-cache init` was never called. For example, if I clone RIOT and launch a new Vagrant VM from scratch, I will have this error:

```
$ cd RIOT/examples/gcoap && make all flash BOARD=samr21-xpro
...
/home/vagrant/RIOT/dist/tools/git/git-cache clone "https://github.com/kaspar030/sock" "cf2aff1b4322cee06bb5b24d0215bb764372fba7" "/home/vagrant/RIOT/examples/gcoap/bin/pkg/samr21-xpro/nanocoap"
fatal: Cannot change to '/home/vagrant/.gitcache': No such file or directory
Cloning into '/home/vagrant/RIOT/examples/gcoap/bin/pkg/samr21-xpro/nanocoap'...
fatal: reference repository '/home/vagrant/.gitcache' is not a local repository.
/home/vagrant/RIOT/pkg/pkg.mk:23: recipe for target '/home/vagrant/RIOT/examples/gcoap/bin/pkg/samr21-xpro/nanocoap/.git-downloaded' failed
...
````

I therefor revised this PR to add `git-cache init` to the appropriate place.

**Comment by cgundogan** [comment]
@kennethjiang actually, the problem that you did encounter should be fixed by #6289. The build system should not throw an error when the gitcache dir does not exist. So, I am not sure it's really necessary to specifically initialize the gitcache dir for vagrant. Could you check whether it works for you on current master without your proposed diff?

**Comment by cgundogan** [comment]
oh, I just realized that you changed the dif to be vagrant agnostic and built the `gitcache init` into the build system. @kaspar030 any remarks on that?

**Comment by cgundogan** [comment]
actually, I am not against this change, but I would rather check whether `GIT_CACHE_AUTOADD=1` before initializing the gitcache directory.

**Comment by kaspar030** [comment]
> oh, I just realized that you changed the diff to be vagrant agnostic and built the gitcache init into the build system. @kaspar030 any remarks on that?

I did not do that because I wanted to avoid having the build system create files in the user's home directory, and also the extra check is executed thousands of times on the CI. The latter is acceptable, the former I'm not sure.

git-cache should transparently do direct check outs if the git-cache directory is not initialized. I think cloning with "--reference" broke that behaviour...

**Comment by kennethjiang** [comment]
I thought the purpose of using apt-cache is to store things in user's home dir. But I'm missing the whole background why apt-cache was adopted to begin with so I won't be surprised if apt-cache is supposed to function in other ways.

What would be the way you suggest to fix the build error caused by apt-cache (the error I posted earlier)?

**Comment by cgundogan** [comment]
@kennethjiang the gitcache error you encountered (not apt-cache) was fixed separately from your proposed pull request. Can you check with the current master branch whether you still get an error while using vagrant?

**Comment by kennethjiang** [comment]
Yes I pulled from master and it all works fine now! Thanks @cgundogan .

**Pull request closed without merging**
