### PR TITLE
doc: remove Travis status image in REAMDE

### PR DESCRIPTION
**Pull request by PeterKietzmann**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Maybe we should wait for other opinions on this before we start adding and removing this line again and again. ;)

**Comment by PeterKietzmann** [comment]
According to your listing in #2363 I think points a) and b) are a matter of taste and can be discussed. c) is a problem as long as we have occasional unrelated build-fails with Travis. But let's wait for opinions and then you can merge at will (or not :-) )

**Comment by OlegHahm** [comment]
For the record: I think putting the build/test status on http://riot-os.org/ makes sense. I thought it would be there already, but either I'm wrong or someone removed it again.

**Comment by OlegHahm** [comment]
(Just checked: it's commented out for some reason.)

**Comment by OlegHahm** [comment]
Oops, this is still open...

**Pull request merged**
