### PR TITLE
make: boards: remove use of export with debug adapter related variables

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

There's no need to export `DEBUG_ADAPTER`/`DEBUG_ADAPTER_ID`/`ST_LINK` variables since they are not passed to an external process.

### Testing procedure

- Verify that flashing a sam0 based board (samr21-xpro, samr30-xpro, etc) works. Try also by passing `DEBUG_ADAPTER_ID` with multiple boards plugged on the same computer
- Verify that flashing an st-link based board (one that is modified by this PR) works

### Issues/PRs references

Removal of unused exports https://github.com/RIOT-OS/RIOT/issues/10850

### CODE REVIEW

**Comment by cladmi** [comment]
Indeed all usages of these variables are inside directly included makefiles:

```
git grep -e '$(DEBUG_ADAPTER)' -e '${DEBUG_ADAPTER}' -e '$(DEBUG_ADAPTER_ID)' -e '${DEBUG_ADAPTER_ID}' -e '$(STLINK_.*)' -e '${STLINK_.*}'
boards/mulle/Makefile.include:    ifneq ($(DEBUG_ADAPTER_ID),)
boards/mulle/Makefile.include:      PORT := $(firstword $(shell $(RIOTTOOLS)/usb-serial/find-tty.sh '^$(DEBUG_ADAPTER_ID)$$'))
boards/mulle/Makefile.include:    ifneq ($(DEBUG_ADAPTER_ID),)
boards/mulle/Makefile.include:      PORT := /dev/tty.usbserial-$(DEBUG_ADAPTER_ID)B
makefiles/boards/sam0.inc.mk:ifeq ($(DEBUG_ADAPTER),dap)
makefiles/tools/edbg.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/edbg.inc.mk:  EDBG_ARGS += --serial $(DEBUG_ADAPTER_ID)
makefiles/tools/openocd-adapters/dap.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/openocd-adapters/dap.inc.mk:  OPENOCD_ADAPTER_INIT += -c 'cmsis_dap_serial $(DEBUG_ADAPTER_ID)'
makefiles/tools/openocd-adapters/jlink.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/openocd-adapters/jlink.inc.mk:  OPENOCD_ADAPTER_INIT += -c 'jlink serial $(DEBUG_ADAPTER_ID)'
makefiles/tools/openocd-adapters/mulle.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/openocd-adapters/mulle.inc.mk:  ifeq "100" "$(word 1, $(sort 100 $(DEBUG_ADAPTER_ID)))"
makefiles/tools/openocd-adapters/mulle.inc.mk:    ifneq "149" "$(word 1, $(sort 149 $(DEBUG_ADAPTER_ID)))"
makefiles/tools/openocd-adapters/mulle.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/openocd-adapters/mulle.inc.mk:  OPENOCD_ADAPTER_INIT += -c 'ftdi_serial $(DEBUG_ADAPTER_ID)'
makefiles/tools/openocd-adapters/stlink.inc.mk:  -c 'source [find interface/stlink-v$(STLINK_VERSION).cfg]' \
makefiles/tools/openocd-adapters/stlink.inc.mk:ifneq (,$(DEBUG_ADAPTER_ID))
makefiles/tools/openocd-adapters/stlink.inc.mk:  OPENOCD_ADAPTER_INIT += -c 'hla_serial $(DEBUG_ADAPTER_ID)'
makefiles/tools/openocd.inc.mk:ifneq (,$(DEBUG_ADAPTER))
makefiles/tools/openocd.inc.mk:  include $(RIOTMAKE)/tools/openocd-adapters/$(DEBUG_ADAPTER).inc.mk
```

Could you also add these variables to the list on variables that must not be exported 

https://github.com/RIOT-OS/RIOT/blob/f8c070c06c7789d566e139235018d466688c94c3/dist/tools/buildsystem_sanity_check/check.sh#L57

It should prevent new usages to export them.

**Comment by aabadie** [comment]
> Could you also add these variables to the list on variables that must not be exported

Wasn't aware of this. Will do.

**Comment by cladmi** [comment]
> > Could you also add these variables to the list on variables that must not be exported
> 
> Wasn't aware of this. Will do.

I will update the tracking issue about exports.

**Comment by aabadie** [comment]
@cladmi, I added the variable to the build system sanity check script. In the meantime, I also cleaned up the `PROGRAMMER_SERIAL` variable (only done in one place)

**Comment by cladmi** [comment]
There are two commented `DEBUG_ADAPTER_ID` usage still reported by the check script. You can fix them directly fix them and squash.

**Comment by aabadie** [comment]
> There are two commented DEBUG_ADAPTER_ID usage still reported by the check script.

Fixed

**Comment by aabadie** [comment]
Thanks @cladmi :)

**Pull request merged**
