### PR TITLE
makefiles/murdock.inc.mk: change policy to run tests by default

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

Change the policy to run the tests by default on murdock.

Introduce `TEST_ON_CI_BLACKLIST` for describing tests that must not be
run in CI.

By default if a test is available and not blacklisted it will be run by
murdock.

This will move from a whitelisting everything that works, to
blacklisting what fails. This way, failing tests will be easier to
track instead of being silently just not run.

It could even allow introducing failing tests before a fix is available.

### TODO

* [x] This pull request will require blacklisting all what fails in a commit before changing the policy.
* [ ] Update the remaining `TEST_ON_CI_WHITELIST` with the reason.
    ```
    git grep 'TEST_ON_CI_WHITELIST' '*' ':!makefiles/murdock.inc.mk'
    tests/libfixmath_unittests/Makefile:TEST_ON_CI_WHITELIST += native
    tests/pkg_libcose/Makefile:TEST_ON_CI_WHITELIST += native
    tests/pkg_tweetnacl/Makefile:TEST_ON_CI_WHITELIST += native
    tests/rng/Makefile:TEST_ON_CI_WHITELIST += native
    ```
* An followup will be to update `dist/tools/compile_an_test_for_board.py` to maybe not handle a failure as `FAILED` but more `expected failure` if the test was not enabled.
* Followup with a command to list all disabled tests in RIOT

#### New behavior

If there is a test and nothing is set the board is enabled

```
BOARD=samr21-xpro make --no-print-directory -C tests/pkg_fatfs_vfs/ test/available test-on-ci-enabled 
```
##### Blacklisting

If all is blacklisted, no test will be run

```
BOARD=native make --no-print-directory -C tests/pkg_fatfs_vfs/ test/available test-on-ci-enabled 
/home/harter/work/git/RIOT/makefiles/murdock.inc.mk:47: recipe for target 'test-on-ci-enabled' failed
make: *** [test-on-ci-enabled] Error 1
BOARD=samr21-xpro make --no-print-directory -C tests/pkg_fatfs_vfs/ test/available test-on-ci-enabled 
/home/harter/work/git/RIOT/makefiles/murdock.inc.mk:47: recipe for target 'test-on-ci-enabled' failed
make: *** [test-on-ci-enabled] Error 1
```

``` diff
diff --git a/tests/pkg_fatfs_vfs/Makefile b/tests/pkg_fatfs_vfs/Makefile
index edbf14bf4..babd1db3c 100644
--- a/tests/pkg_fatfs_vfs/Makefile
+++ b/tests/pkg_fatfs_vfs/Makefile
@@ -50,6 +50,8 @@ BOARD_WHITELIST := airfy-beacon arduino-due arduino-duemilanove \
 
 TEST_DEPS += image
 
+TEST_ON_CI_BLACKLIST += all
+
 include $(RIOTBASE)/Makefile.include
 
 image:
```

If one board is blacklisted only this one will not run

```
BOARD=native make --no-print-directory -C tests/pkg_fatfs_vfs/ test/available test-on-ci-enabled 
BOARD=samr21-xpro make --no-print-directory -C tests/pkg_fatfs_vfs/ test/available test-on-ci-enabled 
/home/harter/work/git/RIOT/makefiles/murdock.inc.mk:47: recipe for target 'test-on-ci-enabled' failed
make: *** [test-on-ci-enabled] Error 1
```

with this diff

``` diff
diff --git a/tests/pkg_fatfs_vfs/Makefile b/tests/pkg_fatfs_vfs/Makefile
index edbf14bf4..d44376293 100644
--- a/tests/pkg_fatfs_vfs/Makefile
+++ b/tests/pkg_fatfs_vfs/Makefile
@@ -50,6 +50,8 @@ BOARD_WHITELIST := airfy-beacon arduino-due arduino-duemilanove \
 
 TEST_DEPS += image
 
+TEST_ON_CI_BLACKLIST += samr21-xpro
+
 include $(RIOTBASE)/Makefile.include
 
 image:
```
#### Kept behavior when `TEST_ON_CI_WHITELIST` is set

The previous behavior when `WHITELIST` is set did not change.

Enabled tests are still enabled:

```
# Only native enabled
BOARD=native make --no-print-directory -C tests/libfixmath_unittests/ test-on-ci-enabled
# all enabled
BOARD=samr21-xpro make --no-print-directory -C tests/bloom_bytes/ test-on-ci-enabled
BOARD=iotlab-m3 make --no-print-directory -C tests/bloom_bytes/ test-on-ci-enabled 
```

Not enabled tests are still not enabled

```
BOARD=samr21-xpro make --no-print-directory -C tests/libfixmath_unittests/ test-on-ci-enabled 
/home/harter/work/git/RIOT/makefiles/murdock.inc.mk:47: recipe for target 'test-on-ci-enabled' failed
make: *** [test-on-ci-enabled] Error 1
```

If a board does not have enough memory, it is still disabled

```
RIOT_CI_BUILD=1 BOARD=samr21-xpro make --no-print-directory -C tests/unittests/ test-on-ci-enabled 
CI-build: skipping link step
/home/harter/work/git/RIOT/makefiles/murdock.inc.mk:47: recipe for target 'test-on-ci-enabled' failed
make: *** [test-on-ci-enabled] Error 1
```

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/issues/11128#issuecomment-470555097
Some tests always fail on some boards, even some supported for testing in CI https://github.com/RIOT-OS/Release-Specs/issues/98#issuecomment-460984572

### CODE REVIEW

**Comment by cladmi** [comment]
Currently
* `tests/lwip` crashes, but it also fails on my machine.
* `tests/socket_zep` works on my machine but not on murdock
* `tests/lua_loader`, `tests/pkg_u8g3`, `tests/pthread_rwlock` work on my machine but not on `murdock`. Are the worker running with an `ascii` console ?

**Comment by cladmi** [comment]
With "cache enabled" the test report is not included for the previous ones. So must re-run it.

**Comment by cladmi** [comment]
Rebased to use `TEST_ON_CI_BLACKLIST` and blacklist failing tests.

**Comment by cladmi** [comment]
Rebased and removed the dependency to the fix in https://github.com/RIOT-OS/RIOT/pull/11688 by currently just blacklisting the test. Fixing is a different task.

**Comment by cladmi** [comment]
This one is touching similar files as https://github.com/RIOT-OS/RIOT/pull/11688 Should I rebase the other one on top of this one ?

**Comment by kaspar030** [comment]
> This one is touching similar files as #11688 Should I rebase the other one on top of this one ? At least the conflicting commit.

IMO this one is larger and should get in first. Please squash!

**Comment by cladmi** [comment]
Squashed with test blacklisting first.

When enabling all tests by default, some additional tests will be run (if compatible) as I did not add `TEST_ON_CI_WHITELIST += all` in all directory before doing it.

Lets check no failing tests were introduced in between.

**Comment by kaspar030** [comment]
ACK. This ran 511 tests (compared to 447 last nightly). &go.

**Comment by cladmi** [comment]
Thank you for the review.

Now I can do the `TODO` further work.

**Pull request merged**
