### PR TITLE
pkg: ccn-lite: adapt to v2

### PR DESCRIPTION
**Pull request by cgundogan**
This PR imports `ccn-lite v2` as a package and replaces the v1 package.

`pkg/ccn-lite/ccn-lite-riot.h` resides in [ccn-lite](https://github.com/cn-uofbasel/ccn-lite/tree/ccnlv2-master/src/ccnl-riot/include) now.

~~Marked as WIP, because https://github.com/cn-uofbasel/ccn-lite/pull/127 needs merging first. I will modify this PR to include the new commit hash once the fix is upstream.~~

### CODE REVIEW

**Comment by cgundogan** [comment]
not WIP anymore as fix got merged upstream

**Comment by cgundogan** [comment]
@PeterKietzmann I would like to have your feedback on this, because you have a bunch of automated stress tests for our ccn-lite integration

**Comment by smlng** [comment]
tried to compile on macOS, got the following error:

```
/RIOT/examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-riot/src/ccn-lite-riot.c:311:56: error: 
      no member named 'linklayer' in 'sockunion'
                            if (ifc->addr_len == dest->linklayer.sll_halen) {
                                                 ~~~~  ^
```

**Comment by cgundogan** [comment]
@smlng could you try again? I updated the commit hash.

**Comment by smlng** [comment]
still the same error on macOS (or similar):

```make
Scanning dependencies of target ccnl-riot
[ 50%] Building C object ccnl-riot/CMakeFiles/ccnl-riot.dir/src/ccn-lite-riot.c.o
/RIOT/examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-riot/src/ccn-lite-riot.c:313:56: error: 
      no member named 'linklayer' in 'sockunion'
                            if (ifc->addr_len == dest->linklayer.sll_halen) {
                                                 ~~~~  ^
```

**Comment by smlng** [comment]
plus murdock uses an old cmake version.

**Comment by smlng** [comment]
sorry for the noise, seems like there is no link layer support for macOS in CCN-lite see [here](https://github.com/cn-uofbasel/ccn-lite/blob/399f562a710d85b17be96df8677d022d2b10eff8/src/ccnl-os-includes.h#L59). However, that should be guarded to raise an error

**Comment by miri64** [comment]
For reference: I've added https://github.com/cn-uofbasel/ccn-lite/pull/142 to adapt it for the changes in #7925. Otherwise, the patch file needs to be adapted.

**Comment by cgundogan** [comment]
>Otherwise, the patch file needs to be adapted.

You mean the patch file can be removed once your PR is merged?

**Comment by miri64** [comment]
And this PR is adapted for that, yes.

**Comment by cgundogan** [comment]
Updated to the latest ccn-lite version. @PeterKietzmann could you give this also a try?

**Comment by miri64** [comment]
Needs a rebuild anyway, because of #7919 ;-)

**Comment by miri64** [comment]
I think the CMake requirement is pretty clear:

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 3.5.1
```

So I guess, our dockerfile needs some update before merging this ;-).

**Comment by cgundogan** [comment]
waiting for https://github.com/RIOT-OS/riotdocker/pull/38

**Comment by kaspar030** [comment]
> waiting for RIOT-OS/riotdocker#38

That has been merged and activated on the CI.

**Comment by cgundogan** [comment]
> That has been merged and activated on the CI.

You are reading my mind! (:

**Pull request merged**
