### PR TITLE
Kinetis: Disable watchdog between flashing and verifying image

### PR DESCRIPTION
**Pull request by gebart**
This PR has evolved to include more OpenOCD improvements for Kinetis platforms.

 - Check image before flashing that the flash configuration field is not set to write protect the flash (anti bricking check)
 - Unlock watchdog before verifying the image after flashing
 - Use on-MCU checksumming algorithm in openocd to speed up flashing.
 - Remove some pba-d-01-kw2x specific openocd scripts in favour of the common `dist/tools/openocd/openocd.sh` script
 - Use `PRE_FLASH_CHECK_SCRIPT` to run a command before openocd when flashing.
 - Use `OPENOCD_EXTRA_INIT` instead of command line arguments for passing extra initialization parameters to openocd.sh
 - Use `OPENOCD_PRE_FLASH_CMDS`, `OPENOCD_PRE_VERIFY_CMDS` to add more openocd commands before flash, before verify, respectively.

Original description below:
This PR adds a binary watchdog disable function under `cpu/k60/dist` and uses it on mulle to enable image verification offloading to the MCU.

Current master gives the following warning when flashing K60 devices:

    Error: No working memory available. Specify -work-area-phys to target.
    Warn : not enough working area available(requested 52)

This PR eliminates the error/warning and also eliminates the error message

    Error: timed out while waiting for target halted

when verifying the image when `-work-area-phys` is used in `openocd.conf`.

When not using `work-area-phys` we get a warning and the whole image is read back over the JTAG interface for verification. When using `work-area-phys` the image CRC is computed by the MCU directly, but on Kinetis the watchdog will reset the MCU because the memory verification takes too long to complete.

Using `work-area-phys` significantly reduces the time it takes to `make flash`, depending on the speed of the JTAG interface (my test run with a 100kB binary went from 6.989 s to 4.251 s, 3 seconds may not be alot, but the relative gain will be similar or greater for larger binaries).

Output comparison:

Current `master`, without `work-area-phys`:

    % time make flash         
    ......
       text    data     bss     dec     hex filename
     103624    1080   63056  167760   28f50 .../riot/examples/rpl_udp/bin/mulle/rpl_udp.elf
    .../riot/dist/tools/openocd/openocd.sh flash -c 'ftdi_serial 328' 
    ### Flashing Target ###
    Open On-Chip Debugger 0.8.0 (2015-02-23-19:21)
    Licensed under GNU GPL v2
    For bug reports, read
            http://openocd.sourceforge.net/doc/doxygen/bugs.html
    adapter speed: 1000 kHz
    Info : only one transport option; autoselect 'jtag'
    srst_only separate srst_gates_jtag srst_push_pull connect_deassert_srst
    cortex_m reset_config sysresetreq
    Info : add flash_bank kinetis k60.pflash.0
    Info : add flash_bank kinetis k60.pflash.1
    Info : clock speed 1000 kHz
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    Info : k60.cpu: hardware has 6 breakpoints, 4 watchpoints
    END...
        TargetName         Type       Endian TapName            State       
    --  ------------------ ---------- ------ ------------------ ------------
     0* k60.cpu            cortex_m   little k60.cpu            running
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    ** Programming Started **
    auto erase enabled
    Info : Probing flash info for bank 0
    Warn : flash configuration field erased, please reset the device
    wrote 108544 bytes from file .../riot/examples/rpl_udp/bin/mulle/rpl_udp.hex in 2.537301s (41.777 KiB/s)
    ** Programming Finished **
    ** Verify Started **
    Error: No working memory available. Specify -work-area-phys to target.
    Warn : not enough working area available(requested 52)
    verified 107188 bytes in 3.421568s (30.593 KiB/s)
    ** Verified OK **
    shutdown command invoked
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    shutdown command invoked
    Done flashing
    make flash  0.65s user 0.38s system 14% cpu 6.989 total

`master` with `work-area-phys` set, watchdog resets the system:

    % time make flash         
    ......
       text    data     bss     dec     hex filename
     103624    1080   63056  167760   28f50 .../riot/examples/rpl_udp/bin/mulle/rpl_udp.elf
    .../riot/dist/tools/openocd/openocd.sh flash -c 'ftdi_serial 328' 
    ### Flashing Target ###
    Open On-Chip Debugger 0.8.0 (2015-02-23-19:21)
    Licensed under GNU GPL v2
    For bug reports, read
            http://openocd.sourceforge.net/doc/doxygen/bugs.html
    adapter speed: 1000 kHz
    Info : only one transport option; autoselect 'jtag'
    srst_only separate srst_gates_jtag srst_push_pull connect_deassert_srst
    adapter_nsrst_assert_width: 10
    adapter_nsrst_delay: 1
    cortex_m reset_config sysresetreq
    Info : add flash_bank kinetis k60.pflash.0
    Info : add flash_bank kinetis k60.pflash.1
    Info : clock speed 1000 kHz
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    Info : k60.cpu: hardware has 6 breakpoints, 4 watchpoints
    END...
        TargetName         Type       Endian TapName            State       
    --  ------------------ ---------- ------ ------------------ ------------
     0* k60.cpu            cortex_m   little k60.cpu            running
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    ** Programming Started **
    auto erase enabled
    Info : Probing flash info for bank 0
    Warn : flash configuration field erased, please reset the device
    wrote 108544 bytes from file .../riot/examples/rpl_udp/bin/mulle/rpl_udp.hex in 2.548009s (41.601 KiB/s)
    ** Programming Finished **
    ** Verify Started **
    Error: timed out while waiting for target halted
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x81000000 pc: 0x00001390 psp: 0x20000ba4
    Error: error executing cortex_m crc algorithm
    verified 107188 bytes in 23.392584s (4.475 KiB/s)
    ** Verified OK **
    shutdown command invoked
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    shutdown command invoked
    Done flashing
    make flash  2.14s user 1.90s system 14% cpu 27.042 total

with extra watchdog unlock:

    % time make flash         
    ......
       text    data     bss     dec     hex filename
     103624    1080   63056  167760   28f50 .../riot/examples/rpl_udp/bin/mulle/rpl_udp.elf
    openocd -f '.../riot/boards/mulle/dist/openocd/mulle-programmer-0.70.conf' -c 'ftdi_serial 328'  -c 'tcl_port 0' -c 'telnet_port 0' -c 'gdb_port 0' -c 'init' -c 'targets' -c 'reset halt' -c 'flash write_image erase .../riot/examples/rpl_udp/bin/mulle/rpl_udp.hex' -c 'reset halt' -c 'load_image .../riot/cpu/k60/dist/wdog-disable.bin 0x20000000 bin' -c 'resume 0x20000000' -c 'verify_image .../riot/examples/rpl_udp/bin/mulle/rpl_udp.hex' -c 'reset run' -c 'shutdown'
    Open On-Chip Debugger 0.8.0 (2015-02-23-19:21)
    Licensed under GNU GPL v2
    For bug reports, read
            http://openocd.sourceforge.net/doc/doxygen/bugs.html
    adapter speed: 1000 kHz
    Info : only one transport option; autoselect 'jtag'
    srst_only separate srst_gates_jtag srst_push_pull connect_deassert_srst
    adapter_nsrst_assert_width: 10
    adapter_nsrst_delay: 1
    cortex_m reset_config sysresetreq
    Info : add flash_bank kinetis k60.pflash.0
    Info : add flash_bank kinetis k60.pflash.1
    Info : clock speed 1000 kHz
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    Info : k60.cpu: hardware has 6 breakpoints, 4 watchpoints
    END...
        TargetName         Type       Endian TapName            State       
    --  ------------------ ---------- ------ ------------------ ------------
     0* k60.cpu            cortex_m   little k60.cpu            running
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    auto erase enabled
    Info : Probing flash info for bank 0
    Warn : flash configuration field erased, please reset the device
    wrote 108544 bytes from file .../riot/examples/rpl_udp/bin/mulle/rpl_udp.hex in 2.545492s (41.642 KiB/s)
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    target state: halted
    target halted due to debug-request, current mode: Thread 
    xPSR: 0x01000000 pc: 0x00000894 msp: 0x20010000
    34 bytes written at address 0x20000000
    downloaded 34 bytes in 0.001155s (28.747 KiB/s)
    target state: halted
    target halted due to breakpoint, current mode: Thread 
    xPSR: 0x01000000 pc: 0x20000020 msp: 0x20010000
    verified 107188 bytes in 0.605770s (172.798 KiB/s)
    Info : JTAG tap: k60.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
    START...
    END...
    shutdown command invoked
    make flash  0.54s user 0.46s system 23% cpu 4.251 total

### CODE REVIEW

**Comment by OlegHahm** [comment]
Wouldn't it be better maintainable to include these changes as a configurable option in the generic OpenOCD script/config?

**Comment by gebart** [comment]
Yes, but I didn't want to add too much special cases to `openocd.sh`

Maybe we can add one variable `OPENOCD_PRE_VERIFY` for the extra arguments or something?

Also it is necessary to replace the OpenOCD command `program erase verify $(HEXFILE)` by the two parts `flash write_image erase $(HEXFILE)` and `verify_image $(HEXFILE)`

**Comment by OlegHahm** [comment]
I think both suggested changes are fine. I prefer to have some additional configuration in the script over having too many platform specific variations spread over the Makefiles. And this affects probably other Kinetis platforms, too, right?

**Comment by gebart** [comment]
@OlegHahm I think it probably applies to all Kinetis devices. I will update this PR later when I have time.

**Comment by jfischer-phytec-iot** [comment]
@gebart It should also go without binary file, I will try it out. On our board, we have a check function for the image(L1&-L26): https://github.com/RIOT-OS/RIOT/blob/master/boards/pba-d-01-kw2x/dist/flash.sh
Maybe it's interesting for you.

**Comment by gebart** [comment]
The check function is useful and should be added to all kinetis platforms which have this flash protection field, I will try to adapt this too.
But the binary has nothing to do with the fcfield, it is for verifying that the written image is identical to the one stored on disk, you have commented out the verification in your flash script above. OpenOCD can do this in two ways, either it copies back the entire image over the JTAG link and verifies it on the host side, or you can run a tiny algorithm on the target for computing the checksum and then transfer only the checksum result and compare those. The checksumming version is much quicker because the memory transfers locally on target are much faster than JTAG transfers. If you try to run the checksumming version without disabling the hardware watchdog the target will reset somewhere halfway through the computations. The binary in this PR is the machine code from the function `wdog_disable` with KINETIS_WDOG_ADVANCED defined and an `__asm__ volatile ("bkpt #0\n");` instead of a function return (I took the machine code from the compiled wdog.o from the hello-world example and replaced `bx r0` at the end of the function with `bkpt #0` by hand in a hex editor, so there are no other source files than what is already in-tree)

The provided binary is loaded into RAM (the script puts it at 0x20000000, but it doesn't matter) and executed until a BKPT instruction is hit.

Below is the code and disassembly of the binary: (origin: https://github.com/gebart/RIOT/blob/pr/openocd-verify-watchdog/cpu/kinetis_common/wdog.c#L61)
```c
void wdog_disable(void)
{
#if KINETIS_WDOG_ADVANCED
    /* unlock and disable the WDOG */
    WDOG->UNLOCK = (uint16_t)0xc520;
    WDOG->UNLOCK = (uint16_t)0xd928;
    WDOG->STCTRLH = (uint16_t)(WDOG_STCTRLH_WAITEN_MASK
                               | WDOG_STCTRLH_STOPEN_MASK
                               | WDOG_STCTRLH_ALLOWUPDATE_MASK
                               | WDOG_STCTRLH_CLKSRC_MASK);
#else
    /* disable the COP WDOG */
    SIM->COPC = (uint32_t)0x00u;
#endif
}
```

```
% arm-none-eabi-objdump -b binary -m arm -M force-thumb -D cpu/k60/dist/wdog-disable.bin
cpu/k60/dist/wdog-disable.bin:     file format binary


Disassembly of section .data:

00000000 <.data>:
   0:   f242 000e       movw    r0, #8206       ; 0x200e
   4:   f24c 5120       movw    r1, #50464      ; 0xc520
   8:   f2c4 0005       movt    r0, #16389      ; 0x4005
   c:   8001            strh    r1, [r0, #0]
   e:   f64d 1128       movw    r1, #55592      ; 0xd928
  12:   8001            strh    r1, [r0, #0]
  14:   f242 0000       movw    r0, #8192       ; 0x2000
  18:   21d2            movs    r1, #210        ; 0xd2
  1a:   f2c4 0005       movt    r0, #16389      ; 0x4005
  1e:   8001            strh    r1, [r0, #0]
  20:   be00            bkpt    0x0000
```

**Comment by jfischer-phytec-iot** [comment]
Sorry, I did not express myself properly. I understand what you intend. I thought may be we can make that directly with openocd, like:
```
...
-c "mww 0x20000000 0x000ef242"
-c "mww 0x20000004 0x5120f24c"
-c "mww 0x20000008 0x0005f2c4"
-c "mww 0x2000000c 0x8001"
-c "mww 0x2000000e 0x1128f64d"
-c "mww 0x20000012 0x8001"
-c "mww 0x20000014 0x0000f242"
-c "mww 0x20000018 0x21d2"
-c "mww 0x2000001a 0x0005f2c4"
-c "mww 0x2000001e 0x8001"
-c "mww 0x20000020 0xbe00"
...
```

@OlegHahm dist/tools/openocd/openocd.sh

**Comment by gebart** [comment]
I see, but that command line becomes quite difficult to understand then.
(Also, some of those mww should be replaced by mwh)

**Comment by jfischer-phytec-iot** [comment]
I have tested it with mww:
```
> mww 0x20000000 0x000ef242    
> mww 0x20000004 0x5120f24c
> mww 0x20000008 0x0005f2c4
> mww 0x2000000c 0x8001
> mww 0x2000000e 0x1128f64d
> mww 0x20000012 0x8001
> mww 0x20000014 0x0000f242
> mww 0x20000018 0x21d2
> mww 0x2000001a 0x0005f2c4
> mww 0x2000001e 0x8001
> mww 0x20000020 0xbe00
> arm disassemble 0x20000000 11

0x20000000  0xf242000e  MOVW    r0, #8206       ; 0x200e
0x20000004  0xf24c5120  MOVW    r1, #50464      ; 0xc520
0x20000008  0xf2c40005  MOVT    r0, #16389      ; 0x4005
0x2000000c  0x8001      STRH    r1, [r0, #0]
0x2000000e  0xf64d1128  MOVW    r1, #55592      ; 0xd928
0x20000012  0x8001      STRH    r1, [r0, #0]
0x20000014  0xf2420000  MOVW    r0, #8192       ; 0x2000
0x20000018  0x21d2      MOVS    r1, #0xd2
0x2000001a  0xf2c40005  MOVT    r0, #16389      ; 0x4005
0x2000001e  0x8001      STRH    r1, [r0, #0]
0x20000020  0xbe00      BKPT    00
```

**Comment by gebart** [comment]
@jfischer-phytec-iot It works because the order of the `mww` commands (the later commands overwrite the tail of the earlier commands) and the fact that this is a little endian CPU :wink:

**Comment by gebart** [comment]
@jfischer-phytec-iot Would you be fine with placing a binary file in kinetis_common and call it `wdog-unlock.bin`? (or any other name if you prefer)
The other watchdog (KW0x) seem to only require that we write a single value to a specific address, which is simple enough to understand written in OpenOCD `mww` command syntax.

**Comment by jfischer-phytec-iot** [comment]
I agree in principle. @OlegHahm How is RIOT's policy about binary files?

**Comment by OlegHahm** [comment]
AFAIR there is no fixed policy, apart from "try to avoid it". But if it is required/very helpful for flashing, debugging or otherwise accessing some board and it stays in `dist` I think it's okay (if the origin is trustworthy). @LudwigOrtmann, @haukepetersen, @emmanuelsearch, @kaspar030, @waehlisch  other opinions?

**Comment by LudwigOrtmann** [comment]
I'm OK with a binary as long as there is documentation (or even better a script of some sort) on how to create it.

**Comment by gebart** [comment]
- Added a source for the binary along with a Makefile inside kinetis_common/dist
 - Refactored `openocd.sh` to allow more hooks during flashing. `openocd` has to be called through `sh -c` in order for argument quoting to work as expected.

**Comment by jfischer-phytec-iot** [comment]
@gebart tested on kw2x, :+1: for turbo verify. I will open a PR against your branch (adaption for pba-d-01 board).

**Comment by jfischer-phytec-iot** [comment]
@gebart done, I have also inserted the anti brick script script.

**Comment by gebart** [comment]
- renamed `antibrick.sh`->`check-fcfield-elf.sh`
 - refactored openocd.sh
 - added `check-fcfield-hex.sh`
 - Dry run tested for pba-d-01-kw2x (I don't have the hardware)
 - Tested on mulle.

Ready for review @jfischer-phytec-iot

**Comment by jfischer-phytec-iot** [comment]
@gebart ACK. ping @OlegHahm

**Comment by gebart** [comment]
@jfischer-phytec-iot OK to squash?

**Comment by gebart** [comment]
Rebased, squashed, reordered some commits, cleaned up.

**Comment by gebart** [comment]
I noticed OpenOCD 0.9.0 has been released and it contains work-area specifications for the Kinetis CPUs by default, but the watchdog is still interfering, so this PR is becoming more important now.

**Comment by OlegHahm** [comment]
Do we need the binary if source and Makefile are there?

**Comment by jfischer-phytec-iot** [comment]
How can we integrate it into RIOT build system?

**Comment by gebart** [comment]
@OlegHahm not having the binary is a minor inconvenience. I'll see if I can refactor the makefile to build the binary before flashing.

**Comment by OlegHahm** [comment]
I was just wondering, because we have the same issue for lpc2k_pgm, the flasher tool for MSB-A2. But navigating once to the corresponding dist folder and call `make` there, seems to be a reasonable effort. Usually, one does not clone a new RIOT version every day.

**Comment by jfischer-phytec-iot** [comment]
>But navigating once to the corresponding dist folder and call make there, seems to be a reasonable effort.

No, no way. This makes any guidance for the customer too complicated. :smile:

@gebart Would you add a script that creates the binary (like check-fcfield-hex.sh )?

**Comment by gebart** [comment]
I added a prerequisite for the flash target in the mulle Makefile.include. It seems to work here for building the binary before flashing. @jfischer-phytec-iot could you try my changes on your side?

**Comment by jfischer-phytec-iot** [comment]
@gebart tested, works very well, thx!

**Comment by gebart** [comment]
Is that an ACK?

**Comment by jfischer-phytec-iot** [comment]
@gebart from my side, yes. @OlegHahm ACK?

**Comment by OlegHahm** [comment]
ACK

**Pull request merged**
