### PR TITLE
misc: use correct hauke.petersen@fu email address

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
I found some leftover @author tags with an incorrect email address of mine, all of those occurances should use my FU mail address. This PR fixes that.

I am however a little unsure of also removing the entry from the `.mailmap` file, could someone confirm (or reject) that change?! Thanks.

### Testing procedure
n/a

### Issues/PRs references
none

### CODE REVIEW

**Comment by miri64** [comment]
Sorry, I was mistaken. `.mailmap` appearently only applies to [`git shortlog`](https://git-scm.com/docs/git-shortlog#_mapping_authors), not `git log` (unless you use [`git log --use-mailmap`](https://git-scm.com/docs/git-log#git-log---use-mailmap))

**Comment by miri64** [comment]
On the other hand: you don't seem to have been using your `devel@` address at all for `user.mail`.

Compare current `master`

```
$ git shortlog -s -n --no-merges | head
  1828	Hauke Petersen
  1549	Martine Lenders
  1438	Oleg Hahm
  1132	Kaspar Schleiser
  1077	Joakim Nohlgård
   788	Alexandre Abadie
   686	Ludwig Knüpfer
   486	Cenk Gündoğan
   425	Sebastian Meiling
   294	René Kijewski
```

vs this PR (the one extra is the one in this PR ;-))

```
$ git shortlog -s -n --no-merges | head
  1829	Hauke Petersen
  1549	Martine Lenders
  1438	Oleg Hahm
  1132	Kaspar Schleiser
  1077	Joakim Nohlgård
   788	Alexandre Abadie
   686	Ludwig Knüpfer
   486	Cenk Gündoğan
   425	Sebastian Meiling
   294	René Kijewski
```

**Comment by haukepetersen** [comment]
> Your current GitHub config

I wouldn't call 2015 current :-) So I have not been using that config for the last 3 years or so...

But I am a little confused now (as I honestly have no plan about git's log handling). Is it save to remove the .mailmap entry or is it not?

> Git grep reports that there's one occurence remaining in drivers/lpd8808/include/lpd8808_params.h

@aabadie not that I can see. Might it be that you grepped on the wrong branch?

**Comment by miri64** [comment]
> But I am a little confused now (as I honestly have no plan about git's log handling). Is it save to remove the .mailmap entry or is it not?

If you want to keep your contributions together under "one name", I'd say no.

**Comment by haukepetersen** [comment]
I see. Removed the fix to the `.mailmap` file from the commit

**Comment by aabadie** [comment]
@haukepetersen, see [here](https://github.com/RIOT-OS/RIOT/blob/master/drivers/lpd8808/include/lpd8808_params.h#L2)

**Comment by haukepetersen** [comment]
@aabadie that is `devel@haukepetersen.de`, and that is completely valid as this is the address I copyright my private work with...

**Comment by haukepetersen** [comment]
All green -> go

**Comment by aabadie** [comment]
Then why is the author below uses another email address ? The copyright should be changed by FU Berlin, at least. This email address is only used in 2 places now (after this PR was merged). This seems rather inconsistent.

**Comment by miri64** [comment]
Can we agree that we leave it to Hauke how he signs off his copyright :laughing:?

**Comment by haukepetersen** [comment]
In that particular case, all the copyrights and author emails should be `devel@hauke..`, as this is a driver I wrote on my spare time back then. But as my default templates are shaped towards my FU copyright and email, it seems that I missed adapting most of the occurrences in that module... So I guess simply handover some of my copyrights to FU Berlin hereby then :-). And for the author contact email address it should really not matter which one I use.

**Pull request merged**
