### PR TITLE
cc2420: Port cc2420 to netdev.802154

### PR DESCRIPTION
**Pull request by authmillenon**
To test this, run

```
export BOARD=telosb # or z1, or wsn430-v1_4
SENDER=0 make -C tests/netdev/ all flash && SENDER=1 make -C tests/netdev/ all flash && make -C tests/netdev/ test
```

~~Depends on #1492.~~ (it's merged)

```
* #1680
|\
… …
| |
| * #1448
| |\
* | | #1733
| * | #1732
| | * #1731
| |/
|/
* (master)
```

Depends on #2163

### CODE REVIEW

**Comment by authmillenon** [comment]
Abondened. But memo'ed for future reference, if someone wants to implement it for #2278.

**Comment by 4dahalibut** [comment]
I'd like to implement this for #2278 . Could somebody tell me some relevant info that would be good to know for this undertaking? Also it seems like somebody started writing it and then stopped?

**Comment by authmillenon** [comment]
@4dahalibut this issue is deprecated since netdev.802154 does not exist anymore. Please look into `ng_netdev` and already existing IEEE 802.15.4 drivers (`ng_at86rf2xx`, `xbee`, `kw2xrf`, … descending order of recommendation) for reference.

**Comment by 4dahalibut** [comment]
Okay I meant implementing the cc2420 driver for ng_netdev. Where should I post about that?

**Comment by authmillenon** [comment]
First you should read "[How to implement a `ng_netdev` enabled device](https://github.com/RIOT-OS/RIOT/wiki/How-to-implement-a-%60ng_netdev%60-enabled-device)". If you have further questions you can ask them on the mailing list. Most people (including me) will be happy to answer your questions there :-). When you have a somewhat complete implementation (you probably can refurbish a lot from the existing implementation at `drivers/cc2420`) you can open a PR for that, or you open a WIP progress and relabel it as done, when you are in a somewhat stable state ;-).

**Comment by kaspar030** [comment]
ng_netdev will probably be outdated soon. I have a native ethernet and cc110x driver based on netdev2 in the queue. Take a look at https://github.com/kaspar030/RIOT/tree/add_gnrc_netdev2_support for my current WIP.

**Comment by 4dahalibut** [comment]
Wait so netdev2 is another device interface different than the one cc2420 was originally written for, different from the one it was going to be written for and abandoned, and different from ng_netdev?

**Comment by kaspar030** [comment]
Yes. cc2420 for RIOT has as long a history as RIOT itself.

But netdev2 is very similar to ng_netdev.

**Comment by 4dahalibut** [comment]
Is the rest of the ng_* stack going to be integrated into the netdev2 interface?

**Comment by kaspar030** [comment]
Yes. netdev2 is just a low-level network driver interface, very similar to ng_netdev. netdev2 just drops all dependencies to ng_*, but in a way that ng* still works with it.

**Pull request closed without merging**
