### PR TITLE
gnrc/lorawan: fixes the handling of downlink frames without payload

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the handling of downlink frames without payload.

According to the [LoRAWAN Specification](https://lora-alliance.org/sites/default/files/2018-07/lorawan1.0.3.pdf), section 4.3.2 _Port field (FPort)_, line 545, the port field must be present if the payload is not empty.

This means that the port field is not available for downlink frames without payload. The following logic does not cover this case correctly: https://github.com/RIOT-OS/RIOT/blob/5e9733645f1671189db577beeafbfec6e5b503f7/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c#L89-L94 If the downlink frame has no payload, `pkt->size` is already 0 and the error condition doesn't match. The subsequent `assert` leads to a crash since `fport` is `NULL` in that case. Even if the application is compiled with `NDEBUG`, the application crashes in next line:  https://github.com/RIOT-OS/RIOT/blob/5e9733645f1671189db577beeafbfec6e5b503f7/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c#L96

The problem was figured out with an ESP32 and a RFM95 module using the TheThingsNetwork. After setting the interface up with `ifconfig 4 up`, a message was sent `send 4 RIOT`. TheThingsNetwork answers with a `Unconfirmed Data Down` message without any payload.

BTW, interestingly, it did not crash with `fport=NULL` on the STM32 architecture.

### Testing procedure

Flash `examples/gnrc_lorawan` to any LoRa board. The following commands should still work:
```
ifconfig 4 up`
send 4 RIOT
```
The uplink frame is acknolowed by a downlink frame without payload. If possible, schedule a downlink frame with payload and use again
```
send 4 RIOT
```
In this case the, the downlink frame should contain data.

### CODE REVIEW

**Comment by jia200x** [comment]
Good catch, thanks. The change makes sense.

I will give it a try now

**Comment by jia200x** [comment]
I could join once, but it somehow stopped now :(. I'm not seeing traffic in the Gateways tab, so there's something wrong. I will wait some minutes and try again

**Comment by jia200x** [comment]
oh, just realized our gateway is down :(

**Comment by jia200x** [comment]
tested on IoT-LAB. It works as expected

**Comment by gschorcht** [comment]
@jia200x Thanks for testing and reviewing.

**Pull request merged**
