### PR TITLE
gnrc_sixlowpan_frag: allow send of multiple datagrams simultaneously

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
For fragment forwarding I need to be able to send (and in case the packet is compressed also [re-]construct) fragments of multiple datagrams. Currently this is not possible, since the source for the datagram tag is always taken from the global variable `_tag`. However, by adding the `tag` to the `gnrc_sixlowpan_msg_frag_t` type we are able to allocate a datagram tag from `_tag` at an earlier point and use the new member to set the fragments datagram tag field from that.

I also piggy-backed some optimizations to the `gnrc_sixlowpan_frag` module, which results in this enhancement only to require 20 more bytes of code.

### Testing procedure
`gnrc_networking` should still be able to ping between two 6Lo-capable nodes with large payloads.

### Issues/PRs references
No dependencies, but provides basis for others:

Route to 6Lo minimal fragment forwarding

### CODE REVIEW

**Comment by miri64** [comment]
#11068 is to experimental so it doesn't make any sense to try to get this into the release => post-poned.

**Comment by miri64** [comment]
Rebased to current master and moved compile configurations to `net/gnrc/sixlowpan/config.h` (see #11415)

**Comment by miri64** [comment]
The effect has nothing to do with the new feature. The same will be visible on master, as you are sending huge packages faster than the node can handle them (RTT for those pings alone is >100ms

**Comment by cgundogan** [comment]
>The effect has nothing to do with the new feature. The same will be visible on master, as you are sending huge packages faster than the node can handle them (RTT for those pings alone is >100ms

yes, but I would expect at least some pings to succeed. I see 0% success.

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
> yes, but I would expect at least some pings to succeed. I see 0% success.

How could a ping succeed, if you are draining the pinged nodes resources in one instance? The "problem" is the new asynchronous ping here. It doesn't wait for a reply until it sends the next package, like the old ping did and thus makes such effects more visible. See also https://github.com/RIOT-OS/Release-Specs/pull/121 for what is happening. Anyway, this is unrelated to this PR.

You won't be able to force the 6LoWPAN thread to send multiple datagrams just with one node. You need fragment forwarding to observe this.

**Comment by cgundogan** [comment]
>You won't be able to force the 6LoWPAN thread to send multiple datagrams just with one node. You need fragment forwarding to observe this.

so it's currently not possible to test this new feature with this PR alone? Nevertheless, I confirmed that it at least does not break the current master's behaviour.

**Comment by miri64** [comment]
> so it's currently not possible to test this new feature with this PR alone?

Yepp, that's why the testing procedures say

> `gnrc_networking` should **still** be able to ping

;-)

**Pull request merged**
