### PR TITLE
native: fix missing includes and declarations for OS X

### LINKED ISSUE #3175: Native: build of vtimer_msg test fails on OS X
Build of vtimer_msg test fails on OS X with current master. 

Error is:

```
In file included from /RIOT/cpu/native/hwtimer_cpu.c:47:
In file included from /RIOT/RIOT/core/include/debug.h:34:
/RIOT/core/include/thread.h:138:14: error: conflicting types for 'thread_create'
kernel_pid_t thread_create(char *stack,
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/mach/task.h:193:15: note: 
      previous declaration is here
kern_return_t thread_create
              ^
1 error generated.
```

Toolchain info:

```
OS X version 10.10.3
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

### PR DESCRIPTION
**Pull request by thomaseichinger**
Fixes #3175 and #3198

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
Seems to work for vtimer_msg, but I still get quite some warnings:

```
make -B clean all
...
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/hwtimer_cpu.c:280:5: warning: 
      implicit declaration of function 'host_get_clock_service' is invalid in
      C99 [-Wimplicit-function-declaration]
    host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &cclock);
    ^
1 warning generated.
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/irq_cpu.c:324:5: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    makecontext(&native_isr_context, native_irq_handler, 0);
    ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/irq_cpu.c:486:9: warning: 
      'getcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    if (getcontext(&native_isr_context) == -1) {
        ^
/usr/include/ucontext.h:37:6: note: 'getcontext' has been explicitly marked
      deprecated here
int  getcontext(ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/irq_cpu.c:504:5: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    makecontext(&native_isr_context, native_irq_handler, 0);
    ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
3 warnings generated.
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:118:9: warning: 
      'getcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    if (getcontext(p) == -1) {
        ^
/usr/include/ucontext.h:37:6: note: 'getcontext' has been explicitly marked
      deprecated here
int  getcontext(ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:131:5: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    makecontext(p, (void (*)(void)) task_func, 1, arg);
    ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:153:9: warning: 
      'setcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    if (setcontext(ctx) == -1) {
        ^
/usr/include/ucontext.h:39:6: note: 'setcontext' has been explicitly marked
      deprecated here
int  setcontext(const ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:174:9: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        makecontext(&native_isr_context, isr_cpu_switch_context_exit, 0);
        ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:175:13: warning: 
      'setcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        if (setcontext(&native_isr_context) == -1) {
            ^
/usr/include/ucontext.h:39:6: note: 'setcontext' has been explicitly marked
      deprecated here
int  setcontext(const ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:196:9: warning: 
      'setcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    if (setcontext(ctx) == -1) {
        ^
/usr/include/ucontext.h:39:6: note: 'setcontext' has been explicitly marked
      deprecated here
int  setcontext(const ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:210:9: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        makecontext(&native_isr_context, isr_thread_yield, 0);
        ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:211:13: warning: 
      'swapcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        if (swapcontext(ctx, &native_isr_context) == -1) {
            ^
/usr/include/ucontext.h:40:6: note: 'swapcontext' has been explicitly marked
      deprecated here
int  swapcontext(ucontext_t * __restrict, const ucontext_t * __restrict...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:223:9: warning: 
      'getcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    if (getcontext(&end_context) == -1) {
        ^
/usr/include/ucontext.h:37:6: note: 'getcontext' has been explicitly marked
      deprecated here
int  getcontext(ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/native_cpu.c:230:5: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
    makecontext(&end_context, sched_task_exit, 0);
    ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
10 warnings generated.
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/syscalls.c:128:9: warning: 
      'makecontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        makecontext(&native_isr_context, native_irq_handler, 0);
        ^
/usr/include/ucontext.h:38:6: note: 'makecontext' has been explicitly marked
      deprecated here
void makecontext(ucontext_t *, void (*)(), int, ...) __OSX_AVAILABLE_BUT...
     ^
/Users/emmanuelB/Documents/work/CODING/RIOT/RIOT/cpu/native/syscalls.c:129:13: warning: 
      'swapcontext' is deprecated: first deprecated in OS X 10.6
      [-Wdeprecated-declarations]
        if (swapcontext(_native_cur_ctx, &native_isr_context) == -1) {
            ^
/usr/include/ucontext.h:40:6: note: 'swapcontext' has been explicitly marked
      deprecated here
int  swapcontext(ucontext_t * __restrict, const ucontext_t * __restrict...
     ^
2 warnings generated.
...
__TEXT	__DATA	__OBJC	others	dec	hex
36864	1544192	0	20480	1601536	187000
```

**Comment by emmanuelsearch** [comment]
concerning testing at runtime, I ran into https://github.com/RIOT-OS/RIOT/issues/3320
Any clues?

**Comment by emmanuelsearch** [comment]
When I follow the how-to (https://github.com/RIOT-OS/RIOT/wiki/Testing-6LoWPAN-on-Ethernet-based-devices) setting the environment variables as specified etc.
I get the following error:

```
clang: error: no such file or directory: '/RIOT/examples/ng_networking/bin/native/ng_zep.a'
make: *** [all] Error 1
```

**Comment by thomaseichinger** [comment]
Updated in respect of #3282

**Comment by thomaseichinger** [comment]
> I get the following error:
> 
> ```
clang: error: no such file or directory: '/RIOT/examples/ng_networking/bin/native/ng_zep.a'
make: *** [all] Error 1
```

Can't reproduce this right now. Could you try again with recent changes?

**Comment by gebart** [comment]
@emmanuelsearch did you do a `make clean` before building?

**Comment by thomaseichinger** [comment]
@emmanuelsearch ping.

**Comment by thomaseichinger** [comment]
Closing this in favour of #3393.

**Pull request closed without merging**
