### PR TITLE
board: EMW3162

### PR DESCRIPTION
**Pull request by DipSwitch**
Initial implementation for the ARM CPU on the EMW3162.

Todo:
- Add WiFi driver.
- See if it's possible to make a module border router. =)

Question:
- The wifi chip is probably a Broadcom with SDIO interface which needs a firmware file to be loaded. Would it be a problem to include such a propriatary firmware file into the OS?

Waits on: 
 #4497 : STM32F2 CPU support

### CODE REVIEW

**Comment by haukepetersen** [comment]
very interesting board, would be nice to finally have something with Wifi supported by RIOT.

Would you mind changing the PR title to something like 'boards: added support for EMW3162-1', as this PR adds a board and no CPU?! Thx.

**Comment by DipSwitch** [comment]
Well I first want to implement the ARM on the module. But the WiFi chip
itself also has an RISC processor of an architecture not yet implemented in
riot :)

**Comment by haukepetersen** [comment]
oh sorry, I have overlooked the WIP... Looking forward to this!

**Comment by DipSwitch** [comment]
Question:

  •  The wifi chip is probably a Broadcom with SDIO interface which needs a firmware file to be loaded. Would it be a problem to include such a propriatary firmware file into the OS?

**Comment by DipSwitch** [comment]
It is distributed trough linux as well, you may use it as a bin.

**Comment by OlegHahm** [comment]
I don't see a general problem with that.

**Comment by OlegHahm** [comment]
This is still WIP?

**Comment by DipSwitch** [comment]
Depends on: #4430 #4431 #4780 #4862 #4926

**Comment by OlegHahm** [comment]
#4497 got postponed.

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by miri64** [comment]
Postponed due to Feature Freeze.

**Comment by PeterKietzmann** [comment]
#5397 was merged

**Comment by aabadie** [comment]
ping @DipSwitch, this PR needs (heavy) rebase. Are you still working on this ?

**Comment by PeterKietzmann** [comment]
@DipSwitch thank you very very much for all the efforts you spent on this board support. However, this PR is really outdated and there hasn't been activity for quite some time. I'll close your PR with memo label now. Please, feel free to reopen at any time you intend to update!

**Pull request closed without merging**
