### PR TITLE
cpu/samd21: Added CPU_MODEL_SAMD21G18A interrupt config

### PR DESCRIPTION
**Pull request by kbumsik**
I noticed the `exti_config` table was uninitialized while porting WINC1500 inside of Arduino MKR1000 (It took me a few days to figure out 😂 ). So I added a proper table for SAMD21G18A.

I also added a guard to make sure there is a matched CPU_MODEL in the source.

Related: #7092 #6881  #6666

---
This change is [Reviewable](https://reviewable.io/reviews/riot-os/riot/7125)

### CODE REVIEW

**Comment by dylad** [comment]
@kbumsik Could you confirm that you can register and use several EXTI at the same time on your board please ? I suspect a bug in gpio driver for SAML21 and SAMD21 (see #6904 and #6932 )

**Comment by kbumsik** [comment]
@dylad I will try and post it on #6932 .

**Comment by dylad** [comment]
@kbumsik Thanks you ! I'm looking forward to your feedback :)

**Comment by photonthunder** [comment]
Thanks for this PR, I also would have spent days trying to figure out why the EXTI was not working.  Just posted on #6932 that I did not see a problem with two EXTI on my samd21g18a.

**Comment by TomKeddie** [comment]
@kbumsik can I suggest we add a #else clause with all entries -1 in it?  or a #error clause in it?  This will give more meaningful results where the CPU_MODEL is not catered for by this block.

**Comment by kbumsik** [comment]
@TomKeddie That's what I was thinking at the beginning. But I think this kind of bug is hard to figure out unless the compiler doesn't explicitly warn about this. Since I am a mere user of RIOT I don't know if a scenario that CPU_MODEL is not listed in that block is normal or intentional.
I would like to ask about this to the maintainers.

Or, as the middle point, we might do like this using #warning instead:
```C
#else 
    #warning CPU_MODEL is not matched here. This may lead to disabling EXTI.
     {-1,  -1, -1, -1, ... 
     },
     {-1,  -1, -1, -1, ... 
     },
#endif
```
By the way, -Werror is enabled by default in RIOT. What do you think?

**Comment by TomKeddie** [comment]
@kbumsik I think that's a great idea, lets push it to the reviewers and see what they think.

**Comment by aabadie** [comment]
and go!

**Pull request merged**
