### PR TITLE
tests: add test for the aconno board acd52832

### PR DESCRIPTION
**Pull request by dnahm**
This PR includes the test for the aconno board ACD52832.

Following features are integrated:
 - Toggle of LED LD2 (over MCP23017)
 - Joystick control S4 (over MCP23017)

And following PRs are required:
 - #7501 
 - #7557 
 - #7652

### CODE REVIEW

**Comment by smlng** [comment]
sorry but IMHO board specific tests are a bit against the general concept here. You should rather add a test for your mcp27017 driver instead - looks like you could start by renaming this one and maybe adapt 1 or 2 things ....

**Comment by dnahm** [comment]
The idea was to expand this test later with features like the electronic paper display.
@smlng What do you think about?

**Comment by smlng** [comment]
still not convinced - as said: this would be against the current concept of having board independent tests. The mcp27013 or the e-paper display could be attached to any board (in theory). So there should rather be tests for these devices, first.

Nevertheless, I do see the merits of having board specific tests that check all the peripheral devices attached to a board at once. But that would be an extension of the current test framework, and definitely needs to be discussed in a broader scope -> maybe write an email to devel/maintainer mailing list.

**Comment by smlng** [comment]
I guess at least @kaspar030  and @miri64 might have an opinion on that, too.

We could also think about having a separate repo for such tests?

**Comment by kaspar030** [comment]
> this would be against the current concept of having board independent tests. The mcp27013 or the e-paper display could be attached to any board (in theory). So there should rather be tests for these devices, first.

Agreed. If the tests are not dependent on each other (e.g., a motor can only be controlled through a joystick, thus a test application for it would need to include the joystick "test"), they should be in separate, board-independent test applications.

**Comment by PeterKietzmann** [comment]
As agreed offline we close this PR now.

**Pull request closed without merging**
