### PR TITLE
tests/pkg_cmsis-dsp: add kconfig configuration + cleanup package modules

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Same as #17997, but applied to CMSIS-DSP package. The same module to directory mapping trick is used to get the directory name (that is using uppercase and lowercase letters) from the module name (lowercase only).

### Testing procedure

Green Murdock

### Issues/PRs references

None

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Strange murdock failure seeing as the other one passed...

**Comment by aabadie** [comment]
> Strange murdock failure seeing as the other one passed...

Ah, I forgot to update the module names in the package Makefile...

**Comment by aabadie** [comment]
Sorry, I removed the branch by mistake...

**Comment by aabadie** [comment]
Murdock failed but that seems unrelated...

**Comment by leandrolanzieri** [comment]
> Murdock failed but that seems unrelated...

Yeah, there are some hiccups sometimes with esp on the CI. We could still not figure those out :-/

**Comment by aabadie** [comment]
[The Murdock failure](https://ci.riot-os.org/RIOT-OS/RIOT/18001/4826468174d97ce254950033f4f4cd922f920b55/output/compile/tests/gnrc_rpl/native:gnu.txt) seems unrelated, retriggerring Murdock...

**Comment by aabadie** [comment]
This is all green !

**Review by leandrolanzieri — APPROVED** [review]
ACK

**Pull request merged**
