### PR TITLE
examples/skald: clarifying names of examples

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
When adding #8884 it was pointed out, that it is not trivial to see, that `Skald` actually implements BLE functionality. So this PR adds `ble_` as prefix to the example application for clarification.

### Issues/PRs references
similar to #8893

### CODE REVIEW

**Comment by kaspar030** [comment]
maybe ```<name>_ble_edistone```?

**Comment by miri64** [comment]
Actually in this case I think the BLE label is more misleading than anything. As a new user not knowing about RIOT I would expect that an application starting with `ble_` would show me how to use RIOT with BLE. However, though Skald implements parts of BLE, it is really just the advertising part. People more familiar with BLE itself, would know that there are two protocols in particular that use that part: Eddystone and iBeacon (which are explicitly named here), while people less familiar might be discouraged because the app isn't doing what they expect BLE to be doing.

**Comment by ilf-S** [comment]
Can I drop my 2 cents of wisdom, strictly as a user. I read the original PR and this one, and although I agree that skald at first doesn't let anyone know that this is a (very basic and partial) implementation of BLE it is perfectly fine by me to just be called skald. As someone who does daily pulls of the repo and reads the docs, it took me about 5 minutes to get up to speed what skald is and what it does. RIOT is not yet that mainstream, I assume, so taking care of the newbie, casual user at this point is a bit counterproductive, again IMHO.

I do agree that the _ble_ prefix is misleading and as a user, if I see the _ble_ prefix, my next thought would be "cool, here we have the broadcaster part, but where is the damn observer. And what about the central and the peripheral implementations?", then cue the outrage and issues.

Again this is just MHO as a user,

**Comment by miri64** [comment]
Thanks @ilf-S, I think this helps us to get some perspective and reflects somewhat what I also wanted to say.

**Comment by aabadie** [comment]
> here we have the broadcaster part, but where is the damn observer

Just a thought but since it's a partial implementation (for the moment), why not just put it in the tests ? As a developer, I would expect something more complete in the examples.

**Comment by miri64** [comment]
> Just a thought but since it's a partial implementation (for the moment), why not just put it in the tests ? 

Skald (as the name implies; a skald is a nordic bard) is supposed to be just that: a broadcaster implementation for BLE, which is a valid use-case (see your favorite candy vending machine). So I thinks examples is the better place.

> As a developer, I would expect something more complete in the examples.

Under the light of implementing a broadcaster protocol like Eddystone or iBeacon, the examples are complete. We have examples that only provide a partial IP-stack with focus on a specific feature as well...

**Comment by haukepetersen** [comment]
@ilf-S I agree with you, just prefixing the examples with `skald_` is IMHO fine and as you have pointed out, it is not very difficult to find out what `Skald` is. But I guess putting them in a `ble_` group does also not hurt - personally I don't have a strong opinion here, but it seemed to me that the general opinion was leaning towards the second option?! 

> Skald (as the name implies; a skald is a nordic bard) is supposed to be just that: a broadcaster implementation for BLE, which is a valid use-case (see your favorite candy vending machine). So I thinks examples is the better place.

+1

**Comment by tcschmidt** [comment]
Is there any resolution for this matter of taste?

**Comment by haukepetersen** [comment]
After reading through this now, I think the current name is sufficient, as `Eddystone` and `IBeacon` are well defined (sub-)protocols for BLE and the search engine of choice result's are very clear on what they are. So I close this PR and leave the name as is -> if anyone has still strong feelings about this feel free to open new PRs :-)

**Pull request closed without merging**
