### PR TITLE
boards: slstk3402a: add docs

### PR DESCRIPTION
**Pull request by basilfx**
### Contribution description

Now that #8516 is merged, I can merge the documentation for the SLSTK3402a. I don't include the images, since there is no place to store them.

If this PR gets merged, I will open similar PR's for the other boards.

### Issues/PRs references

#8516

### CODE REVIEW

**Comment by miri64** [comment]
> I don't include the images, since there is no place to store them.

I theory you could save them at `doc/doxygen/src` and doxygen should pick them up...

**Comment by basilfx** [comment]
> I theory you could save them at doc/doxygen/src and doxygen should pick them up...

In #8516 it was mentioned that this could be a copyright issue (they are taken from the manuals by Silicon Labs).

**Comment by miri64** [comment]
You are right! I assumed you had the copyright.

**Comment by basilfx** [comment]
Ping @jia200x

**Comment by jia200x** [comment]
just tested it and works as expected!

**Pull request merged**
