### PR TITLE
drivers/sx127x: changes in DIO handling

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

There are boards that don't have connected all DIO lines. For example, `esp32-ttgo-t-beam` and `esp32-heltec-lora32-v2` (PR #11265) don't have connected `DIO3` which is used in the `sx127x` driver for the CAD procedure. This is also the case for the [Dragino LoraShield](http://www.dragino.com/products/module/item/102-lora-shield.html).

Therefore, this PR changes the DIO line handling as following:

- If `DIO3` pin is not defined, the `CapDone` interrupt is mapped to `DIO0` (commit https://github.com/RIOT-OS/RIOT/commit/56040e3369c2f8b0c8f8955dfe7967f409f667a3). This allows the use of CAP even on boards where the `DIO3` line is not connected..
- If `DIO3` pin is not defined, at least the related interrupt flags have to be cleared in `_on_dio3_irq` (https://github.com/RIOT-OS/RIOT/commit/87021a0b186a36ae02f0513ca701f2847f21905c). Otherwise the `ValidHeader` interrupt flag keeps pending.
- Since frequency hopping requires the `DIO2` interrupt to work, https://github.com/RIOT-OS/RIOT/commit/1eb8701965f8f82f62ced9de13669bce660cabe0 ensures that `DIO2` pin is defined if frequency hopping is enabled (`LORA_FREQUENCY_HOPPING_DEFAULT = true`).
- Since the `RxTimeout` interrupt is enabled during receive, `DIO1` mapping should be set also to `RxTimeout` in case the driver is extended in future and `DIO1` mapping is changed for any reason (commit https://github.com/RIOT-OS/RIOT/commit/e3a82cd6fc3bed60ebdf3393ec87844aed8cf7d8).

Space for improvement: Since the `FhssChangeChannel` interrupt could also be mapped to `DIO1`, it would be possible to support also boards that don't have connected `DIO2` line.

### Testing procedure

- `tests/driver_sx127x` and/or `examples/lorawan` should still work for any LoRa-Board.
to test commit https://github.com/RIOT-OS/RIOT/commit/56040e3369c2f8b0c8f8955dfe7967f409f667a3 and https://github.com/RIOT-OS/RIOT/commit/87021a0b186a36ae02f0513ca701f2847f21905c 

- Use `tests/driver_sx127x` as following to test commit https://github.com/RIOT-OS/RIOT/commit/56040e3369c2f8b0c8f8955dfe7967f409f667a3as:
   ```
   CFLAGS='-DDEBUG_ASSERT_VERBOSE make BOARD=... -C tests/driver_sx127x flash term
   ```
   should still work, but
   ```
   CFLAGS='-DDEBUG_ASSERT_VERBOSE -DLORA_FREQUENCY_HOPPING_DEFAULT=true -DSX127X_PARAM_DIO2=GPIO_UNDEF' make BOARD=... -C tests/driver_sx127x flash term
   ```
   should result into a failed assertion.

### CODE REVIEW

**Comment by fjmolinas** [comment]
> Changes make sense. I tested this with a b-l072z-lrwan1 and works as usual. Maybe @jia200x can confirm that things still work on other LoRaWAN boards?

On what boards would you want this to be tested @leandrolanzieri I have a couple I could test on.

**Comment by leandrolanzieri** [comment]
> > Changes make sense. I tested this with a b-l072z-lrwan1 and works as usual. Maybe @jia200x can confirm that things still work on other LoRaWAN boards?
> 
> On what boards would you want this to be tested @leandrolanzieri I have a couple I could test on.

I wanted to test this at least on the `sensebox`, which has the DIO pins connected differently, and on the `lobaro`. But any other test that you could provide would be good. We trust here the results provided by @gschorcht on `esp32-ttgo-t-beam`.

**Comment by fjmolinas** [comment]
> > > Changes make sense. I tested this with a b-l072z-lrwan1 and works as usual. Maybe @jia200x can confirm that things still work on other LoRaWAN boards?
> > 
> > On what boards would you want this to be tested @leandrolanzieri I have a couple I could test on.
> 
> I wanted to test this at least on the `sensebox`, which has the DIO pins connected differently, and on the `lobaro`. But any other test that you could provide would be good. We trust here the results provided by @gschorcht on `esp32-ttgo-t-beam`.

Maybe @kYc0o can test on lobaro?

**Comment by leandrolanzieri** [comment]
We just got a new GW so I will be able to test this shortly.

**Comment by kYc0o** [comment]
> Maybe @kYc0o can test on lobaro?

Sure! Will give feedback next week.

**Comment by leandrolanzieri** [comment]
Tests results for `sensebox_samd21` on `gnrc_lorawan`:
```
ifconfig 4 up
2020-05-08 15:31:48,985 #  ifconfig 4 up
> ifconfig
2020-05-08 15:32:01,493 #  ifconfig
2020-05-08 15:32:01,507 # Iface  4  HWaddr: 01:7F:45:B7  Frequency: 868299987Hz  BW: 125kHz  SF: 12  CR: 4/5  Link: up 
2020-05-08 15:32:01,515 #            TX-Power: 14dBm  State: SLEEP  Demod margin.: 0  Num gateways.: 0 
2020-05-08 15:32:01,517 #           IQ_INVERT 
2020-05-08 15:32:01,519 #           RX_SINGLE OTAA L2-PDU:255 
2020-05-08 15:32:01,519 #           
> send 4 RIOT 3
2020-05-08 15:32:39,147 #  send 4 RIOT 3
2020-05-08 15:32:42,689 # Successfully sent packet
> send 4 RIOT 3
2020-05-08 15:32:54,428 #  send 4 RIOT 3
2020-05-08 15:32:58,136 # PKTDUMP: data received:
2020-05-08 15:32:58,146 # ~~ SNIP  0 - size:   7 byte, type: NETTYPE_LORAWAN (1)
2020-05-08 15:32:58,148 # 00000000  48  69  20  6E  6F  64  65
2020-05-08 15:32:58,160 # ~~ SNIP  1 - size:   1 byte, type: NETTYPE_UNDEF (0)
2020-05-08 15:32:58,161 # 00000000  02
2020-05-08 15:32:58,166 # ~~ SNIP  2 - size:   8 byte, type: NETTYPE_UNDEF (0)
2020-05-08 15:32:58,171 # 00000000  A0  B7  45  7F  01  A0  01  00
2020-05-08 15:32:58,175 # ~~ PKT    -  3 snips, total size:  16 byte
2020-05-08 15:32:58,176 # Successfully sent packet
> send 4 RIOT!! 3
2020-05-08 15:33:24,183 #  send 4 RIOT!! 3
2020-05-08 15:33:28,217 # PKTDUMP: data received:
2020-05-08 15:33:28,228 # ~~ SNIP  0 - size:  14 byte, type: NETTYPE_LORAWAN (1)
2020-05-08 15:33:28,229 # 00000000  44  6F  77  6E  73  74  72  65  61  6D  69  6E  67  21
2020-05-08 15:33:28,244 # ~~ SNIP  1 - size:   1 byte, type: NETTYPE_UNDEF (0)
2020-05-08 15:33:28,244 # 00000000  02
2020-05-08 15:33:28,247 # ~~ SNIP  2 - size:   8 byte, type: NETTYPE_UNDEF (0)
2020-05-08 15:33:28,247 # 00000000  A0  B7  45  7F  01  A0  02  00
2020-05-08 15:33:28,248 # ~~ PKT    -  3 snips, total size:  23 byte
2020-05-08 15:33:28,248 # Successfully sent packet
```

**Comment by leandrolanzieri** [comment]
Results for `lobaro-lorabox` with `gnrc_lorawan`:
```
> ifconfig 4 up
2020-05-12 09:20:08,240 #  ifconfig 4 up
> ifconfig
2020-05-12 09:20:18,458 #  ifconfig
2020-05-12 09:20:18,468 # Iface  4  HWaddr: 01:B4:93:95  Frequency: 868099975Hz  BW: 125kHz  SF: 12  CR: 4/5  Link: up 
2020-05-12 09:20:18,477 #            TX-Power: 14dBm  State: SLEEP  Demod margin.: 0  Num gateways.: 0 
2020-05-12 09:20:18,479 #           IQ_INVERT 
2020-05-12 09:20:18,483 #           RX_SINGLE OTAA L2-PDU:255 
2020-05-12 09:20:18,484 #           
> send 4 RIOT! 3
2020-05-12 09:20:51,378 #  send 4 RIOT! 3
2020-05-12 09:20:54,920 # Successfully sent packet
> send 4 RIOT! 3
2020-05-12 09:21:16,091 #  send 4 RIOT! 3
2020-05-12 09:21:20,125 # PKTDUMP: data received:
2020-05-12 09:21:20,137 # ~~ SNIP  0 - size:  14 byte, type: NETTYPE_LORAWAN (1)
2020-05-12 09:21:20,139 # 00000000  44  6F  77  6E  73  74  72  65  61  6D  69  6E  67  21
2020-05-12 09:21:20,151 # ~~ SNIP  1 - size:   1 byte, type: NETTYPE_UNDEF (0)
2020-05-12 09:21:20,152 # 00000000  02
2020-05-12 09:21:20,155 # ~~ SNIP  2 - size:   8 byte, type: NETTYPE_UNDEF (0)
2020-05-12 09:21:20,158 # 00000000  A0  95  93  B4  01  A0  01  00
2020-05-12 09:21:20,161 # ~~ PKT    -  3 snips, total size:  23 byte
2020-05-12 09:21:20,163 # Successfully sent packet
> send 4 RIOT! 3
2020-05-12 09:21:26,503 #  send 4 RIOT! 3
2020-05-12 09:21:30,046 # Successfully sent packet
```

Confirmation of downlink working as well:
image

**Comment by leandrolanzieri** [comment]
Unless @kYc0o wants to perform another test, I'd say we are ok to go

**Comment by kYc0o** [comment]
I'd like to yeah, sorry for the delay, I'll do it today.

**Comment by kYc0o** [comment]
Sorry for the delay. The changes don't affect my platforms.

Thanks for the improvement @gschorcht !

**Pull request merged**
