### PR TITLE
doc: move details section to the top

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
Add a layout file for Doxygen which has the details section at the beginning of a page as opposed to the default where the details are somewhere in the middle.

I'm not sure if it's a good idea to diverge from Doxygen's default settings here, but I always found it confusing not to be presented with the textual API overview at the start of the API documentation.

### Edit
Added the following changes:
- disable REPEAT_BRIEF Doxgen setting - Details follow the brief section immediately now.
- fix trailing whitespace in Doxygen XML

### CODE REVIEW

**Comment by authmillenon** [comment]
I would prefer to use a more modern layout altogether, though I guess this is a good start :-).

**Comment by OlegHahm** [comment]
I haven't checked the actual effect of this change, but moving the details to the top sounds like a good idea to me.

**Comment by OlegHahm** [comment]
I guess you copied the XML from somewhere. Could paste a diff here?

**Comment by cgundogan** [comment]
just a minor question: you authored/commited your commit with another account, was that intentional?

**Comment by LudwigKnuepfer** [comment]
> just a minor question: you authored/commited your commit with another account, was that intentional?

No, will fix tomorrow.

**Comment by LudwigKnuepfer** [comment]
> I guess you copied the XML from somewhere. Could paste a diff here?

The XML was generated by Doxygen as specified in its own documentation:
```
$ doxygen -l
```
The diff looks like this:
```
$ diff -u DoxygenLayout.xml RIOTDoxygenLayout.xml
--- DoxygenLayout.xml	2016-02-21 18:29:55.772533018 +0100
+++ RIOTDoxygenLayout.xml	2016-02-21 18:30:27.119170983 +0100
@@ -25,6 +25,7 @@
   <!-- Layout definition for a class page -->
   <class>
     <briefdescription visible="yes"/>
+    <detaileddescription title=""/>
     <includes visible="$SHOW_INCLUDE_FILES"/>
     <inheritancegraph visible="$CLASS_GRAPH"/>
     <collaborationgraph visible="$COLLABORATION_GRAPH"/>
@@ -62,7 +63,6 @@
       <related title="" subtitle=""/>
       <membergroups visible="yes"/>
     </memberdecl>
-    <detaileddescription title=""/>
     <memberdef>
       <inlineclasses title=""/>
       <typedefs title=""/>
@@ -84,6 +84,7 @@
   <!-- Layout definition for a namespace page -->
   <namespace>
     <briefdescription visible="yes"/>
+    <detaileddescription title=""/>
     <memberdecl>
       <nestednamespaces visible="yes" title=""/>
       <constantgroups visible="yes" title=""/>
@@ -94,7 +95,6 @@
       <variables title=""/>
       <membergroups visible="yes"/>
     </memberdecl>
-    <detaileddescription title=""/>
     <memberdef>
       <inlineclasses title=""/>
       <typedefs title=""/>
@@ -108,6 +108,7 @@
   <!-- Layout definition for a file page -->
   <file>
     <briefdescription visible="yes"/>
+    <detaileddescription title=""/>
     <includes visible="$SHOW_INCLUDE_FILES"/>
     <includegraph visible="$INCLUDE_GRAPH"/>
     <includedbygraph visible="$INCLUDED_BY_GRAPH"/>
@@ -123,7 +124,6 @@
       <variables title=""/>
       <membergroups visible="yes"/>
     </memberdecl>
-    <detaileddescription title=""/>
     <memberdef>
       <inlineclasses title=""/>
       <defines title=""/>
@@ -138,6 +138,7 @@
   <!-- Layout definition for a group page -->
   <group>
     <briefdescription visible="yes"/>
+    <detaileddescription title=""/>
     <groupgraph visible="$GROUP_GRAPHS"/>
     <memberdecl>
       <nestedgroups visible="yes" title=""/>
@@ -160,7 +161,6 @@
       <friends title=""/>
       <membergroups visible="yes"/>
     </memberdecl>
-    <detaileddescription title=""/>
     <memberdef>
       <pagedocs/>
       <inlineclasses title=""/>
@@ -184,11 +184,11 @@
   <!-- Layout definition for a directory page -->
   <directory>
     <briefdescription visible="yes"/>
+    <detaileddescription title=""/>
     <directorygraph visible="yes"/>
     <memberdecl>
       <dirs visible="yes"/>
       <files visible="yes"/>
     </memberdecl>
-    <detaileddescription title=""/>
   </directory>
 </doxygenlayout>
```

**Comment by LudwigKnuepfer** [comment]
> I haven't checked the actual effect of this change, but moving the details to the top sounds like a good idea to me.

sc1
sc2
sc3

**Comment by LudwigKnuepfer** [comment]
With this change it seems reasonable to change this to `NO`:
```
# If the REPEAT_BRIEF tag is set to YES doxygen will prepend the brief
# description of a member or function before the detailed description
#
# Note: If both HIDE_UNDOC_MEMBERS and BRIEF_MEMBER_DESC are set to NO, the
# brief descriptions will be completely suppressed.
# The default value is: YES.

REPEAT_BRIEF           = YES
```

**Comment by LudwigKnuepfer** [comment]
With `REPEAT_BRIEF           = NO`:
sc4

**Comment by OlegHahm** [comment]
ACK from my side.

**Comment by OlegHahm** [comment]
And thanks for the nice screenshot service.

**Comment by LudwigKnuepfer** [comment]
All reviewers seem to think it's a good idea, one ACK is enough => merge.

**Pull request merged**
