### PR TITLE
boards: removed support for redbee-econotag

### PR DESCRIPTION
**Pull request by haukepetersen**
I propose to remove the `redbee-econotag` port for several reasons: 
- its not maintained well -> at least for me locally here it's not even building
- to my information it is not used by anyone (correct me if I am wrong!)
- the CPU would need a lot of attention to make it confirm to peripheral drivers and related changes (e.g. #3164), effectively slowing us down quite a bit
- the platform has a serious RAM problem, since all code needs to be transferred into RAM so it can be executed -> this means that all our networking code does not run on this platform anyway

If there are good reasons for keeping this platform and anyone is volunteering for keeping it up to date I am happy to close this PR again, otherwise I would vote for dropping the support for now and re-add it if there is the need for it later.

### CODE REVIEW

**Comment by OlegHahm** [comment]
> its not maintained well -> at least for me locally here it's not even building

Also, I'm completely fine to remove this legacy board, this sounds weird. What's the error?

**Comment by kaspar030** [comment]
I completely agree. ACK. Let's wait for a second one.

**Comment by OlegHahm** [comment]
Second ACK, but I would still leave this open for at least 24 hours, to give a potential user/supporter of this platform the chance to object.

**Comment by haukepetersen** [comment]
fine with me

**Comment by kaspar030** [comment]
Unfortunately that blocks uart0 removal...

**Comment by OlegHahm** [comment]
Well, I guess we can live with this delay. Since we're in feature freeze, nothing should cause rebasing.

**Comment by kaspar030** [comment]
> I guess we can live with this delay.

+1

**Comment by thomaseichinger** [comment]
There are several occurrences of `redbee-econotag` in Makefiles. Namely
* [ ] examples/gnrc_networking/Makefile
* [ ] tests/coap/Makefile
* [ ] tests/posix_semaphore/Makefile
* [ ] tests/struct_tm_utility/Makefile
* [ ] tests/thread_cooperation/Makefile
* [ ] tests/unittests/Makefile

**Comment by haukepetersen** [comment]
removed blacklistings

**Comment by haukepetersen** [comment]
Travis is happy, any last regrets? Otherwise feel free to push the button :-)

**Comment by OlegHahm** [comment]
3 hours early, but I guess it's okay. ;)

**Pull request merged**
