### PR TITLE
drivers: renamed periph_common

### PR DESCRIPTION
**Pull request by haukepetersen**
Taken from #3420

### CODE REVIEW

**Comment by gebart** [comment]
the name change is somewhat unintuitive, what is the rationale? what does `periphdri` mean?

**Comment by haukepetersen** [comment]
I agree that the new name might not be the most intuitive, but I couldn't think of anything better.

The rationale here is, that periph drivers will be/must be explicitly stated when used in the future, e.g. `USEMODULE += periph_uart`. With this the make system can for example to automatic matching, if a platform provides all peripherals needed for say a temp sensor (i.e. gpio and i2c). Implementing this in the make system makes use of the wildcard `periph_%` quite a bit, which leads to collisions with the existing `periph_common`...

**Comment by haukepetersen** [comment]
hm, how about `common_periph` for a name?

**Comment by gebart** [comment]
or fallback, or noop, or stub

**Comment by PeterKietzmann** [comment]
I prefer **`common_periph`** or `fallback_periph` over `periphdri_common`

**Comment by haukepetersen** [comment]
changed name to `common_periph` how does that look?

**Comment by PeterKietzmann** [comment]
IMO it "looks" better. But now that I'm looking at it, I'm not sure if the name is either speaking or confusing (because of the twisted semantic from `periph_xy` to `xy_periph`)

**Comment by OlegHahm** [comment]
Without reading the discussion here, the name looks pretty confusing indeed (because of the twisted semantic that Peter mentioned). How about leaving this module named `periph_common` and introducing a prefix for MCU specific implementations instead? Something like `periph_arch_uart` or `periph_cpu_uart` or `periph_mcu_uart`.

**Comment by haukepetersen** [comment]
no, that is IMHO not an option - as the module is not CPU specific. When you say `USEMODULE += periph_uart` in your project, you mean to use uart - but you don't care that the implementation is CPU specific -> after all this is why we have those periph interfaces... I see rather the `periph_common` to be the one that is 'hidden' from the app developer, as this is only an internal things when it comes to implementing periph drivers for a specific CPU, hence I would say to give the common module a 'different' name...

**Comment by PeterKietzmann** [comment]
So maybe we need to find a speaking name in one word, without an underscore.

**Comment by haukepetersen** [comment]
I don't care, I tend to now just leave the name as is and add some extra lines to the makesystem that filter out the `periph_common` from the rest of the periph_xxx statements...

**Comment by kaspar030** [comment]
is that very clumsy? if not,it would be my preferred choice...

-----Original Message-----

**Comment by OlegHahm** [comment]
> no, that is IMHO not an option - as the module is not CPU specific. When you say USEMODULE += periph_uart in your project, you mean to use uart - but you don't care that the implementation is CPU specific -> after all this is why we have those periph interfaces... 

I don't see how using `periph_arch_uart` is different in this aspect from using `periph_uart`.

**Comment by haukepetersen** [comment]
@kaspar030: managable, so lets go with that

@OlegHahm: `periph_arch_` is looks more ugly than `periph_xx` :-)

So I will go with some extra magic in the makefile instead of this PR -> closing it.

**Comment by authmillenon** [comment]
Just one question from the background: While documenting I found that `periph` is much more connected to `cpu` than `drivers` (even the implementations are there). Would it make sense to

```sh
git mv drivers/include/periph cpu/include/periph
```

I did not follow this discussion as closely, but maybe this provides a simple solution to that (by calling it `cpu_periph`, rather than `drivers_periph`).

**Comment by haukepetersen** [comment]
moving the peripheral interface defintions into the CPU folder might indeed make sense, I am open to that. Though it does not solve the issue discussed above...

**Comment by OlegHahm** [comment]
@authmillenon, I see your point however, from a logical point of view it is still a driver and your solution would require to create a new folder that has to be added to include pathes. I'm very much in favor or keeping the number of include pathes small. And remember: the documentation structure doesn't have to be 1-to-1 follow the directory structure.

**Comment by haukepetersen** [comment]
I think Oleg has a point -> otherwise just open an issue and lets discuss there...

**Pull request closed without merging**
