### PR TITLE
.murdock: test 200 repeats of known flakey test

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
This is only a test to try to solve the occasional unrelated hash failure problem forcing CI reruns.

### CODE REVIEW

**Comment by gschorcht** [comment]
@MrKevinWeiss The test failed due to a syntax error. Murdock is idle, so it's good time to do some tests now.

**Comment by MrKevinWeiss** [comment]
Heh, but I was not idle.  I will try to hit this on the weekend when there is not much traffic.

**Comment by MrKevinWeiss** [comment]
hmmm
I will try it again, it looks like we are testing what we want we just didn't get a hit...  Note the mobi6 was enabled before running this test...

**Comment by leandrolanzieri** [comment]
This must be the only PR which we want to fail and keeps passing...

**Comment by kaspar030** [comment]
Maybe ccache is too optimistic, so repeated runs yield same result but cache miss causes hash mismatch?

**Comment by MrKevinWeiss** [comment]
Ya, that will be the next phase, disable ccache...

**Comment by MrKevinWeiss** [comment]
I wonder if the failed results are getting overwritten with passing ones...

**Comment by MrKevinWeiss** [comment]
I will wait until the speedup #18423 is in before continuing with this as the feedback cycle is super long.

**Comment by MrKevinWeiss** [comment]
Theory-> something to do with gitcache

<details><summary>stm pkg</summary>

```
-- running on worker riotbuild-0 thread 4, build number 544157.
make: Entering directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/flatbuffers
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/gemmlowp
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/ruy
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/tflite-micro
make: Leaving directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
make: Entering directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
git-cache: cloning from cache. tag=commita9a295fecf3fbd5a4f571f53b01f63202a3e2113-67849
Building application "tests_pkg_tflite-micro" for "nucleo-l552ze-q" with MCU "stm32".

git-cache: cloning from cache. tag=commitfcf61cd086e02c7a1cf7535ffe30622d1f5d36aa-67791
git-cache: cloning from cache. tag=commite844ffd17118c1e17d94e1ba4354c075a4577b88-70078
git-cache: cloning from cache. tag=commit7ef39c5745a61f43071e699c6a96da41701ae59f-71777
git-cache: cloning from cache. tag=commit1501b574b74fd7877aba30aa9d8b667f41b139c3-73447
sha1sum /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro/tests/01-run.py /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.bin > /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/test-input-hash.sha1
   text	   data	    bss	    dec	    hex	filename
 261616	    632	  13592	 275840	  43580	/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.elf
make: Leaving directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
make: Entering directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/flatbuffers
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/gemmlowp
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/ruy
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/tflite-micro
make: Leaving directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
make: Entering directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
Building application "tests_pkg_tflite-micro" for "nucleo-l552ze-q" with MCU "stm32".

git-cache: cloning from cache. tag=commita9a295fecf3fbd5a4f571f53b01f63202a3e2113-97514
git-cache: cloning from cache. tag=commitfcf61cd086e02c7a1cf7535ffe30622d1f5d36aa-97458
git-cache: cloning from cache. tag=commite844ffd17118c1e17d94e1ba4354c075a4577b88-99609
git-cache: cloning from cache. tag=commit7ef39c5745a61f43071e699c6a96da41701ae59f-101711
git-cache: cloning from cache. tag=commit1501b574b74fd7877aba30aa9d8b667f41b139c3-104901
sha1sum /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro/tests/01-run.py /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.bin > /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/test-input-hash.sha1
   text	   data	    bss	    dec	    hex	filename
 261728	    632	  13592	 275952	  435f0	/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.elf
make: Leaving directory '/tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro'
Hashes of binaries with and without Kconfig mismatch for tests/pkg_tflite-micro with nucleo-l552ze-q
Please check that all used modules are modelled in Kconfig and enabled
Input without KConfig:
039de8cf4c7c6517d7ef39857552fa60e2689529  /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro/tests/01-run.py
eaf5f1f9b629c9e76e843a4ea0272fc0ae6f9e79  /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.bin
Input with KConfig:
039de8cf4c7c6517d7ef39857552fa60e2689529  /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/tests/pkg_tflite-micro/tests/01-run.py
966516307607c5b75fa47b09beed7bc9deca06e9  /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/tests_pkg_tflite-micro.bin
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/flatbuffers
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/gemmlowp
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/ruy
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/tflite-micro
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/flatbuffers
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/gemmlowp
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/ruy
rm -rf /tmp/dwq.0.5632680420550714/c5bcaa217ff54478dfecb5ebe2842b82/build/pkg-build/tflite-micro
{"build/": 120}
```
</details>

**Comment by MrKevinWeiss** [comment]
Status update, we still see mismatches in the nightlies (cryptoauth package tests).

This PR has been rebased and we will see if we can make it reproducible.

**Comment by MrKevinWeiss** [comment]
Ugg, this is still an issue but probably does not make sense to work on it during hacknack.

**Comment by MrKevinWeiss** [comment]
Hmmm I give up on this.  It seems like all the changes are somehow working through it.

**Pull request closed without merging**
