### PR TITLE
jerryscript: bump version

### PR DESCRIPTION
**Pull request by miri64**
Alternative to #9735, as it [includes that fix in upstream][851f4].

[851f4]: https://github.com/jerryscript-project/jerryscript/commit/851f4f0b894fecef96c61da1fdd67678f721404e

### Issues/PRs references
Closes #9735 when merged.

### CODE REVIEW

**Comment by miri64** [comment]
Mhh `ek-lm4f120xl`, `mips-malta`, and `hifive1` don't seem to have `nanosleep()` implemented, though they have `time.h` provided with there respective libc. How do we proceed with them? (/cc @haukepetersen, @neiljay, @kenrabold)

**Comment by miri64** [comment]
My investigation so far:

* `ek-lm4f120xl` is a Cortex-M4, but it isn't configured the same as other Cortex-M boards (it doesn't include `makefiles/arch/cortexm.inc.mk` e.g.) so that might be the issue here.
* `mips-malta` is the only MIPS board that isn't blacklisted for `jerryscript` so far (and from what I could gather at least for OpenWRT they support MIPS; however, there is no UART support for it yet)
* `hifive1` is the odd one out. I don't believe `jerryscript` supports RISC-V, but it used to compile.

**Comment by emmanuelsearch** [comment]
OK. So how about just blacklisting `mips-malta` and `hifive1` for now?

**Comment by kYc0o** [comment]
> OK. So how about just blacklisting mips-malta and hifive1 for now?

+1.

**Comment by miri64** [comment]
`mips-malta` doesn't have UART support for now anyways...

**Comment by miri64** [comment]
Done

**Comment by miri64** [comment]
Found a better solution :-) (just deactivated `HAVE_TIME_H`)

**Comment by miri64** [comment]
Murdock likes it :-)

**Comment by kYc0o** [comment]
Perfect! Please squash.

**Comment by miri64** [comment]
Squashed

**Comment by emmanuelsearch** [comment]
Looks good. Tested on IoT-lab M3.

**Pull request merged**
