### PR TITLE
cpu/stm32f1: remove leftover from #5921

### PR DESCRIPTION
**Pull request by PeterKietzmann**
Removes leftover from #5921

### CODE REVIEW

**Comment by lebrush** [comment]
:+1:

**Comment by PeterKietzmann** [comment]
Guess this is an ACK? Please approve PR and merge. Murdock has passed

**Comment by miri64** [comment]
Murdock is happy too, so go

**Comment by lebrush** [comment]
@miri64 thank you proxy :-)

**Pull request merged**
