### PR TITLE
A basic stm32's HRTIM peripheral driver API and implementation

### PR DESCRIPTION
**Pull request by hugueslarrive**
### Contribution description
This PR provide a basic High Resolution Timer API and implementation with configuration for nucleo-f334r8 and a test.

It is basic in the mean that it only manage outputs for now.

### Testing procedure
Tested using the provided test to produce the oscillograms of the HRTIM cookbook's section 2.

### CODE REVIEW

**Comment by maribu** [comment]
IMO something specific to STM32 MCU should not be part of `drivers/periph`. So far, `drivers/periph` contain low level hardware abstraction layers that any MCU with the required features can implement - regardless of vendor or architecture.

The API provided here is super specific to the STM32 peripherals. IMO this is a no-go for something in `drivers/periph`.

Wouldn't it be possible to come up with an API providing the same features, but without leaking hardware specific details?

If you indeed intent to provide some STM32 only API, it should be placed in `cpu/stm32/include` instead. But IMO such vendor specific APIs should only be provided if the feature is extremely vendor specific. E.g. there is a Cortex-M specific API for bit-banding, as bit-banding is not available (to the best of my knowledge) for any other architecture.

**Comment by benpicco** [comment]
Could this not be covered by the `periph/timer.h` interface?
How different is HRTIM from TIM?

sam0 has different kinds of timers too, but they are similar enough that for the most part they can be used interchangeably. (Ok, this has so far only been implemented for the [pwm interface](https://github.com/RIOT-OS/RIOT/blob/master/cpu/sam0_common/periph/pwm.c)).

**Comment by hugueslarrive** [comment]
> IMO something specific to STM32 MCU should not be part of `drivers/periph`. So far, `drivers/periph` contain low level hardware abstraction layers that any MCU with the required features can implement - regardless of vendor or architecture.
> 
I agree with that, I haven't found anything similar from any other manufacturer apart from the SHRTIMER of the gd32e50 from GigaDevice but it's a joke. However I think that their documentation (https://www.gigadevice.com/manual/gd32e50xxxxx-user-manual/) is better illustrated and more understandable than ST's one which is a shame !

I don't have a lot of knowledge of MCUs so maybe it exists and I haven't found it.

> The API provided here is super specific to the STM32 peripherals. IMO this is a no-go for something in `drivers/periph`.
> 
> Wouldn't it be possible to come up with an API providing the same features, but without leaking hardware specific details?
> 
Maybe... As reference manual introduction say "It is primarily intended to drive power conversion systems such as switch mode power supplies".

So basic functionalities missing from the pwm api are :
- Complementary outputs
- Dead time management
- Phase positioning for interlaced converters or dual active bridge...
- Fault protection inputs (not implemented yet but essential)

Can this be in the scope of extending the current pwm API or is it better to develop a new one? A third one for timers peripherals ?

> If you indeed intent to provide some STM32 only API, it should be placed in `cpu/stm32/include` instead. But IMO such vendor specific APIs should only be provided if the feature is extremely vendor specific. E.g. there is a Cortex-M specific API for bit-banding, as bit-banding is not available (to the best of my knowledge) for any other architecture.

The architecture with a master timer and slave timing units is very specific and make difficult the implementation with the current PWM API. This is also the case for numerous other functionalities of this peripheral.

So I think this is what I'm going to do for now because I don't have much time for this task.

This will give me more flexibility in the development and the useful and generic features can be backported into the global API afterwards if relevant.

**Comment by hugueslarrive** [comment]
> Could this not be covered by the `periph/timer.h` interface?
> How different is HRTIM from TIM?
> 
> sam0 has different kinds of timers too, but they are similar enough that for the most part they can be used interchangeably. (Ok, this has so far only been implemented for the [pwm interface](https://github.com/RIOT-OS/RIOT/blob/master/cpu/sam0_common/periph/pwm.c)).

See Issue #15172.

**Pull request closed without merging**
