### PR TITLE
kinetis: Unify cpu.c, update clock initialization code

### PR DESCRIPTION
**Pull request by gebart**
Unify cpu_init for all Kinetis CPUs to reduce code duplication. Updated the MCG driver implementation to make the configuration easier. Most clock settings are initialized by kinetis_mcg_init() called from cpu_init. Board specific external clock source initialization (FRDM-K64F, PhyNode) needs to be performed in board_init instead of in cpu_init.

The clock dividers (SIM_CLKDIV1) previously set in various places for different boards are now unified and handled directly by the MCG driver.

### CODE REVIEW

**Comment by gebart** [comment]
Testing status:

 - [x] frdm-k22f
 - [ ] frdm-k64f
 - [ ] mulle
 - [ ] pba-d-01-kw2x

@haukepetersen @aabadie do you have access to any of the above boards for testing?

**Comment by gebart** [comment]
Forgot to update the documentation. Will address.

**Comment by kYc0o** [comment]
Great! I'll take a look asap.

**Comment by gebart** [comment]
updated docs

**Comment by gebart** [comment]
Relevant tests are tests/xtimer_drift and examples/gnrc_networking (for the Phytec board)

**Comment by kYc0o** [comment]
I just tested this without success. No example runs anymore either on mulle or frdm-k64f. I didn't test on pba-d-01-kw2x.

**Comment by gebart** [comment]
The problem with mulle and k64f is a configuration error. I will update this PR tomorrow, or later tonight. Also found another problem which messed up the FEI mode.

**Comment by gebart** [comment]
@kYc0o 
 - Fixed the configuration error on Mulle and FRDM-K64F
 - Improved safe mode robustness
 - Fixed an issue with settings not being applied when configuring FEI mode
 - Updated all I2C timings to match the board clocks
 - Changed default Mulle core clock to 48 MHz
 - Corrected the I2C clock sources to match their respective reference manuals

**Comment by gebart** [comment]
Tested I2C on Mulle and FRDM-K22F using the tests/drivers_hih6130 and the HIH6130 sensor breakout board from Sparkfun.

**Comment by gebart** [comment]
@kYc0o do you mind testing on k64f? I don't have that board.
@OlegHahm @haukepetersen do you have a PhyTec board available for testing this PR?

**Comment by kYc0o** [comment]
Tested on pba-d-01-kw2x (kw22d512 model) and frdm-k64f boards. Everything works as expected.

**Comment by kYc0o** [comment]
Please squash.

**Comment by gebart** [comment]
@kYc0o squashed, waiting for Murdock

**Comment by kYc0o** [comment]
Go!

**Pull request merged**
