### PR TITLE
doxygen: generate graphs for includes

### PR DESCRIPTION
**Pull request by OlegHahm**
Going visual

### CODE REVIEW

**Comment by authmillenon** [comment]
How can I see them?

**Comment by authmillenon** [comment]
Ah, got it. ACK

**Comment by OlegHahm** [comment]
btw. the downside of this change: building the documentation takes slightly longer.

**Comment by authmillenon** [comment]
I would say significantly longer ;-), but since it is cached for the most part, I would say this is okay. :-)

**Comment by OlegHahm** [comment]
Oh, indeed. That's not good for Travis.

**Comment by authmillenon** [comment]
Travis still needs < 2 min for static tests, so I guess it's okay ;-).

**Comment by LudwigOrtmann** [comment]
ACK & go

**Comment by LudwigOrtmann** [comment]
PS:
Any reason not to also enable other graphs?
EG:
```diff
diff --git a/doc/doxygen/riot.doxyfile b/doc/doxygen/riot.doxyfile
index b46dc6b..63d2c4a 100644
--- a/doc/doxygen/riot.doxyfile
+++ b/doc/doxygen/riot.doxyfile
@@ -2226,7 +2226,7 @@ INCLUDED_BY_GRAPH      = YES
 # The default value is: NO.
 # This tag requires that the tag HAVE_DOT is set to YES.
 
-CALL_GRAPH             = NO
+CALL_GRAPH             = YES
 
 # If the CALLER_GRAPH tag is set to YES then doxygen will generate a caller
 # dependency graph for every global function or class method.
@@ -2237,7 +2237,7 @@ CALL_GRAPH             = NO
 # The default value is: NO.
 # This tag requires that the tag HAVE_DOT is set to YES.
 
-CALLER_GRAPH           = NO
+CALLER_GRAPH           = YES
 
 # If the GRAPHICAL_HIERARCHY tag is set to YES then doxygen will graphical
 # hierarchy of all classes instead of a textual one.
```

**Comment by OlegHahm** [comment]
I thought call and caller graphs were not very helpful since we don't let doxygen parse our C files.

**Comment by kaspar030** [comment]
Can we?

**Comment by OlegHahm** [comment]
We could, but this would introduce a hell lot of new warnings and probably break the output without any changes, I guess. And this would force us to do proper doxygen style even in C files.

**Comment by authmillenon** [comment]
I say we get our header files documented first, before we expose doxygen to our undocumented C files

**Comment by OlegHahm** [comment]
I think undocumented C files are not even the worst problem, but I know that are tons of comments in these files that doxygen would try to parse that are not even meant to be parsed.

**Pull request merged**
