### PR TITLE
core: msg: fix msg_try_receive()

### PR DESCRIPTION
**Pull request by kaspar030**
Incredible, but after all these years I found a bug in the core msg semantics:

msg_try_receive() only considered the message queue, ignoring possibly send blocked threads.

This PR includes a test case. IMHO we could drop that commit before merging, as the small bugfix doesn't deserve a test. Too bad we don't have unittests for messaging...

### CODE REVIEW

**Comment by OlegHahm** [comment]
Nice catch! But there might be an explanation why it hasn't been identified earlier: it's almost unused. The only call of `msg_try_receive()` is inside the shell ping command. Maybe we should consider dropping it completely? (Although, I kind of like the symmetry of send/try_send and receive/try_receive.)

As for the test: how about starting a unittest with just this one test case and creating an issue that we need to add more?

**Comment by kaspar030** [comment]
> As for the test: how about starting a unittest with just this one test case and creating an issue that we need to add more?

In theory, nice. In practice, not this time. I found this bug while working on something else, not time for a unittest currently...

**Comment by authmillenon** [comment]
Another issue with "unittesting msg" ist the one we already discussed million times since we introduced the unittest test app: How? Threading + proper unit testing is hard and/or next to impossible.

**Comment by OlegHahm** [comment]
So, any opinion on removing `msg_try_receive()`?

**Comment by OlegHahm** [comment]
Anyway, that might go into another PR, let's merge this first.

**Comment by kaspar030** [comment]
> So, any opinion on removing msg_try_receive()?

I'd like to keep it, otherwise message sending is always blocking, which is very probably not always wanted.
A simple use-case would be a gnrc thread trying to send a message to another thread whose queue is full. msg_try_send() would allow communicating that case to the caller.
We might not use it, but IMHO it can be useful, (and it's just a couple of lines).

**Comment by kaspar030** [comment]
> Threading + proper unit testing is hard and/or next to impossible.

True that... Though we could create "one application per testcase" and parse the output, like we did using the expect scripts.

**Comment by kaspar030** [comment]
So should I remove the test app commit?

**Comment by OlegHahm** [comment]
> I'd like to keep it, otherwise message sending is always blocking, which is very probably not always wanted.

I was only talking about `msg_try_receive()` not `msg_try_send()`.

> We might not use it, but IMHO it can be useful, (and it's just a couple of lines).

Fine with me.

**Comment by OlegHahm** [comment]
Forgot to say: ACK, please squash!

**Comment by kaspar030** [comment]
- squashed

It's a one-line bugfix of a rarely used function, so I think one ACK will be enough...

**Pull request merged**
