### PR TITLE
Xbee 802.15.4 modem driver for Arduino

### PR DESCRIPTION
**Pull request by rousselk**
This radio driver allows to use an XBee 802.15.4 modem with an Arduino board, using the official Arduino Wireless/SD shield (see http://arduino.cc/en/Main/ArduinoWirelessShield) for connection.

Follow-up to #1463 (from my new personal repository).

### CODE REVIEW

**Comment by rousselk** [comment]
Todo (to remove the WIP status): make this code conformant to the new network API defined in #1492.

I will do it as soon as I have time...

**Comment by haukepetersen** [comment]
Looking good on first sight! I would suggest you wait a week or two with the adaption of the netdev interface, as this is subject to change right now. Would that be ok with you?

**Comment by LudwigOrtmann** [comment]
I've just been thinking if it makes sense to have a `WITH_XBEE_SHIELD` flag the board could use to include the configuration... @Kijewski any thoughts?

**Comment by LudwigOrtmann** [comment]
Please split the commit (into `drivers:xbee`, `boards:arduino`).

**Comment by LudwigOrtmann** [comment]
Have a look at `Makefile.dep`
```
124 ifneq (,$(filter defaulttransceiver,$(USEMODULE)))
125     FEATURES_REQUIRED += transceiver
126 endif
```
Something along this line (for `UART` instead of `transceiver`) is useful for this driver as well, right?

**Comment by authmillenon** [comment]
#2695 already introduced this feature. If you like to update that implementation please open a new PR.

**Pull request closed without merging**
