### PR TITLE
[SWP] coap plugtests

### PR DESCRIPTION
**Pull request by sgso**
This contains the coap-plugtests application. It passes the sections "Base CoAP", "Block", and "Link format" as specified here: https://github.com/cabo/td-coap4/

It depends on a patched libcoap that is referenced in the pkg/libcoap/Makefile and can be found here: https://github.com/sgso/libcoap/tree/riot-pkg. The patches are based on the current HEAD of libcoap. I worked with upstream to include most of the patches that are currently included in the libcoap pkg directory (most of them were due to RIOTs pedantic compiler flags).

There are no handlers programmed for the "Observe" part of the plugtest but my libcoap branch proposes a variant with timer enabled socket functions to compensate for the missing select/*poll.

### CODE REVIEW

**Comment by sgso** [comment]
@OlegHahm I tried, but I don't understand what the config module is doing and why it breaks the native version when I disable it. I don't know what to do.

**Comment by bapclenet** [comment]
Hi @OlegHahm and @sgso, #2235 is merged so does this PR work?
I would like to try CoAP and if I have understood, this PR is the test implementation of CoAP?

**Comment by OlegHahm** [comment]
@bapclenet, you might want to look at microcoap and https://github.com/RIOT-OS/applications/tree/master/microcoap instead.

**Comment by bapclenet** [comment]
Thank you Oleg, I didn't see this one.
It's not the right place to ask this question but what's the difference between uCoAP and libCoAP? (They have both been made for embedded system) Why should I use uCoAP?

**Comment by OlegHahm** [comment]
I don't know much more than what @authmillenon stated in https://github.com/RIOT-OS/RIOT/pull/2383#issue-56168092, but I also heard several people (e.g. @sgso) complaining about complexity of libcoap and its evolution towards the wrong direction.

**Comment by authmillenon** [comment]
> It's not the right place to ask this question but what's the difference between uCoAP and libCoAP? (They have both been made for embedded system)

* `libcoap` is more feature complete and offers a wrapper functionality for sockets and URLs => very complex, but implementation of CoAP clients is possible.
* `microcoap` only offers header building and parsing and is only suitable for CoAP servers.

>  Why should I use uCoAP?

* If you want to implement a CoAP client and/or have enough memory and flash: use `libcoap`.
* If you want to implement a CoAP server, especially on a constraint device: use `microcoap`.

**Comment by bapclenet** [comment]
Thank you both for your answer! I'm going to try microcoap then.

**Comment by Lotterleben** [comment]
I was wondering what the status of this PR is? Dead? :/

**Comment by bapclenet** [comment]
@Lotterleben, even if RIOT should better use uCoAP than libCoAP, this PR is still on and should be merged if it works. Some people may prefer libCoAP to uCoAP.

**Comment by Lotterleben** [comment]
@bapclenet That's what I thought :) And with literally no existing documentation for libcoap (not RIOT's fault...), this could come in handy as a starting point.

**Comment by OlegHahm** [comment]
@sgso, you're still planing to work on this?

**Comment by sgso** [comment]
I stated above 
> If there is any interest left in it, I'd be happy to bring this whole thing in a better shape but not on native only (I'm fed up with that). If you give me board that can theoretically run it (or a recommendation for one to buy) I'd be far more motivated."

I stand by that but I simply don't know enough about the hardware/wireless side and the ever changing state of RIOT to decide what would be suitable combination of equipment. I'll not do any further development on native. It's great for running tests but for anything network related it sucks.

**Comment by OlegHahm** [comment]
Can you elaborate on your problems with nativenet? @LudwigOrtmann might be interested. @authmillenon, @Lotterleben, are you willing to help @sgso to adopt this to the current state of NSTF?

**Comment by authmillenon** [comment]
Since `libcoap` uses the socket API I don't think he needs to. It's us who need to adopt a socket API for the new network stack ;-) (see [next NSTF meeting](https://github.com/RIOT-OS/RIOT/wiki/minutes-network-stack-task-force-april-2015#socket-api)). For μcoap working with `netapi` might be an option, but I would vote against using it in the plugtests since both libcoap and μcoap should be interchangable in my opinion here. I would rather prefer to have a coap server example that utilizes pure `netapi` usage (maybe an adapted version of @Lotterleben's [microcoap example in the `applications` repo](https://github.com/RIOT-OS/applications/tree/master/microcoap)).

The only thing interesting for him might be that #2558 (or whatever version @kaspar030 spins out of it) makes "nativenet" a pure ethernet device => networking with native becomes a whole lot easier.

**Comment by sgso** [comment]
@OlegHahm No specific problem with nativenet, just that it was obviously created to hook together native instances with each other. But when I'm programming some application layer server then I want to use whatever tools I got on my host. That leaves clunky hacks such as marz.

I think the silver bullet would be to look into the native Linux 6LoWPAN stack (http://wpan.cakelab.org/) and try to hook native instances in there some way. Either by having a virtual physical device (there was a "virtual phy" interface in the older linux-zigbee versions) that works on the 802.14.5 level or (preferably) some kind of tapping/bridging to the 6LoWPAN layer. When I looked into that possibility last year the whole project was defunct but there seems to be progress lately (http://events.linuxfoundation.org/sites/events/files/slides/ELC-US-2015.pdf).

As for the ng_tapnet (#2558) thing ("which is basically nativenet without all the RIOT-proprietary headers (so pure Ethernet frames) but with full ng_netdev support."), I  don't get it. Currently we have Ethernet[ Riot[ 802145[ 6lowpan[ UDP ]]]], and with ng_tapnet that changes into what? What are "all the RIOT-proprietary headers"? The 2 (?) bytes Riot[ ... ] part? That was never the problem.

**Comment by sgso** [comment]
@authmillenon I don't know anything about all the new network stuff (is there an overview of what has changed somewhere?), but is there some select/epoll-like thing for networking now? Last time I asked,  I was told to wait for "the new stuff".

**Comment by authmillenon** [comment]
> As for the ng_tapnet (#2558) thing ("which is basically nativenet without all the RIOT-proprietary headers (so pure Ethernet frames) but with full ng_netdev support."), I don't get it. Currently we have Ethernet[ Riot[ 802145[ 6lowpan[ UDP ]]]], and with ng_tapnet that changes into what? What are "all the RIOT-proprietary headers"? The 2 (?) bytes Riot[ ... ] part? That was never the problem.

First of all: it's <Ethernet|riot|802154|6lowpan|IPv6|UDP|…>. `ng_tapnet` changes this to pure ethernet: <Ethernet|IPv6|UDP|…>. So no proprietary Ethernet header, no 802.15.4, no 6LoWPAN. Just IPv6 over Ethernet. To test 6LoWPAN on native regardless I started porting ZEP (Wireshark's Zigbee Encapsulation Protocol) in #2627 which allows you to send IEEE 802.15.4 frames over UDP. Since 6LoWPAN on native is needed only for testing purposes anyway I think that is a better solution, than hooking into some Linux 6LoWPAN implementation through yet another interface ;-). 

But regardless: CoAP is not dependent on 6LoWPAN and neither are the plugtests (at least that's what I remember, because that let to a lot of frustration for us on the last Plugtest in London, because everybody else used plain IPv4 and v6 while we were only speaking 6LoWPAN). So I guess you don't need ZEP.

> @authmillenon I don't know anything about all the new network stuff (is there an overview of what has changed somewhere?), but is there some select/epoll-like thing for networking now? Last time I asked, I was told to wait for "the new stuff".

The lack of asynchronous IO (which is required for `select()`) is more of an scheduler problem for us (at least that's what I gathered from discussions in the past). To make things short: this is not in the scope of the current refactoring. An overview of the current progress can be found in #2278.

**Comment by sgso** [comment]
@authmillenon Thank you, that cleared it up. I tried the ng_tapdev branch and experimented a little with ng_udp. The tap driver works well for me already.

@OlegHahm I'd like to port this to ng_udp in a separate branch and give it some love in the process so it can be included with complete instructions how to test it locally with ng_tapdev against Californium. Ok?

**Comment by OlegHahm** [comment]
@sgso, sounds perfect to me. Thanks.

**Comment by authmillenon** [comment]
@sgso keep in mind that ng_tapnet is more or less obsoleted by @kaspar030's dev_eth_tap (#2776).

**Comment by sgso** [comment]
I put together a tree of dev_eth_net/ipv6/udp in https://github.com/sgso/RIOT/tree/ng_ipv6/dev_eth_netdev/ng_udp/fixes and started working on the coap plugtests in https://github.com/sgso/applications/tree/master/ng_coap_plugtests

There is no coap yet involved but could somebody take a look at it and tell me if I initialize and use the network stack correctly?

**Comment by authmillenon** [comment]
Normally all the initialization you do in `main()` should be done by auto-init (except the device and `nomac` initialization), so you can leave them out. You can also leave out the coap-thread, unless you plan something special with it, except dumping, and just register the `pktdump` module to `NG_NETTYPE_UDP` with `demux_type` 5683, instead of the registration to `NG_NETTYPE_UNDEF` (if you don't want to, I don't know what you need `pktdump` for here anyways).

**Comment by authmillenon** [comment]
The address auto-initialization will come as soon as I find some time for this :-)

**Comment by sgso** [comment]
I replicated the functionality of this PR with the new network stack in:
https://github.com/sgso/applications/tree/coap-plugtests/coap-plugtests

It needs a RIOT tree with ng_udp & dev_eth_tap and of course a patched libcoap. Locations and instructions can be found in README.md.

Because I'm not using sockets (of any kind) this time, the asynchronous parts integrate nicely and I'll probably start to implement the Observe part of the plugtests as well.

I'd like comments 
1) on the vtimer use in coap_thread.c:coap_run_context(): Is it okay to use 2 timers like I do there or should I calculate the minimum of timeouts for one timer?

2) For now I made a lazy port which doesn't try to optimize much. I'd like to get rid of the mallocs. Is something like this legal/intended:
```
while (packet->next) {
    packet = ng_pktbuf_remove_snip(packet, packet->next);
}
/* packet->next == NULL */
      
/* declare our package as payload */
packet = ng_pktbuf_start_write(packet);
      
if (packet) {
    packet->type = NG_NETTYPE_UNDEF;
}
```
Then "carry" around  `packet` through the libcoap functions and let the pktbuf realloc it before adding data/sending as needed. For a lot of requests the answer will probably be smaller or equal the already allocated packet (certainly for simple ACKS). This would avoid copying buffers for nothing in many cases.

**Comment by authmillenon** [comment]
>>     while (packet->next) {
>>          packet = ng_pktbuf_remove_snip(packet, packet->next);
>>     }
>>     /* packet->next == NULL */
>> 
>>     /* declare our package as payload */
>>     packet = ng_pktbuf_start_write(packet);
>>     
>>     if (packet) {
>>         packet->type = NG_NETTYPE_UNDEF;
>>     }
```

Sure, this is absolute legitimate. If you are in your own thread, there is nothing from stopping you doing stuff with the pkt snips as you like, as long as you make sure (what you do) you have exclusive rights on it.

**Comment by authmillenon** [comment]
@sgso ping?

**Comment by sgso** [comment]
Sorry, I got a little fascinated by real hardware and this suffered under it. I'll polish it within the next week.

The main question now is how to provide the library. I'm not happy with the current patch-set method because updating is tiresome and we'll look at differences of patches here at github.
And even though the changes to libcoap are not fundamental they will still affect a majority of the files with RIOT-specific changes for the network stack, random numbers, logging, etc.

I'd prefer to keep a patched libcoap in a separate repository and periodically update the commit/tag the pkg is pointing at. Upstream has been inactive since last summer, so we wouldn't miss out on anything by having a separate version. Would a RIOT repository be suitable for that? Maybe find one or two other people interested in CoAP besides me to maintain it there?

**Comment by authmillenon** [comment]
I'm still uncertain about the separate repository, but since we are more git-dependent than other operating systems which use similar mechanisms for packages, it may be a better solution for now.

**Comment by authmillenon** [comment]
Any other opinions on this?

**Comment by gebart** [comment]
I think keeping a separate repository can help when reviewing changes. Meta diffs (diffs of diffs) are hard to read and to maintain.
I am interested in libcoap because CoAP is our most commonly used protocol in our Contiki sensor applications. From the looks of the libcoap mailing list and repo commits it does not receive a lot of patches so I guess I could try to help out in reviewing if we decide to produce our own fork.

**Comment by OlegHahm** [comment]
I agree with @gebart and @authmillenon here.

**Comment by gebart** [comment]
@sgso Ping!

needs rebase

**Comment by sgso** [comment]
@gebart I'll commit a cleaned & polished libcoap version suitable for integration or separate repository when my exams are over next week. It's pretty much ready but need to fix some formalities.

**Comment by OlegHahm** [comment]
Any news?

**Comment by sgso** [comment]
Yes. I worked on this with the 'old' libcoap base. This (https://github.com/sgso/libcoap/commits/netapio-riot-clean) contains a netapi port that I cleaned from all the cruft, awful style and platform specific code as a basis for a riot specific version like mentioned above. It's probably outdated but in principle it's there. 

After libcoap moved to github, I found out about the 'develop' branch which is active and seems to address a lot of the issues that I loathed about libcoap. Under the assumption that libcoap is developed actively again, above branch does not make sense anymore.

I tried to get the develop branch working with RIOT. But I will not go to GNU/autoconf-University just for integrating this in my free time. I have better things to do than figure out Makefiles and I don't know why an embedded library needs libtool and other crap. I'd suggest to hand over the project to the Eclipse foundation. They would love to provide some more additional layers of build tools. </sarcasm>

Check https://github.com/sgso/applications/tree/coap-plugtests/coap-plugtests for the latest working plugtests application (for some RIOT/libcoap combination, don't know which). It contains some glue code in coap_thread.c which might be interesting.

Provide me with the Makefile to build the develop-branch within RIOT and I can supply some of my modifications. Apart from that, I'm out.

(closing this)

**Comment by dimG79** [comment]
Hello

**Comment by dimG79** [comment]
Hello,

I am new to RIOT OS and do not have much experience with embedded programming. I am trying to flash the client.c code provided by libcoap examples into my board. However I am facing compilation problems. Is including the libcoap pkg into my makefile not enough?

I am sorry if my question is not relevant to this topic.

**Comment by bapclenet** [comment]
Libcoap examples have been tested with RIOT yet. For the moment, you can compile libcoap package with an example as it is shown here:
https://github.com/RIOT-OS/RIOT/tree/master/tests/coap
Feel free to complete this example with a working example of libcoap

**Pull request closed without merging**
