### PR TITLE
Revert "at86rf2xx: Add support for channel page"

### PR DESCRIPTION
**Pull request by OlegHahm**
This reverts commit e9f385ae1d749deea422b9166b9eade116327fa0.

https://github.com/RIOT-OS/RIOT/pull/4412 broke support for at86rf23x drivers. Tested on iotlab-m3 with default example.

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK

**Comment by OlegHahm** [comment]
Please, don't merge yet. I want to evaluate #4486 first.

**Comment by emmanuelsearch** [comment]
Shall we untag and close this then?

**Comment by OlegHahm** [comment]
Definitely closing.

**Pull request closed without merging**
