### PR TITLE
cpu/stm32f1: udpated vendor headers

### LINKED ISSUE #392: clean up license headers
There exist various license headers throughout RIOTs sources. Also some files don't have license headers at all.

* Unify all lgpl license headers.
* Unify all 'other license' headers for each `other license`.
* Identify files without licenses, contact their original authors and get them to explicitly license the respective files under the lgplv2. (see #560)

### PR DESCRIPTION
**Pull request by haukepetersen**
The vendor header we were using for the `stm32f1` is veeery old, it is from STM's pre-Cube-lib-days... The modern headers are much easier to read and more consistent with other STM headers in RIOT.

Also this should fix #392 for the `stm32f1`.

### CODE REVIEW

**Comment by haukepetersen** [comment]
changed dos to unix line endings in header files and squashed

**Comment by thomaseichinger** [comment]
Changes look good to me. ACK when Travis passed.

**Comment by authmillenon** [comment]
Needs rebase due to #3309

**Comment by haukepetersen** [comment]
rebased

**Pull request merged**
