### PR TITLE
Board, cc2650stk: fix button config

### PR DESCRIPTION
**Pull request by smlng**
this PR fixes the button gpio configuration for board cc2650stk (aka SensorTag), the problem is that in `tests/button` on master the buttons will be trigger in a loop without actually pressing them. Adding a PULLUP on init fixes this.

PR requires #7335 to fix a more general platform issue.

### CODE REVIEW

**Comment by smlng** [comment]
> Tested with "tests/buttons".

that was the idea 😉 

Thanks for extensive tests of my open PRs!! For future reference: would also be helpful if you could state that it doesn't work with current master - so its clear that we have a _real_ fix here; not just some code optimization.

**Comment by smlng** [comment]
btw. may need  #7333, too, for flashing

**Comment by PeterKietzmann** [comment]
The fix is independent from any timer PR. Will remove the label and trigger Murdock again

**Comment by PeterKietzmann** [comment]
Aaaah, it was waiting for #7342? Guess you have to rebase

**Comment by smlng** [comment]
> it was waiting for #7342?

yes, but you merged that, will rebase anyway and retrigger Murdock.

**Comment by smlng** [comment]
rebased, wait for Murdock

**Pull request merged**
