### PR TITLE
tests: move all pkg applications to their own pkgs/ folder

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is similar as #19435 but applied to pkg test applications.

### Testing procedure

Green CI

### Issues/PRs references

Follow-up of #19435

### CODE REVIEW

**Comment by gschorcht** [comment]
Looks good and works as expected. One nitpicking comment, the tests for `$RIOTBASE/drivers` are in `$RIOTBASE/tests/drivers`, the tests for `$RIOTBASE/pkg` are now in `$RIOTBASE/tests/pkgs` with `s`. Maybe it makes sense to use same naming scheme as the source directories. I would like to have a second opinion.

**Comment by aabadie** [comment]
> the tests for `$RIOTBASE/drivers` are in `$RIOTBASE/tests/drivers`, the tests for `$RIOTBASE/pkg` are now in `$RIOTBASE/tests/pkgs` with `s`. Maybe it makes sense to use same naming scheme as the source directories

I agree, will change that

**Comment by aabadie** [comment]
> the tests for `$RIOTBASE/drivers` are in `$RIOTBASE/tests/drivers`, the tests for `$RIOTBASE/pkg` are now in `$RIOTBASE/tests/pkgs` with `s`

Actually, that was a bug. The path defined in `app_dirs.inc.mk` without the "s"...

**Comment by miri64** [comment]
> For some reason the static-tests are stuck with this PR...

Maybe the build_system_sanity_check? It might expect the tests (or rather their makefiles) to be in a certain path.

**Comment by miri64** [comment]
We could cancel and restart it to see where exactly it is stuck.

**Comment by miri64** [comment]
Ah, just canceling was sufficient: Seems like vera++ is the check that is stuck:

image

vera++ is the check running after externc, which succeeded:

https://github.com/RIOT-OS/RIOT/blob/04caf1b30a052bce968b0df1e1d892d9c09ea693/dist/tools/ci/static_tests.sh#L118-L122

**Comment by aabadie** [comment]
Thanks for pointing out that the problem was coming from vera++, I could fix the exclude rule of that check in 551472d35f53d3859d32274712175f211f0a89a7. It should be good after that.

**Comment by aabadie** [comment]
`git grep "tests/pkg\_*"` reveals other places where path to pkg test applications have to be updated, mainly in doc. I'll update the PR later.
(I also noticed that there are a few similar things missed in #19435, for Kconfig in .murdock)

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
nimble and lwip are also packages and have their own test application. Any opinion on whether to move their test applications to `tests/pkg` or not? I'm personally in favor of moving them there but maybe some person aren't (and if that's the case what could be an alternative?)

**Comment by gschorcht** [comment]
Hm :thinking: IMHO, if they are test apps for packages, they should reside in `tests/pkg`.

**Comment by aabadie** [comment]
> IMHO, if they are test apps for packages, they should reside in `tests/pkg`.

Let's do this then!

**Comment by aabadie** [comment]
@gschorcht, see #19582

**Pull request merged**
