### PR TITLE
boards: stk3700: add support

### PR DESCRIPTION
**Pull request by basilfx**
### Contribution description

This PR add supports for the Silicon Labs [STK3700](https://github.com/basilfx/EFM2RIOT/blob/master/dist/doc/STK3700.md).

The files are very similar to the SLTB001a already supported

### Issues/PRs references

Made possible by #8139.

### CODE REVIEW

**Comment by kYc0o** [comment]
It turns I have one of this. Will test soon :)

**Comment by basilfx** [comment]
Thanks @kYc0o. I'll look into the issues.

Also, @haukepetersen prefers to have a `common/silab` board (see #8295). I haven't found the time to look into that yet, but I think there are only a few common things.

**Comment by basilfx** [comment]
Closing this one for a common approach that I soon will PR.

**Comment by basilfx** [comment]
New attempt in #8520.

**Pull request closed without merging**
