### PR TITLE
cpu/esp*: remove dependencies on GNRC for ESP network device drivers

### LINKED ISSUE #12964: esp32: network devices pull in GNRC dependencies statically
#### Description
While compile testing #12931 we noticed that the ESP32 won't build `tests/lwip` anymore. The reason: All the device drivers for the SoC network devices pull in GNRC as a static dependency.

#### Steps to reproduce the issue
Build `tests/lwip` for an ESP32 board, e.g.

```sh
BOARD=esp32-wroom-32 make -C tests/lwip
```

#### Expected results
`tests/lwip` should not pull in any GNRC dependencies.

#### Actual results
From the build output in current master:

```
"make" -C /data/riotbuild/riotbase/sys/net/gnrc
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netapi
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif/hdr
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netreg
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pkt
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pktbuf
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pktbuf_static
```

#### Versions
Current master (50c2a2ca066a3725a4d79270e2559a6567893)

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR removes the dependencies of ESP network device drivers on GNRC.

### Testing procedure

The following compilations should still succeed:

- [ ] `esp_eth`: ```make BOARD=esp32-olimex-evb -C tests/shell```
- [ ] `esp_now`: ```make BOARD=esp32-wroom-32 -C tests/lwip```
- [ ] `esp_wifi`: ```USEMODULE=esp_wifi make BOARD=esp32-wroom-32 -C tests/lwip```

### Issues/PRs references

Fixes #12964
Prerequisite for PR #12931

### CODE REVIEW

**Comment by miri64** [comment]
What's with the GNRC dependencies in the driver code?

**Comment by gschorcht** [comment]
@miri64 The fix can be tested without having the hardware. If the compilations succeed, there is no further dependency on `gnrc`.

I hope it is Ok, that I'm pushing another very small fix related to lwip with this PR. The call of `esp_wifi_setup` has to be placed outside the conditional compilation. Otherwise, `esp_wifi_netdev` is not initialized for `lwip_ipv4`.

**Comment by gschorcht** [comment]
> What's with the GNRC dependencies in the driver code?

Are there any? Hm, I will check again, but the compilation didn't complain.

**Comment by gschorcht** [comment]
Indeed, when `auto_init` is enabled.

**Comment by gschorcht** [comment]
Could it happen that `auto_init_...` is called without having `gnrc` enabled?

**Comment by miri64** [comment]
I suggest to put the `gnrc_netif` initialization into `auto_init_gnrc_netif` as all the rest. The `gnrc_netif_t` (if it is needed by the device for some reason) should be a more generic context: either a pointer to a `netif_t` instead or just a `void` pointer (the latter would be preferable as not every stack might use `netif_t`

**Comment by miri64** [comment]
> Could it happen that `auto_init_...` is called without having `gnrc` enabled?

`auto_init_gnrc_netif` shouldn't be, but `auto_init` can be used without GNRC of course.

**Comment by gschorcht** [comment]
Hm, es simple `#if MODULE_GNRC` should help.

**Comment by miri64** [comment]
> Hm, es simple `#if MODULE_GNRC` wrapper should help.

Yepp as a quick-fix this is also acceptable. However, I think in the long run the device / network interface initialization should be unified across all devices.

**Comment by miri64** [comment]
Rather use `#ifdef MODULE_GNRC_NETIF` or `MODULE_GNRC_NETIF_ETHERNET` (so the least broadest dependency)

**Comment by gschorcht** [comment]
> I suggest to put the `gnrc_netif` initialization into `auto_init_gnrc_netif` as all the rest.

I was a bit unsure whether `sys/auto_init/netif` is the right location for platform specific initializations. The only other architecture I can see there is STM32.

Do you think that such a change would be good for this PR? I can do it.

**Comment by gschorcht** [comment]
> The gnrc_netif_t (if it is needed by the device for some reason)

To be honest, I don't remember for what porpose the network devices have this `gnrc_netif_t` pointer at all. The netif is assigned during setup but never used. I will remove them.

**Comment by miri64** [comment]
> Do you think that such a change would be good for this PR? I can do it.

The only other SoC-network device which has the init code not in `auto_init_gnrc_netif` seems to be `nrfmin`. However for that the GNRC code is separate from the device code (including the init function). I'd say it is cleaner to have it with the CPU-specific code (as you don't need to hand it parameters), but put it into a GNRC-specific context (e.g. `esp_..._gnrc.c`).

**Comment by gschorcht** [comment]
> I'd say it is cleaner to have it with the CPU-specific code (as you don't need to hand it parameters), but put it into a GNRC-specific context (e.g. `esp_..._gnrc.c`).

I will do it in that way.

The longer I'm crawling through `sys/auto_init/netif` the more I'm wondering why it is for `gnrc` only? At least it is not really name giving.

**Comment by gschorcht** [comment]
I have removed the `gnrc_netif_t` pointer in netdevs and moved the auto intialization for `gnrc` in separate files called `esp_*_gnrc.c`.

**Comment by miri64** [comment]
> The longer I'm crawling through `sys/auto_init/netif` the more I'm wondering why it is for `gnrc` only? At least it is not really name giving, neither function name `auto_init_*` nor the directory nor the file names

Mostly historical reasons.  ^^" Hopefully, this will be a bit cleaner after @jia200x's rework :-)

**Comment by fjmolinas** [comment]
@miri64 have your comments been addressed?

**Comment by benpicco** [comment]
> - [ ]  esp_now: make BOARD=esp32-wroom-32 -C tests/lwip

With this I end up with an empty `ifconfig` output - is that to be expected?
I get something with `USEMODULE=esp_wifi`

**Comment by miri64** [comment]
> @miri64 have your comments been addressed?

Which ones are you referring to? From what I can see above, I'd say yes.

**Comment by gschorcht** [comment]
make BOARD=esp32-wroom-32 -C tests/lwip

> With this I end up with an empty `ifconfig` output - is that to be expected?
> I get something with `USEMODULE=esp_wifi`

Yes. `esp-now` isn't know as netdev driver in `pkg/lwip/contrib`. That is, there can't be a lwIP netif. 

The tests are compilation tests only to prove that gnrc modules are not enabled if one of these netdev drivers are enabled.

**Comment by benpicco** [comment]
Alright, then I'd say everything works as expected.
I didn't test `esp_eth`, but I assume you tested this already.
The code looks good - please squash.

**Comment by gschorcht** [comment]
> > * [ ]   esp_now: make BOARD=esp32-wroom-32 -C tests/lwip
> 
> With this I end up with an empty `ifconfig` output - is that to be expected?
> I get something with `USEMODULE=esp_wifi`
> 
> (No IP in `examples/gnrc_networking`, but that's a known behavior _SLAAC not activated…_, I still get some interface information)

Yes, because it is not rebased onto a version with merged PR #12998.

**Comment by gschorcht** [comment]
@benpicco Please wait, I just suashed and pushed a wrong branch. I had cherry picks from other PR in my branch that were merged in the meantime.

**Comment by gschorcht** [comment]
@benpicco I have rebased and squashed. Everything is fine now.

**Comment by gschorcht** [comment]
@benpicco Thanks for reviewing, testing and merging.

**Pull request merged**
