### PR TITLE
sys: posix: remove not needed strings.h

### PR DESCRIPTION
**Pull request by kaspar030**
See #6260 for discussion.

### CODE REVIEW

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/6260#issuecomment-269249970

**Comment by kaspar030** [comment]
Updated murdock toolchain makes this rather pressing.

@miri64 wrote:
> @kaspar030 if I remember correctly this was done for msp430 and AVR. There is no newlib (yet) on those platforms

Let's see what murdock says. If those platforms cause trouble, I'll create the file in the platform folders.

**Comment by kaspar030** [comment]
@miri64 seems no code needs it?

**Comment by kaspar030** [comment]
@gebart PR'ed the same, and Murdock is broken, so I'll merge without waiting for @miri64's approval.

**Comment by miri64** [comment]
I think it used to be used by libcoap, but if it still builds (should be by `tests/coap`) :+1:

**Pull request merged**
