### PR TITLE
travis: Actually use the build-skip feature

### PR DESCRIPTION
**Pull request by authmillenon**
I somehow forgot to set an essential parameter ^^"

### CODE REVIEW

**Comment by phiros** [comment]
This is strange. I thought that was already in your previous PR...
Anyways -> ACK.
Merge as soon as travis is happy (You could even merge it earlier if you want;
It's your call)

**Comment by LudwigOrtmann** [comment]
Nice, you broke Travis ;)

**Comment by LudwigOrtmann** [comment]
Please revert unless you can attest that this breakage is unrelated.

**Comment by LudwigOrtmann** [comment]
@phiros @authmillenon don't bother I just did it myself.

**Comment by authmillenon** [comment]
Can you please tell me how this broke Travis? Because I did not observe any breakage yesterday...

**Comment by authmillenon** [comment]
And after looking through the pull requests I still don't know what the problem is...

**Comment by LudwigOrtmann** [comment]
The failing Travis output is in this very PR.

**Pull request merged**
