### PR TITLE
Posix: replace all remaining usages of timex in pthread

### PR DESCRIPTION
**Pull request by smlng**

### CODE REVIEW

**Comment by kaspar030** [comment]
codesize?

**Comment by smlng** [comment]
No difference in code size for `native`, for `samr21-xpro` (and other cortex based boards, e.g. nucleos) this PR increases codesize by 28B.

However, timex was already replaced in [posix_semaphore.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/posix/semaphore/posix_semaphore.c#L38) in a similar fashion.

**Comment by smlng** [comment]
Further: someone who cares about code size, would surely **not** use pthread stuff, right?

**Comment by aabadie** [comment]
@smlng, what is the benefit with this change ?

**Comment by smlng** [comment]
Mainly: consistency - currently its mixed usage of `timex` and `xtimer` in `pthread_*` code. As commented above, semaphore already uses xtimer, but cond and rwlock use timex.

**Comment by kaspar030** [comment]
> this PR increases codesize by 28B

... which is tolerable (IMO).

**Comment by aabadie** [comment]
And go

**Pull request merged**
