### PR TITLE
sys/ztimer/kconfig: enable xtimer compat only with timer backend

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
While testing #17235 I came across a discrepancy between when `Makefile.dep` enables xtimer compatibility modules and when Kconfig does it. Kconfig would enable compatibility whenever xtimer and ztimer are active, but `Makefile.dep` checks in addition that the timer peripheral backend is enabled. This PR adds this condition to the Kconfig choice. To avoid a loop on the selection of MODULE_ZTIMER_PERIPH_TIMER, this also moves its selection from MODULE_ZTIMER_USEC to the visible symbol ZTIMER_USEC.

### Testing procedure
- Green CI
- Check that the behaviour matches the one in `Makefile.dep`.

### Issues/PRs references
#17235

### CODE REVIEW

**Review by fjmolinas — APPROVED** [review]
ACK

**Comment by leandrolanzieri** [comment]
#17317 is merged, it needs probably an update

**Comment by leandrolanzieri** [comment]
There, updated the `select` of the benchmark module

**Comment by fjmolinas** [comment]
ACK still stands

**Comment by leandrolanzieri** [comment]
Thanks for reviewing!

**Pull request merged**
