### PR TITLE
tests: ignore infinite recursion for mpu_stack_test with clang

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
One of the many errors #9398 revealed. I don't intend to fix all of them, but this one was a simple one to snipe ;-)

### Issues/PRs references
None

### CODE REVIEW

**Comment by cladmi** [comment]
GCC complains about the `clang` pragma…

Another solution is to only enable it if llvm is used. This can be done after `include Makefile.include` as before TOOLCHAIN may not have the correct value

``` diff
diff --git a/tests/mpu_stack_guard/Makefile b/tests/mpu_stack_guard/Makefile
index 9732d19..d45349e 100644
--- a/tests/mpu_stack_guard/Makefile
+++ b/tests/mpu_stack_guard/Makefile
@@ -42,3 +42,7 @@ BOARD_WHITELIST += udoo             # cortex-m3
 USEMODULE += mpu_stack_guard
 
 include $(RIOTBASE)/Makefile.include
+
+ifeq (llvm,$(TOOLCHAIN))
+  CFLAGS += -Wno-infinite-recursion
+endif
```

**Comment by kaspar030** [comment]
> GCC complains about the clang pragma…

easy snipe, eh? ;)

**Comment by miri64** [comment]
>> GCC complains about the clang pragma…
>
> easy snipe, eh? ;)

My GCC took it without complaining ¯\\\_(ツ)\_/¯

**Comment by cladmi** [comment]
Works on my GCC now.

    make BOARD=samr21-xpro TOOLCHAIN=llvm clean all
    make BOARD=samr21-xpro TOOLCHAIN=clang clean all  # This correctly replaced by llvm and handled
    make BOARD=samr21-xpro TOOLCHAIN=gcc clean all

**Comment by cladmi** [comment]
Please squash

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
Next one ;-) #9603

**Comment by miri64** [comment]
Backport btw?

**Comment by miri64** [comment]
backport available in #9610

**Pull request merged**
