### PR TITLE
sema: pre-set timeout-timer for sema_wait_timed_msg()

### PR DESCRIPTION
**Pull request by authmillenon**
Work-around to prevent weird errors from happening due to #4372.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Shouldn't this be fixed in xtimer instead?

**Comment by authmillenon** [comment]
I don't know how :(

**Comment by authmillenon** [comment]
In the long-run it is more correct to set this values anyway, I guess.

**Comment by josephnoir** [comment]
Initialization sounds like a good idea. The style guid doesn't say anything about [multiple assignments in one line](https://github.com/RIOT-OS/RIOT/pull/4374/files#diff-4af11e61eb26bcdd3eed69b819563f52R78), is that generally accepted?

**Comment by authmillenon** [comment]
If it doesn't say anything then it is accepted, I guess.

**Comment by OlegHahm** [comment]
:+1: for initialization, but xtimer should be fixed anyway.

**Comment by authmillenon** [comment]
@OlegHahm I'm not sure this CAN be fixed. For all I now, these values might be legally set by some previous `msg_set_*()` to the timer.

**Comment by josephnoir** [comment]
:+1: Looks straight forward. Can't say anything about the xtimer stuff.

**Pull request merged**
