### PR TITLE
Sys beaconing doxy 1

### PR DESCRIPTION
**Pull request by kausthub**
i couldnt do a squash , so i have created this new PR . My old PR is #2561 
Please review it 
thanks

### CODE REVIEW

**Comment by OlegHahm** [comment]
Sorry, but I think you need to learn how to rebase and how to squash, but don't worry it isn't that complicated and we're here to help. (Plus, there's a lot of documentation about Git.)

**Comment by PeterKietzmann** [comment]
@kausthub what exactly prevented you from squashing? Did you read [How to squash commits](https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet)? If you could describe you problems a bit more detailed it would be easier to help you. Cheers

**Comment by PeterKietzmann** [comment]
@kausthub any progress here?

**Comment by kausthub** [comment]
But the other Pr is closed so do I squash and post it in this Pr ? When I
did the merging I found I followed all the steps and still I just got a new
commit but it didn't squash any of the rest of the commits ! Also in the
rebase command I didn't get any commit to choose from ? Like the one showed
in the tutorials ! Please help
Thanks I will revert back quickly and finish this by today !
Thanks for helping

Regards
Kausthub Naarayan
mob : 9535264688

**Comment by BytesGalore** [comment]
Hi @kausthub, it seems you have comitted and pushed things to your own _master_.
If you look in your commit history of your _master_ [1], you will find 3 commits ontop of the merged commit #2693 of Martine from Mar 23, 2015.
The problem is now, anytime you create a new branch, e.g. 
`git checkout -b my_cool_feature_branch`,
it is based on your "mixed" _master_, which cannot be synced with the _RIOT master_.

But don't worry this can be fixed :) .

The first thing what we need to achieve is to have your master in sync with the _RIOT master_.
I suggest that you want to keep the three commits so you should create a clean branch from your current _master_, e.g.:
```
git checkout master
git checkout -b keep_my_commits
```
and switch back to your master branch.
`git checkout master`
_This way you have a backup of the 3 commits in the new branch._

Now lets start repair your _master_.

- Checkout the last synced commit. 
If you type `git log` you will be presented with all commits in your current _master_, where the 3 upper ones should be your commits.
Now we reset your _master_ to the last synced commit from Martine using the commit hash, i.e.:
```
`git reset --hard 3fa96e5eb990b575126a291447352a37b18e968b`
```
If you type `git log` now it should show Martine's commit at first position.
- If this is the case, force push your _master_ to git by entering **`git push -f`** 
When you now have a look in [1], and refresh the view, your 3 commits are gone, but still in your **local** branch `keep_my_commits`. 
_Keep in mind to push the `keep_my_commits` branch to your repo if you want to keep the commits._

- At this point, with a clean but aged _master_, you should first proceed applying [2] to sync your _master_ with the _RIOT master_.

- Now that yo are synced with _RIOT master_ again, you can start to squash commits in your brnach following [3]. 

I hope this helps a bit :)

[1] https://github.com/kausthub/RIOT/commits/master
[2] https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet#how-to-rebase-your-master-on-a-current-riot-master
[3] https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet#how-to-squash-commits

**Comment by gebart** [comment]
@kausthub This is a good improvement, but it needs to be cleaned up before we can merge it. Can you try to rebase onto the latest master and squash your commits into one?

**Comment by gebart** [comment]
this module was dropped

**Pull request closed without merging**
