### PR TITLE
sys/net/dhcpv6: include IA Prefix Option in SOLICIT

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

I was always wondering why I would get a /62 from my DHCPv6 server when `dhcpv6_client_req_ia_pd()` is called with a prefix length of 64.
Turns out that prefix length was never included in the request.

This is a problem as e.g. Linux clients [do not accept](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/addrconf.c#n2790) router advertisements for SLAAC if the prefix length != 64.

Add the IA Prefix Option when soliciting a prefix so we can tell the server what prefix length we want.

### Testing procedure

Can be tested on `native` with your local DHCPv6 server: 

 - create TAP bridge with LAN

       sudo dist/tools/tapsetup/tapsetup -u eno1
 - run `gnrc_border_router`

       make -C examples/gnrc_border_router REUSE_TAP=1 all term

The DHCPv6 server now returns a prefix with the requested length

```
DHCPv6 client: send SOLICIT
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: scheduling RENEW in 1800 sec
DHCPv6 client: scheduling REBIND in 2880 sec

> nib prefix
2001:9e8:1425:e00::/64 dev #6  expires 7195 sec deprecates 3595 sec
2001:9e8:1425:efb::/64 dev #7  expires 7197 sec deprecates 3597 sec
```

### CODE REVIEW

**Comment by benpicco** [comment]
I added two more small quality of life improvements.
I can move them to a separate PR if needed, but only minor cleanups, so might as well include them here.

**Comment by fabian18** [comment]
I have not read [RFC 8415](https://www.rfc-editor.org/rfc/rfc8415.html), but I seeked for "Prefix Option" within it.

For the record:
> The client MAY include values in IA Prefix options (see
   [Section 21.22](https://www.rfc-editor.org/rfc/rfc8415.html#section-21.22)) encapsulated within IA_PD options as hints for the
   delegated prefix and/or prefix length for which the client has a
   preference.  See [Section 18.2.4](https://www.rfc-editor.org/rfc/rfc8415.html#section-18.2.4) for more on prefix-length hints.

>    The client MAY include an IA option for each binding it desires but
   has been unable to obtain.  In this case, if the client includes the
   IA_PD option to request prefix delegation, the client MAY include the
   IA Prefix option encapsulated within the IA_PD option, with the
   "IPv6-prefix" field set to 0 and the "prefix-length" field set to the
   desired length of the prefix to be delegated.

The IA Prefix Option belongs in the [IA Prefix Delegation Option](https://www.rfc-editor.org/rfc/rfc8415.html#section-21.21). It is not a separate option apparently.

> The client SHOULD NOT send an IA Prefix option with 0 in the
   "prefix-length" field (and an unspecified value (::) in the
   "IPv6-prefix" field).  A client MAY send a non-zero value in the
   "prefix-length" field and the unspecified value (::) in the
   "IPv6-prefix" field to indicate a preference for the size of the
   prefix to be delegated.  See [[RFC8168](https://www.rfc-editor.org/rfc/rfc8168)] for further details on prefix-
   length hints.

Prefix length should be 0 and prefix should be `::`.
Our client seems to put it into a `Solicit` and `Request` message.
In the `Solicit` message the prefix is correctly `::` but in the Request message it seems to be uninitialized.
The server replies correctly with the Prefix Option inside the Prefix Delegation option.
See the two wireshark captures: [dhcpv6_.zip](https://github.com/RIOT-OS/RIOT/files/10557695/dhcpv6_.zip)

**Comment by benpicco** [comment]
Good catch, we actually have to zero out the prefix.

**Comment by benpicco** [comment]
I think there is no need to move memory around, let's keep things simple and move the sub-option generation into the function the generates the option.

**Review by fabian18 — APPROVED** [review]
Ok, it works fine. Please squash

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
