### PR TITLE
macros/utils: add LIMIT() and ABS() macros

### PR DESCRIPTION
**Pull request by Enoch247**
### Contribution description

This patch adds a macro that can be used to limit a value to a given range. It also adds the classic `ABS()` macro to go along with the existing `MAX()` and `MIN()` macros.

### Testing procedure

It's fairly trivial. I have used it and it works in my application code.

### Issues/PRs references

- none known

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
If you use the same definition as ESP32, would it still be a redefinition? :thinking:

**Comment by Enoch247** [comment]
> If you use the same definition as ESP32, would it still be a redefinition? 🤔

I tested the following and did not get an error or warning:

``` c
#define FOO 1
#define FOO 1
```
I don't know if that is promised by the language or just allowed by gcc. Do you know off the top of your head before I go looking? It does feel a bit precarious thought to rely on matching a macro defined outside the source tree.

I though about moving it to macros/math.h and calling it `MATH_LIMIT()`. That would require including utils.h in math.h. In my opinion `MAX()` and `MIN()`should be moved to math.h, but I think that change would affect a lot of people.

**Comment by benpicco** [comment]
If it works on CI you can be sure that all supported compilers are covered.

**Comment by Enoch247** [comment]
Ok, I made the change.

Also I added the classic `ABS` macro to go with `MAX`/`MIN`.

**Comment by benpicco** [comment]
Please squash!

**Comment by Enoch247** [comment]
squashed

**Comment by Enoch247** [comment]
Please wait to merge. I will added unit tests for these macros.

**Comment by Enoch247** [comment]
Ok, unit tests are added now for new and some existing macros.

**Pull request merged**
