### PR TITLE
samr21/RTC

### PR DESCRIPTION
**Pull request by bapclenet**
Solve issue #2261 by using the external 32,768KHz Oscillator

### CODE REVIEW

**Comment by bapclenet** [comment]
@thomaseichinger, I let you try the RTC with the default example.

**Comment by PeterKietzmann** [comment]
@bapclenet I didn't really follow this topic but I think I could test and review in general. To simplify the whole thin a bit for me: Can you explain how to test this and what should be seen before and after using this PR?

**Comment by RIOT-notifier** [comment]
Use the default example with module rtc.
Run it, get the time at the beggining, get it one hour later and see if RTC
say one hour or less.
The problem was that RTC was going slower than it should be.
You should see the improvment with the PR. ( one hour on your laptop will
be one hour on the SAMR21)

**Comment by bapclenet** [comment]
@PeterKietzmann , the RIOT-notifier was me btw :-)

**Comment by PeterKietzmann** [comment]
Hm, this is what I get without this PR:
```
2015-04-09 20:50:02,523 - INFO # > rtc gettime
2015-04-09 20:50:02,524 - INFO # 
2015-04-09 20:50:02,561 - INFO # 2000-01-01 00:00:46
rtc gettime
2015-04-09 21:50:13,766 - INFO # > rtc gettime
2015-04-09 21:50:13,766 - INFO # 
2015-04-09 21:50:13,804 - INFO # 2000-01-01 01:00:40
```
Looks ok to me. Will try with `settime` before and with with you PR later/tomorrow

**Comment by PeterKietzmann** [comment]
With `settime` it looks similar, surprise :-)
```
2015-04-09 21:54:48,981 - INFO # > rtc settime 2015-04-09 21:55:00
2015-04-09 21:54:48,981 - INFO # 
rtc gettime
2015-04-09 22:50:09,574 - INFO # > rtc gettime
2015-04-09 22:50:09,575 - INFO # 
2015-04-09 22:50:09,613 - INFO # 2015-04-09 22:50:04
```

**Comment by PeterKietzmann** [comment]
__With__ your changes I also get reasonable results:
```
2015-04-09 22:55:25,783 - INFO # > rtc gettime
2015-04-09 22:55:25,783 - INFO # 
2015-04-09 22:55:25,820 - INFO # 2000-01-01 00:00:03
rtc gettime
2015-04-09 23:53:06,181 - INFO # > rtc gettime
2015-04-09 23:53:06,182 - INFO # 
2015-04-09 23:53:06,219 - INFO # 2000-01-01 00:57:43
```
Any ideas why all tests seem to succeed? Am I doing something wrong?

**Comment by bapclenet** [comment]
Without : 
Computer         Samr21
1 : 00 : 11       0 : 59 : 54


With : 
0 : 57 : 41       0 : 57 : 40
One sec is just a matter of when you get the time(beggining or end of the sec)

Sor for me, 17sec in one hour is not acceptable sonce the device could work for a year :-) 
0 sec is better

**Comment by bapclenet** [comment]
Great!

**Pull request merged**
