### PR TITLE
core/include/init.h: a new initialization concept

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR introduces another initialization concept for core, subsystems and drivers.

Currently the RIOT will be initialized somehow like:

```
reset_isr
 |-------------- board_init
 |                    |--------------------- leds_init
 |                    L--------------------- cpu_init
 |
 |-------------- __libc_init_array
 |                    L--------------------- _init
 |                                              L-------------- uart_stdio_init
 |
 L-------------- kernel_init
                      L---------------------- idle
                      L---------------------- main_trampoline
                                                |-------------- auto_init
                                                L-------------- main
```

This PR uses macros to make sorted function pointers and place it in a particular area. The macros are sorted by the linker. After the reset, the assorted functions are called in a defined order.
Currently the loop inside __libc_init_array will be used to call the functions. Of course we can move the loop to reset_isr. Advantage is that the drivers and subsystems can initialize itself in defined order. You do not need to change/complete auto_init if you will add new driver or subsystem.

With this PR the RIOT can be initialized somehow like:

```
reset_isr
 |--------------------- leds_init
 |--------------------- cpu_init
 |--------------------- core (logging, scheduler, idle ?)
 |--------------------- drivers (register drivers)
 |--------------------- uart_stdio_init
 |--------------------- subsystem
 |--------------------- system (networking, usbdev stack)
 |--------------------- auto_init
 L--------------------- main_trampoline
                               L--------------------- main

```

This PR is WIP and works only on ARMs. I need help to get it adapted for MSP430 and AVR.

Well then, what do you think about it?

### CODE REVIEW

**Comment by kaspar030** [comment]
interesting.

some thoughts & questions:
- we've been avoiding linker magic so far. have to rediscuss this.
- we're executing all auto_init within main's stack in order to keep the ISR stack minimal. guess that could be easily changed.

- why differentiate core, module, submodule?
- how do you realize conditional auto_init (if defined (A) && defined (B) auto_init (C) endif)?


> This PR is WIP and works only on ARMs. I need help to get it adapted for MSP430 and AVR.

One of the reasons we're still managing auto_init.c by hand...

**Comment by Kijewski** [comment]
I think auto_init has to be done in the main thread because it might spawn threads. I think there was a problem once upon a time when auto_init was invoked in the start-up sequece before the threading was started.

**Comment by haukepetersen** [comment]
Though I think this approach is quite elegant for cortex based platforms, I am still very skeptical about linker section based approaches that have to be followed/implemented by all platforms. Especially for MSP430 and AVR8 we are (as the standard toolchains dictate this) using supplied linker scripts, which we can't easily edit. So making this approach work for all RIOT supported platforms would mean that we get this PR to work even with those untouched linkerscripts. So I guess the next step needs to be showing that this concept here will also work for those platforms.

**Comment by jfischer-phytec-iot** [comment]
Should work out of the box for msp430 and AVR8, not have hardware for testing yet, but:

objdump -t bin/arduino-mega2560/init_test.elf
```
00800496 l     O .preinit_array.2.submod        00000002 __initcall_submod_init_test2
00800498 l     O .preinit_array.3.module        00000002 __initcall_module_init_test3
0080049a l     O .preinit_array.1.driver        00000002 __initcall_driver_init_test1
0080049c l     O .preinit_array.0.core  00000002 __initcall_core_init_test0
```
objdump -t bin/msb-430/init_test.elf
```
00000200 l     O .preinit_array.2.submod        00000002 __initcall_submod_init_test2
00000202 l     O .preinit_array.3.module        00000002 __initcall_module_init_test3
00000204 l     O .preinit_array.1.driver        00000002 __initcall_driver_init_test1
00000206 l     O .preinit_array.0.core  00000002 __initcall_core_init_test0
```

**Comment by jfischer-phytec-iot** [comment]
Someone who has the hardware, MSP430 and Arduino (AVR), please can you test it for me?

**Comment by kaspar030** [comment]
both show this:

```
2016-01-27 23:33:22,807 - INFO # init_pattern: 0x00000000
```

**Comment by kaspar030** [comment]
@jfischer-phytec-iot: the functions should be called by the c library's constructor, right? are we sure those little libc's even have those?

**Comment by jfischer-phytec-iot** [comment]
@kaspar030 
>are we sure those little libc's even have those?

No, that's why I want to implement the init loop (current it uses one in the newlib)  as an autoinit function (riots auto init). WIP. I try to organize the hardware.

**Comment by kaspar030** [comment]
@jfischer-phytec-iot let's generalize this (see #4290).

Can we make the interface something like

``` INIT(group, size, priority) ```

with group being autoinit, netdev, saul, ... (different handlers...), and a size field so that structs can be put in there?

**Comment by PeterKietzmann** [comment]
Will the milestone change to over next release

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by OlegHahm** [comment]
Let's remove the milestone until @jfischer-phytec-iot indicates that he has time to work on this again (or someone else picks it up).

**Comment by OlegHahm** [comment]
[Development Procedures](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures) no. 10: "Closing an issue or pull request must always be accompanied by a comment indicating why it gets closed."

**Comment by jfischer-phytec-iot** [comment]
Also here, sorry, excessive cleansing.

**Pull request closed without merging**
