### PR TITLE
lwip: bump to version v2.1.2

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
[New lwIP version](https://savannah.nongnu.org/forum/forum.php?forum_id=9299). ~~Still WIP, since there seems to be a new problem with TCP reception (both in the sock tests and `tests/lwip` when disconnecting)~~.

### Testing procedure
Run and use the `tests/lwip*` applications on various boards. Don't forget to use `LWIP_IPV4` and `LWIP_IPV6` in various settings with the `tests/lwip_sock_*` applications.

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
Note to self: problem is caused by assert in http://git.savannah.nongnu.org/cgit/lwip.git/commit/?id=ebb0dc14a7336c793d32c8e9ebde5bd9666f2a65.

**Comment by miri64** [comment]
Bug was fixed upstream. However, due to that bug they plan to release 2.1.2 soon, so we can merge this or wait for 2.1.2.

**Comment by miri64** [comment]
Updated to current v2.1.2 release candidate.

**Comment by bergzand** [comment]
Tested with
 - `tests/lwip_sock_ip`
 - `tests/lwip_sock_udp`
 - `tests/lwip_sock_tcp`

Each once with `LWIP_IPV4=1`, `LWIP_IPV6=1` and `LWIP_IPV4=1 LWIP_IPV6=1`.

**Comment by bergzand** [comment]
Please squash

**Comment by miri64** [comment]
No wait! This just points to to an RC right now (see https://github.com/RIOT-OS/RIOT/pull/10361#issuecomment-438387571). Please let's wait until the actual release is out!

**Comment by bergzand** [comment]
> No wait! This just points to to an RC right now (see [#10361 (comment)](https://github.com/RIOT-OS/RIOT/pull/10361#issuecomment-438387571)). Please let's wait until the actual release is out!

Whoops! added the WIP tag for now.

**Comment by miri64** [comment]
(you should also test `tests/lwip` on native and samr21-xpro (or some other supported device)

1) the issues in v2.1.1 showed up there first (e. g. crash on `tcp disconnected`)
2) you also test the 6LoWPAN implementation.

**Comment by bergzand** [comment]
> (you should also test `tests/lwip` on native and samr21-xpro (or some other supported device)

Forgot to mention that I ran the tests described above on a samr21-xpro on the IoT-lab. Also ran `tests/lwip` on two samr21-xpro and was able to do UDP client/server stuff.

**Comment by miri64** [comment]
(also do TCP stuff! ;-))

**Comment by bergzand** [comment]
> (also do TCP stuff! ;-))

Okay okay :)

**Comment by miri64** [comment]
Bumped to (and tested) next RC.

**Comment by miri64** [comment]
Moved to final v2.1.2 version and squashed.

**Comment by miri64** [comment]
Ping @bergzand?

**Comment by cladmi** [comment]
Just found out that, I think, the commit message references a wrong issue number:

`tcp.c: Update prev pointer when skipping entries in tcp_slowtmr` (patch #9694)

**Comment by miri64** [comment]
I'm not sure it's worth to put a note into the commit message to reflect this. In this case its just a weird quirk of GitHub.

**Comment by cladmi** [comment]
> @cladmi this is just a copy of the lwIP change log. So it is referring to their bug tracker ;)

There is a note here now, so it should be enough if somebody asks. I was just surprised at first when I visited the given issue page that it was reference by this one :)

**Comment by cladmi** [comment]
I ran all automated tests with `iotlab-m3` on all 3 configurations, and for fun, using `TOOLCHAIN=llvm`:

```
# /bin/bash

export TOOLCHAIN=llvm
export IOTLAB_NODE=auto-ssh
export BOARD=iotlab-m3

for application in tests/lwip_sock_tcp tests/lwip_sock_udp tests/lwip_sock_ip
do
    for config in "LWIP_IPV4=1" "LWIP_IPV6=1" "LWIP_IPV4=1 LWIP_IPV6=1"
    do
        echo ${application} ${config}
        make -C ${application} ${config} distclean all flash test || break
    done
done
```

**Comment by cladmi** [comment]
I cannot run `tcp server stop` it tells me `error: invalid command`.
Otherwise I can exchange tcp messages:

I used `iotlab-m3` compiled with `llvm`.

I tested:

Server:

```
> ifconfig
ifconfig
L6_00:  inet6 fe80::1711:6b10:65fb:aa32

> tcp server start 666
tcp server start 666
Success: started TCP server on port 666
```

Client:

```
> tcp connect fe80::1711:6b10:65fb:aa32 666
tcp connect fe80::1711:6b10:65fb:aa32 666

> tcp send cafecafecafe
tcp send cafecafecafe
Success: send 6 byte over TCP to server
> tcp disconnect
tcp disconnect
```

Server:

```
> TCP client [fe80::1711:6b10:65fc:5e36]:49153 connected
Received TCP data from client [fe80::1711:6b10:65fc:5e36]:49153:
00000000  CA  FE  CA  FE  CA  FE

> tcp server stop
tcp server stop
error: invalid command

# Client disconnects here
> TCP connection to [fe80::1711:6b10:65fc:5e36]:49153 reset, starting to accept again

tcp server stop
tcp server stop
error: invalid command
> 
```

**Comment by cladmi** [comment]
Test with `udp`:

Same issue, `udp server stop` says `invalid command`.

I can correctly send udp messages:

Server:

```
> udp server start 666 
udp server start 666
Success: started UDP server on port 666
```
Client
```
> udp send fe80::1711:6b10:65fb:aa32 666 cafecafecafecafe
udp send fe80::1711:6b10:65fb:aa32 666 cafecafecafecafe
Success: send 8 byte over UDP to [fe80::1711:6b10:65fb:aa32]:666
```

Server
```
> Received UDP data from [fe80::1711:6b10:65fc:5e36]:49153:
00000000  CA  FE  CA  FE  CA  FE  CA  FE
> udp server stop
udp server stop
error: invalid command
```

**Comment by miri64** [comment]
> I cannot run `tcp server stop` it tells me `error: invalid command`.

Apparently, it was never implemented

https://github.com/RIOT-OS/RIOT/blob/77c9cc4041d495120b175fb2089d07d4b15e60d6/tests/lwip/tcp.c#L198-L213

Those lines are from the introduction of this file. Don't know why `stop` is documented though, probably propagated copy-pasta from the `gnrc_netapi` based implementation for UDP in `gnrc_networking`.

**Comment by miri64** [comment]
> Same issue, `udp server stop` says `invalid command`.

Same defence:

https://github.com/RIOT-OS/RIOT/blob/77c9cc4041d495120b175fb2089d07d4b15e60d6/tests/lwip/udp.c#L144-L160

**Comment by cladmi** [comment]
@miri64 I am asked to test, I test what I see :D 
It does not change for this PR indeed as was never implemented.

I could run the same test with `native` too with `udp` and `tcp`. Did not test `ip` as I do not know what to test.

**Comment by cladmi** [comment]
So for me, the tests I ran where OK, is there anything else to test ?
Like the things done in the ReleaseSpecs ?

**Comment by miri64** [comment]
> @miri64 I am asked to test, I test what I see :D
> It does not change for this PR indeed as was never implemented.

I understood it more as a remark to change it in a separate PR (but maybe not now while I have 41 open PRs ^^).

> I could run the same test with `native` too with `udp` and `tcp`. Did not test `ip` as I do not know what to test.

Might be good, since Ethernet on `native` runs through a completely different code-path.

`ip` works as `udp` with the difference that you use a [protocol number](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml) instead of a port to open the server and provide to the `send` command. I recommend using one of the experimental ones because I don't know if and when certain protocol numbers are consumed by the stack.

**Comment by miri64** [comment]
> So for me, the tests I ran where OK, is there anything else to test ?
> Like the things done in the ReleaseSpecs ?

Not required, but desirable (so we don't run into issues during the release tests ;-))

**Comment by cladmi** [comment]
I tried to do the message exchange from releasespecs and I did not receive the message on `lwip` but I may be using a different channel. Do you know which channel is used for `lwip` by default ?

**Comment by miri64** [comment]
Mh... maybe @bergzand's refactoring efforts destroyed something in the channel config. Let me check (it should be the same as with GNRC)

**Comment by cladmi** [comment]
My bad, it is received now, maybe I put the wrong ip, or port, or just a random non receive. 
I finish the interop tests and finish feedback.

**Comment by miri64** [comment]
> My bad, it is received now, maybe I put the wrong ip, or port, or just a random non receive.
I finish the interop tests and finish feedback.

Ok. Just wanted to report, that the channel is not configured stack-side (yet) but comes from the device. So the channels should indeed be the same still.

**Comment by cladmi** [comment]
The `ip` exchange also worked when using `253` as protocol`.

I could exchange UDP messages (both directions) between `lwip` and `gnrc_networking` with `iotlab-m3` compiled with `llvm`. I sent 8bytes messages. Same test commands as before.

When I said `I could run with native` I meant it worked, so it is also tested.

So for me the tests are all ok.

**Comment by miri64** [comment]
Thank you for testing and merging :-) (though I don't expect any issues a rebuild against current master might have been adviced)

**Comment by cladmi** [comment]
Hmm, I indeed tested this PR version and not the rebase with master…

**Pull request merged**
