### PR TITLE
pkg/qcbor: Add QCBOR package

### PR DESCRIPTION
**Pull request by aydoganersoz**

### CODE REVIEW

**Comment by benpicco** [comment]
Thank you for adding the pkg.
Please also provide a test application in `tests/` so the package can be compile-tested by CI.

**Comment by benpicco** [comment]
I think you want to run `git rebase master`.

**Comment by aydoganersoz** [comment]
Yes sorry I made a mistake by pushing the code. It's not yet complete. I'll take care of the rebase once I finish. Thanks for the feedback though.

**Comment by aydoganersoz** [comment]
Yes sorry I made a mistake by pushing the code. It's not yet complete. I'll take care of the rebase once I finish. Thanks for the feedback though.

**Comment by aydoganersoz** [comment]
I think it should be fine now:
 - unit tests have been added
 - rebase has been performed

**Comment by benpicco** [comment]
There are still plenty of unrelated commits in this branch

**Comment by aydoganersoz** [comment]
Yep, you are right :/

Should I perform an interactive rebase for 417 commits in which I should squash except the first line?

**Comment by benpicco** [comment]
In your branch, run

 - `git checkout HEAD^` to get rid of the merge commit
 - `git rebase master` to do the rebase.

**Comment by aydoganersoz** [comment]
> In your branch, run
> 
>     * `git checkout HEAD^` to get rid of the merge commit
> 
>     * `git rebase master` to do the rebase.

My branch gets detached after performing these two commands.

**Comment by benpicco** [comment]
Yea but at that point you can just create a new branch with `git branch`.

Since this is only one commit you could even just create a new branch off master and do

    curl https://github.com/RIOT-OS/RIOT/commit/e126b3a1b52796428934bd2f94f0b657f15af20e.patch | git am

**Pull request closed without merging**
