### PR TITLE
uncrustify: ignore parens on return

### PR DESCRIPTION
**Pull request by authmillenon**
See https://github.com/RIOT-OS/RIOT/pull/4475#discussion_r47655743

### CODE REVIEW

**Comment by Kijewski** [comment]
Against.

**Comment by OlegHahm** [comment]
Why?

**Comment by kaspar030** [comment]
Shouldn't we either go for "add" or "remove"?

**Comment by authmillenon** [comment]
Then stuff like 

```C
return (1);
```

Will pop-up, too.

**Comment by DipSwitch** [comment]
For what it's worth: I would prefer to use ignore over add or remove, for me the ( helps to inform the reader that it's not just a value return, but contain an expression of some kind. Although I just realized that it might be a bit cryptic... xD

**Comment by authmillenon** [comment]
Any consensus?

**Comment by cgundogan** [comment]
I am also for `ignore` here for the same reason @DipSwitch stated above. @Kijewski do you still NACK?

**Comment by gebart** [comment]
I agree with @cgundogan and @DipSwitch, I have the same reasoning as @DipSwitch regarding expression vs. simple value return.

**Comment by haukepetersen** [comment]
+1 for 'ignore'

**Comment by cgundogan** [comment]
and GO

**Pull request merged**
