### PR TITLE
drivers/sx127x: return correct state when device is receiving

### PR DESCRIPTION
**Pull request by Icaltary**
### Contribution description
This PR adds the NETOPT_STATE_RX to the possible results of reading NETOPT_STATE. When the state is requested, the device mode ('RegOpMode' -> 'Mode') is read. If this is 'RXSINGLE' or 'RXCONTINUOUS', the device is currently receiving data or waiting for the preamble. To distinguish both cases, the 'Signal detected' bit in the 'ModemStatus' register is checked. If this is set, a transmission is ongoing so NETOPT_STATE_RX is returned, otherwise the radio is waiting and NETOPT_STATE_IDLE is returned.

Instead of the 'Signal detected' bit, we could also use a different one. The status bits are set in the following order:
'RX on-going'  (This is always set while the radio is in listen mode / waiting for packets)
'Signal detected' (preamble detected)
'Signal synchronized' (after the preamble)
'Header info valid' (This is set when a header with a valid CRC has been received)

The names in this description refer to the register map from the sx127x datasheet:
https://www.semtech.com/uploads/documents/sx1276.pdf (Chapter 6.4)

### Issues/PRs references
None

### CODE REVIEW

**Comment by aabadie** [comment]
Thanks for your contribution. I had a brief look and it makes sense. I'll make a more in-depth review soon (looking at the datasheet and comparing with Semtech code)

**Comment by PeterKietzmann** [comment]
@jia200x you are using that device rather often. Mind to give it a shot?

**Comment by jia200x** [comment]
@PeterKietzmann sure! I will

**Comment by jia200x** [comment]
hi @Icaltary 

The proposed change makes sense to me. I will test it with the RIOT's LoRaWAN pkg and report the results

**Comment by jia200x** [comment]
I tested this PR with the latest state of LoRaWAN and works as expected. Also, I checked the registers in the SX127x datasheet and they seem to be correct.

Im OK with this PR.

**Comment by PeterKietzmann** [comment]
@jia200x then why don't you ACK-approve and merge it :)?

**Comment by jia200x** [comment]
@PeterKietzmann sure! I will ;)

**Comment by jia200x** [comment]
let's wait Murdock

**Comment by miri64** [comment]
Murdock has problems collecting and finishing jobs again -.-

**Comment by cladmi** [comment]
Is it an enhancement or a bug fix that could make test fail ? to know if it should be backported to the release.

**Comment by cladmi** [comment]
Ok so it would prefer not backporting it.

**Pull request merged**
