### PR TITLE
lwm2m: adding client example

### PR DESCRIPTION
**Pull request by Darredevil**
Adding example of a client. At the moment it supports only basic commands.

### CODE REVIEW

**Comment by authmillenon** [comment]
@Darredevil ping me if the PR is out of WIP.

**Comment by Darredevil** [comment]
@authmillenon I will :D

**Comment by authmillenon** [comment]
Sorry @Darredevil, I forgot. Is this the PR I wanted to review this week or was someone else faster?

**Comment by Darredevil** [comment]
@authmillenon Np, yes this was the PR.

**Comment by authmillenon** [comment]
Set "Ready for CI build" label to see if everything is in order compile-wise. Remove at will if Travis can't handle it.

**Comment by authmillenon** [comment]
Needs rebase.

**Comment by Darredevil** [comment]
@authmillenon Rebased.
Sorry for the late follow up :D.

**Comment by markbul** [comment]
Hello, I'm a newbie, I hope some kind people will have the time to reply to me, because I'm not able to go on without help. I'm trying to run the client and the server. Since it doesn't work for me, I have some questions:
1) I followed all the istructions in the readme, but, in the command "ifconfig <if> add 2001:db8::2/64" I assume that I have to substitute <if> with something, what do I have to put there? 
2)The last instruction "lm init <name> 2001:db8::1 <port>" How can I know the client name? Where is it defined? And which is the server port I have to put? When I start the server I have this:
Feb 22, 2016 7:41:21 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at /2001:db8:0:0:0:0:0:1:4242
Feb 22, 2016 7:41:21 PM org.eclipse.californium.core.network.CoAPEndpoint start
INFO: Starting endpoint at 0.0.0.0/0.0.0.0:5684
why are defined two different endpoints for the server?

I really thank you, and I'm sorry for the dumb questions

**Comment by OlegHahm** [comment]
closed as memo

**Pull request closed without merging**
