### PR TITLE
dist/testbed-support: make experiment name configurable

### PR DESCRIPTION
**Pull request by cgundogan**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Actually, I left this unconfigurable on purpose. This way IoT-LAB maintainer can easily check how many people are using this feature.

**Comment by cgundogan** [comment]
I see.. I have no strong opinion regarding this matter though. But restricting the name to `riot_makefile_experiment` makes it less comprehensible when looking at the experiments table in the IoT-Lab front-end. Having the `name` column more descriptive is very supporting if I return to the front-end several weeks later in order to check, which experiments I conducted.

Do you think it is possible to agree on something like `"[riot-os] name"` where `name` is configurable?

**Comment by OlegHahm** [comment]
Sounds like a good compromise.

**Comment by cgundogan** [comment]
@OlegHahm the second commit prefixes the name with `RIOT_` if it is different from `RIOT`. Otherwise the name will stay `RIOT`. It's not possible to use brackets.

**Comment by OlegHahm** [comment]
Hm, maybe that's a bit too ambiguous. Maybe `RIOT_EXP_`?

**Comment by cgundogan** [comment]
@OlegHahm `RIOT_EXP` it is.

**Comment by cgundogan** [comment]
@OlegHahm is it necessary to communicate this to any testbed maintainer?

**Comment by cgundogan** [comment]
squashed

**Comment by OlegHahm** [comment]
I will just mention @cladmi here, so he gets notified about this change. ;)

**Comment by OlegHahm** [comment]
ACK

**Comment by OlegHahm** [comment]
Please rebase and merge.

**Comment by cgundogan** [comment]
rebased and GO.

**Comment by cladmi** [comment]
ACK

**Pull request merged**
