### PR TITLE
pkg/ccn-lite: bump version

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title says.

### Testing procedure

Green murdock.

### Issues/PRs references

Needed for https://github.com/RIOT-OS/RIOT/pull/14702

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
CI is happy and only few changes since the last snapshot

**Comment by miri64** [comment]
> Green murdock.

*from vacation off* Could you at least test if `examples/ccn-lite-relay` still works on `native` :sweat_smile:

**Comment by miri64** [comment]
Works when compiled on Ubuntu 20.04. On Arch Linux I get `Floating point exception (core dumped)` when trying to create a content but that is also the case on `master` (even when building in Docker).

<details>

```
/home/mlenders/Repositories/RIOT-OS/RIOT/examples/ccn-lite-relay/bin/native/ccn-lite-relay.elf tap0
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: buildtest)
Basic CCN-Lite example
> ccnl_cs /test "Hello world"
ccnl_cs /test "Hello world"
> ccnl_cs
ccnl_cs
CS[0]: /test [-1]: Hello world
> ifconfig
ifconfig
Iface  4  HWaddr: 96:8B:D4:CD:3B:45
          L2-PDU:1500  Source address length: 6

>
```

```
/home/mlenders/Repositories/RIOT-OS/RIOT/examples/ccn-lite-relay/bin/native/ccn-lite-relay.elf tap1
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: buildtest)
Basic CCN-Lite example
> ccnl_fib /test  96:8B:D4:CD:3B:45
ccnl_fib /test  96:8B:D4:CD:3B:45
usage: ccnl_fib [<action> <options>]
prints the FIB if called without parameters:
% ccnl_fib
<action> may be one of the following
  * "add" - adds an entry to the FIB, requires a prefix and a next-hop address, e.g.
            ccnl_fib add /riot/peter/schmerzl ab:cd:ef:01:23:45:67:89
  * "del" - deletes an entry to the FIB, requires a prefix or a next-hop address, e.g.
            ccnl_fib del /riot/peter/schmerzl
            ccnl_fib del ab:cd:ef:01:23:45:67:89
> ccnl_fib add /test  96:8B:D4:CD:3B:45
ccnl_fib add /test  96:8B:D4:CD:3B:45
> ccnl_int /test
ccnl_int /test
> PKTDUMP: data received:
~~ SNIP  0 - size:  11 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: Hello world
~~ PKT    -  1 snips, total size:  11 byte
```

</details>

**Review by miri64 — APPROVED** [review]

**Comment by maribu** [comment]
Thanks :-)

**Pull request merged**
