### PR TITLE
remove common globals for rpl with regard to #2346

### PR DESCRIPTION
**Pull request by cgundogan**
This PR removes common globals for the **rpl** module and the **rpl_udp** example.
More information can be found in #2346

### CODE REVIEW

**Comment by gebart** [comment]
Kicked Travis.
The changes seem good, just waiting for Travis.

**Comment by gebart** [comment]
Why does Travis crash on bitaritm_timings?

>Building application: bitarithm_timings (1/70) ....................../home/travis/build.sh: line 41: 13142 Killed ./dist/tools/compile_test/compile_test.py
>The command "./dist/tools/compile_test/compile_test.py" exited with 137.

**Comment by cgundogan** [comment]
seems like travis is happy now. However, I should squash this, otherwise I will be damned to buy beer for everyone at the next hack'n'ack session :)

**Comment by thomaseichinger** [comment]
@cgundogan The beer rule mainly applies for merging commits prefixed with `SQUASHME` or `FIX*`. :smile: I don't see any of those in your descriptions but maybe squash on a per module basis later.

**Comment by cgundogan** [comment]
@thomaseichinger thanks for clearing things up :)

**Comment by cgundogan** [comment]
rebased and squashed commits on module basis. Ready to go?

**Comment by gebart** [comment]
ACK

**Pull request merged**
