### PR TITLE
Make travis whining about trailing whitespaces are a nono

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
The first commit is actually independent from Travis.

**Comment by LudwigOrtmann** [comment]
Could you add a test-commit which breaks the rule please?

**Comment by OlegHahm** [comment]
Travis is sad about white spaces - are you happy? What prefix would you prefer for the first commit?

**Comment by LudwigOrtmann** [comment]
`dist/tools: add trailing whitespace test`

**Comment by LudwigOrtmann** [comment]
I'm happy

**Comment by OlegHahm** [comment]
Updated accordingly.

**Comment by LudwigOrtmann** [comment]
AC

**Pull request merged**
