### PR TITLE
stm32l1: add adc & dac support, update configuration for nucleo-l1

### PR DESCRIPTION
**Pull request by aabadie**
This PR contains the split required by @kYc0o in #6081.

I just want to make things to go faster.

### CODE REVIEW

**Comment by aabadie** [comment]
For the record, this PR supersedes #6383.

**Comment by kYc0o** [comment]
Can you maybe change the title for something like "stm32l1 adc & dac support" and maybe add the other boards which embed this mcu?

**Comment by aabadie** [comment]
@kYc0o, title changed. The other board with a stm32l1 is limifrog-v1. I don't think I'll update it, this can be part of a follow-up PR.

**Comment by aabadie** [comment]
@kYc0o rebased, tested, all works

**Comment by aabadie** [comment]
Murdock fails but this doesn't seem related. @kaspar030 do you have any idea ?

**Comment by aabadie** [comment]
Ok, Murdock is green, I merge

**Pull request merged**
