### PR TITLE
posix_sockets: Fix use of fd_new

### PR DESCRIPTION
**Pull request by samkumar**
This fixes Issue #7054.

@immesys

### CODE REVIEW

**Comment by smlng** [comment]
please change commit message, I think it must not start with `fix` otherwise CI will report an error. Otherwise ACK from me, too, on this one.

**Comment by miri64** [comment]
> please change commit message, I think it must not start with fix otherwise CI will report an error. Otherwise ACK from me, too, on this one.

Oh yes, please prefix it with `posix_sockets: `

**Comment by samkumar** [comment]
@smlng @miri64 I have updated the the commit message to start with "posix_sockets".

**Comment by miri64** [comment]
Murdock issue unrelated to this PR. See #7055

**Comment by miri64** [comment]
#7069 was merged. Let's have another go.

**Pull request merged**
