### PR TITLE
gnrc_netreg: introduce helper macro/function for entry init

### PR DESCRIPTION
**Pull request by miri64**
This introduces a helper macro/function for `gnrc_netreg_entry_t` initialization, similar like the ones in `mutex.h`.

This is a preparation step for `mbox` (see #4919) integration into GNRC

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master and squashed.

**Comment by miri64** [comment]
Missed some instances of setting (hope the introduction of the patch to CCN-lite is alright, I don't want to wait for upstream).

**Comment by miri64** [comment]
Rebased to current master.

**Comment by OlegHahm** [comment]
> Missed some instances of setting (hope the introduction of the patch to CCN-lite is alright, I don't want to wait for upstream). 

Sorry, should have looked at this earlier. Usually, the time to get things into CCN-lite upstream is less than < 1 week - particular if only the RIOT adapter is affected.

However, a) I don't object a patch in general, but I would try to get rid of it ASAP again and b) I think we/I should seriously reconsider to move most of the CCN-lite RIOT adapter functionality into the RIOT repository.

**Comment by miri64** [comment]
> However, a) I don't object a patch in general, but I would try to get rid of it ASAP again and b) I think we/I should seriously reconsider to move most of the CCN-lite RIOT adapter functionality into the RIOT repository.

I prefer (b). That's similar to how I handled lwIP.

**Comment by miri64** [comment]
@OlegHahm ping?

**Comment by miri64** [comment]
Needed for #5772, so added to Release.

**Comment by haukepetersen** [comment]
looks, good, please squash and run Murdock

**Comment by miri64** [comment]
Done

**Comment by BytesGalore** [comment]
tested with `gnrc_networking` example on native -> ACK

**Comment by miri64** [comment]
It's just the squashing label... can we just merge to not wait another 3h?

**Comment by haukepetersen** [comment]
Yes, and go.

**Pull request merged**
