### PR TITLE
kinetis: remove ambiguous BITBAND_REG macro

### PR DESCRIPTION
**Pull request by gebart**
Refactor code to avoid using the ambiguous `BITBAND_REG` macro in favour of `BITBAND_REG32`

There are in total three different macros for bitband accesses depending on the register width: `BITBAND_REG32`, `BITBAND_REG16`, `BITBAND_REG8`

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
Looks good. If you like, add a note to the file MK60DZ10.h that you have adapted it.
Please squash and rebase after #3027 is merged.

**Comment by gebart** [comment]
@jfischer-phytec-iot rebased, updated headers with a short version text, squashed immediately, the changelogs are at the top of MK60D10.h and MK60DZ10.h inside the big comment block.
Do you want me to squash further or is the current commit list OK?

**Comment by jfischer-phytec-iot** [comment]
@gebart Can you please squash it to three commits? Grouped by:
cpu/k60: 90f7ee4 7e56708 9915c2a aa8a00c
cpu/kinetis_common: 2c6ce30
board/mulle: 445d8d2

**Comment by gebart** [comment]
I prefer to keep 
https://github.com/RIOT-OS/RIOT/commit/90f7ee4d7fdf19851c6fd03a0f1cc8b48a3c5cd4 separate, since it touches the vendor-supplied header. OK?

**Comment by jfischer-phytec-iot** [comment]
ACK

**Pull request merged**
