### PR TITLE
byteorder: Add to/from little endian conversion functions

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR adds functions to `byteorder.h` for converting from/to little endian based on the host byte order. Function names are based on `endian.h` from glibc (man 3 endian). While currently all supported platforms are little endian, this might change in the future.

### Testing procedure

Additional tests provided in `unittests/tests-core`, run `make -C tests/unittests -j tests-core test` to test

### Issues/PRs references

Technically required for a USB stack as the USB protocol is little endian.

### CODE REVIEW

**Comment by bergzand** [comment]
> Function names are based on `endian.h` from glibc (man 3 endian).

In hindsight, this was a bad idea:tm:

**Comment by miri64** [comment]
This still looks interesting to me. Hope I find some time to review.

**Comment by tcschmidt** [comment]
@kaspar030 ready to review?

**Comment by fjmolinas** [comment]
Is this one still pertinent?, can you rebase @bergzand?

**Comment by benpicco** [comment]
please rebase

**Comment by aabadie** [comment]
#15519 was merged. Closing

**Pull request closed without merging**
