### PR TITLE
nordic_softdevice_ble: document working Linux versions

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While testing #10514 we found that the `nordic_softdevice_ble` is not able to communicate with newer versions of Linux.

It is not 100% clear if 4.12 is the last version the softdevice is able to interact with, but newer kernel versions than 4.12 definitely don't work (we tried 4.15 on Ubuntu 18.04 and 4.20 on a quite recent Arch).

The reason I believe it's the 4.12 that last worked is that in the documentation of the nRF5 SDK it is mentioned for something called "legacy mode" [[1]]. However, we are using the nRF5 *IoT* SDK which doesn't mention this "legacy mode" at all in its documentation.

I don't know if we can update the `pkg` to the other SDK (and thus be able to deactivate "legacy mode"), so I just updated the documentation accordingly for now.

[1]: https://www.nordicsemi.com/DocLib/Content/SDK_Doc/nRF5_SDK/v15-2-0/group__ble__6lowpan__config?9932#ga5285fd3eaf403092286f607cd66850f3

### Testing procedure
RTFM

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
@kaspar030 can you have a look and are you maybe able to clear this up?

> I don't know if we can update the pkg to the other SDK (and thus be able to deactivate "legacy mode"), so I just updated the documentation accordingly for now.

**Comment by miri64** [comment]
Ping @kaspar030?

**Comment by kaspar030** [comment]
> I don't know if we can update the `pkg` to the other SDK (and thus be able to deactivate "legacy mode"), so I just updated the documentation accordingly for now.

I don't know either and I have no time to work on this.

**Comment by miri64** [comment]
Ok, then let's go with the doc update for now.

**Pull request merged**
