### PR TITLE
 stm32_common/stm32_mem_length: fix RAM_LEN for stm32l1xx-A/X cpu's

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

STM32L1 cpu's sometimes have a `-A/X` in the product name, this changes the amount of RAM on some of these boards. Currently some product names are incorrectly defined according to the specification, e.g: `lobaro-lorabox` `CPU_MODEL=stm32l151cb` when it is actually `stm32l151cb-a`, the first version having 16kB and the second 32 kB (NOTE: since in master the RAM for stm32l151cb is wrongly defined there isn't any functional problem, but incorrect definitions). The parsing script has been updated to include the suffix.

### Testing procedure

Check STM32 documentation to verify the combinations:

https://www.st.com/en/microcontrollers-microprocessors/stm32l151-152.html
https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-ultra-low-power-mcus/stm32l1-series/stm32l100-value-line.html

To verify `RAM_LEN` you can change the `CPU_MODEL` variable while running:

```
CPU_MODEL=stm32l151cb_a RIOT_MAKEFILES_GLOBAL_POST="\$(RIOTBASE)/cpu/stm32_common/Makefile.include" make -C examples/hello-world/ info-stm32
```

This is just including the info-stm32 recipe while allowing to set the `CPU_MODEL` externally (just a bodged command to test). Then check the output is correct:

```
CPU: stm32l151cb_a
        Line: STM32L151xx
        Pin count:      48
        ROM size:       128K (131072 Bytes)
        RAM size:       32K
```

### CODE REVIEW

**Comment by kYc0o** [comment]
Just out of curiosity, are you trying to merge a branch from the RIOT repo? It doesn't seem to come from your repo.

I'm testing this PR and it already looks good.

**Comment by kYc0o** [comment]
For info, I just fetched the RIOT repo and I found two branches which potentially don't belong here:

```console
From https://github.com/RIOT-OS/RIOT
   1a4d083fed..9876e93b6b  2019.01-branch    -> upstream/2019.01-branch
 * [new branch]            2019.04-branch    -> upstream/2019.04-branch
   c3aaf621b5..91d982733f  master            -> upstream/master
 * [new branch]            pr/lorawan_hdr    -> upstream/pr/lorawan_hdr
 * [new branch]            pr_stm32l1_add_AX -> upstream/pr_stm32l1_add_AX
 * [new tag]               2019.01           -> 2019.01
 * [new tag]               2019.01-RC3       -> 2019.01-RC3
 * [new tag]               2019.04           -> 2019.04
 * [new tag]               2019.04-RC1       -> 2019.04-RC1
 * [new tag]               2019.07-devel     -> 2019.07-devel
 * [new tag]               2019.04-RC2       -> 2019.04-RC2
```

**Comment by fjmolinas** [comment]
>  * [new branch]            pr_stm32l1_add_AX -> upstream/pr_stm32l1_add_AX

That one is on me the other I don't now. I'll delete it and re-open the PR, is that Ok with you @kYc0o?

**Comment by fjmolinas** [comment]
> * [new branch]            pr/lorawan_hdr    -> upstream/pr/lorawan_hdr

@jia200x I think that one is on you

**Pull request closed without merging**
