### PR TITLE
gh_action/test-on-iotlab: update available boards

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

After today's maintenance on IoT-LAB some boards are no longer available on the Saclay site and some are now only available in Lille. This PR updates the test-on-iotlab build matrix to reflect that change.

### Testing procedure

- test-on-iotlab should run as expected, e.g use dwm1001 from lille and don't build on nrf51dk and nrf52832mdk

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
I started a manual workflow that can be followed [here](https://github.com/aabadie/RIOT/actions/runs/2630426789)

**Comment by aabadie** [comment]
> I started a manual workflow that can be followed [here](https://github.com/aabadie/RIOT/actions/runs/2630426789)

So far, it works as expected (but it might fail in the end for different reasons)

**Comment by fjmolinas** [comment]
Just out of curiosity @aabadie what happened to the BOARDs in Saclay?

**Comment by aabadie** [comment]
> Just out of curiosity @aabadie what happened to the BOARDs in Saclay?

dwm1001, nrf52840-mdk, nrf52832-mdk, microbit, phynode and pycom were removed. For dwm1001, some others are deployed in Lille. For pycom, there are 30 deployed in Strasbourg.
I know you were using the dwm1001 in Saclay but we the ongoing "refactoring" planned in the building we can't keep the deployment in one of the room (in Digiteo 1) as it was.

**Review by miri64 — APPROVED** [review]

**Comment by miri64** [comment]
> I started a manual workflow that can be followed [here](https://github.com/aabadie/RIOT/actions/runs/2630426789)

Dead link, but I trust that this was tested properly.

**Pull request merged**
