### PR TITLE
Revert "at86rf2xx: Add support for channel page"

### PR DESCRIPTION
**Pull request by OlegHahm**
This reverts commit e9f385ae1d749deea422b9166b9eade116327fa0.

Release version of #4482

### CODE REVIEW

**Comment by haukepetersen** [comment]
ACK

**Comment by kaspar030** [comment]
kicked travis

**Comment by DipSwitch** [comment]
No first other fix.

**Comment by DipSwitch** [comment]
#4486

**Comment by emmanuelsearch** [comment]
Shall we untag and close this then?

**Comment by OlegHahm** [comment]
here too

**Pull request closed without merging**
