### PR TITLE
tests: fix test description for emb6 [2016.10-backport]

### PR DESCRIPTION
**Pull request by miri64**
Backport to #6045

### CODE REVIEW

**Comment by miri64** [comment]
For the release branch build test is required. Sorry :(

**Comment by kYc0o** [comment]
OK no problem, we saved one check at least.

**Comment by kYc0o** [comment]
?? Update branch will run again Murdock?

**Comment by miri64** [comment]
It generates a merge commit, so of course. Will rebase.

**Comment by miri64** [comment]
Rebased.

**Comment by kYc0o** [comment]
Too much check I think...

**Comment by miri64** [comment]
Well you shouldn't hit buttons if you don't know what they are doing ;-)

**Comment by kYc0o** [comment]
Hahaha true... xD

**Comment by kYc0o** [comment]
Too much temptation, it's a BUTTON! come on...

**Pull request merged**
