### PR TITLE
all: Update @gebart family name, email

### PR DESCRIPTION
**Pull request by gebart**
I changed my family name when I got married, this PR updates all the `@author` tags in the repository.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Who am I not to ACK this? ;-)

**Comment by kaspar030** [comment]
btw, gratulations!

**Comment by emmanuelsearch** [comment]
Congrats indeed!

**Comment by haukepetersen** [comment]
All the best!

**Comment by authmillenon** [comment]
Congratulations!

**Comment by cgundogan** [comment]
felicitations! (:

**Comment by DipSwitch** [comment]
Congratulations! :)

**Comment by gebart** [comment]
Thank you! :ring: :tada: :couple:

**Pull request merged**
