### PR TITLE
gh-actions: report release-tests result to Matrix

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Hoping to increase the audience for Release tests notifications beyond me ;-).

### Testing procedure
Will start a test run

### CODE REVIEW

**Comment by miri64** [comment]
Except for some formatting issues that are fixed in the latest commit, it [now works](https://matrix.to/#/!jhUMCIsdEVXOOqAUnn:matrix.org/$GArRtmL29eCHso6Ozcjy4dz5pYlR1TMZwvoVtze3UvQ?via=matrix.org&via=schleiser.de&via=utwente.io) and I moved the notification to the RIOT-maintainer channel.

**Comment by miri64** [comment]
bors merge

**Comment by miri64** [comment]
See https://ci.riot-os.org/?sha=cc83f446fdf6a4bc8e6ab710447ec090c7f5dd9b for reference

**Comment by miri64** [comment]
bors merge

**Comment by miri64** [comment]
bors merge

**Comment by miri64** [comment]
bors merge already...

**Comment by kaspar030** [comment]
This one is also missing the check-labels status

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by kaspar030** [comment]
That did it, now it's waiting in queue.

**Comment by maribu** [comment]
bors retry

**Comment by maribu** [comment]
bors cancel
bors merge

(optimizing the merge train for better usage of our CI)

**Pull request merged**
