### PR TITLE
drivers/periph/uart: remodeled UART interface

### PR DESCRIPTION
**Pull request by haukepetersen**
supersedes #3265

After many iterations #3265 became un-managable, so I decided for a clean approach using the latest consensus. The UART interface is now significantly simplified, only one write function remains. The concepts summarized:
- receiving is done purely ISR based
- transmitting is handled internally by the low-level driver implementation, e.g. blocking, isr-based, DMA-based

All existing CPUs are adapted to the interface changes -> dropping ~1500 lines of code :-)

I did however just adapt the UART drivers for the introduced interface changes, I did not optimize any of the drivers -> this can/has to be done CPU by CPU in follow up PRs, as this is also easier to review...

Tested for:
 - [ ] airfy-beacon
 - [x] arduino-due
 - [ ] arduino-mega2560
 - [ ] avsextreme
 - [ ] cc2538dk
 - [ ] f4vi1
 - [ ] fox
 - [x] frdm-k64f, *only checked `UART_0`*
 - [x] iot-lab_M3, *only checked `UART_0`*
 - [ ] msb430
 - [x] mbed_lpc1768, only checked UART_0
 - [ ] msba2
 - [ ] msbiot
 - [x] mulle *`UART_0` and `UART_1`*
 - [ ] nucleo-f091
 - [ ] nucleo-f303
 - [ ] nucleo-f334
 - [ ] nucleo-l1
 - [x] nrf51dongle
 - [ ] openmote
 - [x] pba-d-01-kw2x, *only checked `UART_0`*
 - [ ] pca10000
 - [ ] pca10005
 - [ ] pttu
 - [ ] saml21-xpro
 - [x] samr21-xpro
 - [ ] spark-core
 - [ ] stm32f0discovery
 - [ ] stm32f3discovery
 - [x] stm32f4discovery
 - [ ] telosb
 - [ ] udoo
 - [ ] wsn430
 - [ ] yunjia-nrf51822
 - [ ] z1

### CODE REVIEW

**Comment by haukepetersen** [comment]
#4115 gives an example, how the changed interface can be utilized for improved UART driver implementations...

**Comment by haukepetersen** [comment]
@gebart, @jfischer-phytec-iot, @kaspar030: are you guys ok with these changes in the UART interface?

**Comment by haukepetersen** [comment]
rebased

**Comment by thomaseichinger** [comment]
After discussions in #3265, do we consent on this approach? Or are their any objections? @daniel-k @gebart @kaspar030 @jfischer-phytec-iot @OlegHahm @sgso @PeterKietzmann

**Comment by gebart** [comment]
I like the simplified API. You have my approval.

**Comment by PeterKietzmann** [comment]
I also like the approach on the first sight. I just started to look at it again and try it with some boards

**Comment by thomaseichinger** [comment]
@PeterKietzmann Great, could you note down the boards you tested here?

**Comment by PeterKietzmann** [comment]
Of course...

**Comment by PeterKietzmann** [comment]
I placed a list of boards in the PR description above and checked some boards that I currently have available (marked them there). Until now I didn't face any problems

**Comment by haukepetersen** [comment]
damn, I actually thought we could go around testing *every* board, as this takes forever again... I mean this PR doesn't change anything logical in the uart drivers, so a good code review and testing of some selected boards should suffice I was hoping...

**Comment by gebart** [comment]
Since this does not change the logic (much), it should be enough to do a quick manual code review, and some spot checks by running tests/periph_uart on various boards along with testing the users on any platform (stdio, gnrc_slip, drivers/xbee).
I'll try out slip on mulle/k60 some time during the weekend.

**Comment by PeterKietzmann** [comment]
I don't want to be responsible for this PR, so I leave the decision up to you ;-) ! I agree with your arguments, even if testing seems to be the "safer" way in general. With my above stated list I did `STDIO` checks for different hardware. @gebart wants to test `slip`. So the last thing to test will be drivers/xbee. Any volunteers? I don't have the hardware available. Is there anything else you want me to do @haukepetersen, @gebart ?

**Comment by haukepetersen** [comment]
@PeterKietzmann: yes, give an ack :-)

**Comment by PeterKietzmann** [comment]
ACK for the part that I tested (described above).

**Comment by haukepetersen** [comment]
thx!

@gebart: did you get to test this on the mulle board?

**Comment by jfischer-phytec-iot** [comment]
@haukepetersen  Tested it on frdm-k64f and with usbdev also on frdm-k64f and pba-d-01-kw2x, works fine.

**Comment by daniel-k** [comment]
Just had a short look at the code. It's a good idea to eliminate the the different IRQ priorities! Looks good to me.

**Comment by gebart** [comment]
Tested for slip and stdio on Mulle/k60 in `examples/gnrc_border_router`, works fine.

**Comment by gebart** [comment]
ACK

**Comment by haukepetersen** [comment]
squashed

**Comment by PeterKietzmann** [comment]
Travis disagrees in some points :-(

**Comment by haukepetersen** [comment]
I see, will fix tomorrow.

**Comment by haukepetersen** [comment]
fixed those Travis issues: by added `FEATURES_PROVIDED += periph_uart` to some msp430 boards, some tests/examples were now build for these boards while not fitting memory wise...

**Comment by PeterKietzmann** [comment]
My ACK holds for the parts that I tested. But I don't dare to hit the button as this doesn't cover the whole PR. Anyone else?

**Comment by haukepetersen** [comment]
yes, with pleasure :-)

**Comment by kaspar030** [comment]
Nice one!

**Pull request merged**
