### PR TITLE
sys/quad_math: remove unused module for quad arithmetic

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

As the title says and since [nobody speaks against the idea](https://forum.riot-os.org/t/are-there-any-users-of-the-quad-math-module/3609).

### Testing procedure

Green Murdock

### Issues/PRs references

https://forum.riot-os.org/t/are-there-any-users-of-the-quad-math-module/3609

### CODE REVIEW

**Comment by kaspar030** [comment]
@OlegHahm maybe deprecate already (in the 2022.04 release notes).

**Comment by OlegHahm** [comment]
> @OlegHahm maybe deprecate already (in the 2022.04 release notes).

What do you mean? Should I explicitly state the this module will get deprecated in the next release cycle?

**Comment by aabadie** [comment]
>  Should I explicitly state the this module will get deprecated in the next release cycle?

In the deprecation section of the release notes, just add a mention that the module is deprecated in this release and will be removed in 2022.07.

**Review by kaspar030 — APPROVED** [review]
ACK.

**Pull request merged**
