### PR TITLE
Fix sys/embunit header include guards.

### PR DESCRIPTION
**Pull request by zhuoshuguo**
Fix sys/embunit header include guards.

Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#).

### CODE REVIEW

**Comment by gebart** [comment]
ACK if Murdock agrees

**Comment by zhuoshuguo** [comment]
Just updated, revised more files, please check again.

**Comment by gebart** [comment]
re-ACK.
Needs an updated commit message though, for example "sys/embunit: revised header include guards".

**Comment by miri64** [comment]
@zhuoshuguo ping?

**Comment by zhuoshuguo** [comment]
Updated.

**Pull request merged**
