### PR TITLE
Fix x86 FPU lazy swap

### PR DESCRIPTION
**Pull request by zehortigoza**
The ucontext->x86_fxsave is initialize as 512 bytes of zeros, but it
is not a valid value to be set onto FPU registers, causing a General
Protection Fault:

Interrupt 0x0d (General Protection Fault) while handling 0x07 (Device not available)
EAX=0012f4c0  ECX=001336e4  EDX=001334ac  EBX=001336e0
ESP=00123784  EBP=001237c8  ESI=00000200  EDI=00000000
Error code=00000000
CR0=80010031  CR2=00000000  CR3=0012d000  CR4=000001e0
EIP=0000:80010031  EFLAGS=0012d000
<stack trace>
00000000
???
</stack trace>
Halting.

So lets copy the initial state of FPU registers before FPU is used
and set it as the initial state of FPU to new threads(coroutine).

### CODE REVIEW

**Comment by OlegHahm** [comment]
@Kijewski, does this make sense to you? I guess you're the only RIOTer with enough understanding of x86 code.

**Comment by zehortigoza** [comment]
I had change the commit message a little bit and rebased over RIOT-OS/master.

**Comment by OlegHahm** [comment]
@Kijewski, ping!

**Comment by zehortigoza** [comment]
@Kijewski ping

**Comment by Kijewski** [comment]
Seems sane enough. ACK.

**Comment by Kijewski** [comment]
For a good measure: please rebase on master (should be easy enough since there are no merge conflicts) and wait for a successful Travis run.

**Comment by authmillenon** [comment]
> (should be easy enough since there are no merge conflicts)

Why rebase then?!??

**Comment by Kijewski** [comment]
Because the Travis script was changed in the meantime.

**Comment by authmillenon** [comment]
Ah… did not realize the merge-base is that old ^^

**Comment by zehortigoza** [comment]
Rebased!

But looks like the Travis when down and some build jobs are marked as failed because of this.

**Comment by authmillenon** [comment]
Can you change the commit subject to `x86: fix FPU lazy swap`? Our convention forbids "Fix" as a prefix.

**Comment by zehortigoza** [comment]
Changed

**Comment by Kijewski** [comment]
Thank you!

**Pull request merged**
