### PR TITLE
boards/im880b: add HSE clock definition

### PR DESCRIPTION
**Pull request by jmfriedt**
### Contribution description

Commit [c14d7ec7dbc2238ad251a70904407e503342b82d](https://github.com/RIOT-OS/RIOT/commit/c14d7ec7dbc2238ad251a70904407e503342b82d) requires the definition of the clock peripherals on a given board but the im880b does not provide such a definition in its configuration file. This PR defines the HSE clock as the 16 MHz external clock.

### Testing procedure

Prior to the update, flashing the tests/shell example on an im880b board leads to no message being displayed on the serial port. Proper operation is resumed with the modification, with the RIOT prompt being displayed on the serial port.

### CODE REVIEW

**Comment by maribu** [comment]
Thanks for the fix!

Would you mind to change the commit title to match `<system>/<subsystem>: <msg>` template, e.g. `boards/im880b: add HSE clock definition`?

I don't have hardware to confirm, but I will just trust your testig. After the rename of the commit msg this should be ready to go.

**Comment by maribu** [comment]
Hmm, that didn't work as expected :/

**Comment by maribu** [comment]
Strange. The issue was that the PR conntained three commits, one of which had the correct title. I squashed those commits into one and pushed into your branch. For some reason, this resulted in the PR being closed. The branch does however now contain only one commit with the correct title and the original changes.

If you could re-open the PR, it could now be merged. Sometimes Github refuses to reopen a PR. If so, please open a new one and post a link to that here.

**Comment by jmfriedt** [comment]
https://github.com/RIOT-OS/RIOT/pull/18295 aims at solving the issue with this PR. Thanks.

**Pull request closed without merging**
