### PR TITLE
tests: fix gnrc_sixlowpan for 2db9ed1 and b272e90

### PR DESCRIPTION
**Pull request by miri64**
2db9ed1 and b272e90 changed the output of `gnrc_pktdump`, but the
`gnrc_sixlowpan` tested fix was never adapted for that and was failing
because of that.

### CODE REVIEW

**Comment by kaspar030** [comment]
(no need to backport, I fixed those tests manually...)

**Comment by miri64** [comment]
> I fixed those tests manually...

But not in the release, apparently ;-)

**Comment by kaspar030** [comment]
> But not in the release, apparently ;-)

nope. I improved out testrunner to include all tests here: [1]. While the testing part works more or less fine, I  don't think it is ready for merging into the release. Nevertheless I intent to use its results. ;)

**Comment by miri64** [comment]
link missing...

**Pull request merged**
