### PR TITLE
drivers/periph_common: add periph_init% modules

### LINKED ISSUE #11026: Recent changes effectively killed modular board designs
What was the reason behind initializing all the interfaces in drivers/periph_common/init.c irregardless of whether actual firmware uses them or not?

It is incompatible with any kind of modular design when external modules may be connected or not and interfaces used or not depending on runtime configuration.

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Following up on #13089 this PR allows disabling `periph_%`auto initialization by adding explicit `periph_init_%` modules for each one of them.

Since they are not initlalized by the `auto-init` module I added a `periph_init` module that just handles enabling or disabling `periph` initialization.

### Testing procedure

- Normal build:

```
make -C tests/xtimer_usleep info-debug-variable-USEMODULE --no-print-directory
auto_init auto_init_xtimer board core core_init core_msg core_panic cpu div native-drivers periph periph_common periph_gpio periph_init periph_init_gpio periph_init_pm periph_init_timer periph_pm periph_timer periph_uart stdin stdio_native sys test_utils_interactive_sync xtimer
```

- Disable one `periph_init_%`

```
DISABLE_MODULE+=periph_init_timer make -C tests/xtimer_usleep info-debug-variable-USEMODULE --no-print-directory
auto_init auto_init_xtimer board core core_init core_msg core_panic cpu div native-drivers periph periph_common periph_gpio periph_init periph_init_gpio periph_init_pm periph_pm periph_timer periph_uart stdin stdio_native sys test_utils_interactive_sync xtimer
```

- Disable all `periph_init`

```
DISABLE_MODULE+=periph_init make -C tests/xtimer_usleep info-debug-variable-USEMODULE --no-print-directory
auto_init auto_init_xtimer board core core_init core_msg core_panic cpu div native-drivers periph periph_common periph_gpio periph_pm periph_timer periph_uart stdin stdio_native sys test_utils_interactive_sync xtimer

```

- Murdock should run all tests.

### Issues/PRs references

Fixes #11026
~~depends on #13401~~

### CODE REVIEW

**Comment by fjmolinas** [comment]
No longer waiting for another PR, I changed the name of all modules to `periph_init` to separate them from `auto_init` since they are not handled in the same place.

**Comment by fjmolinas** [comment]
Only the following failures:

```
    tests/netstats_l2/esp32-wroom-32:gnu
    examples/suit_update/nrf52dk:gnu
```

I believe they are unrelated.

**Comment by fjmolinas** [comment]
@benpicco let me know if I should squash.

**Comment by benpicco** [comment]
Yes, please squash!
Change looks good too.

**Comment by fjmolinas** [comment]
Thanks for the review!

**Comment by gschorcht** [comment]
I am not really happy with this change. For example, until this change it was sufficient
```
USEMODULE=periph_rtc BOARD=... make -C tests/shell
```
to enable the RTC commands and use the RTC. With this change it is now necessary to use
```
USEMODULE='periph_rtc periph_init_rtc' BOARD=... make -C tests/shell
```
It took me some time to figure out the reason why the RTC commands didn't work anymore :worried: The reason is that `periph_rtc` is not included in the `FEATURES_USED` variable. Therefore, the `periph_init_rtc` module is not enabled.

The expected behavior is the following. If a `periph_*` module is used by an application and the board provides the `periph_*` feature, the peripheral should be initialized during the startup.

It seems to work if the `periph_*` module is added to the makefile of the application, but it doesn't work if it is defined in `USEMODULE` environment variable at the command line.

To be honest, I don't understand the necessity for this change. Peripherals are only initialized when the according modules are used. If the according modules are used, the application expects that the peripherals are initialized. There is probably no use case where the application might want to disable the initialization of peripherals using `DISABLE_MODULE`.

**Comment by fjmolinas** [comment]
> ```
> USEMODULE=periph_rtc BOARD=... make -C tests/shell
> ```

You can just as well do `FEATURES_REQUIRED=periph_rtc BOARD=... make -C tests/shell`, it could still change it to set the `DEFAULT_MODULE` based on `USEMODULE` instead.

From my understanding `periph_%` should not be added as `USEMODULE` but as `FEATURES_REQUIRED` in an application Makefile.

> To be honest, I don't understand the necessity for this change. Peripherals are only initialized when the according modules are used. If the according modules are used, the application expects that the peripherals are initialized. There is probably no use case where the application might want to disable the initialization of peripherals using `DISABLE_MODULE`.

Well some users had a used case for this #11026. It seems that in some cases the user does want to handle initialization.

Anyway:

```
# set all USED periph_% init modules as DEFAULT_MODULE
ifneq (,$(filter periph_init, $(USEMODULE)))
  DEFAULT_MODULE += $(subst periph_,periph_init_,$(filter periph_%,$(USEMODULE)))
endif
```

would work for your use case, would you agree on that fix?

**Comment by fjmolinas** [comment]
> 
> ```
> # set all USED periph_% init modules as DEFAULT_MODULE
> ifneq (,$(filter periph_init, $(USEMODULE)))
>   DEFAULT_MODULE += $(subst periph_,periph_init_,$(filter periph_%,$(USEMODULE)))
> endif
> ```
> 
> would work for your use case, would you agree on that fix?

Hmm make doesn't like this.

**Comment by fjmolinas** [comment]
> Hmm make doesn't like this.

Anyway there are still ways of doing this so it checks `USEMODULE` and not `FEATURES_USED`.

**Comment by gschorcht** [comment]
> > ```
> > USEMODULE=periph_rtc BOARD=... make -C tests/shell
> > ```
> 
> You can just as well do `FEATURES_REQUIRED=periph_rtc BOARD=... make -C tests/shell`

Unfortunately not :worried:
```
FEATURES_REQUIRED=periph_rtc BOARD=... make -C tests/shell
```
doesn't do the trick. It enables module `periph_rtc` but not module `periph_init_rtc`.

**Comment by gschorcht** [comment]
> Well some users had a used case for this #11026. It seems that in some cases the user does want to handle initialization.

- 

> > > ```
> > > USEMODULE=periph_rtc BOARD=... make -C tests/shell
> > > ```
> > 
> > 
> > You can just as well do `FEATURES_REQUIRED=periph_rtc BOARD=... make -C tests/shell`
> 
> Unfortunately not 
> 
> ```
> FEATURES_REQUIRED=periph_rtc BOARD=... make -C tests/shell
> ```
> 
> doesn't do the trick. It enables module `periph_rtc` but not module `periph_init_rtc`.

@fjmolinas Sorry, forget it, it works in that way. I had a typo in my command :sunglasses: I can live with this approach, even if it differs from the usual way of activating functionalities.

**Pull request merged**
