### PR TITLE
unittests/base64: fixed header file include guard

### PR DESCRIPTION
**Pull request by Darredevil**
fixes #2623

### CODE REVIEW

**Comment by haukepetersen** [comment]
Oh, didn't see this on your other PR: could you please change your commit message following our usual scheme ("main-module/sub-module: what was changed", e.g. "unittests/base64: fixed header file include guard") and then just state the in den description something like "fixes #2623"? Thx.

And kicked Travis by the way.

**Comment by Darredevil** [comment]
Sorry for the confusion, done.

**Comment by LudwigOrtmann** [comment]
PR title != commit message

**Comment by Darredevil** [comment]
closed, already merged in #2676

**Pull request closed without merging**
