### PR TITLE
cpu: Add clock source selection based on CLOCK_HSE or CLOCK_HSI for STM32F4 family

### PR DESCRIPTION
**Pull request by DipSwitch**
One more with #3703 in mind.

Propose to configure the STM32F4 PLL clock source with the CLOCK_HSE or CLOCK_HSI define in the includes\periph_conf.h from the BSP

Can't test HSI and HSE implementation, although nothing for HSE isn't changed. HSI should also work since the clock tree is the same for HSI and HSE selection.

### CODE REVIEW

**Comment by kYc0o** [comment]
Any news on this?

**Comment by DipSwitch** [comment]
rebased and squashed

**Comment by PeterKietzmann** [comment]
Code looks reasonable to me. Will try to test now

**Comment by PeterKietzmann** [comment]
This doesn't break anything and probably provides the possibility to use external oscillators for stm32f4 CPUs. However, adapting the periph_conf.h to use HSE does not work. Will check the other PRs first

**Comment by DipSwitch** [comment]
I also have an F4Discog will try tonight aswell :)

**Comment by PeterKietzmann** [comment]
@DipSwitch any news from your side? Just besides, do you use the HSI somewhere or is it just for the general support?

**Comment by DipSwitch** [comment]
Just general support and to keep the STM implementations sort of the same.

**Comment by PeterKietzmann** [comment]
Can you show your adaptions in the periph_conf for testing please? Maybe I'm just too tired but I can't get it running on the stm32f0

**Comment by DipSwitch** [comment]
diff --git a/boards/stm32f4discovery/include/periph_conf.h b/boards/stm32f4discovery/include/periph$
	index d497874..40b23c2 100644
	--- a/boards/stm32f4discovery/include/periph_conf.h
	+++ b/boards/stm32f4discovery/include/periph_conf.h
	@@ -30,11 +30,11 @@ extern "C" {
	  * @name Clock system configuration
	  * @{
	  */
	-#define CLOCK_HSE           (8000000U)          /* external oscillator */
	+#define CLOCK_HSI           (16000000U)          /* external oscillator */
	 #define CLOCK_CORECLOCK     (168000000U)        /* desired core clock frequency */

	 /* the actual PLL values are automatically generated */
	-#define CLOCK_PLL_M         (CLOCK_HSE / 1000000)
	+#define CLOCK_PLL_M         (CLOCK_HSI / 1000000)
	 #define CLOCK_PLL_N         ((CLOCK_CORECLOCK / 1000000) * 2)
	 #define CLOCK_PLL_P         (2U)
	 #define CLOCK_PLL_Q         (CLOCK_PLL_N / 48)

**Comment by PeterKietzmann** [comment]
Whoops, yeah. I decreased `CLOCK_CORECLOCK` :/. This way it works. I'd like to merge as is but would be nice to have some documenting words in a follow-up PR

**Comment by DipSwitch** [comment]
I can do a followup PR, maybe tomorrow evening... Where should I put the documentation?

**Comment by PeterKietzmann** [comment]
ACK and go. @DipSwitch I'm not quite sure but probably it makes most sense in the periph_conf.h?

**Pull request merged**
