### PR TITLE
Fix issue #2109

### PR DESCRIPTION
**Pull request by Joelfp**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Thanks for the PR, will try to test tomorrow, when I have access to the board again. If I forget, please be so kind and remind me.

Can you please prefix the commit message and PR title with something like `z1` or `board z1`?

**Comment by Joelfp** [comment]
Oleg Hahm
I just write to remind you about the test with the zolertia boards.

Regards
Joel

**Comment by OlegHahm** [comment]
As you assumed, it was working on my Z1 without this PR, too. But I can confirm that it is still working after the PR and if it fixes the problem for other Z1s,  I'm - of course - completely fine with merging this. Can you run a `git rebase` please to get rid of the merge conflict? As soon as this is done and Travis agrees, we're ready to merge.

ACK.

**Comment by Joelfp** [comment]
I am still not well versed with git, do you want me to rebase on origin/master ?

**Comment by OlegHahm** [comment]
If you just checkout this branch on your machine and just run `git rebase` the merge commit should disappear from the branch. After that you can just do a "force push" by running `git push -f <remote> MSP430-Fix_issue_2109`, where `<remote> should correspond with the remote fork you're using. I.e. `git remote get-url <remote>` should show something like `git@github.com:gtrpucp/RIOT.git`.

**Comment by Joelfp** [comment]
I may have screwed it before when doing another PR. I hadn't read the project's guidelines and didn't do a proper branch to generate it.
So if I rebase to local master I'll introduce my other unrelated commits.
I think about using `git rebase -i HEAD~3` and then as you suggested.

how do you feel about it?

**Comment by OlegHahm** [comment]
Sounds like a good idea.

**Comment by Joelfp** [comment]
Done!

**Comment by OlegHahm** [comment]
Hm, almost. Try `git rebase -i HEAD~3` again and remove the two first lines.

**Comment by OlegHahm** [comment]
Cool!

**Comment by Joelfp** [comment]
Why Travis build failed?

**Comment by gebart** [comment]
@Joelfp I don't know, but sometimes Travis is flaky. I restarted the build for you.

**Comment by OlegHahm** [comment]
Congrats for your first contribution to RIOT!

**Pull request merged**
