### PR TITLE
header file include guards repaired

### PR DESCRIPTION
**Pull request by rajma996**
header file guards repaired as per the issue https://github.com/RIOT-OS/RIOT/issues/2623 
please reply if any additional changes required.....

### CODE REVIEW

**Comment by Kijewski** [comment]
This diff is very broken …

```diff
-  #define __ASM            __asm                                      /*!< asm keyword for ARM Compiler          */
-  #define __INLINE         __inline                                   /*!< inline keyword for ARM Compiler       */
-  #define __STATIC_INLINE  static __inline
+  #define      __asm                                      /*!< asm keyword for ARM Compiler          */
+  #define __   __inline                                   /*!< inline keyword for ARM Compiler       */
+  #define __ST static __inline

-__STATIC_INLINE void NVIC_SystemReset(void)
+__STATIC_INLININE void NVIC_SystemReset(void)

 -      #error "Compiler generates FPU instructions for a device without an FPU (check __FPU_PRESENT)"
+      #error "Compiler nes struns for a device without an FPU (check __FPU_PRESENT)"
```

**Comment by rajma996** [comment]
thanks for pointing out.... 
on it. :)

**Comment by rajma996** [comment]
@Kijewski  are the changes required in header file guards only of the type as mentioned at https://github.com/RIOT-OS/RIOT/issues/2623 or some other formats might also be present...

**Comment by rajma996** [comment]
@Kijewski  also can you tell changes required in the file cpu/cortexm_common/include/core_cm0.h , there are many header includes beginning with __ :(

**Comment by gebart** [comment]
closing this as the remote branch disappeared and #4616 seem to have replaced it

**Pull request closed without merging**
