### PR TITLE
cpu/stm32_common: unified hwrng driver

### PR DESCRIPTION
**Pull request by haukepetersen**
the title should speak for itself...

### CODE REVIEW

**Comment by vincent-d** [comment]
We're getting close to have all the stm32 periph unified! Nice!

**Comment by haukepetersen** [comment]
working on it :-)

**Comment by vincent-d** [comment]
Looks good, https://github.com/OTAkeys/RIOT/commit/f1cfb40098c8ff6316402acc79ba857b1a1a81b0 add the feature in nucleo144-f207 and f413, feel free to cherry-pick / squash it

**Comment by haukepetersen** [comment]
thanks! 

ACK is here, Murdock are happy -> go

**Pull request merged**
