### PR TITLE
tests: fixed INSUF_MEM define for gnrc_ipv6_nib_6ln

### PR DESCRIPTION
**Pull request by haukepetersen**
test does not build for native on my machine, so fixed.

### CODE REVIEW

**Comment by miri64** [comment]
How could this have passed Murdock?!!? Oo @kaspar030 any idea?

**Comment by miri64** [comment]
Please provide a backport to 2017.10-branch

**Comment by miri64** [comment]
Release manager says backporting not required.

**Comment by haukepetersen** [comment]
Release manager was mistaken, backporting does indeed simplify things down the line...

**Comment by haukepetersen** [comment]
backported.

**Pull request merged**
