### PR TITLE
esptools/install.sh: Fix shellcheck issues

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Quote all the things!

### Testing procedure

The script should still work as before

### Issues/PRs references

None

### CODE REVIEW

**Comment by gschorcht** [comment]
As long as the variables do not contain spaces, it should not really be necessary in any shell to enclose them in quotes. But indeed, for path names it is better to quote them.

**Comment by bergzand** [comment]
> As long as the variables do not contain spaces, it should not really be necessary in any shell to enclose them in quotes. But indeed, for path names it is better to quote them.

Yup, path names and argument should always be quoted as they could in theory contain whitespace. Variables, in this case `ARCH_ALL` rely on the whitespace and are not quoted.

**Review by gschorcht — APPROVED** [review]

**Comment by gschorcht** [comment]
Thanks for providing that fix.

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel
bors merge

**Pull request merged**
