### PR TITLE
boards/samr21-xpro: rm unused radio interface defs

### PR DESCRIPTION
**Pull request by haukepetersen**
these are leftovers and unused since the old network stack was removed...

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased

**Comment by haukepetersen** [comment]
@thomaseichinger: care to take a look?

**Comment by OlegHahm** [comment]
Sorry for the delay. I planned to test this for a long time, but never had the hardware with me, when I found it.

**Comment by OlegHahm** [comment]
Now I did. ACK and go!

**Pull request merged**
