### PR TITLE
at86rf231: minor cleanup

### PR DESCRIPTION
**Pull request by OlegHahm**
ARM once nominated me as RIOT cleaner, I should justify this reputation.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Any special reason why you remove all the checks for the `max_len` parameter?

**Comment by OlegHahm** [comment]
See commit message (https://github.com/OlegHahm/RIOT/commit/6a43201147812528bb6a34e5033264293318a831). When I first looked at the code, I found them confusing, and later unnecessary. No strong opinion here, but I can see little benefit in having them, but they are increasing code lines and have some unnecessary runtime overhead. The latter is probably not too bad, since we can expect that these functions won't be called very often. If you object, I can remove the commit.

**Comment by haukepetersen** [comment]
Actually I don't object - I completely agree that they are unreadable and are just adding lots of lines of code. But so far we basically followed the paradigm in the network stack, that we check all parameters before using and this would break with that paradigm. But I do not think that this is bad, we should just all agree with this. And there is always the option to put a `#ifdef DEVELHELP` around them...

@authmillenon what do you think?

**Comment by OlegHahm** [comment]
> And there is always the option to put a #ifdef DEVELHELP around them...

Yes, I thought about this, but in the end it would be probably worse, because - as I said - we can neglect the runtime overhead and the readability would suffer even more.

Concerning the checks in general: I think it's okay to do it for the rest, but for an boolean value it won't break anything if the length is wrong and mis-usae is IMO pretty unlikely.

**Comment by haukepetersen** [comment]
Agree. The only thing I do not like too much is breaking consistency here, but I guess that I can live with

**Comment by OlegHahm** [comment]
It's just a different consistency. :wink: (Checking the length of all parameters which are not bool.)

**Comment by OlegHahm** [comment]
@authmillenon, are you okay?

**Comment by authmillenon** [comment]
Yes, seems to be alright. ACK.

**Pull request merged**
