### PR TITLE
tests: fix linker failure on OS X due to name clash

### PR DESCRIPTION
**Pull request by smlng**
This PR fixes the following failure when build `tests/libfixmath` or `tests/lwip`:

```
ld: entry point (_main) undefined. for architecture i386
```

The problem is that the test application has the same name as the required module and/or package, i.e. `libfixmath`. Renaming the test application with prefix `test_` solves this.

_Note_: this issue exists only on macOS with LLVM/clang but not on Linux with gcc.

### CODE REVIEW

**Comment by smlng** [comment]
based on #6258 and #6333

**Comment by smlng** [comment]
this PR is (re)based on #6333

**Comment by smlng** [comment]
to clarify what its doing: running certain tests on macOS revealed a name clash in the make system when a test has an `APPLICATION` variable in its Makefile that is the same as a package required with `USEPKG`; i.e. this happened with `tests/libfixmath`, `tests/lwip`, and `tests/pkg_tiny-asn1`. 

I resolved it by prefixing the `APPLCIATION` variable with `test_`, for the sake of consistency I applied this scheme to all other tests as well ...

**Comment by kYc0o** [comment]
There's a way to build all the tests at once?

**Comment by smlng** [comment]
@kYc0o yes: murdock or jenkins 😁 btw. Jenkins is fine with the changes. 

you could also run:

```
cd tests;
for i in $(ls); do echo $i; make -C $i; done
```

**Comment by smlng** [comment]
@kYc0o also note that this PR depends on #6333

**Comment by kYc0o** [comment]
Well this PR changes every test's name but strangely some tests build without this change, for instance bloom_bytes... Did you had the errors for all the tests you've modified?

**Comment by smlng** [comment]
nope, as said above:

> for the sake of consistency I applied this scheme to all other tests as well ...

**Comment by miri64** [comment]
Back to the past then?

**Comment by miri64** [comment]
Maybe wait for @Kijewski with this one what he thinks about reverting https://github.com/RIOT-OS/RIOT/pull/1502 ;-)

**Comment by OlegHahm** [comment]
Well, this PR only reverts the renaming of the application, not the renaming of the folder which is okay, I think. I am more confused that we still have this name clash between RIOT and application code - I thought we solved this long ago.

**Comment by smlng** [comment]
mhm, wasn't aware of #1502 ... it seems that name clashes are only an issue on macOS, not Linux.

However I don't think its bad to have the APPLICATION variable of tests to be prefixed by `test_`, and would further suggest to add `example_` to all examples.

But, for now I only want to fix macOS to get it into Jenkins with green build status 😄

**Comment by OlegHahm** [comment]
Out of curiosity: do you understand why it is failing on OSX?

**Comment by smlng** [comment]
not exactly, but I don't think its clang - its the version of `make` on macOS. I didn't dig any deeper into the build system of RIOT, I think others are more familiar with that, @kaspar030 maybe?

As said before, it must be some clash with the `APPLICATIONS` and `USEPKG` variables in a Makefile. For instance `tests/libfixmath` failed where `APPLICATION = libfixmath` and `USEPKG = libfixmath` are present, while `tests/libfixmath_unittests` does not fail, prefixing the former to have `APPLICATION = test_libfixmath` solved the problem. Same thing for `tests/lwip` and `tests/tiny-asn1`, both had APPLICATION and USEPKG with the same _name_ in their Makefiles.

**Comment by smlng** [comment]
@OlegHahm any objections? Otherwise this should go into the release. Btw. CI is happy, too

**Comment by smlng** [comment]
rebased without depending on other PR now

**Comment by miri64** [comment]
Murdock succeeded and Jenkins failed, though from the Webview it isn't clear why.

**Comment by smlng** [comment]
maybe some changes in the CI server infrastructure and the job got stuck, Jenkins is in parts WIP. Anyway, rescheduled on Jenkins - if Murdock is fine, Jenkins should/will be, too. 

🍵 and wait ...

**Comment by smlng** [comment]
rebased

**Comment by miri64** [comment]
Needs rebase again.

**Comment by OlegHahm** [comment]
For the record: I don't object this PR.

**Comment by Kijewski** [comment]
Since #1502 we made some changes to the make system which disallows two modules sharing the same name. So this PR seems to be indeed needed. But maybe it would be enough to edit `tests/Makefile.tests_common`, not every `tests/*/Makefile`?

**Comment by smlng** [comment]
rebased, lets wait for CI ...

**Comment by smlng** [comment]
done! Lets see if CI is happy

**Pull request merged**
