### PR TITLE
pkg: update ccn-lite and adapt shell commands

### PR DESCRIPTION
**Pull request by smlng**
This updates the ccn-lite package version which brings in the
    latest upstream fixes for some compiler issues found on macOS
    with clang and newer GCC versions.

    A minor adaption of the RIOT shell commands is also included.

### Issues/PRs references

https://github.com/cn-uofbasel/ccn-lite/pull/298

### CODE REVIEW

**Comment by smlng** [comment]
huhu @cgundogan you sure want this, right 😉

**Comment by cgundogan** [comment]
Why again did you add a 4. parameter?
https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/src/ccnl-prefix.c#L267
https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/include/ccnl-prefix.h#L155

according to the CCN.-lite master, there are only 3 parameters for `ccnl_URItoPrefix`

**Comment by smlng** [comment]
> Why again did you add a 4. parameter?
 why me? In this PR I remove the 4th parameter to make it work.

**Comment by smlng** [comment]
and according to `git blame` Oleg introduced the original shell command using 4 params:

```
5db537fbab (Oleg Hahm         2016-02-03 16:46:28 +0100 170)     struct ccnl_prefix_s *prefix = ccnl_URItoPrefix(pfx, suite, NULL, 0);
```

**Comment by cgundogan** [comment]
Hm, that's true (:

**Pull request merged**
