### PR TITLE
kinetis: lptmr reload instead of spinning

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Spinning for the correct time has the side effect that it may cause
infinite recursion if the callback function calls timer_set.

timer_set->callback->...->timer_set->callback->...->timer_set-> infinity

In theory, the drawback is that the callback for very short timeouts
(<2 lptmr ticks) may be delayed up to 2 lptmr ticks (61 µs)

In practice however, tests performed using tests/bench_timers shows that
this change only affects the accuracy of the timer target when timer_set
is called with a timeout of 0, which results in a delay of 30 µs.

### Testing procedure

Run the test in #10019 on a kinetis board with an LPTMR configuration (e.g. any of the frdm boards, for k64f, see #9930) with this PR applied.

### Issues/PRs references

Regression test for this bug #10019 
LPTMR configuration for frdm-k64f: #9930

### CODE REVIEW

**Comment by gebart** [comment]
I have noticed that bench_timers shows that the target is missed sometimes when LPTMR timer_set is called with timeout=0. This PR fixes it by reloading whenever timeout == 0 instead of trying to race update the compare register.

**Comment by miri64** [comment]
@smlng @aabadie anyone of you care to test?

**Comment by MrKevinWeiss** [comment]
I tested this PR with tests/periph_timer_timeout0 from #10019 on a frdm-k22f.  At first it failed due to coordination of tests and reset (an the fact it is on a raspberry pi) but it passes when I `make flash -C tests/periph_timer_timeout0` then `make test -C tests/periph_timer_timeout0`
<details><summary>frdm-k22f</summary>
<p>

```
2019-03-26 13:52:42,295 - INFO # main(): This is RIOT! (Version: 2018.10-RC1-549-g438a1-test10020)
2019-03-26 13:52:42,297 - INFO # 
2019-03-26 13:52:42,305 - INFO # Test for timer_set with timeout=0
2019-03-26 13:52:42,307 - INFO # 
2019-03-26 13:52:42,312 - INFO # Available timers: 3
2019-03-26 13:52:42,319 - INFO # 
2019-03-26 13:52:42,324 - INFO # Testing TIMER_DEV(0):
2019-03-26 13:52:42,331 - INFO # TIMER_DEV(0) running at 1000000 Hz
2019-03-26 13:52:42,357 - INFO # (debug) TIMER_DEV(0) switches: 1
2019-03-26 13:52:42,359 - INFO # 
2019-03-26 13:52:42,363 - INFO # Testing TIMER_DEV(1):
2019-03-26 13:52:42,368 - INFO # TIMER_DEV(1) running at 1000000 Hz
2019-03-26 13:52:42,421 - INFO # (debug) TIMER_DEV(1) switches: 1
2019-03-26 13:52:42,421 - INFO # 
2019-03-26 13:52:42,423 - INFO # Testing TIMER_DEV(2):
2019-03-26 13:52:42,426 - INFO # TIMER_DEV(2) running at 32768 Hz
2019-03-26 13:52:43,042 - INFO # (debug) TIMER_DEV(2) switches: 10000
2019-03-26 13:52:43,043 - INFO # 
2019-03-26 13:52:43,044 - INFO # TEST SUCCEEDED

```

</p>
</details>

I just did the test only, I am relying on @kaspar030 review.  Maybe he can merge then.

**Comment by MrKevinWeiss** [comment]
ping @kaspar030 @miri64

**Comment by benpicco** [comment]
Everything is green here already - any reason not to press the button?

**Comment by miri64** [comment]
https://github.com/RIOT-OS/RIOT/pull/10020#issuecomment-448231318 was the only thing missing, but @MrKevinWeiss was taking care of this. Let's just give Murdock another spin, since the last build of this PR is quite old.

**Pull request merged**
