### PR TITLE
cpu: add periph_rtt_overflow feature

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The RTT overflow callback is not available on all RTT implementations.
This means it is either a no-op or `rtt_set_overflow_cb()` is a no-op or it will overwrite the alarm set with `rtt_set_alarm()`.

This adds a feature to indicate that proper overflow reporting is available.

### Testing procedure

No change in functionality.

### Issues/PRs references

split off #15763

### CODE REVIEW

**Comment by maribu** [comment]
Was the first commit intended to be part of this PR?

**Comment by benpicco** [comment]
You are right, this is unrelated

**Comment by maribu** [comment]
```
$ ag overflow cpu/*/periph -l | ag rtt
cpu/atmega_common/periph/rtt.c
cpu/cc2538/periph/rtt.c
cpu/efm32/periph/rtt_series0.c
cpu/efm32/periph/rtt_series1.c
cpu/esp32/periph/rtt.c
cpu/esp8266/periph/rtt.c
cpu/fe310/periph/rtt.c
cpu/kinetis/periph/rtt.c
cpu/nrf5x_common/periph/rtt.c
cpu/sam0_common/periph/rtc_rtt.c
cpu/sam3/periph/rtt.c
cpu/stm32/periph/rtt_f1.c
cpu/stm32/periph/rtt_all.c
```

And all those contain reasonable overflow handling code. But I think you have missed fe310.

**Comment by maribu** [comment]
esp8266 emulates overflow. The code also looks reasonable on the first look to me. I think you should add it as well.

**Comment by maribu** [comment]
The sam3 doesn't support overflow. The match is a comment in the source saying that hardware doesn't support an overflow callback.

**Comment by maribu** [comment]
Sorry for the stream of comments.

Bottom line: Please add fe310 and esp8266 and squash right away. It is ready for merge then.

**Comment by benpicco** [comment]
Yea I originally had intended this for `rtt_rtc` which already has a code path to deal with the !periph_rtt_overflow case that's more efficient than using the emulation in the driver.

But it's more consistent this way.

**Review by maribu — APPROVED** [review]

**Pull request merged**
