### PR TITLE
doc: add release notes to doxygen documentation

### PR DESCRIPTION
**Pull request by miri64**
Provides a script to generate a doxygen page from the
`release-notes.txt` and includes it to the doxygen build.

### CODE REVIEW

**Comment by miri64** [comment]
This should be a straight forward merge ;-)

**Comment by miri64** [comment]
> does Murdock build the docs, anyway?

Of course. How do you think Murdock is able to tell you that you screwed up the documentation.

**Comment by smlng** [comment]
mhm, nobody else has time to look at this? Go, go, go ...

**Comment by miri64** [comment]
> mhm, nobody else has time to look at this? Go, go, go ...

Since when do non-major changes need more than one ACK ;-)?

**Comment by smlng** [comment]
I'd like to have a second opinion, especially concerning stuff I have less expertise or others might have doubts. 

But no reaction after close to a week, so nobody cares that much, anyway? 😉

**Comment by miri64** [comment]
> I'd like to have a second opinion, especially concerning stuff I have less expertise or others might have doubts.

If you don't feel like you have the expertise to give it your ACK, don't ACK ;-)

> But no reaction after close to a week, so nobody cares that much, anyway? :wink:

Or got lost in the endless torrent of PRs ;-)

**Pull request merged**
