### PR TITLE
 boards/msba2/lobaro-lorabox: change TERMFLAGS to PYTERMFLAGS

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

The boards are using `pyterm` specific options that do not work on any
other `RIOT_TERMINAL`. It is a shame this is required but at least do
not pass arbitrary arguments to the other RIOT_TERMINAL.
So use the new PYTERMFLAGS for this.

This addresses setting the TERMFLAGS in an incompatible way to the other `RIOT_TERMINAL` in https://github.com/RIOT-OS/RIOT/issues/12089  https://github.com/RIOT-OS/RIOT/issues/12090

However, `term` would still not work with `socat` or `picocom`.

### Testing procedure

Testing still works on `msba2`. For example `tests/bloom_bytes`

```
BOARD=msba2 RIOT_CI_BUILD=1 make --no-print-directory -C tests/bloom_bytes/ flash >/dev/null; BOARD=msba2 RIOT_CI_BUILD=1 make --no-print-directory -C tests/bloom_bytes/  test
/home/harter/work/git/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyUSB0" -b "115200" -tg
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyUSB0
Welcome to pyterm!
Type '/exit' to exit.
main(): This is RIOT! (Version: buildtest)
Testing Bloom filter.

m: 4096 k: 8

adding 512 elements took 188ms
checking 10000 elements took 1801ms

267 elements probably in the filter.
9733 elements not in the filter.
0.026700 false positive rate.

All done!
```

##### `tests/shell` using `socat`

It does not fail on invalid arguments

```
Reset CPU (into user code)
Programming done.
socat - open:/dev/ttyUSB0,b115200,echo=0,raw
Timeout in expect script at "child.expect('test_shell.')" (tests/shell/tests/01-run.py:67)

/home/harter/work/git/RIOT/tests/shell/../../Makefile.include:605: recipe for target 'test' failed
make: *** [test] Error 1
make: Leaving directory '/home/harter/work/git/RIOT/tests/shell'
```

Where in master, `socat` was called with incompatible arguments

```
BOARD=msba2 make -C tests/shell/ test
make: Entering directory '/home/harter/work/git/RIOT/tests/shell'
socat -tg -p "/dev/ttyUSB0"
2019/08/27 14:23:55 socat[7360] E unknown option "-p"; use option "-h" for help
/home/harter/work/git/RIOT/Makefile.include:566: recipe for target 'term' failed
make[1]: *** [term] Error 1
Unexpected end of file in expect script at "child.expect('test_shell.')" (tests/shell/tests/01-run.py:67)
```
#### `lobaro-lorabox`

The `term` command is still the same for `lobaro-lorabox` as in `master`
I do not have a board to do the real test

```
BOARD=lobaro-lorabox RIOT_CI_BUILD=1 make --no-print-directory -C tests/bloom_bytes/ info-debug-variable-TERMFLAGS
-p /dev/ttyUSB0 -b 115200 --set-rts 0
```

Which gives this execution

```
BOARD=lobaro-lorabox RIOT_CI_BUILD=1 make --no-print-directory -C tests/bloom_bytes/ term | head -n 3
/home/harter/work/git/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyUSB0" -b "115200" --set-rts 0
Twisted not available, please install it if you want to use pyterm's JSON capabilities
Connect to serial port /dev/ttyUSB0
Cannot connect to serial port /dev/ttyUSB0: could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
```

### Issues/PRs references

* https://github.com/RIOT-OS/RIOT/issues/12089
* https://github.com/RIOT-OS/RIOT/issues/12090
* Used as base for https://github.com/RIOT-OS/RIOT/pull/12094

### CODE REVIEW

**Comment by maribu** [comment]
I can confirm that the terminal still works on the MSB-A2.

The flags for `picocom` for the MSB-A2 are ` --lower-rts --lower-dtr` btw.

**Comment by maribu** [comment]
I have no lobaro-lorabox to test. If someone would do this, I'd ACK

**Comment by MrKevinWeiss** [comment]
I think the lobaro-lorabox is a bit more challenging.  It seems like it needs the rts cleared to actually work.  It does compile and connected but the bloombytes test doesn't actually execute...  This is for both socat and picocom, it does work with pyterm.

**Comment by MrKevinWeiss** [comment]
If this is the case then maybe we just throw an error or say `RIOT_TERMINAL=pyterm` for that board?

**Comment by MrKevinWeiss** [comment]
I confirmed that you must toggle the rts to get the board running at all.  Just plugging in will not allow it to execute (though battery power is fine).

**Comment by MrKevinWeiss** [comment]
We could maybe change the flash script to leave the RTS cleared after so it would work if just flashed (meaning if could work for running all the tests).

**Comment by maribu** [comment]
If special requirements for the terminal interface are more commen than exclusively these two boards, how about adding special variables like `TERM_CLEAR_RTS`. The build system could translate these into the correct flags for the supported terminals. That whay support for new terminals could be added without having to touch every board's Makefile again.

**Comment by maribu** [comment]
> We could maybe change the flash script to leave the RTS cleared after so it would work if just flashed (meaning if could work for running all the tests).

`picocom` seems to set RTS on start unless a flag says different. So that would not work for all terminal programs

**Comment by cladmi** [comment]
> I think the lobaro-lorabox is a bit more challenging. It seems like it needs the rts cleared to actually work. It does compile and connected but the bloombytes test doesn't actually execute... This is for both socat and picocom, it does work with pyterm.

This PR does not address any compatibility with the other terminals, it just prevents sending arguments that do not match the program.

> We could maybe change the flash script to leave the RTS cleared after so it would work if just flashed (meaning if could work for running all the tests).

This would also not work after unplugging the board I guess.

**Comment by MrKevinWeiss** [comment]
Yup, if it is out of scope then that is fine.  Consider the lobaro-lorabox tested and expected to fail and another PR can take care of updating that.  Probably by one of the people that have it!
ping @leandrolanzieri @jia200x @me

**Comment by cladmi** [comment]
Thank you for the review.

**Pull request merged**
