### PR TITLE
cpu: rename SAM3X8E to SAM3

### PR DESCRIPTION
**Pull request by haukepetersen**
`sam3x8e` is a specific CPU model while `sam3` is the actual family of devices. As #3180 is introducing a second member to this family, I would say it makes sense to merge this PR to create a solid foundation and reduce code duplication from the beginning.

This PR collides slightly with #3191, but I don't care which one we merge first...

### CODE REVIEW

**Comment by kaspar030** [comment]
travis complains about doxygen. Either we overlooked them when initially commiting, or the path's need to be changed in the ignore lists.

**Comment by haukepetersen** [comment]
adjusted doxygen

**Comment by haukepetersen** [comment]
dammit, overlooked a file...

**Comment by haukepetersen** [comment]
Hm, why does a simple renaming end up in a fixing orgy of unrelated code?

**Comment by haukepetersen** [comment]
should be fixed now.

**Comment by haukepetersen** [comment]
rebased after #3191 was merged.

**Comment by haukepetersen** [comment]
rebased and adjusted to recently merged PWM driver (#3170)

**Comment by sgso** [comment]
Are you sure about this? I don't think this is going to work. Is SAM3S supposed to use the same includes (pio, instance, component) as SAM3X? There are some differences, grep for peripheral select registers "ABCDSR" for example.

**Comment by haukepetersen** [comment]
Pretty sure. There is just one thing I forgot: the includes need of course to be put in a sub-folder named after the CPU_MODEL, so the current files in pio, instance and component need to be moved into something like sam3/include/sam3x8e/...

**Comment by sgso** [comment]
Then this totally makes sense and I'd ask you to do that so I can start working on my part :+1:

**Comment by haukepetersen** [comment]
done.

**Comment by sgso** [comment]
What about the doxygen group names? cpu_sam3 for everything in this folder?

**Comment by haukepetersen** [comment]
yes. Will fix

**Comment by haukepetersen** [comment]
rebased and fixed doxygen group.

**Comment by haukepetersen** [comment]
rebased again.

**Comment by A-Paul** [comment]
Just wondering, https://github.com/haukepetersen/RIOT/commit/2588a62d89867eab80cbd6f19edc1f11d66cf4a7 will require adaption every time the atmel header files are updated. Or will they stay in that version?

**Comment by A-Paul** [comment]
Tested pwm driver. Works like before.

**Comment by haukepetersen** [comment]
@A-Paul: not sure I understand your first question: that commit actually just enables the inclusion of headers for other sam3xxx family members (by putting those in other sub-folders). So from the point of updating, nothing actually changes...

**Comment by sgso** [comment]
I think the question was aimed at how you are including the platform specific headers. I would have expected some cpu conditional include that doesn't need any editing of the original files. But frankly I don't care. I doubt they that they'll ever change in any meaningful way at all. What exactly is stalling this PR?

**Comment by A-Paul** [comment]
@haukepetersen: Sorry, I overlooked your query https://github.com/RIOT-OS/RIOT/pull/3194#issuecomment-113561563 for a while.
My concern was the modification of the original "sam3x8e.h" and the relative include paths. It has to be redone, ***if*** those header files would be updated. And whoever make this update may not be aware of the required changes.
I'm just always getting a little bit nervous when changing external files without documenting it. :-)

**Comment by haukepetersen** [comment]
@A-Paul: I understand, but I don't see that as too much of trouble. Once you want to update the headers, just do a quick diff between the existing and the new headers and you see right away, where the RIOT specific changes were made...

**Comment by thomaseichinger** [comment]
Seems good to me. ACK & Go

**Pull request merged**
