### PR TITLE
net/gnrc,auto_init: Add prerequisites for NDN-RIOT module

### PR DESCRIPTION
**Pull request by cawka**
Necessary hooks to enable [NDN-RIOT module](https://github.com/named-data-iot/ndn-riot)

### CODE REVIEW

**Comment by OlegHahm** [comment]
Woohoo, I can't wait to see NDN-RIOT in action. :)

However, I think it would make sense, to update the Makefile.dep and auto_init only once the module exists.

Do you plan to add it as a package or merge directly into RIOT? (Actually, I have several questions... Maybe we can discuss tomorrow.)

**Comment by mfrey** [comment]
What's the current status of the PR? Is there anything I can help out with?

**Comment by miri64** [comment]
ping?

**Comment by smlng** [comment]
@cgundogan how is this related to #5914, or can it be closed?

**Comment by cgundogan** [comment]
yes, this PR is superseded by #5914

**Pull request closed without merging**
