### PR TITLE
drivers/sx127x: uncrustify code

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

When working on #16177, I took some "inspiration" from the sx127x driver and where I found lots of style issues. This PR is fixing them by running uncrustify on related files:

```
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace drivers/sx127x/*.c
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace drivers/include/sx127x.h
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace tests/driver_sx127x/main.c
```

All files are whitelisted in the uncrustify check.

### Testing procedure

A green CI

### Issues/PRs references

None

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
Looks mostly good, there are still some uncrustify errors reported in the code view.

**Comment by aabadie** [comment]
> there are still some uncrustify errors reported in the code view.

Any idea why ? I just ran uncrustify on those files, so why does the CI report different issues ?

**Comment by leandrolanzieri** [comment]
> Any idea why ? I just ran uncrustify on those files, so why does the CI report different issues ?

I'm not sure. I also don't get the changes suggested by the CI. Version: `Uncrustify_d-0.72.0_f`

**Comment by kfessel** [comment]
more than one time i got the hint that the uncrustify that is checking the PRs is outdated

**Comment by aabadie** [comment]
> Version: Uncrustify_d-0.72.0_f

Mine is `Uncrustify-0.71.0_f`.
In riot/riotbuild docker image, the version is even older:

```
$ docker run --rm -ti riot/static-test-tools  uncrustify --version
Uncrustify-0.66.1_f
```

I'll try with this one.

**Comment by aabadie** [comment]
So indeed, the version doesn't behave the same... I adapted the PR original post with the new commands I used.

**Comment by kaspar030** [comment]
> I'll try with this one.

I'd rather uncrustify with 0.72 and ignore the warning. That way we have correctly indented code but false positives in CI output, compared to wrongly formatted code and false negatives once CI is using 0.72.

**Review by fjmolinas — APPROVED** [review]
ACK, binaries remain unchanged, if we switch untrusty versions later then we can update the nitpicks.

**Pull request merged**
