### PR TITLE
pkg/relic: add patch, fix missing new line

### PR DESCRIPTION
**Pull request by smlng**
required for #6600

### CODE REVIEW

**Comment by smlng** [comment]
@tfar I think its from the upstream, but if this is fixed upstream we need to update the package in RIOT (with patches and so on) <- if you could/would take of that?!

**Comment by tfar** [comment]
Can take a look at that next weekend.

**Comment by smlng** [comment]
@tfar maybe you can create a `riot` branch in your fork that has all the required changes in it, and we can use the latest commit of that branch in the RIOT relic package. This would also help to simplify future update of the package, as you can rebase on upstream master and adapt + we don't need to patch in RIOT. What do you think?

**Comment by smlng** [comment]
@OlegHahm can you've a look and approve, its only minor but needed to get llvm working, see #6600. Hopefully @tfar can update the package in general soonish, but until then I'd like to get llvm finished and enabled in Jenkins.

**Comment by smlng** [comment]
ping! @tfar: any news on patching this upstream and update package version in RIOT?

**Comment by smlng** [comment]
closing in favor of #6965 ...

**Pull request closed without merging**
