### PR TITLE
drivers: partial use of constness when accessing device descriptor

### PR DESCRIPTION
**Pull request by aabadie**
This PR tries to make use of `const` with device descriptor pointer when possible.
Only basic drivers have been updated. Still remain:
* radio drivers
* sd card driver
* mtd driver

I split the PR in 'atomic' commits for each modified drivers to simplify review but I can squash in one if needed.

### CODE REVIEW

**Comment by gebart** [comment]
Great job! Thanks for cleaning up the driver implementations.

**Comment by gebart** [comment]
Let's see what Murdock says.
@aabadie I guess you used some kind of scripted assistance to generate the change set? 

I guess this should be fine as long as everything still compiles, since the change is from relaxed code into a stricter style. I did not review all of the changes manually, a cursory review must still be performed even for this kind of robotic change.

**Comment by aabadie** [comment]
Well, I made the change manually. I don't see an easy automatic of doing that, since not all the use of pointer can be consted. I think it was faster by hand, but boring ;)

**Comment by aabadie** [comment]
I rebased and removed the change in mtd to make Murdock pass. @gebart, do you want me to squash into a single commit ?

**Comment by smlng** [comment]
I would recommend to squash, as this addresses a single issue.

**Comment by aabadie** [comment]
squashed

**Comment by aabadie** [comment]
@smlng, I think you can merge this one

**Comment by aabadie** [comment]
Thanks. This gives reviewers another thing to check in device drivers :)

**Comment by smlng** [comment]
that's your responsibility now 😛

**Comment by haukepetersen** [comment]
>  This gives reviewers another thing to check in device drivers :)

Would you mind to include this in the checklist(s) accumulated on this page: https://github.com/RIOT-OS/RIOT/wiki/Guide:-Writing-a-device-driver-in-RIOT

Thx!

**Comment by aabadie** [comment]
> Would you mind to include this in the checklist(s) accumulated on this page

Done. Also renamed netdev2 => netdev

**Comment by haukepetersen** [comment]
thanks!

**Pull request merged**
