### PR TITLE
doc: add graphic to vision page

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
@maribu proposed on Matrix to add a graphic to the vision documentation page imported from the wiki. I had this graphic still flying around from a talk I did and I think it is fitting.

### Testing procedure
Read the generated doc.

### Issues/PRs references
Follow-up on #20491

### CODE REVIEW

**Review by maribu — APPROVED** [review]
I like this *a lot*. Thx! :)

We might want to not hit merge just yet and rather allow for others to have a look as well.

**Comment by waehlisch** [comment]
thinking about to integrate this web page additionally into riot-os.org, some black lines would be shown on black background. can we find a way to maximize reuse of the content?

**Comment by waehlisch** [comment]
>  couldn't we just use a white background for the vision section on the website? 
>
right, the body part of the text could be in white bg color

then consider the comment as a reminder that we should reuse structured data as much as possible ;).

**Comment by miri64** [comment]
> then consider the comment as a reminder that we should reuse structured data as much as possible ;).

I can add classes so that the style may be overwritten with external CSS. Have to think however, how to integrate this in the doxygen.

**Comment by miri64** [comment]
I added some minimal CSS and classes. However, how to change that externally (without doing a `sed` on the SVG) is anyone's guess. Most current browsers neither seem to support importing external CSS for imported SVGs or using the HTML's CSS for imported SVGs. :-/

**Comment by miri64** [comment]
> Most current browsers neither seem to support importing external CSS for imported SVGs or using the HTML's CSS for imported SVGs. :-/

(And Doxygen's usage of XHTML doesn't make the situation any better)

**Comment by mguetschow** [comment]
Quoting @chrysn from matrix discussion:

> Maybe even throw in a Zephyr and/or a FreeRTOS in as well? (it's 5 RIOTs, we'd still have 3/5 and thus the absolute majority in the embedded space)

I'd second this to emphasize on IoT interoperability, but it might need some highlighting/explanation in the text, too.

**Comment by miri64** [comment]
> Quoting @chrysn from matrix discussion:
> 
> > Maybe even throw in a Zephyr and/or a FreeRTOS in as well? (it's 5 RIOTs, we'd still have 3/5 and thus the absolute majority in the embedded space)
> 
> I'd second this to emphasize on IoT interoperability, but it might need some highlighting/explanation in the text, too.

I steered away from this, mainly because using foreign logos might raise some trademark issues (at least the Zephyr logo is a registered trademark, did not look up FreeRTOS). For the android logo, it does not seem to be the official one (see [here](https://commons.wikimedia.org/wiki/File:Android_logo_(2007-2014).svg), for Tux we might need to add a Copyright notice, if not already provided (will have a look).

**Comment by maribu** [comment]
Maybe it would even underline the intended message better to not pick zephyr/FreeRTOS/other concrete OS, but rather add some generic "other OS using standard internet protocols" node.

**Comment by miri64** [comment]
> Maybe it would even underline the intended message better to not pick zephyr/FreeRTOS/other concrete OS, but rather add some generic "other OS using standard internet protocols" node.

If you provide me with a design for that: Can do! :grin:

**Comment by miri64** [comment]
In the act of attributing the foreign logos correctly, I restructured the whole graphic to be more structural (any clipart is now its own defined path which then is only `<use>`'d in the graphic) and used only classes for styling. A “dark background” version of the graphic can be rendered by changing the stroke colors in `#vision-division-line` and `.vision-house-line` to white and the fill color for `.vision-text` to white. Just while writing this, I noticed that Tux might disappear with black background. Will provide a fixup for that!

**Comment by miri64** [comment]
Done, there is now a thin white border around tux.

**Pull request merged**
