### PR TITLE
CI: enable LLVM in Jenkins

### PR DESCRIPTION
**Pull request by smlng**
this PR enables all tests on native using LLVM toolchain, it depends on ~~#6598~~ #6609.

### CODE REVIEW

**Comment by smlng** [comment]
@gebart now LLVM fails when compiling `tests/unittests/` with: 
```
kernel_init.c:58:18: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
    if (LOG_INFO <= LOG_INFO) printf("main(): This is RIOT! (Version: " "buildtest" ")\n");
                 ^
1 error generated.
```

you see this error too?`

**Comment by gebart** [comment]
Well it is a tautological comparison, so it should be fixed (LOG_INFO ==
LOG_INFO)

**Comment by gebart** [comment]
But no, I did not see the same error.

**Comment by smlng** [comment]
@gebart Jenkins uses `clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)`, so its a bit older than yours (3.9.x something, IIRC?).

**Comment by smlng** [comment]
needs #6612

**Comment by smlng** [comment]
and #6606

**Comment by kYc0o** [comment]
Can we try to get this merged before #6673 ?

**Comment by smlng** [comment]
nope, there are more parts missing.

**Comment by smlng** [comment]
separated commits into extra PR #6752

**Comment by smlng** [comment]
closing as memo, as we go for Murdock 2 instead Jenkins - at least for the time being

**Pull request closed without merging**
