### PR TITLE
CI: copy bors configuration from master

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

This will allow merging PRs again.

Just copies the file from master using `git checkout master -- bors.toml`.

*edit* Also cherry-picks the workflow change that enables the static tests that bors waits for, for the release branch.

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
bors merge

**Comment by kaspar030** [comment]
bors priority=1
bors merge

**Comment by kaspar030** [comment]
"alle guten Dinge sind drei"

bors merge

**Comment by maribu** [comment]
bors ping

**Comment by kaspar030** [comment]
bors merge

**Comment by kaspar030** [comment]
ok, this was stalled on static-tests and tools-test. The release branch was missing the commit that enables those for staging. :/
I've added it here.

**Comment by kaspar030** [comment]
bors merge

**Comment by maribu** [comment]
The static tests failed due to a codespell update. It seems we need to backport d9cde1466926a45360130007d526c8d7f10258c5 for it to pass

**Comment by maribu** [comment]
https://github.com/RIOT-OS/RIOT/pull/19044 is the backport needed to let statics tests passing. If we would get the addition of `bors.toml`, the update of the `murdock.yml` and the fix of the typos into the same merge train, the build should succeed...

**Comment by maribu** [comment]
bors retry

**Comment by kaspar030** [comment]
bors merge

**Pull request merged**
