### PR TITLE
boards: remove non-existent feature 'config'

### PR DESCRIPTION
**Pull request by haukepetersen**
The config feature is as far as I can see not used anywhere. So I propose dropping it...

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Sorry, I accidentally hit "approve" but wanted to give @kaspar030 or @OlegHahm the chance to have a look

**Comment by kaspar030** [comment]
Config has been removed with #5756.

**Comment by gebart** [comment]
examples/default/Makefile has a line FEATURES_OPTIONAL += config

**Comment by haukepetersen** [comment]
fixed in #8021

**Pull request merged**
