### PR TITLE
[RFC] make: Move ENABLE_DEBUG from file to module context

### PR DESCRIPTION
**Pull request by authmillenon**
Just an idea I had floating around in my head for a few weeks.

### CODE REVIEW

**Comment by authmillenon** [comment]
Since they both proposed a logging API I would like to here @LudwigOrtmann's and @kaspar030's opinion, too.

**Comment by OlegHahm** [comment]
Sounds useful to me.

**Comment by LudwigOrtmann** [comment]
I have no real opinion here.

I would still add `ENABLE_DEBUG` lines to specific files for debugging purposes because I prefer the finer granularity. E.g.: I wouldn't want debug messages for all of native or for all of core because there are too many.
As a matter of fact, I tend to enable individual debug lines more often by changing them into `printf` than I am changing `ENABLE_DEBUG`.
As this PR does not prevent me from using the debug system as I did before, I am OK with it.

**Comment by authmillenon** [comment]
@LudwigOrtmann as you've said: you still can do this. Even individual silencing is still possible.

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by OlegHahm** [comment]
Maybe it makes sense to bring this topic up on the devel mailing list before we agree on it.

**Comment by OlegHahm** [comment]
I reassign to someone with a stronger opinion on this.

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by authmillenon** [comment]
Seems like noone has either a real strong opinion for it or is strongly against it. Will close.

**Pull request closed without merging**
