### PR TITLE
ethos: explicitly ignore syscall return values

### LINKED ISSUE #4927: dist/tools/ethos: ignoring return value of write
The following warnings show up when building ethos in master:
```
dist/tools/ethos (master|✔)(328/251)% make
cc -O3 -Wall ethos.c -o ethos
ethos.c: In function ‘main’:
ethos.c:320:33: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                                 write(tap_fd, serial.frame, serial.framebytes);
                                 ^
ethos.c:323:33: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                                 write(STDOUT_FILENO, serial.frame, serial.framebytes);
                                 ^
ethos.c:356:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             write(serial_fd, &delim, 1);
             ^
ethos.c:358:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             write(serial_fd, &delim, 1);
             ^
ethos.c:371:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 write(serial_fd, head, sizeof(head));
                 ^
ethos.c:373:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 write(serial_fd, &delim, 1);
                 ^
ethos.c: In function ‘_send_hello’:
ethos.c:249:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(serial_fd, head, sizeof(head));
     ^
ethos.c:250:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(serial_fd, serial->local_l2_addr, 6);
     ^
ethos.c:251:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(serial_fd, &delim, 1);
     ^
ethos.c: In function ‘_clear_neighbor_cache’:
ethos.c:258:5: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
     system(tmp);
     ^
ethos.c: In function ‘_write_escaped’:
ethos.c:230:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 write(fd, out, 2);
                 ^
ethos.c:236:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 write(fd, out, 2);
                 ^
ethos.c:240:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 write(fd, &c, 1);
                 ^
```
Version info:
```
% cc --version
gcc (Gentoo 5.3.0 p1.0, pie-0.6.5) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by OlegHahm**
fixes #4927

### CODE REVIEW

**Comment by kaspar030** [comment]
Usually I would never do something like this, but in this case:

- half-sent frames don't brake the protocol and pose no problem
- a died file descriptor will be noticed at the next read

So I'd be fine if it silences the compiler.

**Comment by OlegHahm** [comment]
> Usually I would never do something like this, but in this case

It's your code. ;)

**Comment by kaspar030** [comment]
> It's your code. ;)

Yeah, I mean, not checking the return code is one thing, forcing the compiler to silence the explicitly requested warning another. ;)

**Comment by OlegHahm** [comment]
Yes, implementing it this way is sloppy, silencing the compiler is being aware of this sloppiness. ;-)

**Comment by haukepetersen** [comment]
no changes for my compiler:
```
ethos.c:320:33: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                                 (void) write(tap_fd, serial.frame, serial.framebytes);
                                 ^
ethos.c:323:33: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                                 (void) write(STDOUT_FILENO, serial.frame, serial.framebytes);
                                 ^
ethos.c:356:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             (void) write(serial_fd, &delim, 1);
             ^
ethos.c:358:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
             (void) write(serial_fd, &delim, 1);
             ^
ethos.c:371:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 (void) write(serial_fd, head, sizeof(head));
                 ^
ethos.c:373:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 (void) write(serial_fd, &delim, 1);
                 ^
ethos.c: In function ‘_send_hello’:
ethos.c:249:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     (void) write(serial_fd, head, sizeof(head));
     ^
ethos.c:250:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     (void) write(serial_fd, serial->local_l2_addr, 6);
     ^
ethos.c:251:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     (void) write(serial_fd, &delim, 1);
     ^
ethos.c: In function ‘_clear_neighbor_cache’:
ethos.c:258:5: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
     (void) system(tmp);
     ^
ethos.c: In function ‘_write_escaped’:
ethos.c:230:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 (void) write(fd, out, 2);
                 ^
ethos.c:236:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 (void) write(fd, out, 2);
                 ^
ethos.c:240:17: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                 (void) write(fd, &c, 1);
```

**Comment by emmanuelsearch** [comment]
So why do we close this?
To many users, these warnings will look scary and may assume the stuff actually does not work.
@kaspar030 did I miss something or is there a plan to get rid of the warnings?

**Comment by OlegHahm** [comment]
Closed because this patch doesn't solve the problem.

**Comment by emmanuelsearch** [comment]
OK. Sorry I was mistaken (thought it was the issue, not the PR ;)

**Pull request closed without merging**
