### PR TITLE
default example: reduce packet buffer size to 512b

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK and go

**Comment by kaspar030** [comment]
512? Isn't that a bit limiting? I thought anything less than 1280b was against the standards.

**Comment by authmillenon** [comment]
What standards? `default` does not include any IPv6, only link-layer. The shell buffer only excepts 64 bytes so any more than that should be more than enough to handle the payload given by `txtsnd`.

**Comment by OlegHahm** [comment]
I was even thinking about going even lower, but didn't have time for thorough testing and decided to be better safe than sorry.

**Comment by kaspar030** [comment]
Ok, no network stack, of course its fine then.

**Pull request merged**
