### PR TITLE
fmt: Remove unused pwr function

### PR DESCRIPTION
**Pull request by gebart**
Leftovers after cleanup

### CODE REVIEW

**Comment by smlng** [comment]
duplicate, already included in either #7499 or #7263 - we should really merge one of those instead. Both bring further enhancements.

**Comment by aabadie** [comment]
> IMHO duplicate

I don't see it as an issue. The change is minimal and ok to me so we can merge that one fast.
You'll have to rebase your PRs afterwards.

**Comment by smlng** [comment]
> so we can merge that one fast.

why not move the other PRs forward, too? They bring size optimisations *and* new features. 

Otherwise we can start picking apart other open PRs for sub-fixes as well, and duplicate work all over.

**Comment by gebart** [comment]
This fixes the compilation issue with unused function on llvm. The rebase should be fairly trivial after this is merged.

**Comment by smlng** [comment]
> rebase should be fairly trivial 

sure, but that wasn't the point ... anyway, go ahead, I'll dismiss my review

**Comment by aabadie** [comment]
and go

**Pull request merged**
