### PR TITLE
cpu/atmega: use power.h defines instead of direct register access

### LINKED ISSUE #7422: Provide a generic way for PRR in atmega_common instead of MEGA_PRR
The `atmega1284p` (and probably others too) has more than one PRR register (from the avr libs I can tell that there are up to three: PRR0, PRR1, PRR2). At the moment there is only a single PRR register (MEGA_PRR) used / implemented.

Instead I suggest using `avr/power.h` that wraps all of this nicely!

### PR DESCRIPTION
**Pull request by roberthartung**
fixes #7422

### CODE REVIEW

**Comment by kYc0o** [comment]
Go!

**Comment by kYc0o** [comment]
Well... I was about to merge but the commit title is ambiguous. Can you change it to something like "cpu/atmega: use power.h defines instead of direct register access"

**Comment by roberthartung** [comment]
@kYc0o done :-)

**Comment by kYc0o** [comment]
Uhm... not the title, the commit 😄

**Comment by kYc0o** [comment]
And if in your description you write "fixes #7422" the issue will be closed automagically.

**Comment by roberthartung** [comment]
@kYc0o sorry ;-) So commit message should be "cpu/atmega: use power.h defines instead of direct register access and fixes #7422" ?

**Comment by kYc0o** [comment]
Commit message only "cpu/atmega: use power.h defines instead of direct register access" and in the PR description you put at the beginning "fixes #7422". Sorry for not being more explicit. This information is somewhere on the PR guidelines or coding conventions, so it's good if you take a look there if you have doubts on how to code or how to make a PR.

**Comment by roberthartung** [comment]
@kYc0o Done :)

**Comment by lebrush** [comment]
@kYc0o Why did this got merged so fast!!!???? Almost no time for review (3h time window). 

IMO this complicates definition of peripheral in the "new" style using structs and will fill the code of `#if` `#else`. See #7542 as an example.

Now four more defines are required:

```C
#define power_pwm0_enable power_timer0_enable 
#define power_pwm0_disable power_timer0_disable
#define power_pwm1_enable power_timer1_enable 
#define power_pwm1_disable power_timer1_disable
```

And they will have to be rewritten every time the struct changes. Furthermore, it requires now extra code:


```C

if (dev == 0) {
    power_pwm0_enable();
}
else if (dev == 1) {
    power_pwm1_enable();
}
```

And this will happen for every single peripheral defined in the "new" style if we do not want to list all of them. I'm not sure this is an advantage in all the situations.

I disagree with part of this PR and suggest to revert the merge. The functions should be used whenever possible but should not be a must. Makes no sense. Besides they are simple defines which do the same thing.

**Comment by roberthartung** [comment]
@lebrush why does this require #if / #else? The defines will be inlined and will take care of the correct PRR register for different peripherals, IMO this is way cleaner.

**Comment by lebrush** [comment]
I meant `if` `else` sorry, corrected.

**Comment by roberthartung** [comment]
Just noticed PWM is obviously a timer... my bad! You're right about the little "overhead" but IMO this still keeps it consistent across all atmega-based CPUs!

**Comment by roberthartung** [comment]
@lebrush We need an if/else anyway for pm_block / pm_unblock, so this would integrate nicely.

See https://github.com/roberthartung/RIOT/blob/hartung/boards/inga/cpu/atmega_common/periph/timer.c

**Comment by lebrush** [comment]
(for the timers please see my comment in #7542)

I've no issue with defining an interface for the PRR registers, but I don't think the one defined in `avr/power.h` is the best since it has hardcoded names. I think, that much more better option would be to use two methods (enable/disable) which accept one parameter, this parameter being what to enable or disable (TIMER0, ADC, ...). The implementation (maybe per CPU) could be a simple `switch`, or the parameters (preferably an enumeration) defined in an intelligent way so it can easily be mapped and resolved with a couple of `if`s. If the code is small enough could even be an inline in `periph_cpu.h`. This is how it was done for stm32 platforms and I think is really nice approach, since it still brings flexibility of "direct" PRR access but provides an interface. What do you think about it?

**Comment by kYc0o** [comment]
Well I propose to bring back the defines for `PRR` to be used in other contexts, but leave the power.h function calls as is.

**Comment by roberthartung** [comment]
Do we actually need the `PRR`registers when the new atmega timer api provides the required abstraction?

**Comment by kYc0o** [comment]
Apparently @lebrush need it to simplify his code, that was the problem of merging this too fast.

**Pull request merged**
