### PR TITLE
boards/sensebox_samd21: refactor to use stdio over the USB port

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

While working on #15983, I noticed that the dependencies of the sensebox_samd21 board were included from Makefile.include, and this is not needed anymore. This PR fixes that as a first step.
But looking into this board support a bit more, it appears that this board come with a preflashed arduino bootloader, similar to the sodaq, arduino-mkr, etc boards. So this PR uses the same logic for these boards here as well: stdio should be reachable automatically via the usb port, no need for a USB to serial adapter. That should make things easier.

### Testing procedure

- Green CI
- The board can be flashed with bossa and stdio is available via the USB port

### Issues/PRs references

Found while working on #15983

### CODE REVIEW

**Comment by fjmolinas** [comment]
Looks good but only @leandrolanzieri has the board AFAIK, can you give it a quick test?

**Comment by leandrolanzieri** [comment]
> can you give it a quick test?

Sure!

**Comment by leandrolanzieri** [comment]
Works like a charm
```
$ env BOARD=sensebox_samd21 PROGRAMMER=bossa make flash-only term

stty -F /dev/ttyACM0 raw ispeed 1200 ospeed 1200 cs8 -cstopb ignpar eol 255 eof 255
sleep 2
/home/leandro/Work/RIOT/dist/tools/bossa-1.9/bossac -p /dev/ttyACM0 -o 0x2000 -e -i -w -v -b -R /home/leandro/Work/RIOT/examples/hello-world/bin/sensebox_samd21/hello-world.bin
Device       : ATSAMD21x18
Version      : v1.1 [Arduino:XYZ] Feb 19 2018 11:31:39
Address      : 0x0
Pages        : 4096
Page Size    : 64 bytes
Total Size   : 256KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
BOD          : true
BOR          : true
Erase flash

Done in 0.863 seconds
Write 15944 bytes to flash (250 pages)
[==============================] 100% (250/250 pages)
Done in 0.085 seconds
Verify 15944 bytes of flash
[==============================] 100% (250/250 pages)
Verify successful
Done in 0.189 seconds
Set boot flash true
sleep 2
/home/leandro/Work/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"  
2021-02-25 10:56:19,830 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2021-02-25 10:56:20,834 # ards/sensebox_samd21_enh)
2021-02-25 10:56:20,835 # Hello World!
2021-02-25 10:56:20,837 # You are running RIOT on a(n) sensebox_samd21 board.
2021-02-25 10:56:20,839 # This board features a(n) samd21 MCU.

```

**Review by fjmolinas — APPROVED** [review]
ACK, changes are sound and @leandrolanzieri was able to test.

**Comment by fjmolinas** [comment]
Thanks @aabadie and thanks for testing @leandrolanzieri!

**Pull request merged**
