### PR TITLE
docu: enhance timer config docu for cc26x0

### PR DESCRIPTION
**Pull request by smlng**
see discussion in #7335

Updates timer configuration documentation for CC26x0 and copy-pasta to the boards timer config.

### CODE REVIEW

**Comment by haukepetersen** [comment]
looks good, thanks. Should we apply the same comment also to the other cc2538 based boards, e.g. openmote and remote?

**Comment by smlng** [comment]
> Should we apply the same comment also to the other cc2538 based boards

not yet, because that one isn't based on that assumption yet -> its older but I'm reworking that accordingly, see #7361.

Btw. in theory we could have a `cpu/cc_common` and unify most peripheral drivers, *but* currently many defines for registers and stuff are named differently.

**Comment by smlng** [comment]
with unify, I meant for TI cc26x0 and cc2538

**Comment by smlng** [comment]
@haukepetersen, anything to add?

**Comment by haukepetersen** [comment]
all green -> go

**Pull request merged**
