### PR TITLE
gnrc: remove duplicate nomac from Makefile

### PR DESCRIPTION
**Pull request by OlegHahm**
See sys/MakefileL16

### CODE REVIEW

**Comment by authmillenon** [comment]
You removed the wrong one. https://github.com/RIOT-OS/RIOT/blob/master/sys/Makefile#L16 is the outdated one.

**Comment by authmillenon** [comment]
If you're at it: I think you can remove the old `nomac` module in total, too.

**Comment by authmillenon** [comment]
Just checked: it is already removed.

**Comment by OlegHahm** [comment]
oops

**Comment by OlegHahm** [comment]
No, I removed the intended one, but linked the wrong one: ng_nomac exists twice. But I will remove the old nomac, too

**Comment by authmillenon** [comment]
ACK. Please squash

**Pull request merged**
