### PR TITLE
tools: add edbg support

### PR DESCRIPTION
**Pull request by kaspar030**
This PR adds support for [edbg](https://github.com/ataradov/edbg) as flasher.

edbg flashes much faster than openocd:

```
real    0m3.550s
user    0m0.893s
sys     0m0.130s
```

vs

```
real    0m13.890s
user    0m0.813s
sys     0m0.287s
```

This is currently optional and must be selected by setting ```EDBG=edbg``` e.g., on the command line.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Very nice, the edbg tool beats openocd when flashing by millions of seconds :-)

**Comment by haukepetersen** [comment]
I think I would prefer to change the `samr21-xpro/Makefile.include` to something like:
```
...

# if available, use edbg for flashing, otherwise we use openocd
ifeq (edbg,$(PROGRAMMER))
    # set edbg device type
    EDBG_ARGS += -t atmel_cm0p
    ifneq (,$(SERIAL))
        EDBG_ARGS += "--serial $(SERIAL)"
    endif
    include $(RIOTMAKE)/tools/edbg.inc.mk
else
    include $(RIOTMAKE)/tools/openocd.inc.mk
endif
```
This way we are more in line with some other boards (e.g. `mulle`, `remote', ...). We could also also think of moving the `SERIAL` part into `edbg.inc.mk`, as all ARM boards support the `edbg`/`CMSIS_DAP` interface support the serial identification part... Now that I think of that, I think I would even prefer to move it...

**Comment by aabadie** [comment]
Adding some rules to build it in automatically in dist/tools/edbg could help.

**Comment by kaspar030** [comment]
> Now that I think of that, I think I would even prefer to move it...

Yeah, I'm just realizing that all sam0 boards have 20 lines duplicated...

**Comment by kaspar030** [comment]
This is now based on #7068 and #7080.

I set edbg as default, as it is so much faster and compiles flawlessly on Linux and OS X.

@haukepetersen I'm using pkg.mk for checking out edbg, you could do that for bossa, too.

**Comment by haukepetersen** [comment]
nice, will look into adjusting the bossa stuff once the dependencies for this PR are in...

**Comment by kaspar030** [comment]
> nice, will look into adjusting the bossa stuff once the dependencies for this PR are in...

There's no need to wait, you can just set some variables and include pkg.mk, instead of directly cloning as done in the bossac PR. That way you'd  share common git checkout makefile code.

**Comment by haukepetersen** [comment]
done, #7068 should be ready to be merged then...

**Comment by kaspar030** [comment]
Dependencies are merged, ready for testing!

**Comment by haukepetersen** [comment]
Works as expected. There is one thing though that we might want to consider: do we really want to switch using the new `edbg` tool as default flasher? As this is fine locally, are there any cross-dependencies for things like the `iotlab` testbed or the CI or similar?

**Comment by kaspar030** [comment]
> do we really want to switch using the new edbg tool as default flasher? As this is fine locally, are there any cross-dependencies for things like the iotlab testbed or the CI or similar?

Can't say for the iotlab. CI doesn't flash at the moment, and will actually benefit from locally compiled flash tool. :)

**Comment by kaspar030** [comment]
- amended compile fix

**Comment by aabadie** [comment]
> Can't say for the iotlab

It will be a problem when IoTLab will officially support samr21-xpro. It's already the case but the 'port' on the gateway code assumes OpenOCD as programmer. It won't be too difficult to switch to edbg, we just need to provide the tool on the gateways and open A8 images.

**Comment by haukepetersen** [comment]
So how do we proceed? Should we stick with openocd as default flash tool and switch to `edbg` once the iotlab does have support for this, or do we switch to `edbg` per default now and @aabadie takes care of adding the tool to the A8 nodes afterwards?

**Comment by kaspar030** [comment]
> Can't say for the iotlab
> It will be a problem when IoTLab will officially support samr21-xpro. It's already the case but the 'port' on the gateway code assumes OpenOCD as programmer. It won't be too difficult to switch to edbg, we just need to provide the tool on the gateways and open A8 images.

How does it assume it? "make flash" works as before. So should custom flashing using an elf and openocd.

**Comment by aabadie** [comment]
> How does it assume it?

This is the way it's implemented (for the moment) in the IoTLab gateway code.

By the way, I think it's safe for the moment since IoTLab has no official support for samr21. So let's merge this one.

**Comment by haukepetersen** [comment]
Awesome, so go!

**Comment by kaspar030** [comment]
>> How does it assume it?
> This is the way it's implemented (for the moment) in the IoTLab gateway code.

I mean, in what way? :)

**Pull request merged**
