### PR TITLE
pkg/ccn-lite: bump version and adapt shell functions accordingly

### LINKED ISSUE #11948: examples: ccn-lite-relay example broken
#### Description
The standard CCN-lite example in RIOT does not behave as expected: when sending interests

#### Steps to reproduce the issue
Run the `examples/ccn-lite-relay` example application on `native`, its enough to do so on a single node.

Next create some contents and afterwards send interests asking for these contents, and also send interests for some random names, where no content exists.

#### Expected results
The interests send for the contents we created should return the actual content we put in the content store. The interest for the random names should time out at some point.

#### Actual results
Any interest we send simply returns the first content we added to the content store:
```
main(): This is RIOT! (Version: 2019.10-devel-185-g2be13)
Basic CCN-Lite example
> ccnl_cs
ccnl_cs
> ccnl_cs /hello hello
ccnl_cs /hello hello
> ccnl_cs /moin moin
ccnl_cs /moin moin
> ccnl_cs
ccnl_cs
CS[0]: /moin [-1]: moin
CS[1]: /hello [-1]: hello
> ccnl_int /moin
ccnl_int /moin
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: moin
~~ PKT    -  1 snips, total size:   4 byte
> ccnl_int /hello
ccnl_int /hello
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: moin
~~ PKT    -  1 snips, total size:   4 byte
> ccnl_int /blubbblabla
ccnl_int /blubbblabla
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: moin
~~ PKT    -  1 snips, total size:   4 byte
> ccnl_int /hello
ccnl_int /hello
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: moin
~~ PKT    -  1 snips, total size:   4 byte
```
similar:
```
main(): This is RIOT! (Version: 2019.10-devel-185-g2be13)
Basic CCN-Lite example
> ccnl_cs
ccnl_cs
> ccnl_cs /hello hello
ccnl_cs /hello hello
> ccnl_cs /moin moin
ccnl_cs /moin moin
> ccnl_cs
ccnl_cs
CS[0]: /moin [-1]: moin
CS[1]: /hello [-1]: hello
> ccnl_int /blubb
ccnl_int /blubb
PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: GNRC_NETTYPE_CCN_CHUNK (2)
Content is: moin
~~ PKT    -  1 snips, total size:   4 byte
```

#### Versions
Build under Linux Mint 18.3, `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609`

### PR DESCRIPTION
**Pull request by PeterKietzmann**
### Contribution description

This PR bumps the CCN-lite pkg version and adapts to recent API changes in the `sc_ccnl` shell command handler. I've tested the new version briefly in small multi-hop setups under native and in the FIT IoT-LAB testbed on iotlab-m3 nodes. Thereby I did some requests to differently named content items that (i) exist (ii) don't exist (iii) are generated during retransmission procedure. Everything went as expected.

### Testing procedure
(follow description in #11948)

### Issues/PRs references
Fixes #11948

### CODE REVIEW

**Comment by miri64** [comment]
However, there seem to be some problems with CCN-lite when compiled for ARM with LLVM (see Murdock output)

**Comment by miri64** [comment]
Usually adding something like

```Makefile
ifeq (llvm,$(TOOLCHAIN))
  CFLAGS += -Wno-char-subscripts
endif
```

to the `pkg`'s Makefive should suffice (see e.g. [`emb6`](https://github.com/RIOT-OS/RIOT/blob/master/pkg/emb6/Makefile)). I don't know though if CMake likes that.

**Comment by PeterKietzmann** [comment]
I got green lights now.

**Comment by miri64** [comment]
Then let's go

**Pull request merged**
