### PR TITLE
sys/shell: fixed and unified doxygen headers

### PR DESCRIPTION
**Pull request by haukepetersen**
- changed doxygen group name to sys_shell
- added some missing fields
- unified the doxygen header format

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
doxygen does not complain

**Comment by LudwigOrtmann** [comment]
Can't read the diff without getting a blurry vision - didn't find anything to complain.

ACK, merge when Travis is happy.

**Comment by authmillenon** [comment]
Can you confirm that there are no more references to the group names @haukepetersen removed left? (`git grep` helps)

**Comment by haukepetersen** [comment]
@authmillenon, there are none to my knowledge...

**Comment by haukepetersen** [comment]
kicked Travis

**Comment by LudwigOrtmann** [comment]
confirmed, except for `x86-irq`, but that seems to be correct.

**Comment by authmillenon** [comment]
However, I think I prefer to have the shell commands in their own sub-group.

**Comment by LudwigOrtmann** [comment]
Doesn't really matter as long as these docs aren't generated anyways..

**Comment by LudwigOrtmann** [comment]
@authmillenon up to you whether you want to push sub-groups.

**Comment by authmillenon** [comment]
I'd vote for yes, since you can have `shell` without he `shell_commands` module

**Comment by haukepetersen** [comment]
so going with a separate `shell_commands` group it is?

**Comment by authmillenon** [comment]
Yes, please :-)

**Comment by PeterKietzmann** [comment]
This can be a Hack'n'ACK candidate, right :-) ?

**Comment by haukepetersen** [comment]
yes.

**Comment by haukepetersen** [comment]
done.

**Comment by authmillenon** [comment]
ACK when travis is dancing

**Comment by authmillenon** [comment]
(please squash first ;-))

**Comment by haukepetersen** [comment]
done.

**Pull request merged**
