### PR TITLE
pkg: iotivity: temporarily remove

### PR DESCRIPTION
**Pull request by kaspar030**
The examples just don't build, so as discussed offline, I propose removing them for the release, and let them go through a proper review.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Yes, that's what we discussed. ACK from my side once Murdock agrees. @emmanuelsearch d'accord? 
Hmm, the branch has a conflict in examples/iotivity_examples/client_switch/client_switch.c

**Comment by kaspar030** [comment]
I fixed the rebase conflict (#6403 had changed a file that got deleted by this PR). Merge at will!

**Comment by rzr** [comment]
OK I will see what can I do later,

For now I am waiting for this merge and will try again when @kmaloor merges it
https://github.com/01org/tinycbor/pull/61

BTW I am linking to this page
http://wiki.iotivity.org/examples

If anyone want to share the effort of supporting more examples

**Comment by kmaloor** [comment]
@emmanuelsearch @kaspar030 

Just wanted to report back that I have addressed all of the warnings in
IoTivity-Constrained's source, and
@rzr  's patch to tinyCBOR https://github.com/01org/tinycbor/pull/61
was merged in as well.

I am now able to successfully build the IoTivity-Constrained
stack against RIOT-OS with both the native and samr21-xpro BSPs with their default
toolchain options (I used to previously filter out Werror, etc. for a successful build).

So, we might be good to go as far as IoTivity-Constrained is concerned…

At this point, it seems like just the RIOT-OS package and examples that were in the tree
might need some updating/altering.

@mattiantonini  Could you update the package per what was discussed at the end of this thread:
https://github.com/RIOT-OS/RIOT/issues/6241

If there’s no activity on this in a few weeks, I’ll work on it.
If any of you choose to work on it, please copy me when there are questions.

Hopefully we can go through the proper review process this time. I’d very much like 
for the project to have a package and samples in RIOT-OS.

**Comment by emmanuelsearch** [comment]
@mattiantonini @kmaloor @rzr what's the latest on this? (now that the release is out ;)

**Comment by rzr** [comment]
Sorry I was a bit busy with FOSDEM lately ( https://fosdem.org/2017/schedule/event/iot_iotivity/ )
FYI, I didnt use RIOT but baremetal on arduino but I'd like to replace that part with IC on RIOT.

I'll see if I can find time to test it again, in upcoming weeks maybe.

Let's sync with @kmaloor

**Pull request merged**
