### PR TITLE
tests/cpp_ctors: move tests-cpp_ctors out of unittests

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

This moves 'unittests/tests-cpp_ctors' to its own test.
It prevents requiring 'cpp' in the 'unittests' that forced almost all
architectures to link the unittests with `g++`.
It also removes the need to have disabled tests for architectures.

### Testing procedure«

The test should be run on boards to verify it is working for them.

For me the tests works locally on native, samr21-xpro, iotlab-m3:

```
main(): This is RIOT! (Version: 2019.10-devel-416-gb0462-pr/tests/unittests/move_cpp_test)
...
OK (3 tests)
```

And it works on my local test server with:

```
cc2650-launchpad frdm-k64f frdm-kw41z msba2 mulle nrf52dk nucleo-f103rb pba-d-01-kw2x sltb001a stm32f3discovery
```

EDIT: `msba2` does not work but was disabled before anyway.

#### Unittests:

The unittests that were working before keep working.

```
native iotlab-m3 frdm-k64f mulle nrf52dk
```

### Issues/PRs references

Part of https://github.com/RIOT-OS/RIOT/issues/10187 and fixes that all unittests are build with `g++` https://github.com/RIOT-OS/RIOT/issues/10187#issuecomment-523003354

### CODE REVIEW

**Comment by cladmi** [comment]
Squashed.

**Comment by cladmi** [comment]
(this one will also need to update https://github.com/RIOT-OS/RIOT/pull/11680 to remove the RIOT_CI_WHITELIST += all)

**Comment by kaspar030** [comment]
Nice one!

**Comment by cladmi** [comment]
I just noticed that the `msba2` is failing, I must have missed to execute the test on it…

Is it really providing `cpp` ? I will open an issue after this.

**Comment by cladmi** [comment]
Damn the failures that were hidden because of the `cpp` required feature.

This would be fixed with https://github.com/RIOT-OS/RIOT/pull/12038 that moved the `crypto` test out and blacklisted the boards there.

I could split #12038 if required, or just wait for that one before this one here.

**Comment by cladmi** [comment]
@maribu This now enabled the `cpp_ctors` tests that were disabled in `unittests` for `msba2` and it appears that they do not work… Any idea where it could come from ?

I currently blacklisted the `armv7` boards as they were also blacklisted for the `cpp_ctors` test. So it is not blocking but I am curious.

Also global question as we talked about it on Monday in another context.
Is a board allowed to provide the `cpp` feature if it does not support the constructors? If it is the case, then we should add a 'cpp_ctors' feature.

**Comment by jcarrano** [comment]
> Is a board allowed to provide the cpp feature if it does not support the constructors? 

No. I don't see any reason why one would be willing to tolerate C++ without global constructor and at the same time for them being that hard to implement.

**Comment by maribu** [comment]
> @maribu This now enabled the `cpp_ctors` tests that were disabled in `unittests` for `msba2` and it appears that they do not work… Any idea where it could come from ?
> 
> I currently blacklisted the `armv7` boards as they were also blacklisted for the `cpp_ctors` test. So it is not blocking but I am curious.
> 
> Also global question as we talked about it on Monday in another context.
> Is a board allowed to provide the `cpp` feature if it does not support the constructors? If it is the case, then we should add a 'cpp_ctors' feature.

@cladmi: I have no idea. But have a look at https://github.com/RIOT-OS/RIOT/pull/12059. This will help significantly with debugging the MSB-A2 :-)

**Comment by jcarrano** [comment]
Squash.

**Comment by cladmi** [comment]
I squashed and removed the `TEST_ON_CI_WHITELIST += all` as it is now by default.

**Comment by cladmi** [comment]
And rebased as it needed #12308 to work.

**Comment by cladmi** [comment]
I silenced the static-test, and will squash directly to not waste testing.

**Comment by cladmi** [comment]
Not compiling in tests-pkt, missing malloc header…
Is RIOT even working on non 32bit platforms ?…

I blacklisted the 8bit and 16 bit boards. It is not part of this change to make them work.

**Comment by cladmi** [comment]
Github is not showing my updated commits… it looks dead.

**Comment by maribu** [comment]
> Github is not showing my updated commits… it looks dead.

From time to time Github fails to show commits, show them in their correct order and the like after force push. This is a known issue: https://help.github.com/en/articles/why-are-my-commits-in-the-wrong-order

**Comment by cladmi** [comment]
It was having issues with the notifications according to https://www.githubstatus.com/

**Comment by maribu** [comment]
> It was having issues with the notifications according to https://www.githubstatus.com/

Didn't Microsoft recently acquire Github? What a coincidence :-D

**Comment by jcarrano** [comment]
> Not compiling in tests-pkt, missing malloc header…
Is RIOT even working on non 32bit platforms ?…

Which board gives that error? I see msp430 boards seem not to have libstdc++ (nothing we can do about that) and `arduino-uno` shows `undefined reference to `__cxa_guard_acquire'` which seems to be related to the C++ standard being used.

In any case, I think it is quite acceptable (and honest) for us to say that C++ is not supported on those platforms.

**Comment by cladmi** [comment]
Now it is working and only fails due to the `fixup` commit in static-tests that fixed a typo https://github.com/RIOT-OS/RIOT/pull/12040/commits/72b118c81a427798475f6e0b5914854240f179ba

I squash to get the normal CI result.

**Pull request merged**
