### PR TITLE
pkg/libfixmath checkout fixes

### PR DESCRIPTION
**Pull request by gebart**
basename -a is not supported on Travis.
Also added -q to svn command line to suppress printing each filename to stdout.

### CODE REVIEW

**Comment by phiros** [comment]
ACK. Merge when travis is green.

BTW: Also tried the changes on top of my verbose_buildtest branch. Your PR reduces the
number of false warnings quite a bit.

**Comment by gebart** [comment]
I don't understand the Travis failure on native. Everything else completes green on Travis. libfixmath_unittests builds for native on my machine.

**Comment by OlegHahm** [comment]
@authmillenon, @phiros, @LudwigOrtmann, wasn't this a known issue where some of you recently told me the explanation?

**Comment by authmillenon** [comment]
I don't know what you are talking about. Are you sure it was me?

**Comment by OlegHahm** [comment]
No, I don't remember who it was - could have been you, but apparently not.

**Comment by phiros** [comment]
This problem is connected to #3408 it has nothing to with the changes in this PR.

**Comment by gebart** [comment]
Adding a dependency on svn-info.xml didn't help..

**Comment by gebart** [comment]
@phiros you were right, though the problem is not the internal dependencies inside tests/libfixmath_unittests, but between tests/libfixmath and tests/libfixmath_unittests
I managed to reproduce the error by opening two terminals and running `make BOARD=native -j4` in both simultaneously so that they both start to clone the SVN repo at the same time.

```
Building application "libfixmath" for "native" with MCU "native".

"make" -C .../riot/pkg/libfixmath
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy '.../riot/pkg/libfixmath/checkout/trunk-r91' locked.
svn: E155004: '.../riot/pkg/libfixmath/checkout/trunk-r91' is already locked.
Makefile:56: recipe for target '.../riot/pkg/libfixmath/checkout/trunk-r91/svn_info.xml' failed
make[1]: *** [.../riot/pkg/libfixmath/checkout/trunk-r91/svn_info.xml] Error 1
.../riot/tests/libfixmath/../../Makefile.include:233: recipe for target '.../riot/tests/libfixmath/bin/native/libfixmath.a' failed
make: *** [.../riot/tests/libfixmath/bin/native/libfixmath.a] Error 2

```

**Comment by gebart** [comment]
merging in spite of errors, the errors are caused by a race condition in the pkg/libfixmath makefile which makes svn checkout fail sometimes.

**Comment by gebart** [comment]
(the race condition is out of scope for this PR)

**Pull request merged**
