### PR TITLE
core: cleaned up and simplified reboot interface

### PR DESCRIPTION
**Pull request by haukepetersen**
I created this PR to continue the discussion from #3242 on a code example.

@OlegHahm wrote:

> 1. I think the parameter was originally introduced for POSIX or BSD compatibility reasons.
> 2. Calling *_arch() from outside the kernel feels wrong for me.

My thoughts are the following:

1. I was not able to find any usage of the reboot interface w.r.t. POSIX or BSD. So if this is needed, I would say to write a (4line) wrapper modul for reboot somewhere in `sys` and stick with the simplified reboot version for internal use
2. At first it did for me, too. But by thinking about it, I find it not so bad. For one, the user always knows, that he/she is using hardware dependent functionality. But even more important, it prevents weird structures as we use them currently for the interrupt_xxx functions (see `core/arch/irq_arch.h`).

Are there any ideas on solving this in a nicer way?

### CODE REVIEW

**Comment by OlegHahm** [comment]
> I was not able to find any usage of the reboot interface w.r.t. POSIX or BSD.

I was referring to https://github.com/RIOT-OS/RIOT/pull/822.

> But even more important, it prevents weird structures as we use them currently for the interrupt_xxx functions (see core/arch/irq_arch.h).

You mean the defines? I think we could leave with that.

**Comment by haukepetersen** [comment]
ok, I did not know about #822. Though I would actually argue against it: In my opinion is efficiency on embedded platforms (most?) important - so why force all platforms to use a slightly less efficient signature just because this makes implementation for BSD systems easier? And regarding (POSIX) compatibility: I would always opt for a 'wrapper' module that can be used if needed instead of less efficient RIOT core interfaces...

> You mean the defines? I think we could leave with that

True, how about the changes from the last two commits?

**Comment by OlegHahm** [comment]
> ok, I did not know about #822. Though I would actually argue against it: In my opinion is efficiency on embedded platforms (most?) important - so why force all platforms to use a slightly less efficient signature just because this makes implementation for BSD systems easier?

To be honest: I don't care. Some bytes on the stack if you're going to reboot anyway, won't hurt, but as long if this doesn't break building native on BSD/OSX, I'm fine.

> True, how about the changes from the last two commits?

Looks good to me.

**Comment by cgundogan** [comment]
Adding `reboot` again without matching signatures with [1] does not fix the problem that this is not compliant with BSD/OSX.

[1] http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/reboot.2?query=reboot&sec=2

**Comment by cgundogan** [comment]
Just a Gedankenexperiment:
What if we change the signature of `reboot_arch` back to `int reboot_arch(int mode);`
and use `int reboot(int mode) __attribute__ ((weak, alias ("reboot_arch")));;`.

Or a second Gedankenexperiment:
Rename `reboot_arch` to `reboot` and adapt the signature as above? What is the idea to have a second layer?

**Comment by OlegHahm** [comment]
> What if we change the signature of reboot_arch back to int reboot_arch(int mode);
and use int reboot(int mode) __attribute__ ((weak, alias ("reboot_arch")));;

I'm in favor of avoiding any kind of compiler dependent extensions as much as possible.

**Comment by haukepetersen** [comment]
> I'm in favor of avoiding any kind of compiler dependent extensions as much as possible.

+1

**Comment by gebart** [comment]
I don't understand the problem. Why is it not possible to build on OSX? We're not doing a system `reboot` on native, are we?

**Comment by OlegHahm** [comment]
@gebart, IIRC the problem was more related to the build system including the "wrong" (i.e. the host's system header) and complaining about a differing prototype. This might be fixed by now.

**Comment by cgundogan** [comment]
is this PR still needed as a base for a discussion, or can I close it?

**Comment by haukepetersen** [comment]
From my side you can close it.

**Comment by cgundogan** [comment]
I close this because the discussion stalled or there is no need anymore for a discussion

**Pull request closed without merging**
