### PR TITLE
make: introduce PKGDIRBASE

### PR DESCRIPTION
**Pull request by kaspar030**
Previously, packages defined their build folder as ```$(BINDIRBASE)/pkg/$(BOARD)/<pkgname>```, and often used ```$(BINDIRBASE)/pkg/$(BOARD)/``` as part of their include part.

This PR introduces a new makefile variable ```$PKGDIRBASE```, centralizing the definition and making it overridable.

### CODE REVIEW

**Comment by gebart** [comment]
Btw, spelling on the commit message of the first commit.

**Comment by kaspar030** [comment]
> I think it would make sense to use PKG_DIR or PKG_BUILDDIR instead of PKGDIRBASE/package for the include paths. Thoughts?

A package's Makefile.include is being included from many Makefiles,, e.g., not necessarily from the package Makefile. Thus the package name is not known...

**Comment by gebart** [comment]
Ah, I see

**Comment by kaspar030** [comment]
> Btw, spelling on the commit message of the first commit.

fixed

**Comment by kaspar030** [comment]
Murdock is fine. This should be a low hanging fruit, someone feels like ACK'ing?

**Comment by kaspar030** [comment]
&go.

**Comment by kaspar030** [comment]
ups, since when does github enforce all CI's to be green?

**Comment by kYc0o** [comment]
I don't know but jenkins is failing since several days due to an error downloading ccn-lite. It tries so hard that the builds stay for around 45min, I suppose trying to get the package with long timeouts.

**Pull request merged**
