### PR TITLE
core mutex: use ATOMIC_VALUE for debug output

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by gebart** [comment]
ACK

**Comment by gebart** [comment]
core needs a second ACK

**Comment by kaspar030** [comment]
Well, this is in a block with IRQs disabled, so I think the value can be read directly. But it doesn't hurt either, so ACK.

**Comment by gebart** [comment]
@kaspar030 `mutex->val` is of type `atomic_int_t`, which is a struct, the actual value needs to be accessed using either the `ATOMIC_VALUE` macro or access the counter variable directly (i.e. `mutex->val->val` or something similar).

The recommended way is to use the `ATOMIC_VALUE` macro.

**Comment by kaspar030** [comment]
@gebart Ah right!

travis is green -> go!

**Pull request merged**
