### PR TITLE
boards/common/saml1x: configure UART on EXT1

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This adds the configuration for the UART found on EXT1

### Testing procedure

Connect PA8 & PA9 in loopback mode.
Initialize uart 1 and send some data. You should receive the sent data back.

```
> 2020-06-19 00:37:54,481 #  main(): This is RIOT! (Version: 2020.07-devel-1284-gdcda5-cpu/sam0_common/periph/uart-rxonly)
2020-06-19 00:37:54,481 # 
2020-06-19 00:37:54,484 # Manual UART driver test application
2020-06-19 00:37:54,487 # ===================================
2020-06-19 00:37:54,492 # This application is intended for testing additional UART
2020-06-19 00:37:54,498 # interfaces, that might be defined for a board. The 'primary' UART
2020-06-19 00:37:54,504 # interface is tested implicitly, as it is running the shell...
2020-06-19 00:37:54,504 # 
2020-06-19 00:37:54,510 # When receiving data on one of the additional UART interfaces, this
2020-06-19 00:37:54,515 # data will be outputted via STDIO. So the easiest way to test an 
2020-06-19 00:37:54,521 # UART interface, is to simply connect the RX with the TX pin. Then 
2020-06-19 00:37:54,527 # you can send data on that interface and you should see the data 
2020-06-19 00:37:54,529 # being printed to STDOUT
2020-06-19 00:37:54,529 # 
2020-06-19 00:37:54,533 # NOTE: all strings need to be '\n' terminated!
2020-06-19 00:37:54,533 # 
2020-06-19 00:37:54,788 # UARD_DEV(0): test uart_poweron() and uart_poweroff()  ->  [OK]
2020-06-19 00:37:54,788 # 
2020-06-19 00:37:54,789 # UART INFO:
2020-06-19 00:37:54,792 # Available devices:               2
2020-06-19 00:37:54,796 # UART used for STDIO (the shell): UART_DEV(0)
2020-06-19 00:37:54,797 # 
init 1 115200
2020-06-19 00:37:58,652 #  init 1 115200
2020-06-19 00:37:58,656 # Success: Initialized UART_DEV(1) at BAUD 115200
2020-06-19 00:37:58,911 # UARD_DEV(1): test uart_poweron() and uart_poweroff()  ->  [OK]
send 1 hello
2020-06-19 00:38:00,867 #  send 1 hello
2020-06-19 00:38:00,870 # UART_DEV(1) TX: hello
```

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
It seems that the `saml11-xpro` second uart doesn't work...  The tx works but the rx is not functioning. In the tests provided by @benpicco we cannot see any received message which should happen with loopback.

I tried getting it working by switching `GPIO_MUX_x` around so the uart_dev 0 was using `SERCOM0->USART` but that prevented any console interaction. The datasheet looks good.

Could it have something to do with the [isr mapping](https://github.com/RIOT-OS/RIOT/blob/master/cpu/sam0_common/periph/uart.c#L199)?

Maybe someone more familiar to have a look.

**Comment by dylad** [comment]
@MrKevinWeiss I confirm this issue.
This is only a guess but I think the following statement from Microchip datasheet has the answer:

>When Secure Pin Multiplexing is enabled, only the SERCOM1 pins from the above table become mapped.
All of the alternate SERCOM1 pins are kept in a Hi-Z configuration and cannot be selected.


All 3 SERCOMs of SAML11 are secured by default (Fuses configured). This is why only SAML11 is affected. I'll try to disable this to be sure.

**Comment by MrKevinWeiss** [comment]
Nice find... I spent too long not reading the datasheet :)

**Comment by dylad** [comment]
I just managed to set the fuse (PAC->NONSECC.bit.SERCOM1=1) using Atmel Studio 7. Afterwards, the SERCOM RX worked as expected !
So we should either change the second UART or set a notice somewhere to explain this.

**Comment by MrKevinWeiss** [comment]
How possible would it be to add this in RIOT somewhere.  It seems a bit silly to not be able to use any muxing.

**Comment by dylad** [comment]
FYI, user should be able to set the fuse manually through edbg tool. I didn't test it though.

**Comment by benpicco** [comment]
`PAC->NONSECC.bit.SERCOM1=1` can this be set at run-time?
We should at least add this bit to the board documentation.

**Comment by dylad** [comment]
>PAC->NONSECC.bit.SERCOM1=1 can this be set at run-time?

IIRC, I tried without any luck back then

**Pull request merged**
