### PR TITLE
pkg/nanopb: bump version to 0.4.1

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Update the version of the nanopb package to the [latest upstream release](https://github.com/nanopb/nanopb/tree/nanopb-0.4.1).

~~It didn't build with the Python3 patch applied, so I removed that. (I do have `python3-protobuf` installed).~~

### Testing procedure

Run `tests/pkg_nanopb`.

### Issues/PRs references

none

### CODE REVIEW

**Comment by kaspar030** [comment]
> It didn't build with the Python3 patch applied, so I removed that. (I do have `python3-protobuf` installed).

Which OS are you on? Does "python" point to "python3"?

**Comment by benpicco** [comment]
Ubuntu 19.04, `python` is Python 2.7.16

**Comment by benpicco** [comment]
Just want to check if this works on Murdock…

**Comment by benpicco** [comment]
[migration.rst](https://github.com/nanopb/nanopb/blob/master/docs/migration.rst#removal-of-bundled-plugin-proto) has the explanation:

> Removal of bundled plugin.proto
> -------------------------------
> 
> **Rationale:** Google's Python protobuf library, which is used in nanopb
> generator, has included `plugin_pb2` with it since version 3.1.0. It is
> not necessary to bundle it with nanopb anymore.
> 
> **Required actions:** Update `python-protobuf` to version 3.1.0 or newer.
> 
> **Error indications:** `ImportError: No module named compiler.plugin_pb2`

**Comment by benpicco** [comment]
I guess this can be fixed by installing `python-protobuf` in riotdocker and dropping the `0001-generator-nanopb_generator.py-use-python3.patch` patch.

**Comment by benpicco** [comment]
Good news!
looks like nanopb-0.4.1 fixed the issue with Python 3.
I can compile it locally with the Python 3 patch, let's see if Murdock agrees.

**Comment by benpicco** [comment]
Murdock is happy too.

**Pull request merged**
