### PR TITLE
drivers/include: add header for internal temperature periph driver

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description

This PR defines a small API to use MCU internal temperature sensor. Such sensors are available in several MCUs that RIOT support (e.g: Kinetis, STM32, nRF52, SAM0...)

The API is minimalist and only consist of an init and a read functions.

All comments are very welcome ! (especially about naming or API itself)

### Testing procedure
None.

### Issues/PRs references
None.

### CODE REVIEW

**Comment by benpicco** [comment]
Why limit this to internal temperature sensors?
The same API would also work for I2C based ones if the type was `temp_t ` instead 😉

**Comment by dylad** [comment]
> Why limit this to internal temperature sensors?
The same API would also work for I2C based ones if the type was temp_t instead

True but this job is already done by SAUL's API
MCU internal temperature sensor are usually a mere register read or an ADC read value.

**Comment by kaspar030** [comment]
> True but this job is already done by SAUL's API
> MCU internal temperature sensor are usually a mere register read or an ADC read value.

I share some doubts on putting this into `periph_` namespace, as well.

**Comment by dylad** [comment]
> I share some doubts on putting this into periph_ namespace, as well.

What would be suitable then ?

**Comment by kaspar030** [comment]
Discussed a bit on IRC.

@dylad chose to create this because there's no simple way (without adding many ifdefs etc) to initialize a SAUL driver: `In some case, the internal sensor needs calibration or a proper initialization I didn't know how to achieve this through the SAUL api. Of course this could be done through CPU or board init but there is already enough #ifdef in our codebase`

 I voiced concerns of adding another sensor API because of this: `I feel your pain... still, at the moment, saul is the way to provide a sensor API. Unfortunately that reqiures the initialization to be integrated into saul's ifdef rich auto init... But I must say that I think adding a temperature sensor api at this point would add another way to do this.
We'd end up with some drivers being only SAUL, some implementing periph_temp, some doing both, someone writing a periph_temp to saul module. And all that for mapping a simple adc read plus init/calibration...`

@dylad agrees with closing this PR.

**Pull request closed without merging**
