### PR TITLE
doc: Add Kconfig section [backport 2020.01]

### PR DESCRIPTION
**Pull request by leandrolanzieri**
# Backport of #13040

### Contribution description
This adds information regarding the usage of Kconfig from an user perspective and in-depth information on how it is currently integrated into RIOT's build system.

### Testing procedure
Run `make doc` and read 'Kconfig in RIOT' section.

### Issues/PRs references
None

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@fjmolinas, @aabadie what is the consensus of your discussion in #13040 about backporting documentation PRs? Personally, I think it doesn't hurt and it even improves the case that a user builds the doc on his own.

**Comment by aabadie** [comment]
> it even improves the case that a user builds the doc on his own.

which is very unlikely to happen...

**Comment by fjmolinas** [comment]
> which is very unlikely to happen...

Not really, a lot of documentation is markdown. I **never** check that online. And it is the case here.

**Comment by fjmolinas** [comment]
> Not really, a lot of documentation is markdown. I never check that online. And it is the case here.

I do not build it, but I do not check it online either.

**Comment by aabadie** [comment]
@fjmolinas, as a core maintainer, are you that often reading documentation on the release branch instead of master ? Because this is what backporting is about.

**Comment by kaspar030** [comment]
> backporting documentation PRs

The idea is to backport "fixes", not "missing features". We did backport fixes to mistakes in docs (during hard freeze). We did not so far backport PRs adding missing documentation.

But IMO, this is @fjmolinas's call, he's managing the release, and this is not something outrageously against our conventions. It just means more work within the release process.

**Comment by leandrolanzieri** [comment]
In this release we started the process of this new feature, but the release itself would not contain any explanation nor usage guides without this backport. I totally understand what @aabadie points out, that the latest docs are always online. But the release should be self-contained in this matter, take for instance someone who gets the [`.zip` version](https://github.com/RIOT-OS/RIOT/archive/2019.10.zip) of the release.

> It just means more work within the release process.

What's the extra work for adding this docs?

In any case, I'm OK with whatever @fjmolinas thinks is best here.

**Comment by aabadie** [comment]
Finally, it was decided to not backport this one, so closing it.

**Pull request closed without merging**
