### PR TITLE
drivers/mpu9150: adapt to new parameters initialization scheme + provide saul adaption

### PR DESCRIPTION
**Pull request by aabadie**
Similar to #7949, I applied the new init parameters scheme to the mpu9150. More refactoring would be needed on this one but I want to target unification of drivers first.

This PR also provides the SAUL adaption for this driver.

Related to #7519

### CODE REVIEW

**Comment by aabadie** [comment]
Tested on hardware, stills works (the temperature data is invalid, even in master....):
* *tests/driver_mpu9150* output:
```
2017-11-08 09:04:47,468 - INFO # Accel data [milli g] - X: -31   Y: -16   Z: 1059
2017-11-08 09:04:47,468 - INFO # Gyro data [dps] - X: 0   Y: 0   Z: 0
2017-11-08 09:04:47,469 - INFO # Compass data [mikro T] - X: -42   Y: -17   Z: -9
2017-11-08 09:04:47,469 - INFO # Temperature [milli deg] : 12655771
2017-11-08 09:04:47,469 - INFO # 
2017-11-08 09:04:47,470 - INFO # +-------------------------------------+
2017-11-08 09:04:48,430 - INFO # Accel data [milli g] - X: -34   Y: -17   Z: 1058
2017-11-08 09:04:48,433 - INFO # Gyro data [dps] - X: 0   Y: 0   Z: 0
2017-11-08 09:04:48,438 - INFO # Compass data [mikro T] - X: -40   Y: -18   Z: -9
2017-11-08 09:04:48,442 - INFO # Temperature [milli deg] : 12655933
```
* *examples/saul* output:
```
2017-11-08 09:12:07,335 - INFO # saul
2017-11-08 09:12:07,336 - INFO # ID	Class		Name
2017-11-08 09:12:07,338 - INFO # #0	SENSE_BTN	Button(B1 User)
2017-11-08 09:12:07,341 - INFO # #1	SENSE_ACCEL	mpu9150
2017-11-08 09:12:07,342 - INFO # #2	SENSE_GYRO	mpu9150
2017-11-08 09:12:07,344 - INFO # #3	SENSE_MAG	mpu9150
> saul read 1
2017-11-08 09:12:13,022 - INFO #  saul read 1
2017-11-08 09:12:13,026 - INFO # Reading from #1 (mpu9150|SENSE_ACCEL)
2017-11-08 09:12:13,027 - INFO # Data:	[0] -35mg
2017-11-08 09:12:13,028 - INFO # 	[1] -14mg
2017-11-08 09:12:13,030 - INFO # 	[2] 1048mg
> saul read 2
2017-11-08 09:12:16,253 - INFO #  saul read 2
2017-11-08 09:12:16,257 - INFO # Reading from #2 (mpu9150|SENSE_GYRO)
2017-11-08 09:12:16,258 - INFO # Data:	[0] 0.0dps
2017-11-08 09:12:16,259 - INFO # 	[1] 0.0dps
2017-11-08 09:12:16,260 - INFO # 	[2] 0.0dps
> saul read 3
2017-11-08 09:12:20,887 - INFO #  saul read 3
2017-11-08 09:12:20,890 - INFO # Reading from #3 (mpu9150|SENSE_MAG)
2017-11-08 09:12:20,892 - INFO # Data:	[0] -0.42Gs
2017-11-08 09:12:20,893 - INFO # 	[1] -0.20Gs
2017-11-08 09:12:20,894 - INFO # 	[2] -0.09Gs
```

**Comment by aabadie** [comment]
Thanks for reviewing @smlng !

It would be great if someone with an msbiot board could confirm it works. My test was with an I2C module wired with a nucleo board.

**Comment by smlng** [comment]
tested with nucleo board, too: works for `tests/driver_mpu9150` and `examples/saul` as well.

Re-ACK.

**Comment by aabadie** [comment]
Thanks @smlng. Btw, I was going through existing PRs yesterday and realized you have one opened already (#5484). What should we do in this case ?

**Comment by smlng** [comment]
> realized you have one opened already (#5484). What should we do in this case ?

that is an old one, but I will work on it (time given) - however, it also is more about supporting MPU6xyz and MPU9xyz with a generic driver, and not SAUL. So I'm fine with merging this right now and I'll adapt and reuse afterwards.

**Pull request merged**
