### PR TITLE
sys/hashes, sys/checksum: move fletcher* to checksum

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**
As there is a checksum module now, and the fletcher functions qualify as checksum functions and not as hash functions, move them to the appropriate module.

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
BTW: I am planning to add unittests and add checksum start value parameterized versions in a follow-up PR.

**Comment by LudwigKnuepfer** [comment]
I think it would be appropriate to rename the checksum module from `crc` to `checkusm` as far as identifiers go. Paths and Doxygen prefixes say `crc`... Are you OK if I do that as part of this PR?

**Comment by gebart** [comment]
@LudwigKnuepfer I agree with the ideas and I am OK with changing the module name in this PR as well

**Comment by gebart** [comment]
ACK for the move and the changes as they are right now, feel free to update with a module rename, or open a separate PR, your choice @LudwigKnuepfer

**Comment by OlegHahm** [comment]
Wait a minute.

**Comment by LudwigKnuepfer** [comment]
@OlegHahm I did.

**Comment by OlegHahm** [comment]
Sorry, breakfast cropped up. What I wanted to say: currently we differentiate between hash functions (including checksums and cryptographic hash functions), CRCs and crypto libraries. The first category (see http://doc.riot-os.org/group__sys__hashes.html) is derived from this [Wikipedia article](https://en.wikipedia.org/wiki/List_of_hash_functions). I don't argue re-renaming CRC to checksums again, but then one should update the documentation, too.

**Comment by LudwigKnuepfer** [comment]
Haha, I did not notice that it has been renamed and wondered why I chose such a bad identifier in the first place ;)

**Comment by LudwigKnuepfer** [comment]
@OlegHahm may I squash?

**Comment by OlegHahm** [comment]
You may.

**Comment by OlegHahm** [comment]
Care to add some unittests for Fletcher, too?

**Comment by LudwigKnuepfer** [comment]
I already started to write unittests, will open a follow-up PR soon.
Compare https://github.com/RIOT-OS/RIOT/pull/4808#issuecomment-183630071

**Comment by OlegHahm** [comment]
Oops, sorry, overlooked this comment.

**Comment by LudwigKnuepfer** [comment]
> I already started to write unittests, will open a follow-up PR soon.

https://github.com/RIOT-OS/RIOT/pull/4938

**Comment by OlegHahm** [comment]
Thanks!

**Pull request merged**
