### PR TITLE
doc: eliminate driver documentation warnings

### PR DESCRIPTION
**Pull request by OlegHahm**
Another issue addressing #2137. Eliminating about 140 warnings in `drivers`.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
If the last commeny by @authmillenon is wanted, this PR should be ready to merge or not? @fnack already ACKed...

**Comment by OlegHahm** [comment]
Will adapt.

**Comment by OlegHahm** [comment]
Updated

**Comment by PeterKietzmann** [comment]
I didn't really review :/ . @fnack are you willing to merge?

**Comment by OlegHahm** [comment]
Needs squashing before merging.

**Comment by fnack** [comment]
Just reviewed the changes after my last ACK. Looking good, ACK! Please squash and merge @OlegHahm.

**Comment by OlegHahm** [comment]
Squashed.

**Pull request merged**
