### PR TITLE
cdcacm: Activate data out endpoint on DTE present signal

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR modifies the CDC ACM code to signal the data out endpoint to be ready when the host has indicated that an application opened the serial console, DTE present in CDC ACM terminology.

This mainly prevents the code from calling the ready function when no USB host is present and at least after the low level endpoint is initialized by usbus. The downside is that the cdcacm struct requires a reference to the endpoint.

### Testing procedure

Verify that `tests/usbus_cdc_acm` is still working and that RIOT shell commands still work over the CDC ACM function.

### Issues/PRs references

Testing should be a bit easier with #12535 included

### CODE REVIEW

**Comment by dylad** [comment]
> The downside is that the cdcacm struct requires a reference to the endpoint.

Why add a reference to the out endpoint ? I thought this endpoint could be accessible through usbus_interface_t field ?

**Comment by bergzand** [comment]
> Why add a reference to the out endpoint ? I thought this endpoint could be accessible through usbus_interface_t field ?

Good point, however, I think I need a proper getter for that first. Something along the lines of
```
usbus_endpoint_t *usbus_interface_find_endpoint(usb_ep_type_t type, usb_ep_dir_t dir);
```
Which would return a reference to the first endpoint matching the spec. This way we don't depend too much on the order the endpoints are added to the interface.

**Comment by dylad** [comment]
> I think I need a proper getter for that first

I think this is the way to go, this is more generic and this may be reuse in another implementation later.

**Comment by bergzand** [comment]
rebased to include the descriptor bug fix from #12535

**Comment by bergzand** [comment]
And reordered the commits to keep stuff properly incremental

**Comment by benpicco** [comment]
This looks good, please squash.

**Comment by bergzand** [comment]
squashed!

**Pull request merged**
