### PR TITLE
boards/firefly: add renode configuration

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds a renode config file for the Zolertia firefly board. Since the hardware description (board and cpu) are already provided in Renode repository, the addition is pretty straight-forward.

### Testing procedure

- Install Renode (at least 0.9 is required), like [1.11 release](https://github.com/renode/renode/releases/tag/v1.11.0)
- Run `make BOARD=firefly -C examples/hello-world all emulate`

<p align=center>

</p>

### Issues/PRs references

Depends on #15486

### CODE REVIEW

**Comment by aabadie** [comment]
Rebased and no longer waiting for another PR. Still working.

**Comment by fjmolinas** [comment]
Out of the box I get::

```bash
/home/francisco/workspace/RIOT/dist/tools/renode/run-renode.sh start
### Starting Renode ###
/home/francisco/workspace/RIOT/dist/tools/renode/run-renode.sh: 47: cannot create /home/francisco/workspace/RIOT/examples/hello-world/bin/firefly/board.resc: Directory nonexistent
/home/francisco/workspace/RIOT/dist/tools/renode/run-renode.sh: 48: cannot create /home/francisco/workspace/RIOT/examples/hello-world/bin/firefly/board.resc: Directory nonexistent
18:40:52.0552 [INFO] Loaded monitor commands from: /home/francisco/opt/renode_portable/./scripts/monitor.py

```

**Comment by aabadie** [comment]
> Out of the box I get

You have to build once first, so should be `all emulate`. Sorry the testing procedure is not correct :)

**Comment by fjmolinas** [comment]
I get a lot of warnings, is that to be xpected:

```
<pre><font color="#C4A000">18:51:01.2176 [WARNING] nvic: Unhandled read from offset 0xD94.</font>
<font color="#C4A000">18:51:01.2189 [WARNING] nvic: Unhandled write to offset 0xD94, value 0x5.</font>
<font color="#C4A000">18:51:01.2263 [WARNING] nvic: Unhandled value written to System Control Register: 0x10.</font>
<font color="#C4A000">18:51:01.2264 [WARNING] nvic: Unhandled read from offset 0xD14.</font>
<font color="#C4A000">18:51:01.2264 [WARNING] nvic: Unhandled write to offset 0xD14, value 0x200.</font>
<font color="#C4A000">18:51:01.2303 [WARNING] sysbus: [cpu: 0x200CA2] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2098, value 0x1.</font>
<font color="#C4A000">18:51:01.2379 [WARNING] sysbus: [cpu: 0x200CA2] WriteDoubleWord to non existing peripheral at 0x400D40F8, value 0x1.</font>
<font color="#C4A000">18:51:01.2381 [WARNING] sysbus: [cpu: 0x200CA2] WriteDoubleWord to non existing peripheral at 0x400D40FC, value 0x1.</font>
<font color="#C4A000">18:51:01.2385 [WARNING] sysbus: [cpu: 0x200CA2] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.2386 [WARNING] sysbus: [cpu: 0x200CA2] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x10001.</font>
<font color="#C4A000">18:51:01.3066 [WARNING] sysbus: [cpu: 0x200CF8] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.3067 [WARNING] sysbus: [cpu: 0x200CF8] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x1.</font>
<font color="#C4A000">18:51:01.3172 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.3173 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x1.</font>
<font color="#C4A000">18:51:01.3173 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.3174 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x20001.</font>
<font color="#C4A000">18:51:01.3175 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.3175 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x0.</font>
<font color="#C4A000">18:51:01.3176 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1.</font>
<font color="#C4A000">18:51:01.3176 [WARNING] sysbus: [cpu: 0x200D0C] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2000, value 0x101.</font>
<font color="#C4A000">18:51:01.3531 [WARNING] sysbus: [cpu: 0x200E68] WriteDoubleWord to non existing peripheral at 0x400D4084, value 0x8.</font>
<font color="#C4A000">18:51:01.3532 [WARNING] sysbus: [cpu: 0x200E68] WriteDoubleWord to non existing peripheral at 0x400D4004, value 0x0.</font>
<font color="#C4A000">18:51:01.3580 [WARNING] gpioA: Unhandled write to offset 0x420. Unhandled bits: [1] when writing value 0x2. Tags: AFSEL (0x2).</font>
<font color="#C4A000">18:51:01.3581 [WARNING] sysbus: [cpu: 0x200FF8] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2028, returning 0x1.</font>
<font color="#C4A000">18:51:01.3583 [WARNING] sysbus: [cpu: 0x201000] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2028, value 0x1.</font>
<font color="#C4A000">18:51:01.3583 [WARNING] sysbus: [cpu: 0x201000] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D202C, returning 0x1.</font>
<font color="#C4A000">18:51:01.3584 [WARNING] sysbus: [cpu: 0x201000] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D202C, value 0x1.</font>
<font color="#C4A000">18:51:01.3584 [WARNING] sysbus: [cpu: 0x201000] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2030, returning 0x1.</font>
<font color="#C4A000">18:51:01.3585 [WARNING] sysbus: [cpu: 0x201000] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) WriteDoubleWord to non existing peripheral at 0x400D2030, value 0x1.</font>
<font color="#C4A000">18:51:01.3588 [WARNING] uart0: Unhandled write to offset 0xFC8, value 0x0.</font>
<font color="#C4A000">18:51:01.3595 [WARNING] sysbus: [cpu: 0x201036] (tag: &apos;SYS_CTRL_CLOCK_CTRL&apos;) ReadDoubleWord from non existing peripheral at 0x400D2000, returning 0x1. (2)</font>
<font color="#C4A000">18:51:01.3605 [WARNING] sysbus: [cpu: 0x200E28] WriteDoubleWord to non existing peripheral at 0x400D40F4, value 0x8.</font>
<font color="#C4A000">18:51:01.3611 [WARNING] sysbus: [cpu: 0x200E28] WriteDoubleWord to non existing peripheral at 0x400D40F0, value 0x8.</font>
<font color="#C4A000">18:51:01.3613 [WARNING] sysbus: [cpu: 0x200E28] WriteDoubleWord to non existing peripheral at 0x400D40EC, value 0x8.</font>
<font color="#C4A000">18:51:02.3865 [WARNING] nvic: Unhandled write to offset 0xD98, value 0x2.</font>
<font color="#C4A000">18:51:02.3865 [WARNING] nvic: Unhandled write to offset 0xD9C, value 0x20000280.</font>
<font color="#C4A000">18:51:02.3866 [WARNING] nvic: Unhandled write to offset 0xDA0, value 0x16060009.</font>
</pre>
```

and a hardfault:

```
main(): This is RIOT! (Version: 2021.01-devel-1084-gcfb77-pr-15489)
Hello World!
You are running RIOT on a(n) firefly board.
This board features a(n) cc2538 MCU.
*** RIOT kernel panic:
USAGE FAULT HANDLER
*** halted.
Inside isr -10
```

**Comment by fjmolinas** [comment]
Also `all` is not evaluated as a dependency to `emulate` when calling with `-j3`

**Comment by fjmolinas** [comment]
`examples/default` seems to work correctly:
```
main(): This is RIOT! (Version: 2021.01-devel-1084-gcfb77-pr-15489)
Welcome to RIOT!
> help
Command              Description
---------------------------------------
reboot               Reboot the node
version              Prints current RIOT_VERSION
pm                   interact with layered PM subsystem
ps                   Prints information about running threads.
saul                 interact with sensors and actuators using SAUL
> ps
 pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr
  | current     
   - | isr_stack            | -        - |   - |    512 (  188) (  324) | 0x2000000
0 | 0x200001c8
   1 | main                 | running  Q |   7 |   1536 (  644) (  892) | 0x2000028
4 | 0x2000080c 
     | SUM                  |            |     |   2048 (  832) ( 1216)
> pm
Usage:
 pm show: display current blockers for each power mode
 pm set <mode>: manually set power mode (lasts until WFI returns)
 pm block <mode>: manually block power mode
 pm unblock <mode>: manually unblock power mode
 pm off: call pm_off()
> reboot
main(): This is RIOT! (Version: 2021.01-devel-1084-gcfb77-pr-15489)
Welcome to RIOT!
> help
Command              Description
---------------------------------------
reboot               Reboot the node
version              Prints current RIOT_VERSION
pm                   interact with layered PM subsystem
ps                   Prints information about running threads.
saul                 interact with sensors and actuators using SAUL
> version
2021.01-devel-1084-gcfb77-pr-15489
> 
```

**Comment by aabadie** [comment]
> Also all is not evaluated as a dependency to emulate when calling with -j3

`all` is not a dependency of `emulate` yet :)

**Comment by aabadie** [comment]
> I get a lot of warnings, is that to be xpected:

Yes the warning are expected. But the hardfault is surprising, I don't have this. What is your version of renode ? (I have 1.11).

**Comment by fjmolinas** [comment]
> > I get a lot of warnings, is that to be xpected:
> 
> Yes the warning are expected. But the hardfault is surprising, I don't have this. What is your version of renode ? (I have 1.11).
> Can you also try with the cc2538dk (they are very similar) ?

I donwloaded the latest release, so 1.11. The hardfault shows up If I hit enter on the `hello-world` example

**Comment by aabadie** [comment]
I can reproduce the problem and it's also there with the cc2538dk. It might be an issue with the cc2538 definitions provided by renode or the peripheral driver in renode. Hard to tell without further investigations. Maybe @mgielda has an idea ?

**Comment by fjmolinas** [comment]
> I can reproduce the problem and it's also there with the cc2538dk. It might be an issue with the cc2538 definitions provided by renode or the peripheral driver in renode. Hard to tell without further investigations. Maybe @mgielda has an idea ?

If this comes from renode we can merge this but an issue should be opened in the original project. Is there documentaion on renode in RIOT? It would be nice to add a warning there.

**Comment by aabadie** [comment]
Regarding the hardfault, could it be a problem in RIOT:

https://github.com/RIOT-OS/RIOT/blob/19dabc9fd7a68cc0a7c1e42bfa04911ae5a56c2e/cpu/cc2538/periph/uart.c#L148-L155

The UART IRQ is enabled even though the rx callback is not defined. I'm not an expert with cc2538 but on stm32, the IRQ is only enabled with `rx_cb` is set:

https://github.com/RIOT-OS/RIOT/blob/19dabc9fd7a68cc0a7c1e42bfa04911ae5a56c2e/cpu/stm32/periph/uart.c#L219-L222

If I move the `NVIC_EnableIRQ` call in the `if` block, no more HardFault.

**Comment by fjmolinas** [comment]
> `if`

Hmm I can't reproduce the issue on a `cc2538dk`, so not sure if your fix is just hiding an issue or fixing it, but the change itself still makes sense. Lets go ahead with this one. Would you mind opening a follow up with that change?

**Review by fjmolinas — APPROVED** [review]
ACK.

**Comment by aabadie** [comment]
> Lets go ahead with this one. Would you mind opening a follow up with that change?

It's here: #15518

**Pull request merged**
