### PR TITLE
pkg: ccn-lite: minor changes to integrate latest ccn-lite features

### PR DESCRIPTION
**Pull request by cgundogan**
### Contribution description

Minor changes to the pkg integration of CCN-lite are necessary in order to be able to use the latest CCN-lite features.

I don't like version bumping the CCN-lite package every week. But these changes are necessary to use the latest CCN-lite master.

### Issues/PRs references
fixes https://github.com/cn-uofbasel/ccn-lite/issues/208

### CODE REVIEW

**Comment by mfrey** [comment]
Hi,

> I don't like version bumping the CCN-lite package every week. But these changes are necessary to use the latest CCN-lite master.

I totally agree, but since the last PKG version update in RIOT a few CVE's for CCN-;ite came up and subsequently fixes were provided. We probably should have a discussion about how to handle a few things in CCN-lite in the future.

Best
 Michael

**Comment by smlng** [comment]
> I don't like version bumping the CCN-lite package every week. But these changes are necessary to use the latest CCN-lite master.

I guess that applies to many packages from time to time, when there is lots of movement here (in RIOT) and in the package repo. So I agree, we might need to think about and discuss how to improve this process in the future.

One way procedure would be to review and update all third party packages only for an official release.

**Comment by aabadie** [comment]
> One way procedure would be to review and update all third party packages only for an official release.

We could also have a fork of the package somewhere (maybe in the RIOT-OS organisation) and in the package code, the version will point to a specific branch (maybe master?) of this fork, and not a specific commit.
Updating the package version will then just consist in updating the branch on the fork to make it point to the required upstream package version (commit).

**Comment by mfrey** [comment]
> We could also have a fork of the package somewhere (maybe in the RIOT-OS organisation) and in the package code, the version will point to a specific branch (maybe master?) of this fork, and not a specific commit.

Please don't do forks. RIOT probably should simply just stick to the current model. 

CCN-lite got most recently a new feature which allows to set additional parameters to NDN Interests. Unfortunately, this breaks the old API (hence, the "NULL" as a parameter to the ``ccnl_send_interest`` function call in ``sc_ccnl.c``). Usually, this should not happen so often.

**Comment by cgundogan** [comment]
>Updating the package version will then just consist in updating the branch on the fork to make it point to the required upstream package version (commit).

the last time I checked, this doesn't played well with the `gitcache` script we use

**Comment by cgundogan** [comment]
So what's the consensus on this? Merge now, or postpone to accumulate possible new changes?

**Comment by miri64** [comment]
I honestly have to say, that even I as a maintainer find it really intransparent with regards to what changed to go from $randomCommit to $randomCommit worst of all in a repository that is not mainline. This PR isn't moving a release to a random commit, so this discussion might be led elsewhere, but I would be really in favor that for *stable* software we move from release to release and have hot-fixes to the release (when possible) or **desperately** (the emphasis is on *desperately*) needed adaptions to RIOT provided as patches. Yes, most of our software is open source, and my solution doesn't really solve the problem for closed source either, but browsing through a (sometimes very erratic) git history is comparable to trying to reverse engineer closed source software ;-). Just my 2ct regarding `pkg` maintainance, but not blocking this particular PR for the moment, since I also know the state-of-the-art of CCN-lite ;-).

**Comment by mfrey** [comment]
@OlegHahm Could you please check if this fixes your [issues](https://github.com/cn-uofbasel/ccn-lite/issues/208)?

**Comment by OlegHahm** [comment]
Nope. My problems there are not even related to building ccn-lite for RIOT.

**Comment by OlegHahm** [comment]
> I honestly have to say, that even I as a maintainer find it really intransparent with regards to what changed to go from $randomCommit to $randomCommit worst of all in a repository that is not mainline. 

Sorry, I don't understand this sentence. What exactly is intransparent and which repository is not mainline?

> This PR isn't moving a release to a random commit, so this discussion might be led elsewhere,

Again I don't understand.

Personally, I don't see any problem with this PR or with updating the CCN-lite package whenever necessary. As far as I know there is not even a somewhat final specification for ICN released, so no-one should expect a stable software and I would consider this an experimental feature.

**Comment by miri64** [comment]
Maybe I wasn't clear enough, but I was referring to `pkg` in general, not CCN-lite in particular. With

> Just my 2ct regarding pkg maintainance, but not blocking this particular PR for the moment, since I also know the state-of-the-art of CCN-lite ;-).

I wanted to state, that I don't see CCN-lite as stable in any regard (and your statement regarding ICN is also true).

Regarding your comments:

>> I honestly have to say, that even I as a maintainer find it really intransparent with regards to what changed to go from $randomCommit to $randomCommit worst of all in a repository that is not mainline. 
>
> Sorry, I don't understand this sentence. What exactly is intransparent […]

There is only a SHA hash. Ideally for *stable* software we should only go from release tag to release tag (see e.g. lwIP) and have possible hot-fixes provided as patches (that is how Linux distributions usually maintain their packages) so that with the packages release notes and the fixes you have complete documentation what changed. A hash requires best case that you first have to look up at the `PKG_URL` what state the external package is at compared to the actual release and worst case that you also have to dig through jungle of commits of varying quality that the package maintainer provided to port to RIOT.

> […] and which repository is not mainline?

At least two were a trusted source would be very important IMHO: 

```
$ git grep github.com -- pkg/*/Makefile
pkg/tinydtls/Makefile:PKG_URL=https://github.com/rfuentess/TinyDTLS.git
pkg/tweetnacl/Makefile:PKG_URL=https://github.com/RIOT-OS/tweetnacl
…

TinyDTLS's mainline repository is [at https://git.eclipse.org/r/tinydtls/org.eclipse.tinydtls](https://projects.eclipse.org/projects/iot.tinydtls/developer), and TweetNACL is available [here](https://tweetnacl.cr.yp.to/software.html).

Especially for crypto it comes across very unprofessional to just fork it somewhere else and set "random" commits on top.

>> This PR isn't moving a release to a random commit, so this discussion might be led elsewhere,
>
> Again I don't understand.

As said in my initial paragraph: CCN-lite is unstable so this is a problem, but not a problem we should start fixing or discussing in this PR (see https://github.com/RIOT-OS/RIOT/issues/8736 for further discussion).

**Comment by kYc0o** [comment]
> Especially for crypto it comes across very unprofessional to just fork it somewhere else and set "random" commits on top.

At least for tweetNaCl there's no random commits. The repo explains very well why we forked it and adds the hashes (md5) of the original sources. Besides, it also adds information about the changes from the original sources.

**Comment by smlng** [comment]
can we move any ccn-lite **unrelated** discussion to #8736?

**Comment by miri64** [comment]
@kaspar030 what was your title change about?

**Comment by kaspar030** [comment]
> @kaspar030 what was your title change about?

typo (lastest -> latest)

**Comment by cgundogan** [comment]
@miri64 done

**Pull request merged**
