### PR TITLE
tests/sys/shell: increase the stack size of periodic thread

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description
Increase the stack of the periodic thread which is started with the `periodic` command of `tests/sys/shell`.
On LLVM toolchain, the test fails as only one tick occurs. With this patch the test works as intended.

The behavior of the LLVM is unclear to me here, as it seems there is some data corruption occurring on the stack. 

### Testing procedure

CI catches this, so let's run the test on CI once again.

### Issues/PRs references
See [CI tests](https://ci.riot-os.org/details/branch/master/tests)

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
Chances are high that this needs the `Makefile.ci` to be regenerated. You could to this using the script in `dist/tools/insufficient_memory` if this fails the Murdock pass.

**Comment by maribu** [comment]
Yep, the ATmega328P boards no longer fit.

**Comment by dylad** [comment]
round 2.

**Comment by dylad** [comment]
Thanks !

**Pull request merged**
