### PR TITLE
native: add debug-valgrind target

### PR DESCRIPTION
**Pull request by OlegHahm**
Starts valgrind in background and connect gdb to valgrind gdb-server.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@OlegHahm This PR is not tested by Travis right? Are you fine with removing the CI build tag?

**Comment by cgundogan** [comment]
can you briefly explain what I should type into the console to see how this functions? I called `make -B clean all debug-valrind` and then hit `continue` but it always hits another sigtrap/breakpoint apparently

**Comment by OlegHahm** [comment]
Maybe you should try compiling for valgrind? ;-)

`make -B clean all-valgrind debug-valgrind`

**Comment by OlegHahm** [comment]
Hm, maybe it actually does not work for any applications with a shell. How about introducing `valgrind-debug-server` and `valgrind-debug`?

**Comment by OlegHahm** [comment]
Split up and updated the README.

**Comment by OlegHahm** [comment]
@LudwigKnuepfer, maybe you're interested, too.

**Comment by cgundogan** [comment]
@OlegHahm I fail to test this. Can you briefly explain again how I can and should test this?

**Comment by cgundogan** [comment]
looks OK. ACK

**Comment by cgundogan** [comment]
please SQUASH

**Comment by OlegHahm** [comment]
squashed

**Comment by cgundogan** [comment]
please fix the whitespace error that travis complains about

**Comment by OlegHahm** [comment]
Fixed, squashed and force-pushed.

**Comment by cgundogan** [comment]
great - let's see what travis has to say about that tomorrow

**Pull request merged**
