### PR TITLE
cpu/cc2538: handle cc2538_rf deps in Makefile.dep

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Move handling of `cc2538_rf` deps to `cpu/cc2538` and use `cc2538_rf` as `netdev_default` (it was not pulled in when gnrc was not used).

### Testing procedure

Compile `examples/gnrc_networking` for one of the boards, everything should still be up and running:

`BOARD=openmote-b make -C examples/gnrc_networking flash cleanterm`

```
ifconfig
ifconfig
Iface  7  HWaddr: 6F:FF  Channel: 26  Page: 0  NID: 0x23
          Long HWaddr: 00:12:4B:00:14:B5:B5:AF 
           TX-Power: 0dBm  State: IDLE 
          AUTOACK  L2-PDU:102 MTU:1280  HL:64  RTR  
          6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::212:4b00:14b5:b5af  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffb5:b5af
          inet6 group: ff02::1a
          
          Statistics for Layer 2
            RX packets 0  bytes 0
            TX packets 12 (Multicast: 12)  bytes 502
            TX succeeded 0 errors 0
          Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 12 (Multicast: 12)  bytes 754
            TX succeeded 12 errors 0

```

### CODE REVIEW

**Comment by benpicco** [comment]
Just wondering: Why does `gnrc_netdev_default` not automatically select `netdev_default`?

**Comment by fjmolinas** [comment]
> Just wondering: Why does gnrc_netdev_default not automatically select netdev_default?

It does, I wan't to pull in `cc2538_rf` if `netdev_default` is used but not `gnrc_netdev_default`.

**Comment by benpicco** [comment]
> I wan't to pull in `cc2538_rf` if `netdev_default` is used but not `gnrc_netdev_default`.

But wouldn't `ifneq (,$(filter netdev_default,$(USEMODULE)))` be enough then?
I see that most boards check for both modules, so cc2538 should follow suit, but that looks like another potential for cleanup.

**Comment by fjmolinas** [comment]
> But wouldn't ifneq (,$(filter netdev_default,$(USEMODULE))) be enough then?
> I see that most boards check for both modules, so cc2538 should follow suit, but that looks like another potential for cleanup.

Yep you are right.

**Pull request merged**
