### PR TITLE
cpu/sam0_common: fixed UART for samd21

### LINKED ISSUE #7546: samr21-xpro uart broken in master
#7260 seems to have broken uart output on my samr21-xpro... does anyone else see this?

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #7546

The driver is still some steps for ideal, but for now the UARTs should work again. Will do more cleanup once I have access to my saml21-xpro...

Verified working on the `samr21-xpro`.

### CODE REVIEW

**Comment by kaspar030** [comment]
Maybe someone could verify that saml21 is still working? Maybe @dylad?

**Comment by dylad** [comment]
Sorry, I won't have access to my board until this evening.
But I'll try and let you know.

**Comment by haukepetersen** [comment]
I will merge this anyway (as a broken `samr21-xpro` in master is very bad for us). 

@dylad: please let me know, if there is trouble with the `saml21`, then we will fix that separately.

**Comment by dylad** [comment]
@haukepetersen I'll come back to you tonight.

**Comment by dylad** [comment]
`saml21-xpro` works fine with lastest master.
I tested several programs and no problems with UART.

**Comment by haukepetersen** [comment]
perfect :-)

**Pull request merged**
