### PR TITLE
boards: Remove support for the Jiminy-Mega256RFR2

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR drops support for the Jiminy-Mega256RFR2 board

#### Reasoning

- The Jiminy-Mega256RFR2 is seemingly unmaintained, as no one has responded  on requests to test changes on it. This lack of support has been blocking various PRs in the last few months
- No one seems to use it
- Boards that are added to RIOT should match at least one of the following
    - It is actively maintained
    - It has a significant user base
    - It is an off-the-shelf product, so it might be easily obtained for testing
==> The Jiminy is matching none of the above

### Testing procedure

I think that the CI will do enough testing in this case.

### Issues/PRs references

PRs that are (or have been) waiting for someone with the Jiminy to test: https://github.com/RIOT-OS/RIOT/pull/11366, https://github.com/RIOT-OS/RIOT/pull/11923, https://github.com/RIOT-OS/RIOT/pull/11190, https://github.com/RIOT-OS/RIOT/pull/11122, https://github.com/RIOT-OS/RIOT/pull/11039, https://github.com/RIOT-OS/RIOT/pull/11027, ...

### CODE REVIEW

**Comment by maribu** [comment]
To also have the info [received on the mailing list](https://lists.riot-os.org/pipermail/users/2019-September/001339.html) available here: There is interest in keeping support for the CPU (ATmega256RFR2), as adding upstream support for the [Merkur Board](http://osdwiki.open-entry.com/doku.php/en:projekte:merkur) is in progress. The Merkur Board is an off-the-shelf product and commercially available e.g. [here](https://electronics.semaf.at/Merkur-Board-6LoWPAN), or [here (site currently having issues)](https://www.iot-shop.at/).

**Comment by benpicco** [comment]
#9172 lacks the final review from us, but it might need some more work by @Josar too.
I would guess this is the main blocker for the users of this board to use upstream RIOT.

@Josar are you still interested in this? If we get the radio code merged, would that help you with working with upstream RIOT directly or are you now on a different project?

**Comment by shr70** [comment]
I, as one of the two actual users, agree that its probably best to drop support for the board and just keep the cpu support for the Merkur board. As the Jiminy-Board schematics never got published it does not make sense to keep it, especially if it is delaying PRs. 
I currently moved over to the Nucleo-Boards, as the Jiminy-Boards performance was too low for our current application. I guess @Josar should have the final say in this as he was the PHD student responsible for this project.

**Comment by miri64** [comment]
While your arguments are valid, the right process AFAIK would be to deprecate the board first. This way we can phase support out slowly (and also maybe give the merkur board time to be merged in the meantime).

**Comment by maribu** [comment]
> While your arguments are valid, the right process AFAIK would be to deprecate the board first.

Let's recapitulate the context: @shr70 confirmed that in total two persons on this planet have access to the hardware and can be counted as potential users of the code. Also, he confirmed that he no longer is an active user, so there is at most one active user of the code in this universe as far as we know.

With this context in mind, I'm not sure if @miri64's suggestion to follow a multi-step depreciation process is a real suggestion or a joke.

**Comment by miri64** [comment]
> With this context in mind, I'm not sure if @miri64's suggestion to follow a multi-step depreciation process is a real suggestion or a joke.

It was a real suggestion, but the context wasn't clear to me of the writing of the comment ;-) (I saw @shr70 only after I posted it).

**Comment by miri64** [comment]
However, with the apparent context of the board only having two users, I agree that our usual process would be overkill.

**Comment by jcarrano** [comment]
As always, I'm a supported of the wrecking-ball approach, so +1 from me.

@shr70, you want to keep the CPU, but this is the only board using it. How are we going to support the CPU without having a board to test it? There is an Xplained board for that CPU. If you want to have support for the CPU it may be a good option to use that board in RIOT (independently of the board you use yourself) so that other devs can get it easily.

Now that I think about it, it may be a good strategy for people with custom boards that need to have their CPU supported in RIOT to add a _dev_ board with that CPU instead.

**Comment by shr70** [comment]
@jcarrano As @maribu mentioned earlier, there is another board that is using the same CPU in progress. So soon there will be a board to test.

**Comment by Josar** [comment]
@PeterKietzmann should also have a Jiminy-board. 

I am fine with dropping the support for the Jiminy-boards. 
I had a lot to do and so i could not put effort in things that stale in progress. And i don't think that i will find a lot time in future to keep support for a board that only i could use.

As the xtimer for 16bit counter had issues which could not be resolved as all provider PRs did not get enough attention to reach master. And with the xtimer issues a continues network could not be maintained so this 16bit mcu based board can not be used in an LoWPAN.

**Comment by Josar** [comment]
@benpicco i would like to contribute the at86rf part but i have to see if i find time for reworking it.
If the supporter for the Merkur board can use it feel free to take it.

Besides that the mcu can also be used for pinoccio boards files can also be used

**Comment by benpicco** [comment]
The MCU can also be found on the ATRCB256RFR2-XPRO dev board which can be bought off the shelf for ~30€.

**Comment by maribu** [comment]
I think that ztimer will overcome the issues with 16 bit timers, if I remember correctly. ztimer is on the way in anyway, so effort on fixing xtimer might be better spend on reviewing and contributing to ztimer

**Comment by maribu** [comment]
> Besides that the mcu can also be used for pinoccio boards https://github.com/Pinoccio maybe some of them can be bought.

Apparently not. The HTTPS certificate of the website at http://pinocc.io/ has expired, the sale link is broken, the linked support page is no longer available, activity in the forum seems to have faded in 2016, and I would be surprised to see tumbleweeds rolling there. I think it is pretty safe to say that the Pinoccio is no longer available and, thus, no off-the-shelf product.

If I remember correctly, one conclusion of the maintainer assembly in Helsinki was to improve support for handling boards outside of RIOT's master, rather than trying to add support for every board out there. I'd say the evaluation board of the ATmega256RFR2 is a good candidate for inclusion, and the Jiminy and Pinoccio are good candidates for out of tree support.

**Comment by maribu** [comment]
> Do we really need >1 ack?

I'd say yes, as we are not following the standard deprecation process here. Maybe @dylad can give the second ACK, [as he suggested](https://github.com/RIOT-OS/RIOT/pull/11366#issuecomment-529340459) to drop support of the board?

**Comment by jcarrano** [comment]
> I'd say the evaluation board of the ATmega256RFR2 is a good candidate for inclusion.

Agree 100%. For these things, always go for the better established, highest volume suppliers.

**Comment by maribu** [comment]
@dylad: Added the entry. ACK and merge?

**Pull request merged**
