### PR TITLE
make: add cosy as a build target

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`cosy` is a graphical memory usage analyzer.
It is a great tool, but pretty hidden.
Add it as a build target so it can be easiely summoned for any application and board.

### Testing procedure

Run e.g. 

    make -C examples/hello-world cosy

and open the link (http://localhost:12345) in your browser.
You should see a graphical break down of every symbol and it's memory usage.

You can do this for every app or board.

### Issues/PRs references

upstream PRs:
https://github.com/haukepetersen/cosy/pull/9
https://github.com/haukepetersen/cosy/pull/10

### CODE REVIEW

**Comment by maribu** [comment]
Nice :-)

**Comment by aabadie** [comment]
Do you plan to contribute the patches upstream ? The problem with the path not found can be easily fixed by adding `os.path.abspath(__file__)` to `root/symbols.json`. The other patch is even more obvious to push upstream.

**Comment by benpicco** [comment]
Yes i already opened PRs upstream

**Comment by kaspar030** [comment]
Very nice, longing for this since I first patched the cosy RIOT path!

I got an issue. This happens on `BOARD=samr21-xpro make cosy` in `tests/minimal`:

```
/home/kaspar/src/riot/build/pkg/cosy/cosy.py --riot-base /home/kaspar/src/riot /home/kaspar/src/riot/tests/minimal samr21-xpro
Error: ELF file '/home/kaspar/src/riot/tests/minimal/bin/samr21-xpro/minimal.elf' does not exist
make: *** [/home/kaspar/src/riot/tests/minimal/../../Makefile.include:722: cosy] Error 1
```

I guess cosy needs an .elf filename parameter.

**Review by kaspar030 — APPROVED** [review]
ACK from my side.

It is properly integrated now and allows using cosy without manually getting, patching and launching cosy.py.

@aabadie are you fine with improving the path situation later?

**Comment by aabadie** [comment]
> are you fine with improving the path situation later?

Well not really, the upstream patches are simple enough to be merged quite fast without having to merge patches in RIOT. Can someone ping @haukepetersen (IRL or by email or whatever) ?

**Comment by miri64** [comment]
I agree with @aabadie. I don't really see a reason to hasten this, when the patches can be merged upstream first. But great work, @benpicco! Finally, I don't have to change into the `cosy` directory anymore :D.

**Comment by fjmolinas** [comment]
> I agree with @aabadie. I don't really see a reason to hasten this, when the patches can be merged upstream first. But great work, @benpicco! Finally, I don't have to change into the `cosy` directory anymore :D.

Only thing missing is that it recognizes the application name (for test for example), maybe a `make -C info-debug-varaible-APPLICATION` would do the trick.

**Comment by kaspar030** [comment]
>  I don't really see a reason to hasten this, when the patches can be merged upstream first. But great work, @benpicco! Finally, I don't have to change into the `cosy` directory anymore :D.

I don't get you guys. Your comment is contradictory, you'll have to change into the cosy directory still until this is merged.

**Comment by kaspar030** [comment]
> Only thing missing is that it recognizes the application name (for test for example), maybe a `make -C info-debug-varaible-APPLICATION` would do the trick.

isn't this fixed since the last force-push? It works here now.

**Comment by fjmolinas** [comment]
> > Only thing missing is that it recognizes the application name (for test for example), maybe a `make -C info-debug-varaible-APPLICATION` would do the trick.
> 
> isn't this fixed since the last force-push? It works here now.

Ah I did not test, so nice!

**Comment by fjmolinas** [comment]
> > > Only thing missing is that it recognizes the application name (for test for example), maybe a `make -C info-debug-varaible-APPLICATION` would do the trick.
> > 
> > 
> > isn't this fixed since the last force-push? It works here now.
> 
> Ah I did not test, so nice!

I should read the whole discussion next time...

**Comment by miri64** [comment]
> > I don't really see a reason to hasten this, when the patches can be merged upstream first. But great work, @benpicco! Finally, I don't have to change into the `cosy` directory anymore :D.
> 
> I don't get you guys. Your comment is contradictory, you'll have to change into the cosy directory still until this is merged.

This is also done when the fixes get merged upstream which if you really need it _now_ you can do locally since the branch is public. Why merge patches that we later would revert again anyways?

**Comment by kaspar030** [comment]
> Why merge patches that we later would revert again anyways?

Because we are in control of getting the feature *now* and not when upstream goes through another round of reviews that is _not in our control_.

Blocking this because of waiting for patches to get upstream is essentially delaying for an undetermined amount of time. What for?

**Review by jeandudey — APPROVED** [review]
Tested and everything works very good.

<details>
<summary>Me before cosy plus the RIOT cosy target in this PR</summary>

calc

</details>

<details>
<summary>Me after cosy (`make -C examples/saul cosy BOARD=cc1312-launchpad`)</summary>

Screenshot from 2021-02-24 11-41-43
</details>

However it would be nice if the patches could be merged upstream first. Not an strong opinion though.

**Comment by miri64** [comment]
> Blocking this because of waiting for patches to get upstream is essentially delaying for an undetermined amount of time. What for?

1. Nobody has hit a red button, so this is not blocked, 2. it is not like the upstream in question is a stranger to the community, 3. what benefit has it to merge this ASAP? If the PRs upstream are not merged after a reasonable time for @haukepetersen to react, we still can merge it here for (as again: nobody put a hard block on this). But merging it now, just because its there, when the patches could be merged upstream in an hour seems like a waste of time.

**Comment by maribu** [comment]
> > Why merge patches that we later would revert again anyways?
> 
> Because we are in control of getting the feature _now_ and not when upstream goes through another round of reviews that is _not in our control_.
> 
> Blocking this because of waiting for patches to get upstream is essentially delaying for an undetermined amount of time. What for?

Maybe as compromise we could wait for let's say two hours and see if @haukepetersen can give an ETA. The upstream pull requests seem unscary enough that he'd likely merge them after a brief look. So if he is not afk, they likely get upstream real quick.

**Comment by kaspar030** [comment]
> Maybe as compromise we could wait for let's say two hours and see if @haukepetersen can give an ETA.

No ETA, no reaction.

**Pull request merged**
