### PR TITLE
makefiles/buildtests.inc.mk: use per board BINDIR

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

Fix all boards being built in the default application board bin directory.
With this, the 'clean-intermediates' should now also be done per board.

In general all boards were built in `bin/native/` and `bin/pkg/native`.

### Testing procedure

```
rm -rf examples/javascript/bin/; BOARDS="iotlab-m3 samr21-xpro" make -C examples/javascript buildtest ; find examples/javascript/bin/
```

In master we have:

```
find examples/javascript/bin/
examples/javascript/bin/
examples/javascript/bin/native
examples/javascript/bin/native/riot_javascript.elf
examples/javascript/bin/native/riot_javascript.bin
examples/javascript/bin/native/riot_javascript.map
examples/javascript/bin/pkg
examples/javascript/bin/pkg/native
```

With this PR:

```
find examples/javascript/bin/
examples/javascript/bin/
examples/javascript/bin/iotlab-m3
examples/javascript/bin/iotlab-m3/riot_javascript.hex
examples/javascript/bin/iotlab-m3/riot_javascript.elf
examples/javascript/bin/iotlab-m3/riot_javascript.map
examples/javascript/bin/native
examples/javascript/bin/pkg
examples/javascript/bin/pkg/iotlab-m3
examples/javascript/bin/pkg/samr21-xpro
examples/javascript/bin/samr21-xpro
examples/javascript/bin/samr21-xpro/riot_javascript.elf
examples/javascript/bin/samr21-xpro/riot_javascript.bin
examples/javascript/bin/samr21-xpro/riot_javascript.map
```

### Issues/PRs references

~Fixes~ ~https://github.com/RIOT-OS/RIOT/issues/9742~
Needed to test build size change using buildtest in https://github.com/RIOT-OS/RIOT/pull/8711

### CODE REVIEW

**Comment by cladmi** [comment]
It also works in 'docker' but 'BOARDS' is not currently passed to the docker container.

**Comment by cladmi** [comment]
Found out that `info-buildsizes-diff` is also affected and so completely not working. I will do another PR next week for this.

**Comment by tcschmidt** [comment]
@jcarrano ping

**Comment by jcarrano** [comment]
I am unable to reproduce the issue on master.

**Comment by smlng** [comment]
btw. my testing was done on macOS - so if someone would care to try the above on Linux, great!

**Comment by MrKevinWeiss** [comment]
Tested on linux with examples/hello-world:
PR:
```
find examples/hello-world/bin
examples/hello-world/bin
examples/hello-world/bin/samr21-xpro
examples/hello-world/bin/samr21-xpro/hello-world.elf
examples/hello-world/bin/samr21-xpro/hello-world.map
examples/hello-world/bin/samr21-xpro/hello-world.bin
```

master:
```
find examples/hello-world/bin
examples/hello-world/bin
examples/hello-world/bin/native
examples/hello-world/bin/samr21-xpro
examples/hello-world/bin/samr21-xpro/periph_common
examples/hello-world/bin/samr21-xpro/periph_common/cpuid.o
examples/hello-world/bin/samr21-xpro/periph_common/i2c.o
examples/hello-world/bin/samr21-xpro/periph_common/pm.d
examples/hello-world/bin/samr21-xpro/periph_common/i2c.d
examples/hello-world/bin/samr21-xpro/periph_common/flashpage.o
examples/hello-world/bin/samr21-xpro/periph_common/flashpage.d
examples/hello-world/bin/samr21-xpro/periph_common/spi.d
examples/hello-world/bin/samr21-xpro/periph_common/eeprom.d
examples/hello-world/bin/samr21-xpro/periph_common/init.o
examples/hello-world/bin/samr21-xpro/periph_common/init.d
examples/hello-world/bin/samr21-xpro/periph_common/timer.d
examples/hello-world/bin/samr21-xpro/periph_common/cpuid.d
examples/hello-world/bin/samr21-xpro/periph_common/eeprom.o
examples/hello-world/bin/samr21-xpro/periph_common/pm.o
examples/hello-world/bin/samr21-xpro/periph_common/spi.o
examples/hello-world/bin/samr21-xpro/periph_common/timer.o
examples/hello-world/bin/samr21-xpro/periph
examples/hello-world/bin/samr21-xpro/periph/pm.d
examples/hello-world/bin/samr21-xpro/periph/pm.o
examples/hello-world/bin/samr21-xpro/drivers
examples/hello-world/bin/samr21-xpro/hello-world.elf
examples/hello-world/bin/samr21-xpro/cpu.a
examples/hello-world/bin/samr21-xpro/board
examples/hello-world/bin/samr21-xpro/board/board.d
examples/hello-world/bin/samr21-xpro/board/board.o
examples/hello-world/bin/samr21-xpro/newlib_syscalls_default
examples/hello-world/bin/samr21-xpro/newlib_syscalls_default/syscalls.o
examples/hello-world/bin/samr21-xpro/newlib_syscalls_default/syscalls.d
examples/hello-world/bin/samr21-xpro/sys.a
examples/hello-world/bin/samr21-xpro/cpu
examples/hello-world/bin/samr21-xpro/cpu/vectors.o
examples/hello-world/bin/samr21-xpro/cpu/vectors.d
examples/hello-world/bin/samr21-xpro/cpu/cpu.o
examples/hello-world/bin/samr21-xpro/cpu/cpu.d
examples/hello-world/bin/samr21-xpro/pm_layered.a
examples/hello-world/bin/samr21-xpro/sam0_common
examples/hello-world/bin/samr21-xpro/periph.a
examples/hello-world/bin/samr21-xpro/board.a
examples/hello-world/bin/samr21-xpro/tsrb
examples/hello-world/bin/samr21-xpro/tsrb/tsrb.d
examples/hello-world/bin/samr21-xpro/tsrb/tsrb.o
examples/hello-world/bin/samr21-xpro/isrpipe
examples/hello-world/bin/samr21-xpro/isrpipe/isrpipe.d
examples/hello-world/bin/samr21-xpro/isrpipe/isrpipe.o
examples/hello-world/bin/samr21-xpro/core.a
examples/hello-world/bin/samr21-xpro/sam0_common.a
examples/hello-world/bin/samr21-xpro/pm_layered
examples/hello-world/bin/samr21-xpro/pm_layered/pm.d
examples/hello-world/bin/samr21-xpro/pm_layered/pm.o
examples/hello-world/bin/samr21-xpro/sys
examples/hello-world/bin/samr21-xpro/riotbuild
examples/hello-world/bin/samr21-xpro/riotbuild/riotbuild.h
examples/hello-world/bin/samr21-xpro/hello-world.map
examples/hello-world/bin/samr21-xpro/isrpipe.a
examples/hello-world/bin/samr21-xpro/stdio_uart.a
examples/hello-world/bin/samr21-xpro/newlib_syscalls_default.a
examples/hello-world/bin/samr21-xpro/sam0_common_periph.a
examples/hello-world/bin/samr21-xpro/cortexm_common_periph
examples/hello-world/bin/samr21-xpro/cortexm_common_periph/pm.d
examples/hello-world/bin/samr21-xpro/cortexm_common_periph/pm.o
examples/hello-world/bin/samr21-xpro/application_hello-world
examples/hello-world/bin/samr21-xpro/application_hello-world/main.o
examples/hello-world/bin/samr21-xpro/application_hello-world/main.d
examples/hello-world/bin/samr21-xpro/auto_init
examples/hello-world/bin/samr21-xpro/auto_init/auto_init.d
examples/hello-world/bin/samr21-xpro/auto_init/auto_init.o
examples/hello-world/bin/samr21-xpro/application_hello-world.a
examples/hello-world/bin/samr21-xpro/cortexm_common
examples/hello-world/bin/samr21-xpro/cortexm_common/vectors_cortexm.d
examples/hello-world/bin/samr21-xpro/cortexm_common/mpu.o
examples/hello-world/bin/samr21-xpro/cortexm_common/mpu.d
examples/hello-world/bin/samr21-xpro/cortexm_common/cortexm_init.o
examples/hello-world/bin/samr21-xpro/cortexm_common/cortexm_init.d
examples/hello-world/bin/samr21-xpro/cortexm_common/thread_arch.d
examples/hello-world/bin/samr21-xpro/cortexm_common/vectors_cortexm.o
examples/hello-world/bin/samr21-xpro/cortexm_common/panic.o
examples/hello-world/bin/samr21-xpro/cortexm_common/irq_arch.d
examples/hello-world/bin/samr21-xpro/cortexm_common/irq_arch.o
examples/hello-world/bin/samr21-xpro/cortexm_common/thread_arch.o
examples/hello-world/bin/samr21-xpro/cortexm_common/panic.d
examples/hello-world/bin/samr21-xpro/stdio_uart
examples/hello-world/bin/samr21-xpro/stdio_uart/stdio_uart.d
examples/hello-world/bin/samr21-xpro/stdio_uart/stdio_uart.o
examples/hello-world/bin/samr21-xpro/core
examples/hello-world/bin/samr21-xpro/core/ringbuffer.d
examples/hello-world/bin/samr21-xpro/core/atomic_c11.d
examples/hello-world/bin/samr21-xpro/core/rmutex.d
examples/hello-world/bin/samr21-xpro/core/msg.o
examples/hello-world/bin/samr21-xpro/core/thread.o
examples/hello-world/bin/samr21-xpro/core/atomic_c11.o
examples/hello-world/bin/samr21-xpro/core/rmutex.o
examples/hello-world/bin/samr21-xpro/core/sched.o
examples/hello-world/bin/samr21-xpro/core/bitarithm.o
examples/hello-world/bin/samr21-xpro/core/atomic_sync.o
examples/hello-world/bin/samr21-xpro/core/priority_queue.o
examples/hello-world/bin/samr21-xpro/core/assert.o
examples/hello-world/bin/samr21-xpro/core/sched.d
examples/hello-world/bin/samr21-xpro/core/atomic_sync.d
examples/hello-world/bin/samr21-xpro/core/clist.o
examples/hello-world/bin/samr21-xpro/core/panic.o
examples/hello-world/bin/samr21-xpro/core/assert.d
examples/hello-world/bin/samr21-xpro/core/lifo.o
examples/hello-world/bin/samr21-xpro/core/mutex.o
examples/hello-world/bin/samr21-xpro/core/mutex.d
examples/hello-world/bin/samr21-xpro/core/priority_queue.d
examples/hello-world/bin/samr21-xpro/core/kernel_init.o
examples/hello-world/bin/samr21-xpro/core/msg.d
examples/hello-world/bin/samr21-xpro/core/lifo.d
examples/hello-world/bin/samr21-xpro/core/thread.d
examples/hello-world/bin/samr21-xpro/core/kernel_init.d
examples/hello-world/bin/samr21-xpro/core/clist.d
examples/hello-world/bin/samr21-xpro/core/ringbuffer.o
examples/hello-world/bin/samr21-xpro/core/bitarithm.d
examples/hello-world/bin/samr21-xpro/core/panic.d
examples/hello-world/bin/samr21-xpro/sam0_common_periph
examples/hello-world/bin/samr21-xpro/sam0_common_periph/gpio.d
examples/hello-world/bin/samr21-xpro/sam0_common_periph/uart.d
examples/hello-world/bin/samr21-xpro/sam0_common_periph/gpio.o
examples/hello-world/bin/samr21-xpro/sam0_common_periph/uart.o
examples/hello-world/bin/samr21-xpro/hello-world.bin
examples/hello-world/bin/samr21-xpro/periph_common.a
examples/hello-world/bin/samr21-xpro/cortexm_common.a
examples/hello-world/bin/samr21-xpro/tsrb.a
examples/hello-world/bin/samr21-xpro/auto_init.a
examples/hello-world/bin/samr21-xpro/cortexm_common_periph.a
examples/hello-world/bin/samr21-xpro/drivers.a
```

**Comment by cladmi** [comment]
@jcarrano indeed I have issues in my testing procedure description, I will try to find how to test properly.
I may be missing one thing why files are still created in the correct board directory.

**Comment by cladmi** [comment]
@jcarrano actually it should be working as I say.
@smlng @MrKevinWeiss It is really important to run the `rm -rf ..../bin` to run the test. As it looks like you have files remaining from the previous state.

For an all in one test command: (I will update the description)

```
rm -rf examples/hello-world/bin; BOARDS="iotlab-m3 samr21-xpro" make -C examples/hello-world buildtest BUILDTEST_MAKE_REDIRECT='2>/dev/null'; find examples/hello-world/bin
```

In master:

```
make: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building for iotlab-m3 ... make[1]: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building application "hello-world" for "iotlab-m3" with MCU "stm32f1".

   text    data     bss     dec     hex filename
   8408     140    2612   11160    2b98 /home/cladmi/git/work/riot_master/examples/hello-world/bin/native/hello-world.elf
make[1]: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
success.
Building for samr21-xpro ... make[1]: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building application "hello-world" for "samr21-xpro" with MCU "samd21".

   text    data     bss     dec     hex filename
   8404     140    2612   11156    2b94 /home/cladmi/git/work/riot_master/examples/hello-world/bin/native/hello-world.elf
make[1]: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
success.
make: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
examples/hello-world/bin
examples/hello-world/bin/native
examples/hello-world/bin/native/hello-world.bin
examples/hello-world/bin/native/hello-world.elf
examples/hello-world/bin/native/hello-world.map
```

With this PR

```
make: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building for iotlab-m3 ... make[1]: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building application "hello-world" for "iotlab-m3" with MCU "stm32f1".

   text    data     bss     dec     hex filename
   8472     140    2740   11352    2c58 /home/cladmi/git/work/riot_master/examples/hello-world/bin/iotlab-m3/hello-world.elf
make[1]: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
success.
Building for samr21-xpro ... make[1]: Entering directory '/home/cladmi/git/work/riot_master/examples/hello-world'
Building application "hello-world" for "samr21-xpro" with MCU "samd21".

   text    data     bss     dec     hex filename
   8456     140    2740   11336    2c48 /home/cladmi/git/work/riot_master/examples/hello-world/bin/samr21-xpro/hello-world.elf
make[1]: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
success.
make: Leaving directory '/home/cladmi/git/work/riot_master/examples/hello-world'
examples/hello-world/bin
examples/hello-world/bin/iotlab-m3
examples/hello-world/bin/iotlab-m3/hello-world.hex
examples/hello-world/bin/iotlab-m3/hello-world.elf
examples/hello-world/bin/iotlab-m3/hello-world.map
examples/hello-world/bin/samr21-xpro
examples/hello-world/bin/samr21-xpro/hello-world.bin
examples/hello-world/bin/samr21-xpro/hello-world.elf
examples/hello-world/bin/samr21-xpro/hello-world.map
```

**Comment by cladmi** [comment]
The current implementation of this is to only not overwrite it from within the build system.
I would prefer a global fix of never overwriting subdirectories of `bin`.

This would somehow be an api change that the only really handled configurable build directory is where is `bin` not the other variables. We could still keep the sanity checks.
It would solve globally all the related issues, but should be a more reviewed thing that should go after the release.

**Comment by jcarrano** [comment]
@cladmi I followed your new instructions and I get the same output that you describe, so I guess I was doing something wrong the first time.

**Comment by cladmi** [comment]
@jcarrano thanks for testing. Then I re-enable murdock.

**Comment by MrKevinWeiss** [comment]
So running on linux your exact command `rm -rf examples/javascript/bin/; BOARDS="iotlab-m3 samr21-xpro" make -C examples/javascript buildtest ; find examples/javascript/bin/`
In master I get lots of files (all the .o and .d and .a and everything in the package)
```
rm -rf examples/javascript/bin/; BOARDS="iotlab-m3 samr21-xpro" make -C examples/javascript buildtest ; find examples/javascript/bin/
make: Entering directory '/home/kevinweiss/WorkingDirectory/RIOT/examples/javascript'
Building for iotlab-m3 ... success.
Building for samr21-xpro ... success.
make: Leaving directory '/home/kevinweiss/WorkingDirectory/RIOT/examples/javascript'
examples/javascript/bin/
examples/javascript/bin/pkg
examples/javascript/bin/pkg/iotlab-m3
examples/javascript/bin/pkg/iotlab-m3/jerryscript
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/main-unix.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/cli.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/CMakeLists.txt
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/main-unix-test.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/benchmarking.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/cli.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-main/main-unix-snapshot.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/CMakeLists.txt
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger/debugger-common.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger/debugger-ws.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger/debugger-tcp.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger/debugger-sha1.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/debugger/debugger-sha1.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/common
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/common/jext-common.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/handler
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/handler/handler-print.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/handler/handler-register.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/handler/handler-assert.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/handler/handler-gc.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/arg
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/arg/arg-transform-functions.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/arg/arg.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/arg/arg-internal.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/arg/arg-js-iterator-helper.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/module
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/module/module.c
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/handler.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/autorelease.impl.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/debugger.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/arg.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/module.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/arg.impl.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/jerry-ext/include/jerryscript-ext/autorelease.h
examples/javascript/bin/pkg/iotlab-m3/jerryscript/README.md
examples/javascript/bin/pkg/iotlab-m3/jerryscript/CONTRIBUTING.md
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake/toolchain_openwrt_mipsel.cmake
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake/toolchain_linux_i686.cmake
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake/toolchain_mcu_tim4f.cmake
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake/toolchain_openwrt_mips.cmake
examples/javascript/bin/pkg/iotlab-m3/jerryscript/cmake/toolchain_linux_armv7l.cmake
...
```

With your pr I get
```
rm -rf examples/javascript/bin/; BOARDS="iotlab-m3 samr21-xpro" make -C examples/javascript buildtest ; find examples/javascript/bin/
make: Entering directory '/home/kevinweiss/WorkingDirectory/RIOT/examples/javascript'
Building for iotlab-m3 ... success.
Building for samr21-xpro ... success.
make: Leaving directory '/home/kevinweiss/WorkingDirectory/RIOT/examples/javascript'
examples/javascript/bin/
examples/javascript/bin/pkg
examples/javascript/bin/pkg/iotlab-m3
examples/javascript/bin/pkg/samr21-xpro
examples/javascript/bin/iotlab-m3
examples/javascript/bin/iotlab-m3/riot_javascript.map
examples/javascript/bin/iotlab-m3/riot_javascript.hex
examples/javascript/bin/iotlab-m3/riot_javascript.elf
examples/javascript/bin/samr21-xpro
examples/javascript/bin/samr21-xpro/riot_javascript.bin
examples/javascript/bin/samr21-xpro/riot_javascript.map
examples/javascript/bin/samr21-xpro/riot_javascript.elf
```

**Comment by cladmi** [comment]
Hmm then I still get different behavior from what describe… I will investigate.
Because the fix may need to change or at least be documented different.

**Comment by cladmi** [comment]
Thanks for the updated answer @MrKevinWeiss  ! :)

**Comment by cladmi** [comment]
I have different behavior when building with and without providing `RIOT_CI_BUILD`…

**Comment by cladmi** [comment]
Actually whenever I set a variable on the command line instead of in the environment variable, the directory are indeed overridden. If there are none the `MAKEOVERRIDES` does not apply.

https://github.com/RIOT-OS/RIOT/blob/598a3155a924baf344d8e5a38894b271940681b9/Makefile.include#L64-L65

So it is the case when I set `BUILD_IN_DOCKER` or `BUILDTEST_MAKE_REDIRECT`.
Which made the test dependent of which options you put…

The fix actually works but I still want to find out why before going with it.

**Comment by cladmi** [comment]
From what I understood:

`MAKEOVERRIDES` is not overriding anything when no variables are given from the command line.
Maybe there is a trigger to enforce this but I want to get rid of it anyway so I will not look into it.
This show that `MAKEOVERRIDES` should only be populated with the variables which have been set from the command line and not all `__DIRECTORY_VARIABLES`.
I can do a PR for only this if somebody is willing to review it.

And the reason it works by default in master, is as `buildtest` is a special target handled with a different path in Makefile.include `vars.inc.mk` is never included so the path variables are never exported which makes the variable not exported for `buildtest`.

-----

From this PR, I think only the `clean-intermediates` patch should go in for now as it will make the cleaning work.

What do you think ?

**Comment by cladmi** [comment]
Thanks to all the reviews, I found that the original problem mentioned here was a bit different and will need proper attention.
I split the `cleaning` part in a separate to make it merged more easily https://github.com/RIOT-OS/RIOT/pull/10235

**Comment by MrKevinWeiss** [comment]
Is this one ready to go or do you want to do more (since WIP is still on) @cladmi?

**Comment by cladmi** [comment]
All that currently is in this PR is merged in https://github.com/RIOT-OS/RIOT/pull/10235

What I should address is that directories are overridden only if necessary in this line:

https://github.com/RIOT-OS/RIOT/blob/c7894d2bfc0c437da2ca6472ac5c2c439b358330/Makefile.include#L69
 
To not have different behavior when setting a variable on the command line.

I think I should open a dedicated PR for this one mentioning here.

As I already have a tracking issue, I will close this one and update the issue:

https://github.com/RIOT-OS/RIOT/issues/9742

**Pull request closed without merging**
