### PR TITLE
cpu/atmega_common: Provide C++ support (without libstdc++)

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR adds basic C++ support, including support for initializing statically allocated class instances in a thread-safe manner. (The implementation of the later is not AVR specific, so it was moved as module to `sys/`. Other architectures might just use that as well.)

### Testing procedure

All of the C++ tests in `tests/` should work, except those requiring libstdc++ support. (But those should complain about a missing feature, instead of surprising compilation bugs.)

### Issues/PRs references

None

### CODE REVIEW

**Comment by benpicco** [comment]
Murdock isn't happy yet.

**Comment by maribu** [comment]
> Murdock isn't happy yet.

Thanks for pointing this out. I think I fixed the culprit. May I squash before Murdock takes a second look?

**Comment by benpicco** [comment]
Sure, squash!

**Comment by miri64** [comment]
Requeueing to get the release out ASAP.

**Comment by benpicco** [comment]
Looks like utensor also requires libstdcpp

**Comment by maribu** [comment]
Thanks for the review!

**Pull request merged**
