### PR TITLE
sys/fido2: use ztimer instead of xtimer

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Before `fido2` was using `xtimer` and `ztimer` while not making the `xtimer` dependency explicit, this PR uses `ztimer` or `ztimer64` everywhere where `xtimer` was used.

- for ctap hid timeouts xtimer was used, use ztimer64_msec instead
  since the code is using absolute times, an already using ztimer_msec
- use event_timeout_ztimer instead of event_timeout to not pull in
  `xtimer`
  
The code could probably be refactored to not require 64bit, but the GOAL of this PR is just to not require the `64BITS` xtimer API.

### Testing procedure

Green murdock should be enough.

### CODE REVIEW

**Comment by fjmolinas** [comment]
Will de-schedule, re-schedule this one in favor of [#17754](https://github.com/RIOT-OS/RIOT/pull/17754) once [PR #17746](https://github.com/RIOT-OS/RIOT/pull/17746) finished to be sure there are no more overlfows pending.

**Comment by Ollrogge** [comment]
Changes look good. ACK from me

**Comment by fjmolinas** [comment]
Thanks for the review @Ollrogge, could a maintainer take a look and eventually ACK, I think it should be good since @Ollrogge is the contributor here. Maybe @kfessel or @kaspar030?

**Review by benpicco — APPROVED** [review]
I'm a bit surprised `ztimer64_msec` is needed though

**Comment by fjmolinas** [comment]
> I'm a bit surprised `ztimer64_msec` is needed though

I don't think it is, but this was the easiest approach for me that does not understand the fido2 code in detail, it limits this PR to a timer backend change and not the ctap timeout logic, @Ollrogge can probably state better but the timeout code could be reworked to rely on 32bit timeouts?

**Comment by Ollrogge** [comment]
> > I'm a bit surprised `ztimer64_msec` is needed though
> 
> I don't think it is, but this was the easiest approach for me that does not understand the fido2 code in detail, it limits this PR to a timer backend change and not the ctap timeout logic, @Ollrogge can probably state better but the timeout code could be reworked to rely on 32bit timeouts?

Yes it can be reworked. Changing it from 64 bit to 32 bit should have no implications

**Pull request merged**
