### PR TITLE
cpu: Add clock source selection based on CLOCK_HSE or CLOCK_HSI for STM32F1 family

### PR DESCRIPTION
**Pull request by DipSwitch**
One more with #3703 in mind.

Propose to configure the STM32F1 PLL clock source with the CLOCK_HSE or CLOCK_HSI define in the includes\periph_conf.h from the BSP

### CODE REVIEW

**Comment by DipSwitch** [comment]
Tested the HSI and HSE implementation

**Comment by haukepetersen** [comment]
the default example is hardfaulting on the iotlab-m3 for some reason...

**Comment by DipSwitch** [comment]
Any idea when it's hardfaulting? The PLL will never lock if the wrong configuration is applied and it should hang in the init_clock routine...

**Comment by DipSwitch** [comment]
Fixed, rebased and squashed. Should be sound now :)

**Comment by DipSwitch** [comment]
Apparently the `nucleo-f103` is new. Added it and squashed it.

**Comment by DipSwitch** [comment]
And missed `spark-core`

**Comment by haukepetersen** [comment]
looks good, confirmed working for the `iotlab-m3`, CI is happy -> ACK and go.

**Pull request merged**
