### PR TITLE
boards/samr21-xpro: added saul_gpio driver to Makefile.dep

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by kaspar030** [comment]
IMHO the PR description is misleading.

**Comment by cgundogan** [comment]
tested on a `samr21-xpro` board and I was able to turn the LED on and off again

**Comment by haukepetersen** [comment]
@kaspar030: better? If so, I will change the commit message accordingly

**Comment by kaspar030** [comment]
yup, danke!

**Comment by haukepetersen** [comment]
changed commit message

**Comment by haukepetersen** [comment]
you guys ack?

**Comment by kaspar030** [comment]
ACK!

**Comment by haukepetersen** [comment]
and go.

**Pull request merged**
