### PR TITLE
tests/pkg_nanors: use static allocation

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`reed_solomon_new()` uses `malloc()` internally, use `reed_solomon_new_static()` instead to use a static work buffer.

### Testing procedure

`tests/pkg_nanors` still works:

```
2023-03-14 19:43:21,130 # main(): This is RIOT! (Version: 2023.04-devel-648-g94ba33-pkg/nanors-static)
2023-03-14 19:43:21,132 # START
2023-03-14 19:43:21,135 # total: 30 shards (1920 bytes)
2023-03-14 19:43:21,150 # clear shard 25 (64 byte)
2023-03-14 19:43:21,152 # clear shard 17 (64 byte)
2023-03-14 19:43:21,154 # clear shard 18 (64 byte)
2023-03-14 19:43:21,156 # clear shard 18 (64 byte)
2023-03-14 19:43:21,159 # clear shard 28 (64 byte)
2023-03-14 19:43:21,161 # clear shard 12 (64 byte)
2023-03-14 19:43:21,163 # clear shard 11 (64 byte)
2023-03-14 19:43:21,165 # clear shard 0 (64 byte)
2023-03-14 19:43:21,168 # clear shard 12 (64 byte)
2023-03-14 19:43:21,170 # clear shard 24 (64 byte)
2023-03-14 19:43:21,171 # reconstruct…
2023-03-14 19:43:21,178 # done.
2023-03-14 19:43:21,179 # SUCCESS
2023-03-14 19:43:21,186 # { "threads": [{ "name": "main", "stack_size": 1536, "stack_used": 564 }]}
```

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by kaspar030** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
