### PR TITLE
drivers/rtt_rtc: implement rtc_get_time_ms()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

RTC on RTT usually runs at a frequency greater than 1 Hz, so sub-second precision is available.
Add a function to get the current RTC timestamp together with it's sub-second component.

### Testing procedure

To run `tests/periph_rtc` with `rtt_rtc` instead of the hardware RTC, do

```patch
--- a/tests/periph_rtc/Makefile
+++ b/tests/periph_rtc/Makefile
@@ -1,6 +1,7 @@
 include ../Makefile.tests_common
 
-FEATURES_REQUIRED += periph_rtc
+USEMODULE += rtt_rtc
+# FEATURES_REQUIRED += periph_rtc
 FEATURES_OPTIONAL += periph_rtc_ms
 
 DISABLE_MODULE += periph_init_rtc
```

```
2021-04-19 14:32:06,802 # RIOT RTC low-level driver test
2021-04-19 14:32:06,808 # This test will display 'Alarm!' every 2 seconds for 4 times
2021-04-19 14:32:06,811 #   Setting clock to   2020-02-28 23:59:57
2021-04-19 14:32:06,815 # Clock value is now   2020-02-28 23:59:57.014
2021-04-19 14:32:06,819 #   Setting alarm to   2020-02-28 23:59:59
2021-04-19 14:32:06,823 #    Alarm is set to   2020-02-28 23:59:59
2021-04-19 14:32:06,827 #   Alarm cleared at   2020-02-28 23:59:57.025
2021-04-19 14:32:08,831 #        No alarm at   2020-02-28 23:59:59.029
2021-04-19 14:32:08,834 #   Setting alarm to   2020-02-28 23:59:61
2021-04-19 14:32:08,835 # 
2021-04-19 14:32:10,831 # Alarm!
2021-04-19 14:32:12,832 # Alarm!
2021-04-19 14:32:14,833 # Alarm!
2021-04-19 14:32:16,833 # Alarm!
```

### CODE REVIEW

**Comment by fjmolinas** [comment]
Can you adapt the test so that if the new feature is used then the alarm is also set in `ms`?

**Comment by benpicco** [comment]
Setting the alarm in ms is not supported, some RTCs (`lpc23xx`) expose the underlying hardware counter, so we can get ms timestamps from that, but alarm can only be set to full seconds.

**Comment by fjmolinas** [comment]
> Setting the alarm in ms is not supported, some RTCs (`lpc23xx`) expose the underlying hardware counter, so we can get ms timestamps from that, but alarm can only be set to full seconds.

Ok!

**Review by fjmolinas — APPROVED** [review]
ACK.

**Comment by fjmolinas** [comment]
Is this now depending on #16442?

**Comment by benpicco** [comment]
No, but the test will keep failing until #16442  is merged

**Pull request merged**
