### PR TITLE
cpu/atmega*: Clean up timer configs

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR moves the default configurations of `periph_timer` from `boards/common/atmega` to `cpu/<ATMEGA_CPU>`. This allows getting rid of many instances of `#if defined(CPU_ATEMGA<FOO>)`. 

With the current periph code 16 bit timers can only be used for `periph_timer`, and 8 bit timers only for `periph_pwm`. So there is nothing for the board to decide on anyway. Still, this PR allows overwriting the timer config from a boards `periph_conf.h` just by defining `TIMER_NUMOF` there.

### Testing procedure

`tests/periph_timer` should still compile and pass for ATmega boards.

### Issues/PRs references

None

### CODE REVIEW

**Comment by benpicco** [comment]
That will make adding new ATmega CPUs easier too.
But Murdock found an issue.

**Comment by maribu** [comment]
It turned out that I manged to add an include cycle. I had to rework this a bit by splitting the default timer config out into a separate header file. I think I should take the time to `git blame` the original config, so that the authors in the headers are correct, rather than having random people named there.

**Comment by maribu** [comment]
> I think I should take the time to `git blame` the original config, so that the authors in the headers are correct, rather than having random people named there.

Bad idea. There only the author of the last clean up round is shown. I just keep the authors in the list and hope for the best.

**Comment by benpicco** [comment]
Murdock is not happy still.

**Comment by benpicco** [comment]
Looks good now, please squash!

**Comment by maribu** [comment]
Thanks for the review!

**Pull request merged**
