### PR TITLE
pkg ccn-lite: update version

### PR DESCRIPTION
**Pull request by OlegHahm**
This PR updates the ccn-lite version to current upstream master. The new version provides the following new features:
* introduction of the Reactive Optimistic Name-based Routing (RONR)
* better documentation and cleanup of the RIOT adapter
* better handling of FIB functions

This PR adapts the package to new API, updates the documentation and introduces shell commands to interact with the ccn-lite FIB.

### CODE REVIEW

**Comment by OlegHahm** [comment]
This can be tested on native and real hardware. If you test in a multi-hop scenario (e.g. the IoT-LAB) and don't want to configure the FIBs manually, you can active RONR in the Makefile.

All necessary information should be in the README. If something is unclear, let me know.

**Comment by emmanuelsearch** [comment]
Tested, and works on native.

**Comment by emmanuelsearch** [comment]
Building for samr21, I get this error:

```
ccnl-core.c:568:9: error: 'fibface' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         ccnl_face_enqueue(ccnl, fibface, buf_dup(interest->pkt->buf));
         ^
cc1: all warnings being treated as errors
```

**Comment by OlegHahm** [comment]
Yes, I pull requested another fix to ccn-lite that got merged yesterday to fix this:
https://github.com/cn-uofbasel/ccn-lite/commit/9e48d328e162e97f091d913ada0bf50f58d1d3d7

Updated this PR accordingly.

**Comment by emmanuelsearch** [comment]
OK, with the last fix, I could make it work on SAMR21, with two nodes, as the example in the readme.

**Comment by emmanuelsearch** [comment]
ACK

**Comment by OlegHahm** [comment]
Thanks for testing.

**Pull request merged**
