### PR TITLE
Lossless compresso

### PR DESCRIPTION
**Pull request by mrmajik45**
### Contribution description

- Losslessly compressed images

[*Total -- 40.02kb -> 26.29kb (34.31%)

/doc/memos/files/rdm0000/RIOT-logo.png -- 37.03kb -> 23.90kb (35.46%)
/doc/doxygen/src/riot-logo.png -- 2.99kb -> 2.39kb (20.08%)]

### Testing procedure

Details steps to test your contribution:
- (Compressed: Untestable)

### CODE REVIEW

**Comment by kYc0o** [comment]
Mistake? 

@RIOT-OS/maintainers please do not set the CI label.

**Comment by mrmajik45** [comment]
This was a PR for image compression. Smaller but same quality.

**Comment by bergzand** [comment]
Commit author is https://imgbot.net/

**Comment by mrmajik45** [comment]
Pay respects to the lord Imgbot.

**Comment by bergzand** [comment]
Anybody with an opinion on this change? I don't mind merging this as the change itself is valid. Only thing I have against it is that it will significantly increase the history size of the images, but that's not a huge problem for me.

**Comment by kYc0o** [comment]
Besides the complete dismiss of our contribution guidelines from the contributor, do we really gain something by saving 13.7KB?

Obviously it cannot be merged without complying with the contribution guidelines.

**Comment by miri64** [comment]
> Besides the complete dismiss of our contribution guidelines from the contributor, do we really gain something by saving 13.7KB?

In master yes, but within the repo the png's old blob will still exist, so this actually *adds* data to the git repo.

**Comment by miri64** [comment]
However, I don't block it if others see this as a valuable contribution.

**Comment by kYc0o** [comment]
Well, personally I don't see too much benefit on it, so I'll close it for now.

**Pull request closed without merging**
