### PR TITLE
k60: Remove unused macro definitions and typedefs

### PR DESCRIPTION
**Pull request by gebart**
Clean up some left overs from when I initially copied this configuration from our Contiki port.

### CODE REVIEW

**Comment by kYc0o** [comment]
I just tested this PR and the default example doesn't work. I tested hello-world and gnrc_networking with success, so something is maybe bad with a requirement for such example. I didn't investigate further.

**Comment by gebart** [comment]
I will investigate, though I fail to see how this particular change would affect the default example when it still compiles...

**Comment by gebart** [comment]
A clean build of examples/default does work on my Mulle board over here. @kYc0o could you try again with a clean build dir? (rm -rf bin/mulle)

**Comment by kYc0o** [comment]
I just rechecked and it works, I don't know if I was a clean directory before but I'm glad it was a mistake.

**Pull request merged**
