### PR TITLE
shell: sc_netif: add set/unset for flags

### PR DESCRIPTION
**Pull request by authmillenon**
It works exactly as the [POSIX](http://www.freebsd.org/cgi/man.cgi?ifconfig%288%29) [ifconfig](http://linux.die.net/man/8/ifconfig)

### CODE REVIEW

**Comment by OlegHahm** [comment]
How can I test?

**Comment by authmillenon** [comment]
E.g. with `tests/driver_xbee` (in general every app that supports `ng_netif0`). However, `tests/driver_xbee` does not support promiscous afaik, but at least you see if it compiles/the parsing is handled correctly. Maybe @kaspar030's new nativenet supports it or @haukepetersen's new atsomethingrfsomthing ;-)

**Comment by authmillenon** [comment]
The interesting for this PR is however not if the promiscuous mode gets activated, but if the command reaches the device driver. So maybe you can just activate DEBUG for this devices and they will say if say support it or not.

**Comment by OlegHahm** [comment]
But I would still need an xbee to test it, right?

**Comment by authmillenon** [comment]
With nativenet, no. I just gave driver_xbee as an example because it is the only one merged yet ;-)

**Comment by OlegHahm** [comment]
So, my basic question was: can I test with nativenet or do I need to merge anything addionally?

**Comment by authmillenon** [comment]
yes you can, and no you don't have to, at least to my knowledge.

**Comment by OlegHahm** [comment]
So, what would be the corresponding `ifconfig` command then? The online help wasn't very helpful for that.

**Comment by authmillenon** [comment]
`ifconfig promisc` to activate it `ifconfig -promisc` to deactivate it.

**Comment by authmillenon** [comment]
If the device you use does support promiscuous mode it should be notified with `PROMISC` when enabled with `ifconfig [<if>]`

**Comment by OlegHahm** [comment]
```
2015-04-20 10:26:21,436 - INFO # > ifconfig 0 promisc
2015-04-20 10:26:21,436 - INFO # 
2015-04-20 10:26:21,438 - INFO # Usage: ifconfig create <transceiver_1>[,<transceiver_2>,...]
2015-04-20 10:26:21,440 - INFO #        <transceiver_n> may be one of the following values:
2015-04-20 10:26:21,441 - INFO #         * native
2015-04-20 10:26:21,441 - INFO # 
2015-04-20 10:26:21,443 - INFO # or:    ifconfig [<if_id> [add <protocol> <addr>|set <key> <value>]]
```

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by authmillenon** [comment]
@OlegHahm you've got the `net_if` version of `ifconfig` there. You have to compile your application with `ng_netif`.

**Comment by haukepetersen** [comment]
Actually I have to say that I like the approach in #2846 far better: Just look at the code size. Even if it's not a 100% compatible to the POSIX ifconfig, I don't think it needs to be. In my opinion a smaller code size is the more pressing issue at hand (and the sc_netif is by far the largest module at the moment...)!

**Comment by authmillenon** [comment]
1. If we don't want to be POSIX compatible we should not call it `ifconfig`, and we should not advertise it.
2. You really could not argue about code size when it comes to shell.
3. There is room for optimization here, but using a totally different syntax than the original `ifconfig` is not the way to go IMHO.

**Comment by authmillenon** [comment]
Also: your comparison isn't really fair, because most of our changes are output, and you did not even implement output.

**Comment by authmillenon** [comment]
If I boil it down to just setting I've got 44 additions and 1 deletion lines (without RAW mode):

```diff
diff --git a/sys/shell/commands/sc_netif.c b/sys/shell/commands/sc_netif.c
index 76bcf4b..9c14e57 100644
--- a/sys/shell/commands/sc_netif.c
+++ b/sys/shell/commands/sc_netif.c
@@ -80,6 +80,11 @@ static void _set_usage(char *cmd_name)
          "       * \"state\" - set the device state\n");
 }
 
+static void _flag_usage(char *cmd_name)
+{
+    printf("usage: %s <if_id> [-]{promisc|autoack|preload}", cmd_name);
+}
+
 static void _print_netconf(ng_netconf_opt_t opt)
 {
     switch (opt) {
@@ -273,6 +278,15 @@ static void _netif_set_i16(kernel_pid_t dev, ng_netconf_opt_t opt,
     printf(" on interface %" PRIkernel_pid " to %i\n", dev, val);
 }
 
+static void _netif_set_flag(kernel_pid_t dev, ng_netconf_opt_t opt,
+                            ng_netconf_enable_t set)
+{
+    if (ng_netapi_set(dev, opt, 0, &set, sizeof(ng_netconf_enable_t)) < 0) {
+        puts("error: unable to set option");
+    }
+    printf("success: %sset option\n", (set) ? "" : "un");
+}
+
 static void _netif_set_addr(kernel_pid_t dev, ng_netconf_opt_t opt,
                             char *addr_str)
 {
@@ -361,6 +375,29 @@ static void _netif_set(char *cmd_name, kernel_pid_t dev, char *key, char *value)
     }
 }
 
+static int _netif_flag(char *cmd, kernel_pid_t dev, char *flag)
+{
+    ng_netconf_enable_t set = NETCONF_ENABLE;
+    if (flag[0] == '-') {
+        set = NETCONF_DISABLE;
+        flag++;
+    }
+    if (strcmp(flag, "promisc") == 0) {
+        _netif_set_flag(dev, NETCONF_OPT_PROMISCUOUSMODE, set);
+    }
+    else if (strcmp(flag, "preload") == 0) {
+        _netif_set_flag(dev, NETCONF_OPT_PRELOADING, set);
+    }
+    else if (strcmp(flag, "autoack") == 0) {
+        _netif_set_flag(dev, NETCONF_OPT_AUTOACK, set);
+    }
+    else {
+        _flag_usage(cmd);
+        return 1;
+    }
+    return 0;
+}
+
 /* shell commands */
 int _netif_send(int argc, char **argv)
 {
@@ -441,12 +478,17 @@ int _netif_config(int argc, char **argv)
             }
 
             /* TODO implement add for IP addresses */
+            else {
+                return _netif_flag(argv[0], dev, argv[2]);
+            }
         }
         else {
             puts("error: invalid interface given");
         }
     }
 
-    printf("usage: %s [<if_id> set <key> <value>]]\n", argv[0]);
+    printf("usage: %s <if_id>\n", argv[0]);
+    _set_usage(argv[0]);
+    _flag_usage(argv[0]);
     return 1;
 }
```

**Comment by haukepetersen** [comment]
ok ok, lets go with this.

**Comment by haukepetersen** [comment]
works. ACK when squashed.

**Comment by authmillenon** [comment]
Squashed

**Comment by haukepetersen** [comment]
nice. Lets wait for Travis I guess?

**Pull request merged**
