### PR TITLE
lgtm.yml: initial import

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This configures LGTM.com to analyse our repository. This is in a very stage as I still need to get my head around the config file format myself.

### Testing procedure
Let LGTM.com do the job.

### Issues/PRs references
None

### CODE REVIEW

**Comment by kaspar030** [comment]
should LGTM be compiling code already? Seems to only be working on JavaScript, Python.

**Comment by miri64** [comment]
Yeah, how to convince it otherwise :-/. As far _as I understand_ the configuration format it _should_ now at least for this PR check C/C++ and Python... It does not however :-/...

**Comment by miri64** [comment]
Preliminary analysis: this is not as easy to integrate for us, as I thought ...

**Comment by miri64** [comment]
I fear it expect one dedicated C application to be in the repository :-/. I think given that (alternatively the amount of work to adapt it to our use case) it is not really worth it. I'm deactivating this again for now. If someone else have a look, feel free to try.

**Pull request closed without merging**
