### PR TITLE
spi: doc typo

### PR DESCRIPTION
**Pull request by dkm**
2 typos found when reading SPI doc.

### CODE REVIEW

**Comment by aabadie** [comment]
Strange, I saw Jenkins green some time ago and then red...

**Comment by cgundogan** [comment]
> Strange, I saw Jenkins green some time ago and then red...

@aabadie I did a rebuild out of curiosity how the jobs are balanced across the slaves. Should be green again in several minutes.

**Comment by aabadie** [comment]
Thanks @cgundogan. Looks better now. Merging this one.

**Comment by dkm** [comment]
Thanks :)

**Pull request merged**
