### PR TITLE
tests/driver_netdev_common: add compile-test for network drivers

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Each driver should have at least a compile-test so that Murdock can spot commits that break the build.

This generalizes the rather generic test for `at86rf215` and adds new tests for `mrf24j40` and `dose`, two network drivers which currently don't have any board that uses them by default.

### Testing procedure

Murdock should do all the testing.

### CODE REVIEW

**Comment by gschorcht** [comment]
@benpicco What about `tests/driver_xbee`? It seems to be the same test app.

**Comment by gschorcht** [comment]
@benpicco Can we merge. I will provide an according test for PR #13754.

**Comment by gschorcht** [comment]
> @benpicco Can we merge?

I would have done it for you (you know you shouldn't merge your own PRs), I just wanted to make sure you were ready :wink:

**Comment by benpicco** [comment]
> you know you shouldn't merge your own PRs

I still don't think such a rule exists :wink:

**Comment by fjmolinas** [comment]
I'm not sure how this happened but when I check out this PR `arduino-nano` doesn't fit, but it somehow got through with murdock:

```
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.text' will not fit in region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x801728 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x8037f1 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x8037f3 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.noinit' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x801728 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.data' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x8037f1 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.bss' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: address 0x8037f3 of /data/riotbuild/riotbase/tests/driver_mrf24j40/bin/arduino-nano/tests_driver_mrf24j40.elf section `.noinit' is not within region `data'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: region `text' overflowed by 9316 bytes
collect2: error: ld returned 1 exit status
```

This is currently leading to compile failures in unrelated PR. It's an easy fix, I'm more concerned with understanding how this got though.

**Comment by benpicco** [comment]
The same thing happened with another PR before :confused: 
@kaspar030 do you know what might be going on there?

**Pull request merged**
