### PR TITLE
cpu/stm32: unify cpu_init()

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

stm32's cpu.c look the same on all stm32fx and stm32l4, and almost identical for stm32l0&1.

This PR unifies accordingly.

### CODE REVIEW

**Comment by aabadie** [comment]
Very nice !

**Comment by aabadie** [comment]
> stm32's cpu.c look the same on all stm32fx and stm32l4

Looking at the code, the stmclk.c hasn't been merged with other `stm32fx`. Is there something I missed ?

**Comment by aabadie** [comment]
Just to keep track of the testing on cpu family boards:
- [X] stm32l0: works on b-l072z-lrwan1
- [ ]  stm32l1
- [ ] stm32l4
- [ ]  stm32f0
- [ ] stm32f1
- [ ]  stm32f2
- [ ] stm32f3
- [ ]  stm32f4
- [ ] stm32f7

**Comment by aabadie** [comment]
I let @haukepetersen a chance to review this, just in case.

**Comment by kaspar030** [comment]
> Looking at the code, the stmclk.c of stm32l4 hasn't been merged with other stm32fx. Is there something I missed ?

True, I missed that file. But it seems to have quite some differences, thus it'll have to go folo.

**Comment by haukepetersen** [comment]
all green -> go go go

**Pull request merged**
