### PR TITLE
shell: add ng_ipv6 support for ifconfig

### PR DESCRIPTION
**Pull request by authmillenon**
~~Depends on #2736~~ (merged)

~~Waiting for #2602~~ (merged) 

Ports the listing functionality, `ifconfig add` and `ifconfig del` for `ng_ipv6_netif`.

### CODE REVIEW

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by OlegHahm** [comment]
Which configuration/branch do I have to use to test this?

**Comment by authmillenon** [comment]
Try authmillenon/RIOT@138d113 (current HEAD of branch authmillenon/tmp):

```
$ git log --simplify-by-decoration --decorate --graph --oneline 138d113
* 138d113 (origin/tmp, tmp) Adapt default application
*   ece2378 Merge branch 'ng_netreg/feat/allow_nettype_undef' into HEAD
|\  
| * 7f7e5f2 (origin/ng_netreg/feat/allow_nettype_undef, ng_netreg/feat/allow_nettype_undef) [SQUASH ME] netreg: fix look
* |   bf76871 Merge branch 'shell/feat/ifconfig-ipv6-output' into HEAD
|\ \  
| * | ac99c22 (origin/shell/feat/ifconfig-ipv6-output, shell/feat/ifconfig-ipv6-output) [SQUASH ME] ifconfig: fixes
* | | 1c4c35a (origin/ng_tapnet/feat/initial, ng_tapnet/feat/initial) [SQUASH ME] ng_tapnet: fix ethernet check
[…]
```

**Comment by authmillenon** [comment]
(with default application ;-))

**Comment by authmillenon** [comment]
rebased to master

**Comment by authmillenon** [comment]
@OlegHahm you can also now compile `tests/ng_tapnet` in #2558 with

```bash
USEMODULE=ng_ipv6_if make all term
```

if you merge this branch in.

**Comment by authmillenon** [comment]
Merge stalled before #2602 is merged.

**Comment by authmillenon** [comment]
Adapted for return values and prefixes

**Comment by authmillenon** [comment]
Rebased to current #2736.

**Comment by authmillenon** [comment]
Rebased to current #2736

**Comment by OlegHahm** [comment]
Needs rebase

**Comment by authmillenon** [comment]
I don't know why, but when I rebase #2582 and rebase this PR to that, it is still not mergable. So please review #2582 first ;-)

**Comment by OlegHahm** [comment]
You mean https://github.com/RIOT-OS/RIOT/pull/2736?

**Comment by authmillenon** [comment]
Yes.

**Comment by authmillenon** [comment]
Rebased to current #2736 and the rebase problem seems to be fixed

**Comment by authmillenon** [comment]
Rebased to current #2736 and squashed

**Comment by authmillenon** [comment]
Rebased to current master

**Comment by OlegHahm** [comment]
```
/home/oleg/git/RIOT/sys/shell/commands/sc_netif.c: In function ‘_netif_list’
/home/oleg/git/RIOT/sys/shell/commands/sc_netif.c:272:45: error: ‘NG_IPV6_NETIF_FLAGS_NON_UNICAST’ undeclared (first use in this function)
                 if (entry->addrs[i].flags & NG_IPV6_NETIF_FLAGS_NON_UNICAST) {
                                             ^
```
Am I missing something?

**Comment by authmillenon** [comment]
No, I did. Will fix.

**Comment by authmillenon** [comment]
Rebased to current master and adapted for changes there (including https://github.com/RIOT-OS/RIOT/pull/2582#issuecomment-956498)

**Comment by OlegHahm** [comment]
How do I test on native? ng_tapnet is gone and I don't know how to use Kaspar's Ethernet foobar.

**Comment by kaspar030** [comment]
@OlegHahm Did you take a look at my Ethernet foobar? It's rather simple. The ```test/driver_netdev_eth``` shows how to initialize everything up to the mac layer.

**Comment by OlegHahm** [comment]
I did briefly look at it (I'm in a local train with shitty Internet connection right now) and copied stuff from the test Makefile, but I got:
```
/home/oleg/git/RIOT/examples/default/bin/native/ng_nativenet.a(dev_eth_tap.o): In function `_isr'
dev_eth_tap.c:(.text+0xe9): undefined reference to `dev_eth_rx_handler'
/home/oleg/git/RIOT/examples/default/bin/native/ng_nativenet.a(dev_eth_tap.o): In function `_tap_isr'
dev_eth_tap.c:(.text+0x4e3): undefined reference to `dev_eth_isr'
collect2: error: ld returned 1 exit status
/home/oleg/git/RIOT/examples/default/../../Makefile.include:162: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by kaspar030** [comment]
@OlegHahm Try to add "ng_netdev_eth" and "ng_nativenet" to USEMODULES.

**Comment by OlegHahm** [comment]
Thanks. Worked. `ng_netdev_eth` was mising.

**Comment by OlegHahm** [comment]
Ok, after merging this PR and #2766 and #2776 in order to test on native, I'm able to build. (`make term` is broken but I guess that's related to the two WIP PRs.)

However, in the shell I get:
```
> help
help
Command              Description
---------------------------------------
reboot               Reboot the node
ps                   Prints information about running threads.
cur                  Prints current and average power consumption.
rstcur               Resets coulomb counter.
mersenne_init        initializes the PRNG
mersenne_get         returns 32 bit of pseudo randomness
rtc                  control RTC peripheral interface
ifconfig             Configure network interfaces
txtsnd               send raw data
> ifconfig
ifconfig
>
```

My Makefile diff looks like
```diff
diff --git a/examples/default/Makefile b/examples/default/Makefile
index dfaee97..db9aac9 100644
--- a/examples/default/Makefile
+++ b/examples/default/Makefile
@@ -34,10 +34,15 @@ USEMODULE += shell
 USEMODULE += shell_commands
 USEMODULE += ps
 USEMODULE += vtimer
-USEMODULE += defaulttransceiver
 USEMODULE += config
 
-FEATURES_OPTIONAL += transceiver
+USEMODULE += ng_netbase
+USEMODULE += ng_nomac
+USEMODULE += ng_nativenet
+USEMODULE += dev_eth_autoinit
+USEMODULE += ng_ipv6_netif
+USEMODULE += ng_netdev_eth
+
 FEATURES_OPTIONAL += config
 FEATURES_OPTIONAL += periph_rtc
```

**Comment by authmillenon** [comment]
@OlegHahm what were your changes to `main.c`? If you did not change anything, there is of course no interface, because it wasn't initialized.

**Comment by authmillenon** [comment]
Use `tests/driver_netdev_eth` with the following change:

```diff
diff --git a/tests/driver_netdev_eth/Makefile b/tests/driver_netdev_eth/Makefile
index 1ed3733..f7d9e25 100644
--- a/tests/driver_netdev_eth/Makefile
+++ b/tests/driver_netdev_eth/Makefile
@@ -6,6 +6,7 @@ BOARD_WHITELIST := native
 USEMODULE += ng_nativenet
 USEMODULE += ng_netbase
 USEMODULE += ng_nomac
+USEMODULE += ng_ipv6
 USEMODULE += ng_pktdump
 USEMODULE += ng_netdev_eth
 USEMODULE += shell
```

**Comment by authmillenon** [comment]
```
$ ./tests/driver_netdev_eth/bin/native/driver_netdev_eth.elf tap0
RIOT native interrupts/signals initialized.
LED_GREEN_OFF
LED_RED_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

kernel_init(): This is RIOT! (Version: 2014.12-1137-gf0d679-beutlin-tmp)
kernel_init(): jumping into first task...
netdev ethernet device driver test
> ifconfig 5
ifconfig 5
Iface  5   HWaddr: f2:30:3c:e2:5f:6a 
           inet6 addr: ff02::1/128  scope: local [multicast]
           
> ifconfig 5 add fe80::2
ifconfig 5 add fe80::2
success: added fe80::2/128 to interface 5
> ifconfig
ifconfig
Iface  5   HWaddr: f2:30:3c:e2:5f:6a 
           inet6 addr: ff02::1/128  scope: local [multicast]
           inet6 addr: fe80::2/128  scope: local
```

**Comment by authmillenon** [comment]
```
$ git log --graph --simplify-by-decoration --decorate --oneline
*   f0d6798 (HEAD, tmp) Merge remote-tracking branch 'kaspar/add_dev_eth_netdev2' into tmp
|\  
| * 03cd524 (kaspar/add_dev_eth_netdev2) net: netdev_eth: output warning on lost interrupt
| * a7c53f5 (kaspar/add_dev_eth) dev_eth_tap: increase mac address last byte by one
* | fded17f (origin/shell/feat/ifconfig-ipv6-output, shell/feat/ifconfig-ipv6-output) [SQUASH ME] shell: sc_netif: fix for chan
[…]
```

**Comment by kaspar030** [comment]
ACK when squashed.

**Comment by authmillenon** [comment]
Squashed.

**Comment by kaspar030** [comment]
and GO.

**Pull request merged**
