### PR TITLE
examples: add blinker application [RFC]

### PR DESCRIPTION
**Pull request by aabadie**
Minor improvement (imho) of the hello-world example: after the well-known message is displayed, starts an a blinking led in a infinite loop.
This can sometimes be useful for LED debugging.

### CODE REVIEW

**Comment by kaspar030** [comment]
I think a "blinker" deserves it's own example app.

The main reason for this is that "hello-world" hasn't changed since 2014. It is the longest-stable baseline for comparison of build sizes / RAM usage of all other (board/MCU dependent) code.

Other than that, why not use gpio_toggle() (or LED0_TOGGLE())?

**Comment by aabadie** [comment]
> The main reason for this is that "hello-world" hasn't changed since 2014.

I see. Will add the blinker example then, if people agree.

> why not use gpio_toggle() (or LED0_TOGGLE())?

Ah yes indeed...

**Comment by smlng** [comment]
I'm with @kaspar030 hello-world should stay as is. For LEDs there is already `tests/leds`, so no need to re-invent the wheel ...

**Comment by kaspar030** [comment]
> For LEDs there is already tests/leds, so no need to re-invent the wheel ...

A blinker is a classical example for how to use any embedded software stack, though... Would it hurt?

**Comment by smlng** [comment]
> Would it hurt?

code duplication? What would be the difference of such an example to the existing test besides its placement in the examples directory?

**Comment by aabadie** [comment]
> What would be the difference of such an example to the existing test besides its placement in the examples directory?

simplicity.
Examples should be kept simple for newcomers to get into RIOT as fast as possible. The tests/leds play with all on-board leds without xtimer delay (calling asm nop) whereas a blinker could show 2 things in a simpler fashion: extra modules (xtimer), playing with led macros.

**Comment by aabadie** [comment]
Reverted the previous changes and added a dedicated blinker application. I'm open to good ideas of improvements (or rejection)

**Comment by haukepetersen** [comment]
I am against this example, as it is trivial. For testing the LED macros there is the test application, and if one wants to let a LED blink, everyone new to RIOT should be able to do that on their own without an example...

**Comment by smlng** [comment]
> everyone new to RIOT should be able to do that on their own without an example...

learning by doing: I strongly agree!

**Comment by smlng** [comment]
btw. there is also a tutorial task on [that](https://github.com/RIOT-OS/Tutorials/tree/master/task-02), which newbies hopefully will go through. Providing the example will take away all the _fun_ of solving this on their own 😉

**Comment by aabadie** [comment]
I got your points guys. I guess we can close this one then.

I still think a blinker "hello-world" example is must have for an embedded OS. That's why I initially applied this change the hello-world  application. Most of the people won't go to the tutorials or tests at the very beginning but will look at the examples.

**Pull request closed without merging**
