### PR TITLE
examples: tests: optimize for NIB

### PR DESCRIPTION
**Pull request by miri64**
Apparently, I forgot to adapt `gnrc_minimal` for the NIB (`GNRC_IPV6_NC_SIZE` does not exist anymore). Reasoning for the values:

* `GNRC_IPV6_NIB_NUMOF` same as `GNRC_IPV6_NC_SIZE`
* `GNRC_IPV6_NIB_OFFL_NUMOF` be able to configure at least one route to a sub-net.

### CODE REVIEW

**Comment by miri64** [comment]
Scrapes off ~700B of RAM, at least on Cortex-M0.

**Comment by cladmi** [comment]
I see there is also still `GNRC_IPV6_NC_SIZE` in `tests/gnrc_sock_dns/Makefile`

**Comment by cladmi** [comment]
Could you add your the explanation of the `GNRC_IPV6_NIB_OFFL_NUMOF` value in the commit message body ? It helps when git blaming in the future :)

I would assume the reason we are using `1` here is to allow compiling on smaller boards, right ?

**Comment by miri64** [comment]
> I would assume the reason we are using 1 here is to allow compiling on smaller boards, right ?

Well the name of the example is minimal, and having only one forwarding entry, is the most minimal configuration that still makes sense.

On your other comments will address, just need to finish something else first.

**Comment by cladmi** [comment]
> Well the name of the example is minimal, and having only one forwarding entry, is the most minimal configuration that still makes sense.

Yeah I figured it out after re-reading the name of the example

**Comment by miri64** [comment]
Comments addressed. The `BOARD_INSUFFIENT_MEMORY` change is just for testing. I might revert parts of it ;-).

**Comment by miri64** [comment]
\o/ I reached my optimization goal! We can fit GNRC on a `chronos` now ^^.

**Comment by miri64** [comment]
(even in router configuration oO)

**Comment by miri64** [comment]
Squashed and rebased.

**Pull request merged**
