### PR TITLE
core: atomic: add atomic_and() and atomic_or()

### PR DESCRIPTION
**Pull request by kaspar030**

### CODE REVIEW

**Comment by kaspar030** [comment]
@gebart, didn't you initially add the atomic functions?

I used atomic_and() and atomic_or() in an early version of thread flags. No I don't need them anymore, but I had the commit lying around...

**Comment by gebart** [comment]
yep, I did. The atomic implementations are ready for an overhaul though, based on the discussions about volatile in #4700 and maybe using the compiler builtins as far as possible

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by gebart** [comment]
Closing in favour of #5688 which gets rid of our atomic.h header and supports all compiler builtins and C11 atomics in GCC+Clang.

**Pull request closed without merging**
