### PR TITLE
drivers/dev_enums: Remove unused dev_enums.h

### LINKED ISSUE #7941: periph: remove dev_enums.h
The `drivers/include/periph/dev_enums.h` file was introduced for backwards compatibility when we changed the style of doing the board configuration in `periph_conf.h` some time ago. Most of the periph drivers are remodeled by now, though some are open. Except the `i2c` drivers, which will be remodeled while reworking the complete interface, the following drivers need adaption:

timer:
- [ ] samd21
- [ ] saml21 (best to unify these two into sam0_common in the same process)
- [ ] lm4f120
- [ ] lpc1768

uart:
- [ ] cc2538
- [ ] lm4f120
- [ ] lpc1768

I did not really check the open PRs though, so there might be a fix for some of the mentioned in the pipeline already. Please check before starting to work on any of these...

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Now that all dependencies of `dev_enums.h` are resolved we can completely remove it.

### Testing procedure

Only needs a green from the build test.

### Issues/PRs references

Fixes #7941

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Yikes murdock is not green, I will investigate.

**Comment by MrKevinWeiss** [comment]
Murdock is all green.  It should be a quick one!

**Review by aabadie — APPROVED** [review]
Looks all good here.

ACK

**Comment by MrKevinWeiss** [comment]
Thanks for the review!

**Pull request merged**
