### PR TITLE
pkg/nanors: model in kconfig

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Seems relatively easy on first sight but the inclusion of the random module will fail on Murdock:

```
$ make -C tests/pkg_nanors/ clean info-modules --no-print-directory > /tmp/make-modules && TEST_KCONFIG=1 make -C tests/pkg_nanors/ clean info-modules --no-print-directory > /tmp/kconfig-modules && diff /tmp/make-modules /tmp/kconfig-modules 
1c1,3
< rm -rf /work/riot/RIOT/tests/pkg_nanors/bin/native/pkg-build/nanors
---
> === [ATTENTION] Testing Kconfig dependency modelling ===
> === [ATTENTION] Testing Kconfig dependency modelling ===
> make: Nothing to be done for 'clean'.
40c42
< prng_musl_lcg
---
> prng_hwrng
```

This is the same problem as in #18005 

### Testing procedure

Green Murdock

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
Ok, so that's another case where the specific implementation must be selected explicitly in the application config file.

**Review by MrKevinWeiss — COMMENTED** [review]
Normally I would add a note saying this is a hack to match the make system but when we do the switch we will probably just grep for `CONFIG_MODULE_RANDOM`.

Though I prefer this solution I guess Leandro prevents the kconfig selecting the hwrng and copied make completely. Your choice how you want to solve it.

I reran murdock because of the stange esp error.

**Comment by aabadie** [comment]
> I  would add a note saying this is a hack to match the make system

Done that using the same comment used in other applications

**Review by MrKevinWeiss — APPROVED** [review]
ACK!

**Pull request merged**
