### PR TITLE
drivers/periph: enhance low-level peripheral driver doc

### PR DESCRIPTION
**Pull request by PeterKietzmann**
I instantly stopped writing on this after I realized that #4072 is deprecated and responsibilities changed. @haukepetersen I'm willing to help -but please- give me some guidance then. Especially in terms of what is already done by you (and maybe what **needs** to be documented in your opinion).

PS: Feel free to close a or just use this as a starting point, if you haven't already begun...

### CODE REVIEW

**Comment by haukepetersen** [comment]
@PeterKietzmann: I have actually also started on this, though not very much done yet. I plan to put some hours into writing extensive periph driver documentation this week... So I suggest to keep this PR open until I open a new one. If you want to help, you could start to write some more in-depth documentation for the GPIO and the UART drivers, maybe in the same style as I tried for the ADC/DAC driver updates (#4430/#4431)

**Comment by PeterKietzmann** [comment]
@haukepetersen I will give it a try. Don't think I will start before tomorrow.

**Comment by haukepetersen** [comment]
Nice. Let's sync tonight when I am in HH...

**Comment by PeterKietzmann** [comment]
I don't think we need to keep this PR open as a reminder any more.

**Pull request closed without merging**
