### PR TITLE
pkg/nimble: bump NimBLE version

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
NimBLE has again advanced over the last months, many bug fixes to controller and host... This new commit is now also based on the NimBLE 1.2.0 Version.

### Testing procedure
Verify that `examples/nimble_gatt` and the `tests/nimble_l2cap[_server]` applicatoins still work as expected.

### Issues/PRs references
none

### CODE REVIEW

**Comment by miri64** [comment]
Murdock had an unrelated error during the run of `tests/thread_flags` on `native`

**Comment by aabadie** [comment]
@miri64, maybe also test on an nrf51 based board ?

**Comment by miri64** [comment]
Good idea @aabadie. Tested `nimble_gatt` also on `microbit` and `nimble_l2cap*` between a `microbit` (as server) and a `calliope-mini`. With this it is the other way around `flood` works without any problems, `flood 250 10` (250 is the largest packet size possible) leads to the failed assertion. This however, I couldn't reproduce on current master.

**Comment by miri64** [comment]
Ah, it is also a different assertion for nrf51:

```
2019-10-07 14:25:18,570 # tests/nimble_l2cap_server/main.c:72 => 0xc49
2019-10-07 14:25:18,572 # *** RIOT kernel panic:
2019-10-07 14:25:18,573 # FAILED ASSERTION.
```

**Comment by haukepetersen** [comment]
both are buffer related errors, seems like NimBLE changed something in the way it manages buffers for l2cap COCs. Will look into it now.

**Comment by haukepetersen** [comment]
Pushed a fix for the l2cap server test application. Now I was not able to crash the test neither on `nrf52dk` nor on `nrf51`-based boards (`calliope-mini` and `microbit`).

**Comment by miri64** [comment]
> With this it is the other way around `flood` works without any problems, `flood 250 10` (250 is the largest packet size possible) leads to the failed assertion. This however, I couldn't reproduce on current master.

I retried this today and I was able to reproduce this on master after all. Maybe just a fluke or PEBCAK, as I had some problems flashing the two `nrf51` boards with the right version.

**Pull request merged**
