### PR TITLE
ci: activate compile for raspberry native

### PR DESCRIPTION
**Pull request by smlng**
well the title says it all

### CODE REVIEW

**Comment by cgundogan** [comment]
we should probably attach more pis, otherwise this will slow down parallel PR builds

**Comment by smlng** [comment]
will do tomorrow ...

**Comment by waehlisch** [comment]
This needs some thoughts. We don't want that the PIs thwart the overall build process.

**Comment by smlng** [comment]
I'll close this one, @cgundogan and I found, that the RasPi integration will slow down all builds. Will include in a future nightly build maybe.

**Pull request closed without merging**
