### PR TITLE
cpu/nrf51822: use core_panic in startup code

### PR DESCRIPTION
**Pull request by haukepetersen**
added missing `crash.c` files to cortex M0 and M4 common and integrated them into the NRF51822 cpu

~~base on #2415~~

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
The PR is a bit off then..

**Comment by haukepetersen** [comment]
off?

**Comment by LudwigOrtmann** [comment]
Well, it's not mentioning that the crash.c implementation is added (which is not an insignificant part of this PR).

**Comment by LudwigOrtmann** [comment]
In fact I would have opened two PRs for this ;)

**Comment by haukepetersen** [comment]
Come on... It just copied over from cortex-M3, so it's not something new...

**Comment by LudwigOrtmann** [comment]
I don't care how the code came into existence, it's a major part of this PR and isn't mentioned in the title. What's wrong with pointing that out?

**Comment by LudwigOrtmann** [comment]
By the way - if it's an exact copy, why don't you refactor it into a cortex-common structure?

**Comment by gebart** [comment]
Actually, there is nothing processor specific in the crash.c file, would it not be more fitting to move it to `core` or `sys`?

**Comment by LudwigOrtmann** [comment]
I think there is for other architectures.

**Comment by haukepetersen** [comment]
@LudwigOrtmann: ok, I see your point with the PR's... 

About the location of crash.c: putting it into `core` could be an option, but there are slight differences between native, msp430 and cortex versions of the file. Maybe that is something we someone can improve later.
Putting it in a `cortex-common` folder I don't like it too much - it makes finding files more complicated while a little code duplication is a small price to pay for simple folder structures...

**Comment by haukepetersen** [comment]
ok, removed the unrelated commits and rebased this PR on #2415

**Comment by mehlis** [comment]
I'm ok with this PR, travis had a timeout....

**Comment by LudwigOrtmann** [comment]
@haukepetersen please rebase

**Comment by haukepetersen** [comment]
rebased.

**Comment by thomaseichinger** [comment]
ACK & Go

**Pull request merged**
