### PR TITLE
boards*: documentation cleanup

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

#8516 was merged and there are some inconsistencies in the [boards module page](http://doc.riot-os.org/group__boards.html):
- For some board, a copyright is displayed instead of the brief description
- For native, a link to the "Family:native" wiki page is displayed instead of the  brief description
- For some other boards, the brief description is not consistent with other (it should start with "Support for ...")

This PR fixes that.

### Issues/PRs references

Can be considered as a small follow-up of #8516

### CODE REVIEW

**Comment by jia200x** [comment]
Thank you so much for the fixes. I will test it locally now.

**Comment by jia200x** [comment]
works as expected on my side

**Comment by jia200x** [comment]
Murdock found a missing group that was not shown in my `make doc`. I will check

**Comment by jia200x** [comment]
The `boards_frdm-kw41z` doesn't provide a doc.txt file. That's why it throws error.

**Comment by jia200x** [comment]
> Ah, sorry, I forgot to add the file, that's why. It's fixed now, directly squashed the last commit.

Perfect. Let's check

**Comment by aabadie** [comment]
@jia200x, Murdock is green now.

**Comment by jia200x** [comment]
& GO

**Pull request merged**
