### PR TITLE
gnrc_sixlowpan_iphc_nhc: fix NHC UDP decoding for fragmented packets

### PR DESCRIPTION
**Pull request by authmillenon**
While running my experiments for my masterthesis I realized that our NHC implementation isn't really able to handle fragmented packets. With this fix it does though it's really ugly.

### CODE REVIEW

**Comment by gebart** [comment]
Tested working with a Contiki RPL border router connected to Linux, RIOT gnrc_networking example on mulle and using netcat on linux to send long strings to the RIOT node. Without this patch only strings less than 50-something chars could get through.

About the supposed uglyness, I'll leave that to someone more involved with the gnrc stack to decide.

**Comment by OlegHahm** [comment]
If this is working, I think we can live with it. I've seen uglier code.

**Comment by gebart** [comment]
Somewhat related Q: Is there any risk of leaking memory when fragments get lost or are the partial packets freed somewhere?

**Comment by cgundogan** [comment]
@gebart obsolete fragments should be gc'ed [here](https://github.com/authmillenon/RIOT/blob/gnrc_sixlowpan_iphc_nhc/fix/frag/sys/net/gnrc/network_layer/sixlowpan/frag/rbuf.c#L251)

**Comment by authmillenon** [comment]
> Somewhat related Q: Is there any risk of leaking memory when fragments get lost or are the partial packets freed somewhere?

@Yonezawa-T2 already has a PR open for that: #4771.

**Comment by authmillenon** [comment]
Added a fix for compiling without NHC.

**Comment by cgundogan** [comment]
okay, will test with the fix a little bit later. And where is the `[ci skip]` in your fixup commit message? (;

**Comment by cgundogan** [comment]
still need to do some tests with a linux-based boarder router. I have no hardware around today, so I can do it tomorrow

**Comment by authmillenon** [comment]
> And where is the [ci skip] in your fixup commit message? (;

I forward your complaints to the git developers since they still don't allow me to configure the prefix generated by `git commit --fixup=<commit>` and picked up by `git rebase -i --autosquash` ;-)

**Comment by authmillenon** [comment]
(Done)

**Comment by authmillenon** [comment]
((http://permalink.gmane.org/gmane.comp.version-control.git/288173))

**Comment by cgundogan** [comment]
>((http://permalink.gmane.org/gmane.comp.version-control.git/288173))

(Y) couldn't this be fixed with some pre-commit hooks?

**Comment by authmillenon** [comment]
Not if I want the commit still be picked up by `--autosquash` ;-)

**Comment by cgundogan** [comment]
I understand `--autosquash` as a mechanism that inspects the prefix and sets the action while rebasing. In a pre-commit hook you could juts append `[ci skip]` at the end of the commit message?

**Comment by authmillenon** [comment]
I can try, but as far as I undestand the prefixing is the other way around.

**Comment by cgundogan** [comment]
>I can try, but as far as I undestand the prefixing is the other way around.

keep me informed, I would like to copy your fixup process (:

**Comment by authmillenon** [comment]
Nope. Appending or prepending `[ci skip]` to the commit message (either the original or the generated) will cause `--autosquash` not to pickup the commit. :(

**Comment by authmillenon** [comment]
</OT>

**Comment by authmillenon** [comment]
Last commit is a test of something someone proposed on the mailinglist.

**Comment by authmillenon** [comment]
(and removed: seemed to work).

**Comment by gebart** [comment]
@cgundogan did you have a chance to test this today?

**Comment by gebart** [comment]
@authmillenon OK to squash the mini fixup commit

**Comment by authmillenon** [comment]
Done.

**Comment by cgundogan** [comment]
@gebart thanks for the reminder.
I just ran a test with a phytec wega board as a linux border router and a samr21-xpro running the microcoap example. I modified the coap handler to return a long lorem ipsum string.
I explicitely enabled `gnrc_sixlowpan_iphc_nhc` in the Makefile of that example.

https://www.cloudshark.org/captures/062253ad8832

@authmillenon looks correct?

**Comment by authmillenon** [comment]
Mh… I don't know your setup, but did you make sure that a RIOT node received the long coap packet? When it successfully received the packet it is correct. :-)

**Comment by cgundogan** [comment]
nope, the coap message from the linux side was very small (coap get). Only the response from riot -> linux was big (:

**Comment by authmillenon** [comment]
That explains why your previous tries were working ;-). This fix is for *reception* of fragmented NHC encoded packets. So if you are just send those with RIOT you do not test anything touched by this PR ;-)

**Comment by authmillenon** [comment]
An alternative test would be to use my patch in https://github.com/RIOT-OS/Release-Specs/issues/10#issuecomment-165987449 to send 1 KiB sized packets between two RIOT nodes. @cgundogan just needed to go, so if someone else wants to test until monday: knock yourselves out ;-)

**Comment by authmillenon** [comment]
A friendly reminder for @cgundogan to test this tomorrow ;-)

**Comment by authmillenon** [comment]
@cgundogan ping?

**Comment by gebart** [comment]
I am having a problem with the BR dropping the entire payload part of a forwarded UDP packet, possibly related to this PR. Currently investigating..

**Comment by authmillenon** [comment]
Related as in this PR fixes it or this PR causes it?

**Comment by authmillenon** [comment]
The fix for the border router NHC is at #4544 btw.

**Comment by gebart** [comment]
@authmillenon Thanks for the hint, I'll try that PR

**Comment by cgundogan** [comment]
will test tomorrow - I promise (;

**Comment by authmillenon** [comment]
I'm waiting in anticipation :)

**Comment by cgundogan** [comment]
I don't say anything else, before I spread out more empty promises (:
Will be around noon at the university. If you are also there, maybe we can test/confirm it together.

**Comment by cgundogan** [comment]
tested together with @authmillenon between two RIOT nodes and also with a RIOT node with a linux node.
NHC breaks on master and works with this branch. ACK!

**Comment by cgundogan** [comment]
travis is happy, let's see what Murdock has to say.

**Comment by cgundogan** [comment]
@gebart is there an issue somewhere describing this? Maybe I can also invest some time debugging that.

Nevertheless, travis && murdock are happy! GO

**Comment by gebart** [comment]
@cgundogan I think the problem is that #4544 does not fix everything with regards to UDP NHC and fragmented packets

**Pull request merged**
