### PR TITLE
saul: use const for device parameter

### PR DESCRIPTION
**Pull request by smlng**
follow up on #7213, #7243, and #7244

### CODE REVIEW

**Comment by miri64** [comment]
Out of pure interest (in general I think this is a good idea): can we see any significant size changes in the image sizes due to this change?

**Comment by smlng** [comment]
Size of `.elf` file for `pba-d-01-kw2x` and `examples/saul` for master branch is `1086144` bytes and with this PR `1086108` bytes, diff of `36` bytes, so not that much - but not worse either.

**Comment by smlng** [comment]
most of this PR is more like: _do not cast away constness_ and consistency anyway, not so much hoping for size optimisation.

**Comment by haukepetersen** [comment]
@smlng just for future reference: the size of the .elf file does not have any implications on the actual code size, so the relevant data for us is the size of the binary, or better the output of `arm-none-eabi-size ELFFILE.elf`...

**Comment by haukepetersen** [comment]
and 36 byte are significant...

**Comment by miri64** [comment]
> @smlng just for future reference: the size of the .elf file does not have any implications on the actual code size, so the relevant data for us is the size of the binary, or better the output of arm-none-eabi-size ELFFILE.elf...

Addendum to the addendum: The output of this command you see at the end of a successful build (examplified by the output I get from building `examples/saul` on 946256d):

```
  30164	    504	   3480	  34148	   8564	examples/saul/bin/pba-d-01-kw2x/default.elf
```

Binary size doesn't change for me btw in comparison to parent b0aaf8d.

**Comment by smlng** [comment]
> Binary size doesn't change for me btw in comparison

so we are good here, right? Though, one might have expected some negligible effect on code size in either direction - however, it got not worse 😉

**Comment by haukepetersen** [comment]
yepp, all good.

**Pull request merged**
