### PR TITLE
net/ng_netconf: add reset state to ng_netconf_state_t

### PR DESCRIPTION
**Pull request by thomaseichinger**

### CODE REVIEW

**Comment by authmillenon** [comment]
Can you explain, what it is needed for, why you can't use any of the given options, and what it does (for me as a not-so-hardware gal ;-))?

**Comment by thomaseichinger** [comment]
`set(dev, NET_OPT_STATE, NETCONF_STATE_RESET, sizeof(ng_netconf_state_t));` should trigger hardware (re)initialisation and result in `get(dev, NET_OPT_STATE, state, sizeof(ng_netconf_state_t));` with `state == NETCONF_STATE_IDLE`. It can be used when initialising the driver for the first time or in case of misconfiguration or similar error case.
I guess it could be mapped by using `NETCONF_STATE_OFF` and `NETCONF_STATE_IDLE` but ,depending on the hardware, `NETCONF_STATE_RESET` could do this faster.

**Comment by authmillenon** [comment]
In general ok, but I think I better leave this decission to @haukepetersen

**Comment by haukepetersen** [comment]
ACK

**Comment by LudwigOrtmann** [comment]
Could you please document this transition assumption (state => NETCONF_STATE_IDLE)?

**Comment by thomaseichinger** [comment]
@haukepetersen @authmillenon Should `NETCONF_STATE_TX` put the radio device into tx mode or should it **trigger** an actual transmission?

**Comment by haukepetersen** [comment]
good question. I always understood the latter of them, as just putting the device into TX mode on it's own does not really make sense, does it?

**Comment by authmillenon** [comment]
Please provide the rest discussed as a follow-up.

**Pull request merged**
