### PR TITLE
boards/core: removed some hwtimer leftovers

### PR DESCRIPTION
**Pull request by haukepetersen**
Now that the hwtimer was removed, these defines are not needed/used anymore...

### CODE REVIEW

**Comment by OlegHahm** [comment]
ACK

**Comment by authmillenon** [comment]
Technically this is a core change. Does it need a second ACK?

**Comment by OlegHahm** [comment]
Wouldn't hurt. It's mostly about building and testing, I guess. Building works according to Travis and I included it in my RC test branch for border router testing where it also didn't fail.

**Comment by PeterKietzmann** [comment]
ACK from my side. Side question: May [this](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stellaris_common/include/hw_timer.h#L40) cause confusion?

**Comment by OlegHahm** [comment]
I think not any more. ;)

**Pull request merged**
