### PR TITLE
sys/ztimer: auto-select ztimer_no_periph_rtt only for samd21

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

As seen in #14031 ~~`sam3`~~(EDIT: only `samd21`) ~~does to~~ suffer from the same clock domain synchronization issues (or at least much less), see https://github.com/RIOT-OS/RIOT/pull/17786#issuecomment-1064480367 https://github.com/RIOT-OS/RIOT/pull/17786#issuecomment-1064471192 for esting results.

- [x] saml21 see https://github.com/RIOT-OS/RIOT/pull/17786#issuecomment-1064471192
- [x] samd5x see https://github.com/RIOT-OS/RIOT/pull/17786#issuecomment-1064480367
- [x] saml1x see https://github.com/RIOT-OS/RIOT/pull/17786#issuecomment-1064480367
- [ ] sam3

### Testing procedure

I I just ran `USEMODULE=ztimer_periph_rtt IOTLAB_NODE=samr30-1.saclay.iot-lab.info BOARD=samr30-xpro make -C tests/bench_ztimer/` for `samr30-xpro` and it looks OK:

```
main(): This is RIOT! (Version: 2022.04-devel-798-g8fa26-HEAD)
ztimer benchmark application.

                     set() one   121995 / 1000 = 121
                  remove() one     1544 / 1000 = 1
          set() + remove() one   243996 / 1000 = 243
  set() many increasing target   138007 / 1000 = 138
               re-set()  first   122001 / 1000 = 122
               re-set() middle   122100 / 1000 = 122
               re-set()   last   122192 / 1000 = 122
       remove() + set()  first   244009 / 1000 = 244
       remove() + set() middle   243983 / 1000 = 243
       remove() + set()   last   243982 / 1000 = 243
      remove() many decreasing   203144 / 1000 = 203
                  ztimer_now()     7506 / 1000 = 7
              sizeof(ztimer_t)    16000 / 1000 = 16
done.
```

@dylad or @jue89 maybe have a `saml21-xpro`?

### CODE REVIEW

**Comment by fjmolinas** [comment]
```
BOARD=samr30-xpro USEMODULE=ztimer_msec make -C tests/ztimer_msg/ info-modules | grep rtt
periph_init_rtt
periph_rtc_rtt
periph_rtt
ztimer_periph_rtt
```

**Comment by fjmolinas** [comment]
BTW would be good to see if other `sam%` can be filtered-out, @benpicco do you have a `samd5x` to test out? Maybe @dylad has some as well?

**Review by jue89 — CHANGES_REQUESTED** [review]
> @dylad or @jue89 maybe have a saml21-xpro?

No, I just have a `samr30-xpro` at hand.

You should mention why the `saml21` is filtered-out in the comment above.

**Comment by dylad** [comment]
I should be able to test SAML10, SAML11, SAML21 and SAME4 tonight. Worse case tomorrow evening.

**Comment by dylad** [comment]
For SAML21-XPRO:
` USEMODULE=ztimer_periph_rtt  BOARD=saml21-xpro make -C tests/bench_ztimer/ flash`

Output:
```
2022-03-10 21:22:28,685 # START
2022-03-10 21:22:28,692 # main(): This is RIOT! (Version: 2022.04-devel-799-g5cf714-pr_ztimer_rtt_sam3)
2022-03-10 21:22:28,694 # ztimer benchmark application.
2022-03-10 21:22:28,694 # 
2022-03-10 21:22:28,821 #                      set() one   121961 / 1000 = 121
2022-03-10 21:22:28,828 #                   remove() one     2100 / 1000 = 2
2022-03-10 21:22:29,078 #           set() + remove() one   243943 / 1000 = 243
2022-03-10 21:22:29,220 #   set() many increasing target   138031 / 1000 = 138
2022-03-10 21:22:29,347 #                re-set()  first   121963 / 1000 = 121
2022-03-10 21:22:29,474 #                re-set() middle   122062 / 1000 = 122
2022-03-10 21:22:29,601 #                re-set()   last   122153 / 1000 = 122
2022-03-10 21:22:29,850 #        remove() + set()  first   243939 / 1000 = 243
2022-03-10 21:22:30,099 #        remove() + set() middle   243945 / 1000 = 243
2022-03-10 21:22:30,347 #        remove() + set()   last   243945 / 1000 = 243
2022-03-10 21:22:30,555 #       remove() many decreasing   203071 / 1000 = 203
2022-03-10 21:22:30,568 #                   ztimer_now()     7673 / 1000 = 7
2022-03-10 21:22:30,572 #               sizeof(ztimer_t)    16000 / 1000 = 16
2022-03-10 21:22:30,573 # done.
```

**Comment by dylad** [comment]
With this patch:
```
---
 sys/ztimer/Makefile.dep | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/sys/ztimer/Makefile.dep b/sys/ztimer/Makefile.dep
index 757e3649c6..2f4924fb1e 100644
--- a/sys/ztimer/Makefile.dep
+++ b/sys/ztimer/Makefile.dep
@@ -85,7 +85,7 @@ endif
 # the counter is read, this propagates and leads to timing errors
 # on ztimer_msec that are higher than > +-1msec.
 # The same goes for the fe310 rtt.
-ifneq (,$(filter-out saml21,$(filter sam% fe310,$(CPU))))
+ifneq (,$(filter-out saml21 saml1x samd5x,$(filter sam% fe310,$(CPU))))
   USEMODULE += ztimer_no_periph_rtt
 endif
 
-- 
2.17.1

```

SAML11-XPRO:
`USEMODULE=ztimer_periph_rtt  BOARD=saml11-xpro make -C tests/bench_ztimer flash`

```
2022-03-10 21:30:30,994 # START
2022-03-10 21:30:31,001 # main(): This is RIOT! (Version: 2022.04-devel-799-g5cf714-pr_ztimer_rtt_sam3)
2022-03-10 21:30:31,003 # ztimer benchmark application.
2022-03-10 21:30:31,004 # 
2022-03-10 21:30:31,161 #                      set() one   151628 / 1000 = 151
2022-03-10 21:30:31,171 #                   remove() one     4270 / 1000 = 4
2022-03-10 21:30:31,481 #           set() + remove() one   303254 / 1000 = 303
2022-03-10 21:30:31,492 #   set() many increasing target     6583 / 100 = 65
2022-03-10 21:30:31,650 #                re-set()  first   151627 / 1000 = 151
2022-03-10 21:30:31,808 #                re-set() middle   151666 / 1000 = 151
2022-03-10 21:30:31,966 #                re-set()   last   151703 / 1000 = 151
2022-03-10 21:30:32,276 #        remove() + set()  first   303264 / 1000 = 303
2022-03-10 21:30:32,586 #        remove() + set() middle   303254 / 1000 = 303
2022-03-10 21:30:32,896 #        remove() + set()   last   303251 / 1000 = 303
2022-03-10 21:30:32,918 #       remove() many decreasing    16830 / 100 = 168
2022-03-10 21:30:32,938 #                   ztimer_now()    14823 / 1000 = 14
2022-03-10 21:30:32,943 #               sizeof(ztimer_t)     1600 / 100 = 16
2022-03-10 21:30:32,943 # done.
```

SAME54-XPRO:
`USEMODULE=ztimer_periph_rtt  BOARD=same54-xpro make -C tests/bench_ztimer flash`

```
2022-03-10 21:34:23,568 # START
2022-03-10 21:34:23,575 # main(): This is RIOT! (Version: 2022.04-devel-799-g5cf714-pr_ztimer_rtt_sam3)
2022-03-10 21:34:23,578 # ztimer benchmark application.
2022-03-10 21:34:23,578 # 
2022-03-10 21:34:23,674 #                      set() one    91551 / 1000 = 91
2022-03-10 21:34:23,679 #                   remove() one      531 / 1000 = 0
2022-03-10 21:34:23,866 #           set() + remove() one   183104 / 1000 = 183
2022-03-10 21:34:23,923 #   set() many increasing target    52184 / 1000 = 52
2022-03-10 21:34:24,019 #                re-set()  first    91555 / 1000 = 91
2022-03-10 21:34:24,115 #                re-set() middle    91593 / 1000 = 91
2022-03-10 21:34:24,211 #                re-set()   last    91623 / 1000 = 91
2022-03-10 21:34:24,399 #        remove() + set()  first   183085 / 1000 = 183
2022-03-10 21:34:24,587 #        remove() + set() middle   183092 / 1000 = 183
2022-03-10 21:34:24,775 #        remove() + set()   last   183093 / 1000 = 183
2022-03-10 21:34:24,899 #       remove() many decreasing   119677 / 1000 = 119
2022-03-10 21:34:24,904 #                   ztimer_now()     1077 / 1000 = 1
2022-03-10 21:34:24,909 #               sizeof(ztimer_t)    16000 / 1000 = 16
2022-03-10 21:34:24,910 # done.

```

**Comment by fjmolinas** [comment]
So outside of `samd21` which we know presents the issue it seem only `sam3` is additionally being blacklisted:

```
git grep "CPU = sam" | grep -vE "saml21|samd5x|saml1x|samd21"
boards/common/arduino-due/Makefile.features:CPU = sam3
```

I schemed through the datasheet of `ATSAM3X8E` and found no mention to the clock synchronization issue, so I also removed it.

**Review by dylad — APPROVED** [review]
ACK on my side. Re-test on the same platforms, got the same results.
@ju89 any more comments on this ?

**Review by jue89 — APPROVED** [review]
Tested with `samr30-xpro`. ACK.

**Comment by fjmolinas** [comment]
Thanks for testing everyone!

**Pull request merged**
