### PR TITLE
sys/net: fix typo in docs

### PR DESCRIPTION
**Pull request by blueted2**
### Contribution description
Fixed a typo in the IEEE 802.15.4 docs.
```eanbled -> enabled```

(am I being helpful yet ?)

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
Thank you for the fix!

**Comment by benpicco** [comment]
Ah please ammend your commit message so it includes the subsystem:

    net/iee802154: fix typo in docs

You can do so with `git commit --amend`

**Comment by blueted2** [comment]
I believe I have modified the commit message.

**Comment by maribu** [comment]
Let's give the `can_fast_ci_run.py` a chance to figure out this doesn't need any rebuilds :)

**Pull request merged**
