### PR TITLE
cpu/stm32: enable USB OTG FS on high end L4

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR enables the STM32 USB OTG FS driver (e.g periph_usbdev) on some high-end L4 boards already supported by RIOT: nucleo-l496zg (untested), nucleo-l4r5zi (untested), p-l496z-cell02, b-475e-iot01a and stm32l476g-disco (untested). The board level configuration is straight forward since it's the same as for F2/F4/F7.

But to make it fully work on L4  there were missing bits:
- enable 48MHz clock source when usbdev is used. Note that it works in the default clock configuration because MSI is already enabled, clocked at 48MHz and used as 48MHz clock source (for RNG).
- poweron USB

Thanks @dylad for #17281, you gave me good hints.

### Testing procedure

- Green CI
- USB is working:

<details><summary>p-l496g-cell02</summary>

```
$ BUILD_IN_DOCKER=1 make BOARD=p-l496g-cell02 -C examples/usbus_minimal flash term --no-print-directory 
Launching build container using image "riot/riotbuild:latest".
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e 'BUILD_DIR=/data/riotbuild/riotbase/build' -e 'RIOTPROJECT=/data/riotbuild/riotbase' -e 'RIOTCPU=/data/riotbuild/riotbase/cpu' -e 'RIOTBOARD=/data/riotbuild/riotbase/boards' -e 'RIOTMAKE=/data/riotbuild/riotbase/makefiles'      -e 'BOARD=p-l496g-cell02'  -w '/data/riotbuild/riotbase/examples/usbus_minimal/' 'riot/riotbuild:latest' make 'BOARD=p-l496g-cell02'    
Building application "usbus_minimal" for "p-l496g-cell02" with MCU "stm32".

"make" -C /data/riotbuild/riotbase/boards/p-l496g-cell02
"make" -C /data/riotbuild/riotbase/core
"make" -C /data/riotbuild/riotbase/cpu/stm32
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/stmclk
"make" -C /data/riotbuild/riotbase/cpu/stm32/vectors
"make" -C /data/riotbuild/riotbase/drivers
"make" -C /data/riotbuild/riotbase/drivers/periph_common
"make" -C /data/riotbuild/riotbase/sys
"make" -C /data/riotbuild/riotbase/sys/auto_init
"make" -C /data/riotbuild/riotbase/sys/auto_init/usb
"make" -C /data/riotbuild/riotbase/sys/event
"make" -C /data/riotbuild/riotbase/sys/fmt
"make" -C /data/riotbuild/riotbase/sys/frac
"make" -C /data/riotbuild/riotbase/sys/luid
"make" -C /data/riotbuild/riotbase/sys/malloc_thread_safe
"make" -C /data/riotbuild/riotbase/sys/newlib_syscalls_default
"make" -C /data/riotbuild/riotbase/sys/pm_layered
"make" -C /data/riotbuild/riotbase/sys/stdio_uart
"make" -C /data/riotbuild/riotbase/sys/usb/usbus
"make" -C /data/riotbuild/riotbase/sys/ztimer
   text	   data	    bss	    dec	    hex	filename
  17244	    112	   4040	  21396	   5394	/data/riotbuild/riotbase/examples/usbus_minimal/bin/p-l496g-cell02/usbus_minimal.elf
Private testing pid.codes USB VID/PID used!, do not use it outside of test environments!
MUST NOT be used on any device redistributed, sold or manufactured, VID/PID is not unique!
Private testing pid.codes USB VID/PID used!, do not use it outside of test environments!
MUST NOT be used on any device redistributed, sold or manufactured, VID/PID is not unique!
/work/riot/RIOT/dist/tools/openocd/openocd.sh flash /work/riot/RIOT/examples/usbus_minimal/bin/p-l496g-cell02/usbus_minimal.elf
### Flashing Target ###
Open On-Chip Debugger 0.11.0 (2021-11-22-14:28)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 500 kHz
Info : STLINK V2J28M18 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.236915
Warn : target stm32l4x.cpu examination failed
Error: jtag status contains invalid mode value - communication failure
Polling target stm32l4x.cpu failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 100ms
Info : Previous state query failed, trying to reconnect
Error: jtag status contains invalid mode value - communication failure
Polling target stm32l4x.cpu failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 300ms
Info : starting gdb server for stm32l4x.cpu on 0
Info : Listening on port 46763 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32l4x.cpu       hla_target little stm32l4x.cpu       unknown

Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
Error: mem2array: Read @ 0xe0042004, w=4, cnt=1, failed
Error executing event examine-end on target stm32l4x.cpu:
/usr/local/bin/../share/openocd/scripts/mem_helper.tcl:6: Error: 
in procedure 'ocd_process_reset' 
in procedure 'ocd_process_reset_inner' called at file "embedded:startup.tcl", line 288
in procedure 'mmw' called at file "/usr/local/bin/../share/openocd/scripts/target/stm32l4x.cfg", line 108
in procedure 'mrw' called at file "/usr/local/bin/../share/openocd/scripts/mem_helper.tcl", line 36
at file "/usr/local/bin/../share/openocd/scripts/mem_helper.tcl", line 6
Info : Previous state query failed, trying to reconnect
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08000870 msp: 0x20000200
Polling target stm32l4x.cpu failed, trying to reexamine
Info : stm32l4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : device idcode = 0x20006461 (STM32L49/L4Axx - Rev B : 0x2000)
Info : flash size = 1024kbytes
Info : flash mode : dual-bank
Info : Padding image section 1 at 0x080043cc with 4 bytes (bank write end alignment)
Warn : Adding extra erase range, 0x080043d0 .. 0x080047ff
auto erase enabled
wrote 17360 bytes from file /work/riot/RIOT/examples/usbus_minimal/bin/p-l496g-cell02/usbus_minimal.elf in 1.009852s (16.788 KiB/s)

verified 17356 bytes in 0.617653s (27.441 KiB/s)

Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
shutdown command invoked
Done flashing
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"  
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2021-12-01 09:32:15,881 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2021-12-01 09:32:34,236 # main(): This is RIOT! (Version: 2022.01-devel-819-g9f7187-pr/cpu/stm32_usb_l4)
2021-12-01 09:32:34,239 # RIOT USB stack example application
2021-12-01 09:32:34,241 # Started USB stack!
2021-12-01 09:32:36,635 # Exiting Pyterm
```

- on /var/log/syslog:

```
Dec  1 09:32:34 trek kernel: [499413.203504] usb 1-6.3.4: USB disconnect, device number 100
Dec  1 09:32:34 trek kernel: [499413.434047] usb 1-6.3.4: new full-speed USB device number 101 using xhci_hcd
Dec  1 09:32:34 trek kernel: [499413.535801] usb 1-6.3.4: config 1 has no interfaces?
Dec  1 09:32:34 trek kernel: [499413.536697] usb 1-6.3.4: New USB device found, idVendor=1209, idProduct=7d01, bcdDevice= 0.00
Dec  1 09:32:34 trek kernel: [499413.536709] usb 1-6.3.4: New USB device strings: Mfr=3, Product=2, SerialNumber=4
Dec  1 09:32:34 trek kernel: [499413.536716] usb 1-6.3.4: Product: USB device
Dec  1 09:32:34 trek kernel: [499413.536721] usb 1-6.3.4: Manufacturer: RIOT-os.org
Dec  1 09:32:34 trek kernel: [499413.536724] usb 1-6.3.4: SerialNumber: BD171424B43F7AB9
Dec  1 09:32:34 trek mtp-probe: checking bus 1, device 101: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.3/1-6.3.4"
Dec  1 09:32:34 trek mtp-probe: bus: 1, device: 101 was not an MTP device
Dec  1 09:32:34 trek mtp-probe: checking bus 1, device 101: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.3/1-6.3.4"
Dec  1 09:32:34 trek mtp-probe: bus: 1, device: 101 was not an MTP device
```

</details>

<details><summary>b-l475e-iot01a</summary>

```
$ BUILD_IN_DOCKER=1 make BOARD=b-l475e-iot01a -C examples/usbus_minimal flash term --no-print-directory 
Launching build container using image "riot/riotbuild:latest".
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e 'BUILD_DIR=/data/riotbuild/riotbase/build' -e 'RIOTPROJECT=/data/riotbuild/riotbase' -e 'RIOTCPU=/data/riotbuild/riotbase/cpu' -e 'RIOTBOARD=/data/riotbuild/riotbase/boards' -e 'RIOTMAKE=/data/riotbuild/riotbase/makefiles'      -e 'BOARD=b-l475e-iot01a'  -w '/data/riotbuild/riotbase/examples/usbus_minimal/' 'riot/riotbuild:latest' make 'BOARD=b-l475e-iot01a'    
Building application "usbus_minimal" for "b-l475e-iot01a" with MCU "stm32".

[INFO] updating stm32cmsis /data/riotbuild/riotbase/build/stm32/cmsis/l4/.pkg-state.git-downloaded
echo 26ed4846f831f730d852507e178061053e522daf   > /data/riotbuild/riotbase/build/stm32/cmsis/l4/.pkg-state.git-downloaded
[INFO] patch stm32cmsis
"make" -C /data/riotbuild/riotbase/boards/b-l475e-iot01a
"make" -C /data/riotbuild/riotbase/core
"make" -C /data/riotbuild/riotbase/cpu/stm32
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/stmclk
"make" -C /data/riotbuild/riotbase/cpu/stm32/vectors
"make" -C /data/riotbuild/riotbase/drivers
"make" -C /data/riotbuild/riotbase/drivers/periph_common
"make" -C /data/riotbuild/riotbase/sys
"make" -C /data/riotbuild/riotbase/sys/auto_init
"make" -C /data/riotbuild/riotbase/sys/auto_init/usb
"make" -C /data/riotbuild/riotbase/sys/event
"make" -C /data/riotbuild/riotbase/sys/fmt
"make" -C /data/riotbuild/riotbase/sys/frac
"make" -C /data/riotbuild/riotbase/sys/luid
"make" -C /data/riotbuild/riotbase/sys/malloc_thread_safe
"make" -C /data/riotbuild/riotbase/sys/newlib_syscalls_default
"make" -C /data/riotbuild/riotbase/sys/pm_layered
"make" -C /data/riotbuild/riotbase/sys/stdio_uart
"make" -C /data/riotbuild/riotbase/sys/usb/usbus
"make" -C /data/riotbuild/riotbase/sys/ztimer
   text	   data	    bss	    dec	    hex	filename
  17152	    112	   4028	  21292	   532c	/data/riotbuild/riotbase/examples/usbus_minimal/bin/b-l475e-iot01a/usbus_minimal.elf
Private testing pid.codes USB VID/PID used!, do not use it outside of test environments!
MUST NOT be used on any device redistributed, sold or manufactured, VID/PID is not unique!
Private testing pid.codes USB VID/PID used!, do not use it outside of test environments!
MUST NOT be used on any device redistributed, sold or manufactured, VID/PID is not unique!
/work/riot/RIOT/dist/tools/openocd/openocd.sh flash /work/riot/RIOT/examples/usbus_minimal/bin/b-l475e-iot01a/usbus_minimal.elf
### Flashing Target ###
Open On-Chip Debugger 0.11.0 (2021-11-22-14:28)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
srst_only separate srst_nogate srst_open_drain connect_assert_srst

Info : clock speed 500 kHz
Info : STLINK V2J28M18 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.247989
Info : stm32l4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32l4x.cpu on 0
Info : Listening on port 46599 for gdb connections
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32l4x.cpu       hla_target little stm32l4x.cpu       reset

Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08000830 msp: 0x20000200
Info : device idcode = 0x10076415 (STM32L47/L48xx - Rev 4 : 0x1007)
Info : flash size = 1024kbytes
Info : flash mode : dual-bank
Warn : Adding extra erase range, 0x08004370 .. 0x080047ff
auto erase enabled
wrote 17264 bytes from file /work/riot/RIOT/examples/usbus_minimal/bin/b-l475e-iot01a/usbus_minimal.elf in 0.996426s (16.920 KiB/s)

verified 17264 bytes in 0.618130s (27.275 KiB/s)

Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
shutdown command invoked
Done flashing
/work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"  
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2021-12-01 09:29:59,338 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2021-12-01 09:30:05,575 # main(): This is RIOT! (Version: 2022.01-devel-819-g9f7187-pr/cpu/stm32_usb_l4)
2021-12-01 09:30:05,578 # RIOT USB stack example application
2021-12-01 09:30:05,579 # Started USB stack!
2021-12-01 09:30:06,943 # Exiting Pyterm
```

- on /var/log/syslog:

```
Dec  1 09:31:04 trek kernel: [499323.859349] usb 1-6.3.4: USB disconnect, device number 94
Dec  1 09:31:05 trek kernel: [499324.156733] usb 1-6.3.4: new full-speed USB device number 95 using xhci_hcd
Dec  1 09:31:05 trek kernel: [499324.258268] usb 1-6.3.4: config 1 has no interfaces?
Dec  1 09:31:05 trek kernel: [499324.259300] usb 1-6.3.4: New USB device found, idVendor=1209, idProduct=7d01, bcdDevice= 0.00
Dec  1 09:31:05 trek kernel: [499324.259315] usb 1-6.3.4: New USB device strings: Mfr=3, Product=2, SerialNumber=4
Dec  1 09:31:05 trek kernel: [499324.259321] usb 1-6.3.4: Product: USB device
Dec  1 09:31:05 trek kernel: [499324.259326] usb 1-6.3.4: Manufacturer: RIOT-os.org
Dec  1 09:31:05 trek kernel: [499324.259330] usb 1-6.3.4: SerialNumber: 5B842A1CDEC8B2E8
Dec  1 09:31:05 trek mtp-probe: checking bus 1, device 95: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.3/1-6.3.4"
Dec  1 09:31:05 trek mtp-probe: bus: 1, device: 95 was not an MTP device
Dec  1 09:31:05 trek mtp-probe: checking bus 1, device 95: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.3/1-6.3.4"
Dec  1 09:31:05 trek mtp-probe: bus: 1, device: 95 was not an MTP device
```

</details>

I can test the missing board on friday but they should work.

### Issues/PRs references

This is a take over of #13340, so closes #13340

### CODE REVIEW

**Comment by dylad** [comment]
@aabadie Don't you miss Kconfig ?

**Comment by aabadie** [comment]
> Don't you miss Kconfig ?

Ah yes, initially I did the same changes locally (with Kconfig) but wanted to be gentle and reuse @bergzand's commits...

**Comment by dylad** [comment]
> but wanted to be gentle and reuse @bergzand's commits...

That's a good point ! Then add it as extra commits.

**Review by benpicco — APPROVED** [review]

**Comment by dylad** [comment]
Here we go !

**Comment by aabadie** [comment]
Thanks!

**Pull request merged**
