### PR TITLE
makefile: fix implementation info-buildsizes-diff

### PR DESCRIPTION
**Pull request by JonaRaemdonck**
### Contribution description
For some time the make command info-buildsizes-diff has been broken.
This commit will:
* re-enable functionality without changing the usage described on wiki
* only report on boards that are actually available in bindirs
* be faster in some cases

### Testing procedure

The fix was manually tested on multiple of the example projects.
By building for multiple boards in two separate bin directories and
then running:

make info-buildsizes-diff OLDBIN=bin1 NEWBIN=bin2

note: not all builds for the same boards need to be present for this to work,
but it does give a nicer result as there will be no red errors reported.

### Issues/PRs references

initial mention found for of broken functionality:
https://github.com/RIOT-OS/RIOT/pull/9831

### CODE REVIEW

**Comment by cladmi** [comment]
I would prefer to really fix the issue without a `find`.
As the problem is the make variables handling and working it around will not fix the root cause :)

The fact that you need to set variables after `make` to force their value shows the main problem.

**Comment by cladmi** [comment]
I am trying something.

**Comment by cladmi** [comment]
I also think the main issue is only a wiki documentation issue. If no variables are set from the command line but only from the environment it should work properly.
I will verify what I say.

The root cause of all problems is that the build system tries to override variables set from the command line.
And when setting one variable from the command line (any variable) it triggers the `MAKEOVERRIDES` of all directories variables even if not needed.

**Comment by cladmi** [comment]
I thought I gave feedback to this pull request, but did not…

I updated the wiki page to pass `OLDBIN` and `NEWBIN` from the environment https://github.com/RIOT-OS/RIOT/wiki/Comparing-build-sizes

So the handling for the fix in this one is not necessary anymore.

Feel free to re-open with only the improvements if you want.

**Comment by JonaRaemdonck** [comment]
Thanks for the feedback.

Actually this pull-request was about solving a problem that we created ourselves at our project. We decided to prepend the name of our outputted elf-files with the git hash of our current commit for identification purposes afterwards. This is simply incompatible with the current implementation of info-buildsizes-diff.

Instead I have made a custom make target that will stay within our own repo for now and solves our issue.

By revisiting this issue I did find some cumbersome functionality. If you build an image for a certain board on master and your branch, by running info-buildsizes-diff, you have no way of specifying for what boards you want that info, you'll get the info for all boards AND in both bindirs empty dirs will be generated for all compatible boards.

Do you think this is worth spending time on?

**Comment by cladmi** [comment]
> By revisiting this issue I did find some cumbersome functionality. If you build an image for a certain board on master and your branch, by running info-buildsizes-diff, you have no way of specifying for what boards you want that info, you'll get the info for all boards AND in both bindirs empty dirs will be generated for all compatible boards.

You could define the `BOARDS` environment variable it limits to the one you want:

```
BOARDS="iotlab-m3 samr21-xpro native" OLDBIN=bin_old NEWBIN=bin_new make info-buildsizes-diff
text	data	bss	dec	BOARD/BINDIRBASE

-56	0	0	-56	iotlab-m3
8484	140	2620	11244	bin_old
8428	140	2620	11188	bin_new

-52	0	0	-52	samr21-xpro
8592	140	2612	11344	bin_old
8540	140	2612	11292	bin_new

-52	0	0	-52	native
22970	568	47652	71190	bin_old
22918	568	47652	71138	bin_new
```


In case you may find it useful, there is a way to add behavior in the default RIOT repository without modifying it by including your own files to be parsed http://doc.riot-os.org/advanced-build-system-tricks.html
I have example usage to define a new target https://github.com/cladmi/iotlab-os-ci/blob/master/tools/pytest/pytest.mk.post or do change some variables definition before they are set https://git.imp.fu-berlin.de/riot-appstore/riot-buildsystem-ci-server/blob/master/tools/makefiles.pre

**Pull request closed without merging**
