### PR TITLE
net/gnrc_lorawan: implement channel mask support

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR implements channel mask for GNRC LoRaWAN. The channel mask is used to enable/disable LoRaWAN channels (e.g when the network server sends an ADR-Req command or if requested by the user).

Since there's no support for adding/removing channels yet, I'm not exposing this to the user of the interface.
This is required in order to implement ADR (already handled by @akshaim)

### Testing procedure
There's a test commit. Check that GNRC LoRaWAN doesn't assert and that it only transmit in a single channel (868.1 MHz).

### Issues/PRs references
None so far

### CODE REVIEW

**Review by akshaim — COMMENTED** [review]
Tested using EU868 channel plan. The Channel mask is working and uplinks are only sent on the 868.1 MHz frequency.

**Review by leandrolanzieri — COMMENTED** [review]
Just a minor comment. Feel free to squash and remove the test commit.

**Comment by leandrolanzieri** [comment]
Also please set the CI label when ready

**Comment by jia200x** [comment]
fixed, removed test commit and squashed directly

**Review by leandrolanzieri — APPROVED** [review]
ACK

**Pull request merged**
