### PR TITLE
unittests: initial import of IPV6 tests

### PR DESCRIPTION
**Pull request by A-Paul**
Implemented some tests and activated 2 for now.

Some improvement + extension needed. ( e.g I ran into the same difficulties with (re-)initializing threads as in https://github.com/RIOT-OS/RIOT/pull/3307)

After rebase the "__ng__" in branch name isn't correct anymore as it's now based on _gnrc_.

Still some advice needed for creating unit preconditions and test data (See comments of test functions in _tests-ng_ipv6.c_.)

### CODE REVIEW

**Comment by authmillenon** [comment]
Testing `ng_ipv6_init()` this way doesn't make much sense IMHO (since the IPv6 thread is not stopped during runtime, see https://github.com/RIOT-OS/RIOT/pull/3307#discussion_r33860255). Also consider writing the tests the way I did it in #3296 as an extra app.

**Comment by OlegHahm** [comment]
That the DUT cannot be rebooted during unittests is really suboptimal. I try to come up with a solution for that.

**Comment by A-Paul** [comment]
> That the DUT cannot be rebooted during unittests is really suboptimal...

@OlegHahm, have you tried it? I did. With `reboot(0);` in `tear_down()` it is restarting fine after the first test. And then the first test is invoked... :D
A sophisticated `while(1)`.

I think  @authmillenon marked a pragmatic step towards constructing a test suite by running seperate builds here (https://github.com/authmillenon/RIOT/commit/082f9223390e91a432b6398de5e6cf69e7afc98e).

**Comment by A-Paul** [comment]
Rebased.

**Comment by A-Paul** [comment]
PR #3698 addresses issues with module dependencies.

**Comment by cgundogan** [comment]
@A-Paul could you rebase, please?

**Comment by A-Paul** [comment]
Rebased

**Comment by OlegHahm** [comment]
Anyone volunteering as a shepherd? I'm swamped with other stuff and won't have time to review for another long period of time.

**Comment by kYc0o** [comment]
WIP -> postponed. If this can be rebased and retaken for review it would be great!

**Comment by miri64** [comment]
I still think that for these kind of initialization tests we need a new kind of test framework that is able to reset the node and restore the program counter where it is needed. Maybe whatever falls out of #5773 and an according modification of `embUnit` would do the trick.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by miri64** [comment]
Not much progress happened on the restartable unittests (though considering #6286 I would rather do that in a separate test application).

**Comment by OlegHahm** [comment]
Strider is still on it! 😲

**Comment by miri64** [comment]
I still think it's better to test in a (or multiple) separate test application(s). Reopen if you disagree.

**Comment by smlng** [comment]
@miri64 I favor multiple, small test apps, too.

Nevertheless, we might have to (re)think/organize/structure the tests

**Pull request closed without merging**
