### PR TITLE
make: made consistent use of spaces in Makefile.dep

### PR DESCRIPTION
**Pull request by haukepetersen**
seems like some spaces slipped into the `Makefile.dep` which contains only tabs for indention otherwise...

### CODE REVIEW

**Comment by authmillenon** [comment]
This is on purpose (at least for my part). Tabs and spaces are interpreted differently by `make`: tabs are interpreted as “the following line contains a command for a target” (which these lines don't carry) [[Source](http://www.gnu.org/software/make/manual/make.html#index-tabs-in-rules)], while spaces don't have any syntactic connotations. Though [the manual states](http://www.gnu.org/software/make/manual/make.html#Conditional-Syntax) that it is in these cases arbitrary, using tabs for this kind of indentations already lead to problems in the past which is why I try to not use them for simple eye-candy indentatitions between `ifneq()` macros e.g. anymore.

**Comment by authmillenon** [comment]
Never had the time to fix this for all lines though :-/

**Comment by haukepetersen** [comment]
ok, then let me change the (all) tabs to spaces in this file...

**Comment by haukepetersen** [comment]
now there is a consistent use of 2 space indention in `Makefile.dep`. Also changed the PR title accordingly.

**Comment by authmillenon** [comment]
ACK when travis is happy.

**Comment by gebart** [comment]
The commit message is missing a letter. s/ake/make/

**Comment by haukepetersen** [comment]
ups, fixed it.

**Comment by haukepetersen** [comment]
and go.

**Pull request merged**
