### PR TITLE
release-notes.txt: add 2023.07 release notes [backport 2023.07]

### PR DESCRIPTION
**Pull request by benpicco**
# Backport of #19857

### Contribution description
This are the release notes for the 2023.07 Release. Please give it a look and make sure that your work in the last 3 months is present here.

### Testing procedure
- Read the document

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Review by aabadie — APPROVED** [review]

**Comment by maribu** [comment]
bors retry

**Comment by aabadie** [comment]
bors merge

**Review by MrKevinWeiss — APPROVED** [review]

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
come on bors, what's wrong?

**Comment by aabadie** [comment]
bors cancel
bors merge

**Comment by miri64** [comment]
bors merge

**Review by miri64 — APPROVED** [review]

**Comment by miri64** [comment]
bors merge

**Comment by kaspar030** [comment]
bors cancel

**Comment by kaspar030** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
