### PR TITLE
CI: temporarily disable llvm builds

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

llvm update broke many builds. Disable for CI until fixed.

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/15595

### CODE REVIEW

**Review by maribu — DISMISSED** [review]
ACK

**Comment by maribu** [comment]
Let's wait for https://github.com/RIOT-OS/RIOT/pull/15597. Maybe that would also fix the issue, without disabling IRQs.

**Comment by kaspar030** [comment]
> Let's wait for #15597. Maybe that would also fix the issue, without disabling IRQs.

there are more, so better go with this for now. (see https://github.com/RIOT-OS/RIOT/pull/15595).

**Comment by kaspar030** [comment]
> there are more, so better go with this for now. (see #15595).

I suggest if this is merged, I rebase #15595 and revert disabling llvm builds there. then once it passes, we're back to normal.

**Review by maribu — APPROVED** [review]
ACK

**Pull request merged**
