### PR TITLE
gcoap_dtls: destroy session in _tl_send only on connection errors

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
I'd argue it is downright harmful to destroy the DTLS session for a local problem, if e.g. you only ran out of memory.

It might make sense to have this also in other places. With this PR, I still get a worse performance with COAPS than I would get with DTLS (but it is an improvement).

### Testing procedure
`examples/gcoap_dtls` should still be able to exchange messages. When pounding the server with requests (e.g. by hitting Enter fast when accessing the node with `pyterm`) there should be much less likely a connection (read session) loss now. 

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
@janosbrodbeck pretty reliably about 3 seconds after the session was established, the client sends out an Encrypted Alert. Most likely a close? Somehow decrypting the traffic with Wireshark does not work with the IoT-LAB dumps, even if the right PSK is provided... I suspect it to be a close, because after that it tries to reestablish a session which (I think) causes 

https://github.com/RIOT-OS/RIOT/blob/a8cf45f09edb0b261bae313bf6fd599cbe631023/sys/net/application_layer/gcoap/gcoap.c#L271-L275

to be entered. Any idea why that spurious close comes after 3 seconds, and why the slot isn't freed in that case? Or is my analysis off (only can look at what happened after the fact at the moment)

**Comment by miri64** [comment]
Arghs sorry, I set my debug prints wrong. Apparently the `session_destroy` is called in the `_dtls_free_up_session()` callback. But that only be called 15 seconds after the session was last used, right?

**Comment by janosbrodbeck** [comment]
> Arghs sorry, I set my debug prints wrong. Apparently the `session_destroy` is called in the `_dtls_free_up_session()` callback. But that only be called 15 seconds after the session was last used, right?
Yes, that should not be called before the 15 seconds threshold. Could you maybe increase the number of slots to 2, just to see if it does not happen then?

**Comment by miri64** [comment]
Ok, I just had too little sessions: 1 is preconfigured, but the implementation assumes there are more (e.g. one for server and one for client operations). I just increased that number to 2 and now everything works fine in my setup. See #16967 to simplify that configuration somewhat.

**Pull request merged**
