### PR TITLE
posix_sockets: fix assertion on close

### PR DESCRIPTION
**Pull request by miri64**
As reported on the [devel Mailinglist](https://lists.riot-os.org/pipermail/devel/2017-March/005047.html).

### CODE REVIEW

**Comment by smlng** [comment]
looks good. But I wonder, because it looks like the assert was completely wrong before and should have fired for any socket/fd (not only 0)?

**Comment by miri64** [comment]
I tested it, for `socket == 0` it passes, but for anything else it fails (the e-mail indicated the negative of that I know).

**Comment by smlng** [comment]
but why haven't we encountered this before. Has nobody ever tried to close a POSIX socket in RIOT (with asserts enable, that is)?

**Comment by smlng** [comment]
I'll ACK after Murdock is good, too.

**Comment by miri64** [comment]
> but why haven't we encountered this before. Has nobody ever tried to close a POSIX socket in RIOT (with asserts enable, that is)?

I think nobody ever tried to use more than 1 socket and close them ;-).

**Pull request merged**
