### PR TITLE
netdev: add event handler thread as member of `netdev_t`

### PR DESCRIPTION
**Pull request by authmillenon**
To send `NETDEV_MSG_EVENT_TYPE` a target PID (event handler) has to be known. This API extension allows to set one.

Functionality for existing drivers will follow in separate PRs.

### CODE REVIEW

**Comment by fnack** [comment]
@OlegHahm: I don't want to add a HACK n ACK candidate label unauthorized (especially as I am not taking part in the event) but I'd vote to take this PR into consideration. A lot of other PRs (#1968, #2164, #2166, #2237, ...) are depending on it, so it would be great to see this merged anytime soon!

**Comment by OlegHahm** [comment]
Seems valid to me. I wasn't tracking this PR after https://github.com/RIOT-OS/RIOT/pull/2163#issuecomment-67167175.

**Comment by fnack** [comment]
Ping @authmillenon, @haukepetersen . What's the status of this PR? A lot of other PR's seem to rely on this one to be merged.

**Comment by authmillenon** [comment]
@fnack this is still on the table, but `netdev` itself will see some major changes (see #2297), too. Also we kind of set the whole network stack implementation more or less on hold until the Network Stack Task Force Workshop next week, in hopes that we get a stable model from this.

**Comment by fnack** [comment]
Okay, I don't like it but I guess I have to accept it. From my point of view, the restructuring of netdev will probably take a lot of time and meanwhile this PR could simplify using the current master branch.

**Comment by authmillenon** [comment]
That's up to the reviewers of this and the follow-up PRs ;-)

**Comment by haukepetersen** [comment]
@fnack, I would not build on this PR yet, in my opinion is still subject to change (see #2297 for a first draft)...

**Comment by authmillenon** [comment]
Closed in favor for #2398

**Pull request closed without merging**
