### PR TITLE
cpu/stm32f4: implement stmclk interface for stm32f4

### PR DESCRIPTION
**Pull request by vincent-d**
This implement stmclk for stm32f4 (#7123). Mainly copied and adapted from stm32f7.

I had to update a lot of vendor headers, as well as main clock speed for some boards.

Tested on nucleo-f401 and nucleo144-f413 (`example/default` compile and run). I'm not sure of every board config regarding LSE, though.

### CODE REVIEW

**Comment by aabadie** [comment]
I can test on the other boards I have here:
- [  ] nucleo-f410
- [  ] nucleo-f411
- [  ] nucleo-f446
- [  ] nucleo144-f446
- [  ] nucleo144-f429

**Comment by aabadie** [comment]
I'll be with the boards tomorrow so I can test !

**Comment by aabadie** [comment]
I didn't test nucleo144-f446 but the other f4 I have worked.

I have a question: why did you have to update the CMSIS files ?

**Comment by vincent-d** [comment]
> I have a question: why did you have to update the CMSIS files ?

Some defines like `RCC_CFGR_SWS_Msk` were added in between by ST. They were present in the last CMSIS file we added, but not in the oldests.

**Comment by aabadie** [comment]
and go!

**Comment by aabadie** [comment]
Thanks @vincent-d !

**Pull request merged**
