### PR TITLE
drivers/lsm303dlhc: Fix typo

### PR DESCRIPTION
**Pull request by aabadie**

### CODE REVIEW

**Comment by gebart** [comment]
ACK

**Comment by gebart** [comment]
(doesn't need to wait for Murdock here)

**Comment by gebart** [comment]
btw, you pushed your branch to the wrong repo. Set your git remote origin URL to git:// or https:// to avoid pushing to RIOT-OS/RIOT by mistake

**Comment by aabadie** [comment]
@gebart, I just edited the code directly via the github website (it was faster this way).

**Pull request merged**
