### PR TITLE
jlink: fixed typo burn.segg -> burn.seg

### PR DESCRIPTION
**Pull request by sdalu**
[dist]: fixed typo burn.segg -> burn.seg

### CODE REVIEW

**Comment by gebart** [comment]
Please prefix the commit message with a module name.
ACK except commit message

**Comment by cgundogan** [comment]
>Please prefix the commit message with a module name.

Exactly what I was going to write.

ACK after @gebart's comment was addressed

**Comment by cgundogan** [comment]
@sdalu you need to change the commit message also, not only the name of the pull request. You can do so by typing `git commit --amend` on your branch.

**Comment by cgundogan** [comment]
you can use e.g.: `jlink: fixed typo burn.segg -> burn.seg`

**Pull request closed without merging**
