### PR TITLE
boards/samr21-xpro: added third channel for PWM1

### PR DESCRIPTION
**Pull request by haukepetersen**
3rd channel neeed to tinker with rgb-led stipes...

and sorry for the formatting fixes that slipped in :-)

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
ACK

**Comment by PeterKietzmann** [comment]
Travis hast problems with your whitespaces
```
excess elements in array initializer [-Werror]

         { GPIO_PIN(PA, 19), GPIO_MUX_F, 3 }
```

**Comment by haukepetersen** [comment]
ups sorry, overlooked the fixed configuration for 2 channels. Should be fixed now.

**Comment by haukepetersen** [comment]
Fixed one more issue and did a test run driving an LED stripe -> all good now. 

@cgundogan would you look at this again, could simplify stuff with our EW16 demo when this is merged before hand...

**Comment by cgundogan** [comment]
I was able to see a nice square wave with my logic analyzer on pins PA16, PA18, PA19. ACK once you fixed the things that travis complains about

**Comment by haukepetersen** [comment]
fixed this thing and squashed.

**Comment by PeterKietzmann** [comment]
and go

**Pull request merged**
