### PR TITLE
libcoap: switch to the RIOT-OS mirror

### PR DESCRIPTION
**Pull request by OlegHahm**
At least until sf.net is up again.

@OlafBergmann, do you have a more recent version mirrored somewhere?

### CODE REVIEW

**Comment by gebart** [comment]
@OlegHahm I have a more recent clone at https://github.com/gebart/libcoap I have not been following the development though so I don't know how many commits I am missing.

**Comment by OlegHahm** [comment]
@gebart, that's great and I will update our mirror to yours, but it doesn't really matter for now, since an older commit is used in the package anyway.

**Comment by gebart** [comment]
ACK when Travis is fine

**Comment by gebart** [comment]
&go

**Pull request merged**
