### PR TITLE
gnrc: mac: fix types according to print formatting

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
As reported by `llvm`. (see #9398)

### Issues/PRs references
Fixes issue reported due to #9398.

### CODE REVIEW

**Comment by cladmi** [comment]
Which test should I build for seeing it ? the changes look good but still want to test on my computer.

**Comment by miri64** [comment]
[tests/gnrc_gomach](https://ci.riot-os.org/RIOT-OS/RIOT/9398/fa3cbd74aa2f9137292c7b358edf2ba5cb7a8d33/output/compile/tests/gnrc_gomach/samr21-xpro:llvm.txt) and [tests/lwmac](https://ci.riot-os.org/RIOT-OS/RIOT/9398/fa3cbd74aa2f9137292c7b358edf2ba5cb7a8d33/output/compile/tests/gnrc_lwmac/samr21-xpro:llvm.txt) respectively.

**Comment by miri64** [comment]
Fixed whitespace error reported by murdock and squashed.

**Comment by cladmi** [comment]
I still have an issue with `tests/gnrc_lwmac`

```
RIOT/sys/net/gnrc/link_layer/lwmac/tx_state_machine.c:464:47: error: format specifies type
      'unsigned long' but the argument has type 'uint32_t' (aka 'unsigned int') [-Werror,-Wformat]
    DEBUG("[LWMAC-tx]: spent %lu WR in TX\n", netif->mac.tx.wr_sent);
                             ~~~              ^~~~~~~~~~~~~~~~~~~~~
                             %u
/home/harter/work/git/RIOT/core/include/debug.h:97:50: note: expanded from macro 'DEBUG'
#define DEBUG(...) if (ENABLE_DEBUG) DEBUG_PRINT(__VA_ARGS__)
                                                 ^~~~~~~~~~~
/home/harter/work/git/RIOT/core/include/debug.h:63:33: note: expanded from macro 'DEBUG_PRINT'
#define DEBUG_PRINT(...) printf(__VA_ARGS__)
                                ^~~~~~~~~~~
```

**Comment by miri64** [comment]
Fixed

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
Backport in #9611

**Pull request merged**
