### PR TITLE
Adding Extra Uart and Timer peripheral to LM4F120 cpu.

### PR DESCRIPTION
**Pull request by rakendrathapa**
In this Pull request, I have added support for extra UART(UART_1) and TIMER (TIMER_1) peripheral for Stellaris ek-lm4f120xl board.
Also, there is certain restructuring of code for better understanding and clarity.

Regards,
Rakendra

### CODE REVIEW

**Comment by haukepetersen** [comment]
Looks good on first sight. Though I will test this later (probably in 1 or 2 weeks - just after the release is out), as we are currently in feature freeze... Hope that is alright?!

**Comment by rakendrathapa** [comment]
Okay Sure no issues. 
But can the CL flag be enabled so that I am just sure Travis and strider are success ?
Can be merged later.

**Comment by haukepetersen** [comment]
no problem, done.

**Comment by rakendrathapa** [comment]
@haukepetersen  Thanks :)

**Comment by rakendrathapa** [comment]
Some issues with this Pull. I am closing this pull request and will be making some changes and reopen a new one. Thanks guys !

Regards,
Rakendra

**Comment by dkm** [comment]
FYI i've been rewritting timer handling for this board while trying to debug it :)

**Comment by rakendrathapa** [comment]
That's awesome Marc !!

You can take a look at the following Pull request:

https://github.com/RIOT-OS/RIOT/pull/4076

I just closed this Pull request (#3787) and created the new one (#4076)
instead. Do let me know, in case of any feedback.

Thanks and Regards,
Rakendra

**Pull request closed without merging**
