### PR TITLE
[RFC] netif: add stack independent data and connection handlers

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds some stack independent functions passing data between the network stack and the interfaces. 

It adds the following functions:
- `netif_send`: Send MSDU (Mac Service Data Unit, full L3 frame) to an interface.
- `netif_recv`: To be called when radio triggers RX_DONE. This function fetches the packet from the radio and does L2 processing.
- `netif_rx_done`: To be called when the MAC finishes the rx procedure. This can be used to dispatch packets to the upper layers and release resources
- `netif_tx_done`: To be called when the MAC finishes the tx procedure. This can be used to release resources and calculate statistics.
- `netif_rx_pkt_alloc`: Requests the network stack to allocate a packet.
- `netif_link_up`: To be called when the netif link is up.
- `netif_link_down`: To be called when the netif link is down.

## Receiving a packet
- When network device triggers RX_COMPLETE event, the event_handler allocates a packet with `netif_rx_pkt_alloc` and calls `netif_rx_done` right after.
- `netif_rx_done` calls _network-device-specific-link-layer_ receive handlers (via an L2 interface, *TBD*)
- When the link layer finishes processing, it calls `netif_rx_done` with the MSDU (full L3 payload) and rx data (LQI, RSSI, etc). This function dispatcher the packet to the network stack, calculates statistics and releases resources if needed.

## Sending a packet
- Network stack (usually L3 layer) calls `netif_send` with the packet encapsulated in an `iolist_t`.
- `netif_send` calls the link layer `send` function (via the L2 interface to be introduced)
- When the MAC layer finished, it calls `netif_tx_done` with the status and MSDU pointer of the packet. This functions calculates transmission statistics, informs the upper layer about a transmission and releases buffers (if the MAC layer has a queuing mechanism, it's possible to free resources associated to the sent MSDU with the pointer).

## Link status change
If the netif changes its state, it can tell the upper layers with the `netif_link_up` and `netif_link_down` functions.

# Implications
With this it's possible to:
- Avoid [these kind of #ifdef](https://github.com/RIOT-OS/RIOT/blob/master/sys/auto_init/netif/auto_init_at86rf2xx.c#L56), since the network device will always call the `netif_recv` function regardless of the stack. The stack is selected via `netif_xxx` functions implementation.
- Separate interface logic from the network stack, so it's possible e.g to send non IP data (LoRaWAN, etc) via an interface that might not be dependent of GNRC (@aabadie)
- Provide MAC layers independent of the network stack.

# Limitations
The implementation still assumes there's only one network stack. It would be possible to use multiple stacks in the future  with a netif_t `driver` style descriptor.

### Testing procedure
Check that the API makes sense.
Also, check the documentation with `make doc`.

### Issues/PRs references
Depends on #11879

### CODE REVIEW

**Comment by jia200x** [comment]
I thinking of replacing the `netif_dispatch` function with `netif_rx_done` function. Also add `netif_tx_done` and `netif_link_up`/`netif_link_down`. I will write back after some experimentation with IEEE802.15.4

**Comment by miri64** [comment]
Mhhhh... I thought about this a bit: Wouldn't this require always some `switch case` within those function just to distinguish the different interfaces? Why did you move away from the `ops` function pointer struct we have in `gnrc_netif`?

**Comment by jia200x** [comment]
> Wouldn't this require always some switch case within those function just to distinguish the different interfaces?

No, because that should be coded in the interface itself (e.g each instance of `gnrc_netif_t`). For L2 access, there will be another interface for multiplexing that (same as netif->ops)

> Why did you move away from the ops function pointer struct we have in gnrc_netif

Because those are GNRC specific. Migrating `gnrc_netif->ops` to `l2->ops` makes them stack independent

**Comment by miri64** [comment]
> No, because that should be coded in the interface itself (e.g each instance of gnrc_netif_t). For L2 access, there will be another interface for multiplexing that (same as netif->ops)

So we only will support one interface with this API?

> Because those are GNRC specific. Migrating gnrc_netif->ops to l2->ops makes them stack independent

I said *like* the `ops` not taking them verbatim...

So let me try to understand again... these are just wrapper functions for `l2->ops` functions? Why not use those directly then instead of adding more overhead?

**Comment by miri64** [comment]
Can you maybe provide some picture of the current state of your API stack? I still struggling to get my head around it...

**Comment by jia200x** [comment]
> Can you maybe provide some picture of the current state of your API stack? I still struggling to get my head around it...

Yes, for sure. I will also provide some sample code (I'm currently writing the glue code for GNRC)

**Comment by jia200x** [comment]
> So we only will support one interface with this API?

Yes, because the interface only passes data between network stack and MAC layers. 
The diagram looks like this:

Basically it's `Link Layer         <---l2_ops---->     netif        <----stack_api----->      Network Stack`

`l2_ops` (to be introduced) has almost the same members from `netif->ops`.

So, it means:
- `netif` is dependent on the network stack. This will take care of pkt allocation (stack dependent) and passing data between L2 and the network stack
- The Link Layer (LLC and MAC) are independent of the network stack. So, it's possible to send RAW IEEE802.15.4 without GNRC, or reuse the MAC layer for other network stacks (lwip, etc)

It will be more clear with the picture

> So let me try to understand again... these are just wrapper functions for l2->ops functions? Why not use those directly then instead of adding more overhead?

They certainly wrap `l2->ops`, but they also do extra stuff (e.g checking if the L2 layer should process the MAC layer if RAW, check if the interface is up, etc)

**Pull request closed without merging**
