### PR TITLE
tests: Added tests for gpio_init_int() on ATmega boards

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR adds a test that tests `gpio_init_int()` on ATmega boards, which differs in two major points from the existing test for `gpio_init_int()`:

- It can be compiled for ATmega328P based boards
- It takes the pin changed interrupts of the ATmega into account. (A single interrupt vector for 8 pins.)

### Testing procedure

Build, flash and run the provided test on a couple of ATmega based boards

- [ ] ATmega32U4 based board (`arduino-leonardo`)
- ~~[ ] ATmega256RF2 based board (`jiminy-mega256rf2`)~~ (Board support dropped in RIOT)
- [ ] ATmega328P based board (`arduino-uno` or `arduino-nano`)
- [ ] ATmega1281 based board (`waspmote-pro`)
- [ ] ATmega1284P based board (`mega-xplained` or the not yet mainlined INGA board)
- [ ] ATmega2560 based board (`arduino-mega2560`)

### Issues/PRs references

~Depends on and includes https://github.com/RIOT-OS/RIOT/pull/11122~ (merged)
~Depends on and includes https://github.com/RIOT-OS/RIOT/pull/11927~ (merged)

### CODE REVIEW

**Comment by maribu** [comment]
OK. I tested this on the Ardunino Lenoardo, Uno, Nano, and Mega2560. I had to add board specific pin change interrupt configurations to take unconnected or unusable GPIOs into account. I also updated the ATmega328P pin change interrupt configuration, as two pins can be used as both external interrupt and as pin changed interrupt. I disabled those as pin changed interrupts to make it more obvious that RIOT will never configure them that was, as external interrupts take preference in the implementation (which makes sense).

@roberthartung: The PR is now ready to be reviewed

**Comment by maribu** [comment]
@roberthartung: Have you found time to give it a look?

**Comment by roberthartung** [comment]
Works for me so far. :) However is it good to 'randomly' attach flanks? e.g. if pull ups/downs are presented this might cause an issue?

**Comment by maribu** [comment]
I think that the flanks should not be an issue if external pull downs are present: One would need to use a second jumper wire connected to VDD to generate the edge for those pins.

But enabling the internal pull up will be problematic with an external pull down present. I think that the combined resistance of both pull resistors should be high enough to limit the current to a safe value, as they will be in series (and not in parallel), right? But the logical value at the pin could be "jumpy", if both pull resistors pull are similar "strong".

But this should not be an issue on the boards we currently have in RIOT, as they do not use external pull downs on the relevant pins as far as I know.

A better approach for testing would be to provide a shell and let the user pick the pins to test. But using the shell is not possible on the ATmega328P based boards due to memory constrains; and new boards having external pull downs might be using the ATmega328P. So this is not viable, sadly.

I think in case new boards are added that do have external pull downs, those pins could be added conditionally (`#ifdef ...`) to the `blacklist`. Or a second list for "use `GPIO_IN` instead of `GPIO_IN_PU`" could be added. But so far this is not needed.

**Comment by roberthartung** [comment]
> But this should not be an issue on the boards we currently have in RIOT, as they do not use external pull downs on the relevant pins as far as I know.

Well we also have to think about the future I guess. Just wanted to make a hint about that. Maybe we should add a README.md to the test so we mention that we assign the flanks "randomly" (round robin manner) and one needs to be careful, when using the test, if external pull downs are present?

**Pull request closed without merging**
