### PR TITLE
tests: conn_ip: provide test scripts

### PR DESCRIPTION
**Pull request by miri64**
Provides some automated test cases for the `conn_ip` tests.

### CODE REVIEW

**Comment by authmillenon** [comment]
Ah wait, just realized that this restricts the tests only to one BOARD type. :/

**Comment by authmillenon** [comment]
Postponed to next release.

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by miri64** [comment]
Since #5772 provides its own tests I close this one.

**Pull request closed without merging**
