### PR TITLE
Declare adc_config[] like others peripherals configuration arrays

### PR DESCRIPTION
**Pull request by hugueslarrive**
### Contribution description
I don't see why it was done this way.

### CODE REVIEW

**Comment by aabadie** [comment]
Needs a rebase to resolve conflicts now that #14849 is merged.

**Comment by hugueslarrive** [comment]
@aabadie rebased.

**Comment by aabadie** [comment]
Murdock is reporting build issues with the nrf51 base boards. I checked and `adc_conf_t` is not defined for nrf51.

**Comment by hugueslarrive** [comment]
@aabadie typedef added.

**Comment by aabadie** [comment]
There are still issues on blue/backpills with C++. That looks like an issue with the order of attributes as defined in the struct that is not correct in these board periph_conf.h.

**Comment by hugueslarrive** [comment]
> There are still issues on blue/backpills with C++. That looks like an issue with the order of attributes as defined in the struct that is not correct in these board periph_conf.h.

No luck for me, PRs # 14861, # 14862, # 14863, # 14864, and # 14865 were based on this configuration since I have a bluepill...

**Review by aabadie — APPROVED** [review]
All good for me. This PR is mostly using the array config scheme for ADC. I also checked the firmware size on nrf51 and this is unchanged by this PR.

ACK

**Pull request merged**
