### PR TITLE
esp8266: esp_wifi netdev driver

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR adds a `netdev` driver for infrastructure mode WiFi for ESP8266 using the built-in WiFi module. Using this `netdev` driver, ESP8266 can use an existing WiFi network to get connectivity. The `netdev` driver supports WPA authentication only.

The Wifi network interface (module `esp_wifi`) and the ESP-NOW network interface (module `esp_now` #9917)
can be used simultaneously, for example, to realize a border router for a mesh network which uses ESP-NOW.

### Testing procedure

- Compile and flash `example/gnrc_networking` to at least one ESP8266 node using your AP configuration, e.g.,
    ```
    CFLAGS='-DESP_WIFI_SSID=\"<your SSID>\" -DESP_WIFI_PASS=\"your passphrase\"' USEMODULE="esp_wifi" make BOARD=esp8266-esp-12x -C examples/gnrc_networking flash
    ```
- Once the application is flashed connect the ESP32 node with any terminal programm with a default baudrate of 115.200 bps.
- Use `ifconfig` command to check the existence of the network interface. You should be able to observe an output as follows:
   ```
   Iface  7  HWaddr: 5C:CF:7F:80:3F:08  Link: up 
          MTU:1500  HL:64  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wireless
          inet6 addr: fe80::5ecf:7fff:fe80:3f08  scope: local  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff80:3f08
          inet6 group: ff02::1a
          
          Statistics for Layer 2
            RX packets 12  bytes 2698
            TX packets 1 (Multicast: 1)  bytes 0
            TX succeeded 0 errors 0
          Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 1 (Multicast: 1)  bytes 64
            TX succeeded 1 errors 0
    ```
- Ping any host in LAN.
- If the router provides a global routing prefix, check with `ifconfig` that the prefix is set.
   ```
   Iface  7  HWaddr: 5C:CF:7F:80:3F:08  Link: up 
          MTU:1440  HL:255  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wireless
          inet6 addr: fe80::5ecf:7fff:fe80:3f08  scope: local  VAL
          inet6 addr: 2003:c1:e72f:6c40:5ecf:7fff:fe80:3f08  scope: global  VAL
          ...
   ```
- Stress testing from LAN with `sudo ping6 fe80::<ESP_IID> -Ieth0 -s1392 -i 0.0001` should be stable over hours.
- It should also be possible to ping simultaneously
   - the ESP8266 node from the LAN with `sudo ping6 fe80::<ESP_IID> -Ieth0 -s1392 -i 0.0001`
   - the node in the LAN swith `ping6 1000 fe80::<LAN_IID> 1392 0` .

### Issues/PRs references

This PR depends on PRs #10656 and #10766 and is related to PR #9917.

### CODE REVIEW

**Comment by smlng** [comment]
I think this needs a rebase, as the runtime config stuff is merged now.

**Comment by gschorcht** [comment]
> I think this needs a rebase, as the runtime config stuff is merged now.

Yes, but could this later after reviewing it. Travis doesn't fail with doccheck.

**Comment by smlng** [comment]
get a compile error, something lwip related, maybe need to add the package as a dependency? I tried that but ran in further problems. Here the error when just adding `USEMODULE=esp_wifi`

```
esp8266/vendor/espressif/user_interface.h:31:26: fatal error: lwip/ip_addr.h: No such file or directory
 #include "lwip/ip_addr.h"
```

**Comment by gschorcht** [comment]
Hm, this PR depends on PR #10656. My local working branch bases on the branch of this PR. Since the `esp_wifi` netdev driver will not work without this PR, we should try to get PR #10656 merged first.

**Comment by smlng** [comment]
> Hm, this PR depends on PR #10656. My local working branch bases on the branch of this PR. Since the `esp_wifi` netdev driver will not work without this PR, we should try to get PR #10656 merged first.

damn, oversaw the deps completely, will try ... sorry for the noise 😞

**Comment by gschorcht** [comment]
@smlng I have investigated your compilation problem a bit more. It seems that `lwIP` header files are not in the toolchain as installed in riotdocker. It's not really clear why at the moment. I'm using a local installation of the toolchain. Therefore, I didn't realize that problem.

@kaspar030 If I can fix it in the toolchain, do you see any chance to get it in riotdocker and murdock in short term? Otherwise, I would have to provide `lwIP` header files as vendor files for esp8266.

**Comment by miri64** [comment]
> @smlng I have investigated your compilation problem a bit more. It seems that `lwIP` header files are not in the toolchain as installed in riotdocker. It's not really clear why at the moment. I'm using a local installation of the toolchain. Therefore, I didn't realize that problem.
> 
> @kaspar030 If I can fix it in the toolchain, do you see any chance to get it in riotdocker and murdock in short term? Otherwise, I would have to provide `lwIP` header files as vendor files for esp8266.

Can we find another solution? I did not try, but I expect issues when someone tries to use `esp8266` with the [`lwip` *pkg*](https://github.com/RIOT-OS/RIOT/tree/master/pkg/lwip), especially since lwIP's `ip_addr.h` had always been a hellscape of `#ifdef`s when porting the newest lwIP release.

**Comment by miri64** [comment]
Maybe adding an `#ifndef RIOT_VERSION` around the `#include` (or since we imported the files anyways just remove them) would help?

**Comment by gschorcht** [comment]
> Can we find another solution? I did not try, but I expect issues when someone tries to use esp8266 with the `lwip` pkg, especially since lwIP's `ip_addr.h` had always been a hellscape of #ifdefs when porting the newest lwIP release.

There will be no chance to use esp8266  with RIOT's `lwip` at all since any WiFi based communication (modules `esp_now` and `esp_wifi`) requires to use the proprietary libraries from Espressif's SDK which in turn depend on their own port of `lwIP` version 1.4.1. 

> Maybe adding an `#ifndef RIOT_VERSION` around the `#include` (or since we imported the files anyways just remove them) would help?

Where would you suggest to use this?

**Comment by gschorcht** [comment]
@smlng I could fix the compilation problem without touching the toolchain.

**Comment by MrKevinWeiss** [comment]
I think +1 to option 1, I talked to quite a few people that chose other platforms because esp8266 wifi wasn't supported on RIOT.  I think something is better than nothing assuming it doesn't corrupt anything else.

**Comment by kaspar030** [comment]
> I think +1 to option 1

+1 here, too. The esp8266's main reason to exist is providing simple wifi access.

**Comment by smlng** [comment]
maximum I could ping was with 1446B payload including ICMP, i.e. 
```
 ping6 fe80::5a6d:8fff:fe38:2471 1438
```

where the IP is of the AP I used for testing, with `1439` is didn't work anymore

**Comment by smlng** [comment]
ping from my desktop node (iMac) to that node only worked up to 1280 bytes (incl. ICMP), but I guess that's somehow expectable for IPv6.

**Comment by gschorcht** [comment]
Partially good news. With the new [ESP8266 RTOS SDK 3.x](https://github.com/espressif/ESP8266_RTOS_SDK), Espressif started in September last year to publish a SDK which is quite similar to the [ESP-IDF](https://github.com/espressif/esp-idf) (the ESP32 SDK that was also used for the RIOT port to ESP32).

Initially, the RIOT port for ESP8266 was realized using the [ESP8266 NONOS SDK](https://github.com/espressif/ESP8266_NONOS_SDK) since the ESP8266 RTOS SDK up to version 2.x  was also closed source like the NONOS SDK, but additionally bases on FreeRTOS.

I was already thinking to try a port for the new ESP8266 RTOS SDK 3.x.

Cons:
- Parts of the ESP8266 port have to be rewritten from scratch to use this new SDK.
- Some parts of the ESP8266 RTOS SDK depend on FreeRTOS so that an adoption layer has to be written as for the ESP32 port.
- Some parts are still available only as proprietary binary blobs.

Pros for trying a port to the new ESP8266 RTOS SDK 3.x:
- Even though there are still some proprietary binary blobs, important parts of the SDK become available in source code with version 3.x of the ESP8266 RTOS SDK.
- All parts that are not required in RIOT can be dropped, including the `lwIP`.
- ESP8266 RTOS SDK is very similar to the ESP-IDF so that at least some parts of the code can be reused from the ESP32 port, e.g., the FreeRTOS adoption layer.
- There is a clear APIs for using the WiFi interface.

It's already on my ToDo to take a try, but at moment it seems to be more reasonable to get the existing port working with the WiFi interface.

**Comment by gschorcht** [comment]
Even though the MTU for Ethernet is 1.500, my Linux box starts to fragment from 1.440 bytes. That's the reason why I suggested to use `-s1392`. 

> Could there be some mixup of ETHERNET_DATA_LEN and ETHERNET_FRAME_LEN somewhere or am I messing something up here? ;)

Good point. There might be a problem, I didn't realize since my frames including MAC header and FCS were never greater than the MTU in tests.

**Comment by gschorcht** [comment]
BTW, `ifconfig` on esp8266 gives a MTU of 1440 which corresponds to the maximum data size in ICMPv6 of 1392 bytes. `esp_wifi` simply uses `netdev_eth_get(netdev, opt, val, max_len)` for `NETOPT_MAX_PACKET_SIZE` option.

**Comment by gschorcht** [comment]
@smlng @MichelRottleuthner Concerning the different MTU sizes you have seen. The MTU used by ESP8266, your iMac or a Linux box depends on whether the IPv6 MTU option is provided with the Router Advertisement. Although the MTU for an Ethernet (including WiFi) interface is 1500, once the node/machine received a Router Advertisement with the IPv6 MTU option, it is set accordingly.

You should be able to observe after a reset of the ESP8266 node that `ifconfig` gives a MTU of 1500 as long as it has only a link local address. Once ESP8266 received the routing prefix and determined its global unicast address, the MTU is sized down to the value provided with the Router Advertisment.

**Comment by MichelRottleuthner** [comment]
That indeed explains the different MTU sizes. On my setup it stays at 1500 even after receiving the router advertisement. 
Still, with payloads bigger than 1438 bytes the ping stops working. Looking at wireshark when using 1439 bytes I get an ICMP reply stating a parameter problem / erroneous header field encountered (Type 4/code 0).
Anyway, discussing this offline with @smlng we agreed that this shouldn't block this PR and can be fixed with a follow up PR.
Apart from the MTU thing, testing on the esp8266-esp-12x (after merging #10656) did not show any problems. Connecting to wifi and ping in both directions also worked perfectly fine here.

**Comment by gschorcht** [comment]
@MichelRottleuthner 
> I only tested that on an ESP32 but it didn't work. The maximum value that still worked for me was 1437. Adding the 40 bytes for IPv6 and 8 Bytes for ICMP6 there still seem to be 15 bytes missing.
Could there be some mixup of ETHERNET_DATA_LEN and ETHERNET_FRAME_LEN somewhere or am I messing something up here? ;)

Was a good hint. I have double checked the buffer sizes and length checks in ESP32 implementation and had to realize that they use `ETHERNET_DATA_LEN` instead of `ETHERNET_MAX_LEN` even though the are handling complete MAC frames. Once the MTU is downsized by Router Advertisments, it doesn't matter but before there might happen problems. PR should fix the problem.

**Comment by MichelRottleuthner** [comment]
>2c45d16 might fix the problem for esp8266.

yes that did the trick

**Comment by smlng** [comment]
please rebase

**Comment by gschorcht** [comment]
@smIng I have done a lot of stress tests in last days, bombarding one esp8266 node with pings with maximum data size and maximum rate from three nodes.
```
sudo ping6 fe80::5ecf:7fff:fe80:3f08 -Ieth0 -s1392 -i 0
```
I ran sporadically into the following problems:
1. Exception in `rmutex::unlock`
   https://github.com/RIOT-OS/RIOT/blob/0edf76d3622b0611442b595423baff49993b968b/core/rmutex.c#L128
2. Sporadic blocking of frame receiption due to a full packet buffer in `gnrc_pktbuf`. Packets are stucking in `pktbuf` even if pinging nodes are stopped.
3. Sporadic blocking of sending frames if they are sent too fast. Sometimes disconnecting to flush buffers in WiFi hardware and reconnecting helps, but not always.

Problem 1 could be solved by using the memory management function as provided by the Espressif SDK instead of using the newlib memory management.

I'm still working on problem 2 and problem 3.

**Comment by smlng** [comment]
Hi @gschorcht 

first: please rebase, once again so we can get this merged 😄 
second, regarding stress testing: maybe increase the packet buffer a bit, its default is 6K (IIRC) but with 1.5K frames this might be a bit small, especially if once in a while some other packets (e.g. from neighbour discovery) are also around and take up some space.

In general, I don't see a problem in merging this even with these issues present. I mean this is still embedded hardware and under high load I would expect some problems. Nevertheless we should keep them on our list: maybe open a tracking issue for esp_wifi and work on it. But with this merged we will likely attract more people using it and also testing will be easier for others, not requiring them to merge/checkout this PR but rather use master.

@MichelRottleuthner: agreed?

**Comment by MichelRottleuthner** [comment]
I agree, lets get this merged.

**Comment by MrKevinWeiss** [comment]
It isn't depending on any PRs anymore, is this ready @gschorcht ?

**Comment by MrKevinWeiss** [comment]
maybe rebase?

**Comment by gschorcht** [comment]
Rebased.

But I have set state to WIP to avoid merging by mistake since IMHO even an embedded system should be robust. Just give me one day and I will provide some small fixes.

**Comment by smlng** [comment]
>  Just give me one day and I will provide some small fixes.

sure, take your time ... However, to me it already looks more stable than other parts in RIOT 😬

**Comment by gschorcht** [comment]
@smlng I'm not completely satisfied, but it should be OK for the moment.

**Comment by smlng** [comment]
reACK this looks still good to me 😄 

Made some quick tests, Ping from PC -> RIOT:

| Interval [s] | max. packet loss [%] |
|--------:|-------------:|
| 1.000 | 0.0 |
| 0.100 | 0.0 |
| 0.010 | 0.5 |
| 0.005 | 0.6 |
| 0.002 | 10.0 |
| 0.001 | 50.0 |

Also I noted that the max. ping payload was `1452` + `8` ICMP -> `1460` Bytes total.

----

please squash

**Comment by smlng** [comment]
> When testing with `USEMODULE="esp_wifi" BOARD=esp8266-esp-12x make all flash term` everything works as expected.
> Though, by mistake I found a small obstacle: when compiling `gnrc_networking` without providing `USEMODULE="esp_wifi"` this results in a kernel panic shortly after boot (maybe the watchdog?).
> I wouldn't expect this and probably that will pop up quite often as the general usage for gnrc_networking is "just compile without parameters and use". IMHO without `esp_wifi` there should be just no network interface available, but it should not crash. Is there a way to fix this?

I found that, too - but I think its some other layer/function in GNRC. Because removing all `rpl` and `netstat` modules, fixes that and there is no panic anymore. At least for me, it worked when I misspelled `esp_wifi` to `esp-wifi`.

**Comment by gschorcht** [comment]
Indeed it is a pitfall and I'm not sure how we should handle it.

The reason for this kernel panic is an `assert(netif != NULL);` in `sys/net/gnrc/routing/rpl/gnrc_rpl_auto_init.c` since there is no `netif` if module `esp_wifi` is not enabled explicitly. `esp_wifi` is not used as `netdev_default` by intention due to the following reasons:

- Module `esp_wifi` requires to use Espressif SDK which is disabled by default for the reasons documented [here](https://riot-os.org/api/group__cpu__esp8266.html#esp8266_overview).
- Due to symbol conflicts in vendor library `libwpa.so` which is required by module `esp_wifi` with RIOT's `crypto` and `hash` modules, `esp_wifi` cannot be used for applications that use these modules. Therefore, module `esp_wifi` is not enabled automatically when module `netdev_default` is used. Instead, if necessary, the application has to add the module `esp_wifi` in the Makefile. This is documented.

Sure, we could enable module `esp_wifi` by default when module `netdev_default` is used, but if you want to use other network devices, for example [MRF24J40](https://riot-os.org/api/group__cpu__esp8266.html#esp8266_network_devices), you do not need the whole hell of theEspressif SDK. Whenever possible, I would avoid using the Espressif SDK. A deep black box, eating 50 kbytes of RAM, slowing down the execution and competes with the scheduling of RIOT.

**Comment by MichelRottleuthner** [comment]
>Whenever possible, I would avoid using the Espressif SDK.

I absolutely agree.
The [line in the rpl code](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/routing/rpl/gnrc_rpl_auto_init.c#L32) is perfectly fine I think.
The actual problem comes form the [Makefile.include](https://github.com/RIOT-OS/RIOT/blob/master/Makefile.include#L284) that sets GNRC_NETIF_NUMOF to 1 by default - which doesn't make sense to me. But I'm currently not sure about the implications on changing this to 0, and as it turns out this is currently the same for all other boards that don't provide a radio. So lets move on here ;)

**Comment by smlng** [comment]
I hit the green button NOW!

**Comment by smlng** [comment]
🎉 cheap WiFi in RIOT 🎉 finally 🎉

**Comment by MichelRottleuthner** [comment]
Lets remove the WIP label then :P

**Comment by gschorcht** [comment]
:worried: I added this by intention since I though it avoids merging because I found one further complete blocking case I planned to fix before the merge. Too late for the moment.

**Pull request merged**
