### PR TITLE
sys/fmt: optimize scn_u32_hex()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

We can save a branch by always converting to lowercase first.

### Testing procedure

`tests-fmt` in `tests/unittests` covers this.

### CODE REVIEW

**Review by kfessel — COMMENTED** [review]
This PR has an extra call to strnlen, does not check for out of hex range chars like c > 'f'  or control char, fixing that will likely make this less efficient then our current impl.

check [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAMxcpK4AMngMmAByPgBGmMQgAKxmpAAOqAqETgwe3r4BQemZjgJhEdEscQnJtpj2JQxCBEzEBLk%2BfoG19dlNLQRlUbHxSSkKza3t%2BV3j/YMVVaMAlLaoXsTI7BwA9NsA1AAqAJ6pmHtHa8R7aFh7CPGYpHske7SoTOh7hnuYqqyp9AAdCYNABBcz%2BcLIby3Ez%2BNzjfCCQEIOHYEHgsyQhjQryw%2BHjYjhYAotEYjFecIEfxmAD6BD2CmQDFpXhptPuqggaAY42uCBaewAVISnpkAF6Yel7BhLckAdisYL2Kr2lME7IZxEwCj2cIAInsNHCleDlaqAO4IOhnCAMAC09qWesVGNV7rVvLwwAin2Qev8hpFBGI1jD/lNHtVXi9Pswn3QJrdUb2eCoeygYA4GizcLcBuuzvMADYSxn/XmC1mAJxZpZy13mlOqz4F/32jMxzJx9BLLM5jhJpsekzy/XJqN1JSp9OZjigrMB/OBwt6syl9flpdVjgAMTrRcboOb7tbK/bndjvr788X1iNfzkQ%2BPKdH4%2BH7qnZzTGYgWaYd7wm2RbrmW3LbiuWZUAeLqRieKpnoaF4QF23rXv%2Bd6WA%2BTBPhGE4jmO%2BGfrQ06jnB8ExNqTAANbPs2b5Eaq2q6pWQErpIuHkR6zEusuhqJnhYL4Qxw7agQ6wMHszHPiJZqguq1J0gyTIsmydKcmY3ICHyyAClcwZkIyeCStKsoKnBCmalJOoBoaxqCS%2BkkFoSDD0AwECijKcoOfhVo2hmDpOrBjEqqhPbXLZwqEmGWGjm4ew0iaezbEK1wCAAbvEDJEK8qAWvEojTkK2whZ63a%2BnsiERWSkEcABg4fvB7pwruEUdhhHBrhYexcMajVNSqIBtXs/a5g5zY8axfF7BxdEppN8rTQJXGye6YkSdZCgyYRQlgpZSmMsyrLspy/habyDK6YKBlisZUoMmZQlHqFVJWZNK72Vxex%2BfQAWOoeX3Rle8bVSuBkxd1cUJWYSUpWlDCZa0ew5W8%2BUbEwRUlf1M4QKD2AjRw0GdXFUMVvCBMDs6lGYDRc1RmFFVVWT6K1fVpVNS1w0dV1PV9S%2BA0ekNF6jYO43zTZU0FrNYtRgtS10y67789Z4nEJJ0k%2BWOHArLQnCJLwfjZrwqCcPmlj3golybGugS8AQmjays1FJBo%2BicJIBsO6QJscLwCggK79tGyscCwEgaAsKkNpkBQWmR9HIAtCwwBcDSrtYOleCbAAangmAWgA8qchs8HwdAEPE/sQDEXsxOELRHJwpd18wxBHAXMTaJgDhN7wEdsIIBeuY3RukFgMReMAbhiCRvdj5gLCGMA4ij/g2oOHgmX%2B6Pvzd14Fdz1SdRe7QeCUQ3HhYF7IZ4CwvcrFQBjAAouf50XjBz/wggiGI7BSDIghFAqHUKPXQQQDBGBQBDfQZ9/aQBWKgVIDRt72gLmYY2iMiRYDgRAFYdhu4NBcAwdwngOh6FCOEIYlQRiFAyFkAQUw/C0OKNkeYwwEhBHwRvAQfRJikPyJwuoBDegTAGJQhYNDbCiMYXoWYrQ2HUI4Xgq2f8dZ609qPH2exQQACUACyewADibh4qp0BGYQEGgMy4EIC8CEXAlh2wdvWUgztEiu11hwD2pBDZaG9pwP2AdSBBy0C4zx6CfFex9k44OKxEaZGcJIIAA%3D%3D)

**Comment by kfessel** [comment]
[godlblot cortex m0+  including a version 3](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAA7KQADqgKhE4MHt6%2BekkpjgJBIeEsUTHxdpgOaUIETMQEGT5%2BXLaY9nkM1bUEBWGR0XG2NXUNWc0KQ93BvcX9sQCUtqhexMjsHAD06wDUACoAngmYW3tLxFtoWFsI0ZikWyRbtKhM6FuGW5iqrAn0AHQmGgAguYAMzBZDeS4mEFucb4QS/BDQ7AA4FmMEMCFeKEw8bEYLARHI1GbLYAWgA8mZySxkAkvNCACJoOqfMksDQ/LwKGlUJ5MAhkpgRPBMhSoKgEEnbSnU9l0hkg5kkAhsliSVGorzBAggswAfQIWwUyAY%2Bq8ev111UEDQDHG5wQtS2ACo8XcUgAvTCGrYMOaa2JWIFbUNbbWCS1G4iYHlMrYaaHB4EhsMAdwQdCOEAYZLJcy2JiDqLDpfD9rwwBCr2QhaVrrx1ibIOTZbDXgrVcwr3QSZLba2eCoWygYA4GjH0Lc8eQBfMADYFyPa1P42OAJxjuYB4upgdh14z8kjjspLvoOZjiccPt7stFxn9tutJSD4ejjiAsd16f12eFsxF0A5cfzXDgADEtznXdAX3UtDz/Y8IFPStq0vT9v2sBMvjkW9YIHB8nzLF8jiHEcIDHJhMJhGc50ApdbVA%2BsxyoKDCxguCDzrRlziQlDz3QqiOAAixsKYXCWyI0tCLvUsSPY1tOK2CIYyYABrPD9xk/C2xjOMaIMnjJAkxTdNjdjfx43tJKBIjtNLGMCGWBgtj0vDtK1HUo2NU1zUta0zFtAQHWQJ0zjdAgyGNPBvV9f1A0UiNdQNaNzPjRMbPwlz4zxBh6AYCB3T9ANMqIjMsxHXN8wUqT207atePjCLiCbSwLK2PUky2dYXXOAQADdoiNIhHlQNNolEV8XXWWrQ34hqEJ4lcQRRZiOCE2alLrcDeLJLZKMwtquETWSttDEBdv28dJ0y/c9KYyytmMzSB3uotHus0z2MfO9HOc1zY3c2IfpTQEku8k0zQtA1rRBIL7SNULnWaj0Yp9I14tsjjwy8lKAf0niMq%2BrZyvoSq82g4m6rPBrlp45rWtE96OrMLqer6hhBrqLYRqecaViYKaZtOub6u7LZFsalawI2kWtuhHbaz2g7hKw47NqUi6lau68XrbIcIAlutsGw4cCxUzB1L1ss3oMx7ntu160tiD7rfssM/uIFy3NK4GOAWWhOAAVl4Pxx14VBOGnSwsPFZZVgAkEeFIAhNH9hY1JAEEQV%2BbO8/zgv530ThJFDtPSEjjheAUEANBTtOFjgWAkDQFgEizMgKCCtuO5AWoWGALg9TrrB%2BrwVYADU8EwNMKUOMPk5oWhVWIGuIAicuRWYYg9k4ZOt9qPYKQibQKlT7heFbthBApPLd/D0gsAiLxgDcMRaBri/H8wFhDGAcQH74BjJUQan8tCkE%2BBULwqo968B1K0cutA8AqUPh4LA5dIp4BYLAhYfImDAAUFPGec9GCwJkIIEQYh2BSHIfIJQahy66GaAYIwKBGb6GQTXSACxUAJHaJ/WUNIFRMhZKqVQ7JOTeB5OyPkzxBTClFEqcUkoI5c3xFgLhEAFjlEqM4CArgRhNAgQwdAPQiglGyMkVIAhDGWNyGkMxfQYhjFaGfKoExbEuLaO4rojiZjOMGF0TxgS6h%2BIsVwbRpxVgSADsHMuD9K5bEBAAJQALJbAAOJuDcFsIevwzC/A0COXAhAHiggibwc%2BWhtykEztnXOBdGnZyLoHDgpdSBh3AZXautd67h0bjARAIAlgEHpAQcglBW7t3oMQUIrA1gpPSVknJeSCngO7KU9Reh%2BAUNEOIGhOy6EqHUA/JhpA0zECYAkHBxcOAhw6eXSuFJoFjPuMORZmTsm5JzmskcHge4zMThUvp1SM5Zxzk0pptz2mdIjpwHpdcqnp1uWYeJXT4UguRVzFIzhJBAA%3D%3D)

**Comment by kfessel** [comment]
one might want to look at #19027

**Comment by Teufelchen1** [comment]
As I stated in PR https://github.com/RIOT-OS/RIOT/pull/19027#issuecomment-1343106941, the unittest for the fmt module are lacking. Your changes break the API promised in `fmt.h`. Sadly, our unittest don't catch that.

**Comment by kfessel** [comment]
@Teufelchen1 : You probably already got something in mind  would you want to make that a PR?

**Comment by Teufelchen1** [comment]
Hey hey, the new test just got merged. It will fail with the current implementation in this PR.
Do you want to adapt or close this?

**Review by Teufelchen1 — APPROVED** [review]

**Review by kfessel — CHANGES_REQUESTED** [review]
uses more stack

**Comment by benpicco** [comment]
> uses more stack

How?

**Comment by kfessel** [comment]
> > uses more stack
> 
> How?

seem like it needs an intermediate for the case-conversion

**Comment by kfessel** [comment]
https://godbolt.org/z/dz3c6d1oh

for your experiments

**Comment by kfessel** [comment]
ah and the test ist still incomplete

**Comment by kfessel** [comment]
https://godbolt.org/z/KTYWf4v66

execute on x86 godlbolt reveals this PR will return `2467` if asked  for `scn_u32_hex2("9:3k",5)`

i am not sure how it does that

**Comment by benpicco** [comment]
Yea I guess it's mostly obfuscation at this point…

**Comment by kfessel** [comment]
It's now even worse (more stack and more assembly, and the code is barely readable)

Do you really want to try to optimize this function? (I might be biased because i wrote the current implementation)

If you do please provide some kind of proof for: "this is better"  

I like godbolt  `gcc-arm a current version` `-O(2,z or 3) -mcpu=cortex-m0plus -mfloat-abi=soft` or `-O(2,z,3) -mcpu=cortex-m4` for reading 
with a main function and an x86-64 you can also have it run something  print or compare (know good to new) and print test cases in arrays iterate across ranges  ... it is realy nice

**Comment by Teufelchen1** [comment]
I am with @kfessel here. Closing this PR seems to be the best way to handle this? Even if we find an implementation that produces perfect out put for a given compiler: There are so many variables. So far we only looked at arm but RIOT supports more ISAs. How do their compilations compare? What is about run-time performance? etc. etc.

**Comment by Teufelchen1** [comment]
In consent with benpicco: Closed, not worth the extra time.

**Pull request closed without merging**
