### PR TITLE
cpu/atmega1281: fix pcint

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
The atmega1281 is declaring more PCINTs than it has, causing compilation to fail when `atmega_pcint` is used (together with `periph_gpio_irq`). Looking at [the datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega640-1280-1281-2560-2561-Datasheet-DS40002211A.pdf) there are only PCINT0:8. This fixes this mapping.

### Testing procedure
- With this PR you should be able to compile `tests/periph_gpio` with `BOARD=waspmote-pro USEMODULE="atmega_pcint" make`, which fails on current master.

### Issues/PRs references
Found in #17224

### CODE REVIEW

**Comment by maribu** [comment]
The datasheet says:

GPIO Port B contains PCINT0 to PCINT8
GPOI PORT E contains PCINT8 (at pin PE0)
GPIO Port J contains PCINT9 to PCINT15
GPIO Port K seems to have PCINT16 to PCINT23

So there should be three Pin Changed banks, pcint0, pcint1 and pcint2.

**Comment by leandrolanzieri** [comment]
> The datasheet says:
> 
> GPIO Port B contains PCINT0 to PCINT7 GPIO PORT E contains PCINT8 (at pin PE0) GPIO Port J contains PCINT9 to PCINT15 GPIO Port K seems to have PCINT16 to PCINT23
> 
> So there should be three Pin Changed banks, pcint0, pcint1 and pcint2.

Is that so also for this model? Ports J and K are not even defined for this CPU in RIOT, and I get
```
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c: In function 'pcint_init_int':
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:276:13: error: 'PCMSK2' undeclared (first use in this function); did you mean 'PCMSK1'?
  276 |             PCMSK2 |= (1 << bank_idx);
      |             ^~~~~~
      |             PCMSK1
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:276:13: note: each undeclared identifier is reported only once for each function it appears in
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:277:28: error: 'PCIE2' undeclared (first use in this function); did you mean 'PCIE0'?
  277 |             PCICR |= (1 << PCIE2);
      |                            ^~~~~
      |                            PCIE0
In file included from /home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:31:
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c: In function 'PCINT2_vect':
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:431:5: error: 'PCINT2_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Werror=misspelled-isr]
  431 | ISR(PCINT2_vect, ISR_BLOCK)
      |     ^~~~~~~~~~~
/home/leandro/Work/RIOT/cpu/atmega_common/periph/gpio.c:433:31: error: 'PCMSK2' undeclared (first use in this function); did you mean 'PCMSK1'?
  433 |     pcint_handler(PCINT2_IDX, PCMSK2);
      |                               ^~~~~~
      |                               PCMSK1
```

**Comment by leandrolanzieri** [comment]
Checking the interrupt vectors, the interrupt for `PCINT2` says: `3. Only available in ATmega640/1280/2560.`

**Comment by maribu** [comment]
The datasheet says that the 1281 is having only 54 GPIOs compared to the 86 GPIOs of the 1280. So I guess you are right. The datasheet is pretty confusing regarding the differences between the versions...

**Comment by maribu** [comment]
In Figure 1-3. "Pinout ATmega1281/2561" it is obvious: No GPIO port J or port K present in the pinout.

**Review by maribu — APPROVED** [review]
ACK. Thanks for fixing!

**Comment by leandrolanzieri** [comment]
Thanks for the review!

**Pull request merged**
