### PR TITLE
cc3200 board and cpu

### PR DESCRIPTION
**Pull request by attdona**
This PR is a rebase and obsoletes #4055 and #4059.
NB: this PR comprises cpu and board part of cc3200. 

Once accepted The next (and last) cc3200 PR will be the SDK driverlib and simplelink library from TI required for building the riot image.

### CODE REVIEW

**Comment by kbumsik** [comment]
Hello, I am currently working at CC3100. I looked through you PR and it looks like some work for Wifi SDK. Could I see your current work on the driverlib and simplelink SDK? I will look into it to port CC3100 as well.

**Comment by attdona** [comment]
You can see my work on the tdd branch:
cpu/cc3200/sdk containes the ti sdk and the riot adaptation layer osi_riot.c

Greetings
Attilio

**Comment by kbumsik** [comment]
Thanks I will take a look :)

**Comment by OlegHahm** [comment]
Any news?

**Comment by attdona** [comment]
Hi Oleg,
I prepared this PR some time ago, please let me know if I will have to do some more adjustements.

**Comment by OlegHahm** [comment]
Does anyone among the maintainers have the hardware to test?

**Comment by rosenk** [comment]
I wish to help on supporting cc3200 launchpad in RIOT. I hare the hardware. Please tell me what's need to be done.

**Comment by aabadie** [comment]
Someone still working on porting to CC3200 ?

**Comment by attdona** [comment]
Please give a look to https://github.com/attdona/NAIS.
I wil be using a port to cc3200 for NAIS. The port under burba would works with the master branch of RIOT.

Note: once xtimer did not support mcu timer frequencies not powers of two of 1Mhz so I rewrote a xtimer implementation (just for 32 bits) and I use that for the port.
Now I think the new xtimer would work as well, but I have no tested this part.

**Comment by tcschmidt** [comment]
@rosenk @A-Paul any testing & reviewing work completed? Is there any change to progress on this?

**Comment by A-Paul** [comment]
@attdona, are you still working on this port? I can't figure out if your last comment is stating a running system or if it's a "work in progress" notification.
Also the xtimer has gotten some essential changes. Maybe the mentioned workaround isn't needed anymore.

**Comment by attdona** [comment]
I'm not working any more on this port.

Greetings
Attilio

**Comment by tcschmidt** [comment]
Then close?

**Comment by A-Paul** [comment]
> Then close?

@tcschmidt, I think so. I'm not aware of any developer/maintainer which is using that board for now.

**Comment by A-Paul** [comment]
Closing because upstream activity has been stopped. Labeling `memo`.

**Pull request closed without merging**
