### PR TITLE
tests/{cpp_ext, cpp_exclude}: model in kconfig

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR slightly adapts the dependencies of `tests/cpp_ext` and `tests/cpp_exclude` test application (just remove apparently useless libstdcpp required feature) and add to them a Kconfig app.config.test file.

### Testing procedure

Green Murdock should be enough

### Issues/PRs references

I dropped that change from #17992 because I couldn't find why libstdcpp dependency resolution is different with and without TEST_KCONFIG set on esp32. And apparently libstdcpp is not needed in these applications.

### CODE REVIEW

**Comment by aabadie** [comment]
This one is finally green. Just missing an ACK

**Review by benpicco — APPROVED** [review]
Looks pretty straightforward

**Comment by MrKevinWeiss** [comment]
Hmm, the only thing I was unsure about was a module selecting `HAS_*` which is normally selected based on the arch, for example, the `arduino-mega2560` does not have `libstdcpp`.  It passes murdock because the supported boards check is done with make but when running with TEST_KCONFIG we get:
```
/home/weiss/wd/RIOT/tests/cpp_exclude/main.cpp:21:18: fatal error: cstdio: No such file or directory
compilation terminated.
make[1]: *** [/home/weiss/wd/RIOT/Makefile.base:166: /home/weiss/wd/RIOT/tests/cpp_exclude/bin/arduino-mega2560/application_tests_cpp_exclude/main.o] Error 1
make: *** [/home/weiss/wd/RIOT/tests/cpp_exclude/../../Makefile.include:744: application_tests_cpp_exclude.module] Error 2
make: Leaving directory '/home/weiss/wd/RIOT/tests/cpp_exclude'
```

**Comment by MrKevinWeiss** [comment]
I just didn't have a better way to solve it at the moment.

**Pull request merged**
