### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by francois-berder**
### Contribution description

I recently came accross [codespell](https://github.com/codespell-project/codespell), a tool that fixes typos in source code. I simply applied this tool to RIOT with this command: ```codespell -w .```.

I did not include any change that affects:
* vendor headers in `cpu/`
* files in `pkg/`
* source code (excluding comments and strings)

### Testing procedure

This PR does not change the source code. However, since some strings were changed, it might have an effect on tests looking for specific strings.

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
Thanks for pointing us to the codespell tool. I tested locally and it's indeed very useful for tracking typos in contributions (see #12232).

In the current state, it will be difficult to merge this PR: there are a lot of files changes, all in a single commit. To make reviewing (and merging) easier for maintainers, I would recommend to merge #12232 first, so we are sure no typos are missing in the changed files and maybe also split this PR in sub-PRs, maybe one PR per top level directories (cpu, boards, drivers, etc) ?

**Comment by benpicco** [comment]
Murdock didn't finish ~~succesfully~~ successfully either, so looks like not everything got replaced.

**Comment by kaspar030** [comment]
I have rebased and squashed this, the result is 3a9dade0c24367bb4eb546312d7b764368ce60a5 in my repo.

**Comment by kaspar030** [comment]
#12558 fixes the remaining typos.

**Comment by francois-berder** [comment]
> #12558 fixes edit most of the remaining typos.

ok so I am closing this PR.

**Pull request closed without merging**
