### PR TITLE
SAUL/phydat: parts per million support

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

Add ppm (parts per million) unit support to saul and phydat.

### Issues/PRs references

None, but a dependency for a follow up PR for a driver for the MH-Z19 CO2 sensor.

### CODE REVIEW

**Comment by bergzand** [comment]
@gebart You're right. I would argue for changing it to SENSE_GAS here. I think changing it to SENSE_CO2 might cause a huge list of gas sensor types in the future.

**Comment by gebart** [comment]
On the other hand, the sensor type is an enum, which gives us the possibility to define a large number of sensors

**Comment by bergzand** [comment]
I have really no clue how many types of gas sensor are used in practice and thus how large this list might grow. I'm also fine with changing it to SENSE_CO2 as it is more clear as soon as there are different gas sensor types.

**Comment by bergzand** [comment]
After a short discussion on IRC, it became clear that there are not that many types of gas that are interesting to measure (mostly co2, co and VOC). Changing it to SENSE_CO2 as that gives more information about the sensor then.

@gebart is this okay with you?

**Comment by gebart** [comment]
SENSE_CO2 is fine for me

**Comment by bergzand** [comment]
Changed to SENSE_CO2

**Comment by smlng** [comment]
I think we might need both, i.e., having an ambiguous `SENSE_GAS` and specific `SENSE_CO`, `SENSE_CO2` and so on. For instance, `MQ-135` is a multi gas sensor --hence qualifying for `SENSE_GAS`, while `MQ-9` is for `CO` and `MQ-3` for ethanol, only.

**Comment by gebart** [comment]
@smlng let's add them when we need them

**Comment by smlng** [comment]
>  let's add them when we need them

sure! Just wanted to stress that having both makes sense (in the long run).

**Comment by bergzand** [comment]
Thanks for the comments.

@gebart, @smlng Can I squash here?

**Comment by bergzand** [comment]
Squashed

**Pull request merged**
