### PR TITLE
cpu: native: hwtimer: change mach includes

### LINKED ISSUE #3175: Native: build of vtimer_msg test fails on OS X
Build of vtimer_msg test fails on OS X with current master. 

Error is:

```
In file included from /RIOT/cpu/native/hwtimer_cpu.c:47:
In file included from /RIOT/RIOT/core/include/debug.h:34:
/RIOT/core/include/thread.h:138:14: error: conflicting types for 'thread_create'
kernel_pid_t thread_create(char *stack,
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/mach/task.h:193:15: note: 
      previous declaration is here
kern_return_t thread_create
              ^
1 error generated.
```

Toolchain info:

```
OS X version 10.10.3
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

### PR DESCRIPTION
**Pull request by kaspar030**
fixes #3175

### CODE REVIEW

**Comment by kaspar030** [comment]
@emmanuelsearch Could you confirm that 3175 is fixed, and merge when travis is ready?

**Comment by kaspar030** [comment]
@emmanuelsearch This should make master build again... Did you try?

**Comment by OlegHahm** [comment]
IIRC master is not even compiling for OS X.

**Comment by kaspar030** [comment]
This PR is intended to fix that...

**Comment by OlegHahm** [comment]
Sorry commented on the wrong PR.

**Comment by thomaseichinger** [comment]
Obsolete with #3282

**Pull request closed without merging**
