### PR TITLE
dist/tools/uncrustify/uncrustify.sh: fix uncrustify check logic

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Previously, uncrustify.sh would fail (report uncrustifying necessary) if
there was any output of uncrustify. Turns out uncrustify sometimes
outputs something.

This commit changes the logic to use uncrustify's output value as
indicator, not the presence of any output.

Also, adds printing which file causes the check to fail.

For example, I'm using "Uncrustify_d-0.70.1_f", which outputs something even if a file passed:

 ```$ uncrustify -c uncrustify-riot.cfg --check -f core/include/thread.h 2> /dev/null
Parsing: core/include/thread.h as language C-Header
parse_cleanup(444): pc->orig_line is 545, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(446): (frm.top().type + 1) is UNKNOWN
PASS: core/include/thread.h (17382 bytes)
[kaspar@ng riot.tmp (fix_uncrustify_logic)]$
```

### Testing procedure

Uncrustify a file, commit it, add it to `dist/tools/uncrustify/whitelist.txt`, run ```dist/tools/uncrustify/uncrustify.sh --check`. On master, this fails with my uncrustify version.

### CODE REVIEW

**Comment by kaspar030** [comment]
@jia200x please take a look, this probably prevents any core changes at the moment ...

**Comment by jia200x** [comment]
I'm on it

**Comment by jia200x** [comment]
well, the change makes sense. I'm testing it now

**Comment by jia200x** [comment]
It works. 

<details><summary><b>With this PR:</b></summary>

```
commit 8e8e524af8a05f714648e974aa391e95260b9460 (HEAD -> copr/13974)
Author: Jose Alamos <jose.alamos@haw-hamburg.de>
Date:   Wed Apr 29 10:50:39 2020 +0200

    uncrustify gnrc_ipv6

commit 95142f42b5fdaeb360206df4cf383f82a7148f17
Author: Jose Alamos <jose.alamos@haw-hamburg.de>
Date:   Wed Apr 29 10:50:26 2020 +0200

    add whitelist
```
And
```
git checkout 8e8e524af8a05f714648e974aa391e95260b9460
 ./dist/tools/uncrustify/uncrustify.sh --check        
All files are uncrustified!

git checkout 95142f42b5fdaeb360206df4cf383f82a7148f17
./dist/tools/uncrustify/uncrustify.sh --check
file sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c needs to be uncrustified.
```

</details>

<details><summary><b>Without this PR:</b></summary>

```
commit 71185e14cee792b740ba8de3fa0342de0a48234b (HEAD -> master)
Author: Jose Alamos <jose.alamos@haw-hamburg.de>
Date:   Wed Apr 29 10:50:39 2020 +0200

    uncrustify gnrc_ipv6

commit 2c2add3f1b212e8b61570f1d414bc98d4b75a1d4
Author: Jose Alamos <jose.alamos@haw-hamburg.de>
Date:   Wed Apr 29 10:50:26 2020 +0200

    add whitelist
```
And:

```
git checkout 71185e14cee792b740ba8de3fa0342de0a48234b
./dist/tools/uncrustify/uncrustify.sh --check        
Please run 'dist/tools/uncrustify/uncrustify.sh'

git checkout 2c2add3f1b212e8b61570f1d414bc98d4b75a1d4
./dist/tools/uncrustify/uncrustify.sh --check        
Please run 'dist/tools/uncrustify/uncrustify.sh'
```
</details>

**Comment by kaspar030** [comment]
> Thanks!

Thanks go to you!

**Comment by maribu** [comment]
Hmm, this might still not be the final solution or @fjmolinas is using a different version of uncrustify. He is having a similar issue here: https://github.com/RIOT-OS/RIOT/pull/13999#issuecomment-623888228

**Comment by kaspar030** [comment]
And here: https://github.com/RIOT-OS/RIOT/pull/13975
I assume that this might be a version difference between uncrustify.

**Comment by fjmolinas** [comment]
So what do we do here? This is currently blocking development, can we disable it for now? (or not make it fail)

**Comment by fjmolinas** [comment]
>  I assume that this might be a version difference between uncrustify.

Or what uncrustify version is used on the ci? Because I get the same result when `BUILDING_IN_DOCkER`

**Comment by fjmolinas** [comment]
Or what is the version of `uncrustify` used in travis and murdock? I tried to run it int the docker container, but it is not there.

**Pull request merged**
