### PR TITLE
sys/event: fix of compilation problems

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

Unstructured static initializers of the form { 0 } lead to compilation errors on ESP8266, MSP430 and MIPS platforms. Therefore, the following compilation errors occur when  `EVENT_QUEUE_INIT_DETACHED` is used for initialization of event queues.
```
error: (near initialization for 'queue.event_list') [-Werror=missing-braces]
error: (near initialization for 'queue.waiter') [-Werror=missing-field-initializers]
```
This PR fixes the compilation problem.

### Testing procedure

Compilation of `tests/events` should work on any of the platforms ESP8266, MSP430 or MIPS. Without the change in [`sys/include/event.h`](https://github.com/RIOT-OS/RIOT/blob/9028be5e08857d9e34436fe8370d2bf89d5f0d72/sys/include/event.h#L124) it should not compile for these platforms.

### Issues/PRs references

Required by #10555

### CODE REVIEW

**Comment by miri64** [comment]
@benpicco please provide some reasoning for your ACK and what you did to make sure this does not cause breakage.

I read the PRs description and it makes sense. I also compile tested on `native` but was not able to confirm for the other platforms, as I currently don't have the toolchains installed (I know however that this is an issue e.g. Mac OSX as well). @gschorcht would you mind adding your test application to `tests`, so it can be executed by Murdock?

**Comment by gschorcht** [comment]
@miri64 I tested the compilation for given platforms with riotdocker. The compilation problem doesn't happen for Atmega, ARM, STM32 and native.

Concerning, the test application, it is not a complete test just a C fragment. I thought it is not worth to be added as test application since it has no functionality. Of course, I could add a modified copy of `tests/event`. PR #10555 will bring an test application which requires this change.

**Comment by miri64** [comment]
> @miri64 I tested the compilation for given platforms with riotdocker. The compilation problem doesn't happen for Atmega, ARM, STM32 and native.

I know, that's why I rather would like a test on Murdock, so that the toolchains in question are tested (don't have my usual work setup available atm :-/).



> Concerning the test application, it is not a complete test just a C fragment. I thought it's not worth to be added as test application since it has no functionality.

Every test is worthy if it prevents regression ;-).

**Comment by miri64** [comment]
> PR #10555 will bring an test application which requires this change.

Since my wish for a test is about regression testing and #10555 seems quite large compared to this one (i.e. might take a while to get merged), I think it would be wiser to provide the test for this specific case here or in a separate PR.

> Of course, I could add a modified copy of `tests/event`.

This could make sense

**Comment by gschorcht** [comment]
@miri64 It's much easier than I thought since `events/tests` already contains the definition of a detached event queue but don't uses the static initializer. I simply have to modify the test.

**Comment by gschorcht** [comment]
@miri64 Thanks for reviewing and merging it.

**Pull request merged**
