### PR TITLE
sys/phydat: align numbers, remove index if dim == 1

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Align the printed numbers and only print array index if there is more than one value to print.

Future work: Use fmt instead

### Issues/PRs references

Depends on #8582

### CODE REVIEW

**Comment by miri64** [comment]
ACK, but needs rebase.

**Comment by gebart** [comment]
rebased

**Comment by miri64** [comment]
(But https://github.com/RIOT-OS/RIOT/pull/8582 needs to be merged first)

**Comment by basilfx** [comment]
#8582 is merged.

**Pull request merged**
