### PR TITLE
gnrc_ipv6: fix regression from #8215

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
While `tmp` in the loop for write-protection for the check-sum calculation is used to check the return value of `gnrc_pktbuf_start_write()`, it never overwrites `payload` causing the original snip to be used in the following iteration `prev` when duplicated, and destroying the sanity of `ipv6`. However, since no
release in this function is required anyways, we can just use `payload` to check the return value directly.

### Issues/PRs references
Detected via #9669.

### CODE REVIEW

**Comment by cladmi** [comment]
It removed the segfault in `native` when running `tests/gnrc_netif`.

I am missing background to understand the change. As it is not only a `test` fix I would prefer that someone else reviews the commit message and the changes.

**Comment by miri64** [comment]
>  I would prefer that someone else reviews the commit message and the changes.

@bergzand you reviewed #8215. Want to give it a spin?

**Comment by cladmi** [comment]
It also fixes a hardfault for `iotlab-m3` (I forgot to re-test master before this PR).

**Comment by cladmi** [comment]
Question also, why was it not triggered by other tests, like the integration ones ?

**Comment by miri64** [comment]
> Question also, why was it not triggered by other tests, like the integration ones ?

From https://github.com/RIOT-OS/RIOT/pull/9669#issuecomment-409662172

> The problem is caused, due to IPv6 packets having multiple subscribers due to the gnrc_pktdump subscription in this test. This special edge-case wasn't tested for #8215 and leads to some weird handling in the users setting of the pktsnips, which I currently try to wrap my head around

**Comment by cladmi** [comment]
Thanks, I forgot to cross reference with the original thread.

**Comment by miri64** [comment]
Rebased to current master to include #9675.

**Comment by cladmi** [comment]
@smlng how do you managed to reproduce this bug in another situation ?

**Comment by cladmi** [comment]
Please provide a backport :)

**Comment by miri64** [comment]
Backport provided in #9684.

**Pull request merged**
