### PR TITLE
pkg/nordic-softdevice: remove deprecated package

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR removes the nordic-softdevice package and all related code from the code base. The package is marked as deprecated and its removal is planned for after 2020.10 release, so at any time now that we are in feature freeze.

https://github.com/RIOT-OS/RIOT/blob/76ddfdbbdef0ad0df8a2528381046233a2b6e21a/pkg/nordic_softdevice_ble/doc.txt#L6-L7

### Testing procedure

- A green Murdock
- Ensure no more mentions to the package are present (except in the release notes):

```
$ git grep -i -n softdevice | grep -v release-notes
boards/nrf52840dongle/Makefile.include:11:  # the end, leaving 892k for the application. This overwrites any SoftDevice,
```

I kept the mention to softdevice in `boards/nrf52840dongle/Makefile.include` because I think this is not related to RIOT: the softdevice could have been put there by a previously installed firmware.

### Issues/PRs references

Was marked as deprecated in #14092

### CODE REVIEW

**Comment by miri64** [comment]
I still found some mentions of the softdevice:

```console
$ git log -1 --oneline
03f7904bda (HEAD) tests/l2util: remove mention to nordic-softdevice-ble
$ ls r*    # checking if release-notes.txt is the only thing starting with r
release-notes.txt
$ git grep -i softdevice -- [^r]*   # check all except paths starting with r
boards/common/nrf52/Kconfig:    select HAS_RIOTBOOT if !USEPKG_NORDIC_SOFTDEVICE_BLE
boards/nrf52840dongle/Makefile.include:  # the end, leaving 892k for the application. This overwrites any SoftDevice,
cpu/nrf52/Kconfig:    select HAS_BLE_NORDIC_SOFTDEVICE
cpu/nrf5x_common/Kconfig:config HAS_BLE_NORDIC_SOFTDEVICE
cpu/nrf5x_common/Kconfig:        Indicates that Nordic SoftDevice support in RIOT has been verified on the
cpu/nrf5x_common/periph/hwrng.c:#ifndef MODULE_NORDIC_SOFTDEVICE_BLE
cpu/nrf5x_common/periph/hwrng.c: * The hardware peripheral is used by the SoftDevice. When the SoftDevice is
cpu/nrf5x_common/periph/hwrng.c: * enabled, it shall only be accessed through the SoftDevice API
cpu/nrf5x_common/periph/hwrng.c:#ifndef MODULE_NORDIC_SOFTDEVICE_BLE
cpu/nrf5x_common/periph/hwrng.c:#endif /* MODULE_NORDIC_SOFTDEVICE_BLE */
sys/net/gnrc/netif/gnrc_netif_device_type.c:    defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/gnrc/netif/gnrc_netif_device_type.c:#if defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/gnrc/netif/init_devs/init.c:    if (IS_USED(MODULE_NORDIC_SOFTDEVICE_BLE)) {
sys/net/link_layer/l2util/l2util.c:    defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/link_layer/l2util/l2util.c:           defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF) */
sys/net/link_layer/l2util/l2util.c:#if defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/link_layer/l2util/l2util.c:#endif  /* defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF) */
sys/net/link_layer/l2util/l2util.c:#if defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/link_layer/l2util/l2util.c:#endif  /* defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF) */
sys/net/link_layer/l2util/l2util.c:    defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF)
sys/net/link_layer/l2util/l2util.c:           defined(MODULE_NORDIC_SOFTDEVICE_BLE) || defined(MODULE_NIMBLE_NETIF) */

**Comment by dylad** [comment]
Shouldn't we add an entry to LOSTANDFOUND.md for this ?

**Comment by aabadie** [comment]
> I still found some mentions of the softdevice

Indeed, I adapted the testing procedure. Will remove the remaining mentions.

> Shouldn't we add an entry to LOSTANDFOUND.md for this ?

That's in the plan but should in a follow-up PR since this one contains several removal commits and I prefer to reference a single merge commit in LOSTANDFOUND.md.

**Comment by aabadie** [comment]
Should be good now. Let's see what Murdock thinks of it.

**Comment by miri64** [comment]
What about this one?

https://github.com/RIOT-OS/RIOT/blob/32cf12dcb4c2b637940708cd46f8740b28167f6f/boards/nrf52840dongle/Makefile.include#L7-L12

Not sure though, if @chrysn maybe meant other softdevices.

**Comment by aabadie** [comment]
> What about this one?

I'm not sure either (I edited the OP about that) but it would good if @chrysn could confirm.

**Comment by miri64** [comment]
>  (I edited the OP about that)

The problem with edits :sweat_smile: ...

**Comment by aabadie** [comment]
> The problem with edits

I should have mentioned that in https://github.com/RIOT-OS/RIOT/pull/15326#issuecomment-718041168 ;)

**Comment by chrysn** [comment]
What I meant by the line is "overwrites the SoftDevice if it is present", though thinking back to that PR I think I even adapted it later to just leave the SoftDevice in place. At any rate, I'm only aware of one thing called the SoftDevice, and the nrfutil flashing procedure does not depend on RIOT having any support for it (other than possibly excluding that area from the usable space, which it may or may not do right now but is immaterial to the removal of the nordic-softdevice package).

**Review by miri64 — APPROVED** [review]
In that case I give the current state my ACK. @aabadie please squash.

**Comment by aabadie** [comment]
Let's merge. I'll open another PR to list softdevice removal in LOSTANDFOUND.md.

**Pull request merged**
