### PR TITLE
gnrc_sixlobac: initial import

### PR DESCRIPTION
**Pull request by miri64**
I posted this branch a while back to the mailing list, but did never PR'd it. Now it is here in all its glory! :D

### CODE REVIEW

**Comment by OlegHahm** [comment]
Re-assigned to @thomaseichinger, since he and @haukepetersen wanted to look into this topic.

**Comment by authmillenon** [comment]
:+1:

**Comment by OlegHahm** [comment]
btw. we don't need the ng_ prefix any more, do we?

**Comment by authmillenon** [comment]
Well it would be `gnrc_sixlobac` then. Since the gnrc hierarchy isn't really visible yet, I would prefer to keep it like that for now ;-)

**Comment by OlegHahm** [comment]
Wouldn't it be rather `gnrc/sixlobac`?

**Comment by authmillenon** [comment]
The hierarchy yes, but the module would still be called `gnrc_sixlobac`.

**Comment by authmillenon** [comment]
@thomaseichinger did you use this one for the 6lo plugtest?

**Comment by haukepetersen** [comment]
@authmillenon: Might it be that there are some commits missing here? Where are the actual 6lowbac files?

**Comment by OlegHahm** [comment]
@haukepetersen, I think this PR contains more configuration for 6lo, not the link layer implementation.

**Comment by authmillenon** [comment]
Rebased and adapted to current master. And yes, @OlegHahm is right.

**Comment by authmillenon** [comment]
@thomaseichinger did you use this PR for your implementation or did you do your own thing?

**Comment by OlegHahm** [comment]
@thomaseichinger, ping

**Comment by OlegHahm** [comment]
I don't think this is relevant for the next release.

**Comment by miri64** [comment]
Rebased to current master. Maybe @thomaseichinger and I can discuss this on today's Hack'n'ACK

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by miri64** [comment]
Interest in this seems to be low and @thomaseichinger seems to have another solution for his 6LoBAC implementation, so close.

**Pull request closed without merging**
