### PR TITLE
cpu/gd32v: fix and extend Kconfig clock settings

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the following issus of the clock configuration which led to highly deviating peripheral clocks so that the UART interface was not usable in my case:

1. Setting the `RCU_CTL` register just to the IRC8M bit also removes the IRC8M calibration and trim adjust value in this register. Therefore IRC8M calibration and trim adjust value have to be preserved and the IRC8M has to be set.
2. `CLOCK_HXTAL` is a value and not a flag, so that shifting to the left changes anything in the register but does not set the PLLSEL bit. `RCU_CFG0_PLLSEL_Msk` has to be used instead to set the PLLSEL bit.
3. `CONFIG_BOARD_HAS_HXTAL` is used to indicate that the board has an HXTAL connected. If the HXTAL is present, it is used as PLL clock source. But if the HXTAL is not present, the half IRC8M clock should be used as PLL clock source and must not be disabled at the end of clock settings. Using IRC8M clock as PLL clock source also requires another PLL multiplication factor.

Issues 1 and 2 led to the problem that IRC8M was used without calibration instead of HXTAL. With the fixes, the GD32V is working with as well as without HXTAL correctly.

Furthermore, the Kconfig configuration has been extended. It is now possible to configure the HXTAL frequency as well, since the GD32VF103 allows HXTAL clocks from 3 MHz to 25 MHz. This has currently been added directly to the board's Kconfig, as it is currently the only GD32VF103 board. It should be moved to a common Kconfig later when more GD32V boards are added.

### Testing procedure

`BOARD=seeedstudio-gd32 make -C tests/shell flash term` should still work.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Why the hell failed the Murdock compilation the second time due another unrelated error?

**Comment by gschorcht** [comment]
bors merge

**Comment by benpicco** [comment]
Looks like a Kconfig mismatch

**Comment by gschorcht** [comment]
> Looks like a Kconfig mismatch

What should in this PR cause a Kconfig error?

**Comment by gschorcht** [comment]
> > Looks like a Kconfig mismatch
> 
> What should in this PR cause a Kconfig error?

Ah ok, `CLOCK_HXTAL` needs a type.

**Comment by gschorcht** [comment]
I squashed it directly.

**Comment by benpicco** [comment]
bors merge

**Comment by gschorcht** [comment]
Thanks  for review.

**Pull request merged**
