### PR TITLE
sys: added a single linked list implementation

### PR DESCRIPTION
**Pull request by OlegHahm**
Followed @cgundogan's suggestion from https://github.com/RIOT-OS/RIOT/pull/2294#discussion_r22881937

### CODE REVIEW

**Comment by cgundogan** [comment]
We should investigate if the ulist and slist implementations differ that much enough to have them both in sys

**Comment by OlegHahm** [comment]
Yeah, you're probably right. The only added functionality by slist currently seems to be the `simple_list_add_head()`, basically calling `calloc()`. I'm trying to get rid of it.

**Comment by LudwigOrtmann** [comment]
> I'm trying to get rid of it.

Which "it"? The `calloc` here or the dependency on slist in #2294 ?

**Comment by OlegHahm** [comment]
I meant to get rid of both - but after some thinking I will keep OLSR depending on calloc/free and leave this task for a later point of time.

**Comment by authmillenon** [comment]
I heard this got superceded by `utlist`. Is this correct? If yes: close?

**Comment by OlegHahm** [comment]
Yes, I think so.

(You're well informed, @authmillenon :wink:)

**Pull request closed without merging**
