### PR TITLE
sys/coding: add XOR based coding module

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This implements the XOR based error-correction code described by @jue89 [at the RIOT Summit](https://summit.riot-os.org/2021/wp-content/uploads/sites/16/2021/09/s02-01.pdf).

A parity byte is generated for each 3 payload bytes, then the payload array is transposed by interpreting it as a 2D matrix with height of 3.

This is to reduce the chance of consecutive bytes ending up in the same packet.
With this it is possible to recover one in 3 lost data packets (if parity packets are received).

I'm not sure if the transpose function is ideal for mixing the bytes as it still generates a rather predictable pattern and we can't recover from two consecutive lost packets, but this might require more advanced codes (e.g. [raptor codes](https://github.com/obolo/freeRaptor)).

### Testing procedure

So far only unit tests have been added to `unittests/tests-coding`.
This should be the basis of future work to make firmware updates more reliable / efficient by transmitting parity data along with the payload to recover lost packets without retransmissions.

### CODE REVIEW

**Comment by benpicco** [comment]
Sorry for the long time it took me to reply, I had to think about this for a bit (and then DOSE kept me busy 😉)

Do I get it right that you can reconstruct one in 64 (`CONFIG_MOTA_CHUNK_SIZE`) packets? 
Also how large are `CONFIG_MOTA_DATA_CHUNKS_PER_COL` and `CONFIG_MOTA_COLS_PER_BLOCK`? 

I tried to keep the memory footprint low with my implementation, a drawback however is that I can't recover if two consecutive chunks are lost (I can recover 1 in 4 chunks).

How much RAM do you need for one `mota_block_t`?

**Comment by fjmolinas** [comment]
ping @jue89 :)

**Comment by chrysn** [comment]
There have been [recent chat exchanges](https://matrix.to/#/!pqHdpanAvkJvlCwUDE:matrix.org/$4QAJRZXk-_TNR4LHdg8Q4v8rh_IuNTt8mQRZM-BPbVc?via=matrix.org&via=rubdos.be&via=utwente.io) on how this might look in the big picture of CoAP, so maybe it's not as stale as the bot makes it sound.

**Comment by benpicco** [comment]
Some feedback on the algorithm would be great though, otherwise I would say this is pretty stale.

**Review by maribu — APPROVED** [review]
API looks nice. I didn't really check the mathematics behind the C code, but the unit tests looks assuring that it does what is claimed.

**Comment by benpicco** [comment]
I was hoping @jue89 could chip in if his algorithm is performing any better than mine.
I can only recover one in three packets, so that seems pretty poor. And if 2 consecutive packets are lost, there is only a 33% chance of being able to recover them.

**Comment by maribu** [comment]
I though this is intentionally a less capable but more lightweight alternative to Reed Solomon codes... IMO this is still useful for when rs too large

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
