### PR TITLE
nanocoap_sock: add nanocoap_sock_put()

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Same as `nanocoap_sock_get()`, but for PUT and POST.

### Testing procedure

Run two instances of `tests/nanocoap_cli`, on one do a `server start` and on the other
```
> url get coap://[fe80::581a:98ff:fe23:2d6c]/value
offset 000: 0
> url put coap://[fe80::581a:98ff:fe23:2d6c]/value 23
> url get coap://[fe80::581a:98ff:fe23:2d6c]/value
offset 000: 23
```

### CODE REVIEW

**Review by fabian18 — COMMENTED** [review]
Looks solid and works, analog to `nanocoap_sock_get()`:

```
2022-08-30 11:31:13,662 # server start
2022-08-30 11:31:13,665 # starting server on port 5683
```

```
2022-08-30 11:55:35,297 # url put coap://[fe80::4c49:6f54:4f76:0%6]/value 22

2022-08-30 11:59:46,987 # url get coap://[fe80::4c49:6f54:4f76:0%6]/value
2022-08-30 11:59:47,015 # offset 000: 22
```

The next steps would be `nanocoap_{put | post}_blockwise_url` ?

**Comment by benpicco** [comment]
> The next steps would be `nanocoap_{put | post}_blockwise_url` ?

We've got [`nanocoap_block_request_init_url()`](https://doc.riot-os.org/group__net__nanosock.html#gafe10713c83859bbb1c78d1aa391a7a43) and [`nanocoap_sock_block_request()`](https://doc.riot-os.org/group__net__nanosock.html#gaa9282335cdd7d0bb39bcd4d48fab1517) for that

**Comment by fabian18** [comment]
But blockwise PUT / POST is not intended for the simple `/value` resource, so it is reasonable to use `nanocoap_sock_post() / _put()`, over `nanocoap_block_request_init_url()` and `nanocoap_sock_block_request()`?

**Comment by benpicco** [comment]
It's a more convenient API for simple PUT/POST when no block-wise is needed.

**Review by fabian18 — APPROVED** [review]
> It's a more convenient API for simple PUT/POST when no block-wise is needed.

Ok, ACK

**Comment by benpicco** [comment]
Thank you for the quick review!

**Pull request merged**
