### PR TITLE
conn: fix UDP port byteorder in recvfrom

### PR DESCRIPTION
**Pull request by OlegHahm**
Additionally cleans up some superfluous functions.

### CODE REVIEW

**Comment by authmillenon** [comment]
Can you run the conn_ip test please? I'm not so sure these functions are superfluous.

**Comment by OlegHahm** [comment]
> Can you run the conn_ip test please? 

Verified.

**Comment by PeterKietzmann** [comment]
Shouldn't that also be fixed for the release branch?

**Comment by OlegHahm** [comment]
Yes, you're absolutely right. Can you set the label, please? I don't have access to Github right now.

On 23 November 2015 08:42:57 CET, Peter Kietzmann <notifications@github.com> wrote:
>Shouldn't that also be fixed for the release branch?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RIOT-OS/RIOT/pull/4324#issuecomment-158870974

-- 
Join the RIOT
http://www.riot-os.org

**Comment by kaspar030** [comment]
Confirmed working with the (adapted) microcoap example in #4287. ACK.

**Pull request merged**
