### PR TITLE
tools: install pexpect from Ubuntu repo

### PR DESCRIPTION
**Pull request by OlegHahm**
Let's see if this fixes strange Travis problems.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Travis is failing for e.g. #4389 and #4394 because of unrelated Travis problem. With this "fix" the x86 tests seems to work again.

**Comment by gebart** [comment]
I don't understand why Travis skipped the pip install line, but if this fixes the problem then I'm OK with it.
Do you know what the problem was with the old version in the ubuntu repo? Why was the comment about the package being erroneous there to begin with?

**Comment by OlegHahm** [comment]
I'm investigating: https://github.com/RIOT-OS/RIOT/pull/3309#issuecomment-189745698 ;)

Yes, I don't understand the problem either, but if the "normal" Ubuntu package does the trick, it should be the preferred solution anyways.

**Comment by gebart** [comment]
we can probably remove the python-pip package from the pkg list script too (it was added in #3309 as well)

**Comment by OlegHahm** [comment]
addressed

**Comment by gebart** [comment]
ACK, please squash

**Comment by OlegHahm** [comment]
squashed

**Comment by authmillenon** [comment]
The Ubuntu version has a bug that won't kill subprocesses on termination properly.

**Comment by OlegHahm** [comment]
Do you know if this bug is still present?

**Comment by OlegHahm** [comment]
I'm confused. After the latest changes it doesn't find the pexpect module anymore.

**Comment by OlegHahm** [comment]
Gonna try with python-pexpect instead of python3-pexpect.

**Comment by OlegHahm** [comment]
I'm completely puzzled:
```
./tests/01-run.py

Exception AttributeError: "'spawn' object has no attribute 'closed'" in <bound method spawn.__del__ of <pexpect.spawn object at 0x2b292cdccbd0>> ignored

Traceback (most recent call last):

  File "./tests/01-run.py", line 38, in <module>

    sys.exit(main())

  File "./tests/01-run.py", line 17, in main

    encoding="utf-8")

TypeError: __init__() got an unexpected keyword argument 'encoding'

make: *** [test] Error 1

make: Leaving directory `/home/travis/build/RIOT-OS/RIOT/tests/unittests'
```

**Comment by authmillenon** [comment]
Ah right the older version of pexpect doesn't support this either. There was a major API shift between v3.3 (ubuntu version) and v4.0 (pip version) so yes: The problem does persist. What is the problem with the pip version again?

**Comment by OlegHahm** [comment]
I'm not sure: see https://travis-ci.org/RIOT-OS/RIOT/jobs/104574521

**Comment by authmillenon** [comment]
This PR simply needs a rebase to include the most current .travis.yml at travis boot-up.

**Pull request closed without merging**
