### PR TITLE
make: export VALGRIND_PID only for debug-valgrind

### LINKED ISSUE #4987: native: pgrep: option requires an argument -- 'u'
`make buildtest` shows the following message when building for native:

```
Building for native .. success
pgrep: option requires an argument -- 'u'

Usage:
 pgrep [options] <pattern>

Options:
 -d, --delimiter <string>  specify output delimiter
 -l, --list-name           list PID and process name
 -a, --list-full           list PID and full command line
 -v, --inverse             negates the matching
 -w, --lightweight         list all TID
 -c, --count               count of matching processes
 -f, --full                use full process name to match
 -g, --pgroup <PGID,...>   match listed process group IDs
 -G, --group <GID,...>     match real group IDs
 -i, --ignore-case         match case insensitively
 -n, --newest              select most recently started
 -o, --oldest              select least recently started
 -P, --parent <PPID,...>   match only child processes of the given parent
 -s, --session <SID,...>   match session IDs
 -t, --terminal <tty,...>  match by controlling terminal
 -u, --euid <ID,...>       match by effective IDs
 -U, --uid <ID,...>        match by real IDs
 -x, --exact               match exactly with the command name
 -F, --pidfile <file>      read PIDs from file
 -L, --logpidfile          fail if PID file is not locked
 --ns <PID>                match the processes that belong to the same
                           namespace as <pid>
 --nslist <ns,...>         list which namespaces will be considered for
                           the --ns option.
                           Available namespaces: ipc, mnt, net, pid, user, uts

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see pgrep(1).
```

### PR DESCRIPTION
**Pull request by OlegHahm**
Not very pretty, but should fix #4987.

### CODE REVIEW

**Comment by cgundogan** [comment]
I was working on the same currently (; Looks exactly to what I did, but I went further and transformed all of them, not only `debug-valgrind`. Somehow I was unable to transform `term-gprof` because it has a dependency on `term` .. so I will just drop the work now.

ACK!

**Comment by cgundogan** [comment]
Do you want to update the other targets also? Maybe this can speed up things, because it appears to me that make executes the exports when looking for the specified goal.

**Comment by OlegHahm** [comment]
No, I didn't work on the other targets. Please feel free to open another PR.

**Comment by cgundogan** [comment]
double green. GO

**Pull request merged**
