### PR TITLE
header file include guards repaired

### PR DESCRIPTION
**Pull request by rajma996**
pull request created as per the issue https://github.com/RIOT-OS/RIOT/issues/2623 
please notify if any further changes required... :)

### CODE REVIEW

**Comment by cgundogan** [comment]
@rajma996 thank you very much for this effort. In order to make the reviewing a little bit simpler, could you split this giant commit into separate commits? E.g. all changes within the boards directory could be in a single commit prefixed with `boards: header file include guards repaired` All changes within the cpu folder `cpu: header file include guards repaired` and all changes within the sys folder `sys: header file include guards repaired`.

**Comment by gebart** [comment]
A few problems, please read #2623 again, carefully.

 - This is too big to review, please split into multiple PRs each containing one or a few updated subdirectories. In my opinion, keep it less than 20 files to make the review go smooth and easy.
 - Only header include guards should be changed.
    - Symbols such as `__FPU_PRESENT`, `__MSP430F1612__` etc. configure the system headers and must not be touched
    - `__APPLE__`, `__ARM_CC` etc. are compiler checks which must not be touched either
 - Header include guards with double underscores within the name should also be updated when removing any leading underscores, e.g. `__X86__PCI_INIT__H` could be changed to `X86_PCI_INIT_H`

Using a script to do small fixes to many files is fine, but you still need to manually review the changes and make sure the script didn't mess anything up.

#2623:
>Git grep tells me there are a lot of files that need to be adjusted. **So if anyone is taking this on, please do it in small, easily reviewable and logical grouped chunks...**

**Comment by BytesGalore** [comment]
@rajma996 do yo plan to use this PR for the changes in `sys/`, since it has been opened before #4626 and contains `board/cpu` changes?

**Comment by OlegHahm** [comment]
@rajma996, ping!

**Comment by rajma996** [comment]
@BytesGalore this PR was made initially for making all changes, but as separate commits were required for each directory, I made a new PR ( [4626](https://github.com/RIOT-OS/RIOT/pull/4626) ) leaving this one.. :(

**Comment by rajma996** [comment]
@OlegHahm I have been working on [4626](https://github.com/RIOT-OS/RIOT/pull/4626). Sorry for the delay..

**Comment by OlegHahm** [comment]
Thanks for the info. Then let's close this one.

**Pull request closed without merging**
