### PR TITLE
cpu/samr30: update vendor files using ASF 3.35.1

### PR DESCRIPTION
**Pull request by keestux**
The recent addition of SAMR30 vendor files were from ASF 3.34.2. This PR will update
the SAMR21 files using ASF 3.35.1

The difference looks bigger than it really is. There is one actual change between 3.34.2 and 3.35.1 and that is

```
-typedef volatile       uint32_t WoReg8;  /**< Write only  8-bit register (volatile unsigned int) */
+typedef volatile       uint8_t  WoReg8;  /**< Write only  8-bit register (volatile unsigned int) */
```

The rest is:

1. reverting the white space changes that were done in the initial support
2. reverting the removal of `LITTLE_ENDIAN` define (it's taken care of in `sam0.h`
3. removal of the `README.md` in the `samr30` subdirectory

Notice that it's untested since I don't have a SAMR30. But it looks Obviously Correct :-).

### CODE REVIEW

**Comment by aabadie** [comment]
The IoT-LAB site of Saclay provide 2 of these boards (samr30-1 is broken but not samr30-2 and samr30-3). You can easily try remotely on a running experiment and by using `IOTLAB_NODE=auto-ssh` in the RIOT make command:
```
$ iotlab-experiment submit -n samr30 -d 60 -l saclay,samr30,2
$ iotlab-experiment wait     # it takes a few seconds before the board is ready
$ make BOARD=samr30-xpro IOTLAB_NODE=auto-ssh -C tests/shell flash test
```

**Comment by dylad** [comment]
@aabadie 
I tried your commands on iotlab SSH frontend but I got this:
```
ladurant@saclay:~/RIOT$ make BOARD=samr30-xpro IOTLAB_NODE=auto-ssh -C tests/shell flash test
make: Entering directory '/senslab/users/ladurant/RIOT/tests/shell'
Traceback (most recent call last):
  File "/usr/local/bin/iotlab-experiment", line 23, in <module>
    iotlabcli.parser.experiment.main()
  File "/usr/local/lib/python2.7/dist-packages/iotlabcli/parser/experiment.py", line 777, in main
    common.main_cli(experiment_parse_and_run, parser, args)
  File "/usr/local/lib/python2.7/dist-packages/iotlabcli/parser/common.py", line 171, in main_cli
    print_result(result, parser_opts.jmespath, parser_opts.format)
  File "/usr/local/lib/python2.7/dist-packages/iotlabcli/parser/common.py", line 128, in print_result
    formatted = format_function(result)
TypeError: can only join an iterable
/senslab/users/ladurant/RIOT/dist/testbed-support/makefile.iotlab.single.inc.mk:110: *** Could not automatically find a node for BOARD=samr30-xpro. Arrêt.
make: Leaving directory '/senslab/users/ladurant/RIOT/tests/shell'
```

Do you know what's wrong ?

**Comment by aabadie** [comment]
> Do you know what's wrong ?

I saw your experiment on IoT-LAB. There's a problem with the samr30-xpro on the testbed. I'll have a look but the last time I checked the boards were somehow bricked.

**Comment by dylad** [comment]
> I'll have a look but the last time I checked the boards were somehow bricked.

It's a shame... I'll try to have a look at them next time at Saclay if you want.

**Comment by aabadie** [comment]
> I'll try to have a look at them next time at Saclay if you want.

If you know how to revive them, that would be awesome! (Note that I tried multiple things already and none worked...)

**Comment by dylad** [comment]
I'll give it a try for the sake of this PR.

**Comment by dylad** [comment]
@aabadie Now that your SAMR30 are back to life, do you mind give this PR a quick look please ?

**Comment by aabadie** [comment]
> do you mind give this PR a quick look please ?

yep, rerunning the test suite on one board. Results will arrive in a couple of hours.

**Comment by aabadie** [comment]
Tests report:
```
Failures during test:
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed)
- [tests/gnrc_ipv6_ext_frag](tests/gnrc_ipv6_ext_frag/test.failed)
- [tests/gnrc_rpl_srh](tests/gnrc_rpl_srh/test.failed)
- [tests/gnrc_sock_dns](tests/gnrc_sock_dns/test.failed)
- [tests/pkg_ubasic](tests/pkg_ubasic/test.failed)
```

`gnrc_*`  are related to the missing scapy dependency. `tests/pkg_ubasic` works but fails because of a timeout in the test script.

In other words, this PR works on samr30-xpro.

**Comment by aabadie** [comment]
Rerunning Murdock on latest master, just in case.

**Comment by aabadie** [comment]
All green, go!

**Pull request merged**
