### PR TITLE
cpu/sam0_common: merge GPIO driver

### PR DESCRIPTION
**Pull request by dylad**
I pursuit my effort to merge samd21 & saml21 drivers together.
Both files were almost the same. 
I just move EXTI lines definitions to `cpu/sam0_common/include/periph_cpu_common.h` instead of `cpu/samx21/periph/gpio.c` because this is where they should belong IMHO. (Maybe I'm wrong ?)
What do you think ?
Tested on `saml21-xpro` with `tests/periph_gpio `(2 EXTI + 2 GPIO out). Everything was fine but I'll need help for testing on a samd21 based board.
Cheers.

### CODE REVIEW

**Comment by aabadie** [comment]
Tested on Arduino Zero, I could make on-board LED blink using SAUL and `default` application. Please rebase on latest master so that the shell works !

**Comment by dylad** [comment]
@aabadie I rebased this PR as you wanted.
Could you also confirme nothing is broken with EXTI please ?

**Comment by aabadie** [comment]
> Could you also confirme nothing is broken with EXTI please ?

I'll try to test this today.

**Comment by aabadie** [comment]
@dylad, I tested some networking with samr21-xpro (with EXTI inside) and it's broken with this PR. I have no idea why.

**Comment by dylad** [comment]
@aabadie Good to know. I'll investigate tonight & submit a fix (if I find what's wrong)

**Comment by aabadie** [comment]
@dylad, looking at your changes you seem to have mixed a bit the order of the different initialization steps for the samd21. That's probably the reason of my failing test.

**Comment by dylad** [comment]
Yes I wanted to avoid as much #ifdef as I can.
Seems It was not the best idea I had...

**Comment by dylad** [comment]
@aabadie I've arranged the calls order. EXTI should work now.
I'll retry on my `saml21-xpro` tomorrow and share results :)

**Comment by photonthunder** [comment]
@dylad tried this on my samd21 board and it appears to work.  One note is that for EXTI the code calls for generic clock 2 which is either the ultra low power internal or external 32 kHz if you use RTC/RTT.  It should work either way but there probably should be a comment or something indicating the choice.  If I can get some traction, PR #7315 does attempt to organize these generic clock calls.

**Comment by dylad** [comment]
@photonthunder Thanks for testing, I'll add a comment regarding the generic clock. I'm sure we can optimize a bit more this PR but I'll wait to have the required hardware to do so. I'll also work on an extension to #7315 for SAML21 whenever I find some time :)

Note: I re-tested this PR on saml21-xpro -> works like a charm

**Comment by dylad** [comment]
@aabadie Squashed.

**Pull request merged**
