### PR TITLE
boards/arduino-mega2560: add support to flash it on mac osx

### PR DESCRIPTION
**Pull request by kYc0o**
A wiki page with the procedure should be created (I can create it)

### CODE REVIEW

**Comment by kYc0o** [comment]
To install avr-gcc:

```make
brew install avr-libc
```

it takes a while...

to install avrdude:

```make
brew install avrdude --with-usb
```

**Comment by emmanuelsearch** [comment]
Tested. Works, after yet another driver issue for the USB serial on El Capitan (what a fuck-up from Apple on this version of OS X for that matter!!!)

**Comment by emmanuelsearch** [comment]
ACK

**Comment by haukepetersen** [comment]
and go

**Pull request merged**
