### PR TITLE
doc: add Docker info to doxygen

### PR DESCRIPTION
**Pull request by bergzand**
### Contribution description

This PR migrates the docker info from the wiki to doxygen.

### Testing procedure

Read the new doxygen page.

### Issues/PRs references

None

### CODE REVIEW

**Comment by aabadie** [comment]
There's a trailing whitespace reported by Travis: https://travis-ci.org/github/RIOT-OS/RIOT/builds/740169630#L158

**Comment by aabadie** [comment]
I don't like the how the Docker is integrated in the documentation: it shows at the root of the documentation structure (which is already a mess, but let's not add even more mess). I would rather integrate in the `Getting Started/Compiling RIOT` page (see [here](http://doc.riot-os.org/getting-started.html#setting-up-a-toolchain)).

image

**Comment by fjmolinas** [comment]
Ping @bergzand!

**Comment by bergzand** [comment]
> I would rather integrate in the `Getting Started/Compiling RIOT` page

Is my latest push a bit like what you had in mind?

**Comment by aabadie** [comment]
> Is my latest push a bit like what you had in mind?

Yes that looks better. Please squash!

**Comment by bergzand** [comment]
Squashed!

**Comment by aabadie** [comment]
Seems that there are some problems with the static tests. Can you have a look ?

**Comment by bergzand** [comment]
> Seems that there are some problems with the static tests. Can you have a look ?

Amended some minor fixes in. Should be good now, but lets see what the CI thinks :)

**Review by aabadie — APPROVED** [review]
CI is happy and the [generated documentation](https://5068-7370241-gh.circle-artifacts.com/0/doc/getting-started.html#docker) looks good.

ACK

**Pull request merged**
