### PR TITLE
boards/cc2538: use FLASHFILE for boards using cc2538-bsl.py

### PR DESCRIPTION
**Pull request by cladmi**
### Contribution description

Update to use FLASHFILE as file to be flashed on the board.

This also removes `OFLAGS` that is set by `Makefile.include` in the `.bin` and `.hex` rules.

### Testing procedure

Flash on a board using the `cc2538-bsl.py` and also by connecting a `jlink` to flash it with `PROGRAMMER=jlink`.

(I do not have any at the moment)

### Testing without a board

```
CC2538_BOARDS=$(git grep -e cc2538-bsl.py -e 'common/remote/Makefile.include' | grep -v 'boards/common' | cut -f 2 -d/)
echo ${CC2538_BOARDS} 
cc2538dk firefly openmote-b openmote-cc2538 remote-pa remote-reva remote-revb
```

The output of the `FFLAGS` is the same on `master` and this `PR` with the default and `jlink` programmer

#### cc2538

<details><summary><code>for board in ${CC2538_BOARDS}; do echo ${board}; BOARD=${board} make -C examples/hello-world --no-print-directory flash-only FLASHER=true PORT=none; done</code></summary><p>

```
for board in ${CC2538_BOARDS}; do echo ${board}; BOARD=${board} make -C examples/hello-world --no-print-directory flash-only FLASHER=true PORT=none; done
cc2538dk
true -p "none" -e -w -v /home/harter/work/git/RIOT/examples/hello-world/bin/cc2538dk/hello-world.bin
firefly
true -p "/dev/ttyUSB0" -e -w -v -b 115200 /home/harter/work/git/RIOT/examples/hello-world/bin/firefly/hello-world.bin
openmote-b
true -p "/dev/ttyUSB1" --bootloader-invert-lines -e -w -v -b 460800 /home/harter/work/git/RIOT/examples/hello-world/bin/openmote-b/hello-world.bin
openmote-cc2538
true -p "none" -e -w -v -b 460800 /home/harter/work/git/RIOT/examples/hello-world/bin/openmote-cc2538/hello-world.bin
remote-pa
true -p "/dev/ttyUSB1" -e -w -v -b 115200 /home/harter/work/git/RIOT/examples/hello-world/bin/remote-pa/hello-world.bin
remote-reva
true -p "/dev/ttyUSB0" -e -w -v -b 115200 /home/harter/work/git/RIOT/examples/hello-world/bin/remote-reva/hello-world.bin
remote-revb
true -p "/dev/ttyUSB0" -e -w -v -b 115200 /home/harter/work/git/RIOT/examples/hello-world/bin/remote-revb/hello-world.bin
```

</p></details>

### Jlink

<details><summary><code>for board in ${CC2538_BOARDS}; do echo ${board}; BOARD=${board} PROGRAMMER=jlink make -C examples/hello-world --no-print-directory flash-only FLASHER=true PORT=none; done</code></summary></p>

```
for board in ${CC2538_BOARDS}; do echo ${board}; BOARD=${board} PROGRAMMER=jlink make -C examples/hello-world --no-print-directory flash-only FLASHER=true PORT=none; done
cc2538dk
true /home/harter/work/git/RIOT/examples/hello-world/bin/cc2538dk /home/harter/work/git/RIOT/examples/hello-world/bin/cc2538dk/hello-world.bin
firefly
true /home/harter/work/git/RIOT/examples/hello-world/bin/firefly /home/harter/work/git/RIOT/examples/hello-world/bin/firefly/hello-world.bin
openmote-b
true /home/harter/work/git/RIOT/examples/hello-world/bin/openmote-b /home/harter/work/git/RIOT/examples/hello-world/bin/openmote-b/hello-world.bin
openmote-cc2538
true flash /home/harter/work/git/RIOT/examples/hello-world/bin/openmote-cc2538/hello-world.bin
remote-pa
true /home/harter/work/git/RIOT/examples/hello-world/bin/remote-pa /home/harter/work/git/RIOT/examples/hello-world/bin/remote-pa/hello-world.bin
remote-reva
true /home/harter/work/git/RIOT/examples/hello-world/bin/remote-reva /home/harter/work/git/RIOT/examples/hello-world/bin/remote-reva/hello-world.bin
remote-revb
true /home/harter/work/git/RIOT/examples/hello-world/bin/remote-revb /home/harter/work/git/RIOT/examples/hello-world/bin/remote-revb/hello-world.bin
```

</p></details>

### Issues/PRs references

Part of https://github.com/RIOT-OS/RIOT/pull/8838

### CODE REVIEW

**Comment by cladmi** [comment]
Thank you for the review!

**Comment by PeterKietzmann** [comment]
Did this PR interfere with/ or fix #9851?

**Comment by cladmi** [comment]
@PeterKietzmann 

This indeed require to apply the same changes to the pull request.
But does not fix #9851 

I can take over the removal of the `dist/tools/flash|reset.sh` scripts for the boards that uses Jlink with a separate script.
I would however prefer doing it after https://github.com/RIOT-OS/RIOT/pull/11554 as it modifies many common lines.

**Comment by PeterKietzmann** [comment]
That would be cool! No objections waiting for #11554

**Comment by cladmi** [comment]
It's merged, now I need to work, damn :D

**Pull request merged**
