### PR TITLE
tests/gnrc_rpl_srh: fix test assumption

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
If the destination address or an address within the source route is multicast within a RPL source routing header, a receiving node is supposed to just discard the packets, but not to send an ICMPv6 error message, as the test assumes at the moment.

Source: https://tools.ietf.org/html/rfc6554#section-4.2

There is also a fix that prevents the implementation from sending such an error message: If we leave the `err_ptr` unset in these cases, the [node will not send an error message][err_ptr set].

[err_ptr set]: https://github.com/RIOT-OS/RIOT/blob/9bc600a/sys/net/gnrc/network_layer/ipv6/ext/rh/gnrc_ipv6_ext_rh.c#L100-L105

### Testing procedure
Read the algorithm provided above, especially the section regarding multicast:

         if Address[i] or the IPv6 Destination Address is multicast {
            discard the packet
         }

The test cases that check multicast addresses in `tests/gnrc_rpl_srh` should now pass (the test in general does not pass completely (but will, when #12442 is merged).

### Issues/PRs references
Fixes one of the issues in https://github.com/RIOT-OS/RIOT/issues/12436
Accompanies #12442

### CODE REVIEW

**Comment by miri64** [comment]
> The test cases that check multicast addresses in `tests/gnrc_rpl_srh` should now pass (the test in general does not pass completely (see [#12436 (comment)](https://github.com/RIOT-OS/RIOT/issues/12436#issuecomment-541551192), I will provide a separate fix for that).

See #12442 for that.

**Comment by miri64** [comment]
> However, what is the reasoning behind modifying the test to include UDP headers in the test packets? At first sight, the change to UDP appears unrelated to the fix, but there's probably something behind that? Though, I cannot find any hint neither in the code doc, nor in the commit message.

Mainly to check if _something_ is forwarded (in the error case). The routing header and the IPv6 header both change so they are no guaranteed point of reference. The added UDP header provides that with the (randomly selected) destination port.

**Comment by miri64** [comment]
Isn't using a User Port just as valid? The dynamic range is mainly for ephemeral ports. As this is a "fantasy application" using 2602 as _specific_ port might be just as valid. Especially since I don't bind the port (neither on the node nor the host), there should be no worries about using that port.

**Comment by miri64** [comment]
(fun fact: `scapy` uses port 53 for UDP as default ;-))

**Comment by miri64** [comment]
Or do you want me to change it because of that so the DNS "reply" is to an ephemeral port?

**Comment by miri64** [comment]
> Or do you want me to change it because of that so the DNS "reply" is to an ephemeral port?

If yes, I still disagree with changing since specifically for testing it is important to send unexpectedly formatted or valued packets ;-).

**Comment by cgundogan** [comment]
Alright, was just a suggestion (: GO

**Comment by miri64** [comment]
Backport provided in #12443

**Pull request merged**
