### PR TITLE
sixlowpan_sfr: initial import Selective Fragment Recovery definitions

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This provides a helper header to parse and set the headers defined in https://tools.ietf.org/html/draft-ietf-6lo-fragment-recovery-05#section-5.

### Testing procedure
I provided unittests for this helper header:

```sh
BOARD="<your choice>" make -C tests/unittests/ tests-sixlowpan_sfr flash-only test
```

### Issues/PRs references
None

### CODE REVIEW

**Comment by benpicco** [comment]
The headers look good and Murdock will soon confirm that all the tests are running ;)

But does it make sense to merge this before there is any code that makes use of this?

**Comment by miri64** [comment]
> But does it make sense to merge this before there is any code that makes use of this?

Will be coming in in the coming weeks. It would greatly reduce some rebasing hassle if it were merged (same goes for #12220 ;-))

**Comment by benpicco** [comment]
I understand the reasoning that keeping PRs small would speed up the review process.
But I think interdependent PRs slow things down even more.

I review PRs one commit after the other, so that's already reasonable chunks.

**Comment by miri64** [comment]
On one hand, many reviewers (myself included) seem to prefer smaller updates as larger PRs just feel overwhelming. On the other, I prefer to get my code published and reviewed fast, so kinks can be ironed out, while I'm still working on follow-ups (which to my understanding are seperate units so should be separate PRs)

**Comment by miri64** [comment]
Also, in this specific instance the feature is expected to be quite large (think IPv6 fragmentation + reassembly + a lot more extra) so I rather go small logically divided steps.

**Comment by miri64** [comment]
Added a check to generically check if the header is any of the two SFR headers.

**Comment by miri64** [comment]
Squashed.

**Pull request merged**
