### PR TITLE
 tests: introduce dedicated `gnrc_rpl_srh` test

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This introduces a dedicated test application for GNRC's RPL source router header implementation. It utilizes `scapy` for the generation of the routing headers. It also moves the unittests from the unittests application into this application.

### Testing procedure
Compile `tests/gnrc_rpl_srh` and flash it to a board of your choice. Use `sudo make test` to run (due to the required Ethernet frame construction with the tap interface you need root permissions). The tests might hang and fail due to `scapy`'s sniffer sometimes not picking up the expected packet. Maybe someone can help me with syncing the main thread and the sniffer thread of the python script here?

### Issues/PRs references
Depends on #10242, #10244, and ~~#10300~~(merged) and their dependencies:

PR dependencies

Addresses #8941 partly.

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master and dependencies.

**Comment by miri64** [comment]
Rebased to and tested for current master and dependencies.

**Comment by miri64** [comment]
Rebased to current master and dependencies.

**Comment by miri64** [comment]
Rebased to current master and dependencies.

**Comment by miri64** [comment]
Rebased to current master and dependencies

**Comment by jia200x** [comment]
Same as #10382. Please rebase so I can continue with this one

**Comment by miri64** [comment]
Rebased to current master

**Comment by miri64** [comment]
No longer waiting for any other PRs.

**Comment by miri64** [comment]
Fixed some formatting errors pointed out by `flake8`

**Comment by jia200x** [comment]
proposed tests make sense

**Comment by jia200x** [comment]
```
archlinux% sudo make BOARD=samr21-xpro test
..............SUCCESS
```
:tada:

**Comment by jia200x** [comment]
native also works ok

**Comment by jia200x** [comment]
flake8 output:
```
17:23: E126 continuation line over-indented for hanging indent
31:3: E121 continuation line under-indented for hanging indent
88:13: E126 continuation line over-indented for hanging indent
91:9: E121 continuation line under-indented for hanging indent
97:13: E126 continuation line over-indented for hanging indent
100:9: E121 continuation line under-indented for hanging indent
103:17: E126 continuation line over-indented for hanging indent
103:80: E501 line too long (80 > 79 characters)
104:13: E121 continuation line under-indented for hanging indent
111:13: E126 continuation line over-indented for hanging indent
114:9: E121 continuation line under-indented for hanging indent
117:17: E126 continuation line over-indented for hanging indent
118:13: E121 continuation line under-indented for hanging indent
130:13: E126 continuation line over-indented for hanging indent
177:80: E501 line too long (84 > 79 characters)
190:80: E501 line too long (84 > 79 characters)
206:80: E501 line too long (84 > 79 characters)
207:80: E501 line too long (80 > 79 characters)
218:80: E501 line too long (84 > 79 characters)
219:80: E501 line too long (81 > 79 characters)
234:80: E501 line too long (92 > 79 characters)
235:43: E226 missing whitespace around arithmetic operator
235:45: E226 missing whitespace around arithmetic operator
235:80: E501 line too long (81 > 79 characters)
267:80: E501 line too long (80 > 79 characters)
311:13: E126 continuation line over-indented for hanging indent
312:9: E121 continuation line under-indented for hanging indent
333:80: E501 line too long (84 > 79 characters)
```

**Comment by miri64** [comment]
@jia200x are you sure you are on the most recent version of the branch? I fixed this quite recently and when I run `flake8` I only get E501:

```
$ flake8 tests/gnrc_rpl_srh/tests/01-run.py 
tests/gnrc_rpl_srh/tests/01-run.py:103:80: E501 line too long (80 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:177:80: E501 line too long (84 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:190:80: E501 line too long (84 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:206:80: E501 line too long (84 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:207:80: E501 line too long (80 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:218:80: E501 line too long (84 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:219:80: E501 line too long (81 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:234:80: E501 line too long (92 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:235:80: E501 line too long (81 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:267:80: E501 line too long (80 > 79 characters)
tests/gnrc_rpl_srh/tests/01-run.py:333:80: E501 line too long (84 > 79 characters)
```

(also neither Murdock nor Travis are reporting any `flake8` issues.

**Comment by jia200x** [comment]
you are right, I used an old version. Sorry

**Comment by miri64** [comment]
I guess you need to redo testing then as well (sorry removed the other labels accidentally)

**Comment by jia200x** [comment]
> I guess you need to redo testing then as well (sorry removed the other labels accidentally)

Yes, I'm already into that

**Comment by jia200x** [comment]
re-tested. Everything OK

**Comment by jia200x** [comment]
(I reviewed the last commit, so 4-Code-style stays there ;)

**Comment by jia200x** [comment]
I don't see any issues with the documentation

**Comment by jia200x** [comment]
@miri64 could you squash?

**Comment by miri64** [comment]
Squashed

**Comment by miri64** [comment]
Murdock and Travis are happy.

**Comment by jia200x** [comment]
So this completes the GNRC IPv6 refactor. Congratz :tada:

GO

**Comment by miri64** [comment]
Thank you @jia200x for all the review work for this project!

**Comment by jia200x** [comment]
no problem! thanks for all the work :)

**Pull request merged**
