### PR TITLE
Boards/Generic support for the ATSAMR21G18-MR210UA module

### PR DESCRIPTION
**Pull request by mxgxw**
### Contribution description
This commit adds initial support for the [ATSAMR21 Breakout Board](http://hackerspace.teubi.co/wiki/index.php?title=HSSV_ATSAMR21_Breakout_English) from [Hackerspace San Salvador](http://hackerspace.teubi.co/).

The initial support includes:
- Board definition for the [ATSAMR21G18-MR210UA module](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42475-ATSAMR21G18-MR210UA_Datasheet.pdf)
- Patch for using bossac to load RIOT to the board via USB.
- Support for antenna diversity

Features not included yet:
- Support for using the embedded MAC address
- Drivers for the included 4Mb flash memory
- Drivers for the crypto-auth chip
- USB-CDC support to remove the requirement of an external USB-Serial converter

Design files for this board are available over: [https://github.com/hackerspacesv/RIOT-hardware](https://github.com/hackerspacesv/RIOT-hardware)

**Note:** This is an OSHW board, we would like to have support for RIOT before releasing the first production batch. However we have the initial testing batch and we can provide a couple of them to the RIOT community for testing purposes. We also think that other ports using the ATSAMR21 could benefit from this board definition as an example.

### Bootloader info
This board supports the Arduino MRK1000 bootloader without any troubles. However we recommend to use our port. The port uses our reserved [VID/PID USB identifiers](http://pid.codes/1209/053A/) from [pid.codes](http://pid.codes/).

Procedure:
Clone our ArduinoCore-samd port:
`git clone https://github.com/hackerspacesv/ArduinoCore-samd`

You can find the pre-compiled bootloader under the directory:
`cd ArduinoCore-samd/bootloaders/HSSV_SAMR21_Mote`

'Burn' the bootloader using your preffered JTAG programmer. Bin/hex files are available under the following names:
`samr21_sam_ba_HSSV_SAMR21_Mote.bin`
`samr21_sam_ba_HSSV_SAMR21_Mote.hex`

### Testing procedure
Clone the RIOT repository from Hackerspace San Salvador with the following command: 
`git clone https://github.com/hackerspacesv/RIOT`

Change to the network examples directory:
`cd RIOT/examples/gnrc_networking`

Compile the example specifying the breakout board:
`make BOARD=hssv-atsamr21-breakout`

Execute the following command to flash the board:
`make flash BOARD=hssv-atsamr21-breakout`

Connect an external USB-Serial bridge and open a terminal client with the following command (We assume minicom and the serial device /dev/ttyUSB0):
`minicom -b 115200 -D /dev/ttyUSB0`

If you press the reset button you'll see a message as the following:
> main(): This is RIOT! (...)
> RIOT Network stack example application
> All up, running the shell now
> >

### Issues/PRs references
N/A

### CODE REVIEW

**Comment by kYc0o** [comment]
Hi @mxgxw ! Thanks for your contribution! Is there a way to get the board already assembled?

**Comment by mxgxw** [comment]
Hi @kYc0o! Please send us your address to [info@teubi.co](mailto:info@teubi.co)! We will send you a couple of boards via EMS it will take between 7-10 days depending on were are you located.

**Comment by benpicco** [comment]
Sorry for dropping out on this one. But it seems like the board is in active use by your community?
Can you please rebase this on top of master, so it only includes your commits.

**Comment by mxgxw** [comment]
Hi @benpicco ! Thanks for taking a look on this. We developed this board a year ago when no one was using the [atsamd21g18-mr210ua](http://ww1.microchip.com/downloads/en/devicedoc/atmel-42475-atsamr21g18-mr210ua_datasheet.pdf) module (I think that there is no many people is using those). We tried to sent a board sample but DHL messed up the delivery.

We already have a new revision of the board that we are planning to deliver by the end of this year. The board is essentially is a breakout for the module and the only additional peripheral is a charge-management unit for LiPo batteries. This means that essentially if you are planning to develop on this module this board definition should work "as is".

May be we can remove the specifics for the breakout and only focus on the module, this way any user of the module could use this repository. We choose this module because it already includes antenna diversity, a crypto-accelerator and a factory-delegated MAC address.

Let me talk with @joksan to separate the antenna diversity as a separate PR. 

What do you think?

**Comment by benpicco** [comment]
Off-the shelf modules are of course preferable over custom boards as more people will have access to those.

Antenna diversity should be a nice addition to the at86rf2xx driver regardless.

**Comment by mxgxw** [comment]
Great! Let us work on this and send a separate PR for the antenna diversity. Let me see with the guys if we can have something by the next week!

**Pull request closed without merging**
