### PR TITLE
newlib+llvm: Use --sysroot instead of -nostdinc

### PR DESCRIPTION
**Pull request by gebart**
Depends on ~~#6670~~ 

This PR cleans up the LLVM include header path search to use the Clang supplied headers for the compiler-specifics in C instead of GCC's counterpart. For C++ we still need GCC (libstdc++).

Affected headers are the compiler bundled headers with close ties to compiler internals, such as `<limits.h>`

### CODE REVIEW

**Comment by tcschmidt** [comment]
ping @cladmi

**Comment by cladmi** [comment]
I cannot really help right now, I do not have/use llvm, the original files changed since then and I am not sure on the rebase choices. There are also both fix for  `--nostdinc` to `--sysroot` and `WIP improvements` which makes it harder to do code review without testing.

Also there is currently https://github.com/RIOT-OS/RIOT/pull/9216 that touches the newlib.mk file that is getting a lot of attention.

But definitely `newlib.mk` needs reworking.

**Comment by smlng** [comment]
@gebart is this still valid? Also needs rebase due to (several) changes in the mean time.

**Comment by gebart** [comment]
I think the idea is still relevant, the rebase might need a rewrite though.

**Comment by miri64** [comment]
No activity for over a year (except by stale bot). Let's close this for now as archived.

**Comment by miri64** [comment]
(+ many of the involved people are not active in RIOT anymore)

**Pull request closed without merging**
