### PR TITLE
cpu/esp32: add ESP-IDF API

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR is a split-off from PR #17841. It adds the basic structure for an API which is used for ESP-IDF types and functions that are required by RIOT-OS but cannot be included directly due to naming conflicts.

For this purpose, the header files of this API declare the types and functions that are required from the ESP-IDF, but without using the ESP-IDF header files to avoid conflicting names. The implementation of the API then uses the ESP-IDF. In most cases, simple wrapper functions are sufficient.

### Testing procedure

Since the basic structure of the API contains almost no functionality, a green CI is sufficient.

### Issues/PRs references

Split-off from PR #17841

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
Makes it painfully clear why namespaces would sometimes be a good thing to have…

I hope we can enable LTO one day so this at least wouldn't add any run-time cost anymore.

**Comment by gschorcht** [comment]
@benpicco Can we merge this one? It should then be possible to prepare the PRs for peripherals independent of other PRs once this PR is merged.

**Comment by gschorcht** [comment]
@benpicco Thanks for reviewing and merging.

**Comment by gschorcht** [comment]
> It should then be possible to prepare the PRs for peripherals independent of other PRs once this PR is merged.

Unfortunately this is not possible after all. The function `esp_intr_get_cpu` is needed, which is provided by PR #18261. So we have to wait for this PR.

**Pull request merged**
