### PR TITLE
tests/gnrc_udp: Replace atoi() by strtol() [backport 2019.04]

### PR DESCRIPTION
**Pull request by jcarrano**
### Contribution description

Partial backport of #11356 (only the bare minimum required to get the tests going.)

### Issues/PRs references

See #11356 .

### CODE REVIEW

**Comment by miri64** [comment]
Let's discuss the fix first before backporting it ;-). Otherwise, you just have more work, when you have to backport your fixups ;)

**Comment by miri64** [comment]
(also when you backport after merge you can use the convenient [backporting script](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/backport_pr/backport_pr.py))

**Comment by jcarrano** [comment]
@miri64 I removed all of the changes that were unrelated to the Zero-length bug.

> (also when you backport after merge you can use the convenient backporting script)

Actually, I forward-ported. I first made the change in the release branch and afterwards cherry-picked to master.

**Comment by miri64** [comment]
> Actually, I forward-ported. I first made the change in the release branch and afterwards cherry-picked to master.

Can you apply the changes here to master then, please, so we can merge there first?

**Comment by miri64** [comment]
@jcarrano ping: Please adapt your backport. Also needs rebase.

**Pull request merged**
