### PR TITLE
tools/zep_dispatch: run dispatch with custom topology

### LINKED ISSUE #18169: tools/zep_dispatch: Run dispatch with custom topology
#### Description

./topogen.sh file only generate random distributions of the nodes and if you want to add a custom topology file the program change this file to a random topology, changing the expected behavior.
  

#### Steps to reproduce the issue

Let's suppose that the file [filenew.topo] exist in the folder ``` /tools/zep_dispatch ``` with a custom topology.

Run the following command in console: 

```
make run TOPOLOGY= filenew.topo
```

#### Expected results

Is expected that the file [filenew.topo] will remain unaltered after command execution.

#### Actual results

 The file changes the custom topology to a random one.

#### Versions

RIOT version Release 2022.04

### PR DESCRIPTION
**Pull request by RocioRojas**
### Contribution description
 With this patch, any custom topology will remain unaltered after run command execution. This also allows random topology generation.

### Testing procedure
Create a new custom file topology [filenew.topo] in the folder /tools/zep_dispatch. Then, run:
```
make run TOPOLOGY= filenew.topo
```
Then check that filenew.topo remain unaltered.

For random generation, check:

```
make run
```

### Issues/PRs references
Fixes #18169

### CODE REVIEW

**Review by benpicco — COMMENTED** [review]
Thank you for the fix!

**Comment by benpicco** [comment]
You can now also get rid of `toposvg.sh` as it's no longer used.

**Comment by RocioRojas** [comment]
It's done. thanks! @benpicco

**Comment by benpicco** [comment]
Thank you, please squash!
(You can do `git rebase -i HEAD~4`, then select `fixup` for all but the first commit)

**Comment by RocioRojas** [comment]
Done! @benpicco

**Review by benpicco — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
