### PR TITLE
native: dynamically load malloc

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
g++ 5.2.0 apparently requires malloc before startup is run.

@authmillenon 
Please check if a change to Makefile.include like 8a33a629144374b03d97a4265f7948ee7d54a0df is required.

### CODE REVIEW

**Comment by authmillenon** [comment]
Is that a fix for the issue discussed in #4038?

**Comment by authmillenon** [comment]
> @authmillenon 
Please check if a change to Makefile.include like 8a33a62 is required.

I don't have the required version of gcc available.

**Comment by authmillenon** [comment]
`all-asan` is failing for me due to an unrelated issue. Will fix when I find the time, so this might not be a blocker for now.

```
#0  __memset_sse2 () at ../sysdeps/i386/i686/multiarch/memset-sse2.S:370
#1  0x555bad9c in __asan::PoisonShadow (addr=134627328, size=4160331776, value=value@entry=0 '\000')
    at ../../../../src/libsanitizer/asan/asan_poisoning.cc:27
#2  0x555b6ced in __asan_handle_no_return () at ../../../../src/libsanitizer/asan/asan_rtl.cc:401
#3  0x0804a927 in sched_task_exit () at /home/martine/Repositories/RIOT-OS/RIOT/core/sched.c:193
#4  0x56bcac6b in makecontext () at ../sysdeps/unix/sysv/linux/i386/makecontext.S:87
#5  0x00000000 in ?? ()
```

**Comment by LudwigOrtmann** [comment]
If this takes to test is `make clean all-asan term` such a change appears to be unneeded. In that case I'll remove the `ifdef` stuff.

**Comment by OlegHahm** [comment]
fixes #4039.

**Comment by LudwigOrtmann** [comment]
> Is that a fix for the issue discussed in #4039?

I think so, @OlegHahm made me do it.

**Comment by OlegHahm** [comment]
Yes, it is.

**Comment by OlegHahm** [comment]
Unfortunately, this merging this PR would require a new RC. :(

**Comment by LudwigOrtmann** [comment]
With clang + Valgrind memcheck this happens (GCC does not show it):
```
==11072== Command: /home/lo/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp.elf
==11072== 

parse DIE(readdwarf3.c:3651): confused by:
 <2><8e>: Abbrev Number: 7 (DW_TAG_subrange_type)
     DW_AT_type        : <95>	
     DW_AT_count       : 2	
parse_type_DIE:
--11072-- WARNING: Serious error when reading debug info
--11072-- When reading debug info from /home/lo/RIOT/examples/riot_and_cpp/bin/native/riot_and_cpp.elf:
--11072-- confused by the above DIE
RIOT native interrupts/signals initialized.
...
```

**Comment by LudwigOrtmann** [comment]
Can someone with a non-5.2.0 version of GCC test this PR so I can squash it?

**Comment by gebart** [comment]
I can test this on gcc-4.9.3 (x86) soon. We need to test this on OSX as well, as there may be differences there too.

**Comment by LudwigOrtmann** [comment]
Thanks =)

**Comment by gebart** [comment]
@LudwigOrtmann do you have an OSX machine?

**Comment by LudwigOrtmann** [comment]
Maybe remote if it still exists...will check in a bit.

**Comment by LudwigOrtmann** [comment]
OSX works before and after (`Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)`).

**Comment by gebart** [comment]
This PR works without segfault on my machine.

Tested:
 - examples/riot_and_cpp
 - tests/cpp11_condition_variable
 - tests/cpp11_mutex
 - tests/cpp11_thread

g++ (Gentoo 4.9.3 p1.0, pie-0.6.2) 4.9.3 on Linux 4.2.2-gentoo x86_64

**Comment by authmillenon** [comment]
Same for g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4 and Ubuntu clang version 3.4-1ubuntu3 on Linux 3.13.0-65-generic x86_64.

**Comment by OlegHahm** [comment]
Works for all related applications on my machine (gcc 5.2.0). ACK

**Comment by authmillenon** [comment]
The clang problem described in #4039 is unrelated?

**Comment by OlegHahm** [comment]
Yes.

**Pull request merged**
