### PR TITLE
hashes: cleanup

### PR DESCRIPTION
**Pull request by OlegHahm**
I found our structure of hashing algorithms inconsistent and a bit confusing. Based on the categories on [Wikipedia](https://en.wikipedia.org/wiki/List_of_hash_functions) I restructured the functions into
* CRC
* hashes
* crypto

Functions in these categories should provide the same (or similar) syntax.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Anyone with an opinion?

**Comment by BytesGalore** [comment]
Its the same for me, I find the current structure/grouping a bit odd.
:+1: to structure the hash like you did.

**Comment by OlegHahm** [comment]
Does someone know why relic tests are suddenly failing? This seems to be completely unrelated.

**Comment by OlegHahm** [comment]
Ok, found it, relic isn't pinned to a particular version.

**Comment by haukepetersen** [comment]
ACK! I guess is a successful run of the unittests enough as passing criteria?!

**Comment by OlegHahm** [comment]
I tried manually and Travis seems to agree.

**Pull request merged**
