### PR TITLE
sys: elfloader implementation for RIOT

### PR DESCRIPTION
**Pull request by SGSSGene**
The elfloader implementation was created for the Telematik-Softwareproject SS14.

### CODE REVIEW

**Comment by A-Paul** [comment]
@SGSSGene and/or @pandemie, do you have any ambitions to continue working on this PR?

**Comment by SGSSGene** [comment]
@A-Paul : We don't have any ambitions to continue. We are far far away from any RIOT development at the moment.

**Comment by A-Paul** [comment]
@kushalsingh007 do you mind if I close this PR, or do it yourself?
As you are working on a similar topic, the *memo* label might be set then.

**Comment by kushalsingh007** [comment]
@A-Paul : I am working on the same topic. Although I don't have any issue with this PR getting closed. But I don't think I am the right person to close the PR.

Maybe @OlegHahm or someone else can make the choice.

**Comment by OlegHahm** [comment]
@kushalsingh007, does your work incorporate the functionality provided by this PR?

**Comment by kushalsingh007** [comment]
Not completely , there are still a few things that this PR has, which mine does not have.

**Comment by authmillenon** [comment]
From what I can gather, we can close this PR as memo.

**Comment by LudwigKnuepfer** [comment]
@kushalsingh007 which PR were you talking about?

**Comment by OlegHahm** [comment]
Use the power of the search function, Luke: https://github.com/RIOT-OS/RIOT/pull/3686

**Pull request closed without merging**
