### PR TITLE
examples/pkgs: rename modules with duplicate names

### PR DESCRIPTION
**Pull request by cladmi**
Some examples and packages root directory use a module name that is already defined somewhere else.

Building works right now because when both an APPLICATION an a MODULE have the same
name AR just adds objects for both to the same library MODULE.a.

It currently works because they do not have conflicting file names.

### CODE REVIEW

**Comment by cladmi** [comment]
I found them with https://github.com/RIOT-OS/RIOT/pull/7952 but only tested native and samr21-xpro.

**Comment by kaspar030** [comment]
I don't understand the second commit. Are you renaming the package modules to pkg-X?

**Comment by cladmi** [comment]
I am renaming the package root module to pkg-X yes.

For `libfixmath` for example: both the package root and the libfixmath directory Makefile have `MODULE=libfixmath`. For the package root its because the directory is named `libfixmath`.
So they both define the `libfixmath` module and both produce the `libfixmath.a` archive.

Currently everything is working because ar just adds new files to the archive and does not care that two modules modify it.

What I did, is rename the root directory module to some dummy name. It will produce an empty unused archive but not touch the real `libfixmath.a` one.

**Comment by kaspar030** [comment]
> I am renaming the package root module to pkg-X yes.

Where do they get selected for linking?

**Comment by cladmi** [comment]
They don't get selected for linking but they are empty libraries.

No source files in the module Makefile directory:

```
RIOT/tests/libfixmath$ ls bin/pkg/native/libfixmath/
0001-Move-to-RIOT-Makefiles.patch                                benchmarks  images      unittests
0002-Fix-warnings.patch                                          contrib     libfixmath
0003-Adapt-unittests-for-RIOT.patch                              fixsingen   Makefile
0004-Change-conflicting-module-name-for-pkg-root-director.patch  fixtest     README.md
```

And the produced library is indeed empty
```
RIOT/tests/libfixmath$ ar t bin/native/pkg-libfixmath.a
RIOT/tests/libfixmath$ 
```

**Comment by kaspar030** [comment]
> They don't get selected for linking but they are empty libraries.

I see. Seems to me the package Makefile is more complicated than needed. That package's ```Makefile.include``` could just add the necessary folders to "DIRS", saving the empty module.

Anyhow, thanks for the explanation!

**Comment by cladmi** [comment]
I also think that, in general, setting `DIRS` should be handled by the main and sub `Makefile.include` and not submodules `Makefile` but that is a separate task.

**Pull request merged**
