### PR TITLE
[DO NOT MERGE] run CI on top of 9f6e676163dac282f5410f523c6da7a6e4fb9bac

### PR DESCRIPTION
**Pull request by jia200x**
The CI test is taking several days to complete. This PR is there to run Murdock on top of the last commit of 2021.01-branch (pointing to the upcoming RC-2)

### CODE REVIEW

**Comment by jia200x** [comment]
I ran this test on a server at HAW and some tests failed because it was an old riot/riotbuild image (it seems picolibc was not introduced yet). Running these tests again with the newer docker image indeed worked. Let's see what Murdock reports here, just to be 100% sure ;)

**Comment by miri64** [comment]
Maybe something like `on: tags` in the Github actions would also something what we want for Murdock? What do you think @kaspar030?

**Comment by jia200x** [comment]
This is the output of Murdock:
```
-- github reports HEAD of 2021.01-branch as 9f6e676163dac282f5410f523c6da7a6e4fb9bac
--- creating merge commit ...
-- merging b22bc2de6bf4e301a3bcc811e4e0e5c09a6d574d into 9f6e676163dac282f5410f523c6da7a6e4fb9bac
--- done.
---- using merge commit SHA1=f6b3bbeaf76d25cc3709e3f306635530fd3edb6d
-- Building PR#15869 https://github.com/RIOT-OS/RIOT/pull/15869 head: b22bc2de6bf4e301a3bcc811e4e0e5c09a6d574d...
-- processing results ...
- running script "/opt/murdock2/scripts/post-build.d/00sizes.py"
- running script "/opt/murdock2/scripts/post-build.d/01metrics.py"
-- done processing results

--- result: BUILD SUCCESSFUL.
```

As expected, this dummy commit got rebased on top of 9f6e676163dac282f5410f523c6da7a6e4fb9bac. The compile tests passed. Therefore I declare 01-ci/01 as passed ;)

**Comment by miri64** [comment]
> As expected, this dummy commit got rebased on top of [9f6e676](https://github.com/RIOT-OS/RIOT/commit/9f6e676163dac282f5410f523c6da7a6e4fb9bac). The compile tests passed. Therefore I declare 01-ci/01 as passed ;)

So I guess this can be closed then :-)

**Pull request closed without merging**
