### PR TITLE
 boards/nucleo-f303re: fix I2C[1] sda_pin and scl_af settings

### PR DESCRIPTION
**Pull request by roh849**
### Contribution description
boards/nucleo-f303re: fix I2C[1] sda_pin and scl_af settings

The config-values of second i2c-device did not match the values given in stm32f303re datasheet - now they do.

### Testing procedure
The new configuration has been tested with tests/periph_i2c, tests/driver_bmx280, tests/driver_at24cxxx and suitable i2c devices (bme280-sensor, 24lc512-eeprom)

### CODE REVIEW

**Comment by chrysn** [comment]
The changes are consistent with the 303xE datasheet (whereas the original values were not).

Is there a particular reason why for SCL the AF was adjusted to the pin, and for SDA the pin was adjusted to the AF?

**Comment by fjmolinas** [comment]
> The changes are consistent with the 303xE datasheet (whereas the original values were not).
> 
> Is there a particular reason why for SCL the AF was adjusted to the pin, and for SDA the pin was adjusted to the AF?

I think it mainly to match a layout where both pins are close to each other:

image

So since @chrysn verified the datasheet values this one seems good to go, @roh849 can you modify the commit message to fit our coding conventions, there are some details [here](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md#commit-conventions), but basically, the commit should be something like `boards/nucleo-f303re: fixe I2C2 SCA/SCL pin settings`

**Comment by roh849** [comment]
> > The changes are consistent with the 303xE datasheet (whereas the original values were not).
> > Is there a particular reason why for SCL the AF was adjusted to the pin, and for SDA the pin was adjusted to the AF?
> 
> I think it mainly to match a layout where both pins are close to each other:
> 
> image
> 
> So since @chrysn verified the datasheet values this one seems good to go, @roh849 can you modify the commit message to fit our coding conventions, there are some details [here](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md#commit-conventions), but basically, the commit should be something like `boards/nucleo-f303re: fixe I2C2 SCA/SCL pin settings`

I modified the commit message title. @chrysn: Thanks for removing the comment markers.

**Comment by fjmolinas** [comment]
@roh849 you modified the PR title, not the commit message ;)

**Comment by roh849** [comment]
> @roh849 you modified the PR title, not the commit message ;)

I modified the commit message too.

**Comment by fjmolinas** [comment]
> > @roh849 you modified the PR title, not the commit message ;)
> 
> I modified the commit message too.

Did you push? I don't see the change in github

**Comment by benpicco** [comment]
You can edit your commit with `git commit --amend`.
Since that means you are re-writing history, a force push is necessary (`git push -f`)

**Comment by roh849** [comment]
seems to be a difficult birth ;)
-changed the commit message on my local copy
-pushed it to my remote fork
-PR has been changed automatically(?)

**Comment by fjmolinas** [comment]
Thanks @roh849 its all good know, let see if murdock agrees, I triggered the CI!

**Review by fjmolinas — APPROVED** [review]
ACK!

**Pull request merged**
