### PR TITLE
core/lifo: Remove lifo [after 2021.04]

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

remove core/lifo and it's unittests

Why?:
- no part of riot uses it but the unittests
- core/lifo is lifo for a very specific usecase 
- core/lifo has very tight usage requirements (see documentation) and is prone to be used incorrectly
- incorrect usage will have very bad effects (bounds are unchecked and values are treated as adresses)
- correct usage seems unlikely to me, even if such a structure is need it is very application specific therefor it should be part of that very application or a library.

- unittests will run faster since there are less tests.

### Testing procedure

nothing new added -> nothing to test but the core unittests

### Issues/PRs references

@maribu might want to have a look at this

### CODE REVIEW

**Comment by miri64** [comment]
Last usage of `lifo.h` outside of the unittests seems to have been removed with `hwtimer`, the predecessor of `periph/timer`, in 2015 :grimacing:: 085383bfaeda67302a4359d

**Comment by miri64** [comment]
But, in case someone is using it externally still, should we go the usual deprecation procedure still?

**Comment by miri64** [comment]
> Last usage of `lifo.h` outside of the unittests seems to have been removed with `hwtimer`, the predecessor of `periph/timer`, in 2015 grimacing: [085383b](https://github.com/RIOT-OS/RIOT/commit/085383bfaeda67302a4359d3aecdb4555c5fb46f)

(Found using `git log -S"lifo.h"` btw ;-))

**Comment by maribu** [comment]
I have trouble to imagine for what this sensibly can be used. If there are users out there, they could just copy lifo.c and lifo.h into their app.

If we really want to deprecate, we should at least move this to sys right away.

**Comment by kfessel** [comment]
@miri64: Thank you for searching the last (i think the only ever) user of lifo.h.
As I wrote in the PR i don't think that lifo with it's tight constrains has any use outside its former one, i think it should have been part of hwtimer. I am not sure if there is a distinction between public (use in applications or off tree modules) and non public headers / interfaces in RIOT, but even if I would consider this non even if it was. The description of it is more of how to fatally (to big values, a value twice) break it than how to use it.

While the removal of kernel_types.h moved an API that was in use at that very time, this has none.

I would not move or deprecate this to SYS in it's current form keeping its name (maybe if its renamed to "fast_small_int_lifo").

If one needs that functionality it should be part of that very compile step (static inline or define) to keep the fastness which is its feature.

**Comment by kaspar030** [comment]
I understand the urge to merge this and be done with it. I also basically agree with the reasoning. Still, changing API's and dropping functionality should not be done lightly.
In this case, having the code in doesn't hurt and poses no maintenance burden.

I suggest a tight deprecation as per our procedures. Like, mark deprecated this cycle, remove next.

**Comment by maribu** [comment]
> I understand the urge to merge this and be done with it. I also basically agree with the reasoning. Still, changing API's and dropping functionality should not be done lightly.
> In this case, having the code in doesn't hurt and poses no maintenance burden.
> 
> I suggest a tight deprecation as per our procedures. Like, mark deprecated this cycle, remove next.

But let's please move this out of `core`.

**Comment by kfessel** [comment]
I am not sure how the deprecation procedure in RIOT works (`#warn ...`will result in error with `-Werror`), i searched how kernel_types.h was deprecated but could not find it. But maybe that is the best example of how not to do this, in this case i am all in for deprecating (no fancy move to sys since it should really be gone in its current form).

**Comment by maribu** [comment]
Via the [`@deprecated`](http://epic-alfa.kavli.tudelft.nl/share/doc/doxygen-1.6.1/html/commands.html#cmddeprecated) Doxygen command.

**Comment by maribu** [comment]
> In sys this would become a new? module? and its code would spread to `RIOT/sys/include` and `RIOT/sys/module_name`


:+1:

**Comment by kfessel** [comment]
since the removal has to wait #16101 at least deprecates it

**Comment by kfessel** [comment]
rebased on current master (track the deprecation of lifo)

**Comment by kfessel** [comment]
there seems to be a hickup in murdock.

**Comment by miri64** [comment]
Same problem as in https://github.com/RIOT-OS/RIOT/pull/16101#pullrequestreview-599942929, just another worker 🙄

**Comment by kfessel** [comment]
with 2021.04 released: This can be merged (i think)

**Review by fjmolinas — APPROVED** [review]
ACK, but this needs a second one.

**Review by maribu — APPROVED** [review]

**Comment by fjmolinas** [comment]
Thanks for the contribution @kfessel

**Pull request merged**
