### PR TITLE
cpu/stm32-common: Add support for DMA to F2/4/7 [BACKPORT]

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This is the backport of #7658 

### Issues/PRs references

#6577

### CODE REVIEW

**Comment by aabadie** [comment]
Tested locally the scenario where dma is merged in new_i2c_if which is then merged in master. This is OK.
I'm merging this.

**Comment by miri64** [comment]
So we just merge our PRs nows without review oO? Yes this is a backport, but the branch is supposed to go into master, right?

**Comment by aabadie** [comment]
Well, I backported commit from master to new_i2c_if. They are the same, I tool the initial branch and rebased it on new_i2c_if.

**Comment by miri64** [comment]
But the base is not the same => the code base is not the same => tests can have different effects ... Having a second pair of eyes on this is *always* better, and we never should merge un-ACK'd code!

**Comment by aabadie** [comment]
I know that, I take on me. The changes in #7658 are limited to stm32_common code and a few board periph_conf files. It shouldn't make too much difference. I took the exact same commits without any change (only using git).

**Comment by kYc0o** [comment]
I'm with @miri64 here. I know the merge is not harmful (luckily) and maybe that's why you merged it without hesitation. It's just a kind reminder to not merge **any** PR without an ACK.

**Comment by kYc0o** [comment]
Tried to run Murdock just in case but it's not triggered when a PR was merged.

**Comment by aabadie** [comment]
Murdock will certainly fail for many other reasons: the new_i2c_if branch in its current state is totally broken since all CPUs don't implement the new interface and not all drivers have been adapted.

**Pull request merged**
