### PR TITLE
drivers: ethos: fix _recv signature

### LINKED ISSUE #4908: drivers/ethos/ethos.c:343:13: error: initialisation from incompatible pointer type
Someone can explain me this?

https://github.com/RIOT-OS/RIOT/blob/master/drivers/ethos/ethos.c#L294 != https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/net/netdev2.h#L143

There is no new commit changing this and I was able to build the gnrc_border_router example until this afternoon... How it was possible?

@kaspar030 @authmillenon any hints?

### PR DESCRIPTION
**Pull request by kaspar030**
fixes #4908.

### CODE REVIEW

**Comment by kYc0o** [comment]
should we wait for travis? I'll try to make a PR for a test for this on travis.

**Comment by OlegHahm** [comment]
IMO it doesn't make sense to wait for Travis if isn't built anyways. :+1: for merging now and creating another PR with a simple test.

**Comment by OlegHahm** [comment]
P.S. The simplest case would be a test that just compiles ethos and remove this test as soon as the simplified border router example is merged.

**Comment by kYc0o** [comment]
ok, I ACK and will create the test as soon as simple br is working as expected.

**Comment by kaspar030** [comment]
Ok, then I merge as is.

**Pull request merged**
