### PR TITLE
netdev2: rename to netdev and remove `gnrc_netdev`

### PR DESCRIPTION
**Pull request by miri64**
With some minor hand-edits I used the following chain of commands:

```sh
git rm sys/include/net/gnrc/netdev.h
git grep --name-only -i netdev2 | \
        xargs sed -i -e 's/^\(NETDEV\)2\(.*\)\( [("]\)/\1\2 \3/g' \
                     -e 's/\(netdev\)2\(.*\)\( \/\*\*<\)/\1\2 \3/I' \
                     -e 's/\(netdev\)2/\1/gI'
git add -p
git commit --amend
git ls-tree --full-tree -r HEAD --name-only | \
        grep "netdev2" | xargs -I'{}' dirname '{}' | uniq | \
        grep "netdev2" | while read dir; do
                new_dir="$(echo "$dir" | sed "s/netdev2/netdev/g")"
                git mv -f "$dir" "$new_dir"
        done
git commit --amend
git ls-tree --full-tree -r HEAD --name-only | \
        grep "netdev2" | while read file; do
                new_file="$(echo "$file" | sed "s/netdev2/netdev/g")"
                git mv -f "$file" "$new_file"
        done
git commit --amend
git grep --name-only "\<drivers_netdev_netdev\>" | \
        xargs sed -i "s/\<drivers_netdev_netdev\>/drivers_netdev_api/g"
git add -p
git commit --amend
```

### CODE REVIEW

**Comment by miri64** [comment]
found and fixed minor issue (inclusion of (original) `net/gnrc/netdev.h` led to problems ;-))

**Comment by miri64** [comment]
Rebased (fun!)

**Comment by miri64** [comment]
Rebased.

**Comment by miri64** [comment]
Rebased. I would like to avoid another ;-)

**Comment by kaspar030** [comment]
Well, it compiles... I'd say, merge once Murdock1 agrees?

@miri64 how hard would it be to seperate removal of gnrc_netdev, automatic changes and the changes made by hand into seperate commits?

**Comment by emmanuelsearch** [comment]
By the way: would this be a good candidate to test Coccinelle use?

**Comment by emmanuelsearch** [comment]
+1 for merging after Murdock agrees

**Comment by kaspar030** [comment]
> By the way: would this be a good candidate to test Coccinelle use?

Maybe. But the work is done I guess. ;)

**Comment by emmanuelsearch** [comment]
Yes, the work is done, but it could still be a good benchmark for the usefulness of the tool in RIOT?

**Comment by kaspar030** [comment]
> Yes, the work is done, but it could still be a good benchmark for the usefulness of the tool in RIOT?

Try and let us know!

**Comment by kaspar030** [comment]
Do we need a second ACK for this? I admit I did not look at all thost 1700 changed lines.

**Comment by miri64** [comment]
> @miri64 how hard would it be to seperate removal of gnrc_netdev, automatic changes and the changes made by hand into seperate commits?

it would be basically doing everything all over again, since I do not remember which change I did how :-/

> By the way: would this be a good candidate to test Coccinelle use?

TBH, I totally forgot about this tool again :( Thanks for the reminder. But since there were a few handcrafted changes that might have been able automatized with a more complex tool than `sed` (e.g. removing `#include "net/gnrc/netdev.h"` completely, since `net/gnrc/netdev2.h` now became that and is completely different), I think it would have been the better choice.

**Comment by miri64** [comment]
> Do we need a second ACK for this? I admit I did not look at all those 1700 changed lines.

I would feel better if someone else than me would at least test, if `gnrc_networking` is still working ;-).

**Comment by kaspar030** [comment]
> I would feel better if someone else than me would at least test, if gnrc_networking is still working ;-).

Confirmed gnrc_networking is still working (tried ping). Let's go!

**Comment by kaspar030** [comment]
@miri64 Would you mind letting devel@ know about the change?

**Comment by miri64** [comment]
Not at all, will write a mail.

**Comment by emmanuelsearch** [comment]
@miri64 great to finally have straightened this part of the API out!

**Comment by drcef** [comment]
Networking is partly broken in my 2 samr21-xpro boards since this PR was merged.

They can ping each other only on their link local addresses. Even if they have global addresses assigned (or autoconfigured) they can't ping each other using them. This rename might have introduced issues to NDP which breaks the neighbor cache of the nodes.

In another scenario, one xpro is acting as a border router (based on the gnrc_border_router example, modified to use the enc28j60 ethernet adapter instead of ethos for uplink) and the other as a node with gnrc_networking. Networking with global addresses is now broken there too. The border router can't talk to the upstream network router or the 802.15.4 nodes except using link-local addresses.

**Comment by miri64** [comment]
I can't confirm the border router case (samr21-xpro with ethos ethernet). For the first case: Did you set the forwarding in the FIB as well? Auto-config won't cut that (that was the case before this PR was merged too).

**Comment by drcef** [comment]
Yes I did. I've been testing the border router case, now it works again after I reverted just before this PR.

**Comment by miri64** [comment]
As I said: I can't confirm (I don't have the `enc28j60` chip though :-/). Both scenarios work in the default set-up (i.e. with ethos border router). Tested scenario 1 on both samr21-xpro and native.

**Comment by drcef** [comment]
I will investigate it a bit further when I have some time, it might be an issue with enc28j60 as well. Thanks for checking on your end!

**Pull request merged**
