### PR TITLE
core: fix typo in kernel_macros.h (alternative to #3364)

### PR DESCRIPTION
**Pull request by BytesGalore**
just what it says, alternative to #3364

### CODE REVIEW

**Comment by OlegHahm** [comment]
You fixed the Kenrel!

**Comment by PeterKietzmann** [comment]
Oleg ACK from your side? I would also ACK, it's a (minor) kernel change :-). Long time nothing heard in #3364...

**Comment by BytesGalore** [comment]
I just stole the fix from @grandmou

**Comment by OlegHahm** [comment]
I was considering NACKing, but I changed my mind. ;)

ACK

**Comment by PeterKietzmann** [comment]
Travis fails unrelated to this change:
```
nhdp:chronos:

Building application "nhdp" for "chronos" with MCU "cc430".

make -C /home/travis/build/RIOT-OS/RIOT/pkg/oonf_api/oonf_api

make[2]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.

mkdir -p /home/travis/build/RIOT-OS/RIOT/tests/nhdp/bin/chronos/

/home/travis/build/RIOT-OS/RIOT/pkg/oonf_api/oonf_api/src-api/common/autobuf.c: In function 'abuf_strftime':

/home/travis/build/RIOT-OS/RIOT/pkg/oonf_api/oonf_api/src-api/common/autobuf.c:210:3: error: implicit declaration of function 'strftime' [-Werror=implicit-function-declaration]

/home/travis/build/RIOT-OS/RIOT/pkg/oonf_api/oonf_api/src-api/common/autobuf.c:210:8: error: incompatible implicit declaration of built-in function 'strftime' [-Werror]

cc1: all warnings being treated as errors

make[3]: *** [/home/travis/build/RIOT-OS/RIOT/tests/nhdp/bin/chronos/oonf_common/autobuf.o] Error 1

make[2]: *** [all] Error 1

make[1]: *** [all] Error 2

make: *** [/home/travis/build/RIOT-OS/RIOT/tests/nhdp/bin/chronos/oonf_api.a] Error 2
```
Master @OlegHahm, would you merge?

**Comment by cgundogan** [comment]
@PeterKietzmann unrelated to this PR: I blacklisted chronos for the nhdp buildtest in #4341

**Pull request merged**
