### PR TITLE
gnrc/ipv6: Remove unused 'GNRC_IPV6_STATIC_LLADDR' macro

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
The usage of `GNRC_IPV6_STATIC_LLADDR` (introduced in #6623) has been removed from `GNRC netif` some releases ago, but it is still documented and referenced in some examples.

This PR removes the macro from documentation and example Makefiles.

### Testing procedure
- `examples/gnrc_networking` should work as usual

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
Mh... I don't think the use case outlined in https://github.com/RIOT-OS/RIOT/pull/6623 is invalid, but the macro must have been slipped through in the `gnrc_netif` rework. So it make sense to go the other way and re-add support for that macro in my opinion.

**Comment by fjmolinas** [comment]
> Mh... I don't think the use case outlined in #6623 is invalid, but the macro must have been slipped through in the gnrc_netif rework. So it make sense to go the other way and re-add support for that macro in my opinion.

is it a commit that should be reverted?

**Comment by miri64** [comment]
> is it a commit that should be reverted?

No. That would revert the whole netif rework ^^. But I can readd support for it again :-)

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/13122.

**Pull request closed without merging**
