### PR TITLE
Subsystem for different uart implementations (e.g. peripheral UART and one over USB)

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR allows the use of different uart implementations (e.g. peripheral UART and one over USB).
~~Depends on #4114~~ and serves as an example for #4155 . WIP

### CODE REVIEW

**Comment by kaspar030** [comment]
Shouldn't we generalize this? chardevops_t?

**Comment by jfischer-phytec-iot** [comment]
Ne rather not. UART fits already.

I would like to use something like (sys/Makefile):
```
ifneq (,$(filter periph_uart_extended,$(FEATURES_PROVIDED)))
    DIRS += uart
endif
```
to make it less ugly :-) Any idea?

**Comment by kaspar030** [comment]
> Ne rather not. uart (uartdev_ops_t) fits better.

I'm thinking, you're introducing a generic interface for read(), write(), poweron/off, and init.
The only thing uart-specific is "init", the rest would also work for, e.g., a tcp connection.

**Comment by jfischer-phytec-iot** [comment]
@kaspar030 Ok, now I have understood you.

**Comment by OlegHahm** [comment]
Still WIP, I guess it won't make it for this release. @jfischer-phytec-iot retag if you disagree.

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by OlegHahm** [comment]
I remove the milestone because it seems quite unpredictable when @jfischer-phytec-iot will have time to finish this work.

**Comment by OlegHahm** [comment]
Why?

**Comment by jfischer-phytec-iot** [comment]
Ups, sorry, excessive cleansing. But.. there was a discussion about this during summit, and it was rejected because it caused more latencies and code.

**Comment by OlegHahm** [comment]
Thanks for the explanation.

**Pull request closed without merging**
