### PR TITLE
boards: add stm32mindev (clone of the Blue Pill board)

### PR DESCRIPTION
**Pull request by maribu**
This pull requests basically does this:

 - Moved code from the `bluepill` board into a new module `boards_common_stm32f103c8` located at `board/common/stm32f103c8`, so that multiple STM32F103C8 based boards can share the same code
- Updated the `bluepill` to use the new module
- Added support for the board `stm32mindev`, the STM32 Minimum System Development Boards, which, unlike the `bluepill` board, is still easily and cheaply available

The blue pill code is the perfect base for the common module of STM32F103C8 based boards: Apart from the LED it only contains the bare minimum required for a STM32F103C8 MCU based board. The new `stm32mindev` board is nearly identical to `bluepill`. The only relevant difference is that the LED is connected to a different GPIO pin.

### CODE REVIEW

**Comment by kaspar030** [comment]
Thanks for taking the time to properly factor out similarities!

Please change your commit subjects. RIOT's convention is "subsystem: do foo", e.g., "boards: add support for xxx".

I don't have an stm32mindev, but can test bluepill, probably by tomorrow.

**Comment by maribu** [comment]
Hi,

I updated the PR:
- The commit messages now comply with RIOT's format
- The common code for on-board LEDs is a bit more flexible

Kind regards,
Marian

**Comment by maribu** [comment]
Hi,

I think I will update the PR to not include the LED unification. This should be done in a separate PR and for all boards on which LEDs can be treated in this uniform way. But, honestly, I now think the code is more readable without that unification, so I might just drop that idea.

Kind regards,
Marian

**Comment by MrKevinWeiss** [comment]
Please add the stm32mindev board to the following BOARD_INSUFFICIENT_MEMORY makefiles:
- RIOT/examples/dtls-echo/Makefile
- RIOT/examples/gnrc_border_router/Makefile
- RIOT/examples/gnrc_tftp/Makefile
- RIOT/examples/javascript/Makefile
- RIOT/examples/lua/Makefile
- RIOT/tests/gnrc_netif/Makefile
- RIOT/tests/pkg_fatfs_vfs/Makefile
- RIOT/tests/pkg_fatfs/Makefile
- RIOT/tests/unittests/Makefile

and maybe also add it to the ARM_CORTEX_M_BOARDS in RIOT/tests/unittests/Makefile

Hopefully that makes murdock happy!

**Comment by maribu** [comment]
@MrKevinWeiss: Thanks for the review. I updated the BOARD_INSUFFICIENT_MEMORY as required. The tests "pkg_fatfs_vfs" and "pkg_fatfs" now contain a white list, so I did not need to modify them.

**Comment by MrKevinWeiss** [comment]
ACK, merging!

**Comment by dylad** [comment]
This PR violates the ongoing embargo on I2C refactoring.

**Comment by maribu** [comment]
@dylad: Please elaborate which embargo it violates (e.g. a link to an issue/PR), how this PR (which is unrelated to I2C) violates an embargo related to I2C, and what should be done about it since this PR is already merged

**Comment by dylad** [comment]
This PR renamed bluepill to stm32f103.. probably to avoid code duplication between bluepill and stm32mindev board. But by doing so, it cause lot of trouble after rebasing the feature branch to master + some Murdocks failures. We're trying to backport it to the feature branch but we have merge conflict.

**Comment by maribu** [comment]
@dylad: The Murdock failures are likely do be caused by some missing `BOARD_INSUFFICIENT_MEMORY` entries for the stm32mindev board. This PR looks bigger than it is, because mostly code is just moved from the bluepill board to common/stm32f103c8 for deduplication. If you need help merging, provide a link to the Repo/branch your working on

**Comment by dylad** [comment]
@smlng is working on it #9570.

**Pull request merged**
