### PR TITLE
Cc3200

### PR DESCRIPTION
**Pull request by nqd**
This this the begin of porting RIOT to CC3200.
This pull request just make hello-world example compile, without printing out anything since uart is not functional yet.

Only peripheral in using is LED of the launchpad.

The program can be load to launchpad via gdb & openocd.

Please consider this pull request as testing for RIOT conventional coding style. More pull requests for other peripheral, and simplelink (wifi) will come later.

Happy new year.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Nice effort, would be great to get support for the CC3200 into RIOT!

I would though strongly vote for dropping the TI SDK, and to implement the periph driver interface directly on register basis. This is the approach we take for almost all the supported platforms in RIOT, yielding a much better code efficiency and less code we have to maintain...

**Comment by kaspar030** [comment]
> I would though strongly vote for dropping the TI SDK, and to implement
> the periph driver interface directly on register basis. This is the
> approach we take for almost all the supported platforms in RIOT,
> yielding a much better code efficiency and less code we have to maintain...

We should put that very high up in the porting guide / FAQ. The only
platforms where we should allow using the vendor libraries is when
they're in ROM and thus greatly reduce codesize.

**Comment by haukepetersen** [comment]
@kaspar030: working on it!

**Comment by nqd** [comment]
With the fact that TI haven't provided CMSIS headers yet https://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/t/348552 (and I don't see any clue that they gonna release soon), getting the function run on register basis needs more hacking.

You may have more experience with the stellaris, any hints on common headers or the like @haukepetersen?

**Comment by haukepetersen** [comment]
@nqd: you are right, TI is for some reason not in the mood of generating CMSIS style headers. But IMHO the solution is simple: we write them ourselfes. This we have already done for the `CC2538` and partly for the `MSP430`. Also we are in the process of doing this while porting the TI SensorTag2 (featuring a `CC2560`).

The thing to keep in mind here is, that we don't have to write a complete set of CMSIS headers, just adding the defines and reg structs we actually need in RIOT is sufficient. After all this is not as much work as I thought some time ago - while having the benefit of way way more efficient and configurable code!

When creating this header file(s), I would prefer to do it in the following style:
- structs for each periph module, naming them something like `gpio_regs_t`, `gptimer_regs_t`, `usart_regs_t` (fitting with the module names used in the datasheet). E.g.
```c
#define REG32   voltatile uint32_t

typedef struct {
    REG32 IN;
    REG32 OUT;
    REG32 TGL;
    REG32 CFG;
...
} gpio_regs_t;
```
- bitmaps for the used registers, e.g.
```c
#define GPIO_CFG_EN   0x01
#define GPIO_CFG_IF   0x02
...
- module base addresses:
```c
#define GPIOA_BASE  0x40020000
...
#define GPIOA     ((gpio_regs_t *)GPIOA_BASE)
```

Note: alle module and register names in the example above are pseudo-code, I don't know which names they use for the CC3200...

**Comment by nqd** [comment]
Thank @haukepetersen, i have momentum seeing you guys wrote the headers yourselves. I will look into this, and come back later.

**Comment by haukepetersen** [comment]
cool

**Comment by OlegHahm** [comment]
@nqd, any progress?

**Comment by nqd** [comment]
@haukepetersen hey, I got tight schedule. Will update in coming week :).

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by miri64** [comment]
Postponed due to Feature Freeze.

**Comment by OlegHahm** [comment]
No response for almost one year. Let's close this. :-(

**Pull request closed without merging**
