### PR TITLE
gnrc_sixlowpan: update documentation

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This updates the documentation of 6LoWPAN in accordance to some (not quite so) recent changes.

I also considered to update the line-length to <70 characters, but I figured the simpler updates would just get drowned in that change, so I rather like to do it as a follow-up if desired.

### Testing procedure
`make doc` should still pass without errors, but more important, the doc should still make sense when read ;-).

### Issues/PRs references
Updates doc for outdated stuff following #8064 and the [GNRC 6Lo refactoring](https://github.com/RIOT-OS/RIOT/projects/18).

### CODE REVIEW

**Comment by miri64** [comment]
Addressed comments in separate change as they address a new thing.

**Comment by smlng** [comment]
As this is not code but just docu, I would suggest to squash ... but that's non-blocking 😬

**Comment by miri64** [comment]
> As this is not code but just docu, I would suggest to squash ... but that's non-blocking

The commits still address different topics within the doc, so I disagree.

**Comment by miri64** [comment]
@smlng wanna merge?

**Comment by smlng** [comment]
> > As this is not code but just docu, I would suggest to squash ... but that's non-blocking
> 
> The commits still address different topics within the doc, so I disagree.

To me the common topic here is *gnrc_sixlowpan: update documentation* ... anyways

ACK & GO

**Comment by miri64** [comment]
> To me the common topic here is _gnrc_sixlowpan: update documentation_ ... anyways

Yeah, that's the usual non-descript commit message one encounters in the history and then have to look and see what *actually* was updated I'm trying to avoid nowadays.

**Comment by smlng** [comment]
> > To me the common topic here is _gnrc_sixlowpan: update documentation_ ... anyways
> 
> Yeah, that's the usual non-descript commit message one encounters in the history and then have to look and see what _actually_ was updated I'm trying to avoid nowadays.

that's what the commit message body is meant for (IMHO). I mean, its mostly impossible to describe the whole purpose of a PR in just its headline (and also ideally within 50 chars). So in this case here, the commit title would be as mentioned above and in the body one would have a (bullet) list with the 4 commit messages of the distinct commit in here. I mean what is the commit message body good for otherwise, if you explain everything in the title already?

Though, splitting up a PR into distinct commits make sense for code to separate functional changes and ease bisecting for instance, (to me) it does not for documentation. I would rather avoid having extra commits making the history unnecessarily longer with only limited (functional) benefit. 

Still, you got your way ...

**Comment by miri64** [comment]
> I mean, its mostly impossible to describe the whole purpose of a PR in just its headline (and also ideally within 50 chars). 

We were talking about commits and as you can see I did that by subdividing the steps I did. One PR does not need to be one commit.

> So in this case here, the commit title would be as mentioned above and in the body one would have a (bullet) list with the 4 commit messages of the distinct commit in here. […] I would rather avoid having extra commits making the history unnecessarily longer with only limited (functional) benefit.

I don't see a longer, more detailed history as a bad thing. Your proposal is basically doing the same thing, just hiding the actual changes from Git. Also: documentation history should also be searchable and revertable. So IMHO fine-grained history for documentation makes as much sense as for functional code.

**Pull request merged**
