### PR TITLE
drivers: add support for DS3231 RTC

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
For a current project I was in the need for a battery-backed real-time clock and so I ended up with some `ds3231` modules. This PR adds basic support for these devices to RIOT. Unfortunately my modules to not provide access to the 32khz nor the interrupt/square wave pins, so I was not able to test that functionality. In the end I decided to also omit the alarm and square wave code from this PR altogether. If somebody is interested that code can be found here: https://github.com/haukepetersen/RIOT/tree/add_driver_ds3231_alarm_sqw

Note: there is some slight overlap with the existing `ds3234` driver, that would be worth of being merged together at some point. For now I decided to keep this PR independent as I want to get a little better overview on the other devices of the `ds323x` family before merging the code bases...

### Testing procedure
Connect a ds3231 device to a board of your choice and run the `test` shell command from the provided test application.

### Issues/PRs references
none

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
ACK. Code looks good, and given that the DS3234 driver only implements only one function it makes sense to implement a new driver (with the potential of merging them later also with other variants). Tested with `samr21-xpro`, all functions work as expected.

**Comment by jdavid** [comment]
Tested with the feather-m0 board and https://www.adafruit.com/product/3028 

```
$ BOARD=feather-m0 make -C tests/driver_ds3231 all flash test
[...]
Welcome to pyterm!
Type '/exit' to exit.
This is Rma
shell: command not found: main():
> test
 
>  test
testing device now
OK

make: Leaving directory '/home/jdavid/sandboxes/UiO/RIOT/tests/driver_ds3231'
```

**Comment by miri64** [comment]
Ah yeah, apart from the test command I also tested the other commands provided in the test, to increase the coverage of my tests. :-)

**Comment by haukepetersen** [comment]
pushed some minor static fixes, as pointed out by murdock, and squashed.

**Comment by miri64** [comment]
ACK upholds.

**Comment by miri64** [comment]
There are still some boards for which the test is to small: `arduino-leonardo`, `nucleo-l011k4`

**Comment by haukepetersen** [comment]
updated blacklisted boards, hopefully i caught them all...

**Comment by miri64** [comment]
Then let's go! :-)

**Pull request merged**
