### PR TITLE
Update README.md for ethos and start_network.sh

### PR DESCRIPTION
**Pull request by kYc0o**
Added documentation for ethos and automatic setup with the start_network.sh script on #4725

### CODE REVIEW

**Comment by authmillenon** [comment]
Which README.md?

**Comment by OlegHahm** [comment]
examples/gnrc_border_router/README.md

**Comment by authmillenon** [comment]
(I know that, but the commit message and PR description should reflect that ;-))

**Comment by kYc0o** [comment]
It is not in the commit message?

**Comment by authmillenon** [comment]
No, it just states "Update README.md …". There are a lot of `README.md`s in RIOT ;-). Please prefix the commit message with something like `gnrc_border_router: `.

**Comment by kYc0o** [comment]
Ok yes, actually this is so wrong so I'll do another PR and close this one...

**Comment by authmillenon** [comment]
You could have just fixed up your changes ;-)

**Comment by OlegHahm** [comment]
No. ;-) Wrong fork.

**Comment by authmillenon** [comment]
Ah oO

**Comment by kYc0o** [comment]
... *he escapes to mexico*

**Pull request closed without merging**
