### PR TITLE
pkg/semtech-loramac: add timer calibration

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds 2 macros for calibrating LoRaMAC reception windows timers, as described in [RX Window Calibration](https://stackforce.github.io/LoRaMac-doc/_p_o_r_t_i_n_g__g_u_i_d_e.html) in the original Semtech documentation.

Macros are added to the `@config` group so can be found in Doxygen.
- `#define LORAMAC_DEFAULT_SYSTEM_MAX_RX_ERROR    (50)`
- `#define LORAMAC_DEFAULT_MIN_RX_SYMBOLS                  (12)`

### Testing procedure
- Try to perform OTA and send confirmed messages in LoRaMAC
- Check if the macros appear in Doxygen.

### Issues/PRs references
#10352

### CODE REVIEW

**Comment by aabadie** [comment]
Very nice! I'll test this asap

**Comment by jia200x** [comment]
@aabadie thanks!

**Comment by leandrolanzieri** [comment]
Looks good. Tested on _sensebox_samd21_ and works fine!. Though the parameters should be placed under the LoraMAC config group

**Comment by aabadie** [comment]
> Though the parameters should be placed under the LoraMAC config group

Not sure, there are other default parameters that are not part of the config group.

I tested this PR on b-l072z-lrwan1, multiple DR, sending/receiving, everything worked. No more retry-confirmed messages. Awesome!

**Comment by aabadie** [comment]
CI is green, let's go!

**Comment by jia200x** [comment]
thank you so much :)

**Pull request merged**
