### PR TITLE
tests/pkg_lvgl: remove binary file added by mistake

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR removes an elf file that was added by mistake in a70fad5747b428e78a4a70ace16dc75b56c0c289 (from #15175).

#15175 was backported in 2020.10, so I'm wondering if this one also needs a backport.

### Testing procedure

Check that `tests/pkg_lvgl/tests_pkg_lvgl.elf` is not there:

- this PR:

```
$ ls tests/pkg_lvgl/tests_pkg_lvgl.elf
ls: cannot access 'tests/pkg_lvgl/tests_pkg_lvgl.elf': No such file or directory
```

- master:

```
$ ls tests/pkg_lvgl/tests_pkg_lvgl.elf
tests/pkg_lvgl/tests_pkg_lvgl.elf
```

### Issues/PRs references

Introduced by mistake in #15175

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
The binary was backported too https://github.com/RIOT-OS/RIOT/pull/15181/files

**Comment by aabadie** [comment]
> The binary was backported too

This is why I'm asking if we need a backport ;)

**Comment by benpicco** [comment]
I'd say so, just looks cleaner.

**Comment by aabadie** [comment]
Backport created: #15248

**Comment by aabadie** [comment]
To prevent future mistakes of this kind, I'm now wondering if using `find . -type d -name bin -prune -false -o -name *.elf` in a static test would make sense or if just adding `*.elf` in `.gitignore` would be enough.

**Comment by benpicco** [comment]
> just adding `*.elf` in `.gitignore` would be enough.

strong +1

I wonder why this isn't yet the case.

**Pull request merged**
