### PR TITLE
cpu: change adc_sample return to int32_t

### PR DESCRIPTION
**Pull request by olegart**
### Contribution description

adc_sample return value type changed from `int` to `int32_t`

1) There are 16-bit CPUs on the market with 18-bit or even 24-bit ADCs (e.g. some MSP430s)
2) MISRA-C:2004 rule 6.3 recommends to avoid using types without explicitly specified size and signedness

### Testing procedure

Build tests/periph_adc for the board of your choice.

### CODE REVIEW

**Comment by gebart** [comment]
I agree this is a good improvement.

**Comment by gebart** [comment]
Could you grep through the source and update the adc_sample users too?

**Comment by olegart** [comment]
1) ADC resolutions 18/20/22/24 bits added to adc.h and CPU configuration files
2) SAUL rejects ADC resolutions over 16 bits
3) adc_sample users fixed (Arduino's AnalogRead return value still declared as `int` — it is fixed at ADC_RES_10BIT anyway)

**Comment by olegart** [comment]
Regarding SAUL — it is deliberately declared as int16 in phydat.h

**Comment by olegart** [comment]
Will address build issues/typos on weekend.

**Pull request closed without merging**
