### PR TITLE
cpu/stm32: fix name clash between cpu/stm32/Kconfig files and cpu/stm32/kconfig directory [backport 2020.10]

### LINKED ISSUE #15255: Repository 'broken' on macOS due to case-insensitive names
#### Description
When cloning RIOT-OS, Git immediately complains about `cpu/stm32/Kconfig` being deleted. When restoring that file, it removes the directory `cpu/stm32/kconfig`. This has to do with macOS being case-insensitive by default.

I work-around this issue by creating a case-insensitive volume for my RIOT workspace. But I think this issue should be resolved to provide a better user experience.

#### Steps to reproduce the issue
Clone RIOT and notice that `git status` immediately complains about `cpu/stm32/Kconfig`.

#### Expected results
A clean repository.

#### Actual results
`git status` shows that `cpu/stm32/Kconfig` is deleted.

#### Versions
```
Operating System Environment
----------------------------
         Operating System: Mac OS X 10.15.7
                   Kernel: Darwin 19.6.0 x86_64 i386
             System shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
             make's shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

Installed compiler toolchains
-----------------------------
               native gcc: Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: Apple clang version 11.0.0 (clang-1100.0.33.8)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.3.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: missing
                    cmake: cmake version 3.18.4
                 cppcheck: missing
                  doxygen: missing
                      git: git version 2.29.0
                     make: GNU Make 3.81
                  openocd: missing
                   python: Python 2.7.16
                  python2: Python 2.7.16
                  python3: Python 3.8.6
                   flake8: error: /usr/local/opt/python@3.8/bin/python3.8: No module named flake8
               coccinelle: missing
```

### LINKED ISSUE #15256: Kconfig file/folder name collision on case-insensitive filesystem
#### Description

The Kconfig file in cpu/stm32/ is missing in the cloned repository. 
Because there is a folder with the same name the file cannot be created.

I think this is related to #14158 and #14160

#### Steps to reproduce the issue

Clone repository on MacOS with case-insensitive APFS filesystem.

#### Expected results

Both file and folder available.

#### Actual results

cpu/stm32/Kconfig is missing.

#### Versions

MacOS 10.13.6 with case-insensitive APFS filesystem.

### PR DESCRIPTION
**Pull request by aabadie**
# Backport of #15257 

I had to fix a conflict with 2020.10-branch so the backport_pr script didn't work out of the box.

### Contribution description

Fixes #15256 and fixes #15255 

The directory `cpu/stm32/kconfig` is renamed to `cpu/stm32/kconfigs` to avoid the name clash on systems with non case-sensitive file systems.

I added the `Needs backport` label to the PR because it's also in 2020.10-branch.

### Testing procedure

- A green Murdock

### Issues/PRs references

Fixes #15256 and fixes #15255

### CODE REVIEW

**Comment by aabadie** [comment]
modifications applied to gen_config.py are not applied because it's not part of 2020.10-branch :)

**Comment by fjmolinas** [comment]
@aabadie the testing procedure does not apply then

**Comment by aabadie** [comment]
> the testing procedure does not apply then

Indeed, I _adapted_ it

**Review by fjmolinas — APPROVED** [review]
Both files are present:

```
ls -la cpu/stm32/
total 108
drwxr-xr-x 10 francisco francisco  4096 Oct 21 11:01 .
drwxr-xr-x 45 francisco francisco  4096 Oct  1 16:03 ..
drwxrwxr-x  2 francisco francisco  4096 Oct  1 16:03 bootloader
-rw-rw-r--  1 francisco francisco  7598 Oct  1 16:03 cpu_common.c
-rw-rw-r--  1 francisco francisco  5687 Oct 21 10:51 cpu_init.c
drwxrwxr-x  4 francisco francisco  4096 Oct 21 10:51 dist
-rw-rw-r--  1 francisco francisco  2713 Oct  1 16:03 doc.txt
drwxr-xr-x  5 francisco francisco  4096 Oct 21 10:51 include
-rw-rw-r--  1 francisco francisco   950 Oct 21 11:01 Kconfig
drwxrwxr-x 14 francisco francisco  4096 Oct 21 11:01 kconfigs
drwxrwxr-x  2 francisco francisco  4096 Oct  1 16:03 ldscripts
-rw-rw-r--  1 francisco francisco   181 Oct 21 11:00 Makefile
-rw-rw-r--  1 francisco francisco   692 Oct 21 11:00 Makefile.dep
-rw-rw-r--  1 francisco francisco  1430 Oct 21 11:00 Makefile.features
-rw-rw-r--  1 francisco francisco  3459 Oct  1 16:03 Makefile.include
drwxrwxr-x  2 francisco francisco  4096 Oct 21 11:00 periph
-rw-rw-r--  1 francisco francisco  1253 Oct 21 11:00 stm32_info.mk
-rw-rw-r--  1 francisco francisco  4949 Oct 21 11:00 stm32_line.mk
-rw-rw-r--  1 francisco francisco 10034 Oct 21 11:00 stm32_mem_lengths.mk
-rw-rw-r--  1 francisco francisco  2415 Oct  1 16:03 stm32_riotboot.mk
drwxrwxr-x  2 francisco francisco  4096 Oct 21 11:00 stmclk
drwxrwxr-x  2 francisco francisco  4096 Oct 21 10:37 vectors
```

ACK.

**Pull request merged**
