### PR TITLE
drivers/at86rf2xx: add missing handler for TRX24_RX_START interrupt

### LINKED ISSUE #12857: examples/gnrc_networking_mac broken on ATmega
#### Description
`examples/gnrc_networking_mac` is broken on (at least) ATmega based MCUs.
When a second board comes online it will cause a kernel panic on the first one.

To check if this is a general problem I also flashed the example on a `same54-xpro` board with an at86rf233 radio module attached. Here the 32bit ARM board would not crash when the 8bit AVR came online, but AVR would crash after a short while when the ARM board would send period messages or was rebooted.

#### Steps to reproduce the issue
Flash `examples/gnrc_networking_mac` on an ATmega board, ideally one with an ATmega256RFR2 as that chip provides enough memory and the at86rf2xx radio needed for the example.

Flash a second compatible board with the example.

#### Expected results
Both boards can communicate.

#### Actual results
The moment the second board comes online, the ATMega board crashes:
```
2019-12-02 15:31:45,498 #  IRQ_STATUS 0x81
2019-12-02 15:31:45,499 # IRQ_STATUS1 0x1
2019-12-02 15:31:45,501 # SCIRQS 00
2019-12-02 15:31:45,501 # BATMON 0x22
2019-12-02 15:31:45,502 # EIFR 00
2019-12-02 15:31:45,504 # PCIFR 00
2019-12-02 15:31:45,504 # *** RIOT kernel panic:
2019-12-02 15:31:45,507 # ver on port %u
2019-12-02 15:31:45,507 # 
2019-12-02 15:31:45,507 # 
2019-12-02 15:31:45,515 # 	pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     
2019-12-02 15:31:45,524 # 	  1 | idle                 | running  Q |  15 |    128 (  126) |     0x3c30 |     0x3c54 
2019-12-02 15:31:45,532 # 	  2 | main                 | bl mutex _ |   7 |    640 (  272) |     0x3cb0 |     0x3e23 
2019-12-02 15:31:45,539 # 	  3 | pktdump              | bl rx    _ |   6 |    640 (  166) |     0x5bed |     0x5dca 
2019-12-02 15:31:45,547 # 	  4 | 6lo                  | bl rx    _ |   3 |    512 (  248) |     0x6c24 |     0x6d79 
2019-12-02 15:31:45,556 # 	  5 | ipv6                 | bl rx    _ |   4 |    512 (  262) |     0x62a9 |     0x63fc 
2019-12-02 15:31:45,564 # 	  6 | udp                  | bl rx    _ |   5 |    512 (  174) |     0x5e6f |     0x5fc4 
2019-12-02 15:31:45,573 # 	  7 | at86rf2xx-gomach     | bl rx    _ |   2 |    512 (  394) |     0x6084 |     0x6199 
2019-12-02 15:31:45,581 # 	  8 | RPL                  | bl rx    _ |   5 |    512 (  102) |     0x6a24 |     0x6bc1 
2019-12-02 15:31:45,588 # 	    | SUM                  |            |     |   3968 ( 1744)
2019-12-02 15:31:45,588 # 
2019-12-02 15:31:45,588 # *** halted.
```

#### Versions
RIOT master.

### PR DESCRIPTION
**Pull request by chudov**
### Contribution description

Missing ISR's added to at86rf2xx_netdev.c for ATmegaRFA1/RFR2:

- TRX24_PLL_LOCK
- TRX24_PLL_UNLOCK
- TRX24_RX_START
- TRX24_CCA_ED_DONE
- TRX24_AWAKE

### Testing procedure

Add one of ATMegaRFR2-based boards to BOARD_WHITELIST in tests\gnrc_gomach\Makefile or in examples\gnrc_networking_mac:
`BOARD_WHITELIST := samr21-xpro iotlab-m3 derfmega256`

Run the test on 2 boards. Check that board with ATMegaRFR2 shows received packets

### Issues/PRs references

Fixes #12857

### CODE REVIEW

**Comment by herjulf** [comment]
Verified PR on avr-rss2 (atmega256rfr2) with gnrc_networking_mac. 
Yes it might be good to populate the missing ISR to avoid hard debugged oopses. This bug have been lurking for quite some time. Good work all!

**Comment by kaspar030** [comment]
(pushed back in CI queue as this would fail anyway without https://github.com/RIOT-OS/RIOT/pull/16042)

**Comment by maribu** [comment]
https://github.com/RIOT-OS/RIOT/pull/16042 is now in. I restarted the build so that it indeed gets build on top of this, otherwise it would fail again.

**Review by benpicco — APPROVED** [review]
Nice, thank you!
I'll see if we can get rid of `irq_status` and directly call netdev_event as a follow-up.

**Pull request merged**
