### PR TITLE
tests: gnrc_netif2: make link-layer information matching generic

### PR DESCRIPTION
**Pull request by miri64**
The interface information checked in `tests/gnrc_netif2` might differ in `gnrc_pktdump` for non-native platforms so it can be that these tests fail on non-native platforms. This fixes that by just expecting any number for these (in the end they are not important anyways).

### CODE REVIEW

**Comment by cladmi** [comment]
Works now with `samr21-xpro` (if testrunner waits before running reset, or by pressing reset manually).

**Comment by miri64** [comment]
@RIOT-OS/maintainers Can someone who is a maintainer please proxy-ACK?

**Comment by haukepetersen** [comment]
all green -> go

**Comment by haukepetersen** [comment]
@miri64: please provide the matching backport. Thx

**Comment by miri64** [comment]
Backport provided in #7812

**Pull request merged**
