### PR TITLE
cpu/lpc23xx: model kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This models modules for the lpc23xx CPU and its related boards:
- avsextrem
- mcb2388
- msba2

It also includes some changes on drivers to follow the current modelling approach using feature symbols.

### Testing procedure
- Green CI
- The list of used symbols should match when using Kconfig and Makefile.

### Issues/PRs references
Part of #16875

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
looks good to me

**Comment by leandrolanzieri** [comment]
@benpicco could you take a look at the last 2 commits? Now these boards are actually bringing the mtd_mci which showed an issue with `tests/pkg_fatfs_vfs`, I think it should work now but I don't have the board to test.

**Comment by fjmolinas** [comment]
ping @benpicco :)

**Comment by benpicco** [comment]
looks good to me - but needs a rebase

**Comment by leandrolanzieri** [comment]
Rebased

**Comment by aabadie** [comment]
5666d1b has to be dropped

**Comment by leandrolanzieri** [comment]
> [5666d1b](https://github.com/RIOT-OS/RIOT/commit/5666d1b96240ce26928c9f1765857386d4e0efba) has to be dropped

Dropped

**Comment by leandrolanzieri** [comment]
Thanks for reviewing!

**Pull request merged**
