### PR TITLE
README: use dynamic badge for the hil-ci-badge

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

As promised, the badge not shows the results from the nightly.  Note that the tests passed/failed indicats test suites not the test cases.  It will go green if all tests pass, this hasn't happened (as some tests just cannot due to features not being supported).  I will be improving the test in the short term to hopefully get some reliable passes.

This should still be a nice window into the current state though and we should be able to see if something is going really wrong. I think also showing that we are running on 24 different boards is pretty nice (and that number will continue to go up).

Note that this information is being generated from the [nightly](https://ci.riot-os.org/hil/job/nightly/) job script.  Those who have access can change and adapt it.  This should also become a bit easier as I try to simplify the jenkins job script deployment.

### Testing procedure

Go to the [link](https://shields.io/endpoint?url=https://hil.riot-os.org/api/v1/nightly/latest/badge.json) and it should read something like `HiL | 153 pass / 7 fail / 24 boards`.

### CODE REVIEW

**Comment by kaspar030** [comment]
> It will go green if all tests pass, this hasn't happened (as some tests just cannot due to features not being supported). I will be improving the test in the short term to hopefully get some reliable passes.

IMO we should add a badge if we expect it to be green?

**Comment by MrKevinWeiss** [comment]
It should be green eventually.  This will require some work improving tests, improving broken things in RIOT, and improving infrastructure.  I can also set the colors as we wish (maybe orange or red isn't good, we can just keep it blue so we are not trying to hint at anything).

Can we agree that it would be cool to have the dynamic output?  If we are worried about the quality then we can also just have the boards and passed tests (or total tests run) or something?

I am open to suggestions.

**Comment by kaspar030** [comment]
> Can we agree that it would be cool to have the dynamic output? If we are worried about the quality then we can also just have the boards and passed tests (or total tests run) or something?

+1

**Comment by MrKevinWeiss** [comment]
I added a little writeup here.

**Comment by OlegHahm** [comment]
So, what is missing here?

**Comment by MrKevinWeiss** [comment]
I guess people don't like seeing inconsistent failures.  We can add it but it is more like a quick overview of the current hil tests.  I wanted to get everything passing but there are a lot of dependencies in doing do and probably won't be done this release.  Currently just the link should be OK.

**Comment by MrKevinWeiss** [comment]
Before this progresses, there are many problems that need to be solved from the Jenkins script side...

**Pull request closed without merging**
