### PR TITLE
release-notes: add 2020.07.1 release notes [backport 2020.07]

### PR DESCRIPTION
**Pull request by miri64**
# Backport of #14875

### Contribution description
This provides the release notes for the 2020.07.1 point release.

### Testing procedure
Read. Check if everything is right ;-).

The release was tested on the current version of `2020.07-branch` ~~e24586db0d~~  f415d935f640ef276b6af56c84803f4f5434a8a0. @fjmolinas ran [spec99 of the release-specs](https://github.com/RIOT-OS/Release-Specs/tree/master/99-compile-and-test-one-board) [on his machine](https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/162/artifact/) and I ran spec99 as the [`test-on-iotlab` GitHub workflow](https://github.com/RIOT-OS/RIOT/actions/runs/218388740). All results can be found [here](https://github.com/miri64/RIOT-2020.07-results/tree/master/2020.07.1-RC1-e24586db0d).

Additionally, I [ran the automated specs](https://github.com/RIOT-OS/RIOT/actions/runs/218665502).

This should cover everything that was changed since the release. We did not encounter anything getting worse since the release ;-).

### Issues/PRs references
None

### CODE REVIEW

**Comment by miri64** [comment]
I added the change for the VERSION file here too to safe some time.

**Review by benpicco — APPROVED** [review]
same as #14875

**Comment by miri64** [comment]
> same as #14875

Can't be! I updated the VERSION file here, which does not exist in #14875 ;-P

**Comment by benpicco** [comment]
same as #14875 *except for the version file*

**Pull request merged**
