### PR TITLE
tests/posix_sleep: Kconfig uses rtt if possible

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Matches kconfig usemodues from tests/posix_sleep with ones generated from makefile since the test isn't enforced.

### Testing procedure

Apply:
```diff
diff --git a/.murdock b/.murdock
index acb1356065..7200f309e2 100755
--- a/.murdock
+++ b/.murdock
@@ -23,7 +23,7 @@ tests/driver_motor_driver tests/driver_mpl3115a2 tests/driver_mpu9x50
 tests/driver_mq3 tests/driver_my9221 tests/driver_nvram_spi tests/mtd_flashpage
 tests/mtd_mapper tests/driver_o* tests/driver_p* tests/driver_q*
 tests/driver_r* tests/driver_s* tests/driver_t* tests/driver_u*
-tests/driver_v*"}
+tests/driver_v* tests/posix_sleep"}
 : ${TEST_KCONFIG_native:="examples/hello-world
 tests/cb_mux*
 tests/congure_*
```

and run
```
/bin/bash -c "source .murdock; JOBS=4 compile tests/posix_sleep samr21-xpro:gnu"
```

on master and on this pr and it should show this fixes it.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Here is my result:

<details>

```
/bin/bash -c "source .murdock; JOBS=4 compile tests/posix_sleep samr21-xpro:gnu"
make: Entering directory '/home/weiss/wd/RIOT/tests/posix_sleep'
make: Leaving directory '/home/weiss/wd/RIOT/tests/posix_sleep'
make: Entering directory '/home/weiss/wd/RIOT/tests/posix_sleep'
=== [ATTENTION] Testing Kconfig dependency modelling ===
=== [ATTENTION] Testing Kconfig dependency modelling ===
Building application "tests_posix_sleep" for "samr21-xpro" with MCU "samd21".

sha1sum /home/weiss/wd/RIOT/tests/posix_sleep/tests/01-run.py /home/weiss/wd/RIOT/build/tests_posix_sleep.elf > /home/weiss/wd/RIOT/build/test-input-hash.sha1
   text	   data	    bss	    dec	    hex	filename
  16016	    176	   2504	  18696	   4908	/home/weiss/wd/RIOT/build/tests_posix_sleep.elf
make: Leaving directory '/home/weiss/wd/RIOT/tests/posix_sleep'
make: Entering directory '/home/weiss/wd/RIOT/tests/posix_sleep'
make: Nothing to be done for 'clean'.
Building application "tests_posix_sleep" for "samr21-xpro" with MCU "samd21".

sha1sum /home/weiss/wd/RIOT/tests/posix_sleep/tests/01-run.py /home/weiss/wd/RIOT/build/tests_posix_sleep.elf > /home/weiss/wd/RIOT/build/test-input-hash.sha1
   text	   data	    bss	    dec	    hex	filename
  16016	    176	   2504	  18696	   4908	/home/weiss/wd/RIOT/build/tests_posix_sleep.elf
make: Leaving directory '/home/weiss/wd/RIOT/tests/posix_sleep'
-- build directory size: 1,7M
```
<\details>

**Comment by fjmolinas** [comment]
I know this is a bit out of scope of this PR, but shouldn't this be a dependency of this module and not the test?

**Comment by fjmolinas** [comment]
@MrKevinWeiss can you see if this is still needed? `periph_rtt` is always included if possible now.

**Comment by MrKevinWeiss** [comment]
OK, I will rebase and check.

**Comment by MrKevinWeiss** [comment]
Fixed in master, thanks @fjmolinas and @leandrolanzieri

**Comment by fjmolinas** [comment]
@MrKevinWeiss is there a reason not to add the application to the check though?

**Comment by MrKevinWeiss** [comment]
I am pushing for a better way to test kconfig and didn't want to rebase the Murdock file every time.

**Comment by MrKevinWeiss** [comment]
PR #16487 FYI, (sorry I was on my phone yesterday)

**Pull request closed without merging**
