### PR TITLE
cpu/esp32: add low-level LCD parallel interface using LCD peripheral

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR the implementation of the LCD low-level MCU 8080 parallel interface using the LCD peripheral for ESP32, ESP32-S2 and ESP32-S3 or `periph_gpio_ll` for the ESP32-C3.

### Testing procedure

```
BOARD=esp32s3-wt32-sc01-plus make -C tests/drivers/st77xx flash
```
should work on top of PR #19941. Drawing operations should be much faster.

### Issues/PRs references

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel
bors merge

**Comment by gschorcht** [comment]
What currently needs to be done to merge this PR? It seems to be stuck in the merge-queue migration phase because it is still waiting for bors. Is a rebase sufficient to trigger the merge? Auto-merge is enabled.

**Comment by benpicco** [comment]
I think you need to do a rebase to get the new GitHub config in.

**Pull request merged**
