### PR TITLE
cpu/esp32: split ESP32 port into ESP32x common and ESP32 specific parts

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR splits the ESP32 port into a part that is common for all variants of the ESP32 SoC series and a part that is specific for the ESP32 SoC. It is required to handle different variants of the ESP32 SoC series.

This PR includes PR ~#17601 and~ #17841 to be compilable. Once these PRs are merged this PR is rebased. The first additional commit of this PR is ba6aa2e7fd7a2ccea260a4425866be274bf368d2.

### Testing procedure

Green CI with test run.

### Issues/PRs references

Depends on PR #17601
Depends on PR #17841
Prerequisite for PR #17844

### CODE REVIEW

**Comment by gschorcht** [comment]
Does anyone have an idea why the status of the compilation of the PR in Murdock is shown as failed although no compilation error is shown and all compilations were successful according to the [log](https://ci.riot-os.org/RIOT-OS/RIOT/17842/5512a488d85213b7404f1c0dfccb4b821fe8f9ca/output.html)?

**Comment by maribu** [comment]
It says

> The build only failed the label check.

so once the `State: waiting for other PR` it would pass.

**Comment by gschorcht** [comment]
> so once the `State: waiting for other PR` is dropped it would pass.

Ah ok, I didn't know that. So there is no reason to be worried and the compilation is fine.

**Comment by gschorcht** [comment]
All split-offs are merged now.

**Pull request closed without merging**
