### PR TITLE
boards/stm32-based: allow SPI signals routed on multiple alternate functions

### PR DESCRIPTION
**Pull request by Yanok35**
There is no hardware limitation for custom boards based on STM32 to uses
SPI bus with signals coming from different PORT and alternate functions.

Signed-off-by: Yannick Gicquel <ygicquel@gmail.com>

### CODE REVIEW

**Comment by aabadie** [comment]
On STM32, other serial buses configurations (e.g. UART and I2C) also defines af per bus pin, so this change makes sense to me as well even if it will slightly increase code size.
I also checked and changes are ok (no obvious mistake).

@haukepetersen any opinion ?

**Comment by Yanok35** [comment]
@aabadie : Thanks for your review.
At Cogip robotic team, we previously had to patch the spi cpu driver implementation to match our custom board design (stm32f446 based), thus we think this could be a slight improvement to give more flexibility in the future.
@haukepetersen , @vincent-d  : Did you get a chance to take a look to these changes ?
Please let me know your opinion on this. Thanks.

**Comment by gdoffe** [comment]
Hello @Yanok35, @aabadie, @haukepetersen, @vincent-d 

Up. ;)

This change gives more flexibility on pinout configuration, which is much appreciable on devices with several spi (and others) devices plugged.

**Comment by gdoffe** [comment]
Hi,

I up again this PR.

@aabadie except rebasing on master, is there something wrong with this PR ?

Thx

**Comment by aabadie** [comment]
> except rebasing on master, is there something wrong with this PR ?

AFAIR, nothing, so please rebase. There might be boards missing now.
Sorry, this PR was completely forgotten.

**Comment by haukepetersen** [comment]
Sorry. No time to review in depth, but the changes look valid to me, so no objections.

**Comment by Yanok35** [comment]
Hi,
rebase done, including addition of 5x new boards.
Please let me know if anything shows up.
Thanks

**Comment by aabadie** [comment]
> Please let me know if anything shows up.

I triggered Murdock to verify nothing is missing. Went through the changes and didn't see any issues.

**Comment by Yanok35** [comment]
Murdock highlighted the spi_init_with_gpio_mode() API introduced in the meantime was requiring the alternate function update. Now the overall looks ready to merge. Looking forward to see this patch in mainline, Thanks.

**Pull request merged**
