### PR TITLE
nucleo144-f412: fix clock configuration

### PR DESCRIPTION
**Pull request by aabadie**
#6723 has been merged a bit fast: recent changes in clock configuration #7158 weren't applied yet (my bad) and it breaks RIOT build.

I updated the CMSIS file version and adapt the clock configuration of the board.

### CODE REVIEW

**Comment by aabadie** [comment]
Can we merge this one asap ? Otherwise, all build on Murdock will fail.

**Comment by kYc0o** [comment]
Whops! My bad too... but how murdock agreed?

**Comment by aabadie** [comment]
> but how murdock agreed?

He was green before the clock change and it doesn't re-build if the branch doesn't change...

**Comment by miri64** [comment]
I have no idea about clock configuration or how boards should be implemented, so I revoke my assignment ;-).

**Pull request merged**
