### PR TITLE
examples: tests: Moving gnrc_tcp_src/cli from examples to tests

### PR DESCRIPTION
**Pull request by brummer-simon**
Moving gnrc_tcp examples to tests

### CODE REVIEW

**Comment by miri64** [comment]
Please keep in the constraints of the Git commit summary character limit (50 at best, 72 at max) ;-).

**Comment by miri64** [comment]
(How about `examples: tests: move gnrc_tcp examples to tests/`?)

**Comment by brummer-simon** [comment]
Ok?

**Comment by miri64** [comment]
Now the prefix is missing ;-) (e.g. `examples: tests:`)

**Comment by brummer-simon** [comment]
Any Idea why the check fails?

**Comment by miri64** [comment]
That you have to ask @cgundogan or @smlng. Seems like a Jenkins hick-up.

**Pull request merged**
