### PR TITLE
make: Use unique module name for cpu_common periph

### PR DESCRIPTION
**Pull request by gebart**
Hopefully fixes the random Travis failures we have seen since #4762 was merged.

For the nrf51, there are files in both nrf5x_common/periph and nrf51/periph which are both built and put in periph.a before linking. My theory is that the random Travis failures we have been experiencing have been caused by a race between builds of these two directories, possibly overwriting each others' output file (static library).

### CODE REVIEW

**Comment by gebart** [comment]
whoops, I was a bit too tired, amended to fix new Travis failures.

**Comment by basilfx** [comment]
Out of curiosity, are the Travis errors 'malformed archive' errors in/after the linking step? If so, I experience similar errors while using `make -j8` on my local machine (quad core with SSD), even before #4762. Cleaning and rebuilding using `make -jN` fixes it for N = 1 and lowers the probability for N << 8.

**Comment by gebart** [comment]
The Travis errors are missing symbols. The Makefile dependency graph should ensure that the archives have finished generating before starting the linking recipe.. I think your errors are unrelated to this, unless there are more cases of the same module name in multiple directories. Is it the same archive(s) every time or is it completely random which one fails? I usually use make -j4 on my machine (quad core) and I have never seen the "malformed archive" error when building RIOT (so far).

Could you open a separate issue with your problems and add any relevant information (what system, compiler versions, etc)?

https://travis-ci.org/RIOT-OS/RIOT/jobs/108546524:
```
sizeof_tcb:nrf6310:
Building application "sizeof_tcb" for "nrf6310" with MCU "nrf51".
/home/travis/build/RIOT-OS/RIOT/tests/sizeof_tcb/bin/nrf6310/uart_stdio.a(uart_stdio.o): In function `uart_stdio_init':
/home/travis/build/RIOT-OS/RIOT/sys/uart_stdio/uart_stdio.c:76: undefined reference to `uart_init'
/home/travis/build/RIOT-OS/RIOT/tests/sizeof_tcb/bin/nrf6310/uart_stdio.a(uart_stdio.o): In function `uart_stdio_write':
/home/travis/build/RIOT-OS/RIOT/sys/uart_stdio/uart_stdio.c:94: undefined reference to `uart_write'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

The failing application is random, but the likelihood of it happening is large enough that it happens to 1 or 2 applications on every Travis build right now.

**Comment by haukepetersen** [comment]
Nice catch, this would indeed explain why I was not able to re-produce the Travis failures locally (I always build with the `-j1` default I guess). 

I was hoping to use just the one `periph` module and fill it from different builds might work, too bad its not.

ACK.

**Comment by haukepetersen** [comment]
and Travis already likes this -> go

**Pull request merged**
