### PR TITLE
shell: remove vtimer internals from rpl shell cmd

### PR DESCRIPTION
**Pull request by OlegHahm**
Apparently someone had difficulties to read the [documentation](http://doc.riot-os.org/structvtimer__t.html#details). ;-)

Without this #3525 won't work.

### CODE REVIEW

**Comment by cgundogan** [comment]
>Apparently someone had difficulties to read the documentation. ;-)

Well, the documentation says `should not`, not `must not` (:
Is there really no way to get the absolute value in a legitimate way? Otherwise, I will reluctantly ACK this for now to speed up the xtimer integration. Btw, the level of reluctancy can be reduced by tossing a :beer: (:

**Comment by OlegHahm** [comment]
> Well, the documentation says should not, not must not (:

This is not an RF. ;)

> Is there really no way to get the absolute value in a legitimate way?

I guess this question is better answered by @kaspar030.

> Btw, the level of reluctancy can be reduced by tossing a :beer: (:

Now, @kaspar030, and see [what you've done](https://github.com/RIOT-OS/RIOT/issues/3630#issuecomment-137542222)

**Comment by kaspar030** [comment]
> Is there really no way to get the absolute value in a legitimate way?

In vtimer, no. In xtimer, I'll create one.

**Comment by cgundogan** [comment]
see #3776, this is a semi-alternative to this PR. `tc` and `ti` has beedn replaced with `xtimer`. The `cleanup` is still a `vtimer`, though. I have to make the timer switch for RPL now in order to fix this. I guess this PR can be closed afterwards?

>In vtimer, no. In xtimer, I'll create one.
@kaspar030 can you also take a look at #3776? I used the `xtimer->target` to get the same behaviour as with the `vtimer` before.

**Comment by kaspar030** [comment]
> I used the xtimer->target to get the same behaviour as with the vtimer before.

That works if only the 32bit absolute value is required.

**Comment by OlegHahm** [comment]
@cgundogan, from my side we can close this PR immediately and focus on #3776.

**Comment by kaspar030** [comment]
@OlegHahm :beer: anyways!

**Comment by cgundogan** [comment]
#3778 obsoletes this PR

**Pull request closed without merging**
