### PR TITLE
git: handle patch files as binary

### PR DESCRIPTION
**Pull request by OlegHahm**
Thanks for the proposal, @kaspar030!

### CODE REVIEW

**Comment by kaspar030** [comment]
ACK. saving travis the work.

**Comment by benpicco** [comment]
But why? They are text files.

**Comment by OlegHahm** [comment]
See #4403

**Comment by OlegHahm** [comment]
I always found a diff of a diff very hard to decipher but if you think it's gonna be useful please go ahead.

**Pull request merged**
