### PR TITLE
sixlowpan: Handle short hardware addresses correctly

### PR DESCRIPTION
**Pull request by gebart**
Third attempt at fixing #2508

### CODE REVIEW

**Comment by cgundogan** [comment]
I tested this on native. Looks good in wireshark for short addresses. I have no experience in using long addresses however, can someone verify? @authmillenon ? @fnack Can you also test this PR regarding the udp checksum error?

**Comment by fnack** [comment]
Just tested the rpl_udp example on native with this PR. No checksum error :+1:

**Comment by gebart** [comment]
after studying the shell commands in rpl_udp I found this:

    ifconfig 0 set srcaddrmode long

I can now see that the long address is wrong.. it is set to 00-00-00-ff-fe-00-xx-xx

**Comment by gebart** [comment]
Long address is fine, I forgot to rebuild after switching between PR branches

**Comment by cgundogan** [comment]
I also tested long addresses with the command specified by @gebart .
wireshark looks fine, udp-server send/recv does also work.

**Comment by cgundogan** [comment]
@authmillenon I really would like to see your ACK on this one (quickly), because currently master is faulty and the rpl_udp example does not work without this fix

**Comment by authmillenon** [comment]
ACK when travis is high

**Pull request merged**
