### PR TITLE
cpu: Initial import of the STM32F2xx family

### PR DESCRIPTION
**Pull request by DipSwitch**
Initial implementation for the STM32F2xx family.

Mostly copied from the F4 and F1 ;)

Since almost all STM's share the same USART, I2C, SPI, DMA, TIM, PWM, ADC, RTC peripheral maybe they can be moved to a shared location?
So we don't have to merge each change to the other family? Special's (like the DMA, RTT and ADC of the F1 family can be overruled in the CPU specific location?)

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Great, I 'd love that! Question would be if one could also merge F2, F3, F4 ... drivers

**Comment by DipSwitch** [comment]
I'm quite sure thew can be merged :) The F1 (and maybe the F3) is the exception to the rest :)

**Comment by haukepetersen** [comment]
Looking good! I thought about merging the STM periph drivers for a number of times, but I always stopped perusing this when I got annoyed by the small little differences between all of them (sometimes the bits in some config registers are at slightly different positions, sometimes the regs have slightly different names in the vendor headers...). But it still might make sense if we could find a reasonable (readable and maintainable) solution

**Comment by OlegHahm** [comment]
> +10,163 −0 

this looks scary ;)

**Comment by haukepetersen** [comment]
` cpu/stm32f2/include/stm32f2xx.h`: +6,913 -0, the good old register def files...

**Comment by OlegHahm** [comment]
@DipSwitch, @haukepetersen, what's the latest here?

**Comment by PeterKietzmann** [comment]
I'd vote to keep this out of the next release. Also, did something go wrong during rebase or something?

**Comment by DipSwitch** [comment]
Haha not really wrong, but it is not needed to be merged for the next
release :) I meanly use it to verify and test the the new peripheral
implementations atm.

**Comment by kYc0o** [comment]
WIP -> postponed.

**Comment by kYc0o** [comment]
maybe we can close it in favor of #5397 ?

**Comment by miri64** [comment]
Since #4497 was merged I say this makes very much sense. If there is something in here that #4497 does not offer, please open a new PR with those features.

**Pull request closed without merging**
