### PR TITLE
net/fib: adapted to gnrc include style

### PR DESCRIPTION
**Pull request by haukepetersen**
Make the FIB use the same style of includes than the rest of the GNRC stack.

### CODE REVIEW

**Comment by BytesGalore** [comment]
ACK, thx

**Comment by cgundogan** [comment]
Ack Ack Ack

**Comment by haukepetersen** [comment]
Forgot quite some occurrences of `#include "ng_fib."` fixes.

@cgundogan, @BytesGalore: could you re-ack?

**Comment by BytesGalore** [comment]
re-ACK :) 
the old-stack aodvv2 and the shell-commands didn't came into my mind

**Comment by haukepetersen** [comment]
waiting with merging for #3334...

**Comment by haukepetersen** [comment]
closing this in favor of #3568

**Pull request closed without merging**
