### PR TITLE
netdev_ieee802154: add txpower and page

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This PR adds `txpower` and `page` to the `netdev_ieee802154_t` struct, since it'ss currently holding most PHY and MAC values (PIB and MAC respectively).

This settings are not device specific. Thus, it's necessary to keep them in a common place.
Although 2.4 GHz doesn't allow to set page (a.k.a only page 0 is supported), it's still required to expose it to the upper layer.

### Testing procedure
Probably only `make doc` and static checks.

### Issues/PRs references
#11483

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
AFAIK this interface is proposed by IEEE anyway, right? If so, could you give a pointer?

`ping6 -c 1000 -i 500 -s 1000 <dst IPv6>` still works between iotlab-m3 nodes. 

**current master** (6db5aa09cbbd46efd5a486f6fed6d81533b2a4f4) 
  text	   data	    bss	    dec	    hex	filename
  83804	    560	  18728	 103092	  192b4

**current master + 2 commits of this PR**
   text	   data	    bss	    dec	    hex	filename
  83816	    560	  18736	 103112	  192c8

-> Overhead is feasible and likely to reduce with #11483 anyway.

**Comment by miri64** [comment]
(just blocking to discuss this, if what I propose is the long-term plan anyways, you can dismiss my block)

**Comment by miri64** [comment]
See also https://github.com/RIOT-OS/RIOT/pull/9417

**Comment by jia200x** [comment]
> Doesn't this interfere with the plan to separate PHY and MAC layer? Shouldn't PHY stuff like chan, page, txpower rather go into its own netdev layer?

The long term plan is indeed to have a separate PHY and MAC layer. However, it's required to move PHY and MAC stuff out of the drivers first (so far `netdev_ieee802154` is carrying most of the PHY/MAC stuff)

**Comment by miri64** [comment]
@bergzand is that answer sufficient for you?

**Comment by bergzand** [comment]
> @bergzand is that answer sufficient for you?

After some out of band discussion with @jia200x and getting a better view on the goal, I'd say yes, definitely sufficient. I don't have a reason (anymore) to block this so go ahead :)

**Pull request merged**
