### PR TITLE
sys/shell/gnrc_netif: Fix a few blockers for sharing ifconfig shell

### PR DESCRIPTION
**Pull request by yarrick**
### Contribution description

When using general IPv6 functions, require only shared IPV6 module instead of gnrc version.

Print addresses using l2util functions in gnrc_netif instead of with gnrc wrappers.

### Testing procedure

* ifconfig with gnrc_networking example still works

```
> ifconfig
Iface  8  HWaddr: 24:0A:C4:E6:0E:9F  Link: up
          L2-PDU:1500  MTU:1500  HL:64  RTR
          RTR_ADV
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::260a:c4ff:fee6:e9f  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffe6:e9f
          inet6 group: ff02::1a
```

* tests/pkg/lwip ifconfig prints v6 info when 7160ed925813334f89875d0245980af1d25c6a5b applied

```
> ifconfig
Iface  ET0  HWaddr: 24:0A:C4:E6:0E:9F  Link: up
          L2-PDU:1500  Source address length: 6
          Link type: wired
          inet6 addr: fe80::260a:c4ff:fee6:e9f  scope: link
          inet6 addr: 2001:db8::260a:c4ff:fee6:e9f  scope: global
```

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
Looks good to me!

**Comment by yarrick** [comment]
Will rebase after #19973 submitted

**Comment by yarrick** [comment]
bors merge

**Comment by yarrick** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
