### PR TITLE
native: Take care of cleaning up networking properly on reboot

### PR DESCRIPTION
**Pull request by benoit-canet**
These patch touch both the old tap implementation and the new one while
taking care of being cross platform.

Tested on Linux and not on OSx

### CODE REVIEW

**Comment by authmillenon** [comment]
With the `git://` URL it's even lesser likely. HTTPS still allows Basic Auth (which can be stored), git protocol does not support push. Also, it's [slightly faster](https://git-scm.com/book/be/v2/Git-Internals-Transfer-Protocols).

**Comment by OlegHahm** [comment]
@authmillenon, wrong PR?

**Comment by authmillenon** [comment]
Yes …

**Comment by benoit-canet** [comment]
ping

**Comment by OlegHahm** [comment]
Can confirm that this works as intended on my Linux machine (Arch Linux, Kernel 4.1.3, gcc 5.2.0).

@thomaseichinger, @emmanuelsearch, @x3ro, can you confirm that it's working on OSX, too?

**Comment by thomaseichinger** [comment]
Works for OS X :+1:

**Comment by OlegHahm** [comment]
@benoit-canet, can you please rebase on current master? ACK as soon as Travis is happy (which should be the case after rebasing.)

**Comment by benoit-canet** [comment]
@OlegHahm: Done. Let hope the capricious cortex CI build will not bugg us.

**Comment by benoit-canet** [comment]
@OlegHahm : CI seems ok

**Comment by OlegHahm** [comment]
In this case I see no reason in not merging this now.

**Pull request merged**
