### PR TITLE
tests/xtimer_periodic_wakeup: all states

### PR DESCRIPTION
**Pull request by Josar**
This PR adds additional test for all states in the xtimer_periodic_wakeup() function.
Untill now there was no dependency of the parameter XTIMER_PERIODIC_SPIN and XTIMER_PERIODIC_RELATIVE which ensures to test all possible configuration.

in some cases only spinning and relativ timestamps where tested.

The test is now changed to test spinning, relativ timestamp and also absolut timestamping.

### CODE REVIEW

**Comment by cladmi** [comment]
I successfully ran the tests on the following boards:

* `samr21-xpro`: `Min/max error: 7/40`
* `iotlab-`: `Min/max error: 1/21`
* `wsn430-v1_4`: `Min/max error: 14/129`
* `arduino-zero`: `Min/max error: 7/46`

I did not review the code changes though.

**Comment by Josar** [comment]
Ping

**Comment by PeterKietzmann** [comment]
@cladmi I think this is a perfect Hack'n'ACK candidate, don't you think so?

**Comment by PeterKietzmann** [comment]
@cladmi now that you already ran some tests would you mind to provide a review?

**Pull request closed without merging**
