### PR TITLE
xtimer: Code refactoring and clean ups

### PR DESCRIPTION
**Pull request by gebart**
Various clean ups in the xtimer implementation to prepare for some functional enhancements.

 - Two commits are taken from @kaspar030's #5428, with ~~one~~ two fixups added by me for fixing some minor left overs in the configuration.
 - The xtimer.h header was getting a bit long and unwieldy so I decided to split it into one API declaration header and one implementation header for defining the inline functions.
 - The _lltimer functions are available from the xtimer.h header so they have to be prefixed in order to keep the namespace conventions. There is still an underscore prefix used to indicate that these functions are meant to be private and should not be called from user applications.
 - Renamed `XTIMER` -> `XTIMER_DEV` to make the macro less generic and more describing.
 - Renamed the type `timer_callback_t` -> `xtimer_callback_t`
 - Delete an old test `xtimer_shift_on_compare` which has no use any more.

### CODE REVIEW

**Comment by kaspar030** [comment]
Thanks, works for me and overdue! (Will make rebasing hard for me, though...)

ACK.

**Comment by kaspar030** [comment]
(pls squash)

**Comment by gebart** [comment]
@kaspar030 is the current commit list OK or should I squash further?

**Comment by gebart** [comment]
Added a missing closing brace in implementation.h for `extern "C" {` when building C++, immediately squashed.

**Comment by gebart** [comment]
rebased after #5610 was merged

**Comment by gebart** [comment]
Murdock is finally happy! @kaspar030 ACK holds?

**Comment by kaspar030** [comment]
Yes!

**Pull request merged**
