### PR TITLE
cpu, sam0_common: update vendor headers

### PR DESCRIPTION
**Pull request by smlng**
This PR updates the ASF CMSIS vendor header to version 3.35.1. It is based on #7631, so there is no need to modify the vendor header anymore. Some adaption of peripheral drivers are included as well.

Also have a look at #7621 and #7622.

### CODE REVIEW

**Comment by smlng** [comment]
@travisgriggs maybe you can have look at this one, too? Would be great to have this verified by testing, thx!

**Comment by photonthunder** [comment]
tried to test this but got a read only error on 

`TIMER_X_DEV.INTFLAG.bit.MC0 = 1` 

stating that MC0 is read only.  If you look at tc.h for the samd21 it state the reason for adding _I to the structure:
"// __I to avoid read-modify-write on write-to-clear register"

So in this particular case probably need to leave them.

**Comment by smlng** [comment]
@photonthunder I fixed all places where `*.INTFLAG.bit.*` is written by `*.INTFLAG.reg`, specifically there is no write to `MC0` anymore (see second commit in this PR). Also note that our CI (Mudock) would have found that error, too - but reported nothing. Maybe you need to update your fork or make a clean checkout of this PR?

**Comment by photonthunder** [comment]
@smlng sorry for confusion.  I didn't not realize that the changes were part of the CMSIS update and so when I merged a few features for my board with your code and picked the wrong version.  Everything works fine on the samd21 board.

**Comment by smlng** [comment]
@photonthunder no problem, thanks for testing!

**Comment by smlng** [comment]
@PeterKietzmann maybe you can test as well, if you have a samr21-xpro at hand - you *promised* to have a look at some PRs :stuck_out_tongue_winking_eye:

**Comment by smlng** [comment]
hey ho, anyone willing to approve and merge this one? It works as verified by testing.

**Comment by haukepetersen** [comment]
I am not so sure I like it too much. My main issue with this PR is to include a huge list of vendor header files for CPUs that are not used in RIOT (I missed to object when the headers for the sam0 MCUs were included)... The default way was and is to only include the vendor headers for the MCUs that are actually used...

**Comment by haukepetersen** [comment]
ups, seems like I commented the wrong PR, the comment above was meant to go into #7622...

**Comment by smlng** [comment]
So you @haukepetersen  are okay with updating/bump to a newer ASF version, here?

**Comment by haukepetersen** [comment]
I don't really see a reason for updating, but then again I don't see a reason for not. So no objections from my side. Though it would be nice if someone else could take a closer look at the changes in this PR.

**Comment by smlng** [comment]
Besides the updated vendor headers, I had to adapt some periph-drivers (see 2. commit) because the newer header made the bit-fields read-only hence write access only via `reg` and BIT_MASK. However, using read-only bitfields my allow to speed-up read operations by putting them in read-only registers instead of RW ones?

**Comment by haukepetersen** [comment]
The changes in the periph drivers make much sense - the `timer` and `rtt` drivers are both in an old and not optimized state anyway...

**Comment by haukepetersen** [comment]
By the way: looking at the diff of the PR illustrates quite well why I am not a big fan of blindly including every available vendor header of an MCU family instead of selectively only including the ones for the CPUs that are actually used with RIOT... It is easy to add new CPUs once they are actually used, and keeping track of PRs like this one is soo much easier if one has to only care for 3-4 headers instead of hundreds of them...

**Comment by smlng** [comment]
> looking at the diff of the PR illustrates quite well why I am not a big fan of blindly including 

you mean in contrast to #7621? Because for sam0 only the headers of used MCUs are includes, namely samd21, saml21, and samr21 (though the latter is actually using samd21, somehow). Anyway, here I only updated what was already there, for #7621 we can discuss what's needed and what not.

**Comment by haukepetersen** [comment]
All green -> go

**Pull request merged**
