### PR TITLE
pkg/nimble: improve initialization and add host thread

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
This PR makes NimBLE a little easier to use. It
- runs the host in a dedicated thread
- runs NimBLE's threads from `auto_init`
- adapts the example application accordingly

### Testing procedure
build and run `examples/nimble_gatt` to verify that the changes to not break anything

### Issues/PRs references
none

### CODE REVIEW

**Comment by haukepetersen** [comment]
almost missed: this PR is based on #10203

**Comment by miri64** [comment]
Please rebase.

**Comment by haukepetersen** [comment]
waiting for #10196, so a matter of minutes :-)

**Comment by miri64** [comment]
Ah sorry... i somehow was convinced that was already merged :astonished:

**Comment by haukepetersen** [comment]
wait a minute, the rebase did break things, will look into it.

**Comment by haukepetersen** [comment]
or just do `make clean` :-)

should be all good now.

**Comment by miri64** [comment]
Murdock issue is unrelated

**Pull request merged**
