### PR TITLE
sys: vtimer: introduce vtimer_(u)sleep_until

### PR DESCRIPTION
**Pull request by kaspar030**
Periodic wakeups are necessary for some applications.

Concept based on http://www.freertos.org/vtaskdelayuntil.html

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Will this maybe be part of the Timer Task Force or should we handle this PR separately?

**Comment by kaspar030** [comment]
@PeterKietzmann Well, we shouldn't put too much effort in debugging this now. The next timer will include this functionality.

**Comment by PeterKietzmann** [comment]
In my clean-up madness I was just looking for PRs to merge or close...

**Comment by OlegHahm** [comment]
Is this a wontfix?

**Comment by kaspar030** [comment]
new timer infrastructure will include this functionality.

**Comment by LudwigOrtmann** [comment]
Let's keep it open until the new timer structure is actually there.

**Comment by LudwigOrtmann** [comment]
Oh, I thought this was an issue, not a PR... sry for the noise.

**Pull request closed without merging**
