### PR TITLE
cord_standalone: Add a fire-and-forget version of cord_ep_register()

### PR DESCRIPTION
**Pull request by fengelhardt**
### Contribution description

This PR adds a the function `void cord_ep_standalone_register(sock_udp_ep_t *remote, char *regif)` to the submodule `cord_ep_standalone`. 
It uses the background thread of the standalone module, so the function operates asynchronously.

### Testing procedure

In the example `examples/cord_ep`, put the following code before the `shell_run()` call.

Replace `CONFIG_RD_PORT` with the port number of the RD, and `CONFIG_RD_ADDR` with the IPv6 address of the RD (as string constant). 

The node should register with the RD on startup, and a success message should show up tin the node's terminal.

```
    /* register endpoint at RD */
    sock_udp_ep_t remote;
    ipv6_addr_t addr;
    remote.family = AF_INET6;
    remote.netif = SOCK_ADDR_ANY_NETIF;
    if (ipv6_addr_from_str(&addr, CONFIG_RD_ADDR) == NULL) {
        puts("unable to parse RD address");
    }
    memcpy(remote.addr.ipv6, &addr.u8[0], sizeof(addr.u8));
    remote.port = CONFIG_RD_PORT;
    cord_ep_standalone_register(&remote, NULL);
```

### CODE REVIEW

**Comment by miri64** [comment]
I think you need to rebase this to `master`, but it can stay open :-).

**Comment by fengelhardt** [comment]
> I think you need to rebase this to `master`, but it can stay open :-).

Indeed - let me clean that up :)
Thank you!

**Comment by fengelhardt** [comment]
It is rebased now, but I can not re-open because it was a force-push. :(

**Comment by miri64** [comment]
Then just open a new one, please. I guess the PR should have been re-opened before the force push.

**Comment by maribu** [comment]
> Then just open a new one, please. I guess the PR should have been re-opened before the force push.

I was hit by this also once in the past: force-pushing prevented my from re-opening an accidentally closed PR :/

**Comment by fengelhardt** [comment]
Done!
Thanks a lot so far! :)

**Pull request closed without merging**
