### PR TITLE
sys/cbor: remove module

### PR DESCRIPTION
**Pull request by nmeum**
### Contribution description

Since #8467 has been merged a few hours ago we can finally "fix" #7800 by removing the homebrewed cbor module. This shouldn't cause too many problems since I honestly doubt that there are people out there who use this cbor module.

### Issues/PRs references

#7707
#7800
#8467

### CODE REVIEW

**Comment by bergzand** [comment]
@vincent-d Since the release branch is created, can we merge this or do you prefer to wait for the actual release?

**Comment by miri64** [comment]
@bergzand [As far as I can see](http://doc.riot-os.org/deprecated.html) this module isn't even deprecated yet. We should at least have it deprecated for a release cycle before we remove it, otherwise the few people that might use it might not be too happy about it ;-).

**Comment by bergzand** [comment]
@miri64 You're right :)

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/9023

**Comment by miri64** [comment]
@nmeum we only just deprecated it. Staying deprecated for at least one release cycle means, we include it into 2018.07 still, then we delete it ;-).

**Comment by nmeum** [comment]
> 2018.07 is out, @nmeum can you rebase please.

Will do!

**Comment by nmeum** [comment]
Done!

**Comment by miri64** [comment]
Otherwise I'm fine with this PR. Murdock as well, even with [tests running](https://ci.riot-os.org/RIOT-OS/RIOT/8793/92548515a33040fdce669fa35579071b5c7391c8/output.html).

**Comment by nmeum** [comment]
> There is also a mention of this module in sys/Makefile.include. Please remove as well.

Whoops :see_no_evil:, fixed it!

**Comment by miri64** [comment]
@nmeum this PR also needs rebase.

**Comment by nmeum** [comment]
Done. Is @vincent-d still around? Do we have to wait for his approval until we can merge this?

**Comment by vincent-d** [comment]
Sorry, I forgot this one. It was OK for me ;)

**Pull request merged**
