### PR TITLE
README.md: update CI badge

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Before I forget, this PR is updating the README links to the CI status badge and job details of the new Murdock instance.

### Testing procedure

Check the [README](https://github.com/aabadie/RIOT/tree/pr/readme_ci_status):
- the badge is displayed 
- the link points to the last nightly job run on master

### Issues/PRs references

This is part of the migration to the new Murdock instance

### CODE REVIEW

**Review by chrysn — APPROVED** [review]

**Comment by miri64** [comment]
Does it make sense to merge this?

1. ci-prod is not a full build in the nightlies
2. If I understand correctly, once ci-prod replaces ci, it will point to the ci.riot-os.org name again.

**Comment by aabadie** [comment]
> Does it make sense to merge this?

I think so :) but not before ci-prod.riot-os.org becomes ci.riot-os.org and after the urls in this PR are updated accordingly. The PR is essentially here to show that this feature won't be lost (and that I won't forget it).

**Comment by miri64** [comment]
Then let's set the appropriate label for now.

**Review by miri64 — DISMISSED** [review]
Preventing accidental merges before ci-prod became ci. Feel free to dismiss this review, once this is the case.

**Comment by aabadie** [comment]
Once the DNS update is ready (ci.riot-os.org pointing to the new Murdock), this PR can be merged.

**Pull request merged**
