### PR TITLE
3269 fix msg init queue calls

### PR DESCRIPTION
**Pull request by benoit-canet**
This series is done to close the just openned #3269.

It will hopefully fix a couple of crashes and erratic behavior.

### CODE REVIEW

**Comment by Kijewski** [comment]
Nice catch. ACK if Travis is happy.

**Comment by haukepetersen** [comment]
Nice one - ACK here, too. Travis is happy -> go!

**Comment by kaspar030** [comment]
Wow, this might have caused a lot of vtimer_msg's crashes... Really nice catch.

**Comment by OlegHahm** [comment]
@kaspar030, but only for the tests.

**Pull request merged**
