### PR TITLE
crypto: remove skipjack support

### PR DESCRIPTION
**Pull request by Kijewski**
Unused, unmaintained, buggy code for an unknown algorithm.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Well, I would not call it an unknown algorithm and I don't know if it is buggy, but with unmaintained and (probably) unused, you're likely right.

**Comment by Kijewski** [comment]
Probably I cannot call algorithms unknown when they have a [wikipedia entry](https://en.wikipedia.org/wiki/Skipjack_%28cipher%29). :)

Should I change the commit message? I don't think that shipping skipjack serves any purpose.

**Comment by kaspar030** [comment]
Maybe change "unknown" to "barely used"?

**Comment by OlegHahm** [comment]
Any objections against removing this for the release?

**Comment by LudwigOrtmann** [comment]
I'm in favour of this removal.

**Comment by OlegHahm** [comment]
Well then: ACK and go!

**Pull request merged**
