### PR TITLE
cpu: samd21: Move samd21 to samr21

### PR DESCRIPTION
**Pull request by keestux**
This PR moves the current cpu/samd21 to cpu/samr21 so that we can more easily add other SAMD21 and SAMR21 variants. This change is also needed to be able to:

- update SAMx21 include files from ASF (Atmel Software Factory)
- add new boards, e.g. SODAQ boards, Autonomo and SODAQONE (and Arduino Zero, etc)

Furthermore the modules in cpu/samr21/periph have been moved to cpu/sam21_common, so that they can be shared between SAMD21 and SAMR21 (and maybe even SAML21).

The changes were only tested by building the hello-world example for samr21-xpro.

### CODE REVIEW

**Comment by kaspar030** [comment]
waitaminute. the samr21 is a variant of samd21. so why move it to samr21?
and if the saml21 cannot share the periphs, they cannot go into sam21_common.

@keestux I thought I understood that only minor changes were needed in order to get the Autonomo working.

**Comment by bapclenet** [comment]
samr21-xpro is a board with a samd21 cpu, samr21 is not a cpu and shouldn't be inside /cpu.
When you are talking about variants, do you mean samd21e18a, samd21j18a and so on? If yes, then we should edit samd21 to samd21g18a.
For your new board, you should create a new board in /board and connect it to a new CPU (samd21XXXX) in /cpu
And you could share periph drivers inside cpu/samd21_common
@kaspar030, what do you think about that?

**Comment by kaspar030** [comment]
> When you are talking about variants, do you mean samd21e18a, samd21j18a and so on? If yes, then we should edit samd21 to samd21g18a.

That's what I meant. I hoped that these are similar enough that a shared samd21/ folder would be sufficient. Usually the variants mostly differ in the amount of RAM/ROM/peripherals.

**Comment by PeterKietzmann** [comment]
In our mail conversation we concluded that differences are rather small an that a selective include for the CPU mode should be fine, like e.g. [here](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32f3/include/cpu_conf.h#L27). Memory sizes can be adjusted by separate linker scripts, compare [here](https://github.com/RIOT-OS/RIOT/tree/master/cpu/stm32f3/ldscripts). Did I misunderstand something?
Who can answer that question: Can sam**l**21 and sam**d**21 shar the same peripheral driver code base?
@kaspar030 may I assign you? Well, I'll just do it ;-). Reassign me if your not comfortable with that.

**Comment by kYc0o** [comment]
I agree too, the code can be shared both for CPUs and for boards IMO, but definitely samr21 is not a cpu. I did something similar for atmega CPUs in #5529, then I'll try to generalise for arduino boards with similar characteristics

**Comment by keestux** [comment]
@kaspar030 @PeterKietzmann  let's restart.
I appreciate everybody's concern for a new "cpu". So forget about the PR.

Perhaps it is doable to create an extra subdirectory in cpu/samd21 where we can add the samd21 and samr21 trees from ASF sam0/utils/cmsis. (Did anyone bother to look at it?) Preferably copy an unmodified copy of that tree and administrate which ASF version was used.

**Comment by keestux** [comment]
Did we all notice that it is cpu/sam21_common, i.e. without the 'd' ?

**Comment by kaspar030** [comment]
> Did we all notice that it is cpu/sam21_common, i.e. without the 'd' ?

I hope. It is supposed do hold stuff shared by samd21 and saml21. ;)

**Comment by keestux** [comment]
Hmm, OK. I didn't know that. Shouldn't we add a small Readme then?

**Comment by keestux** [comment]
Shall I close this PR? I have a new one lined up.

**Comment by aabadie** [comment]
> Shall I close this PR? I have a new one lined up.

@keestux, I would say yes but don't forget to mention this one in the new PR.

**Comment by PeterKietzmann** [comment]
@keestux I think I prefer your second proposal. You mean to provide vendor files in subdirectories in the [include](https://github.com/RIOT-OS/RIOT/tree/master/cpu/samd21/include) folder, right? In my personal opinion it should be fine at that location to give includes the "correct" name to indicate the single CPU version. Let's keep this PR open until the new one is there. Will close then.

**Comment by PeterKietzmann** [comment]
Closing in favour of #5556

**Pull request closed without merging**
