### PR TITLE
esp32/eth: Don't overwrite queued event with RX packet

### PR DESCRIPTION
**Pull request by yarrick**
### Contribution description

If there is an event to be handled by `_esp_eth_isr()`, don't
overwrite it if a new packet has been received.

In my testing, all `SYSTEM_EVENT_ETH_CONNECTED` events except the first
are immediately followed by at least one `SYSTEM_EVENT_ETH_RX_DONE` event.
This causes the `SYSTEM_EVENT_ETH_CONNECTED` to not get handled, and the
IP stack will not be notified of the new link state.

Protect the other events by dropping the packet instead. If an earlier
unhandled `SYSTEM_EVENT_ETH_RX_DONE` event exists, overwrite it with the
newer packet.

I only saw this happen with lwIP and not with GNRC - I am not sure why.
But it still is a race waiting to happen. The nice long term solution
is probably to have a queue of unhandled events, allowing them all to
be processed once there is time.

### Testing procedure

Flash an ESP32 board with ethernet with `tests/lwip` including #16082. Observe that without this change,
the link state will be stuck as down after the second link up event (first one is at startup or when cable is connected).
With this change, the link state is correctly reflected no matter how many times the cable is removed and reconnected.

### Issues/PRs references

Made visible by PR #16082

### CODE REVIEW

**Comment by jia200x** [comment]
I don't have hardware to test it, but the fix sosunds reasonable. This is what we do in most network devices anyway

**Comment by yarrick** [comment]
I could also try a bigger change and remove the event field, and instead use `rx_len` to keep track of if a packet has been read, and add two booleans for link up/down signaling. The isr method would then check all these in turn instead of switching on the event.

**Comment by jia200x** [comment]
> I could also try a bigger change and remove the event field, and instead use rx_len to keep track of if a packet has been read, and add two booleans for link up/down signaling. The isr method would then check all these in turn instead of switching on the event. (if calling netdev.event_callback multiple times from the isr is fine)

IIUC this means keeping track of the events and then handle those to the upper layer instead of generating a single event each time the ISR is executed?

I think it's good to "tag" these events if the events can be somehow concurrent and then leave the upper layer to execute the events one by one.

> (if calling netdev.event_callback multiple times from the isr is fine

You mean calling it from ISR context or from netdev's `isr` function?
As it is now, the only netdev event that's safe to trigger from ISR is `NETDEV_EVENT_ISR` (triggered via `netdev_trigger_event_isr`. Some events on TX can also be generated on ISR if using #14660 . On RX, triggering `NETDEV_EVENT_RX_DONE` from ISR triggers GNRC netif in ISR context. This is not desied, since packet allocation might add some overhead.

But if you plan to tag several events and then trigger them once via `NETDEV_EVENT_ISR`, it's indeed possible to call multiple times `event_callback` in the same netdev's `isr` function (but this is executed in thread context)

**Comment by maribu** [comment]
Maybe it makes sense merge this fix as is first and do the bigger change as follow up?

Note: There is a [PR open](https://github.com/RIOT-OS/RIOT/pull/15821) that will change the situation with signalling events from ISR, so that any kind of event can be signaled, not only `NETDEV_EVENT_ISR` - but so far only for GNRC. But I think that the other stacks will follow suit swiftly. So if this would help with the follow, it might be worth wait a bit for that to get upstream?

**Comment by yarrick** [comment]
I was thinking about having the `isr` method using the `event_callback` many times in one invocation.

Merging this now and doing a more complete solution later is fine with me.

**Review by maribu — APPROVED** [review]
ACK. I don't have any ESP32 with Ethernet to test, but the reasoning and code is sane. I think we can have this in untested.

**Pull request merged**
