### PR TITLE
cbor: add API to encode non null-terminated byte strings

### PR DESCRIPTION
**Pull request by tfar**

### CODE REVIEW

**Comment by tfar** [comment]
Builds for me. Don't know what's up with CI.

**Comment by kaspar030** [comment]
@tfar CI only builds if the tag has been set.

**Comment by tfar** [comment]
@kaspar030 ahh. maybe the tag should also be settable for _Collaborators_.

**Comment by OlegHahm** [comment]
@tfar, 1. afaik Github settings do not allow this and 2. it is on purpose that a maintainer has to "unlock" a PR to avoid Travis being overloaded.

**Comment by tfar** [comment]
@OlegHahm Ah. Okay. Maybe you could adjust the user experience, so it doesn't look like the build failed but more that it didn't build anything yet.

**Comment by OlegHahm** [comment]
Agreed, but right now I have no clue how this could be achieved, but in general the idea is to leave Travis behind ASAP anyway and have a dedicated build-and-test infrastructure for RIOT anyway. This label is more a kind of workaround to avoid a huge Travis backlog.

**Comment by PeterKietzmann** [comment]
I'm fine with this so ACK in general. I'm just wondering if we really need both functions: `cbor_serialize_byte_string()` and `cbor_serialize_byte_stringl()`....

**Comment by PeterKietzmann** [comment]
Ah, Travis is already happy.

**Pull request merged**
