### PR TITLE
boards: removed support for pca1000[0|5] (gnrc_netif2 backport)

### PR DESCRIPTION
**Pull request by miri64**
To solve the merge conflict in #7925, this backports #7979 to #7925. The merge in d683afd has to stay in I'm afraid, so git can keep track of the move of `test/gnrc_netif2` to `test/gnrc_netif`. I'm not happy about this approach, but save from rebasing (which again: would require re-reviewing all changes that were contributed to #7925) this seems to be the sanest approach.

### CODE REVIEW

**Comment by miri64** [comment]
static tests fail because Murdock is doing a rebase instead of a merge so my git history hack does not apply for it. Since we merge this PR anyways instead of rebasing it, I would say: merge anyway. Can I get an 'Aye'?

**Comment by haukepetersen** [comment]
'Ei'

**Comment by miri64** [comment]
:egg:

**Comment by miri64** [comment]
Wasn't the sanest idea after all -.-... will revert this

**Comment by miri64** [comment]
For later reference: this PR was removed without any trace from the git history in #7925 after it was merged.

**Pull request merged**
