### PR TITLE
cpu/kinetis_common: moved drivers to periph subdir

### PR DESCRIPTION
**Pull request by haukepetersen**
I always find it confusing, that the Kinetis based boards are the only ones, having their peripheral driver implementations not in a `periph` subdir. So doing something as `subl RIOT/cpu/*/periph/adc.c` to open all ADC implementations in my editor always misses the Kinetis ones...

### CODE REVIEW

**Comment by gebart** [comment]
I agree, please rebase

**Comment by haukepetersen** [comment]
rebased

**Comment by haukepetersen** [comment]
rebased again.

**Comment by haukepetersen** [comment]
fixed possible null ptr ref in the gpio driver as pointed out by cppcheck

**Comment by gebart** [comment]
ACK for the change, why doesn't travis pick it up?

**Comment by haukepetersen** [comment]
now it did

**Comment by OlegHahm** [comment]
Took some time.

**Comment by haukepetersen** [comment]
Travis is happy -> go

**Pull request merged**
