### PR TITLE
kinetis_common: Refactor GPIO implementation

### PR DESCRIPTION
**Pull request by gebart**
This is a refactor of the GPIO implementation on Kinetis to follow the updated GPIO interface in #3095.

This implementation uses a linked list to handle the interrupt callbacks instead of statically allocating a few bytes per pin, this keeps the RAM usage down when not using all pins as interrupt inputs.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Compare https://github.com/RIOT-OS/RIOT/pull/3996#issuecomment-145349321

**Comment by gebart** [comment]
Depends on #3847

**Comment by gebart** [comment]
(Updated the commit message to explain what this does)

**Comment by PeterKietzmann** [comment]
I could test this on the phy-board soon, if it speeds up things. @gebart is this PR still waiting for an other?

**Comment by gebart** [comment]
@PeterKietzmann not waiting any more

**Comment by gebart** [comment]
rebased on latest master

**Comment by gebart** [comment]
ping @PeterKietzmann 
Could you test on the phytec board? Do you have a freedom k64 board as well?

**Comment by gebart** [comment]
Rebased after #3485 was merged, updated GPIO pin for NVRAM CS, immediately squashed

**Comment by jfischer-phytec-iot** [comment]
I can test it tomorrow.

**Comment by PeterKietzmann** [comment]
Aaah, dammit. Sorry for the delay. @jfischer-phytec-iot did you already test anything here?

**Comment by jfischer-phytec-iot** [comment]
@gebart There is somewhere a bug when testing with init_int. Maybe I can dig deeper today afternoon.

**Comment by PeterKietzmann** [comment]
@gebart, @jfischer-phytec-iot , @haukepetersen I tested some pins one the pba-d-01-kw2x with the functionalities from tests/periph_gpio. Everything went well. I don't have time for a complete review here

**Comment by PeterKietzmann** [comment]
@jfischer-phytec-iot what is the bug looking like? I didn't see it

**Comment by jfischer-phytec-iot** [comment]
@PeterKietzmann Please try ```init_int 3 1 0 1``` ("a Button") out.

**Comment by jfischer-phytec-iot** [comment]
```
 port->PCR[pin] &= ~(PORT_PCR_IRQC_MASK); /* Disable interrupt */
BITBAND_REG32(port->PCR[pin], PORT_PCR_ISF_SHIFT) = 1; /* Clear interrupt flag */
port->PCR[pin] |= config->irqc; /* Enable interrupt */       /* <= BUG*/
config->cb = cb;
config->arg = arg;
config->irqc = irqc;
/* Allow the callback to be found by the IRQ handler by setting the proper
```

**Comment by jfischer-phytec-iot** [comment]
@gebart @PeterKietzmann https://github.com/gebart/RIOT/pull/7

**Comment by gebart** [comment]
rebased on latest master, added the ISR fix by @jfischer-phytec-iot

**Comment by gebart** [comment]
@jfischer-phytec-iot does the current state of this PR work on your test set up?

**Comment by PeterKietzmann** [comment]
I can confirm that the button didn't trigger an interrupt **without** Johan's PR but does work with it.

**Comment by jfischer-phytec-iot** [comment]
@gebart We test it, still need about 30 minutes.

**Comment by jremmert-phytec-iot** [comment]
Just tested the communication between two pba-d-01 boards with this PR -> works fine.

**Comment by jfischer-phytec-iot** [comment]
@gebart ACK, please throw cpu/stm32f1/periph/gpio.c out.

**Comment by gebart** [comment]
rebased, squashed and threw out the unrelated change in stm32f1

**Comment by PeterKietzmann** [comment]
Happy times and go

**Pull request merged**
