### PR TITLE
drivers/gpio: renamed GPIO(x,y) macro to GPIO_PIN

### PR DESCRIPTION
**Pull request by thomaseichinger**
Replaces #3847.

### CODE REVIEW

**Comment by gebart** [comment]
Typo: GPIO_PINTPA in some locations

**Comment by thomaseichinger** [comment]
@gebart Thanks, should be fixed.

**Comment by thomaseichinger** [comment]
Rebased on current master and adopted newly introduced GPIO macros.

**Comment by gebart** [comment]
OK to squash

**Comment by gebart** [comment]
ACK

I am assuming from inspecting the changeset by eye that all platforms that still build should still work if they were working before and we do not need to test on actual hardware on all platforms, do you agree @thomaseichinger?

**Comment by thomaseichinger** [comment]
Squashed and removed the label.
@gebart I tested with the boards I had laying around so by induction rule I consider the others working too. :grinning: Especially as this is not a semantic change.

**Comment by thomaseichinger** [comment]
Travis passed and ACKed, go.

**Pull request merged**
