### PR TITLE
drivers: periph: add generic spi fallbacks

### PR DESCRIPTION
**Pull request by kaspar030**
I've seen multiple definitions of basically the same functions, so I factored them out into a common module.

There's room for more, e.g., the locking of SPI buses could be unified in the same way.

For spi_transfer_reg*, I've chosen the implementation with the most eror checking, though I'm not sure that is actually needed or even harmful.

### CODE REVIEW

**Comment by kaspar030** [comment]
(launching CI to spot build errors)

**Comment by kaspar030** [comment]
- rebased

**Comment by haukepetersen** [comment]
I actually had something similar in mind once, but never got to it. In #3216 I actually already improved those implementations a bit, though the PR slipped pretty far down on my prio list... 

ACK once squashed and Travis is happy.

**Comment by kaspar030** [comment]
and GO.

**Pull request merged**
