### PR TITLE
core: fix typo in kernel_macros.h

### PR DESCRIPTION
**Pull request by grandmou**
New pull request from the URL given by Kijewski

### CODE REVIEW

**Comment by kaspar030** [comment]
@grandmou Nice, congrats to your first pull request!

There are some formal things:

- you need to fix the commit message, so it says what it does. Also, prepend the subsystem you're working on. In this case, something like "core: fix typo in kernel_macros.h"

- same for the PR message

- you need to add labels. I can do that for this PR.

**Comment by grandmou** [comment]
Yeah! Thanks kaspar030 :)
I renamed the PR, and amended the comment of the commit, pushed it to my forked repository. Do I have to do something else?
I'll have a closer look at the available labels next time.

**Comment by kaspar030** [comment]
Now there's a merge commit. :)

**Comment by gebart** [comment]
On Jul 10, 2015 8:17 PM, "Kaspar Schleiser" <notifications@github.com>
wrote:
>
> @grandmou Nice, congrats to your first pull request!
>
> There are some formal things:
>
> you need to fix the commit message, so it says what it does. Also,
prepend the subsystem you're working on. In this case, something like
"core: fix typo in kernel_macros.h"
>
> same for the PR message
>
> you need to add labels. I can do that for this PR.

Only RIOT maintainers can add labels to the issues and PRs. (it's a Github
restriction)

**Comment by OlegHahm** [comment]
@grandmou, gonna rebase?

**Comment by BytesGalore** [comment]
@grandmou could you squash your 3 commits, then the CI will be triggered :)
And -> ACK when the CI is happy

**Comment by grandmou** [comment]
Hey, just woke up from hibernation. When I rebase (git rebase -i master), I don't see my previous commits, just "noop", and comments below.

Shouldn't I see something like:
pick fb554f5 This is commit 1
pick 2bd1903 This is commit 2
pick d987ebf This is commit 3

And that change those lines to:
pick fb554f5 This is commit 1
squash 2bd1903 This is commit 2
squash d987ebf This is commit 3

Sorry for these noob questions

**Comment by BytesGalore** [comment]
yes, you should see that kind of lines and change them just as you described :)
> I don't see my previous commits, just "noop"

probably you are not on the right branch(?)

**Comment by BytesGalore** [comment]
@grandmou you can try:
```
git rebase --interactive HEAD~3
```
which tells git to start rebasing the last 3 commits.
I experienced also `noop`s while directly rebasing on a rebased branch. 
The above line helped me to convince git that I really want to rebase my commits :).

**Comment by PeterKietzmann** [comment]
@grandmou did you manage to handle the git stuff? If it simplifies things, I would also agree to close this PR and open a new one (should be easy as your changes are small). For that, you should strongly follow the steps described in the [Development procedures](https://github.com/RIOT-OS/RIOT/wiki/Development-procedures) or in [Contributing to RIOT](https://github.com/RIOT-OS/RIOT/wiki/Contributing-to-RIOT) (under Contributing Code). The [git cheatsheet](https://github.com/RIOT-OS/RIOT/wiki/Git-cheatsheet) might help you again...

**Comment by PeterKietzmann** [comment]
Done in #4337

**Pull request closed without merging**
