### PR TITLE
boards/nucleo: include arduino pinmap in board definitions

### PR DESCRIPTION
**Pull request by aabadie**
Discovered this issue while looking at #6787.

### CODE REVIEW

**Comment by smlng** [comment]
are you sure that all nucleos have the arduino pinmapping? I haven't worked with these boards nor do I have them available for testing here, so just asking - cause we have and had trouble with general/common definitions in other places.

**Comment by smlng** [comment]
for instance the nucleo-f302 does not use the `board_common.h`, so pinmap does not apply.

**Comment by aabadie** [comment]
> for instance the nucleo-f302 does not use the board_common.h, so pinmap does not apply.

Looks like an issue. AFAIR, the nucleo-f302 doesn't have the exact same pinout. Will check and amend.

**Comment by aabadie** [comment]
on nucleo-f302, the SPI is not on the same pins. I'll push an update here.

**Comment by aabadie** [comment]
@smlng, just pushed an update. Can you test again #6787 with nucleo-f302 removed from blacklisted boards ?

**Comment by smlng** [comment]
looks good in #6787

**Comment by aabadie** [comment]
> maybe squashed?

I created the commits with atomicity in mind. I think they are fine.

**Comment by smlng** [comment]
okay fine, lets wait for murdock, then ACK and GO ...

**Pull request merged**
