### PR TITLE
shell_commands: port ifconfig netstats neighbor for gnrc_netif2 

### PR DESCRIPTION
**Pull request by bergzand**
As requested in #7449.

Based on #7404 and #6873 

Although the output should not have changed from #7449, I was unable to test the output for the command since I could not get a test with shell and netif2 working. Will try again and report tomorrow.

### CODE REVIEW

**Comment by miri64** [comment]
Thank you :-).

**Comment by miri64** [comment]
> Although the output should not have changed from #7449, I was unable to test the output for the command since I could not get a test with shell and netif2 working. Will try again and report tomorrow.

Take an example that has the `ifconfig` command and compile it with `USEMODULE=gnrc_netif2` set in the environment. The counters will not increase, since the real integration into GNRC only starts at #7424, but at least the output should be testable.

**Comment by bergzand** [comment]
Tested and fixed, should be good now.

**Comment by miri64** [comment]
Needs rebase ;-).

**Comment by bergzand** [comment]
Do you mind if I pick this one up when the PR this is depending on has progressed a bit more?

**Comment by miri64** [comment]
Not at all. Just notify me, when you got back to this.

**Comment by miri64** [comment]
Please rebase ;-)

**Comment by miri64** [comment]
Ping @bergzand?

**Comment by bergzand** [comment]
@miri64 I might have ignored this a bit. Anyway, this PR is useless without #6873. I don't mind closing this one and maybe reopen it in the future if it happens to become useful then.

**Comment by miri64** [comment]
Ok, then let's close this as memo for now so it is off my monthly radar ;-).

**Pull request closed without merging**
