### PR TITLE
gnrc_netif: receive packets in a loop

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The `NETDEV_EVENT_RX_COMPLETE` event means that we received *at least* one packet.
If there was another packet received we also have to process it, as otherwise it will be stuck in the RX buffer until the next packet arrives:

```
2022-06-08 19:15:52,658 - INFO # > ping -i 2000 fd11:a000::e858:4ed2:564e:215b
2022-06-08 19:15:52,658 - INFO # 
2022-06-08 19:15:54,667 - INFO # 12 bytes from fd11:a000::e858:4ed2:564e:215b: icmp_seq=0 ttl=64 time=2001.958 ms
2022-06-08 19:15:56,667 - INFO # 12 bytes from fd11:a000::e858:4ed2:564e:215b: icmp_seq=1 ttl=64 time=2001.959 ms
2022-06-08 19:15:59,658 - INFO # 
2022-06-08 19:15:59,662 - INFO # --- fd11:a000::e858:4ed2:564e:215b PING statistics ---
2022-06-08 19:15:59,667 - INFO # 3 packets transmitted, 2 packets received, 33% packet loss
2022-06-08 19:15:59,672 - INFO # round-trip min/avg/max = 2001.958/2001.958/2001.959 ms
```

### Testing procedure

IMG_0176

The issue can be triggered by heavy network traffic, e.g.

    sudo ping -f fd11:9c00::e858:4ed2:564e:215a
    sudo ping -A fd11:9800::e858:4ed2:564e:215b

With this patch, we don't have packets stuck in the RX buffer after that anymore

```
2022-06-13 15:42:47,841 - INFO # > ping fd11::1
2022-06-13 15:42:47,841 - INFO # 
2022-06-13 15:42:47,855 - INFO # 12 bytes from fd11::1: icmp_seq=0 ttl=61 time=8.472 ms
2022-06-13 15:42:48,855 - INFO # 12 bytes from fd11::1: icmp_seq=1 ttl=61 time=8.367 ms
2022-06-13 15:42:49,856 - INFO # 12 bytes from fd11::1: icmp_seq=2 ttl=61 time=8.557 ms
2022-06-13 15:42:49,856 - INFO # 
2022-06-13 15:42:49,859 - INFO # --- fd11::1 PING statistics ---
2022-06-13 15:42:49,864 - INFO # 3 packets transmitted, 3 packets received, 0% packet loss
2022-06-13 15:42:49,869 - INFO # round-trip min/avg/max = 8.367/8.465/8.557 ms
```

### Issues/PRs references

alternative to #18201
requires #18066 to not produce incomplete frames with SLIP (as that will currently just return `tsrb_avail()` which might not be a complete frame.)

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK. The change is trivial and brings behavior and expectations of `sys/event` back in alignment.

I'm sure hell will break loose once this is merged, because it will expose bugs like the one mentioned in slip. However, once those bugs are exposed they can be fixed.

Also, some drivers actually emit another `RX_COMPLETE` event at the end of the RX handler when the queue is not drained. This will be no longer needed. But those cleanups can be done later on.

**Comment by benpicco** [comment]
Jup just did a random check, `mrf24j40` disables RX on the first `_recv` (with `buf == NULL && len == 0` and enables it again whhen the second `_recv` is done. `at86rf2xx` does something similar and enables frame buffer protection in `_recv`.

**Comment by jia200x** [comment]
I'm a little bit scared of this change as it is.
Most drivers (including netdev_ieee802154_submac) were designed to process one `_recv` event after the ISR. In case of the Submac, there's even a strict state machine (that will assert if something goes wrong).
Therefore, I think this change will definitely break some stuff.

Why don't we simply trigger NETDEV_EVENT_ISR from the driver, if there are more pending packets? That way the driver can handle its internal logic if it has a packet queue (which is not common e.g in 802.15.4 transceivers)

**Comment by benpicco** [comment]
So like #18201?

**Comment by jia200x** [comment]
> So like #18201?

Yes, something in that direction, but I would call `netdev_trigger_event_isr` instead of triggering `NETDEV_EVENT_RX_COMPLETE`. Otherwise it adds a recursive call to `_recv` (which can be problematic if you implement something with state machines on top or you need to trigger other events in the future such as `NETDEV_EVENT_RX_START`)

**Comment by benpicco** [comment]
closing in favor of #18201

**Pull request closed without merging**
