### PR TITLE
[port][arm] Port RIOT to ARMv7-A S5P4418 platform

### PR DESCRIPTION
**Pull request by kamejoko80**
Hello everyone,

This is my port for ARMv7-A architecture, Samsung S5P4418 ARM cortex-9 SoC and JF4418 custom board.
I've also tested with MRF24J40MA RF module with gnrc_networking example and see it worked well.

Brief guide how to deploy the image run on the development board :

1> Build the RIOT application :
   $ make BOARD=jellyfish
   Convert hex file to binary file .
   $ arm-none-eabi-objcopy -O binary gnrc_networking.elf gnrc_networking.bin

2> Deploy and run RIOT :
   Use u-boot to load the binary image gnrc_networking.bin into DDR RAM at address 0x48000000 then execute command :
   u-boot> go 0x48000000
   
My custom board is based on S5P4418 SoC and compatible with NanoPi2 board, I'll test on NanoPi2 later.

I'm a RIOT newbie, please help review my task, thank you very much.

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@kamejoko80 First of all, thank you for your time and code proposal. 
I fear however we will not be able to merge the proposed support to RIOT's main repository. Let me quickly explain why.

1. With RIOT we mostly try to cover platforms that can't run Linux. Your platform is by magnitudes more capable than all our other platforms and thus out of scope for RIOT in our opinion. We fear we won't have enough maintainer time to take care of this CPU.
2. Your PR includes a fair amount of code licensed under GPL. Using this at any step of the build process would mean that any application would have to be open sourced too.
3. As a rule of thumb we only try to take platforms into our tree that are kind of easily accessible, I couldn't find any possibility to order a Jellyfish (JF4418) board online.

That said, we are happy to receive and review contributions for any other platform in scope.

**Comment by kamejoko80** [comment]
Hi thomaseichinger,

No problem, thanks so much for your reply.

I'll keep synchronizing with RIOT mainline and continue developing in my own branch.
I have one question, it is possible to use RIOT's Jenkins automation build/checking without creating a pull request?

Thank you very much.

**Comment by miri64** [comment]
> I see RIOT project plan here: 
> https://github.com/RIOT-OS/RIOT/wiki/SWP14
> "Project: ARM Cortex A8 port for RIOT"

This site was for a student project at FU Berlin in the summer term of 2014. Since then our thinking changed quite a bit. @emmanuelsearch can we remove that wiki page?

> BTW, I have one question, it is possible to use RIOT's Jenkins automation build/checking without creating a pull request?

We are actually in the process of phasing out Jenkins in favor for Murdock(2). But in general we would appreciate to either test your setup locally first or maybe even setup your own CI infrastructure, since build time on the CI is precious to us (we are constantly trying to optimize for faster build times to be able to merge PRs faster). Hope you can understand.

**Comment by kamejoko80** [comment]
Hello miri64,

Yes, I see.
I'm very sorry for bothering you in recent days. 
Now you can close my pull request to reduce the CI workload.
Thank you very much.

**Comment by kaspar030** [comment]
> But in general we would appreciate to either test your setup locally first or maybe even setup your own CI infrastructure, since build time on the CI is precious to us (we are constantly trying to optimize for faster build times to be able to merge PRs faster). Hope you can understand.

I think if the goal is keeping an out-of-tree port checked CI-checked, we should find a solution. Murdock2 makes it very easy to watch more repositories (if they share the same build scripts), and also to only build a subset (e.g., only one board). @kamejoko80 I'll try to bring this up on the next CI-related meetings.

**Comment by miri64** [comment]
> But there is no problem, I'll keep synchronizing with RIOT mainline and continue developing in my own branch.

Can we close this PR then?

**Comment by kamejoko80** [comment]
OK, you can close the PR now.
Thank you.

**Pull request closed without merging**
