### PR TITLE
kconfig explore all allowed boards on all apps

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

Run all non-blockisted boards for every kconfig enabled app only during nightlies.
This should find any corner cases slipping through the regular testing (currently only one on the ublox-c030-u201 board due to incorrect makefile modelling).  This should also have no impact on regular CI times, only the nightly will be longer (since it will eventually double the jobs).

### Testing procedure

Check to see that the removeme commit, forcing nightly, tests a board that would not normally be tested for kconfig.

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Well surprisingly things are looking very good. The only issue was with the ublox-c030-u201 makefile.dep modelling.  I think it just wasn't done correctly.

I removed it and added now think we can run all tests on all non-blocklisted boards for the nightlies.  I added a removeme commit to test if the nightly flag would actually run it properly.

**Comment by MrKevinWeiss** [comment]
[This shows](https://ci.riot-os.org/RIOT-OS/RIOT/17595/f50dee7c80a8dbd4c228bd54d1e847442f54c1f6/output/compile/tests/vfs_plus_stdio/ublox-c030-u201:gnu.txt) that the `ublox-c030-u201` was tested for kconfig on `tests/vfs_plus_stdio`.  Since that board is not in the `TEST_KCONFIG_BOARDS_AVAILABLE`.

**Comment by MrKevinWeiss** [comment]
Before removing the "REMOVEME" commit, it would be nice to complete the review as it will delete the link indicating nightly does actually perform the tests.  Of course, I squash, rebase, and remove the commit, it should indicate that the ublox board is not tested.

ping @leandrolanzieri @fjmolinas or @kaspar030

**Comment by fjmolinas** [comment]
Can you explain a bit more what 51c30624e0a6d1279ef281dd82d7cb3fb44a6803 commit is doing?

**Comment by MrKevinWeiss** [comment]
I guess it is easier to look at it after the fixup. This was my initial commit that removed the `TEST_KCONFIG_BOARDS_AVAILABLE` and just tested everything.  I didn't actually think everything would work out so well.  The fixup brings the list back so that normal behaviour is returned with the exception of nightlies.

**Comment by fjmolinas** [comment]
> I guess it is easier to look at it after the fixup. This was my initial commit that removed the `TEST_KCONFIG_BOARDS_AVAILABLE` and just tested everything. I didn't actually think everything would work out so well. The fixup brings the list back so that normal behaviour is returned with the exception of nightlies.

Makes sense, I checked that the test was run, inlined the result in your comments as well. Please squash @MrKevinWeiss!

**Comment by MrKevinWeiss** [comment]
Let me just post a link to the test result from murdock before we merge.

**Pull request merged**
