### PR TITLE
examples/lorawan/main: use auto_init_loramac

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

Change to use `auto_init_loramac`

This PR is sparked from https://forum.riot-os.org/t/cant-get-lorawan-shell-working/3526. 

### Testing procedure

- green murdock

### CODE REVIEW

**Comment by fjmolinas** [comment]
@aabadie what do you think of this?

**Comment by aabadie** [comment]
I don't like to remove the `static` keyword, just because someone tried to readapt this application with the shell. That makes no sense for the example as it now.

I would rather just use the `auto_init_loramac` module and drop the driver/mac initialization sequence. That would make the whole application simpler and extensible.

**Comment by fjmolinas** [comment]
> I don't like to remove the `static` keyword, just because someone tried to readapt this application with the shell. That makes no sense for the example as it now.
> 
> I would rather just use the `auto_init_loramac` module and drop the driver/mac initialization sequence, as suggested in the README. That would make the whole application simpler and extensible.

Done as suggested.

**Review by aabadie — APPROVED** [review]
ACK

**Comment by fjmolinas** [comment]
Thanks!

**Pull request merged**
