### PR TITLE
drivers/flashrom: added addr-to-page function

### PR DESCRIPTION
**Pull request by haukepetersen**
Continuation of #5365 ~(on which this is also rebased).~

Added also some unittests for result validation.

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased and ready for review as #5365 is merged.

**Comment by haukepetersen** [comment]
@kYc0o ping

**Comment by kYc0o** [comment]
I'd like to ACK but CIs are complaining...

**Comment by haukepetersen** [comment]
rebased and fixed `lpc11`

**Comment by kYc0o** [comment]
There are some integer overflows generated by the test, can you check it?

**Comment by haukepetersen** [comment]
yepp, will look into it

**Comment by haukepetersen** [comment]
fixed issue with 8-bit AVRs, unittests should now build fine for those boards.

**Comment by haukepetersen** [comment]
@kYc0o: Murdock is happy now, care to ack/merge?

**Comment by kYc0o** [comment]
Ja! Gerne!

**Pull request merged**
