### PR TITLE
pkg/lvgl: Change all references of LittlevGL to LVGL

### PR DESCRIPTION
**Pull request by OkiStuff**
Change all references of LittlevGL to LVGL in pkg/lvgl/doc.txt per request of LVGL team (https://github.com/lvgl/lvgl/pull/3761)

### Contribution description

Changing parts of the pkg/lvgl/doc.txt to replace "LittlevGL" to LVGL as per request of the LVGL team

### Issues/PRs references
https://github.com/lvgl/lvgl/pull/3761

### CODE REVIEW

**Comment by benpicco** [comment]
Thank you for the patch!

`git grep -i LittlevGL` shows some more occurrences though :wink: 

One more thing: please prefix the commit message with the subsystem (`pkg/lvgl:`) to keep the git log tidy.

**Comment by OkiStuff** [comment]
Will do

**Comment by OkiStuff** [comment]
Changed all instances of LittlevGL to LVGL when applicable and fixed the merge conflicts in the Makefile (I assumed they were caused by a new version of the LVGL package being pushed)

**Comment by Citrullin** [comment]
@OkiStuff Can you squash your commits?

**Review by aabadie — APPROVED** [review]
I allowed myself to rebase and squash a bit this PR. I removed the release-notes.txt change for history. The changes are good otherwise.

ACK

**Comment by aabadie** [comment]
bors merge

**Comment by Citrullin** [comment]
@OkiStuff Congrats. Your first merge :)

**Pull request merged**
