### PR TITLE
dist: enable cppcheck warnings for all files [2017.04 backport]

### PR DESCRIPTION
**Pull request by miri64**
Backport of #6703

### CODE REVIEW

**Comment by miri64** [comment]
@kaspar030 (or maybe @smlng ?) ping?

**Comment by smlng** [comment]
ACK and approve, though its not required here. But, I'rather leave it to the release manager to finally merge this.

**Comment by miri64** [comment]
Ping @kaspar030?

**Comment by kaspar030** [comment]
Yeah, lets go.

**Pull request merged**
