### PR TITLE
periph/flashpage: extend API

### PR DESCRIPTION
**Pull request by Ollrogge**
### Contribution description

This PR extends the flashpage API with two functions that return information about the first and last free flashpage.
This is supposed to make it easier store data in flash without accidentally corrupting e.g. firmware or bootloaders.

I am aware that as of now this only adds the function implementations for Cortex-M CPUs. 

I am opening this PR to start a discussion if this approach is correct and a reasonable addition to the API. If it is, I will also add function implementations for other CPUs implementing the flashpage APl.

### CODE REVIEW

**Comment by benpicco** [comment]
Looks like you missed esp8266/32

**Comment by benpicco** [comment]
@kaspar030 can you provide the output of `tests/periph_flashpage` on msp430?
I don't know who else has the hardware.

**Comment by benpicco** [comment]
Thanks @riot-hil-bot, but the test doesn't actually do anything with that information but print them.

Thinking about it, it would probably be a good idea to use those functions in `cmd_test_last()` instead of `TEST_LAST_AVAILABLE_PAGE`

**Comment by Ollrogge** [comment]
> Was it intended to add the new files (_flashpage.c_) to the doxygen group `drivers_periph_pm`? If so, why?

That is a stupid mistake on my side because I copied the header from another file. It should be `drivers_periph_flashpage` not `drivers_periph_pm`. Should I open a follow up for this ?

**Comment by PeterKietzmann** [comment]
Of course :)

**Comment by Ollrogge** [comment]
In a follow up PR based on the functionality introduced in this PR, [concerns](https://github.com/RIOT-OS/RIOT/pull/17096#issuecomment-975863390) about the necessity of the functionality were raised. I think the mentioned arguments are correct and reduce the necessity of the `flashpage_*_free` functions.

What are you opinions on this @benpicco @fjmolinas ?

**Pull request merged**
