### PR TITLE
cpu/nrf5x: unified and reworked timer driver

### PR DESCRIPTION
**Pull request by haukepetersen**
Both NRF CPUs have almost identical timers, to using the same implementation for both makes much sense.

I also more or less re-implemented the driver to make it look nicer and more efficient, saving ~200byte ROM on the `nrf52dk`...

### CODE REVIEW

**Comment by OlegHahm** [comment]
You may want to rebase this before tonight.

**Comment by thomaseichinger** [comment]
@haukepetersen Please rebase, will test tonight.

**Comment by haukepetersen** [comment]
rebased

**Comment by haukepetersen** [comment]
something broke while rebasing before, now it should be fine

**Comment by authmillenon** [comment]
Now it works. ACK and go when T-buddy will be ready soon.

**Comment by authmillenon** [comment]
(tested for nrf51dongle and airfy-beacon)

**Comment by PeterKietzmann** [comment]
and go

**Pull request merged**
