### PR TITLE
pkg/tinycbor: fix of compiler warnings "uninitialized variable used"

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR patches the `tinycbor` package. On ESP32 and new ESP8266 (PR #11108) platforms, the compilation of the package fails since a local variable is potentially used uninitialized:
```
error: 'valf' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```
With the patch provided in this PR, the variable is initialized with a default value and the according boards are removed from the balcklist.

### Testing procedure

Just try to compile `tests/tinycbor` for a ESP32 board:
```
make BOARD=esp32-wroom-32 -C tests/pkg_tinycbor
```

### Issues/PRs references

Required for PR #11108

### CODE REVIEW

**Comment by gschorcht** [comment]
@benpicco Can we merge it? It is required by #11108. After rebasing there are no conflicts with the master anymore.

**Comment by benpicco** [comment]
It's all green, feel free to press the button :wink:
I'd still would like it if you'd propose the patch upstream so we can drop it from our pkg in a future version.

**Comment by gschorcht** [comment]
> l green, feel free to press the button

@benpicco It's a bad style to merge own PRs. This should always be done by a reviewer or at least by another maintainer.

**Comment by benpicco** [comment]
> It's a bad style to merge own PRs.

That feels like unnecessary friction. If you want to adhere to that, the maintainer would have to go through all PRs again after they already ACKed them, just to see if CI has finished running.

I see that it would be a bad idea to merge if there is still an ongoing discussion, but when you got an uncontested ACK you are free to merge IMHO.

**Comment by gschorcht** [comment]
Thanks.

**Pull request merged**
