### PR TITLE
pkg/oonf_api: fix cflags for osx

### PR DESCRIPTION
**Pull request by smlng**
This PR sets some CFLAGS to make the package compile on latest OSX

### CODE REVIEW

**Comment by gebart** [comment]
For future reference, could you post a copy of the errors/warnings that happen on OSX without this flag?

**Comment by smlng** [comment]
Good point @gebart , here you go:

```
touch /Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/pkg/native/oonf_api/.git-patched
"/Applications/Xcode.app/Contents/Developer/usr/bin/make" -C /Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/pkg/native/oonf_api
mkdir -p /Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/native/
In file included from /Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/pkg/native/oonf_api/src-api/common/avl.c:47:
In file included from /Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/pkg/native/oonf_api/src-api/common/list.h:47:
/Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/pkg/native/oonf_api/src-api/common/container_of.h:50:9: error: keyword is hidden by macro definition [-Werror,-Wkeyword-macro]
#define typeof(x) __typeof__(x)
        ^
1 error generated.
make[3]: *** [/Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/native/oonf_common/avl.o] Error 1
make[2]: *** [all] Error 1
make[1]: *** [all] Error 2
make: *** [/Volumes/workspace/github/smlng/RIOT/examples/gnrc_aodvv2/bin/native/oonf_api.a] Error 2
```

**Comment by gebart** [comment]
Shouldn't that macro definition be corrected instead of hiding the error?

**Comment by smlng** [comment]
Yeah, would be best. But to be honest, I haven't spend much thought on this, I just needed it to work at that very moment. As it is an external package, I may open an issue at the original repo?!

**Comment by smlng** [comment]
Ping! 

Fixing this should be done either in the original source code or via patch during import when running make. For not adding the proposed CFLAGS seems to be best (easier), from RIOT point of view, or not?

**Comment by gebart** [comment]
I would prefer to have this fixed in the source either via a patch applied here, or, the best solution, fixed upstream. Do you have the time to provide a PR for upstream?

**Comment by smlng** [comment]
@gebart: actually I'm not sure how to fix the macro to work on OS X *without* breaking any other OS. Further, RIOT uses oonf 0.3 (of 2012) but current version is 0.12.x (2015) - however the macro definition remains the same. So it might be easier to make a small patch to the RIOT package ...

**Comment by smlng** [comment]
superseded by #6157

**Pull request closed without merging**
