### PR TITLE
cpu: remove superfluous SystemCoreClockUpdate()

### PR DESCRIPTION
**Pull request by DipSwitch**
The functions calculated a lot but the values they assigned where never used.

I propose to make an API call to request the configured clock speeds instead of always calculating it. Or include it in a define of `DEVHELP` and print it to the terminal. This to safe some space and keep the code cleaner. :)

### CODE REVIEW

**Comment by DipSwitch** [comment]
@haukepetersen @gebart Any thoughts on the subject? I know a release is worked on, but I would like to know if I can remove the code from the K20 import as well :)

**Comment by haukepetersen** [comment]
nice one! The `SystemCoreClock` variable and the `SystemCoreClockUpdate` function came actually from the ARM CMSIS files, but we dropped them already for almost all Cortex boards (as we wrote a slimmer version in `cpu_init()`). So removing these also from the rest of the boards make much sense! 

+1! for this change, though no ressources to review in detail until the release is out...

**Comment by gebart** [comment]
I am in favour of the general concept of cleaning up CPU code, but simply deleting the function and the call won't work for Mulle. The SystemCoreClock etc. variables are used it to derive timings for device drivers, so that the clocking matches the running CPU configuration.
I have no time to review or evaluate any alternatives for the forseeable future though.

**Comment by haukepetersen** [comment]
@gebart: I think I can take over the part of reviewing and testing the Mulle board (as we now have some here...).

**Comment by gebart** [comment]
Sorry, I won't have time to participate during the HnA

**Comment by haukepetersen** [comment]
@DipSwitch sorry, this PR slipped away... Would you mind rebasing it?!

**Comment by DipSwitch** [comment]
Done

**Comment by DipSwitch** [comment]
Rebased, adding `Ready for CLI` to give travis a kick, still needs ACK

**Comment by DipSwitch** [comment]
@gebart Ah sorry, missed that part, only checked `SystemCoreClock`

**Comment by OlegHahm** [comment]
So, this is WIP then?

**Comment by haukepetersen** [comment]
I like this PR very much, but I am thinking we can go one step further?! As also discussed in #4430, I think it makes sense to get rid of the CMSIS functions all together and substitute them with our own (simplified) code and defines for the clock setup sequences, as we did for all other CPU's. 

I will take a look at the `sam3` to demonstrate what I mean...

**Comment by haukepetersen** [comment]
ok, for the `sam3` I would propose this solution: #4933. It gets rid of those system_xx file all together :-)

**Comment by DipSwitch** [comment]
Fixed the `mulle` implementation, but don't know if it's correct :)

**Comment by kYc0o** [comment]
Can you rebase please? This could come into the next release.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by haukepetersen** [comment]
@DipSwitch time passes by so fast: are you willing to rebase this PR and prepare it for testing once more? Would be nice to have this in for 2017.01!

**Comment by haukepetersen** [comment]
@DipSwitch ping

**Comment by gebart** [comment]
needs rebase

**Comment by gebart** [comment]
I did a rebase in #6867. Closing this for lack of updates

**Pull request closed without merging**
