### PR TITLE
native: Fix a bug in native_isr_entry() and another in the way native timers are armed (WIP)

### PR DESCRIPTION
**Pull request by benoit-canet**
-native_isr_entry() was forgetting to disable interrupts and this would confuse restoreIRQ().

-the scheduler_timer() function was try arm native timer while signals where disabled and this would lead to the signals being ignored causing deadlocks.

This close two longstanding bugs.

Aditional cleanup patches will be required.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Can you please update the PR title to something more meaningful and add the `native` prefix?

**Comment by benoit-canet** [comment]
Why does travis seems to fail randomly on my PR ?

**Comment by OlegHahm** [comment]
@benoit-canet, Travis won't run the compile tests and unittests until a maintainer sets the "Ready for CI build" on Github (in order to save time). Usually this flag is set after an ACK.

**Comment by benoit-canet** [comment]
I still have some work to do on the last patch I repush when it's done.

**Comment by OlegHahm** [comment]
So, you'll come up with a new PR?

**Comment by benoit-canet** [comment]
I'll repush it and reopen when it's done to keep the tags.

**Comment by benoit-canet** [comment]
That better now is pass my testing.

**Pull request closed without merging**
