### PR TITLE
pkg: wakaama: Fix and update wakaama package to version fe48d45

### PR DESCRIPTION
**Pull request by moenoel**
This pull request updates the Eclipse wakaama package to a more current version from the main repository.

I've tested this change by compiling `examples/hello-world/` with `USEPKG += wakaama` for several `BOARD`s  (native, bluepill, stm32f4discovery, ...), since there is no actual test for this package. I also only tested whether it would compile but no functionality (yet).

This does **not** compile when `size_t` <= 16 bit , like with `BOARD=arduino-uno`, but that shouldn't work with the current version either (if that ever worked, since there's an error in the makefile and the patches don't apply for me).

In the future I would like add an example application for this and/or a module that could provide default objects for LwM2M and bindings for supported hardware.

### CODE REVIEW

**Comment by cladmi** [comment]
There also is this related issue https://github.com/RIOT-OS/RIOT/issues/8106
I will look at both.

**Comment by cladmi** [comment]
If I understand what you did (trying to read diff between two patch files is tricky):
* Fix the not updated `PKG_TEMP_DIR` to `PKG_BUILDDIR`
* Bump the version
* Make the patches apply and fix warnings/errors

When rebased on the last master with -Wall -Wextra -Werror I have no error when building.
It may not work, but its better than not building.

If you could change the commit message, to prepend the directory, like the older commit in this directory: `pkg: wakaama: Fix and update wakaama package to version XYZ` and in the body the steps of the update (== my description or your corrected one) it would be perfect.

I will ACK after rewording the commit message.

@florian-jean: can you check this too ? It could be used as a base commit for your added functionalities

**Comment by florian-jean** [comment]
@cladmi 

Yes I would gladly use this as base commit.
In fact I already bump in the lattest version of wakkama and modified all the core and examples files in order to compile the without the WERROR=0 in the repo I updated in #8106

**Comment by cladmi** [comment]
For maintainers: can be tested with

    USEPKG+=wakaama make -C examples/hello-world
    USEPKG+=wakaama make -C examples/hello-world BOARD=samr21-xpro

**Comment by moenoel** [comment]
@cladmi I did just that and added a few more fixes while I was at it.

I forgot to test compilation with the different operation modes. I've tested the new changes as follows:

Client with bootstrap mode:
```USEPKG+=wakaama CFLAGS+="-DLWM2M_CLIENT_MODE -DLWM2M_BOOTSTRAP" make -C examples/hello-world```

Client without bootstrap mode:
```USEPKG+=wakaama CFLAGS+=-DLWM2M_CLIENT_MODE make -C examples/hello-world```

Server mode:
```USEPKG+=wakaama CFLAGS+=-DLWM2M_SERVER_MODE make -C examples/hello-world```

Bootstrap-server mode:
```USEPKG+=wakaama CFLAGS+=-DLWM2M_BOOTSTRAP_SERVER_MODE make -C examples/hello-world```

**Comment by miri64** [comment]
Agreed

**Pull request merged**
