### PR TITLE
make: introduce RIOT_CI_BUILD

### PR DESCRIPTION
**Pull request by kaspar030**
Murdock can be simplified with some tweaks to the build system.

~~WIP, but I need the PR open for testing.~~ *edit* not WIP anymore

### CODE REVIEW

**Comment by kYc0o** [comment]
@kaspar030 still WIP?

**Comment by kYc0o** [comment]
Let's take it for the next release.

**Comment by miri64** [comment]
Postponed due to feature freeze

**Comment by smlng** [comment]
@cgundogan are you aware of this PR, maybe this contains some missing features for our murdock replica?

**Comment by kaspar030** [comment]
- rebased, reduced a little

**Pull request merged**
