### PR TITLE
pkg/littlefs{,2}: fix compilation with -Wcast-align

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title says.

### Testing procedure

The generated binaries should remain identical to before, but compilation with `-Wcast-align` won't fail.

### Issues/PRs references

Split out of https://github.com/RIOT-OS/RIOT/pull/14955

### CODE REVIEW

**Comment by kaspar030** [comment]
Sorry, my new docker-compose worker seems to have trouble with git-cache not being initialized, which causes pkg checkouts to fail. re-started with new worker disabled.

**Review by vincent-d — APPROVED** [review]
> This is one of the "How did this ever worked?" kind of bug

If `foo[]` is an array, `&foo` is equal to `foo` but this is not very readable, though ;) 

If the unit tests still pass, it should be fine!

**Comment by maribu** [comment]
> If `foo[]` is an array, `&foo` is equal to `foo`

Indeed:

```
$ cat test.c 
#include <stdio.h>

int main(void)
{
    int array[] = {1, 2, 3, 4};
    int *pa = array;
    printf("array = %p, &array = %p, pa = %p, &pa = %p\n",
           array, &array, pa, &pa);

    return 0;
}

$ gcc -o test test.c

~ $ ./test
array = 0x7ffd38b3f7f0, &array = 0x7ffd38b3f7f0, pa = 0x7ffd38b3f7f0, &pa = 0x7ffd38b3f7e8
```

C never stops to surprise me. Let me fix the commit message and PR title then. I'll skip compilation test now, as a change in the commit message shouldn't break any C code. (And if so, that code really had it coming.)

**Comment by maribu** [comment]
Hey, Murdock: Skip compile tests ;-P

**Comment by maribu** [comment]
Thx!

**Pull request merged**
