### PR TITLE
tests/driver_mq3: fix build upon avr 8 bits MCU

### PR DESCRIPTION
**Pull request by mali**
this test won't build with avr MCU like atmega328p because of
tests/driver_mq3/main.c:58:27: error: integer overflow in expression [-Werror=overflow]
         xtimer_usleep(500 * 1000);

also use timex.h constant define.
see #6148

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@mali please check Jenkins log

**Comment by mali** [comment]
strange... timex.h is included by xtimer.h, anyway, re use literal number instead.

**Comment by smlng** [comment]
should've been squashed before merge ... wasn't there a fine on such things 😜

**Comment by mali** [comment]
I was thinking that too :-)

**Comment by miri64** [comment]
> wasn't there a fine on such things :stuck_out_tongue_winking_eye:

I guess there will be free beer tomorrow in Hamburg ;-)

**Pull request merged**
