### PR TITLE
sys/pm_layered: use message bus SYS_BUS_POWER to notify about MCU power mode change

### PR DESCRIPTION
**Pull request by fabian18**
### Contribution description

This adds a header file which redefines the call to `pm_set()` with a function that sends a message over the system power bus before the power save mode is entered and when the CPU wakes up again. For that it was necessary that messages are sent synchronous as in `msg_send_receive()`, so I added a `msg_send_receive_bus()`.

### Testing procedure

I provide a test in `tests/thread_sys_bus_power` which is similar to `tests/thread_msg_bus`.
It spawns 3 threads which are notified when a power mode change happened. The power mode change is executed with our `pm` shell command. The CPU is woken up by a timer interrupt. The header file can be included by any interested user and when the module `pm_layered_sys_bus` is used calls to `pm_set()` send messages over the system power bus.
Threads that are interested in power events and want to prepare for energy saving must subscribe to the "pm changed" event.
```C
    msg_bus_entry_t sub;
    msg_bus_attach(sys_bus_get(SYS_BUS_POWER), &sub);
    msg_bus_subscribe(&sub, SYS_BUS_POWER_EVENT_PM_CHANGED);
```

On an `same54-xpro` the tests runs shows the following output.
```
2023-05-04 10:46:47,351 # pm set 2
2023-05-04 10:46:47,353 # CPU is entering power mode 2.
2023-05-04 10:46:47,356 # Now waiting for a wakeup event...
2023-05-04 10:46:47,359 # T1 recv:  (type=1) from bus
2023-05-04 10:46:47,361 # received pm mode 2 event
2023-05-04 10:46:47,363 # T2 recv:  (type=1) from bus
2023-05-04 10:46:47,365 # received pm mode 2 event
2023-05-04 10:46:47,368 # T3 recv:  (type=1) from bus
2023-05-04 10:46:47,370 # received pm mode 2 event
2023-05-04 10:47:07,324 # T1 recv: e (type=1) from bus
2023-05-04 10:47:07,326 # received pm mode 4 event
2023-05-04 10:47:07,329 # T2 recv: e (type=1) from bus
2023-05-04 10:47:07,331 # received pm mode 4 event
2023-05-04 10:47:07,333 # T3 recv: e (type=1) from bus
2023-05-04 10:47:07,336 # received pm mode 4 event
2023-05-04 10:47:07,339 # CPU has returned from power mode 2.
```

### CODE REVIEW

**Review by benpicco — COMMENTED** [review]
Do I understand it right that this will wait for *all* threads waiting on the bus to have received and acknowledged the message?

I see some problems with this:

 - What if a thread is subscribed to the bus, but currently not waiting for messages (e.g. blocked on a mutex)? Will this wait for that thread to receive the message (possible deadlock) or simply ignore it?
 - What if the thread that does the `pm_set()` has a higher priority than the thread waiting for the message? Once all messages have been acknowledged, the thread doing `pm_set()` would be able to run again without the lower priority receiver thread being able to do any work with the new message.
 - `pm_set()` happens very often (in idle mode) so this would result in a lot of overhead unless you filter by level early

What problem are you trying to solve with this? Maybe a callback based architecture could be a better solution.

**Comment by fabian18** [comment]
> Do I understand it right that this will wait for all threads waiting on the bus to have received and acknowledged the message?

That was the plan.

> I see some problems with this:

You are right. It does not work. I assigned one thread a priority of `THREAD_PRIORITY_MAIN + 1` and it is all time pending and does not catch messages.

> What problem are you trying to solve with this?

Stop a periodic timer when `pm_set()` is called.

> Maybe a callback based architecture could be a better solution.

The message bus solution to me seemed like a more elegant way but if it does not work apparently ...

**Comment by benpicco** [comment]
Maybe something like [event sources](https://doc.riot-os.org/source_8h.html) would work - but where you don't have a separate thread to run the events, but instead do it in the `pm_set()` function.

Or maybe this is really specific to ztimer and you want to stop all timers that are not marked "run standby" or something like that.

**Comment by fabian18** [comment]
I was writing this in the meantime.
```C
void pm_set_notify_listeners(unsigned mode)
{
    if (mode >= PM_NUM_MODES) {
        /* do not notify when power mode is invalid */
        return;
    }
    const pm_layered_listener_t *listeners = (const pm_layered_listener_t *)_pm_callback_list.next;
    mutex_lock(&_mutex);
    while (listeners) {
        listeners = container_of(listeners->node.next, pm_layered_listener_t, node);
        if (listeners->on_pm_set) {
            listeners->on_pm_set(mode);
        }
    }
    mutex_unlock(&_mutex);
    /* zzzzzz ... */
    pm_set(mode);
    /* woke up */
    listeners = (const pm_layered_listener_t *)_pm_callback_list.next;
    mutex_lock(&_mutex);
    while (listeners) {
        listeners = container_of(listeners->node.next, pm_layered_listener_t, node);
        if (listeners->on_pm_set) {
            listeners->on_pm_set(PM_NUM_MODES);
        }
    }
    mutex_unlock(&_mutex);
}
```

Is this what you mean or should I better use event sources?

**Comment by kfessel** [comment]
I like the idea. (prepare for standby ...)
I like the event idea and the message idea.

I think there should not be a list implementation in pm_set but just a callback to one function that handles that. That callback can be put into pm_layered::pm_set (like sched_cb (dynamicliy linked) or linked a compile time like sched_runq_callback).

**Comment by fabian18** [comment]
Karls idea is the simplest and most lightweight. Our company has a wrapper around `pm_set` which calls a `weak` function before and afterwards. I would see internal  RIOT functions `static _pre_pm_set()` and `static _post_pm_set()` (or so) where each modules function is called. And also for external applications, there can be two weak functions. So before `pm_set` the internal RIOT `_pre_pm_set` is called, then the weak applications `_pre_pm_set` is called. After wake up the internal RIOT `_post_pm_set` is called, then the weak applications `_post_pm_set` is called.

Oh, or there are just the internal RIOT functions which cycle through XFAs of function pointers, just like in auto init.

**Pull request closed without merging**
