### PR TITLE
at86rf2xx: Set page 2 by default on AT86RF212B

### PR DESCRIPTION
**Pull request by gebart**
Page 2 is O-QPSK 100 kbit/s or 250 kbit/s, which matches the bandwidth provided in the 2.4 GHz band, at the cost of receiver sensitivity. The previous default, page 0, provides only 20 kbit/s in channel 0, and
40 kbit/s in channels 1-10, and should be used in specific applications where the radio environment requires the maximum receiver sensitivity and noise resilience.

### CODE REVIEW

**Comment by miri64** [comment]
In general untested ACK, but could you please provide a source @gebart?

**Comment by miri64** [comment]
(just as comment, not in-code)

**Comment by gebart** [comment]
Source for the information about channel pages for the sub-GHz PHY:

http://ieeexplore.ieee.org/browse/standards/get-program/page/series?id=68
802.15.4-2015

Page 387, **10.1.2.2 Channel numbering for 868 MHz, 915 MHz, and 2450 MHz bands**

> For channel page zero, 16 channels are available in the 2450 MHz band, 10 in the 915 MHz band, and 1 in
> the 868 MHz band. This channel page supports the channels defined in the 2003 edition of this standard. The
> center frequency of these channels is defined as follows:
> Fc = 868.3 in megahertz, for k = 0
> Fc = 906 + 2 (k – 1) in megahertz, for k = 1, 2, ..., 10
> Fc = 2405 + 5 (k – 11) in megahertz, for k = 11, 12, ..., 26
> where k is the channel number.
> For channel pages one and two, 11 channels numbered zero to ten are available across the two frequency
> bands to support the ASK and O-QPSK PHYs, respectively. Ten channels are available in the 915 MHz
> band and one in the 868 MHz band. The center frequency of these channels is defined as follows:
> Fc = 868.3 in megahertz, for k = 0
> Fc = 906 + 2 (k – 1) in megahertz, for k = 1, 2, ..., 10
> where k is the channel number.
> 

Page 412, **12.2.1 Data rate**

> The data rate of the O-QPSK PHY shall be 250 kb/s when operating in the 2450 MHz, 915 MHz, 780 MHz
> or 2380 MHz bands and shall be 100 kb/s when operating in the 868 MHz band.
> Support for the 2450 MHz O-QPSK PHY is mandatory when operating in the 2450 MHz band.
> Support for the 2380 MHz O-QPSK PHY is mandatory when operating in the 2380 MHz band.
> The O-QPSK PHY is not mandatory in the 868 MHz or 915 MHz band. If the O-QPSK PHY is used in the
> 868 MHz or 915 MHz band, then the same device shall be capable of signaling using the BPSK PHY as
> well.
> 

Page 418, **13.2.1 BPSK PHY data rates**

> The data rate of the BPSK PHY shall be 20 kb/s when operating in the 868 MHz band and 40 kb/s when
> operating in the 915 MHz band.

Regarding sensitivity on the AT86RF212B:

http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42002-MCU_Wireless-AT86RF212B_Datasheet.pdf

image
image
image

See the data sheet for more numbers. My experience is that we most of the time want the higher throughput rather than the increased sensitivity.
The sensitivity numbers for O-QPSK in the data sheet for this transceiver matches the sensitivity numbers for the AT86RF233 in the 2.4 GHz band, which supports O-QPSK only.

**Comment by miri64** [comment]
Thank you @gebart, for the information!

From what I've read I'm not sure if channel page 2 is actually the (recommended) default or if this even is relevant. Your arguments about throughput aside I'm thinking more about interoperability here. What if a Contiki user want's to connect there RIOT device to their network? Do they have to hand-edit stuff with this change or would it work out-of-the-box.

**Comment by gebart** [comment]
Regarding Contiki compatibility I don't know, Contiki is a very fragmented space, all the drivers are platform dependent and the configurations are done per project through a project-conf.h file which manages the settings for each project. We have been using a radio configuration equivalent to setting page 2, as the default configuration on the Eistec Mulle port of Contiki, but I have not investigated what others are using, if there are any sub-GHz users at all? 2.4 GHz seem to be what most users are running.
I don't have a strong opinion about this though, it's just a default setting that can be changed during runtime so it's only a convenience thing to get it set to page 2 by default.

**Comment by miri64** [comment]
> I don't have a strong opinion about this though, it's just a default setting that can be changed during runtime so it's only a convenience thing to get it set to page 2 by default.

True, but can we take the extra step and make it compile-time configurable (in `net/ieee802154.h`)? I think that would make me a lot less stomach ache-y ;-).

**Comment by gebart** [comment]
@miri64 you mean next to IEEE802154_DEFAULT_CHANNEL etc?

**Comment by miri64** [comment]
Yes.

**Comment by miri64** [comment]
@gebart ping?

**Comment by gebart** [comment]
will update this PR to introduce a default page define instead.

**Comment by miri64** [comment]
@gebart see https://github.com/gebart/RIOT/pull/15.

**Comment by miri64** [comment]
(can be squashed into your commit if you want to; I just wanted to prevent a longer wait ;-))

**Comment by smlng** [comment]
@gebart and @miri64, this looks good to me, can we merge this? Otherwise postpone until next release.

**Comment by gebart** [comment]
sorry for the delay, I will update my branch with @miri64 suggestions

**Comment by gebart** [comment]
Addressed comments

**Pull request merged**
