### PR TITLE
tests/pkg_tinydtls_sock_async: fix stack size for event thread

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
The stack size of `event_thread_medium` is way to small to handle DTLS, so let's increase it ;-).

### Testing procedure
Use two `samr21-xpro` or `iotlab-m3` and flash `tests/tests/pkg_tinydtls_sock_async` to both of them. Start a terminal to each. Run `dtlss start` on one and send a DTLS message from the other `dtlsc <server address> "Hello World!"`.

With this patch it should succeed. Currently it crashes.

### Issues/PRs references
Found in https://github.com/RIOT-OS/RIOT/pull/14906#issuecomment-684797218

### CODE REVIEW

**Comment by miri64** [comment]
Unrelated, but `ps` shows the used bytes of the `event_thread` weirdly. According to this it is basically maxed out directly at the start of the application (even before starting the DTLS server). @jia200x @kaspar030 do you maybe have an idea why?

```
2020-09-01 18:34:29,826 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2020-09-01 18:34:29,835 # 	  - | isr_stack            | -        - |   - |    512 (  368) (  144) | 0x20000000 | 0x20000198
2020-09-01 18:34:29,844 # 	  1 | idle                 | pending  Q |  15 |    256 (  208) (   48) | 0x2000169c | 0x200016d4 
2020-09-01 18:34:29,853 # 	  2 | main                 | running  Q |   7 |   4096 (  920) ( 3176) | 0x2000069c | 0x20001424 
2020-09-01 18:34:29,862 # 	  3 | event                | bl anyfl _ |   6 |   4096 ( 4092) (    4) | 0x20001f24 | 0x20002dd4 
2020-09-01 18:34:29,872 # 	  4 | 6lo                  | bl rx    _ |   3 |   1024 (  640) (  384) | 0x20005274 | 0x20005504 
2020-09-01 18:34:29,881 # 	  5 | ipv6                 | bl rx    _ |   4 |   1024 (  640) (  384) | 0x20002f24 | 0x200031b4 
2020-09-01 18:34:29,890 # 	  6 | udp                  | bl rx    _ |   5 |   1024 (  564) (  460) | 0x20005a58 | 0x20005cec 
2020-09-01 18:34:29,899 # 	  7 | at86rf2xx            | bl rx    _ |   2 |   1024 (  768) (  256) | 0x20003654 | 0x20003894 
2020-09-01 18:34:29,905 # 	    | SUM                  |            |     |  13056 ( 8200) ( 4856)
```

**Comment by fjmolinas** [comment]
> Unrelated, but ps shows the used bytes of the event_thread weirdly. According to this it is basically maxed out directly at the start of the application (even before starting the DTLS server). @jia200x @kaspar030 do you maybe have an idea why?

I think its because its not started with `THREAD_CREATE_STACKTEST` so the stack usage is not measured, can that be it?

**Comment by miri64** [comment]
> > Unrelated, but ps shows the used bytes of the event_thread weirdly. According to this it is basically maxed out directly at the start of the application (even before starting the DTLS server). @jia200x @kaspar030 do you maybe have an idea why?
> 
> I think its because its not started with `THREAD_CREATE_STACKTEST` so the stack usage is not measured, can that be it?

m) Yep, that must be it.

**Review by fjmolinas — COMMENTED** [review]
Your fix works but wouldn't the best solution be to use `USEMODULE += event_thread_highest` and change the code accordingly?

- client

```
dtlsc fe80::204:2519:1801:ab07 hello
2020-09-01 18:59:40,349 # dtlsc fe80::204:2519:1801:ab07 hello
> 2020-09-01 18:59:40,447 #  Session handshake received
2020-09-01 18:59:40,450 # Connection to server successful
2020-09-01 18:59:40,452 # Sending data "hello"
2020-09-01 18:59:40,455 # Sent DTLS message
2020-09-01 18:59:40,457 # Session became ready
2020-09-01 18:59:40,459 # DTLS message was sent
2020-09-01 18:59:40,470 # Received 5 bytes: "hello"
2020-09-01 18:59:40,472 # Terminating session
```

- server
```
2020-09-01 18:59:26,208 # ifconfig
2020-09-01 18:59:26,215 # Iface  7  HWaddr: 2B:07  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK
2020-09-01 18:59:26,216 #
2020-09-01 18:59:26,220 #           Long HWaddr: 00:04:25:19:18:01:AB:07
2020-09-01 18:59:26,227 #            TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4
2020-09-01 18:59:26,234 #           AUTOACK  ACK_REQ  CSMA  L2-PDU:102  MTU:1280  HL:64  6LO
2020-09-01 18:59:26,236 #           IPHC
2020-09-01 18:59:26,239 #           Source address length: 8
2020-09-01 18:59:26,242 #           Link type: wireless
2020-09-01 18:59:26,247 #           inet6 addr: fe80::204:2519:1801:ab07  scope: link  VAL
2020-09-01 18:59:26,250 #           inet6 group: ff02::1
2020-09-01 18:59:26,251 #
> dtlss start
2020-09-01 18:59:30,728 #  dtlss start
> 2020-09-01 18:59:40,436 #  Session handshake received
2020-09-01 18:59:40,438 # New client connected
2020-09-01 18:59:40,440 # Session became ready
2020-09-01 18:59:40,461 # Received 5 bytes -- (echo)
2020-09-01 18:59:40,482 # Session was destroyed by peer

```

**Comment by miri64** [comment]
> Your fix works but wouldn't the best solution be to use `USEMODULE += event_thread_highest` and change the code accordingly?

How would that help me with stack size? The high priority event thread has the same pre-configured stack size as the medium one?

**Comment by fjmolinas** [comment]
> How would that help me with stack size? The high priority event thread has the same pre-configured stack size as the medium one?

Ah sorry I misread the code and though `EVENT_THREAD_HIGHEST_STACKSIZE` changed the stacksize, sorry for the noise.

**Review by fjmolinas — APPROVED** [review]
Tested, ACK.

**Pull request merged**
