### PR TITLE
sys: shell: remove superfluous optimization

### PR DESCRIPTION
**Pull request by OlegHahm**
IMO this optimization isn't required any more.

### CODE REVIEW

**Comment by kaspar030** [comment]
did you test whether it is still needed?

**Comment by kaspar030** [comment]
Maybe try the minimal example with a few puts, with this PR and without?

**Comment by OlegHahm** [comment]
I tested for one example including the shell, but only for Cortex-M3. The difference was 8 bytes.

**Comment by OlegHahm** [comment]
Hm, the optimization saves 28 bytes for Cortex-M0, 8 bytes for Cortex-M3 and nothing for MSP430. Maybe we should leave it as is. Basically, the trade-off is between saving some bytes and ugly code.

**Comment by OlegHahm** [comment]
Okay, I think we can live with this little ugliness.

**Pull request closed without merging**
