### PR TITLE
murdock: add some doc on how to efficiently limit builds

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

When limiting builds by just adding `BOARDS` or `APPS`, murdock calls "make info-boards-supported", then filters by BOARDS. This is slower than just exporting BOARDS, which is honoured by "make info-boards-supported".

This PR adds some (uncommented) examples on how to limit builds, with "export" in place. Hopefully users will use those in the future.

### CODE REVIEW

**Comment by kaspar030** [comment]
(added limiting commit for testing)

**Comment by fjmolinas** [comment]
What is the impact of this? Is is significant?

**Comment by kaspar030** [comment]
> What is the impact of this? Is is significant?

It should reduce time needed for the collection phase a bit, for "limited" builds. That'll become more interesting once @maribu's script is integrated.

**Comment by kaspar030** [comment]
> What is the impact of this? Is is significant?

So for limited builds, this is cutting of some seconds to 1 minute, depending on which workers get the jobs. It's hard to measure...

**Review by fjmolinas — APPROVED** [review]
ACK!

**Pull request merged**
