### PR TITLE
board/native: fix CFLAGS and LINKFLAGS for FreeBSD

### PR DESCRIPTION
**Pull request by thomaseichinger**
Works with FreeBSD 10.1-RELEASE-p6 on amd64.

### CODE REVIEW

**Comment by gebart** [comment]
is `-march=i686` actually needed or is `-m32` "the magic"?

**Comment by thomaseichinger** [comment]
You are totally right, I also dismissed the -L flag as it was producing a lot of `not used` noise.

**Comment by gebart** [comment]
I don't have a FreeBSD machine to test on, but the change looks good to me. I'll let someone with a FreeBSD machine do the acking.

**Comment by LudwigOrtmann** [comment]
will test

**Comment by LudwigOrtmann** [comment]
Still compiles.

What exactly does this fix?

**Comment by LudwigOrtmann** [comment]
(It looks like it's just a cleanup ;)

**Comment by thomaseichinger** [comment]
The `-m32` flag was added.

**Comment by LudwigOrtmann** [comment]
please squash (and change label to ready)

**Comment by thomaseichinger** [comment]
Sqashed and changed labels.

**Comment by thomaseichinger** [comment]
CI passed, do I hear an ACK?

**Comment by kaspar030** [comment]
ACK! ;)

**Pull request merged**
