### PR TITLE
sys: add  JSON serialization and deserialization module

### PR DESCRIPTION
**Pull request by Kijewski**
~~Work in progress.~~

~~Entirely untested and undocumented.~~

### CODE REVIEW

**Comment by OlegHahm** [comment]
Anyone volunteering to review this? I think it would be a nice feature.

**Comment by Kijewski** [comment]
> Anyone volunteering to review this?

**Comment by kaspar030** [comment]
I will!

**Comment by OlegHahm** [comment]
@kaspar030, ping

**Comment by kaspar030** [comment]
@Kijewski Could you provide a simple example? Or a mini-tutorial on how to get started, either given a simple json dump or some data that I want to dump to json?

**Comment by kaspar030** [comment]
@Kijewski *ping*

**Comment by Kijewski** [comment]
@kaspar030


Sorry, will do (at least before the next release), but the services I had in mind all use TCP, which I understand has currently no ETA in RIOT?

**Comment by temmihoo** [comment]
CoAP for one can use JSON for the payload

**Comment by waehlisch** [comment]
@Kijewski what do you mean with "has currently no ETA in RIOT"? @brummer-simon is working on TCP implementation.

**Comment by Kijewski** [comment]
@temmihoo, well, does his implementation have an ETA? http://i.imgur.com/l47ghaz.gifv

**Comment by OlegHahm** [comment]
> Sorry, will do (at least before the next release),

@Kijewski, next release is soon...

**Comment by OlegHahm** [comment]
3 days left.

**Comment by Kijewski** [comment]
Will look at it at the weekend.

**Comment by kaspar030** [comment]
I'll untag the release for now.

**Comment by Kijewski** [comment]
:turtle:

**Comment by cgundogan** [comment]
>Will look at it at the weekend.

@Kijewski was your weekend fruitful?

**Comment by OlegHahm** [comment]
@Kijewski, can you test on top of @brummer-simon's TCP PR?

**Comment by authmillenon** [comment]
ping?

**Comment by cgundogan** [comment]
and please rebase to get strider out of your PR (:

**Comment by kYc0o** [comment]
@Kijewski can we have this merged for this release?

**Comment by authmillenon** [comment]
Summon @Kijewski.

**Comment by miri64** [comment]
ph'nglui mglw'nafh @Kijewski R'lyeh wgah'nagl fhtagn

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by cgundogan** [comment]
@miri64 your dark magic didn't work..

**Comment by miri64** [comment]
Well I didn't technically summoned him, did I. Just stated, that he's sleeping in a city at the bottom of the ocean :-)

**Comment by miri64** [comment]
Postponed due to feature freeze (but I really would like to have this in 2017.01!)

**Comment by kaspar030** [comment]
@Kijewski Hey, here are 6k lines of code that need some love!

**Comment by Kijewski** [comment]
@kaspar030, that 6k lines got some love two weeks ago. I'm still didn't come up with a concise example, because IMO the tests show to usage well enough.

**Comment by OlegHahm** [comment]
So, how do we proceed here?

**Comment by kYc0o** [comment]
I was trying to review it but it's pretty big... What I found it's an extensive use of macros which, I thought, we prefer to have them as `static inline` functions. Do we care about it?

**Comment by OlegHahm** [comment]
Can you post a pointer to these macros? Couldn't find it at a first glance.

**Comment by kYc0o** [comment]
[sys/json/json_write.c](https://github.com/RIOT-OS/RIOT/pull/2189/files#diff-33d5a83d2b5dae356a42a1c6438c6ff6) is full of them.

**Comment by OlegHahm** [comment]
I can see only two macros, but I agree that they are ugly and should be removed.

**Comment by kYc0o** [comment]
Oh yeah, there are few macros, but they used everywhere. There are more in other sources, but I don't know if that's a real problem.

Besides, to review this it takes really a lot of time... I worked with a JSON implementation which was far less big in terms of code (but maybe less efficient, to be tested...). Do we know why is it so big?

**Comment by OlegHahm** [comment]
@Kijewski, can you explain?

@kYc0o, do you have a pointer to these JSON implementations?

**Comment by kYc0o** [comment]
Actually is only a [JSON parser](https://github.com/contiki-os/contiki/tree/master/apps/json), which leads me to a question: Why do we need a JSON serialisator? (assuming that it can be very easily created using buffers and strings per application).

**Comment by Kijewski** [comment]
> Do we know why is it so big?

Did you even look at the code, or only at the number of changed lines? Json_write.c
 is 362 lines (including boiler plate, comments, blank lines), json_read.c is 434. I could strip 2/3 if I didn't follow RIOT's coding convention, which encourages many newlines. Most of the code are documentation and tests.

**Comment by kYc0o** [comment]
@OlegHahm Do we have a policy for generated code? There are 2K more lines of this code, and it's not really readable, some pragmas are also present...

**Comment by kYc0o** [comment]
Well I did a first quick review and found some problems... 

If you want to exclude the atmega cpus I think you should specify which ones, since the atmega_common hold common code for these cpus but maybe in the future not all of them, and the characteristics can be very different between them.

Besides, there are a lot of macros and several style issues, I'll try to point them once, since they're repeated several times.

**Comment by OlegHahm** [comment]
> @OlegHahm Do we have a policy for generated code? There are 2K more lines of this code, and it's not really readable, some pragmas are also present...

AFAIK there is no policy for generated code and I don't have strong opinion in general. Important is that the code has good quality - whether it was manually written or generated. (Do we have generated code here btw?)

Concerning the pragmas: they should be avoided wherever possible. @Kijewski, any way to get rid of them?

And finally, apart from the LoC - what in particular makes the code unreadable in your opinion.

**DISCLAIMER:** I only scanned over the code - I'm only reacting to the comments here.

**Comment by OlegHahm** [comment]
> If you want to exclude the atmega cpus I think you should specify which ones, since the atmega_common hold common code for these cpus but maybe in the future not all of them, and the characteristics can be very different between them.

I don't quite understand this comment. @Kijewski, can you briefly state why you exclude these MCUs? Maybe that could simplify the discussion.

**Comment by Kijewski** [comment]
> I don't quite understand this comment. @Kijewski, can you briefly state why you exclude these MCUs? Maybe that could simplify the discussion.

Anno 2014 atmega's libc was lacking int64_t support (I can't remember if it didn't know the type altogether or if only some functions were missing). I did not test if the situation change in the meantime. I'll check if the `ifndef MODULE_ATMEGA_COMMON` guards are still needed.

**Comment by OlegHahm** [comment]
> @waehlisch, well, does his implementation have an ETA in RIOT? 

It's finally merged. ;-)

**Comment by smlng** [comment]
@Kijewski are you going/willing to work on this (again)? Then, I suggest to rebase first so Jenkins is aware of this PR.

**Comment by miri64** [comment]
I've tried to compile this for AVR (rebased to master first) and it seems at least to build.

**Comment by aabadie** [comment]
ping !

**Comment by smlng** [comment]
summon @Kijewski, please squash 🍻

**Comment by smlng** [comment]
@Kijewski could you squash (and rebase) within the next few days - or do you agree that someone overtakes this PR to get it merged (maybe before X-mas)?

IMHO its time we either merge this or close it as memo, or what?

**Comment by smlng** [comment]
I adopted the PR in #8312, if you @Kijewski don't mind and others agree, too. If so, this can be closed.

**Comment by miri64** [comment]
I interpret @Kijewski's replies in #8312, that he doesn't mind.

**Pull request closed without merging**
