### PR TITLE
sys/stdio: Wrap stdio.h to enforce printf()'s first arg is a str literal

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This PR adds a `stdio.h` that will get included instead of the C lib's `stdio.h`, which however will include the C lib's `stdio.h` via `#include_next`. The intent is that this can transparently extend/modify the behavior of the C lib's `stdio.h`.

This is directly done by modifying `printf()` to only accept string literals as first argument. The motivation for this is three-fold:

1. It prevents security issues due format strings controlled by adversaries.
2. It makes sure that modern C compilers that do understand format specifiers have knowledge of the format string and can verify that the other arguments match what is given via format string specifiers
3. It allows to force the format string to flash even for Harvard architectures transparently

In PR https://github.com/RIOT-OS/RIOT/pull/18148, this will be extended to send the string literal into flash on Harvard Arches (such as used by the still immensely popular Arduino UNO and Arduino Nano).

Note: https://github.com/RIOT-OS/RIOT/pull/18148 is not yet using this. It does make sense to wait for this, so that this approach is actually proven to work. Otherwise just adding `-Wformat-nonliteral` to `CFLAGS` may be a tiny bit more readable than the dark magic used here.

### Testing procedure

No changes in generated binaries and everything (hopefully!) still compiles. Adding something like

```C
    const char *test = "Foobar!\n";
    printf(test);
```

to e.g. `examples/hello-world/main.c` should result in compilation failures.

### Issues/PRs references

Useful for https://github.com/RIOT-OS/RIOT/pull/18148

### CODE REVIEW

**Review by kaspar030 — CHANGES_REQUESTED** [review]
Fix the C standart with macro hammers!?
I don't like it at all. ;)

For the reasons given:

1.) If that's important, can't we use a linter or some static analysis for that?

2.) I was under the impression that format strings are already checked?

3.) We need a serious talk about that. There was an (unwritten) understanding that we don't compromise much of the higher level code for sake of one architecture's quirks. Macro meddling string literals is the definition of that.

**Comment by benpicco** [comment]
> Otherwise just adding `-Wformat-nonliteral` to `CFLAGS` may be a tiny bit more readable than the dark magic used here.

That *does* sound like a much more compelling solution, why not use that instead? Or is this PR doing something more than that?

**Comment by maribu** [comment]
> 2.) I was under the impression that format strings are already checked?

Yes, if *and only if* the first argument is a string literal. If that is some `extern const char *foo;` the compiler has no insight in what format it contains (it may have with LTO, but I doubt that this linting is still done at that stage). Even worse, if that is some write-able buffer, the format string may actually be controlled by some adversary.

> 3.) We need a serious talk about that. There was an (unwritten) understanding that we don't compromise much of the higher level code for sake of one architecture's quirks. Macro meddling string literals is the definition of that.

This is definitely not the case here: There is an agreement that the first arg of `printf()` must be a string literal for security reasons.

And now that the format string is a literal anyway, we can make use of that for some optimization as side benefit.

> > Otherwise just adding `-Wformat-nonliteral` to `CFLAGS` may be a tiny bit more readable than the dark magic used here.
> 
> That _does_ sound like a much more compelling solution, why not use that instead? Or is this PR doing something more than that?

The thing is that if we actually want to push the string literals to flash on AVR, we need to wrap `printf()` to invoke `TO_FLASH()` on the first argument. Something like `#define printf(x, ...) printf_P(TO_FLASH(x), __VA_ARGS__)` would work for `printf()` statements with more than one arg, but would be illegal for e.g. `printf("foo");`. But it wouldn't be popular to ban legal use of `printf()` for the sake of AVR, so instead that macro needs to work with any legal and secure use of `printf()`. This is why this needs to dispatch into a SINGLEARG and a MULTIARG variant.

**Comment by kaspar030** [comment]
If we enforce the first argument to be a literal with `-Wformat-nonliteral`, can the stdio.h wrapping be contained to avr?

**Comment by maribu** [comment]
Yes, the wrapper `stdio.h` could just be moved into `cpu/avr8_common/include`.

I'll open a PR add that flag. We should enforce string literals regardless of what the outcome of this is.

**Comment by maribu** [comment]
Fun fact: We would need to disable `-Wformat-nonliteral` for AVR again, as the `TO_FLASH(str_literal)` macro allocates the string given as `str_literal` in flash and returns a flash pointer to that. And a flash pointer no longer is a string literal...

But from the user's point of view this is an implementation detail, as `printf()` without a string literal as format would fail for both AVR and non-AVR.

**Comment by maribu** [comment]
> Fun fact

Turns out I was wrong. We had `-Wformat=2` enabled which, according to GCCs `man`-page, enables `-Wformat-nonliteral`. And it works just fine there. Maybe that warning is not checking `printf_P()`, or maybe GCC is smart enough to that the flash pointer is just alias of a string literal.

**Comment by benpicco** [comment]
> Turns out I was wrong. We had `-Wformat=2` enabled which, according to GCCs man-page, enables `-Wformat-nonliteral`. And it works just fine there. 

So is this PR even still needed?

**Comment by maribu** [comment]
> So is this PR even still needed?

`SINGLEARG_OR_MULTIARG()` is still needed to legally dispatch `printf(x)` to `PRINTF_SINGLEARG(x)` and `printf(x, ...)` to `PRINTF_MULTIARG(x, ...)`. But that could live in `cpu/avr_common` now and be introduced with the `flash_utils` PR. It could be moved to some common place if a second user pops up.

**Pull request closed without merging**
