### PR TITLE
boards: use explicit paths for file inclusion

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

While testing #12972 I realized that when having an external `native` board name e.g.: `BOARD=native-external` it will try to include headers in `RIOTBASE` with the external BOARD name, thus failing.

**EDIT**: I extended this to all of the cases of:

<details><summary>git grep \/\$\(BOARD\) boards/ </summary>

```
boards/arduino-mkrwan1300/Makefile.include:INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
boards/cc2538dk/Makefile.include:DEBUGGER = $(RIOTBOARD)/$(BOARD)/dist/debug.sh
boards/cc2538dk/Makefile.include:RESET ?= $(RIOTBOARD)/$(BOARD)/dist/reset.sh
boards/cc2538dk/Makefile.include:  FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
boards/chronos/Makefile.include:INCLUDES += -I$(RIOTBOARD)/$(BOARD)/drivers/include
boards/common/arduino-mkr/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/common/nrf52/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/f4vi1/Makefile.include:DEBUGGER = $(RIOTBOARD)/$(BOARD)/dist/debug.sh
boards/f4vi1/Makefile.include:DEBUGGER_FLAGS = $(RIOTBOARD)/$(BOARD)/dist/gdb.conf $(ELFFILE)
boards/feather-m0/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/mbed_lpc1768/Makefile.include:FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
boards/native/Makefile.include:export NATIVEINCLUDES += -I$(RIOTBOARD)/$(BOARD)/include/
boards/native/Makefile.include:RESET ?= $(RIOTBOARD)/$(BOARD)/dist/reset.sh
boards/opencm904/Makefile.include:FLASHER = $(RIOTBOARD)/$(BOARD)/dist/robotis-loader.py
boards/openmote-b/Makefile.include:  export JLINK_RESET_FILE = $(RIOTBOARD)/$(BOARD)/dist/hw_reset.seg
boards/sensebox_samd21/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
```
</details>

Except for `boards/common/nrf52/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep` since it is a hack for dependency resolution.

### Testing procedure

- cp external-native to whatever directory out of riotbase

```
cp -r tests/external_board_native/external_boards/ <dir/external-boards>
```

- change native to externalnative  `mv native/ external-native`

- compile on external BOARD, fails without this change.

```
BOARDSDIR=<dir/external-boards> BOARD=native make -C examples/hello-world/
```

- No change in any of the touched variables.

```
for board in arduino-mkrwan1300 cc2538dk chronos f4vi1 feather-m0 mbed_lpc1768 native opencm904 openmote-b sensebox_samd21; do BOARD=${board} make --no-print-directory -C examples/hello-world/ info-debug-variable-BOARD info-debug-variable-USEMODULE info-debug-variable-JLINK_RESET_FILE info-debug-variable-FLASHER info-debug-variable-RESET info-debug-variable-DEBUGGER_FLAGS info-debug-variable-INCLUDES info-debug-variable-DEBUGGER; done > pr.txt; git checkout upstream/master; for board in arduino-mkrwan1300 cc2538dk chronos f4vi1 feather-m0 mbed_lpc1768 native opencm904 openmote-b sensebox_samd21; do BOARD=${board} make --no-print-directory -C examples/hello-world/ info-debug-variable-BOARD info-debug-variable-USEMODULE info-debug-variable-JLINK_RESET_FILE info-debug-variable-FLASHER info-debug-variable-RESET info-debug-variable-DEBUGGER_FLAGS info-debug-variable-INCLUDES info-debug-variable-DEBUGGER; done > master.txt; diff pr.txt master.txt; git checkout pr-12999
# no diff
```

### CODE REVIEW

**Comment by miri64** [comment]
I'm not sure I understand the use case.

**Comment by fjmolinas** [comment]
> I'm not sure I understand the use case.

Sorry, I'll give more details. With the addition of `BOARDSDIR` one can reuse common `BOARDS` code present in `$(RITOBOARD)` by changing `$(BOARDSDIR)` to an external directory where your `BOARD` code is stored and replicate some of the included to pull in the common `BOARD` code present in `RIOTBOARD`. For example I could extend a `samr21-xpro` to a `samr21-xpro-lora` which has an additional `lora` radio. 

`tests/external_board_native/Makefile` is supposed to show this with a native `BOARD` only it does a couple of hacks, namely keeping the original `native` name so the ci compiles and tests this. If you change the fake directory name for native to something else, lets say `native-2` (`tests/external_board_native/external_boards/native-2` instead of `tests/external_board_native/external_boards/native`) then you get:

```
cc1: error: /home/francisco/workspace/RIOT/boards/native-2/include/: No such file or directory [-Werror=missing-include-dirs]
```

Because $(BOARD) doesn't have the expected name. I don't know how much of a use case there is for this. But this goes in the direction of saying all our `BOARD` code is actually re-usable common code, it is similar to what we do when making explicit a `include $(RIOTBOARD)/common/arduino-mkr/Makefile.include` include.

And actually I would change it for all boards and add a static check:

<details><summary>git grep \/\$\(BOARD\) boards/ </summary>

```
boards/arduino-mkrwan1300/Makefile.include:INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
boards/cc2538dk/Makefile.include:DEBUGGER = $(RIOTBOARD)/$(BOARD)/dist/debug.sh
boards/cc2538dk/Makefile.include:RESET ?= $(RIOTBOARD)/$(BOARD)/dist/reset.sh
boards/cc2538dk/Makefile.include:  FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
boards/chronos/Makefile.include:INCLUDES += -I$(RIOTBOARD)/$(BOARD)/drivers/include
boards/common/arduino-mkr/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/common/nrf52/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/f4vi1/Makefile.include:DEBUGGER = $(RIOTBOARD)/$(BOARD)/dist/debug.sh
boards/f4vi1/Makefile.include:DEBUGGER_FLAGS = $(RIOTBOARD)/$(BOARD)/dist/gdb.conf $(ELFFILE)
boards/feather-m0/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
boards/mbed_lpc1768/Makefile.include:FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
boards/native/Makefile.include:export NATIVEINCLUDES += -I$(RIOTBOARD)/$(BOARD)/include/
boards/native/Makefile.include:RESET ?= $(RIOTBOARD)/$(BOARD)/dist/reset.sh
boards/opencm904/Makefile.include:FLASHER = $(RIOTBOARD)/$(BOARD)/dist/robotis-loader.py
boards/openmote-b/Makefile.include:  export JLINK_RESET_FILE = $(RIOTBOARD)/$(BOARD)/dist/hw_reset.seg
boards/sensebox_samd21/Makefile.include:include $(RIOTBOARD)/$(BOARD)/Makefile.dep
```
</details>

**Comment by fjmolinas** [comment]
@miri64 I updated the PR description and testing procedure with what I mentioned.

**Comment by fjmolinas** [comment]
Rebased and squashed since review doesn't seem to have started yet. Also added a build system sanity check.

**Comment by miri64** [comment]
Thanks for the explanation. This makes sense.

**Comment by miri64** [comment]
Oops, sorry /o\. Hit the wrong button by accident.

**Comment by miri64** [comment]
Sorry, I should have explained: I first and foremost wanted to understand if the concept makes sense. IMHO it does, so I gave the label for that. However, I also think the final decision should be made by someone else, as this is not my usual work area ;-).

**Comment by fjmolinas** [comment]
Maybe @leandrolanzieri @smlng can take a look?

**Comment by fjmolinas** [comment]
@leandrolanzieri thanks for testing and reviewing, addressed comments.

**Comment by fjmolinas** [comment]
@leandrolanzieri thanks for the review!

**Pull request merged**
