### PR TITLE
tests: no default interactive sync for native

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

The aim is to allow faster test cycles on native for unit test style apps (that don't need interaction) by bypassing the python test framework using e.g.:

    make RIOT_TERMINAL=native all term

This would work already before, but now is more convenient as no manual press of the `s` key is needed to start the test.

For non-native boards we need the sync, as otherwise the board may finish booting before the python test automation framework can capture output. For `native` and `native64`, we actually control when the RIOT app is started and do not need to sync.

On a typical machine this can reduce the test cycle by more than 4 seconds.

### Testing procedure

With this change:

    $ time sh -c 'make BOARD=native -C tests/unittests tests-nanocoap -j && make BOARD=native RIOT_TERMINAL=native -C tests/unittests term'
    [...]
    main(): This is RIOT! (Version: 2024.10-devel-394-gd65dec-tests/no-sync-control)
    ...................................
    OK (35 tests)
    [...]
    make: Leaving directory '/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/tests/unittests'
    sh -c   0.30s user 0.24s system 113% cpu 0.476 total

Before t his change:

    $ time sh -c 'make BOARD=native -C tests/unittests tests-nanocoap -j && make BOARD=native -C tests/unittests test'
    [...]
    main(): This is RIOT! (Version: 2024.10-devel-394-gd65dec-tests/no-sync-control)
    Help: Press s to start test, r to print it is ready
    READY
    s
    START
    ...................................
    OK (35 tests)
    [...]
    make: Leaving directory '/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/tests/unittests'
    sh -c   0.50s user 0.37s system 17% cpu 4.863 total

### Issues/PRs references

None

### CODE REVIEW

**Comment by maribu** [comment]
> `make NOSYNC=1 test` will surprisingly not work

That is expected: `make test` will run whatever binary is in place. If the `make test` is run with `NOSYNC=1` but `make all` is run with `NOSYNC=0`, the test will expect no interactive sync, but the binary will provide it.

> and for all cases where the Python tests do more than just grepping for OK (xx tests), this will need to be done manually.

True, but native does actually pass through the return value of the `main` thread.

In my experience tests that do rely heavily on python scripting are both slow and fragile, especially since stdio can be unreliable (e.g. bit errors on UART is a thing). For these reasons, the simple test style where the python only checks for some `TEST PASSED` or `TEST SUCCEEDED` in the output is becoming more and more popular.

> This adds another obscure environment variable that is not documented anywhere except in the Makefile

True. Maybe we should just disable interactive sync for `native` and `native64` unconditionally instead? I think there is no reason to sync with native anyway.

**Comment by mguetschow** [comment]
> > `make NOSYNC=1 test` will surprisingly not work
> 
> That is expected: `make test` will run whatever binary is in place. If the `make test` is run with `NOSYNC=1` but `make all` is run with `NOSYNC=0`, the test will expect no interactive sync, but the binary will provide it.

Ah, that's not what I meant, I thought the Python testrunner would always expect the interactive sync. According to the docs in `tests/README.md` it should actually adapt automatically if the module is disabled. So please disregard this comment, and also the follow up of it (the manual vs. Python grepping one).

> > This adds another obscure environment variable that is not documented anywhere except in the Makefile
> 
> True. Maybe we should just disable interactive sync for `native` and `native64` unconditionally instead? I think there is no reason to sync with native anyway.

Sounds like a plan. Maybe check if you find a nice place to document this, either for the native board or in the above-mentioned tests README.

**Comment by maribu** [comment]
The tests on `native` and `native64` are run no matter what, but let's also test for regressions.

I think it is fine to have the `CI: run tests` set only for the quick run - after all, this change would effect all tests and boards, if this introduces issues. I'll drop that label when this passes.

**Review by mguetschow — CHANGES_REQUESTED** [review]

**Review by mguetschow — APPROVED** [review]
Thanks! please squash @maribu  :)

**Pull request merged**
