### PR TITLE
pkg/lwip: Fix dualstack build when only using 6lowpan

### PR DESCRIPTION
**Pull request by yarrick**
### Contribution description

* Disable ARP if Ethernet is not used
* Use macro converting netif v6 address to `ip6_addr_t` (which is noop in v6-only setup)

### Testing procedure

`BOARD=iotlab-m3 LWIP_IPV4=1 LWIP_IPV6=1 make -C tests/lwip  -j` now works

`BOARD=iotlab-m3 LWIP_IPV4=1 make -C tests/lwip  -j` is still broken (since it disables IPv6): linking fails with `undefined reference to 'ipv6_addr_link_local_prefix'`

### Issues/PRs references

Part of #17162

### CODE REVIEW

**Comment by miri64** [comment]
> Part of #17162

Why only "Part of" and not "Fixes"?

**Comment by miri64** [comment]
> `BOARD=iotlab-m3 LWIP_IPV4=1 make -C tests/lwip -j` is still broken (since it disables IPv6): linking fails with `undefined reference to 'ipv6_addr_link_local_prefix'`

This can be fixed when applying

```diff
diff --git a/pkg/lwip/contrib/netdev/lwip_netdev.c b/pkg/lwip/contrib/netdev/lwip_netdev.c
index e70e4eacee..34398470db 100644
--- a/pkg/lwip/contrib/netdev/lwip_netdev.c
+++ b/pkg/lwip/contrib/netdev/lwip_netdev.c
@@ -159,17 +159,19 @@ err_t lwip_netdev_init(struct netif *netif)
             if (netdev->driver->set(netdev, NETOPT_SRC_LEN, &val, sizeof(val)) < 0) {
                 return ERR_IF;
             }
-            /* netif_create_ip6_linklocal_address() does weird byte-swapping
-             * with full IIDs, so let's do it ourselves */
-            addr = ip_2_ip6(&(netif->ip6_addr[0]));
-            /* addr->addr is a uint32_t array */
-            if (l2util_ipv6_iid_from_addr(dev_type,
-                                          netif->hwaddr, netif->hwaddr_len,
-                                          (eui64_t *)&addr->addr[2]) < 0) {
-                return ERR_IF;
+            if (IS_USED(MODULE_IPV6_ADDR)) {
+                /* netif_create_ip6_linklocal_address() does weird byte-swapping
+                 * with full IIDs, so let's do it ourselves */
+                addr = ip_2_ip6(&(netif->ip6_addr[0]));
+                /* addr->addr is a uint32_t array */
+                if (l2util_ipv6_iid_from_addr(dev_type,
+                                              netif->hwaddr, netif->hwaddr_len,
+                                              (eui64_t *)&addr->addr[2]) < 0) {
+                    return ERR_IF;
+                }
+                ipv6_addr_set_link_local_prefix((ipv6_addr_t *)&addr->addr[0]);
+                ip6_addr_assign_zone(addr, IP6_UNICAST, netif);
             }
-            ipv6_addr_set_link_local_prefix((ipv6_addr_t *)&addr->addr[0]);
-            ip6_addr_assign_zone(addr, IP6_UNICAST, netif);
             /* Set address state. */
 #if LWIP_IPV6_DUP_DETECT_ATTEMPTS
             /* Will perform duplicate address detection (DAD). */
```

However, then another error is revealed:

```
tests/lwip/bin/iotlab-m3/application_tests_lwip/ip.o:tests/lwip/ip.c:70: undefined reference to `ipv6_addr_to_str'
```

Which is weird, as this part of the code is `#if IS_USED(MODULE_LWIP_IPV6)`'d... `make info-modules` reveals that the module is indeed selected. However, LWIP_IPV6 is 0 as can be shown with. Will have a look where this is coming from...

```diff
diff --git a/tests/lwip/Makefile b/tests/lwip/Makefile
index c7b2472561..42dde78c7c 100644
--- a/tests/lwip/Makefile
+++ b/tests/lwip/Makefile
@@ -16,0 +17,2 @@ endif
+$(warning $(LWIP_IPV6))
+
```

**Comment by miri64** [comment]
Ah...

https://github.com/RIOT-OS/RIOT/blob/ff8983c1551f07876a34de18ea4621a1a81e5def/sys/Makefile.dep#L175-L179

selects `lwip_sixlowpan` (weird that this is in `sys/Makefile.dep`, this should be in `pkg/lwip/Makefile.dep` IMHO). That leads to

https://github.com/RIOT-OS/RIOT/blob/ff8983c1551f07876a34de18ea4621a1a81e5def/pkg/lwip/Makefile.dep#L59-L62

which leads to

https://github.com/RIOT-OS/RIOT/blob/ff8983c1551f07876a34de18ea4621a1a81e5def/pkg/lwip/Makefile.dep#L26-L28

IMHO the very first dependency listed should depend on `lwip_ipv6%` rather than `lwip`.

**Comment by yarrick** [comment]
Only part of because it only fixes the dualstack issue, and not when IPv6 is totally missing.

I don't think we should guard on ipv6_addr, it could be useful to still format such addresses without having protocol support for them. The issue might be that `lwip_sixlowpan` is enabled from sys/, but that does not depend on actual ipv6 support inside lwIP. I think this could be a separate PR however (either skip those interfaces, or fail to even try to compile anything)

**Comment by miri64** [comment]
> I don't think we should guard on ipv6_addr, it could be useful to still format such addresses without having protocol support for them.

Then `ipv6_addr` and `ipv4_addr` should be included in `tests/lwip/Makefile` in all cases.

**Comment by miri64** [comment]
But yes, this can be done as a follow-up. Likewise the dependency fix.

**Review by miri64 — APPROVED** [review]
Fixes the issue described in #17162.

**Comment by miri64** [comment]
:tada: Congrats on your first merge commit!

**Pull request merged**
