### PR TITLE
cpu/cc2538/periph/gpio: use bit-banding macros for thread-safe GPIO

### PR DESCRIPTION
**Pull request by hexluthor**
Replaces the read-modify-write operations with bitband macros from `cpu/k60`. Tested on `cc2538dk`.

### CODE REVIEW

**Comment by gebart** [comment]
If we clean up the K60 macros we could move it to cortexm_common since bit banding is a feature of most (all?) Cortex-M3 and M4 processors.

**Comment by PeterKietzmann** [comment]
Be aware of #6182

**Comment by gebart** [comment]
Needs a rewrite since #6182 was merged

**Comment by aabadie** [comment]
@hexluthor, any chance to have this one rebased for the next release ?

**Comment by gebart** [comment]
I think the best solution is to rebase on top of #6916.

**Comment by hexluthor** [comment]
Agree to all. Will try to deliver for this release.

**Comment by gebart** [comment]
Ping @hexluthor

**Comment by hexluthor** [comment]
Sorry, I don't have time to work on this and don't want to muck it up. If anyone would like to pick up where I left off, please feel free.

**Comment by smlng** [comment]
likely obsolete, with rework done in #7316, #7373 and #7517

**Comment by tcschmidt** [comment]
Any objections to close this?

**Comment by hexluthor** [comment]
I'm closing this because it's hopelessly old, but the cc2538 gpio is still not thread-safe. The gpio functions should be rewritten to call the bitband functions added in #6916.

**Pull request closed without merging**
