### PR TITLE
boards/mulle: cleanup

### LINKED ISSUE #3636: cpu: k60: not using uart_stdio
The k60 is using it's own newlib implementation.

Just making it use the shared newlib module would drop filesystem/fd support from the port, but the port-specific syscalls.c doesn't use uart_stdio, and also it still offers uart0 support.

Could we either

1. make that implementation use uart_stdio and drop uart0
2. factor out the syscalls into its own module, so the user can chose between the shared newlib implementation and the specific one
3. ?

@jfischer-phytec-iot ideas?

### PR DESCRIPTION
**Pull request by gebart**
Remove old syscalls implementation from before cortexm_common unification and sys/newlib introduction.

fixes #3636 

Moved the power pin initialization before clock init to allow peripheral devices to perform power-on initialization while we are simply wasting time spinning in order for the clock to stabilize.

### CODE REVIEW

**Comment by gebart** [comment]
Tested the shell in ng_networking works properly on mulle (the only k60 platform in master)

**Comment by kaspar030** [comment]
Shouldn't this somewhere have a dependency on the newlib module?

I don't have the board, can't test...

**Comment by gebart** [comment]
I think the newlib dependency is defined in cortexm_common. I'm on my
mobile, can't check now, though.

**Comment by kaspar030** [comment]
> the newlib dependency is defined in cortexm_common.

Ah, right. Well, if you say this compiles & works, you have my ACK. Merge at will.

**Comment by gebart** [comment]
confirmed newlib dependency: https://github.com/RIOT-OS/RIOT/blob/master/cpu/Makefile.include.cortexm_common#L9

**Pull request merged**
