### PR TITLE
w5100: fixed RX interrupt handling 

### PR DESCRIPTION
**Pull request by enzingerm**
### Fix for W5100 driver RX interrupt handling
When testing with an W5100 ethernet shield I came across an error where the system freezed when receiving packets. While debugging, I noticed that the `ir` variable holding the interrupt register was never updated (read again from the device) which led the loop to run forever and thus freezing my system. With this fix, receiving packets works fine.

### CODE REVIEW

**Comment by kYc0o** [comment]
I have no way to test this and I didn't find the hardware in FU. Should we merge for this release?

**Comment by dobby880** [comment]
We tested it at LMU with a Nucleo F091 and the following board if that is any helpful for you!

https://www.amazon.de/keyestudio-W5100-Ethernet-Erweiterung-Mega2560-mit-Kartenslot/dp/B01GO2JB4S/ref=sr_1_5?ie=UTF8&qid=1531827121&sr=8-5&keywords=arduino+ethernet

**Comment by kYc0o** [comment]
@dobby880 and your test was successful with this PR?

**Comment by dobby880** [comment]
Yes, that's the setup we provided for @enzingerm . 
If you need more tests, I can do them with other boards (arduino m0, nucleo f411, arduino due) and another w5100 module https://www.mouser.de/ProductDetail/WIZnet/WIZ810MJ?qs=sGAEpiMZZMtNlGR3Dbecs0TQSbQSUOhHEWo8PUSa%252bWU%3d but not before end of July

**Comment by kYc0o** [comment]
@PeterKietzmann do you mind to re-ACK?

**Pull request merged**
