### PR TITLE
netdev: remove NETOPT_IPV6_IID support for network devices

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This option is handled in the `gnrc_netif`-layer without any access to the driver's option since #10569.

The implementation on the device driver is deprecated and was slated for removal in [2019.07 already](https://doc.riot-os.org/group__net__netopt.html#gga19e30424c1ab107c9c84dc0cb29d9906a74f1c2aac469e1132c28cb902007ecfe), so let's get rid of them.

### Testing procedure
Auto-generated IPv6 addresses do not change compared to master in `examples/gnrc_networking` on

- [x] Ethernet-based boards (e.g. `native`)
- [x] IEEE-802.15.4-based boards including `xbee`. (e.g. `samr21-xpro` and `arduino-due` + `xbee`)
- [x] `nrfmin`-based boards (e.g. `nrf51dk`)
- [ ] `cc110x`-based boards (e.g. `msba2`)

Same for `tests/nordic_softdevice`.

Tests still pass.

### Issues/PRs references
Very late follow-up on https://github.com/RIOT-OS/RIOT/pull/10569 and https://github.com/RIOT-OS/RIOT/pull/10595

### CODE REVIEW

**Comment by fjmolinas** [comment]
`xbee` + `arduino-zero`

- pr

```
2020-06-25 11:32:22,656 # ifconfig
2020-06-25 11:32:22,700 # Iface  7  HWaddr: D4:44  Channel: 26  NID: 0x23 
2020-06-25 11:32:22,705 #           Long HWaddr: 00:13:A2:00:40:C2:D4:C4 
2020-06-25 11:32:22,709 #           L2-PDU:100 MTU:1280  HL:64  RTR  
2020-06-25 11:32:22,711 #           6LO  IPHC  
2020-06-25 11:32:22,714 #           Source address length: 8
2020-06-25 11:32:22,717 #           Link type: wireless
2020-06-25 11:32:22,723 #           inet6 addr: fe80::213:a200:40c2:d4c4  scope: link  VAL
2020-06-25 11:32:22,726 #           inet6 group: ff02::2
2020-06-25 11:32:22,729 #           inet6 group: ff02::1
2020-06-25 11:32:22,732 #           inet6 group: ff02::1:ffc2:d4c4
2020-06-25 11:32:22,733 #           
2020-06-25 11:32:22,736 #           Statistics for Layer 2
2020-06-25 11:32:22,739 #             RX packets 0  bytes 0
2020-06-25 11:32:22,744 #             TX packets 0 (Multicast: 0)  bytes 72
2020-06-25 11:32:22,747 #             TX succeeded 0 errors 0
2020-06-25 11:32:22,750 #           Statistics for IPv6
2020-06-25 11:32:22,753 #             RX packets 0  bytes 0
2020-06-25 11:32:22,757 #             TX packets 2 (Multicast: 2)  bytes 128
2020-06-25 11:32:22,760 #             TX succeeded 2 errors 0
2020-06-25 11:32:22,761 # 

```

- master

```
2020-06-25 11:31:28,191 #  ifconfig
2020-06-25 11:31:28,236 # Iface  7  HWaddr: D4:44  Channel: 26  NID: 0x23 
2020-06-25 11:31:28,240 #           Long HWaddr: 00:13:A2:00:40:C2:D4:C4 
2020-06-25 11:31:28,244 #           L2-PDU:100 MTU:1280  HL:64  RTR  
2020-06-25 11:31:28,247 #           6LO  IPHC  
2020-06-25 11:31:28,250 #           Source address length: 8
2020-06-25 11:31:28,252 #           Link type: wireless
2020-06-25 11:31:28,258 #           inet6 addr: fe80::213:a200:40c2:d4c4  scope: link  VAL
2020-06-25 11:31:28,261 #           inet6 group: ff02::2
2020-06-25 11:31:28,264 #           inet6 group: ff02::1
2020-06-25 11:31:28,268 #           inet6 group: ff02::1:ffc2:d4c4
2020-06-25 11:31:28,269 #           
2020-06-25 11:31:28,272 #           Statistics for Layer 2
2020-06-25 11:31:28,275 #             RX packets 0  bytes 0
2020-06-25 11:31:28,279 #             TX packets 0 (Multicast: 0)  bytes 144
2020-06-25 11:31:28,282 #             TX succeeded 0 errors 0
2020-06-25 11:31:28,285 #           Statistics for IPv6
2020-06-25 11:31:28,288 #             RX packets 0  bytes 0
2020-06-25 11:31:28,293 #             TX packets 4 (Multicast: 4)  bytes 256
2020-06-25 11:31:28,296 #             TX succeeded 4 errors 0
2020-06-25 11:31:28,296 # 
```

**Comment by fjmolinas** [comment]
`native`

- pr

```
ifconfig
Iface  6  HWaddr: 52:28:3F:CA:BB:2B 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::5028:3fff:feca:bb2b  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffca:bb2b
          
          Statistics for Layer 2
            RX packets 19  bytes 3296
            TX packets 1 (Multicast: 1)  bytes 78
            TX succeeded 1 errors 0
          Statistics for IPv6
            RX packets 19  bytes 3030
            TX packets 1 (Multicast: 1)  bytes 64
            TX succeeded 1 errors 0
```

- master

```
Iface  6  HWaddr: 52:28:3F:CA:BB:2B 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::5028:3fff:feca:bb2b  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffca:bb2b
          
          Statistics for Layer 2
            RX packets 5  bytes 843
            TX packets 1 (Multicast: 1)  bytes 78
            TX succeeded 1 errors 0
          Statistics for IPv6
            RX packets 5  bytes 773
            TX packets 1 (Multicast: 1)  bytes 64
            TX succeeded 1 errors 0

```

**Comment by aabadie** [comment]
Tested on nrf51dk:

<details><summary>this PR</summary>

```
> ifconfig
ifconfig
Iface  7  HWaddr: 45:8B  Channel: 0  NID: 0xaffe 
           TX-Power: 0dBm  State: IDLE 
          L2-PDU:200 MTU:1280  HL:64  RTR  
          6LO  IPHC  
          Link type: wireless
          inet6 addr: fe80::ff:fe00:458b  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff00:458b
          
          Statistics for Layer 2
            RX packets 0  bytes 0
            TX packets 0 (Multicast: 0)  bytes 52
            TX succeeded 0 errors 0
          Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 2 (Multicast: 2)  bytes 112
            TX succeeded 2 errors 0


```

</details>

<details><summary>master</summary>

```
> ifconfig
ifconfig
Iface  7  HWaddr: 45:8B  Channel: 0  NID: 0xaffe 
           TX-Power: 0dBm  State: IDLE 
          L2-PDU:200 MTU:1280  HL:64  RTR  
          6LO  IPHC  
          Link type: wireless
          inet6 addr: fe80::ff:fe00:458b  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff00:458b
          
          Statistics for Layer 2
            RX packets 0  bytes 0
            TX packets 0 (Multicast: 0)  bytes 52
            TX succeeded 0 errors 0
          Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 2 (Multicast: 2)  bytes 112
            TX succeeded 2 errors 0

> 

```

</details>

**Comment by fjmolinas** [comment]
@maribu @kaspar030 do you have an msba2?

**Comment by miri64** [comment]
@fjmolinas @aabadie remember also to test `tests/nordic_softdevice` with an eligeble device.

**Comment by miri64** [comment]
Fixed issues pointed out by Murdock

**Comment by miri64** [comment]
Just noticed that I accidentally had put the `xbee` change into another commit, so I had to reorganize my git history. As such I squashed.

**Comment by aabadie** [comment]
>  remember also to test tests/nordic_softdevice with an eligeble device.

nordic softdevice is not working for me. I tried on nrf52832-mdk with this PR, master, 2020.04, 2020.01. I'm wondering if it ever worked on this board (I'm flashing with openocd, jlink is not available).
BTW, is nordic softdevice so important since it's deprecated ?

**Comment by miri64** [comment]
> BTW, is nordic softdevice so important since it's deprecated ?

Nope. We can skip if it, if need be. Same (even though not deprecated) for `cc110x`: I think the tests already done, show already, that this option is not needed anymore.

**Comment by fjmolinas** [comment]
> Nope. We can skip if it, if need be. Same (even though not deprecated) for cc110x: I think the tests already done, show already, that this option is not needed anymore.

I think its ok to proceed here.

**Pull request merged**
