### PR TITLE
cpu/kinetis: use LPTMR as rtt backend 

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This pr makes `rtc` use the RTC peripheral and `rtt` use the `RTT` peripheral. This wants to remove the remaining od-ball that is `kinetis`, with this we can simply do:

```
ifneq (,$(filter ztimer_msec,$(USEMODULE))
  FEATURES_OPTIONAL += periph_rtt
  ifneq (,$(filter periph_rtt,$(FEATURES_USED)))
    USEMODULE += ztimer_periph_rtt
  endif
endif

ifneq (,$(filter stm32 nrf52 sam%,$(CPU)))
  RTT_FREQUENCY ?= RTT_MAX_FREQUENCY
  CFLAGS += -DRTT_FREQUENCY=$(RTT_FREQUENCY)
endif
```
 And have `rtt` always pulled as the `ztimer_msec` backend if available.

### Testing procedure

On all kinetis as possible run

- `tests/periph_rtt`

```
2021-06-11 17:59:01,668 # main(): This is RIOT! (Version: 2021.07-devel-322-g92924-HEAD)
2021-06-11 17:59:01,668 # 
2021-06-11 17:59:01,671 # RIOT RTT low-level driver test
2021-06-11 17:59:01,673 # RTT configuration:
2021-06-11 17:59:01,675 # RTT_MAX_VALUE: 0x0000ffff
2021-06-11 17:59:01,677 # RTT_FREQUENCY: 1024
2021-06-11 17:59:01,677 # 
2021-06-11 17:59:01,680 # Testing the tick conversion
2021-06-11 17:59:01,683 # Trying to convert 1 to seconds and back
2021-06-11 17:59:01,687 # Trying to convert 256 to seconds and back
2021-06-11 17:59:01,691 # Trying to convert 65536 to seconds and back
2021-06-11 17:59:01,694 # Trying to convert 16777216 to seconds and back
2021-06-11 17:59:01,699 # Trying to convert 2147483648 to seconds and back
2021-06-11 17:59:01,700 # All ok
2021-06-11 17:59:01,700 # 
2021-06-11 17:59:01,702 # Initializing the RTT driver
2021-06-11 17:59:01,707 # This test will now display 'Hello' every 5 seconds
2021-06-11 17:59:01,707 # 
2021-06-11 17:59:01,708 # RTT now: 4
2021-06-11 17:59:01,711 # Setting initial alarm to now + 5 s (5124)
2021-06-11 17:59:01,714 # rtt_get_alarm() PASSED
2021-06-11 17:59:01,718 # Done setting up the RTT, wait for many Hellos
2021-06-11 17:59:06,708 # Hello
2021-06-11 17:59:11,708 # Hello
2021-06-11 17:59:16,708 # Hello
2021-06-11 17:59:21,709 # Hello
2021-06-11 17:59:26,709 # Hello
2021-06-11 17:59:31,709 # Hello
2021-06-11 17:59:36,709 # Hello
2021-06-11 17:59:41,708 # Hello
2021-06-11 17:59:46,709 # Hello
```

- `tests/periph_rtc`

```
main(): This is RIOT! (Version: 2021.07-devel-323-g3aa10-pr_kinetis_lptmr_rtt)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59
  Alarm cleared at   2020-02-28 23:59:59
       No alarm at   2020-02-28 23:59:59
  Setting alarm to   2020-02-28 23:59:61

Alarm!
Alarm!
Alarm!
Alarm!
```

### CODE REVIEW

**Comment by fjmolinas** [comment]
`pba-d-01-kw2x` doesn't seem to have `LPTMR` so removed `periph_rtt`

**Comment by kaspar030** [comment]
LGTM, but I don't have a board to test.

**Comment by fjmolinas** [comment]
Maybe @benpicco can test? I can provided test output for `frdm-64f`, `frdm-kw41z`, `pba-d-01-kw2x`

**Comment by benpicco** [comment]
Looks good!

```
2021-06-15 10:36:05,811 # main(): This is RIOT! (Version: 2021.04-devel-766-gddbaa-HEAD)
2021-06-15 10:36:05,812 # 
2021-06-15 10:36:05,814 # RIOT RTT low-level driver test
2021-06-15 10:36:05,815 # RTT configuration:
2021-06-15 10:36:05,817 # RTT_MAX_VALUE: 0xffffffff
2021-06-15 10:36:05,819 # RTT_FREQUENCY: 1
2021-06-15 10:36:05,820 # 
2021-06-15 10:36:05,821 # Testing the tick conversion
2021-06-15 10:36:05,825 # Trying to convert 1 to seconds and back
2021-06-15 10:36:05,828 # Trying to convert 256 to seconds and back
2021-06-15 10:36:05,831 # Trying to convert 65536 to seconds and back
2021-06-15 10:36:05,836 # Trying to convert 16777216 to seconds and back
2021-06-15 10:36:05,839 # Trying to convert 2147483648 to seconds and back
2021-06-15 10:36:05,842 # All ok
2021-06-15 10:36:05,842 # 
2021-06-15 10:36:05,844 # Initializing the RTT driver
2021-06-15 10:36:05,847 # This test will now display 'Hello' every 5 seconds
2021-06-15 10:36:05,847 # 
2021-06-15 10:36:05,850 # RTT now: 0
2021-06-15 10:36:05,853 # Setting initial alarm to now + 5 s (5)
2021-06-15 10:36:05,857 # Done setting up the RTT, wait for many Hellos
2021-06-15 10:36:10,844 # Hello
2021-06-15 10:36:15,845 # Hello
2021-06-15 10:36:20,844 # Hello
```

**Comment by fjmolinas** [comment]
- `frdm-kw64F`

```
main(): This is RIOT! (Version: 2021.07-devel-323-gd9ee42-pr_kinetis_lptmr_rtt)

RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0x0000ffff
RTT_FREQUENCY: 1024

Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok

Initializing the RTT driver
This test will now display 'Hello' every 5 seconds

RTT now: 4
Setting initial alarm to now + 5 s (5124)
rtt_get_alarm() PASSED
Done setting up the RTT, wait for many Hellos
Hello
Hello
Hello
Hello
Hello
```

```
main(): This is RIOT! (Version: 2021.07-devel-323-gd9ee42-pr_kinetis_lptmr_rtt)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59
  Alarm cleared at   2020-02-28 23:59:59
       No alarm at   2020-02-28 23:59:59
  Setting alarm to   2020-02-28 23:59:61

Alarm!
Alarm!
Alarm!
Alarm!
```

- `pba-d01-kw2x`

```
main(): This is RIOT! (Version: 2021.07-devel-323-gd9ee42-pr_kinetis_lptmr_rtt)

RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
  Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
  Setting alarm to   2020-02-28 23:59:59
   Alarm is set to   2020-02-28 23:59:59
  Alarm cleared at   2020-02-28 23:59:59
       No alarm at   2020-02-28 23:59:59
  Setting alarm to   2020-02-28 23:59:61

Alarm!
Alarm!
Alarm!
Alarm!
```

**Comment by kaspar030** [comment]
ACK.

**Review by kaspar030 — APPROVED** [review]

**Pull request merged**
