### PR TITLE
drivers: remove accidentally added binary Makefile

### PR DESCRIPTION
**Pull request by haukepetersen**
A binary makefile called `.Makefile.dep.swo` was added with #7586. This seems to be a mistake, right?

### CODE REVIEW

**Comment by cladmi** [comment]
Oops my bad. Would the good solution to add these '.swo' to the repository .gitignore or should I just add them to my global git configuration ?

**Comment by cladmi** [comment]
Yeah I have issue sometime with a tmux mess or reboot with a terminal open.

**Comment by kaspar030** [comment]
we could add .*.swo to gitignore...

**Comment by miri64** [comment]
((`*.swp` is already in `.gitignore`))

You can add files that are only locally relevant to ignore to `.git/info/exclude` for git to ignore them. I do that with the config files for my RIOT-specific vim config well ;-)

**Pull request merged**
