### PR TITLE
tests/periph: Add test using the Peripheral Selftest Shield

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

This adds a test that makes use of the peripheral selftesting shield.

#### ToDo

- [x] Add doc

### Testing procedure

- grab an Arduino UNO compatible board that has the Arduino pin map feature
- connect it to the testing shield
- configure the testing shield
    - make sure the VCC selector matches the logic level of the board (3.3V and 5V are the only options)
    - enabled all the "loops" needed for testing on SW1
    - it could be that the UART on D0, D1 is used for stdio. In that case, do *NOT* close the loop
- flash and run the test application

### Issues/PRs references

none

### CODE REVIEW

**Comment by maribu** [comment]
Ah, it still contains unrelated commits (that are useful to not get the PWM test stuck on an `assert()`) and fix a bug on nRF. I'll drop them now.

**Comment by MichelRottleuthner** [comment]
Just ran it on `nucleo-l476rg`. Runs fine up to the SPI test but there it asserts in the spi_acquire in `tests/periph/selftest_shield/main.c:777` due to an invalid SPI bus. It tries to use `SPI_DEV(1)` but only `SPI_DEV(0)` exists on this board. This is due to ARDUINO_SPI_D11D12D13 being unconditionally defined to SPI_DEV(1) in `boards/common/nucleo64/include/arduino_iomap.h`.  So it seems like this will be at least a problem on all nucleo64 boards that only define a single SPI instance in periph_conf.

**Review by MrKevinWeiss — COMMENTED** [review]
Maybe we can reduce the spam a bit...

```diff
diff --git a/tests/periph/selftest_shield/main.c b/tests/periph/selftest_shield/main.c
index 0c16fd85e2..8de848cdd5 100644
--- a/tests/periph/selftest_shield/main.c
+++ b/tests/periph/selftest_shield/main.c
@@ -783,7 +783,7 @@ static bool periph_spi_rxtx_test(spi_t bus, spi_mode_t mode, spi_clk_t clk,
     /* C̅S̅ should still be HIGH while no chip is selected */
     failed |= TEST(gpio_read(cs_check) != 0);
 
-    for (uint8_t i = 0; i < UINT8_MAX; i++) {
+    for (uint8_t i = 0; i < UINT8_MAX && !failed; i++) {
         uint16_t start = 0;
         if (IS_USED(MODULE_PERIPH_TIMER)) {
             start = timer_read(TIMER);
@@ -808,7 +808,7 @@ static bool periph_spi_rxtx_test(spi_t bus, spi_mode_t mode, spi_clk_t clk,
     failed |= TEST(gpio_read(cs_check) != 0);
 
     /* no also test for different sizes */
-    for (unsigned i = 1; i <= sizeof(testdata); i++) {
+    for (unsigned i = 1; i <= sizeof(testdata) && !failed; i++) {
         uint8_t target[sizeof(testdata) + 4];
         memset(target, 0x55, sizeof(target));
         /* C̅S̅ should be HIGH before chip is selected */
@@ -857,10 +857,10 @@ static bool periph_spi_test(void)
 
     /* using a signed comparison here to also compile when no SPI buses are
      * available for testing */
-    for (int i = 0; i < (int)ARRAY_SIZE(spi_buses); i++) {
+    for (int i = 0; i < (int)ARRAY_SIZE(spi_buses) && !failed; i++) {
         spi_t bus = spi_buses[i];
         gpio_t clk_check = spi_clk_check_pins[i];
-        for (unsigned j = 0; j < ARRAY_SIZE(clocks); j++) {
+        for (unsigned j = 0; j < ARRAY_SIZE(clocks) && !failed; j++) {
             spi_clk_t clk = clocks[j];
             uint32_t clk_hz = clk_hzs[j];
             failed |= periph_spi_rxtx_test(bus, SPI_MODE_0, clk, clk_hz, clk_check, false);

```

I also think it will be pretty hard to identify the failing parameters within the loops.  Maybe one could count the failure messages and try to find the parameters from that...

If this is only meant to indicate pass/fail then better to keep it clean I would think.

**Comment by MrKevinWeiss** [comment]
Seems like all my boards are failing... Maybe it would be good to get rid of the kernel panic
<details>

```
NODE:0:BOARD:nucleo-g474re: r
NODE:0:BOARD:nucleo-g474re: /home/weiss/wd/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM3" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line
NODE:0:BOARD:nucleo-g474re: Twisted not available, please install it if you want to use pyterm's JSON capabilities
NODE:0:BOARD:nucleo-g474re: Connect to serial port /dev/ttyACM3
NODE:0:BOARD:nucleo-g474re: Welcome to pyterm!
NODE:0:BOARD:nucleo-g474re: Type '/exit' to exit.
NODE:0:BOARD:nucleo-g474re: READY
NODE:0:BOARD:nucleo-g474re: s
NODE:0:BOARD:nucleo-g474re: START
NODE:0:BOARD:nucleo-g474re: main(): This is RIOT! (Version: 2023.10-devel-260-g4bf23-peripheral-selftest)
NODE:0:BOARD:nucleo-g474re: self-testing peripheral drivers
NODE:0:BOARD:nucleo-g474re: ===============================
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO at tests/periph/selftest_shield/main.c:283
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO at tests/periph/selftest_shield/main.c:305
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO at tests/periph/selftest_shield/main.c:335
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO at tests/periph/selftest_shield/main.c:365
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO at tests/periph/selftest_shield/main.c:391
NODE:0:BOARD:nucleo-g474re: (skipped)
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:438
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:501
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:564
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:1:BOARD:nucleo-g070rb: r
NODE:0:BOARD:nucleo-g474re: Starting test for I2C at tests/periph/selftest_shield/main.c:638
NODE:1:BOARD:nucleo-g070rb: /home/weiss/wd/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM1" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line
NODE:1:BOARD:nucleo-g070rb: Twisted not available, please install it if you want to use pyterm's JSON capabilities
NODE:1:BOARD:nucleo-g070rb: Connect to serial port /dev/ttyACM1
NODE:1:BOARD:nucleo-g070rb: Welcome to pyterm!
NODE:1:BOARD:nucleo-g070rb: Type '/exit' to exit.
NODE:1:BOARD:nucleo-g070rb: READY
NODE:0:BOARD:nucleo-g474re: [OK]
NODE:0:BOARD:nucleo-g474re: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:0:BOARD:nucleo-g474re: 8002427
NODE:0:BOARD:nucleo-g474re: *** RIOT kernel panic:
NODE:0:BOARD:nucleo-g474re: FAILED ASSERTION.
NODE:0:BOARD:nucleo-g474re: 
NODE:0:BOARD:nucleo-g474re: *** halted.
NODE:0:BOARD:nucleo-g474re: 
NODE:1:BOARD:nucleo-g070rb: s
NODE:1:BOARD:nucleo-g070rb: START
NODE:1:BOARD:nucleo-g070rb: main(): This is RIOT! (Version: 2023.10-devel-260-g4bf23-peripheral-selftest)
NODE:1:BOARD:nucleo-g070rb: self-testing peripheral drivers
NODE:1:BOARD:nucleo-g070rb: ===============================
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO at tests/periph/selftest_shield/main.c:283
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO at tests/periph/selftest_shield/main.c:305
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO at tests/periph/selftest_shield/main.c:335
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO at tests/periph/selftest_shield/main.c:365
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO at tests/periph/selftest_shield/main.c:391
NODE:1:BOARD:nucleo-g070rb: (skipped)
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:438
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:501
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:564
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for I2C at tests/periph/selftest_shield/main.c:638
NODE:2:BOARD:nucleo-f303re: r
NODE:2:BOARD:nucleo-f303re: /home/weiss/wd/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line
NODE:2:BOARD:nucleo-f303re: Twisted not available, please install it if you want to use pyterm's JSON capabilities
NODE:2:BOARD:nucleo-f303re: Connect to serial port /dev/ttyACM0
NODE:2:BOARD:nucleo-f303re: Welcome to pyterm!
NODE:2:BOARD:nucleo-f303re: Type '/exit' to exit.
NODE:2:BOARD:nucleo-f303re: READY
NODE:1:BOARD:nucleo-g070rb: [OK]
NODE:1:BOARD:nucleo-g070rb: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:1:BOARD:nucleo-g070rb: 8002297
NODE:1:BOARD:nucleo-g070rb: *** RIOT kernel panic:
NODE:1:BOARD:nucleo-g070rb: FAILED ASSERTION.
NODE:1:BOARD:nucleo-g070rb: 
NODE:1:BOARD:nucleo-g070rb: *** halted.
NODE:1:BOARD:nucleo-g070rb: 
NODE:2:BOARD:nucleo-f303re: s
NODE:2:BOARD:nucleo-f303re: START
NODE:2:BOARD:nucleo-f303re: main(): This is RIOT! (Version: 2023.10-devel-260-g4bf23-peripheral-selftest)
NODE:2:BOARD:nucleo-f303re: self-testing peripheral drivers
NODE:2:BOARD:nucleo-f303re: ===============================
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO at tests/periph/selftest_shield/main.c:283
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO at tests/periph/selftest_shield/main.c:305
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO at tests/periph/selftest_shield/main.c:335
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO at tests/periph/selftest_shield/main.c:365
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO at tests/periph/selftest_shield/main.c:391
NODE:2:BOARD:nucleo-f303re: (skipped)
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:438
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:501
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:509
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:514
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:519
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:524
NODE:3:BOARD:nucleo-l433rc: r
NODE:3:BOARD:nucleo-l433rc: /home/weiss/wd/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM2" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line
NODE:3:BOARD:nucleo-l433rc: Twisted not available, please install it if you want to use pyterm's JSON capabilities
NODE:3:BOARD:nucleo-l433rc: Connect to serial port /dev/ttyACM2
NODE:3:BOARD:nucleo-l433rc: Welcome to pyterm!
NODE:3:BOARD:nucleo-l433rc: Type '/exit' to exit.
NODE:3:BOARD:nucleo-l433rc: READY
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:529
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:541
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:545
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:550
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:555
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:2:BOARD:nucleo-f303re: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:564
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:572
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:577
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:582
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:587
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:592
NODE:3:BOARD:nucleo-l433rc: s
NODE:3:BOARD:nucleo-l433rc: START
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:604
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:608
NODE:3:BOARD:nucleo-l433rc: main(): This is RIOT! (Version: 2023.10-devel-260-g4bf23-peripheral-selftest)
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:613
NODE:3:BOARD:nucleo-l433rc: self-testing peripheral drivers
NODE:3:BOARD:nucleo-l433rc: ===============================
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:618
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO at tests/periph/selftest_shield/main.c:283
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:2:BOARD:nucleo-f303re: Starting test for I2C at tests/periph/selftest_shield/main.c:638
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO at tests/periph/selftest_shield/main.c:305
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO at tests/periph/selftest_shield/main.c:335
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO at tests/periph/selftest_shield/main.c:365
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO at tests/periph/selftest_shield/main.c:391
NODE:3:BOARD:nucleo-l433rc: (skipped)
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:438
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:2:BOARD:nucleo-f303re: [OK]
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:501
NODE:2:BOARD:nucleo-f303re: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:780
NODE:3:BOARD:nucleo-l433rc: Starting test for GPIO-IRQ at tests/periph/selftest_shield/main.c:564
NODE:3:BOARD:nucleo-l433rc: [OK]
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:806
NODE:3:BOARD:nucleo-l433rc: Starting test for I2C at tests/periph/selftest_shield/main.c:638
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:832
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:3:BOARD:nucleo-l433rc: FAILURE in tests/periph/selftest_shield/main.c:648
NODE:3:BOARD:nucleo-l433rc: [FAILED]
NODE:2:BOARD:nucleo-f303re: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:780
NODE:3:BOARD:nucleo-l433rc: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:3:BOARD:nucleo-l433rc: 8002493
NODE:3:BOARD:nucleo-l433rc: *** RIOT kernel panic:
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:806
NODE:3:BOARD:nucleo-l433rc: FAILED ASSERTION.
NODE:3:BOARD:nucleo-l433rc: 
NODE:3:BOARD:nucleo-l433rc: *** halted.
NODE:3:BOARD:nucleo-l433rc: 
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:832
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:2:BOARD:nucleo-f303re: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:796
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:806
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:2:BOARD:nucleo-f303re: Starting test for SPI at tests/periph/selftest_shield/main.c:763
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:796
NODE:2:BOARD:nucleo-f303re: FAILURE in tests/periph/selftest_shield/main.c:806
NODE:2:BOARD:nucleo-f303re: [FAILED]
NODE:2:BOARD:nucleo-f303re: 
NODE:2:BOARD:nucleo-f303re: 
NODE:2:BOARD:nucleo-f303re: SOME TESTS FAILED
NODE:2:BOARD:nucleo-f303re: { "threads": [{ "name": "main", "stack_size": 1536, "stack_used": 488 }]}
NODE:0:BOARD:nucleo-g474re: Timeout in expect script at "child.expect("ALL TESTS SUCCEEDED")" (tests/periph/selftest_shield/tests/01-run.py:17)
NODE:0:BOARD:nucleo-g474re: 
NODE:0:BOARD:nucleo-g474re: make: *** [/home/weiss/wd/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1
NODE:1:BOARD:nucleo-g070rb: Timeout in expect script at "child.expect("ALL TESTS SUCCEEDED")" (tests/periph/selftest_shield/tests/01-run.py:17)
NODE:1:BOARD:nucleo-g070rb: 
NODE:1:BOARD:nucleo-g070rb: make: *** [/home/weiss/wd/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1
NODE:2:BOARD:nucleo-f303re: Timeout in expect script at "child.expect("ALL TESTS SUCCEEDED")" (tests/periph/selftest_shield/tests/01-run.py:17)
NODE:2:BOARD:nucleo-f303re: 
NODE:2:BOARD:nucleo-f303re: make: *** [/home/weiss/wd/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1
NODE:3:BOARD:nucleo-l433rc: Timeout in expect script at "child.expect("ALL TESTS SUCCEEDED")" (tests/periph/selftest_shield/tests/01-run.py:17)
NODE:3:BOARD:nucleo-l433rc: 
NODE:3:BOARD:nucleo-l433rc: make: *** [/home/weiss/wd/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1
RESULT:NODE:0:BOARD:nucleo-g474re: 2
RESULT:NODE:1:BOARD:nucleo-g070rb: 2
RESULT:NODE:2:BOARD:nucleo-f303re: 2
RESULT:NODE:3:BOARD:nucleo-l433rc: 2
```
</details>

**Comment by MrKevinWeiss** [comment]
The question is do we want to do fixes with this PR or merge it known many boards will be failing?

**Comment by maribu** [comment]
> Maybe it would be good to get rid of the kernel panic (ie. the problem @MichelRottleuthner found)

I just rebased on top of `master` that the failing `assert()` on the SPI bus on Nucleo-64 boards no longer triggers in this branch. The incorrect Arduino mapping for them was fixed in https://github.com/RIOT-OS/RIOT/pull/19935 except for three boards.

> Maybe we can reduce the spam a bit...

I do like the fact that the worse the situation is, the worse the output will look :) I'll add an stop-on-first-failure mode.

I was thinking about adding some more output (e.g. `testing now SPI with speed <num> Hz, clock phase <bool>, clock polarity <bool>`). That would also ease identifying the issue. But that would have to be optional, so that the ROM overhead is only need to be paid by boards that can store a lot of strings.

I'll try to add a fixup that does this.

**Comment by MrKevinWeiss** [comment]
Perfect, I also don't think there are no fundamental issues with the test  and we can get it in for this release.  I don't think it will be forgotten and improvements can come later!

**Review by MrKevinWeiss — APPROVED** [review]
Please squash.

ACK.  probably there will be an issue during the release testing pointing out all the bugs this catches :)

**Comment by MrKevinWeiss** [comment]
Please fix the static checks and we can get this in!

**Comment by maribu** [comment]
Sorry for the delay. I also sneaked in the changed that increases the level of verbosity by adding `DETAILED_OUTPUT=1` to the command line. This makes it easier to e.g. figure out which SPI configuration was tested when a test failed. This should also make it a bit more obvious why a test in the same code location can fail multiple times, when above each failure a message indicates that the same peripheral but a different configuration is tested.

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel

**Comment by MrKevinWeiss** [comment]
looks like murdock pointed out a small issue

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
ugg, maybe casting is needed...

**Comment by maribu** [comment]
bors retry

**Comment by maribu** [comment]
bors retry

**Comment by maribu** [comment]
bors retry

**Comment by maribu** [comment]
bors retry

**Comment by benpicco** [comment]
bors ping

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by maribu** [comment]
Thx everyone! :-)

**Pull request merged**
