### PR TITLE
split WPAN specific options into own command 

### PR DESCRIPTION
**Pull request by jfischer-phytec-iot**
This PR splits WPAN specific options into own command (iwpan, similar on Linux). #5487

Currently it is the reduced version of ifconfig (`sc_netif.c`). The next step would be the removal of overlaps from `sc_netif.c`

### CODE REVIEW

**Comment by miri64** [comment]
Didn't we say `iw` instead of `iwpan`? Also (but don't know if that's possible right now): I would prefer a GNRC-independent solution (so pure `netdev2`).

**Comment by jfischer-phytec-iot** [comment]
>Didn't we say iw instead of iwpan?

Yes but, ``iw`` command is specifically for 802.11 MAC on linux, ``iwpan`` was introduced for 802.15.4 (http://wpan.cakelab.org/). In order to prevent possible confusions, I opted for iwpan :smile:

>Also (but don't know if that's possible right now): I would prefer a GNRC-independent solution (so pure netdev2).

I do not know if it makes sense, I am happy with  ``net_gnrc_netapi`` for now.

:thought_balloon: It is more accurate to interface with the MAC and not with netdev2. The current set of the commands would be possibly the same (common)  for all the 802.15.4 MACs, plus additional MAC specific commands. Interfacing with ``netdev2`` enables direct control over e.g. radio back-end, and I do not know for what it is needed except for testing. :question:

**Comment by miri64** [comment]
> :thought_balloon: It is more accurate to interface with the MAC and not with netdev2. The current set of the commands would be possibly the same (common) for all the 802.15.4 MACs, plus additional MAC specific commands. Interfacing with netdev2 enables direct control over e.g. radio back-end, and I do not know for what it is needed except for testing. :question:

Okay, then maybe later move it to #5511 as soon as that one is somewhat stable. My argument is more about stack-independence than about the layer.

**Comment by miri64** [comment]
I tested and it works (though `ifconfig` still shows IEEE 802.15.4 related stuff, too still). Question remains: what do we do with non-IEEE 802.15.4 radios? Do we duplicate the code that overlaps? Can we find a common module?

**Comment by miri64** [comment]
@jfischer-phytec-iot Ping?

**Comment by miri64** [comment]
Postponed due to Feature Freeze.

**Comment by jfischer-phytec-iot** [comment]
I will unfortunately not have time for it, sorry, it needs new caretaker.

**Pull request closed without merging**
