### PR TITLE
sys/shell: shortened description of netif shell cmd

### PR DESCRIPTION
**Pull request by haukepetersen**
I don't like the line break in the description - and if one needs help with the usage, just call the command to get that information. Also this saves some byte of flash :-)

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK, wanted to fix it myself, but somehow forgot.

**Comment by haukepetersen** [comment]
so waiting for Travis it is :-)

**Comment by authmillenon** [comment]
Only ~100 jobs to go >.<

**Comment by haukepetersen** [comment]
and go (finally)

**Pull request merged**
