### PR TITLE
ng_icmpv6: pre-set checksum field to 0 for sending

### LINKED ISSUE #2988: ng_inet_csum: incorrect checksum calculation
There are reproducable instances, where the the checksum of ICMPv6 (and probably UDP - though not confirmed) packets is wrong: This includes some echo requests ([see the two last ones here](https://www.cloudshark.org/captures/d0aeb1504620), interestingly enough the 4th has the checksum has the checksum the 3rd was expecting) and echo replies, when testing #2910 with two nodes on `ng_nativenet`: https://www.cloudshark.org/captures/b985f35e13a1 (packet 4).

@sgso also observed echo requests where the checksum will always be off by `0x700`.

### PR DESCRIPTION
**Pull request by authmillenon**
Hopefully fixes #2988.

### CODE REVIEW

**Comment by OlegHahm** [comment]
I don't have neither enough insights nor time to test, if this fixes the bug, but this to be at least a good idea. ACK

**Comment by authmillenon** [comment]
It's not just a good idea, it's how a checksum is supposed to be calculated ;-)

**Comment by OlegHahm** [comment]
Yes, I know. But I wasn't able to check if this not done elsewhere.

**Comment by authmillenon** [comment]
No, it did not, but I think it is a better idea to initialize it here. Can't really rationally argue why though.

**Comment by authmillenon** [comment]
[it was however never set, which is why some packets had a correct checksum and some did not, since there was garbage (or more precise because of the traffic predictability in most cases the checksum of the previous package) still in there]

**Comment by OlegHahm** [comment]
As long as it is documented that the checksum calculation expects an initialized value, I don't care.

**Comment by sgso** [comment]
Works for me. Checksums are correct now.

**Pull request merged**
