### PR TITLE
boards/nucleo32-l432: initial support

### PR DESCRIPTION
**Pull request by aabadie**
This adds support for nucleo-l432kc. Thanks to @haukepetersen work on stm32l4, it was easy to add.

### CODE REVIEW

**Comment by aabadie** [comment]
Marking this one as WIP:
* I'd like to extend the board configuration (PWM, SPI, etc)
* There's an issue with the shell : the UART isr doesn't work. I still have to dig into this.

**Comment by aabadie** [comment]
No more WIP, all is working.

**Comment by astralien3000** [comment]
I tested : default (saul LED), periph_timer, periph_uart, periph_pwm and xtimer_usleep.
Everything is ok !

**Comment by aabadie** [comment]
Thanks @astralien3000, that was fast :)
Anyone for a quick code review and an ACK ? @vincent-d @haukepetersen ?

**Comment by aabadie** [comment]
@haukepetersen this branch is ready. I adapted the interrupt number macro for the stm32l432kc MCU.

**Comment by vincent-d** [comment]
Murdock is OK, go

**Pull request merged**
