### PR TITLE
native: compile with -g, "make term" runs through gdb

### PR DESCRIPTION
**Pull request by kaspar030**
Trying to debug #5040...

### CODE REVIEW

**Comment by kaspar030** [comment]
Let's see if this shows a backtrace in Murdock ...

**Comment by cgundogan** [comment]
I am full of excitement

**Comment by cgundogan** [comment]
`Terminal program gdb -ex r -ex bt -batch /data/riotbuild/tests/unittests/bin/native/unittests.elf not found. Aborting.`

**Comment by kaspar030** [comment]
No gdb in the riot docker images?

**Comment by cgundogan** [comment]
>No gdb in the riot docker images?

ah yes, I had to install gdb manually yesterday, too when I was testing out docker

**Comment by kaspar030** [comment]
I'll add it to the murdock image...

**Comment by OlegHahm** [comment]
> Program received signal SIGSEGV, Segmentation fault.
0x0804baaf in main () at main.c:40
40	    while(1) *fail++ = '\0';
#0  0x0804baaf in main () at main.c:40

looks "good" :+1:

**Comment by kaspar030** [comment]
Ok, I'll drop the fail commit.

**Comment by cgundogan** [comment]
hmm .. not sure if we should opt for running gdb as `TERMPROG` default.. Isn't this why we have the targets `all-debug` and `debug` on native?

**Comment by kaspar030** [comment]
Hm. I see your point.
Does it hurt?

**Comment by kaspar030** [comment]
"all-debug" builds with debug symbols, so indeed, that would be redundant.
"debug" starts a full debugging session. This PR uses gdb's "-batch" mode, which is exactly for the purpose of getting backtraces, without launching a full interactive session.

IMHO, for native, performance didn't really matter in the past (as we're building without any optimization), and so always adding the debug symbols will probably make life easier for us devs.

**Comment by cgundogan** [comment]
well .. for now this will break our riot docker image, because we have no gdb installed there by default. I agree with you that this will not hurt anything on native, so I will probably ACK because of the usefulness that we win from this. An alternative would be to use the gdb command in the test scripts instead of using `make term/test` What do you think about that?

**Comment by kaspar030** [comment]
> An alternative would be to use the gdb command in the test scripts instead of using make term/test What do you think about that?

Yes, or better, just set the term line for our static tests. I'll update.

**Comment by cgundogan** [comment]
>Yes, or better, just set the term line for our static tests. I'll update.

ah right :+1:

**Comment by kaspar030** [comment]
Works perfectly. Should we merge, so we can see what's wrong in #5040? ;)

**Comment by OlegHahm** [comment]
Let's go!

**Comment by kaspar030** [comment]
dockerfile PR: https://github.com/RIOT-OS/riotdocker/pull/20

**Comment by Yonezawa-T2** [comment]
I got the following message from Travis:
```
 Terminal program gdb -batch -ex r -ex bt /home/travis/build/RIOT-OS/RIOT/tests/unittests/bin/native/unittests.elf not found. Aborting.
```
https://travis-ci.org/RIOT-OS/RIOT/jobs/118144712

The message is also generated from CI of this PR.
https://travis-ci.org/RIOT-OS/RIOT/jobs/118095472

Is the message relate to this PR? Is Travis deprecated in favor of RIOT CI?

**Pull request merged**
