### PR TITLE
makefile: indentation cleanup

### PR DESCRIPTION
**Pull request by aabadie**
While reviewing #7636, I noticed there were indentation inconsistencies (4 spaces instead of 2) remaining in some makefiles, at least where `DIRS += ` is used.

### CODE REVIEW

**Comment by smlng** [comment]
Just for clarification, we use 4 space indention in C and header files and 2 space indention for Makefiles? I'm fine with that and not questioning the effort here, but I didn't know we have a (separate) rule for Makefiles - or is more an agreement by majority usage?

**Comment by cladmi** [comment]
Also `sys/auto_init/Makefile` has no indentation for `DIRS +=`. I will check if there are others.

**Comment by cladmi** [comment]
It looks like `sys/auto_init/Makefile` is the only one left with bad indented `DIRS +=`.

> Reviewed with
> vim $(git grep -e '^ *DIRS *+=' | grep -v  'Makefile.*:  DIRS'  | sed 's/\([^:]*\):.*/\1/' | sort -u)

**Comment by aabadie** [comment]
Thanks @cladmi. Pushed the update and fixed other places (with UNIT_TESTS). There might be other keywords than `DIRS += ` to look for...

**Comment by aabadie** [comment]
@cladmi @miri64, I pushed a couple of extra commits to cleanup indentation in other places (with CFLAGS and export keywords).

**Comment by miri64** [comment]
@smlng there is a syntactic difference in make between spaces and tabs (target definitions actually *have* to start with tabs). To prevent confusing the two spaces were agreed upon for non-command-definition indentations.

**Pull request merged**
