### PR TITLE
drivers/periph_timer: Use uint32_t over unsigned long for frequency

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

For all currently supported architectures `unsigned long` is 32 bit in size. But let's better use `uint32_t` to make sure frequencies are given in 32 bit on future platforms. Also, yadda yadda MISRA C.

### Testing procedure

- Green Murdock
- No change in binaries

### Issues/PRs references

None

### CODE REVIEW

**Comment by maribu** [comment]
Note to myself: Squash by hand due to incorrect commit being referenced in fixup.

**Comment by benpicco** [comment]
Just squash alea, no need to run Murdock twice

**Comment by maribu** [comment]
> no need to run Murdock twice

Sorry, read this to late. But I squashed now.

**Review by benpicco — APPROVED** [review]

**Comment by maribu** [comment]
Thanks :-)

**Pull request merged**
