### PR TITLE
auto_init: rename auto_init_ng_netif to auto_init_gnrc_netif

### PR DESCRIPTION
**Pull request by authmillenon**
As prophecised in its introduction: I missed that one in #3645.

But it wasn't that hard:
```bash
# remove legacy files
git rm -rf boards/samr21-xpro/auto_init_gnrc_netif/
git rm -rf tests/driver_*/auto_init_ng_netif/
# move directories
find . -type d -name auto_init_ng* | while read f; do
  git mv "${f}" "${f/_ng_/_gnrc_}"
done
# move files
find . -type f -name auto_init_ng* | while read f; do
  git mv "${f}" "${f/_ng_/_gnrc_}"
done
git grep --name-only "auto_init_ng" | 
  xargs sed -i 's/auto_init_ng/auto_init_gnrc/g'
git grep --name-only "AUTO_INIT_NG" |
  xargs sed -i 's/AUTO_INIT_NG/AUTO_INIT_GNRC/g'
```

### CODE REVIEW

**Comment by OlegHahm** [comment]
Can you put the cleanup of the test application in a separate commit?

**Comment by authmillenon** [comment]
Done.

**Comment by jremmert-phytec-iot** [comment]
Seems good to me, **but** currently I don't have any hardware to test. I also haven't tracked the complete renaming process. So I suggest someone else should review and test this, sry.

@jfischer-phytec-iot Do you have a minute to verify and test it?

**Comment by authmillenon** [comment]
> Seems good to me, but currently I don't have any hardware to test. I also haven't tracked the complete renaming process. So I suggest someone else should review and test this, sry.

I mainly assigned you because I saw that you wrote one file I removed and took that as a great oportunity to assign someone else than my usual people :D. But if you are not able to test: please do re-assign :-)

**Comment by jremmert-phytec-iot** [comment]
>I mainly assigned you because I saw that you wrote one file I removed and took that as a great oportunity to assign someone else than my usual people :D.

I appreciate that and I will hopefully be up on track in some weeks.

> But if you are not able to test: please do re-assign :-)

I have no privileges for reassignment in Github. I will go to ask for them as soon as I will have more time to work on RIOT. Until then you need to carry out the reassignment ;).

**Comment by authmillenon** [comment]
Since @kaspar030 already made a duplicate PR of this I assign him :-)

**Comment by kaspar030** [comment]
ACK & go!

**Pull request merged**
