### PR TITLE
sys/net/dhcpv6: Refactor DHCPv6 client

### PR DESCRIPTION
**Pull request by JKRhb**
### Contribution description

This PR makes a couple of changes to the DHCPv6 client implementation to increase maintainability and the possibility to add new features.

It mostly moves existing code to separate functions but also refactors the composition of messages by adding a new `_compose_message` function which eliminates some code duplication and makes it easier to see which options are used (or requested) with each message type. This should also make it easier to add additional features like information-requests to the client.

### Testing procedure

You can use the existing tests under `tests/gnrc_dhcpv6_client` and `tests/gnrc_dhcpv6_client_6lbr`. Despite the changes, these should still work.

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
ACK. Confirmed that this code mostly moves code and removes code duplication. I ran both `tests/gnrc_dhcpv6_client` and `tests/gnrc_dhcpv6_client_6lbr` and both still succeed (with the usual OS-specific adaptations I need to do with Arch:

```diff
diff --git a/tests/gnrc_dhcpv6_client/Makefile b/tests/gnrc_dhcpv6_client/Makefile
index 5c8b0c0d89..98ccf027d4 100644
--- a/tests/gnrc_dhcpv6_client/Makefile
+++ b/tests/gnrc_dhcpv6_client/Makefile
@@ -39,10 +39,13 @@ TEST_ON_CI_BLACKLIST += all
 
 include $(RIOTBASE)/Makefile.include
 
-.PHONY: dhcpv6_server
+.PHONY: dhcpv6_server sudo
 
-dhcpv6_server:
-	$(CURDIR)/dhcpv6_server.sh $(DHCPV6_SERVER_PORT) $(CURDIR)/kea-dhcp6.conf
+dhcpv6_server: sudo
+	sudo $(CURDIR)/dhcpv6_server.sh $(DHCPV6_SERVER_PORT) $(CURDIR)/kea-dhcp6.conf
+
+sudo:
+	@sudo true
 
 ifeq (,$(filter native,$(BOARD)))
 .PHONY: ethos
diff --git a/tests/gnrc_dhcpv6_client/kea-dhcp6.conf b/tests/gnrc_dhcpv6_client/kea-dhcp6.conf
index b42eade5bd..a2a8ab429c 100644
--- a/tests/gnrc_dhcpv6_client/kea-dhcp6.conf
+++ b/tests/gnrc_dhcpv6_client/kea-dhcp6.conf
@@ -27,20 +27,5 @@
                          "prefix-len": 33,
                          "delegated-len": 64 } ] }
     ]
-  },
-"Logging":
-{
-  "loggers": [
-    {
-      "name": "kea-dhcp6",
-      "output_options": [
-          {
-            "output": "stderr"
-          }
-      ],
-      "severity": "INFO",
-      "debuglevel": 0
-    }
-  ]
-}
+  }
 }
```

)

**Comment by miri64** [comment]
BTW: what do you think of using `sock_async` for the client message exchanges? This way, both the DHCPv6 relay and client could run in the same thread (as the client would not block on receive anymore).

**Comment by JKRhb** [comment]
> BTW: what do you think of using `sock_async` for the client message exchanges? This way, both the DHCPv6 relay agent and client could run in the same thread (as the client would not block on receive anymore).

That sounds very good :) I guess this would also make it easier to add support for reconfigure messages in the client.

**Comment by benpicco** [comment]
I think this broke operation with two downstream interfaces and `CFLAGS += -DCONFIG_DHCPV6_CLIENT_PFX_LEASE_MAX=2`:

```
2022-02-17 16:36:47,420 # DHCPv6: Selecting interface 7 as upstream
2022-02-17 16:36:47,935 # DHCPv6 client: send SOLICIT
2022-02-17 16:36:48,966 # DHCPv6 client: resend SOLICIT
2022-02-17 16:36:51,124 # DHCPv6 client: resend SOLICIT
2022-02-17 16:36:55,430 # DHCPv6 client: resend SOLICIT
2022-02-17 16:36:55,436 # DHCPv6 client: received ADVERTISE
2022-02-17 16:36:55,439 # DHCPv6 client: scheduling REQUEST
2022-02-17 16:36:55,441 # DHCPv6 client: send REQUEST
2022-02-17 16:36:55,521 # DHCPv6 client: received REPLY
2022-02-17 16:36:55,525 # DHCPv6 client: scheduling RENEW in 1800 sec
2022-02-17 16:36:55,529 # DHCPv6 client: scheduling REBIND in 2880 sec

2022-02-17 16:36:58,931 # Iface  7  HWaddr: FC:C2:3D:0B:D4:4F 
2022-02-17 16:36:58,936 #           L2-PDU:1500  MTU:1492  HL:255  RTR  
2022-02-17 16:36:58,939 #           Source address length: 6
2022-02-17 16:36:58,941 #           Link type: wired
2022-02-17 16:36:58,947 #           inet6 addr: fe80::fec2:3dff:fe0b:d44f  scope: link  VAL
2022-02-17 16:36:58,954 #           inet6 addr: 2001:16b8:459a:b900:fec2:3dff:fe0b:d44f  scope: global  VAL
2022-02-17 16:36:58,957 #           inet6 group: ff02::2
2022-02-17 16:36:58,959 #           inet6 group: ff02::1
2022-02-17 16:36:58,963 #           inet6 group: ff02::1:ff0b:d44f
2022-02-17 16:36:58,964 #           
2022-02-17 16:36:58,967 #           Statistics for Layer 2
2022-02-17 16:36:58,970 #             RX packets 70  bytes 13706
2022-02-17 16:36:58,975 #             TX packets 9 (Multicast: 9)  bytes 922
2022-02-17 16:36:58,978 #             TX succeeded 9 errors 0
2022-02-17 16:36:58,981 #           Statistics for IPv6
2022-02-17 16:36:58,984 #             RX packets 21  bytes 4889
2022-02-17 16:36:58,988 #             TX packets 9 (Multicast: 9)  bytes 796
2022-02-17 16:36:58,991 #             TX succeeded 9 errors 0
2022-02-17 16:36:58,992 # 
2022-02-17 16:36:58,995 # Iface  6  HWaddr: 66:9B:87:4C:57:53 
2022-02-17 16:36:58,999 #           L2-PDU:1500  MTU:1500  HL:64  RTR  
2022-02-17 16:36:59,002 #           Source address length: 6
2022-02-17 16:36:59,005 #           Link type: wired
2022-02-17 16:36:59,010 #           inet6 addr: fe80::649b:87ff:fe4c:5753  scope: link  VAL
2022-02-17 16:36:59,013 #           inet6 group: ff02::2
2022-02-17 16:36:59,016 #           inet6 group: ff02::1
2022-02-17 16:36:59,019 #           inet6 group: ff02::1:ff4c:5753
2022-02-17 16:36:59,020 #           
2022-02-17 16:36:59,023 #           Statistics for Layer 2
2022-02-17 16:36:59,026 #             RX packets 0  bytes 0
2022-02-17 16:36:59,030 #             TX packets 4 (Multicast: 4)  bytes 0
2022-02-17 16:36:59,034 #             TX succeeded 0 errors 4
2022-02-17 16:36:59,036 #           Statistics for IPv6
2022-02-17 16:36:59,039 #             RX packets 0  bytes 0
2022-02-17 16:36:59,044 #             TX packets 4 (Multicast: 4)  bytes 224
2022-02-17 16:36:59,047 #             TX succeeded 4 errors 0
2022-02-17 16:36:59,047 # 
2022-02-17 16:36:59,050 # Iface  5  HWaddr: 66:9B:87:4C:57:52 
2022-02-17 16:36:59,054 #           L2-PDU:1500  MTU:1500  HL:64  RTR  
2022-02-17 16:36:59,056 #           RTR_ADV  
2022-02-17 16:36:59,059 #           Source address length: 6
2022-02-17 16:36:59,061 #           Link type: wired
2022-02-17 16:36:59,067 #           inet6 addr: fe80::649b:87ff:fe4c:5752  scope: link  VAL
2022-02-17 16:36:59,074 #           inet6 addr: 2001:16b8:459a:b9f4:649b:87ff:fe4c:5752  scope: global  VAL
2022-02-17 16:36:59,077 #           inet6 group: ff02::2
2022-02-17 16:36:59,080 #           inet6 group: ff02::1
2022-02-17 16:36:59,083 #           inet6 group: ff02::1:ff4c:5752
2022-02-17 16:36:59,084 #           
2022-02-17 16:36:59,087 #           Statistics for Layer 2
2022-02-17 16:36:59,090 #             RX packets 0  bytes 0
2022-02-17 16:36:59,095 #             TX packets 4 (Multicast: 4)  bytes 0
2022-02-17 16:36:59,098 #             TX succeeded 0 errors 4
2022-02-17 16:36:59,100 #           Statistics for IPv6
2022-02-17 16:36:59,103 #             RX packets 0  bytes 0
2022-02-17 16:36:59,108 #             TX packets 4 (Multicast: 4)  bytes 264
2022-02-17 16:36:59,111 #             TX succeeded 4 errors 0

2022-02-17 16:37:46,967 # nib prefix
2022-02-17 16:37:46,974 # 2001:16b8:459a:b900::/64 dev #7  expires 7145 sec deprecates 3545 sec
2022-02-17 16:37:46,980 # 2001:16b8:459a:b9f4::/62 dev #5  expires 7148 sec deprecates 3548 sec
```

Previously both downstream interfaces would receive a prefix

**Comment by benpicco** [comment]
Looks like my router is the culprit, something must have changed with a recent update.
This still works with

    make -C examples/gnrc_border_router USE_DHCPV6=1 ZEP_DEVICES=2 all term

```
Iface  8  HWaddr: 63:70  Channel: 26  NID: 0x23  PHY: O-QPSK 
          Long HWaddr: AA:38:98:C1:4A:8F:63:70 
           State: IDLE 
          ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::a838:98c1:4a8f:6370  scope: link  VAL
          inet6 addr: 2001:db8:0:4:a838:98c1:4a8f:6370  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff8f:6370
          
Iface  7  HWaddr: 63:71  Channel: 26  NID: 0x23  PHY: O-QPSK 
          Long HWaddr: AA:38:98:C1:4A:8F:63:71 
           State: IDLE 
          ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::a838:98c1:4a8f:6371  scope: link  VAL
          inet6 addr: 2001:db8:0:5:a838:98c1:4a8f:6371  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff8f:6371
          
Iface  6  HWaddr: 7A:37:FC:7D:1A:AF 
          L2-PDU:1500  MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::7837:fcff:fe7d:1aaf  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff7d:1aaf
```

sorry for the noise.

**Pull request merged**
