### PR TITLE
doccheck: avoid generating dot or html

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

doccheck without generating dot or html

this also has some new generated lines for exclude_pattern (some of them where broke so I regenerated the block)

### Testing procedure

doccheck

### CODE REVIEW

**Comment by kaspar030** [comment]
> this also has some new generated lines for exclude_pattern (some of them where broke so I regenerated the block)

that takes the option of just comparing the warnings master / PR. also the doccheck commit also modifies `exclude_patterns`, so revert of the fixed patterns won't work.

After `git co master -- dist/tools/doccheck/exclude_patterns`, I do get less warnings with this PR compared to master. Is that expected?

**Comment by kaspar030** [comment]
otherwise, works as expected. and less warnings might be better. :)

**Review by kaspar030 — APPROVED** [review]

**Comment by kaspar030** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by kfessel** [comment]
> > this also has some new generated lines for exclude_pattern (some of them where broke so I regenerated the block)
> 
> that takes the option of just comparing the warnings master / PR. also the doccheck commit also modifies `exclude_patterns`, so revert of the fixed patterns won't work.

the patterns modified with the first commit where broken (opened groups without closing, used lists where they should not be used in exclude patterns and had unescaped `.`)

the pattern added by the second commit is necessary for the check build target for that reason it is in the same commit.
 
> After `git co master -- dist/tools/doccheck/exclude_patterns`, I do get less warnings with this PR compared to master. Is that expected?

i will have an other  look at these (maybe some warning-errors are only happening when `html` and `dot` are build)

**Comment by kfessel** [comment]
these are types of warnings that might be missed with the check build:
```
error: md5 hash does not match for two different runs of RIOT/doc/doxygen/html/3_2include_2arduino__board__common_8h__incl.dot !
 warning: found documented return type for *** that does not return anything
 warning: explicit link request to *** could not be resolved
 warning: unable to resolve reference to *** for \ref command
```

the 3w arnings would still show up, if we build html but disable dot  (and we will get some extra warnings for `/dot` commands that are used in in our documentation

**Pull request merged**
