### PR TITLE
cflags: use gnu99 only if nothing else is specified (mips, msp430, native)

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

On mips, msp430 and native, the `-std` option was forced to `gnu99` even though the user changed it.
This propose to change it only if nothing else is passed in the `CFLAGS` by adding a makefile variable and use it in the central cflags.inc.mk

### Issues/PRs references

Workaround #9371 by allowing a user to switch to c11.
First gnu99 changes were introduced in #5824

### CODE REVIEW

**Comment by kaspar030** [comment]
How about adding ```CFLAGS_STD```? If evaluated using ```CFLAGS_STD ?= foo``` at the right spots, we might save some of the logic.

**Comment by vincent-d** [comment]
> How about adding CFLAGS_STD?

While I also believe it could save some of the logic, it will break any existing app already using `CFLAGS += -std=...` so I'm not sure if it's the best choice.

**Comment by vincent-d** [comment]
Renamed the variable to `STD_DEFAULT_GNU_99` and added to `vars.inc.mk`. I don't know if it should be exported or not, though.

**Comment by vincent-d** [comment]
Ping @gebart @kaspar030

**Comment by gebart** [comment]
After some consideration, I am reluctant to add yet another environment variable to the build system. What do you think about using this instead? 
```make
ifeq (, filter(-std=%, $(CFLAGS)))
CFLAGS += -std=gnu99
endif
```

**Comment by vincent-d** [comment]
@gebart you're right it's actually easier. See the last update

**Comment by gebart** [comment]
Initial Murdock failure was unrelated, retry fixed it. -> go

**Pull request merged**
