### PR TITLE
core: redefine LOG macro to fix tautological compare error

### PR DESCRIPTION
**Pull request by smlng**
required by #6600

### CODE REVIEW

**Comment by smlng** [comment]
mhm, okay need to this another way. I'll see to it

**Comment by smlng** [comment]
for clarification, the statement:

```
#define LOG(level, ...) if (level <= LOG_LEVEL) log_write(level, __VA_ARGS__)
```

led to a _tautological compare_ error when using toolchain LLVM. I read they also added this to gcc 6.x.y, so this will likely hit more often in the future.

This PR resolves the issue ...

**Comment by gebart** [comment]
The original idea of these tautological comparisons was to enable the
compiler to do syntax checks during CI build tests, but to let the
optimizer kick out the unreachable log calls. I don't like the thought of
removing that robustness check. We used to have a lot of broken debug
prints in various places in the code but they didn't fail until you tried
to build with ENABLE_DEBUG 1. That was a hassle because when you wanted to
debug some failure in the application you would have to start with fixing
the debug printfs before you could look for the actual problem.

**Comment by smlng** [comment]
@gebart please note that the logging defined here, has nothing to do with logging done be `ENABLE_DEBUG`! This logging facility is enabled when you `#include "log.h"` into your code and set an appropriate `LOG_LEVEL`, default is `LOG_INFO` -- while the other is done by `#include "debug.h"`.

**Comment by kaspar030** [comment]
> and set an appropriate LOG_LEVEL, default is LOG_INFO

If you don't, the log code will be kicked out by the preprocessor, which this log.h previously intentionally tried to not do.

Can this be fixed with pragmas?

**Comment by smlng** [comment]
@kaspar030 please elaborate, I'm unsure what you mean? 

In any case with whatever `LOG_LEVEL`, `LOG_{ERROR|WARNING|INFO|DEBUG}` will be defined as `(void)(0)`.

**Comment by smlng** [comment]
@kaspar030 ping!

**Comment by kaspar030** [comment]
> In any case with whatever LOG_LEVEL, LOG_{ERROR|WARNING|INFO|DEBUG} will be defined as (void)(0).

Exactly that is what the log module tries to avoid. Not used debug code will end up as

```
if (0 < 1) {
   ...
}
```

... which the compile correctly marks as always true.
The idea is that the optimizer just removes the code, *after* it has been syntax checked.

Historically, there were proper changes to code, which did not update the corresponding DEBUG statements. Enabling DEBUG would break the compile, but our CI would not spot those as per default we compile with ```ENABLE_DEBUG == 0```.

The next time someone wanted to actually debug, a lot of time was lost repairing broken debug statements elsewhere in the file.

That's why this PR's solution is contrary to what the module tries to achieve.

It should be possible to disable the warning (which points to expected behavior), using compiler pragmas. Sth like push/tautological-compare/<function>/pop should do.

**Comment by kaspar030** [comment]
> Historically

Just realized that @gebart already explained this...

**Comment by kaspar030** [comment]
@smlng Can you try if this patch solves the problem?

https://gist.github.com/kaspar030/621c5929cb8256b5e327180b67739efd

**Comment by smlng** [comment]
closing, superseded by #6744

**Pull request closed without merging**
