### PR TITLE
gnrc_tcp: Add missing includes

### PR DESCRIPTION
**Pull request by brummer-simon**
This PR adds missing includes required by GNRC_TCP.

### CODE REVIEW

**Comment by miri64** [comment]
Instead of `gnrc/pktbuf.h` and `gnrc/netreg.h` you could also just use `gnrc.h` ;-)

**Comment by miri64** [comment]
@smlng @kaspar030 why are tests running even though I did not set the CI-test label?

**Comment by miri64** [comment]
(the fail is unrelated to this PR)

**Comment by smlng** [comment]
because native tests are executed with every build (was surprised too, when I found out first), ci-test label only triggers tests on boards, i.e., samr21-xpro as of now.

**Comment by miri64** [comment]
Ok... That explains why build times went up so significantly ^^... Anyway, merge!

**Pull request merged**
