### PR TITLE
cpu/stm32f1: simplified pin initialization in periph drivers

### PR DESCRIPTION
**Pull request by haukepetersen**
~~based on #3535~~

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Why?

**Comment by haukepetersen** [comment]
easy: much easier to read, less lines of code and less code-size.

**Comment by PeterKietzmann** [comment]
No, I meant, why separate PR. Anyway, now I see. Let's merge #3535 first

**Comment by haukepetersen** [comment]
ups, I see. I just like to have rather small PRs (if possible) -> easier to review. But one can of course test both at once...

**Comment by PeterKietzmann** [comment]
Ups, nearly forgot this one. Please rebase

**Comment by haukepetersen** [comment]
rebased.

**Comment by PeterKietzmann** [comment]
Tested by Travis and me. ACK and go

**Pull request merged**
