### PR TITLE
net: update ng_* version documentation + some fixes

### PR DESCRIPTION
**Pull request by authmillenon**
Applies naming scheme according to #2422 and fixes some syntax issues.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
```
Generating docs for f/home/lo/RIOT/sys/include/net/ng_netreg.h:40: warning: unable to resolve reference to `ng_netreg' for \ref command
/home/lo/RIOT/sys/include/net/ng_netreg.h:32: warning: unable to resolve reference to `ng_netreg' for \ref command
<unknown>:1: warning: unable to resolve reference to `ng_netreg' for \ref command
ile ng_netconf.h...
```

**Comment by authmillenon** [comment]
Fixed

**Comment by LudwigOrtmann** [comment]
ACK, please squash

**Comment by authmillenon** [comment]
Squashed

**Pull request merged**
