### PR TITLE
xtimer: small cleanups

### PR DESCRIPTION
**Pull request by gebart**
This PR is only a clean up of xtimer code, no added functionality or bugs fixed. This clean up is necessary to make future xtimer PRs more readable and easier to follow.

### CODE REVIEW

**Comment by kaspar030** [comment]
ACK.

**Comment by kaspar030** [comment]
@gebart Would some squashing make sense?

**Comment by gebart** [comment]
@kaspar030 I can squash them if you want, what should I do with the commit message? Make a single list from the current (split) commit messages?

**Comment by kaspar030** [comment]
@gebart Actually the commits are fine as is. Lets skip the squashing. :)

**Comment by gebart** [comment]
Travis is happy -> go

**Pull request merged**
