### PR TITLE
cpu: Use thread_getpid() and thread_get_active() instead of sched_active_*

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Replaced all occurrences of `sched_active_pid` and `sched_active_thread` with the corresponding API calls. (Noteworthy exceptions: ESP platform handled in https://github.com/RIOT-OS/RIOT/pull/14772, and all assembly code.)

### Testing procedure

In most cases the generated binaries should not change. (When repeatedly accessing `sched_active_thread` while IRQs disabled, I introduced a temporary `thread_t *` variable without the `volatile` qualifier. This could result in more efficient code being generated.)

### Issues/PRs references

Same as https://github.com/RIOT-OS/RIOT/pull/14772, but for all non-ESP platforms.

### CODE REVIEW

**Comment by benpicco** [comment]
Travis found something to nitpick on `fe310`.

**Comment by maribu** [comment]
> There is also still `sched_active_thread` in `arm7_common/common.s`.

That's intentionally. For now, this PR only updates C code. With inline assembly, it would be possible to use the API calls using GCC's extended asm to pass the address as argument. But for plain assembly files, this is not an option. It might be possible however to re-implement `arm7_common/common.s` in C with some inline assembly. IMO, that would be a good thing to do, as few people are really comfortable with assembly code anyway.

**Comment by maribu** [comment]
All green :-)

**Comment by maribu** [comment]
Thanks for the review!

**Pull request merged**
