### PR TITLE
evtimer: optimized adding

### PR DESCRIPTION
**Pull request by Josar**
Minor changes to optimize adding an event timer.

Removes variable  `delta_sum` and three calculations.

### CODE REVIEW

**Comment by kaspar030** [comment]
> Minor changes to optimize adding an event timer.

can you elaborate? +19 -6 doesn't seem minor.

**Comment by Josar** [comment]
@kaspar030 most of the +19 are comments and DEBUG().

**Comment by Josar** [comment]
@smlng better like this?

**Comment by smlng** [comment]
looks good to me now, @miri64 and @kaspar030 any objections?

**Comment by kaspar030** [comment]
> looks good to me now, @miri64 and

Nope, let's go. Thanks @Josar!

**Pull request merged**
