### PR TITLE
tests: optimize xtimer drift for size

### PR DESCRIPTION
**Pull request by smlng**
the test description was inlined with `puts`, which caused unnecessary blown up memory sizes. 

This PR moves most of the text into a separate README. With this improvements the test works on _arduino duemilanove_ with 2K RAM.

### CODE REVIEW

**Comment by miri64** [comment]
If you optimize for size, maybe have a look if `BOARD_INSUFFICIENT_MEMORY` is still valid ;-)

**Comment by smlng** [comment]
@miri64 it wasn't in the first place: without this PR it wouldn't fit onto a _arduino-duemilanove_ thats why I started this 😉 From the specs it should work with the blacklisted _nucleos_ (`BOARD_INSUFFICIENT_MEMORY := nucleo32-f042 nucleo32-f031`) now, too. Unfortunately, as with many test cases: I do not have those boards at my disposal 😞

**Comment by smlng** [comment]
Besides: I think its better to have a README for tests, anyway - while the test apps in itself should be small without unnecessary bloat.

**Comment by miri64** [comment]
> Unfortunately, as with many test cases: I do not have those boards at my disposal :disappointed:

You don't need it: assuming the board provider configured the linker correctly, just running the linker (i.e. run `make all`) would suffice. If it does not fit it will error.

**Comment by miri64** [comment]
> Besides: I think its better to have a README for tests, anyway - while the test apps in itself should be small without unnecessary bloat.

I agree. Just want to keep the build tests up to date ;-)

**Comment by smlng** [comment]
@miri64 the nucleos still don't fit. At least not with the current board/cpu configuration, i.e., the problem is that even those small mem nucleos share common config from `cpu/cortrexm_common` where `#define THREAD_STACKSIZE_DEFAULT        (1024)` is set, which is way to large here. 

I created an issue see #6669.

**Comment by smlng** [comment]
ping!

**Pull request merged**
