### PR TITLE
Whitespace fixes

### PR DESCRIPTION
**Pull request by gebart**
This PR contains:
 - convert to Unix line endings (LF, `\n`)
 - remove trailing spaces in various files
 - remove extra blank lines at the bottom of files
 - replaces tabs by spaces in multiple files

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Looks good.. did you use some sort of script? In this case you might want to drop it into the repo as well..

**Comment by LudwigOrtmann** [comment]
I think @haukepetersen voiced the recommendation not to change vendor files like `cpu/stm32f3/include/stm32f334x8.h` in order to allow for easier integration of upstream updates.

**Comment by gebart** [comment]
@LudwigOrtmann I was part of that discussion too, but that was regarding changing defines and include guard names etc. to match the coding standard. This is simply a whitespace change to eliminate the existing `git diff --check` errors in the tree. `git diff -w` can be used to compare the headers without whitespace differences when we update them to a later vendor version.

**Comment by gebart** [comment]
There are still some errors caused by the patches under pkg, but I am working on a `.gitattributes` fix for that.
After that there will be no more whitespace errors left in the master tree.

**Comment by OlegHahm** [comment]
@gebart, thanks for the effort! Can you please state which script or command line arguments to which tool you have used for this patch? I think it makes more sense to review such a script than the change itself.

**Comment by gebart** [comment]
I only used `git diff --check 4b825dc642cb6eb9a060e54bf8d69288fbee4904` to list all the errors inside the repo and then opened one file at a time and resaved in my editor (Geany) with "strip trailing whitespace on save" enabled in the settings

4b825dc642cb6eb9a060e54bf8d69288fbee4904 is the hash of the empty commit at the root of all git trees.

**Comment by gebart** [comment]
I added a commit for selectively excluding the non-conforming patch files one by one inside `pkg`. Any future non-conforming files must be added explicitly.

**Comment by OlegHahm** [comment]
Well, I would say ACK. If Travis is green nothing should be seriously broken by this PR.

**Comment by gebart** [comment]
I found that there are still some files that have tabs for indentation, but I don't have the time to fix that right away. I'll post a follow up PR when I get the time to finish this.

Note: Tabs for indentation is not an error in `git diff --check` (and is mandatory for Makefile recipes)

Is there a check script in the dist directory for checking tabs for indentation in (non-Makefile) source files?

**Comment by OlegHahm** [comment]
> Is there a check script in the dist directory for checking tabs for indentation in (non-Makefile) source files?

I don't think so.

**Pull request merged**
