### PR TITLE
drivers/periph/spi: clean up error codes and doc

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- Use negative errno as error codes, rather than home-grown enums
    - Update the home-grown enum with negative errno codes for backward compatibility and mark it deprecated
    - This brings the API back to current coding practices in RIOT, e.g. as documented in the driver guide
- Update API doc to use negative errno codes
- Fix various style issues in Doxygen doc
    - Use `@retval` to document specific return values instead of abusing `@return` for this
    - Align parameters to proper indent level

#### Note on API Change

As this change is fully backward compatible, there should not be any issues. But marking previous behavior (using e.g. `SPI_OK`) as deprecated IMO qualifies this as an API change.

### Testing procedure

- Generated binaries should be *almost* identical. (Using different constants in return values will change binaries, obviously)
- All SPI tests should still work

### Issues/PRs references

None

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
Nobody should depend on the exact numeric values of the enum anyway, as long as 0 stays success and errors remain negative.

**Comment by maribu** [comment]
The [only failed test](https://ci.riot-os.org/RIOT-OS/RIOT/15896/ae79f5fc596ed9d6b8d7f1ee125a71b28a74dfa3/output/compile/tests/pkg_c25519/esp32-ethernet-kit-v1_1:gnu.txt) is an CI hiccup and completely unrelated to this PR, so I trigger a re-run without compilation.

**Review by jeandudey — APPROVED** [review]
LGTM, [Documentation](https://7296-7370241-gh.circle-artifacts.com/0/doc/group__drivers__periph__spi.html) matches the changes. It's very unlikely that someone's else code is depending on magic numbers rather than the provided enum values.

**Comment by miri64** [comment]
FYI `tests/congure_test` is failing since a docker container is outdated. This should be fixed soon (alternatively try restarting the build until you don't hit that one for native tests...).

**Comment by jeandudey** [comment]
Officially I've pressed the green button :P 🎉

**Comment by maribu** [comment]
Hooray!

**Pull request merged**
