### PR TITLE
Add support for Raspberry Pi RP2040 MCU and the Pico board

### PR DESCRIPTION
**Pull request by iia**
### Contribution description

Initial support for Raspberry Pi Pico and RP2040 MCU. The board is configured to operate using the on-board XTAL at 12MHz.

Currently using the picotool to flash the board (by pressing the BOOTSEL button).

Implemented drivers:

- UART.
- GPIO (no GPIO IRQs yet).
- Timer.

### Testing procedure

Tested by compiling and flashing:
- test/periph_stdin
- test/periph_gpio
- test/periph_timer

### Issues/PRs references

I just saw another PR #16609 was submitted just an hour before I was about to submit this one. Don't know what to do about it.

### CODE REVIEW

**Comment by benpicco** [comment]
Now this is a single commit adding 165118 lines and touching 478 files, it's very hard to review that.
Generally adding a new CPU should be split into 

 - adding vendor files
 - adding core CPU support
 - one commit for each driver
 - a commit adding board support

The duplicate effort is unfortunate, but then again this makes you the ideal person to take a look at #16609 and chip in what you learned from the process of porting RIOT to the rp2040.
Seeing that the other PR still lacks a timer driver, you might be a able to contribute yours :wink: 

And there are still plenty of other peripheral drivers that need to be implemented.

**Comment by iia** [comment]
@benpicco Thanks for the comment.

There are too many new files because for adding the vendor files I added the complete Pico SDK. I guess that was not a very good idea.

For future, it would be preferable in such cases to only add what is required from the vendor SDK?

Cheers.

**Comment by kaspar030** [comment]
Hm, these clashes are most unfortunate. :(
This PR seems to have a timer driver!

**Comment by iia** [comment]
So what do you guys suggest? The only feasible option is to wait until the other PR is upstreamed and then contribute, for example the timer driver?

**Comment by benpicco** [comment]
The USB peripheral would be anther big and important feature, I'm not sure if anyone is working on that yet.
Not sure what's the status of SPI and I2C, those are comparably low hanging fruits but I could imagine someone is already working on that.

**Comment by maribu** [comment]
Maybe it is best to use https://github.com/RIOT-OS/RIOT/issues/15822 to sync efforts? @fabian18 is also working on peripheral drivers, but will be busy writing exams in the next weeks.

**Comment by benpicco** [comment]
superseded by #16609 and #16627, sorry for the duplicate effort.

**Pull request closed without merging**
