### PR TITLE
gnrc_netif: assume `netif->ops->init()` to be set to at least a default

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
See https://github.com/RIOT-OS/RIOT/pull/10371#pullrequestreview-174909604

### Testing procedure
This should be tested very well and if the following is still compiling and working:
- [x] GNRC over CC110x (e.g. with `gnrc_networking` on `msba2`)
- [x] GNRC over Ethernet (e.g. with `gnrc_networking` on `native`)
- [x] GNRC over IEEE 802.15.4 (e.g. `gnrc_networking` on `iotlab-m3`)
- [x] GNRC over Xbee (e.g. `gnrc_networking` on `arduino-zero` with `xbee`)
- [x] GNRC over `nordic_softdevice_ble` (e.g. `gnrc_networking` on `nrf52dk` with `nordic_softdevice_ble`)
- [ ] GNRC over `nimble` (e.g. `gnrc_networking` on `nrf52dk` with `nimble` [default])
- [x] GNRC over RAW (e.g. `gnrc_border_router` with `slipdev` instead of `ethos`) (tested on `b-l072z-lrwan1` with `sx127x`)
- [x] `examples/gnrc_networking_mac` with GoMacH
- [x] `examples/gnrc_networking_mac` with LWMAC
- [x] `tests/gnrc_ndp`
- [x] `tests/gnrc_netif`

### Issues/PRs references
Based on a question raised in https://github.com/RIOT-OS/RIOT/pull/10371

### CODE REVIEW

**Comment by cgundogan** [comment]
rebased locally and tested successfully with `native` and `iotlab-m3` so far. Can continue on other platforms tomorrow.

**Comment by miri64** [comment]
Rebased to current master

**Comment by miri64** [comment]
Ping? Except for the testing effort this should be a pretty low-hanging fruit

**Comment by jia200x** [comment]
codewise looks fine. I'm currently testing in `arduino_zero`

**Comment by jia200x** [comment]
(I'm still waiting IoT-LAB booking 2 `arduino_zero`. This might take a while...)

**Comment by miri64** [comment]
Ping @jia200x?

**Comment by jia200x** [comment]
I'm back

**Comment by jia200x** [comment]
this PR fails when running `gnrc_networking` on `arduino-zero` (failed assertion at gnrc_rpl_auto_init.c:32)

**Comment by jia200x** [comment]
(also maybe a rebase at this point woudn't be bad :) )

**Comment by miri64** [comment]
> this PR fails when running `gnrc_networking` on `arduino-zero` (failed assertion at gnrc_rpl_auto_init.c:32)

Is it only in this PR or in master as well? IIRC this is "normal" behavior in master, as the arduino-zero has no network interface and RPL expects one. I think there was an issue for that, at least I remember discussing it with @cgundogan at some point, I can't find it however.

**Comment by miri64** [comment]
Rebased and adapted (see 2075e53b2ed9311a2a49926945c43bdacd4db0f0) for current master.

**Comment by miri64** [comment]
> this PR fails when running `gnrc_networking` on `arduino-zero` (failed assertion at gnrc_rpl_auto_init.c:32)

Note that the testing description says "arduino-zero _with_ Xbee" ;-)

**Comment by jia200x** [comment]
`tests/gnrc_netif` is not passing on samr21-xpro:
```
2019-09-27 15:45:54,390 - INFO # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2019-09-27 15:45:57,463 - INFO # .0x76af
Timeout in expect script at "child.expect(r"OK \(\d+ tests\)")" (tests/gnrc_netif/tests/01-run.py:16)
  File "/home/jialamos/Development/RIOT/dist/pythonlibs/testrunner/__init__.py", line 29, in run
    testfunc(child)
  File "/home/jialamos/Development/RIOT/tests/gnrc_netif/tests/01-run.py", line 16, in testfunc
    child.expect(r"OK \(\d+ tests\)")
  File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
```

I tried the commit before 76248aea3b5269866c20a72c0d6629324ed129bb and works OK.

**Comment by jia200x** [comment]
@miri64 any idea?

**Comment by miri64** [comment]
Will have a look.

**Comment by miri64** [comment]
> `tests/gnrc_netif` is not passing on samr21-xpro:
> 
> ```
> 2019-09-27 15:45:54,390 - INFO # Connect to serial port /dev/ttyACM0
> Welcome to pyterm!
> Type '/exit' to exit.
> 2019-09-27 15:45:57,463 - INFO # .0x76af
> Timeout in expect script at "child.expect(r"OK \(\d+ tests\)")" (tests/gnrc_netif/tests/01-run.py:16)
>   File "/home/jialamos/Development/RIOT/dist/pythonlibs/testrunner/__init__.py", line 29, in run
>     testfunc(child)
>   File "/home/jialamos/Development/RIOT/tests/gnrc_netif/tests/01-run.py", line 16, in testfunc
>     child.expect(r"OK \(\d+ tests\)")
>   File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
>     timeout, searchwindowsize, async_)
>   File "/usr/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
>     return exp.expect_loop(timeout)
>   File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 119, in expect_loop
>     return self.timeout(e)
>   File "/usr/lib/python3.7/site-packages/pexpect/expect.py", line 82, in timeout
>     raise TIMEOUT(msg)
> ```
> 
> I tried the commit before [76248ae](https://github.com/RIOT-OS/RIOT/commit/76248aea3b5269866c20a72c0d6629324ed129bb) and works OK.

Mh okay, somehow the wrong device type is returned. Will investigate.

**Comment by jia200x** [comment]
now the test doesn't compile for `samr21-xpro` :/

```
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c: In function 'gnrc_netif_default_init':
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c:1153:5: error: implicit declaration of function '_test_options' [-Werror=implicit-function-declaration]
     _test_options(netif);
     ^~~~~~~~~~~~~
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c: At top level:
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c:1181:13: error: conflicting types for '_test_options' [-Werror]
 static void _test_options(gnrc_netif_t *netif)
             ^~~~~~~~~~~~~
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c:1181:13: error: static declaration of '_test_options' follows non-static declaration
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c:1153:5: note: previous implicit declaration of '_test_options' was here
     _test_options(netif);
     ^~~~~~~~~~~~~
/home/jialamos/Development/RIOT/sys/net/gnrc/netif/gnrc_netif.c:1181:13: error: '_test_options' defined but not used [-Werror=unused-function]
 static void _test_options(gnrc_netif_t *netif)
             ^~~~~~~~~~~~~
```

**Comment by miri64** [comment]
Won't go into the release anyways, but will fix so it is good to go after FF.

**Comment by miri64** [comment]
Ping @jia200x?

**Comment by jia200x** [comment]
I will run the tests again

**Comment by jia200x** [comment]
`xbee` doesn't seem to work, but I'm having the same issue in master

**Comment by miri64** [comment]
Then rather concentrate on the other tests ;-).

**Comment by jia200x** [comment]
> Then rather concentrate on the other tests ;-).

Already on it...

**Comment by jia200x** [comment]
Tested all boards. In some of them I couldn't test the connectivity (softdevice_ble, cc110x), but I least I ensured that it didn't call a NULL _init or that the corresponding _init function was being called.

So, it would say let's proceed with this one.

**Comment by jia200x** [comment]
can you rebase?

**Comment by miri64** [comment]
> can you rebase?

Not really sure why, but sure. May I squash as well?

**Comment by miri64** [comment]
Rebased:

```
$ git range-diff master d758ed10 5051e00c
1:  76248aea3b = 1:  4b82a56c89 gnrc_netif: introduce common init function
2:  e7c141c2e0 = 2:  09b5db28f1 gnrc_netif: expose common init function as default
3:  1fe2587743 = 3:  4aa7dd3893 gnrc: use gnrc_netif_default_init() for all implementations
4:  bc5a5498f7 = 4:  336d936f5f gnrc_netif: assume `netif->ops->init()` to be set
5:  2075e53b2e = 5:  952ab4ccf4 fixup! gnrc: use gnrc_netif_default_init() for all implementations
6:  f5ece38dbe = 6:  351fa92aa0 fixup! gnrc_netif: assume `netif->ops->init()` to be set
7:  032a46b00d = 7:  4f3b3e5f82 fixup! fixup! gnrc_netif: assume `netif->ops->init()` to be set
8:  d758ed10cc = 8:  5051e00c2b fixup! fixup! fixup! gnrc_netif: assume `netif->ops->init()` to be set
```

**Comment by miri64** [comment]
Did you test with `nimble`? Murdock is complaining about it :sweat_smile:

**Comment by jia200x** [comment]
> Not really sure why, but sure. May I squash as well?

Yes, I meant that :sweat_smile:.

**Comment by jia200x** [comment]
> Did you test with nimble? Murdock is complaining about it sweat_smile

Nope, I didn't test that one. It was not in the list and I didn't know I should include it

**Comment by jia200x** [comment]
(Ok, I see it was in the files. I reviewed it some time ago and only tested what was on the list. My mistake)

**Comment by miri64** [comment]
> > Did you test with nimble? Murdock is complaining about it sweat_smile
> 
> Nope, I didn't test that one. It was not in the list and I didn't know I should include it

The list is older than GNRC's nimble support. I'll update it :-)

**Comment by miri64** [comment]
Squashed and updated `gnrc_netif_ops_t::init()` (it was a bit confusing in my opinion and also half-way in the old behavior still).

**Pull request merged**
