### PR TITLE
ztimer: pull ztimer_periph_rtt for ZTIMER_MSEC if available

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

With #16546 `ztimer_periph_rtt` can always be included since all rtt are capable of supplying a msec timer, so this PR includes it by default.

I'm not sure how the Kconfig dependency should be adapted, I gave it a go but maybe @leandrolanzieri could take a second look.

### Testing procedure

Included modules should be the same for the affected pkgs, `rtt` is included when possible otherwise `ztimer_msec` fallbacks to `periph_timer`,

### Issues/PRs references

Takeover of #16334

### CODE REVIEW

**Comment by fjmolinas** [comment]
Applied offline suggestion from @leandrolanzieri, each CLOCK can configure a different backend.

image

**Comment by kaspar030** [comment]
LGTM, can't say much about the Kconfig part, though. @jia200x @leandrolanzieri mind to take a look? (Murdock shows some errors).

**Comment by leandrolanzieri** [comment]
One difference that I see, is that with the change introduced in Kconfig, where each clock allows to select a backend, now the RTC backend is included, which did not happen before. This causes in native to also bring xtimer, as RTC in native is done with xtimer :/  Perhaps add it as an exception?

**Comment by fjmolinas** [comment]
> LGTM, can't say much about the Kconfig part, though. @jia200x @leandrolanzieri mind to take a look? (Murdock shows some errors).

Indeed for some reason xtiemr got pulled in... looking into it

**Comment by fjmolinas** [comment]
Murdock is happy this time, @leandrolanzieri do you think everything is OK?

**Comment by leandrolanzieri** [comment]
> Murdock is happy this time, @leandrolanzieri do you think everything is OK?

The Kconfig looks good to me!

**Comment by fjmolinas** [comment]
@kaspar030 @leandrolanzieri may I squash?

**Comment by leandrolanzieri** [comment]
Go ahead!

**Review by kaspar030 — APPROVED** [review]
ACK.

**Pull request merged**
