### PR TITLE
gnrc_sock_ip: fix NULL pointer dereference

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
See https://github.com/RIOT-OS/RIOT/pull/5772#discussion_r483986833

### Testing procedure
Run `tests/gnrc_sock_ip`. Without the fix in b187917 the test will crash with a segfault. With the fix it will pass.

### Issues/PRs references
https://github.com/RIOT-OS/RIOT/pull/5772#pullrequestreview-483093328

### CODE REVIEW

**Comment by benpicco** [comment]
Looks like `01-run.py` needs an update.

**Review by keestux — APPROVED** [review]
Looks good to me

**Comment by aabadie** [comment]
@miri64 it seems that Murdock spotted an issue: https://ci.riot-os.org/RIOT-OS/RIOT/14963/b1879172ec693f89e33990bcf0dcdd5776bfad47/output/compile/tests/gnrc_sock_ip/native:llvm.txt

**Comment by miri64** [comment]
Addressed and squashed

**Pull request merged**
