### PR TITLE
cpu/atmega_common: remove linkerscript duplication

### PR DESCRIPTION
**Pull request by benpicco**
`ldscripts_compat/avr_2.26.ld` is duplicated for every Atmega CPU.
Move it into `atmega_common`.

### CODE REVIEW

**Comment by kYc0o** [comment]
Would you provide a testing procedure? I'd say it looks good but I don't know what are the consequences beyond compilation failure/success.

@cladmi it was you who contributed these isn't it?

**Comment by benpicco** [comment]
It should just behave as before - the common code was copied verbatim among all Atmega CPUs.
Actually I just deleted the common code in one Implementation and applied the resulting patch on each other sibling CPU.

Interestingly enough, those linkerscripts are [only used](https://github.com/RIOT-OS/RIOT/blob/master/makefiles/arch/atmega.inc.mk#L41) if the internal linkerscript (outputted by `avr-ld --verbose`) does not contain `__TEXT_REGION_LENGTH__`.

This seems to be the case at least on the one shipped by Ubuntu (avr-ld 2.26.20160125), so to test it I had to delete that conditional.

**Comment by cladmi** [comment]
The reason for the duplication in that case, was that it was the output of the toolchain without modification (except removing the first comments I think). Putting things in common means that we start keeping track of what is inside.

```
Generated by extracting the output of

    avr-gcc -Wl,--verbose --mmcu=$(CPU)

With avr-binutils 2.26
```

https://github.com/RIOT-OS/RIOT/commit/56a1ac4f2b158cb6859d09a9e73754d76699e5cf

**Comment by cladmi** [comment]
And yes, the goal was to evaluate the rom length during link time when the toolchain was not doing it in the previous reference buuntu toolchain version.

**Comment by smlng** [comment]
I agree with @cladmi, however we should add an explanatory text to the readme, stating the command used to generated them - why they are needed is already in the README.

**Comment by cladmi** [comment]
I added the documentation here https://github.com/RIOT-OS/RIOT/pull/11615

**Pull request closed without merging**
