### PR TITLE
drivers/at86rf2xx: clear channels for rf23x series too

### PR DESCRIPTION
**Pull request by OlegHahm**
Alternative to #4482.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Seems to work on iotlab-M3.

**Comment by DipSwitch** [comment]
I will try to test it on the AT86RF212 tomorrow but I don't see why it
would break it :)

**Comment by smlng** [comment]
Hi, I am testing on the samr21-xpro - while send and receive with current 2015.12-branch is _not_ working, this PR fixes the issue. So it should definitely be merge asap :)

**Comment by DipSwitch** [comment]
Sorry no time to test... But I can merge anyways? Who does the back-porting?

**Comment by OlegHahm** [comment]
Can you confirm that the test looks sound to you?

**Comment by DipSwitch** [comment]
Yes it would make allot of sense that the channel needs to be cleared
before setting it for all devices.

I would however expect that the AT86RF23x works if riot uses the same
channel as the default of the phy. Also in #4481 you can see that the lines
are placed back in func: set_chan

+ tmp = at86rf2xx_reg_read(dev, AT86RF2XX_REG__PHY_CC_CCA);
+ tmp &= ~(AT86RF2XX_PHY_CC_CCA_MASK__CHANNEL);
+ tmp |= (channel & AT86RF2XX_PHY_CC_CCA_MASK__CHANNEL);
+ at86rf2xx_reg_write(dev, AT86RF2XX_REG__PHY_CC_CCA, tmp);

In current master that seems to be the only thing not done for the 23x
series.

**Comment by DipSwitch** [comment]
Although for cleaner code i would maybe insert lines 163 - 165 to line 202
since the procedure is then isolated :)

**Comment by OlegHahm** [comment]
see #4501

**Pull request closed without merging**
