### PR TITLE
rpl: initial import of an attacker

### PR DESCRIPTION
**Pull request by BytesGalore**
Rationale:
This RP introduces the possibility to attack RPL.
Right now it is possible to perform a rank-attack pretending to have a deliberately low rank.
Doing so will attract neighbour nodes to choose the Attacker as prefered parent, causing a partition of the topology.
This attack can easily affect a very large number of nodes.

Attacking can be triggered using shell commands.
**edit:** use the `gnrc_networking` example, and
just type `rpl atk help` in the shell to see how to perform basic attacks.

**This RP is not meant to be merged to RPL and will remain WIP, but I think its probably useful for testing.**

And now have fun :).

**edit:** ~~(A version number attack is on the way)~~ added.

### CODE REVIEW

**Comment by BytesGalore** [comment]
added DODAG version number attack, which allows an attacker to rise the DODAG version number. 
The new DODAG version be will eventually distributed in DIOs by the Attacker affecting **all nodes** in the DODAG.

**Comment by cgundogan** [comment]
this sounds interesting. I would actually like it if you could move most of the code into a subfolder of RPL and then declare it as a module. This way your changes will be in different files and therefore we will have less merge conflicts (: You could do it in the same fashion I did for P2P-RPL

**Comment by BytesGalore** [comment]
@cgundogan sounds like a good idea, I will try to out-source the source :)

**Comment by kYc0o** [comment]
Feature freeze -> postponed.

**Comment by miri64** [comment]
Postponed due to Feature Freeze.

**Comment by OlegHahm** [comment]
@BytesGalore, what's up with this PR?

**Comment by BytesGalore** [comment]
@OlegHahm I close this one, since I'm the only one using the features.
I will maintain this branch in my fork.

**Pull request closed without merging**
