### PR TITLE
Use TARGET_ARCH for more platforms

### PR DESCRIPTION
**Pull request by gebart**
- Moved PREFIX setting to Makefile.include
 - Set TARGET_ARCH for avr and arm7 targets

### CODE REVIEW

**Comment by OlegHahm** [comment]
Looks good, but needs a rebase.

**Comment by OlegHahm** [comment]
I don't understand why Murdock fails for MSP430 here.

**Comment by gebart** [comment]
Fixed the msp430 problem.

**Comment by gebart** [comment]
@OlegHahm care to ACK?

**Comment by OlegHahm** [comment]
Ack and go!

**Pull request merged**
