### PR TITLE
cpu/atmega32u4: Fixed external interrupts; boards/arduino-leonardo: Fixed dependency tracking

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

- Removes incorrect entry for external interrupt on non-existing pin PE7 for MCU ATmega32U4
- Adds missing Makefile.dep to Arduino Leonardo board

### Testing procedure

- Everything should still build
- The non-existing pin PE7 should no longer be configured as interrupt in the test added in https://github.com/RIOT-OS/RIOT/pull/11923
- `make BOARD=arduino-leonardo info-modules` e.g. in `examples/hello_world` should now list `boards_common_arduino-atmega`

### Issues/PRs references

Found bug while testing https://github.com/RIOT-OS/RIOT/pull/11923

### CODE REVIEW

**Comment by maribu** [comment]
@miri64: Mind to review? (I know, not your field of interest. But you have a board and this PR is quite small ;-))

**Comment by miri64** [comment]
I'll have look next week. My leonardo is at the office. If I don't come back to this on Monday, please feel free to remind me ;-).

**Comment by miri64** [comment]
> I'll have a look next week. My leonardo is at the office. If I don't come back to this on Monday, please feel free to remind me ;-).

Sorry, had no internet today in the office. In the meantime: a more descriptive PR title would be appreciated ;-)

**Comment by maribu** [comment]
> however after that I was not able to flash anymore (/dev/ttyACM0 disappearing during flashing)…

Can you provide more details? Upon boot the bootloader of the Leonardo provides `/dev/ttyACM0` for a bounded time (2 seconds if I remember correctly). Afterwards, the flashed firmware is loaded. In case of RIOT the USB devices than vanishes, as RIOT does not have support for USB on the ATmega32U4 yet. So if the re-build of the firmware during `make flash` takes too long, the time window the bootloader provides `/dev/ttyACM0` might be too short for the build system to reach the point `avrdude` is started.

So the most reliable way to flash is using the following steps:

1. Run `make BOARD=arduino-leonardo`
2. Type `make BOARD=arduino-lenoardo flash-only` without hitting the enter key yet
3. Press the reset button on the board
4. Press the enter key to issue the flash only command

> I'm not sure if it was this PR that effectively bricked it :-/

That is very unlikely. Only the bootloader in the AVR should be able to write to the flash, so unless some advanced hack to work around this protection is used, RIOT (or any other firmware flashed via the bootloader) will not be able to brick the device.

I heard that some people still had to rewrite the bootloader of an Arduino. The only plausible explanation to me is that a hard to trigger bug in the bootloader can cause it to overwrite/modify portions of itself.

**Comment by maribu** [comment]
@miri64: Time to give this another try?

If the Leonardo's bootloader was indeed somehow bricked, you can just flash it using an ISP or [a second Arduino as ISP](https://www.arduino.cc/en/Tutorial/ArduinoISP). But again: Bricking the bootloader is theoretically impossible from RIOT, only the bootloader itself has write access to the flash. But I cannot rule out that some bug in the bootloader was triggered somehow :-/

**Comment by miri64** [comment]
Thanks, I'll try that!

**Comment by miri64** [comment]
Ok, after burning the bootloader via an Arduino Uno as ISP, /dev/ttyACM0 does not disappear anymore after a few seconds (which was my problem) I will now test your PR :-)

**Comment by maribu** [comment]
Thanks for review!

**Pull request merged**
