### PR TITLE
boards/stm32f723e-disco: add initial support

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds a very basic support for the [stm32f723e-disco](https://www.st.com/en/evaluation-tools/32f723ediscovery.html) board.
This board provides an nice LCD TFT screen, an Arduino pinout and an STMod+ connector. The STMod+ connector provide an easy way to extend the board with Xbee or other mikrobus compilant devices.
There's also an ESP-01 connector that allows to plug an esp8266 on it and configure wifi using AT commands on the ESP8266.

Only uart, timer, rtc and rtt features are configured at board level for the moment but I plan to extend the pinout support.

There's an issue with uart when using application without stdin: no output can be printed on stdio. The workaround is to use stdin by default with this board. I haven't looked at it further yet.

### Testing procedure

Run `compile_and_test_for_board.py` for this board.

### Issues/PRs references

None

### CODE REVIEW

**Comment by fjmolinas** [comment]
Testing results, a lot of failures:

```
Failures during test:
- [tests/bloom_bytes](tests/bloom_bytes/test.failed) [hardfaults]
- [tests/float](tests/float/test.failed) [hardfaults]
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed) [sudo]
- [tests/gnrc_rpl_srh](tests/gnrc_rpl_srh/test.failed) [sudo]
- [tests/gnrc_sock_dns](tests/gnrc_sock_dns/test.failed) [sudo]
- [tests/libfixmath_unittests](tests/libfixmath_unittests/test.failed) [hardfaults]
- [tests/pkg_cn-cbor](tests/pkg_cn-cbor/test.failed)  [hardfaults]
- [tests/pkg_lora-serialization](tests/pkg_lora-serialization/test.failed)  [hardfaults]
- [tests/pkg_ubasic](tests/pkg_ubasic/test.failed)  [hardfaults]
- [tests/rng](tests/rng/test.failed) [hardfaults]
- [tests/unittests](tests/unittests/test.failed) [hardfaults]
```

**Comment by aabadie** [comment]
For the moment, I have no idea why these tests are failing. I noticed they are also failing on nucleo-f746zg but not on nucleo-f767zi.

**Comment by aabadie** [comment]
> It is missing documentation though.

Indeed....

**Comment by aabadie** [comment]
Documentation added @fjmolinas :)

**Comment by fjmolinas** [comment]
> For the moment, I have no idea why these tests are failing. I noticed they are also failing on nucleo-f746zg but not on nucleo-f767zi.

Failing tests seem to be for all `stm32f7`, if you open an issue we can merge this, since it is unrelated.

**Comment by aabadie** [comment]
> if you open an issue we can merge this

See  #12286

**Pull request merged**
