### PR TITLE
2015.09 branch

### PR DESCRIPTION
**Pull request by KamalDSOberoi**
In file core/kernel_init.c in thread idle_thread, there is no need for any condition. It should be that whenever this thread runs, it goes into idle state, without checking any condition. And if an interrupt comes, it wakes up.

### CODE REVIEW

**Comment by OlegHahm** [comment]
This looks like a mishap. Okay to close?

**Comment by cgundogan** [comment]
the description suggests it to be linked with #4019 @KamalDSOberoi what was your intention?

**Comment by authmillenon** [comment]
Closing, since there was no response by @KamalDSOberoi and release is out for a month (I assume this was opened by accident).

**Comment by authmillenon** [comment]
Maintainers: Do NOT hit the "Delete branch" button. It will remove the release branch from the repository.

**Pull request closed without merging**
