### PR TITLE
jenkinsfile: optimizations

### PR DESCRIPTION
**Pull request by smlng**
testing some optimizations on the Jenkins build configuration

### CODE REVIEW

**Comment by smlng** [comment]
@cgundogan some enhancements, they bring about 30% speedup. Brings  build time from currently 11min down to 7min.

**Comment by kaspar030** [comment]
> Brings build time from currently 11min down to 7min.

Nice! On how many cores?

**Comment by smlng** [comment]
@kaspar030: should be 80-90 Cores including HT. But, this includes 16 VMs (at INRIA) with 2 Cores each, which often lack behind the more powerful workers. I think it's better to have a big iron with lots of cores compared to many small workers - at least if plain speed (build time per single PR) is the metric to look at.

**Comment by smlng** [comment]
closing as memo, for jenkins is shutdown in favor of Murdock 2

**Pull request closed without merging**
