### PR TITLE
pkg: port nordic_softdevice_ble to gnrc_netif2

### PR DESCRIPTION
**Pull request by miri64**
Couldn't test this due to the soft device not being build properly (?)

~~Depends on #7370.~~

This PR is part of the network layer remodelling effort:
PR dependencies

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master and current dependencies

**Comment by miri64** [comment]
Rebased to current master, no longer waiting for other PR

**Comment by miri64** [comment]
@kaspar030 made some comments about my usage of LOG_ERROR() in #7410. I will remove them here and in the other PRs.

**Comment by miri64** [comment]
I changed the base branch now to the freshly created gnrc_netif2_integration/master branch.

**Comment by kaspar030** [comment]
Doesn't link, cannot test.

**Comment by miri64** [comment]
Which application did you try?

**Comment by kaspar030** [comment]
```examples/default```

**Comment by miri64** [comment]
Rebased. Should work now.

**Comment by miri64** [comment]
Another day a another rebase.

**Pull request merged**
