### PR TITLE
Bug: code to reproduce xtimer hang with concurrent xtimer_usleep() 

### PR DESCRIPTION
**Pull request by daniel-k**
This is a bugreport. I wanted to add code to reproduce, therefore a PR.

This test should reproduce a hangup for concurrent threads that use `xtimer_usleep()`. I'm experiencing this in my project and finally can reproduce it. I'm not really sure why it happens, but my investigations indicate that xtimer calls `_lltimer_set()` with a target in the past, so every xtimer_sleep hangs.

Maybe I only misused xtimer somehow or this can be fixed by those xtimer tuning variables. Just wanted to escalate this now, as I've already spent too much time on this without really having a clue :)

I based this on #4058 so that you can easily verify that it's the `xtimer_usleep()` calls that hang and facilitate debugging. For further instructions see #4058.

This behaviour is observed on `samr21-xpro`, last lines before hang on terminal:
```
[...]
2015-10-07 15:49:08,366 - INFO # -
2015-10-07 15:49:08,366 - INFO # +
2015-10-07 15:49:08,366 - INFO # -
2015-10-07 15:49:08,367 - INFO # +
2015-10-07 15:49:08,367 - INFO # -
2015-10-07 15:49:08,367 - INFO # +
2015-10-07 15:49:08,367 - INFO # -
2015-10-07 15:49:08,367 - INFO # Pong 3
```

Active threads:
```
(gdb) info threads
  Id   Target Id         Frame 
  4    Thread 4 (timer2 :  : Blocked mutex) mutex_lock (mutex=mutex@entry=0x200010d4 <stack_timer2+908>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
  3    Thread 3 (timer1 :  : Blocked mutex) mutex_lock (mutex=mutex@entry=0x20000cd4 <stack_timer1+908>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
  2    Thread 2 (main :  : Blocked mutex) mutex_lock (mutex=mutex@entry=0x2000081c <main_stack+1400>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
* 1    Thread 1 (idle :  : Running) idle_thread (arg=<optimized out>) at /home/daniel/Entwicklung/RIOT/core/kernel_init.c:73
```

Thread 2 (main)
```
(gdb) bt
#0  mutex_lock (mutex=mutex@entry=0x2000081c <main_stack+1400>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
#1  0x00000ec2 in _xtimer_sleep (offset=offset@entry=100000, long_offset=long_offset@entry=0) at /home/daniel/Entwicklung/RIOT/sys/xtimer/xtimer.c:52
#2  0x00000dc0 in xtimer_usleep (offset=100000) at /home/daniel/Entwicklung/RIOT/sys/include/xtimer.h:487
#3  main () at /home/daniel/Entwicklung/RIOT/tests/xtimer_hang/main.c:61
```

Thread 3 (timer1)
```
(gdb) bt
#0  mutex_lock (mutex=mutex@entry=0x20000cd4 <stack_timer1+908>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
#1  0x00000ec2 in _xtimer_sleep (offset=offset@entry=1000, long_offset=long_offset@entry=0) at /home/daniel/Entwicklung/RIOT/sys/xtimer/xtimer.c:52
#2  0x00000d4c in xtimer_usleep (offset=1000) at /home/daniel/Entwicklung/RIOT/sys/include/xtimer.h:487
#3  timer_func1 (arg=<optimized out>) at /home/daniel/Entwicklung/RIOT/tests/xtimer_hang/main.c:19
#4  0x0000022c in sched_switch (other_prio=<optimized out>) at /home/daniel/Entwicklung/RIOT/core/sched.c:189
```

Thread 4 (timer2)
```
(gdb) bt
#0  mutex_lock (mutex=mutex@entry=0x200010d4 <stack_timer2+908>) at /home/daniel/Entwicklung/RIOT/core/mutex.c:53
#1  0x00000ec2 in _xtimer_sleep (offset=offset@entry=1100, long_offset=long_offset@entry=0) at /home/daniel/Entwicklung/RIOT/sys/xtimer/xtimer.c:52
#2  0x00000d2e in xtimer_usleep (offset=1100) at /home/daniel/Entwicklung/RIOT/sys/include/xtimer.h:487
#3  timer_func2 (arg=<optimized out>) at /home/daniel/Entwicklung/RIOT/tests/xtimer_hang/main.c:28
#4  0x0000022c in sched_switch (other_prio=<optimized out>) at /home/daniel/Entwicklung/RIOT/core/sched.c:189
```

### CODE REVIEW

**Comment by gebart** [comment]
I ran into a similar problem when I was working on #3990. See if your XTIMER_BACKOFF is less than your XTIMER_OVERHEAD settings. That will cause _lltimer_set to set a timer in the past in some circumstances.

**Comment by daniel-k** [comment]
> See if your XTIMER_BACKOFF is less than your XTIMER_OVERHEAD settings. That will cause _lltimer_set to set a timer in the past in some circumstances.

That's not the case, for it's:
```
XTIMER_BACKOFF = 30
XTIMER_OVERHEAD = 20
```

**Comment by daniel-k** [comment]
It seems that
```c
#define XTIMER_ISR_BACKOFF 40
```

fixes this bug. At least it already runs since >5min without hang up. 

I guess the behaviour was caused by:
```c
if (timer_list_head) {
    /* schedule callback on next timer target time */
    next_target = timer_list_head->target - XTIMER_OVERHEAD;
} else { [...] }

/* set low level timer */
_lltimer_set(next_target);
````

So when all timer callback were served the last target was far enough in the future for `XTIMER_ISR_OVERHEAD`, but the time it took to set the low level timer was too long, so that `next_target` was already in the past when set.

**Comment by daniel-k** [comment]
I wonder what happens if a higher-priority IRQ fires just before `_lltimer_set()` is called. Did you think this through?

**Comment by kaspar030** [comment]
Well, we don't allow nested interrupts, so, no.

**Comment by kaspar030** [comment]
@daniel-k Could you give #4061 a try?

**Comment by daniel-k** [comment]
@kaspar030 Sure, just a sec :)

**Comment by daniel-k** [comment]
@kaspar030 
It doesn't hang anymore, but the output now looks like this and I'm not sure if this is supposed to happen:

```
2015-10-07 19:08:08,053 - INFO # +
2015-10-07 19:08:08,053 - INFO # -
2015-10-07 19:08:08,054 - INFO # Pi+
2015-10-07 19:08:08,054 - INFO # n-
2015-10-07 19:08:08,055 - INFO # g 1892
2015-10-07 19:08:08,055 - INFO # +
2015-10-07 19:08:08,055 - INFO # -
```

**Comment by daniel-k** [comment]
Nevermind the above. That's what thread priorities are for! :) Thank you for the fix!

**Comment by kaspar030** [comment]
np, I love bugs with reproducing code, thanks for taking the time!

So can I close this?

**Comment by daniel-k** [comment]
> So can I close this?

Yes, I'll close.

Concerning disabled nested interrupts I still got a question, but let's not discuss this here. IRC maybe?

**Pull request closed without merging**
