### PR TITLE
dist: Add pythonlib pkg to make system

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description

This PR downloads the if_lib from the RIOT-OS repo to treat is as a modular package.  This should eventually remove the current if_lib in RIOT (again to promote modularity).

### Testing procedure

`make get_pylibs -C examples/hello-world/`

### Issues/PRs references

For integration with https://github.com/smlng/RIOT/tree/robotframework

### CODE REVIEW

**Comment by kaspar030** [comment]
How about making if_lib a pip package?

**Comment by MrKevinWeiss** [comment]
That could simplify things, I'll look into it.

**Comment by smlng** [comment]
Making this a python package sounds great. Also: wouldn't it make sense to have a riot-pip-package list  of dependencies, e.g. `pyserial` is also (kind of) mandatory for RIOT, and this list is installed through the build system?

**Comment by gebart** [comment]
@smlng do you mean like a meta package similar to e.g. build-essentials on Ubuntu?

I would not want the build system to touch the system packages, but what would be useful would be to have the build system set up a virtualenv for the repo where all deps can be installed without affecting the system.

**Comment by MrKevinWeiss** [comment]
So if we do move this to a pip file we should improve the name.

I think @smlng suggested riot_unilib, short and unique.

**Comment by miri64** [comment]
> I think @smlng suggested riot_unilib, short and unique.

What does "uni" stand for? Isn't there a name that describes better what the library is doing or at least something less generic (like e.g. @haukepetersen's favorite example "horst" :stuck_out_tongue_winking_eye:)?

**Comment by smlng** [comment]
I actually suggested `riot-unishell` for *universal shell* interface, or similar

**Comment by MrKevinWeiss** [comment]
Ya sorry, too much lib...  Generic is good though because it is supposed to take many different interfaces to hardware and standardize the commands, parse the data, provide validation and give extra information (such as decoding error messages)

**Comment by miri64** [comment]
> Generic is good though because it is supposed to take many different interfaces to hardware and standardize the commands, parse the data, provide validation and give extra information (such as decoding error messages)

I guess the key distinctive element here is "take many different interfaces **to hardware**" . Don't forget that while you are dwelling in the nether regions of the architecture stack, that there are *interfaces* above that have nothing to do with hardware ;-).

**Comment by miri64** [comment]
> I actually suggested `riot-unishell` for *universal shell* interface, or similar 

"`unishell`" for someone like me, who never to rarely interacts with the HAL directly, sounds to me like some kind of new shell feature or shell. "Can this new shell finally give an end to the centuries old shell war and be a universal shell every UNIX user can be happy with?"

**Comment by MrKevinWeiss** [comment]
riot_std_shell - for RIOT Standard Shell, it enforces standard commands and responses?

**Comment by miri64** [comment]
Can we go away from predicates like `uni` or `std`? This is not the standard shell for RIOT, right? How about `periph_shell`, `hal_shell`, `hw_shell`, `hw_test`, ...?

**Comment by MrKevinWeiss** [comment]
I was thinking about hardware abstraction layer but it is more a protocol abstraction layer...
`riot_pal`?  It is at least funny.

**Comment by miri64** [comment]
What does "application protocol" mean here. I guess I prefer `PAL` over it then ;-).

**Comment by MrKevinWeiss** [comment]
Can we go with `riot_pal` for the time being?  If anyone else has some better name I am super open to them but I do want to move forward (at least test the pip package procedure).

**Comment by MrKevinWeiss** [comment]
Closing since now all we have to do is `pip install riot_pal` :)

**Pull request closed without merging**
