### PR TITLE
periph/gpio: Clean up Doxygen text

### PR DESCRIPTION
**Pull request by gebart**
The Doxygen text was not matching what it describes. See http://riot-os.org/api/group__drivers__periph__gpio.html#ga48ba4c318486db320a4bf6237b49d61c

### CODE REVIEW

**Comment by LudwigKnuepfer** [comment]
Wasn't there a Doxygen warning for this?

**Comment by gebart** [comment]
Don't know, maybe it was ignored when the PR was merged.

**Comment by LudwigKnuepfer** [comment]
There were warnings, I'm too lazy to check since when ;)

**Comment by kYc0o** [comment]
I think doxygen warnings are recently treated, I can't remember Murdock complaining about this before... but well.. nice catch! ACK and Murdock green, so let's merge it!

**Pull request merged**
