### PR TITLE
cpu: use hwtimer_compat module for STM CPUs

### PR DESCRIPTION
**Pull request by haukepetersen**
and the cleanup continues...

tested for:

- nucleo-f091 (stm32f0)
- iot-lab_M3 (stm32f1)
- stm32f3discovery (stm32f3)
- stm32f4discovery (stm32f4)

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Will test soon. Hopefully

**Comment by haukepetersen** [comment]
yeah :-)

**Comment by PeterKietzmann** [comment]
ACK for the changes. Successfully tested with stm32f0, stm32f1, stm32f4. Don't have a stm32f3 and stm32l1. Who has?

**Comment by haukepetersen** [comment]
I do and did test with them successfully. Can I merge?

**Comment by PeterKietzmann** [comment]
Ok, Travis and me will trust you. ACK and go

**Comment by OlegHahm** [comment]
Can someone point me to what hwtimer_compat is actually doing? (On a high level perspective.)

**Comment by kaspar030** [comment]
It provides a hwtimer on top of periph/timer.

**Comment by OlegHahm** [comment]
But didn't we already had this for these platforms?

**Comment by kaspar030** [comment]
Yes, 10 exact copies of the same file. hwtimer_compat makes the compat layer a sys/ module.

**Comment by OlegHahm** [comment]
A sys module as an abstraction of a CPU module to implement a core module?

**Comment by kaspar030** [comment]
We could discuss where to put it, but I'd rather get rid of it by obsoleting hwtimer...

**Comment by OlegHahm** [comment]
Looking forward for this.

**Pull request merged**
