### PR TITLE
pkg tlsf: statistics

### PR DESCRIPTION
**Pull request by OlegHahm**
fixes https://github.com/RIOT-OS/RIOT/issues/4491

Caveat: for now the ps command will only show heap usage of the default memory pool (the one that is used at initialization).

For testing, one can use the ccn-lite example.

### CODE REVIEW

**Comment by OlegHahm** [comment]
For the diff of the patch file, see https://github.com/OlegHahm/tlsf/commit/854a8515202e04d79e18160324956f5801752422

**Comment by OlegHahm** [comment]
Anyone willing to review/test?

**Comment by authmillenon** [comment]
Indentation seems a little off.

**Comment by authmillenon** [comment]
How is one supposed to change the walker?

**Comment by OlegHahm** [comment]
> Indentation seems a little off.

Can you comment in https://github.com/OlegHahm/tlsf/commit/854a8515202e04d79e18160324956f5801752422 ? I think it might be that this happens because I mostly re-included original TLSF code.

> How is one supposed to change the walker?

That's currently not foreseen. There's some more work to do - particular if you use more than one memory pool, but I think it's better than nothing for now.

**Comment by authmillenon** [comment]
> Can you comment in OlegHahm/tlsf@854a851 ? I think it might be that this happens because I mostly re-included original TLSF code.

Done

**Comment by OlegHahm** [comment]
Ok, thanks. I will use tabs instead of white spaces consistently and not adapt TLSF's coding style to RIOT, okay?

**Comment by authmillenon** [comment]
Sounds like a good idea :-)

**Comment by OlegHahm** [comment]
did

**Comment by OlegHahm** [comment]
see https://github.com/OlegHahm/tlsf/commit/86c09263e1ca8ecbd31b43046cd60889e9d6aeb4

**Comment by authmillenon** [comment]
ACK, please squash.

**Comment by OlegHahm** [comment]
squashed

**Comment by authmillenon** [comment]
Patches contain whitespaces + lwIP is still not updated in the git-cache on Murdock's machine.

**Comment by OlegHahm** [comment]
> Patches contain whitespaces

That's what she said - but where?

**Comment by miri64** [comment]
Dunno. But running 

```bash 
sed -i 's/ \+$//' pkg/tlsf/patch.txt
```

Should fix it ;)

**Comment by OlegHahm** [comment]
Nope.

**Comment by miri64** [comment]
Try 

```bash
sed -i 's/\s\+$//' pkg/tlsf/patch.txt
```

instead (maybe they're just carriage-returns)

**Comment by OlegHahm** [comment]
Thanks

**Comment by OlegHahm** [comment]
Hm, since TLSF uses carriage-returns removing them from the patch seems to be harmful. Would you be okay to ignore Murdock for now if I revert the patchfile?

**Comment by miri64** [comment]
Okay, then revert it and we ignore Murdock for these static tests.

**Comment by miri64** [comment]
(ACK)

**Comment by OlegHahm** [comment]
All other tests succeed.

**Pull request merged**
