### PR TITLE
Unittest: sizeof core-tcb

### PR DESCRIPTION
**Pull request by odem99**

### CODE REVIEW

**Comment by Kijewski** [comment]
What does this test test?

**Comment by odem99** [comment]
It compares the size of each element of the struct tcb_t(tcb.h) with the defined data types.

**Comment by Kijewski** [comment]
But for what purpose?

**Comment by PeterKietzmann** [comment]
@Kijewski this PR should be more understood as an initial exercise for @odem99. Would you NACK it? I thought we could replace the test application

**Comment by authmillenon** [comment]
I think the purpose of `tests/sizeof_tcb` was not to put any prerequisite on the size of the tcb (which this tests effectively do), but to determine it for benchmarking purposes.

**Comment by PeterKietzmann** [comment]
Anyway, it was my negligence when I told @odem99 to write that as an initial exercise (which he fulfilled). Would you NACK merging this PR to unittests? Besides we can still stay with the benchmarking test in tests/.

**Comment by PeterKietzmann** [comment]
Ok seems like I did a mistake, sorry @odem99. I'll close this PR for now because of the lack of ACKs. Let's discuss further in personal (I sent you a mail). And btw: Technically the PR looks really good, was just my ignorance...

**Pull request closed without merging**
