### PR TITLE
gnrc: rename ng_netconf to ng_netopt

### PR DESCRIPTION
**Pull request by authmillenon**
Since [NETCONF](https://tools.ietf.org/html/rfc4741) is also a network protocol, the naming of this module already led to some issues regarding communicating about it. This is just an initial rename commit to ask for comments. If there is interest I will adapt the code using the types defined here.

### CODE REVIEW

**Comment by OlegHahm** [comment]
How about gnrc_conf?

**Comment by authmillenon** [comment]
Afaik the options are not restricted to gnrc.

**Comment by authmillenon** [comment]
Maybe @kaspar030 can answer this.

**Comment by haukepetersen** [comment]
@authmillenon is right, these options are not restricted to the `gnrc` stack, but also used for `netdev/netdev2` and thereby shared with other stacks. I can live with `NETOPT`, sound good to me.

**Comment by OlegHahm** [comment]
Me too.

**Comment by OlegHahm** [comment]
I would assume that the silence indicates that no one objects the name change. So, please go ahead!

**Comment by authmillenon** [comment]
Will do… tomorrow :D

**Comment by authmillenon** [comment]
Done

**Comment by authmillenon** [comment]
(Set the Ready for CI build to check if everything is set correctly… no capacities to do this locally :/)

**Comment by authmillenon** [comment]
All is well :D (except the static tests, because this PR needs squashing
)

**Comment by OlegHahm** [comment]
Since this is only a renaming PR and no one objects, I would say squash, wait for Travis again and merge.

**Comment by authmillenon** [comment]
Careful Cowboy, or we don't have anything to merge at the Hack'n'ACK :stuck_out_tongue_winking_eye:

**Comment by authmillenon** [comment]
Git was acting weird and removed 6f56b98 from history for some reason

**Comment by OlegHahm** [comment]
ACK and go!

**Pull request merged**
