### PR TITLE
ci: use riot/static-test-tools Docker image with static-tests and doc-build

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

Following https://github.com/RIOT-OS/riotdocker/pull/127, I manually pushed a [riot/static-test-tools Docker image](https://hub.docker.com/repository/docker/riot/static-test-tools).
This PR is using it in replacement of `riot/riotbuild`. We should see a noticeable speed improvement because the new image, dedicated to static tests is less than 700MB and `riot/riotbuid` is more than 6GB.

### Testing procedure

A green CI

### Issues/PRs references

Reuse the new Docker image organisation from https://github.com/RIOT-OS/riotdocker/pull/127

### CODE REVIEW

**Comment by aabadie** [comment]
The performance gain is quite important with the new riot/static-test-tools:
- The spin-up environment of doc-build (where the Docker image is fetch) goes from [1m37s](https://app.circleci.com/pipelines/github/RIOT-OS/RIOT/6782/workflows/3ea66504-f7f7-4787-9ffe-ba4594484613/jobs/6771/parallel-runs/0/steps/0-0) to [16s](https://app.circleci.com/pipelines/github/RIOT-OS/RIOT/6783/workflows/01d78b07-c1bb-499c-b722-3653877cc6e1/jobs/6773/parallel-runs/0/steps/0-0). Well here the gain is marginal, compared to the global 30 minutes taken by the whole job.
- In the static test action, the time spent fetching the Docker image goes from [2m4s](https://github.com/RIOT-OS/RIOT/runs/1702338021?check_suite_focus=true). In this case, the performance gain is significant, the time taken by the whole job is reduced by 1/3 (4m30 against 3m with this PR).

**Comment by miri64** [comment]
>     * In the static test action, the time spent fetching the Docker image goes from [2m4s](https://github.com/RIOT-OS/RIOT/runs/1702338021?check_suite_focus=true). In this case, the performance gain is significant, the time taken by the whole job is reduced by 1/3 (4m30 against 3m with this PR).

Unrelated to this PR, but this can probably be sped up even more, when the `buildsystem_sanity_check` script would only considered `changed_files` for its tests (currently it takes the whole repo into account which makes it quite slow).

**Comment by aabadie** [comment]
RIOT-OS/riotdocker#127 was merged and the [static-test-tools image](https://hub.docker.com/repository/docker/riot/static-test-tools) is now built automatically on dockerhub.
If we are ok with this PR, I think it can be merged.

**Comment by miri64** [comment]
Let's give the static tests a spin :-).

**Comment by fjmolinas** [comment]
Nice! Downloading the image dropped from 2m to 13s! Should we go ahead with this one?

**Comment by miri64** [comment]
> Nice! Downloading the image dropped from 2m to 13s! Should we go ahead with this one?

Of course!

**Review by miri64 — APPROVED** [review]
Works as advertised! Not sure about the circle CI test, but I guess that will also just work ;-).

**Comment by miri64** [comment]
Anyone wants to speed up the `buildsystem_sanity_check` now? It tests the whole repo and could be optimized by just checking the changed files, as the other tests do.

**Comment by miri64** [comment]
`circle-ci` had no problems pulling the new docker and succeeded to do `make doc` as expected.

**Comment by aabadie** [comment]
Thanks everyone :)

**Pull request merged**
