### PR TITLE
cpu/stm32l1: uart defaults with pull-ups

### PR DESCRIPTION
**Pull request by lebrush**
Just as done in st lib.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Did that optimize anything at your side? I'm just wondering if this is needed or useful. Reading through some forums you'll find that maybe the rx line needs pullups in some cases,  but I've never read about the tx line.

**Comment by gebart** [comment]
The TX line would be driven in both directions in a typical UART scenario. I don't know the particular MCU but I would guess that adding a pull-up on the TX (without open drain) would either do nothing or simply increase power consumption..

**Comment by lebrush** [comment]
The story of this is that while debugging the problem that lead to #4854 I stopped having UART output. Comparing the initialization with the st lib I saw that they do configure them as pull up while RIOT keeps them floating. Changing them to pull-up fixed my UART problem. 

The whole thing was a misconfiguration of the uart on my side (as I said, I was trying to figure out what was going on with the i2c), so #4854 has no dependency on this; but since I saw a difference with st lib (which as far as I know is usually quite right) I though that it would be a good idea to do the same thing.

Summarizing: I couldn't find any reference neither in the user guide nor in the errata and the system works as it is but they do it differently and I guess there must be a reason.

**Comment by gebart** [comment]
@lebrush I am more sceptical to the flawlessness of st lib. I would guess that the TX pull up in st lib is merely a copy and paste mistake by the ST engineers, unless the st lib configures the TX as open drain, in which case it would make sense to set the pull up.

**Comment by lebrush** [comment]
Actually what you say @gebart makes perfect sense regarding power consumption. Since the code is already working and pull ups are not required for UART to work. I'll close this PR :-)

**Comment by gebart** [comment]
@lebrush It might still be an idea to use pullups on RX to avoid floating the input if the UART is not connected externally. The change that I contested was the pullup on the TX pin, since that should be driven by the stm32l1 for both 0 and 1.

**Pull request closed without merging**
