### PR TITLE
ip: use d_addr instead of s_addr when setting the destaddr

### PR DESCRIPTION
**Pull request by cgundogan**

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
ACK

**Comment by BytesGalore** [comment]
ACK -> merge at will

**Comment by gebart** [comment]
NACK, this is rather a symptom of a copy and paste error.

**Comment by gebart** [comment]
https://github.com/RIOT-OS/RIOT/pull/2512/files#diff-04c08581fb7bf56b778bffcde524a698R1432 s_addr -> d_addr

**Comment by cgundogan** [comment]
this is what I hoped to hear (:

**Comment by gebart** [comment]
@cgundogan the link is not working, but see line 1432 of lowpan.c

**Comment by LudwigOrtmann** [comment]
@cgundogan maybe provide a description next time ;)

**Comment by cgundogan** [comment]
@gebart can you look at my second attempt? I did as you stated - replaced `s_addr` by `d_addr`.

**Comment by gebart** [comment]
@cgundogan the change looks right.

**Comment by gebart** [comment]
Travis is happy, ACK & go

This was a copy and paste error in #2499 (compare L1431 with L1496 in the original implementation)

**Pull request merged**
