### PR TITLE
cpu/samd21: fixed broken spi_transfer_byte function

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by kaspar030** [comment]
ACK. Had the same on l21...

**Comment by kaspar030** [comment]
Once I get an R21, I'll unify the implementations.

**Comment by OlegHahm** [comment]
Can you briefly the bug and it's effect?

**Comment by haukepetersen** [comment]
Simple, SPI does not work if the `in` paramter for the `spi_transfer_byte()` function is NULL. My guess is that this bug shows only for F_CPU values > 8MHz (which will be standard soon). So this is why @kaspar030 and were probably the first ones to experience this bug on the samd21 and the saml21...

**Comment by kaspar030** [comment]
the problem is that if ```in``` is not given, the function does only wait until the spi send register is empty, but not until reception is complete. The effect is that SPI transfers without ```in``` and on fast CPUs un-CS before the transfer is complete.

**Comment by OlegHahm** [comment]
Thanks, got it.

**Comment by haukepetersen** [comment]
Travis is happy -> go.

**Pull request merged**
