### PR TITLE
examples/nimble_*: use nimble_autoadv module

### PR DESCRIPTION
**Pull request by HendrikVE**
### Contribution description

This PR modifies the example applications `nimble_gatt` and `nimble_heart_rate_sensor` such that they use the new automated advertising module, provided by PR #13425

### Testing procedure

This PR is rebased on top of PR #13425, so you only have to build and test the applications mentioned above.

#### Dependencies:
- [x] PR #13425

### CODE REVIEW

**Review by fjmolinas — APPROVED** [review]
ACK, both applications still work as expected, @HendrikVE can you rebase so that the newer actions are triggered?

**Comment by fjmolinas** [comment]
BTW this does come at the price of some code size:

- master:

```
   text	   data	    bss	    dec	    hex	filename
  77220	    684	  10692	  88596	  15a14	/home/francisco/workspace/RIOT/examples/nimble_heart_rate_sensor/bin/nrf52840-mdk/nimble_heart_rate_sensor.elf
```

- rebased pr:

```
   text	   data	    bss	    dec	    hex	filename
  77560	    684	  10756	  89000	  15ba8	/home/francisco/workspace/RIOT/examples/nimble_heart_rate_sensor/bin/nrf52840-mdk/nimble_heart_rate_sensor.elf

```

**Comment by HendrikVE** [comment]
@fjmolinas Thank you very much for testing my PR. I rebased to the newest master. Regarding the code size I think it's ok as the nrf52 has quite some flash storage and we are reducing code duplication :)

**Comment by fjmolinas** [comment]
> @fjmolinas Thank you very much for testing my PR. I rebased to the newest master. Regarding the code size I think it's ok as the nrf52 has quite some flash storage and we are reducing code duplication :)

Yep just wanted to state it.

**Comment by benpicco** [comment]
All green here

**Pull request merged**
