### PR TITLE
sys/arduino: add Serial over stdio support

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides the support for using the `Serial` over `stdio_*`

On Arduino boards, the `Serial` object uses
- either an UART interface connected to an USB interface via an additional ATmega chip (class `HardwareSerial`)
- or directly the USB CDC interface (class `_Serial`).

However, the `Serial` object in RIOT always uses the UART interface defined by `ARDUINO_UART_DEV`, usually `UART_DEV(0)`. Therefore `Serial` does not work for boards like `feather-m0` and `arduino-mkr` which use the USB CDC interface directly. Since the STDIO already uses the USB CDC interface for such boards with the help of the module `stdio_cdc_acm`, it is possible to realize the `Serial` object for such boards on top of the STDIO.

For this purpose the module `arduino_serial_stdio` is introduced. If this module is enabled AND the `ARDUINO_UART_DEV` is defined as `UART_UNDEF`, the STDIO is used for `Serial`. This allows either the use of the STDIO or the use of a UART interface if defined by `ARDUINO_UART_DEV`.

The module `arduino_serial_stdio` is automatically enabled for boards using `stdio_cdc_acm`. However, to actually use `Serial` via STDIO, `ARDUINO_UART_DEV` have to be defined additionally `UART_UNDEF`. This is done by this PR for
- `feather-m0`
- `arduino-mkr`.

For `sodaq` boards the situation is unclear, since `ARDUINO_UART_DEV` is explicitly defined for these boards and it is not clear whether this is intentional.

The use of `Serial` over STDIO requires that the used `stdio` backend implements the `stdio_available` function that was introduced by PR #17446.

### Testing procedure

1. Use either a `feather-m0` or an `arduino-mkr` board and use the following example to test:
    ```
    make BOARD=arduino-mkr1000 -C examples/arduino_hello-world flash term
    make BOARD=feather-m0 -C examples/arduino_hello-world flash term
    ```
    Enter a string should be echoed as expected.
2. Use any other board that uses `std_uart`, for example `esp32-wroom` and do the same:
    ```
    CFLAGS='-DARDUINO_UART_DEV=UART_UNDEF' USEMODULE=arduino_serial_stdio \
    make BOARD=esp32-wroom-32 -C examples/arduino_hello-world flash term
    ```
    Enter a string should be echoed as expected.

### Issues/PRs references

Depends on PR #17446.

### CODE REVIEW

**Comment by gschorcht** [comment]
OK, I have rebased to have the changes of PR #17446. `ARDUINO_UART_DEV` is set to `UART_UNDEF` for all `sodaq*` boards. We could move this definition to a `arduino_board_common.h` file to define it at only one place.

**Comment by aabadie** [comment]
Thanks !

> We could move this definition to a arduino_board_common.h file to define it at only one place.

Let's keep this for a follow-up.

**Review by aabadie — APPROVED** [review]
ACK!

**Comment by gschorcht** [comment]
Thanks for reviewing and merging

**Pull request merged**
