### PR TITLE
features_modules: include puf_sram if used

### LINKED ISSUE #14939: puf_sram not used when included as a feature
#### Description
Opportunistic inclusion of the `puf_sram` module does not work.
It has to be added to `USEMODULE` in order to seed the PRNG.

##### puf_sram is used

    USEMODULE=puf_sram make BOARD=samr21-xpro -C examples/gnrc_networking -j flash

##### puf_sram is not used

    FEATURES_REQUIRED=puf_sram make BOARD=samr21-xpro -C examples/gnrc_networking -j flash

#### Expected results
```
2020-09-03 18:47:37,606 # random: PUF SEED not fresh
2020-09-03 18:47:37,616 # main(): This is RIOT! (Version: 2020.10-devel-1225-gffea8)
2020-09-03 18:47:37,620 # RIOT network stack example application
2020-09-03 18:47:37,623 # All up, running the shell now
```

#### Actual results
```
2020-09-03 18:50:42,383 #  main(): This is RIOT! (Version: 2020.10-devel-1225-gffea8)
2020-09-03 18:50:42,388 # RIOT network stack example application
2020-09-03 18:50:42,390 # All up, running the shell now
```
(no `puf_sram` used)

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`puf_sram` is advertised as a CPU feature, but it can only be used as a module.

### Testing procedure

Run `FEATURES_REQUIRED=puf_sram make BOARD=samr21-xpro -C examples/gnrc_networking -j flash`

`puf_sram` should now be used.
On `master` the `FEATURES_REQUIRED` is simply ignored and no `puf_sram` is used, nor is an error raised.

### Issues/PRs references

suggested by @fjmolinas in https://github.com/RIOT-OS/RIOT/issues/14939#issuecomment-686932347
fixes #14939

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK. `make info-modules -C tests/puf_sram` gives the same output as in master, so this works as intended.

**Comment by kaspar030** [comment]
@PeterKietzmann wasn't this per-board so the cold/warm reboot assumptions are validated on a per-case basis?

**Comment by kaspar030** [comment]
> @PeterKietzmann wasn't this per-board so the cold/warm reboot assumptions are validated on a per-case basis?

unrelated, sorry for the noise.

**Comment by maribu** [comment]
> @PeterKietzmann wasn't this per-board so the cold/warm reboot assumptions are validated on a per-case basis?

This was actually improved by re-generating the seed from a warm reboot counter in case of warm boots. This way, the random seed will not easily repeat. (However, the entropy with the current implementation is not that high in case of warm boots, due to not using a cryptographic hash function.)

**Pull request merged**
