### PR TITLE
nrf802154/hal: fix unwanted emissions at the end of ACK frame

### PR DESCRIPTION
**Pull request by jia200x**
### Contribution description
This commit turns off the transceiver immediately after sending an ACK frame in order to avoid unwanted emissions (see [ERRATA ID 204, page 25](https://infocenter.nordicsemi.com/pdf/nRF52840_Rev_2_Errata_v1.3.pdf)).
When the radio stays in TX_ON without an explicit transition, the radio keeps sending a spurious signal for some milliseconds.

Check the following picture to see how this looks like (using the SDR, Y axis is RF power, X axis is time, first frame is the CC2538 and the second one is the ACK of the nrf802154)
pic

And this is how it looks with this PR:
img

### Testing procedure
Hard to test without an SDR, but at least make sure that some ping stress tests still work ok.

### Issues/PRs references
None so far

### CODE REVIEW

**Comment by jia200x** [comment]
Besides the ugly shape of the ACK, I suspect this causes some packet losses because of failed CCA. So, this should definitely be in the release :)

**Review by maribu — APPROVED** [review]
ACK. Code and reasoning makes sense and I trust your testing.

**Comment by maribu** [comment]
Out of personal interest: What is your SDR setup? (Software & Hardware)?

**Comment by jia200x** [comment]
> Out of personal interest: What is your SDR setup? (Software & Hardware)?

I'm using a bladeRF x40 (https://www.nuand.com/product/bladerf-x40/) with GNU Radio. I'm quite happy about it TBH!
I plan to upload the patches at some point, since this can be use to discover serious bugs. I'm also able to decode IEEE 802.15.4 frames using [gr-ieee802-15-4](https://github.com/bastibl/gr-ieee802-15-4)

**Comment by jia200x** [comment]
thanks for the review!

**Pull request merged**
