### PR TITLE
boards: fixed include guards

### PR DESCRIPTION
**Pull request by haukepetersen**
solves #2623 for all boards

### CODE REVIEW

**Comment by authmillenon** [comment]
Usually there is one trailing `_`, but this is not necessary. ACK, when travis is happy.

**Comment by haukepetersen** [comment]
Acutally, I'd like to propose as a best practice to not use a trailing `_`...

**Comment by authmillenon** [comment]
I just prefer it, because it syntactically separates include guards from other macros.

**Comment by Kijewski** [comment]
Would you consider me a heretic if I told you that I prefer [`#pragma once`](https://en.wikipedia.org/wiki/Pragma_once)?

**Comment by haukepetersen** [comment]
> syntactically separates include guards from other macros

so does the `_H` ending :-)

> Would you consider me a heretic if I told you that I prefer #pragma once?

nope. I also like it, but as long it's not by the standard I would always have a bad feeling about it...

**Comment by haukepetersen** [comment]
Oh, and Travis is happy -> go.

**Comment by authmillenon** [comment]
>> syntactically separates include guards from other macros
> so does the _H ending :-)

```C
#ifndef BAROMETER_H_
#define BAROMETER_H_
/**
 * @brief Height of the sensor
 */
#define BAROMETER_H
#endif
```

Proof by counter-example ;-)

**Pull request merged**
