### PR TITLE
VERSION: add 2019.04 version file

### PR DESCRIPTION
**Pull request by danpetry**
### Contribution description

Add version file for release branch

### CODE REVIEW

**Comment by miri64** [comment]
We should merge this after the release note backport.

**Comment by miri64** [comment]
Please rebase.

**Comment by danpetry** [comment]
I'm just raising a fixup to the release notes to include the failing tests for the frdm-k64f, please hold off :)

**Comment by miri64** [comment]
Due to https://github.com/RIOT-OS/RIOT/pull/11457, another rebase is needed :-/

**Comment by danpetry** [comment]
done

**Comment by miri64** [comment]
And go.

**Pull request merged**
