### PR TITLE
cpu: remove superfluous SystemCoreClockUpdate

### PR DESCRIPTION
**Pull request by gebart**
rebase of #4553 
Fixed the K60 merge conflicts. Tested on Mulle.

### CODE REVIEW

**Comment by haukepetersen** [comment]
Just some minor doxygen warnings in `boards/mulle/include/periph_conf.h`

**Comment by gebart** [comment]
Okay, will fix the warnings

**Comment by gebart** [comment]
Ok to do the doxygen fixes in a followup?

**Comment by gebart** [comment]
fixed the doxygen warnings, amended

**Comment by gebart** [comment]
Murdock (1) fails on unrelated Cortex-M0 boards because of full disk. Murdock2 is fine though, OK to merge?

**Pull request merged**
