### PR TITLE
jerryscript: Fix conversion errors reported by LLVM/clang

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Fixes some conversion errors caused when compiling with LLVM/clang

### Issues/PRs references
Detected in #9398

### CODE REVIEW

**Comment by kYc0o** [comment]
As far as I can see it's only about casting isn't it?

**Comment by miri64** [comment]
Yes, the target type (specific `enum`) has a smaller value range than the source type (`uint16_t`). LLVM/clang is throwing an *error* because of that.

**Comment by miri64** [comment]
After talking with @emmanuelsearch I decided to try to get it upstream, however.

**Comment by miri64** [comment]
Oops.

**Comment by kYc0o** [comment]
Ok, so you leave this open until you get news from upstream?

**Pull request closed without merging**
