### PR TITLE
Implement MCI emulation for native

### PR DESCRIPTION
**Pull request by x3ro**
The MSBA2 has an MCI driver to talk to the on-board
SD-card reader, but until now there was no way of
running/testing an application using it under native.
This PR adds rudimentary emulation of the MCI interface
and provides a test application.

### CODE REVIEW

**Comment by authmillenon** [comment]
Would be cool if you can actually store to a file instead of an array :-)

**Comment by x3ro** [comment]
@authmillenon This is just the low-level interface for talking to the storage medium. Everything else will be built on top of that, but I need this for testing :)

**Comment by authmillenon** [comment]
Maybe I miss something, but `cpu/native/mci/native-mci.c` looks pretty much like an implementation and not like an interface for me. ;-) I meant, that you could store everything you throw in there into a file (with a fixed filename and size, e.g. `cpu/native/mci_512.dat`), instead of the array `native_mci_memory`

**Comment by x3ro** [comment]
Oh :) Yeah, I misunderstood you there. Why would you want to store a file? That is, what would be your use case?

**Comment by authmillenon** [comment]
The MCI interface is used for persistent data, right? A file is persistent. An array in RAM not.

**Comment by authmillenon** [comment]
+ the module would block less RAM. And yes, when you start to use 8MB for one module I get grumpy, even on native ^^.

**Comment by LudwigOrtmann** [comment]
I already wrote a file based storage driver for native for some other interface.

**Comment by LudwigOrtmann** [comment]
https://github.com/RIOT-OS/RIOT/pull/2239

**Comment by x3ro** [comment]
@authmillenon Updated to use a file instead of RAM :sparkles:

**Comment by authmillenon** [comment]
:dancer:

**Comment by authmillenon** [comment]
Superseded by #4345

**Pull request closed without merging**
