### PR TITLE
jenkins: add initial config

### PR DESCRIPTION
**Pull request by cgundogan**
Rationale: I am currently evaluating the performance of Jenkins and for this a `Jenkinsfile` is necessary.

Jenkins is able to detect PRs and branches when a `Jenkinsfile` is included in the root directory.
Such a `Jenkinsfile` orchestrates a build's operation (much like `.travis.yml` for Travis).
This PR is WIP and feedback is very welcome.

### CODE REVIEW

**Comment by kaspar030** [comment]
Ok, so whats the plan? We merge as soon as Jenkins builds properly?

**Comment by OlegHahm** [comment]
Shouldn't Jenkins wait for the "Ready for CI" label, too?

**Comment by cgundogan** [comment]
The Jenkinsfile has no impact on Murdock, so I removed the `Ready for CI build` label to free up Murdock's Q for other important PRs

**Comment by OlegHahm** [comment]
I see - but in principle Jenkins is able to react on Github labels?

**Comment by cgundogan** [comment]
In theory yes, but I am currently failing to let Jenkins react correctly on label events. I will get this PR merged once it shows green and from there we can tackle further. Currently, every commit push would generate a build (as it used to be for travis way back in time). A simple semi-solution could be to look at the labels from within the Jenkinsfile (curl+GitHub API), but there is still the problem, that a null-commit would be necessary to trigger another  build. But then again, are there many cases where the same commit must be build several times?

**Comment by cgundogan** [comment]
>that a null-commit would be necessary to trigger another build

and, ofcourse, it is also possible to trigger a build from the Jenkins GUI directly.

**Comment by cgundogan** [comment]
@RIOT-OS/maintainers from my point of view this PR is ready to merge, so that we can observe how Jenkins performs on production. However, I am not able to merge my own PR, is anyone willing to hit the button? @kaspar030 (: ?

**Comment by smlng** [comment]
btw. all RIOT-OS maintainers are allow to login into [Jenkins](riot-ci.inet.haw-hamburg.de) with their github credentials. They can trigger or cancel builds of PRs.

**Comment by miri64** [comment]
Seems like the script for the nightly builds isn't as it supposed to be (`stderr: fatal: Couldn't find remote ref refs/pull/${GITHUB_PR_NUMBER}/merge`. Doesn't make much sense if it is supposed to build master ;-))

**Comment by cgundogan** [comment]
the nightly config. was just an experiment some weeks ago. @smlng do you want to save the config. before I remove the job?

**Comment by smlng** [comment]
ah simply delete it, I'll recreate it later ...

**Comment by smlng** [comment]
btw. rebased my PRs #6333 and #6326 onto new master both are building in jenkins now! the latter with OS X enabled

**Comment by miri64** [comment]
How do I add mine? I have a native PR in the pipeline (#6337) which I would very much like to test :-)

**Comment by cgundogan** [comment]
simply rebasing to current master should suffice (:

**Comment by miri64** [comment]
Meh :disappointed_relieved:

**Pull request merged**
