### PR TITLE
tests: move core related applications to their own tests/core/ folder

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is similar as #19435, #19552, #19551 and #19564 but applied to core related test applications. There's no clear `core_` naming scheme for these applications so maybe some were missed or added by mistake.

### Testing procedure

- Green CI
- Check the right applications have been moved

### Issues/PRs references

#15358, #19435, #19552, #19551 and #19564

### CODE REVIEW

**Review by maribu — APPROVED** [review]
I wonder if the irq_cpp should rather be in a new `tests/cpp` (or maybe `tests/cxx`, as cpp could also mean c preprocessor).

But anyway, let's not have this discussion here. Once there is a `tests/cxx` folder, that could still be easily moved from `tests/core` to `tests/cxx`.

**Comment by aabadie** [comment]
The cpp applications will be moved in `tests/sys` after #19566 is merged (but it's still broken now)

**Comment by aabadie** [comment]
bors merge

**Comment by aabadie** [comment]
bors merge

**Comment by maribu** [comment]
bors merge

**Pull request merged**
