### PR TITLE
dist/openocd.sh: added shutdown to flash commands

### LINKED ISSUE #2470: Flashing is not working on SAMR21 any more
As stated in https://github.com/RIOT-OS/RIOT/pull/2408#issuecomment-75021353 `make flash` (using the unified OpenOCD script from #2408) is currently not working for the SAMR21 - at least on ArchLinux. (Neither with the AUR version of OpenOCD nor with a fresh compiled from current git HEAD.) Putting an `exit` at the end of the `program` command or adding a `shutdown` command at the end helps, but leads to `1` as an exit code indicating an error - but I don't know why, because flashing seems to work correctly.

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #2470

### CODE REVIEW

**Comment by OlegHahm** [comment]
Does this fix the problem for STM32f4 as well?

**Comment by haukepetersen** [comment]
yapp. That problem was no real problem, it was just because of my own stupidity...

**Comment by haukepetersen** [comment]
actually without this PR the stm shows the same behavior than the atmel board with the newest OpenOCD version...

**Comment by haukepetersen** [comment]
hm, but there seems to be some other trouble - Make is exiting from `make flash` with some Error.

**Comment by OlegHahm** [comment]
Like I've written in #2470. ;)

**Comment by haukepetersen** [comment]
ups, that part I did not read...

**Comment by haukepetersen** [comment]
ok, here is a small workaround - what do you say?

**Comment by LudwigOrtmann** [comment]
Can't you figure out *why* openocd exits with a non-zero exit code?

**Comment by haukepetersen** [comment]
probably, but not at the moment...

**Comment by LudwigOrtmann** [comment]
Then at least add a comment in there.

**Comment by OlegHahm** [comment]
I made a patch for OpenOCD: https://github.com/OlegHahm/openocd/commit/61c126327d1346795a0e4a9fbd364eec43caeede

To me it looks like that the command value for shutdown is interpreted as an error value without this patch.

**Comment by OlegHahm** [comment]
The behavior was introduced in https://github.com/ntfreak/openocd/commit/a35712a8

**Comment by LudwigOrtmann** [comment]
So ... the comment should point to the issue (which has to be created first?) over at openocd?

**Comment by OlegHahm** [comment]
#2472 should do the trick in a sensible way.

**Comment by OlegHahm** [comment]
How about we merge this, but leave #2472 open until newer OpenOCD versions are available in most distributions (preferably even in Ubuntu LTS)?

**Comment by haukepetersen** [comment]
don't really like the idea of keeping #2472 open for (what could be) a long time. I would rather merge this PR and close #2472, and then just revisit this in a year or so. And if we really forget about it by then, it's not like overwriting the openOCD return value does break anything...

**Comment by OlegHahm** [comment]
We have issues that are open for far more time and I hope that even Ubuntu people aren't that slow. Ignoring the OpenOCD return value is not a clean solution in my opinion.

**Comment by haukepetersen** [comment]
true

**Comment by kaspar030** [comment]
Seems upstream openocd got fixed. See #2897.

**Comment by OlegHahm** [comment]
But OpenOCD in Ubuntu is still 0.8, right?

**Pull request merged**
