### PR TITLE
core: missing restoreIRQ in mutex_unlock

### PR DESCRIPTION
**Pull request by Kijewski**
`mutex_unlock()` did not restore IRQsbefore yielding for the woken up
thread.

~~The priority of the woken up thread has to be read before reenabling the
IRQs, or there will a race condition.~~

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Could you please explain what exactly the race condition would look like (including correct and defective behavior)?

**Comment by kaspar030** [comment]
Looks like an error introduced when converting from dump disable/enableIRQ to disable/restoreIRQ.

Currently, save gets saved, but then we might yield to another thread, return at any point, and then restore the old irqstate which might already be stale.

**Comment by Kijewski** [comment]
> Could you please explain what exactly the race condition would look like

My fault, I introduced a race condition in my first attempt to fix the PR missing mutex_unlock issue and forgot about that. :)

**Comment by LudwigOrtmann** [comment]
Why is the race condition part crossed out in the PR description? Should the commit message be altered accordingly?

**Comment by authmillenon** [comment]
What's the status on this PR? Could this be an alternative fix to the issue we faced at IETF related to #3450?

**Comment by kaspar030** [comment]
Needs a rebase, but the bug is still valid.

**Comment by Kijewski** [comment]
Sorry, my time is *very* limited right now. I will rebase this PR once I have a little more breath, but I guess you two are at least as apt as I am to turn this issue into a proper PR. Do y'all want to adopt this PR?

**Comment by kaspar030** [comment]
@Kijewski I'll adopt it. Sorry for not getting back to this bug earlier.

**Comment by Kijewski** [comment]
@kaspar030 no problem at all.

**Comment by OlegHahm** [comment]
Superseeded by #3640. :turtle:

**Pull request closed without merging**
