### PR TITLE
cpu/cc260x: add I2C implementation

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Adds a previously missing periph/i2c implementation for TI cc26xx.

### Testing procedure

HIL FTW!

### Issues/PRs references

none

### CODE REVIEW

**Comment by MrKevinWeiss** [comment]
Will test tomorrow, I think I have the hardware I just need to connect it up.

**Comment by MrKevinWeiss** [comment]
So here are some things I found, I leave it to you to determine if they are a problem:
- the speed seems fast for the internal pullups, I needed external pullups to get reliable communication (I don't even know if they have internal pullups)
- There is no recovery from NACK in the read bytes (so if you nack an address then try to read bytes after it gives EIO)
- It appears that you write a byte even if a NACK occurs on the write
- No protection for incorrect flag usage, (sending an I2C_NOSTART read/write bytes without checking if the bus is busy first)

Overall I would say it is usable in most applications, just a few corner cases that are not covered (sometimes, depending on hardware, they can be quite hard).

Here are the [test results](https://gist.github.com/MrKevinWeiss/e96973e854f88ea6e9126fbe762f0002) after altering the test to not read bytes after NACK (because I didn't connect the reset pin)

**Comment by MrKevinWeiss** [comment]
As discussed IRL, I can take this over.  I will start later in the week (I think it was this one)

**Comment by kaspar030** [comment]
> As discussed IRL, I can take this over. I will start later in the week (I think it was this one)

thanks a bunch!

**Comment by MrKevinWeiss** [comment]
Closed in favor of #11306

**Pull request closed without merging**
