### PR TITLE
boards/nucleo-l552ze-q doc: Improvements to documentation

### PR DESCRIPTION
**Pull request by krzysztof-cabaj**
### Contribution description
Improvements to STM Nucleo L552ZE-QE documentation:

- Add board image,
- Add MCU table - similar to those, for example for, Nucleo F103RB, F302R8 or F446RE,
- Add information concerning accessing RIOT shell (see Issue #17453) 

### Testing procedure

```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l552ze-q.html
```

### Issues/PRs references

Issue #17453

### CODE REVIEW

**Comment by benpicco** [comment]
Looks good but CI is complaining about trailing whitespace

**Comment by krzysztof-cabaj** [comment]
Now everything should be fine. BTW. Can we move PR #17550 forward ? ;)

**Comment by benpicco** [comment]
please squash

**Comment by krzysztof-cabaj** [comment]
Squashed!

**Comment by krzysztof-cabaj** [comment]
Fixed. Sorry. My fault.

**Comment by benpicco** [comment]
Thank you!

**Comment by krzysztof-cabaj** [comment]
Thank for rapid response! This was very fruitful "Friday with RIOT" :D

**Pull request merged**
