### PR TITLE
lis3mdl: fix default params

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
In the default config .odr and .scale where switched around.

### Issues/PRs references
Detected in #9398

### CODE REVIEW

**Comment by cladmi** [comment]
This fix building:

```
make -C tests/driver_lis3mdl BOARD=nucleo-f401re clean all TOOLCHAIN=llvm
```

It requires https://github.com/RIOT-OS/RIOT/pull/9612  for testing this PR though (even in master).

**Comment by miri64** [comment]
It's not just fixing the the build issue, but an actual configuration bug ;-). Now the device is initialized with 10Hz ODR and a scaling factor of 4 ;-).

**Comment by cladmi** [comment]
I edited my comment too late to say "for testing with `llvm`".

**Comment by miri64** [comment]
Back port in #9614

**Pull request merged**
