### PR TITLE
ng_netreg: Allow registration of NG_NETTYPE_UNDEF

### PR DESCRIPTION
**Pull request by authmillenon**
This is an alternative to #2564.

I think it makes sense to allow registration to `NG_NETTYPE_UNDEF`, e. g. to receive packets from radio drivers that don't have an Ethertype-like field in their header. Or just for someone to receive the packet.

### CODE REVIEW

**Comment by haukepetersen** [comment]
+1, ACK and kicked Travis...

**Comment by haukepetersen** [comment]
the unittests seem to have some trouble...

**Comment by authmillenon** [comment]
Adapted the unittests (or rather removed the test that assumed `NETTYPE_UNDEF` to be an invalid value ;-))

**Comment by OlegHahm** [comment]
Unittests segfault on native.

**Comment by authmillenon** [comment]
I thought I fixed this …

**Comment by authmillenon** [comment]
fixed. Strange that this only happens with the global unittests

**Comment by authmillenon** [comment]
Does the ACK still uphold on this?

**Comment by haukepetersen** [comment]
yes (when squashed).

**Comment by authmillenon** [comment]
Done.

**Pull request merged**
