### PR TITLE
cpu/stm32/periph/eth: Fix transmission bug

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

Using the `TER` bit in the TX descriptors when only using a single descriptor for sending triggered a hardware bug. Thus, stop using the TER bit and store the currently active TX descriptor in RAM instead.

### Testing procedure

See https://github.com/RIOT-OS/RIOT/pull/14594#issuecomment-681696715

### Issues/PRs references

Bug introduced by https://github.com/RIOT-OS/RIOT/pull/14594

### CODE REVIEW

**Comment by maribu** [comment]
Note: I also tested for regressions with `examples/gnrc_networking` and was still able to ping my Nucleo with GNRC. So this time TX should work with both multiple chunks in the `iolist` or only one chunk.

**Comment by maribu** [comment]
TODO: Fix typo in commit message

**Comment by maribu** [comment]
> TODO: Fix typo in commit message

Done

**Review by benpicco — APPROVED** [review]
Code looks OK, I don't have the hardware to test, but I trust your testing.

**Comment by maribu** [comment]
ping ;-)

**Comment by maribu** [comment]
Thanks! :-)

**Pull request merged**
