### PR TITLE
pkg/libfixmath: Protect svn checkout with a lock

### PR DESCRIPTION
**Pull request by gebart**
Should fix problems on Travis with failing checkouts.

### CODE REVIEW

**Comment by gebart** [comment]
Works fine on my Linux system with util-linux 2.26.2.
Needs testing on OSX and FreeBSD (the `lockf` path, it's not installed on Linux by default).

**Comment by gebart** [comment]
Finally Travis is all green for the first time in a long time!

**Comment by gebart** [comment]
Please prioritize reviewing this PR as it fixes a major problem with Travis testing of all other PRs.

**Comment by OlegHahm** [comment]
To be honest I'm too lazy to review the scripts, but since Travis is green and only libfixmath is affected.

**Pull request merged**
