### PR TITLE
WIP cpu/native: allow for multiple netdev2_tap devices

### PR DESCRIPTION
**Pull request by toonst**
While implementing some changes in #5613, I saw that the netdev2_tap driver could make use of this change to allow multiple tap devices. 
TODO: find some way to have a pointer to the right netdev2_tap device in startup.c

I'm not sure if this makes sense to go through with this, so comments very welcome.

### CODE REVIEW

**Comment by miri64** [comment]
It definitely makes sense! I wanted to do this month ago, but never found the time. Please go ahead!

**Comment by LudwigKnuepfer** [comment]
I would like to encourage you to take a look at https://github.com/RIOT-OS/RIOT/pull/5582 as it most likely has conflicts / opportunities for positive synergy effects ;-)
Maybe you and @alexaring can work together to combine your respective needs into one pull request. (Remember, you can create pull requests against a pull request..)

**Comment by toonst** [comment]
@LudwigKnuepfer Good idea, seems really similar to the netdev2_tap implementation indeed.

I'm wondering where this netdev2_tap should be defined. It should probably either be in the `startup.c` or in the `auto_init_netdev2_tap.c`. How do make sure it is accessible in both places? @miri64 What's the use case for multiple tap devices and how should we handle that?

**Comment by alexaring** [comment]
@toonst can you provide somehow that the tap interface can be optional? Or is this already included in this pull-request? So starting native riot without any tap device argument is possible?

Thanks. If your pull-request is fine, I will try to adapt your changes to #5582

**Comment by miri64** [comment]
Fixes #2195 btw.

**Comment by LudwigKnuepfer** [comment]
Sorry, I don't have time to review this properly at the moment - removed my assignment.

**Comment by miri64** [comment]
I get

```
/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_networking/bin/native/cpu/startup.o: In function `startup':
startup.c:(.text.startup+0x372): undefined reference to `netdev2_tap'
collect2: error: ld returned 1 exit status
/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_networking/../../Makefile.include:259: recipe for target 'all' failed
make: *** [all] Error 1
make: Leaving directory '/home/mlenders/Repositories/RIOT-OS/RIOT/examples/gnrc_networking'
```

if I try to compile. Or is that what you mean by

> TODO: find some way to have a pointer to the right netdev2_tap device in startup.c

**Comment by toonst** [comment]
Sorry for not getting back earlier on this. I'm currently travelling without developer pc and will be for the next 10 months, so I won't be able to finish this timely.

@miri64 Yes, exactly. Before, ```netdev2_tap_t netdev2_tap;``` was defined in ```cpu/native/netdev2_tap/netdev2_tap.c  +L 66```. But since we want to be able to use multiple interfaces this doesn't seem to make sense anymore. What I did was put it in ```sys/auto_init/netif/auto_init_netdev2_tap.c ```, which is similar to other auto_init files, but then there is the problem that ```startup.c``` needs access to that variable (the linking problem you showed in previous port). 
I hope it's more clear now.

**Comment by miri64** [comment]
> What I did was put it in sys/auto_init/netif/auto_init_netdev2_tap.c, which is similar to other auto_init files, but then there is the problem that startup.c needs access to that variable (the linking problem you showed in previous port). 

I'm currently working on another networking device for native and came up with a solution I think, that would also make netdev2_tap more similar to the other devices: do not use the device itself in `startup.c` at all, just set the `params` struct.

Given that you said you won't be able to work on this the next year (or less ;-)): do you mind if I take over this one?

**Comment by toonst** [comment]
Hey @miri64, of course not, go ahead! Seems a clean solution to me.

**Comment by miri64** [comment]
Adapted in #6311

**Pull request closed without merging**
