### PR TITLE
cpu/cortex_m0_common: added crash.c

### PR DESCRIPTION
**Pull request by haukepetersen**

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
ACK, merge when Travis is happy.

**Comment by gebart** [comment]
I've kicked Travis a couple of times yesterday and today, but it keeps timing out at bitarithm_timings, server overloaded?

**Comment by gebart** [comment]
Travis is happy now.

**Comment by LudwigOrtmann** [comment]
@gebart I assume something like this regarding Travis.

**Pull request merged**
