### PR TITLE
dist/tools: ethos baudrate configuration

### PR DESCRIPTION
**Pull request by aabadie**
This is a follow up of #5303.

### CODE REVIEW

**Comment by kaspar030** [comment]
Looks ok.

My linux termios also defines

```
#define  B230400  0010003
#define  B460800  0010004
#define  B576000  0010006
#define  B921600  0010007
#define  B1000000 0010010
#define  B1152000 0010011
#define  B1500000 0010012
#define  B2000000 0010013
#define  B2500000 0010014
#define  B3000000 0010015
#define  B3500000 0010016
#define  B4000000 0010017
```

Can we add them too? Or are they Linux only?

**Comment by aabadie** [comment]
> Can we add them too? Or are they Linux only?

Sounds reasonable. Some baudrate seems to Linux specific so I put them in a dedicated macro.

**Comment by kaspar030** [comment]
Looks good to me. Pls squash your two commits together, then you got an ACK.

**Comment by aabadie** [comment]
squashed

**Comment by aabadie** [comment]
Murdock is green => ACK and go !

**Pull request merged**
