### PR TITLE
pkg/tinydtls: drop libc_gettimeofday dependency

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`gettimeofday()` (via `time()`) is only used to print timestamps in the debug output. 
We don't need this, use our own debug functions without the expensive timestamp.

With this, we can drop the requirement to include `libc_gettimeofday`.

#### before

Code should still compile

``` 
   text	   data	    bss	    dec	    hex	filename
 123068	    384	  24920	 148372	  24394	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```

#### with this patch

```
   text	   data	    bss	    dec	    hex	filename
 107756	    272	  24776	 132804	  206c4	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```

### Issues/PRs references

upstream PR https://github.com/eclipse/tinydtls/pull/187

### CODE REVIEW

**Comment by benpicco** [comment]
Dropped the patch to tinydtls as it has been merged upstream.

**Review by kfessel — APPROVED** [review]
:+1:

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
