### PR TITLE
 pkg/nordic_softdevice_ble: Imminent deprecation warning

### LINKED ISSUE #11951: nordic_softdevice_ble: Update to allow modern kernels for IPSP
There is an interoperability cut in 6lo-over-bluetooth (Bluetooth's IPSP) that happened in Linux around 4.12 and in nRF SDK between the currently-used "nRF IoT SDK" and the "nRF SDK" (which supports it at least since the [14.1 release](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v14.1.0%2Fiot_sdk_user_guides_linux_commands.html))

The current [documentation in RIOT](https://github.com/RIOT-OS/RIOT/blob/master/pkg/nordic_softdevice_ble/README-BLE-6LoWPAN.md) says it requires the old behavior by indicating the maximum supported Linux version as 4.12.

Please consider updating the upstream version, allowing to set `BLE_6LOWPAN_LEGACY_MODE = 0`, and updating the documentation.

(Note this is all from reading current documentation; I did not test the behavior as I don't have suitable hardware yet, so the fix might be as easy as stating in the documentation that RFC7668 mode can be enabled).

### PR DESCRIPTION
**Pull request by chrysn**
### Contribution description

This makes the nRF softdevice docs accessible via doxygen and explains the outdatedness situation.

The goal of this is to bring some form of closure to #11951, whose underlying issue is that the first thing you find when searching for RIOT and Linux IPSP connectivity is that "it works only with kernels up to 4.12" (ie. still didn't solve the ages-old bug there).

### Issues/PRs references

This won't technically close #11951, but put it in a state where I'd be comfortable closing it with "won't fix unless someone resumes work on #9473.

### Alternatives

* Fully deprecate that module. Might well be an option, I don't know enough about non-IPSP uses of that module to make assertions there.
* Finish #9473. Doesn't seem like anyone is (still) motivated to work on the softdevice now that Nimble works.

### CODE REVIEW

**Comment by miri64** [comment]
Putting this after #11785 so we can utilize the new label ;-)

**Comment by miri64** [comment]
> Putting this after #11785 so we can utilize the new label ;-)

Welp... it wasn't merged when the build started, so this was a bit of a waste of time ^^" Sorry

**Comment by fjmolinas** [comment]
Should we add a concrete deprecation date? We have removed it from testing and I though this actually scheduled for deprecation but the warning is currently ambiguous IMO.

**Comment by miri64** [comment]
> Should we add a concrete deprecation date?

Probably a good idea.

**Comment by chrysn** [comment]
"Will be deprecated starting with the 2020.04 release?" There's still time to get that in, and if it's already not tested any more, it'd be a good time now to get it into the release changes.

**Comment by fjmolinas** [comment]
> "Will be deprecated starting with the 2020.04 release?" There's still time to get that in, and if it's already not tested any more, it'd be a good time now to get it into the release changes.

Sounds good. I would propose adding that to ``pkg/nordic_softdevice_ble/doc.txt` as a note:

```
 * @defgroup pkg_nordic-softdevice-ble   Nordic Softdevice BLE
 * @ingroup  pkg
 * @ingroup  net
 *
 * @brief    Provides a RIOT adaption for Nordic Softdevice BLE library
 *
 * @note    Will be deprecated starting with the 2020.04 release
```

Once 2020.04 is officially announced we change that to a ` * @deprecated   Will be removed starting with the 2020.07 release` or `2020.10`.

**Pull request merged**
