### PR TITLE
release-tests: add capability to run on PR comment

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This adds the capability to trigger a `release-tests` run when a member or owner of the RIOT-OS organization leaves a review that contains "@riot-ci do release tests" (case insensitive).

I decided to go for a review rather than comments, since

1. the comments trigger would also include issue comments and it would spin up the action every time a comment is made (it is then however canceled early, but it would just clutter our already full Actions tab)
2. the comment trigger would not add the results to the checks for the PR.

Additionally, a pytest filter can be used by commenting '@riot-ci do release tests with "\<pytest filter>"' instead.

### Testing procedure
I did extensive testing of this functionality here: https://github.com/miri64/RIOT/pull/37. AFAIK for this to work in main RIOT, this PR has to be merged first.

### Issues/PRs references
None.

### CODE REVIEW

**Review by miri64 — COMMENTED** [review]
But let's give it a try

@riot-ci Do release tests

**Comment by miri64** [comment]
Ah, works also here already! But I rather cancel it for now.

**Review by miri64 — COMMENTED** [review]
@riot-ci Do release tests with "(spec01 and task02) or (spec04 and task01)"

**Comment by kaspar030** [comment]
This is very nice! I'll try to add support to do specific tests on Murdock (maybe on boards that are not used by default).

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by miri64** [comment]
It is a bit weird though, that the SSH credentials apparently were not found :-/. We'll see, if this is only something that was a problem in this PR.

**Comment by miri64** [comment]
> This is very nice! I'll try to add support to do specific tests on Murdock (maybe on boards that are not used by default).

Since these tests in total (even split between native and non-native) take several hours, they should, however, stay weekly tests.

**Pull request merged**
