### PR TITLE
gh-actions: release-tests: do not run linters for release tests

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
The release tests are marked as failing currenty since there is a bug in `pylint` (or one of its libraries). There is not much sense to run the linter for the release tests on the test scripts, as this is already done in the [CI of the release tests](https://github.com/RIOT-OS/Release-Specs/blob/master/.github/workflows/self-test.yml#L46). As such, we only need to run the test environment of `tox`, which executes the release tests.

### Testing procedure
I'll run the workflow in my fork, just to see if everything works (to shorten the runtime a REMOVE ME commit is included).

### Issues/PRs references
See https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823210031

### CODE REVIEW

**Comment by miri64** [comment]
> I'll run the workflow in my fork, just to see if everything works (to shorten the runtime a REMOVE ME commit is included).

See https://github.com/miri64/RIOT/actions/runs/777070704

**Comment by miri64** [comment]
> > I'll run the workflow in my fork, just to see if everything works (to shorten the runtime a REMOVE ME commit is included).
> 
> See https://github.com/miri64/RIOT/actions/runs/777070704

Oops, `TOX_ARGS`, dispite its name is piped into `pylint` so that was the wrong entry point for that argument. Latest fixup should do the trick. See https://github.com/miri64/RIOT/actions/runs/777090015

**Comment by miri64** [comment]
[Only the `test` environment is run](https://github.com/miri64/RIOT/runs/2417975825?check_suite_focus=true#step:12:37) now.

**Comment by kaspar030** [comment]
> [Only the `test` environment is run](https://github.com/miri64/RIOT/runs/2417975825?check_suite_focus=true#step:12:37) now.

that's what we want, right?

**Comment by miri64** [comment]
> > [Only the `test` environment is run](https://github.com/miri64/RIOT/runs/2417975825?check_suite_focus=true#step:12:37) now.
> 
> that's what we want, right?

Yepp, sorry for not being clear on that :-).

**Comment by kaspar030** [comment]
Then please squash! :)

**Comment by miri64** [comment]
Squashed

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by miri64** [comment]
Backport provided in #16380

**Pull request merged**
