### PR TITLE
sock: tcp: fix sock_tcp_read() example

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`sock_tcp_read()` will return 0 if the connection was closed, we need to check for this.

### Issues/PRs references

https://github.com/RIOT-OS/RIOT/pull/16494#issuecomment-899027401

### CODE REVIEW

**Review by brummer-simon — APPROVED** [review]

**Review by maribu — COMMENTED** [review]
Note that the example is currently conaistent with the API doc. According to the current API doc, there is no way to detect when a TCP connection is closed. That obviously is a design flaw in need to be fixed. I trust that the implementation already has been fixed, but fixing the was forgotten. Care to add a commit to fiz this? Also, the `@retval` Doxygen command would make sense for documenting the individual magic return constants.

**Comment by benpicco** [comment]
TBH I'm a bit surprised it does not return `-ECONNABORTED` when the remote side closes the connection.

**Comment by maribu** [comment]
Maybe it is worth to discuss the correct behaviour first.

But note: Both POSIX `read()` and `recv()` return 0 at end of file/stream. For that reason, they had to introduce non-error error-codes for nonblocking operation to indicate that no data is available yet. This kind of proves that not using an error code for EOF / closed connection was a bad idea. But still, since the SOCK API was modeled after BSD sockets, I think there will be some confusion with different behaviour.

**Comment by brummer-simon** [comment]
> 
> 
> TBH I'm a bit surprised it does not return `-ECONNABORTED` when the remote side closes the connection.
-ECONNABORTED is used as an error condition.  Closing a connection normall is not an ERROR. ;)

**Review by fjmolinas — APPROVED** [review]
LGTM and @brummer-simon is fine with the change. ACK.

**Pull request merged**
