### PR TITLE
gnrc/netreg: fix assert

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

Fixes wrong order in preprocessor `if-else` causing failed assertions during release testing, see [here](https://github.com/RIOT-OS/Release-Specs/issues/55#issuecomment-358957220)

### Issues/PRs references

https://github.com/RIOT-OS/Release-Specs/issues/55#issuecomment-358957220

### CODE REVIEW

**Comment by miri64** [comment]
I'm not sure what you are trying to do here (except for the bit of information you state in the description which just describes the change), but what you are doing is definitely wrong. The `(entry->type != GNRC_NETREG_TYPE_DEFAULT)` has nothing to do with `DEVELHELP`, so not testing it only if `DEVELHELP` is not defined will cause false negative assertions when `GNRC_NETREG_TYPE_MBOX` or `GNRC_NETREG_TYPE_CB` is set for `entry->type` (where a message queue for the target is not required).

**Comment by miri64** [comment]
(I'm not sure why the `#ifdef DEVELHELP` is there in the first place though... maybe an artifact from the time before `assert()` was bound to `DEVELHELP`?)

**Comment by smlng** [comment]
> I'm not sure why the #ifdef DEVELHELP is there in the first place though

I don't see how `assert` is bound to `DEVELHELP`, but I also think that the if-else is somewhat wrong anyway - though my "fix" might make it even worse or more wrong 😕

**Comment by smlng** [comment]
ah, okay NDEBUG is bound to DEVELHELP and NDEBUG enables or disables `assert()`. Anyway, DEVELHELP can be omitted here.

**Comment by smlng** [comment]
though the failed assertions remains in unittests as reported by @aabadie then. At least as long we compile with `DEVELHELP=1`.

**Comment by miri64** [comment]
> though the failed assertions remains in unittests as reported by @aabadie then. At least as long we compile with DEVELHELP=1.

At least for the unittests I rather would set `DEVELHELP=0`. This way some wonky values and their behavior can also be tested (which is one of the main points of unittests).

**Comment by smlng** [comment]
> for the unittests I rather would set DEVELHELP=0

mhm, there is no problem with DEVELHELP with any other (unit)test other than `unittests/tests-netreg`, which tells me that we should rather fix that test.

**Comment by miri64** [comment]
> Let's discuss DEVELHELP=0 for unittests elsewhere.

See #8440.

**Pull request merged**
