### PR TITLE
drivers/sht21: initial support for the SHT21 sensor

### PR DESCRIPTION
**Pull request by shr70**
This commit adds support for the Sensirion SHT21 temperature and humidity sensor.
A driver test is also supplied.

### CODE REVIEW

**Comment by shr70** [comment]
@PeterKietzmann I'll start adjusting #7866 now. I checked, but despite of the close name the sensors are fairly different. Their commands, options and conversions differ. Only the CRC is the same.

**Comment by PeterKietzmann** [comment]
I just stumbled over #6734 which seems to be a bit more generic. Maybe your PR can benefit from it?

**Comment by shr70** [comment]
I now integrated #6734 into it. Should i just force push it to my branch? It is quite different

**Comment by PeterKietzmann** [comment]
@shr70 so far I haven't reviewed this PR and we decided to go with #7866 first, right? So I'd say push what you think is the best solution.

**Comment by shr70** [comment]
Ok, I now pushed the new version, as it includes polling & clock-stretching modes

**Comment by keestux** [comment]
@PeterKietzmann how would it work if I wanted to add commits to this PR? Or do I send in my PR based on this one and mention it in the description?

**Comment by smlng** [comment]
@keestux the latter would an option, ie. base your PR on this one add your changes and note in the description of your PR that it depends on this one ... a maintainer should than also add the `waiting for PR` label.

**Comment by PeterKietzmann** [comment]
PS: Directly pushing to the PR requires (i) maintainer status and (ii) enabled "Allow edits from maintainers" flag set.  Personally I prefer to open PRs against the initial authors branch in such situations.

**Comment by keestux** [comment]
@smlng @PeterKietzmann @aabadie @shr70 After looking at this PR I propose to continue with my own driver (keestux:add-driver-sht2x) reopening #10750. I'll go through the features of this branch (Josar:sht21) and include things that I find worthwhile. Is that OK with you?

**Comment by PeterKietzmann** [comment]
@keestux fine with me but please agree with @shr70 or @Josar

**Comment by PeterKietzmann** [comment]
We agreed to go with #10750. Closing in favor of that one

**Pull request closed without merging**
