### PR TITLE
core: document msg_reply_int()

### LINKED ISSUE #2219: core: msg_reply_int() is undocumented and unused
`msg_reply_int()` is undocumented and unused. Do we need it? An ISR cannot receive messages, so how could it reply to messages?

### PR DESCRIPTION
**Pull request by OlegHahm**
Fixes #2219.

### CODE REVIEW

**Comment by kaspar030** [comment]
ACK.

**Comment by OlegHahm** [comment]
stop

**Comment by OlegHahm** [comment]
Just updated the last commit and added your explanation for the use case. Please proofread this sentence as well. ;)

**Comment by kaspar030** [comment]
ACK again. Do we need a second? ;)

**Comment by PeterKietzmann** [comment]
ACK

**Comment by OlegHahm** [comment]
No

**Comment by OlegHahm** [comment]
But it doesn't hurt. ;)

**Pull request merged**
