### PR TITLE
*: remove trailing underscores from header guards

### PR DESCRIPTION
**Pull request by OlegHahm**
Relaces #4626 and fixes #2623.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Comment addressed

**Comment by OlegHahm** [comment]
> It's always a delight that github doesn't allow me to mark line that are not changed. :D

Isn't that a good indicator that these issues should be addressed in a separate PR?

**Comment by OlegHahm** [comment]
But since you were so kind to already provide a list, I've extended the purpose of this PR. :)

**Comment by A-Paul** [comment]
Then I don't understand why you didn't object my first comment, that was also related to areas you hadn't changed.

**Comment by miri64** [comment]
May I ask why we remove the trailing `_`, too? #2623 was only about leading IIRC.

**Comment by OlegHahm** [comment]
May I ask why you raise this question after more than one year? ;-)

But anyway, I read #2623 differently and I don't see a good reason for the trailing underscore.

**Comment by miri64** [comment]
> May I ask why you raise this question after more than one year? ;-)

Wasn't aware #2623 also included trailing `_` ;-)

> But anyway, I read #2623 differently and I don't see a good reason for the trailing underscore.

Fine by me, just need to adapt my templates.

**Comment by A-Paul** [comment]
It's all about balance. ;-)

**Comment by miri64** [comment]
> It's all about balance. ;-)

Come to the dark side. We have cookies.

**Comment by OlegHahm** [comment]
Interesting problem - I'm investigating.

**Comment by OlegHahm** [comment]
Figured the problem - LWIP has ambiguous header guards.

**Comment by miri64** [comment]
Oops :-/

**Comment by OlegHahm** [comment]
I must admit, I'm a little bit lost regarding the CI fails.

**Comment by gebart** [comment]
@OlegHahm The patches to pkg don't apply, you need to revert the `-` lines so that they can be applied.
Also you might need to check that the patches are still working as intended, there's some preprocessor ifdefs there which might have been affected.

**Comment by cgundogan** [comment]
To complement @gebart's comment. This is what I can read from the Jenkins output:
```
git -C /opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/tests/nhdp/bin/pkg/airfy-beacon/oonf_api am --ignore-whitespace "/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/pkg/oonf_api"/patches/*.patch
Applying: add RIOT support
Applying: port tests to riot
Applying: port example to riot
Applying: fix conflicting types
Applying: only define container_of when necessary
Applying: if_index is not used
Applying: Use RIOT's container_of implementation
Applying: Dissolve enum into single defines
Applying: Add missing include
Applying: Change index of array from 0 to 1
Applying: remove error: array subscript has type 'char' [-Werror=char-subscripts]
Applying: isolate oonf list implementation of riot's implementation
error: patch failed: src-api/common/list.h:466
error: src-api/common/list.h: patch does not apply
error: patch failed: src-api/subsystems/oonf_packet_socket.h:131
error: src-api/subsystems/oonf_packet_socket.h: patch does not apply
Patch failed at 0012 isolate oonf list implementation of riot's implementation
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/pkg/pkg.mk:17: recipe for target '/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/tests/nhdp/bin/pkg/airfy-beacon/oonf_api/.git-patched' failed
make[1]: *** [/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/tests/nhdp/bin/pkg/airfy-beacon/oonf_api/.git-patched] Error 128
/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/tests/nhdp/../../Makefile.include:321: recipe for target '/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/jenkins_bin/oonf_api.a' failed
make: *** [/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/jenkins_bin/oonf_api.a] Error 2
make: Leaving directory '/opt/jenkins/workspace/RIOT_PR-6407-AJNL6AFS5Q2QDBPR2KWOCIYZ2LMVFJSEIJILOO2BGRBMGFT5EUDA@2/tests/nhdp'
```

**Comment by OlegHahm** [comment]
Yes, thanks. I somehow overlooked that I've actually touched the patch files.

**Comment by cgundogan** [comment]
seems to be in need of a rebase

**Comment by OlegHahm** [comment]
Rebased.

**Comment by cgundogan** [comment]
FYI: Jenkins is happy with the changes, it just complains about the squashing.

**Comment by OlegHahm** [comment]
For some strange reason the header for the NRF softdevice package was complete shit. Fixed it.

**Comment by miri64** [comment]
> For some strange reason the header for the NRF softdevice package was complete shit. Fixed it.

Maybe because the review for it happened crammed in the FU lecture hall during RIOT summit ^^.

**Comment by miri64** [comment]
FYI: there are still headers with trailing `_` guards that were merged from PRs that were merged before this PR was last forked/rebased.

**Comment by miri64** [comment]
(and of course all open PRs have the potential to re-introduce #2623 again)

**Pull request merged**
