### PR TITLE
cpu/msp430: added flashpage implementation

### PR DESCRIPTION
**Pull request by haukepetersen**
this PR removes the deprecated `flashrom` driver and re-adds the code conforming to the current `periph/flashpage` interface.

Tested and verified on the `z1` (as this is the only msp430 board I have available here...) using the `test/periph_flashpage` application.

### CODE REVIEW

**Comment by haukepetersen** [comment]
rebased

**Comment by kYc0o** [comment]
Tested on z1 -> working.

**Comment by miri64** [comment]
`chronos` seems to tick a little different :clown_face:

**Comment by haukepetersen** [comment]
not different, but the driver is just not configured for the `chronos`. So this is once more an issue of periph drivers being build unconditionally... I need to think about an solution...

**Comment by haukepetersen** [comment]
added memory configuration for the `cc430f6137` (`chronos`). Murock should be happy now.

**Comment by haukepetersen** [comment]
@kYc0o does your ACK still hold?

**Comment by kYc0o** [comment]
Yes!

**Pull request merged**
