### PR TITLE
boards/pic32-{clicker,wifire}: delete boards

### PR DESCRIPTION
**Pull request by jcarrano**
### Why

There has not been any any progress towards addressing the issues put forward in https://github.com/RIOT-OS/RIOT/pull/11788/commits/ec3252bed3766a5568cb9df9d37d7bd39c0be60c (part of #11788).

We already did away with malta. Now, shall we remove clicker and wifire too?

Before answering consider the following points:

Are clicker and wifire (in their present state) adding any substantial value to RIOT? Do they solve anyone's problems, compared to those which they create? Since this is a community effort: do they address any common, shared needs of (a relevant part of) the community?

Anyone trying to affirmatively answer the above would have to explain why #9259 is still unmerged after almost a year and half, and why it is being proposed by a person with no interest in pic32 or mips and whose time could be spent in ways more useful to our community.

### What

Please see the commit description for a more complete explanation, also see the discussion in #11788.

### CODE REVIEW

**Comment by kaspar030** [comment]
I'm against removing these.

**Comment by jcarrano** [comment]
> I'm against removing these.

Ok, fine, but would you mind giving a rationale? I'm not dogmatic- I spelled out my arguments and if you counter them then of course I can change my opinion.

**Comment by kaspar030** [comment]
> I'm not dogmatic- I spelled out my arguments and if you counter them then of course I can change my opinion.

1. there probably have been hundred(s) of hours of work in order to get MIPS support to the current state. Even if it has some problems, opening a removal PR takes what, 5 minutes? This is at least rude towards the original contributors.

2. So let's say basic MIPS support is currently barely usable (e.g., no board is flashing without extra PR, and UART input is non-functional). I consider those minor and solvable issues, again, compared to the rather huge amount of work that has already been invested to get us here.

3. While an extra architecture requires maintenance, it also brings many benefits: validation of our abstractions, exposure of our code to wider amount of use-cases, the possibility to do more exhaustive comparisons for our scientific crowd, and hopefully, thankful users that can benefit from RIOT on their platform of choice (or what has been forced on them). And the warm feeling that we can say "RIOT runs on almost everything that you'd call MCU".

4. RIOT is not primarily business driven. If it would, why on earth would we support anything else than Cortex-M (and maybe RISC-V, just to be able to jump ship when necessary)? The community is not a company, it is not bound by shareholder value. We do have the freedom to support stuff that we feel like we want to support it, for whatever reasons.

5. "Anyone trying to affirmatively answer the above would have to explain why #9259 is still unmerged after almost a year and half"

This one puzzles me a lot. You've been sitting across @cladmi that whole time. It should have been a rather quick merge, if there'd been some communication between you guys.
Probably you don't see value in MIPS support, and rather concentrate on other stuff that you find important, like the colored output of our build system. I'd say that's alright, work on whatever floats your boat. I respect that. I'd like to ask you to also respect different interests from other community members.

**Comment by jcarrano** [comment]
1. Effort != Value. I can take hundreds of hours digging a hole and covering it. The fact it took a lot of effort is irrelevant here- the point is the value it delivers.

2. Same issue as (1). Also, I question that those "minor and solvable issues" are so, considering the have not been fixed. I would have expected that if they were so small in scale compared to the original effort, then they would have been fixed when the boards were introduced or shortly after.

3. We do software to solve problems. I doubt that warm feelings is a problem to be solved by RIOT. **What problem** and **for whom** is MIPS/clicker/wifire solving? Our resources are scarce, as shown by the 600+ open PRs. What you mention are _potential benefits_. I ask about _realized benefits_.

4. Excellent point.  The community as such is not profit-driven. The community is driven by the shared interests of its members (which in turn may or may not be business-oriented). Any group of people can only collaborate on what mutually benefits them. As the intersection of the mutual interests narrow, the chances for collaboration diminish. That is why there exists several OS. " it is not bound by shareholder value": well, the members _are_ the shareholders.

5. Why am I supposed to review or test  #9259? I'm not familiar with the hardware and I don't even know anybody who needs it- it would be a complete waste of time for me and my project. I'm being consistent: I say I don't care about MIPS and act the same way. I should be asking why _the people who want MIPS support_ did not review #9259.

PS, off topic: "the colored output of our build system" is part of what makes it run as slow as it does, and AFAICT it is _you_ who often complains about build times in the CI. Those long build times are caused by a combination of inept programming and extensive use of hacks, which is what I'm trying to ameliorate.

**Comment by jcarrano** [comment]
One more point. I am paid with public funds, as is the case for _many_ members of the RIOT community. It is therefore a duty for us who are paid by the public to constantly ask ourselves: **how does this benefit the public?** and, am I using public resources effectively and responsibly?

**Comment by aabadie** [comment]
Since there is some still work done by @francois-berder on these boards, I don't think we'll remove them for the moment.
This PR is also very outdated. I'm closing it.

**Pull request closed without merging**
