### PR TITLE
Add support for the Sillicon Labs Thunderboard Sense

### PR DESCRIPTION
**Pull request by basilfx**
This PR adds initail support for the Sillicon Labs Thunderboard Sense. It is split into five commits, to differentiate between vendor sources and own sources. It is a similar PR to #4824 and the comments of PR #4722 still apply.

It is initial support only, as there is no board documentation. There are even no references of the board on the web, so it must be very new or not production-ready :-) I just got lucky in enabling the UART (similar to SLSTK3401A). The peripherals will also work, but are not mapped. LED and Buttons are also not working :-)

Board can be flashed and debugged using JLink. Make sure you have the latest version installed.

About the name: it is different from the other starter kits. I am open for new suggestions, but the whole series is called Thunderboard Sense/Wear/Whatever.

A Wiki page is also ready: https://github.com/basilfx/EFM2Riot/blob/master/dist/doc/Thunderboard%20Sense.md

### CODE REVIEW

**Comment by OlegHahm** [comment]
Awesome! :)

**Comment by basilfx** [comment]
I have asked for documentation via the [Sillicon Labs Forum](http://community.silabs.com/t5/Wireless/Documentation-for-Thunderboard-Sense/m-p/174272). Let's see if that yields some documentation.

**Comment by basilfx** [comment]
I've received the documentation and asked about the official part number. The board will be called SLTB001A, so I'll rename the board to match the other boards names by Silicon Labs.

**Comment by basilfx** [comment]
I updated this PR:

* Renamed board from `thunderboard_sense` to `sltb001a` to be in line with the other boards.
* SAUL support for LEDs + Si7021
* Definition of pins
* [Docs](https://github.com/basilfx/EFM2RIOT/blob/master/dist/doc/SLTB001A.md)

Seems like all sensors are enabled via a GPIO expander, for which an EFM8 MCU is used. I have requested documentation for this, since I don't know how to control the GPIO expander.

**Comment by chrysn** [comment]
i tested the branch and the default program works, exposing the leds and buttons. (the rest of the peripherals would need interaction with the i2c expander mcu, for which i found no documentation yet).

i'm using the board not with the silabs jlink software, but with openocd with patch http://openocd.zylin.com/3736 .

**Comment by basilfx** [comment]
Just received this link: https://twitter.com/siliconlabs/status/778662620199055361. Just a few more days :-)

**Comment by basilfx** [comment]
The user manual is available at http://www.silabs.com/Support%20Documents/TechnicalDocs/UG250.pdf.

Compared to the samples we received during the Summit, the Hall-effect sensor (Si7201) is now removed.

I think this board is an excellent SAUL demo board, when all the sensors are implemented.

**Comment by emmanuelsearch** [comment]
Great initial port! I guess the most urgent is to work on radio support now. Right?

**Comment by basilfx** [comment]
@emmanuelsearch Yes, that is still something that has to be done. However, that is something a bit out of my league at this moment (time/knowledge) :-)

**Comment by basilfx** [comment]
Rebased to latest master, updated sources and added support for the GPIO expander. 

The on-board Si7021 temperature/humidity sensor and RGB leds work. The other sensors don't have drivers yet. It also works with SAUL.

schermafbeelding 2016-10-24 om 23 35 54

(when the RGB leds are on, the PCB temperature rises, which affects the temperature sensor)

**Comment by kYc0o** [comment]
Let's see what Murdock thinks...

**Comment by haukepetersen** [comment]
Hej, nice work. There are some (minor) issues that need to be fixed:
- [ ] the emlib files need to be excluded from doxygen
- [ ] the license header of the emlib files needs to be included into the license patterns
- [ ] please check your files for missing newlines at the end of the files
- [ ] for the peripheral drivers (except SPI and I2C for now): remove the `#ifdef xx_NUMOF` guards around the file, since the peripheral remodeling these are not longer needed

**Comment by kYc0o** [comment]
ping @basilfx

**Comment by basilfx** [comment]
Still alive!

I have fixed the issues in [my EFM2RIOT](https://github.com/basilfx/EFM2Riot) tree, but I am/was waiting for #4926 and #4780. However, work got in the way so I haven't found the time to continue :-)

I also want to finish #5429 first.

**Comment by emmanuelsearch** [comment]
@basilfx would be really great to have initial support merged, others could start working on radio support. This board looks great at first sight...

**Comment by basilfx** [comment]
@emmanuelsearch I have updated this PR with my latest changes. I am waiting for the new I2C and SPI interface, and the new power module (I had some problems which I put on the mailing list).

**Comment by haukepetersen** [comment]
sorry for the long long silence... We just got talking about this board again so I thought I give it a try - works like a charm with this PR.

Regarding #4926: this won't get merged anytime soon: so my take would be to go with the existing I2C interface for now and adapt later.

I'd say let's get it merged (and I accept the use of the `emlib`, although I still don't like it...). I have only a few more or less trivial change requests:
- all vendor supplied headers should be moved to a vendor include (sub)dir as we did for all other CPUs. This helps to separate things and also tells doxygen not to look at them
- I think it would be much better to provide the emlib as a pkg. As it seems, SiLabs provides it in their official github (https://github.com/SiliconLabs/Gecko_SDK/tree/master/platform/emlib/src), so this should be easy to do -> this would significantly reduce the number of lines in this PR and make it much easier to update to a newer version in the future (one line change in the pkg makefile...)

@basilfx do you have some time you can spend on this during the next weeks? If not, I could see if I find an evening to take over if you don't mind.

**Comment by chrysn** [comment]
The branch doesn't easily merge into the current master; apart from the trivial doxyfile conflict, there appears to have been a Makefile.include.something → something.inc.mk renaming.

The current code uses the pre-#4780 API (`spi_transfer_byte(spi_t dev, char...)` instead of `spi_transfer_byte(spi_t dev, spi_cs_t cs, bool cont, ...)` so that can't be built, and I didn't see any branch that does that in @basilfx' clone, so let's see if I can update those device drivers...

**Comment by chrysn** [comment]
I've merged master and integrated some of the minor convention changes in my copy of this branch at <https://github.com/chrysn-pull-requests/RIOT/tree/feature/thunderboard>. I haven't updated the SPI changes (just sidestepping the problem with `SPI_NUMOF 0` in `boards/sltb001a/include/periph_conf.h`).

**Comment by chrysn** [comment]
just finished and roughly tested an spi port update; cleaning it up a bit before uploading.

**Comment by chrysn** [comment]
@basilfx, do you want to pull my changes (SPI now pushed) into your branch, or should I rather open a pull request with the combined changes?

**Comment by basilfx** [comment]
Just want to let you know that I've been working on this PR (or EFM32 in general).

@haukepetersen I have moved all vendor files in a separate directory, and emlib to a package.

@chrysn I have incorporated some of your SPI changes using copy-paste. I did add you to the authors of `spi.c` :-)

Will update this PR soon, first have to fix and test a lot of RIOT-OS changes I have missed.

**Comment by basilfx** [comment]
The story continues in #7929.

**Pull request closed without merging**
