### PR TITLE
sys/sema: add sema_get_value()

### PR DESCRIPTION
**Pull request by haukepetersen**
### Contribution description
I'd like to optimize the NimBLE port by moving its mapping from the rather large `posix_semaphore` to use RIOTs native semaphore implementation (`sys/sema`). Everyhting is quite straight forward, expect the missing `get_value()` function. So this PR adds this function to the `sys/sema` module.

### Testing procedure
Build test should do.

### Issues/PRs references
none

### CODE REVIEW

**Comment by miri64** [comment]
If there is a `get_value()` function in the POSIX semaphores, should that function maybe the mapped to `sema_get_value()`?

**Comment by haukepetersen** [comment]
there is. Made it use the new function.

**Comment by miri64** [comment]
Can you provide a link? It is not in this PR.

**Comment by haukepetersen** [comment]
now it is :-) pushed to the wrong branch first...

**Comment by miri64** [comment]
Ah, now it is :-)

**Review by miri64 — APPROVED** [review]
ACK. Running the `tests/posix_semaphore` test in the CI should catch any errors.

**Comment by haukepetersen** [comment]
All green -> go

**Pull request merged**
