### PR TITLE
drivers/at86rf231: fix LQI / frame reading

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
According to the **AT86RF233** datasheet, a "frame" read operation starts with one byte `PHR` indicating the length of the `PSDU` and ends with up to three bytes `LQI`, `ED`, `RX_STATUS` (after the `PSDU`). Since we only care for `LQI`, read it and ignore the rest.

I'm a bit confused by the data sheet and the current implementation - is this different for the `AT86RF231`?

I'll fix the commit message etc. once this is cleared up.

### CODE REVIEW

**Comment by LudwigOrtmann** [comment]
Tested with a `samr21-xpro` and this shield:
samr21-antenna-shield

**Comment by LudwigOrtmann** [comment]
Maybe we do care for `ED` after all - not sure why, but RSSI values are always `0` or `1` for me - `ED` instead appears to decrease with distance.

```diff
diff --git a/drivers/at86rf231/at86rf231_rx.c b/drivers/at86rf231/at86rf231_rx.c
index ce46c52..af17ce8 100644
--- a/drivers/at86rf231/at86rf231_rx.c
+++ b/drivers/at86rf231/at86rf231_rx.c
@@ -43,10 +43,11 @@ void at86rf231_rx_handler(void)
 
     /* read psdu, read packet with length as first byte and lqi as last byte. */
     uint8_t *buf = buffer[rx_buffer_next];
-    at86rf231_read_fifo(buf, length + 2);
+    at86rf231_read_fifo(buf, length + 3);
 
     /* read lqi which is appended after the psdu */
     lqi = buf[length + 1];
+    uint8_t ed = buf[length + 2];
 
     /* read fcs and rssi, from a register */
     fcs_rssi = at86rf231_reg_read(AT86RF231_REG__PHY_RSSI);
@@ -54,7 +55,7 @@ void at86rf231_rx_handler(void)
     /* build package */
     at86rf231_rx_buffer[rx_buffer_next].lqi = lqi;
     /* RSSI has no meaning here, it should be read during packet reception. */
-    at86rf231_rx_buffer[rx_buffer_next].rssi = fcs_rssi & 0x0F;  // bit[4:0]
+    at86rf231_rx_buffer[rx_buffer_next].rssi = ed;
     /* bit7, boolean, 1 FCS valid, 0 FCS not valid */
     at86rf231_rx_buffer[rx_buffer_next].crc = (fcs_rssi >> 7) & 0x01;
 
diff --git a/drivers/include/at86rf231.h b/drivers/include/at86rf231.h
index 80e25bc..64fa152 100644
--- a/drivers/include/at86rf231.h
+++ b/drivers/include/at86rf231.h
@@ -76,7 +76,7 @@ typedef struct __attribute__((packed))
     /** @{ */
     uint8_t length;             /**< the length of the frame of the frame including fcs*/
     ieee802154_frame_t frame;   /**< the ieee802154 frame */
-    int8_t rssi;                /**< the rssi value */
+    uint8_t rssi;               /**< the rssi value */
     uint8_t crc;                /**< 1 if crc was successfull, 0 otherwise */
     uint8_t lqi;                /**< the link quality indicator */
     /** @} */
```
```
# 30 cm distance
2015-01-10 23:12:31,694 - INFO # Got radio packet:
2015-01-10 23:12:31,695 - INFO # 	Length:	15
2015-01-10 23:12:31,696 - INFO # 	Src:	0
2015-01-10 23:12:31,697 - INFO # 	Dst:	1
2015-01-10 23:12:31,698 - INFO # 	LQI:	255
2015-01-10 23:12:31,699 - INFO # 	RSSI:	43
2015-01-10 23:12:31,700 - INFO # Payload Length:4
2015-01-10 23:12:31,701 - INFO # Payload:123
# 1 cm distance
2015-01-10 23:12:36,086 - INFO # Got radio packet:
2015-01-10 23:12:36,087 - INFO # 	Length:	15
2015-01-10 23:12:36,088 - INFO # 	Src:	0
2015-01-10 23:12:36,089 - INFO # 	Dst:	1
2015-01-10 23:12:36,090 - INFO # 	LQI:	255
2015-01-10 23:12:36,091 - INFO # 	RSSI:	84
2015-01-10 23:12:36,092 - INFO # Payload Length:4
2015-01-10 23:12:36,093 - INFO # Payload:123
```

**Comment by thomaseichinger** [comment]
This won't work for rf231 chips, as these don't append `ED` and `RX_STATUS` to a frame read.
We'd need to ask for `ED` with a separat transaction of `AT86RF231_REG__PHY_ED_LEVEL` register for now.

**Comment by LudwigOrtmann** [comment]
rebased

**Comment by LudwigOrtmann** [comment]
I'm currently working on splitting the `at86rf2xx` family of drivers and will base this functionality on the upcoming PR once it's merged. Just keeping it open in case someone actually needs these readings in the meantime.

**Comment by LudwigOrtmann** [comment]
Thomas has promised to incorporate my `at86rf2xx` efforts into the refactoring of the driver for the NSTF API. Waiting for this now.

**Comment by bapclenet** [comment]
Let's close this PR as #2825 is taking it into account and almost done?
@LudwigOrtmann

**Comment by LudwigOrtmann** [comment]
Don't care.

**Pull request closed without merging**
