### PR TITLE
boards/nucleo-f334: indicate periph_cpuid feature

### PR DESCRIPTION
**Pull request by LudwigOrtmann**
Follow up to https://github.com/RIOT-OS/RIOT/pull/2552 by  @jhollister

### CODE REVIEW

**Comment by haukepetersen** [comment]
works as expected. I would prefer to list every future in it's own line of code:
```
FEATURES_PROVIDED += periph_cpuid 
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += cpp
FEATURES_MCU_GROUP = cortex_m4
```
This prevents the collisions on some occasions and saves us some rebasing efforts (also opened an issue for this -> #2611)

**Comment by LudwigOrtmann** [comment]
Amended the change.

**Comment by thomaseichinger** [comment]
ACK when Travis passed.

**Comment by haukepetersen** [comment]
kicked Travis

**Pull request merged**
