### PR TITLE
fix sys/crypto header include guards.

### PR DESCRIPTION
**Pull request by zhuoshuguo**
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#).

### CODE REVIEW

**Comment by gebart** [comment]
ACK

**Comment by gebart** [comment]
you need to modify the commit message to contain the module first.
for example "sys/crypto: Rename header include guards"

**Comment by gebart** [comment]
you can use `git commit --amend` to change the latest commit message, or use `git rebase -i HEAD~1` and change the word `pick` to `r` in the commit list on the commit that you want to modify.

**Comment by zhuoshuguo** [comment]
Updated.

**Pull request merged**
