### PR TITLE
saul/gpio: add handling of active-low signals + state initialization

### PR DESCRIPTION
**Pull request by haukepetersen**
motivated by #7148

The SAUL GPIO driver can now handle inverted logic (active-low pins) and the initial state can be configured on a per-pin basis.

This costs us on the `samr21-xpro` with two configured SAUL GPIOs ~100 byte, so it doesn't come cheap...

I have not yet adapted other boards than the `samr21-xpro`, wanted to get opinions first.

### CODE REVIEW

**Comment by gebart** [comment]
I don't think this belongs in SAUL. If anywhere it should be placed in the periph gpio driver. Some MCUs have hardware support for inverted GPIOs, which would give this feature almost for free on those platforms.

**Comment by smlng** [comment]
to be frank: I don't like it - considering the cost (you said it yourself) and the added complexity.

**Comment by haukepetersen** [comment]
> Some MCUs have hardware support for inverted GPIOs

Good to know, I have never seen this...

I am not too big of a fan to this approach myself, but this would be the clean way in terms of concepts...

**Comment by haukepetersen** [comment]
closed in favor of #7586

**Pull request closed without merging**
