### PR TITLE
core: Updated include guards to remove leading underscores

### PR DESCRIPTION
**Pull request by altairpearl**
Refering to the issue #2623. Have modified the module cores include guards . Please review.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
ACK and go

**Comment by OlegHahm** [comment]
Core changes require two ACKs. ;-b

**Comment by PeterKietzmann** [comment]
Oh nooo. Sorry, I was in the "I-need-to-megre-what-I-can" mode. Before reverting the commit to fulfill the correct procedure, was this an ACK from your side :-) ?

**Comment by LudwigOrtmann** [comment]
ACK

**Comment by PeterKietzmann** [comment]
Thanks :-)

**Pull request merged**
