### PR TITLE
sys/shell add neighbor stats output for ifconfig

### PR DESCRIPTION
**Pull request by bergzand**
Pretty output for the netstats_neighbor module from #6873.

Based on #7447, #7448 and #6873.

### CODE REVIEW

**Comment by miri64** [comment]
Can you also add an alternative PR dependent on #7404, please?

**Comment by bergzand** [comment]
Should I port only the ifconfig command or also the PR's this PR depends on?

**Comment by miri64** [comment]
The `ifconfig` adjustments should suffice. The rest will be pulled in via your `netdev` and `netopt` changes anyway.

**Comment by miri64** [comment]
With #7925 being on its way, I think we can close this in favor of #7463. Re-open, if I missed something.

**Pull request closed without merging**
