### PR TITLE
cpu/cortexm_common: Overwrite stack up until the current stack pointer only

### PR DESCRIPTION
**Pull request by gebart**
Alternative to #3328 

@daniel-k: can you test if this works on your device with -O0?

### CODE REVIEW

**Comment by daniel-k** [comment]
I didn't step through, but running it with either `-O0` and `-Os` seems to work.

**Comment by PeterKietzmann** [comment]
Happy Travis

**Comment by kaspar030** [comment]
I don't like the printf's, either, but I guess if it fixes the problem for now, ACK.

**Comment by kaspar030** [comment]
(let's write simple ```print_ptr(void*)``` functions later)

**Comment by kaspar030** [comment]
Would someone else with an opinion about printf in ISRs give a second ACK?

**Comment by kaspar030** [comment]
ups, commented in wrong PR. nvm.

**Pull request merged**
