### PR TITLE
Board: initial support for the STM32F103C8T6

### PR DESCRIPTION
**Pull request by smlng**
This adds support for the STM32F103C8T6 demo board. Its a rather cheap board (i.e., approx. 2 EUR on ebay), and because of that kind of popular with lots of resources on-line - now users can switch and use RIOT 🎉

### CODE REVIEW

**Comment by pyropeter** [comment]
This board is commonly known as "Blue Pill" and there is a second PR adding support for it here: !7727

**Comment by bergzand** [comment]
> This board is commonly known as "Blue Pill" and there is a second PR adding support for it here: #7727

The "blue pill" uses the stm32f103cb, this one is known as the "[black pill](http://wiki.stm32duino.com/index.php?title=Black_Pill)" I think.

**Comment by smlng** [comment]
sorry wasn't aware of these alternative names, though I saw the other PR I (hence) didn't made the connection. I'll check if and how they are related, as @bergzand pointed out there might be differing MCUs here?

**Comment by smlng** [comment]
mhm, seems like mine is actually the _bluepill_, too. And as far as my quick look up resolved, the stm32f103cb and stm32f103c8t6 have only minor diffs, so it should be possible to integrate both into one or use the greatest common denominator (regarding periphs).

I'll try #7727 with my board and report back if it is working, and will close my PR then - no need to duplicate a board under different names 😉

**Comment by nmeum** [comment]
The board added with #7727 theoretically also has an stm32f103c8, however, we discovered that it has 128 KiB flash even though it claims to have only 64 KiB flash therefore we decided to use stm32f103cb as the `CPU_MODEL`. We are currently investigating this further.

Besides your PR seems to add some things we didn't for instance the `gpio_params.h` saul configuration, if you decide to close this one in favor of #7727 I would copy this file to our PR.

**Comment by gebart** [comment]
I suggest you keep the ordering of the UART modules to match the chip order, and instead define UART_STDIO_DEV in board.h. See boards/mulle/include/board.h for an example.

**Comment by smlng** [comment]
@gebart wasn't aware of that, thanks for the pointer. And obviously a good idea, I totally agree to better keep order of periphs according to board and select RIOTs usage separately.

**Comment by smlng** [comment]
closing in favour #7727

**Pull request closed without merging**
