### PR TITLE
boards/nucleo-f042: configure PWM pins, add extra UART, add ADC

### PR DESCRIPTION
**Pull request by aabadie**
Yet another PR configuring more peripherals on a Nucleo board. This one is for  nucleo32-f042.

### CODE REVIEW

**Comment by vincent-d** [comment]
Looks good to me. Untested though.

**Comment by aabadie** [comment]
@astralien3000 has the board, I'll ask him to give a try.

**Comment by astralien3000** [comment]
Hey, I ran : 
 - `example/default`
 - `test/periph_uart`
 - `test/periph_timer`
 - `test/periph_pwm`

Successfully.

**Comment by PeterKietzmann** [comment]
How about `tests/periph_adc`?

**Comment by aabadie** [comment]
> How about tests/periph_adc?

Just tested the build but not the hardware. I don't think I made a mistake there as the pin mapping is the same for all nucleo32 boards.

**Comment by aabadie** [comment]
I think this one is ready for an approval and a click on the green button ;)

**Comment by PeterKietzmann** [comment]
Ok this is just configuration. Checked against board manual. ACK

**Pull request merged**
