### PR TITLE
2015.09 branch

### PR DESCRIPTION
**Pull request by Dialine**
rtc periph driver for SAML21

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@Dialine It seems there went something wrong creating your PR.

**Comment by Dialine** [comment]
Yes, sorry.
 Not familiar with Git to send my first ull Request.
 And I don't find very easy help ...

 I dont known how to send my rtc.c file ...

             FWX.

**Comment by OlegHahm** [comment]
Have you taken a look at https://help.github.com/categories/collaborating-on-projects-using-pull-requests/ ?

**Comment by Dialine** [comment]
No, but I found other link, not easy to understand for me ;-((

 So "bapclenet" has sent a PR for me :

  https://github.com/RIOT-OS/RIOT/pull/4655

 Regards,

       FWX.

**Comment by PeterKietzmann** [comment]
@Dialine thanks for your work. I will close this PR now in favour of #4655.

**Pull request closed without merging**
