### PR TITLE
pkg/tweetnacl: tweetnacl crypto library as a package

### PR DESCRIPTION
**Pull request by BytesGalore**
alternative to #4317, providing the `tweetnacl` crypto library [1] as a package

[1] https://tweetnacl.cr.yp.to/

### CODE REVIEW

**Comment by kaspar030** [comment]
I think we should directly add those two files into our repo. Upstream changes rarely, and like this there are two http requests per application/board combo that gets built by the CI (that makes >100 requests just for unittests).

**Comment by miri64** [comment]
> Upstream changes rarely, and like this there are two http requests per application/board combo that gets built by the CI (that makes >100 requests just for unittests).

Why is it downloaded for every application/board (I know why, I'm just questioning). Shouldn't one download suffice for all and the build then only happen for those combinations? At least that was what used to be possible.

**Comment by kaspar030** [comment]
> Shouldn't one download suffice for all and the build then only happen for those combinations?

(It get's downloaded only for the app/board combinations that need it for building, not sure that is clear.)
Sure, there needs to be some caching. We have that (mostly) for git, but not for plain HTTP downloads.

> At least that was what used to be possible.

Well, before, packages just downloaded their source into ```pkg/<pkg-name>```, and some even built there. That was flawed in many ways. And it only made it possible to re-use already downloaded source if stuff gets built sequentially, which would make Murdock crawl at something like 4-5hrs per build.

**Comment by BytesGalore** [comment]
> It get's downloaded only for the app/board combinations that need it for building, not sure that is clear.

at least not for me.

> Sure, there needs to be some caching.

+1
I mean we use always the same source for all permutations, so re-downloading it in every single case is just obsolete.

**Comment by OlegHahm** [comment]
I'm a bit confused, too. Why should building from the same source harm concurrency?

**Comment by kaspar030** [comment]
> Why should building from the same source harm concurrency?

Building from the same source is fine. But the Makefile targets that set up the source need to be parallel-safe.

Imagine N builds try to execute the "download" target at the same time, to the same location. Downloading, patching, ... would interfere badly.

Of course there are ways around that, but that is just not implemented yet.

**Comment by OlegHahm** [comment]
Hm, okay, I see. Thanks for the reminder. How about setting up a Git repository for tweetnacl as a workaround? (E.g. with a cronjob that pushes the latest version available via HTTP periodically, so that Murdock can leverage the git-cache abilities?)

**Comment by BytesGalore** [comment]
@OlegHahm, @kaspar030  so how should we proceed? Should we close this PR?

**Comment by OlegHahm** [comment]
After some time and thinking, probably @kaspar030 is right. Let's just import the code into our repository. Hence, yes, let's close this PR.

**Comment by PeterKietzmann** [comment]
Sorry @BytesGalore :/

**Pull request closed without merging**
